### ISSUE TITLE
Modify statfs/df to reflect BtrFS quotas

### ISSUE THREAD

**Issue by Harvie** [lxc/lxc#1003]
Hello,
i use BtrFS quotas to limit disk usage inside LXC. Basically as described here: https://btrfs.wiki.kernel.org/index.php/Quota_support
(every container has own quota on host)

But even if there's quota and your usage of space in the container is limited, the df inside still the sees size of whole filesystem.

That's basically what one expects from btrfs quotas, however it's not how i like my containers :-) It would be cool if LXC in kernel detected that it has btrfs subvolume with quota mounted and then faked the statfs, so df would look like the filesystem is actually smaller.

Otherwise user of container can be quite confused. He pays for 20GB container, but sees 1TB, sees usage of space that is not caused by him, sees that filesystem is half empty, but does not see that he already reached his own quota and wonders why are things not working...

**Comment by stgraber** [comment]
There is no such thing as "LXC in kernel". You could try to convince the btrfs guys upstream to report the usage of the subvolume, though given that subvolumes don't show up as separate mount entries, that seems unlikely to happen.

An alternative would be to fake /proc to return the right thing in userspace, which is what lxc/lxcfs does for a few things, but not for disk space. You could send a branch there to add support for btrfs disk space, assuming it can be done without having to mask proc files which are very frequently accessed.

In any case, the LXC project is the wrong place to report this as there is nothing LXC itself can do about this, so sending a kernel patch or a new feature branch to lxcfs would be the way to go.
