### ISSUE TITLE
Sabayon x64 template

### ISSUE THREAD

**Issue by necrose99** [lxc/lxc#1006]
http://www.sabayon.org/download 

basically Gentoo Template , add urls for sabayon stages. 
(Gentoo Compatable and bleeding edge. ) 
http://mirror.clarkson.edu/sabayon/iso/monthly/Sabayon_Linux_**16.05**_amd64_tarball.tar.gz

year mount of current time.  

arm or arm64 would be nice over time for any distro on host.. ie   static QUEM bin into container. as a distro or distroless template ie adds in before any distro if asked. 
sabayon also supports armfl however docker dose this , now.

**Comment by brauner** [comment]
If someone is willing to work on a template for this we're happy to merge.

**Comment by necrose99** [comment]
mainly if their was the ability to **sub template** ,  ie use template , run few extra commands in the chroot  it would be far easier & faster.... or simply sheaduale them to run...on boot. 
ie my-centos-7 (do cent add repo's , add my package lists etc)  

Sabayon.lxcst depends on Gentoo.lxc  , do gentoo , run more commands in chroot to add on , close or on first spin up do ad-hoc migration commands. 

sabayon is mainly an overlay  as is Pentoo etc. 

**however could lock the arch to x64 only.** 

Gentoo template , name it Sabayon-x64-??? 

 , emerge layman git  # layman build and git required to add 
layman -L && Layman -a  sabayon && layman -a sabayon-distro  ## add sabayon source package overlays , ## next run build
&& emerge equo entropy.
equo rescue spmsync  ## sync Gentoo portage-SPM to binary package manger...  & build DB. 
equo update  && equo upgrade  update/upgrade system.   (entropy wraps portage to better handle binaries , though portage can , it can also be more picky if packages are not yet added to match the binary, and if you have an infinite loop of circular depends .... esp on a newer machine this isnt fun. if some packages are added later the features can be then enabled. )  

anyhow thiers umpta'zillion distro forks of Ubuntu /Debian/RPM distros  , Etc, if one could just add repos , fire up a migration **sub-template**  could save alot of work , 
Xubuntu , (Ubuntu + add repo commands etc)
