### ISSUE TITLE
Missleading error message for lxc.network.type none instead of empty

### ISSUE THREAD

**Issue by jm009** [lxc/lxc#1009]
I accidentially put  `lxc.network.type=none` in my config file, instead of `lxc.network.type=empty`. The unprivileged container did not start, and the log contained completely missleading error messages:

```
lxc-start 1462654885.385 INFO     lxc_conf - conf.c:mount_autodev:1197 - Mounted container /dev
      lxc-start 1462654885.386 ERROR    lxc_utils - utils.c:safe_mount:1692 - Operation not permitted - Failed to mount sysfs onto /usr/lib/x86_64-linux-gnu/lxc/rootfs/sys
      lxc-start 1462654885.386 ERROR    lxc_conf - conf.c:lxc_mount_auto_mounts:828 - Operation not permitted - error mounting sysfs on /usr/lib/x86_64-linux-gnu/lxc/rootfs/sys flags 14
      lxc-start 1462654885.386 ERROR    lxc_conf - conf.c:lxc_setup:3910 - failed to setup the automatic mounts for 'test'
      lxc-start 1462654885.386 ERROR    lxc_start - start.c:do_start:717 - failed to setup the container
      lxc-start 1462654885.386 ERROR    lxc_sync - sync.c:__sync_wait:51 - invalid sequence number 1. expected 2
      lxc-start 1462654885.397 ERROR    lxc_start - start.c:__lxc_start:1192 - failed to spawn 'test'
```
Why does lxc try to mount sysfs here?
I suggest to at least improve the error messages.

Debian jessie stable. LXC 1.1.5 from backports.

**Comment by hallyn** [comment]
Hi,

if you had given an invalid keyword we could detect that.  But what
you provided was in fact valid, just not what you wanted.

**Comment by jm009** [comment]
I suggest to output a DEBUG, like for example: Mounting sysfs to access hosts net device...
Or: Using hosts net device

**Comment by hallyn** [comment]
If you'd like to submit a patch to that end, it may suffice to add that line to
src/lxc/conf.c:instantiate_none().

**Comment by linvinus** [comment]
same problem here (Debian jessie stable. LXC 1.1.5 from backports.), could someone explain is it possible to use unprivileged container  with lxc.network.type=none or not?
thanks.

i need to use hosts ip but start|stop container without issues, 
privileged container with lxc.network.type=none break my host system after shutting-down guest system
