### ISSUE TITLE
Maven can't be used inside lxc container (apparmor profile)

### ISSUE THREAD

**Issue by gcontini** [lxc/lxc#1023]
Hi, i'm trying to use Maven 3.2.5 inside an lxc.
The version of lxc is 2.0.0-0ubuntu2 (the same shipped with ubuntu xenial).

I get this error :

> type=1400 audit(1463111029.250:162): apparmor="DENIED" operation="file_lock" profile="lxc-container-default-cgns" pid=6679 comm="java" family="unix" sock_type="stream" protocol=0 addr=none

and in the container Maven can't download any file from remote repository.

**Comment by hallyn** [comment]
Thanks.  We've seen the same error with systemd-hostnamed .  It
appears to be an actual bug in apparmor:

https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1575779

**Comment by brauner** [comment]
This is not a lxc bug and is tracked on launchpad so closing here.
