### ISSUE TITLE
Share folders as devices with containers such that they're writeable by root inside the container

### ISSUE THREAD

**Issue by nottrobin** [lxc/lxc#1024]
As I understand it the way to share a folder with a container is by creating a device. This works, but it leads to the mounted device being owned by `nobody:nogroup`, so `root` can't write to it:

``` bash
[robin@xps ~ ]$ lxc launch ubuntu:16.04 my-xenial  # Create the container
[robin@xps ~ ]$ lxc config device add my-xenial share disk source=`pwd`/share path=/srv/share  # Share the current directory at `/srv/share`
[robin@xps ~ ]$ lxc exec my-xenial -- ls -ld /srv/share                                      
drwxrwxr-x 2 nobody nogroup 4096 May 13 13:22 /srv/share
[robin@xps ~ ]$ lxc exec my-xenial -- touch /srv/share/afile
touch: cannot touch '/srv/share/afile': Permission denied
```

Following [discussion in #lxcontainers on freenode](http://pastebin.ubuntu.com/16388488/), I found that the best existing solution to this problem is to use [setfacl](http://linuxcommand.org/man_pages/setfacl1.html) to expand the permissions on that directory explicitly for `lxd` and the container's `root` user:

``` bash
# Where 165536 is the user ID of root in my container
setfacl -Rm user:lxd:rwx,default:user:lxd:rwx,user:165536:rwx,default:user:165536:rwx share
```

([more expansive command-line illustration](https://gist.github.com/nottrobin/a66d3d5b9722149136d7fc6f93dae59f))

Would it be possible for LXC/LXD itself to setup ACLs, or do something similar, so that any shared devices are automatically set-up with write permissions for `root` inside the container?

Even better, would it be possible to set it up so that files created in the shared folder by `root` inside the container would be owned by a different non-root user (e.g. `robin`) on the host filesystem?

**Comment by hallyn** [comment]
Hi

do you mind re-opening this issue at github.com/lxc/lxd instead?

There is upstream kernel discussion going on about a vfs feature to mount
filesystems with shifted uids, which if it lands could also be used to make
this more transparent.  Otherwise, yes, shifting uids by lxd should be
possible.  Or lxd could have an option to mount as a overlayfs and shift
the uids in the writeable layer, with the option to merge changes back in
at unmount.

**Comment by nottrobin** [comment]
Refiled here: https://github.com/lxc/lxd/issues/2025
