### ISSUE TITLE
Configuring id_map on create (lxc-2.0.1)

### ISSUE THREAD

**Issue by thebigb** [lxc/lxc#1025]
Hi,

Is there a decent way of configuring a custom id_map during create (preferably with the python 3 API)?

As far as I can tell the only options now are modifying the default configuration before running create, or modifying the container configuration after create and remapping the rootfs afterwards ([nsexec](https://bazaar.launchpad.net/~serge-hallyn/+junk/nsexec/view/head:/uidmapshift.c) seems to have a tool for this).

The use case is that I'm building a kind of wrapper that assigns unique sub-uid/gid ranges to containers.

I've also been looking at LXD, but there it doesn't appear to be configurable at all.

Another issue I ran into is that running `container.get_config_item("lxc.id_map")` fails, saying that the key is not found, while the configuration definitely specifies it. I'm currently parsing the configuration files manually which works fine, but I'm rather curious why that fails.

Any pointers?

**Comment by hallyn** [comment]
> Another issue I ran into is that running `container.get_config_item("lxc.id_map")` fails, saying that the key is not found, while the configuration definitely specifies it. I'm currently parsing the configuration files manually which works fine, but I'm rather curious why that fails.

This is a bug.  It's simply not implemented right now, and should be.

**Comment by brauner** [comment]
The python 3 bindings have been moved into a separate repo. If the bug still exists it should be filed against it.
