### ISSUE TITLE
Please add --overlaydir XXX option to lxc-start-ephemeral

### ISSUE THREAD

**Issue by dankegel** [lxc/lxc#1028]
lxc-start-ephemeral --storage-type dir -n name creates directory in /var/lib/lxc/name/tmpfs and stores the overlay in it, which is fine... but sometimes it's too slow.

lxc-start-ephemeral --storage-type tmpfs -n name furthermore mounts a tmpfs on that directory, which is fast... but could run out of memory.

It would be nice to have an --overlaydir option to put the overlay on a faster disk for those times when tmpfs isn't big enough.  (Or maybe --tmpdir, or --storage-dir.  Any name I can think of is worse than --overlaydir.)

I had a patch for that back in olden days, but not for lxc 2.0.

'Course, nowadays, I have 20GB of RAM on some boxes, so maybe I don't care *quite* as much :-)

**Comment by brauner** [comment]
Hi,
lxc-start-ephemeral has been deprecated starting with lxc 2.0.0. It has been superseded by lxc-copy. Maybe you can test if this fits your use-case better and report back.

**Comment by dankegel** [comment]
I had some trouble figuring out how to map
```
  lxc-start-ephemeral --orig oldfoo --name foo --user joe -- command
```
onto lxc-copy.  I guess it's something like
```
   lxc-copy  --name oldfoo --newname foo -e
   lxc-attach --name foo -- su joe -c "command"
   lxc-stop --name foo
```
which seems pretty convoluted.  Is that the recommended path?

**Comment by beanieboi** [comment]
hey,

this is how we do this.

```
sudo lxc-copy -n base_container -e -N test1 -B overlayfs -p /ssd2 -F
```

this starts a ephemeral container using "base_container" as base and puts the overlay on `/ssd2` instead of tmpfs

**Comment by brauner** [comment]
Closing as this is not a real bug. Thanks!
