### ISSUE TITLE
Reload lxc service for apply config changes

### ISSUE THREAD

**Issue by ingtarius** [lxc/lxc#1039]
Hello! LXC 2.0.0-3~bpo8+1 have some strange issue - it doesnt get my changes from config file
lxc-ls -f

> NAME  STATE   AUTOSTART GROUPS IPV4     IPV6
> app08 RUNNING 0        -      10.9.5.8 -    

I set lxc.start.auto = 1 to /var/lib/lxc/app08/config file and no changes for lxc-ls -f
reload lxc service solve this issue, but all containers will be restarted.

**Comment by evgeni** [comment]
Please see how to properly report bugs for Debian backports: https://backports.debian.org/Instructions/#index6h2 ;-)

But that issue is probably not strictly bpo related, so let me see if I can reproduce it. Thanks for reporting :)

**Comment by evgeni** [comment]
Nope, can't reproduce:

```
root@jessie:~# lxc-ls -f
NAME   STATE   AUTOSTART GROUPS IPV4 IPV6 
jessie STOPPED 0         -      -    -    
root@jessie:~# echo "lxc.start.auto = 1" >> /var/lib/lxc/jessie/config 
root@jessie:~# lxc-ls -f
NAME   STATE   AUTOSTART GROUPS IPV4 IPV6 
jessie STOPPED 1         -      -    -    
```

**Comment by evgeni** [comment]
Ha, the container has to be running to reproduce!

```
root@jessie:~# lxc-ls -f
NAME   STATE   AUTOSTART GROUPS IPV4 IPV6 
jessie RUNNING 0         -      -    -    
root@jessie:~# echo "lxc.start.auto = 1" >> /var/lib/lxc/jessie/config 
root@jessie:~# lxc-ls -f
NAME   STATE   AUTOSTART GROUPS IPV4 IPV6 
jessie RUNNING 0         -      -    -    
```

**Comment by ingtarius** [comment]
Yes, it is true... When containter is stopped config work well...

**Comment by brauner** [comment]
This is expected. With the low-level `lxc-*` tools the config cannot be easily reloaded during runtime. This is different for `LXD`.
