### ISSUE TITLE
No /sbin/init in debian stretch rootfs

### ISSUE THREAD

**Issue by timofurrer** [lxc/lxc#1057]
After creating a lxc container with ...

```lxc-create -t debian -n swam-dev-stretch -- --release stretch --arch amd64```

... I cannot start the container because `/sbin/init` is missing in the rootfs. The log tells:

```
      lxc-start 20160624172252.809 NOTICE   lxc_start - start.c:start:1435 - exec'ing '/sbin/init'
      lxc-start 20160624172252.809 ERROR    lxc_start - start.c:start:1438 - No such file or directory - failed to exec /sbin/init
      lxc-start 20160624102252.809 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
      lxc-start 20160624102252.809 ERROR    lxc_start - start.c:__lxc_start:1353 - failed to spawn 'swam-dev'
```

I double checked this and `/sbin/init` really does not exist - it's not a permission problem.

The same commands but using `jessie` as a release works fine.

My host is an Ubuntu 16.04 using lxc version `2.0.1` from the xenial repositories.

**Comment by timofurrer** [comment]
It looks like the `minbase` in stretch removed systemd as a package. I've added them now with: `--packages=systemd,systemd-sysv`

**Comment by stgraber** [comment]
Pretty sure we merged a fix for that a tiny while ago, will be in the next bugfix release.

**Comment by timofurrer** [comment]
Okay, so then: lxc itself is installing init to the containers/rootfs? This is not something the bootstrap process has to take care of? 
And that was done for other debian versions but not stretch - or in general newer debian versions?

**Comment by stgraber** [comment]
debootstrap in debian no longer installs an init system. This seems wrong to me but it's intentional. A recent template change in LXC now has lxc-debian always install an init system, fixing this issue.
