### ISSUE TITLE
LXC 2.0 on Debian Jessie: No freezer controller mountpoint found 

### ISSUE THREAD

**Issue by Napsty** [lxc/lxc#1071]
As (mistakenly) mentioned in issue #979 , I experience problems with LXC 2.0 on Debian Jessie (running on purpose without systemd). LXC 2.0 was installed through jessie-backports. 

lxc-ls is throwing errors now, containers cannot even be started anymore:

	# lxc-ls -f
	lxc-ls: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found
	lxc-ls: state.c: lxc_str2state: 66 invalid state ''
	lxc-ls: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found
	lxc-ls: state.c: lxc_str2state: 66 invalid state ''
	lxc-ls: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found
	lxc-ls: state.c: lxc_str2state: 66 invalid state ''
	lxc-ls: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found
	lxc-ls: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found
	lxc-ls: state.c: lxc_str2state: 66 invalid state ''
	lxc-ls: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found

Start:

	# lxc-start -n a1 -F
	lxc-start: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found
	lxc-start: start.c: lxc_spawn: 1079 failed initializing cgroup support
	lxc-start: start.c: __lxc_start: 1329 failed to spawn 'a1'
	lxc-start: lxc_start.c: main: 344 The container failed to start.
	lxc-start: lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.

cgroup is mounted:

    # mount|grep cgroup
    cgroup on /sys/fs/cgroup type cgroup (rw,relatime,cpuset,cpu,cpuacct,memory,devices,freezer,net_cls,blkio,perf_event,net_prio)

I meanwhile rolled back and ditched lxc 2.0 which, as I mentioned, was installed from jessie-backports:

    Upgrade: lxc:amd64 (1.1.5-1~bpo8+1, 2.0.0-3~bpo8+1)

As jessie-backports doesn't contain 1.1.5 version anymore I went back to 1.0.6 from the jessie repository. All containers work again.

/proc/self/cgroup shows the following, but it's possible that this has changed again since I now installed LXC 1.0.6 again:

    # cat /proc/self/cgroup
    1:cpuset,cpu,cpuacct,memory,devices,freezer,net_cls,blkio,perf_event,net_prio:/

**Comment by hallyn** [comment]
cgfsng assumes cgroups are mounted on /sys/fs/cgroup/$controller.  So the bug here is
that cgfsng should simply be falling back to the older cgfs driver.

**Comment by hallyn** [comment]
This seems to be several bugs.  Each triggered by having all cgroups mounted
directly under /sys/fs/cgroup.  The simplest workaround should be to install
cgroupfs-mount.

First, libpam-cgfs fails to create cgroups for you.  The do_enter() fn is
failing, and I've not tracked down why.

Second, even if you create your own cgroup and move yourself to it, lxc still
fails to start.

**Comment by LynxChaus** [comment]
lxc 2.0.3 works perfectly in Jessie. lxc-2.0.0 from jessie-backports still missing commit #956, tell maintainer to build 2.0.3 version instead.

**Comment by Napsty** [comment]
@LynxChaus did you try it without systemd as well? I'm not sure whether this might be the buggy part or not. Besides that thanks for the hint. I will contact the backports maintainer.

**Comment by LynxChaus** [comment]
I'm always purge systemd after install. It normally works under sysvinit with fstab entry
`cgroup /sys/fs/cgroup cgroup  defaults 0 0`

**Comment by Napsty** [comment]
Sorry to have kept this issue open for so long. The maintainer meanwhile pushed 2.0.3 to the backports repos and with the current version (as of today 2.0.3-1~bpo8+1) it works; no problems anymore on Jessie.
