### ISSUE TITLE
bdev/bdev.c: overlayfs renamed overlay

### ISSUE THREAD

**Issue by allgoewer** [lxc/lxc#1076]
```
% sudo lxc-copy -s -B overlay -n base -N new
lxc-copy: bdev/bdev.c: bdev_copy: 381 no such block device type: overlay
lxc-copy: lxccontainer.c: copy_storage: 2844 Error copying storage.
clone failed
```

bdev/bdev.c refers to the overlay-filesystem as 'overlayfs' though it is actually named 'overlay' in upstream linux.

**Comment by brauner** [comment]
I'm looking into this.

**Comment by allgoewer** [comment]
Nevermind, this is already addressed here, my bad.
https://github.com/lxc/lxc/issues/389

**Comment by brauner** [comment]
Yeah, so you need to specificy `-B overlayfs` then it should work. We can however, add `overlay` as a valid alternative to `overlayfs`.

**Comment by allgoewer** [comment]
Ok thanks, I was confused because the man-page for lxc-copy actually calls it 'overlay', not 'overlayfs'. I'm running lxc-2.0.3.

**Comment by brauner** [comment]
Yeah, as I said. I might just add `overlay` as a valid name for the option. :)
