### ISSUE TITLE
lxc-debian improvement: use qemu-debootstrap instead of interpreter argument?

### ISSUE THREAD

**Issue by pdsouza** [lxc/lxc#1079]
It took me a while to figure out that I had to pass `-I /usr/bin/qemu-arm-static` as an argument when creating an armhf container on an amd64 host. This argument was introduced in https://github.com/lxc/lxc/commit/d50cebd6974da307bc4fe8b7e28fbebd204b43ff by @vivier.

Perhaps I am missing a use-case here, but wouldn't it be a lot simpler to use `qemu-debootstrap` instead? This is how it's done in the ubuntu template as well: https://github.com/lxc/lxc/blob/master/templates/lxc-ubuntu.in#L379. It would be nice to have parity between the ubuntu and debian templates, given that they both use debootstrap.

`qemu-debootstrap` will fall back to a standard debootstrap if the host and container arch are the same, so this is pretty transparent as long as the user installs the package `qemu-user-static`. It would simplify a lot of the extra logic here that does checks on the interpreter, which I think increases the code complexity. All that's needed is to change "debootstrap" to "qemu-debootstrap" if it is available on the system.

I'm happy to open a PR for this if needed, but I don't want to open one which deletes all of this (working) code if I'm missing some important use-case in this commit that isn't satisfied with the much simpler `qemu-debootstrap`.

Just wanted to bring this up as a possible simplification. Either way, I'm glad that now cross-bootstrapping works out-of-the-box for debian containers!

**Comment by vivier** [comment]
I install debian container on my Fedora 23 host and only the debootstrap package is available, not qemu-debootstrap.

**Comment by pdsouza** [comment]
Ah, I use Debian / Ubuntu and I didn't think about `qemu-bootstrap` availability on other distros. That makes complete sense then. Thanks for clarifying!
