### ISSUE TITLE
Migration from lxc-start-ephemeral to lxc-copy

### ISSUE THREAD

**Issue by beanieboi** [lxc/lxc#1081]
Hey,

As mentioned in #1080. I want to move from `lxc-start-ephemeral` to `lxc-copy`.
The problem with `lxc-copy` is that I wasn't able to reproduce `lxc-start-ephemeral` behavior.
We kind of implicitly rely on the feature that `lxc-start-ephemeral` uses a tmpfs to back the overlayfs and keeps everything in memory. I tried to move to lxc-copy but even with fast SSD's we saw a major performance hit. Kind of expected if you compare memory vs SSD but it was at a level that wasn't acceptable to us at this time and would need some major changes on our infrastructure to allow this kind of "slowness". Is there a way to reproduce the tmpfs other than managing the tmpfs on my own?
I'm not sure how complicated it is to add such a backing storage to `lxc-copy` or was this intentionally left out?

Thanks for your input
Best,
ben

**Comment by brauner** [comment]
Should be closed via #1084.
