### ISSUE TITLE
System volume is increased when starting the first container

### ISSUE THREAD

**Issue by iainlane** [lxc/lxc#1083]
I'm using non-lxd containers (they have been dist-upgraded for a long time) with lxc 2.0.3-0ubuntu1 on yakkety.

If I've got some audio playing, like a song in Spotify, then the first time I do

$ sudo lxc-start -n xenial -d

will raise the volume. The config is definitely a bit hacked (I don't remember all of the details; I think that maybe unconfined was necessary for schroot/sbuild somehow?), so maybe some of this is relevant.

    root@raleigh:/var/lib/lxc/xenial# more config 
    lxc.network.type=veth
    lxc.network.link=br0
    lxc.network.flags=up
    lxc.network.hwaddr = 00:16:3e:09:b5:2c
    lxc.rootfs = /var/lib/lxc/xenial/rootfs
    lxc.utsname = xenial
    
    lxc.devttydir = lxc
    lxc.tty = 4
    lxc.pts = 1024
    lxc.mount  = /var/lib/lxc/xenial/fstab
    lxc.mount.auto = cgroup
    lxc.arch = amd64
    lxc.cap.drop = sys_module mac_admin mac_override
    lxc.pivotdir = lxc_putold
    
    # uncomment the next line to run the container unconfined:
    lxc.aa_profile = unconfined
    
    lxc.cgroup.devices.deny = a
    # Allow any mknod (but not using the node)
    lxc.cgroup.devices.allow = c *:* m
    lxc.cgroup.devices.allow = b *:* m
    # /dev/null and zero
    lxc.cgroup.devices.allow = c 1:3 rwm
    lxc.cgroup.devices.allow = c 1:5 rwm
    # consoles
    lxc.cgroup.devices.allow = c 5:1 rwm
    lxc.cgroup.devices.allow = c 5:0 rwm
    #lxc.cgroup.devices.allow = c 4:0 rwm
    #lxc.cgroup.devices.allow = c 4:1 rwm
    # /dev/{,u}random
    lxc.cgroup.devices.allow = c 1:9 rwm
    lxc.cgroup.devices.allow = c 1:8 rwm
    lxc.cgroup.devices.allow = c 136:* rwm
    lxc.cgroup.devices.allow = c 5:2 rwm
    # rtc
    lxc.cgroup.devices.allow = c 254:0 rwm
    #fuse
    lxc.cgroup.devices.allow = c 10:229 rwm
    #tun
    lxc.cgroup.devices.allow = c 10:200 rwm
    #full
    lxc.cgroup.devices.allow = c 1:7 rwm
    #hpet
    lxc.cgroup.devices.allow = c 10:228 rwm
    #kvm
    lxc.cgroup.devices.allow = c 10:232 rwm

**Comment by brauner** [comment]
Your problem is that you don't expect the audio level to be raised? This seems to be a privileged container. If you grant device access to your audio devices then the container can change settings etc. So what you're experiencing is not a bug it's just inherent to what privileged containers can do. My best guess is that the container re-initializes the default alsa volume again. You could try to prevent this by setting a default alsa volume in a configuration file inside the container.

**Comment by iainlane** [comment]
Fair enough, thanks for the response. I didn't think that AppArmor was my only line of defence here, that's interesting to know.
