### ISSUE TITLE
Please use lxc.haltsignal = SIGRTMIN+3 for systemd containers

### ISSUE THREAD

**Issue by mbiebl** [lxc/lxc#1085]
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831691

Hi,

he had an interesting discussion today on #pkg-systemd IRC about what
modifications are currently done for LXC containers to work properly
with systemd. Ideally we'd like to make a default systemd installation work
ootb.

Atm, the Debian template hooks up
/etc/systemd/system/sigpwr.target -> /lib/systemd/system/halt.target.

At some point, Martin added a workaround to the systemd package [1].

Systemd upstream is pretty clear though, that (mis)using SIGPWR to
initiate an ordered shutdown is not the preferred way under systemd [2].
If the container manager sends SIGRTMIN+3 to the init process following
the container spec [3], then systemd will shut down nicely.

I therefor suggest, that lxc should use haltsignal = SIGRTMIN+3 for
systemd based containers.

I would set that in the container config file during lxc-create if the
template is for a systemd-based distro.

Regards,
Michael

[1] https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?id=44c3369f9
[2] https://lists.freedesktop.org/archives/systemd-devel/2016-July/037166.html
[3] https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/

**Comment by brauner** [comment]
Should be closed by #1086. Please reopen, if you experience issues.
