### ISSUE TITLE
Problem on latest kernel: kernel:NMI watchdog: BUG: soft lockup

### ISSUE THREAD

**Issue by LaKing** [lxc/lxc#1088]
Today, after an upgrade from lxc 2.0.0 to 2.0.3 + a full OS update, some strange errors shed light.

In the terminal:

kernel:NMI watchdog: BUG: soft lockup - CPU#2 stuck for 22s! [rpc.nfsd:25666]

.. beeps every 10 seconds or so. 

top shows indeed rpc.nfsd with the given pid at continuous 100% CPU usage.
It renders the system completely out of control, even a reboot command times out.  
This behavior is getting started after starting a couple of containers.

On another server, the same upgrade took place, and after a couple of same style errors (with kworker as I remember) - the system started up and so far runs as normal. Seems pure luck. 3 containers.

On a third system, there were no errors, but that had only one container. ...

Distro update from fedora 23 to 24 didn't help.
lxc downgrade to 2.0.0 didn't help either ,...

Any suggestions really appreciated.

**Comment by LaKing** [comment]
Note: The process seems to start as lxc-start, and then it turns to rpc.nfsd.

**Comment by LaKing** [comment]
rcu_sched detected expedited stalls on CPU/tasks: { 7-m.. } 240003 jiffies s: 351 root: 0x80/. 

.. and all processes hang.  takes 30 min to shut down a couple of tasks if a reboot starts ...

**Comment by LaKing** [comment]
Okay, seems I can reproduce this on other systems. ...

Might be a bug in my configs. :/ ...

Seems to be the case with 3 or more then 3 containers ...

**Comment by LaKing** [comment]
Kernel 4.4.9-300 seems to work fine!

Kernel 4.6.x ... seems to break the system with lxc.

**Comment by pedro7** [comment]
Does `intel_idle.max_cstate=7` help?

**Comment by tssge** [comment]
The kernel did have bug in oom killer related to cgroups, which caused lockups if a cgroup ran out of memory and the oom killer was activated. It was resolved for me by kernel upgrade. I don't remember the version which had the bug, but please upgrade your kernel and see if the issue persists. We achieved quite ridiculous load averages: http://i.imgur.com/u2zQx2c.png

Were you by any chance hitting your cgroup's memory limits?

**Comment by brauner** [comment]
This is not a LXC bug but rather a kernel bug. There's nothing to do on our side.

**Comment by AncientRemember** [comment]
which issu related,i encounter the same issue
Apr 30 10:35:42 bj2916 kernel: NMI watchdog: BUG: soft lockup - CPU#6 stuck for 23s! [java:18923]
Apr 30 10:35:42 bj2916 kernel: NMI watchdog: BUG: soft lockup - CPU#7 stuck for 23s! [java:18928]
Apr 30 10:35:42 bj2916 kernel: NMI watchdog: BUG: soft lockup - CPU#3 stuck for 23s! [java:18925]
Apr 30 10:35:42 bj2916 kernel: NMI watchdog: BUG: soft lockup - CPU#2 stuck for 23s! [java:18921]
Apr 30 10:35:42 bj2916 kernel: NMI watchdog: BUG: soft lockup - CPU#0 stuck for 23s! [java:18927]
Apr 30 10:35:42 bj2916 kernel: NMI watchdog: BUG: soft lockup - CPU#4 stuck for 23s! [java:18922]
