### ISSUE TITLE
lxc 2.0.3 K 4.1.0 some command crash even lxc works

### ISSUE THREAD

**Issue by father-mande** [lxc/lxc#1107]
Hi,
First ... I am happy to join your group ...
I am an integrator ... and do port of software on some NAS ... here lxc
Problem (perhaps some previous posts seems to have some common point with this ... but I am not sure)
lxc-create (download) works (debian jessie amd64), lxc-start start it as well lxc-stop close friendly the container
network (veth) works ssh server inside also output to local + masquerade also
BUT  some command generate error and incomplete output (first view seems to be for network information access ???)
lxc-ls -f (when cont. is started)
_________
lxc-ls: utils.c: switch_to_ns: 1096 Function not implemented - failed to set process 9742 to net of 3.
lxc-ls: lxccontainer.c: do_lxcapi_get_interfaces: 1789 Function not implemented - failed to enter namespace
lxc-ls: utils.c: switch_to_ns: 1096 Function not implemented - failed to set process 9742 to net of 3.
lxc-ls: lxccontainer.c: do_lxcapi_get_ips: 1881 Function not implemented - failed to enter namespace
lxc-ls: utils.c: switch_to_ns: 1096 Function not implemented - failed to set process 9742 to net of 3.
lxc-ls: lxccontainer.c: do_lxcapi_get_ips: 1881 Function not implemented - failed to enter namespace
NAME STATE   AUTOSTART GROUPS IPV4 IPV6
test RUNNING 0         -      -    -
__________
even proc 9742 run and /proc/9742/ns is accessible (hereafter)
__________
 ps -eaf | grep 9742
root      4077  2672  0 18:43 pts/3    00:00:00 grep 9742
root      9742  9695  0 18:14 ?        00:00:00 /sbin/init
root      9803  9742  0 18:14 ?        00:00:00 /lib/systemd/systemd-journald
root      9895  9742  0 18:14 ?        00:00:00 dhclient -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
root      9916  9742  0 18:14 ?        00:00:00 /usr/sbin/sshd -D
root      9923  9742  0 18:14 pts/1    00:00:00 /sbin/agetty --noclear --keep-baud console 115200 38400 9600 vt102
___________
lxc-info also have error (in the middle of the output)
___________
  lxc-info -n test
Name:           test
State:          RUNNING
PID:            9742
lxc-info: utils.c: switch_to_ns: 1096 Function not implemented - failed to set process 9742 to net of 3.
lxc-info: lxccontainer.c: do_lxcapi_get_ips: 1881 Function not implemented - failed to enter namespace
CPU use:        4.60 seconds
BlkIO use:      131.77 MiB
Memory use:     78.94 MiB
KMem use:       0 bytes
Link:           vethFR3PQQ
 TX bytes:      208.55 KiB
 RX bytes:      6.20 MiB
 Total bytes:   6.40 MiB
___________
last lxc-attach also failed : lxc_attach_to_ns: 270 Function not implemented - failed to set namespace 'mnt'
______________
here the ns folder for the process
 ll /proc/9742/ns
total 0
dr-x--x--x    2 root     root           0 Jul 28 18:14 ./
dr-xr-xr-x    8 root     root           0 Jul 28 18:14 ../
lrwxrwxrwx    1 root     root           0 Jul 28 18:14 ipc -> ipc:[4026532307]
lrwxrwxrwx    1 root     root           0 Jul 28 18:14 mnt -> mnt:[4026532303]
lrwxrwxrwx    1 root     root           0 Jul 28 18:14 net -> net:[4026532310]
lrwxrwxrwx    1 root     root           0 Jul 28 18:14 pid -> pid:[4026532308]
lrwxrwxrwx    1 root     root           0 Jul 28 18:46 user -> user:[4026531837]
lrwxrwxrwx    1 root     root           0 Jul 28 18:14 uts -> uts:[4026532306]

Any advice ?
the lxc use have been compile in an Ubuntu 14.04 system (with a prefix to match target system architecture)... then moved to the target
I use rpath to have directly the good lib (no LD_LIBRARY_PATH)
apparmor, secomp have been disabled (cgmanager have been added)

Philippe.

**Comment by father-mande** [comment]
Hi,

to complete ... and perhaps help me to identify the "Function not implemented"
the strace of : lxc-ibfo -n container -i ( -i = I.P. = crash) compare to same version on another system (armhf ... )
______________________________________________
strace working ARMHF (just before crash) kernel 3.10.20
_________________________________________________
open("/sys/fs/cgroup/freezer//lxc/test1/freezer.state", O_RDONLY|O_CLOEXEC) = 3
read(3, "THAWED\n", 100)                = 7
close(3)                                = 0
socket(PF_LOCAL, SOCK_STREAM, 0)        = 3
connect(3, {sa_family=AF_LOCAL, sun_path=@"/var/lib/lxc/test1/command"}, 29) = 0
getuid32()                              = 0
getgid32()                              = 0
sendmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\3\0\0\0\0\0\0\0\0\0\0\0", 12}], msg_controllen=24, [{cmsg_len=24, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=27841, uiG_NOSIGNAL) = 12
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\0\0\0\0\0\0\0\0\2\0\0\0", 12}], msg_controllen=0, msg_flags=0}, 0) = 12
close(3)                                = 0
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0xb5fe6068) = 27847
close(4)                                = 0
read(3, "10.0.3.218\0\0\260s\376\265\1\0\0\0\0\0\0\0\1\0\0\0X\331\376\265"..., 46) = 46
read(3, "", 46)                         = 0
wait4(27847, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 27847
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=27847, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
close(3)                                = 0
fstat64(1, {st_mode=S_IFCHR|0600, st_rdev=makedev(136, 2), ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb5fe5000
write(1, "IP:             10.0.3.218\n", 27IP:             10.0.3.218
) = 27
exit_group(0)                           = ?
+++ exited with 0 +++
______________________________________
strace for same command falling AMD64 kernel 4.1.0
________________________________________________
open("/sys/fs/cgroup/lxc/test/freezer.state", O_RDONLY|O_CLOEXEC) = 3
read(3, "THAWED\n", 100)                = 7
close(3)                                = 0
socket(PF_LOCAL, SOCK_STREAM, 0)        = 3
connect(3, {sa_family=AF_LOCAL, sun_path=@"/usr/local/AppCentral/lxc/var/lib/lxc/test/command"}, 53) = 0
getuid()                                = 0
getgid()                                = 0
sendmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16}], msg_controllen=32, [{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=27939, uid=0, gid=0}}], msg_flags=0}, MSG_NOSIGNAL) = 16
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\0\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0", 16}], msg_controllen=0, msg_flags=0}, 0) = 16
close(3)                                = 0
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f34806caa50) = 27940
close(4)                                = 0
read(3, lxc-info: utils.c: switch_to_ns: 1096 Function not implemented - failed to set process 27446 to net of 3.
lxc-info: lxccontainer.c: do_lxcapi_get_ips: 1881 Function not implemented - failed to enter namespace
"", 46)                         = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=27940, si_uid=0, si_status=1, si_utime=0, si_stime=0} ---
wait4(27940, [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 27940
close(3)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++


Philippe.

**Comment by brauner** [comment]
The error seems to be related to the `setns()` system call. `LXC` complains that `setns()` is not implemented. This is weird since the glibc version shipping with 14.04 should be newer then `2.14` and hence, have `setns()` implemented. Can you please show the output of `cat /etc/os-release`, `ldd --version`, and `uname -a` on the system showing the error? Also, please append any logs that you can produce by running `lxc-ls -f -l DEBUG -o output_file.txt` on the affected system.

**Comment by father-mande** [comment]
Hi,

Thanks for helping us ...
F.Y.I. I also send (and discuss with us) the problem to Asustor the provider of the NAS where run test (and remember I can use it in input or output network but some command are restricted)
INFO requested : 
os-release don't exist on NAS
uname : 
Linux AS5002TaPhil 4.1.0 #1 SMP Mon Jul 18 02:46:43 CST 2016 x86_64 GNU/Linux
Glibc version : 2.22
GNU C Library (GNU libc) stable release version 2.22, by Roland McGrath et al.
Compiled by GNU CC version 4.6.4.
        crypt add-on version 2.1 by Michael Glad and others
ldd --version : 
ldd (crosstool-NG crosstool-ng-1.22.0 - x86_64 64-bit toolchain - ASUSTOR Inc.) 2.22
$Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$Written by Roland McGrath and Ulrich Drepper.
output_file.ttxt produce by lxc-ls -f
___________________________________________
# cat output_file.txt
         lxc-ls 20160730183301.673 WARN     lxc_confile - confile.c:config_pivotdir:1879 - lxc.pivotdir is ignored.  It will soon become an error.
         lxc-ls 20160730183301.677 WARN     lxc_commands - commands.c:lxc_cmd_get_cgroup_path:461 - 'test' has stopped before sending its state
         lxc-ls 20160730183301.677 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:579 - 'test' is in 'RUNNING' state
         lxc-ls 20160730183301.677 WARN     lxc_commands - commands.c:lxc_cmd_get_cgroup_path:461 - 'test' has stopped before sending its state
         lxc-ls 20160730183301.677 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:579 - 'test' is in 'RUNNING' state
         lxc-ls 20160730183301.678 ERROR    lxc_utils - utils.c:switch_to_ns:1096 - Function not implemented - failed to set process 28244 to net of 4.
         lxc-ls 20160730183301.678 ERROR    lxc_container - lxccontainer.c:do_lxcapi_get_interfaces:1789 - Function not implemented - failed to enter namespace
         lxc-ls 20160730183301.679 ERROR    lxc_utils - utils.c:switch_to_ns:1096 - Function not implemented - failed to set process 28244 to net of 4.
         lxc-ls 20160730183301.679 ERROR    lxc_container - lxccontainer.c:do_lxcapi_get_ips:1881 - Function not implemented - failed to enter namespace
         lxc-ls 20160730183301.680 ERROR    lxc_utils - utils.c:switch_to_ns:1096 - Function not implemented - failed to set process 28244 to net of 4.
         lxc-ls 20160730183301.680 ERROR    lxc_container - lxccontainer.c:do_lxcapi_get_ips:1881 - Function not implemented - failed to enter namespace
         lxc-ls 20160730183301.681 WARN     lxc_commands - commands.c:lxc_cmd_get_cgroup_path:461 - 'test' has stopped before sending its state
         lxc-ls 20160730183301.681 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:579 - 'test' is in 'RUNNING' state
         lxc-ls 20160730183301.681 WARN     lxc_commands - commands.c:lxc_cmd_get_cgroup_path:461 - 'test' has stopped before sending its state
         lxc-ls 20160730183301.682 WARN     lxc_commands - commands.c:lxc_cmd_get_cgroup_path:461 - 'test' has stopped before sending its state
         lxc-ls 20160730183301.682 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:579 - 'test' is in 'RUNNING' state
         lxc-ls 20160730183301.682 WARN     lxc_commands - commands.c:lxc_cmd_get_cgroup_path:461 - 'test' has stopped before sending its state
         lxc-ls 20160730183301.682 WARN     lxc_commands - commands.c:lxc_cmd_get_cgroup_path:461 - 'test' has stopped before sending its state
         lxc-ls 20160730183301.683 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:579 - 'test' is in 'RUNNING' state
         lxc-ls 20160730183301.683 WARN     lxc_commands - commands.c:lxc_cmd_get_cgroup_path:461 - 'test' has stopped before sending its state
         lxc-ls 20160730183301.683 WARN     lxc_commands - commands.c:lxc_cmd_get_cgroup_path:461 - 'test' has stopped before sending its state
         lxc-ls 20160730183301.683 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:579 - 'test' is in 'RUNNING' state
         lxc-ls 20160730183301.684 WARN     lxc_commands - commands.c:lxc_cmd_get_cgroup_path:461 - 'test' has stopped before sending its state
______________________________________________________

NB I have also try some ip netns and nsenter command without success ... so ... The strange here is to have only problem getting the I.P. related information (or attach) ???

Philippe.

**Comment by brauner** [comment]
My guess it that the kernel on your machine does not implement the `setns()` syscall and hence returns `ENOSYS` aka `Function not implemented`. You should check with your provider if they applied some custom kernel patches. There is unfortunately nothing `LXC` can do to solve this.
