### ISSUE TITLE
Lxc live migartion on CentOS/RHEL 6

### ISSUE THREAD

**Issue by pain15** [lxc/lxc#1113]
I have installed LXC and created few containers based on this link [1] .My main intention is to perform live migration which I have succeeded on Ubuntu16.04 [2]. But, I'm unable to find any guidelines to perform Lxc live migration on CenOS/RHEL 6.

Is Lxc live migration available on CentOS/RHEL?

1. http://www.tecmint.com/install-create-run-lxc-linux-containers-on-centos/
2. https://insights.ubuntu.com/2015/05/06/live-migration-in-lxd/

**Comment by tych0** [comment]
Assuming you have CRIU >= 2.0, a kernel >= 4.4, and liblxc >= 2.0 it should work for most cases.

**Comment by pain15** [comment]
In rhel/centos , after installing lxc only the commands like lxc-start , lxc-ls etc will work i.e lxc- (lxc hyphen commands) . 

If i just type "lxc" and enter .It says command not found

Unlike ubuntu where lxc command can be used which allows us to create lxc remote files, profiles , and finally migrate

Without lxc command , I dint find any similar commands with lxc- (lxc hyphen) to perfrom live migration

**Comment by tych0** [comment]
Yes, for the `lxc` command you'll need LXD, which I don't think is yet packaged for centos. Perhaps building from source is the best option there.

**Comment by pain15** [comment]
Building from source?

I have never used Centos. So, will there be any PPA or any other method  to install packages as in ubuntu.As per my knowledge LXD is not yet predefined package in CentOS

**Comment by brauner** [comment]
As @tych0 suggested you need to either build `LXD` from source or package `LXD` for centos. Closing as there's nothing we can do about it.
