### ISSUE TITLE
/etc/mtab is not a symlink on Ubuntu 12.04 image

### ISSUE THREAD

**Issue by zenitraM** [lxc/lxc#1121]
LXD 2.0.2 running on Ubuntu 16.04, ubuntu image hash 38a72ae0da86.

Steps to reproduce:
```
ubuntu@cont02:~$ lxc launch ubuntu:12.04 mtabtest
Creating mtabtest
Starting mtabtest
ubuntu@cont02:~$ lxc exec mtabtest -- ls -l /etc/mtab
-rw-r--r-- 1 root root 1497 Aug 12 11:44 /etc/mtab
```

It seems that mtab is being written as a file instead of symlinked to `/proc/mounts`, which causes further mounts not to appear.

On Ubuntu 16 image it appears:
```
ubuntu@cont02:~$ lxc launch ubuntu:16.04 mtabtest
Creating mtabtest
Starting mtabtest
ubuntu@cont02:~$ lxc exec mtabtest -- ls -la /etc/mtab
lrwxrwxrwx 1 root root 19 Aug 12 11:46 /etc/mtab -> ../proc/self/mounts
```

I haven't been able to find out where they are being created from as in both cases they don't seem to be on the image rootfs.

**Comment by stgraber** [comment]
That's on purpose. Upstart expects /etc/mtab to be a writable file, so Ubuntu 12.04 and 14.04 should be a normal file. Systemd expects it to be a symlink to /proc/self/mounts, so Ubuntu 16.04 should be a symlink.

**Comment by zenitraM** [comment]
Oh, that makes sense. Then I guess the bug is rather that new disk mounts aren't added to `/etc/mtab` once mounted (is this LXC/LXD responsiblity or of something inside the container?)

**Comment by stgraber** [comment]
Right, so mounts done before init starts won't show up. I'd argue that this is an upstart/mountall bug, the init system should dump whatever's in /proc/self/mounts into /etc/mtab at boot time.

It's clearly not a use case that was considered at the time those init systems were written since containers weren't a thing and so they pretty much always had an empty mount table at the time pid 1 was executed.

**Comment by zenitraM** [comment]
Mounts "hotplugged" after init aren't shown either, i suspect this is expected as well.

Strangely enough upstart hasn't complained yet about replacing mtab with a symlink and it's left it alone, so I might just do that on my template as a workaround

**Comment by brauner** [comment]
Closing as this is likely not our bug.
