### ISSUE TITLE
Root inside the container able to delete any file in a mounted directory

### ISSUE THREAD

**Issue by andreitognolo** [lxc/lxc#1130]
I have an unprivileged container which has access to a mount entry. I was expecting the root inside the container to **only** have "special power" over files which belongs to the users in the subuid mapping. However, the root inside the container (who is actually the user 100000 outside the container) is able to delete any file regardless of who is the owner. Is that expected to happen? Am I missing something?

Here is some informations about my environment and the sequence of steps to reproduce:

### Configurations
```
Distribution: Ubuntu 14.04.5 LTS
uname -r: 3.13.0-93-generic
lxc version: 2.0.3

~/.config/lxc/default.conf
(...)
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536

sudo usermod --add-subuids 100000-165536 $USER
sudo usermod --add-subgids 100000-165536 $USER
sudo chmod +x $HOME
```

### Deleting a file owned by an user in subuid mapping range
```
lxc-create -t download -n p1 -- -d ubuntu -r trusty -a amd64

sudo mkdir -p ~/.local/share/lxc/p1/rootfs/projectdata
sudo mkdir -p projectdata
sudo chown 100000:100000 projectdata

sudo touch projectdata/user-in-subid-file
sudo chown 110000:110000 projectdata/user-in-subid-file


lxc-start -n p1 -d -s lxc.mount.entry="$HOME/projectdata projectdata none rw,bind 0 0"
lxc-attach -n p1 -- rm -rf /projectdata/user-in-subid-file
# It deletes the file (as I was expecting)
```

### Deleting a file owned by the real root
```
sudo touch projectdata/real-root-file
lxc-attach -n p1 -- rm -rf /projectdata/real-root-file
# It deletes the file (but I was expecting a permission denied here)
```

**Comment by brauner** [comment]
`sudo chown 100000:100000 projectdata`
^^^ Assuming that `~/projectdata` has the standard permissions `755` the owner of the file will be able to delete any file inside of the directory. Since you change the owner of the directory to be your mapped container user and then start the container you are able to delete files inside. This is standard *nix DAC behavior. :) Try the same but do: `sudo chown ${id -u}:${id -g} projectdata` and you won't be able to delete the file even if it belongs to your mapped container user.

**Comment by hallyn** [comment]
> ### Deleting a file owned by the real root
> ```
> sudo touch projectdata/real-root-file
> lxc-attach -n p1 -- rm -rf /projectdata/real-root-file
> # It deletes the file (but I was expecting a permission denied here)
> ```

Note also,

mkdir xxx
sudo touch xxx/ab
rm -f xxx/ab

**Comment by andreitognolo** [comment]
@brauner @hallyn thanks for your patience and detailed explanation. That makes sense :)
