### ISSUE TITLE
lxc 2.0.4

### ISSUE THREAD

**Issue by LaKing** [lxc/lxc#1135]
After installing 2.04 from the tarball, lxc stopped working on my system. Investigating about the possible causes.

**Comment by LaKing** [comment]
Seems some underlying parameters changed. 

After symlinking the main config dir /usr/local/share/lxc to /usr/local/lxc I was able to list newly created containers, oddly not the existing ones. It's not just lxc-ls behaving different then it used to, other commands suffer from changes as well. Still investigating. ...

**Comment by stgraber** [comment]
None of that changed in 2.0.4, /usr/local/share is what you get when you don't tell the configure script about another prefix.

It looks like your previous version of LXC (possibly from your distro?) was built with one set of configure options (including --prefix and possibly a bunch more path related ones) but your 2.0.4 one wasn't, leading to existing containers pointing to paths that no longer exist.

**Comment by LaKing** [comment]
Yes it looks like something messed with the path's. Thank you for your reply.
