### ISSUE TITLE
python-lxc attach_wait prevents further keyboard input

### ISSUE THREAD

**Issue by larryprice** [lxc/lxc#1137]
I've found that my python scripts stop responding to keyboard input after running an lxc attach_wait command in python3-lxc (2.0.4-0ubuntu2).

I wrote a small script to quickly reproduce the issue. With the script, one can see that using Ctrl+C _before_ running the lxc command causes a KeyboardInterrupt, but using Ctrl+C _after_ the lxc command finishes is no longer caught.

``` python
#!/usr/bin/env python3

import lxc
import time
import os

CONTAINER_NAME='xenial'
CONTAINER_PATH='%s/.cache/libertine-container' % os.environ["HOME"]

def lxc_work():
    container = lxc.Container(CONTAINER_NAME, CONTAINER_PATH)
    container.start()
    container.attach_wait(lxc.attach_run_command, ['ls'])

print("Ctrl+C will attempt to stop the script during the next ~5 seconds")
time.sleep(5)

print("Running lxc command 'ls' in container '%s', please wait..." % CONTAINER_NAME)
lxc_work()

print("Ctrl+C should attempt to stop the script in the next ~5 seconds, but doesn't")
time.sleep(5)
```

Also see: https://gist.github.com/larryprice/f562f838ff84929c1619978a6404b8b6

**Comment by brauner** [comment]
This is not reproducible for me anymore with current git master. If it still is, please re-open.
