### ISSUE TITLE
Mount rootfs failed

### ISSUE THREAD

**Issue by liushuo0826** [lxc/lxc#1153]
Hello,
I do have this directory on my Android system, but it can't be mounted, this is the log:
lxc-start guest 20160109005126.974 ERROR    lxc_conf - conf.c:mount_rootfs:807 - No such file or directory - failed to get real path for '/data/lxc/lxc/lib/lxc/rootfs

Thank you!

**Comment by brauner** [comment]
Hi, this is unfortunately not enough information to debug this. What version of `LXC` are you using? Can you please append the full log and the containers config file?

**Comment by liushuo0826** [comment]
1. I clone the master branch and make a cross-compiling by myself.
2. My config file is very simple, I just wanna a test
```
lxc.utsname=guest
lxc.rootfs=/data/lxc/lxc/lib/lxc/rootfs
lxc.mount=/system/local/fstab
```

3.This is the whole log,
```
lxc-start guest 20160109005126.864 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:209 - connect : backing off 10
      lxc-start guest 20160109005126.875 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:209 - connect : backing off 50
      lxc-start guest 20160109005126.926 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:209 - connect : backing off 100
'     lxc-start guest 20160109005126.974 ERROR    lxc_conf - conf.c:mount_rootfs:807 - No such file or directory - failed to get real path for '/data/lxc/lxc/lib/lxc/rootfs
      lxc-start guest 20160109005126.975 ERROR    lxc_conf - conf.c:setup_rootfs:1221 - failed to mount rootfs
      lxc-start guest 20160109005126.975 ERROR    lxc_conf - conf.c:do_rootfs_setup:3623 - failed to setup rootfs for 'guest'
      lxc-start guest 20160109005126.975 ERROR    lxc_conf - conf.c:lxc_setup:3705 - Error setting up rootfs mount after spawn
      lxc-start guest 20160109005126.975 ERROR    lxc_start - start.c:do_start:841 - failed to setup the container
      lxc-start guest 20160109005126.975 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
      lxc-start guest 20160109005127.027 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:214 - connect : Connection refused
      lxc-start guest 20160109005127.027 ERROR    lxc_start_ui - tools/lxc_start.c:main:344 - The container failed to start.
      lxc-start guest 20160109005127.027 ERROR    lxc_start_ui - tools/lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start guest 20160109005127.027 ERROR    lxc_start_ui - tools/lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.
      lxc-start guest 20160109005127.071 ERROR    lxc_start - start.c:__lxc_start:1361 - failed to spawn 'guest'

```

**Comment by liushuo0826** [comment]
The log when enable TRACE.

`      lxc-start guest 20160109092121.881 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 4
      lxc-start guest 20160109092121.883 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 9
      lxc-start guest 20160109092121.896 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:797 - Attempting to set proc title to [lxc monitor] /data/lxc/lxc/var/lib/lxc guest
      lxc-start guest 20160109092121.898 INFO     lxc_utils - utils.c:setproctitle:1460 - setting cmdline failed - Invalid argument
      lxc-start guest 20160109092121.902 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 9
      lxc-start guest 20160109092121.903 DEBUG    lxc_start - start.c:setup_signal_fd:297 - sigchild handler set
      lxc-start guest 20160109092121.904 DEBUG    lxc_console - console.c:lxc_console_peer_default:469 - no console peer
      lxc-start guest 20160109092121.904 INFO     lxc_start - start.c:lxc_init:496 - 'guest' is initialized
      lxc-start guest 20160109092121.909 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 4
      lxc-start guest 20160109092121.911 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 9
      lxc-start guest 20160109092121.916 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/ab92e3253a903eb4//data/lxc/lxc/var/lib/lxc
      lxc-start guest 20160109092121.918 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:209 - connect : backing off 10
      lxc-start guest 20160109092121.930 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:209 - connect : backing off 50
      lxc-start guest 20160109092121.982 DEBUG    lxc_start - start.c:__lxc_start:1334 - Not dropping cap_sys_boot or watching utmp
      lxc-start guest 20160109092121.982 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:209 - connect : backing off 100
      lxc-start guest 20160109092121.982 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:68 - cgroup driver cgroupfs initing for guest
'     lxc-start guest 20160109092122.030 ERROR    lxc_conf - conf.c:mount_rootfs:807 - No such file or directory - failed to get real path for '/data/lxc/lxc/lib/lxc/rootfs
      lxc-start guest 20160109092122.031 ERROR    lxc_conf - conf.c:setup_rootfs:1221 - failed to mount rootfs
      lxc-start guest 20160109092122.031 ERROR    lxc_conf - conf.c:do_rootfs_setup:3623 - failed to setup rootfs for 'guest'
      lxc-start guest 20160109092122.031 ERROR    lxc_conf - conf.c:lxc_setup:3705 - Error setting up rootfs mount after spawn
      lxc-start guest 20160109092122.031 ERROR    lxc_start - start.c:do_start:841 - failed to setup the container
      lxc-start guest 20160109092122.031 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
      lxc-start guest 20160109092122.083 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:214 - connect : Connection refused
      lxc-start guest 20160109092122.083 ERROR    lxc_start_ui - tools/lxc_start.c:main:344 - The container failed to start.
      lxc-start guest 20160109092122.083 ERROR    lxc_start_ui - tools/lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start guest 20160109092122.084 ERROR    lxc_start_ui - tools/lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.
      lxc-start guest 20160109092122.090 ERROR    lxc_start - start.c:__lxc_start:1361 - failed to spawn 'guest'
`

**Comment by stgraber** [comment]
So, does /data/lxc/lxc/lib/lxc/rootfs exist on your host within the environment that lxc-start is being called from (from past Android experience, it may be within some kind of chroot).

**Comment by stgraber** [comment]
The source for the error you're getting from LXC is that it failed to bind-mount the container's rootfs (as defined by lxc.rootfs) onto the LXC mount path which on your system appears to be at /data/lxc/lxc/lib/lxc/rootfs

**Comment by liushuo0826** [comment]
Thank you for your reply, I have found a new problem.  When the source code using mkdir() API to create a directory on Android6.0, it always returns "no such file or directory".  But the directory can be created.
I have root permission and selinux also disable.  Now I doubt it is the fault of the NDK toolchain.
The /data/lxc/lxc/lib/lxc/rootfs does exist and I use the shell command mkdir to create it.

Can you give me more information about the chroot you mentioned on Android platform?

**Comment by stgraber** [comment]
What command are you running on your phone exactly?

**Comment by liushuo0826** [comment]
Complie:
-1.$autogen.sh
-2.$./configure --host=aarch64-linux-android --with-runtime-path=/cache/lxcruntime --prefix=/cache/lxc/ --disable-python
-3.$make CFLAGS="-fPIE -pie" LDFLAGS="-fPIE"
-4.$sudo make install
-5 Push all the binaries and libs to the Phone
Run:
#lxc-create -t none -n android0
lxc-create: lxccontainer.c: do_create_container_dir: 972 No such file or directory - failed to create container path /cache/lxc/var/lib/lxc/android0
lxc-create: tools/lxc_create.c: main: 318 Error creating container android0
> Then I create /cache/lxc/var/lib/lxc/ manually by mkdir and run lxc-create again successfully

#lxc-start -f /cache/config --logfile=log.txt --logpriority=TRACE -n android0
 lxc-start 20160109233921.678 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 4
 lxc-start 20160109233921.680 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 9
 lxc-start 20160109233921.694 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:797 - Attempting to set proc title to [lxc monitor] /cache/lxc/var/lib/lxc android0
 lxc-start 20160109233921.696 INFO     lxc_utils - utils.c:setproctitle:1460 - setting cmdline failed - Invalid argument
 lxc-start 20160109233921.699 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 9
 lxc-start 20160109233921.701 DEBUG    lxc_start - start.c:setup_signal_fd:290 - sigchild handler set
 lxc-start 20160109233921.702 DEBUG    lxc_console - console.c:lxc_console_peer_default:469 - no console peer
 lxc-start 20160109233921.702 INFO     lxc_start - start.c:lxc_init:489 - 'android0' is initialized
 lxc-start 20160109233921.707 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 4
 lxc-start 20160109233921.709 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 9
 lxc-start 20160109233921.721 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/6c8130cf6e3edff8//cache/lxc/var/lib/lxc
 lxc-start 20160109233921.722 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:209 - connect : backing off 10
 lxc-start 20160109233921.733 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:209 - connect : backing off 50
 lxc-start 20160109233921.784 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:209 - connect : backing off 100
 lxc-start 20160109233921.813 DEBUG    lxc_start - start.c:__lxc_start:1327 - Not dropping cap_sys_boot or watching utmp
 lxc-start 20160109233921.814 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:68 - cgroup driver cgroupfs initing for android0
 lxc-start 20160109233921.817 ERROR    lxc_cgfs - cgroups/cgfs.c:handle_cgroup_settings:2133 - Device or resource busy - failed to set memory.use_hierarchy to 1; continuing
 lxc-start 20160109233921.818 ERROR    lxc_cgfs - cgroups/cgfs.c:handle_cgroup_settings:2133 - Device or resource busy - failed to set memory.use_hierarchy to 1; continuing
 lxc-start 20160109233921.860 ERROR    lxc_conf - conf.c:mount_rootfs:807 - No such file or directory - failed to get real path for '/cache/lxc/lib/lxc/rootfs
 lxc-start 20160109233921.860 ERROR    lxc_conf - conf.c:setup_rootfs:1221 - failed to mount rootfs
 lxc-start 20160109233921.860 ERROR    lxc_conf - conf.c:do_rootfs_setup:3623 - failed to setup rootfs for 'android0'
 lxc-start 20160109233921.860 ERROR    lxc_conf - conf.c:lxc_setup:3705 - Error setting up rootfs mount after spawn
 lxc-start 20160109233921.860 ERROR    lxc_start - start.c:do_start:834 - failed to setup the container
 lxc-start 20160109233921.862 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
 lxc-start 20160109233921.885 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:214 - connect : Connection refused
 lxc-start 20160109233921.885 ERROR    lxc_start_ui - tools/lxc_start.c:main:344 - The container failed to start.
 lxc-start 20160109233921.886 ERROR    lxc_start_ui - tools/lxc_start.c:main:346 - To get more details, run the container in foreground mode.
 lxc-start 20160109233921.886 ERROR    lxc_start_ui - tools/lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.
 lxc-start 20160109233921.954 ERROR    lxc_start - start.c:__lxc_start:1354 - failed to spawn 'android0'

**Comment by liushuo0826** [comment]
I think I've found the problem, sir.
When I cross-complie the lxc, I disabled the CAPBILITY and HOSTNAME macro because of lack of libcap for Android NDK.  Now I add the libcap for the NDK and complie again. It seems work now!
```
$lxc-info -n android0
Name:           android0
State:          RUNNING
PID:            2480
CPU use:        3.13 seconds
Memory use:     2.49 MiB
```

One more, the log still shows followings, I will check it.
```
 lxc-start android0 20160101083019.759 ERROR    lxc_start - start.c:__lxc_start:1361 - failed to spawn 'android0'
      lxc-start android0 20160101085346.315 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:209 - connect : backing off 10
      lxc-start android0 20160101085346.326 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:209 - connect : backing off 50
      lxc-start android0 20160101085346.362 ERROR    lxc_cgfs - cgroups/cgfs.c:handle_cgroup_settings:2133 - Device or resource busy - failed to set memory.use_hierarchy to 1; continuing
      lxc-start android0 20160101085346.363 ERROR    lxc_cgfs - cgroups/cgfs.c:handle_cgroup_settings:2133 - Device or resource busy - failed to set memory.use_hierarchy to 1; continuing
      lxc-start android0 20160101085346.377 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:209 - connect : backing off 100
      lxc-start android0 20160101085346.477 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:214 - connect : Connection refused
      lxc-start android0 20160101085346.478 ERROR    lxc_start_ui - tools/lxc_start.c:main:344 - The container failed to start.
      lxc-start android0 20160101085346.478 ERROR    lxc_start_ui - tools/lxc_start.c:main:346 - To get more details, run the container in foreground mode.
```

**Comment by liushuo0826** [comment]
Please

**Comment by huanghaitao** [comment]
I am working for the lxc running on android. I also face many problems. May I ask some question?
