### ISSUE TITLE
checkpoint failed for debain image 

### ISSUE THREAD

**Issue by chenhaiq** [lxc/lxc#1156]
This is another error from #1150 . I have lxc using master code, which fixed error from restoring trusty instance, but debain still fails.

To reproduce:
```
lxc-create -t download -n d1 -- -r wheezy -d debian -a amd64
# edit config to support checkpoint
lxc-start -n d1
lxc-checkpoint -n d1 -v -D /tmp/dump6 -s
lxc-checkpoint -n d1 -v -D /tmp/dump6 -r -o /tmp/dump6/lxc.log -l TRACE
```

log files:
https://pek3a.qingstor.com/oc-storage/dump.log
https://pek3a.qingstor.com/oc-storage/lxc.log
https://pek3a.qingstor.com/oc-storage/restore.log

**Comment by chenhaiq** [comment]
```
lxc.include = /usr/share/lxc/config/debian.common.conf
lxc.arch = x86_64

# Container specific configuration
lxc.rootfs = /var/lib/lxc/d1/rootfs
lxc.rootfs.backend = dir
lxc.utsname = d1

# Network configuration
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:7f:90:dd


lxc.console = none
lxc.tty = 0
lxc.cgroup.devices.deny = c 5:1 rwm
lxc.mount.auto = cgroup:mixed
lxc.autodev = 1
lxc.kmsg = 0
lxc.include = /usr/share/lxc/config/common.conf.d/00-lxcfs.conf
```
LXC is master code. The same env with #1150

**Comment by chenhaiq** [comment]
debain/jessie also fail in restore, but has different log:
https://pek3a.qingstor.com/oc-storage/dump_8027.log
https://pek3a.qingstor.com/oc-storage/lxc_dump_0827.log
https://pek3a.qingstor.com/oc-storage/lxc_restore_0827.log
https://pek3a.qingstor.com/oc-storage/restore_0827.log

**Comment by brauner** [comment]
This seems to be fixed with above PRs. Please reopen if the issue still persists with newer versions of `LXC`.
