### ISSUE TITLE
templates should not set insecure default passwords

### ISSUE THREAD

**Issue by evgeni** [lxc/lxc#1158]
Hi,

promted by https://bugs.debian.org/831850, I had a look at the various templates and how they handle passwords.
There is an (outdated) overview done by the Fedora people at https://fedoraproject.org/wiki/LXC_Template_Security_Improvements

Let's update it and discuss :)

| template | default root password | root password changeable | notes |
| --- | --- | --- | --- |
| alpine | N/A | No |  |
| altlinux | rooter | No |  |
| archlinix | N/A | Yes |  |
| busybox | root | No |  |
| centos | random | Yes | IMHO not really random |
| cirros | N/A | No | password not touched, probably cirros default |
| debian | N/A | No |  |
| fedora | random | Yes | IMHO not really random |
| gentoo | toor | Yes | can be disabled |
| openmandriva | root | No |  |
| opensuse | root | No |  |
| oracle | root | No | additional oracle user with oracle password |
| plamo | root | No |  |
| pld | root | No |  |
| slackware | root | No |  |
| sparclinux | root | No |  |
| sshd | N/A | No |  |
| ubuntu | N/A | No | ubuntu user with ubuntu password, overridable |

IMHO containers should ship with no default passwords, and have a way to set them at creation time (either via `--pasword` or from the ENV).

**Comment by brauner** [comment]
I think we decided that we want no root password to be set per default. Setting a password at creation time is probably not necessary since you can always just `lxc-attach` and set a password. We've discussed both of these issues before and I think this sums up the outcome. (/cc @stgraber). Patches to remove the passwords from templates are very much welcome. :)

**Comment by stgraber** [comment]
Right and that's what I've been doing for the download template.

We were discussing whether we wanted to use the fancy random password generation code that fedora/centos have in their templates but now that we can basically assume all users have a kernel capable of setns. So I'd be fine with just removing all of them and having the templates tell the user how to set a password with lxc-attach.

**Comment by evgeni** [comment]
Updated version for master (as of b49bb7dce83d6ea55785b7c7ccacca2370a3ba63)

| template | default root password | root password changeable | notes |
| --- | --- | --- | --- |
| alpine | N/A | No |  |
| altlinux | rooter | No | still unfixed |
| archlinix | N/A | Yes |  |
| busybox | N/A | No |  fixed |
| centos | random | Yes | IMHO not really random |
| cirros | N/A | No | password not touched, probably cirros default |
| debian | N/A | No |  |
| fedora | random | Yes | IMHO not really random |
| fedora-legacy | random | Yes | IMHO not really random |
| gentoo | toor | Yes | can be disabled, still unfixed |
| openmandriva | root | No | still unfixed |
| opensuse | N/A | No | fixed |
| oracle | N/A | No | fixed |
| plamo | N/A | No | fixed |
| pld | root | No |  still unfixed |
| sabayon | N/A | No |  |
| slackware | N/A | No |  fixed |
| sparclinux | N/A | No | fixed |
| sshd | N/A | No | but sshd allows logins without password! |
| ubuntu | N/A | No | ubuntu user with ubuntu password, overridable |

**Comment by evgeni** [comment]
Updated version for master (as of 1a9eaaab20fc41a096808fd36f355c54a0f4c1ce)

| template | default root password | root password changeable | notes |
| --- | --- | --- | --- |
| alpine | N/A | No |  |
| altlinux | N/A | No | fixed |
| archlinix | N/A | Yes |  |
| busybox | N/A | No |  fixed, but sshd allows logins without password! |
| centos | random | Yes | IMHO not really random |
| cirros | N/A | No | password not touched, probably cirros default |
| debian | N/A | No |  |
| fedora | random | Yes | IMHO not really random |
| fedora-legacy | random | Yes | IMHO not really random |
| gentoo | N/A | Yes | fixed |
| openmandriva | N/A | No | fixed |
| opensuse | N/A | No | fixed |
| oracle | N/A | No | fixed |
| plamo | N/A | No | fixed |
| pld | N/A | No |  fixed |
| sabayon | N/A | No |  |
| slackware | N/A | No |  fixed |
| sparclinux | N/A | No | fixed |
| sshd | N/A | No | but sshd allows logins without password! |
| ubuntu | N/A | No | ubuntu user with ubuntu password, overridable |

**Comment by evgeni** [comment]
with #1488 merged, I think we are done here, closing
