### ISSUE TITLE
Facing issue with snapshot on btrfs backed volume

### ISSUE THREAD

**Issue by bharad1988** [lxc/lxc#1160]
I have been using lxc-go libraries to create container and take a snapshot. Working on un-previleged containers as a non root user.

When i take a snapshot, i am seeing the following error.
newgidmap: gid range [100000-100001) -> [200000-200001) not allowed
error mapping child

here is my config:
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536

found this issue similar to id - #579
Also , went through this mail chain.
https://www.mail-archive.com/lxc-users@lists.linuxcontainers.org/msg03197.html

Can i get some help with any workarounds ?

Thanks
Aj

**Comment by brauner** [comment]
What is the name of your non-root user and what are the contents of `/etc/subuid/` and `/etc/subgid`?

**Comment by bharad1988** [comment]
ajay@ajay-ubuntu:~$ cat /etc/subuid
ajay:100000:65536
git:165536:65536
ajay@ajay-ubuntu:~$ cat /etc/subgid
ajay:100000:65536
git:165536:65536
ajay@ajay-ubuntu:~$ 

user name - ajay

**Comment by brauner** [comment]
Can you please also show the default group your user belongs to aka the output of `id -g`?

**Comment by bharad1988** [comment]
ajay@ajay-ubuntu:~$ id -g
1000

**Comment by brauner** [comment]
Can you please paste or attach the config for the container and the commands you use to produce the problem.
This seems like you're trying to map gids which your user is not assigned in `/etc/subgid`. Please make sure that you attach the right config.

**Comment by bharad1988** [comment]
The container was created by providing the Backend device option using go-lxc example code for create container . Value provided for lxc.Backend = 1
container name: tetsrubik
_Note: When container is created without backend device ( such as btrfs ), snapshot creation passed with the same configs. In that case no new btrfs sub-volumes were created_

Config:
$ cat ~/.config/lxc/default.conf 
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:xx:xx:xx
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536


Golang code snippet:
```
var backend    `lxc.BackendStore`
    backend = 1
    options := lxc.TemplateOptions{
        Template:             template,
        Distro:               distro,
        Release:              release,
        Arch:                 arch,
        FlushCache:           flush,
        DisableGPGValidation: validation,
        Backend:              backend,
    }

    if err := c.Create(options); err != nil {
        log.Printf("ERROR: %s\n", err.Error())
    }
}

```



mount path
/dev/loop0 on /home/ajay/btrfsStore type btrfs (rw,relatime,compress=zlib,space_cache,user_subvol_rm_allowed,subvolid=5,subvol=/)
ID 260 gen 161 top level 5 path tetsrubik/snaps/snap0/rootfs
ID 261 gen 186 top level 5 path tetsrubik/rootfs
ID 262 gen 109 top level 5 path tetsrubik/snaps/snap1/rootfs
ID 266 gen 109 top level 5 path tetsrubik/snaps/snap2/rootfs
ID 267 gen 109 top level 5 path tetsrubik/snaps/snap3/rootfs
ID 268 gen 109 top level 5 path tetsrubik/snaps/snap4/rootfs
ID 269 gen 109 top level 5 path tetsrubik/snaps/snap5/rootfs

**Comment by brauner** [comment]
I don't know if this is immediately related to you error but shouldn't you set `backend` to something like `dir`, `btrfs` or whatever is appropriate in your case. At least that is what I gather from the [sources](https://github.com/lxc/go-lxc/blob/d89df0ad9dc13a7ce491eedaa771b076cf32db16/examples/clone.go):

```
flag.Var(&backend, "backend", "Backend type to use, possible values are [dir, zfs, btrfs, lvm, aufs, overlayfs, loopback, best]")
```

**Comment by bharad1988** [comment]
$ go run ./examples/clone.go -backend btrfs
2016/08/29 22:02:32 Cloning the container using btrfs backend...
newgidmap: gid range [100000-100001) -> [200000-200001) not allowed
error mapping child
setgid: Invalid argument

The issue prevails. I think the variable enumerates to same thing. Is it an issue with the uid namespace mapping when subvolumes in btrfs is used ?

One more observation made:
I ran few more tests,
test1: 
restore tetsrubik with snap0 
When the snapshot was created the same error message was received. Now after restore as well i received the same message but the container successfully started.

`
$go run ./examples/restore_snapshot.go 
2016/08/29 22:08:17 Restoring the container...
newgidmap: gid range [100000-100001) -> [200000-200001) not allowed
error mapping child
setgid: Invalid argument
ajay@ajay-ubuntu:~/$ lxc-start -n rubik-restore1

`
Now i am not sure of the impact of the message.

below is the subvolume list from btrfs 
`
ID 260 gen 161 top level 5 path tetsrubik/snaps/snap0/rootfs
ID 261 gen 188 top level 5 path tetsrubik/rootfs
ID 262 gen 193 top level 5 path tetsrubik/snaps/snap1/rootfs
ID 266 gen 109 top level 5 path tetsrubik/snaps/snap2/rootfs
ID 267 gen 109 top level 5 path tetsrubik/snaps/snap3/rootfs
ID 268 gen 109 top level 5 path tetsrubik/snaps/snap4/rootfs
ID 269 gen 109 top level 5 path tetsrubik/snaps/snap5/rootfs
.
.
.
ID 291 gen 194 top level 5 path rubik-restore1/rootfs
root@ajay-ubuntu:~/btrfsStore/rubik-restore# 

`


Please let me know if the info. helps ...

Thanks

**Comment by bharad1988** [comment]
Also to clarify, i did the same thing as a root user + privileged containers, there seems to be no issues..

**Comment by brauner** [comment]
`~/.config/lxc/default.conf` is your default config. Can you please show the configuration file of the container you're cloning/snapshotting? And how did you create that container?

**Comment by bharad1988** [comment]
ajay@ajay-ubuntu:~$ cat .config/lxc/default.conf 
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:xx:xx:xx
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
lxc.logfile = /home/ajay/containers/lxc.log

Create container was issued through the go-lxc APIs using the example script. Also snapshotting was done using the example script.

One observation i saw when i ran the container create with root and non-root user : 
As non-root user
drwxrwx---  1 100000 ajay      34 Aug 30 07:19 testrubik5/
drwxrwx--- 1 100000 ajay 28 Aug 30 07:19 snap0/

As root user with subuid and subgids, 
drwxrwx---  1 100000 100000    34 Aug 29 23:11 testrubik4/
drwxrwx--- 1 100000 100000 28 Aug 30 07:16 snap0/

the subgid mapping is different
To summeraize ,
3 types of containers were created .
1) non-root user without specifying the backend device as btrfs ( resulted in full copy of the container, but no error message )
2) non-root user specifying the backend device as btrfs ( Snapshot was using the compression feature of btrfs very efficiently but threw the error message although i was able to start ) 
3) root user with btrfs as backend device ( Snapshot was efficient with space usage and no error message )

Thanks,
Ajay

**Comment by brauner** [comment]
On Mon, Aug 29, 2016 at 06:57:21PM -0700, bharad1988 wrote:
> ajay@ajay-ubuntu:~$ cat .config/lxc/default.conf 
> lxc.network.type = veth
> lxc.network.link = lxcbr0
> lxc.network.flags = up
> lxc.network.hwaddr = 00:16:3e:xx:xx:xx
> lxc.id_map = u 0 100000 65536
> lxc.id_map = g 0 100000 65536
> lxc.logfile = /home/ajay/containers/lxc.log
> 

My point was that you're currently showing me the contents for your *default*
configuration file. What I would like to see is the configuration file of the
container you're copying/snapshotting. For example, if you create a container
via the go-lxc API the container will probably for a non-root user be located at

	.local/share/lxc/CONTAINERNAME/

and you will find the corresponding configuration file usually here:

	.local/share/lxc/CONTAINERNAME/config

> Create container was issued through the go-lxc APIs using the example script. Also snapshotting was done using the example script.
> 
> One observation i saw when i ran the container create with root and non-root user : 
> As non-root user
> drwxrwx---  1 100000 ajay      34 Aug 30 07:19 testrubik5/
> drwxrwx--- 1 100000 ajay 28 Aug 30 07:19 snap0/
> 
> As root user with subuid and subgids, 
> drwxrwx---  1 100000 100000    34 Aug 29 23:11 testrubik4/
> drwxrwx--- 1 100000 100000 28 Aug 30 07:16 snap0/
> 
> the subgid mapping is different

This is expected. When you create a container as root then LXC will look at

	/etc/lxc/default.conf

and when you create a container as non-root then LXC will look at

	~/.config/lxc/default.conf

So it seems that you have not set

	lxc.id_map = g 0 100000 65536

in /etc/lxc/default.conf

> To summeraize ,
> 3 types of containers were created .
> 1) non-root user without specifying the backend device as btrfs ( resulted in full copy of the container, but no error message )

Expected, since btrfs default to snapshot mode.

> 2) non-root user specifying the backend device as btrfs ( Snapshot was using the compression feature of btrfs very efficiently but threw the error message although i was able to start ) 

I can't make much sense of this why this error would be caused specifically by
btrfs. It should happen with other backends as well.

> 3) root user with btrfs as backend device ( Snapshot was efficient with space usage and no error message )

**Comment by brauner** [comment]
@caglar10ur can you maybe help out here?

**Comment by bharad1988** [comment]
# Distribution configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.include = /usr/share/lxc/config/ubuntu.userns.conf
lxc.arch = x86_64

# Container specific configuration
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
lxc.logfile = /home/ajay/containers/lxc.log
lxc.rootfs = /home/ajay/btrfsStore/testrubik5/rootfs
lxc.rootfs.backend = btrfs
lxc.utsname = testrubik5

# Network configuration
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:ef:fa:2a

-----------------------------------------------------------
Btw,  I had set the subgid 
lxc.id_map = g 0 100000 65536

Right now, I have moved on to use root user ( instead of a non-root user ) to create un-privileged containers. I assume it will be safe to create them with root user. Please let me know any specific things i have to take care of to make them fully secure. 

>  2) non-root user specifying the backend device as btrfs ( Snapshot was using the compression feature of btrfs very efficiently but threw the error message although i was able to start )

Not bothered to much with this issue as long as btrfs would be safe to continue as a root user. Just curious to understand this case.

Thanks brauner...
