### ISSUE TITLE
lxc- start is not working with specific UID and GID map for privilege container

### ISSUE THREAD

**Issue by ragavaluvijay** [lxc/lxc#1176]
Hi Everyone ,

I would like to create & start LXC container for specific UID & GID for below purpose.

Login to root user(sudo user) , Do lxc-create of container, then do lxc-start of the container with same root user id. while staring container i need to start all the process inside the container with low privilege(un-priv) user id in which access to the user is restricted to only container and not to host.basically when i say ps -axu in host , i should be able to see the container process with low privilege user id(basically mapped UID/GID).

PS : my host which is VM with ubuntu 16.04 LTS is systemd init system and my container(type busybox) will be started with systemd services . for that i have modified busybox template as below
Code:
`lxc.init_cmd=/lib/systemd/systemd`
and also removed all rcS & inittab related scripts in the busybox default template
and for user id map , i have changed as below in my template
Code:

```
   lxc.id_map=u 0 165536 65536
   lxc.id_map=g 0 165536 65536
```

after that i just followed below commends

Container created normally with below commend (and i cross checked config file at /var/lib/lxc/testecho_uid/config to make sure that all my lxc template changes are reflected or not, found ok)
Command:
`sudo lxc-create -n testecho_uid -t busybox_systemd_uid`

Entered below command to start the container with foreground
Command:
`sudo lxc-start -n testecho_uid -F`

Error is :

>  vijay@vijay-VirtualBox:~$ sudo lxc-start -n testecho_uid -F
>     lxc-start: cgfsng.c: cgfsng_create: 1072 No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/testecho_uid: No such file or directory
>     lxc-start: cgfsng.c: cgfsng_create: 1072 No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/testecho_uid-1: No such file or directory
>     newuidmap: uid range [0-65536) -> [165536-231072) not allowed
>     lxc-start: start.c: lxc_spawn: 1161 failed to set up id mapping
>     lxc-start: start.c: __lxc_start: 1353 failed to spawn 'testecho_uid'
>     newuidmap: uid range [0-65536) -> [165536-231072) not allowed
>     lxc-start: conf.c: userns_exec_1: 4315 Error setting up child mappings
>     lxc-start: cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/systemd//lxc/testecho_uid-2
>     newuidmap: uid range [0-65536) -> [165536-231072) not allowed
>     lxc-start: conf.c: userns_exec_1: 4315 Error setting up child mappings
>     lxc-start: cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/perf_event//lxc/testecho_uid-2
>     newuidmap: uid range [0-65536) -> [165536-231072) not allowed
>     lxc-start: conf.c: userns_exec_1: 4315 Error setting up child mappings
>     lxc-start: cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/hugetlb//lxc/testecho_uid-2
>     newuidmap: uid range [0-65536) -> [165536-231072) not allowed
>     lxc-start: conf.c: userns_exec_1: 4315 Error setting up child mappings
>     lxc-start: cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/cpu//lxc/testecho_uid-2
>     newuidmap: uid range [0-65536) -> [165536-231072) not allowed
>     lxc-start: conf.c: userns_exec_1: 4315 Error setting up child mappings
>     lxc-start: cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/memory//lxc/testecho_uid-2
>     newuidmap: uid range [0-65536) -> [165536-231072) not allowed
>     lxc-start: conf.c: userns_exec_1: 4315 Error setting up child mappings
>     lxc-start: cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/pids//lxc/testecho_uid-2
>     newuidmap: uid range [0-65536) -> [165536-231072) not allowed
>     lxc-start: conf.c: userns_exec_1: 4315 Error setting up child mappings
>     lxc-start: cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/blkio//lxc/testecho_uid-2
>     newuidmap: uid range [0-65536) -> [165536-231072) not allowed
>     lxc-start: conf.c: userns_exec_1: 4315 Error setting up child mappings
>     lxc-start: cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/cpuset//lxc/testecho_uid-2
>     newuidmap: uid range [0-65536) -> [165536-231072) not allowed
>     lxc-start: conf.c: userns_exec_1: 4315 Error setting up child mappings
>     lxc-start: cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/net_cls//lxc/testecho_uid-2
>     newuidmap: uid range [0-65536) -> [165536-231072) not allowed
>     lxc-start: conf.c: userns_exec_1: 4315 Error setting up child mappings
>     lxc-start: cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/devices//lxc/testecho_uid-2
>     newuidmap: uid range [0-65536) -> [165536-231072) not allowed
>     lxc-start: conf.c: userns_exec_1: 4315 Error setting up child mappings
>     lxc-start: cgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/freezer//lxc/testecho_uid-2
>     lxc-start: lxc_start.c: main: 344 The container failed to start.
>     lxc-start: lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.

Can anyone please tell me whether i am missing anything here.

below are my ubuntu 16.04 setup for uid & gid

```
vijay@vijay-VirtualBox:~$ sudo cat  /etc/subgid
vijay:100000:65536
usrlxc:165536:65536
```

```
vijay@vijay-VirtualBox:~$ sudo cat  /etc/subuid
vijay:100000:65536
usrlxc:165536:65536
```

I have also tried by doing below config , still lxc-start was not happening 

```
lxc.cap.keep = sys_admin
lxc.cap.keep = net_admin
lxc.cap.keep = setgid
lxc.cap.keep = setuid
lxc.cap.keep = sys_boot
lxc.tty = 1
lxc.pts = 1
lxc.kmsg = 0

lxc.id_map=u 0 165536 65536
lxc.id_map=g 0 165536 65536
```

**Comment by brauner** [comment]
I suspect you need to add `uid` and `gid` mappings for your root user as well. So probably add something like

```
root:165536:65536
```

in `/etc/subgid` and `/etc/subuid`.

**Comment by ragavaluvijay** [comment]
@brauner ,
After adding uid & gid mapping for root i dont see one earlier error (mentioned the same here)
> newuidmap: uid range [0-65536) -> [165536-231072) not allowed
(this error is resolved now)

However now i am seeing below error 

> sudo lxc-start -n vijayhome -F
> lxc-start: cgfsng.c: cgfsng_create: 1072 No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/vijayhome: No such file or directory
>                                       lxc-start: cgfsng.c: cgfsng_create: 1072 No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/vijayhome-1: No such file or directory
>                                                                               lxc-start: cgfsng.c: cgfsng_create: 1072 No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/vijayhome-2: No such file or directory
>       lxc-start: cgfsng.c: cgfsng_create: 1072 No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/vijayhome-3: No such file or directory
>                                               lxc-start: cgfsng.c: cgfsng_create: 1072 No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/vijayhome-4: No such file or directory
>                                                                                       lxc-start: cgfsng.c: cgfsng_create: 1072 No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/vijayhome-5: No such file or directory
>               lxc-start: conf.c: mount_rootfs: 807 Permission denied - failed to get real path for '/var/lib/lxc/vijayhome/rootfs'
>                   lxc-start: conf.c: setup_rootfs: 1221 failed to mount rootfs
>                                                                               lxc-start: conf.c: do_rootfs_setup: 3612 failed to setup rootfs for 'vijayhome'
>                                              lxc-start: conf.c: lxc_setup: 3694 Error setting up rootfs mount after spawn
>          lxc-start: start.c: do_start: 833 failed to setup the container
>                                                                         lxc-start: sync.c: __sync_wait: 57 An error occurred in another process (expected sequence number 3)
>                                                             lxc-start: start.c: __lxc_start: 1353 failed to spawn 'vijayhome'
>              lxc-start: lxc_start.c: main: 344 The container failed to start.
> lxc-start: lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.
> 


and below are /etc/subuid and /etc/subgid info
```
root:165536:65536
vijay:100000:65536
usrlxc:165536:65536
```

```
root:165536:65536
vijay:100000:65536
usrlxc:165536:65536
```

Please see below my container config file , with this config i am facing above error.
```
# Template used to create this container: /usr/share/lxc/templates/lxc-busybox_vijayhome
# Parameters passed to the template:
# For additional config options, please look at lxc.container.conf(5)

# Uncomment the following line to support nesting containers:
#lxc.include = /usr/share/lxc/config/nesting.conf
# (Be aware this has security implications)

lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:e3:06:32
lxc.rootfs = /var/lib/lxc/vijayhome/rootfs
lxc.rootfs.backend = dir
lxc.haltsignal = SIGUSR1
lxc.rebootsignal = SIGTERM
lxc.utsname = vijayhome
lxc.tty = 1
lxc.pts = 1
lxc.cap.drop = sys_module mac_admin mac_override sys_time

# When using LXC with apparmor, uncomment the next line to run unconfined:
#lxc.aa_profile = unconfined


#lxc.cap.keep = sys_admin
#lxc.cap.keep = net_admin
#lxc.cap.keep = setgid
#lxc.cap.keep = setuid
#lxc.cap.keep = sys_boot
#lxc.kmsg = 0

lxc.id_map=u 0 165536 65536
lxc.id_map=g 0 165536 65536

lxc.init_cmd=/lib/systemd/systemd
lxc.mount.auto = cgroup:mixed proc:mixed sys:mixed
lxc.mount.entry = shm /dev/shm tmpfs defaults 0 0
lxc.mount.entry = /lib lib none ro,bind 0 0
lxc.mount.entry = /usr/lib usr/lib none ro,bind 0 0
lxc.mount.entry = /lib64 lib64 none ro,bind 0 0
lxc.mount.entry = /sys/kernel/security sys/kernel/security none ro,bind,optional 0 0
```

**Comment by ragavaluvijay** [comment]
I also tried lxc-execute to drop the root privilege , but no luck. .

I created the container from root using busy box template 
`lxc-create -t busybox -n cont_name`

then 
`lxc-execute -n cont_name -u 1001 -g 1001 ps`

output 

> init.lxc.static: initutils.c: mount_fs: 36 failed to mount /proc : Operation not permitted
> init.lxc.static: initutils.c: mount_fs: 36 failed to mount /dev/shm : Operation not permitted
> init.lxc.static: initutils.c: mount_fs: 36 failed to mount /dev/mqueue : Operation not permitted
> PID   USER     COMMAND
>     1 root     /init.lxc.static -- ps
>     2 root     ps

i still see ps is running as root . i am expecting it suppose to run as -u & -g option UID/GID value.

what i am missing here?
1001 is UID/GID value of the host and not user of the container , 
Do i need to create 1001 user under container ?
