### ISSUE TITLE
lxc-copy fails to clone unprivileged containers

### ISSUE THREAD

**Issue by oxwivi** [lxc/lxc#1180]
I created a a container that I want to use as a base to clone for installing different apps in each, however attempting to clone results in user mapping error:
```
$ lxc-copy -s --name ubuntu-gui --newname google-chrome
newgidmap: gid range [100000-100001) -> [200000-200001) not allowed
error mapping child
setgid: Invalid argument
```
Can I not make the clone reuse the same mapping?

**Comment by brauner** [comment]
It seems like you're trying to map a `subuid`/`subgid` that you're not controlling.
- What version of `LXC` are you using?
- Can you please append or paste the containers (`ubuntu-gui`) config?
- Can you please append or paste the contents of `/etc/subuid` and `/etc/subgid`?

**Comment by oxwivi** [comment]
Aah, if only you responded earlier. I left for a trip away from my systems a couple of hours before you commented.

I can't provide the details you asked for right now, but my containers are set up exactly as the instructions of stgraber's article on unprivileged containers and GUI in containers.

LXC's version is whatever the latest being shipped on Xenial repos.

**Comment by brauner** [comment]
Hm, okay. So if you retry, make sure that the `subuids`/`subgids` your container uses are actually assigned to the correct user in `/etc/subuid` and `/etc/subgid`. Please reopen if you can reproduce and provide the info. :)

**Comment by oxwivi** [comment]
I'm back.

Both `/etc/{subuid,subgid}`'s filled with the following:
```
virtoki:100000:65536
virtoki:100000:65537
```
How do I modify it so the new clone and any subsequent clones (I'm planning on cloning more) does not have the same issue?

**Comment by oxwivi** [comment]
Okay, just after the last comment I removed the `65537` line. I don't know how it came to be and stgraber's post only mention `65536`... After that `google-chrome` ran without any issue. I are confused.

**Comment by oxwivi** [comment]
... Oh, that's wrong too. Other than outputting that error, it does not affect function of cloned containers in anyway. I wonder if ignoring the error is fine...
