### ISSUE TITLE
Running application containers

### ISSUE THREAD

**Issue by coolavibv** [lxc/lxc#1182]
I want to set a virtual network using application containers. In the process I wrote config file, fstab, created rootfs and enabled cgroups. But when I execute application containers using "lxc-execute -n container_name -f ./config --ps -ef " the following command is shown.

lxc-execute: utils.c: safe_mount: 1692 No such file or directory - Failed to mount /usr/libexec onto /usr/local/lib/lxc/rootfs//usr/lib
lxc-execute: conf.c: mount_entry: 1650 No such file or directory - failed to mount '/usr/libexec' on '/usr/local/lib/lxc/rootfs//usr/lib'
lxc-execute: conf.c: lxc_setup: 3726 failed to setup the mounts for 'sairam9'
lxc-execute: start.c: do_start: 833 failed to setup the container
lxc-execute: sync.c: __sync_wait: 57 An error occurred in another process (expected sequence number 3)
lxc-execute: start.c: __lxc_start: 1353 failed to spawn 'sairam9'

I have created rootfs at given path in the error and tried but did not work. Can any body suggest a fix?
I am attaching config and fstab file.

![fstab](https://cloud.githubusercontent.com/assets/22145734/18432496/e75d67b6-78ff-11e6-98e5-ad66be8c105f.png)
![lxc config](https://cloud.githubusercontent.com/assets/22145734/18432501/f28263e4-78ff-11e6-9a57-51c47aac5a7b.png)

**Comment by brauner** [comment]
You should use relative paths for the target mount in your fstab, e.g.:

`/lib lib`

and you should add `create=dir` or `create=file` options when the target mountpoint or file does not exist:

`/usr/libexec usr/lib none ro,bind,create=dir 0 0`

so that it gets created automatically within the container.

**Comment by brauner** [comment]
If you don't experience any issues with this anymore, please don't forget to close the issue. :)

**Comment by coolavibv** [comment]
I sorted out the problem. The directory I wanted to mount did not exist, hence I commented that mount line. Here I needed init.lxc running inside lxc as PID 1. For that to happen I needed to mount that directory, which worked for me.
