### ISSUE TITLE
error starting container issue in a 3.8 kernel    

### ISSUE THREAD

**Issue by laithrafid** [lxc/lxc#1186]
this's the error 

lxc-create: symbol lookup error: lxc-create: undefined symbol: current_config

[root@dhcp-10-17-17-40 /]# lxc-checkconfig
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: enabled
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/local/bin/lxc-checkconfig

uname -a :
diablo.lan 3.18.35-g1d82046-

**Comment by brauner** [comment]
For a start, can you please specifiy which distro you're using, and what the version of all `LXC` related packages is? :)

**Comment by laithrafid** [comment]
Centos7 how to get the version of all lxc related packages , is there a script ?

**Comment by brauner** [comment]
If you have installed them it's best to use you package manager. There should be an option to list installed packages and their versions.

**Comment by laithrafid** [comment]
[root@dhcp-10-17-17-40 /]# yum deplist lxc
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.mirror.rafal.ca
 * epel: mirrors.cat.pdx.edu
 * extras: centos.mirror.rafal.ca
 * updates: centos.mirror.rafal.ca
package: lxc.x86_64 1.0.8-1.el7
  dependency: /bin/sh
   provider: bash.x86_64 4.2.46-20.el7_2
  dependency: /usr/bin/env
   provider: coreutils.x86_64 8.22-15.el7_2.1
  dependency: libc.so.6(GLIBC_2.8)(64bit)
   provider: glibc.x86_64 2.17-106.el7_2.8
  dependency: libcap.so.2()(64bit)
   provider: libcap.x86_64 2.22-8.el7
  dependency: liblxc.so.1()(64bit)
   provider: lxc-libs.x86_64 1.0.8-1.el7
  dependency: libpthread.so.0()(64bit)
   provider: glibc.x86_64 2.17-106.el7_2.8
  dependency: libpthread.so.0(GLIBC_2.2.5)(64bit)
   provider: glibc.x86_64 2.17-106.el7_2.8
  dependency: libseccomp.so.2()(64bit)
   provider: libseccomp.x86_64 2.2.1-1.el7
  dependency: libselinux.so.1()(64bit)
   provider: libselinux.x86_64 2.2.2-6.el7
  dependency: libutil.so.1()(64bit)
   provider: glibc.x86_64 2.17-106.el7_2.8
  dependency: lua-alt-getopt
   provider: lua-alt-getopt.noarch 0.7.0-4.el7
  dependency: lua-lxc(x86-64) = 1.0.8-1.el7
   provider: lua-lxc.x86_64 1.0.8-1.el7
  dependency: rtld(GNU_HASH)
   provider: glibc.x86_64 2.17-106.el7_2.8
   provider: glibc.i686 2.17-106.el7_2.8

**Comment by laithrafid** [comment]
[root@dhcp-10-17-17-40 /]# yum deplist lxc
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.mirror.rafal.ca
 * epel: mirrors.cat.pdx.edu
 * extras: centos.mirror.rafal.ca
 * updates: centos.mirror.rafal.ca
package: lxc.x86_64 1.0.8-1.el7
  dependency: /bin/sh
   provider: bash.x86_64 4.2.46-20.el7_2
  dependency: /usr/bin/env
   provider: coreutils.x86_64 8.22-15.el7_2.1
  dependency: libc.so.6(GLIBC_2.8)(64bit)
   provider: glibc.x86_64 2.17-106.el7_2.8
  dependency: libcap.so.2()(64bit)
   provider: libcap.x86_64 2.22-8.el7
  dependency: liblxc.so.1()(64bit)
   provider: lxc-libs.x86_64 1.0.8-1.el7
  dependency: libpthread.so.0()(64bit)
   provider: glibc.x86_64 2.17-106.el7_2.8
  dependency: libpthread.so.0(GLIBC_2.2.5)(64bit)
   provider: glibc.x86_64 2.17-106.el7_2.8
  dependency: libseccomp.so.2()(64bit)
   provider: libseccomp.x86_64 2.2.1-1.el7
  dependency: libselinux.so.1()(64bit)
   provider: libselinux.x86_64 2.2.2-6.el7
  dependency: libutil.so.1()(64bit)
   provider: glibc.x86_64 2.17-106.el7_2.8
  dependency: lua-alt-getopt
   provider: lua-alt-getopt.noarch 0.7.0-4.el7
  dependency: lua-lxc(x86-64) = 1.0.8-1.el7
   provider: lua-lxc.x86_64 1.0.8-1.el7
  dependency: rtld(GNU_HASH)
   provider: glibc.x86_64 2.17-106.el7_2.8
   provider: glibc.i686 2.17-106.el7_2.8

**Comment by brauner** [comment]
Can you paste the output of `lxc-start --version`, please?

**Comment by laithrafid** [comment]
[root@dhcp-10-17-17-40 /]# lxc-start --version
lxc-start: symbol lookup error: lxc-start: undefined symbol: current_config

**Comment by brauner** [comment]
Can you update your system? This looks like a version mismatch between the lxc tools and liblxc.

**Comment by laithrafid** [comment]
it's up to date

**Comment by laithrafid** [comment]
lxc-start 1473875830.199 ERROR    lxc_start_ui - lxc_start.c:main:341 - The container failed to start.
      lxc-start 1473875830.199 ERROR    lxc_start_ui - lxc_start.c:main:345 - Additional information can be obtained by setting the --logfile and --logpriority options.
      lxc-start 1473876437.525 ERROR    lxc_start - start.c:start:1182 - No such file or directory - failed to exec lxc-monitord
      lxc-start 1473876437.525 ERROR    lxc_sync - sync.c:__sync_wait:51 - invalid sequence number 1. expected 4
      lxc-start 1473876437.525 ERROR    lxc_start - start.c:__lxc_start:1100 - failed to spawn 'test'
      lxc-start 1473876437.526 ERROR    lxc_cgfs - cgfs.c:cgroup_rmdir:207 - Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/cpuset/lxc/test
      lxc-start 1473876437.526 ERROR    lxc_cgfs - cgfs.c:cgroup_rmdir:207 - Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory/lxc/test
      lxc-start 1473876437.526 ERROR    lxc_cgfs - cgfs.c:cgroup_rmdir:207 - Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/perf_event/lxc/test
      lxc-start 1473876437.526 ERROR    lxc_cgfs - cgfs.c:cgroup_rmdir:207 - Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/cpu,cpuacct/lxc/test
      lxc-start 1473876437.526 ERROR    lxc_cgfs - cgfs.c:cgroup_rmdir:207 - Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/freezer/lxc/test
      lxc-start 1473876437.526 ERROR    lxc_cgfs - cgfs.c:cgroup_rmdir:207 - Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/devices/lxc/test
      lxc-start 1473876437.526 ERROR    lxc_cgfs - cgfs.c:cgroup_rmdir:207 - Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/blkio/lxc/test
      lxc-start 1473876437.526 ERROR    lxc_cgfs - cgfs.c:cgroup_rmdir:207 - Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/net_cls,net_prio/lxc/test
      lxc-start 1473876437.526 ERROR    lxc_start_ui - lxc_start.c:main:341 - The container failed to start.
      lxc-start 1473876437.527 ERROR    lxc_start_ui - lxc_start.c:main:345 - Additional information can be obtained by setting the --logfile and --logpriority options.
      lxc-start 1473876466.354 INFO     lxc_start_ui - lxc_start.c:main:264 - using rcfile /var/lib/lxc/test/config
      lxc-start 1473876466.355 WARN     lxc_log - log.c:lxc_log_init:316 - lxc_log_init called with log already initialized
      lxc-start 1473876466.355 WARN     lxc_cgfs - cgfs.c:lxc_cgroup_get_container_info:1100 - Not attaching to cgroup net_cls unknown to /var/lib/lxc test
      lxc-start 1473876466.355 WARN     lxc_cgfs - cgfs.c:lxc_cgroup_get_container_info:1100 - Not attaching to cgroup blkio unknown to /var/lib/lxc test
      lxc-start 1473876466.355 WARN     lxc_cgfs - cgfs.c:lxc_cgroup_get_container_info:1100 - Not attaching to cgroup devices unknown to /var/lib/lxc test
      lxc-start 1473876466.355 WARN     lxc_cgfs - cgfs.c:lxc_cgroup_get_container_info:1100 - Not attaching to cgroup freezer unknown to /var/lib/lxc test
      lxc-start 1473876466.356 WARN     lxc_cgfs - cgfs.c:lxc_cgroup_get_container_info:1100 - Not attaching to cgroup cpu unknown to /var/lib/lxc test
      lxc-start 1473876466.356 WARN     lxc_cgfs - cgfs.c:lxc_cgroup_get_container_info:1100 - Not attaching to cgroup perf_event unknown to /var/lib/lxc test
      lxc-start 1473876466.356 WARN     lxc_cgfs - cgfs.c:lxc_cgroup_get_container_info:1100 - Not attaching to cgroup memory unknown to /var/lib/lxc test
      lxc-start 1473876466.356 WARN     lxc_cgfs - cgfs.c:lxc_cgroup_get_container_info:1100 - Not attaching to cgroup cpuset unknown to /var/lib/lxc test
      lxc-start 1473876466.356 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver SELinux
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:324 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:426 - Adding native rule for reject_force_umount action 0
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:429 - Adding compat rule for reject_force_umount action 0
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:324 - processing: .[all].
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:324 - processing: .kexec_load errno 1.
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:426 - Adding native rule for kexec_load action 327681
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:429 - Adding compat rule for kexec_load action 327681
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:324 - processing: .open_by_handle_at errno 1.
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:426 - Adding native rule for open_by_handle_at action 327681
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:429 - Adding compat rule for open_by_handle_at action 327681
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:324 - processing: .init_module errno 1.
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:426 - Adding native rule for init_module action 327681
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:429 - Adding compat rule for init_module action 327681
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:324 - processing: .finit_module errno 1.
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:426 - Adding native rule for finit_module action 327681
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:429 - Adding compat rule for finit_module action 327681
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:324 - processing: .delete_module errno 1.
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:426 - Adding native rule for delete_module action 327681
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:429 - Adding compat rule for delete_module action 327681
      lxc-start 1473876466.356 INFO     lxc_seccomp - seccomp.c:parse_config_v2:436 - Merging in the compat seccomp ctx into the main one
      lxc-start 1473876466.356 DEBUG    lxc_conf - conf.c:lxc_create_tty:3791 - allocated pty '/dev/pts/0' (5/6)
      lxc-start 1473876466.356 DEBUG    lxc_conf - conf.c:lxc_create_tty:3791 - allocated pty '/dev/pts/3' (7/8)
      lxc-start 1473876466.356 DEBUG    lxc_conf - conf.c:lxc_create_tty:3791 - allocated pty '/dev/pts/7' (9/10)
      lxc-start 1473876466.356 DEBUG    lxc_conf - conf.c:lxc_create_tty:3791 - allocated pty '/dev/pts/8' (11/12)
      lxc-start 1473876466.356 INFO     lxc_conf - conf.c:lxc_create_tty:3802 - tty's configured
      lxc-start 1473876466.356 DEBUG    lxc_start - start.c:setup_signal_fd:249 - sigchild handler set
      lxc-start 1473876466.356 DEBUG    lxc_console - console.c:lxc_console_peer_default:500 - opening /dev/tty for console peer
      lxc-start 1473876466.356 DEBUG    lxc_console - console.c:lxc_console_peer_default:506 - using '/dev/tty' as console
      lxc-start 1473876466.356 DEBUG    lxc_console - console.c:lxc_console_sigwinch_init:179 - 6298 got SIGWINCH fd 17
      lxc-start 1473876466.356 DEBUG    lxc_console - console.c:lxc_console_winsz:88 - set winsz dstfd:14 cols:164 rows:24
      lxc-start 1473876466.356 INFO     lxc_start - start.c:lxc_init:449 - 'test' is initialized
      lxc-start 1473876466.357 DEBUG    lxc_start - start.c:__lxc_start:1073 - Dropping cap_sys_boot
      lxc-start 1473876466.359 DEBUG    lxc_conf - conf.c:instantiate_veth:3130 - instantiated veth 'veth0G1F5A/vethR7TGOI', index is '23'
      lxc-start 1473876466.359 INFO     lxc_cgroup - cgroup.c:cgroup_init:62 - cgroup driver cgroupfs initing for test
      lxc-start 1473876466.364 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.deny' set to 'a'
      lxc-start 1473876466.364 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c *:* m'
      lxc-start 1473876466.364 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'b *:* m'
      lxc-start 1473876466.364 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:3 rwm'

**Comment by laithrafid** [comment]
lxc-start 1473876466.364 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'b *:* m'
      lxc-start 1473876466.364 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:3 rwm'
      lxc-start 1473876466.364 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:5 rwm'
      lxc-start 1473876466.364 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:7 rwm'
      lxc-start 1473876466.364 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 5:0 rwm'
      lxc-start 1473876466.364 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:8 rwm'
      lxc-start 1473876466.364 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:9 rwm'
      lxc-start 1473876466.364 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 136:* rwm'
      lxc-start 1473876466.364 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 5:2 rwm'
      lxc-start 1473876466.364 INFO     lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1926 - cgroup has been setup
      lxc-start 1473876466.381 DEBUG    lxc_conf - conf.c:lxc_assign_network:3547 - move '(null)' to '6306'
      lxc-start 1473876466.381 DEBUG    lxc_start - start.c:do_start:697 - Dropped cap_sys_boot
      lxc-start 1473876466.384 DEBUG    lxc_conf - conf.c:setup_rootfs:1625 - mounted '/var/lib/lxc/test/rootfs' on '/usr/lib64/lxc/rootfs'
      lxc-start 1473876466.384 INFO     lxc_conf - conf.c:setup_utsname:912 - 'test.diablo.lan' hostname has been setup
      lxc-start 1473876466.399 DEBUG    lxc_conf - conf.c:setup_hw_addr:2682 - mac address 'fe:00:42:0e:5f:fe' on 'eth0' has been setup
      lxc-start 1473876466.399 DEBUG    lxc_conf - conf.c:setup_netdev:2909 - 'eth0' has been setup
      lxc-start 1473876466.399 INFO     lxc_conf - conf.c:setup_network:2930 - network has been setup
      lxc-start 1473876466.399 INFO     lxc_conf - conf.c:mount_autodev:1432 - Mounting container /dev
      lxc-start 1473876466.399 DEBUG    lxc_conf - conf.c:mount_check_fs:1264 - entering mount_check_fs for /dev
      lxc-start 1473876466.400 DEBUG    lxc_conf - conf.c:mount_check_fs:1306 - mount_check_fs returning 1 last devtmpfs
      lxc-start 1473876466.400 DEBUG    lxc_conf - conf.c:mount_autodev:1458 - Bind mounting /dev/.lxc/test.13de0fe6c1e2ecda to /usr/lib64/lxc/rootfs/dev
      lxc-start 1473876466.400 INFO     lxc_conf - conf.c:mount_autodev:1490 - Mounted container /dev
      lxc-start 1473876466.400 INFO     lxc_conf - conf.c:setup_autodev:1518 - Creating initial consoles under container /dev
      lxc-start 1473876466.400 INFO     lxc_conf - conf.c:setup_autodev:1526 - Populating container /dev
      lxc-start 1473876466.400 INFO     lxc_conf - conf.c:setup_autodev:1541 - Populated container /dev
      lxc-start 1473876466.400 INFO     lxc_conf - conf.c:setup_ttydir_console:1869 - created /usr/lib64/lxc/rootfs/dev/lxc
      lxc-start 1473876466.401 INFO     lxc_conf - conf.c:setup_ttydir_console:1915 - console has been setup on lxc/console
      lxc-start 1473876466.401 INFO     lxc_conf - conf.c:setup_tty:1041 - 4 tty(s) has been setup
      lxc-start 1473876466.401 INFO     lxc_conf - conf.c:do_tmp_proc_mount:4095 - I am 6306, /proc/self points to '6306'
      lxc-start 1473876466.411 INFO     lxc_conf - conf.c:do_tmp_proc_mount:4111 - Mounted /proc in container for security transition
      lxc-start 1473876466.411 DEBUG    lxc_conf - conf.c:setup_rootfs_pivot_root:1211 - created '/usr/lib64/lxc/rootfs/lxc_putold' directory
      lxc-start 1473876466.411 DEBUG    lxc_conf - conf.c:setup_rootfs_pivot_root:1214 - mountpoint for old rootfs is '/usr/lib64/lxc/rootfs/lxc_putold'
      lxc-start 1473876466.411 DEBUG    lxc_conf - conf.c:setup_rootfs_pivot_root:1227 - pivot_root syscall to '/usr/lib64/lxc/rootfs' successful
      lxc-start 1473876466.417 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/dev/shm'
      lxc-start 1473876466.423 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/dev/pts'
      lxc-start 1473876466.429 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/dev/mqueue'
      lxc-start 1473876466.435 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/proc/sys/fs/binfmt_misc'
      lxc-start 1473876466.441 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/proc/fs/nfsd'
      lxc-start 1473876466.447 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/kernel/security'
      lxc-start 1473876466.453 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/fs/cgroup/systemd'
      lxc-start 1473876466.459 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/fs/cgroup/net_cls,net_prio'
      lxc-start 1473876466.468 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/fs/cgroup/blkio'
      lxc-start 1473876466.474 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/fs/cgroup/devices'
      lxc-start 1473876466.480 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/fs/cgroup/freezer'
      lxc-start 1473876466.486 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/fs/cgroup/cpu,cpuacct'
      lxc-start 1473876466.492 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/fs/cgroup/perf_event'
      lxc-start 1473876466.498 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/fs/cgroup/memory'
      lxc-start 1473876466.504 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/fs/cgroup/cpuset'
      lxc-start 1473876466.510 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/fs/pstore'
      lxc-start 1473876466.516 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/kernel/config'
      lxc-start 1473876466.522 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/fs/selinux'
      lxc-start 1473876466.528 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/kernel/debug'
      lxc-start 1473876466.534 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/fs/fuse/connections'
      lxc-start 1473876466.540 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/run/user/0/gvfs'
      lxc-start 1473876466.546 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/var/lib/nfs/rpc_pipefs'
      lxc-start 1473876466.552 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/home'
      lxc-start 1473876466.558 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/boot'
      lxc-start 1473876466.564 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/dev'
      lxc-start 1473876466.570 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/proc'
      lxc-start 1473876466.576 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys/fs/cgroup'
      lxc-start 1473876466.585 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/run/user/0'
      lxc-start 1473876466.594 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/sys'
      lxc-start 1473876466.600 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold/run'
      lxc-start 1473876466.606 DEBUG    lxc_conf - conf.c:umount_oldrootfs:1150 - umounted '/lxc_putold'
      lxc-start 1473876466.606 INFO     lxc_conf - conf.c:setup_personality:1803 - set personality to '0x0'
      lxc-start 1473876466.606 DEBUG    lxc_conf - conf.c:setup_caps:2596 - drop capability 'mac_admin' (33)
      lxc-start 1473876466.606 DEBUG    lxc_conf - conf.c:setup_caps:2596 - drop capability 'mac_override' (32)
      lxc-start 1473876466.606 DEBUG    lxc_conf - conf.c:setup_caps:2596 - drop capability 'setfcap' (31)

**Comment by laithrafid** [comment]
lxc-start 1473876466.606 DEBUG    lxc_conf - conf.c:setup_caps:2596 - drop capability 'mac_override' (32)
      lxc-start 1473876466.606 DEBUG    lxc_conf - conf.c:setup_caps:2596 - drop capability 'setfcap' (31)
      lxc-start 1473876466.606 DEBUG    lxc_conf - conf.c:setup_caps:2596 - drop capability 'sys_module' (16)
      lxc-start 1473876466.606 DEBUG    lxc_conf - conf.c:setup_caps:2596 - drop capability 'sys_nice' (23)
      lxc-start 1473876466.606 DEBUG    lxc_conf - conf.c:setup_caps:2596 - drop capability 'sys_pacct' (20)
      lxc-start 1473876466.606 DEBUG    lxc_conf - conf.c:setup_caps:2596 - drop capability 'sys_rawio' (17)
      lxc-start 1473876466.606 DEBUG    lxc_conf - conf.c:setup_caps:2596 - drop capability 'sys_time' (25)
      lxc-start 1473876466.606 DEBUG    lxc_conf - conf.c:setup_caps:2605 - capabilities have been setup
      lxc-start 1473876466.606 NOTICE   lxc_conf - conf.c:lxc_setup:4370 - 'test' is setup.
      lxc-start 1473876466.606 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.deny' set to 'a'
      lxc-start 1473876466.606 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c *:* m'
      lxc-start 1473876466.606 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'b *:* m'
      lxc-start 1473876466.606 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:3 rwm'
      lxc-start 1473876466.606 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:5 rwm'
      lxc-start 1473876466.606 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:7 rwm'
      lxc-start 1473876466.606 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 5:0 rwm'
      lxc-start 1473876466.606 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:8 rwm'
      lxc-start 1473876466.606 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:9 rwm'
      lxc-start 1473876466.606 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 136:* rwm'
      lxc-start 1473876466.606 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 5:2 rwm'
      lxc-start 1473876466.606 INFO     lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1926 - cgroup has been setup
      lxc-start 1473876466.621 NOTICE   lxc_start - start.c:start:1179 - exec'ing '/sbin/init'
      lxc-start 1473876466.621 NOTICE   lxc_start - start.c:post_start:1190 - '/sbin/init' started with pid '6306'
      lxc-start 1473876466.622 DEBUG    lxc_utmp - lxcutmp.c:lxc_utmp_mainloop_add:383 - Added '/proc/6306/root/run' to inotifywatch
      lxc-start 1473876466.622 WARN     lxc_start - start.c:signal_handler:297 - invalid pid for SIGCHLD
      lxc-start 1473876466.624 DEBUG    lxc_start - start.c:signal_handler:301 - container init process exited
      lxc-start 1473876466.624 DEBUG    lxc_start - start.c:__lxc_start:1143 - Pushing physical nics back to host namespace
      lxc-start 1473876466.624 DEBUG    lxc_start - start.c:__lxc_start:1146 - Tearing down virtual network devices used by container
      lxc-start 1473876466.625 WARN     lxc_conf - conf.c:lxc_delete_network:3423 - failed to remove interface '(null)'
      lxc-start 1473876466.625 INFO     lxc_error - error.c:lxc_error_set_and_log:49 - child <6306> ended on error (1)
      lxc-start 1473876466.625 WARN     lxc_conf - conf.c:lxc_delete_network:3423 - failed to remove interface '(null)'
      lxc-start 1473876466.651 INFO     lxc_conf - conf.c:lxc_delete_autodev:1595 - Cleaning /dev/.lxc/test.13de0fe6c1e2ecda
      lxc-start 1473876466.652 ERROR    lxc_start_ui - lxc_start.c:main:341 - The container failed to start.

**Comment by brauner** [comment]
Ok, but what did you do to get it to work and avoid the `lxc-create: symbol lookup error: lxc-create: undefined symbol: current_config` error?

**Comment by laithrafid** [comment]
sudo

**Comment by laithrafid** [comment]
now facing this error 
lxc-start: lxc_start.c: main: 341 The container failed to start.

**Comment by boshido** [comment]
I faced the same problem when I used lxc version 1.1.5 
But the problem disappeared when I installed the latest version (2.x.x)

**Comment by brauner** [comment]
`LXC 1.*.*` is deprecated so you should always try to use a current `LXC 2.*.*`. Haven't heard back from that issue in a while so closing.

**Comment by vcargats** [comment]
Just for anyone who will stuck w/ the same issue. For me it was the collision of versions. The installed by debian apt was lxc 1 and manually compiled was 3. So after running ldd on new executable it was obvious that it tried to load old lib. So either LD_LIBRARY_PATH or removing the debian apt one helped.
