### ISSUE TITLE
LVM create error

### ISSUE THREAD

**Issue by dmitrygribenchuk** [lxc/lxc#1188]
Hi everyone! I'm start to use LXC version 1.1.5 on Debian Jessie.
  Sometimes when I create a container I recieve an error:

  lxc-create -n test -t vps --bdev=lvm --lvname=test --vgname=vg
  --fstype=xfs --fssize=8G -- --release=jessie --clean

  File descriptor 3 (/var/lib/lxc/test/partial) leaked on lvcreate invocation. Parent PID 1089: lxc-create
    Logical volume "test" created
  lxc-create: bdev/lxclvm.c: lvm_create: 411 Error creating filesystem type xfs on /dev/vg/test
  lxc-create: lxccontainer.c: do_bdev_create: 1035 Failed to create backing store type lvm
  lxc-create: lxccontainer.c: do_lxcapi_create: 1511 Error creating backing store type lvm for test
  lxc-create: tools/lxc_create.c: main: 318 Error creating container test

  Recently I'm upgrade LXC to 2.0.4, but the error remains.

**Comment by brauner** [comment]
Are `xfsprogs` installed? If not, please do so and try again.

**Comment by dmitrygribenchuk** [comment]
Yes, xfsprogs v. 3.2.1

**Comment by dmitrygribenchuk** [comment]
Anybody can help with this issue?

**Comment by dmitrygribenchuk** [comment]
I found same issue https://bugzilla.opensuse.org/show_bug.cgi?id=919681
But with btrfs and ext4

**Comment by brauner** [comment]
@dmitrygribenchuk, `LXC 1.1.*` is deprecated. Please update to `LXC 2.*.*`. If the problem still persists, please leave a comment and I'll re-open the issue. :)

**Comment by dmitrygribenchuk** [comment]
In version 2.0.4 error present

**Comment by dmitrygribenchuk** [comment]
In version 2.0.5 error present

**Comment by brauner** [comment]
So this works flawlessly for me:

```
chb@conventiont|~
> sudo lxc-create -n test3 -t ubuntu --bdev=lvm --lvname=test2 --vgname=test --fstype=xfs --fssize=1G
WARNING: ext4 signature detected on /dev/test/test2 at offset 1080. Wipe it? [y/n]: y
  Wiping ext4 signature on /dev/test/test2.
  Logical volume "test2" created.
Checking cache download in /var/cache/lxc/zesty/rootfs-amd64 ...
Copy /var/cache/lxc/zesty/rootfs-amd64 to /usr/lib/x86_64-linux-gnu/lxc ...
Copying rootfs to /usr/lib/x86_64-linux-gnu/lxc ...
Generating locales (this might take a while)...
  en_IE.UTF-8... done
Generation complete.
Creating SSH2 RSA key; this may take some time ...
2048 SHA256:3MZtDPhkFhsmCe6j44bPlHTTW+L0ScQidDiVKuf9WG0 root@conventiont (RSA)
Creating SSH2 ECDSA key; this may take some time ...
256 SHA256:ZPlFu48PGMBs9xwtV75UDnP2ZORhL7llsw7OtmURyXI root@conventiont (ECDSA)
Creating SSH2 ED25519 key; this may take some time ...
256 SHA256:tdlFLE5GShyRCeS8HupL8PsjSI5FzEvXK7jFoZjABMk root@conventiont (ED25519)
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.

Current default time zone: 'Etc/UTC'
Local time is now:      Wed Feb  1 21:58:56 UTC 2017.
Universal Time is now:  Wed Feb  1 21:58:56 UTC 2017.


##
# The default user is 'ubuntu' with password 'ubuntu'!
# Use the 'sudo' command to run tasks as root in the container.
##
```

So what is `t vps` is this your private template? And could you please append all logs run the container command with `-l debug -o container.log` and append the log file?

**Comment by dmitrygribenchuk** [comment]
Yes, we are use private template. In attachment debug info (level: trace) for start container
[lxc.log.txt](https://github.com/lxc/lxc/files/747392/lxc.log.txt)

**Comment by brauner** [comment]
The log you appended shows that the container started and that the `xfs` filesystem must have been created correctly:

```
      lxc-start 1486029681.334 DEBUG    bdev - bdev.c:find_fstype_cb:156 - trying to mount '/dev/vg_data/vps886'->'/usr/lib/x86_64-linux-gnu/lxc/rootfs' with fstype 'xfs'
      lxc-start 1486029681.457 INFO     bdev - bdev.c:find_fstype_cb:172 - mounted '/dev/vg_data/vps886' on '/usr/lib/x86_64-linux-gnu/lxc/rootfs', with fstype 'xfs'
      lxc-start 1486029681.457 DEBUG    lxc_conf - conf.c:setup_rootfs:1295 - mounted '/dev/vg_data/vps886' on '/usr/lib/x86_64-linux-gnu/lxc/rootfs'
```

**Comment by dmitrygribenchuk** [comment]
Its log from successful created container.
This logs for normal creating container and failed.
[lxc.normal.log.txt](https://github.com/lxc/lxc/files/747509/lxc.normal.log.txt)
[lxc.error.log.txt](https://github.com/lxc/lxc/files/747508/lxc.error.log.txt)

**Comment by brauner** [comment]
@dmitrygribenchuk is there an active filesystem on `/dev/vg_data/test4` at the time `mkfs.xfs` is called? If so this might explain the failure since it should refuse to simply create a new filesystem without the `-f` flag.

**Comment by dmitrygribenchuk** [comment]
test4 created when I call lxc-create.
I'm try to mount logical volume test4 and
root@ws# mount /dev/vg_data/test4 /mnt/
mount: unknown filesystem type 'xfs_external_log'

**Comment by brauner** [comment]
Hm, it could be that when the logical volume is created it doesn't show up fast enough so `mkfs.xfs` fails since the lv is not yet available. One solution is to wrap the `execlp()` and retry a couple of times until a given timeout is reached.

**Comment by dmitrygribenchuk** [comment]
Where I can do this?

**Comment by dmitrygribenchuk** [comment]
I'm assembled lxc from source codes and add sleep for 1,3,5,10,30 seconds before call function of creating fs. And it's doesn't work.

**Comment by dmitrygribenchuk** [comment]
I'm found one strange things. I wrote a small script to run lxc-create with params and run it about 50 times after a few seconds to cteate testvps_1, testvps_2, etc. And I see: Create ok, create ok, create fail, create ok, create ok, create fail. When I destroy all lxc and started re-creating and the numbers of the failed creatures were repeated. I check it twise. And after reboot too.

**Comment by dmitrygribenchuk** [comment]
I'm added -f flag to mkfs and all ok, thanks.

**Comment by brauner** [comment]
So there was an active filesystem present. :) Good to hear, closing this.

**Comment by dmitrygribenchuk** [comment]
How can there be an active file system on the newly created lvm?

**Comment by brauner** [comment]
If `mkfs.xfs` works with the `-f` flag and the `-f` flag is documented as:

> -f     Force overwrite when an existing filesystem is detected on the device.  By default, mkfs.xfs will not write to the device if it suspects that there  is a filesystem or partition table on the device already.
