### ISSUE TITLE
Unncessary bdev_init actions on container launch

### ISSUE THREAD

**Issue by DeHackEd** [lxc/lxc#119]
Would it be possible to reduce the actions performed by `bdev_init` on container start?

Specifically I run ZFS on Linux. On launch lxc-start invokes "zfs list" which can actually be a pretty long/slow operation since it needs to read metadata from all datasets of which there can be a lot.

I can't speak for other bdev drivers but with the way ZFS is set up by default by lxc-create there isn't anything to be done for mounting beyond any bind operations. It strikes me as being wasteful.

**Comment by brauner** [comment]
This can be closed. If one wants to avoid the hit of `zfs list` it is as simple as prefixing `lxc.rootfs.path = zfs:<dataset-name>` at which point lxc will not call `zfs list` anymore.
