### ISSUE TITLE
Confused about accessing /dev

### ISSUE THREAD

**Issue by liushuo0826** [lxc/lxc#1190]
I have a problem:
When I use "lxc-start -f config.txt -n vm1 /test_dev"  the test_dev will access the $LXC_ROOTFS/dev/.  But when I use "lxc-start -f config.txt -n vm1 /init" to fork the test_dev, it will access the dev directory from host. Is that true and why?
Thank you!

**Comment by brauner** [comment]
I'm not following. Can you expand a little, please.

**Comment by liushuo0826** [comment]
OK, I have a container named vm1, it has  its own $rootfs.
On the host there are tow misc device file named /dev/test and /dev/test1.
I mount the /dev/test1 with "-o bind" to $rootfs/dev/test, but the sub-process in the vm1 still access the /dev/test on the host while not the one $rootfs/dev/test binded.

Is that clear?

**Comment by liushuo0826** [comment]
Oh, the init on the container remounts the rootfs/dev/ to /dev/ again.
Thank you!
