### ISSUE TITLE
create container on sub-directory

### ISSUE THREAD

**Issue by Obarun** [lxc/lxc#1191]
version of lxc used=lxc-1:2.0.4-2
hello,
i use lxc to build some versionning package onto a container. If i try to create some container like this : 
`lxc-create -n accountsservice -t /path_of_the_template`
all works fine.
But if i try something like this : 
`lxc-create -n accountsservice/0.6.42-1 -t /path_of_the_template` 
i get this error 

> lxc-create: lxccontainer.c: do_create_container_dir: 972 No such file or directory - failed to create container path /var/lib/lxc/accountsservice/0.6.42-1

So, if i  hack the file lxccontainer.c at line 964 by 
`ret = mkdir_p(path, 0770);`
instead of
`ret = mkdir(path, 0770);`
and the line 3122 by
`if (mkdir_p(newpath, 0755) < 0) {`
instead of 
`if (mkdir(newpath, 0755) < 0) {`
i do not have this previous error anymore.

But now i have this new error : 
> lxc-create: lxclock.c: lxclock: 231 Error opening /run/lxc/lock//var/lib/lxc/.accountsservice/0.6.42-1

If i create manualy the file /run/lxc/lock/var/lib/lxc/.accountsservice/0.6.42-1/0.6.42-1, the container is builded successfully.
So now if i try something like this : `lxc-start -n accountsservice/0.6.42-1` all works fine.
But if i try `lxc-ls`, obviously this command do not list the container accountsservice/0.6.42-1.

Certainly, i do something wrong or i make it with a wrong way. Can you explain me how i can create container on sub directory? If i need to create a patch which files i need to change and how?

Thanks for your help

**Comment by brauner** [comment]
You're giving the container a path `accountsservice/0.6.42-1`. Please use a name without a slash in it. :)

**Comment by Obarun** [comment]
ho yes i can, but having multiple version in /var/lib/lxc/accountsservice-0.6.42-1,accountsservice-0.6.42-2,..} and /var/lib/lxc/accountsservice/{0.6.42-1,0.6.42-2,...} are not the same. The second manner is better for classified and see quickly the different version. Apparently is not possible, so i will try to find a workaround.
Thanks for your reply
