### ISSUE TITLE
lxc.mount Unix sockets for DBus

### ISSUE THREAD

**Issue by oxwivi** [lxc/lxc#1198]
I'm trying to connect container's app to host system's DBus. For that, I figured I'd need to mount host DBus socket in the container, then set host's `DBUS_SESSION_BUS_ADDRESS` as an environment variable in the container before running the app.

But, how exactly do I mount an Unix socket? Manpages haven't been of help. Or is it not possible at all?

**Comment by brauner** [comment]
This should be as simple as:

```
lxc.mount.entry=/tmp/.X11-unix/X0 tmp/.X11-unix/X0 none bind,optional,create=file
```
The above line bind-mounts the unix socket for your `xserver` into the container. Note however, that if you're using unprivileged containers that in order to use the socket, you need to give your container user permissions to do so (e.g. `ACL` permissions).

**Comment by oxwivi** [comment]
`DBUS_SESSION_BUS_ADDRESS` points to an abstract socket, for example: `unix:abstract=/tmp/dbus-X01BP87fpK`. How do I mount that?

At the same time, I read that abstract sockets are not namespaced. Is that true? How can I confirm.

**Comment by brauner** [comment]
I'm not sure this will work easily. First of all, afaik, abstract unix domain sockets are bound to network namespaces. So your container will probably have to share the network namespace of the host, then the abstract unix socket should be accessible. Second, afaik, mounts require proper VFS (virtual-filesystem) objects which abstract unix domain sockets are not. In short, I'm not sure if it is possible and if it is, it might be tricky. :)

**Comment by stgraber** [comment]
@brauner is correct, abstract unix sockets are tied to a network namespace so you won't be able to connect from inside a container, and since they aren't filesystem objects, they can't be bind-mounted.

Your only real option is to either configure dbus to use a normal unix socket (which it definitely supports), or use a small proxy which forwards an abstract unix socket to a regular unix socket (socat lets you do that for example).

**Comment by oxwivi** [comment]
@stgraber, thanks for the input. I changed the socket address in `/usr/share/upstart/sessions/dbus.conf` to `unix:path=/tmp/dbus`, and running LXC apps with the correct socket address works... with its own individual quirks:
 1. Google Chrome's appmenu integrates perfectly
 2. Firefox's appmenu don't show at all
 3. Eclipse, the reason why I wanted to do it in first place to save horizontal space in all its clutter, doesn't show the menu in either the global indicator or in the titlebar

I'm also curious why Upstart session files still works with systemd, but neither are related to LXC, so I'll rest my case here.

Thanks for the guide and all the help both of you have provided on GitHub.
