### ISSUE TITLE
regression in lxc-attach -s USER

### ISSUE THREAD

**Issue by overlayfs** [lxc/lxc#1199]
`lxc-attach -n trusty -s USER -- bash
`
fails with error message,

> lxc-attach: trusty: seccomp.c: lxc_seccomp_load: 751 Error loading the seccomp policy.
> lxc-attach: trusty: attach.c: attach_child_main: 1217 Loading seccomp policy

**Using the lxc-daily ppa:**  
- version 2.0.4+master~20160914-1732-0ubuntu1~trusty is good.
-  version 2.0.4+master~20160920-0955-0ubuntu1~trusty is bad.

**Details**:
- lxc version:  lxc-daily ppa
- container: unprivileged ubuntu-14.04 
- host: fresh install of ubuntu-14.04 in a virtual machine.  kernel 4.4.

**Comment by brauner** [comment]
I'm bisecting this.

**Comment by overlayfs** [comment]
Thank you Christian!

**Comment by brauner** [comment]
Did you test it? :)

**Comment by brauner** [comment]
(I did, but the more the merrier. :))
