### ISSUE TITLE
Unprvileged container: lxc-start not working if cpu-related cgroups are set

### ISSUE THREAD

**Issue by hinhthoi** [lxc/lxc#1205]
For privileged container, i can set the value for `lxc.cgroup.memory.limit_in_bytes` and `lxc.cgroup.cpuset.cpus` in the config file.

For unprivileged containers (containers created by a regular user, without sudo capability), `lxc-start` is not working if `lxc.cgroup.cpuset.cpus` or `lxc.cgroup.cpu.shares` are set

Error message: `lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1651 - No such file or directory - Error setting cpu.shares to 256 for ubuntu1404`
`lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1651 - No such file or directory - Error setting cpuset.cpus to 1 for ubuntu1404`

To install the unprivileged container, i login to regular user shell, and use the following command
`lxc-create -t download -n centos7 -- -d centos -r 7 -a amd64`

So, i really appreciate if anyone could help me point out what i'm doing wrongly. I want to restrict cpu limit for unprivileged container.

My second related question is: I see the cgroups files for privileged container in `/sys/fs/cgroup`, but for unprivileged container, i can't find the location for cgroup.

I'm using ubuntu 16.04 as the host OS

**Comment by brauner** [comment]
This is likely caused by your user not being placed in a writeable cgroup for the `cpuset` and `cpu` controller. Per default `libpam_cgfs`, the pam module shipped with `LXCFS`, will only place you in a writeable cgroup for the `freezer` and `memory` controller. To verify you can paste the output of:

```
cat /proc/self/cgroup
```

here. If you want `cpuset` and `cpu` to be writeable you can append the missing `cpuset` and `cpu` controllers to this line:

```
session	optional	pam_cgfs.so -c freezer,memory,name=systemd
```

in `/etc/pam.d/common-session` and `/etc/pam.d/common-session-noninteractive` or manually create writeable cgroups for your unprivileged user and move your current shell into it.

**Comment by hinhthoi** [comment]
Hi brauner,

Thank you very much for your help, here is the additional information

`root@dedi1:~# cat /proc/self/cgroup
11:blkio:/user.slice/user-0.slice/session-7100.scope
10:memory:/user/root/0
9:freezer:/user/root/0
8:pids:/user.slice/user-0.slice/session-7100.scope
7:cpu,cpuacct:/user.slice/user-0.slice/session-7100.scope
6:devices:/user.slice/user-0.slice/session-7100.scope
5:perf_event:/
4:hugetlb:/
3:net_cls,net_prio:/
2:cpuset:/
1:name=systemd:/user.slice/user-0.slice/session-7100.scope
`

After appending `cpuset` and `cpu` into the line of those 2 files, adding `lxc.cgroup.cpuset.cpus = 1` to the `config` file, and restarting lxc, i cannot start the container, a lot of permission problems in the log file

`lxcuser@dedi1:~/.local/share/lxc/centos72$ cat log.log
      lxc-start 20160925133407.420 ERROR    lxc_cgfs - cgroups/cgfs.c:lxc_cgroupfs_create:897 - Could not set clone_children to 1 for cpuset hierarchy in parent cgroup.
      lxc-start 20160925133407.421 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/blkio/user.slice/user-1000.slice
      lxc-start 20160925133407.421 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory//lxc/1022
      lxc-start 20160925133407.421 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory//lxc/test-container
      lxc-start 20160925133407.422 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory//lxc
      lxc-start 20160925133407.422 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory//user/root/1
      lxc-start 20160925133407.422 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory//user/root/5
      lxc-start 20160925133407.423 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory//user/root/6
      lxc-start 20160925133407.423 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory//user/root
      lxc-start 20160925133407.423 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory//user/lxcuser/2
      lxc-start 20160925133407.424 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory//user/lxcuser/3/lxc/centos6
      lxc-start 20160925133407.424 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory//user/lxcuser/3/lxc
      lxc-start 20160925133407.424 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory//user/lxcuser/3
      lxc-start 20160925133407.424 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory//user/lxcuser

...`

Maybe there are additional step to make it work.

**Comment by brauner** [comment]
You need to log out and log in again.

**Comment by hinhthoi** [comment]
I have tried multiple times of loging out and relogging in, but the error is still the same. I also restart lxc service, but it doesn't help.

**Comment by hinhthoi** [comment]
Also, when i added `cpuset` and `cpu` to the 2 files, i logged out and logged in, then it doesn't even start another test container that doesn't have `lxc.cgroup.cpuset.cpus=1` in the `config` file.

My kernel is `4.4.0-38-generic`

**Comment by brauner** [comment]
Can you show `cat /proc/self/cgroup` after the changes again, please?

**Comment by brauner** [comment]
And please also show your `LXC` version and the config file for the container.

**Comment by hinhthoi** [comment]
Here is the detail
`root@dedi1:~# cat /proc/self/cgroup

11:blkio:/user.slice/user-0.slice/session-7478.scope

10:memory:/

9:freezer:/

8:pids:/user.slice/user-0.slice/session-7478.scope

7:cpu,cpuacct:/

6:devices:/user.slice/user-0.slice/session-7478.scope

5:perf_event:/

4:hugetlb:/

3:net_cls,net_prio:/

2:cpuset:/

1:name=systemd:/user.slice/user-0.slice/session-7478.scope
`
LXC version: 2.0.4-0ubuntu1~ubuntu16.04.2

config file
`lxcuser@dedi1:~$ cat /home/lxcuser/.local/share/lxc/centos75/config
# Template used to create this container: /usr/share/lxc/templates/lxc-download
# Parameters passed to the template: -d centos -r 7 -a amd64
# For additional config options, please look at lxc.container.conf(5)

# Uncomment the following line to support nesting containers:
#lxc.include = /usr/share/lxc/config/nesting.conf
# (Be aware this has security implications)


# Distribution configuration
lxc.include = /usr/share/lxc/config/centos.common.conf
lxc.include = /usr/share/lxc/config/centos.userns.conf
lxc.arch = x86_64

# Container specific configuration
lxc.id_map = g 0 100000 65536
lxc.id_map = u 0 165536 65536
lxc.rootfs = /home/lxcuser/.local/share/lxc/centos75/rootfs
lxc.rootfs.backend = dir
lxc.utsname = centos75

# Network configuration
lxc.network.type = veth
lxc.network.link = br0
lxc.network.flags = up
#lxc.network.hwaddr = 00:16:3e:xx:xx:xx
`


Please note, the same config file (same container) can boot if the `cpuset` and `cpu` were removed from the 2 files you mentioned in your first post

**Comment by hinhthoi** [comment]
Sorry about the big bold words, all lines containing the big bold words are the commented-out lines in the config file

**Comment by brauner** [comment]
Please show the contents of `/etc/pam.d/common-session` and `/etc/pam.d/common-session-auth`, if you can. Also, try rebooting if you can.

**Comment by hinhthoi** [comment]
After restarting the server, i can start containers that doesn't have `lxc.cgroup.cpuset.cpus=1` in the config file.

But if i add the `lxc.cgroup.cpuset.cpus=1` into the config file, it still doesn't boot up, the error now is

lxcuser@dedi1:~/.local/share/lxc$ cat log.log
      lxc-start 20160925154521.436 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1651 - No such file or directory - Error setting cpuset.cpus to 1 for centos75
      lxc-start 20160925154521.436 ERROR    lxc_start - start.c:lxc_spawn:1181 - failed to setup the cgroup limits for 'centos75'
      lxc-start 20160925154521.436 ERROR    lxc_start - start.c:__lxc_start:1354 - failed to spawn 'centos75'
      lxc-start 20160925154526.981 ERROR    lxc_start_ui - tools/lxc_start.c:main:344 - The container failed to start.
      lxc-start 20160925154526.982 ERROR    lxc_start_ui - tools/lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 20160925154526.982 ERROR    lxc_start_ui - tools/lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.

**Comment by brauner** [comment]
Can you please post the contents of `common-session` and `common-session-auth` as requested above? :) Also, show the output of `cat /proc/self/cgroup` after the reboot, please.

**Comment by hinhthoi** [comment]
Here is the required detail
root@dedi1:~# cat /proc/self/cgroup

11:perf_event:/

10:cpuset:/

9:hugetlb:/

8:freezer:/user/root/1

7:net_cls,net_prio:/

6:pids:/user.slice/user-0.slice/session-79.scope

5:cpu,cpuacct:/user/root/1

4:memory:/user/root/1

3:devices:/user.slice/user-0.slice/session-79.scope

2:blkio:/user.slice/user-0.slice/session-79.scope

1:name=systemd:/user.slice/user-0.slice/session-79.scope

root@dedi1:~# cat /etc/pam.d/common-session

session [default=1]                     pam_permit.so

session requisite                       pam_deny.so

session required                        pam_permit.so

session optional                        pam_umask.so

session required        pam_unix.so

session optional        pam_systemd.so

session optional        pam_cgfs.so -c freezer,memory,name=systemd,cpuset,cpu

**Comment by hinhthoi** [comment]
root@dedi1:~# cat /etc/pam.d/common-session-noninteractive

session [default=1]                     pam_permit.so

session requisite                       pam_deny.so

session required                        pam_permit.so

session optional                        pam_umask.so

session required        pam_unix.so

session optional        pam_cgfs.so -c freezer,memory,name=systemd,cpuset,cpu

**Comment by hinhthoi** [comment]
I removed all commenting lines so that the post look less messy

**Comment by hinhthoi** [comment]
When i create any container, i must add `--no-validate` in order for the creation to succeed. Could this be the reason for the weird behaviour?

**Comment by brauner** [comment]
`--no-validate` only disables gpg key verification. This should have no effect on anything else.

What I'm confused about is why you're not placed in a writeable cgroup for the `cpuset` controller even though you enabled it in `libpam_cgfs`.

Another thing, you said that you're running unprivileged containers as a normal user. However, the output of `cat /proc/self/cgroup` shows that you're logged in as `root`:
  - Did you make sure that you logged in as a normal user when you tried to start the container after make the changes to `common-session` and `common-session-auth`?
  - Please show the contents of `cat /proc/self/cgroup` as when you're logged in as non-root user.
  - Please show the contents of `/etc/subuid` and `/etc/subgid`.


Side Note:
You can also append files here or should you prefer to paste it in here directly, you can place the copied contents between three backticks at the beginning and end of the paste to make it more readable:

```
Pasted text rendered in readable format.
```

**Comment by hinhthoi** [comment]
Since previously the lxcuser is a regular user without root privileges, so i used root to edit and view the files (Since i thought a file should show the same content for both root and regular user).

```
lxcuser@dedi1:~$ cat /proc/self/cgroup
11:memory:/
10:blkio:/user.slice/user-1000.slice
9:hugetlb:/
8:cpuset:/
7:devices:/user.slice/user-1000.slice
6:pids:/user.slice/user-1000.slice
5:perf_event:/
4:cpu,cpuacct:/user/lxcuser/2
3:net_cls,net_prio:/
2:freezer:/user/lxcuser/2
1:name=systemd:/user.slice/user-1000.slice/session-3482.scope
```
Here is the content of the subuid and subhid
```
lxcuser@dedi1:~$ cat /etc/subgid
lxcuser:100000:65536
lxcuser@dedi1:~$ cat /etc/subuid
ralf:100000:65536
lxcuser:165536:65536
```

**Comment by hinhthoi** [comment]
This afternoon i reinstalled the host OS, i have just redone, i.e. adding `cpuset` and `cpu` to the 2 files using `lxcuser` user (with sudo privilege). Then i logout and login, i cannot start the container, here is the error
```
      lxc-start 20160926152614.360 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1651 - No such file or directory - Error setting memory.limit_in_bytes to 5000000000 for centos6
      lxc-start 20160926152614.360 ERROR    lxc_start - start.c:lxc_spawn:1181 - failed to setup the cgroup limits for 'centos6'
      lxc-start 20160926152614.361 ERROR    lxc_start - start.c:__lxc_start:1354 - failed to spawn 'centos6'
      lxc-start 20160926152619.909 ERROR    lxc_start_ui - tools/lxc_start.c:main:344 - The container failed to start.
      lxc-start 20160926152619.909 ERROR    lxc_start_ui - tools/lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 20160926152619.910 ERROR    lxc_start_ui - tools/lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.
      lxc-start 20160926152726.365 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1651 - No such file or directory - Error setting memory.limit_in_bytes to 5000000000 for centos6
      lxc-start 20160926152726.365 ERROR    lxc_start - start.c:lxc_spawn:1181 - failed to setup the cgroup limits for 'centos6'
      lxc-start 20160926152726.365 ERROR    lxc_start - start.c:__lxc_start:1354 - failed to spawn 'centos6'
      lxc-start 20160926152731.932 ERROR    lxc_start_ui - tools/lxc_start.c:main:344 - The container failed to start.
      lxc-start 20160926152731.932 ERROR    lxc_start_ui - tools/lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 20160926152731.932 ERROR    lxc_start_ui - tools/lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.
      lxc-start 20160926153055.696 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1651 - No such file or directory - Error setting cpuset.cpus to 1 for centos6
      lxc-start 20160926153055.696 ERROR    lxc_start - start.c:lxc_spawn:1181 - failed to setup the cgroup limits for 'centos6'
      lxc-start 20160926153055.697 ERROR    lxc_start - start.c:__lxc_start:1354 - failed to spawn 'centos6'
      lxc-start 20160926153101.249 ERROR    lxc_start_ui - tools/lxc_start.c:main:344 - The container failed to start.
      lxc-start 20160926153101.250 ERROR    lxc_start_ui - tools/lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 20160926153101.250 ERROR    lxc_start_ui - tools/lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.
```
Then, i restarted the node, and tried starting the container again, i got a lot of permission problem
```
      lxc-start 20160926153658.029 ERROR    lxc_cgfs - cgroups/cgfs.c:lxc_cgroupfs_create:897 - Could not set clone_children to 1 for cpuset hierarchy in parent cgroup.
      lxc-start 20160926153658.039 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/blkio/user.slice/user-1000.slice
      lxc-start 20160926153658.039 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Read-only file system - cgroup_rmdir: failed to delete /sys/fs/cgroup/net_cls,net_prio/
      lxc-start 20160926153658.039 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Read-only file system - cgroup_rmdir: failed to delete /sys/fs/cgroup/hugetlb/
      lxc-start 20160926153658.039 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Read-only file system - cgroup_rmdir: failed to delete /sys/fs/cgroup/perf_event/
      lxc-start 20160926153658.039 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/freezer//user/root/0
      lxc-start 20160926153658.040 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/freezer//user/root
      lxc-start 20160926153658.040 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/freezer//user/lxcuser
      lxc-start 20160926153658.040 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Permission denied - cgroup_rmdir: failed to delete /sys/fs/cgroup/freezer//user
      lxc-start 20160926153658.040 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Read-only file system - cgroup_rmdir: failed to delete /sys/fs/cgroup/freezer/
.....
```
From the above error, it seems it was trying to delete some file system directories ???

**Comment by brauner** [comment]
Hm, so you can't set a memory limit unless you're in a writeable cgroup for the memory controller, the same for the cpuset controller. I'm not sure why this is not working for you. However, if you want a solution, you can use this script:

```
#! /bin/bash

printf '\n\033[42mCreating cgroup hierarchy\033[m\n\n' &&
for d in /sys/fs/cgroup/*; do
        f=$(basename $d)
        echo "looking at $f"
        if [ "$f" = "cpuset" ]; then
                echo 1 | sudo tee -a $d/cgroup.clone_children;
        elif [ "$f" = "memory" ]; then
                echo 1 | sudo tee -a $d/memory.use_hierarchy;
        fi
        sudo mkdir -p $d/$USER
        sudo chown -R $USER $d/$USER
        # add current process to cgroup
       echo $PPID > $d/$USER/tasks
done
```

Putting this in an executable script and running it will place the shell for your user into a writeable cgroup for *all* controllers. Note, that if you switch to a different shell you will have to run that script again.

**Comment by hinhthoi** [comment]
Dear Brauner,

That code works very well, but i can imagine a hard time to find out a way to automate the entire LXC creation process.

Thank you again for your time and your help!

Have a nice day!
