### ISSUE TITLE
lxcbr0 bridge interface is missing 

### ISSUE THREAD

**Issue by ragavaluvijay** [lxc/lxc#1218]
Hello,

I have installed lxc v 2.0.4 in to my target platform and all the basic lxc functionalities work as expected for privilege container . however  lxcbr0 is missing in host hence no support for network interface inside the container. 
I used lxc-busybox template to create the container( i added below config in the /etc/lxc/default.conf file)

```
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:xx:xx:xx
```

below commands are used to create and start container.

```
lxc-create -n Cont_network -t busybox
lxc-start -n Cont_network - F
```

while lxc-start below error were seen

> lxc-start: conf.c: instantiate_veth: 2596 failed to attach 'vethDNUH5X' to the bridge 'lxcbr0': Operati
> on not permitted
> lxc-start: conf.c: lxc_create_network: 2882 failed to create netdev
> lxc-start: start.c:
> lxc_spawn: 1081 failed to create the network
> lxc-start: start.c: __lxc_start: 1354 failed to spawn 'Cont_network'
> lxc-start: tools/lxc_start.c: main: 344 The container failed to start.
> lxc-start: tools/lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile
>  and --logpriority options.

I found that lxcbr0 interface is missing in my host and i am using systemd init system on my target platform for this experiment and kernel ver 3.14(uname -a)
`3.14.28-1.12 #1 SMP Tue Sep 27 18:10:18 IST 2016 armv7l GNU/Linux`

Can you please let me know how to enable lxcbr0 in host?

I have stopped the lxc-net service and started again , but still issue is not resolved.

```
systemctl stop lxc-net.service
systemctl start lxc-net.service
```

ifconfig output from host and no lxcbr0 interface

> eth2      Link encap:Ethernet  HWaddr D4:0A:A9:D5:B2:EC
>           inet addr:10.237.22.214  Bcast:10.237.23.255  Mask:255.255.254.0
>           inet6 addr: fe80::d60a:a9ff:fed5:b2ec/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:19552 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:5224 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000
>           RX bytes:3622816 (3.4 MiB)  TX bytes:1194017 (1.1 MiB)
> 
> lo        Link encap:Local Loopback
>           inet addr:127.0.0.1  Mask:255.0.0.0
>           inet6 addr: ::1/128 Scope:Host
>           UP LOOPBACK RUNNING  MTU:65536  Metric:1
>           RX packets:6329 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:6329 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:0
>           RX bytes:797845 (779.1 KiB)  TX bytes:797845 (779.1 KiB)

I understand, there is bug fixes for "lxcbr0 interface missing" issue for ubuntu 15.10 or higher version which is based on systemD init systems. i dont know whether similar fix can resolve my issue and also i dont know how to add that fix for my target platform as i my environment is not ubuntu
[https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1312532]

**Comment by ragavaluvijay** [comment]
Trail 1) 
I have also tried below config under /etc/lxc/default.conf file 
lxc.network.type = none
with that i get eth2 ip address which is my host network ip address and i am actaully looking different ip address , for that i think lxcbr0 interface needs to be enabled .

Trail 2)
Similarly , i have also tried below 
added below in /etc/network/interfaces 
```
auto lxcbr0
iface lxcbr0 inet dhcp
        bridge_ports eth2
        bridge_fd 0
        bridge_maxwait 0
```
added below in /etc/network/if-pre-up.d/lxcbr0
```
#! /bin/sh

brctl show |grep lxcbr0 > /dev/null 2>/dev/null
if [ \$? != 0 ] ; then
      brctl addbr lxcbr0
      brctl addif lxcbr0 eth2
      ip addr flush eth2
      ifconfig eth2 up
fi

```
with this change i get lxcbr0 interface on the host , but there is not ip address for eth2 host 
please below after this change

>  eth2      Link encap:Ethernet  HWaddr D4:0A:A9:D5:B2:EC
>           inet6 addr: fe80::d60a:a9ff:fed5:b2ec/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:25013 errors:0 dropped:23 overruns:0 frame:0
>           TX packets:6104 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000
>           RX bytes:4344203 (4.1 MiB)  TX bytes:1188933 (1.1 MiB)
> 
> lo        Link encap:Local Loopback
>           inet addr:127.0.0.1  Mask:255.0.0.0
>           inet6 addr: ::1/128 Scope:Host
>           UP LOOPBACK RUNNING  MTU:65536  Metric:1
>           RX packets:7692 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:7692 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:0
>           RX bytes:815294 (796.1 KiB)  TX bytes:815294 (796.1 KiB)
> 
> lxcbr0    Link encap:Ethernet  HWaddr D4:0A:A9:D5:B2:EC
>           inet addr:10.237.22.214  Bcast:10.237.23.255  Mask:255.255.254.0
>           inet6 addr: fe80::d60a:a9ff:fed5:b2ec/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:9670 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:1805 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:0
>           RX bytes:1240676 (1.1 MiB)  TX bytes:260147 (254.0 KiB)

suggest me , how to resolve this issue.

I basically wanted to communicate between two container using socket communication.

**Comment by ragavaluvijay** [comment]
on Trail2  i did below changes ,
```
brctl show |grep lxcbr0 > /dev/null 2>/dev/null
if [ \$? != 0 ] ; then
      brctl addbr lxcbr0
      brctl addif lxcbr0 eth2
      ifconfig eth2 up
fi
```
i could get same IPaddress for both eth2 and lxcbr0 same IP address , and when i create container with below config , i get IP static address inside the container 
```
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.ipv4 = 10.237.22.215
lxc.network.hwaddr = 00:16:3e:xx:xx:xx
```

however when i try to ping  from host to the container , it is not pinging and also , i have seen that below virtual network interface is getting created for each container creation with above config and only static IP addr change like 216,217..etc ,  Ifconfig output from host 
```
eth2   Link encap:Ethernet  HWaddr D4:0A:A9:D5:B2:EC
          inet addr:10.237.22.214  Bcast:10.237.23.255  Mask:255.255.254.0
          inet6 addr: fe80::d60a:a9ff:fed5:b2ec/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:25013 errors:0 dropped:23 overruns:0 frame:0
          TX packets:6104 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4344203 (4.1 MiB)  TX bytes:1188933 (1.1 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:7692 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7692 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:815294 (796.1 KiB)  TX bytes:815294 (796.1 KiB)

lxcbr0    Link encap:Ethernet  HWaddr D4:0A:A9:D5:B2:EC
          inet addr:10.237.22.214  Bcast:10.237.23.255  Mask:255.255.254.0
          inet6 addr: fe80::d60a:a9ff:fed5:b2ec/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:9670 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1805 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1240676 (1.1 MiB)  TX bytes:260147 (254.0 KiB)

vethCF1G0R Link encap:Ethernet  HWaddr FE:8D:9F:61:27:71
          inet6 addr: fe80::fc8d:9fff:fe61:2771/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:273 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:648 (648.0 B)  TX bytes:24115 (23.5 KiB)
```

Guide me, how to communicate between host and container with this config or am i missing any config here for communication between host and container.

**Comment by ragavaluvijay** [comment]
i also seen that i could ping between two containers and not with host to container or container to host and even not able to communicate outside IP connected in same LAN network.
Can anyone please tell me what is that i am missing here

**Comment by claudiojulioferraz** [comment]
Same problem. This Issue is already years old and no one answered.
Translated automatically.

**Comment by stgraber** [comment]
`systemctl start lxc-net` should create `lxcbr0` unless your configuration in `/etc/default` has it disabled. If it doesn't show up, run `journalctl -u lxc-net.service -n 30` to hopefully get an error message.

**Comment by brauner** [comment]
Reopen if issue still exists after @stgraber's instructions. Sorry for the delay.

**Comment by 7r1n1t3** [comment]
in my case, loading br_netfilter fixed it.
`sudo modprobe br_netfilter`
`sudo sysctl -w net.bridge.bridge-nf-call-iptables=1`
and to make it persistent across reboots: 

put in /etc/modules-load.d/br_netfilter.conf
`br_netfilter`
and /etc/sysctl.d/99-br-netfilter.conf
`net.bridge.bridge-nf-call-iptables = 1`
