### ISSUE TITLE
start Unprivileged containers with apparmor error

### ISSUE THREAD

**Issue by isunnyi** [lxc/lxc#1220]
Host information:
Linux Debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux

When i start my lxc with non-root user , apparmor service couldn't start and there are failed information printed:

> Starting AppArmor profiles:Mounting securityfs on /sys/kernel/security...mount: permission denied
> failed.
>  failed!
> startpar: service(s) returned failure: apparmor ... failed!

Is there anything we can do to mount securityfs on /sys/kernel/security successfully in my Unprivileged container?
thanks a lot!

**Comment by brauner** [comment]
Can you please post the version of `LXC` you are using?

**Comment by isunnyi** [comment]
sorry for being late.
here is the version information of LXC:
 lxc                     1:1.0.6-6+deb8u3

**Comment by brauner** [comment]
This version of `LXC` is really old and you should at least upgrade to the latest `1.0.*` bugfix release which as of this writing is `LXC 1.0.8`.

**Comment by isunnyi** [comment]
These days i upgrade lxc to 1.0.8,problem still exists. But when i create and start lxc with root,apparmor can work  normally.That is to say,priviledged container has no such problem.

**Comment by brauner** [comment]
I suspect that this is because apparmor mount features are not supported by your kernel. To alleviate this problem commit 7196c7b37c4dec6fc206fe4240eca8ef63119e42 is needed. The commit can probably be backported by @stgraber once we sort out `stable-1.0`.

**Comment by isunnyi** [comment]
Lxc 1.0.8 has modified apparmor.c based on commit 7196c7b,but problem still exists. 
I want to know whether apparmor service could be  supported by unprivileged containt. If supported,is there any way to support apparmor service in unprivileged container.
 thanks!

**Comment by brauner** [comment]
Afaict, `LXC 1.0.8` does not include commit 7196c7b.

To your second question: That depends what you mean by this. If you're talking about apparmor stacking whereby an unprivileged container is allowed to load its own apparmor profile, then this can be supported but isn't in low-level `LXC` right now. It is however possible with our rest-api daemon `LXD` which builds on top of `LXC`/`liblxc`.
Your specific problem however is that you're not allowed to mount `securityfs` and this is something which aforementioned commit deals with. You could try to update to `stable-2.0` for production or our latest feature release `LXC 2.0.5` and try again. Both should include this commit.

**Comment by isunnyi** [comment]
I upgrade lxc to 2.0.5 but problem still exists.
Below is detailed information about starting apparmor service:
root@lxc:/# systemctl status apparmor.service
● apparmor.service - LSB: AppArmor initialization
   Loaded: loaded (/etc/init.d/apparmor)
   Active: failed (Result: exit-code) since Mon 2016-10-10 14:15:40 UTC; 31s ago
  Process: 128 ExecStart=/etc/init.d/apparmor start (code=exited, status=1/FAILURE)

Oct 10 14:15:40 lxc apparmor[128]: Starting AppArmor profiles:Mounting securityfs on /sys/kernel/security...mount: permission denied
Oct 10 14:15:40 lxc apparmor[128]: failed.
Oct 10 14:15:40 lxc apparmor[128]: failed!
Oct 10 14:15:40 lxc systemd[1]: apparmor.service: control process exited, code=exited status=1
Oct 10 14:15:40 lxc systemd[1]: Failed to start LSB: AppArmor initialization.
Oct 10 14:15:40 lxc systemd[1]: Unit apparmor.service entered failed state.
root@lxc:/# 
root@lxc:/# journalctl -xn
-- Logs begin at Mon 2016-10-10 14:11:49 UTC, end at Mon 2016-10-10 14:15:40 UTC. --
Oct 10 14:15:40 lxc systemd[1]: Configuration file /lib/systemd/system/systemd-shutdownd.socket is marked executable. Please remove executable permission bits. Proceeding anyway.
Oct 10 14:15:40 lxc systemd[1]: Configuration file /lib/systemd/system/systemd-udevd-control.socket is marked executable. Please remove executable permission bits. Proceeding anyway.
Oct 10 14:15:40 lxc systemd[1]: Configuration file /lib/systemd/system/systemd-udevd-kernel.socket is marked executable. Please remove executable permission bits. Proceeding anyway.
Oct 10 14:15:40 lxc systemd[1]: Starting LSB: AppArmor initialization...
-- Subject: Unit apparmor.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit apparmor.service has begun starting up.
Oct 10 14:15:40 lxc apparmor[128]: Starting AppArmor profiles:Mounting securityfs on /sys/kernel/security...mount: permission denied
Oct 10 14:15:40 lxc apparmor[128]: failed.
Oct 10 14:15:40 lxc apparmor[128]: failed!
Oct 10 14:15:40 lxc systemd[1]: apparmor.service: control process exited, code=exited status=1
Oct 10 14:15:40 lxc systemd[1]: Failed to start LSB: AppArmor initialization.
-- Subject: Unit apparmor.service has failed

**Comment by brauner** [comment]
So again, what are you trying to do?:
1. Are you just trying to start an unprivileged container and the container fails to start due to `AppArmor`?
or
2. Are you trying to run `AppArmor` *in* an unprivileged container?

**Comment by isunnyi** [comment]
I means item 2,trying to run appArmor in an unprivileged container.
My unprivileged container has started successfully,but when i start appArmor service ,it failed because of Mounting securityfs being failed.

**Comment by brauner** [comment]
That is only possible if `AppArmor` nesting is supported in your kernel. Afaik, this is only possible with a fairly recent (`4.8`) `Ubuntu` kernel which carries the necessary patches. You won't be able to do this with your kernel.

**Comment by isunnyi** [comment]
I have a question why i could start apparmor service in privileged container
