### ISSUE TITLE
[lxc1.0.6 - Openwrt ] implicit declaration of function 'openat' during compilation 

### ISSUE THREAD

**Issue by StanOnix** [lxc/lxc#1222]
Hello,

I don't know if it's the right place to ask for help but you'll probably tell me. My issue is thaht when I compile lxc 1.0.6, I got an error in bdev.c [1896], telling me that it doesn't find openat which is declared in fcntl.h. I don't think that the problem is about the Openwrt  I use. If you want any file which can help you help me let me know. 

Thank you in advance.

**Comment by stgraber** [comment]
What C library are you using for your openwrt build?

**Comment by StanOnix** [comment]
I use uClibc for the build.

**Comment by StanOnix** [comment]
The version is 0.9.30. I check on the staging_dir and files like fcntl.h  stat.h are there.

**Comment by stgraber** [comment]
Ok. So you said you're building LXC 1.0.6, that's a bit out of date. Current LXC 1.0.x is 1.0.8, could you try to build that?

It'd also help if you could try to reproduce this with current LXC, either from git or the recently released 2.0.5 version.

My best guess is that it's some missing define or include ordering issue with uclibc.

Our CI tests on glibc and bionic which usually gives us pretty good coverage given how weird bionic is, but maybe we should figure out a way to add musl and uclibc to the mix.

**Comment by brauner** [comment]
Hm, yeah that's weird. Fairly recent versions of `uclibc` should actually ship an `openat()` implementation. So the cause might also be that your `uclibc` is out of date.

**Comment by brauner** [comment]
We haven't heard back in a while so I assume the issue is gone. If it still persists, please re-open.
