### ISSUE TITLE
Where is lxc_strerror()?

### ISSUE THREAD

**Issue by Jafaral** [lxc/lxc#1227]
Hi, 

The source code has a couple of references to lxc_strerror() in arguments.h and lxc.h that looks like this:
```c
extern const char *lxc_strerror(int error); 
```
It is obvious that this function is modeled after strerror() to give a human readable error message given an error code, which is great. The two references above are only extern definitions. It is not actually used anywhere in the code or even implemented. Does this function actually exist?  Who is supposed to provide it?

Thanks,
Jafar

**Comment by brauner** [comment]
It doesn't seem to be implemented. I'm not sure whether we have use for it. If you see a legitimate usecase/improvement, feel free to submit an implementation.

**Comment by Jafaral** [comment]
@brauner thanks for the quick reply.  I pumped into this issue while trying to use the ruby-lxc bindings list ed on https://github.com/lxc. lxc_strerror() is used in the library but I get undefined symbol error when I try to use  the library. I reported the issue there but got no response. I fixed my issue locally by adding a dummy implementation. I just wanted to make sure that this function actually, or not, before moving forward with any proper fix. 

You are right, there is probably no "great" use for it  directly within the library itself, but it is useful for any library/language-binding, or application that want to use the library and want to be able to do error handling at their level. Most functions exposed by the the API in lxccontainers.h return either true or false. When the function fails there is no easy way to tell what went wrong. Am I right? or is there to do that?

**Comment by hallyn** [comment]
On Thu, Oct 13, 2016 at 09:18:39AM -0700, Christian Brauner wrote:
> It doesn't seem to be implemented. I'm not sure whether we have use for it. If you see a legitimate usecase/improvement, feel free to submit an implementation.

Removed in 2009 :)

Author: Michel Normand <normand@fr.ibm.com>
Date:   Mon May 18 22:30:39 2009 +0200

    remove lxc_error_t enum that is now useless

    There is no more need of the LXC_ERROR defines
    and related lxc_strerror function.

**Comment by Jafaral** [comment]
@hallyn Thanks for clarifying this. lxc_strerror() should be dropped then, including the left over extern definitions in the two files I pointed out in the original post. Should I submit a patch for those?

**Comment by stgraber** [comment]
Sure, sounds good

**Comment by Jafaral** [comment]
Done! Thanks everyone. 

On a related subject, is ruby-lxc still maintained? I posted this lxc_strerror() issue there more than two weeks ago but got no response. I submitted a patch for that as well, is there anyone to pick it up?

Thanks.

**Comment by stgraber** [comment]
ruby-lxc is maintained by @andrenth, not sure how active he is these days.
