### ISSUE TITLE
improve bash completion

### ISSUE THREAD

**Issue by evgeni** [lxc/lxc#1236]
For instance:

lxc-create -B <tab> should show a list of backing store types.  Instead it shows a list of filesystem objects in the current directory.

From: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840541

**Comment by brauner** [comment]
Patches welcome. :)

**Comment by abbasally5** [comment]
Is this still an issue that needs fixing? I would love to take a look at it

**Comment by brauner** [comment]
Sure, feel free.
