### ISSUE TITLE
Debian images not working right

### ISSUE THREAD

**Issue by brontide** [lxc/lxc#1247]
```
root@bento:~# lxc --version
2.4.1
```

I don't know if it's me but I have not been able to get any of the stock debian images or my own debootstrap images to behave within a container.  I have tried with both the default ldxbr0 NAT as well as directly bridged to a network segment.  All debian containers have difficulty resolving hosts ( seems hit and miss ), I often have the force shutdown, and many packages will hang the installer.

In one term I did a `apt-get install dnsmasq`

```
Unpacking dnsmasq (2.72-3+deb8u1) ...
Processing triggers for dbus (1.8.20-0+deb8u1) ...
```

And here is journalctl

```
Oct 23 12:46:14 d1 systemd[1]: Started Update UTMP about System Runlevel Changes.
Oct 23 12:46:14 d1 systemd[1]: Startup finished in 26.445s.
Oct 23 12:46:49 d1 systemd[1]: Reloading.
Oct 23 12:46:50 d1 systemd[1]: Failed to parse /proc/swaps:2
Oct 23 12:46:50 d1 systemd[1]: Reloading.
Oct 23 12:46:50 d1 systemd[1]: Failed to parse /proc/swaps:2
Oct 23 12:46:50 d1 systemd[1]: Reloading.
Oct 23 12:46:50 d1 systemd[1]: Failed to parse /proc/swaps:2
Oct 23 12:46:50 d1 systemd[1]: Reloading.
Oct 23 12:46:50 d1 systemd[1]: Failed to parse /proc/swaps:2
Oct 23 12:46:51 d1 systemd[1]: Reloading.
Oct 23 12:46:51 d1 systemd[1]: Failed to parse /proc/swaps:2
Oct 23 12:47:05 d1 systemd[1]: Reloading.
Oct 23 12:47:05 d1 systemd[1]: Failed to parse /proc/swaps:2
Oct 23 12:47:05 d1 groupadd[340]: group added to /etc/group: name=messagebus, GID=109
Oct 23 12:47:05 d1 groupadd[340]: group added to /etc/gshadow: name=messagebus
Oct 23 12:47:05 d1 groupadd[340]: new group: name=messagebus, GID=109
Oct 23 12:47:05 d1 useradd[344]: new user: name=messagebus, UID=104, GID=109, home=/var/run/dbus, shell=/bin/false
Oct 23 12:47:05 d1 usermod[349]: change user 'messagebus' password
Oct 23 12:47:05 d1 chage[354]: changed password expiry for messagebus
Oct 23 12:47:05 d1 systemd[1]: Reloading.
Oct 23 12:47:05 d1 systemd[1]: Failed to parse /proc/swaps:2
Oct 23 12:47:05 d1 systemd[1]: Reloading.
Oct 23 12:47:05 d1 systemd[1]: Failed to parse /proc/swaps:2
Oct 23 12:47:05 d1 systemd[1]: Starting D-Bus System Message Bus Socket.
Oct 23 12:47:05 d1 systemd[1]: Listening on D-Bus System Message Bus Socket.
Oct 23 12:47:05 d1 systemd[1]: Starting D-Bus System Message Bus...
Oct 23 12:47:05 d1 systemd[1]: Started D-Bus System Message Bus.
Oct 23 12:47:05 d1 systemd[407]: Failed at step OOM_ADJUST spawning /usr/bin/dbus-daemon: Permission denied
Oct 23 12:47:30 d1 systemd[1]: Failed to register match for Disconnected message: Connection timed out
Oct 23 12:47:56 d1 systemd[1]: Failed to register match for Disconnected message: Connection timed out
Oct 23 12:47:56 d1 systemd[1]: dbus.service: main process exited, code=exited, status=206/OOM_ADJUST
Oct 23 12:47:56 d1 systemd[1]: Unit dbus.service entered failed state.
Oct 23 12:47:56 d1 systemd[1]: Reloading.
Oct 23 12:47:56 d1 systemd[1]: Failed to parse /proc/swaps:2
Oct 23 12:47:56 d1 systemd[1]: Looping too fast. Throttling execution a little.
Oct 23 12:47:57 d1 systemd[1]: Looping too fast. Throttling execution a little.
Oct 23 12:47:58 d1 systemd[1]: Looping too fast. Throttling execution a little.
Oct 23 12:47:59 d1 systemd[1]: Looping too fast. Throttling execution a little.
Oct 23 12:48:00 d1 systemd[1]: Looping too fast. Throttling execution a little.
```

I have no problems with recent ubuntu, centos, or oracle images. 

I'm hoping to get jessie and wheezy images working for testing of pihole installations.

If there are more diagnostic steps I can try let me know.

**Comment by brontide** [comment]
One problem down.  I can get dbus to behave by creating the file `/etc/systemd/system/dbus.service.d/override.conf` with the contents below.  

```
[Service]
OOMScoreAdjust=0
```

The debian based images still don't shutdown properly and just hang.

**Comment by brauner** [comment]
This is likely a `systemd` problem that does misbehave inside the container; especially if you use your own images. There's likely nothing that `LXC/LXD` can do about this.

**Comment by brontide** [comment]
So why publish images that are incompatible with lxc?

**Comment by brontide** [comment]
journalctl 

```
Oct 23 13:30:18 d1 systemd[1]: Starting Halt...
Oct 23 13:30:18 d1 systemd[1]: Assertion 'sd_id128_randomize(&id) >= 0' failed at ../src/core/dbus.c:688, function bus_on_connection(). Aborting.
Oct 23 13:30:18 d1 systemd[1]: Caught <ABRT>, dumped core as pid 462.
Oct 23 13:30:18 d1 systemd[1]: Freezing execution.
```

Upon searching for this it does appear as though debian is incompatible with LXC at this time, why publish images?

**Comment by brauner** [comment]
This should only affect `Debian Jessie` which ships a version of `systemd` that does some things that won't work inside a container. `Debian Wheezy` should be fine as it runs `sysvinit` and `Debian Sid` should work fine as well.

Now, the ultimate idea is to just bootstrap an unmodified rootfs for a given distribution and to be able to run it. This is only partially possible as you can see from our templates. They modify some things - though really not a lot anymore - to guarantee that a given image can safely run in a container and is functional. But if you create your own rootfs it's up to you to make the changes required to make the image behave correctly

Even with our template system, most images we ship are a community effort. It's up to the template maintainers to ensure that they work correctly even though we try to keep an eye on this as well. But what we of course can't do, is to guarantee that each package that ships with a given distribution will behave correctly in a container. `systemd` is one such case and a special one at that. You need a new enough version that is smart enough to not perform operations that are impossible or invalid in a container. There is nothing we can do about this given that `Debian Jessie` doesn't ship a new enough version. Sorry. :)

**Comment by brontide** [comment]
For anyone else that might stumble across this post I did find a workaround.

http://code.saghul.net/index.php/2016/01/15/lxd-debian-containers-and-systemd/

```
lxc exec jessie-test /bin/bash
apt-get update && apt-get install sysvinit-core
exit
lxc stop jessie-test --force
lxc start jessie-test
lxc exec jessie-test /bin/bash
apt-get remove --purge --auto-remove systemd
rm -rf /var/lib/apt/lists/*
rm -rf /var/cache/apt/archives/*
exit
lxc stop jessie-test
lxc publish jessie-test --alias jessie-amd64-base-sysvinit
```

It's not perfect if you need to emulate jessie perfectly, but when you just need the libraries and environment it's a viable alternative.

**Comment by pcdummy** [comment]
I found a way without ditching systemd, enable backports and install systemd from there:

all as root:

    echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list
    apt-get update
    apt-get -t jessie-backports install systemd dbus

For now it seems to work, will report more about my Debian jessie in container experience here.
