### ISSUE TITLE
Container reboot detection via utmp does not work if "/run" is mounted after container init

### ISSUE THREAD

**Issue by wracoon** [lxc/lxc#1250]
Hello,

Background to the issue:
We have an opensuse 13.1 based lxc container running in lxc-2.0.5.
There is an issue with reboots triggered from inside the container - instead of actually rebooting the container is shut down.

After some tracing of this issue I found that the lxc reboot detection doesn't work.
There are two issues:
- The SystemD init process does not return exit status expected for reboot (LXC expects a signal exit status for SIGHUP => reboot). This is an issue of SystemD.
- The other mechanism for detecting reboot - reading /var/run/utmp or /run/utmp file inside container - does not work because opensuse mounts /run (symlink to /var/run) as tmpfs filesystem shortly after boot.

Explanation:
LXC creates an inotify watch for the /run directory inside container before starting container init (I think):
`lxc-start 20161025131645.109 DEBUG    lxc_utmp - lxcutmp.c:lxc_utmp_mainloop_add:383 - Added '/proc/1290/root/run' to inotifywatch`

It does this so that it can watch for runlevel changes in the utmp file.
But after the tmpfs is mounted on /run directory by opensuse then the inotify watch is on the old directory which is not updated anymore by container. "/run/utmp" file is written to the tmpfs (not being watched by LXC). 

As a result if the container init exits as a result of reboot, LXC assumes that it was shutdown.

Q: Do you think lxc could detect such change in "/run" or maybe update the inotify watch periodically?

NOTE:
I have confirmed this by bind-mounting the /run directory "hidden" by tmpfs (on harddisk) and touched the utmp file. This triggered the lxc utmp inotify watch:

```
lxc-start 20161025152358.163 DEBUG    lxc_utmp - lxcutmp.c:utmp_handler:190 - got inotify event 2 for utmp
lxc-start 20161025152358.163 DEBUG    lxc_utmp - lxcutmp.c:utmp_get_runlevel:281 - utmp handler - run level is ^@/3
lxc-start 20161025152358.163 DEBUG    lxc_utmp - lxcutmp.c:utmp_handler:232 - Container running
lxc-start 20161025152358.163 DEBUG    lxc_utmp - lxcutmp.c:utmp_handler:190 - got inotify event 2 for utmp
lxc-start 20161025152358.163 DEBUG    lxc_utmp - lxcutmp.c:utmp_get_runlevel:281 - utmp handler - run level is ^@/3
lxc-start 20161025152358.163 DEBUG    lxc_utmp - lxcutmp.c:utmp_handler:232 - Container running
```

**Comment by stgraber** [comment]
What kind of kernel are you using for you to need the utmp monitoring at all?

I thought we were only using this for very very old kernels (2.6.x) that didn't send the proper signal on reboot() calls.

**Comment by wracoon** [comment]
Thank you for your time and swift reply, Stéphane.

Oh, right, we use a more "vintage" kernel on the lxc host:
# uname -a
Linux bra 3.0.101-71-default #1 SMP Thu Mar 3 12:56:15 UTC 2016 (7bdad2e) x86_64 x86_64 x86_64 GNU/Linux

Unfortunately we are currently stuck with this kernel.
So it is the kernel that should set the correct exit status for init on reboot?
I thought it was systemd's responsibility to return correct exit status, but I guess it makes sense - since it's a signal status.

**Comment by wracoon** [comment]
Whoops, sorry about the issue status change, wrong click.

Do you think it's worth fixing here in upstream lxc?
I was considering patching our lxc package to make the reboot work,
but I'm not yet completely familiar with the code.

Can you maybe think of a good place to put another inotify watch on the /run (or /var/run) directory after container init started?
