### ISSUE TITLE
[Question] Reasons to limit copy/snapshot to stopped containers

### ISSUE THREAD

**Issue by Anthony25** [lxc/lxc#1254]
Hello,
lxc-copy and lxc-snapshot check that the target is stopped to continue. Is there a reason to do so? 

Backends like btrfs or zfs can do instant snapshots. I understand that it could be an issue if a database is running, but if it is the only reason, you could just warn the user about it in your manpages, no? Plus, tell me if I am wrong, but lxd allows hot snapshot/copy.

I patched lxc because I need to backup running containers, so I would like to know what possible drawbacks it could involve.

Thanks!

**Comment by brauner** [comment]
I couldn't find an explanation why @hallyn used `is_stopped()` in `do_lxcapi_clone()`. Maybe he can enlighten us. :)

**Comment by hallyn** [comment]
If lack of instant fs snapshots was the only problem we could have just frozen the containers around the snapshot action.  The problem (iirc) was inconsistent application state.  Applications may be in the middle of a transaction which cannot be correctly completed or reversed without knowing the state of the application's memory.

**Comment by hallyn** [comment]
Note if you wanted to add a sufficiently scary sounding flag to override that that would be fine.

**Comment by Anthony25** [comment]
Yep, I did a PR: #1277
You can always change the flag if it doesn't look scary enough :p
