### ISSUE TITLE
lxc-top: add CPU percent column

### ISSUE THREAD

**Issue by alphaonex86** [lxc/lxc#1265]
Hello,

CPU seconds is not useful, can you add CPU percent column?
To see just now the cpu usage for each vm

Cheers,

**Comment by stgraber** [comment]
The kernel cgroup interface doesn't report anything remotely close to a CPU percentage so there's not much we can do there :)

**Comment by alphaonex86** [comment]
With munin I do it with:
cat /sys/fs/cgroup/cpuacct/lxc/$guest_name/cpuacct.stat | grep user | awk '{print($2)}'
cat /sys/fs/cgroup/memory/lxc/$guest_name/memory.usage_in_bytes
cat /sys/fs/cgroup/memory/lxc/$guest_name/memory.stat | grep total_inactive_anon | awk '{print($2)}'
cat /sys/fs/cgroup/memory/lxc/$guest_name/memory.stat | grep total_cache | awk '{print($2)}'
cat /sys/fs/cgroup/memory/lxc/$guest_name/memory.stat | grep total_active_anon | awk '{print($2)}'
cat /sys/fs/cgroup/cpuacct/lxc/$guest_name/cpuacct.stat | grep system | awk '{print($2)}'
        if [ `lxc-info -H -S -n ${guest} 2> /dev/null | grep -F 'RX bytes' | wc -l` -ne 0 ]
        then
    echo -n "${guestclean}_down.value "
    lxc-info -H -S -n ${guest} | grep -F 'RX bytes' | grep -oE "[[:digit:]]{1,}"
    echo -n "${guestclean}_up.value "
    lxc-info -H -S -n ${guest} | grep -F 'TX bytes' | grep -oE "[[:digit:]]{1,}"
        fi
cat /sys/fs/cgroup/blkio/lxc/$guest/blkio.sectors | cut -d' ' -f2
