### ISSUE TITLE
lxc init --auto - enhancement request to add lxdbr0 initialization

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxc#1267]
lxc init seems to have no option to setup lxdbr0.

This means setup of machines to host LXD containers requires manual intervention to setup lxdbr0.

Be great if an option was added to initialize lxdbr0, so new machine setup can be automated.

Thanks for your consideration.

**Comment by stgraber** [comment]
Can't you just run "lxc network create lxdbr0"?

**Comment by stgraber** [comment]
Well, technically:

    lxc network create lxdbr0
    lxc network attach-profile lxdbr0 default eth0

**Comment by stgraber** [comment]
I'm not necessarily against adding more command line options to init, but I think we should seriously think about it as we don't want to end up with dozens of options in there, so maybe switch to accepting a yaml configuration document or something instead.

**Comment by brauner** [comment]
Leaving @stgraber's arguments aside, this is a `LXD` issue, not a `LXC/liblxc` issue. So if this is still something worth to be discussed please reopen at https://github.com/lxc/lxd. :)

**Comment by davidfavor** [comment]
Sounds good.

I'll use the above info.

Thanks.
