### ISSUE TITLE
Fixed vethXXXXX name on host

### ISSUE THREAD

**Issue by alphaonex86** [lxc/lxc#1272]
Hello,

I need have fix vethXXXX on host (to keep interface coerancy into zabbix), I use:
lxc.network.type = veth
lxc.network.link = br0
lxc.network.name = eth0
lxc.network.hwaddr = 7e:32:06:a8:00:13
Default name base on hash of lxc.network.hwaddr is correct, but able to configure the name is very better.
Tel me if you need more information.

Cheers,

**Comment by stgraber** [comment]
Set "lxc.network.veth.pair".
