### ISSUE TITLE
Node.js segmentation fault in unprivileged containers

### ISSUE THREAD

**Issue by mradke** [lxc/lxc#1278]
I am running an Alpine Linux host system with lxc version 1.1.5.
Everything is working as expected, except for an unprivileged container created via the download template in combination with node.js.

LXC-config
```
lxc.network.type = veth
lxc.network.link = br0
lxc.network.name = eth0
lxc.network.ipv4 = 10.0.0.15/24
lxc.network.flags = up
```

I am using Ansible but generally it should be this command that creates the container:
```
lxc-create -n test -t download -- --dist ubuntu --release xenial --arch amd64
```

When I run `lxc-attach -n test` I can update, install and run everything as normal (I even installed a functional open-xchange inside such a container), but when I try to run `node` or `npm` it doesn't do anything but print "Segmentation fault" and does nothing.

Is this caused by some arcane lxc-setting I forgot to set?
Thanks in advance! 👍

**Comment by stgraber** [comment]
Can you run node or npm under strace to see what it's doing at the time it segfaults?

**Comment by mradke** [comment]
Of course. I created a gist, because the output is fairly long: https://gist.github.com/mradke/b45ec415eec55408eb15273bcc7b29ed

Thanks for the fast response!

**Comment by stgraber** [comment]
I can't reproduce this issue on an Ubuntu host with LXC 2.0 and using the same nodejs you are (Ubuntu 16.04).

The source of the segfault is almost certainly those failed mmap calls as they are succeeding for me here.
I'm not sure what would cause mmap to return EPERM but there are some folks suggesting that it could have to do with some kernel security flags.

**Comment by stgraber** [comment]
To see how nodejs works in an unprivileged container on an Ubuntu host, you can go to https://linuxcontainers.org/lxd/try-it then start a session and install nodejs, it'll get you into the nodejs shell just fine.

You can also strace it if you want to compare the output with yours, in case there is some other hints as to what may be going on with your system.

**Comment by mradke** [comment]
Okay that may very well be since alpine has pretty rigid default kernel settings. Thanks for the heads up. I'll analyse it further and reach out to the alpine linux folks or just switch to ubuntu for the host-system. :-)
