### ISSUE TITLE
LXC1.2 - Debian Jessie (8.6), no console when following instructions

### ISSUE THREAD

**Issue by ddurdle** [lxc/lxc#1281]
When following these instructions:https://wiki.debian.org/LXC
lxc-create -n test -t debian -- -r jessie
lxc-start -n test -d
lxc-console -n test

All I get is this:

sudo lxc-console -n test

Connected to tty 1
                  Type <Ctrl+a q> to exit the console, <Ctrl+a Ctrl+a> to enter Ctrl+a itself

**Comment by brauner** [comment]
I'm not sure what you mean. Because this is what you would expect to see. Do you mean you don't get a login screen like this?:

```
Connected to tty 1
Type <Ctrl+a q> to exit the console, <Ctrl+a Ctrl+a> to enter Ctrl+a itself

Ubuntu Yakkety Yak (development branch) yak pts/0

yak login:
```

**Comment by ddurdle** [comment]
No login prompt.  From your output, I only got first two lines. I can try -t 0 or -t 2 and I get the same result.

I noticed if I don't start in -d, it starts the container and then returns me to a prompt.  It is running, I can stop it, etc.

I never had an issue with Debian Wheezy host using LXC, albeit it was 2 years ago when I last used it.  New machine, new install, with Jessie, and using the LXC 2 and everything looks in order, just have this problem actually using the containers.

I still have some of my old LXC containers on a secondary BTRFS drive.  I'm going to try to start them on this machine -- I know they are fully functioning containers.

**Comment by ddurdle** [comment]
When I tried the lxc instances from a previous install, after making a few updates to the config file to allow them to work, they worked.  It seems like the creation of containers in my LXC2 install is not working.

If I compare configs, the LXC2 configs seems to be lacking:

```
# Template used to create this container: /usr/share/lxc/templates/lxc-debian
# Parameters passed to the template: -r jessie
# For additional config options, please look at lxc.container.conf(5)

# Uncomment the following line to support nesting containers:
#lxc.include = /usr/share/lxc/config/nesting.conf
# (Be aware this has security implications)

lxc.network.type = empty
lxc.rootfs = /var/lib/lxc/test/rootfs
lxc.rootfs.backend = dir
#lxc.aa_allow_incomplete = 1
# Common configuration
lxc.include = /usr/share/lxc/config/debian.common.conf
lxc.aa_profile = unconfined


# Container specific configuration
lxc.tty = 4
lxc.utsname = test
lxc.arch = amd64
```

Compare with a working one:

```
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = virbr1
lxc.network.ipv4 = 192.168.100.0/24
lxc.network.ipv4.gateway = 192.168.100.1
lxc.mount.entry = /tmp/.X11-unix tmp/.X11-unix none bind,optional,create=dir
lxc.aa_profile = unconfined

lxc.rootfs = /var/lib/lxc/test3/rootfs
lxc.tty = 4
lxc.pts = 1024
lxc.utsname = test3

# When using LXC with apparmor, uncomment the next line to run unconfined:
#lxc.aa_profile = unconfined

lxc.cgroup.devices.deny = a
# /dev/null and zero
lxc.cgroup.devices.allow = c 1:3 rwm
lxc.cgroup.devices.allow = c 1:5 rwm
# consoles
lxc.cgroup.devices.allow = c 5:1 rwm
lxc.cgroup.devices.allow = c 5:0 rwm
lxc.cgroup.devices.allow = c 4:0 rwm
lxc.cgroup.devices.allow = c 4:1 rwm
# /dev/{,u}random
lxc.cgroup.devices.allow = c 1:9 rwm
lxc.cgroup.devices.allow = c 1:8 rwm
lxc.cgroup.devices.allow = c 136:* rwm
lxc.cgroup.devices.allow = c 5:2 rwm
# rtc
lxc.cgroup.devices.allow = c 254:0 rwm
# tun
lxc.cgroup.devices.allow = c 10:200 rwm
# sound
lxc.cgroup.devices.allow = c 14:0 rwm
lxc.cgroup.devices.allow = c 14:1 rwm
lxc.cgroup.devices.allow = c 14:3 rwm
lxc.cgroup.devices.allow = c 14:4 rwm
lxc.cgroup.devices.allow = c 14:8 rwm
lxc.cgroup.devices.allow = c 116:* rwm # dev/snd/
# video
lxc.cgroup.devices.allow = c 226:0 rwm
lxc.cgroup.devices.allow = c 29:0 rwm

# Use autodev to be compatible with systemd
#lxc.autodev = 1
#lxc.hook.autodev = /etc/lxc/autodev

# mounts point
lxc.mount.entry = proc proc proc nodev,noexec,nosuid 0 0
lxc.mount.entry = sysfs sys sysfs defaults  0 0

```

**Comment by brauner** [comment]
I don't see anything that would explain this change in behaviour. Please also note that Jessie containers, due to an old `systemd` version might not work correctly.

**Comment by ddurdle** [comment]
Good point.  The old containers are still based on wheezy.  Do you have any references I can follow to get Jessie containers working?

I was actually planning to do an upgrade on these working wheezy containers.

**Comment by brauner** [comment]
Unfortunately there's nothing `LXC` can do about this.

**Comment by Nevax07** [comment]
I already got this issue.
It's because the boot process was stuck on something and block the tty1 access.
Maybe try to accees on the tty2.

lxc-console -n CTID  --tty=2

For me it was a network issue, i have forget which process, but all i have to do was to set an ip manually.
