### ISSUE TITLE
lxc-test-ubuntu does not work with yakkety

### ISSUE THREAD

**Issue by Cypresslin** [lxc/lxc#1287]
The lxc-test-ubuntu test case will try to fetch -root.tar.gz (the compressed tar file of /) file for the test, the wget task will fail with error 404, as the -root.tar.gz file for Yakkety has been replaced by squashfs image format file [1].

Error message:

    wget is /usr/bin/wget
    --2016-10-22 16:18:43-- https://cloud-images.ubuntu.com/server/yakkety/20161020.1/yakkety-server-cloudimg-i386-root.tar.xz
    Connecting to 91.189.89.216:3128... connected.
    Proxy request sent, awaiting response... 302 Found
    Location: https://cloud-images.ubuntu.com/yakkety/20161020.1/yakkety-server-cloudimg-i386-root.tar.xz [following]
    --2016-10-22 16:18:44-- https://cloud-images.ubuntu.com/yakkety/20161020.1/yakkety-server-cloudimg-i386-root.tar.xz
    Reusing existing connection to cloud-images.ubuntu.com:443.
    Proxy request sent, awaiting response... 404 Not Found
    2016-10-22 16:18:44 ERROR 404: Not Found.

A possible solution is to add an if statement in lxc-ubuntu-cloud.in, ask it to fetch the .squashfs file for Yakkety and Zesty. Then do the unsquashfs task for it.

[1] https://bugs.launchpad.net/cloud-images/+bug/1634543

**Comment by stgraber** [comment]
Yes, we need to implement unsquashfs support for this, a branch that does so would be very much appreciated.

xenial and higher have squashfs, so you could just have the logic be to use squashfs on anything that's NOT "precise" or "trusty".

**Comment by Cypresslin** [comment]
OK! I do have a mock-up for that, but I think I will need some help for the tar command flag:

    if [ $in_userns -eq 1 ]; then
        tar --anchored --exclude="dev/*" --numeric-owner -xpf "$cache/$filename"
    $in_userns -eq 1

For tar, it can exclude something you don't want, but I can't find equivalent command for unsquashfs, do you think it's a good idea to run unsquashfs first then rm to achieve this?

Also, for the numeric-owner flag, I think squashfs does not need this (and it does not have this)?

Thanks

**Comment by stgraber** [comment]
So the reason for the --exclude in tar is to avoid errors when it can't mknod device nodes in unprivileged containers. In LXD we're using the following unsquashfs which seems to be working okay:

    unsquashfs -f -d . -n $cache/$filename

**Comment by Cypresslin** [comment]
Cool, I made my patch base on that.

If you want the feature to ignore /dev, I found it can be done with:
`shopt -s extglob`
`unsquashfs -f ubuntu-16.10-server-cloudimg-amd64.squashfs  -e '/!(dev)`

Just let me know if you want to have this add to the code.
Thanks
