### ISSUE TITLE
Can't expose /dev/ block device into LXC container

### ISSUE THREAD

**Issue by pedr000000** [lxc/lxc#1291]
Hi,
I have created the container using the usual lxc-container command and I have slightly modified the configuration file to expose a block device I need to operate upon:

```

lxc.aa_profile = lxc-container-default-with-mounting
lxc.cgroup.devices.allow = b 179:0 rwm

```

I am quite frustrated :-( It does not work and it complains :
     ```
 lxc-start 20161111114454.232 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1658 - No such file or directory - Error setting devices.allow to b 179:0 rwm for rcom
      lxc-start 20161111114454.232 ERROR    lxc_start - start.c:lxc_spawn:1227 - failed to setup the devices cgroup for 'rcom'
      lxc-start 20161111114454.232 ERROR    lxc_start - start.c:__lxc_start:1354 - failed to spawn 'rcom'

```
I am running on Ubuntu 16.06 and the container's starts an Ubuntu trusty distribution, is there a way I can track the problem down and, possibly, fix it ?

Thanks in advance.
Pietro

**Comment by brauner** [comment]
Hi, can you please show:

- `cat /proc/1/mountinfo | grep -i cgroup`
- `cat /proc/self/cgroup`

Also, what block device is `179:0`?

**Comment by pedr000000** [comment]
Hi,

output follows as requested :

```
root@rcom:/# cat /proc/1/mountinfo | grep -i cgroup
926 960 0:53 / /sys/fs/cgroup rw,relatime - tmpfs none rw,size=4k,mode=755,uid=100000,gid=100000

root@rcom:/# cat /proc/self/cgroup 
11:devices:/
10:freezer:/
9:cpuset:/
8:pids:/
7:cpu,cpuacct:/
6:memory:/
5:perf_event:/
4:hugetlb:/
3:net_cls,net_prio:/
2:blkio:/
1:name=systemd:/
root@rcom:/# 

```

It is a flash card inserted in my SD card reader, it is named 
```

/dev/mmcblk0
[136883.078819] mmc0: new high speed SDHC card at address aaaa
[136883.079100] mmcblk0: mmc0:aaaa SL08G 7.40 GiB 


```

Hope this could help you, please feel free to ask me additional question as I really need to get that working or to change my setup otherwise.

**Comment by brauner** [comment]
So, couple of things. You said you're running `Ubuntu 16.06.` that doesn't exist and you probably mean `Ubuntu 16.04` or are you running another distro? Please show `cat /etc/os-release`. :)
But you're main problem is that you don't have a `cgroupfs` mounted which is a necessary condition for `LXC` to work. That is __very weird__ since `Ubuntu 16.04` should do that out of the box for you. Did you do anything to bust your system? Did you install or uninstall any old/new init system. In any case, you're best bet so far is to reboot the machine, check `cat /proc/1/mountinfo | grep -i cgroup` again and see if any cgroup hierarchies with controllers are mounted. For example, if `/sys/fs/cgroup/devices` is present. Otherwise, there is nothing much we can do on the `LXC` side of things.

**Comment by pedr000000** [comment]
Hi,

I am sorry I meant 16.10  (yakkety)

The command after a reboot gives :
```

pietro@pietroocado:~$ cat /proc/1/mountinfo | grep -i cgroup
29 19 0:24 / /sys/fs/cgroup rw shared:9 - tmpfs tmpfs rw,mode=755
30 29 0:25 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:10 - cgroup cgroup rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
32 29 0:27 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:13 - cgroup cgroup rw,devices
33 29 0:28 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:14 - cgroup cgroup rw,perf_event,release_agent=/run/cgmanager/agents/cgm-release-agent.perf_event
34 29 0:29 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,blkio
35 29 0:30 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,cpuset,clone_children
36 29 0:31 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,freezer
37 29 0:32 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,net_cls,net_prio
38 29 0:33 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,hugetlb,release_agent=/run/cgmanager/agents/cgm-release-agent.hugetlb
39 29 0:34 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:20 - cgroup cgroup rw,pids,release_agent=/run/cgmanager/agents/cgm-release-agent.pids
40 29 0:35 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:21 - cgroup cgroup rw,cpu,cpuacct
41 29 0:36 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:22 - cgroup cgroup rw,memory

```
It still fails to bring up the container though.

```
lxc.aa_profile = lxc-container-default-with-mounting
lxc.cgroup.devices.allow = b 179:0 rwm

```

**Comment by brauner** [comment]
Can you please start the container with `lxc-start -n c -l debug -o c.log` and attach/paste the `c.log` file here? It seems like you are running `cgmanager` which should be unnecessary and might complicate things. If installed, you should remove `cgmanager` and reboot again and try again.

**Comment by pedr000000** [comment]
Hi, 

Thanks a lot for helping out, I can't see any cmanager process name running on the system and I can't see any package with that name either installed in my system, are there better ways to check ?

This is the output of the mentioned command : 
```
lxc-start 20161115165009.044 INFO     lxc_start_ui - tools/lxc_start.c:main:264 - using rcfile /home/pietro/.local/share/lxc/c/config
lxc-start 20161115165009.044 ERROR    lxc_start_ui - tools/lxc_start.c:main:295 - Executing '/sbin/init' with no configuration file may crash the host

```

**Comment by brauner** [comment]
I take it that you replaced `c` in `lxc-start -n c -l debug -o c.log` with the name of the container on your system. Otherwise this doesn't make much sense.

**Comment by pedr000000** [comment]
No I did not and I double check the history and the config file mentioned in the logfile should confirm that.

```
pietro@pietroocado:~$ rm c.log 
pietro@pietroocado:~$ lxc-start -n c -l debug -o c.log
lxc-start: tools/lxc_start.c: main: 295 Executing '/sbin/init' with no configuration file may crash the host
pietro@pietroocado:~$ cat c.log 
      lxc-start 20161115170348.933 INFO     lxc_start_ui - tools/lxc_start.c:main:264 - using rcfile /home/pietro/.local/share/lxc/c/config
      lxc-start 20161115170348.933 ERROR    lxc_start_ui - tools/lxc_start.c:main:295 - Executing '/sbin/init' with no configuration file may crash the host
pietro@pietroocado:~$ 
```

**Comment by pedr000000** [comment]
I do need a coffee.


xx@xx:~$ rm c.log 
xx@xx:~$ lxc-start -n rcom -l debug -o c.log
lxc-start: tools/lxc_start.c: main: 344 The container failed to start.
lxc-start: tools/lxc_start.c: main: 346 To get more details, run the container in foreground mode.
lxc-start: tools/lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.
xx@xx:~$ cat c.log 
      lxc-start 20161115170754.493 INFO     lxc_start_ui - tools/lxc_start.c:main:264 - using rcfile /home/pietro/.local/share/lxc/rcom/config
      lxc-start 20161115170754.495 WARN     lxc_confile - confile.c:config_pivotdir:1879 - lxc.pivotdir is ignored.  It will soon become an error.
      lxc-start 20161115170754.496 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 100000 range 65536
      lxc-start 20161115170754.496 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 100000 range 65536
      lxc-start 20161115170754.496 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 4
      lxc-start 20161115170754.499 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:797 - Attempting to set proc title to [lxc monitor] /home/pietro/.local/share/lxc rcom
      lxc-start 20161115170754.499 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:402 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:567 - Adding native rule for reject_force_umount action 0.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:251 - Setting Seccomp rule to reject force umounts.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:570 - Adding compat rule for reject_force_umount action 0.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:251 - Setting Seccomp rule to reject force umounts.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:402 - processing: .[all].
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:402 - processing: .kexec_load errno 1.
      lxc-start 20161115170754.499 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 4
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:567 - Adding native rule for kexec_load action 327681.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:570 - Adding compat rule for kexec_load action 327681.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:402 - processing: .open_by_handle_at errno 1.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:567 - Adding native rule for open_by_handle_at action 327681.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:570 - Adding compat rule for open_by_handle_at action 327681.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:402 - processing: .init_module errno 1.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:567 - Adding native rule for init_module action 327681.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:570 - Adding compat rule for init_module action 327681.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:402 - processing: .finit_module errno 1.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:567 - Adding native rule for finit_module action 327681.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:570 - Adding compat rule for finit_module action 327681.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:402 - processing: .delete_module errno 1.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:567 - Adding native rule for delete_module action 327681.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:570 - Adding compat rule for delete_module action 327681.
      lxc-start 20161115170754.499 INFO     lxc_seccomp - seccomp.c:parse_config_v2:580 - Merging in the compat Seccomp ctx into the main one.
      lxc-start 20161115170754.500 DEBUG    lxc_start - start.c:setup_signal_fd:290 - sigchild handler set
      lxc-start 20161115170754.500 DEBUG    console - console.c:lxc_console_peer_default:469 - no console peer
      lxc-start 20161115170754.501 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/2e6157b106fc36fb//home/pietro/.local/share/lxc
      lxc-start 20161115170754.566 INFO     lxc_start - start.c:lxc_init:489 - 'rcom' is initialized
      lxc-start 20161115170754.566 DEBUG    lxc_start - start.c:__lxc_start:1327 - Not dropping cap_sys_boot or watching utmp
      lxc-start 20161115170754.566 INFO     lxc_start - start.c:resolve_clone_flags:1014 - Cloning a new user namespace
      lxc-start 20161115170754.566 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for rcom
      lxc-start 20161115170754.570 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1663 - cgroup 'devices.allow' set to 'b 179:0 rwm'
      lxc-start 20161115170754.570 INFO     lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1667 - cgroup has been setup
      lxc-start 20161115170754.698 NOTICE   lxc_start - start.c:do_start:778 - switching to gid/uid 0/0 in new user namespace
      lxc-start 20161115170754.698 DEBUG    lxc_conf - conf.c:setup_rootfs:1215 - mounted '/home/pietro/.local/share/lxc/rcom/rootfs' on '/usr/lib/x86_64-linux-gnu/lxc'
      lxc-start 20161115170754.698 INFO     lxc_conf - conf.c:setup_utsname:843 - 'rcom' hostname has been setup
      lxc-start 20161115170754.698 DEBUG    lxc_conf - conf.c:setup_hw_addr:2146 - mac address '00:16:3e:9b:c3:eb' on 'eth0' has been setup
      lxc-start 20161115170754.699 DEBUG    lxc_conf - conf.c:setup_netdev:2373 - 'eth0' has been setup
      lxc-start 20161115170754.699 INFO     lxc_conf - conf.c:setup_network:2394 - network has been setup
      lxc-start 20161115170754.699 INFO     lxc_conf - conf.c:mount_autodev:1072 - Mounting container /dev
      lxc-start 20161115170754.700 INFO     lxc_conf - conf.c:mount_autodev:1095 - Mounted tmpfs onto /usr/lib/x86_64-linux-gnu/lxc/dev
      lxc-start 20161115170754.700 INFO     lxc_conf - conf.c:mount_autodev:1113 - Mounted container /dev
      lxc-start 20161115170754.701 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /sys/fs/fuse/connections on /usr/lib/x86_64-linux-gnu/lxc/sys/fs/fuse/connections to respect bind or remount options
      lxc-start 20161115170754.701 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /sys/fs/fuse/connections was 4096, required extra flags are 0
      lxc-start 20161115170754.701 DEBUG    lxc_conf - conf.c:mount_entry:1681 - mountflags already was 4096, skipping remount
      lxc-start 20161115170754.701 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/sys/fs/fuse/connections' on '/usr/lib/x86_64-linux-gnu/lxc/sys/fs/fuse/connections', type 'none'
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /sys/kernel/debug on /usr/lib/x86_64-linux-gnu/lxc/sys/kernel/debug to respect bind or remount options
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /sys/kernel/debug was 4096, required extra flags are 0
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1681 - mountflags already was 4096, skipping remount
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/sys/kernel/debug' on '/usr/lib/x86_64-linux-gnu/lxc/sys/kernel/debug', type 'none'
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /sys/kernel/security on /usr/lib/x86_64-linux-gnu/lxc/sys/kernel/security to respect bind or remount options
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /sys/kernel/security was 4110, required extra flags are 14
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/sys/kernel/security' on '/usr/lib/x86_64-linux-gnu/lxc/sys/kernel/security', type 'none'
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /sys/fs/pstore on /usr/lib/x86_64-linux-gnu/lxc/sys/fs/pstore to respect bind or remount options
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /sys/fs/pstore was 4110, required extra flags are 14
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/sys/fs/pstore' on '/usr/lib/x86_64-linux-gnu/lxc/sys/fs/pstore', type 'none'
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted 'mqueue' on '/usr/lib/x86_64-linux-gnu/lxc/dev/mqueue', type 'mqueue'
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /dev/console on /usr/lib/x86_64-linux-gnu/lxc/dev/console to respect bind or remount options
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /dev/console was 4098, required extra flags are 2
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/dev/console' on '/usr/lib/x86_64-linux-gnu/lxc/dev/console', type 'none'
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /dev/full on /usr/lib/x86_64-linux-gnu/lxc/dev/full to respect bind or remount options
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /dev/full was 4098, required extra flags are 2
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/dev/full' on '/usr/lib/x86_64-linux-gnu/lxc/dev/full', type 'none'
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /dev/null on /usr/lib/x86_64-linux-gnu/lxc/dev/null to respect bind or remount options
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /dev/null was 4098, required extra flags are 2
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/dev/null' on '/usr/lib/x86_64-linux-gnu/lxc/dev/null', type 'none'
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /dev/random on /usr/lib/x86_64-linux-gnu/lxc/dev/random to respect bind or remount options
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /dev/random was 4098, required extra flags are 2
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/dev/random' on '/usr/lib/x86_64-linux-gnu/lxc/dev/random', type 'none'
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /dev/tty on /usr/lib/x86_64-linux-gnu/lxc/dev/tty to respect bind or remount options
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /dev/tty was 4098, required extra flags are 2
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/dev/tty' on '/usr/lib/x86_64-linux-gnu/lxc/dev/tty', type 'none'
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /dev/urandom on /usr/lib/x86_64-linux-gnu/lxc/dev/urandom to respect bind or remount options
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /dev/urandom was 4098, required extra flags are 2
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/dev/urandom' on '/usr/lib/x86_64-linux-gnu/lxc/dev/urandom', type 'none'
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /dev/zero on /usr/lib/x86_64-linux-gnu/lxc/dev/zero to respect bind or remount options
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /dev/zero was 4098, required extra flags are 2
      lxc-start 20161115170754.702 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/dev/zero' on '/usr/lib/x86_64-linux-gnu/lxc/dev/zero', type 'none'
      lxc-start 20161115170754.702 INFO     lxc_conf - conf.c:mount_entry:1646 - failed to mount '/sys/firmware/efi/efivars' on '/usr/lib/x86_64-linux-gnu/lxc/sys/firmware/efi/efivars' (optional): No such file or directory
      lxc-start 20161115170754.742 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /proc/sys/fs/binfmt_misc on /usr/lib/x86_64-linux-gnu/lxc/proc/sys/fs/binfmt_misc to respect bind or remount options
      lxc-start 20161115170754.742 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /proc/sys/fs/binfmt_misc was 4096, required extra flags are 0
      lxc-start 20161115170754.742 DEBUG    lxc_conf - conf.c:mount_entry:1681 - mountflags already was 4096, skipping remount
      lxc-start 20161115170754.742 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/proc/sys/fs/binfmt_misc' on '/usr/lib/x86_64-linux-gnu/lxc/proc/sys/fs/binfmt_misc', type 'none'
      lxc-start 20161115170754.742 INFO     lxc_conf - conf.c:mount_file_entries:1927 - mount points have been setup
      lxc-start 20161115170754.742 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.mount.hook' for container 'rcom', config section 'lxc'
      lxc-start 20161115170754.753 INFO     lxc_conf - conf.c:fill_autodev:1141 - Creating initial consoles under container /dev
      lxc-start 20161115170754.753 INFO     lxc_conf - conf.c:fill_autodev:1152 - Populating container /dev
      lxc-start 20161115170754.753 INFO     lxc_conf - conf.c:fill_autodev:1189 - Populated container /dev
      lxc-start 20161115170754.753 INFO     lxc_conf - conf.c:setup_dev_console:1437 - console has been setup
      lxc-start 20161115170754.753 INFO     lxc_utils - utils.c:mount_proc_if_needed:1776 - I am 1, /proc/self points to '1'
      lxc-start 20161115170754.781 DEBUG    lxc_conf - conf.c:setup_rootfs_pivot_root:1050 - pivot_root syscall to '/usr/lib/x86_64-linux-gnu/lxc' successful
      lxc-start 20161115170754.783 DEBUG    lxc_conf - conf.c:lxc_create_tty:3310 - allocated pty '/dev/pts/0' (9/12)
      lxc-start 20161115170754.783 DEBUG    lxc_conf - conf.c:lxc_create_tty:3310 - allocated pty '/dev/pts/1' (14/15)
      lxc-start 20161115170754.783 DEBUG    lxc_conf - conf.c:lxc_create_tty:3310 - allocated pty '/dev/pts/2' (16/17)
      lxc-start 20161115170754.783 DEBUG    lxc_conf - conf.c:lxc_create_tty:3310 - allocated pty '/dev/pts/3' (18/19)
      lxc-start 20161115170754.783 INFO     lxc_conf - conf.c:lxc_create_tty:3321 - tty's configured
      lxc-start 20161115170754.783 INFO     lxc_conf - conf.c:setup_tty:995 - 4 tty(s) has been setup
      lxc-start 20161115170754.783 INFO     lxc_conf - conf.c:setup_personality:1393 - set personality to '0x0'
      lxc-start 20161115170754.783 DEBUG    lxc_conf - conf.c:setup_caps:2057 - drop capability 'mac_admin' (33)
      lxc-start 20161115170754.783 DEBUG    lxc_conf - conf.c:setup_caps:2057 - drop capability 'mac_override' (32)
      lxc-start 20161115170754.783 DEBUG    lxc_conf - conf.c:setup_caps:2057 - drop capability 'sys_time' (25)
      lxc-start 20161115170754.783 DEBUG    lxc_conf - conf.c:setup_caps:2057 - drop capability 'sys_module' (16)
      lxc-start 20161115170754.783 DEBUG    lxc_conf - conf.c:setup_caps:2057 - drop capability 'sys_rawio' (17)
      lxc-start 20161115170754.783 DEBUG    lxc_conf - conf.c:setup_caps:2066 - capabilities have been setup
      lxc-start 20161115170754.783 NOTICE   lxc_conf - conf.c:lxc_setup:3858 - 'rcom' is setup.
      lxc-start 20161115170754.783 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1658 - No such file or directory - Error setting devices.allow to b 179:0 rwm for rcom
      lxc-start 20161115170754.783 ERROR    lxc_start - start.c:lxc_spawn:1227 - failed to setup the devices cgroup for 'rcom'
      lxc-start 20161115170754.783 ERROR    lxc_start - start.c:__lxc_start:1354 - failed to spawn 'rcom'
      lxc-start 20161115170754.822 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'rcom', config section 'lxc'
      lxc-start 20161115170755.324 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
      lxc-start 20161115170800.329 ERROR    lxc_start_ui - tools/lxc_start.c:main:344 - The container failed to start.
      lxc-start 20161115170800.329 ERROR    lxc_start_ui - tools/lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 20161115170800.329 ERROR    lxc_start_ui - tools/lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.
xx@xx:~$

**Comment by pedr000000** [comment]
Hi,

No hope ?

**Comment by brauner** [comment]
Can you please run `export LXC_DEBUG_CGFSNG=1` and then do `lxc-start -n you-actual-containername` in the same shell and paste the output you receive?

**Comment by pedr000000** [comment]
$ lxc-start -n rcom
basecginfo is 11:cpuset:/
10:memory:/user.slice
9:devices:/user.slice
8:pids:/user.slice/user-1000.slice/session-c2.scope
7:freezer:/user/pietro/1
6:blkio:/user.slice
5:hugetlb:/
4:cpu,cpuacct:/user.slice
3:perf_event:/
2:net_cls,net_prio:/
1:name=systemd:/user.slice/user-1000.slice/session-c2.scope

kernel subsystem 0: cpuset
kernel subsystem 1: memory
kernel subsystem 2: devices
kernel subsystem 3: pids
kernel subsystem 4: freezer
kernel subsystem 5: blkio
kernel subsystem 6: hugetlb
kernel subsystem 7: cpu
kernel subsystem 8: cpuacct
kernel subsystem 9: perf_event
kernel subsystem 10: net_cls
kernel subsystem 11: net_prio
named subsystem 0: name=systemd
lxc-start: tools/lxc_start.c: main: 344 The container failed to start.
lxc-start: tools/lxc_start.c: main: 346 To get more details, run the container in foreground mode.
lxc-start: tools/lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.

**Comment by brauner** [comment]
Ok, so apart from some weirdness around your initial cgroup setup, you're running an unprivileged container which essentially means that allowing anything in `/sys/fs/cgroup/devices/*` won't help you. What you probably want to do is to `sudo setfacl -m "u:100000:rw" /dev/path/and/name_of_your_device` and then create an `lxc.mount.entry` for that device in your containers config:

```
lxc.mount.entry=/dev/path/and/name_of_your_device dev/path/and/name_of_your_device none bind,create=dir 0 0
```

**Comment by pedr000000** [comment]
Hi,

It now complains because of :

   ```
lxc.mount.entry=/dev/mmcblk0 dev/flash none bind,create=dir 0 0
   lxc-start 20161116170702.880 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/home/pietro/shared-rcom/' on '/usr/lib/x86_64-linux-gnu/lxc//home/build/shared/', type 'none,rw'
      lxc-start 20161116170702.901 ERROR    lxc_utils - utils.c:safe_mount:1742 - Not a directory - Failed to mount /dev/mmcblk0 onto /usr/lib/x86_64-linux-gnu/lxc/dev/flash
      lxc-start 20161116170702.901 ERROR    lxc_conf - conf.c:mount_entry:1650 - Not a directory - failed to mount '/dev/mmcblk0' on '/usr/lib/x86_64-linux-gnu/lxc/dev/flash'

```

I would need to have access to the block device directly, is a privileged container the quickest way to achieve the goal ?

**Comment by brauner** [comment]
If it's a file, you need to use:

```
lxc.mount.entry=/dev/mmcblk0 dev/flash none bind,create=file 0 0 
```

**Comment by brauner** [comment]
And yes, a privileged container would be easier from a configuration point of view but also a lot less safe.

**Comment by pedr000000** [comment]
I can see the device under dev.

The is problem now is that :
```
# ls -la /dev/mmcblk0 
brw-rw---- 1 nobody nogroup 179, 0 Nov 16 17:24 /dev/mmcblk0

# fdisk -l /dev/mmcblk0 
Cannot open /dev/mmcblk0

```
Is there a quick fix for it ? As alternative can I "upgrade" my container to be privileged ?

Thanks a lot, all this it must exhausting for you !

**Comment by brauner** [comment]
As I said, you can set `acl` permissions to allow access to the device for you containers user. This must be done as a privileged user on the host so you would do:

```
sudo setfacl -m "u:100000:rw" /dev/mmcblk0
```

for you containers root user which has uid `0` in the container and uid `100000` outside the container. If you wanted to grant access for you unprivileged container user with uid `1000` inside the container with uid `101000` outside the container you'd have to use:

```
sudo setfacl -m "u:101000:rw" /dev/mmcblk0
```

**Comment by pedr000000** [comment]
Sorry, I had plugged out and back again the flash card, it now works fine.

Thanks a lot, really.

**Comment by pedr000000** [comment]
I am sorry to hammer but it is strictly relates, how do I give permission to the container to mount partitions I have created on the block device ?
