### ISSUE TITLE
OverlayFS entry in lxc.mount not working, blocking boot

### ISSUE THREAD

**Issue by oxwivi** [lxc/lxc#1292]
I've added an OverlayFS entry according to this [lxc-devel mail](https://lists.linuxcontainers.org/pipermail/lxc-devel/2015-October/012536.html) my Google-fu dug up:
```
# lxc-devel example
lxc.mount.entry = /lower merged overlay lowerdir=/lower,upper=/upper,workdir=/workdir,create=dir
# my entry
lxc.mount.entry = /usr/share/fonts/ usr/share/fonts/ overlay lowerdir=/usr/share/fonts/,upper=/home/user/.cache/libertine-container/closed/rootfs/usr/share/fonts/,workdir=/home/user/.cache/libertine-container/closed/rootfs/usr/share/tmp/,create=dir
```
This is messing with an automatically created unprivileged Libertine container. I can't get it to spit error output or find any logs, so I can't diagnose with that.

**Comment by oxwivi** [comment]
I've previously tried with pure `fstab` entry, but that didn't work, and again no logs to help diagnose that.

**Comment by brauner** [comment]
Mountpoints inside the container's rootfs are not allowed for `uppderdir` and `workdir`. They must be pointing to directories under the containers directory (Usually one step above the rootfs.).

**Comment by oxwivi** [comment]
I don't quite understand what you mean. Can you give me an example? Or just correct my `entry` if it's salvageable.

**Comment by oxwivi** [comment]
@brauner, I managed to get it to work by simply adding the `bind` option, hence the end result:
```
lxc.mount.entry = /usr/share/fonts/ usr/share/fonts/ overlay lowerdir=/usr/share/fonts/,upper=/home/user/.cache/libertine-container/closed/rootfs/usr/share/fonts/,workdir=/home/user/.cache/libertine-container/closed/rootfs/usr/share/tmp/,bind,create=dir

$ ls -al /usr/share/fonts
total 0
drwxr-xr-x 1 root root   56 Oct 13 00:47 .
drwxr-xr-x 1 root root 5898 Nov  1 14:41 ..
drwxr-xr-x 1 root root  150 Oct 13 00:45 cmap
drwxr-xr-x 1 root root   34 Oct 13 00:47 opentype
drwxr-xr-x 1 root root  444 Nov  1 14:22 truetype
drwxr-xr-x 1 root root   14 Oct 13 00:46 type1
drwxr-xr-x 1 root root   44 Oct 13 00:47 X11

$ libertine-launch closed ls -al /usr/share/fonts
total 0
drwxr-xr-x 1 nobody nogroup   56 Oct 13 00:47 .
drwxr-xr-x 1 root   root    1426 Nov 12 14:00 ..
drwxr-xr-x 1 nobody nogroup  150 Oct 13 00:45 cmap
drwxr-xr-x 1 nobody nogroup   34 Oct 13 00:47 opentype
drwxr-xr-x 1 nobody nogroup  444 Nov  1 14:22 truetype
drwxr-xr-x 1 nobody nogroup   14 Oct 13 00:46 type1
drwxr-xr-x 1 nobody nogroup   44 Oct 13 00:47 X11
```

**Comment by oxwivi** [comment]
Unfortunately, I discovered late that, while the `lxc.mount` line worked, it did not allow the container to write to the the `upperdir`. Am I doing something wrong or is LXC inherently incapable?

**PS** I later changed the line to the following to same effect:

**Comment by oxwivi** [comment]
Unfortunately, I discovered late that, while the lxc.mount line worked, it did not allow the container to write to the the upperdir. Am I doing something wrong or is LXC inherently incapable?

**PS** I later changed the line to the following to same effect:
```
lxc.mount.entry = /usr/share/fonts/ usr/share/fonts/ overlay lowerdir=/usr/share/fonts/,upper=usr/share/fonts/,workdir=usr/share/tmp/,bind,create=dir
```

**Comment by brauner** [comment]
You're specifying the mount options wrong. Overlay mounts do not need the `bind` option, `upper` is actually called `upperdir` and `LXC` places restrictions on where `upperdir` and `workdir` can be created. Both directories can only be located under the containers directory, not anywhere else. So `upperdir=/path/to/container/directory/ovl/a`, `workdir=/path/to/container/directory/ovl/b`:

```
lxc.mount.entry = /usr/share/fonts/ usr/share/fonts/ overlay lowerdir=/usr/share/fonts/,upperdir=/home/chb/.local/share/lxc/yak/ovl/a,workdir=/home/chb/.local/share/lxc/yak/ovl/b
```

Additionally,  `overlay` requires that `upperdir` and `workdir` be under the same mountpoint.

The second problem about non being able to write to the merged directory stems from the fact that you're using an unprivileged container that has not been started by root. This means that you're lacking `CAP_SYS_ADMIN` in the initial `user namespace` and so you're not allowed to write there. You can cicumvent this by either using a root-owned unprivileged container or by granting `acl` permissions on the directory on the host. In any case, there is nothing `LXC` can do about this. :)

**Comment by oxwivi** [comment]
Why are you in a hurry to close the issue? Now that I can no longer reopen it, I don't expect any response, as I've seen with other issues I opened. I'll leave this comment as a protestation for not actually resolving the issue.

Like I said, I originally set `upper` as `upperdir=/home/user/.cache/libertine-container/closed/rootfs/usr/share/fonts/` and `work` as `workdir=/home/user/.cache/libertine-container/closed/rootfs/usr/share/tmp/`. It did not work without `bind` option. I reverted to this line right now and removed `bind`, it doesn't work. I add `bind`, it works.
```
lxc.mount.entry = /usr/share/fonts/ usr/share/fonts/ overlay lowerdir=/usr/share/fonts/,upperdir=/home/user/.cache/libertine-container/closed/rootfs/usr/share/fonts/,workdir=/home/user/.cache/libertine-container/closed/rootfs/usr/share/tmp/,bind,create=dir
```
The `merged` directory is within the container's `rootdir` itself. How the heck does it not have permission to write?

**Comment by brauner** [comment]
Maybe I did not explain myself well enough.

- You definitely need not add `bind`. If you add `bind` your getting a bind-mount not an overlay mount. The additional mount options like `lowerdir` and `upperdir` will then be ignored by the kernel.
- The correct identifiers are indeed `lowerdir` and `upperdir` so keep them.
- This is important: As I said before:

> Mountpoints inside the container's rootfs are not allowed for uppderdir and workdir. They must be pointing to directories under the containers directory (Usually one step above the rootfs.).

So your mount line could e.g. be:
```
lxc.mount.entry = /usr/share/fonts/ usr/share/fonts/ overlay lowerdir=/usr/share/fonts/,upperdir=/home/user/.cache/libertine-container/closed/ovl/b,workdir=/home/user/.cache/libertine-container/closed/ovl/b,bind,create=dir
```

> The merged directory is within the container's rootdir itself. How the heck does it not have permission to write?
Ok, I think you're not quite clear about what unprivileged containers do. An unprivileged containers maps the uids used inside the container to different uids outside the container to provide additional security and isolation from the host. This has the consequence, that if you mount a directory from the host inside the container, that you cannot write to it since you do not own these files and directories or lack so-called capabilities on the host. There is nothing `LXC` itself can do about this. This is purely the kernels area.

**Comment by oxwivi** [comment]
Thank you for clarifying these. But did you see the example I mentioned in the last comment? I use absolute paths for both `upper` and `work`, but if I remove `bind` container doesn't even boot.

And regarding the write permissions, isn't the point of defining the `upper` directory to be something the user can write to, without touching the `lower`, the whole point of OverlayFS?

**Comment by brauner** [comment]
> Thank you for clarifying these. But did you see the example I mentioned in the last comment? I use absolute paths for both upper and work, but if I remove bind container doesn't even boot.

Yes, but that is to be expected since you use the wrong name for upper and work and because you're giving a path inside of the containers rootfs which is not allowed for security reasons. I tried to give you a fully functional line.

> And regarding the write permissions, isn't the point of defining the upper directory to be something the user can write to, without touching the lower, the whole point of OverlayFS?

Yes, it should actually work. So if you could try booting with the mount line I gave you and check.

**Comment by oxwivi** [comment]
I booted successfully with the following line:
```
lxc.mount.entry = /usr/share/fonts/ usr/share/fonts/ overlay lowerdir=/usr/share/fonts/,upperdir=/home/user/.cache/libertine-container/closed/ovl/a,workdir=/home/user/.cache/libertine-container/closed/ovl/b,create=dir
```
All the `lower`'s files are clearly accessible. But the success ends there. Still cannot write.

**Comment by oxwivi** [comment]
And there is no way I can use variables like `$HOME` and `$LXC_NAME` to define path, is there?

**Comment by brauner** [comment]
Can you show the output of:
```
ls -al /home/user/.cache/libertine-container/closed/ovl/
```

**Comment by oxwivi** [comment]
```
$ ls -al /home/user/.cache/libertine-container/closed/ovl/
total 0
drwxr-xr-x 1 100000   100000  4 Dec  2 01:46 .
drwxrwx--- 1 100000 virtouni 30 Dec  2 01:46 ..
drwxr-xr-x 1 100000   100000  0 Dec  2 01:46 a
drwxr-xr-x 1 100000   100000  8 Dec  2 01:46 b
```

**Comment by brauner** [comment]
So I looked at the `overlay` kernel code again and I was right the first time: You will not be able to make any changes. This is a kernel enforced security mechanism. Otherwise you could e.g. modify setuid files to do evil things. Again, this is a kernel security check and not related to `LXC`.

**Comment by oxwivi** [comment]
Is that code relevant to OverlayFS or mechanisms utilized by LXC?

**Comment by brauner** [comment]
Well, `overlay` is a `filesystem` that is part of the upstream kernel and `LXC` is using this kernel feature when setting up overlay mounts. There is no other way to use the official `overlay` file system.

If you're really set on making this work you can switch to privileged containers. Although that will cause you to loose a lot of security.

**Comment by oxwivi** [comment]
Is it possible to do the reverse? `lower` being relative address within container, and `upper` some point outside the container, in the host's root?
