### ISSUE TITLE
lxc Container does not start

### ISSUE THREAD

**Issue by ha1987** [lxc/lxc#1298]
I am trying to run an lxc container on Ubuntu 16.10 with the following configurations:

    lxc.utsname = cont
    lxc.network.type = veth
    lxc.network.flags = up
    lxc.network.link = bridge
    lxc.network.ipv4 = 10.0.0.10/24

The bridge is already up and running. I create the container using xenial template as following:

    lxc-create -f lxc-veth.conf -t download -n cont -- --dist ubuntu --release xenial --arch amd64 --no-validate

Then I start the container:

    lxc-start -n cont /bin/bash --logfile log.txt

I get the following errors:

      lxc-start 20161114114122.026 ERROR    lxc_start - start.c:start:1439 - No such file or directory - failed to exec /lib/lxc cont
      lxc-start 20161114124122.026 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
      lxc-start 20161114124122.026 ERROR    lxc_start - start.c:__lxc_start:1354 - failed to spawn 'cont'
      lxc-start 20161114124127.568 ERROR    lxc_start_ui - tools/lxc_start.c:main:344 - The container failed to start.
      lxc-start 20161114124127.568 ERROR    lxc_start_ui - tools/lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 20161114124127.568 ERROR    lxc_start_ui - tools/lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.

What is the source of the problem?

**Comment by brauner** [comment]
Well, you seemed to have accidently or on pupose passed an init command to `lxc-start`. Usually, when starting system container, you'd expect it to exec `/sbin/init` and not `/lib/lxc`. This can easily happen if you'd do something like `lxc-start -n cont -- /lib/lxc` so something got messed up in terms of your `stdin`.

**Comment by ha1987** [comment]
It is pretty strange because I did not pass anything to `lxc-start` in the command-line except for the `bash`. I am executing all my commands in sudo mode. I destroyed my previous lxc container and created it again using the previous supplied command but I am still having the same problem.

**Comment by brauner** [comment]
Well, I don't know why you'd want the `/bin/bash` but it's legitimate, so it's ok but you should call it as:

```
lxc-start -n cont --logfile bla.txt -- /bin/bash
```

**Comment by brauner** [comment]
I assume that you issue resolved given you thumbs-up. So closing this.
