### ISSUE TITLE
LXC container network interface in promiscuous mode

### ISSUE THREAD

**Issue by rsd** [lxc/lxc#1304]
Is it possible to have the veth interface in promiscuous mode?
For example to have network monitoring tools in a container.

It seems that phys would let it to be done, but the container would own the device.

**Comment by stgraber** [comment]
The container should certainly be able to switch its side of the veth to promisc mode, i'm not sure whether the kernel will replicate this change to the other side of the pair though... If not, then you'd need to manually change the host side for this to work.
