### ISSUE TITLE
lxc-ls don't list running containers

### ISSUE THREAD

**Issue by lessmian** [lxc/lxc#133]
Hi.

After upgrade lxc from 0.7 to 0.9 i realized that lxc-list don't show running containers. I compared both scripts and old version creates container list based on /proc stuff when new version does glob on /var/lib/lxc/*/config. In my environment i don't use lxc-create, so i don't have any objects unde /var/lib/lxc/. In other hand, lxc-info show info about that container. I think it's bug and lxc-ls works with bad assumptions. It should list all containers, no matter it has /val/lib/lxc/CN dir or no.

lxc-ls v0.9:
:~# /usr/bin/lxc-ls

lxc-ls v0.7:
:~# /usr/local/bin/lxc-ls 
cloudmon

:~# lxc-info -n cloudmon
state:   RUNNING
pid:      2649

**Comment by coolavibv** [comment]
I am also facing same problem with lxc-ls:
#lxc-execute -n container_name -- sleep 100

For listing all containers we have lxc-ls command and for seeing active containers we have lxc-ls --active command. But both of them does not give any output. Whereas lxc-info -n container_name gives all the relevant information about the container. 
root@avinash-OptiPlex-3020:/home/avinash# lxc-info -n guest
Name:           guest
State:          RUNNING
PID:            3211
CPU use:        0.00 seconds
BlkIO use:      60.00 KiB
Memory use:     816.00 KiB
KMem use:       0 bytes

Can anybody sort out why this lxc-ls command not listing containers?
P.S. I am using ubuntu 14.04 and lxc 2.0.0.

**Comment by coolavibv** [comment]
Please refer to https://github.com/lxc/lxc/issues/68.
