### ISSUE TITLE
lxc-create (from cache) does not reconsider host networking changes

### ISSUE THREAD

**Issue by jmoudy** [lxc/lxc#1330]
Host was created from 
% lxc-create -n ubuntu -t ubuntu

Subsequently, I altered the host network to bridge br0 and eth0 so I could expose the container to my primary network.  I adjusted the /var/lib/lxc/<container>/config with the appropriate ip.network.ipv4 address and gateway.

The container could not resolve addresses, but could route the traffic. Debugging showed the /etc/resolvconf/resolv.conf.d was not properly configured. (I think tail should have been linked to original).

Recreated the container with:
% lxc-create -n ubuntu -t ubuntu -- -r trusty --flush-cache 
Made the same change to /var/lib/lxc/<container>/config again, and the container was able to resolve the names properly. 

It appears the network get configured and stored in the containers /var/cache/lxc directory. Subsequent creations of the containers do not re-configure the network but rather draw from the cache which is no longer correct for the context of the cache'd containers, and the container fails to work properly.

Suggestion, can a list of the host files that were considered when populating/configuring the cached container be cataloged and checked. The user could then get a warning that the hosts' configuration has changed and have the option to flush-cache or not.

Jim

**Comment by brauner** [comment]
To be honest, that sounds like adding unnecessary complexity, especially because you can circumvent this issue with `--flush-cache` so I'm not sure that this is worth the trouble.

**Comment by stgraber** [comment]
Those templates aren't shipped in LXC anymore.
