### ISSUE TITLE
File descriptor leak

### ISSUE THREAD

**Issue by oddjobz** [lxc/lxc#1345]
With regards to;
https://github.com/lxc/lxc/commit/81f466d05f2a89cb4f122ef7f593ff3f279b165c

src/lxc/attach.c, line 978
It would "appear" that "labelfd" is never closed.

I'm seeing my application crash after doing "many" attaches, on inspection, "/proc/<pid>/fd" is full of;
lrwx------ 1 root root 64 Dec  8 17:53 987 -> /proc/10349/attr/current
...

**Comment by brauner** [comment]
Closes #1345.

**Comment by oddjobz** [comment]
Well, that's certainly a concise reply (!)

**Comment by brauner** [comment]
Sorry, intended to write this as comment under the pr that fixes this issue not under the issue itself.

**Comment by oddjobz** [comment]
Hi Guys, just a quick note; this was a *critical* fix in that anyone using python3-lxc over time will crash unpredictably when they run out of file handles (for me, it's a matter of minutes). 3 weeks on, and it doesn't appear to be present in the stable PPA. IMHO, might be worth forcing a push ... (?)

**Comment by hallyn** [comment]
Is there a launchpad bug for this, assuming this bug affected the packaged version?

If the archive versions are affected, you can use the ppa versions to get the fix, but agreed the archive versions should be fixed asap.

**Comment by oddjobz** [comment]
Mmm, I'm using the daily which seems to contain the fix, but the latest stable-PPA up there was compiled before the fix was submitted. So, I'm thinking that either nobody is using a version of python-lxc since the bug was introduced, or there are lots of apps out there literally just waiting to lock up.
