### ISSUE TITLE
Thread lockout issue ...

### ISSUE THREAD

**Issue by oddjobz** [lxc/lxc#1349]
I had a number of problems with my application locking up for seconds (or minutes) and it appears to be due to my use of threads. If I call "container.clone" for example, which I expect to take 20 seconds, I call it in a thread, however the rest of the application still locks up for the duration. If on the other hand I spawn a process and run "lxc-clone" in that thread, it works fine. (which is what I'm now doing for everything that doesn't warrant "attach_wait")

It appears that where "attach_wait" calls;
```python3
        Py_BEGIN_ALLOW_THREADS
        ret = lxc_wait_for_pid_status(pid);
        Py_END_ALLOW_THREADS
```
Nothing else does ...is there any chance of wrapping all other potentially time consuming operations in ALLOW_THREADS (and I'm thinking, start/stop/clone/destroy/copy specifically) , or is there a reason why this hasn't / can't be done ??

**Comment by brauner** [comment]
You can make a PR against the lxc-python3 repo in the lxc github namespace. Sorry for the late reply we're currently cleaning up a lot of issues.
