### ISSUE TITLE
Add --format=json for more commands

### ISSUE THREAD

**Issue by larsemil** [lxc/lxc#1350]
in issue #1789 and the merge request with commit hash cddaada(pr #1876) the --format=json was added for lxc list.

Similar should exist for subcommand: lxc info

**Comment by larsemil** [comment]
@cmars could you have a looksie? You did really good job on the lxc list command. 👍

**Comment by stgraber** [comment]
Wrong project, that's a LXD command, not a LXC one, so should be filed against github.com/lxc/lxd.
