### ISSUE TITLE
Fedora template maintenance

### ISSUE THREAD

**Issue by ganto** [lxc/lxc#1356]
I lately put some [effort](https://copr.fedorainfracloud.org/coprs/ganto/lxd/) in creating community packages for LXD on Fedora and therefore I also had a look at the `lxc-fedora` template in LXC. It's a very feature rich template that still works fine also with newer Fedora releases but it hasn't seen much love lately (maybe because of its complexity?).

To get know the template a bit better I ported the bootstrapping part for non-yum distributions from the currently used Fedora 20 squashfs image to the Fedora 24 image and therefore was able to get rid of some complexity (see my [fedora](https://github.com/ganto/lxc/tree/fedora) branch). By dropping `python` (`dnf` now requires `python-3`), `yum`, `rsyslog` and `chkconfig`, I was able to reduce the image size from 230MB to around 160MB, what I think is a big win.

However, the shift to `dnf` made me think of some issues with the current code paths that I would like to address here:

* Is it worth to put more effort in updating the `lxc-fedora` template or is this something that might not be widely used anymore with the availability of the Fedora [CloudImages](http://archives.fedoraproject.org/pub/fedora/linux/releases/24/CloudImages/x86_64/images/)?

 * Are there users which use this template to build containers of unsupported versions (non-`dnf`, non-`systemd`) of Fedora?

* Getting rid of all this compatibility code for old Fedora versions would simplify the template quite a bit. Would you be interested if I put some effort in doing this?

Please let me know what you think.

**Comment by brauner** [comment]
I would vote for getting rid of the complexity. (@stgraber)

**Comment by stgraber** [comment]
1) I don't think too many people use the fedora cloud images since there's no straightforward way to turn those into LXC containers (no template script). I'm not opposed changing lxc-fedora to just repack those images though.
2) It's hard to know what our users do, but I'd say it's certainly not worth keeping a lot of complexity for such corner cases.
3) Assuming that "old" here means no longer supported, I'm absolutely fine with removing that code.

**Comment by ganto** [comment]
Ok, thanks for your reply. I will work on a suggestion for a new template in the next few days and maybe also try out how this would work when converting a CloudImage.

**Comment by brauner** [comment]
The template has been completely reworked and merged. This can be closed.
