### ISSUE TITLE
gnutls dead code ?

### ISSUE THREAD

**Issue by ffontaine** [lxc/lxc#1359]
Hello,

lxc has 3 files that depends on HAVE_LIBGNUTLS (in utils.h, lxccontainer.c and utils.c).
However, this variable is never set even when gnutls is detected by configure:
AC_CHECK_LIB([gnutls], [gnutls_hash_fast], [enable_gnutls=yes], [enable_gnutls=no])
Indeed, enable_gnutls is only used to display a message.
Is this some kind code of dead code that should be removed?

If this is the case, I would also suggest to update https://linuxcontainers.org/fr/lxc/getting-started as libgnutls is listed as a recommended library for various checksumming.

Best Regards,

Fabrice

**Comment by stgraber** [comment]
The  HAVE_ defines are auto-generated by AC_CHECK_LIB and written to config.h

**Comment by ffontaine** [comment]
Thanks for your anwser, but actually HAVE_LIBGNUTLS is never written to config.h because you're overriding the default action-if-found of AC_CHECK_LIB by enable_gnutls=yes in:
AC_CHECK_LIB([gnutls], [gnutls_hash_fast], [enable_gnutls=yes], [enable_gnutls=no])

For other dependencies such as apparmor, you're managing this by calling AC_CHECK_LIB twice. I will send you a pull request that will correct this by adding an --enable-gnutls option which will be set to auto like the other dependencies.

**Comment by ffontaine** [comment]
Please review #1360
