### ISSUE TITLE
Impossible to build with --disable-capabilities if libcap sys/capability.h is present

### ISSUE THREAD

**Issue by ffontaine** [lxc/lxc#1361]
Currently, it is impossible to build lxc with --disable-capabilities if the user has libcap-dev installed on his system as:
- calls to cap_xxx functions in caps.c are not protected by HAVE_LIBCAP defines. The whole file is only protected by HAVE_SYS_CAPABILITY_H.
- AC_CHECK_LIB default action-if-found is overriden by [true] so HAVE_LIBCAP is never written to config.in

As a result, if the user specifies --disable-capabilities, lxc's configure will not include -lcap which will result in a link error as HAVE_SYS_CAPABILITY_H will nevertheless be true (as sys/capability.h will be found).

So I would suggest to at least protect all calls to cap_xxx functions by HAVE_LIBCAP. An other option would be to replace all HAVE_SYS_CAPABILITY_H defines by HAVE_LIBCAP defines.

What's your opinion on this?

**Comment by brauner** [comment]
I don't see a problem with this if this is true.
