### ISSUE TITLE
Comments in config break parser

### ISSUE THREAD

**Issue by johnlane** [lxc/lxc#1363]
As discussed on the [LXC mailing list](https://lists.linuxcontainers.org/pipermail/lxc-users/2016-December/012668.html), some config entries (not all) fail to parse on version 2.0.6 if they have trailing comments. They parse fine in version 2.0.4. It does not affect all config entries but I have experienced `lxc.tty` and `lxc.pts` failing.

That is to say a config entry like 

    lxc.tty=1 # comment

will cause the config parser to break with LXC version 2.0.6.

Steps to reproduce (on Arch Linux and as `root` for simplicity)

    # lxc-create -n playtime -t /usr/share/lxc/templates/lxc-archlinux
    # lxc-start -n playtime
    # lxc-stop -n playtime
    # echo 'lxc.tty=1 # comment' >> /var/lib/lxc/playtime/config
    # lxc-start -n playtime
    # lxc-stop -n playtime

Both work until step 5. Version 2.0.4 continues to work. Version 2.0.6 breaks with the below:

    lxc-start: parse.c: lxc_file_for_each_line: 57 Failed to parse config: lxc.tty=1 # comment
    lxc-start: tools/lxc_start.c: main: 279 Failed to create lxc_container

I used the [official Arch Linux LXC package](https://www.archlinux.org/packages/community/x86_64/lxc) for these tests.

* https://archive.archlinux.org/packages/l/lxc/lxc-1%3A2.0.6-2-x86_64.pkg.tar.xz
* https://archive.archlinux.org/packages/l/lxc/lxc-1%3A2.0.4-2-x86_64.pkg.tar.xz

**Comment by brauner** [comment]
Likely introduced by changes made to safely parse integer values where we check for invalid characters when parsing numbers.

**Comment by brauner** [comment]
I'm actually not sure about this. This behavior predates the integer parsing changes and can e.g. be also observed with `lxc.rootfs.backend`. So I'm not sure whether we want to add more complexity to the parser by detecting a comment after a valid configuration item. (ping @stgraber)

**Comment by stgraber** [comment]
So we technically only ever documented "#" as a token to make a whole line a comment, there is no mention in our documentation for "#" after a value as meaning the rest of the line is a comment.

I'm a bit concerned that in attempting to fix this we'll effectively end up breaking some other cases.
There is technically nothing wrong with you having a "#" in a path that you set in lxc.mount, lxc.mount.entry, lxc.rootfs, ...

Same goes with network interface names, utsname, ...

So I'm tempted to say that the right fix for this is documentation. Updating lxc.container.conf to make it even clearer that the only thing that we support is making a whole line a comment and that adding comments after a value is not supported, will lead to errors or potentially be interpreted literally by LXC.


I don't like that we ended up breaking some users when moving from 2.0.5 to 2.0.6, but the fact is that this was never supported and it was a bit of a miracle that it didn't cause crashes or other errors (it may still have caused part of the config from not being interpreted).

**Comment by brauner** [comment]
I agree with @stgraber about this. I checked and there are various places that complain about this way before `LXC 2.*.*`. The fact is that this just accidently happened to work so we should simply point out that it won't. Let's keep the parser simple.

**Comment by johnlane** [comment]
I'll just update my configs then. Thanks for looking at it so quickly.
