### ISSUE TITLE
Memory seems never released

### ISSUE THREAD

**Issue by mayasd** [lxc/lxc#1366]
Hi,
There are something I don't understand with LXC and memory. On a fresh LXC install (lxc 2.0.6 and lxcfs 2.0.5, Debian Jessie), I created a debian container.
On this container, I have a postgresql database. I executed a SELECT on a table, the request finishes correctly but all memory appear used and not released.

Container memory stats before sql request : https://paste.ubuntu.com/23693584/
Container memory stats after sql request : https://paste.ubuntu.com/23693595/

On LXC host I see memory used but it's cached : https://paste.ubuntu.com/23693535/

**Comment by brauner** [comment]
This is likely a `LXCFS` bug and not a `LXC` bug. Can you please close this issue here and reopen on https://github.com/lxc/lxcfs.

**Comment by mayasd** [comment]
Ok, no problem ;)
