### ISSUE TITLE
remaping user-ids in privileged container fails.

### ISSUE THREAD

**Issue by linas** [lxc/lxc#1369]
Using `lxc.id_map` in a root-owned container seems not to work.

I am trying to move a container, created as a user, and run it as root. If I don't use `lxc.id_map` the container starts fine, although the large user-land id's are visible, and so is not really "usable" in the intended sense. But altering the config to use `lxc.id_map`  prevents the container from starting, with a spew of `lxc_cgfsng cgroups/cgfsng.c` errors.

System: Debian unstable, as of today's date.So
```
$ lxc-info --version
2.0.6
$ cat /proc/version
Linux version 4.7.0-1-amd64 (debian-kernel@lists.debian.org) (gcc version 5.4.1 20160904 (Debian 5.4.1-2) ) #1 SMP Debian 4.7.6-1 (2016-10-07)
$ /sbin/cgmanager --version
cgmanager 0.41
$ zless /usr/share/doc/libpam-cgm/changelog.Debian.gz
cgmanager (0.41-2) unstable; urgency=medium

  * debian/rules: fix dpkg-buildpackage -A (Closes: #806004)

 -- Serge Hallyn <serge.hallyn@ubuntu.com>  Tue, 05 Apr 2016 00:10:20 -0500
```
As user, create a container (running ubuntu xenial, as it happens)  The config file is:
```
# Distribution configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.include = /usr/share/lxc/config/ubuntu.userns.conf
lxc.arch = x86_64

# Container specific configuration
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
# lxc.rootfs = /home/linas/.local/share/lxc/foo-base/rootfs
lxc.rootfs = /home2/linas/lxc-local-containers/foo-base/rootfs
# lxc.rootfs.backend = dir
lxc.utsname = foo-base

# Network configuration
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:1d:8e:d6
```
This is a minimal config only placing the rootfs where I have some disk space.  It runs fine (well, almost fine, I had to do some cgm fiddling to get it started, but once done, it starts reliably.  The cgm fiddling was this:
```
sudo apt-get install libpam-cgm
sudo cgm create all linas
sudo cgm chown all linas $(id -u) $(id -g)
cgm movepid all linas $$
```
The rootfs uses mapped id's just fine:  so for example:
```
$ ls -la rootfs
total 84
drwxrwxr-x 21 100000 linas  4096 Dec 30 12:03 .
drwxrwx---  4 100000 linas  4096 Dec 30 12:09 ..
drwxr-xr-x  2 100000 100000 4096 Nov 13 23:17 bin
drwxr-xr-x  2 100000 100000 4096 Apr 12  2016 boot
drwxr-xr-x  3 100000 100000 4096 Sep  5 22:57 dev
drwxr-xr-x 92 100000 100000 4096 Nov 16 01:41 etc
drwxr-xr-x  3 100000 100000 4096 Sep  5 22:57 home
...
```
and also
```
$ ls -la rootfs/home
total 12
drwxr-xr-x  3 100000 100000 4096 Sep  5 22:57 .
drwxrwxr-x 21 100000 linas  4096 Dec 30 12:03 ..
drwxr-xr-x  7 101000 101000 4096 Dec 30 11:10 ubuntu
```
so that looks normal.  Next, as root, a config file without the id mapping works fine:  
```
# Distribution configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.rootfs = /home2/linas/lxc-local-containers/foo-base/rootfs
lxc.utsname = foo-base

# Network configuration
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = lxcbr0
lxc.network.hwaddr = 00:16:3e:1d:1f:7f
```
The above config file is placed in `/var/lib/lxc/foo-base`, where it can be found (as opposed to the earlier config file, which lives in its default location `~/.local/share/lxc/foo-base` where userland finds it)

Sooo .. above config file boots fine, except that the user-ids are not remapped, which is unfortunate.  (Warning: booting it like that changes ownership perms of rootfs/tmp from 100000:100000 to root:root which is maybe undesirable ...)   Adding 
```
lxc.include = /usr/share/lxc/config/ubuntu.userns.conf
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
```
to the config file causes container not to boot.  The error spew is this:
```
# lxc-start -n foo-base --daemon --logfile bar
lxc-start: tools/lxc_start.c: main: 360 The container failed to start.
lxc-start: tools/lxc_start.c: main: 362 To get more details, run the container in foreground mode.
lxc-start: tools/lxc_start.c: main: 364 Additional information can be obtained by setting the --logfile and --logpriority options.
# cat bar
      lxc-start 20161230121338.395 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1310 - Path "/sys/fs/cgroup/systemd//lxc/foo-base" already existed.
      lxc-start 20161230121338.395 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1367 - No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/foo-base: No such file or directory
      lxc-start 20161230121338.395 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1310 - Path "/sys/fs/cgroup/systemd//lxc/foo-base-1" already existed.
      lxc-start 20161230121338.395 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1367 - No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/foo-base-1: No such file or directory
      lxc-start 20161230121338.395 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1310 - Path "/sys/fs/cgroup/systemd//lxc/foo-base-2" already existed.
      lxc-start 20161230121338.395 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1367 - No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/foo-base-2: No such file or directory
      lxc-start 20161230121338.395 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1310 - Path "/sys/fs/cgroup/systemd//lxc/foo-base-3" already existed.
      lxc-start 20161230121338.395 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1367 - No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/foo-base-3: No such file or directory
      lxc-start 20161230121338.395 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1310 - Path "/sys/fs/cgroup/systemd//lxc/foo-base-4" already existed.
      lxc-start 20161230121338.395 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1367 - No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/foo-base-4: No such file or directory
      lxc-start 20161230121338.403 ERROR    lxc_start - start.c:lxc_spawn:1163 - Failed to set up id mapping.
      lxc-start 20161230121338.460 ERROR    lxc_start - start.c:__lxc_start:1338 - Failed to spawn container "foo-base".
      lxc-start 20161230121339.007 ERROR    lxc_conf - conf.c:userns_exec_1:4374 - Error setting up child mappings
      lxc-start 20161230121339.007 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1274 - Error destroying /sys/fs/cgroup/systemd//lxc/foo-base-5
      lxc-start 20161230121339.011 ERROR    lxc_conf - conf.c:userns_exec_1:4374 - Error setting up child mappings
      lxc-start 20161230121339.011 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1274 - Error destroying /sys/fs/cgroup/cpu//lxc/foo-base-5
      lxc-start 20161230121339.016 ERROR    lxc_conf - conf.c:userns_exec_1:4374 - Error setting up child mappings
      lxc-start 20161230121339.016 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1274 - Error destroying /sys/fs/cgroup/memory//lxc/foo-base-5
      lxc-start 20161230121339.020 ERROR    lxc_conf - conf.c:userns_exec_1:4374 - Error setting up child mappings
      lxc-start 20161230121339.020 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1274 - Error destroying /sys/fs/cgroup/freezer//lxc/foo-base-5
      lxc-start 20161230121339.025 ERROR    lxc_conf - conf.c:userns_exec_1:4374 - Error setting up child mappings
      lxc-start 20161230121339.026 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1274 - Error destroying /sys/fs/cgroup/net_cls//lxc/foo-base-5
      lxc-start 20161230121339.029 ERROR    lxc_conf - conf.c:userns_exec_1:4374 - Error setting up child mappings
      lxc-start 20161230121339.029 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1274 - Error destroying /sys/fs/cgroup/blkio//lxc/foo-base-5
      lxc-start 20161230121339.033 ERROR    lxc_conf - conf.c:userns_exec_1:4374 - Error setting up child mappings
      lxc-start 20161230121339.033 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1274 - Error destroying /sys/fs/cgroup/perf_event//lxc/foo-base-5
      lxc-start 20161230121339.036 ERROR    lxc_conf - conf.c:userns_exec_1:4374 - Error setting up child mappings
      lxc-start 20161230121339.036 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1274 - Error destroying /sys/fs/cgroup/cpuset//lxc/foo-base-5
      lxc-start 20161230121339.040 ERROR    lxc_conf - conf.c:userns_exec_1:4374 - Error setting up child mappings
      lxc-start 20161230121339.040 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1274 - Error destroying /sys/fs/cgroup/pids//lxc/foo-base-5
      lxc-start 20161230121339.045 ERROR    lxc_conf - conf.c:userns_exec_1:4374 - Error setting up child mappings
      lxc-start 20161230121339.045 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1274 - Error destroying /sys/fs/cgroup/devices//lxc/foo-base-5
      lxc-start 20161230121344.006 ERROR    lxc_start_ui - tools/lxc_start.c:main:360 - The container failed to start.
      lxc-start 20161230121344.006 ERROR    lxc_start_ui - tools/lxc_start.c:main:362 - To get more details, run the container in foreground mode.
      lxc-start 20161230121344.006 ERROR    lxc_start_ui - tools/lxc_start.c:main:364 - Additional information can be obtained by setting the --logfile and --logpriority options.
```
Using google to search for the error messages yields nothing productive. Ergo, a new bug report seems to be in order.

**Comment by stgraber** [comment]
That's because your root user isn't allowed to use the provided uid/gid map and the helper tool that lxc shells out to (newuidmap/newgidmap) fails.

You'll need to edit /etc/subuid and /etc/subgid and replicate whatever you had for your user to the root account.

**Comment by linas** [comment]
Wow. Thanks! That worked! ... but getting to here was fairly painful, so is there some way that the lxc_cgfsng error messages could be changed to suggest that `/etc/subuid` might need an update or that it fails to contain correct information? Perhaps the `lxc-start` command itself could verify "common" config errors?

Am I, in fact, "doing it wrong" by fiddling around by hand? Should I have used a tool? I don't recall ever having fiddled with `/etc/subuid` before, but I guess I must have...

For anyone else who stumbles onto this: adding the following to `/etc/subuid` did the trick.
```
root:100000:65536
```
whereas previously it had
```
linas:100000:65536
```
and likewise for `/etc/subgid`

**Comment by hallyn** [comment]
Hi,

Fwiw I suppose the safest way is using usermod with the -v and -w flags.

More helpful user messages definately sound worthwhile.

**Comment by linas** [comment]
Ahh .. but using usermod is not the issue -- its knowing that one needs to use usermod that is.  So for example: http://stackoverflow.com/questions/23427129/how-do-i-backup-move-lxc-containers provides correct instructions for root-owned containers.  A naive user who attempted to do the same for user-owned containers would discover things don't work, because the usermod step is missing.  Perhaps the answer is "use lxd instead". I feel I'm wringing my hands over a maybe non-issue... but ...

**Comment by hallyn** [comment]
Quoting Linas Vepštas (notifications@github.com):
> Ahh .. but using usermod is not the issue -- its knowing that one needs to use usermod that is.

Of course, I was only answering the part of your previous email where you said

> Am I, in fact, "doing it wrong" by fiddling around by hand?

Or maybe you're saying 'fiddling around by hand' didn't mean the usermod
part...  In any case,

> So for example: http://stackoverflow.com/questions/23427129/how-do-i-backup-move-lxc-containers provides correct instructions for root-owned containers.  A naive user who attempted to do the same for user-owned containers would discover things don't work, because the usermod step is missing.  Perhaps the answer is "use lxd instead". I feel I'm wringing my hands over a maybe non-issue... but ... 

I think there's room for some better tools wrapping what we currently have
for manipulating mappings of filesystems on disk.  I.e.

	remapfs --from 100000:65536 --to 200000:65536 $lxcpath

in place of

	lxc-usernsexec -m b:0:100000:65536 -m b:100000:200000:65536 -- uidmapshift -b $lxcpath 0 100000 65536

Perhaps this belongs as a new command in coreutils (where unshare lives),
although it would also be nice to teach its unshare command about more
baroque ranges and default /etc/sub[ug]id ranges.

Or, maybe it belongs in shadow-utils.
