### ISSUE TITLE
lxc-snapshot replaces container name multiple times in path

### ISSUE THREAD

**Issue by jgoodson** [lxc/lxc#1375]
I am using lxc 1.0.9 on CentOS 7.

If you create a container and store it in a path that contains the container name in the path, when you attempt to create a snapshot, both instances of the name will be replaced with the snapshot name, resulting in failure to create a snapshot.

Example:

Container name: xenial
Container path: /mnt2/xenial_ssd

```
[admin@rockstor ~]# lxc-snapshot -n xenial
lxc_container: bdev.c: btrfs_snapshot: 1442 No such file or directory - Error opening new container dir /mnt2/snap0_ssd/snap0
lxc_container: bdev.c: bdev_copy: 3235 failed getting pathnames for cloned storage: /mnt2/xenial_ssd/xenial/rootfs
lxc_container: lxccontainer.c: copy_storage: 2452 Error copying storage
lxc_container: lxccontainer.c: lxcapi_snapshot: 2887 clone of /var/lib/lxc:xenial failed
lxc_container: lxc_snapshot.c: do_snapshot: 55 Error creating a snapshot
```

**Comment by brauner** [comment]
Can you please append/copy the config file of the container your creating the snapshot from and the snapshot?

**Comment by brauner** [comment]
And the complete log of both. :)

**Comment by jgoodson** [comment]
Container config:

```
# Template used to create this container: /usr/share/lxc/templates/lxc-download
# Parameters passed to the template:
# For additional config options, please look at lxc.container.conf(5)

# Distribution configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.arch = x86_64

# Container specific configuration
lxc.rootfs = /mnt2/xenial_ssd/xenial/rootfs
lxc.utsname = xenial

# Network configuration
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = dirbr0
lxc.network.hwaddr = 00:16:3e:b7:32:05
```

/mnt2/xenial_ssd/xenial/xenial.log is empty

I do not know where I would find the config or log for the snapshot, as it is never created because the destination path is not real. If there are additional locations for log or config files, I can check them.

**Comment by brauner** [comment]
Is the original container a btrfs backed container or a directory backed container?

**Comment by jgoodson** [comment]
I have figured out most of the issue. I had symlinked the /mnt2/xenial_ssd/xenial directory to /var/lib/lxc in an attempt to integrate the extra store with the default container store. If I give lxc-snapshot the correct store with the -P argument, it works correctly.
