### ISSUE TITLE
How to create an unprivileged container when the distro image in not available via the lxc-download template?

### ISSUE THREAD

**Issue by graysky2** [lxc/lxc#1380]
I have an ODROID-C2 which is an ARMv8 device running [Arch ARM](https://archlinuxarm.org/platforms/armv8/amlogic/odroid-c2) arch=aarch64.  I'd like to run an unprivileged container on it but I am not seeing an image for the distro when I attempt to create one.  Can I modify the upstream provided ` /usr/share/lxc/templates/lxc-archlinux` somehow to achieve this?  If not, what are my options?  Thank you!

```
# lxc-create -n sandbox -t download
Setting up the GPG keyring
Downloading the image index

---
DIST	RELEASE	ARCH	VARIANT	BUILD
---
...
alpine	edge	i386	default	20170108_17:50
archlinux	current	amd64	default	20170109_01:27
archlinux	current	i386	default	20170109_01:27
centos	6	amd64	default	20170109_02:16
...
```

**Comment by stgraber** [comment]
You'd need to manually create a privileged container and then manually shift the filesystem before changing the container config to be unprivileged.

**Comment by graysky2** [comment]
@stgraber - Thanks for the quick reply.  That means the pending PR in #1099 is needed, yes?  It isn't as simple as just `chown -R 100000:100000 /path/to/container` I think.

**Comment by stgraber** [comment]
Indeed not as simple as that. We have a go tool in the LXD tree called fuidshift that can do that for you and I think @hallyn has a more minimal C implementation somewhere too.

**Comment by brauner** [comment]
The code for the program in question is https://bazaar.launchpad.net/~serge-hallyn/+junk/nsexec/view/head:/uidmapshift.c.

**Comment by brauner** [comment]
Note, that one of the `C` functions used in this program is broken with older `musl` libc versions.

**Comment by graysky2** [comment]
Thank you for the link.  I will compile and test it shortly.

**Comment by graysky2** [comment]
Rookie question: is compilation as simple as just:
`gcc uidmapshift.c` ... That seems to have given a binary.  And an equally rookie follow-up question: 

I created the following on my host system:
`/etc/subgid` and `/etc/subuid` which each contain
```
root:100000:100000
```

I added the following two lines to my container config:
```
lxc.id_map = u 0 100000 100000
lxc.id_map = g 0 100000 100000
```

Is the correct usage of this program simply:
`./a.out -b 100000 /var/lib/lxc/foo`

Thanks!

**Comment by brauner** [comment]
```
gcc -o uidmapshift uidmapshift.c
```

    /etc/subuid
    /etc/subgid

should contain

     root:100000:65536

And the default config:

    lxc.id_map = u 0 100000 65536
    lxc.id_map = g 0 100000 65536
    
To shift the rootfs:

    ./uidmapshift -b /path/to/directory 0 100000 65536

**Comment by graysky2** [comment]
Thanks for the tip.  I have the system configured as you recommend and I prepared two different containers, one unprivileged (sandbox) and an 2nd privileged (sandbox2).

* Sandbox was created with the `-t download` switch and the modified `/etc/lxc/default.conf`
* Sandbox2 was created with the `-t /usr/share/lxc/templates/lxc-archlinux` switch and the stock `/etc/lxc/default.conf`

To compare their virgin states:
```
# /scratch/uidmapshift -r /var/lib/lxc/sandbox
UIDs 0 - 100999
GIDs 0 - 100999

# /scratch/uidmapshift -r /var/lib/lxc/sandbox2
UIDs 0 - 0
GIDs 0 - 998
```

Now invoking as you recommended:
```
# /scratch/uidmapshift -b /var/lib/lxc/sandbox2 0 100000 65536
# /scratch/uidmapshift -r /var/lib/lxc/sandbox2
UIDs 100000 - 100000
GIDs 100000 - 100998
```

Is that correct?

**Comment by brauner** [comment]
That's fine, I suspect. Probably just means that some files don't exist.

**Comment by graysky2** [comment]
Thank you very much for the help with this.  In transitioning over to the unprivilieged setup, I encountered some additional snags.  Perhaps you can share your insights?

When I start my unprivileged container, `systemd-tmpfiles-setup.service` fails to start with the following errors per journalctl:

```
Jan 09 14:16:20 playtime systemd[1]: systemd-tmpfiles-setup.service: Failed to reset devices.list: Operation not permitted
Jan 09 14:16:20 playtime systemd[1]: systemd-tmpfiles-setup.service: Failed to set invocation ID on control group /system.slice/systemd-tmpfiles-setup.service, ignoring: Operation not permitted
Jan 09 14:16:20 playtime systemd[1]: Starting Create Volatile Files and Directories...
Jan 09 14:16:20 playtime systemd-tmpfiles[18]: Setting default ACL "u::rwx,g::r-x,g:adm:r-x,g:wheel:r-x,g:4294967295:r-x,g:4294967295:r-x,m::r-x,o::r-x" on /var/log/journal failed: Invalid argument
Jan 09 14:16:20 playtime systemd-tmpfiles[18]: Setting access ACL "u::rwx,g::r-x,g:adm:r-x,g:wheel:r-x,g:4294967295:r-x,g:4294967295:r-x,m::r-x,o::r-x" on /var/log/journal failed: Invalid argument
Jan 09 14:16:20 playtime systemd-tmpfiles[18]: Setting default ACL "u::rwx,g::r-x,g:adm:r-x,g:wheel:r-x,g:4294967295:r-x,g:4294967295:r-x,m::r-x,o::r-x" on /var/log/journal/838a973609414ab38d2bc4af2756cc27 failed: Invalid argument
Jan 09 14:16:20 playtime systemd-tmpfiles[18]: Setting access ACL "u::rwx,g::r-x,g:adm:r-x,g:wheel:r-x,g:4294967295:r-x,g:4294967295:r-x,m::r-x,o::r-x" on /var/log/journal/838a973609414ab38d2bc4af2756cc27 failed: Invalid argument
Jan 09 14:16:20 playtime systemd[1]: systemd-tmpfiles-setup.service: Main process exited, code=exited, status=1/FAILURE
Jan 09 14:16:20 playtime systemd[1]: Failed to start Create Volatile Files and Directories.
Jan 09 14:16:20 playtime systemd[1]: systemd-tmpfiles-setup.service: Unit entered failed state.
Jan 09 14:16:20 playtime systemd[1]: systemd-tmpfiles-setup.service: Failed with result 'exit-code'.
``
I must be missing something key in the config but am unsure what:
```
lxc.rootfs = /var/lib/lxc/playtime/rootfs
lxc.utsname = playtime
lxc.arch = x86_64
lxc.include = /usr/share/lxc/config/archlinux.common.conf
lxc.rootfs.backend = dir

## for namespaces
lxc.include = /usr/share/lxc/config/archlinux.userns.conf
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536

## network
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = br0
lxc.network.name = eth0
lxc.network.ipv4 = 192.168.1.105/24
lxc.network.ipv4.gateway = 192.168.1.1

## mounts
lxc.mount.entry = /dev/net dev/net none bind,create=dir
lxc.mount.entry = tmpfs tmp tmpfs defaults
lxc.mount.entry = /dev/dri dev/dri none bind,optional,create=dir
lxc.mount.entry = /dev/snd dev/snd none bind,optional,create=dir
lxc.mount.entry = /tmp/.X11-unix tmp/.X11-unix none bind,optional,create=dir
lxc.mount.entry = /dev/video0 dev/video0 none bind,optional,create=file

lxc.cgroup.devices.allow = c 10:200 rwm
```

**Comment by graysky2** [comment]
I edited the previous post to make things more clear.  Interested to hear your thoughts and thank you!

**Comment by brauner** [comment]
The errors you are seeing are perfectly fine and are explained by the fact that you are running an unprivileged container. Some things just aren't allowed for safety reasons or inherent limitations of running unprivileged containers. As I see it this question has also been sufficiently answered on by Fajar here: https://lists.linuxcontainers.org/pipermail/lxc-users/2017-January/012734.html. Please avoid, double posting when possible. Since you have managed to convert the container to unprivileged, this issue can be closed. :)
