### ISSUE TITLE
Sharing multiple CPUs 

### ISSUE THREAD

**Issue by NSD2000** [lxc/lxc#1384]
Hello All,
Is it possible to share the multiple CPUs between multiple containers. My system is having 4 CPUs and 4 containers, each CPU will be shared between 4 containers. 
For example: CPU1 will be shared between containers 1,2 and 3
                      CPU2 will be shared between containers 1,3,4
                       CPU3 will be shared between containers 2,3,4 ...

From my understanding LXC can share only single CPU between multiple container.

Is it possible to share multiple CPUs between multiple containers.?
most important it should be configured using configuration file.

Please help with possible solution.

**Comment by brauner** [comment]
You can configure the cpus a container has access to by setting

    lxc.cgroup.cpuset.cpus


e.g.

    lxc.cgroup.cpuset.cpus = 0,3,1-2
in the containers configuration files.

**Comment by NSD2000** [comment]
lxc.cgroup.cpuset.cpus = 0,3,1-2 
It will allocate a dedicated CPU, how about sharing the CPUs
Lets say  container_1 : allocate CPU 0 with 100% and CPU1 30%
               container_2 : allocate CPU2 with 100% and CPU1 40%
               container_3 : allocate CPU3 with 100% and CPU1 30%

**Comment by ss1h2a3tw** [comment]
You can use `cpu.cfs_quota_us` and `cpu.cfs_period_us` to limit the cpu usage,
But It cannot specify per CPU usage, since it is implemented according to the scheduler

**Comment by brauner** [comment]
What @ss1h2a3tw will get you closest to what you want but there's nothing easy for LXC to do at this moment so closing.
