### ISSUE TITLE
How to run unprivileged containers on Raspberry Pi without cgm commands ?

### ISSUE THREAD

**Issue by Radoslaw-K** [lxc/lxc#1387]
I have LXC 1.0.6 installed on Rpi3 running Raspbian Jessie Lite kernel 4.4.38(with slight modifications by myself to allow LXC functionalities). It works fine in both privileged and unprivileged mode. The problem however is that each time I want to run unprivileged container I have to manually type the 3 commands below:

```
sudo cgm create all EXAMPLE 
sudo cgm chown all EXAMPLE $(id -u) $(id -g) 
cgm movepid all EXAMPLE $$ 
```

and then of course I start the container using:

`lxc-start -n c1 -d` 

Now I've been at it for days upon days trying different ways to figure out how to use the command above without the preceeding cgm commands but no luck at all.

Would love some help on this

**Comment by stgraber** [comment]
You'd need libpam-cgm or libpam-cgfs to have those done for you automatically on user login.

**Comment by Radoslaw-K** [comment]
As you suggested I installed libpam-cgfs and it kinda worked. What I mean by that is that when i checked /proc/self/cgroup I had some cgroup controllers created but not all as done by the 3 commands above. I looked through libpam-cgfs dependency packages and compared them to what I have on my pi. The only dependency that didn't match was libc6. On my Pi I have version 2.18 installed whereas libpam-cgfs requires version 2.24. I can manually download that version but I get errors when I try to install it. 

Am I right in thinking that to get all cgroup controllers set up for a user I need libc6 2.24 ? or do I have to do some configuration somewhere on the system instead ?

**Comment by brauner** [comment]
So `libpam-cgfs` is a pam-module which places you into a writeable cgroup for a given set of controllers on login. Which controllers `libpam-cgfs` will create a writeable cgroup for is controlled in `/etc/pam.d/common-session` and `/etc/pam.d/common-session-noninteractive`. In these files you will find the lines:

    session	optional	pam_cgfs.so -c freezer,memory,name=systemd

If you want more controllers then that you should list them here. The available (kernel) controllers can be found out via:

```
chb@conventiont|~
> cat /proc/cgroups
#subsys_name    hierarchy       num_cgroups     enabled
cpuset  11      4       1
cpu     3       144     1
cpuacct 3       144     1
blkio   9       144     1
memory  6       401     1
devices 5       144     1
freezer 2       13      1
net_cls 7       4       1
perf_event      10      4       1
net_prio        7       4       1
hugetlb 4       4       1
pids    8       148     1
```

So if you wanted to have a writeable cgroup for you user created in the, say, `cpuset` controller, you'd add the `cpuset` controller to the list in the aformentioned files.

**Comment by Radoslaw-K** [comment]
Gents, Thanks to both of you I now have unprivileged LXC fully working on my Pi! 

I'm very happy and appreciate your help a lot @stgraber and @brauner

**Comment by brauner** [comment]
No problem. Great to hear it's working now. :)
