### ISSUE TITLE
preserve_ns prevents starting containers on pre-3.8 kernels

### ISSUE THREAD

**Issue by stgraber** [lxc/lxc#1390]
I just got report that on a 3.2 kernel (Ubuntu 12.04 release kernel), we're now getting:

    Kernel does not support attaching to mnt namespaces

Which suggests we're hitting the preserve_ns code and failing rather than skipping.

The fact that nobody else reported this suggests that most people are finally running recent or heavily backported kernels but still, we should fix this.

**Comment by brauner** [comment]
This is fixed.
