### ISSUE TITLE
CoreOS image/template?

### ISSUE THREAD

**Issue by TalasZh** [lxc/lxc#1391]
Hi there, do you have plans to bring CoreOS as lxc image in near future?

**Comment by stgraber** [comment]
Anyone is certainly welcome to contribute one, but my understanding of Container Linux (the current name of CoreOS I believe), is that it's meant to run Docker or Rkt containers, which don't usually play very well with running inside another container.

That is, CoreOS/Container Linux is meant to be a container host, not a container guest, so unless I'm missing something, I'm not sure this really makes sense.

**Comment by styxlab** [comment]
CoreOS is a linux distribution stripped to the essentials for running docker or rkt containers, but it's still a regular linux distro. In the ubuntu canonical-kubernetes deployment, docker is also run inside an ubuntu lxc container. Why bot replace the ubuntu guest with an CoreOs guest? As CoreOS is more specialized it might have a lighter footprint compared to ubuntu.

Bootstrapping CoreOS might be an issue tough, as it needs a cloud config or ignition file from which it reads it's configuration. I'm not sure how that fits into the lxc/lxd framework.

**Comment by matti** [comment]
coreos in lxc makes sense, its just a linux distro

**Comment by gattytto** [comment]
first part is here https://github.com/lxc/distrobuilder/issues/254 @matti and as @styxlab says there's a challenge on firing the ignition process when we have a stripped image without /boot and the ignition file will be provided by a volume and not a url. 

Let's do it
