### ISSUE TITLE
error copying container between two hosts

### ISSUE THREAD

**Issue by sicktoy1971** [lxc/lxc#1394]
It is impossible to copy containers between hosts

root@hi2:~# lxc copy hi1:app1 local:app3

After some time I always get:

error: x509: certificate is valid for hi2, not hi1

I have tried to $HOME/.config/lxc/client.crt (both hosts)
I have tried to reboot (both hosts)

I also tried to copy from host 1 to host 2
root@hi1:~# lxc copy app1 hi2:app3
and I get the same error (error: x509: certificate is valid for hi2, not hi1)

I have tried to delete the remote and add it again.
same result.

if I try to copy an image 
lxc image copy hi1:fc6d723a6e66 local: --copy-aliases
I get no errors

--- HOST 1 DETAILS -----

root@hi1:~# lxc --version
2.0.8
root@hi1:~# uname -a
Linux hi1 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@hi1:~# lxc remote list
+-----------------+------------------------------------------+---------------+--------+--------+
|      NAME       |                   URL                    |   PROTOCOL    | PUBLIC | STATIC |
+-----------------+------------------------------------------+---------------+--------+--------+
| hi2             | https://93.188.225.82:8443               | lxd           | NO     | NO     |

--- HOST 1 DETAILS -----

root@hi2:~/.config/lxc# lxc --version
2.0.8
root@hi2:~/.config/lxc# uname -a
Linux hi2 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
+-----------------+------------------------------------------+---------------+--------+--------+
|      NAME       |                   URL                    |   PROTOCOL    | PUBLIC | STATIC |
+-----------------+------------------------------------------+---------------+--------+--------+
| hi1             | https://93.188.225.81:8443               | lxd           | NO     | NO     |

Any idea?
Thank you very much

Andrea.

**Comment by stgraber** [comment]
The most likely reason is that the two hosts have an identical alternative IP address which they're attempting to use for the transfer and hit their own LXD rather than the target's.

"lxc info hi1:" and "lxc info hi2:" would confirm

**Comment by sicktoy1971** [comment]
Dear Stephane

yes you are perfectly right

hi1 = 
environment:
  addresses:
  - 93.188.225.81:8443
  - 172.16.11.81:8443
  - 172.16.1.1:8443
  - 192.168.122.1:8443
 
hi2 = 
environment:
  addresses:
  - 172.16.11.82:8443
  - 93.188.225.82:8443
  - 172.16.2.1:8443
  - 192.168.122.1:8443

I dind't notice at first because 192.168.122.1 is bound automatically by Ubuntu to virbr0 (which is unneeded in my case as well) 

Thank you very much for your quick answer, you saved my night :)
Andrea.

**Comment by stgraber** [comment]
No worries. It's always a bit confusing when looking at the error message in those cases :)

**Comment by gaetanquentin** [comment]
i have the same problem but second host does not exist..it was the old name of the first host.
