### ISSUE TITLE
Error in documentation of lxc-copy about interaction between --ephemeral and -N option

### ISSUE THREAD

**Issue by sephii** [lxc/lxc#1396]
The documentation of `lxc-copy` states:

> When -e is specified and no newname is given via -N a random name for the snapshot will be chosen.

However, running `sudo lxc-copy -e -n testoverlaystd -s -B overlayfs` fails with the following error:

> Error: You must provide a NEWNAME for the clone.

Tested on LXC 2.0.6.

**Comment by brauner** [comment]
That's because you're combining the `-e` and `-s` flag. The `e` flag will take care to make a snapshot so specifying `s` is not needed. Try without the `s` flag. I just need to decide whether it makes sense to allow for `e` and `s` to be combined. If so, I'll change it for the next release. :)

**Comment by sephii** [comment]
You're right, it works without the `-s` flag. Thanks!
