### ISSUE TITLE
faild to start container 

### ISSUE THREAD

**Issue by aaronsuns** [lxc/lxc#1401]
I have one container running OK for some weeks, after this weekend it failed to start:

root@aws1:~# lxc start lb
error: Error calling 'lxd forkstart lb /var/lib/lxd/containers /var/log/lxd/lb/lxc.conf': err='exit status 1'
  lxc 20170130100133.362 ERROR lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
  lxc 20170130100133.362 ERROR lxc_start - start.c:lxc_init:465 - failed to run pre-start hooks for container 'lb'.
  lxc 20170130100133.362 ERROR lxc_start - start.c:__lxc_start:1313 - failed to initialize the container

Try `lxc info --show-log lb` for more info
root@aws1:~# lxc info --show-log lb
Name: lb
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/01/23 13:23 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

            lxc 20170130100133.362 ERROR    lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
            lxc 20170130100133.362 ERROR    lxc_start - start.c:lxc_init:465 - failed to run pre-start hooks for container 'lb'.
            lxc 20170130100133.362 ERROR    lxc_start - start.c:__lxc_start:1313 - failed to initialize the container
            lxc 20170130100133.362 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response

root@aws1:~# lxc version
2.7

**Comment by aaronsuns** [comment]
After reboot host, the problem is gone.

**Comment by brauner** [comment]
This issue should be filed against https://github.com/lxc/lxd if it is a recurring problem. Thanks! :)
