### ISSUE TITLE
[python-lxc] set_config_item doesn't clear old item

### ISSUE THREAD

**Issue by googley** [lxc/lxc#1404]
set_config_item() must remove old keys before applying new values : https://github.com/lxc/lxc/blob/master/src/python-lxc/lxc/__init__.py#L378

```python
c = lxc.Container('test')
c.create(template='ubuntu')
c.set_config_item('lxc.utsname', 'test-new-hostname')
c.save_config()
```

And then, in the  config file, there is two entries of lxc.utsname.

```INI
lxc.utsname = test
lxc.utsname = test-new-hostname
```

**Comment by brauner** [comment]
This should be fixed in current git master. Please re-open if the issue still persists. thanks!
