### ISSUE TITLE
setproctitle() sometimes corrupts argv, breaking lxc-start with command argument

### ISSUE THREAD

**Issue by willmo** [lxc/lxc#1407]
do_lxcapi_start() calls setproctitle() (in utils.c) to change the process name to "[lxc monitor]" followed by the config path and container name. setproctitle() works by changing argv[0], as the kernel sees it, to the new name, by calling prctl(PR_SET_MM, PR_SET_MM_MAP, ...).

If the new name fits in the space where argv currently is, setproctitle() will write the new name over argv. This is problematic because, if you invoke lxc-start with a command to run inside the container, this command is passed into do_lxcapi_start() as the "argv" pointer argument, and this pointer points into the process's original argv--which gets overwritten by setproctitle(). So when we eventually try to exec() the command inside the container, using the same argv pointer, we instead exec() part of the string written by setproctitle().

The manifestation of this issue depends on the length of the new process name and the total length and types of the arguments passed to lxc-start. If the arguments are shorter than the new process name, setproctitle() will heap-allocate a new buffer for the new process name and avoid corrupting the original argv. If the option arguments passed to lxc-start (before the command to run) are longer than the new process name, setproctitle() will only overwrite those options, which is harmless and leaves the command intact.

For example, on my system, if I run `lxc-start --logpriority INFO -n bar -- /dummyfoo/init.lxc` (58 bytes including NUL separators/terminators), then the new process name is `[lxc monitor] /usr/local/var/lib/lxc bar` (41 bytes including NUL). setproctitle() overwrites the first 41 bytes of the original argv, and the last two bytes of those 41 are the "/d" at the beginning of the command to run, which are overwritten with "r\0" (the "r" in "bar" plus a terminating NUL). So we try to exec() the command "r" inside the container, resulting in this error:

`lxc-start 20170201054535.087 ERROR    lxc_start - start.c:start:1423 - No such file or directory - Failed to exec "r".`.

In this example, the issue can be avoided by adding a no-op `--daemon` option argument, since this moves the command to run 9 bytes later in the original argv, thus 7 bytes past the end of the new process name written by setproctitle(). However, if the `--logpriority INFO` option were then removed, the command would be corrupted again.

Anyway, I think the simplest solution is to have setproctitle() always heap-allocate the buffer for the new name. If it would help, I may be able to submit a patch for this.

**Comment by tych0** [comment]
> Anyway, I think the simplest solution is to have setproctitle() always heap-allocate the buffer for the new name.

I agree; premature optimization is the root of all evil and all that. Cheers.

**Comment by willmo** [comment]
Awesome, thanks for the quick turnaround! :-)

I forgot to point out that some of the comments at the top of the function have been obsolete for a while too:

> \*   2. it clears /proc/self/environ
> \*   3. it may not succed (e.g. if title is longer than /proc/self/environ +
> \*      the original title)

**Comment by tych0** [comment]
On Thu, Feb 02, 2017 at 01:12:21AM -0800, willmo wrote:
> Awesome, thanks for the quick turnaround! :-)
> 
> I forgot to point out that some of the comments at the top of the function have been obsolete for a while too:
> 
> > \*   2. it clears /proc/self/environ
> > \*   3. it may not succed (e.g. if title is longer than /proc/self/environ +
> > \*      the original title)

Ah, indeed. I'll send a PR for that too. Thanks!
