### ISSUE TITLE
Can we add lxc.hook.pre-stop ?

### ISSUE THREAD

**Issue by asp24** [lxc/lxc#141]
It can be usefull for application isolation

**Comment by brauner** [comment]
This issue has been open quite a long time and no-one has re-requested a `pre-stop` hook and the original motiviation for this proposal seems to be solved by `lxc.stopsignal`. We should close this now an re-open if someone wants to work on this.

**Comment by khodnev** [comment]
I encountered a similar problem.
Standard option of using **`lxc.stopsignal`** does not always work correctly. For example, MySQL server does not have time to complete their work and as a result - the database is destroyed. 
It would be a good start `lxc.hook.pre-stop` to perform **`lxc-attach -n <NAME> "service mysql stop"`**.

**Comment by hallyn** [comment]
What do you mean by not enough time? is the init system giving up too early?

**Comment by khodnev** [comment]
Very load server may close the connection and flush caches up to 30-40 seconds. For example, my  bacula-director database server stops about 45 seconds. I do not want to all LXC containers in the my  cluster set a large timeout (about 45 seconds) to `lxc-stop`. Many other containers closed quickly. But there are those who must first give a command to close connections and flush caches. It would be very nice to have a hook with which it would be possible to perform a series of actions inside the container before closing it.

**Comment by hallyn** [comment]
Quoting Alexander Khodnev (notifications@github.com):

Sorry, I'm probably being dense, but a few more clarification questions:

> Very load server may close the connection and flush caches up to 30-40
> seconds. For example, my  bacula-director database server stops about 45
> seconds. I do not want to all LXC containers in the my  cluster set a large
> timeout (about 45 seconds) to `lxc-stop`.

Why not?

Would a 'lxc.killtimeout' container configuration item, acting like the
--timeout option to lxc-stop, work for you?  (Which you could hack
using a configuration file and a lxc-stop wrapper in the meantime)

>  Many other containers closed
> quickly.

Providing a long timeout for all containers doesn't affect the ones that close
quickly, as they will just cleanly shutdown...

So can you tell us exactly what is the problem with just doing something like

	for x in `lxc-ls --running`; do
		lxc-stop --timeout 120 $x
	done

>  But there are those who must first give a command to close
> connections and flush caches. It would be very nice to have a hook with which
> it would be possible to perform a series of actions inside the container
> before closing it.

It's possible that'll turn out to be the best way, but given that lxc and
init together seem to be able to do this at least in part using stopsignal, I
want to make sure that there's a real need first.

**Comment by khodnev** [comment]
All that you say I know. All this is good. In another case. 
I have more than 1000 LXC containers in my cluster. All of them often move between nodes in the cluster. All of them are created using templates. I'm a very intense use different hooks at work. And I really don't have enough hook, which would run before the process will begin stopping the container.
I think that many people who make heavy use of LCX agree with me.
I can do without this hook. But it would be very good to have it.

**Comment by akorn** [comment]
Currently, lxc can't easily stop a container that uses runit as its init system, because all lxc can do on a shutdown request is send a signal to the guest's init, and there is no single signal that will cause runit to initiate a shutdown (it has its own mechanism, but essentially it boils down to calling `init 0`).

It would be great if there were a hook lxc could run prior to killing the guest's init; ideally, this hook would run in the guest context, but calling `init 0` via `lxc-attach` would work for me.

(I have also submitted a patch for `runit` to support shutdown on `SIGPWR`, fwiw.)
