### ISSUE TITLE
Disabling link-local IPv6 on veth interfaces

### ISSUE THREAD

**Issue by candlerb** [lxc/lxc#1414]
I am using containers via lxd, see https://github.com/lxc/lxd/issues/2845.  However I am told that this change requires work on the lxc side.

Platform: ubuntu 16.04 with these standard packages:

* liblxc1 2.0.6-0ubuntu1~ubuntu16.04.2
* lxc-common 2.0.6-0ubuntu1~ubuntu16.04.2
* lxcfs 2.0.5-0ubuntu1~ubuntu16.04.1

# Issue description

When lxc attaches containers to bridges, there is a vethXXXXXX interface on the host side and an ethX interface at the container side.

The vethXXXXXX interfaces all get IPv6 link local addresses (which are different from the link-local addresses of the ethX interfaces inside the containers).

With many containers, the host gains many link-local addresses:

~~~
        "ansible_all_ipv6_addresses": [
            "fe80::fc7d:f7ff:fed7:d4f5",
            "fe80::fc2f:1eff:fe51:1633",
            "fe80::fc69:31ff:fe23:2990",
            "fe80::fcf8:a8ff:fed7:7e7",
            "fe80::fc66:8eff:fe07:e10a",
            "fe80::fca2:26ff:feb6:c370",
            "fe80::fc0c:90ff:fe3c:31ef",
            "fe80::fc03:c9ff:fe2d:fcc1",
... etc
~~~

A veth interface is never a source or target for traffic, so should never have its own IPv4 or IPv6 address.

I'd like to disable these link-local addresses: for cleanliness, and to reduce risk of traffic being able to reach bridges that I don't want it to.

This could probably be done by:

~~~
echo 0 > /proc/sys/net/ipv6/conf/vethXXXXXX/autoconf
~~~

and it definitely can be removed by:

~~~
echo 1 > /proc/sys/net/ipv6/conf/vethXXXXXX/disable_ipv6
~~~

However this depends on the actual assigned name, so has to be done when the interface is created. I don't want to set `net.ipv6.conf.default.autoconf=0` as that would have global effect, only for veth interfaces.

# Steps to reproduce

* Start containers
* 'ifconfig -a' on host
* Look at all those link local addresses.

**Comment by Blub** [comment]
I agree that this should be done for veth devices. Note that `disable_ipv6` is the correct choice here if you plug the host-end into a bridge, while `autoconf=0` would be for a "loose" veth device.
Personally I *do* prefer to use `default.disable_ipv6=1` because I usually know exactly which interfaces I want to enable it for... (opt-in is easier to maintain than opt-out). Its effect isn't exactly "global" (that would be `all.disable_ipv6`), it simply sets the default for *newly* created interfaces.

**Comment by stgraber** [comment]
So I don't think autoconf=0 is a good idea. I do have environments where radvd is running inside the container and the host is the one getting an IP over SLAAC. Doing autoconf=0 would regress such setups.

I do however agree that for bridged veth devices we should set disable_ipv6 to 1 if the file exists.

**Comment by Blub** [comment]
Interesting setup. So I guess the question is how generic the solution should be. Simply doing it for bridge-connected devices, or adding a `lxc.network.sysctl.*` variable set, or adding a network-device hook to be run for a device on/after creation?

**Comment by Blub** [comment]
Actually... just noticed there's already `lxc.network.script.{up,down}`.

**Comment by stgraber** [comment]
Yeah, I'd say we should do the enable_ipv6 thing for bridged interfaces and leave the rest to the network hooks rather than try to expose a full sysctl API.

**Comment by mikma** [comment]
Has this issue been fixed? I don't get any link-local IPv6 address on the veth interfaces anyway. I use Ubuntu 20.04 and lxd 4.6 with default network configuration in both Ubuntu and lxd. And /proc/sys/net/ipv6/conf/vethXXXXXX/disable_ipv6 apparently is set to 1 automatically.

**Comment by stgraber** [comment]
@mikma you're correct for LXD. LXD has its own nic management logic which does disable ipv6 on the host interface. liblxc/lxc itself does not which is why we have this issue to make it behave like LXD.

**Comment by AndrewElvisDeng** [comment]
@stgraber Is it alright if I tackle this issue?

**Comment by stgraber** [comment]
Certainly, assigning it to you.

**Comment by AndrewElvisDeng** [comment]
@stgraber In an email you sent us a few months back, you mentioned that this was a C change, but looking at this it seems like it's more of a shell change. Is there a specific C file where we should be looking? network.c?

**Comment by stgraber** [comment]
Yeah, I'd expect network.c, when creating a bridged veth pair, we need to write `1` in `/proc/sys/net/ipv6/conf/NAME/disable_ipv6` (and ignore the potentially missing file).
