### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by Cantalupo** [lxc/lxc#1416]
Need help...
I would like to make my life even easier, but I need to know if there is any way to leave the OpenSSH-Server package installed inside the tar.gz file of each template.

In a way I lose some time, installing manually.

Thanks in advance for your attention.

**Comment by brauner** [comment]
That depends on whether the package let's you specify additional packages during installation. This info can be gathered by looking at the scripts.

**Comment by Cantalupo** [comment]
So how could customize the templates?
Thank you!
