### ISSUE TITLE
LXC communication to outside world

### ISSUE THREAD

**Issue by abhijitsahu** [lxc/lxc#1419]
Hi ,

How LXC communicate to outside world? Can you give some example?

Thanks,
Abhijit

**Comment by stgraber** [comment]
LXC containers are typically bridged, either to a physical network or a standalone bridge (like our default lxcbr0). This gives NATed network connectivity to containers which configure over DHCP.

**Comment by abhijitsahu** [comment]
Thank you Stgraber !
