### ISSUE TITLE
Regarding LXC inputs and clarifications 

### ISSUE THREAD

**Issue by abhijitsahu** [lxc/lxc#1421]
Hi ,

I have gone through the site "https://linuxcontainers.org/"  ; installed LXC and done the examples provided "https://linuxcontainers.org/lxc/articles/" successfully. I seek some clarifications/inputs as below.

PC used: Ubuntu 14.04 LTS 64bit system

Could you please provide me your valuable inputs on below points. How can i achieve it?

1. Consider i have two containers C1 and C2. C1 is having process P1 and C2 is having process P2. How P1 and P2 process communicates each-other?
2. How a process inside container communicates with another process which is not part of that container?
3. How sandboxing and seccomp achieved though LXC? I have posted the my concern/clarifications on your web link "https://www.stgraber.org/2014/01/01/lxc-1-0-security-features/". Waiting for the same.
4. How a particular memory i need to protect though LXC. For example process P1(which is part of container C1) uses the from the RAM location offset 0xXXXX to 0xYYYY. How can i protect  this RAM location data (RAM location data offset 0xXXXX to 0xYYYY) from other processes (which can be both inside and outside the process). 

I am eagerly waiting for the inputs. Thanks a lot in advance.

**Comment by brauner** [comment]
Sorry, this is out of scope for us right now.
