### ISSUE TITLE
Some systemd components fail to start

### ISSUE THREAD

**Issue by timofurrer** [lxc/lxc#1423]
When I create a LXC on an Ubuntu Host with debian jessie as a guest, some systemd components fail to start:

```
sudo lxc-create -n systemd-test -t debian -- -r jessie -a amd64
sudo lxc-start -n systemd-test
sudo lxc-attach -n systemd-test
``` 

Inside the container services like `localectl` and `hostnamectl` are not available - they fail with: `Failed to create bus connection: No such file or directory`

When I try to start them manually with: `systemd start systemd-localed` it fails. The logs show me the following:

```
Feb 07 10:23:56 systemd-test systemd[1]: Failed to reset devices.list on /system.slice/console-getty.service: Operation not permitted
Feb 07 10:23:56 systemd-test systemd[1]: Failed to reset devices.list on /system.slice/systemd-user-sessions.service: Operation not permitted
Feb 07 10:23:56 systemd-test systemd[1]: Failed to reset devices.list on /system.slice/systemd-remount-fs.service: Operation not permitted
Feb 07 10:23:56 systemd-test systemd[1]: Failed to reset devices.list on /system.slice/systemd-random-seed.service: Operation not permitted
Feb 07 10:23:56 systemd-test systemd[1]: Failed to reset devices.list on /system.slice/networking.service: Operation not permitted
Feb 07 10:23:56 systemd-test systemd[1]: Failed to reset devices.list on /system.slice/systemd-journald.service: Operation not permitted
Feb 07 10:23:56 systemd-test systemd[1]: Failed to reset devices.list on /system.slice/dev-tty4.mount: Operation not permitted
Feb 07 10:23:56 systemd-test systemd[1]: systemd-localed.service: main process exited, code=exited, status=225/NETWORK
Feb 07 10:23:56 systemd-test systemd[1]: Failed to start Locale Service.
-- Subject: Unit systemd-localed.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit systemd-localed.service has failed.
-- 
-- The result is failed.
Feb 07 10:23:56 systemd-test systemd[1]: Unit systemd-localed.service entered failed state.
```

What's the reason for that? I assume it has to do with some permissions I'm lacking of?

I'm using:
Ubuntu:  16.04
LXC: 2.0.6-0ubuntu1~ubuntu16.04.2
cgroups:
```
11:blkio:/lxc/systemd-test
10:pids:/lxc/systemd-test
9:perf_event:/lxc/systemd-test
8:freezer:/lxc/systemd-test
7:cpuset:/lxc/systemd-test
6:hugetlb:/lxc/systemd-test
5:memory:/lxc/systemd-test
4:cpu,cpuacct:/lxc/systemd-test
3:net_cls,net_prio:/lxc/systemd-test
2:devices:/lxc/systemd-test
1:name=systemd:/lxc/systemd-test
```

**Comment by brauner** [comment]
There are a bunch of systemd services and tasks that are not allowed to run in a container since they can cause security issues; manipulating devices being one of them.

**Comment by timofurrer** [comment]
Fair enough. However, I've got some containers which run those systemd services successfully. I've set them up a long time ago - so I don't really remember what I did there. 

What could this have been?

**Comment by brauner** [comment]
Well, I don't know exactly what e.g. `localectl` and `hostnamectl` try to do. But have you installed and started dbus inside the container as this is what they complain about. For the other issue do you have some custom `lxc.cgroup.devices.allow` lines in these old container's config. Also, it would matter if those old containers run other versions of systemd that might do less-intrusive things.

**Comment by evgeni** [comment]
These commands need dbus, the Debian default containers don't have dbus installed. IIRC.

**Comment by timofurrer** [comment]
I've installed and started `dbus`. The following `dbus` process is running:

```
/usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
```
If I want to start the `systemd-localed` service I'll get the above error logs or the following one:

```
Feb 09 08:14:02 systemd-test systemd[949]: Failed at step NETWORK spawning /lib/systemd/systemd-localed: Permission denied
```

They are alternating. One time I'll get the ones above and the other time I'll get the one shown in this post - It's reproducible. I don't have any custom `lxc.cgroup.devices.allow` lines in the old container's config.

**Comment by evgeni** [comment]
Sorry, I have no immediate clue for you :(

**Comment by jljouannic** [comment]
Same problem here on an Ubuntu 16.04 host with Ubuntu 16.04 as guest.

It may be related to this : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=773932

What do you think?

**Comment by brauner** [comment]
Maybe, as I said localectl might do something equally weird as hostnamectl and if this is so then this should not be allowed in the container. As a sidenote:

> "I do not think that we want to support systems without namespaces, since 
we want to encourage adoption of the systemd security-related features 
in the default unit files shipped by packages."

It's an init system. Believe it or not it might sometimes encounter a system that doesn't support namespaces.

**Comment by brauner** [comment]
Closing this as LXC's behavior seems correct.

**Comment by huegelc** [comment]
Sorry to bump this but I too have this issue. Any solutions for this?

**Comment by brauner** [comment]
This is with Debian Jessie? What's the systemd version of Debian Jessie. This is not a LXC problem.

**Comment by brauner** [comment]
Also, can you try and reproduce with LXC master, if you can.
