### ISSUE TITLE
Outdated config paths in GUI tutorial

### ISSUE THREAD

**Issue by vv0iadyk** [lxc/lxc#1429]
I am trying to run GUI apps run from lxc with stgrabers [GUI tutorial](https://stgraber.org/2014/02/09/lxc-1-0-gui-in-containers/) but it seems that since 2014 the paths of some folders and config files have changed
and modifying will not make needed effect. An example  ~/.local/share/lxc/container/ no more contains file with name **config** . Not sure also if lxc.mount.entry linking still have correct paths. What are correct paths if i want to follow that tutorial?

**Comment by brauner** [comment]
Well, the folder `~/.local/share/lxc/container` will only exist if you created an unprivileged container. If you created a privileged container you will find it in `/var/lib/lxc/container/config`.

**Comment by vv0iadyk** [comment]
Folder `~/.local/share/lxc/container `exist but inside is `container.log` only. Is that because i have lxd installed ?

**Comment by brauner** [comment]
No, that likely means that the container got deleted.

**Comment by brauner** [comment]
Seems to be not an issue anymore, so closing for now.
