### ISSUE TITLE
Add the possibility to delete a container without destroying the ZFS filesystem

### ISSUE THREAD

**Issue by NicolasGoeddel** [lxc/lxc#1439]
I have two servers which act as LXC Hosts. Every night I copy backups from one server to the other one using `zfs send/receive`.
Sometimes I need to check if the backups are working and so I use `lxd import` after which I am able to start the backed up container. Now it would be nice if there were a counterpart to `lxd import` available which deletes the container in the configuration but does not touch the ZFS filesystem. This way I would be able to continue incremental backups using `zfs send/receive` and import the container when it really is necessary.

Alternatively it would be nice to be able to call `lxd import` when the container was already imported. Then it could update the container instead of reimporting it completely.

**Comment by stgraber** [comment]
The alternative (have "lxd import" import grow a --force flag to allow importing over an existing container) sounds fine to me.

Can you please file this feature request at https://github.com/lxc/lxd instead?

**Comment by cebe** [comment]
@stgraber I think this would also fit as a feature request for `lxc-destroy` so one would be able to destroy the container, i.e. remove its configuration but keep the data on the lvm partition.

**Comment by stgraber** [comment]
@cebe well, for LXC, you can simply remove the container's directory, that's not quite that simple with LXD though :)

**Comment by cebe** [comment]
good to know, can we add that to the lxc-destroy man page? I can make a pull request for that if you agree.

**Comment by stgraber** [comment]
I don't think it's really something we want to advertise in the manpage, especially as someone doing this wouldn't even use lxc-destroy in the first place.

It's pretty backend specific and will likely cause a subsequent lxc-create to fail as the container storage is already present.

**Comment by cebe** [comment]
what would be the correct way of restoring a container from a backup?

considering the situation that I have recovered the lvm partition from a snapshot and now want to create a new container from it to replace the old/broken one. I'd also want to delete the old container without touching the underlying storage. Imo there should be a supported way of doing this with lxc tools.

**Comment by stgraber** [comment]
@cebe All that should be on disk (outside of LVM) is the container's directory and a plain text config file. To restore the container you just need to re-create the directory and put the text config file back in there (or copy the one from a nearby container and change the few mention of the container's name).

**Comment by cebe** [comment]
okay, thanks for the explanation!
