### ISSUE TITLE
cgroups memory leakage?

### ISSUE THREAD

**Issue by FransM** [lxc/lxc#1443]
Hi,

I ran into a problem where we could not create new containers.
root cause was that /proc/cgroups had 65535 as num_cgroups for memory.
So this seemed maxed out.

We've observed this with lxc 1.0.8 with on ubuntu 14.04 with a 3.19 kernel.

This command:
echo 1 > /proc/sys/vm/drop_caches
drops the num_cgroups greatly.

(this command was suggested in https://github.com/docker/docker/issues/29638 )

I've also noticed that  num_cgroups was substantially higher than the other numbers on my system with lxc 2.8, ubuntu 16.04, kernel 4.4.0

Then again one of our systems was still on a 3.13 kernel but with lxc 1.0.9 and that one did not show the issue.

If more info is needed, let me know what commands I should give
(I am not a cgroups wiz; the echo command reduced the number but it is growing again; so I still have the system for analysis).

**Comment by brauner** [comment]
It doesn't sound like a memory leak. So there are two possibilities:

- There are a lot of leftover cgroups in the memory cgroup. (You can check by looking at `/sys/fs/cgroup/memory/**`.
- Second this is a kernel bug whereby the deleted cgroups internally are still marked as alive while they are actually dead. <-- This is my guess. Newer kernels should not be affected by this. So if you can get your hands on a system running a newer kernel and try to reproduce you could check.

**Comment by FransM** [comment]
/sys/fs/cgroup/memory only contained a few 100 entries.

Actually to geet rid of things I've rebooted the system about 6 hours ago. /proc/cgroups now looks like this:

#subsys_name	hierarchy	num_cgroups	enabled
cpuset	1	28	1
cpu	2	28	1
cpuacct	3	28	1
memory	4	4172	1
devices	5	28	1
freezer	6	28	1
net_cls	7	28	1
blkio	8	28	1
perf_event	9	28	1
net_prio	10	28	1
hugetlb	11	28	1

Looking at /sys/fs/cgroup/memory I see 21 subdirectores in the lxc folder and 2 in the user folder.
The number of containers currently running is 20, and there are indeed 20 users logged in.

Actually in 10 minutes or so num_cgroups for memory increased by about 100.

I seem to have the issue also with my lxd system; but that one is in much lower use (still working on the migration) This lxd system has a 4.4 kernel. (runnning ubuntu 16.04 server)

For now the only solution I see is to run a cron jobs that writes to /proc/sys/vm/drop_caches every day or so, but that is more of a workaround, not a real fix.

**Comment by FransM** [comment]
Short update: 10 hours later I am at 10120 memory cgroups. All the other numbers are 23 or lower.

I suspect that this is indeed something related to cgroups/kernel not properly flushing or garbage collecting.

**Comment by brauner** [comment]
@FransM, on which kernel version where you able to reproduce this?

**Comment by FransM** [comment]
3.19 (with ubuntu 14.04). It seems the issue is not there on 3.13 (also ubuntu 14.04).
Then again I see the same cgroups leakage with lxd 2.8 on a 4.4.0 kernel (ubuntu 16.04.1)

We do start/stop containers quite often (it is part of a test setup); suspect that triggers the issue

**Comment by FransM** [comment]
tried a bit more to reproduce it with lxd 2.8 (I know this is an lxc ticket but our lxc system is in active use so I cannot do reliable measurements here).

When I do this:
cat /proc/cgroups; lxc start u1604; sleep 5; lxc stop u1604; sleep 5; cat /proc/cgroups
I see the num_cgroups for memory increase; if I try it a few times more the increases become smaller and eventually it stabilizes.

Then I did lxc copy u1604 tst and ran
cat /proc/cgroups; lxc start tst; sleep 5; lxc stop tst; sleep 5; cat /proc/cgroups
the num_cgroups raised from 888 to 932

repeated runs cause some increase (but not much)

lxc copy tst tst2 and rerun: I go from 943 to 989

$ uname -a
Linux LXC-Master-FM 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

**Comment by hallyn** [comment]
Are there any warnings in syslog?

Can you attach a file with the outputs of
  tree -d /sys/fs/cgroup/memory
  find /sys/fs/cgroup/memory -type d | while read dir; do echo $dir; cat $dir/tasks; done | less
when the cgroups count is high?

**Comment by FransM** [comment]
oh, this is a while ago, we went back to the 3.13 kernel and the issue was gone, suspect it is fixed in the kernel (the 3.19 kernel I had before was end of life, 3.13 is still maintained so maybe it got fixed. (we could for other reasons not yet go to 4.4)
For 4.4. the increase seems less, I will try to reproduce, but it may be a few days before I get to that.

**Comment by brauner** [comment]
@hallyn, there once was a bug like that were references to cgroups were not properly released. But I don't remember which kernel version.

**Comment by tejasmanohar** [comment]
@hallyn We're seeing https://github.com/moby/moby/issues/31120 and found this issue as a result. Here are logs while cgroups count is high https://gist.github.com/tejasmanohar/ab5d1451c78d9d7ab64ebe344823f6e0

```
core@elastic-010 /sys/fs/cgroup $ cat /proc/cgroups | grep memory
memory	7	65535	1
```

**Comment by hallyn** [comment]
I'm going to close this issue as it appears to be kernel-version-specific,
and hasn't had any comments in several months.
