### ISSUE TITLE
lxc-2.0.7: umask doesn't work properly in the lxc guest

### ISSUE THREAD

**Issue by iDarkTemplar** [lxc/lxc#1448]
I'm using lxc-2.0.7 on Gentoo host with Gentoo guest. Issue was discovered with portage not working properly inside the lxc container, and the root of issue is umask() and open() not interacting properly inside the container.

How to reproduce it on gentoo:
1. emerge =app-emulation/lxc-2.0.7
2. lxc-create -n testbox -t gentoo
3. lxc-start -n testbox
4. lxc-attach -n testbox
5. inside the lxc: FEATURE="userpriv" emerge -1v portage

Actual Results:  
emerge fails on unpack stage

Expected Results:  
emerge should succeed

The test script:
```
#!/usr/bin/env python
# https://bugs.gentoo.org/show_bug.cgi?id=611114
from __future__ import print_function

import os
import stat
import sys

if len(sys.argv) != 2:
        print("usage: %s <filename>" % (sys.argv[0],), file=sys.stderr)
        sys.exit(1)

filename = sys.argv[1]

os.umask(0o000)
fd = os.open(filename, os.O_CREAT|os.O_RDWR, 0o660)

# This is supposed to output 660
print("%o" % (stat.S_IMODE(os.fstat(fd).st_mode),))
```

On the host system result is:
```
$ rm /tmp/testfile &> /dev/null
$ /tmp/test_bug_611114.py /tmp/testfile
660
```
which is correct.

On the guest system I get incorrect result:
```
$ rm /tmp/testfile &> /dev/null
$ /tmp/test_bug_611114.py /tmp/testfile
640
```

As already mentioned, it looks like umask() call has no effect inside container.

Related bug on gentoo bugzilla: https://bugs.gentoo.org/show_bug.cgi?id=611114

**Comment by stgraber** [comment]
I'm failing to reproduce this in LXD privileged or unprivileged containers, though using Ubuntu rather than gentoo for the container. I guess I'd have to test with just LXC and a gentoo container to see if this is some kind of kernel bug on Gentoo that can't be reproduced on the Ubuntu kernel.

**Comment by stgraber** [comment]
```
>>> Original instance of package unmerged safely.
 * 
 * This release of portage NO LONGER contains the repoman code base.
 * Repoman has its own ebuild and release package.
 * For repoman functionality please emerge app-portage/repoman
 * Please report any bugs you may encounter.
 * 
>>> sys-apps/portage-2.3.3 merged.
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * GNU info directory index is up-to-date.

 * IMPORTANT: 12 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

testbox ~ # nano test.py
testbox ~ # python3 test.py /tmp/a
660
testbox ~ # ls -lh /tmp/a
-rw-rw---- 1 root root 0 Mar  2 12:59 /tmp/a
testbox ~ # 
testbox ~ # 
```

**Comment by stgraber** [comment]
Using your exact instructions but on an Ubuntu host, also running LXC 2.0.7, I'm unable to reproduce your issue.

**Comment by iDarkTemplar** [comment]
Hmm, but I definitely have the issue. What additional information I must provide you to find the root of issue? Any tests to run?

**Comment by stgraber** [comment]
What's your umask outside of the container before you start or attach to the container?

**Comment by iDarkTemplar** [comment]
umask is 0022.

**Comment by iDarkTemplar** [comment]
I've tried to reproduce issue on fresh setup inside virtualbox, but didn't succeed yet.

**Comment by iDarkTemplar** [comment]
I've finally found the root of issue. It was related to ACL. The box I ran had default acl on every directory like this:
```
$ getfacl /
getfacl: Removing leading '/' from absolute path names
# file: .
# owner: root
# group: root
user::rwx
group::r-x
other::r-x
default:user::rwx
default:group:r-x
default:other:r-x
```

I've compared this setup with my other boxes (and virtualbox test setup) and didn't find similar ACLs on other boxes. After that I remounted root system with 'noacl' and issue gone. I didn't notice this issue on host system since directories /tmp and /var/tmp/portage were mounted as tmpfs there.

I've booted to recovery image, ran 'setfacl -kR ...' on every filesystem since I didn't need these ACL, booted to system and confirmed that issue disappeared.

Now I know the missing step to reproduction (NOTE, don't do if you have some ACL set up, either on host, or in any client which has filesystem located in /var/lib/lxc, or save it before doing it):
`setfacl -dR --set=u::rwx,g::rx,o::rx /var/lib/lxc`
To remove this ACL later run (same NOTE as above):
`setfacl -kR /var/lib/lxc`

I've fixed my setup. One thing I might propose is to remove those custom ACLs from rootfs directory when that rootfs directory is created in lxc-create. Please close the issue if you think there's nothing to fix for lxc.

**Comment by stgraber** [comment]
That falls in the same category as having /var/lib/lxc mounted noexec or nodev. Those are possible things an administrator can do and yes, that will prevent LXC from behaving properly. The kernel is however doing exactly what you asked it to do :)

So I don't think LXC should attempt to undo such things, especially when they may be there for a reason.
