### ISSUE TITLE
Checkpoint failed: Can't check shutdown state of inet socket

### ISSUE THREAD

**Issue by davidebaldini** [lxc/lxc#1451]
Hello,

`lxc-checkpoint` fails to dump my lxc instance.

This:

    # apt-get purge lxcfs
    # (then I restart all my 4 lxc containers)
    # lxc-checkpoint -D /tmp/c_106/ -P /media/raid1/ -n ve-106

produces the following `/tmp/c_106/dump.log`:

    Error (criu/util.c:670): exited, status=3
    Can't check shutdown state of inet socket
    Warn  (criu/arch/x86/crtools.c:138): Will restore 28759 with interrupted system call
    Warn  (criu/arch/x86/crtools.c:138): Will restore 26897 with interrupted system call
    Warn  (criu/arch/x86/crtools.c:138): Will restore 28100 with interrupted system call
    Warn  (criu/arch/x86/crtools.c:138): Will restore 28392 with interrupted system call
    tar: ./minissdpd.sock: socket ignored
    tar: ./dbus/system_bus_socket: socket ignored
    tar: ./saslauthd/mux: socket ignored
    tar: ./udev/control: socket ignored
    tar: ./log: socket ignored

### System info:

    # lxc-checkpoint --version
    2.0.7

    # criu --version
    Version: 2.11.1

    # uname -a
    Linux debianBunker 4.9.0 #5 SMP Sat Mar 4 00:42:17 CET 2017 x86_64 GNU/Linux

All kernel options specified [here](https://criu.org/Installation#Linux_Kernel) have been enabled.

**Comment by stgraber** [comment]
Not sure why we've not responded to this one before.
This is a CRIU failure due to what (at the time at least) was a CRIU limitation.

I believe CRIU has greatly improved in its ability to dump sockets, so this may well be fixed with a more modern CRIU.
