### ISSUE TITLE
Nested container: network error due to mtu size.

### ISSUE THREAD

**Issue by madkoala** [lxc/lxc#1452]
I'm trying to utilize lxc on virtual machines running in openstack environment.
When I create a container, access to Internet failed due to mtu size.
MTU size of the virtual machine is set to 1450, but the mtu of the container image is set to 1500.
When I change mtu size to 1400, then it works normally.

Is there any way to set default mtu size of the created image?
Thanks in advance.

**Comment by stgraber** [comment]
Edit /etc/lxc/default.conf and set lxc.network.mtu to whatever value you want

**Comment by brauner** [comment]
Right, closing this since @stgraber pointed out the way to handle this. If there are still issues, please reopen.
