### ISSUE TITLE
lxc dont write all data in containers

### ISSUE THREAD

**Issue by standula** [lxc/lxc#1455]
Hi, 
I use lxc to setup demo installations for my application. I have self extract bash script. 
I use for application install and setup in container command: 
lxc-attach -n demo_app_1 -- "/root/test_do_something.sh"
In one instance (without loop) is installation and setup success, but if i give lxc-attach command into loop, tar file will not extract and write some files from tarball. 
So i debug installation and tar contain all files, but in contrainter is extracted and written approximately 50% files.
When i attach directly into container via lxc-attach -n demo_app_1  and run command /root/test_do_something.sh via attached container enviroment, extraction  and installation works fine and success.

I don`t known what is wrong. 
I make simple test case 
--------------------test.sh - start -----------------------
#Start from clone
lxc-start -d -n $lxc_clone
lxc-attach -n ${name} -- "/root/test_do_something.sh"
lxc-attach -n ${name} -- "ls -la /tmp"
--------------------test.sh - end -----------------------

--------------------/root/test_do_something.sh - start -----------------------
#!/bin/bash -x
mkdir /tmp/create_dir_test.lab || {
	echo "CREATE FAILED" 
}
echo "LAB_TEST_STRING" > /tmp/touch_test.lxc_lab || {
	echo "WRITE FAILED" 
}
--------------------/root/test_do_something.sh - end -----------------------

-------------------- Output  -----------------------------------
+ lxc-start -d -n lxc_lab_single_test
+ lxc-attach -n lxc_lab_single_test -- /root/test_do_something.sh
+ mkdir /tmp/create_dir_test.lab
+ echo LAB_TEST_STRING
+ lxc-attach -n lxc_lab_single_test -- 'ls -la /tmp'
lxc-attach: attach.c: lxc_attach_run_command: 1292 No such file or directory - Failed to exec "ls -la /tmp".
-------------------- Output  -----------------------------------
dir -  /tmp/create_dir_test.lab - not exists
file - /tmp/touch_test.lxc_lab - not -exists

What should I do?

**Comment by stgraber** [comment]
This has nothing to do with LXC. The problem you're running into is that your container, like most LInux systems wipes /tmp clean on boot.

If you run your script before that process has completed, whatever data your wrote to /tmp at that point will be wiped.

**Comment by standula** [comment]
Well, 
my mistake. I relied that container is started completly after call lxc-create. But not yet. For speed test i add into script  "sleep 5 " after create and this solve problem. 
Thank you for your answer.
Best regards,
SL
