### ISSUE TITLE
Docs about Template Scripts

### ISSUE THREAD

**Issue by guettli** [lxc/lxc#1459]
I was told to learn template scripts where: https://wiki.gentoo.org/wiki/LXC#Template_scripts

This link seems good, but unofficial.

Where are the canonical/official docs for "Template Scripts"?

**Comment by brauner** [comment]
There aren't any official documents on how to write template scripts. What usually happens is that users orient themselves on the already existing scripts which have been around for the while. The best to guide these efforts are probably the Ubuntu and Debian ones.

**Comment by guettli** [comment]
@brauner thank you explaining the current state of the docs.

I see. There are no canonical upstream docs up to now.

Does the lxc project want this to stay like it this?

**Comment by brauner** [comment]
Not necessarily. If the community decides to have and maintain a sort-of best practice guide on how to write templates we'd not be opposed to merging it. (@stgraber, objections?)

**Comment by stgraber** [comment]
Template scripts are now out of the LXC project.
