### ISSUE TITLE
Unable to get macvlan interface for container

### ISSUE THREAD

**Issue by lpvm** [lxc/lxc#1464]
I've followed a [2013 hands-on guide](http://containerops.org/2013/11/19/lxc-networking/) but also tried a [2015 post](https://www.flockport.com/lxc-macvlan-networking/) in order to setup some containers with the `macvlan` network type in `bridge` mode.  All my attempts failed, as never an interface seemed to be created for the containers.

A `enp9s0` network interface should be the one used to service these containers.
```
# ip addr l enp9s0
3: enp9s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether d0:50:99:1b:5f:c3 brd ff:ff:ff:ff:ff:ff
    inet 85.85.91.204/21 brd 85.85.95.255 scope global enp9s0
       valid_lft forever preferred_lft forever
    inet6 fe80::d250:99ff:fe1b:5fc3/64 scope link
       valid_lft forever preferred_lft forever
```
In one of the attempts:
```
# brctl show
bridge name     bridge id               STP enabled     interfaces
lxcbr0          8000.000000000000       no
lxcbr1          8000.000000000000       no
lxcbr2          8000.000000000000       no
```
`lxcbr1` was created for this case.
```
# grep network macvlanbridge01/config | grep -v '^#'
lxc.network.type = macvlan
lxc.network.macvlan.mode = bridge
lxc.network.hwaddr = 00:16:3e:48:35:d2
lxc.network.flags = up
lxc.network.link = lxcbr1
lxc.network.ipv4 = 10.0.5.3/24
```

```
 ~> lxc-start -n macvlanbridge01 -o macvlanbridge01.log -l trace
~> lxc-ls --fancy
NAME            STATE   AUTOSTART GROUPS IPV4 IPV6
macvlanbridge01 RUNNING 1         -      -    -
```
(removed other stopped that where running with veth)

As can be seen, no ipv4 address.

```
 ~> lxc-attach -n macvlanbridge01

root@macvlanbridge01:/# ifconfig
lo        Link encap:Local Loopback
      (deleted remaining lines)
```

No other interface.

Tried again with instruction from the second post mentioned above.
```
ip link add mvlan0 link eth0 type macvlan mode bridge
ifconfig mvlan0 up

lxc.network.type = macvlan
lxc.network.macvlan.mode = bridge
lxc.network.flags = up
lxc.network.link = mvlan0
lxc.network.name = eth0
lxc.network.hwaddr = 00:16:3e:41:11:65
lxc.network.mtu = 1500
```
(note, the authors didn't specify any ipv4 address, so didn't I in this example)

`~> lxc-start -n macvlanbridge01 -o macvlanbridge01.log -l trace`

The only errors from the log:
```
~> grep -i error macvlanbridge01.log 
      lxc-start 20170315154255.340 WARN     lxc_confile - confile.c:config_pivotdir:1910 - lxc.pivotdir is ignored.  It will soon become an error.
      lxc-start 20170315154255.341 WARN     lxc_cgmanager - cgroups/cgmanager.c:cgm_get:992 - do_cgm_get exited with error
```
```
~> grep -i network macvlanbridge01.log 
      lxc-start 20170315154255.429 INFO     lxc_conf - conf.c:setup_network:2473 - network has been setup
```

No interface create as above:
```
 ~> lxc-ls --fancy
NAME            STATE   AUTOSTART GROUPS IPV4 IPV6
macvlanbridge01 RUNNING 1         -      -    -
```

Did something change for `macvlan` type since the release of those texts?  What should I look for?

**Comment by ogroot** [comment]
I hit exactly the same problem! 
Container is not able to get eth0 and ip.
Is this a macvlan limitation with unpriviliged containers?

**Comment by stgraber** [comment]
EIther of you still hitting macvlan issues on LXC 3.0 or higher?
We have quite a large userbase of that feature nowadays and haven't seen such reports before.

**Comment by brauner** [comment]
Closing as this doesn't seem to be an issue anymore.
