### ISSUE TITLE
Container creation

### ISSUE THREAD

**Issue by J-kumari** [lxc/lxc#1470]
Hi,
I am getting error during container creation.
Error: lxc-create: lxccontainer.c: create_run_template:1292 No such file or directory - failed to execute template /usr/share/lxc/templates/
Help me to solve the above error.

**Comment by stgraber** [comment]
What did you run exactly?

**Comment by J-kumari** [comment]
I am trying to run own templates.

**Comment by stgraber** [comment]
That's not answering the question. Also the error you pasted shows "/us/share" instead of "/usr/share".

**Comment by J-kumari** [comment]
I corrected it. How to solve the above error?

**Comment by stgraber** [comment]
Since you still haven't told use what command you actually ran, it's impossible to tell.

**Comment by J-kumari** [comment]
I am running the below command
lxc-create -n container1 -t lxc-container -- --rootfs-dir rootfs  --rootfs.tgz ./rootfs.tar.gz
Also, kernel version is 3.10.104 and lxc version is 2.0.7.
**I have enabled CONFIG_USER_NAMESPACE and it still shows missing. Let me know if I missed out any dependency package?**
lxc-checkconfig output:
Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
**User namespace: missing**
Network namespace: enabled
Multiple /dev/pts instances: enabled
--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled
--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: missing
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: missing
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
Checkpoint restore: missing
CONFIG_FHANDLE: missing
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: missing
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: missing
CONFIG_NETLINK_DIAG: missing
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

Below dependencies are enabled
•	kernel support for LXC
•	busybox support for lxc-create tool
•	support for seccomp in LXC
•	kernel cgroups
•	kernel namespaces
•	miscellaneous LXC related options   
•	libcap
•	libseccomp
•	kmod-veth

**Comment by stgraber** [comment]
And you have a file called /usr/share/lxc/templates/lxc-lxc-container? (note the lxc-lxc prefix)

If you only have a /usr/share/lxc/templates/lxc-container script, then you need to pass "-t container" instead.

**Comment by J-kumari** [comment]
I have lxc-container file. i have passed it as -t container but still I am getting error.

**Comment by stgraber** [comment]
can you paste the output of "ls -lh /usr/share/lxc/templates/"?

**Comment by J-kumari** [comment]
![lxc](https://cloud.githubusercontent.com/assets/26481004/24090425/0f677c74-0d66-11e7-995c-1032e477cf30.PNG)

**Comment by J-kumari** [comment]
Hi stgraber,
Should I need to give more information related to the above issue so that it can be easy to debug?

**Comment by J-kumari** [comment]
Hi stgraber
Should I need to give more information to debug the above error?

**Comment by stgraber** [comment]
running your lxc-create under "strace -fF" should help figure out what path it's actually trying to access

**Comment by Radoslaw-K** [comment]
@J-kumari 

To answer your question above : 
> **I have enabled CONFIG_USER_NAMESPACE and it still shows missing. Let me know if I missed out any dependency package?**

I'm not sure what `CONFIG_USER_NAMESPACE` does but what you actually need to enable for `lxc-checkconfig` to pass it's user namesepace test is `CONFIG_USER_NS` enabled

**Comment by J-kumari** [comment]
Ohhh, its CONFIG_USER_NAMESPACE

**Comment by J-kumari** [comment]
@stgraber 
[lxc-create.txt](https://github.com/lxc/lxc/files/860483/lxc-create.txt)
Find the attached of log file that was created after running lxc-create under strace -fF.

**Comment by hallyn** [comment]
78 access("/usr/share/lxc/templates/lxc-container", X_OK) = 0
 79 stat64(0x4141b0, 0x7fb06488)            = -1 ENOENT (No such file or directory)

**Comment by stgraber** [comment]
Can you paste the output of "head -1 /usr/share/lxc/templates/lxc-container"?

**Comment by stgraber** [comment]
strace shows that lxc-container exists and is executable which matches your earlier listing, but then fails to exec it with ENOENT. The most likely explanation for this is a missing shebang or broken shebang at the top of the file.

**Comment by J-kumari** [comment]
Thanks all. Problem is solved.

**Comment by sunhuchang** [comment]
Dear J-kumari, could u pls tell us the rootcause of this issue and your solution? I met the same one.
