### ISSUE TITLE
lxc-ls gives unexpected output

### ISSUE THREAD

**Issue by FransM** [lxc/lxc#1472]
lxc-ls (1.09) gives unexpected output:

$ lxc-ls D_wan_8*
D_wan_190_1  D_wan_31_1   D_wan_41_1   D_wan_51_1   D_wan_61_1   D_wan_81_1   D_wan_8_1  

These are all containers whose name starts with D_wan_
I also have containers whose name starts with D_lan_ but these are not listed

I expected only to get the last two container names.

**Comment by brauner** [comment]
That's has nothing to do with `lxc-ls` this sounds like python regex behavior:
```
>>> None == re.match("D_wan_8*", "D_wan190_1")
True
>>> None == re.match("D_wan_8*", "D_wan_1901")
False
```
The latter indicating that `match()` counts this as a match (https://docs.python.org/2/library/re.html might help).

**Comment by FransM** [comment]
Ah ok, I had expected the shell way of regexp handling where a* means a followed with anything.

Python re says this: 
Causes the resulting RE to match 0 or more repetitions of the preceding RE, as many repetitions as are possible. ab* will match ‘a’, ‘ab’, or ‘a’ followed by any number of ‘b’s

Guess this is is a false report then. Will close. Thanks for the info

**Comment by brauner** [comment]
Np, didn't know about that Python behavior myself. :)
