### ISSUE TITLE
Rebooting containers forget their veth.pair interface name.

### ISSUE THREAD

**Issue by t-fohrer** [lxc/lxc#1477]
Hi,

1. If i configure a simple lxc container with following network settings:

```
lxc.network.type = veth
lxc.network.name = eth0
lxc.network.veth.pair = v_11_lxc1
```
2. Starting container i got v_11_lxc1 on host.
2. Rebooting them via lxc-stop external or reboot inside container. 
3. I got a interface public veth pair interface named vethXXXX instead.

lxc version 2.0.6/2.0.7 by ubuntu.

Thanks for insight/look after.

**Comment by t-fohrer** [comment]
After looking in source code and removing 2 lines (see commit 85134663a4a52d92511bac80dbd47ae19ddc237e) veth pair name survive reboots.

best regards

Torsten Fohrer

**Comment by brauner** [comment]
Hm, we need to handle this a little smarter. Just removing the `free()` and `NULL` doesn't seem like a good idea. Thanks for digging into this.

**Comment by t-fohrer** [comment]
Hi,
have you any idea about a fix/eta for it?

We depend on fixed veth.pair names, and so this is blocker for us.

best regards
Torsten Fohrer

**Comment by brauner** [comment]
@t-fohrer, looked at the code right now and I think the patch you have is fine. Care to send it against LXC master?

**Comment by t-fohrer** [comment]
What aboud inclusion in stable-2.0 branch / next 2.0.x release?

best regards

**Comment by brauner** [comment]
@t-fohrer, I'm sure @stgraber will do this soon.

**Comment by brauner** [comment]
This has been cherry-picked into stable-2.0.
