### ISSUE TITLE
Seccomp:Container Fails to start with MIPS architecture

### ISSUE THREAD

**Issue by hemaintel** [lxc/lxc#1478]
Hello All, My container do not start, any insights to debug this issue would be greatly appreciated.

Details of the issue:
OS:Linux Kernel 3.10
LXC:1.1.15
HW:MIPS
Container: OpenWRT for MIPS arch

I am  using OpenWRT 15.05 with the malta target as container rootFS.

Container is started using below command 	

lxc-start  -n container3 -F  -P /lxc -o /lxc/test6.log -l trace

Log after trying to start the container
lxc-start 1490081470.949 INFO     lxc_start_ui - lxc_start.c:main:264 - using rcfile /lxc/ container3/config
      lxc-start 1490081470.960 WARN     lxc_cgfs - cgfs.c:lxc_cgroup_get_container_info:1100 - Not attaching to cgroup net_prio unknown to /lxc container3
      lxc-start 1490081470.964 INFO     lxc_seccomp - seccomp.c:parse_config_v2:324 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
      lxc-start 1490081470.964 INFO     lxc_seccomp - seccomp.c:parse_config_v2:324 - processing: .[all].
      lxc-start 1490081470.965 INFO     lxc_seccomp - seccomp.c:parse_config_v2:324 - processing: .kexec_load errno 1.
      lxc-start 1490081470.965 INFO     lxc_seccomp - seccomp.c:parse_config_v2:416 - Adding native rule for kexec_load action 327681
      lxc-start 1490081470.965 INFO     lxc_seccomp - seccomp.c:parse_config_v2:324 - processing: .open_by_handle_at errno 1.
      lxc-start 1490081470.965 INFO     lxc_seccomp - seccomp.c:parse_config_v2:416 - Adding native rule for open_by_handle_at action 327681
      lxc-start 1490081470.966 INFO     lxc_seccomp - seccomp.c:parse_config_v2:324 - processing: .init_module errno 1.
      lxc-start 1490081470.966 INFO     lxc_seccomp - seccomp.c:parse_config_v2:416 - Adding native rule for init_module action 327681
      lxc-start 1490081470.966 INFO     lxc_seccomp - seccomp.c:parse_config_v2:324 - processing: .finit_module errno 1.
      lxc-start 1490081470.967 INFO     lxc_seccomp - seccomp.c:parse_config_v2:416 - Adding native rule for finit_module action 327681
      lxc-start 1490081470.968 DEBUG    lxc_start - start.c:setup_signal_fd:264 - sigchild handler set
      lxc-start 1490081470.969 DEBUG    lxc_console - console.c:lxc_console_peer_default:500 - opening /dev/tty for console peer
      lxc-start 1490081470.969 DEBUG    lxc_console - console.c:lxc_console_peer_default:506 - using '/dev/tty' as console
      lxc-start 1490081470.970 DEBUG    lxc_console - console.c:lxc_console_sigwinch_init:179 - 28743 got SIGWINCH fd 9
      lxc-start 1490081470.970 DEBUG    lxc_console - console.c:lxc_console_winsz:88 - set winsz dstfd:6 cols:0 rows:0
      lxc-start 1490081470.970 INFO     lxc_start - start.c:lxc_init:460 - 'container3' is initialized
      lxc-start 1490081471.024 DEBUG    lxc_start - start.c:__lxc_start:1165 - Not dropping cap_sys_boot or watching utmp
      lxc-start 1490081471.246 DEBUG    lxc_conf - conf.c:instantiate_veth:2821 - instantiated veth 'vethF9HD38/vethY2DQE3', index is '38'
      lxc-start 1490081471.246 INFO     lxc_cgroup - cgroup.c:cgroup_init:65 - cgroup driver cgroupfs initing for container3
      lxc-start 1490081471.446 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.deny' set to 'a'
      lxc-start 1490081471.446 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:3 rwm'
      lxc-start 1490081471.447 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:5 rwm'
      lxc-start 1490081471.447 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 5:0 rwm'
      lxc-start 1490081471.447 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 5:1 rwm'
      lxc-start 1490081471.447 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:8 rwm'
      lxc-start 1490081471.447 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:9 rwm'
      lxc-start 1490081471.447 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 5:2 rwm'
      lxc-start 1490081471.448 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 136:* rwm'
      lxc-start 1490081471.448 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 254:0 rm'
      lxc-start 1490081471.448 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 10:200 rwm'
      lxc-start 1490081471.448 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 4:0 rwm'
      lxc-start 1490081471.448 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 4:1 rwm'
      lxc-start 1490081471.449 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'b 7:* rwm'
      lxc-start 1490081471.449 INFO     lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1926 - cgroup has been setup
      lxc-start 1490081471.557 DEBUG    lxc_conf - conf.c:lxc_assign_network:3238 - move 'veth0' to '28774'
      lxc-start 1490081471.729 DEBUG    lxc_conf - conf.c:setup_rootfs:1295 - mounted '/lxc/container3/rootfs' on '/usr/lib/lxc/rootfs'
      lxc-start 1490081471.730 INFO     lxc_conf - conf.c:setup_utsname:928 - 'container3' hostname has been setup
      lxc-start 1490081471.794 DEBUG    lxc_conf - conf.c:setup_hw_addr:2368 - mac address '00:FF:AA:00:00:03' on 'veth0' has been setup
      lxc-start 1490081471.799 DEBUG    lxc_conf - conf.c:setup_netdev:2595 - 'veth0' has been setup
      lxc-start 1490081471.799 INFO     lxc_conf - conf.c:setup_network:2616 - network has been setup
      lxc-start 1490081471.799 INFO     lxc_conf - conf.c:mount_autodev:1157 - Mounting container /dev
      lxc-start 1490081471.800 INFO     lxc_conf - conf.c:mount_autodev:1179 - Mounted tmpfs onto /usr/lib/lxc/rootfs/dev
      lxc-start 1490081471.800 INFO     lxc_conf - conf.c:mount_autodev:1197 - Mounted container /dev
      lxc-start 1490081471.801 INFO     lxc_conf - conf.c:fill_autodev:1225 - Creating initial consoles under container /dev
      lxc-start 1490081471.801 INFO     lxc_conf - conf.c:fill_autodev:1236 - Populating container /dev
      lxc-start 1490081471.802 INFO     lxc_conf - conf.c:fill_autodev:1269 - Populated container /dev
      lxc-start 1490081471.802 INFO     lxc_conf - conf.c:setup_ttydir_console:1539 - created /usr/lib/lxc/rootfs/dev/lxc
      lxc-start 1490081471.802 INFO     lxc_conf - conf.c:setup_ttydir_console:1585 - console has been setup on lxc/console
      lxc-start 1490081471.836 INFO     lxc_utils - utils.c:mount_proc_if_needed:1724 - I am 1, /proc/self points to '1'
      lxc-start 1490081471.837 DEBUG    lxc_conf - conf.c:setup_rootfs_pivot_root:1135 - pivot_root syscall to '/usr/lib/lxc/rootfs' successful
      lxc-start 1490081471.839 DEBUG    lxc_conf - conf.c:lxc_create_tty:3482 - allocated pty '/dev/pts/0' (11/14)
      lxc-start 1490081471.839 DEBUG    lxc_conf - conf.c:lxc_create_tty:3482 - allocated pty '/dev/pts/1' (15/16)
      lxc-start 1490081471.839 DEBUG    lxc_conf - conf.c:lxc_create_tty:3482 - allocated pty '/dev/pts/2' (17/18)
      lxc-start 1490081471.839 DEBUG    lxc_conf - conf.c:lxc_create_tty:3482 - allocated pty '/dev/pts/3' (19/20)
      lxc-start 1490081471.840 INFO     lxc_conf - conf.c:lxc_create_tty:3493 - tty's configured
      lxc-start 1490081471.840 INFO     lxc_conf - conf.c:setup_tty:1080 - 4 tty(s) has been setup
      lxc-start 1490081471.875 INFO     lxc_conf - conf.c:setup_personality:1473 - set personality to '0x8'
      lxc-start 1490081471.875 DEBUG    lxc_conf - conf.c:setup_caps:2279 - drop capability 'mac_admin' (33)
      lxc-start 1490081471.875 DEBUG    lxc_conf - conf.c:setup_caps:2279 - drop capability 'mac_override' (32)
      lxc-start 1490081471.875 DEBUG    lxc_conf - conf.c:setup_caps:2279 - drop capability 'sys_admin' (21)
      lxc-start 1490081471.875 DEBUG    lxc_conf - conf.c:setup_caps:2279 - drop capability 'sys_module' (16)
      lxc-start 1490081471.876 DEBUG    lxc_conf - conf.c:setup_caps:2279 - drop capability 'sys_nice' (23)
      lxc-start 1490081471.876 DEBUG    lxc_conf - conf.c:setup_caps:2279 - drop capability 'sys_pacct' (20)
      lxc-start 1490081471.876 DEBUG    lxc_conf - conf.c:setup_caps:2279 - drop capability 'sys_ptrace' (19)
      lxc-start 1490081471.876 DEBUG    lxc_conf - conf.c:setup_caps:2279 - drop capability 'sys_rawio' (17)
      lxc-start 1490081471.876 DEBUG    lxc_conf - conf.c:setup_caps:2279 - drop capability 'sys_resource' (24)
      lxc-start 1490081471.876 DEBUG    lxc_conf - conf.c:setup_caps:2279 - drop capability 'sys_time' (25)
      lxc-start 1490081471.876 DEBUG    lxc_conf - conf.c:setup_caps:2279 - drop capability 'sys_tty_config' (26)
      lxc-start 1490081471.876 DEBUG    lxc_conf - conf.c:setup_caps:2279 - drop capability 'syslog' (34)
      lxc-start 1490081471.876 DEBUG    lxc_conf - conf.c:setup_caps:2279 - drop capability 'wake_alarm' (35)
      lxc-start 1490081471.876 DEBUG    lxc_conf - conf.c:setup_caps:2288 - capabilities have been setup
      lxc-start 1490081471.876 NOTICE   lxc_conf - conf.c:lxc_setup:4026 - 'container3' is setup.
      lxc-start 1490081471.876 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.deny' set to 'a'
      lxc-start 1490081471.877 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:3 rwm'
      lxc-start 1490081471.877 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:5 rwm'
      lxc-start 1490081471.877 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 5:0 rwm'
      lxc-start 1490081471.877 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 5:1 rwm'
      lxc-start 1490081471.877 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:8 rwm'
      lxc-start 1490081471.877 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:9 rwm'
      lxc-start 1490081471.878 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 5:2 rwm'
      lxc-start 1490081471.878 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 136:* rwm'
      lxc-start 1490081471.878 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 254:0 rm'
      lxc-start 1490081471.878 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 10:200 rwm'
      lxc-start 1490081471.878 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 4:0 rwm'
      lxc-start 1490081471.879 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 4:1 rwm'
      lxc-start 1490081471.879 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'b 7:* rwm'
      lxc-start 1490081471.879 INFO     lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1926 - cgroup has been setup
      _**lxc-start 1490081471.880 ERROR    lxc_seccomp - seccomp.c:lxc_seccomp_load:593 - Error loading the seccomp policy
      lxc-start 1490081471.880 ERROR    lxc_sync - sync.c:__sync_wait:51 - invalid sequence number 1. expected 4
      lxc-start 1490081471.881 ERROR    lxc_start - start.c:__lxc_start:1192 - failed to spawn 'container3'
      lxc-start 1490081471.905 ERROR    lxc_cgfs - cgfs.c:cgroup_rmdir:207 - Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/lxc/container3-1
      lxc-start 1490081471.905 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
      lxc-start 1490081471.905 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.**_

The lxc-start is running into an error while trying to load the LXC-Seccomp policy.

When I disable the seccomp configuration loading at the startup by commenting it out in  /usr/share/lxc/config/openwrt.common.conf file, then the container starts properly.

# Blacklist some syscalls which are not safe in privileged
# containers
#lxc.seccomp = /usr/share/lxc/config/common.seccomp
The following packages are enabled in system

support for seccomp in LXC
libcap
libseccomp

Why does the LXC container fails to start? Any suggestions would be greatly appreciated to debug the issue.

**Comment by stgraber** [comment]
LXC 1.1.x is an unsupported release. Please reproduce this with one of:
 - LXC 1.0.9
 - LXC 2.0.7
 - current git

**Comment by stgraber** [comment]
```
commit 2ccd9edaa8b76f55e96187e9f3a44d758459b707
Author: James Cowgill <james410@cowgill.org.uk>
Date:   Mon Aug 15 16:09:44 2016 +0000
```

Confirmed that this commit is in LXC 1.0.9, LXC 2.0.7 and current git. But wasn't part of LXC 1.1.

So the problem is most likely that you're running unsupported LXC.

**Comment by hemaintel** [comment]
Tried with LXC 2.0.7 version and Issue is not resolved. LXC fails to start when I enable seccomp configuration at the start up in /usr/share/lxc/config/openwrt.common.conf file . Please find the log below:
 lxc-start 20170322043329.790 ERROR    lxc_seccomp - seccomp.c:lxc_seccomp_load:742 - Error loading the seccomp policy.
      lxc-start 20170322043329.791 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
      lxc-start 20170322043329.791 ERROR    lxc_start - start.c:__lxc_start:1346 - Failed to spawn container "container1".
      lxc-start 20170322043329.792 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20170322043329.792 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20170322043329.828 ERROR    lxc_cgfs - cgroups/cgfs.c:cgroup_rmdir:209 - Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/lxc/container1-4
      lxc-start 20170322043329.828 ERROR    lxc_start_ui - tools/lxc_start.c:main:366 - The container failed to start.
      lxc-start 20170322043329.835 ERROR    lxc_start_ui - tools/lxc_start.c:main:370 - Additional information can be obtained by setting the --logfile and --logpriority options.



Please provide your inputs to debug the issue.

**Comment by stgraber** [comment]
Ah, looks like the kernel is lacking seccomp bpf support for MIPS until the 3.15 kernel.

**Comment by hemaintel** [comment]
Can I have the patches to support secommp bpf for MIPS in 3.10 kernel?
One more question? I have not enabled aapamor and libcmanager packages? Does secommp package has any dependency on aapamor and libcmanager packages? Please clarify?

**Comment by stgraber** [comment]
seccomp is separate from apparmor and cgmanager so that's fine.

As for the kernel patches for MIPS seccomp support on 3.10, I don't know if anyone made some. Your best bet is to go look at what was pushed into the kernel around the 3.15 timefram and attempt to cherry-pick those commits into your kernel. https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/

**Comment by hemaintel** [comment]
Ok Thanks for your inputs.!
Does this issue has any dependency on libsecommp2 package. I am using libseccomp package.

Please clarify.

**Comment by stgraber** [comment]
It probably does, newer libseccomp2 is usually needed when they add new architectures.
