### ISSUE TITLE
Question: dnsmasq option

### ISSUE THREAD

**Issue by ojan** [lxc/lxc#1481]
Sorry for posting that may be a silly question in an issue but can't find the solution after searching.

How can i add dnsmasq option to a LXD version 2.11 ? I was using LXD_CONFILE in the /etc/default/lxd-bridge before but now this file is not used anymore, i'm lost.

I need to set a dns forwarding option for dnsmasq

thanks

**Comment by stgraber** [comment]
Hey there,

With LXD 2.3 and higher, the bridge is managed by LXD itself. To add custom options, you can set the "raw.dnsmasq" config option with whatever extra dnsmasq options you want.

Easiest is to do "lxc network edit lxdbr0" (or whatever your bridge is called), then in the "config" section, add the "raw.dnsmasq" key and set it to whatever you want.

Something like:
```
config:
  ipv4.address: 10.90.151.1/24
  ipv4.nat: "true"
  ipv6.address: 2001:470:b368:b2b5::1/64
  ipv6.nat: "true"
  raw.dnsmasq: |-
    no-hosts
    expand-hosts
    dhcp-ttl=3600
```

**Comment by stgraber** [comment]
Closing this issue as it was a support question which I believe has been answered.
