### ISSUE TITLE
 Failed to setup container 

### ISSUE THREAD

**Issue by fossxplorer** [lxc/lxc#1484]
I'm using LXC stable2.0 on CentOS 7 and i can't start a container with macvlan anymore. This used to work just fine for about an year ago IIRC. 

[root@node02 containers]# lxc-start --name cache_srv_01 -F
lxc-start: cgroups/cgfsng.c: create_path_for_hierarchy: 1306 Path "/sys/fs/cgroup/systemd//lxc/cache_srv_01" already existed.
   lxc-start: cgroups/cgfsng.c: cgfsng_create: 1363 No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/cache_srv_01: No such file or directory
                                          lxc-start: conf.c: setup_netdev: 2364 failed to set 'eth2' up : Device or resource busy
       lxc-start: conf.c: setup_network: 2465 failed to setup netdev
                                                                    lxc-start: conf.c: lxc_setup: 3855 failed to setup the network for 'cache_srv_01'
                           lxc-start: start.c: do_start: 811 Failed to setup container "cache_srv_01".
                                                                                                      lxc-start: sync.c: __sync_wait: 57 An error occurred in another process (expected sequence number 3)
                                                                                lxc-start: start.c: __lxc_start: 1350 Failed to spawn container "cache_srv_01".
                                     lxc-start: tools/lxc_start.c: main: 366 The container failed to start.
lxc-start: tools/lxc_start.c: main: 370 Additional information can be obtained by setting the --logfile and --logpriority options.

[root@node02 containers]# uname -r
4.10.1-1.el7.elrepo.x86_64
[root@node02 containers]# cat lxc/cache_srv_01/config
#### Uncomment the following line to support nesting containers:
###lxc.include = /usr/local/share/lxc/config/nesting.conf
#### Distribution configuration
lxc.include = /usr/local/share/lxc/config/centos.common.conf
lxc.arch = x86_64

### Container specific configuration
lxc.rootfs = /var/data/raptor/containers/lxc/cache_srv_01/rootfs
lxc.rootfs.backend = dir
lxc.utsname = cache_srv_01
lxc.cgroup.memory.limit_in_bytes = 4096M
lxc.cgroup.cpuset.cpus = 0-3 
### Network configuration
lxc.network.type = macvlan
lxc.network.macvlan.mode = bridge
lxc.network.link = enp2s0f0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:5a:18:05
lxc.network.name = eth2

lxc.network.type = veth
lxc.network.link = br0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:5a:19:6

It works works when i don't use macvlan network interfaces with the config file. I'm dependent on macvlan support.

**Comment by clhedrick** [comment]
Reloading the ixgbe module allows the container to be started again.
Definitely looks like a driver issue.

**Comment by stgraber** [comment]
Yeah, that error would be coming from the kernel, unfortunately not much we can do at the LXC level.
If this still happens, you'll definitely want to file a kernel bug with your distro to have this investigated.
