### ISSUE TITLE
Problems using lxc-device command

### ISSUE THREAD

**Issue by Radoslaw-K** [lxc/lxc#1485]
Hi LXC team,

I've built from source LXC 2.0.7 for Raspberry Pi 3 in general it looks to be functioning okay except for `lxc-device` command. What I want to do is to add a device such as `/dev/sda` from Pi to a container but when I run `lxc-device` with appropriate parameters then nothing happens. 

When I run it without any parameters expecting a usage info again nothing happens. Briefly looking through the `lxc-device.c` code on branch **stable-2.0** I figured I have to run this command as sudo. When I do I am able to see usage info when running this command without any parameters. 

However when I do run it with parameters then what I get is a message saying that the container I want to add the device to is not running even though it is running. 

Probably worth adding that I'm looking to run my containers in unprivileged mode.

Would appreciate any help please

**Comment by Radoslaw-K** [comment]
**Update:**

Tried going with the answer here:

http://serverfault.com/questions/663433/how-to-connect-a-dev-usb-modem-in-an-lxc-container

I'm stuck on the error that is mentioned there. 

Any ideas ?

**Comment by hallyn** [comment]
On Mon, Mar 27, 2017 at 03:37:17AM -0700, Radoslaw Kieltyka wrote:
> **Update:**
> 
> Tried going with the answer here:
> 
> http://serverfault.com/questions/663433/how-to-connect-a-dev-usb-modem-in-an-lxc-container
> 
> I'm stuck on the error that is mentioned there. 

It doesn't mention an error there ,just says "it doesn't work".  Can you
please show the precise error?

i.e.

lxc-start -n container -l debug -o debug.out

then show us the debug.out, show us the file you get in the container, and
show us what exactly fails.

**Comment by Radoslaw-K** [comment]
### debug.out: 

```
lxc-start 20170328083943.932 ERROR    lxc_conf - conf.c:mount_entry:1706 - No such file or directory - failed to mount '/dev/sda' on '/usr/local/lib/lxc/rootfs//dev/sda'
      lxc-start 20170328083943.932 ERROR    lxc_conf - conf.c:lxc_setup:3880 - failed to setup the mount entries for 'c1'
      lxc-start 20170328083943.932 ERROR    lxc_start - start.c:do_start:811 - Failed to setup container "c1".
      lxc-start 20170328083943.933 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
      lxc-start 20170328083943.934 ERROR    lxc_start - start.c:__lxc_start:1350 - Failed to spawn container "c1".
      lxc-start 20170328083949.526 ERROR    lxc_start_ui - tools/lxc_start.c:main:366 - The container failed to start.
      lxc-start 20170328083949.528 ERROR    lxc_start_ui - tools/lxc_start.c:main:368 - To get more details, run the container in foreground mode.
      lxc-start 20170328083949.529 ERROR    lxc_start_ui - tools/lxc_start.c:main:370 - Additional information can be obtained by setting the --logfile and --logpriority options.
```

### .local/share/lxc/c1/config:

```
# Template used to create this container: /usr/local/share/lxc/templates/lxc-download
# Parameters passed to the template: -d ubuntu -r trusty -a armhf
# For additional config options, please look at lxc.container.conf(5)

# Uncomment the following line to support nesting containers:
#lxc.include = /usr/local/share/lxc/config/nesting.conf
# (Be aware this has security implications)


# Distribution configuration
lxc.include = /usr/local/share/lxc/config/ubuntu.common.conf
lxc.include = /usr/local/share/lxc/config/ubuntu.userns.conf

# Container specific configuration
lxc.id_map = u 0 362144 65536
lxc.id_map = g 0 362144 65536
lxc.rootfs = /home/pi/.local/share/lxc/c1/rootfs
lxc.rootfs.backend = dir
lxc.utsname = c1





lxc.cgroup.devices.allow = b 8:* rwm
lxc.mount.entry = /dev/sda /home/pi/.local/share/lxc/c1/rootfs/dev/sda none bind 0 0
lxc.aa_profile = unconfined
```

As requested, above is the error log and configuration file that I'm using for the container. To answer "What exactly fails" - The container doesn't start at all.

**Comment by hallyn** [comment]
Change 
lxc.mount.entry = /dev/sda /home/pi/.local/share/lxc/c1/rootfs/dev/sda none bind 0 0

to

lxc.mount.entry = /dev/sda /home/pi/.local/share/lxc/c1/rootfs/dev/sda none bind,create=file 0 0

**Comment by Radoslaw-K** [comment]
@hallyn That worked fine in that I can now start the container and see the device in it but when I try to perform any operation on it I get "Permission denied". Same when I try with a serial device (ttyS0). What can I do now ?

**Comment by hallyn** [comment]
Assuming the device isn't shared with anything on the host, you
may be able to chown it to the container root permissions, i.e.

	sudo chown 362144:362144 /dev/sdc

Of course, giving an unprivileged container access to a raw disk
device is not advisable if the host is also going to be using it.

There are also many cases where this will still fail because userspace
tries to do an ioctl() or something on the device, which the kernel
will fail if you are not host root.  In that case you simply cannot
use an unprivileged container.

Hardware access from containers at this point remains barbarian.

**Comment by Radoslaw-K** [comment]
@hallyn Your help is much appreciated. Chown'ing the device to the subuid as you specified above solved the problem. As a side note I did not know that having devices owned by subuid user was possible. 

I'll also take into consideration your words of caution about the use of unprivileged containers for this purpose.

Again, thank you very much 👍
