### ISSUE TITLE
lxc.network.script.up with multiple interfaces - relate it to the network setting in config file?

### ISSUE THREAD

**Issue by tomponline** [lxc/lxc#1497]
When using a lxc.network.script.up script, the interface name in the parent is passed as an argument to the command.

However when using dynamic peer device names (the default) there doesn't seem to be a way for the script to relate the temporary device name to the container's config file (i.e to parse IP addresses, MAC addresses etc).

Also, the up script seems to be executed before the MAC address in the config file is applied to the container's network interface. This means I can't use 'ip link' to figure out the container's mac address from the peer's device name and then relate it to config.

This all feels rather complicated. Could the network device index from the config file (i.e 0,1,2) be passed to the network up script, so that I can then parse the config file and figure out the settings for that particular interface.

The reason for this btw is that I'm using proxy arp and proxy ndp, so need to configure per-IP routes on the host for the container's IPs going to the correct peer veth device.

Thanks!

**Comment by tomponline** [comment]
I was thinking, could the ifindex be added as an arg to the up script:

https://github.com/lxc/lxc/blob/master/src/lxc/conf.c#L2680

**Comment by tomponline** [comment]
I've solved my problem, but wanted to check this is a "supported" approach.

I've found that the netup script supports arguments, e.g.

```
lxc.network.name = eth0
lxc.network.ipv4 = 192.168.1.4/32
lxc.network.script.up = /root/bin/net-up eth0
```

The "eth0" argument is then pass to the net-up script and so I can use it to interrogate the config file and find the IP addresses for that network using go-lxc library.

Is using arguments in the lxc.network.script.up supported?

Thanks

**Comment by brauner** [comment]
Sorry, I somehow missed this issue totally. So yes, the way you do it in the last step is definitely possible. The command you're using is internally passed to a function that will take care of running the command through the shell.

I am somewhat confused by the title of your issue since you said "multiple interfaces". So when you want to specify multiple networks with `LXC` the correct way to do it is:

```
	lxc.network.0.type = veth
	lxc.network.0.flags = up
	lxc.network.0.link = lxdbr0
	lxc.network.0.hwaddr = 00:16:3e:09:7a:39
	lxc.network.0.name = eth0

	lxc.network.1.type = veth
	lxc.network.1.flags = up
	lxc.network.1.link = lxdbr1
	lxc.network.1.hwaddr = 00:16:3e:b2:8f:56
	lxc.network.1.name = eth1
```
I think we can close this issue but please ping if you want to re-open. :)

**Comment by tomponline** [comment]
@brauner thanks thats good to hear.

The reason I was having trouble is that the built in arguments passed to the lxc.network.script.up script do not indicate which interface is being brought up/down relative to the config file.

In your example above, the interface identifier in the config is the index number, e.g. 0 or 1, but this is not passed to the up script as an arg/env var (AFAIK) so I could get the up script to parse the config file (using go-lxc) and then extract the config for the particular interface being brought up/down.

An example here is that I'm using proxy arp rather than bridging, and need to know what IPs are in the config file, in order to setup the relevant proxy arg settings on the host node.

I have a go-lxc based script that can parse the config file and get the IPs, but right now the only way to identify which interface is being brought up is to put a manual identifier as an argument in the up script definition in the config file.

**Comment by brauner** [comment]
Hm, we can indeed pass this as an envelope variable. Just need to make sure that this isn't somehow done already.

**Comment by brauner** [comment]
s/envelope/environment/

**Comment by brauner** [comment]
When you say "interface identifier" do you mean `eth0` or whatever the name of the interface is when we dynamically allocate it? Surely you want the name (e.g. `eth0`) and not just the index `0` which can be missing.

**Comment by tomponline** [comment]
@brauner Actually the name of the device inside the container isn't something I'm after. Although if it is statically specified in the config file and passed to the up script as an arg/env var then it could be used as an anchor to find which interface was being brought up.

The ideal thing though would be the specified IPs themselves being injected as an environment variable.

This is the script I am working on btw:

https://github.com/tomponline/ctctl/blob/master/ctctl-netup/ctctl-netup.go

Combined with an example config like:

```
lxc.network.type = veth
lxc.network.flags = up
lxc.network.script.up = /usr/libexec/lxc/ctctl-netup
lxc.network.ipv4 = 192.168.1.10/32
lxc.network.ipv4 = 192.168.3.10/32
lxc.network.ipv6 = xxxx:390:76f4:1::10/128
lxc.network.ipv4.gateway = 192.0.2.1
lxc.network.ipv6.gateway = fd60:eafa:54a9::1
```

Right now this script only works with a single interface anyway.

But in the future, it would be useful for the up script to be able to know enough to be able to read the config file and parse the rest of the network information for the specific interface being brought up.
