### ISSUE TITLE
Ubuntu template: breaks host keymap and consolefont

### ISSUE THREAD

**Issue by globalcitizen** [lxc/lxc#15]
While the version I am using is not absolute latest, diffing /usr/share/lxc/templates/lxc-ubuntu with the raw https://raw.github.com/lxc/lxc/staging/templates/lxc-ubuntu.in file revealed nothing suggesting this issue has been resolved.

Observed behaviour: Both the use of windows/command keys on PC/Mac to migrate to previous/next console, and the console font for virtual terminals on the host's console (within the default range of the Ubuntu container under setup) are broken.

Desired behaviour: Any script executing to set up the guest should not affect the host system.

**Comment by brauner** [comment]
This bug should be fixed. Please reopen if it persists.
