### ISSUE TITLE
Get stdout and stderr of a command in Python variable

### ISSUE THREAD

**Issue by npatel33** [lxc/lxc#1506]
I am trying to understand Python API for lxc. So far I am unsuccessful in getting output of the command ran in container into python variable.

for example, i am running following command and I want output inside one python variable,
`cont.attach_wait(lxc.attach_run_command, ["ifconfig"])`

Anyone know how to do that?

**Comment by stgraber** [comment]
If you care about the output, you need to pass a different function to attach_wait and setup some kind of communication channel between the main process and the command to send the output back.

Opening an fd and sending the output over it should do the trick.

**Comment by npatel33** [comment]
Thanks a lot. It works.

This link also helped:
[https://lists.linuxcontainers.org/pipermail/lxc-devel/2013-August/004898.html](https://lists.linuxcontainers.org/pipermail/lxc-devel/2013-August/004898.html)

I used following statements:
`fd = open('filename', 'w')`
`cont.attach_wait(lxc.attach_run_command, ["ifconfig"], stdout=fd)`
`fd.close()`

after running this, i get required output in file just created.

**Comment by npatel33** [comment]
Just a quick question though, is it safe in terms of isolation?

**Comment by psrihari007** [comment]
Another option is to use pipes:
p_rd, p_wr = os.pipe()
writF = os.fdopen(p_wr)
cont.attach_wait(lxc.attach_run_command, ["ifconfig"], stdout=writF)
writF.close()
# Now read from p_rd as a regular file and then close it.

It should be safe regarding isolation, as the output is collected from outside the container.
