### ISSUE TITLE
Use standard resolver in lxc-download

### ISSUE THREAD

**Issue by ghost** [lxc/lxc#1507]
When filesystem eg. /dev/sda1 is mounted to **/srv/nginx** and **lnx.lnxpatch = /srv** is set too.

```
root@rastel:/srv# lxc-create -n nginx -t download

Setting up the GPG keyring
ERROR: Unable to fetch GPG key from keyserver.
lxc-create: lxccontainer.c: create_run_template: 1297 container creation template for nginx failed
lxc-create: utils.c: _recursive_rmdir: 170 _recursive_rmdir: **failed to delete /srv/nginx**
lxc-create: lxccontainer.c: container_destroy: 2411 Error destroying container directory for nginx
lxc-create: tools/lxc_create.c: main: 318 Error creating container nginx
```

Everything is OK, when
`root@rastel:/srv# lxc-create -n nginx -t gentoo`

**Comment by brauner** [comment]
Sorry, what exactly is the problem?

**Comment by akasei** [comment]
Can't create lxc container when /srv/nginx has filesystem mounted.

**Comment by stgraber** [comment]
What do you have in /etc/lxc/default.conf?

**Comment by akasei** [comment]
/etc/lxc/default.conf
`lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:xx:xx:xx`

/etc/lxc/lxc.conf
`lxc.lxcpath = /srv`

**Comment by stgraber** [comment]
Cool, so yeah, the error makes sense.

lxc-create assumes that it's creating the container path, so on failure will attempt to remove it, which fails here as the particular path is a mountpoint.

The real issue you're running into is that the lxc-download template is failing to connect to the GPG key network and so can't fetch the GPG key needed to then download the image.

If you are on a restricted network which requires the use of a proxy, make sure that http_proxy and https_proxy are set to appropriate values in your environment, lxc-create will then respect those.

**Comment by akasei** [comment]
This is not a restricted network :) but dunno.
lxc-create should on mountpoint only dump everything inside directory.

**Comment by MrSorcus** [comment]
I think that would be great to add option `standard-resolver` (dirmngr.conf) here https://github.com/lxc/lxc/blob/508f4700109a44963038b7354db0a3fc2ef5cc5d/templates/lxc-download.in#L128-L133

**Comment by comannnnndooooo** [comment]
Myself and my uni group are taking a look at putting this in.
