### ISSUE TITLE
ZFS unprivileged ephemeral copy: Invalid argument - Overlayfs

### ISSUE THREAD

**Issue by kadfak** [lxc/lxc#1515]
Creating an ephemeral copy in a ZFS pool using `lxc-copy -n c1 -e` gives me such error:
```
lxc-copy: bdev/lxcoverlay.c: ovl_mount: 430 Invalid argument - Overlayfs: Error mounting /embeddabl/c1/rootfs onto /usr/lib/x86_64-linux-gnu/lxc with options upperdir=/embeddabl/c1_j7f5zM/delta0,lowerdir=/embeddabl/c1/rootfs: Invalid argument.
```

Base container was created using `lxc-create -t download -n c1 -- -d ubuntu -r yakkety -a amd64`

.config/lxc/default.conf
```
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
lxc.network.type = veth
lxc.network.link = lxcbr0
```

.config/lxc/lxc.conf 
```
lxc.lxcpath = /embeddabl
lxc.bdev.zfs.root = embeddabl
```
Everything was working perfectly until I went on using ZFS.

**Comment by brauner** [comment]
I'm not sure that overlay works correctly with cow filesystems like btrfs and zfs. It may have changed though. The right solution would probably to use the snapshot feature of zfs itself. If someone's up for writing a patch the code is in `bdev/lxczfs.{c,h}`.

**Comment by stgraber** [comment]
overlayfs cannot be stacked on top of zfs, so this is unfortunately expected.
I also don't think we should be putting detection logic for this case as exactly what can be stacked on what is kernel dependent and may vary based on distros.
