### ISSUE TITLE
Second lxcbr?

### ISSUE THREAD

**Issue by chiasamen** [lxc/lxc#1524]
Is there any builtin functionality for a second net separated from the first lxcbr0? 
 > /usr/lib/x86_64-linux-gnu/lxc/lxc-net

seems pretty fixed to lxcbr0
I want to encapsulate two containers in their own net (with own ip range) and don't want access to the others.
How would I get a seond lxcbr? Is there any other recommended way of achieving this?

**Comment by hallyn** [comment]
lxc-net is indeed not well laid out for doing this for you
automatically.  You can pretty easily create your own.  Instructions
will vary a bit based on your distro, but basically just create the
bridge, write the nat rule for it, and start using it..

Quoting chiasamen (notifications@github.com):

**Comment by chiasamen** [comment]
Mhm, ok thanks.
I did as you advised. I'd share my solution but actually it's pretty embarrassing since I didn't want to waste much time and basically copied the script and changed some function and variable names...
Where would I store the new script in order to overwrite the original script but not being exposed to an package update? (Ubuntu if relevant)
If it were a bin file I'd copy it to /usr/local/bin - is there any similiar directory for that?

**Comment by stgraber** [comment]
```
sudo dpkg-divert --local --divert /usr/lib/x86_64-linux-gnu/lxc/lxc-net.orig --add /usr/lib/x86_64-linux-gnu/lxc/lxc-net
```

This will cause any package update of /usr/lib/x86_64-linux-gnu/lxc/lxc-net to be written to /usr/lib/x86_64-linux-gnu/lxc/lxc-net.orig instead. Keeping your modified version untouched.

**Comment by evgeni** [comment]
Or you could just setup a static bridge in `/etc/network/interfaces(.d)?`

```
auto lxcbr1
iface lxcbr1 inet static
        address         172.16.0.1/24
        pre-up          brctl addbr lxcbr1
        post-down       brctl delbr lxcbr1
        bridge_fd       0
        bridge_maxwait  0
```

**Comment by brauner** [comment]
Cool, this sounds like two viable options to get this done. I think we can close.
