### ISSUE TITLE
Delete port from OVS bridge when starting container 

### ISSUE THREAD

**Issue by itoffshore** [lxc/lxc#1530]
This issue is the same as https://github.com/lxc/lxc/issues/590 but with a different cause.

`lxc` should probably also run `ovs-vsctl --if-exists del-port portname` when it starts a container using an openvswitch `bridge`.

If a container is not stopped gracefully (due to a power off  or similar) -  it won't start next time around.

I work around this by using in the container `config`:

`lxc.hook.pre-start = /etc/lxc/ovsdown`

& in `ovsdown`:

```
#!/bin/sh
ovs-vsctl --if-exists del-port veth.$LXC_NAME 
```
I use Alpine Linux containers in an Alpine host 
```
root@alpine [~]# lxc-start --version
2.0.6
```

**Comment by brauner** [comment]
I don't think that we want LXC to delete random ports on container startup. It might just be the case that someone created a `veth.$LXC_NAME` device manually that they would like to keep around.

**Comment by brauner** [comment]
@itoffshore, my point is that someone could have created that port with that name independent of lxc. So starting lxc with your proposed patch would delete that port (given the right permissions) even though it's not under lxc's control.

**Comment by itoffshore** [comment]
ok I see your point - perhaps the above will be helpful for others with broken containers after a power off
