### ISSUE TITLE
Force a Snapshot Overwrite

### ISSUE THREAD

**Issue by kpirnie** [lxc/lxc#1532]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04.2

# Issue description
It would be nice to be able to overwrite an existing snapshot.  For instance I take nightly snapshots, but if I go and decide to work on a container, I'd like to overwrite the latest with a new one.

Right now, I have to delete it, and recreate it.

**Comment by brauner** [comment]
This is likely something which is out of focus for low-level liblxc. We might implement something like this in [LXD](https://github.com/lxc/lxd) but for the simple tools here you should simply script this.

**Comment by kpirnie** [comment]
Mmmm...  I guess.  delete the orginal first, then take a new snap.  Seems a tad "hacky" tho... sort of along the lines of no "real"way to remove "old" snapshots...  (which I have a hacky solution for...)

**Comment by brauner** [comment]
Wait, what exactly are you trying to do?
- are you trying to restore a container from a snapshot?
- are you trying to delete an already existing snapshot?
- are you trying to delete an existing snapshot and replace it with a new one of the same name?

**Comment by kpirnie** [comment]
Sorry mate.  Didn't mean any confusion.  For this topic, my goal was to have an easier way to overwrite an existing snapshot.

Without having to jump through the "delete the existing one first, create the new one"

**Comment by brauner** [comment]
Ah, no worries. I was just wonder whether we've actually have a command for this. :)

**Comment by kpirnie** [comment]
I wish :)   Was trying the ol' --force (but alas, no dice) lol

You should see the convoluted work around I have in place LMFAO...   (once the week's over, I'll actually have some time to re-write it so it's clean  LOL)

**Comment by hallyn** [comment]
If you're going to write this, how about calling it --overwrite. --force could be confusing.

**Comment by kpirnie** [comment]
I could certainly try...  but I would not know where to start lol.
I can write bash scripts, vb, c#, php, js, html, css   that's about the extent of it LOL

**Comment by kpirnie** [comment]
Here's the basics of what I have now... again... seems to me it's a bit of a hacky way to have to do something like this..  but... que se ra, se ra

```
#!/bin/bash
# Change to match your environment
CONT_DIR=/home/containers;

for d in $CONT_DIR/*
do
	if [ -d $d ]; then
		name=`basename $d`;
		s=( $( lxc list $name --format=json | jq -r '.[].snapshots[].name' ) );
		snaps="${s[@]}";
		today=$(date +'%Y-%m-%d');
		yesterday=$(date -d '1 day ago' '+%Y-%m-%d');
		echo "Snapshots for: $name"
		for sn in $snaps; do
			if [[ $sn == "$name/$today-$name" ]] || [[ $sn == "$name/$yesterday-$name" ]]; then
				echo "MATCH: $sn";
			else
				echo "NON-MATCH: $sn";
			fi;
		done;
		echo '--------------------------';
	fi
done;
	
```
This only lists, and "matches" the last 2 days worth of snapshots.  It also assumes your snapshots are named: YYYY-MM-DD-CONTAINERNAME
