### ISSUE TITLE
detect the wrong init type on centos 7

### ISSUE THREAD

**Issue by 0x0916** [lxc/lxc#1546]
# Required information

 * Distribution: centos
 * Distribution version: 7
 * The output of `cat /etc/os-release `
```
localhost:~/lxc # cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

# Issue description

on centos 7, the init type is `systemd`, but the `./configure` detect the wrong init type.(`sysvinit`). 

# Steps to reproduce

 1. Step one
```
./autogen.sh
```
 2. Step two
```
$ ./configure
...
----------------------------
Environment:
 - compiler: gcc
 - distribution: centos
 - init script type(s): sysvinit
 - rpath: no
 - GnuTLS: no
 - Bash integration: yes
...
```

Also, the ubuntu now use systemd, I think we should find a proper way to detect the init type.

**Comment by brauner** [comment]
@0x0916, are you planning on sending a PR?

**Comment by 0x0916** [comment]
I still  can not find a proper way to detect the init system type. here are some search result:

* https://unix.stackexchange.com/questions/196166/how-to-find-out-if-a-system-uses-sysv-upstart-or-systemd-initsystem
* https://unix.stackexchange.com/questions/18209/detect-init-system-using-the-shell

@brauner , Do you think which is better?
