### ISSUE TITLE
lxc_spawn failure

### ISSUE THREAD

**Issue by jlatency** [lxc/lxc#1555]
# Required information

 * Distribution: ArchLinux
 * `lxc-start --version` 2.0.8
 * `uname -m` x86_64
 *  `uname -r` 4.10.13-1-ARCH

# Issue description

After updating to last release of lxc, a privileged container does not work anymore.
I created a new container (template archlinux).
Everything worked, but when I tried to launch it, an error occurred.

The following is an extract from the log file
`sudo lxc-start -n trial -o log -l debug`
`cat log | less`
...
lxc-start 20170513140813.734 ERROR    lxc_start - start.c:lxc_spawn:1182 - Failed to set up id mapping.
lxc-start 20170513140813.735 ERROR    lxc_start - start.c:__lxc_start:1354 - Failed to spawn container "trial".
...

# Steps to reproduce

 1. `sudo lxc-create -t /usr/share/lxc/templates/lxc-archlinux -n trial`
 2. `sudo lxc-start -n trial`
output: 
lxc-start: tools/lxc_start.c: main: 366 The container failed to start.
lxc-start: tools/lxc_start.c: main: 368 To get more details, run the container in foreground mode.
lxc-start: tools/lxc_start.c: main: 370 Additional information can be obtained by setting the --logfile and --logpriority options.

# Information to attach

The container config file is the default one.
I'll attach it below.

`sudo cat /var/lib/lxc/trial/config`
\# Template used to create this container: /usr/share/lxc/templates/lxc-archlinux
\# Parameters passed to the template:
\# Template script checksum (SHA-1): fbb0f184178e8d53f27d19e5828701033a19c543
\# For additional config options, please look at lxc.container.conf(5)

\# Uncomment the following line to support nesting containers:
\#lxc.include = /usr/share/lxc/config/nesting.conf
\# (Be aware this has security implications)

lxc.network.type = empty
lxc.rootfs = /var/lib/lxc/trial/rootfs
lxc.rootfs.backend = dir
lxc.utsname = trial
lxc.arch = x86_64
lxc.include = /usr/share/lxc/config/archlinux.common.conf

**Comment by brauner** [comment]
Can you please start the container with `sudo lxc-start -n trial -l debug -o trial.log` and either append `trial.log` or paste its contents in here?

**Comment by jlatency** [comment]
# Cmd

`sudo lxc-start -n trial -l debug -o trial.log`
 
lxc-start: tools/lxc_start.c: main: 366 The container failed to start.
lxc-start: tools/lxc_start.c: main: 368 To get more details, run the container in foreground mode.
lxc-start: tools/lxc_start.c: main: 370 Additional information can be obtained by setting the --logfile and --logpriority options.

# Log File

      lxc-start 20170513142726.426 INFO     lxc_start_ui - tools/lxc_start.c:main:275 - using rcfile /var/lib/lxc/trial/config
      lxc-start 20170513142726.426 WARN     lxc_confile - confile.c:config_pivotdir:1916 - lxc.pivotdir is ignored.  It will soon become an error.
      lxc-start 20170513142726.426 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:330 - Going to wait for pid 4232.
      lxc-start 20170513142726.427 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:349 - Trying to sync with child process.
      lxc-start 20170513142726.427 INFO     lxc_start - start.c:lxc_check_inherited:235 - Closed inherited fd: 4.
      lxc-start 20170513142726.427 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:387 - Using pipe file descriptor 5 for monitord.
      lxc-start 20170513142726.430 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:364 - Successfully synced with child process.
      lxc-start 20170513142726.430 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:333 - Finished waiting on pid 4232.
      lxc-start 20170513142726.431 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:802 - Attempting to set proc title to [lxc monitor] /var/lib/lxc trial
      lxc-start 20170513142726.431 INFO     lxc_utils - utils.c:setproctitle:1506 - setting cmdline failed - Invalid argument
      lxc-start 20170513142726.431 DEBUG    lxc_start - start.c:setup_signal_fd:273 - Set SIGCHLD handler with file descriptor: 5.
      lxc-start 20170513142726.431 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:330 - Going to wait for pid 4236.
      lxc-start 20170513142726.432 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:349 - Trying to sync with child process.
      lxc-start 20170513142726.432 DEBUG    console - console.c:lxc_console_peer_default:438 - process does not have a controlling terminal
      lxc-start 20170513142726.432 INFO     lxc_start - start.c:lxc_init:475 - Container "trial" is initialized.
      lxc-start 20170513142726.432 INFO     lxc_start - start.c:lxc_check_inherited:235 - Closed inherited fd: 4.
      lxc-start 20170513142726.432 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:387 - Using pipe file descriptor 5 for monitord.
      lxc-start 20170513142726.432 DEBUG    lxc_start - start.c:__lxc_start:1325 - Not dropping CAP_SYS_BOOT or watching utmp.
      lxc-start 20170513142726.432 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for trial
      lxc-start 20170513142726.432 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:filter_and_set_cpus:480 - No isolated cpus detected.
      lxc-start 20170513142726.432 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:handle_cpuset_hierarchy:650 - "cgroup.clone_children" was already set to "1".
      lxc-start 20170513142726.433 INFO     lxc_start - start.c:lxc_spawn:1165 - Cloned CLONE_NEWNS.
      lxc-start 20170513142726.433 INFO     lxc_start - start.c:lxc_spawn:1165 - Cloned CLONE_NEWPID.
      lxc-start 20170513142726.433 INFO     lxc_start - start.c:lxc_spawn:1165 - Cloned CLONE_NEWUTS.
      lxc-start 20170513142726.433 INFO     lxc_start - start.c:lxc_spawn:1165 - Cloned CLONE_NEWIPC.
      lxc-start 20170513142726.433 INFO     lxc_start - start.c:lxc_spawn:1165 - Cloned CLONE_NEWNET.
      lxc-start 20170513142726.433 DEBUG    lxc_conf - conf.c:lxc_map_ids:3377 - Either one or both of the newuidmap and newgidmap binaries do not exist or are missing necessary privilege.
      lxc-start 20170513142726.433 ERROR    lxc_start - start.c:lxc_spawn:1182 - Failed to set up id mapping.
      lxc-start 20170513142726.434 ERROR    lxc_start - start.c:__lxc_start:1354 - Failed to spawn container "trial".
      lxc-start 20170513142726.435 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:364 - Successfully synced with child process.
      lxc-start 20170513142726.435 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:333 - Finished waiting on pid 4236.
      lxc-start 20170513142726.435 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:201 - using monitor socket name "lxc/ad055575fe28ddd5//var/lib/lxc" (length of socket name 33 must be <= 105)
      lxc-start 20170513142726.435 DEBUG    lxc_monitor - monitor.c:lxc_monitor_open:225 - opening monitor socket lxc/ad055575fe28ddd5//var/lib/lxc with len 33
      lxc-start 20170513142726.469 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.
      lxc-start 20170513142731.470 ERROR    lxc_start_ui - tools/lxc_start.c:main:366 - The container failed to start.
      lxc-start 20170513142731.470 ERROR    lxc_start_ui - tools/lxc_start.c:main:368 - To get more details, run the container in foreground mode.
      lxc-start 20170513142731.470 ERROR    lxc_start_ui - tools/lxc_start.c:main:370 - Additional information can be obtained by setting the --logfile and --logpriority options.

**Comment by brauner** [comment]
Thanks for reporting this. Will send a branch soon!

**Comment by brauner** [comment]
Can you show me the output of `which newuidmap` and `which newgidmap`, please?

**Comment by jlatency** [comment]
Sure!

 * `which newgidma`  →  /usr/bin/newuidmap
 * `which newgidmap `  →  /usr/bin/newgidmap

**Comment by brauner** [comment]
This is a `LXC` bug but independent of that your distro should ship `newuidmap` and `newgidmap` either as `setuid` binaries or set necessary capabilities on them. So as a temporary workaround until we push that fix, please either do:

```
sudo chmod 04755 /usr/bin/newuidmap
sudo chmod 04755 /usr/bin/newgidmap
```
or

```
sudo setcap cap_setuid+ep /usr/bin/newuidmap
sudo setcap cap_setgid+ep /usr/bin/newgidmap
```

This should allow you to start your containers.

**Comment by jlatency** [comment]
This works!
Thanks
