### ISSUE TITLE
Is there an easy way to update `lxc.utsname`?

### ISSUE THREAD

**Issue by 0x0916** [lxc/lxc#1561]
Hi, I want to update the `lxc.utsname` item for my container by coding, currently my code looks like

```c
	c->clear_config_item(c, "lxc.utsname");
	c->set_config_item(c, "lxc.utsname", NEW_UTSNAME);
``` 

before update, the config file for container already contains `lxc.utsname`  item,
after call `{clear|set}_config_time()` and `save_config`, the new config file contains two
`lxc.utsname` item.

I expect that the new config file only contains only one `lxc.utsname` item.

Is there an easy way to update an lxc config item except updating it by using editors directly?
If no way, how about implement an new  API for lxc container `update_config_item`?

**Comment by brauner** [comment]
This is in line with all of our configuration options so far. They override each other in the order specified. So you can specify:

    lxc.utsname = a
    lxc.utsname = b
    lxc.utsname = c

and `LXC` will only care about `c`. However, we should allow to clear any pre-existing set of e.g. `lxc.utsname` items so that when you add doe `clear(lxc.utsname)`,  `set(lxc.utsname=bla)`, `save_config()` you'd always only get:

    lxc.utsname =
    lxc.utsname = d

instead of


    lxc.utsname = a
    lxc.utsname = b
    lxc.utsname = c
    lxc.utsname = d

**Comment by 0x0916** [comment]
how about implement an new API for lxc container `update_config_item`?  Pseudo-code ：

```c
update_config_item()
{
         clear_unexp_config_line(c->config, "lxc.utsname", false);
         set_config_item_locked(c2, "lxc.utsname", newname);
}
```
I would like to add a new API for update if you do not mind.

**Comment by brauner** [comment]
That would achieve the same as:

    c->clear_config_item(c, "lxc.utsname");
    c->set_config_item(c, "lxc.utsname", NEW_UTSNAME);

when my changes are merged. So I don't see the value of having another public api call just for that. :)

**Comment by 0x0916** [comment]
@brauner, not the same.
```
lxc.utsname = a
```
after the update, we will get 

```
lxc.utsname = b
```
instead of 
```
lxc.utsname =
lxc.utsname = b
```

**Comment by brauner** [comment]
I'm not convinced enough for another api call just for that. The api call would basically just exist to update the on-disk config file. The in-memory update will already be done reliably through the existing api calls. Apart from `{load,save}_config()` we don't really allow a lot if interaction with the on-disk config file through the api. Also, this might make sense for some keys that usually just appear a single time but it will make less sense for keys that can appear multiple times (e.g. `lxc.mount.entry` and so on).
