### ISSUE TITLE
Any plans to add feature for limit syscall argument?

### ISSUE THREAD

**Issue by 0x0916** [lxc/lxc#1564]
`seccomp` can limit syscall arguments, but it does not exposed by lxc, we can extend seccomp feature to support that.

**Comment by brauner** [comment]
Sure, patches welcome.

**Comment by 0x0916** [comment]
Hello all, before the coding, I would like to discuss the design for it.

The current seccomp configuration file support version 1 and version 2. for the version 2, it looks
like:

```
2
blacklist
reject_force_umount  # comment this to allow umount -f;  not recommended
[all]
kexec_load errno 1
open_by_handle_at errno 1
init_module errno 1
finit_module errno 1
delete_module errno 1
```

To support limit syscall arguments, how should we design the new configuration file.
how about extend the version 2 file to the following format:

```
syscall_name default_action num [index,value,valueTwo,op]...
```

* `num`: the number of the, the maximum of num is 6。

for one arguments, `[index,value,valueTwo,op]`

* `index`: the index for syscall arguments（type uint）
* `value`: the value for syscall arguments （type uint64）
* `valueTwo`: the value for syscall arguments （type uint64）
* `op`: the operator for syscall arguments, a valid list of constants as of libseccomp v2.3.2 is
`SCMP_CMP_NE`,`SCMP_CMP_LE`,`SCMP_CMP_LE`, `SCMP_CMP_EQ`, `SCMP_CMP_GE`, `SCMP_CMP_GT`, `SCMP_CMP_MASKED_EQ`.


For example:
```
2
blacklist
reject_force_umount  # comment this to allow umount -f;  not recommended
[all]
kexec_load errno 1 3 [0,1,0,SCMP_CMP_LE][3,1,0,SCMP_CMP_GT][5,1,0,SCMP_CMP_MASKED_EQ]
open_by_handle_at errno 1
init_module errno 1
finit_module errno 1
delete_module errno 1
```

Any ideas?

**Comment by brauner** [comment]
It sounds reasonable to me but I'd like to give a little thought before "giving my blessing". :) Does that sound ok?

**Comment by 0x0916** [comment]
It's okay, looking forward to your suggestion.

**Comment by stgraber** [comment]
@hallyn you may have an opinion on this one too

**Comment by hallyn** [comment]
I'm worried about api there. Can we see a particular use case?

I suspect at this point we'll just want the ebpf explicitly listed in the configuration, but not sure.

**Comment by Blub** [comment]
EBPF makes more sense to me, needs an interface as well though (blobs, numbers (representing `struct bpf_insn`, like `tc-bpf`), numbers where syscall names get serached&replaced, ...?)
Btw. I'm not sure what the second value in the proposed interface should be? If you compare a parameter to a value, shouldn't you only need a parameter index, an operation and a value?

**Comment by 0x0916** [comment]
@Blub when the operation is `SCMP_CMP_MASKED_EQ`, we need the `valueTwo` as the mask. for other operations, we only use `value`
