### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [lxc/lxc#158]
[An extra null pointer check is not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for NULL before free(p)?") in [the function "lxc_proc_get_context_info"](https://github.com/lxc/lxc/blob/442f5c0fdfe829d6e4baac224bf8df0bb74fc6eb/src/lxc/attach.c#L101 "Improve lxc_proc_get_context_info function?").

**Comment by brauner** [comment]
I think this can be closed since the commits have been merged.
