### ISSUE TITLE
unknown key lxc.bdev.zfs.root

### ISSUE THREAD

**Issue by jelmd** [lxc/lxc#1581]
`+ lxc-create -n oe2 -B zfs -P /zones -t ubuntu-csmd -f /tmp/oe2.tmp/zone.cmd` fails with
```
lxc-create: confile.c: parse_line: 2008 unknown key lxc.bdev.zfs.root
lxc-create: parse.c: lxc_file_for_each_line: 57 Failed to parse config: lxc.bdev.zfs.root = rpool/zones/oe2
```
The config file used is:
```
lxc.network.type = macvlan
lxc.network.macvlan.mode = bridge
lxc.network.link = mb0
lxc.network.flags = up

lxc.network.hwaddr = 00:01:01:18:09:10
lxc.start.order = 16
lxc.start.auto = 1
lxc.bdev.zfs.root = rpool/zones/oe2
lxc.mount = /tmp/oe2.tmp/zone.fstab.extern
```

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.2
 * kernel: Linux foo 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by stgraber** [comment]
lxc.bdev.zfs.root isn't a container option, it's a system option so it needs to be set in /etc/lxc/lxc.conf

The lxc.system.conf and lxc.container.conf show you which go where.

**Comment by jelmd** [comment]
Uhhm, so there is no usable/convenient way to use zfs in linux containers? What a pity!!!
