### ISSUE TITLE
lxc-start-ephemeral in 2.0.8 creates configuration it can't parse

### ISSUE THREAD

**Issue by LarsFronius** [lxc/lxc#1595]
# Required information

 * Distribution: Ubuntu 14.04
 * Distribution version: Ubuntu 14.04.5 LTS
 * The output of
   * `lxc-start --version` : 2.0.8
   * `uname -a` : Linux vagrant-ubuntu-trusty-64 3.13.0-119-generic #166-Ubuntu SMP Wed May 3 12:18:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

# Issue description

Given I have a container and I want to create a new ephemeral container from it, a configuration is being created, that leads to lxc erroring out on parsing it and thus lxc tooling not being able to interact with the new container. This wasn't the case in 2.0.7 but is now the case in 2.0.8.

# Steps to reproduce

`lxc-create -n foobar -t ubuntu`
`lxc-start-ephemeral -n foobar-ephemeral -o foobar -d`
`lxc-ls -f` leads to:
`lxc-ls: parse.c: lxc_file_for_each_line: 57 Failed to parse config: lxc.ephemeral =`

# Information to attach

- the configuration file looks as follows
```
cat /var/lib/lxc/foobar-ephemeral/config
# Template used to create this container: /usr/share/lxc/templates/lxc-ubuntu
# Parameters passed to the template:
# Template script checksum (SHA-1): 4d7c613c3c0a0efef4b23917f44888df507e662b
# For additional config options, please look at lxc.container.conf(5)
# Uncomment the following line to support nesting containers:
#lxc.include = /usr/share/lxc/config/nesting.conf
# (Be aware this has security implications)
# Common configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
# Container specific configuration
lxc.rootfs.backend = dir
lxc.arch = amd64
# Network configuration
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:9b:4e:ab
lxc.utsname =
lxc.utsname = foobar-ephemeral
lxc.rootfs =
lxc.rootfs = /var/lib/lxc/foobar-ephemeral/rootfs
lxc.network.0.hwaddr = 00:16:3e:6f:fd:69
lxc.hook.pre-mount =
lxc.hook.pre-mount = /var/lib/lxc/foobar-ephemeral/pre-mount
lxc.ephemeral =
lxc.ephemeral = 1
```

I believe the line `lxc.ephemeral =` is the one triggering the configuration parse issue.

**Comment by brauner** [comment]
Yeah, I see the problem thanks!
