### ISSUE TITLE
Should lxc-user-nic accept mtu from arguments?

### ISSUE THREAD

**Issue by ss1h2a3tw** [lxc/lxc#1602]
In current mainline version of lxc,
When using unprivileged lxc with configuration of lxc.network.mtu = xxx
will not work because of mtu is assigned by the lxc-user-nic
which assigns mtu according to the bridge the lxc connecting to
I think that it will be better if we can pass mtu to lxc-user-nic , and user can assign custom mtu more easily.

**Comment by stgraber** [comment]
This is done on purpose. If we were to allow a user to set the MTU on their device, it would lower the bridge MTU to match, making it trivial for an unprivileged user to break host networking.

**Comment by ss1h2a3tw** [comment]
But if user using a lower mtu than bridge, it will not break host networking, I think

**Comment by stgraber** [comment]
The bridge always picks whichever is the lowest MTU of all its member interfaces. If the bridge you're using is bridging your physical ethernet device, as many people do, then yes, bridging a container with a low MTU will break host networking for any packet that's larger than the new MTU.

**Comment by ss1h2a3tw** [comment]
OK, I get it.
Or maybe adding a warning when setting mtu in the config? To prevent confusing.

**Comment by brauner** [comment]
Yeah, we can indeed add a comment about that. Will send a patch later.

**Comment by brauner** [comment]
Ah, sorry, didn't see that you already sent a patch. Perfect, thanks!
