### ISSUE TITLE
cannnot create network interface and therefore breaks containers

### ISSUE THREAD

**Issue by fabianfrz** [lxc/lxc#1604]
# Required information

 * Distribution:
   Arch linux
 * Distribution version:
   Current
 * The output of
   * `lxc-start --version`
     2.0.8
   * `lxc-checkconfig`

```
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: missing
Network namespace: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: enabled
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```
   * `uname -a`
     Linux hostname 4.11.2-1-ARCH #1 SMP PREEMPT Mon May 22 06:53:49 CEST 2017 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`

```
10:devices:/user.slice/user-0.slice/session-c3.scope
9:net_cls:/
8:memory:/user.slice/user-0.slice/session-c3.scope
7:pids:/user.slice/user-0.slice/session-c3.scope
6:freezer:/
5:blkio:/user.slice/user-0.slice/session-c3.scope
4:cpuset:/
3:cpu,cpuacct:/user.slice/user-0.slice/session-c3.scope
2:perf_event:/
1:name=systemd:/user.slice/user-0.slice/session-c3.scope
```

# Issue description

Container fails to create the veth device and therefore does not start

# Steps to reproduce

 1. Step one
start the container

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
       does not print anything related
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)

```
      lxc-start 20170531054351.529 ERROR    lxc_conf - conf.c:instantiate_veth:2677 - failed to create veth pair (vethXYHGJD and vethKUBMFC): Operation not supported
      lxc-start 20170531054351.532 ERROR    lxc_conf - conf.c:lxc_create_network:3021 - failed to create netdev
      lxc-start 20170531054351.532 ERROR    lxc_start - start.c:lxc_spawn:1103 - Failed to create the network.
      lxc-start 20170531054351.532 ERROR    lxc_start - start.c:__lxc_start:1358 - Failed to spawn container "nextcloud".
      lxc-start 20170531054356.538 ERROR    lxc_start_ui - tools/lxc_start.c:main:366 - The container failed to start.
      lxc-start 20170531054356.538 ERROR    lxc_start_ui - tools/lxc_start.c:main:368 - To get more details, run the container in foreground mode.
      lxc-start 20170531054356.538 ERROR    lxc_start_ui - tools/lxc_start.c:main:370 - Additional information can be obtained by setting the --logfile and --logpriority options.
```
 - [ ] the containers configuration file

```
lxc.network.type = veth
lxc.network.link = xxx
lxc.network.flags = up
lxc.network.ipv4 = xxx
lxc.network.ipv4.gateway = xxx
lxc.network.name = eth0
lxc.rootfs = /path/to/rootfs
lxc.rootfs.backend = dir
lxc.utsname = nextcloud
lxc.arch = x86_64
lxc.include = /usr/share/lxc/config/archlinux.common.conf
```

**Comment by brauner** [comment]
Can you please show the output of

     ls -al /usr/lib/lxc/lxc-user-nic

**Comment by brauner** [comment]
And another question is `xxx` really the name of your network bridge?

**Comment by fabianfrz** [comment]
-rwsr-xr-x 1 root root 39704 15. Mai 15:04 /usr/lib/lxc/lxc-user-nic

and no (just removed the real name as well as the real ip/netmask)

**Comment by fabianfrz** [comment]
the bridge is working on the host and has an ipv4 as well as an ipv6 IP address assigned. It is created by systemd

**Comment by fabianfrz** [comment]
note: this container and lxc did already work

**Comment by ss1h2a3tw** [comment]
`sudo modprobe veth` can you try this?
Maybe veth is unload in kernel and you have done a kernel upgrade without rebooting

**Comment by fabianfrz** [comment]
```
# modprobe veth
modprobe: FATAL: Module veth not found in directory /lib/modules/4.11.2-1-ARCH
```

and 

```
lsmod | grep veth
```
has an empty output

a veth kernel module exists under `/lib/modules/4.11.3-1-ARCH/kernel/drivers/net/veth.ko.gz`

**Comment by ss1h2a3tw** [comment]
You can downgrade your kernel or reboot your system or force insmod by path
It should work after doing this.

**Comment by fabianfrz** [comment]
`insmod` does work as a temporary workaround.

**Comment by brauner** [comment]
So this is not really LXC's fault since we're not concerned with making the necessary kernel modules available. :)

**Comment by ss1h2a3tw** [comment]
@brauner Maybe lxc-checkconfig should also check whether the modules are probed into kernel?
Not just checking the compile flag.

**Comment by brauner** [comment]
Yeah, only check but not load itself. I don't want our scripts to just randomly insert modules behind users backs. :)

**Comment by fabianfrz** [comment]
and more importantly: provide a useful error message (for example: The driver for virtual ethernet (veth) is not loaded. You can load it by executing the command **insmod /path/to/veth.ko** as root (root shell or sudo)).

The easiest way to find it out is calling something like `lsmod | grep veth | wc -l`.
