### ISSUE TITLE
kill utmp

### ISSUE THREAD

**Issue by brauner** [lxc/lxc#1616]
in start.c

**Comment by 0x0916** [comment]
@brauner What is the details of this issue? We will no longer use utmp in lxc?

**Comment by stgraber** [comment]
The utmp watch was only there for backward compatibility to very old Linux kernels.
LXC 2.1 will be restricting compatibility to kernel 3.10 or higher, making this code unnecessary.

**Comment by 0x0916** [comment]
Since Linux 3.4, when reboot() is called from a PID namespace other than the initial PID namespace, the effect of the call is to send a signal to the namespace "init" process.

So,  we does not need to watch utmp file on kernel 3.10 or higher.  am I right?

**Comment by brauner** [comment]
No, sending the signal to the init namespace is what makes the utmp watch unneeded.
