### ISSUE TITLE
Not able to read and write file in USB inside LXC container

### ISSUE THREAD

**Issue by J-kumari** [lxc/lxc#1617]
I have mounted USB inside LXC container by adding below line in container's config file.
lxc.mount.entry = /mnt/usb/ mnt/ none bind, rw 0 0

I am able to see the USB inside container but not able to read and write a file in USB.
Is there any dependencies that I am missing?

**Comment by brauner** [comment]
@J-kumari, can you please provide the information we request in our issue template? Specifically, I'd like to see your container's config file.

**Comment by J-kumari** [comment]
Actually I am not able to copy any file from host to USB inside container. Is there any other way to mount USB with permission same as host.

**Comment by brauner** [comment]
@J-kumari, could please show me the container's config file?
