### ISSUE TITLE
is this a problem to send a signal when the signal is blocked in function do_lxcapi_shutdown

### ISSUE THREAD

**Issue by tanyifeng** [lxc/lxc#1625]
In function "do_lxcapi_shutdown" which is in file src/lxc/lxccontainer.c . lxc detects whether a signal is blocked:
```
 /* Detect whether we should send SIGRTMIN + 3 (e.g. systemd). */
	if (task_blocking_signal(pid, (SIGRTMIN + 3)))
		haltsignal = (SIGRTMIN + 3);
```
I wonder why still set haltsignal to SIGRTMIN + 3 when the signal is blocked ? should it be:
```
if (!task_blocking_signal(pid, (SIGRTMIN + 3)))
```

Another question is :
In function "task_blocking_signal", I think the way to detect whether the signal is blocked is wrong.
```
if (sigblk & signal)
	bret = true;
```
Cause signal is type of int, so we should detect like this:
```
if (sigblk & (1 << (signal - 1)))
	bret = true;
```

**Comment by brauner** [comment]
Hey there,
When the signal is blocked it means that there's likely a signal handler installed to be able to run e.g. cleanup code before shutting down so the current version is correct.
About testing whether the bit is set. I'm not sure how testing the way you suggested would be an improvement to what we do right now.

**Comment by tanyifeng** [comment]
Thanks for comment.
Actually, sigblk is a bit set,  assume that signal is 37, then we should detect whether the 37th bit of sigblk is 1 or 0, rather than using (sigblk & signal) which may have wrong result. And using function sigismember is a good way, thus:
```
if (sigismember((sigset_t)sigblk, signal))
        bret = true;
```

**Comment by tanyifeng** [comment]
Sorry, using sigismember is wrong, we should use bit operation due to what i comment above.
```
if (sigblk & (1 << (signal - 1)))
	bret = true;
```

**Comment by brauner** [comment]
Can you explain how `(a & b)` may have the wrong result?

**Comment by tanyifeng** [comment]
when the 7th bit of sigblk is 0, and we want to detect it, so:
```
sigblk = 0x FFFF FFFF FFFF FFBF;
signal = 0x 0000 0000 0000 0007;
```
using (sigblk & signal) will get true, and (sigblk & (signal - 1)) get false. is this right?

**Comment by tanyifeng** [comment]
reference to this :
[bitmask](https://unix.stackexchange.com/questions/85364/how-can-i-check-what-signals-a-process-is-listening-to)

**Comment by brauner** [comment]
@tanyifeng, sorry that issue got lost. Please send a PR. :)

**Comment by brauner** [comment]
For the bitmask issue. :)
