### ISSUE TITLE
lxc.pc.in: generate wrong lxc.pc

### ISSUE THREAD

**Issue by 0x0916** [lxc/lxc#1636]
# Required information

 * Distribution:
   ubuntu
 * Distribution version:
   16.04

# Issue description

build lxc from source with the following command

```bash
./autogens.h
./configure
make
sudo make install
```
and 

```
# pkg-config --libs lxc
-L/usr/local//usr/local/lib -llxc -lutil
```

`/usr/local//usr/local/lib` is the wrong path for `liblxc.so`

Does this [Add a prefix to the lxc.pc](https://github.com/lxc/lxc/commit/758243d8af0406e63cc5446c65d415298fa3cef2) correctly?

**Comment by brauner** [comment]
Could be wrong. I haven't tested this feature yet. Do you have a fix?

**Comment by 0x0916** [comment]
yes, just revert https://github.com/lxc/lxc/commit/758243d8af0406e63cc5446c65d415298fa3cef2 ?

**Comment by brauner** [comment]
@0x0916, not sure. I'll wait for some more opinions. :)
