### ISSUE TITLE
[TAKEN]: Community/Up-For-Grabs: tree-wide: wipe all references to lxc.network.{[i]}.* and replace with lxc.net.[i].*

### ISSUE THREAD

**Issue by brauner** [lxc/lxc#1641]
This relates to templates, documentation and configuration files. The code itself is already ready. :)

**Comment by 0x0916** [comment]
Assign to me.

**Comment by brauner** [comment]
### Note, that this issue has been assigned to @0x0916 . In loser terms, @0x0916 called dibs please respect that. :)
