### ISSUE TITLE
[TAKEN]: Community/Up-For-Grabs: Switch to new configuration keys

### ISSUE THREAD

**Issue by brauner** [lxc/lxc#1642]
The following keys will be renamed:
```
lxc.limit => lxc.prlimit
lxc.devttydir => lxc.tty.dir
lxc.utsname => lxc.uts.name
lxc.haltsignal => lxc.signal.halt
lxc.rebootsignal => lxc.signal.reboot
lxc.stopsignal => lxc.signal.stop
lxc.logfile => lxc.log
lxc.loglevel => lxc.log.level
lxc.syslog => lxc.log.syslog
lxc.init_cmd => lxc.init
lxc.init_uid => lxc.init.uid
lxc.init_gid => lxc.init.gid
```
The old jump table methods in `confile.c` will be moved to `confile_legacy.{c,h}` and new methods implemented in `confile.c`. The old and the new configuration keys need to be supported up until `LXC 3.0` and dropped afterwards. If someone wants to work on this, just ask for more instructions. If not I will do it.

**Comment by brauner** [comment]
- New keys need to be tested in `test/parse_config_file.c`

**Comment by 0x0916** [comment]
@brauner I would like to do this. please give me more instructions.

**Comment by brauner** [comment]
Note, that this issue has been assigned to @0x0916 . In loser terms, @0x0916 called dibs please respect that. :)

**Comment by brauner** [comment]
So this is actually straightforward. Until we release `LXC 3.0` we need to support the old and the new keys. For example, until we remove the old keys in `LXC 3.0` users can e.g. set `lxc.haltsignal` and `lxc.signal.halt`. The way I want to implement this is to move the old {set, get, clr} methods in `confile.c` to `confile_legacy.{c,h}`. The keys themselves will be marked `/* REMOVE IN LXC 3.0 */ in the configuration jump table in `confile.c`. You can see an example of this in my PR: https://github.com/lxc/lxc/pull/1639/files#diff-2f3344d3cb9700d11140decc560aaacaR423 . Then you simply add the new keys to the jump table in `confile.c` and implement the corresponding {get, set, clr} methods. That should be straightforward. Just take the existing legacy methods as a pointer. And of course, if you need more guidance don't hesitate to ask.

**Comment by brauner** [comment]
Note, the code duplication for this is intentional. This way, we can just rip-out the `confile_legacy.{c,h}` files, remove the legacy keys from the jump table in `confile.c` and then remove them from `conf.h` and delete them all over the tree without any effort when `LXC 3.0` comes out.

**Comment by 0x0916** [comment]
@brauner got it. thanks.
