### ISSUE TITLE
Two questions about the daemonize containers stdfds

### ISSUE THREAD

**Issue by lifeng68** [lxc/lxc#1646]
There are a few questions about the daemonize containers stdfds.
Q1: When we start a daemonize container, in the function `do_lxcapi_start`, redirected 0,1,2 to /dev/null
```
		/* like daemon(), chdir to / and redirect 0,1,2 to /dev/null */
		if (chdir("/")) {
			SYSERROR("Error chdir()ing to /.");
			exit(1);
		}
		lxc_check_inherited(conf, true, -1);
		if (null_stdfds() < 0) {
			ERROR("failed to close fds");
			exit(1);
		}
```
In the function `lxc_spawn` ,clone out the container process.  In the process,  `do_start` call `lxc_console_set_stdfds` with the purpose to redirect 0,1,2 to the `handler->conf->console.slave`, but the STDIN_FILENO、STDOUT_FILENO、STDERR_FILENO had been  redirected to /dev/null, they would not be a tty, so lxc_console_set_stdfds will not redirect 0,1,2 to the `handler->conf->console.slave`.
Is this a bug?
```
int lxc_console_set_stdfds(int fd)
{
	if (fd < 0)
		return 0;

	if (isatty(STDIN_FILENO))
		if (dup2(fd, STDIN_FILENO) < 0) {
			SYSERROR("failed to duplicate stdin.");
			return -1;
		}

	if (isatty(STDOUT_FILENO))
		if (dup2(fd, STDOUT_FILENO) < 0) {
			SYSERROR("failed to duplicate stdout.");
			return -1;
		}

	if (isatty(STDERR_FILENO))
		if (dup2(fd, STDERR_FILENO) < 0) {
			SYSERROR("failed to duplicate stderr.");
			return -1;
		}

	return 0;
}
```
Q2: In the function do_start, why we should redirect 0,1,2 to /dev/null when start container backgrounded? I think we should redirect 0,1,2 to the `handler->conf->console.slave` always, and when we start a daemon container,  do not read the master of the pty (`console.master`)
```
	if (devnull_fd < 0) {
		devnull_fd = open_devnull();

		if (devnull_fd < 0)
			goto out_warn_father;
	}

	if (handler->backgrounded && set_stdfds(devnull_fd))
		goto out_warn_father;
```

**Comment by brauner** [comment]
Q1:
You're misreading the `dup2()` syscall I think. `dup2(OLDFD, NEWFD)` so `dup2()` makes `std{in,out,err}` refer to the `tty` file descriptor. And that's exactly what you want. You can try to start a daemonized container via `lxc-start -n <container-name>` and set `lxc.console.logfile=/home/<your-username>/bla.log` and you will see the output of the console logged right there.

**Comment by brauner** [comment]
Q2:
That will only work if the container does have a console. We explicitly support not allocating a console for the container via `lxc.console=none`.

**Comment by lifeng68** [comment]
@brauner ， Q1: thanks for your response, but I think you did not understand my thoughts. 
In the parent process (`do_lxcapi_start`), we dup the std{in,out,err} refer to the "/dev/null" by function `null_stdfds `. So. while we call `handler->pid = lxc_clone(do_start, handler, flags);` to clone child process, the STDIN_FILENO、STDOUT_FILENO、STDERR_FILENO  of child process were still  redirected to /dev/null by inheritance. Then in the function `lxc_console_set_stdfds`  ` if (isatty(STDIN_FILENO))` will return 0,we will not can call ` if (dup2(fd, STDIN_FILENO) < 0) `

I tested a  daemonized container,  my config as follow, and` lxc.init_cmd = /home/ubuntu/a.out` is a test program to print 'hello' in a while(1)

```
lxc.arch = x86_64
lxc.utsname = ubuntu
lxc.init_cmd = /home/ubuntu/a.out
lxc.environment = PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
lxc.environment = TERM=xterm
lxc.rootfs = rootfs
lxc.rootfs.options = ro
lxc.rootfs.backend = dir
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none bind,optional 0 0
lxc.mount.entry = /sys/kernel/security sys/kernel/security none bind,optional 0 0
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none bind,optional 0 0
lxc.mount.entry = mqueue dev/mqueue mqueue rw,realtime,create=dir,optional 0 0
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections non bind,optional 0 0
lxc.cgroup.devices.allow = c 254:* rm
lxc.cgroup.devices.allow = c 10:200 rwm
lxc.cgroup.devices.allow = c 10:228 rwm
lxc.cgroup.devices.allow = c 10:232 rwm
lxc.cgroup.devices.deny = a *:* (null)
lxc.cgroup.devices.allow = c *:* m
lxc.cgroup.devices.allow = b *:* m
lxc.cgroup.devices.allow = c 1:3 rwm
lxc.cgroup.devices.allow = c 1:5 rwm
lxc.cgroup.devices.allow = c 1:7 rwm
lxc.cgroup.devices.allow = c 5:* rwm
lxc.cgroup.devices.allow = c 5:1 rwm
lxc.cgroup.devices.allow = c 5:2 rwm
lxc.cgroup.devices.allow = c 1:8 rwm
lxc.cgroup.devices.allow = c 1:9 rwm
lxc.cgroup.devices.allow = c 136:* rwm
lxc.cgroup.devices.allow = c 10:229 rwm
lxc.tty = 4
lxc.pts = 1024
lxc.devttydir = lxc
lxc.rootfs = /var/lib/lcrd/lcr/test_666/rootfs
lxc.utsname = test_666
lxc.console.logfile=/home/lifeng/test_66i6.log
```
The pid of the conainer is 32410,  I printed the fds as fellow, and `/home/lifeng/test_66i6.log` has nothing .
20:08_[/home/lifeng/lcr_lxc/lxc]_huawei*# ls -al  /proc/32410/fd
total 0
lrwx------ 1 root root 64 6月  26 20:08 0 -> /dev/null
lrwx------ 1 root root 64 6月  26 20:08 1 -> /dev/null
lr-x------ 1 root root 64 6月  26 20:08 10 -> /dev/ptmx
lrwx------ 1 root root 64 6月  26 20:08 2 -> /dev/null

**Comment by lifeng68** [comment]
Q2:
If we call`  if (handler->backgrounded && set_stdfds(devnull_fd))`   to redirecte STDIN_FILENO、STDOUT_FILENO、STDERR_FILENO  to "/dev/null", the console outputs of container will not print to the slave of the allocated PTY, we can not get the console output from the master of the PTY?

**Comment by brauner** [comment]
I haven't forgotten this issue. I need to prioritize something else right now but will be back shortly. :)

**Comment by lifeng68** [comment]
Replication step
1.create a container by lxc-create
2.modify the config of the container
```
# Template used to create this container: /usr/local/share/lxc/templates/lxc-ubuntu
# Parameters passed to the template:
# For additional config options, please look at lxc.container.conf(5)

# Uncomment the following line to support nesting containers:
#lxc.include = /usr/local/share/lxc/config/nesting.conf
# (Be aware this has security implications)


# Common configuration
lxc.include = /usr/local/share/lxc/config/ubuntu.common.conf

# Container specific configuration
lxc.rootfs = /usr/local/var/lib/lxc/ubuntu/rootfs
lxc.rootfs.backend = dir
lxc.utsname = ubuntu
lxc.arch = amd64
**lxc.init_cmd = echo hello
lxc.console.logfile=/home/lifeng/lxc.log**

# Network configuration
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:6a:af:88
```
3.  I want to get the word 'hello' in the logfile `/home/lifeng/lxc.log`, but after i started the container by lxc-start, the /home/lifeng/lxc.log  has nothing in it

**Comment by brauner** [comment]
@lifeng68, so do you want to send a patch for this that we can discuss? (Sorry for the lat reply!)

**Comment by lifeng68** [comment]
OK，I have other things to do today,  I will submit a patch next week.

**Comment by brauner** [comment]
@lifeng68, np. :) I was the one taking a long time here. :)
