### ISSUE TITLE
Upgrading to new configuration files

### ISSUE THREAD

**Issue by brauner** [lxc/lxc#1654]
`liblxc 2.1` will introduce quite some changes. One of the bigger ones being the changed configuration file. For example, `lxc.network.{[i]}.*` keys will be deprecated in favor of `lxc.net.[i].*` style keys, `lxc.aa_profile` will be replaced by `lxc.apparmor.profile` and `lxc.aa_allow_incomplete` by `lxc.apparmor.allow_incomplete`. There are a bunch of other keys that will be deprecated as well. In addition to warning users about these deprecated keys @hallyn pointed out that it might be a good idea to provide an upgrade story. We should discuss what this upgrade story looks like.

@hallyn suggested to introduce a `lxc.version` config tag and shipping `sed` scripts that upgrade based on the tag. This is still a little vague. @hallyn, would `lxc.version` simply be another configuration key like `lxc.tty` or would this only be an internal thing in the lxc config struct?

**Comment by hallyn** [comment]
It has to be in the config file.  We should make it look different
from other config items (so not just lxc.version) to stress that users
shouldn't really mess with it

leavethisalone.version? :)

**Comment by brauner** [comment]
We now have an update script in our tree. So closing this.
