### ISSUE TITLE
Start an unprivileged container as different user

### ISSUE THREAD

**Issue by aubreybox** [lxc/lxc#1655]
What do I have to do in order to lxc-attach to another users container?

Imagine user  A with group A
I just created a user B with group A and created an lxc.conf with user A's lxc.lxcpath

lxc-attach -n Acontainer returns:
Insufficent privileges to control Acontainer

Any idea? Is this even possible?

**Comment by brauner** [comment]
`lxc-attach -n <container-name> --rcfile </path/to/other/users/container's/config`

and you can also do:

`sudo `lxc-attach -n <container-name> --rcfile </path/to/other/users/container's/config` -P </path/to/other/user/container`
