### ISSUE TITLE
snapshot of unprivileged container as template for different  user

### ISSUE THREAD

**Issue by aubreybox** [lxc/lxc#1656]
https://help.ubuntu.com/lts/serverguide/lxc.html
> It is advised instead to consider C1 a canonical base container, and to only use its snapshots. 

Is this possible in combination with unprivileged containers? I.e. can bob make use of a template-container of alice? If so, how?

**Comment by hallyn** [comment]
> Is this possible in combination with unprivileged containers? I.e. can bob make use of a template-container of alice? If so, how?

...  They would have to share delegated subuids, and alice would have to set
up permissions so that a group shared by both bob and alice owned and could
traverse /home/alice/.local/share/lxc/$container/ .  There may be other
gotchas, but those are starters.
