### ISSUE TITLE
Feature Request : Adding official support for CentOs 7

### ISSUE THREAD

**Issue by ApertureSecurity** [lxc/lxc#1671]
There is a bunch of information that is wanted for me to receive support on an issue . I am really liking LXD. I think that is is a lot more stable than  Docker . However, I cannot seem to get LXD to install and run properly in a CentOs environment. I think this is important , because CentOs, RHEL , is usually the defacto enterprise environment for Linux.

Is there a chance that we will get official support for CentOs ? I have seen a few install methods on various sites but it looks like they are for LXC and appears that it will be EOL soon. Not to mention, none of the installation methods appear to work for me.

**Comment by brauner** [comment]
Wait, I'm confused what exactly is EOL?

**Comment by ApertureSecurity** [comment]
End of Life..

Reading a bit further, it s going to be carried on ... However, I still would like to be able to use this product in a CentOs Environment.

**Comment by brauner** [comment]
No no, I know what "EOL" means. :) Sorry, that was confusing I mean what exactly you think is EOL? LXC? LXC is the runtime used by LXD and it is definitely not EOL. We are preparing LXC 2.1 which again, will be used by LXD.

**Comment by ApertureSecurity** [comment]
I understand. 

Are there instructiona for inatalling LXD in centos7?

**Comment by brauner** [comment]
Well, this is not the right place and I saw that you commented on an issue in LXD that is concerned with installing LXD on CentOS. I tell you what: I'm opening a new issue on LXD to come up with instructions to use LXD on CentOS and make it a community thing. Let's see where this goes and what the other maintainers think of this. Closing this for now here.
