### ISSUE TITLE
general question - reading lxc's tmpfs from the host

### ISSUE THREAD

**Issue by graysky2** [lxc/lxc#1679]
This isn't a problem but a question: is it possible to access a file in a container's /run space (systemd so it's tmpfs) from the host running it?

**Comment by stgraber** [comment]
You could access it through "/proc/\<PID of a pid1 in container\>/root/run/...".
You can get the PID of PID1 from lxc-info.

**Comment by graysky2** [comment]
Very cool, thank you!  I didn't see in the manpage if it's possible to just get the pid... the closest I found would be:
```
lxc-info -p -n rs-pihole|awk '{print $2}'
```
