### ISSUE TITLE
Run specific command on autostarted container

### ISSUE THREAD

**Issue by devi** [lxc/lxc#168]
Hi,

For example, I'm using this command to run a container:
```lxc-start -n container -d -- /some/script```

Is there anyway to run ```/some/script``` on autostarted container ?

I could only find ```container name``` on lxc upstart script:
```
lxc-autostart -L | while read line; do
	set -- $line
	(start lxc-instance NAME=$1 && sleep $2) || true
done
```

TIA

**Comment by brauner** [comment]
Since we have `lxc.init_cmd` we can close this.
