### ISSUE TITLE
Is there any additional optimizations LXC has done for the system container?

### ISSUE THREAD

**Issue by lifeng68** [lxc/lxc#1691]
This issue is not a bug, but a consultation:
I learned  that LXC's main focus is system containers from the introductions of LXC.  I wonder is there any additional optimizations LXC has done for the system container?  If there were，can you give me some guidance on architecture or code?

**Comment by brauner** [comment]
Cheers, not that I'm currently in the middle of a big chunk of work in LXD so this will have to sit for a bit. Sorry about that. I'll definitely come back to this!

**Comment by brauner** [comment]
The best place is to probably look at the code itself and given that you sent quite a few patches over the year it seems that's what you've done. :)
