### ISSUE TITLE
regression in lxc-copy -B btrfs

### ISSUE THREAD

**Issue by overlayfs** [lxc/lxc#1698]
**Issue**
`lxc-copy -B btrfs -n trusty -N debug`

fails with error message,
> lxc-copy: trusty: bdev/lxcbtrfs.c: btrfs_clonepaths: 387 btrfs snapshot from dir backing store is not supported
> lxc-copy: trusty: bdev/bdev.c: bdev_copy: 402 failed getting pathnames for cloned storage: /home/ubuntu/.local/share/lxc/trusty/rootfs
> lxc-copy: trusty: lxccontainer.c: copy_storage: 3070 Error copying storage.
> clone failed

**Distribution Information**
- **host**: ubuntu-14.04 with the lxc-daily ppa, linux-generic-lts-xenial kernel and btrfs filesystem.
- **container**: ubuntu-14.04
      `btrfs subvol list -o /`
>     ID 260 gen 1658 top level 5 path home/ubuntu/.local/share/lxc/trusty/rootfs
- version 2.0.8+master\~20170705-1708-0ubuntu1~trusty of lxc-copy works
- version 2.0.8+master\~20170712-0906-0ubuntu1~trusty of lxc-copy fails

**Comment by overlayfs** [comment]
**Output of lxc-copy -B btrfs -n trusty -N debug -l TRACE:**

[lxc-copy.log.txt](https://github.com/lxc/lxc/files/1144425/lxc-copy.log.txt)

**Comment by brauner** [comment]
I'd need the container's config as well, please.

**Comment by brauner** [comment]
I suspect that the original container was created before we deprecated `lxc.rootfs.backend` and the fallback logic to handle this is somehow incorrect.

**Comment by overlayfs** [comment]
**trusty/config**
> lxc.include = /usr/share/lxc/config/ubuntu.common.conf
> lxc.include = /usr/share/lxc/config/ubuntu.userns.conf
> lxc.arch = x86_64
> lxc.include = /etc/lxc/default.conf
> lxc.id_map = u 0 100000 65536
> lxc.id_map = g 0 100000 65536
> lxc.rootfs = /home/ubuntu/.local/share/lxc/trusty/rootfs
> lxc.utsname = trusty

**/etc/lxc/default.conf**

> lxc.net.0.type = veth
> lxc.net.0.link = lxcbr0
> lxc.net.0.flags = up
> lxc.net.0.hwaddr = 00:16:3e:xx:xx:xx

**Comment by brauner** [comment]
To fix the problem right now simply do:

    lxc.rootf.path = btrfs:/home/ubuntu/.local/share/lxc/trusty/rootfs

**Comment by brauner** [comment]
Fwiw, if you want to use it with older liblxcs you should use the legacy `lxc.rootfs` instead of the new `lxc.rootfs.path` key.

**Comment by overlayfs** [comment]
> lxc.rootfs.path = btrfs:/home/ubuntu/.local/share/lxc/trusty/rootfs

Thank you Christian!  This resolves the issue.
