### ISSUE TITLE
How to mount a readonly rootfs?

### ISSUE THREAD

**Issue by lifeng68** [lxc/lxc#1702]
The following config leads to a container with a r/w rootfs while it should be r/o instead, assuming  /home/lifeng/myrootfs is a directory containing a container rootfs:

[ lxc.conf ]
```
lxc.rootfs = /home/lifeng/myrootfs
lxc.rootfs.options = ro
lxc.rootfs.backend = dir
```

```
1:25_[/home/lifeng/test]# lxc-execute -n lifeng -f /var/lib/lcrd/lcr/test_run1/config /bin/bash
root@mrsdalloway:/# touch /foo 
root@mrsdalloway:/# ls foo
foo
root@mrsdalloway:/# 
```
The `touch /foo` should be failed, but it successed.

The mount info as follow
```
root@mrsdalloway:/# mount
/dev/sda1 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
none on /dev type tmpfs (rw,relatime,size=492k,mode=755)
udev on /dev/sdb type devtmpfs (rw,nosuid,relatime,size=32768948k,nr_inodes=8192237,mode=755)
udev on /dev/sda type devtmpfs (rw,nosuid,relatime,size=32768948k,nr_inodes=8192237,mode=755)
/dev/sda1 on /init.lxc.static type ext4 (rw,relatime,errors=remount-ro,data=ordered)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=666)
devpts on /dev/ptmx type devpts (rw,relatime,gid=5,mode=620,ptmxmode=666)
proc on /proc type proc (rw,relatime)
shmfs on /dev/shm type tmpfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
```
What actions do I need to do to mount a readonly rootfs?

**Comment by lifeng68** [comment]
I think we should do re-mount with MS_REMOUNT | MS_BIND | MS_RDONLY in the function 
`int dir_mount(struct bdev *bdev)` if mntflags has option` ro`, reference to #570

**Comment by brauner** [comment]
@lifeng68, sure send a patch we can argue over. :)

**Comment by brauner** [comment]
I assigned you but that of course doesn't mean you have to do it. :)

**Comment by lifeng68** [comment]
OK, I will do it , I will submit a patch next week.

**Comment by brauner** [comment]
Cool, thanks @lifeng68.
