### ISSUE TITLE
How to match processes to containers

### ISSUE THREAD

**Issue by dignifiedquire** [lxc/lxc#171]
In earlier versions there was `lxc-ps` which allowed to match processes to containers. The commit that removes that 7f12cae956c003445e6ee182b414617b52532af6 says something about using `lxc-attach` instead for most use cases, but I'm not sure how that should work. 

My use case is that I have a number of containers running and I want to look at all processes of the host and see which of those processes belong to which container.

**Comment by 2ion** [comment]
Just wanting to document it here, I've implemented the lxc-ps command line interface using Python + liblxc Python bindings: https://github.com/2ion/lxc-ps.

This is not meant to displace more modern options; this tool was written due to an internal request and I was allowed to publish it.
