### ISSUE TITLE
lxc-checkpoint fails to dump/handle tty

### ISSUE THREAD

**Issue by lmouelle** [lxc/lxc#1730]
Distros: Fedora Workstation 25 (within and outside a VM) and Ubuntu Server 16.04.

lxc version: 2.0.8.
`lxc-checkconfig` output attached as file. 
`cat /proc/1/mounts` attached as a file.
Container config attached as a file (I've made many fresh ones, same result every time).
CRIU dump.log attached as a file.
CRIU version is 3.3, built from master branch.

`uname -a output` is `Linux 4.11.12-200.fc25.x86_64 #1 SMP Fri Jul 21 16:41:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Exact command issued is `lxc-checkpoint -v -l TRACE -s -o lxc_checkpoint.log -D /tmp/c8`

If I run that, or attempt to checkpoint a freshly made container in any way, it fails with the attached error logs. Workaround is to set `lxc.tty = 0` in the `/var/lib/lxc/$CONTAINER/config` file, though of course that will disable tty.

Containers in my environment occasionally yelp about trouble with dumping namespaces, don't think it's the same issue but worth mentioning anyway.

Seems related to https://github.com/lxc/lxd/issues/3086, though I am not using LXD.

[cat_proc_1_mounts.txt](https://github.com/lxc/lxc/files/1198828/cat_proc_1_mounts.txt)
[cat_proc_self_cgroup.txt](https://github.com/lxc/lxc/files/1198833/cat_proc_self_cgroup.txt)
[container_config.txt](https://github.com/lxc/lxc/files/1198830/container_config.txt)
[criu_dump.txt](https://github.com/lxc/lxc/files/1198832/criu_dump.txt)
[lxc_checkconfig.txt](https://github.com/lxc/lxc/files/1198829/lxc_checkconfig.txt)
[lxc_checkpoint.txt](https://github.com/lxc/lxc/files/1198831/lxc_checkpoint.txt)

**Comment by rst0git** [comment]
This error still exists with LXC v2.21 CRIU v3.8 and Fedora 27
```
tty: Unable to find a master for /3
```
Thanks for the workaround: setting `lxc.tty.max = 0` in `/var/lib/lxc/$CONTAINER/config`

**Comment by stgraber** [comment]
Yes, that's to be expected with CRIU. CRIU cannot dump things that didn't originate in the container, which is the case with TTY devices.

Some work was done to improve that in more recent LXC releases though, combined with work on the CRIU side too.
