### ISSUE TITLE
inittab running getty on non-existing terminals

### ISSUE THREAD

**Issue by hadmut** [lxc/lxc#1751]
Hi, 

running LXD under Ubuntu 17.04 and had trouble with Alpine images:

just starting

lxc launch alpine/3.6 -e

without doing anything else causes the init process in this alpine machine to go into an endless loop and blasting error messages like

Aug 17 08:23:03 civil-seagull daemon.info init: process '/sbin/getty 38400 tty1' (pid 374) exited. Scheduling for restart.
Aug 17 08:23:03 civil-seagull daemon.info init: process '/sbin/getty 38400 tty2' (pid 375) exited. Scheduling for restart.
Aug 17 08:23:03 civil-seagull daemon.info init: process '/sbin/getty 38400 tty3' (pid 376) exited. Scheduling for restart.
Aug 17 08:23:03 civil-seagull daemon.info init: process '/sbin/getty 38400 tty4' (pid 377) exited. Scheduling for restart.
Aug 17 08:23:03 civil-seagull daemon.info init: can't open /dev/tty1: No such file or directory
Aug 17 08:23:03 civil-seagull daemon.info init: can't open /dev/tty2: No such file or directory
Aug 17 08:23:03 civil-seagull daemon.info init: can't open /dev/tty3: No such file or directory
Aug 17 08:23:03 civil-seagull daemon.info init: can't open /dev/tty4: No such file or directory

into /var/log/messages. 

Reason: /etc/inittab contains 
_ # Set up a couple of getty's
tty1::respawn:/sbin/getty 38400 tty1
tty2::respawn:/sbin/getty 38400 tty2
tty3::respawn:/sbin/getty 38400 tty3
tty4::respawn:/sbin/getty 38400 tty4

but /dev/tty[1234] do not exist if run in LXD. 

Interestingly the LXC setup script for Alpine contains

setup_inittab() {
        # Remove unwanted ttys.
        sed -i '/^tty[5-9]\:\:.*$/d' etc/inittab

        cat <<-EOF >> etc/inittab
                # Main LXC console console
                ::respawn:/sbin/getty 38400 console
        EOF
}

so it removes these lines for tty[5..9] but not 1..4 

(an ubuntu 17.04 image running under LXD doesn't have /dev/tty[1..9] either)

**Comment by stgraber** [comment]
So I guess the best thing we can do here is ship an override for that file in the LXD image.

systemd based distros don't run into such problems as systemd uses an environment variable to know what console to spawn a getty on and lxc sets that environment variable based on lxc.tty.
