### ISSUE TITLE
lxc-attach command give error in cron script

### ISSUE THREAD

**Issue by MetaAbstract** [lxc/lxc#1754]
I have such command in bash backup script:
`lxc-attach -n sde4 -- service apache2 stop`
when i run it's from console all is ok, but when it's run from cron of root  i have:
`lxc_container: No such file or directory - failed to exec 'service'`
but command
`lxc-attach -n sde4 -- tar -cvf /home/melchukaa/${filename_sde4} /var/www/html`
go fine.
what it's can be?

 * Debian Jessie
  * The output of
   * `lxc-start --version` 1.0.6
   * `lxc-checkconfig` all options enabled
   * `uname -a`3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
8:perf_event:/
7:blkio:/
6:net_cls,net_prio:/
5:freezer:/
4:devices:/
3:cpu,cpuacct:/
2:cpuset:/
1:name=systemd:/user.slice/user-1000.slice/session-14837.scope

   * `cat /proc/1/mounts`
rootfs / rootfs rw 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,relatime,size=10240k,nr_inodes=484354,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,relatime,size=778532k,mode=755 0 0
/dev/sda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
tmpfs /etc/machine-id tmpfs ro,relatime,size=778532k,mode=755 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=23,pgrp=1,timeout=300,minproto=5,maxproto=5,direct 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=389268k,mode=700,uid=1000,gid=1000 0 0

**Comment by stgraber** [comment]
My guess is that the PATH environment variable when run by cron is much more restrictive than what you normally get.

lxc-attach passes the environment to the container, so if cron restricts the value of PATH, the container will then fail to find the command you're trying to run.

**Comment by MetaAbstract** [comment]
Thx,  a lot! You i right!
root@sdeserver:~/scripts# printenv PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

sh backup.sh 
sde4 dokuwiki backup=============
PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

cron backup.sh
PATH
/usr/bin:/bin

root@sde4:/home/melchukaa# which service
/usr/sbin/service
what is the best solution? i can write in script  
lxc-attach -n sde4 -- /usr/sbin/service apache2 stop

**Comment by MetaAbstract** [comment]
.../usr/sbin/service  work fine

**Comment by stgraber** [comment]
you can do something like:

    env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin lxc-attach -n sde4 -- service apache2 stop

Or use the full path, or set a global env variable in your crontab.

**Comment by MetaAbstract** [comment]
Thx, a lot again!!! I will think about best way.
