### ISSUE TITLE
Gentoo hardened template

### ISSUE THREAD

**Issue by asarubbo** [lxc/lxc#1759]
Hello,

actually there is just a gentoo container which pulls the default stage.

The gentoo hardened variant (https://wiki.gentoo.org/wiki/Hardened_Gentoo) is widely used, so would be great to have such container.

To make the gentoo hardened container you just need to pull a different stage tarball which is located here:
http://distfiles.gentoo.org/releases/amd64/autobuilds/current-stage3-amd64-hardened/stage3-amd64-hardened-20170817.tar.bz2

**Comment by stgraber** [comment]
The lxc-gentoo template takes a variant argument which can be amd64-hardened, it's even listed in its help message.

**Comment by stgraber** [comment]
```
variant: gentoo's Architecture variant as of dec 2013 : (currently: '${variant}')
    for amd64 arch: amd64 (default), amd64-hardened+nomultilib, amd64-hardened, amd64-nomultilib, x32
    for x86 arch: i686 (default), i486, i686-hardened
    for arm arch: armv7a (default), armv7a_hardfp, armv6j, armv6j_hardfp, armv5tel, armv4tl
```

**Comment by asarubbo** [comment]
ok...but I was talk about the ready images...I saw the support for hardened in the template.
