### ISSUE TITLE
Kernel complains about mounting ext4 LVM device

### ISSUE THREAD

**Issue by Roosterfish** [lxc/lxc#1762]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04
 * The output of
   * `lxc-start --version`: 2.0.7
   * `uname -a`: 4.4.0-92-generic x86_64

# Issue description

Every time I try to create/start a container with `--fstype ext4` and LVM as backingstore, the kernel first
tries to mount the device as ext3, then ext2. The machines root file system is ext4 too.

# Steps to reproduce

1. `lxc-create -t download -n container -B lvm --vgname [VG] --fssize 1000M --fstype ext4 -- -d ubuntu -r trusty -a amd64`
2. `lxc-start -n container -d`

# Information to attach

The dmesg output looks like the following:
```
[ 4978.481424] EXT4-fs (dm-0): couldn't mount as ext3 due to feature incompatibilities
[ 4978.481780] EXT4-fs (dm-0): couldn't mount as ext2 due to feature incompatibilities
[ 4978.502470] EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: (null)
```

**Comment by brauner** [comment]
In the next LXC release (2.1) we will have ext4 as default filesystem and the code will hopefully be smarter in a bunch of ways.

However, does the mount succeed and the container start?

**Comment by Roosterfish** [comment]
Yes, at the end both commands succeed. But if there is nothing I can do to prevent this behaviour, I'm looking forward for the next release. 
Is there any release date planned yet?

**Comment by brauner** [comment]
@Roosterfish, pretty soon. I'm mostly done. I'm just working on an update script from old to new configuration files. This should be done today. Then I'll have to get a review for one larger branch from one of the other maintainers and we should be good to go.

**Comment by Roosterfish** [comment]
Awesome! Keep up the great work.
