### ISSUE TITLE
lxc listings are always dashed - problem : scripts need to clean output before actions

### ISSUE THREAD

**Issue by jadjay** [lxc/lxc#1764]
# Required information

 * Distribution: all
 * Distribution version: all

# Issue description

lxc listing is always dashed, this is very time consuming for scripts

Hence it is fastidious for simple commands : 
`
$ LOCAL=C lxc list $filter -c n | grep -v "NAME" | awk '{print $2}' | grep -v "^$" | xargs lxc stop
`

# Modification needed

- Add a tiny option '-s --simple' which permit to have only tabulated output
- Or add a format csv or tabulated

Both options have to be compatible with -c option

# more

Could be interesting to have a ~/.lxcrc configuration file, where you could put default line option per tool, like mysql and ~/.my.cnf.

**Comment by brauner** [comment]
That's LXD issue: https://github.com/lxc/lxd

**Comment by stgraber** [comment]
And LXD has the "--format=csv" option for that (also supports yaml and json)
