### ISSUE TITLE
Being able to see container's mounts on the host

### ISSUE THREAD

**Issue by Kentzo** [lxc/lxc#1765]
As far as I understand the only way to see successful LXC mounts is to use `lxc-attach` or by connecting a tty. It would be convenient if LXC mounts would be exposed to the host directly and available, e.g. in the `mount` output.

**Comment by brauner** [comment]
Linux mount semantics do not easily allow for this change without a substantial rework of our internal mount handling. This is also potentially security sensitive given how mount namespaces work. So this will unfortunately not be something we would want to support.

**Comment by Kentzo** [comment]
@brauner Perhaps they could be exposed through some other interface than `mount`?

**Comment by stgraber** [comment]
You can always read /proc/\<PID1 of container\>/mounts and access the mounted filesystem at /proc/\<PID1 of container\>/root/.

That PID is provided to you by lxc-info
