### ISSUE TITLE
How to compute/retrieve the fingerprint of an exported image

### ISSUE THREAD

**Issue by olivier-etienne** [lxc/lxc#1774]
I have generated an image using lxc image export image_name image_archive_name
I can get the fingerprint of an existing image with : lxc image info 

But I would like to retriev the fingerprint of the image_archive before to import it again.

How can I do that ? 

Olivier

**Comment by brauner** [comment]
Hi, this the wrong repo to report this issue. You're looking for our LXD project: https://github.com/lxc/lxd . Please open an issue there. Closing this one.

**Comment by olivier-etienne** [comment]
Nope, the question is pure lxc :)
I would like to get the finger print from lxc  command line or bash commands.

**Comment by brauner** [comment]
`lxc <subcommand>` is the command line tool for `LXD` :)

**Comment by olivier-etienne** [comment]
Oups... sorry.
