### ISSUE TITLE
lxc delete aborts if btrfs subvolume is already absent

### ISSUE THREAD

**Issue by treba123** [lxc/lxc#1795]
Ubuntu 16.04, lxc version 2.17

###

When using `lxc delete` on a container residing in a btrfs storage and the corresponding subvolume does not exist anymore, it failes with the message:

`error: Failed to run: btrfs subvolume delete [...]: ERROR: cannot access subvolume: [...]: No such file or directory `

IMO, lxc should check if the subvolume is already absent and remove the container from it's database, atleast with the `--force` option set. Otherwise it could promt the user to decide.

# Steps to reproduce

1. create a lxc storage with btrfs source: `lxc storage create test-storage btrfs source=/mnt/btrfs`
2. create a container in it: `lxc launch ubuntu:16.04 test-container -s test-storage`
3. stop the container: `lxc stop test-container`
4. manually remove the subvolume: `btrfs subvolume delete /mnt/btrfs/containers/test-container`
5. try to remove it from lxc: `lxc delete test-container --force`

Expected behaviour:
lxc deletes the container from it's db

Actual behavior:
lxc aborts with the error
`error: Failed to run: btrfs subvolume delete [...]: ERROR: cannot access subvolume: [...]: No such file or directory `

**Comment by brauner** [comment]
@treba123, this is the wrong repository. You should open this issue against https://github.com/lxc/lxd . This is unrelated to liblxc's storage backend.

**Comment by treba123** [comment]
Ah alright, sorry :)
