### ISSUE TITLE
Provide container configuration as json

### ISSUE THREAD

**Issue by haraldrudell** [lxc/lxc#1797]
Every lxc container and the system itself has a config file with directives that a human can easily edit.
Modifying a bash-like configuration in software, however, is too old-fashioned and error prone.

Instead, lxc should offer json format export and import of all settings in the configuration file, json that can be easily modifyable by some managing software. json can be reliably parsed and modified as a one-liner in most languages.

lxc should also be able to programmatically provide the paths used so that paths do not have to be hard coded by consuming software.

This is similar to the capabilities of aws and gcp command-line interfaces,

**Comment by stgraber** [comment]
If you want this level of abstraction with JSON and YAML configuration, LXD provides that.
LXC as a low-level tool won't be changed to deal with JSON as that's painful to do in C and would break our APIs.
