### ISSUE TITLE
Assertion failed when start container

### ISSUE THREAD

**Issue by max107** [lxc/lxc#181]
Create container

```
[vagrant:vagrant-ubuntu-saucy-64:~]$ lxc-create -t download -n p2 -- -d ubuntu -r trusty -a amd64
```

Start container

```
[vagrant:vagrant-ubuntu-saucy-64:~]$ lxc-start -n p2
lxc_container: call to cgmanager_create_sync failed: invalid request
lxc_container: Failed to create cpuset:p2
lxc_container: Error creating cgroup cpuset:p2
lxc_container: failed creating cgroups
lxc_container: failed to spawn 'p2'
(null):cgmanager-client.c:5090: Assertion failed in cgmanager_remove_sync: cgroup != NULL
[1]    7980 abort      lxc-start -n p2
```

lxc-checkconfig

```
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-3.11.10userspace
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```

Default config

```
[vagrant:vagrant-ubuntu-saucy-64:~]$ cat ~/.config/lxc/default.conf
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:xx:xx:xx
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
```

```
[vagrant:vagrant-ubuntu-saucy-64:~]$ sudo cat /etc/lxc/default.conf
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:xx:xx:xx
```

```
[vagrant:vagrant-ubuntu-saucy-64:~]$ sudo cat /etc/lxc/lxc-usernet
# USERNAME TYPE BRIDGE COUNT
vagrant veth lxcbr0 10
```

```
[vagrant:vagrant-ubuntu-saucy-64:~]$ uname -a
Linux vagrant-ubuntu-saucy-64 3.11.10userspace #1 SMP Sun Jan 12 04:52:45 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Installed lxc `1.0.1+master~20140308-0019-0ubuntu1~ppa1~saucy1 0`

```
[vagrant:vagrant-ubuntu-saucy-64:~]$ sudo apt-cache policy lxc
lxc:
  Installed: 1.0.1+master~20140308-0019-0ubuntu1~ppa1~saucy1
  Candidate: 1.0.1+master~20140308-0019-0ubuntu1~ppa1~saucy1
  Version table:
 *** 1.0.1+master~20140308-0019-0ubuntu1~ppa1~saucy1 0
        500 http://ppa.launchpad.net/ubuntu-lxc/daily/ubuntu/ saucy/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.0~alpha1-0ubuntu14.1 0
        500 http://ru.archive.ubuntu.com/ubuntu/ saucy-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ saucy-security/main amd64 Packages
     1.0.0~alpha1-0ubuntu14~ubuntu12.04.1 0
        100 http://ru.archive.ubuntu.com/ubuntu/ precise-backports/universe amd64 Packages
     1.0.0~alpha1-0ubuntu11 0
        500 http://ru.archive.ubuntu.com/ubuntu/ saucy/main amd64 Packages
     0.7.5-3ubuntu69 0
        500 http://ru.archive.ubuntu.com/ubuntu/ precise-updates/universe amd64 Packages
     0.7.5-3ubuntu52 0
        500 http://ru.archive.ubuntu.com/ubuntu/ precise/universe amd64 Packages
```

What's wrong?

**Comment by lulcat** [comment]
hmmm. Indeed. Did a pxe trusty server install, headless, ssh login and cgroups aren't set for user. I use a non sudo user for lxc, first ssh in as adm user, then ssh localhost to lxc user. But it doesn't set :/

I have UsePAM yes in sshd_config. (ps. thanks, I would have never thought of checking that ).

I have the lib and sigh, logind.conf is fine, so now what :/. I can't log in as the user locally so.

**Comment by hallyn** [comment]
Quoting lulcat (notifications@github.com):
> hmmm. Indeed. Did a pxe trusty server install, headless, ssh login and cgroups aren't set for user. I use a non sudo user for lxc, first ssh in as adm user, then ssh localhost to lxc user. But it doesn't set :/
> 
> I have UsePAM yes in sshd_config. (ps. thanks, I would have never thought of checking that ).
> 
> I have the lib and sigh, logind.conf is fine, so now what :/. I can't log in as the user locally so.

For a trusty host, you have to restart systemd-logind by hand after
installing cgmanager.  (sudo restart systemd-logind)

**Comment by lulcat** [comment]
+1

**Comment by julianlam** [comment]
@hrj I hope I am not too late, but I took many of the comments here and write-ups I've found online (s3hh's blog, lxc blog, etc) and found that utilising `cgm` to add the current subshell to that user's cgroup worked quite well. [I can now start and stop unprivileged containers via script/subshell](https://gist.github.com/julianlam/4e2bd91d8dedee21ca6f)

**Comment by kislyuk** [comment]
I'm hitting this error too, and starting to get really annoyed at it. I'm running a shell script as root, and all lxc-start calls of the form "sudo -u unprivileged-user lxc-start --name=... --foreground -- command" fail with the errors listed above ("lxc_cgmanager_create: 299 call to cgmanager_create_sync failed: invalid request").

When I run the script above (with the cgm commands), it gives me these errors instead: "Error org.freedesktop.DBus.Error.InvalidArgs: invalid request". The end result is the same: unable to run lxc-start as the unprivileged user.

**Comment by kislyuk** [comment]
Also, libpam-systemd is installed.

**Comment by kislyuk** [comment]
One thing to note. The user "unprivileged-user" is never logged in, by design. They have no password. It seems to have something to do with this - if I sub in the user that I used to ssh into the instance, it works fine.

I'm puzzled. Were unprivileged containers only designed to work for interactive users (those with PAM sessions)? That's really bizarre because many (most?) container applications involve service users - non-interactive users who never have sessions and who have their login shell disabled.

**Comment by julianlam** [comment]
@kislyuk Perhaps my gist about this issue may help? I ran into similar issues with my lxc containers, as my Node.js script started via upstart was also not granted the proper cgroup.

https://gist.github.com/julianlam/4e2bd91d8dedee21ca6f

**Comment by kislyuk** [comment]
@julianlam, thanks, I read your guide and followed the advice to use the cgm commands. I get the error "Error org.freedesktop.DBus.Error.InvalidArgs: invalid request", and the commands don't have the desired effect.

**Comment by kislyuk** [comment]
@julianlam, thanks for your gist, it really helped. In the end I figured out what I was doing wrong (the cgm commands need to be run by the privileged user, not the unprivileged one).

I don't understand why this machinery is not built into the lxc utilities. In the end it's lxc's responsibility to manage this - the end effect is that short of this workaround, unprivileged containers are currently not compatible with any sort of uid-based privilege separation and switching in the host, including things like su and sudo.

Does this situation change in lxd?

**Comment by hallyn** [comment]
This isn't an issue for lxd because lxd runs as root, and starts its unprivileged containers as root.
