### ISSUE TITLE
Support OCI images

### ISSUE THREAD

**Issue by hallyn** [lxc/lxc#1813]
Support creating containers from OCI images and running them.  This is probably mostly fine tuning my lxc-oci template.

**Comment by giuseppe** [comment]
@hallyn, as @lifeng68 pointed out in https://github.com/lxc/lxc/issues/1814, would [libocispec](https://github.com/giuseppe/libocispec) be useful for this task?  It simplifies the parsing of the OCI spec files so that they can be more easily accessed from C programs

**Comment by hallyn** [comment]
@giuseppe 

Hi,

That looks like it could be useful at some point - however so far it seems like what we need is translation of OCI format into lxc native container configuration, which is handled by an lxc template.  I'll keep this library in mind, though.

Thanks!
