### ISSUE TITLE
Support OCI run-time config

### ISSUE THREAD

**Issue by hallyn** [lxc/lxc#1814]
If we want k8s to be able to spawn lxc containers, it will pass OCI run-time configuration, which we will need to be able to parse.  This may just be a script to run as a pre-start hook to fill out the container config.

**Comment by lifeng68** [comment]
@hallyn ，this project may be helpful to parse the runtime spec json and image spec json
[libocispec](https://github.com/giuseppe/libocispec)

**Comment by brauner** [comment]
@hallyn, @lifeng68 is this issue still relevant? We won't put the effort in ourselves right now but what's the goal, a native way for liblxc to user oci? Meaning you could call `load_config()` on a native lxc or a native oci runtime config? That shouldn't be too hard to do. It's a little bit of code and you'd need an embeddable json parser like http://zserge.com/jsmn.html . The libocispec bothers me in so far as it uses Python. If you want to do this it should be done in C.

**Comment by giuseppe** [comment]
@brauner Python is used only to generate the parser that is a C library, you'll need to re-run the Python script only if the OCI spec files are changed.  There is no Python involved after the `.c` files are created.

**Comment by brauner** [comment]
Hi @giuseppe, cool. @hallyn, what's your opinion on this one?

**Comment by hallyn** [comment]
Well, I guess it does have the advantage of automatically keeping up with the specs.

I'm ok with using it in principle.  Would love to see some patches.

**Comment by brauner** [comment]
@giuseppe, are you interested in working on this?

**Comment by giuseppe** [comment]
I've a limited amount of spare time to dedicate to some new task right now, but I can have a look to get a better idea of what must be done.  Do you have any pointer where I can start looking at?

**Comment by brauner** [comment]
> I've a limited amount of spare time to dedicate to some new task right now, but I can have a look to get a better idea of what must be done. Do you have any pointer where I can start looking at?

Sure, I guess the main idea would be to enable `load_config()` to natively parse an oci config file. Fyi, the callstack relevant for our config file parsing can be found here:
- https://github.com/lxc/lxc/blob/4c6fb19b30e5edaa632ee07df0838e3bf2122551/src/lxc/lxccontainer.c#L596
- https://github.com/lxc/lxc/blob/4c6fb19b30e5edaa632ee07df0838e3bf2122551/src/lxc/lxccontainer.c#L582
- https://github.com/lxc/lxc/blob/03a0a42b99543623a3b4a042707ea874e918fc34/src/lxc/confile.c#L2361
- https://github.com/lxc/lxc/blob/4c6fb19b30e5edaa632ee07df0838e3bf2122551/src/lxc/parse.c#L67
- https://github.com/lxc/lxc/blob/03a0a42b99543623a3b4a042707ea874e918fc34/src/lxc/confile.c#L2270

Essentially, I `mmap()` the file and then parse it line by line but our config file is very simple. Now, in addition to `lxc_config_read()`  `load_config()` would now also understand a `oci_config_read()`. This would allow `load_config()` to either load an `oci` or a `lxc` config file. I think we can just dynamically detect this at load time. This way we don't have to break API. The `oci_config_read()` function would need to fill in the values of the lxc config in:

- https://github.com/lxc/lxc/blob/4c6fb19b30e5edaa632ee07df0838e3bf2122551/src/lxc/conf.h#L230

We already have a script that maps oci config values to lxc config values so there's precedence:

- https://github.com/lxc/lxc/blob/master/templates/lxc-oci.in

Feel free to ask more questions. :)

**Comment by giuseppe** [comment]
I don't have enough time at the moment to complete the implementation, but I've done a quick experiment with libocispec:

https://github.com/giuseppe/lxc/tree/libocispec

One thing I am wondering about though is that in the `lxc-oci.in` example the data from the image spec is used.  The metadata in the image spec is very limited, as it defines just the entrypoint and additional environment variables, uid and working directory (basically what you can define in a Dockerfile).  There is no information like the mounts, capabilities, or anything you can find in the runtime OCI spec.

In the WIP branch I've linked, I have added the infrastructure for using the OCI runtime spec, not the image spec.

About k8s, are you sure this will be enough?  AFAIK, the OCI runtime spec is not generated directly by k8s.

**Comment by 3XX0** [comment]
That's right, the `lxc-oci` template only tries to convert images that use the OCI image spec (or something similar like Docker). This is useful if you want to pull say an image from DockerHub with LXC.

If you want to implement the OCI runtime spec it's quite different, you need to have LXC parse this json spec instead of its config file.

About K8s that's correct you will also need a CRI interface, but if you're OCI compliant you can use something like CRIO or add a new runtime to cri-containerd

**Comment by giuseppe** [comment]
Thanks, I asked as I was not sure if I missed any part of LXC that already does that.

As you need the OCI runtime spec, then I think libocispec can be quite helpful as the code will look like:

https://github.com/giuseppe/lxc/commit/1c6edf93ca4c8b04e8ed016c762cac7cbf539a07#diff-2f3344d3cb9700d11140decc560aaacaR2373

instead of worrying about parsing the json file and keep it in sync with the specs.

**Comment by hallyn** [comment]
> As you need the OCI runtime spec, then I think libocispec can be quite helpful as the code will look like:

The lxc-oci template aims to produce an lxc configuration for the container,
so that no runtime spec needs to be parsed.

If lXC gets into the business of reading oci runtime configuration, then
we'll need to decide things like how lxc should find it and how it
should decide which configuration to use.

**Comment by giuseppe** [comment]
> The lxc-oci template aims to produce an lxc configuration for the container, so that no runtime spec needs to be parsed.

how would lxc-oci do that?  The image spec has very limited metadata on how to run the container, unless you expect the users to customize the configuration (as you would do with the arguments to `docker run`) then it won't be enough to run the container.

**Comment by hallyn** [comment]
Hi,

In the face of the oci template and the crio-lxc project, I'm going to close this issue.

If someone still has a need for this, please feel free to re-open.
