### ISSUE TITLE
Unprivileged container isn't booting

### ISSUE THREAD

**Issue by Dominik28111** [lxc/lxc#1815]
My unprivileged LXC container isn't booting.

# Informations:

Distribution: Debian 9.1

Output of `lxc-start --version`:  

2.0.8

==========

Output of `lxc-checkconfig`:

Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.10.17-1-pve
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: enabled
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

==========

Output of `uname -a`:

Linux dedi 4.10.17-1-pve #1 SMP PVE 4.10.17-16 (Tue, 11 Jul 2017 09:55:44 +0200) x86_64 GNU/Linux

==========

Output of `cat /proc/self/cgroup`:

11:devices:/system.slice/ssh.service
10:hugetlb:/
9:perf_event:/
8:cpuset:/
7:cpu,cpuacct:/system.slice
6:memory:/
5:blkio:/
4:pids:/system.slice/ssh.service
3:net_cls,net_prio:/
2:freezer:/
1:name=systemd:/system.slice/ssh.service

==========

Output of `lxc-start -n 110 -F -l DEBUG -o /tmp/lxc-110.log`:

      lxc-start 20170918145406.392 INFO     lxc_start_ui - tools/lxc_start.c:main:275 - using rcfile /var/lib/lxc/110/config
      lxc-start 20170918145406.392 WARN     lxc_confile - confile.c:config_pivotdir:2022 - lxc.pivotdir is ignored.  It will soon become an error.
      lxc-start 20170918145406.392 INFO     lxc_confile - confile.c:config_idmap:1643 - read uid map: type u nsid 0 hostid 100000 range 65536
      lxc-start 20170918145406.392 INFO     lxc_confile - confile.c:config_idmap:1643 - read uid map: type g nsid 0 hostid 100000 range 65536
      lxc-start 20170918145406.392 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for reject_force_umount action 0.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:259 - Setting Seccomp rule to reject force umounts.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for reject_force_umount action 0.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:259 - Setting Seccomp rule to reject force umounts.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:259 - Setting Seccomp rule to reject force umounts.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .[all].
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .kexec_load errno 1.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for kexec_load action 327681.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for kexec_load action 327681.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .open_by_handle_at errno 1.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for open_by_handle_at action 327681.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for open_by_handle_at action 327681.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .init_module errno 1.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for init_module action 327681.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for init_module action 327681.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .finit_module errno 1.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for finit_module action 327681.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for finit_module action 327681.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .delete_module errno 1.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for delete_module action 327681.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for delete_module action 327681.
      lxc-start 20170918145406.392 INFO     lxc_seccomp - seccomp.c:parse_config_v2:603 - Merging in the compat Seccomp ctx into the main one.
      lxc-start 20170918145406.392 INFO     lxc_conf - conf.c:run_script_argv:483 - Executing script "/usr/share/lxc/hooks/lxc-pve-prestart-hook" for container "110", config section "lxc".
      lxc-start 20170918145407.160 DEBUG    lxc_start - start.c:setup_signal_fd:273 - Set SIGCHLD handler with file descriptor: 5.
      lxc-start 20170918145407.160 DEBUG    console - console.c:lxc_console_peer_default:447 - using "/dev/tty" as peer tty device
      lxc-start 20170918145407.160 DEBUG    console - console.c:lxc_console_sigwinch_init:144 - 32667 got SIGWINCH fd 9
      lxc-start 20170918145407.160 DEBUG    console - console.c:lxc_console_winsz:71 - set winsz dstfd:6 cols:80 rows:24
      lxc-start 20170918145407.160 INFO     lxc_start - start.c:lxc_init:475 - Container "110" is initialized.
      lxc-start 20170918145407.161 DEBUG    lxc_start - start.c:__lxc_start:1352 - Not dropping CAP_SYS_BOOT or watching utmp.
      lxc-start 20170918145407.166 INFO     lxc_conf - conf.c:run_script:534 - Executing script "/usr/share/lxc/lxcnetaddbr" for container "110", config section "net".
      lxc-start 20170918145407.659 DEBUG    lxc_conf - conf.c:instantiate_veth:2849 - instantiated veth 'veth110i0/vethUJM07B', index is '124'
      lxc-start 20170918145407.659 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for 110
      lxc-start 20170918145407.659 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:filter_and_set_cpus:481 - No isolated cpus detected.
      lxc-start 20170918145407.659 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:handle_cpuset_hierarchy:651 - "cgroup.clone_children" was already set to "1".
      lxc-start 20170918145407.660 INFO     lxc_start - start.c:lxc_spawn:1169 - Cloned CLONE_NEWUSER.
      lxc-start 20170918145407.660 INFO     lxc_start - start.c:lxc_spawn:1169 - Cloned CLONE_NEWNS.
      lxc-start 20170918145407.660 INFO     lxc_start - start.c:lxc_spawn:1169 - Cloned CLONE_NEWPID.
      lxc-start 20170918145407.660 INFO     lxc_start - start.c:lxc_spawn:1169 - Cloned CLONE_NEWUTS.
      lxc-start 20170918145407.660 INFO     lxc_start - start.c:lxc_spawn:1169 - Cloned CLONE_NEWIPC.
      lxc-start 20170918145407.660 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
      lxc-start 20170918145407.660 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
      lxc-start 20170918145407.660 DEBUG    lxc_conf - conf.c:lxc_map_ids:3469 - Functional newuidmap and newgidmap binary found.
      lxc-start 20170918145407.664 INFO     lxc_start - start.c:do_start:745 - Unshared CLONE_NEWNET.
      lxc-start 20170918145407.664 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:2031 - cgroup 'memory.limit_in_bytes' set to '536870912'
      lxc-start 20170918145407.664 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:2031 - cgroup 'memory.memsw.limit_in_bytes' set to '536870912'
      lxc-start 20170918145407.664 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:2031 - cgroup 'cpu.shares' set to '1024'
      lxc-start 20170918145407.664 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:2031 - cgroup 'cpuset.cpus' set to '5'
      lxc-start 20170918145407.664 INFO     lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:2035 - cgroup has been setup
      lxc-start 20170918145407.664 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
      lxc-start 20170918145407.664 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
      lxc-start 20170918145407.664 DEBUG    lxc_conf - conf.c:lxc_map_ids:3469 - Functional newuidmap and newgidmap binary found.
      lxc-start 20170918145407.701 DEBUG    lxc_conf - conf.c:lxc_assign_network:3356 - move 'vethUJM07B'/'eth0' to '32749': .
      lxc-start 20170918145407.701 NOTICE   lxc_utils - utils.c:lxc_switch_uid_gid:2062 - Switched to gid 0.
      lxc-start 20170918145407.701 NOTICE   lxc_utils - utils.c:lxc_switch_uid_gid:2068 - Switched to uid 0.
      lxc-start 20170918145407.701 NOTICE   lxc_utils - utils.c:lxc_setgroups:2080 - Dropped additional groups.
      lxc-start 20170918145407.705 DEBUG    lxc_conf - conf.c:setup_rootfs:1260 - Mounted rootfs "/var/lib/lxc/110/rootfs" onto "/usr/lib/x86_64-linux-gnu/lxc/rootfs" with options "(null)".
      lxc-start 20170918145407.705 INFO     lxc_conf - conf.c:setup_utsname:881 - 'test.to' hostname has been setup
      lxc-start 20170918145407.741 DEBUG    lxc_conf - conf.c:setup_hw_addr:2340 - mac address '02:00:00:cc:96:a9' on 'eth0' has been setup
      lxc-start 20170918145407.741 DEBUG    lxc_conf - conf.c:setup_netdev:2567 - 'eth0' has been setup
      lxc-start 20170918145407.741 INFO     lxc_conf - conf.c:setup_network:2588 - network has been setup
      lxc-start 20170918145407.741 INFO     lxc_conf - conf.c:mount_autodev:1110 - Mounting container /dev
      lxc-start 20170918145407.741 INFO     lxc_conf - conf.c:mount_autodev:1133 - Mounted tmpfs onto /usr/lib/x86_64-linux-gnu/lxc/rootfs/dev
      lxc-start 20170918145407.741 INFO     lxc_conf - conf.c:mount_autodev:1151 - Mounted container /dev
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1830 - remounting /sys/fs/fuse/connections on /usr/lib/x86_64-linux-gnu/lxc/rootfs/sys/fs/fuse/connections to respect bind or remount options
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1845 - (at remount) flags for /sys/fs/fuse/connections was 4096, required extra flags are 0
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1854 - mountflags already was 4096, skipping remount
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1880 - mounted '/sys/fs/fuse/connections' on '/usr/lib/x86_64-linux-gnu/lxc/rootfs/sys/fs/fuse/connections', type 'none'
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1830 - remounting /dev/full on /usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/full to respect bind or remount options
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1845 - (at remount) flags for /dev/full was 4098, required extra flags are 2
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1880 - mounted '/dev/full' on '/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/full', type 'none'
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1830 - remounting /dev/null on /usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/null to respect bind or remount options
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1845 - (at remount) flags for /dev/null was 4098, required extra flags are 2
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1880 - mounted '/dev/null' on '/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/null', type 'none'
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1830 - remounting /dev/random on /usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/random to respect bind or remount options
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1845 - (at remount) flags for /dev/random was 4098, required extra flags are 2
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1880 - mounted '/dev/random' on '/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/random', type 'none'
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1830 - remounting /dev/tty on /usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/tty to respect bind or remount options
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1845 - (at remount) flags for /dev/tty was 4098, required extra flags are 2
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1880 - mounted '/dev/tty' on '/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/tty', type 'none'
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1830 - remounting /dev/urandom on /usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/urandom to respect bind or remount options
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1845 - (at remount) flags for /dev/urandom was 4098, required extra flags are 2
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1880 - mounted '/dev/urandom' on '/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/urandom', type 'none'
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1830 - remounting /dev/zero on /usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/zero to respect bind or remount options
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1845 - (at remount) flags for /dev/zero was 4098, required extra flags are 2
      lxc-start 20170918145407.742 DEBUG    lxc_conf - conf.c:mount_entry:1880 - mounted '/dev/zero' on '/usr/lib/x86_64-linux-gnu/lxc/rootfs/dev/zero', type 'none'
      lxc-start 20170918145407.742 INFO     lxc_conf - conf.c:mount_file_entries:2100 - mount points have been setup
      lxc-start 20170918145407.742 INFO     lxc_conf - conf.c:run_script_argv:483 - Executing script "/usr/share/lxcfs/lxc.mount.hook" for container "110", config section "lxc".
      lxc-start 20170918145407.758 INFO     lxc_conf - conf.c:run_script_argv:483 - Executing script "/usr/share/lxc/hooks/lxc-pve-autodev-hook" for container "110", config section "lxc".
      lxc-start 20170918145407.941 ERROR    lxc_conf - conf.c:run_buffer:464 - Script exited with status 1.
      lxc-start 20170918145407.941 ERROR    lxc_conf - conf.c:lxc_setup:4138 - failed to run autodev hooks for container '110'.
      lxc-start 20170918145407.941 ERROR    lxc_start - start.c:do_start:811 - Failed to setup container "110".
      lxc-start 20170918145407.941 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
      lxc-start 20170918145407.941 INFO     lxc_conf - conf.c:lxc_delete_network:3165 - Interface "eth0" with index 124 already deleted or existing in different network namespace.
      lxc-start 20170918145408.616 INFO     lxc_conf - conf.c:lxc_delete_network:3190 - Removed interface "veth110i0" from host.
      lxc-start 20170918145408.618 ERROR    lxc_start - start.c:__lxc_start:1381 - Failed to spawn container "110".
      lxc-start 20170918145408.129 INFO     lxc_conf - conf.c:run_script_argv:483 - Executing script "/usr/share/lxcfs/lxc.reboot.hook" for container "110", config section "lxc".
      lxc-start 20170918145408.632 INFO     lxc_conf - conf.c:run_script_argv:483 - Executing script "/usr/share/lxc/hooks/lxc-pve-poststop-hook" for container "110", config section "lxc".
      lxc-start 20170918145409.673 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
      lxc-start 20170918145409.673 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
      lxc-start 20170918145409.673 DEBUG    lxc_conf - conf.c:lxc_map_ids:3469 - Functional newuidmap and newgidmap binary found.
      lxc-start 20170918145409.677 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
      lxc-start 20170918145409.677 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
      lxc-start 20170918145409.677 DEBUG    lxc_conf - conf.c:lxc_map_ids:3469 - Functional newuidmap and newgidmap binary found.
      lxc-start 20170918145409.680 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
      lxc-start 20170918145409.680 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
      lxc-start 20170918145409.680 DEBUG    lxc_conf - conf.c:lxc_map_ids:3469 - Functional newuidmap and newgidmap binary found.
      lxc-start 20170918145409.687 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
      lxc-start 20170918145409.687 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
      lxc-start 20170918145409.687 DEBUG    lxc_conf - conf.c:lxc_map_ids:3469 - Functional newuidmap and newgidmap binary found.
      lxc-start 20170918145409.692 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
      lxc-start 20170918145409.692 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
      lxc-start 20170918145409.692 DEBUG    lxc_conf - conf.c:lxc_map_ids:3469 - Functional newuidmap and newgidmap binary found.
      lxc-start 20170918145409.696 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
      lxc-start 20170918145409.696 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
      lxc-start 20170918145409.696 DEBUG    lxc_conf - conf.c:lxc_map_ids:3469 - Functional newuidmap and newgidmap binary found.
      lxc-start 20170918145409.701 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
      lxc-start 20170918145409.701 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
      lxc-start 20170918145409.701 DEBUG    lxc_conf - conf.c:lxc_map_ids:3469 - Functional newuidmap and newgidmap binary found.
      lxc-start 20170918145409.705 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
      lxc-start 20170918145409.705 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
      lxc-start 20170918145409.705 DEBUG    lxc_conf - conf.c:lxc_map_ids:3469 - Functional newuidmap and newgidmap binary found.
      lxc-start 20170918145409.709 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
      lxc-start 20170918145409.709 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
      lxc-start 20170918145409.709 DEBUG    lxc_conf - conf.c:lxc_map_ids:3469 - Functional newuidmap and newgidmap binary found.
      lxc-start 20170918145409.716 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
      lxc-start 20170918145409.716 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
      lxc-start 20170918145409.716 DEBUG    lxc_conf - conf.c:lxc_map_ids:3469 - Functional newuidmap and newgidmap binary found.
      lxc-start 20170918145409.722 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
      lxc-start 20170918145409.722 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:3408 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
      lxc-start 20170918145409.722 DEBUG    lxc_conf - conf.c:lxc_map_ids:3469 - Functional newuidmap and newgidmap binary found.
      lxc-start 20170918145409.754 ERROR    lxc_start_ui - tools/lxc_start.c:main:366 - The container failed to start.
      lxc-start 20170918145409.754 ERROR    lxc_start_ui - tools/lxc_start.c:main:370 - Additional information can be obtained by setting the --logfile and --logpriority options.

**Comment by brauner** [comment]
Your custom `autodev`  hook `/usr/share/lxc/hooks/lxc-pve-autodev-hook` fails. What is in there?

**Comment by Dominik28111** [comment]
```perl
#!/usr/bin/perl

use strict;
use warnings;

exit 0 if $ENV{LXC_NAME} && $ENV{LXC_NAME} !~ /^\d+$/;

use File::Path;
use File::Basename;

use PVE::Tools;

my $vmid = $ENV{LXC_NAME};
my $root = $ENV{LXC_ROOTFS_MOUNT};

if (@ARGV != 3 || $ARGV[1] ne 'lxc' || $ARGV[2] ne 'autodev') {
    die "invalid usage, this is an LXC autodev hook\n";
}

if ($vmid ne $ARGV[0]) {
    die "got wrong name: $ARGV[0] while LXC_NAME=$vmid\n";
}

my $devlist_file = "/var/lib/lxc/$vmid/devices";
my $fd;

if (! open $fd, '<', $devlist_file) {
    exit 0 if $!{ENOENT}; # If the list is empty the file might not exist.
    die "failed to open device list: $!\n";
}

while (defined(my $line = <$fd>)) {
    if ($line !~ m@^(b):(\d+):(\d+):/dev/(\S+)\s*$@) {
	warn "invalid .pve-devices entry: $line\n";
    }
    my ($type, $major, $minor, $dev) = ($1, $2, $3, $4);

    # Don't break out of $root/dev/
    if ($dev =~ /\.\./) {
	warn "skipping illegal device node entry: $dev\n";
	next;
    }

    # Never expose /dev/loop-control
    if ($major == 10 && $minor == 237) {
	warn "skipping illegal device entry (loop-control) for: $dev\n";
	next;
    }

    my $rel_devpath = "/dev/$dev";
    my $rel_dir = dirname($rel_devpath);
    File::Path::mkpath("$root/$rel_dir");

    PVE::Tools::run_command(['mknod', '-m', '666', "$root/dev/$dev",
                             $type, $major, $minor]);

    if ($dev =~ /^dm-\d+$/) {
	File::Path::mkpath("$root/dev/mapper");
	my $mapped_name = PVE::Tools::file_get_contents("/sys/block/$dev/dm/name");
	chomp $mapped_name;
	symlink("/dev/$dev", "$root/dev/mapper/$mapped_name");
    }
}
close $fd;

exit 0;
```

**Comment by brauner** [comment]
@Dominik28111, you're calling `mknod()` in the autodev hook that won't work with unprivileged containers. By the time the autodev sript is run liblxc will have already cloned a new user namespace. User namespaces do not allow creating device nodes. However, @hallyn and I are thinking about adding a new hook that runs with the host's privileges right before the container exec's. This would allow you to call `mknod()` iff you start the unprivileged container as root on the host, i.e. when the user that calls the binary is real root.

**Comment by brauner** [comment]
In case you don't need access to the container's rootfs, i.e. if you're fine with the rootfs not being mounted you could see if the `pre-start` or `pre-mount` hooks are sufficient for your use-case for now.

**Comment by Dominik28111** [comment]
@brauner, this means that I should remove only the following line:

```perl
PVE::Tools::run_command(['mknod', '-m', '666', "$root/dev/$dev",
                             $type, $major, $minor]);
```

**Comment by Dominik28111** [comment]
@brauner, I removed the line and the container is booting now but I see the CPU usage and load of the Host and not of the container. Furthermore I get the following message on the host:

`Message from syslogd@dedi at Sep 19 13:52:18 ...
 kernel:[4279917.797705] unregister_netdevice: waiting for lo to become free. Usage count = 0
`

**Comment by brauner** [comment]
@Dominik28111, inside of the container you'll always see the cpu usage and load of the host since /proc is not virtualized. That's why we provide `lxcfs` which does a partial /proc virtualization. Debian should have a package for it. The latter sounds like a kernel problem unrelated to liblxc.

**Comment by Dominik28111** [comment]
@brauner, lxcfs is installed. What I have to do now to use it?

**Comment by brauner** [comment]
Can you show

    systemctl status lxcfs

please and also

    cat /proc/1/mountinfo 

from inside the container?

**Comment by Dominik28111** [comment]
Ohh, only on the Host is lxcfs installed but not on the container.

Output `cat /proc/1/mountinfo` inside container:

```
212 176 7:0 / / rw,relatime - ext4 /dev/loop0 rw,data=ordered,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group
213 212 0:47 / /dev rw,relatime - tmpfs none rw,size=492k,mode=755,uid=100000,gid=100000
214 212 0:46 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
215 216 0:46 /sys/net /proc/sys/net rw,nosuid,nodev,noexec,relatime - proc proc rw
216 214 0:46 /sys /proc/sys ro,nosuid,nodev,noexec,relatime - proc proc rw
217 214 0:46 /sysrq-trigger /proc/sysrq-trigger ro,nosuid,nodev,noexec,relatime - proc proc rw
218 212 0:48 / /sys rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
219 218 0:48 / /sys ro,nosuid,nodev,noexec,relatime - sysfs sysfs rw
220 219 0:48 / /sys/devices/virtual/net rw,relatime - sysfs sysfs rw
221 220 0:48 /devices/virtual/net /sys/devices/virtual/net rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
222 219 0:40 / /sys/fs/fuse/connections rw,relatime master:28 - fusectl fusectl rw
223 213 0:6 /full /dev/full rw,nosuid,relatime master:2 - devtmpfs udev rw,size=8181196k,nr_inodes=2045299,mode=755
224 213 0:6 /null /dev/null rw,nosuid,relatime master:2 - devtmpfs udev rw,size=8181196k,nr_inodes=2045299,mode=755
225 213 0:6 /random /dev/random rw,nosuid,relatime master:2 - devtmpfs udev rw,size=8181196k,nr_inodes=2045299,mode=755
226 213 0:6 /tty /dev/tty rw,nosuid,relatime master:2 - devtmpfs udev rw,size=8181196k,nr_inodes=2045299,mode=755
227 213 0:6 /urandom /dev/urandom rw,nosuid,relatime master:2 - devtmpfs udev rw,size=8181196k,nr_inodes=2045299,mode=755
228 213 0:6 /zero /dev/zero rw,nosuid,relatime master:2 - devtmpfs udev rw,size=8181196k,nr_inodes=2045299,mode=755
229 214 0:43 /proc/cpuinfo /proc/cpuinfo rw,nosuid,nodev,relatime master:83 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
230 214 0:43 /proc/diskstats /proc/diskstats rw,nosuid,nodev,relatime master:83 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
231 214 0:43 /proc/meminfo /proc/meminfo rw,nosuid,nodev,relatime master:83 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
232 214 0:43 /proc/stat /proc/stat rw,nosuid,nodev,relatime master:83 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
233 214 0:43 /proc/swaps /proc/swaps rw,nosuid,nodev,relatime master:83 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
234 214 0:43 /proc/uptime /proc/uptime rw,nosuid,nodev,relatime master:83 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
235 213 0:19 /1 /dev/console rw,nosuid,noexec,relatime master:3 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
177 213 0:49 / /dev/pts rw,relatime - devpts devpts rw,gid=100005,mode=620,ptmxmode=666
178 213 0:49 /ptmx /dev/ptmx rw,relatime - devpts devpts rw,gid=100005,mode=620,ptmxmode=666
179 213 0:49 /0 /dev/tty1 rw,relatime - devpts devpts rw,gid=100005,mode=620,ptmxmode=666
180 213 0:49 /1 /dev/tty2 rw,relatime - devpts devpts rw,gid=100005,mode=620,ptmxmode=666
181 212 0:50 / /run rw,nosuid,noexec,relatime - tmpfs tmpfs rw,size=1639564k,mode=755,uid=100000,gid=100000
182 181 0:51 / /run/lock rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,size=5120k,uid=100000,gid=100000
183 181 0:52 / /run/shm rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,size=104840k,uid=100000,gid=100000
```

**Comment by brauner** [comment]
Oh right, so `loadavg` is not virtualized in `LXCFS` yet but it is an open issue against the repo. As for cpu info what does top show you when you try to restrict `cpuset.cpus`?

**Comment by brauner** [comment]
Oh, I see you're placed in the root cgroup for the cpuset controller on the host which means you won't be able to apply cgroup limits since you're not placed in a writable cgroup for that controller. Now, there's abug in liblxc I think in so far as it doesn't error out when the user requests a limit to be set that can't be fulfilled. I'll take a look now.

**Comment by Dominik28111** [comment]
@brauner, okay how can I add lxcfs now that `/proc` is virtualized too?
