### ISSUE TITLE
We need to update a manpage for lxc-user-nic(1)

### ISSUE THREAD

**Issue by tenforward** [lxc/lxc#1823]
Now lxc-user-nic has subcommands(create and delete), so we need to update the man page.

**Comment by AkihiroSuda** [comment]
@brauner @stgraber any update?

**Comment by brauner** [comment]
Hey, @AkihiroSuda yeah, I can take a look at that tomorrow most likely.

**Comment by tenforward** [comment]
Thanks! I will transrate it later

**Comment by tenforward** [comment]
Japanese man page
https://github.com/lxc/lxc/pull/2926
