### ISSUE TITLE
bash_completion.d errors when building LXC  (2.0.8 or 2.1.0) rpm on Oracle Linux 7.4

### ISSUE THREAD

**Issue by gstanden** [lxc/lxc#1825]
# Required information

 * Distribution:  Oracle Linux
 * Distribution version: 7.4
 * The output of
   * `lxc-start --version` 
2.0.8 or 2.1.0 (both have the issue - although 2.1.0 the issue is not fatal)
   * `lxc-checkconfig`  
clean - all give "enabled" status (for lxc 1.1.5 which is installed first from epel) then source build rpm is created and installed - which succeeds for 2.0.5 but fails for 2.0.8 and gives errors but succeeds for 2.1.0
   * `uname -a` 
Linux ol74a 4.1.12-103.3.8.1.el7uek.x86_64 #2 SMP Fri Sep 15 17:23:08 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
[ubuntu@ol74a Downloads]$ cat /proc/self/cgroup
10:perf_event:/
9:memory:/
8:freezer:/
7:cpu,cpuacct:/
6:hugetlb:/
5:devices:/user.slice
4:net_cls,net_prio:/
3:blkio:/
2:cpuset:/
1:name=systemd:/user.slice/user-1000.slice/session-1.scope
[ubuntu@ol74a Downloads]$ 

   * `cat /proc/1/mounts`
[ubuntu@ol74a Downloads]$ cat /proc/1/mounts
sysfs /sys sysfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
devtmpfs /dev devtmpfs rw,seclabel,nosuid,size=4966256k,nr_inodes=1241564,mode=755 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,seclabel,nosuid,nodev 0 0
devpts /dev/pts devpts rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,seclabel,nosuid,nodev,mode=755 0 0
tmpfs /sys/fs/cgroup tmpfs ro,seclabel,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,seclabel,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,seclabel,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,seclabel,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,seclabel,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,seclabel,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,seclabel,nosuid,nodev,noexec,relatime,perf_event 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
/dev/mapper/ol-root / xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=32,pgrp=1,timeout=0,minproto=5,maxproto=5,direct 0 0
debugfs /sys/kernel/debug debugfs rw,seclabel,relatime 0 0
mqueue /dev/mqueue mqueue rw,seclabel,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,seclabel,relatime 0 0
nfsd /proc/fs/nfsd nfsd rw,relatime 0 0
/dev/sda1 /boot xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0
/dev/mapper/ol-home /home xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0
sunrpc /var/lib/nfs/rpc_pipefs rpc_pipefs rw,relatime 0 0
ROOT /media/sf_ROOT vboxsf rw,nodev,relatime 0 0
tmpfs /run/user/42 tmpfs rw,seclabel,nosuid,nodev,relatime,size=998072k,mode=700,uid=42,gid=42 0 0
tmpfs /run/user/1000 tmpfs rw,seclabel,nosuid,nodev,relatime,size=998072k,mode=700,uid=1000,gid=1000 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
[ubuntu@ol74a Downloads]$ 

# Issue description
Building LXC *.rpm from source on Oracle Linux 7.4 fails with messages about file not found "bash_completion.d" for source versions 2.0.8 and 2.1.0.  The problem does NOT occur with 2.0.5 LXC source.

Processing files: lxc-2.1.0-1.el7.x86_64
error: File not found: /home/ubuntu/Downloads/orabuntu-lxc-master/uekulele/lxc/rpmbuild/BUILDROOT/lxc-2.1.0-1.el7.x86_64/etc/bash_completion.d

RPM build errors:
    File not found: /home/ubuntu/Downloads/orabuntu-lxc-master/uekulele/lxc/rpmbuild/BUILDROOT/lxc-2.1.0-1.el7.x86_64/etc/bash_completion.d

A brief description of what failed or what could be improved.

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
 - [ ] the containers configuration file

**Comment by gstanden** [comment]
Hey I found the fix to this myself.  Sorry for the bogus issue.  I haven't tested yet but this should fix the problem:  https://www.cyberciti.biz/faq/fedora-redhat-scientific-linuxenable-bash-completion/

**Comment by gstanden** [comment]
The install of bash-completion and bash-completion-extras from epel did not solve the problem.  LXC source code tarball 2.0.8 still errors out complaining that bash_completion.d does not exist.  LXC tarball 2.1.0 gives the same error and it's fatal to the build in both cases.   LXC tarball 2.0.5 is not affected and builds normally with no errors

**Comment by gstanden** [comment]
Update the workaround:  
[ubuntu@ol74a ~]$ sudo mkdir -p /home/ubuntu/Downloads/orabuntu-lxc-master/uekulele/lxc/rpmbuild/BUILDROOT/lxc-2.1.0-1.el7.x86_64/etc/bash_completion.d
[sudo] password for ubuntu: 
[ubuntu@ol74a ~]$ 
This worked and the build continues as normal so I am closing the issue as solved for my needs.

**Comment by vinod-990** [comment]
@gstanden 

I had the same issue and I borrowed the solution from src rpm of fedora. Here are changes in spec file:

%if 0%{?fedora} || 0%{?rhel} >= 7
%dir %{_datadir}/bash-completion
%dir %{_datadir}/bash-completion/completions
%{_datadir}/bash-completion/completions/%{name}
%else
%dir %{_sysconfdir}/bash_completion.d
%{_sysconfdir}/bash_completion.d/%{name}
%endif

**Comment by gstanden** [comment]
thanks! @vinod-990 I will try this fix tonight

**Comment by gstanden** [comment]
Just to provide some closure, this turned out to be a problem with my software Orabuntu-LXC not cleaning up lxc.spec files properly from previous installs of other LXC versions resulting in mixing of source code with incorrect lxc.spec file versions (facepalm - sorry) as my software has a user-selectable install/reinstall feature for LXC versions.  
Still, thanks very much @vinod-990 for the comment because that got me looking at the lxc.spec and eventually the lightbulb went on about the lxc.spec files not being cleaned up. 
Closing issue.
