### ISSUE TITLE
LXC mount entry devpts to read only after lxc-stop container. Can not start container back

### ISSUE THREAD

**Issue by phuclb1** [lxc/lxc#1841]
LXC mount entry devpts to read only after lxc-stop container. Can not start container back

# Required information

 * Distribution: aarch64
 * Distribution version: aarch64
 * The output of
   * `lxc-start --version`
2.0.5
   * `lxc-checkconfig`

--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: enabled
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled
   * `uname -a`
Linux 192.168.69.11 4.9.0 #1 SMP Wed Sep 13 19:20:14 JST 2017 aarch64 GNU/Linux
   * `cat /proc/self/cgroup`
1:cpuset,cpu,cpuacct,blkio,memory,devices,freezer,perf_event,hugetlb,pids,debug:/
   * `cat /proc/1/mounts`
/dev/root / ext4 rw,relatime,data=ordered 0 0
devtmpfs /dev devtmpfs rw,relatime,size=1496720k,nr_inodes=374180,mode=755 0 0
none /dev/pts devpts rw,relatime,mode=620,ptmxmode=000 0 0
none /dev/shm tmpfs rw,relatime 0 0
none /proc proc rw,relatime 0 0
none /sys sysfs rw,relatime 0 0
tmpfs /run tmpfs rw,nosuid,nodev,mode=755 0 0
tmpfs /var/volatile tmpfs rw,relatime 0 0
none /sys/fs/cgroup cgroup rw,relatime,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,perf_event,hugetlb,pids,debug,clone_children 0 0
/dev/mmcblk0p3 /var/lib/lxc ext4 rw,relatime,data=ordered 0 0

# Issue description
After stop lxc container, i cant start it back. Because /dev/pts was mounted to read only after stop container.

# Steps to reproduce

 1. lxc-stop -n test
 2. lxc-start -n test

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
      lxc-start 20170823053733.549 ERROR    console - console.c:lxc_console_create:514 - Read-only file system - failed to allocate a pty
      lxc-start 20170823053733.549 ERROR    lxc_start - start.c:lxc_init:480 - failed to create console
      lxc-start 20170823053733.549 ERROR    lxc_start - start.c:__lxc_start:1313 - failed to initialize the container
      lxc-start 20170823053738.556 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
      lxc-start 20170823053738.557 ERROR    lxc_start_ui - lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 20170823053738.557 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.

 - [ ] the containers configuration file
lxc.utsname = zinrai
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = lxcbr0
lxc.network.hwaddr = 00:16:3e:xx:xx:xx
lxc.network.ipv4 = 192.168.69.12/24
lxc.network.ipv4.gateway = 192.168.69.1
lxc.rootfs = /var/lib/lxc/zinrai/rootfs
lxc.mount.entry=/dev /var/lib/lxc/zinrai/rootfs/dev none bind 0 0
lxc.mount.entry=devpts /var/lib/lxc/zinrai/rootfs/dev/pts devpts gid=5,mode=620,newinstance,ptmxmode=0666 0 0
lxc.mount.entry=proc /proc /var/lib/lxc/zinrai/rootfs/proc nodev,noexec,nosuid 0 0
lxc.mount.entry=sysfs /var/lib/lxc/zinrai/rootfs/sys sysfs defaults 0 0
lxc.cgroup.devices.deny = a
lxc.cgroup.devices.allow = c 1:3 rwm
lxc.cgroup.devices.allow = c 1:5 rwm
lxc.cgroup.devices.allow = c 5:1 rwm
lxc.cgroup.devices.allow = c 5:0 rwm
lxc.cgroup.devices.allow = c 4:0 rwm
lxc.cgroup.devices.allow = c 4:1 rwm
lxc.cgroup.devices.allow = c 1:9 rwm
lxc.cgroup.devices.allow = c 1:8 rwm
lxc.cgroup.devices.allow = c 136:* rwm
lxc.cgroup.devices.allow = c 5:2 rwm
lxc.cgroup.devices.allow = c 254:0 rwm

**Comment by brauner** [comment]
Right, the problem here is that you're bind-mounting the host's `/dev` into a privileged container which means it can do everything it wants to the devices especially unmounting and removing even with the restrictions. That's something you should actually not do. I mean you can and we always want to allow experienced users to do just that but it's generally not safe. Newer liblxc instances like `2.1` and probably already `2.0.8` will warn the user in the logs about doing this but it's still not the greatest idea.
