### ISSUE TITLE
ZFS: `move` does not transfer snapshots

### ISSUE THREAD

**Issue by LordAro** [lxc/lxc#1842]
`lxc move` does not also transfer existing snapshots.

I can appreciate this not being default, but I believe there should be an option for it.

In particular, this is useful when moving containers between hosts, which are then backed-up elsewhere

**Comment by stgraber** [comment]
What LXD version is that?

I thought we added support migration in recent LXD releases which is why we now have a --container-only flag to copy/move.

**Comment by LordAro** [comment]
Hmm, interesting. I'm on 2.17, but I'll check again. There was definitely something weird happening...

**Comment by brauner** [comment]
For future reference, this is the wrong repo to report this issue to. LXD issues should be filed against https://github.com/lxc/lxd . :)

**Comment by LordAro** [comment]
It is? Honestly I've got not idea what the split is, it seems fairly arbitrary. `lxc move` is the command used, so I assume it's an LXC thing

**Comment by brauner** [comment]
Yeah, it's quite easy to get confused here. `lxc <subcommand>` is the client tool for `LXD` and lives in another repo. This repo right here - `liblxc` - is just the low-level `C` runtime that `LXD` uses to spawn containers. Don't worry about it. It's just for future bug reports. :)

**Comment by brauner** [comment]
2.18 should fix this issue. If you can reproduce with 2.18 please file a new bug outlining exactly what you did against https://github.com/lxc/lxd . :) Thanks!
