### ISSUE TITLE
 No file space on the device - Storage Pool 

### ISSUE THREAD

**Issue by otavio-prestes** [lxc/lxc#1843]
# Required information

 * Distribution: Ubuntu 16.04.03 LTS
 * Distribution version: lxc/lxd 2.16

# Issue description
 Os containers se encontram /var/lib/lxd/storage-pools/zfs/containers e em alguns momentos quando são iniciados vários containers todos vão a 100% do uso de disco na saída do comando df -h.
Ao logar em algum container e tentar criar algum arquivo ou pasta aparece a seguinte mensagem: "no file space on the device".
Alguém sabe como posso resolver esse problema? 
É possível criar criar um novo pool para novos containers?

**Comment by stgraber** [comment]
Sorry but we require the bug reports to be in English.

Based on the above, it sounds like you've managed to fill up your main storage pool.

You can possibly grow it through the zfs tools directly or create another one to use for additional containers, though note that we do not yet have a way to move containers between pools, so you'd likely need to delete a few of your containers to free up space.
