### ISSUE TITLE
[feature] Virtual network device

### ISSUE THREAD

**Issue by iglov** [lxc/lxc#1847]
Hi there!
Could you plz tell me, it is possible make something like **venet** ([Virtual network device](https://wiki.openvz.org/Virtual_network_device)) how it's doing on openvz?

**Comment by stgraber** [comment]
The upstream Linux kernel doesn't have anything similar to venet (L3 host to container interface), only L2 interfaces are available (macvlan, veth).

You may want to look at ipvlan which is pretty similar to macvlan but at the L3 layer, though we've never managed to get that to work in a useful way.
