### ISSUE TITLE
More sophisticated way for configuring seccomp

### ISSUE THREAD

**Issue by Harvie** [lxc/lxc#1848]
My `/usr/share/lxc/config/common.conf` contains this:
```
# Blacklist some syscalls which are not safe in privileged
# containers
lxc.seccomp.profile = /usr/share/lxc/config/common.seccomp
```
So when i need to add seccomp rules, i have to add them to file `/usr/share/lxc/config/common.seccomp`,
but that is overwritten during LXC upgrade.

Can you please make it possible to specify multiple seccomp profiles, so i can add my rules and have them safe even when package manager upgrades `/usr/share/lxc/config/common.seccomp` ?

There is already `/usr/share/lxc/config/common.conf.d/` where i can put my configuration so it does not get overwritten. So i guess  it could be usefull to have something like `/usr/share/lxc/config/common.seccomp.d/`

Also specifiing multiple profilles in lxc config might be usefull feature. might need boolean (AND/OR) operations on seccomp enabled syscalls (so you can decide whether syscalls should be added or removed from what is currently enabled).

```
lxc.seccomp.and.profile = /usr/share/lxc/config/common.seccomp
lxc.seccomp.and.profile = /usr/share/lxc/config/something_else.seccomp
```
And combining with inline rules can also be awesome. Something like:

```
lxc.seccomp.and.blacklist = kexec_load errno 1, open_by_handle_at errno 1
lxc.seccomp.and.blacklist = init_module errno 1, finit_module errno 1, delete_module errno 1
lxc.seccomp.and.blacklist = syslog errno 1
lxc.seccomp.or.whitelist = enable some previously disabled syscall
```

**Comment by brauner** [comment]
I'm not sure that adding logical operators into the configuration keys themselves is a good way to go. That's a potential layer of complexity I'm not convinced is ultimately that useful.
Specifying multiple seccomp profiles is also something I'm not convinced of. That would likely involve a lot of weird internal parsing and then you have the issue of liblxc supporting a v1 and v2 seccomp format and so on.
There's an issue open on expanding seccomp actually https://github.com/lxc/lxc/issues/1564 where we track this. Couldn't you just add a common config to `common.conf.d` like you said and then simply set `lxc.seccomp.profile` in there and keep the seccomp profile you don't want to have overwritten in `common.conf.d` as well?

**Comment by stgraber** [comment]
@brauner at what stage do we open the seccomp profile? Could a pre-start hook generate the file?

**Comment by Harvie** [comment]
@stgraber Is this really fixed? i think i don't understand the changes in #3314

**Comment by stgraber** [comment]
It now allows for a pre-start hook to write a profile which is then loaded through lxc.seccomp
