### ISSUE TITLE
SIGPWR not propgated after lxc-stop is called 

### ISSUE THREAD

**Issue by radzik30084** [lxc/lxc#1850]
Hello, 

I am using following lxc version:
lxc-execute --version
1.1.3

# Issue description
I stop LXC container via "lxc-stop -n name".
I expect, that by  default SIGPWR will be sent to all processes working inside container (childs of init process) based on:
https://linuxcontainers.org/lxc/manpages/man1/lxc-stop.1.html
"By default, it will request a clean shutdown of the container by sending lxc.signal.halt (defaults to SIGPWR) to the container's init process,"

and

https://linuxcontainers.org/lxc/manpages/man1/lxc-execute.1.html
"The above lxc-init is designed to forward received signals to the started command"

But I fact SIGTERM is sent to every application.

# Steps to reproduce

 1. Start container via lxc-execute
 2. Stop container via lxc-stop
 3. Check signals received via applications working inside container

Please let me know, if I misunderstand  description here or there is issue.
Why SIGTERM is propagated by init process instead SIGPWR ?

Regards,
Radek

**Comment by brauner** [comment]
No, `SIGPWR` is sent to the init process of the container. What happens after this completely depends on what runs as init inside the container. If it is a proper init system then it will usually send `SIGTERM` to all processes that are still running. If it is just a shell (e.g. `bash`) then it won't forward any signal at all.

**Comment by radzik30084** [comment]
Thank you for answer.
In this case how should I understand following sentence ?
The above lxc-init is designed to forward received signals to the started command

**Comment by brauner** [comment]
Well, the only thing the minimal init binary does is to forward signals to the started command. So in the case of `lxc-execute` you have:

    mini-init
             \
               started program

So if you send:

    SIGTERM --> mini-init

(or any other signal that is forwardable) then what happens is:

    receive(mini-init, SIGTERM);
    forward(minit-init, SIGTERM, started program)

**Comment by radzik30084** [comment]
Can you provide details about mini-init ? How to configure LXC in order to use mini-init ?

**Comment by brauner** [comment]
`lxc-execute` will take care of using the minimal init for you.

**Comment by brauner** [comment]
In essence, `init.lxc`/`init.lxc.static` is a minimal init binary that `liblxc` used to ship since `2008` when it was first conceived to correctly handle application containers. The minimal init is just taking over the basic tasks that the semantics of `PID namespaces` require: signal handling, reaping children, etc. Without this minimal set of features an application container is in essence dysfunctional.
