### ISSUE TITLE
LXC and ZFS rootfs not mounted

### ISSUE THREAD

**Issue by VoidAndAny** [lxc/lxc#1858]
This issue is more a need of explanation than a problem because I found a solution.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04
 * LXC Version : 2.1.0

# Issue description

Since LXC 2.1 the rootfs path of a container using ZFS is defined like this zfs:tank/lxc/container (note the zfs:) in lxc.rootfs.path variable.
Before it was a directory path : /tank/lxc/container/rootfs
With this configuration it seems that the ZFS dataset is not mounted, the container can still access the files and start normally but we can't access rootfs files's through filesystem host.

# Steps to reproduce

In /etc/lxc/lxc.conf I've got this configuration:
```
lxc.lxcpath = /tank/lxc
lxc.bdev.zfs.root = tank/lxc
```

Create new container named gogs (great git web interface by the way) : 
`sudo lxc-create -t download -n gogs -B zfs -- -d ubuntu -r xenial -a amd64`

So in /tank/lx/gogs/config, I've got this : 
`lxc.rootfs.path = zfs:tank/lxc/gogs`

Container can start normally, but roots FS is not mounted and seem empty : 
```
sudo lsl /tank/lxc/gogs/rootfs
total 0
```

If we try to mount dataset, ZFS return an error:
```
filesystem 'tank/lxc/gogs' is already mounted
cannot mount 'tank/lxc/gogs': mountpoint or dataset is busy
```

If we stop container, we can mount dataset and access files.
```
sudo lxc-stop -n gogs
sudo zfs mount tank/lxc/gogs
sudo ll /tank/lxc/gogs/rootfs
total 56K
drwxr-xr-x  2 root root 132 12/10/2017 13:50 bin/
drwxr-xr-x  2 root root   2 12/04/2016 22:14 boot/
drwxr-xr-x  3 root root  90 06/10/2017 05:55 dev/
...
```

But container don't start, with dataset mounted : 
```
lxc-start: gogs: lxccontainer.c: wait_on_daemonized_start: 760 Received container state "ABORTING" instead of "RUNNING"
lxc-start: gogs: tools/lxc_start.c: main: 368 The container failed to start.
lxc-start: gogs: tools/lxc_start.c: main: 370 To get more details, run the container in foreground mode.
lxc-start: gogs: tools/lxc_start.c: main: 372 Additional information can be obtained by setting the --logfile and --logpriority options.
```

It seems that with this configuration the access is exclusive, dataset mounted OR usable by LXC.

Always with dataset mounted (so file can be accessed through host filesystem), if we change lxc.rootfs.path to /tank/lxc/container/rootfs (replace zfs: with / and add rootfs directory at the end) we can mount dataset AND start container.

At the same time I also notice that the canmount zfs option of dataset created by LXC has change before 2.1 it was "on" now it's "noauto", preventing zfs dataset to be automatically mounted.

Am I right in my diagnostic ?
Why this changes ?

Thanks

**Comment by brauner** [comment]
@VoidAndAny, so there's a bug in zfs around mounting in different mount namespace which you are hitting here as well. Changing to the `noauto` options is on way of mitigating the bug which we also do in `LXD`. If you want you can try changing the option on the zfs dataset and see whether you run into problems or not.

**Comment by jaytaylor** [comment]
I'm still hitting this issue with lxc v2.18.

`noauto` is active, but the rootfs is still empty:

```bash
tank/lxc/base                      canmount              noauto                                local
```

```bash
root@ubuntu:~# ls /tank/lxc/base/rootfs/
root@ubuntu:~# du -sc /tank/lxc/base/rootfs/
1	/tank/lxc/base/rootfs/
1	total
root@ubuntu:~#
```

Any advice or insight you can offer would be appreciated!

**Comment by brauner** [comment]
@jaytaylor, this is a privileged or an unprivileged container?

**Comment by jaytaylor** [comment]
Unprivileged.
