### ISSUE TITLE
Push unprivileged fuse mounts feature into the upstream kernel

### ISSUE THREAD

**Issue by narcisgarcia** [lxc/lxc#1868]
As of  issue #1867 about Debian 9, Christian Brauner concluded

> unprivileged fuse mounts is a feature available in the Ubuntu kernel only atm. We are actively working on pushing this into the upstream kernel though

Please, close this issue when it's done.

**Comment by stgraber** [comment]
lxc is a userspace tool, what you're mentioning is unrelated kernel work so it doesn't make sense to have a Github issue against lxc to track this.

**Comment by narcisgarcia** [comment]
Where is a good place?
Thanks.

**Comment by stgraber** [comment]
https://launchpad.net/ubuntu/+source/linux/+filebug

**Comment by narcisgarcia** [comment]
Okay:
https://bugs.launchpad.net/bugs/1725382
