### ISSUE TITLE
overlayfs wrong  path

### ISSUE THREAD

**Issue by purplegrape** [lxc/lxc#1869]
* Distribution: CentOS 7
 * version: LXC 2.0.9

OUTPUTS
###############################################################
# lxc-create -n vm -t download -B overlayfs -- -d centos -r 7 -a amd64
Using image from local cache
Unpacking the rootfs

---
You just created a CentOS container (release=7, arch=amd64, variant=default)

To enable sshd, run: yum install openssh-server

For security reason, container images ship without user accounts
and without a root password.

Use lxc-attach or chroot directly into the rootfs to set a root password
or create user accounts.
# grep overlayfs /var/lib/lxc/vm/config 
lxc.rootfs = overlayfs:/var/lib/lxc/vm/rootfs:/var/lib/lxc/vm/delta0
lxc.rootfs.backend = overlayfs
# ls /var/lib/lxc/vm/rootfs
# ls /var/lib/lxc/vm/delta0
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  selinux  srv  sys  tmp  usr  var
###############################################################

howtofix it
rm -rf /var/lib/lxc/vm/rootfs
mv /var/lib/lxc/vm/delta0 /var/lib/lxc/vm/rootfs
mkdir -p /var/lib/lxc/vm/delta0

Note
1、lxc rpm packages build by command : rpmbuild -tb lxc-2.0.9.tar.gz
2、kernel 4.9.54-29.el7.x86_64 from CentOS-Xen repo

**Comment by brauner** [comment]
I pushed a patch to master and stable to fix this.
