### ISSUE TITLE
Python detection

### ISSUE THREAD

**Issue by kaithar** [lxc/lxc#187]
Pkg-config is being called with the opts `--exists --print-errors "python3 >= 3.2"` but that doesn't seem to be portable.  On Gentoo at least it's doing minor slotting, so we have python-3.2.pc and python-3.3.pc.

I bypassed it with `PYTHONDEV_CFLAGS=-I/usr/include/python3.2 PYTHONDEV_LIBS=-lpython3.2 ./configure`

**Comment by brauner** [comment]
Afaik, we're doing some `Python` detection now. If not, please reopen.
