### ISSUE TITLE
API: add console ringbuffer API extensions

### ISSUE THREAD

**Issue by brauner** [lxc/lxc#1870]
Since we merged the console ringbuffer implementation we now need at least two new API calls. For example:

- `console_get_ringbuffer()`
- `console_clear_ringbuffer()`

Or maybe just one `console_ringbuffer()`?

**Comment by brauner** [comment]
New API to get console log:

```
static char *do_lxcapi_console_get_log(struct lxc_container *c, size_t *len)
{
	return lxc_cmd_get_console_log(c->name, do_lxcapi_get_config_path(c), len);
}
```

The `len` argument can be used by the caller to restrict the size of the buffer that will be allocated. We need to decide whether length is taken to be relative to the start or end of the ringbuffer's current read offset.

`ringbuf.{c,h}`:

```
int lxc_ringbuf_read(struct lxc_ringbuf *buf, char **out, size_t *len)
{
	char *res;
	uint64_t used;

	/* there's nothing to read */
	if (buf->r_off == buf->w_off)
		return -ENODATA;

	/* read maximum amount available */
	used = lxc_ringbuf_used(buf);
	if (used < *len)
		*len = used;

	res = malloc(*len + 1);
	if (!res)
		return -ENOMEM;
	*out = res;

	/* copy data to reader but don't advance addr */
	memcpy(*out, lxc_ringbuf_get_read_addr(buf), *len);
	*out[*len] = '\0';
	return 0;
}

int lxc_ringbuf_read_move(struct lxc_ringbuf *buf, char **out, size_t *len)
{
	int ret;

	ret = lxc_ringbuf_read(buf, out, len);
	if (ret < 0)
		return ret;

	lxc_ringbuf_move_read_addr(buf, *len);
	return 0;
}
```

`command.{c,h}`:

```
char *lxc_cmd_get_console_log(const char *name, const char *lxcpath, size_t *len)
{
	int ret, stopped;
	struct lxc_cmd_rr cmd = {
		.req = { .cmd = LXC_CMD_GET_CONSOLE_LOG,
			 .data = &len,
			 .datalen = 0,
		       },
	};

	ret = lxc_cmd(name, &cmd, &stopped, lxcpath, NULL);
	if (ret < 0)
		return NULL;

	if (cmd.rsp.ret < 0)
		return NULL;

	*len = cmd.rsp.datalen;

	return cmd.rsp.data;
}

static int lxc_cmd_get_console_log_callback(int fd, struct lxc_cmd_req *req,
					    struct lxc_handler *handler)
{
	char *val;
	struct lxc_cmd_rsp rsp;
	size_t len = *(size_t *)req->data;
	struct lxc_ringbuf *buf = &handler->conf->console.ringbuf;

	rsp.ret = lxc_ringbuf_read_move(buf, &val, &len);
	rsp.data = val;
	rsp.datalen = len;
	return lxc_cmd_rsp_send(fd, &rsp);
}
```

**Comment by hallyn** [comment]
The only way to get or consume data is through the command api right?  So technically there isn't a need to do the malloc - you can just do the lxc_cmd_rsp_send() straight from the buffer itself?

**Comment by brauner** [comment]
Well, there's one problem currently. Namely that the amount of data we currently allow to send over the command socket is limited to:

    #define LXC_CMD_DATA_MAX (MAXPATHLEN * 2)

We should decide whether we want to remove that limit or just ignore it for the console log.

**Comment by hallyn** [comment]
That may be because the lxc_cmd_handler uses alloca(), and doesn't want to risk an overrun.

If so, then we could conditionally use malloc if the size is too big.

**Comment by brauner** [comment]
We somehow also should inform the caller that there's no new data available.

**Comment by brauner** [comment]
Basically a way for the caller to differentiate between failure and no data.
