### ISSUE TITLE
Problem during the restore part after an iterative migration

### ISSUE THREAD

**Issue by ramy150** [lxc/lxc#1894]
Dear all

I already put this on the criu repository and I was asking my self if my current lxc version doesn't affect the migration process. It seems that we have found a problem during the last part of the live migration (restore part). After longly investigating we observed that MySQL daemon ((mysqld) (mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper )) could be the source of the problem.

attached you can find all the collected information and log files:

Host1 information:
[host1_information.txt](https://github.com/checkpoint-restore/criu/files/1433759/host1_information.txt)

Host2 information:
[host2_information.txt](https://github.com/checkpoint-restore/criu/files/1433760/host2_information.txt)

container config file:
[config.txt](https://github.com/checkpoint-restore/criu/files/1433772/config.txt)

first pre-dump log file:
[pre-dump.log](https://github.com/checkpoint-restore/criu/files/1433761/pre-dump.log)

second pre-dump log file:
[pre-dump2.log](https://github.com/checkpoint-restore/criu/files/1433763/pre-dump2.log)

dump log file:
[dump.log](https://github.com/checkpoint-restore/criu/files/1433764/dump.log)

restore file:
[restore.log](https://github.com/checkpoint-restore/criu/files/1433765/restore.log)

Screen Shot before the migration process:
![runningprocesses](https://user-images.githubusercontent.com/22980151/32270844-21e9f470-bf00-11e7-8799-83d0e6c09330.png)

**Comment by stgraber** [comment]
LXC 3.x will have better CRIU handling, though in this case, the dump was successful so I'm not sure it'd be much different. The ability to restore the dump is almost exclusively on CRIU as LXC does pretty little at that stage.

In general, trying a newer version of CRIU is always a safe bet. That being said, we've not had good luck with modern systemd systems, too many new kernel features getting used that CRIU just can't handle yet.
