### ISSUE TITLE
lxc-attach fails when cgroup namespaces are unsupported

### ISSUE THREAD

**Issue by 3XX0** [lxc/lxc#1897]
On platforms where cgroup namespaces are unsupported (e.g. RHEL), `lxc-attach` fails as it tries to open `/proc/<pid>/ns/cgroup` unconditionally.

There is a check [here](https://github.com/lxc/lxc/blob/master/src/lxc/attach.c#L1131) but it doesn't prevent [lxc_attach_to_ns](https://github.com/lxc/lxc/blob/master/src/lxc/attach.c#L303) from trying to join the cgroup namespace

Here is the (ugly) workaround:
```diff
--- a/src/lxc/attach.c
+++ b/src/lxc/attach.c
@@ -314,6 +314,9 @@ static int lxc_attach_to_ns(pid_t pid, int which)
        for (i = 0; i < LXC_NS_MAX; i++) {
                fd[i] = -EINVAL;
 
+               if (ns_info[i].clone_flag == CLONE_NEWCGROUP && !cgns_supported())
+                       continue;
+
                /* Ignore if we are not supposed to attach to that namespace. */
                if (which != -1 && !(which & ns_info[i].clone_flag)) {
                        /* We likely inherited the namespace from someone. We
```

**Comment by brauner** [comment]
Should be fixed by https://github.com/lxc/lxc/pull/1893 .
