### ISSUE TITLE
OCI template doesn't actually support "--url"

### ISSUE THREAD

**Issue by flx42** [lxc/lxc#1898]
```
$ lxc-create -t oci -n xenial -- --url docker://ubuntu:xenial
getopt: unrecognized option '--url'
```
But `-u` works.

Just need to add `url:` here:
https://github.com/lxc/lxc/blob/190f9aeedcc73753428fdaf5178ee5d16ab840d2/templates/lxc-oci.in#L121-L122

**Comment by hallyn** [comment]
Oops. Do you mind posting a pull request?

**Comment by flx42** [comment]
Will do, just need corporate approval (for this + other patches we plan to do with @3XX0)

**Comment by brauner** [comment]
@flx42, cool!

**Comment by flx42** [comment]
#1914
