### ISSUE TITLE
LVM default file system is documented as ext4 by default, but actually creates ext3

### ISSUE THREAD

**Issue by tomponline** [lxc/lxc#1899]
LXC 2.1.1
Debian 6 64bit.

When creating a container with lxc-create using LVM, the default filesystem is supposed to be ext4 as per the docs:

https://github.com/lxc/lxc/blob/18000bb3a3cd9b647c6ceb2915e5d8f962f402ee/doc/lxc-create.sgml.in#L153

However the actual filesystem is created as ext3, and is per the code:

https://github.com/lxc/lxc/blob/42f055d0f6aef0861593bc01cc6cfa424aaa0f7e/src/lxc/storage/storage.h#L64

Also, the command line docs are out of date and still say ext3:

https://github.com/lxc/lxc/blob/70cc6755544d743e614a43e79ff4cb86669f8979/src/lxc/tools/lxc_create.c#L166

**Comment by brauner** [comment]
Oh, I thought I had sent a patch for this a while back. Will do now.

**Comment by tomponline** [comment]
thanks @brauner i discovered this yesterday, as MariaDB's Debian packages have a bug in them where they dont run on ext3, but they do run on ext4. Converting my container from ext3 to ext4 sorted the issue :) https://jira.mariadb.org/browse/MDEV-14244

**Comment by tomponline** [comment]
thanks!
