### ISSUE TITLE
Debian 9 dirmngr doesn't shutdown with lxc-stop, leaves file system in use after container has stopped

### ISSUE THREAD

**Issue by tomponline** [lxc/lxc#1900]
LXC 2.1.1
Debian 9 64bit

Running GPG's dirmng inside a container, when using lxc-stop to shutdown the container, the process doesn't stop, and is left running under the host's process tree.

This leaves the container's filesystem "in use" and means it can't be destroyed.

Extract from ps:
```
1258512   1590  0.0  0.2 126808  8904 ?        Ss   12:58   0:00 dirmngr --daemon --homedir /tmp/tmp.IK8TuVWzYr/gpg
```

Resolution: On host

```
killall dirmngr
```

**Comment by brauner** [comment]
There's nothing that LXC can really do I think. The easiest option is to configure `dirmngr` such that it doesn't keep hanging around. Unless you have another idea.

**Comment by tomponline** [comment]
Doesnt that mean that dirmngr is 'escaping' back to the host's process after the container has ended?

Should processes created inside a container be killed when a container is stopped?

**Comment by brauner** [comment]
No, dirmngr just holds a reference to the rootfs of the container that's why it can't be destroyed. It's running on the host the whole time.

**Comment by tomponline** [comment]
Ahh ok, do you know why dirmngr has opened something on the container's LVM filesystem?

AFAIK its something to do with GPG keys?

**Comment by brauner** [comment]
@tomponline, well `dirmngr` is invoked as the unprivileged container user during container creation to download the gpg keys iirc.

**Comment by tomponline** [comment]
@brauner yes thats correct, although it seems to hang around after container creation, and then also keep a file open on the lvm volume.

**Comment by tomponline** [comment]
@brauner i was looking at a similar issue here, i think its relevant:

https://dev.gnupg.org/T2858

Sounds like it would be worth adding a call to "gpgconf --kill dirmngr" after using gpg at container create time.

**Comment by brauner** [comment]
Yeah, but I'm not sure we should do that in our scripts though since we might annoy users by killing `dirmngr` session they have running. /cc @stgraber
