### ISSUE TITLE
lxc-destroy --quiet acts like --force

### ISSUE THREAD

**Issue by calder** [lxc/lxc#1905]
# Issue description

In `lxc_destroy.c`, passing the `--quiet` flag causes the container to be killed if it's running, just as if `--force` had been passed.

https://github.com/lxc/lxc/blob/70cc6755544d743e614a43e79ff4cb86669f8979/src/lxc/tools/lxc_destroy.c#L183-L190

# Suggested fix

```c
	if (c->is_running(c)) {
		if (!my_args.force) {
			if (!quiet) {
				fprintf(stderr, "%s is running\n", my_args.name);
			}
			return false;
		}
		/* If the container was ephemeral it will be removed on shutdown. */
		c->stop(c);
	}
```

**Comment by brauner** [comment]
@Calder, can you send a signed-off PR with the suggested fix, please?

**Comment by brauner** [comment]
We can't include the code without a signed-off by so please send it as a pr.
