### ISSUE TITLE
lxc-copy -s with BTRFS on LVM uses same rootfs on original and snapshot

### ISSUE THREAD

**Issue by bhelm** [lxc/lxc#1909]
* Distribution: Debian
 * Distribution version: 9
 * The output of
   * `lxc-start --version` 2.0.7
   * `lxc-checkconfig`
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.9.0-4-amd64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled
--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: enabled
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled
FUSE (for use with lxcfs): enabled
--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled
   * `uname -a`
Linux vps464623 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
10:memory:/user/root/0
9:blkio:/system.slice/ssh.service
8:pids:/system.slice/ssh.service
7:freezer:/user/root/0
6:cpu,cpuacct:/system.slice/ssh.service
5:perf_event:/
4:devices:/system.slice/ssh.service
3:cpuset:/
2:net_cls,net_prio:/
1:name=systemd:/user/root/0
   * `cat /proc/1/mounts`
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=12044348k,nr_inodes=3011087,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=2411280k,mode=755 0 0
/dev/sda2 / btrfs rw,relatime,ssd,discard,space_cache,subvolid=5,subvol=/ 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=33,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=10783 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,relatime 0 0
# Issue description

When cloning a container using lvm snapshot, both containers seem to share the same volume. i.e. i can create a file in one and see it on the other.

# Steps to reproduce

i created an image based on -t download debian stretch, lvm as backend and btrfs as filesystem.

Here is my log:

```
root@vps464623:~# lxc-ls -f
NAME      STATE   AUTOSTART GROUPS IPV4 IPV6 
baselinux STOPPED 0         -      -    -    
ris       STOPPED 0         -      -    -    
root@vps464623:~# lxc-start -n ris
root@vps464623:~# lxc-attach -n ris
root@ris:~# ls
root@ris:~# df /
Filesystem     1K-blocks   Used Available Use% Mounted on
/dev/main/ris    1048576 364812    606676  38% /
root@ris:~# exit
exit
root@vps464623:~# lxc-stop -n ris
root@vps464623:~# lxc-ls -f
NAME      STATE   AUTOSTART GROUPS IPV4 IPV6 
baselinux STOPPED 0         -      -    -    
ris       STOPPED 0         -      -    -    
root@vps464623:~# lxc-copy -n ris -N ris2 -s          
  Using default stripesize 64.00 KiB.
  Logical volume "ris2" created.
root@vps464623:~# lvdisplay 
  --- Logical volume ---
  LV Path                /dev/main/baselinux
  LV Name                baselinux
  VG Name                main
  LV UUID                0GHhph-ZiMt-JrYz-a6Rd-S5CU-iK0d-Iesu5i
  LV Write Access        read/write
  LV Creation host, time vps464623, 2017-11-07 14:31:13 +0100
  LV Status              available
  # open                 0
  LV Size                1.00 GiB
  Current LE             256
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           254:1
   
  --- Logical volume ---
  LV Path                /dev/main/ris
  LV Name                ris
  VG Name                main
  LV UUID                5isq5h-5j83-Oa7G-gGrR-5P7S-ukoC-tAQAuh
  LV Write Access        read/write
  LV Creation host, time vps464623, 2017-11-08 10:17:47 +0100
  LV snapshot status     source of
                         ris2 [active]
  LV Status              available
  # open                 0
  LV Size                1.00 GiB
  Current LE             256
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           254:0
   
  --- Logical volume ---
  LV Path                /dev/main/ris2
  LV Name                ris2
  VG Name                main
  LV UUID                Qi3dH7-rxQC-0lNt-ggWW-RPOZ-zPhB-GXEanH
  LV Write Access        read/write
  LV Creation host, time vps464623, 2017-11-08 10:54:11 +0100
  LV snapshot status     active destination for ris
  LV Status              available
  # open                 0
  LV Size                1.00 GiB
  Current LE             256
  COW-table size         1.00 GiB
  COW-table LE           256
  Allocated to snapshot  0.06%
  Snapshot chunk size    4.00 KiB
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           254:4
   
root@vps464623:~# lxc-ls -f
NAME      STATE   AUTOSTART GROUPS IPV4 IPV6 
baselinux STOPPED 0         -      -    -    
ris       STOPPED 0         -      -    -    
ris2      STOPPED 0         -      -    -    
root@vps464623:~# lxc-start -n ris -l DEBUG -o ris.log
root@vps464623:~# lxc-start -n ris2 -l DEBUG -o ris2.log
root@vps464623:~# lxc-ls -f
NAME      STATE   AUTOSTART GROUPS IPV4          IPV6 
baselinux STOPPED 0         -      -             -    
ris       RUNNING 0         -      192.168.34.20 -    
ris2      RUNNING 0         -      -             -    
root@vps464623:~# lxc-ls -f
NAME      STATE   AUTOSTART GROUPS IPV4          IPV6 
baselinux STOPPED 0         -      -             -    
ris       RUNNING 0         -      192.168.34.20 -    
ris2      RUNNING 0         -      192.168.34.22 -    
root@vps464623:~# lxc-attach -n ris
root@ris:~# df /
Filesystem     1K-blocks   Used Available Use% Mounted on
/dev/main/ris2   1048576 364816    606672  38% /
root@ris:~# touch this_is_1
root@ris:~# ls
this_is_1
root@ris:~# exit
exit
root@vps464623:~# lxc-attach -n ris2
root@ris:~# ls
this_is_1
root@ris:~# df /
Filesystem     1K-blocks   Used Available Use% Mounted on
/dev/main/ris2   1048576 364816    606672  38% /
root@ris:~# exit
exit
```
so the filesystems of ris and ris2 are the same somehow.
i can create files in one and see them live on the other
both appear to have /dev/main/ris2 mounted
both call themself "ris" as hostname

[ris.log](https://github.com/lxc/lxc/files/1453376/ris.log)
[ris2.log](https://github.com/lxc/lxc/files/1453379/ris2.log)
[ris_config.txt](https://github.com/lxc/lxc/files/1453388/ris_config.txt)
[ris2_config.txt](https://github.com/lxc/lxc/files/1453392/ris2_config.txt)

**Comment by bhelm** [comment]
btrfs is able to cleanly mount a single filesystem at two mountpoints and this is what i think happens here.
using blkid i can see that both, original and snapshot, have the same UUID (as expected):
/dev/mapper/main-ris: UUID="2c5967de-07b6-44b0-9d03-b10d4617b23a" UUID_SUB="003df3dd-3c3f-49fd-b8ce-ed7c1c16e981" TYPE="btrfs"
/dev/mapper/main-ris2: UUID="2c5967de-07b6-44b0-9d03-b10d4617b23a" UUID_SUB="003df3dd-3c3f-49fd-b8ce-ed7c1c16e981" TYPE="btrfs"

i used btrfstune -u /dev/mapper/main-ris2 to change the UUID and the snapshot now works as expected.

**Comment by brauner** [comment]
Send a branch that should take care of generating new UUIDs for `xfs` and `btrfs` on lvm ( https://github.com/lxc/lxc/pull/1922 ) .
