### ISSUE TITLE
No output in foreground mode

### ISSUE THREAD

**Issue by coconut30** [lxc/lxc#1921]
# Required information

 * Distribution: debian
 * Distribution version: 9.2
 * The output of
   * `lxc-start --version`   
      2.0.7
   * `lxc-checkconfig`   
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.9.0-4-amd64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: enabled
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
   * `uname -a`   
Linux foo 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
   * `cat /proc/self/cgroup`   
10:memory:/user/foo/0
9:cpuset:/user/foo/0
8:perf_event:/
7:pids:/user.slice/user-166536.slice/user@166536.service
6:net_cls,net_prio:/
5:freezer:/user/foo/0
4:blkio:/user.slice
3:devices:/user.slice
2:cpu,cpuacct:/user.slice
1:name=systemd:/user.slice/user-166536.slice/user@166536.service/gnome-terminal-server.service
   * `cat /proc/1/mounts`
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=7995908k,nr_inodes=1998977,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=1601668k,mode=755 0 0
/dev/mapper/vg_system-lv_root / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs rw,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids,release_agent=/run/cgmanager/agents/cgm-release-agent.pids 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event,release_agent=/run/cgmanager/agents/cgm-release-agent.perf_event 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=41,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=12660 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
/dev/mapper/vg_system-lv_home /home ext4 rw,relatime,data=ordered 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
tmpfs /run/user/117 tmpfs rw,nosuid,nodev,relatime,size=1601664k,mode=700,uid=117,gid=121 0 0
tmpfs /run/user/166536 tmpfs rw,nosuid,nodev,relatime,size=1601664k,mode=700,uid=166536,gid=166536 0 0
gvfsd-fuse /run/user/166536/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=166536,group_id=166536 0 0   

# Issue description

When a container is started in foreground mode, there is no output and the shell freeze, but I can attach or ssh to it in another shell. Then lxc-stop give me back the shell freezed.

# Steps to reproduce

 1. lxc-start -n base -F

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [x ] container log (The <log> file from running `lxc-start -n <c> -F -l <log> -o DEBUG`)
[base_debug_log.txt](https://github.com/lxc/lxc/files/1466133/base_debug_log.txt)
 - [x ] the containers configuration file
[config.txt](https://github.com/lxc/lxc/files/1466097/config.txt)

**Comment by brauner** [comment]
What Debian are you running inside the container. This sounds like systemd not behaving correctly.

**Comment by coconut30** [comment]
Inside the container it's debian 9.1.

**Comment by brauner** [comment]
Hm, likely caused by cgroup v2 issues. `2.0.7` is not able to handle this correctly. Can you reproduce this with `LXC 2.1.*`?

**Comment by coconut30** [comment]
Same issue with lxc 2.1.1, the output of lxc-start -n base -F is empty. And in 2.1.1 when i stop the container, i have this message:   
   
lxc-stop: base: commands_utils.c: lxc_cmd_sock_rcv_state: 71 failed to receive message: Resource temporarily unavailable
lxc-stop: base: commands.c: lxc_cmd_rsp_recv: 157 Command stop response data 1702060386 too long.

**Comment by brauner** [comment]
Can you show `ps auxf` from inside the container when you've attached to it, please.

**Comment by coconut30** [comment]
This is the result of the command:
root@base:/# ps auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        59  0.0  0.0  19828  3512 ?        Ss   16:35   0:00 /bin/bash
root        60  0.0  0.0  38304  3188 ?        R+   16:35   0:00  \_ ps auxf
root         1  0.5  0.0  56804  6632 ?        Ss   16:35   0:00 /sbin/init
root        15  0.2  0.0  46092  6708 ?        Ss   16:35   0:00 /lib/systemd/systemd-journald
message+    42  0.0  0.0  45132  3780 ?        Ss   16:35   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
root        47  0.0  0.0  37980  2140 ?        Ss   16:35   0:00 /lib/systemd/systemd-logind
root        55  0.0  0.0  69944  5472 ?        Ss   16:35   0:00 /usr/sbin/sshd -D
root        57  0.0  0.0  14496  2068 ?        Ss   16:35   0:00 /sbin/agetty --noclear --keep-baud console 115200,38400,9600 vt220

**Comment by brauner** [comment]
Can you maybe show a screenshot or asciinema of the `lxc-start -n <container-name> -F` command, please.

**Comment by coconut30** [comment]
https://asciinema.org/a/4N0QVjIsWhMxoktFF8V3NuW6o

At 50s, I launch lxc-stop command on another shell.

**Comment by brauner** [comment]
Hm, can you show:

    cat /proc/1/mountinfo

from inside the container and the ouput of `umask` on the host, please.

**Comment by coconut30** [comment]
Here the result of cat /proc/1/mountinfo inside the container:   
root@base:/# cat /proc/1/mountinfo 
347 245 254:2 /brenault/.local/share/lxc/base/rootfs / rw,relatime master:26 - ext4 /dev/mapper/vg_system-lv_home rw,data=ordered
348 347 0:54 / /dev rw,relatime - tmpfs none rw,size=492k,mode=755,uid=166536,gid=166536
349 347 0:53 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
350 351 0:53 /sys/net /proc/sys/net rw,nosuid,nodev,noexec,relatime - proc proc rw
351 349 0:53 /sys /proc/sys ro,nosuid,nodev,noexec,relatime - proc proc rw
352 349 0:53 /sysrq-trigger /proc/sysrq-trigger ro,nosuid,nodev,noexec,relatime - proc proc rw
353 347 0:55 / /sys rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
354 353 0:55 / /sys ro,nosuid,nodev,noexec,relatime - sysfs sysfs rw
355 354 0:55 / /sys/devices/virtual/net rw,relatime - sysfs sysfs rw
356 355 0:55 /devices/virtual/net /sys/devices/virtual/net rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
357 354 0:41 / /sys/fs/fuse/connections rw,relatime master:163 - fusectl fusectl rw
358 348 0:6 /null /dev/null rw,nosuid,relatime master:2 - devtmpfs udev rw,size=7995908k,nr_inodes=1998977,mode=755
359 348 0:6 /zero /dev/zero rw,nosuid,relatime master:2 - devtmpfs udev rw,size=7995908k,nr_inodes=1998977,mode=755
360 348 0:6 /full /dev/full rw,nosuid,relatime master:2 - devtmpfs udev rw,size=7995908k,nr_inodes=1998977,mode=755
361 348 0:6 /urandom /dev/urandom rw,nosuid,relatime master:2 - devtmpfs udev rw,size=7995908k,nr_inodes=1998977,mode=755
362 348 0:6 /random /dev/random rw,nosuid,relatime master:2 - devtmpfs udev rw,size=7995908k,nr_inodes=1998977,mode=755
363 348 0:6 /tty /dev/tty rw,nosuid,relatime master:2 - devtmpfs udev rw,size=7995908k,nr_inodes=1998977,mode=755
364 348 0:18 /2 /dev/console rw,nosuid,noexec,relatime master:3 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
246 348 0:56 / /dev/pts rw,relatime - devpts devpts rw,gid=166541,mode=620,ptmxmode=666,max=1024
247 348 0:56 /ptmx /dev/ptmx rw,relatime - devpts devpts rw,gid=166541,mode=620,ptmxmode=666,max=1024
248 348 0:56 /0 /dev/tty1 rw,relatime - devpts devpts rw,gid=166541,mode=620,ptmxmode=666,max=1024
249 348 0:56 /1 /dev/tty2 rw,relatime - devpts devpts rw,gid=166541,mode=620,ptmxmode=666,max=1024
250 348 0:56 /2 /dev/tty3 rw,relatime - devpts devpts rw,gid=166541,mode=620,ptmxmode=666,max=1024
251 348 0:56 /3 /dev/tty4 rw,relatime - devpts devpts rw,gid=166541,mode=620,ptmxmode=666,max=1024
252 348 0:57 / /dev/shm rw,nosuid,nodev - tmpfs tmpfs rw,uid=166536,gid=166536
253 347 0:58 / /run rw,nosuid,nodev - tmpfs tmpfs rw,mode=755,uid=166536,gid=166536
286 253 0:59 / /run/lock rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,size=5120k,uid=166536,gid=166536
287 354 0:60 / /sys/fs/cgroup rw,nosuid,nodev,noexec - tmpfs tmpfs rw,mode=755,uid=166536,gid=166536
288 287 0:23 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
289 287 0:27 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,blkio
290 287 0:29 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,net_cls,net_prio
291 287 0:30 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,pids,release_agent=/run/cgmanager/agents/cgm-release-agent.pids
292 287 0:32 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuset,clone_children
293 287 0:33 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,memory
294 287 0:28 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,freezer
295 287 0:31 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,perf_event,release_agent=/run/cgmanager/agents/cgm-release-agent.perf_event
297 287 0:25 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpu,cpuacct
302 287 0:26 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,devices
333 348 0:52 / /dev/mqueue rw,relatime - mqueue mqueue rw   
   
And umask on the host:   
brenault@brenault:~$ umask 
0022

**Comment by brauner** [comment]
Can you please do:

    tty

in the current shell and show the output here. Then in the same shell issue:

    lxc start -n <container> -F

then in another shell show the output of:

    ls -al /dev/pts/

**Comment by coconut30** [comment]
In the first shell:   
tty
/dev/pts/0
   
In a another shell after lxc-start -n base -F on the first shell:   
ls -al /dev/pts
total 0
drwxr-xr-x  2 root     root      0 nov.  13 09:24 .
drwxr-xr-x 21 root     root   3680 nov.  13 09:24 ..
crw--w----  1 brenault tty  136, 0 nov.  14 13:52 0
c--x--x--x  1 brenault tty  136, 1 nov.  13 16:29 1
c--x--x--x  1 brenault tty  136, 2 nov.  14 13:52 2
crw--w----  1 brenault tty  136, 3 nov.  14 13:52 3
c---------  1 root     root   5, 2 nov.  13 09:24 ptmx

**Comment by brauner** [comment]
Ha, I see what the problem is I think. The pty is not chowned to your unprivileged container user so you can't write to it. So there's a bug in `chown_mapped_root()` I guess.

**Comment by brauner** [comment]
What does:

    id -u
    id -u -r

show you?

**Comment by coconut30** [comment]
```
brenault@brenault:~$ id -u
166536 
```  
```
brenault@brenault:~$ id -u -r
166536
```

**Comment by brauner** [comment]
It seems that somehow you end up in a situation where `liblxc` detects that it doesn't need to chown the pty device since the uid the container runs with for it's root mapping is you uid. The only way I can see this happening is when your effective user id is different from your real user id or when your uid is part of the mapping.

**Comment by brauner** [comment]
That's interesting. Why do you have that uid?

**Comment by brauner** [comment]
Hm, what happens if you do:

```
chown $(id -u):$(id -g) /dev/pts/<idx>
```

and press enter a couple of times in the shell where the container command is running?

**Comment by coconut30** [comment]
Long story short, I have this uid because I want my uid of the user brenault on my host match uid of the root user inside the container.
If I do
   
`chown $(id -u):$(id -g) /dev/pts/0
`
   
on the shell where the `lxc-start -n base -F` is running, nothing happens.

**Comment by coconut30** [comment]
I have not the issue with a user with uid = 1001 and an idmap like this:
lxc.idmap = u 0 232072 65536
lxc.idmap = g 0 232072 65536

**Comment by brauner** [comment]
Uhm, you can achieve the same by just setting up a custom idmapping for you uid. So if you had the standard uid `1000` just add to `/etc/sub{g,u}id`:

`brenault:1000:1`

and then configure your mapping template in `~/.local/share/lxc/config` to include:

```
lxc.id_map = u 1 166536 65536
lxc.id_map = u 0 1000 1
lxc.id_map = g 1 166536 65536
lxc.id_map = u 0 1000 1
```

**Comment by brauner** [comment]
Do you use `setuid()` somehow or is your `uid` actually by default `165536` on your system?

**Comment by coconut30** [comment]
166536 is my default uid for user brenault on this system

**Comment by coconut30** [comment]
So, I have the issue because of my container root user uid is mapped to my host user uid

**Comment by brauner** [comment]
Well, actually I'm not managing to reproduce this here and I wonder what brings this about. I need to debug this further.

**Comment by stgraber** [comment]
Is that issue still happening with recent LXC?
