### ISSUE TITLE
resolve.conf Permission Denied in archlinux template

### ISSUE THREAD

**Issue by heroxbd** [lxc/lxc#1927]
In comment 137162e84759b9e172ff8e563170bd4f274ff3a3 Stéphane Graber has introduced `systemd-resolved` and used `ln -sf` to overwrite `/etc/resolv.conf` in the container.

This induces permission denied error because now the newest [arch-chroot](https://git.archlinux.org/arch-install-scripts.git/tree/arch-chroot.in#n42) bind mounts resolv.conf from the host with `chroot_add_mount /etc/resolv.conf "$resolv_conf" --bind`.

**Comment by brauner** [comment]
Are you up for writing a patch to fix this if this is still an issue?
