### ISSUE TITLE
Error occured during container creation /usr/share/lxc/templates/lxc-sles is /usr/share/lxc/templates/lxc-sles

### ISSUE THREAD

**Issue by kuncao** [lxc/lxc#1976]
Hello every gurus
I have a issue when create lxc container in suse 11sp3,the following is the detail:
1 os infor
uname -a
Linux controller-10-179-179-43 3.0.76-0.11-default #1 SMP Fri Jun 14 08:21:43 UTC 2013 (ccab990) x86_64 x86_64 x86_64 GNU/Linux
cat /etc/issue
Welcome to SUSE Linux Enterprise Server 11 SP3  (x86_64) - Kernel \r (\l).
2 lxc version
rpm -qa | grep lxc
lxc-0.8.0-0.15.15
yast2-lxc-2.17.7-0.7.18
3 issue
when  create lxc container with YaST(refer https://www.suse.com/documentation/sles11/book_quickstarts/data/sec_lxc_setup_yast.html)
the error occur:
Error  
Error occured during container creation:
/usr/share/lxc/templates/lxc-sles is /usr/share/lxc/templates/lxc-sles
Checking cache download in /var/cache/lxc/sles/rootfs-x86_64 ...
Downloading sles minimal ...
File 'repomd.xml' from repository 'suse11sp3' is unsigned, continue? [yes/no] (no): no
Please insert medium [] #1 and type 'y' to continue or 'n' to cancel the operation. [yes/no] (no): no
Warning: The metadata cache needs to be built for the 'SUSE-Linux-Enterprise-Server-11-SP3 11.3.3-1.138' repository. You can run 'zypper refresh' as root to do this.
File 'repomd.xml' from repository 'suse11sp3' is unsigned, continue? [yes/no] (no): no
Warning: The metadata cache needs to be built for the 'suse11sp3' repository. You can run 'zypper refresh' as root to do this.
Please insert medium [] #1 and type 'y' to continue or 'n' to cancel the operation. [yes/no] (no): no
Warning: The metadata cache needs to be built for the 'SUSE-Linux-Enterprise-Server-11-SP3 11.3.3-1.138' repository. You can run 'zypper refresh' as root to do this.
File 'repomd.xml' from repository 'suse11sp3' is unsigned, continue? [yes/no] (no): no
Warning: The metadata cache needs to be built for the 'suse11sp3' repository. You can run 'zypper refresh' as root to do this.
Failed to download the rootfs, aborting.
Failed to download 'sles base'
failed to install sles

even after run zypper refresh
can not resolve the issue

please help to give some advise
thanks a  lot

**Comment by brauner** [comment]
Uhm, this is `lxc-0.8.0`, this is pre our first LTS release which was `1.0.0` and not supported anymore from our side. Also, this is SUSE specific template so I can't even say what is going wrong where.

**Comment by kuncao** [comment]
@brauner 
Thanks a lot
I will try to install the latest lxc .

**Comment by brauner** [comment]
I'm not sure if there's anything we can do about this from our side since we can't really debug non-open-source templates. :) So closing for now but feel free to comment if you think we can help.
