### ISSUE TITLE
lxc-2.1.1 autogen.sh error occur

### ISSUE THREAD

**Issue by kuncao** [lxc/lxc#1978]
Hello gurus:
When run autogen.sh of lxc-2.1.1 ,there is error occur. The following is the detail info.
1 os infor
uname -a
Linux controller-10-179-179-43 3.0.76-0.11-default #1 SMP Fri Jun 14 08:21:43 UTC 2013 (ccab990) x86_64 x86_64 x86_64 GNU/Linux
cat /etc/issue
Welcome to SUSE Linux Enterprise Server 11 SP3 (x86_64) - Kernel \r (\l).
+ test -d autom4te.cache
+ rm -rf autom4te.cache
+ libtoolize
libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree.
+ aclocal -I config
configure.ac:259: warning: macro `AM_COND_IF' not found in library
configure.ac:274: warning: macro `AM_COND_IF' not found in library
configure.ac:288: warning: macro `AM_COND_IF' not found in library
configure.ac:303: warning: macro `AM_COND_IF' not found in library
configure.ac:321: warning: macro `AM_COND_IF' not found in library
configure.ac:372: warning: macro `AM_COND_IF' not found in library
configure.ac:410: warning: macro `AM_COND_IF' not found in library
configure.ac:421: warning: macro `AM_COND_IF' not found in library
configure.ac:483: warning: macro `AM_COND_IF' not found in library
configure.ac:498: warning: macro `AM_COND_IF' not found in library
+ autoheader
+ autoconf
configure.ac:24: error: possibly undefined macro: AC_SUBST
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:52: error: possibly undefined macro: AC_MSG_CHECKING
configure.ac:99: error: possibly undefined macro: AC_MSG_RESULT
configure.ac:150: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:255: error: possibly undefined macro: AC_CHECK_LIB
configure.ac:259: error: possibly undefined macro: AM_COND_IF
configure.ac:260: error: possibly undefined macro: AC_CHECK_HEADER
configure.ac:304: error: possibly undefined macro: PKG_CHECK_MODULES
configure.ac:333: error: possibly undefined macro: AC_DEFINE
configure.ac:411: error: possibly undefined macro: AM_PATH_PYTHON
configure.ac:413: error: possibly undefined macro: AC_DEFINE_UNQUOTED
configure.ac:434: error: possibly undefined macro: PKG_CHECK_VAR
+ exit 1
Please help to give some advice.
Thanks a lot

**Comment by marcosps** [comment]
@kuncao do you have libtool, autogen, autotools and autoconf installed in your environment? If you don't, please install these packages and try again.

**Comment by kuncao** [comment]
zypper install -y libtool
Loading repository data...
Reading installed packages...
'libtool' is already installed.
No update candidate for 'libtool-2.2.6-2.131.1.x86_64'. The highest available version is already installed.
Resolving package dependencies...
zypper install -y  autogen
Loading repository data...
Reading installed packages...
'autogen' not found in package names. Trying capabilities.
No provider of 'autogen' found.
zypper install -y  autotools
Loading repository data...
Reading installed packages...
'autotools' not found in package names. Trying capabilities.
No provider of 'autotools' found.
zypper install -y  autoconf
Loading repository data...
Reading installed packages...
'autoconf' is already installed.
No update candidate for 'autoconf-2.63-1.158.x86_64'. The highest available version is already installed.
Resolving package dependencies...

**Comment by kuncao** [comment]
when install lxc 2.1.1 in suse 12 sp2,  there is no error
after export LD_LIBRARY_PATH evn ,lxc is ok.
export LD_LIBRARY_PATH=:/usr/local/lib:/usr/lib:/lib
controller-10-179-193-97:~ # echo $LD_LIBRARY_PATH
:/usr/local/lib:/usr/lib:/lib
controller-10-179-193-97:~ # lxc-create --version
2.1.1

**Comment by kuncao** [comment]
thanks all
