### ISSUE TITLE
lxc-attach seems broken when lxc-start has been used with --shared-net [PID]

### ISSUE THREAD

**Issue by p-l-** [lxc/lxc#1985]
Hi,

I've noticed that `lxc-attach` creates a shell that is not in the container's netns when `lxc-start` has been used with `--shared-net [PID]`.

# Required information

 * Distribution: ArchLinux
 * The output of
   * `lxc-start --version` 2.1.1
   * `lxc-checkconfig`
```
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: missing
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/devices
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/pids
/sys/fs/cgroup/memory
/sys/fs/cgroup/blkio
/sys/fs/cgroup/freezer
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/perf_event

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loadedCONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

```
   * `uname -a`: `Linux server 4.12.8-2-ARCH #1 SMP PREEMPT Fri Aug 18 14:08:02 UTC 2017 x86_64 GNU/Linux`

# Issue description

When using `lxc-start` with option `--shared-net [PID]`, the container starts in the expected netns. But when one run `lxc-attach` to the container, the shell is not in the netns, except when using `-s NETWORK`.

# Steps to reproduce

 1. Create a netns, and exec a shell in that netns, list the network interfaces, get the shell's PID (and leave the shell running):
```
# ip netns add test
# ip netns exec test /bin/bash
# ip link show
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
# echo $$
11962
```

 2. List the PIDs in the netns, create and start a container sharing the shell's netns, list the PIDs in the netns.
```
# ip netns pids test
11962
# lxc-create --name test --template archlinux
[...]
# lxc-start --name test --share-net 11962
# ip netns pids test
11962
[... 19 other PIDs]
```

As expected the containers's processes are in the `test` netns.

 3. Attach to the container and list the network interfaces, without `--namespaces`, then with `--namespaces NETWORK` 
```
# lxc-attach --name test
[root@test /]# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
[... all the host's network interfaces]
[root@test /]# exit
# lxc-attach --name test --namespaces NETWORK
# ip link show
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
```

I would expect that `lxc-attach` to create a shell in the same netns as the container without specifying `--namespaces NETWORK`.

**Comment by brauner** [comment]
This issue is fixed in master and will be included in the next set of stable and feature releases. If it is still reproducible in master please re-open.

**Comment by p-l-** [comment]
@brauner thanks and sorry, I should have checked with master before bothering you with that.

**Comment by brauner** [comment]
@p-l-, oh that's perfectly fine. So no worries. As I said, if you can reproduce with master just re-open or comment here.
