### ISSUE TITLE
LXC 2.0.9 + Kernel 4.14.0-1 =  Failed to mount rootfs (…) rootfs onto "/usr/lib/x86_64-linux-gnu/lxc/rootfs" with options "(null)".

### ISSUE THREAD

**Issue by ne0zer0** [lxc/lxc#1986]
# Required information

 * Distribution: Debian
 * Distribution version: Sid
 * The output of
   * `lxc-start --version` = 2.0.9

   * `lxc-checkconfig` =

> Kernel configuration not found at /proc/config.gz; searching...
> Kernel configuration found at /boot/config-4.14.0-1-amd64
> --- Namespaces ---
> Namespaces: enabled
> Utsname namespace: enabled
> Ipc namespace: enabled
> Pid namespace: enabled
> User namespace: enabled
> Network namespace: enabled
> 
> --- Control groups ---
> Cgroups: enabled
> 
> Cgroup v1 mount points: 
> /sys/fs/cgroup/systemd
> /sys/fs/cgroup/devices
> /sys/fs/cgroup/cpu,cpuacct
> /sys/fs/cgroup/freezer
> /sys/fs/cgroup/perf_event
> /sys/fs/cgroup/pids
> /sys/fs/cgroup/memory
> /sys/fs/cgroup/net_cls,net_prio
> /sys/fs/cgroup/cpuset
> /sys/fs/cgroup/blkio
> 
> Cgroup v2 mount points: 
> /sys/fs/cgroup/unified
> 
> Cgroup v1 clone_children flag: enabled
> Cgroup device: enabled
> Cgroup sched: enabled
> Cgroup cpu account: enabled
> Cgroup memory controller: enabled
> Cgroup cpuset: enabled
> 
> --- Misc ---
> Veth pair device: enabled, loaded
> Macvlan: enabled, not loaded
> Vlan: enabled, not loaded
> Bridges: enabled, not loaded
> Advanced netfilter: enabled, not loaded
> CONFIG_NF_NAT_IPV4: enabled, loaded
> CONFIG_NF_NAT_IPV6: enabled, loaded
> CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
> CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
> CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loadedCONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
> FUSE (for use with lxcfs): enabled, loaded
> 
> --- Checkpoint/Restore ---
> checkpoint restore: enabled
> CONFIG_FHANDLE: enabled
> CONFIG_EVENTFD: enabled
> CONFIG_EPOLL: enabled
> CONFIG_UNIX_DIAG: enabled
> CONFIG_INET_DIAG: enabled
> CONFIG_PACKET_DIAG: enabled
> CONFIG_NETLINK_DIAG: enabled
> File capabilities: enabled
> 
> Note : Before booting a new kernel, you can check its configuration
> usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -a` = Linux debian 4.14.0-1-amd64 #1 SMP Debian 4.14.2-1 (2017-11-30) x86_64 GNU/Linux

   * `cat /proc/self/cgroup`
> 10:blkio:/user.slice
> 9:cpuset:/
> 8:net_cls,net_prio:/
> 7:memory:/user/zero/0
> 6:pids:/user.slice/user-1000.slice/session-2.scope
> 5:perf_event:/
> 4:freezer:/user/zero/0
> 3:cpu,cpuacct:/user.slice
> 2:devices:/user.slice
> 1:name=systemd:/user.slice/user-1000.slice/session-2.scope
> 0::/user.slice/user-1000.slice/session-2.scope

   * `cat /proc/1/mounts`
   
> sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
> proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
> udev /dev devtmpfs rw,nosuid,relatime,size=7858044k,nr_inodes=1964511,mode=755 0 0
> devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
> tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=1574340k,mode=755 0 0
> /dev/mapper/sdd1_crypt / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
> securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
> tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
> tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
> tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
> cgroup /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
> cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
> pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
> cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
> cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
> cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
> cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
> cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
> cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
> cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
> cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
> cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
> systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=565 0 0
> mqueue /dev/mqueue mqueue rw,relatime 0 0
> debugfs /sys/kernel/debug debugfs rw,relatime 0 0
> /dev/sdd1 /boot ext4 rw,relatime,data=ordered 0 0
> /dev/mapper/sdd6_crypt /var ext4 rw,relatime,data=ordered 0 0
> /dev/mapper/sdd5_crypt /home ext4 rw,relatime,data=ordered 0 0
> /dev/mapper/sdd7_crypt /tmp ext4 rw,relatime,data=ordered 0 0
> /dev/mapper/sde5_crypt /var/log ext4 rw,relatime,data=ordered 0 0
> lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
> fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
> xenfs /proc/xen xenfs rw,relatime 0 0
> tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=1574336k,mode=700,uid=1000,gid=1000 0 0

# Issue description

Lxc unprivileged containers work great with linux-image-4.13.0-1-amd64.
But with Kernel 4.14.0-1-amd64, when trying to start any unprivileged containers, I get the output provided below.

# Steps to reproduce

 1. Use kernel 4.14.0-1
 2. start lxc-start -n devel
 3. see the output

# Information to attach

 - container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
>      lxc-start 20171202205306.551 INFO     lxc_start_ui - tools/lxc_start.c:main:277 - using rcfile /home/zero/.local/share/lxc/devel/config
>      lxc-start 20171202205306.581 WARN     lxc_confile - confile.c:set_config_pivotdir:2262 - lxc.pivotdir is ignored.  It will soon become an error.
>      lxc-start 20171202205306.606 INFO     lxc_confile - confile.c:set_config_idmaps:1861 - read uid map: type u nsid 0 hostid 1214112 range 1000
>      lxc-start 20171202205306.606 INFO     lxc_confile - confile.c:set_config_idmaps:1861 - read uid map: type g nsid 0 hostid 1214112 range 1000
>      lxc-start 20171202205306.606 INFO     lxc_confile - confile.c:set_config_idmaps:1861 - read uid map: type u nsid 1000 hostid 1000 range 1
>      lxc-start 20171202205306.606 INFO     lxc_confile - confile.c:set_config_idmaps:1861 - read uid map: type g nsid 1000 hostid 1000 range 1
>      lxc-start 20171202205306.606 INFO     lxc_confile - confile.c:set_config_idmaps:1861 - read uid map: type u nsid 1001 hostid 1215113 range 64535
>      lxc-start 20171202205306.606 INFO     lxc_confile - confile.c:set_config_idmaps:1861 - read uid map: type g nsid 1001 hostid 1215113 range 64535
>      lxc-start 20171202205306.613 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:877 - Attempting to set proc title to [lxc monitor] /home/zero/.local/share/lxc devel
>      lxc-start 20171202205306.620 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
>      lxc-start 20171202205306.625 INFO     lxc_seccomp - seccomp.c:parse_config_v2:435 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
>      lxc-start 20171202205306.625 INFO     lxc_seccomp - seccomp.c:parse_config_v2:610 - Adding native rule for reject_force_umount action 0(kill).
>      lxc-start 20171202205306.625 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:276 - Setting Seccomp rule to reject force umounts.
>      lxc-start 20171202205306.625 INFO     lxc_seccomp - seccomp.c:parse_config_v2:614 - Adding compat rule for reject_force_umount action 0(kill).
>      lxc-start 20171202205306.625 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:276 - Setting Seccomp rule to reject force umounts.
>      lxc-start 20171202205306.625 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:276 - Setting Seccomp rule to reject force umounts.
>      lxc-start 20171202205306.625 INFO     lxc_seccomp - seccomp.c:parse_config_v2:435 - processing: .[all].
>      lxc-start 20171202205306.625 INFO     lxc_seccomp - seccomp.c:parse_config_v2:435 - processing: .kexec_load errno 1.
>      lxc-start 20171202205306.625 INFO     lxc_seccomp - seccomp.c:parse_config_v2:610 - Adding native rule for kexec_load action 327681(errno).
>      lxc-start 20171202205306.625 INFO     lxc_seccomp - seccomp.c:parse_config_v2:614 - Adding compat rule for kexec_load action 327681(errno).
>      lxc-start 20171202205306.626 INFO     lxc_seccomp - seccomp.c:parse_config_v2:435 - processing: .open_by_handle_at errno 1.
>      lxc-start 20171202205306.626 INFO     lxc_seccomp - seccomp.c:parse_config_v2:610 - Adding native rule for open_by_handle_at action 327681(errno).
>      lxc-start 20171202205306.626 INFO     lxc_seccomp - seccomp.c:parse_config_v2:614 - Adding compat rule for open_by_handle_at action 327681(errno).
>      lxc-start 20171202205306.626 INFO     lxc_seccomp - seccomp.c:parse_config_v2:435 - processing: .init_module errno 1.
>      lxc-start 20171202205306.626 INFO     lxc_seccomp - seccomp.c:parse_config_v2:610 - Adding native rule for init_module action 327681(errno).
>      lxc-start 20171202205306.626 INFO     lxc_seccomp - seccomp.c:parse_config_v2:614 - Adding compat rule for init_module action 327681(errno).
>      lxc-start 20171202205306.626 INFO     lxc_seccomp - seccomp.c:parse_config_v2:435 - processing: .finit_module errno 1.
>      lxc-start 20171202205306.626 INFO     lxc_seccomp - seccomp.c:parse_config_v2:610 - Adding native rule for finit_module action 327681(errno).
>      lxc-start 20171202205306.626 INFO     lxc_seccomp - seccomp.c:parse_config_v2:614 - Adding compat rule for finit_module action 327681(errno).
>      lxc-start 20171202205306.626 INFO     lxc_seccomp - seccomp.c:parse_config_v2:435 - processing: .delete_module errno 1.
>      lxc-start 20171202205306.626 INFO     lxc_seccomp - seccomp.c:parse_config_v2:610 - Adding native rule for delete_module action 327681(errno).
>      lxc-start 20171202205306.626 INFO     lxc_seccomp - seccomp.c:parse_config_v2:614 - Adding compat rule for delete_module action 327681(errno).
>      lxc-start 20171202205306.626 INFO     lxc_seccomp - seccomp.c:parse_config_v2:624 - Merging in the compat Seccomp ctx into the main one.
>      lxc-start 20171202205306.627 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
>      lxc-start 20171202205306.627 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
>      lxc-start 20171202205306.627 INFO     lxc_conf - conf.c:run_script_argv:398 - Executing script "/home/zero/.local/share/lxc/devel/setup-pulse.sh" for container "devel", config section "lxc".
>      lxc-start 20171202205306.758 DEBUG    lxc_conf - conf.c:run_buffer:370 - Script /home/zero/.local/share/lxc/devel/setup-pulse.sh devel lxc pre-start with output: 22.
>      lxc-start 20171202205306.765 DEBUG    lxc_start - start.c:setup_signal_fd:288 - Set SIGCHLD handler with file descriptor: 7.
>      lxc-start 20171202205306.773 DEBUG    console - console.c:lxc_console_peer_default:450 - process does not have a controlling terminal
>      lxc-start 20171202205306.773 DEBUG    lxc_conf - conf.c:chown_mapped_root:2830 - trying to chown "/dev/pts/1" to 1000
>      lxc-start 20171202205306.133 INFO     lxc_start - start.c:lxc_init:677 - container "devel" is initialized
>      lxc-start 20171202205306.134 DEBUG    lxc_start - start.c:__lxc_start:1501 - Not dropping CAP_SYS_BOOT or watching utmp.
>      lxc-start 20171202205306.134 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:67 - cgroup driver cgroupfs-ng initing for devel
>      lxc-start 20171202205306.135 INFO     lxc_start - start.c:lxc_spawn:1324 - Cloned CLONE_NEWUSER.
>      lxc-start 20171202205306.135 INFO     lxc_start - start.c:lxc_spawn:1324 - Cloned CLONE_NEWNS.
>      lxc-start 20171202205306.135 INFO     lxc_start - start.c:lxc_spawn:1324 - Cloned CLONE_NEWPID.
>      lxc-start 20171202205306.135 INFO     lxc_start - start.c:lxc_spawn:1324 - Cloned CLONE_NEWUTS.
>      lxc-start 20171202205306.135 INFO     lxc_start - start.c:lxc_spawn:1324 - Cloned CLONE_NEWIPC.
>      lxc-start 20171202205306.135 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:2516 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
>      lxc-start 20171202205306.135 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:2516 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
>      lxc-start 20171202205306.135 DEBUG    lxc_conf - conf.c:lxc_map_ids:2604 - Functional newuidmap and newgidmap binary found.
>      lxc-start 20171202205306.142 INFO     lxc_start - start.c:do_start:914 - Unshared CLONE_NEWNET.
>      lxc-start 20171202205306.143 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:2516 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
>      lxc-start 20171202205306.143 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:2516 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
>      lxc-start 20171202205306.143 DEBUG    lxc_conf - conf.c:lxc_map_ids:2604 - Functional newuidmap and newgidmap binary found.
>      lxc-start 20171202205306.151 INFO     lxc_network - network.c:lxc_create_network_unpriv_exec:2081 - Execing lxc-user-nic create /home/zero/.local/share/lxc devel 1792 veth ovsbr0 (null)
>      lxc-start 20171202205306.214 NOTICE   lxc_utils - utils.c:lxc_switch_uid_gid:2070 - Switched to gid 0.
>      lxc-start 20171202205306.214 NOTICE   lxc_utils - utils.c:lxc_switch_uid_gid:2076 - Switched to uid 0.
>      lxc-start 20171202205306.214 NOTICE   lxc_utils - utils.c:lxc_setgroups:2088 - Dropped additional groups.
>      lxc-start 20171202205306.214 INFO     lxc_start - start.c:do_start:1001 - Unshared CLONE_NEWCGROUP.
>      lxc-start 20171202205306.214 DEBUG    storage - storage/storage.c:get_storage_by_name:212 - Detected rootfs type "dir"
>      lxc-start 20171202205306.214 ERROR    lxc_conf - conf.c:lxc_setup_rootfs:1254 - Failed to mount rootfs "dir:/home/zero/.local/share/lxc/devel/rootfs" onto "/usr/lib/x86_64-linux-gnu/lxc/rootfs" with options "(null)".
>      lxc-start 20171202205306.214 ERROR    lxc_conf - conf.c:do_rootfs_setup:3044 - failed to setup rootfs for 'devel'
>      lxc-start 20171202205306.214 ERROR    lxc_conf - conf.c:lxc_setup:3085 - Error setting up rootfs mount after spawn
>      lxc-start 20171202205306.214 ERROR    lxc_start - start.c:do_start:1020 - Failed to setup container "devel".
>      lxc-start 20171202205306.214 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
>      lxc-start 20171202205306.215 INFO     lxc_network - network.c:lxc_delete_network_unpriv_exec:2228 - Execing lxc-user-nic delete /home/zero/.local/share/lxc devel /proc/1781/fd/10 veth ovsbr0 vethSFMVAX
>      lxc-start 20171202205306.228 INFO     lxc_network - network.c:lxc_delete_network_unpriv:2338 - Removed interface "vethSFMVAX" from "ovsbr0"
>      lxc-start 20171202205306.228 DEBUG    lxc_network - network.c:lxc_delete_network:3096 - Deleted network devices
>      lxc-start 20171202205306.228 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
>      lxc-start 20171202205306.228 ERROR    lxc_container - lxccontainer.c:wait_on_daemonized_start:754 - Received container state "ABORTING" instead of "RUNNING"
>      lxc-start 20171202205306.228 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
>      lxc-start 20171202205306.228 ERROR    lxc_start - start.c:__lxc_start:1530 - Failed to spawn container "devel".
>      lxc-start 20171202205306.228 ERROR    lxc_start_ui - tools/lxc_start.c:main:368 - The container failed to start.
>      lxc-start 20171202205306.228 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
>      lxc-start 20171202205306.229 ERROR    lxc_start_ui - tools/lxc_start.c:main:370 - To get more details, run the container in foreground mode.
>      lxc-start 20171202205306.229 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
>      lxc-start 20171202205306.229 ERROR    lxc_start_ui - tools/lxc_start.c:main:372 - Additional information can be obtained by setting the --logfile and --logpriority options.
>      lxc-start 20171202205306.269 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:2516 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
>      lxc-start 20171202205306.269 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:2516 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
>      lxc-start 20171202205306.269 DEBUG    lxc_conf - conf.c:lxc_map_ids:2604 - Functional newuidmap and newgidmap binary found.
>      lxc-start 20171202205306.277 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:2516 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
>      lxc-start 20171202205306.277 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:2516 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
>      lxc-start 20171202205306.277 DEBUG    lxc_conf - conf.c:lxc_map_ids:2604 - Functional newuidmap and newgidmap binary found.
>      lxc-start 20171202205306.284 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:2516 - The binary "/usr/bin/newuidmap" does have the setuid bit set.
>      lxc-start 20171202205306.284 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:2516 - The binary "/usr/bin/newgidmap" does have the setuid bit set.
>      lxc-start 20171202205306.284 DEBUG    lxc_conf - conf.c:lxc_map_ids:2604 - Functional newuidmap and newgidmap binary found.
>      lxc-start 20171202205306.291 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
>      lxc-start 20171202205306.291 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
>      lxc-start 20171202205306.291 INFO     lxc_conf - conf.c:run_script_argv:398 - Executing script "/usr/share/lxcfs/lxc.reboot.hook" for container "devel", config section "lxc".

 - the containers configuration file

>   lxc.include = /usr/share/lxc/config/debian.common.conf
>   lxc.include = /usr/share/lxc/config/debian.userns.conf
>   lxc.arch = x86_64
>   lxc.autodev = 1 
>   lxc.kmsg = 0
>   lxc.pts=6
>   lxc.tty=6
>   lxc.mount.auto = proc:mixed sys:ro cgroup:mixed
>   lxc.rootfs = /home/zero/.local/share/lxc/devel/rootfs
>   lxc.rootfs.backend = dir
>   lxc.utsname = devel
>   lxc.network.type = veth
>   lxc.network.link = ovsbr0
>   lxc.network.flags = up
>   lxc.network.hwaddr = 00:FF:AA:xx:xx:xx
>   lxc.network.ipv4 = xx.xx.xx.xx/xx
>   lxc.network.ipv4.gateway = xx.xx.xx.xx
>   lxc.mount.entry = /dev/dri dev/dri none bind,optional,create=dir
>   lxc.mount.entry = /dev/snd dev/snd none bind,optional,create=dir
>   lxc.mount.entry = /tmp/.X11-unix tmp/.X11-unix none bind,optional,create=dir
>   lxc.mount.entry = /dev/video0 dev/video0 none bind,optional,create=file
>   lxc.hook.pre-start = /home/zero/.local/share/lxc/devel/setup-pulse.sh
>   lxc.id_map = u 0 100000 1000
>   lxc.id_map = g 0 100000 1000
>   lxc.id_map = u 1000 1000 1
>   lxc.id_map = g 1000 1000 1
>   lxc.id_map = u 1001 101001 64535
>   lxc.id_map = g 1001 101001 64535

**Comment by brauner** [comment]
Can you try setting `lxc.aa_profile=unconfined`.

**Comment by brauner** [comment]
Please show the `dmesg` output directly after failing to start a container. It should contain AppArmor denies.

**Comment by ne0zer0** [comment]
Seems you right:
> audit: type=1400 audit(1512296054.596:50): apparmor="DENIED" operation="mount" info="failed mntpnt match" error=-13 profile="/usr/bin/lxc-start" name="/usr/lib/x86_64-linux-gnu/lxc/rootfs/" pid=3894 comm="lxc-start" srcname="/home/zero/.local/share/lxc/devel/rootfs/" flags="rw, rbind"

**Comment by ne0zer0** [comment]
using
`lxc.aa_profile=unconfined`
in config file do nothing…

**Comment by ne0zer0** [comment]
Adding these options in Apparmore, at least, "complain mode" solves the problem:
> /usr/bin/lxc-start
>   lxc-container-default
>   lxc-container-default-cgns
>   lxc-container-default-with-mounting
