### ISSUE TITLE
No build on BE machines 

### ISSUE THREAD

**Issue by tlosm** [lxc/lxc#1990]
Machine type BE ,
Distro Ubuntu Mate 16.04.3
Kernel 64bit 

[Issue:](url)
lxc dont build . 
log attached 
[buld_lxc_log.txt](https://github.com/lxc/lxc/files/1524685/buld_lxc_log.txt)

**Comment by brauner** [comment]
You need `docbook-2x`. Is it installed?

**Comment by tlosm** [comment]
Hi brauner thanks for the info . with docbook now installed it build without issue .
