### ISSUE TITLE
lxc_cgfsng - cgroups/cgfsng.c:lxc_cgroup_set_data:1931 - Failed to setup limits for the "memory" controller. The controller seems to be unused by "cgfsng" cgroup driver or not enabled on the cgroup hierarchy

### ISSUE THREAD

**Issue by ne0zer0** [lxc/lxc#1991]
For contextual informations, see:
https://github.com/lxc/lxc/issues/1986
If I add in config files, somethings related to memory limit like this:
`lxc.cgroup.memory.limit_in_bytes = 4096M`
I get this message
> lxc_cgfsng - cgroups/cgfsng.c:lxc_cgroup_set_data:1931 - Failed to setup limits for the "memory" controller. The controller seems to be unused by "cgfsng" cgroup driver or not enabled on the cgroup hierarchy

**Comment by brauner** [comment]
That's very unlikely related to AppArmor. Have you delegated the `memory` cgroup controller to your unprivileged container user? Look at:

    cat /proc/self/cgroup

then take the cgroup for the `memory` cgroup controller you're in (e.g. `/some/thing` and look at:

    ls -al /sys/fs/cgroup/some/thing

and check the permissions. Cgroup delegation needs to be done by the a privileged user or by using our pam module that ships with `lxcfs`. If you haven't delegated the `memory` cgroup `liblxc` will not be able to start limits and setup the container. From what I gather you seem to have delegated them but please double check.

Please show:

    findmnt | grep cgroup

or, if `findmnt` is not available (e.g. `Alpine`)

    cat /proc/1/mountinfo | grep cgroup

from inside the container.

**Comment by ne0zer0** [comment]
Adding `cgroup_enable=memory` in grub solve the problem…
Strangely, if I am not mistaken, older Kernel like linux-image-4.9.0-3-amd64 works great without this option.

**Comment by brauner** [comment]
Right, glad that this is solved then.
