### ISSUE TITLE
Cannot attach to a container

### ISSUE THREAD

**Issue by p-l-** [lxc/lxc#1993]
Hi,

To check if #1985 was fixed in the development version, I've switched from ArchLinux lxc package (2.1.1-1) to AUR lxc-git package, built against this repository.

Now I can no longer attach to a container.

# Required information

 * Distribution: ArchLinux
 * The output of
   * `lxc-start --version` 2.1.0-devel
     * `pacman -Q lxc-git`: `lxc-git 1:2.1.0.322.g7ded3c18-1`
   * `lxc-checkconfig`:
```
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: missing
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/blkio
/sys/fs/cgroup/freezer
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/memory
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/pids
/sys/fs/cgroup/devices
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/cpuset

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```
   * `uname -a`: `Linux server 4.14.3-1-ARCH #1 SMP PREEMPT Thu Nov 30 18:33:13 UTC 2017 x86_64 GNU/Linux`

# Issue description

I can create and start a container, but no longer attach to it.

# Steps to reproduce

 1. Build and start the container

```
# lxc-create --name test --template archlinux
[...]
Arch Linux container test is successfully created! The configuration is
stored in /var/lib/lxc/test/config. Please refer to https://wiki.archlinux.org for
information about configuring Arch Linux.
# lxc-start --name test
# lxc-ls
test
# lxc-info --name test
Name:           test
State:          RUNNING
PID:            29301
CPU use:        0.26 seconds
BlkIO use:      7.54 MiB
Memory use:     16.44 MiB
KMem use:       6.15 MiB
```

 2. Try to attach to the container

```
# lxc-attach --name test
lxc-attach: test: attach.c: lxc_attach: 922 No such file or directory - Failed to attach to user namespace of 29362
                                                                                                                   #
```
 3. Try using `--namespaces`

As you can tell from the error message, the bug is actually related to attaching to the user namespace:
```
# lxc-attach --namespaces 'MOUNT|PID|UTSNAME|IPC|USER|NETWORK' --name test 
lxc-attach: test: attach.c: lxc_attach: 922 No such file or directory - Failed to attach to user namespace of 29409
                                                                                                                   #
```
```
# lxc-attach --namespaces 'MOUNT|PID|UTSNAME|IPC|NETWORK' --name test 
[root@test ~]# exit
exit
#
```

**Comment by brauner** [comment]
Thanks for testing, will look into this now.

**Comment by brauner** [comment]
I can't really reproduce this.

**Comment by brauner** [comment]
Oh right, you're on ArchLinux which means you do not have user namespaces in your kernel. Let me see if that could be the problem.

**Comment by brauner** [comment]
@p-l-, I sent a patch for this it's in my #1994 branch. It's the last commit. Depending on how experienced you are with building liblxc from source you can test it if you want.

**Comment by p-l-** [comment]
@brauner I can confirm that commit 134284c3ff235958150acca3588fba9c27c62b1c fixes this issue (and I can confirm #1985 is fixed in master + this commit).

BTW, for some reason I have not been able to build lxc with your full PR #1994 (malformed sgml files apparently; did not dig but I can if it helps you), so I had to cherry-pick the specific commit.

**Comment by brauner** [comment]
> BTW, for some reason I have not been able to build lxc with your full PR #1994 (malformed sgml files apparently; did not dig but I can if it helps you), so I had to cherry-pick the specific commit.

I think I remember that problem no ArchLinux when I used to compile from source there. Make sure that you have `docbook-2xs` installed or something. That is usually the reason. But you could likely also just download the lxc-git PKGBUILD script and point it to my branch.

**Comment by p-l-** [comment]
> Make sure that you have `docbook-2xs` installed or something.

Cannot find that, but I have `community/docbook2x` installed (and it is in `makedepends`).

> But you could likely also just download the lxc-git PKGBUILD script and point it to my branch.

That's what I did (sort of, I just added `git fetch origin +refs/pull/1994/merge` and `git checkout -qf FETCH_HEAD` in `pkgver()`).

**Comment by p-l-** [comment]
Thanks @brauner & @stgraber!
