### ISSUE TITLE
`lxc-info` show xxx doesn't exist

### ISSUE THREAD

**Issue by qingyunha** [lxc/lxc#1999]
# Required information

 * The output of
   * `lxc-start --version`
2.1.0-devel

# Issue description
I start a container named xxx as root. Then I run `lxc-info -n xxx -P /var/lib/lxc` using a non-root user, it report `xxx doesn't exist`.

**Comment by brauner** [comment]
That is expected behavior, unprivileged users shouldn't be able to see containers that are run by a privileged user. They can't control or interact with them anyway.

**Comment by qingyunha** [comment]
I think is better to show `Permission denied` or something like that.
