### ISSUE TITLE
Centos template doesnt work with LVM?

### ISSUE THREAD

**Issue by jamesbennet** [lxc/lxc#200]
Centos template doesnt work with LVM?

I have a VG called "lxc" as per the docs and I am running:

sudo lxc-create -t centos -n centos5 -f network.conf -B lvm --vgname lxc -- release=5.10 arch=x86_64 name=centos5

I get errors like:

Copy /var/cache/lxc/centos/x86_64/5.10/rootfs to /dev/lxc/centos5 ...
Copying rootfs to /dev/lxc/centos5 ...mkdir: cannot create directory ‘/dev/lxc/centos5’: File exists
rsync: writefd_unbuffered failed to write 4 bytes to socket [sender]: Broken pipe (32)
rsync: ERROR: cannot stat destination "/dev/lxc/centos5/": Not a directory (20)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(583) [Receiver=3.0.9]
rsync: connection unexpectedly closed (9 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=3.0.9]

Im guessing this script doesn't play nice with LVM backed containers? - /dev/lxc/centos5 is a device, not a mountpoint (It works if I dont use LVM)

**Comment by nehaljwani** [comment]
CentOS 6 works fine with LVM for me:
`lxc-create -n test -t centos -B lvm --vgname lxc --fssize=2G --fstype ext4  -- --release=6`

**Comment by brauner** [comment]
The `centos` template seems to work with `LVM` now. Please reopen if issue still persists.
