### ISSUE TITLE
CLI log options don't correctly override the configuration file

### ISSUE THREAD

**Issue by flx42** [lxc/lxc#2003]
I think this comment is currently incorrect:
https://github.com/lxc/lxc/blob/a144d2883021e67d22412e11fb6d2ee2a6439798/src/lxc/conf.h#L290-L297

I tried using the `LXC_LOG_LEVEL` feature in my hook (since b8f88d9bb2371d2e11b9c2fbc0a72d8e9608042e), but I was always getting `NOTSET` when using `lxc-execute --logpriority=DEBUG`. However, setting `lxc.log.level` in the container configuration file worked fine. Do we agree it's a bug?

I believe we are missing something like this:
https://github.com/flx42/lxc/commit/36b881fa9310438fc6ac2942b70b0a2e6202fd6f
However, this is no fully correct. If you specify a log file in the configuration, this file will still be created (but will be empty). It's because the log file is opened immediately when the configuration file is parsed:
https://github.com/lxc/lxc/blob/a144d2883021e67d22412e11fb6d2ee2a6439798/src/lxc/confile.c#L1246-L1251

Should we extract the log initialization from this function? As a side-effect, I believe it will also avoid opening all log files when doing a simple `lxc-ls`.

**Comment by brauner** [comment]
> Should we extract the log initialization from this function? As a side-effect, I believe it will also avoid opening all log files when doing a simple lxc-ls.

That sounds like a good idea.

**Comment by brauner** [comment]
> I tried using the LXC_LOG_LEVEL feature in my hook (since b8f88d9), but I was always getting NOTSET when using lxc-execute --logpriority=DEBUG. However, setting lxc.log.level in the container configuration file worked fine. Do we agree it's a bug?

Hm, this is because that field is indeed initialized to `NOTSET` since there's nothing specified in the config. Let me check something.

**Comment by flx42** [comment]
> Hm, this is because that field is indeed initialized to NOTSET since there's nothing specified in the config.

Sure, but I was expecting the CLI arguments to override it, like here for UID:
https://github.com/lxc/lxc/blob/a144d2883021e67d22412e11fb6d2ee2a6439798/src/lxc/tools/lxc_execute.c#L180-L181

**Comment by brauner** [comment]
@flx42, we need to figure that out bit by bit and I don't want to introduce additional hacks now. I might have an idea but I need to verify.

**Comment by flx42** [comment]
Of course, that's why I filed an issue before doing a PR (and marked my commit `[WIP]`). I felt this had the potential of breaking a lot of things.

**Comment by brauner** [comment]
I think it's just the wrong function that is called in there.

**Comment by brauner** [comment]
Also, the comment is wrong. oO

**Comment by flx42** [comment]
:(
I think I'll let you handle it then :)

**Comment by brauner** [comment]
@flx42, oh let's see if I am right I'll annoy you in a second with a proposed fix. :)

**Comment by brauner** [comment]
@flx42, I have a branch for renewing our Coverity integration - since we discussed this per mail - you can take a look and tell me if I did it right.

**Comment by brauner** [comment]
@flx42, care to give this a try?

I hacked in a `SYSERROR()` **JUST** for testing and did:

``` 
lxc-execute -n art1 -l trace -o AAA -- bash
```
looking at the log with my `SYSERROR()` hack I now get:

```
    lxc-execute art1 20171205231455.971 TRACE    lxc_start - start.c:lxc_init:607 - set container state to "STARTING"
    lxc-execute art1 20171205231455.971 ERROR    lxc_start - start.c:lxc_init:634 - No such file or directory - SET LXC_LOG_LEVEL=TRACE
    lxc-execute art1 20171205231455.971 TRACE    lxc_start - start.c:lxc_init:637 - set environment variables
```

**Comment by flx42** [comment]
Works fine! Thanks!
Still creating an empty log file if I specify one in the config file and override it from the CLI, but that's fine.

**Comment by brauner** [comment]
@flx42, if you have an idea for a patch to prevent that we can definitely land it. Sounds good to have.
