### ISSUE TITLE
Centos 7 template not able to change root password

### ISSUE THREAD

**Issue by razerrazer** [lxc/lxc#2005]
Hello,

Right now i have a issue with starting my new Centos 7 template on lxc v 2.20

this occurs when i tried to create it, there seems to be a permission error when it start up and you are not able to login to the container and change the root password.

Copy /var/cache/lxc/centos/x86_64/7/rootfs to /var/lib/lxc/centostest/rootfs ...
Copying rootfs to /var/lib/lxc/centostest/rootfs ...
sed: can't read /var/lib/lxc/centostest/rootfs/etc/init/tty.conf: No such file or directory
Storing root password in '/var/lib/lxc/centostest/tmp_root_pass'
chpasswd: cannot open /etc/passwd
Expiring password for user root.
passwd: Libuser error at line: 413 - Error replacing `/etc/passwd': Permission denied.
passwd: Error
sed: can't read /var/lib/lxc/centostest/rootfs/etc/rc.sysinit: No such file or directory
sed: can't read /var/lib/lxc/centostest/rootfs/etc/rc.d/rc.sysinit: No such file or directory

Container rootfs and config have been created.
Edit the config file to check/enable networking setup.

The temporary root password is stored in:

        '/var/lib/lxc/centostest/tmp_root_pass'

The root password is set up as expired and will require it to be changed
at first login, which you should do as soon as possible.  If you lose the
root password or wish to change it without starting the container, you
can change it from the host by running the following command (which will
also reset the expired flag):

        chroot /var/lib/lxc/centostest/rootfs passwd

lxc-create: confile.c: parse_line: 2368 Unknown configuration key "lxc.uts.name"
lxc-create: parse.c: lxc_file_for_each_line: 57 Failed to parse config: lxc.uts.name = centostest

lxc-create: tools/lxc_create.c: main: 326 Error creating container centostest

**Comment by brauner** [comment]
It looks like your templates and the liblxc version are out of sync. How did you install lxc or did you compile from master?

**Comment by razerrazer** [comment]
Hello i followed this guide to install LXC on centos 7 : 
https://github.com/lxc/lxd/files/1319385/centosLXD.sh.txt

**Comment by razerrazer** [comment]
After i have compile the source on a new machine the same problem occurs with stable 2.0 stable2.1

**Comment by brauner** [comment]
I'm confused. You're referencing LXD here not LXC in the installation instructions.

**Comment by razerrazer** [comment]
Hi, You asked me how i installed LXC ? or do you mean by create a LXC container?

Easy answer i have compile the code from stable-2.1 if that helps.

**Comment by GeoTob** [comment]
I am seeing exactly the same thing on my machine, both for `centos` and `fedora`, using distro-provided `lxc` and `lxc-templates` packages:

```
$ dnf info lxc lxc-templates
Last metadata expiration check: 0:33:26 ago on Wed 20 Dec 2017 12:30:43 NZDT.
Installed Packages
Name         : lxc
Version      : 2.0.9
Release      : 1.fc27
Arch         : x86_64
Size         : 477 k
Source       : lxc-2.0.9-1.fc27.src.rpm
Repo         : @System
From repo    : updates
Summary      : Linux Resource Containers
URL          : http://linuxcontainers.org
License      : LGPLv2+ and GPLv2
Description  : Linux Resource Containers provide process and resource isolation without the
             : overhead of full virtualization.

Name         : lxc-templates
Version      : 2.0.9
Release      : 1.fc27
Arch         : x86_64
Size         : 393 k
Source       : lxc-2.0.9-1.fc27.src.rpm
Repo         : @System
From repo    : updates
Summary      : Templates for lxc
URL          : http://linuxcontainers.org
License      : LGPLv2+ and GPLv2
Description  : Linux Resource Containers provide process and resource isolation without the
             : overhead of full virtualization.
             : 
             : The lxc-templates package contains templates for creating containers.
```

**Comment by GeoTob** [comment]
Adding to my note above:

1. It's not quite the same error, I do not see the last few lines that @razerrazer had posted:
```
lxc-create: confile.c: parse_line: 2368 Unknown configuration key "lxc.uts.name"
lxc-create: parse.c: lxc_file_for_each_line: 57 Failed to parse config: lxc.uts.name = centostest
lxc-create: tools/lxc_create.c: main: 326 Error creating container centostest
```

2. After machine creation I cannot use `passwd` or `chpasswd` from chroot at all, the latter fails with `cannot open /etc/passwd` just like when setting up the machine. I can however delete the root password from `/etc/shadow`, start the machine and then login as root.

**Comment by brauner** [comment]
@GeoTob, something's wrong with your setup though. `lxc.uts.name` is the replacement key for `lxc.utsname` introduced in `lxc 2.1` but your packages suggest that you are on `2.0.9`.

**Comment by razerrazer** [comment]
The problem for me was that i have forgot to deactivate SElinux and after i have done that everything works much better.

So if you have Centos or Fedora, just be sure that you have deactivate SElinux !!!

**Comment by hallyn** [comment]
Quoting razerrazer (notifications@github.com):
> The problem for me was that i have forgot to deactivate SElinux and after i have done that everything works much better.
> 
> So if you have Centos or Fedora, just be sure that you have deactivate SElinux !!!

wait wat?

**Comment by razerrazer** [comment]
@hallyn what did you not understand?

**Comment by hallyn** [comment]
The part where it was recommended to disable selinux rather than to fix the relevant policies.

**Comment by razerrazer** [comment]
well i agree with you, but... In my case this is just for a test environment so i don't need SeLinux enabled and that fix my issue that i have with the hole LXC installation, now i using LXC latest build and centos without any issues.

**Comment by hallyn** [comment]
That's fine of course :)  I was just alarmed at:

"So if you have Centos or Fedora, just be sure that you have deactivate SElinux !!!"

because people will see this issue months or years later and think that is a generally safe approach.

**Comment by indrayam** [comment]
```bash
lxc-create -n mylxccentos -t centos
Host CPE ID from /etc/os-release: cpe:/o:centos:centos:7
Checking cache download in /var/cache/lxc/centos/x86_64/7/rootfs ... 
Cache found. Updating...
Loaded plugins: fastestmirror
base                                                                                                                 | 3.6 kB  00:00:00     
extras                                                                                                               | 3.4 kB  00:00:00     
updates                                                                                                              | 3.4 kB  00:00:00     
(1/4): base/7/x86_64/group_gz                                                                                        | 156 kB  00:00:00     
(2/4): extras/7/x86_64/primary_db                                                                                    | 145 kB  00:00:00     
(3/4): base/7/x86_64/primary_db                                                                                      | 5.7 MB  00:00:05     
(4/4): updates/7/x86_64/primary_db                                                                                   | 5.2 MB  00:00:08     
Determining fastest mirrors
 * base: repos-tx.psychz.net
 * extras: repos-tx.psychz.net
 * updates: mirror.math.princeton.edu
No packages marked for update
Loaded plugins: fastestmirror
Cleaning repos: base extras updates
0 package files removed
Update finished
Copy /var/cache/lxc/centos/x86_64/7/rootfs to /var/lib/lxc/mylxccentos/rootfs ... 
Copying rootfs to /var/lib/lxc/mylxccentos/rootfs ...
sed: can't read /var/lib/lxc/mylxccentos/rootfs/etc/init/tty.conf: No such file or directory
Storing root password in '/var/lib/lxc/mylxccentos/tmp_root_pass'
chpasswd: cannot open /etc/passwd
Expiring password for user root.
passwd: Libuser error at line: 413 - Error replacing `/etc/passwd': Permission denied.
passwd: Error
sed: can't read /var/lib/lxc/mylxccentos/rootfs/etc/rc.sysinit: No such file or directory
sed: can't read /var/lib/lxc/mylxccentos/rootfs/etc/rc.d/rc.sysinit: No such file or directory

Container rootfs and config have been created.
Edit the config file to check/enable networking setup.

The temporary root password is stored in:

        '/var/lib/lxc/mylxccentos/tmp_root_pass'


The root password is set up as expired and will require it to be changed
at first login, which you should do as soon as possible.  If you lose the
root password or wish to change it without starting the container, you
can change it from the host by running the following command (which will
also reset the expired flag):

        chroot /var/lib/lxc/mylxccentos/rootfs passwd
```

I am getting the same error as above, minus the last few lines. Here's the version of lxc and lxc-templates...

```bash
[root@centos anand]# yum info lxc lxc-templates
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.fdcservers.net
 * epel: mirror.math.princeton.edu
 * extras: mirrors.cmich.edu
 * updates: distro.ibiblio.org
Installed Packages
Name        : lxc
Arch        : x86_64
Version     : 1.0.11
Release     : 1.el7
Size        : 317 k
Repo        : installed
From repo   : epel
Summary     : Linux Resource Containers
URL         : http://linuxcontainers.org
License     : LGPLv2+ and GPLv2
Description : Linux Resource Containers provide process and resource isolation without the
            : overhead of full virtualization.

Name        : lxc-templates
Arch        : x86_64
Version     : 1.0.11
Release     : 1.el7
Size        : 333 k
Repo        : installed
From repo   : epel
Summary     : Templates for lxc
URL         : http://linuxcontainers.org
License     : LGPLv2+ and GPLv2
Description : Linux Resource Containers provide process and resource isolation without the
            : overhead of full virtualization.
            : 
            : The lxc-templates package contains templates for creating containers.
```

Any ideas?

**Comment by Skorpeo** [comment]
I am able to workaround this by attaching to the running container then editing /etc/shadow, remove the asterisk for root, then run passwd.  I am then able to use the container normally.

**Comment by brauner** [comment]
If someone's interested in fixing this. This would need fixing the new new `lxc-templates` repo in the LXC namespace. Nothing to do for us here now.

**Comment by vbmade2000** [comment]
I am getting same issue I guess.

```
Host CPE ID from /etc/os-release: cpe:/o:centos:centos:7
Checking cache download in /var/cache/lxc/centos/x86_64/7/rootfs ... 
Cache found. Updating...
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.cisp.com
 * extras: mirrors.sorengard.com
 * updates: repos-lax.psychz.net
No packages marked for update
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Cleaning repos: base extras updates
0 package files removed
Update finished
Copy /var/cache/lxc/centos/x86_64/7/rootfs to /var/lib/lxc/sspl-test/rootfs ... 
Copying rootfs to /var/lib/lxc/sspl-test/rootfs ...
sed: can't read /var/lib/lxc/sspl-test/rootfs/etc/init/tty.conf: No such file or directory
Storing root password in '/var/lib/lxc/sspl-test/tmp_root_pass'
chpasswd: cannot open /etc/passwd
Expiring password for user root.
passwd: Libuser error at line: 413 - Error replacing `/etc/passwd': Permission denied.
passwd: Error
sed: can't read /var/lib/lxc/sspl-test/rootfs/etc/rc.sysinit: No such file or directory
sed: can't read /var/lib/lxc/sspl-test/rootfs/etc/rc.d/rc.sysinit: No such file or directory

Container rootfs and config have been created.
Edit the config file to check/enable networking setup.

The temporary root password is stored in:

        '/var/lib/lxc/sspl-test/tmp_root_pass'


The root password is set up as expired and will require it to be changed
at first login, which you should do as soon as possible.  If you lose the
root password or wish to change it without starting the container, you
can change it from the host by running the following command (which will
also reset the expired flag):

        chroot /var/lib/lxc/sspl-test/rootfs passwd
...
```

**Comment by hkdd** [comment]
Same issue using the lxc-centos template.  The debian template worked fine.  Also I'm unable to change the password using passwd in the container (get a token manipulation error).  Disabling selinux on the host running lxc allowed me to successfully change passwords in the container using passwd.  Something's definitely going on here and my guess is it's selinux related.

**Comment by hkdd** [comment]
Apologies and thanks, I'll report it there.

**Comment by joassouramou** [comment]
Hi there, 
Just checking if a fix has been found for this bug?

thanks

**Comment by chubin** [comment]
I suppose that it is selinux related.
Try to call 
```
    setenforce 0
```
in the hot system and see if it helps (to localize the problem).

**Comment by ilsaTi** [comment]
Thanks chubin. Disabling selinux resolved the issue.
