### ISSUE TITLE
Cant Start containers on BE

### ISSUE THREAD

**Issue by tlosm** [lxc/lxc#2018]
Distribution: Ubuntu Mate
    Distribution version: 16.04.3
    The output of "lxc info" or if that fails:
        Kernel version: 4.9.67
        LXC version: 2.0.11
        Hardware: Big Endian

Hi, i check all the tutorials and all similar issue but nothing fix my issue .
I try all distros powerpc compatible but i continue have this ... probably i miss something or something dont run right on BE:
"zesty: network.c: lxc_create_network_unpriv_exec: 2142 lxc-user-nic failed to configure requested network: lxc_user_nic.c: 530: create_nic: Error attaching vethTPS81K to lxcbr0
lxc-start: zesty: start.c: lxc_spawn: 1381 Failed to create the configured network.
lxc-start: zesty: start.c: __lxc_start: 1534 Failed to spawn container "zesty". The container failed to start.

i sow i have : 
● lxc-bridge.service
Loaded: not-found (Reason: No such file or directory)
Active: inactive (dead) 

i had been start again the lxc service but no container run
sudo systemctl restart lxc-net.service
sudo systemctl status -l lxc-net.service
● lxc-net.service - LXC network bridge setup
Loaded: loaded (/lib/systemd/system/lxc-net.service; enabled; vendor preset: enabled)
Active: active (exited) since dom 2017-12-10 10:16:59 CET; 8s ago
Process: 8276 ExecStop=/usr/local/libexec/lxc/lxc-net stop (code=exited, status=0/SUCCESS)
Process: 8279 ExecStart=/usr/local/libexec/lxc/lxc-net start (code=exited, status=0/SUCCESS)
Main PID: 8279 (code=exited, status=0/SUCCESS)

attached the log
[log.txt](https://github.com/lxc/lxc/files/1545582/log.txt)

**Comment by Uday6** [comment]
Any update with this issue?  I am facing similar issues.

**Comment by brauner** [comment]
Sorry, for the delayed reply. Can you verify that `lxc-user-nic` is owned by root and has the setuid bit set?

**Comment by brauner** [comment]
Hm, does the `lxcbr0` bridge exist?
