### ISSUE TITLE
Do not create an empty container folder if there is no config

### ISSUE THREAD

**Issue by flx42** [lxc/lxc#2032]
Kinda a follow-up to #2023 

Let's say I type too fast and write this:
```sh
$ lxc-execute -n -- ls
```
This will create a folder at `~/.local/share/lxc/--/` with just an empty log file (`--.log`):

**Comment by brauner** [comment]
@flx42, do you feel up for sending a patch for this. Otherwise this might take a while.

**Comment by flx42** [comment]
Sure, I might have time next week.

**Comment by brauner** [comment]
@flx42, assigning you. Just to track it not to force you in any way to do this. :)
