### ISSUE TITLE
Regression in lxc-copy -B btrfs

### ISSUE THREAD

**Issue by overlayfs** [lxc/lxc#2051]
**Regression**
```
lxc-copy -B btrfs -n test -N debug
```
fails with error message,
> lxc-copy: test: storage/btrfs.c: btrfs_create_snapshot: 478 Failed to run "btrfs_snapshot_wrapper"
> lxc-copy: test: lxccontainer.c: copy_storage: 3339 Error copying storage.
> clone failed

**Steps to reproduce**
```
lxc-create -B btrfs -n test -t download -- -d ubuntu -r trusty -a amd64
lxc-copy -B btrfs -n test -N debug
```
**OS details**
-lxc-daily ppa
-host & container: ubuntu-14.04 64bit
-kernel: linux-generic-lts-xenial

The regression is not present in lxc vesion 2.1.1+master\~20171207-2101-0ubuntu1\~trusty . It is present in version 2.1.1+master\~20171215-0227-0ubuntu1\~trusty .

**Comment by brauner** [comment]
@overlayfs, thanks for tracking these regressions. :) Is this with unprivileged containers? Privileged containers with current master work fine for me.

**Comment by brauner** [comment]
Right, unprivileged containers.
