### ISSUE TITLE
maybe lose log before enable syslog

### ISSUE THREAD

**Issue by duguhaotian** [lxc/lxc#2054]
https://github.com/lxc/lxc/blob/5305675314fd3948df41a3f86701e435dead8a07/src/lxc/start.c#L260

before enable here, syslog don't remember anything. Some call chain, never reach here. For example lxc-ls, you will lose lxc-ls log in syslog.
This enable code, just to avoid that make the check_inherited function enter an infinite loop. Why do not disable before while loop, and enable after while loop?????

Thanks!!!

**Comment by brauner** [comment]
@duguhaotian, I'm sorry, can you illustrate what you mean with a minimal patch? Shouldn't be too long.

**Comment by duguhaotian** [comment]
int lxc_check_inherited(struct lxc_conf *conf, bool closeall,
            int *fds_to_ignore, size_t len_fds)
{
    struct dirent *direntp;
    int fd, fddir;
    size_t i;
    DIR *dir;

**---------------------------------------**
**enable syslog after call lxc_log_init and disable syslog here.**
**some operation of container, maybe don't call this function. So, will never enable syslog, we will log some log in syslog.**
**-----------------------------------------**

    if (conf && conf->close_all_fds)
        closeall = true;

restart:
    dir = opendir("/proc/self/fd");
    if (!dir) {
        WARN("Failed to open directory: %s.", strerror(errno));
        return -1;
    }

    fddir = dirfd(dir);

    while ((direntp = readdir(dir))) {
        struct lxc_list *cur;
        bool matched = false;

        if (!direntp)
            break;

        if (!strcmp(direntp->d_name, "."))
            continue;

        if (!strcmp(direntp->d_name, ".."))
            continue;

        if (lxc_safe_int(direntp->d_name, &fd) < 0) {
            INFO("Could not parse file descriptor for: %s", direntp->d_name);
            continue;
        }

        for (i = 0; i < len_fds; i++)
            if (fds_to_ignore[i] == fd)
                break;

        if (fd == fddir || fd == lxc_log_fd ||
            (i < len_fds && fd == fds_to_ignore[i]))
            continue;

        /* Keep state clients that wait on reboots. */
        if (conf) {
            lxc_list_for_each(cur, &conf->state_clients) {
                struct lxc_state_client *client = cur->elem;

                if (client->clientfd != fd)
                    continue;

                matched = true;
                break;
            }
        }

        if (matched)
            continue;

        if (current_config && fd == current_config->logfd)
            continue;

        if (match_fd(fd))
            continue;

        if (closeall) {
            close(fd);
            closedir(dir);
            INFO("Closed inherited fd %d", fd);
            goto restart;
        }
        WARN("Inherited fd %d", fd);
    }

 /* Only enable syslog at this point to avoid the above logging function
     * to open a new fd and make the check_inherited function enter an
     * infinite loop.
     */
    lxc_log_enable_syslog();

    closedir(dir); /* cannot fail */
    return 0;
}

if just to avoid make the check_inherited function enter an infinite loop, i can to avoid it like above .
this is my opion.
Has any other reason do not implement like above??? 

that's all.
thanks.

**Comment by duguhaotian** [comment]
My  test:

First, insert  log call in lis_all_containers and lxc_container_new， and then test.

`lxc-ls  -P /var/lib/lcrd/lcr/ -n haozi --logfile=/root/lxc.log --logpriority=INFO`

`tail -f /root/lxc.log
      lxc-start haozi20171220062653.293 INFO     lxc_commands - commands.c:lxc_cmd_stop_callback:649 - -----kill failed ret 0, errno 22
      lxc-start haozi20171220062653.293 INFO     lxc_commands - commands.c:lxc_cmd_stop_callback:651 - unfreeze succes
      lxc-start haozi20171220062653.304 INFO     lxc_start - start.c:signal_handler:280 - begin get signal
      lxc-start haozi20171220062653.304 INFO     lxc_start - start.c:signal_handler:292 - begin check signal
      lxc-start haozi20171220062653.304 INFO     lxc_start - start.c:signal_handler:299 - finish wait signal
      lxc-start haozi20171220062653.304 INFO     lxc_start - start.c:__lxc_start:1542 - finish poll-----------
      lxc-start haozi20171220062653.304 INFO     lxc_start - start.c:__lxc_start:1548 - ------begin waitpid: 31470
      lxc-start haozi20171220062653.304 INFO     lxc_error - error.c:lxc_error_set_and_log:54 - Child <31470> ended on signal (9).
       lxc-stop haozi20171220062653.397 INFO     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - ----finish rsp revc fd----
       lxc-stop haozi20171220062653.397 INFO     lxc_commands - commands.c:lxc_cmd_stop:628 - Container "haozi" has stopped.



         lxc-ls20171220112734.470 INFO     lxc_container - lxccontainer.c:list_all_containers:4553 - ---------list all container-------

         lxc-ls20171220112734.472 INFO     lxc_container - lxccontainer.c:lxc_container_new:4200 - ---------new a container-------
`

`tail -f /var/log/syslog
Dec 20 18:17:01 rtoswork CRON[1421]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Dec 20 18:25:04 rtoswork systemd-timesyncd[2632]: Timed out waiting for reply from 91.189.91.157:123 (ntp.ubuntu.com).
Dec 20 18:25:14 rtoswork systemd-timesyncd[2632]: Timed out waiting for reply from 91.189.89.199:123 (ntp.ubuntu.com).
Dec 20 18:25:24 rtoswork systemd-timesyncd[2632]: Timed out waiting for reply from 91.189.89.198:123 (ntp.ubuntu.com).
Dec 20 18:25:35 rtoswork systemd-timesyncd[2632]: Timed out waiting for reply from 91.189.94.4:123 (ntp.ubuntu.com).
Dec 20 18:59:53 rtoswork systemd-timesyncd[2632]: Timed out waiting for reply from 91.189.91.157:123 (ntp.ubuntu.com).
Dec 20 19:00:03 rtoswork systemd-timesyncd[2632]: Timed out waiting for reply from 91.189.94.4:123 (ntp.ubuntu.com).
Dec 20 19:00:14 rtoswork systemd-timesyncd[2632]: Timed out waiting for reply from 91.189.89.199:123 (ntp.ubuntu.com).
Dec 20 19:00:24 rtoswork systemd-timesyncd[2632]: Timed out waiting for reply from 91.189.89.198:123 (ntp.ubuntu.com).
Dec 20 19:17:01 rtoswork CRON[1667]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

Dec 20 19:26:02 rtoswork lxc-ls[1718]: this is 128 a test log for syslog


Dec 20 19:27:34 rtoswork lxc-ls[1753]: this is 128 a test log for syslog   ////to ensure syslog have config.

`
So, we can see , filelog can get two new log, but syslog do not get anythings.

**Comment by brauner** [comment]
I don't think we want `lxc-ls` to spam the `syslog` that's definitely not its job. We don't want `lxc-ls` to cause any open() or close() call on a containers log or syslog.

**Comment by duguhaotian** [comment]
Just want remember log after lxc-start a container? OK, i got it.

**Comment by brauner** [comment]
Closing for now but thanks! :)
