### ISSUE TITLE
Possibly reattaching container uses different configuration when copy fails.

### ISSUE THREAD

**Issue by TimJSwan89** [lxc/lxc#2059]
I was in middle of filling one of these issues out with the goal of being able to ping google.com from within my container. I was running a jenkins job, cancelled, and ran another with a git push that I had forgotten and suddenly the ping worked. I was confused because I thought the only change was printing more things to the console. Now I'm wondering if it has to do with the fact that I cancelled the job and left the container sitting around so when I reattached it used different configure settings or something similar to that effect.

Here's a more top-level script
```
lxc-copy -s -e -B overlay -m bind=`pwd`:/mnt/jenkins:rw -n ubuntu-14.04-java -N mycontainer \
&& trap stopLxc EXIT
lxc-info --name mycontainer
lxc-start --version
lxc-checkconfig
uname -a
cat /proc/self/cgroup
cat /proc/1/mounts
lxc-info --name ubuntu-14.04-java
lxc-info --name mycontainer
lxc-attach -n mycontainer -- su -l -c /mnt/jenkins/scriptwhichpingsgoogle.sh
```
The last run resulted in:
```
lxc-copy: lxccontainer.c: do_lxcapi_clone: 3092 error: clone: /var/lib/jenkins/.local/share/lxc/mycontainer/config exists
Name:           mycontainer
State:          RUNNING
PID:            460
IP:             10.0.1.116
Link:           veth1KPGJV
 TX bytes:      4.53 KiB
 RX bytes:      8.91 KiB
 Total bytes:   13.44 KiB
2.0.8
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-3.19.0-80-generic
```
Then the ping worked for some reason.
Let me know if I need to add some sort of information to this issue to help get an explanation.

**Comment by brauner** [comment]
No, that shouldn't matter. What likely happened is that your init system didn't have enough time to setup networking inside the container (e.g. running dhcp and so on). Then, when you tried the second time, enough time had passed for the init system to bring up networking. lxc itself has no control what init does inside the container. It only fires it up and hands over execution to the init binary.

**Comment by brauner** [comment]
Closing as this is not really a liblxc bug. If you disagree, please comment here or re-open. :)
