### ISSUE TITLE
unprivlieged lxc_container: command get_cgroup failed to receive response, kernel 3.14.1

### ISSUE THREAD

**Issue by vrodic** [lxc/lxc#206]
Hello,
I get the lxc_container: command get_cgroup failed to receive response when trying to start the lxc container with 3.14.1 Linux from here: http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.14.1-trusty/

The 3.13.8, Ubuntu 14.04 current stock kernel (linux-image-extra-3.13.0-22-generic) also works.

**Comment by madsurgeon** [comment]
Hi Stéphane,
I seem to be running into the same error as vrodic on utopic amd64 btrfs with kernel 3.16.0-30 and systemd 208-8ubuntu8.2.

The error message is:
      lxc-start 1423396555.329 ERROR    lxc_cgmanager - cgmanager.c:lxc_cgmanager_create:284 - call to cgmanager_create_sync failed: invalid request
      lxc-start 1423396555.330 ERROR    lxc_cgmanager - cgmanager.c:lxc_cgmanager_create:286 - Failed to create name=systemd:p1
      lxc-start 1423396555.330 ERROR    lxc_cgmanager - cgmanager.c:cgm_create:638 - Error creating cgroup name=systemd:p1
      lxc-start 1423396555.333 ERROR    lxc_start - start.c:lxc_spawn:864 - failed creating cgroups
      lxc-start 1423396555.334 ERROR    lxc_start - start.c:__lxc_start:1087 - failed to spawn 'p1'
      lxc-start 1423396560.340 ERROR    lxc_start_ui - lxc_start.c:main:337 - The container failed to start.
      lxc-start 1423396560.340 ERROR    lxc_start_ui - lxc_start.c:main:339 - To get more details, run the container in foreground mode.
      lxc-start 1423396560.340 ERROR    lxc_start_ui - lxc_start.c:main:341 - Additional information can be obtained by setting the --logfile and --logpriority options.

My /proc/self/cgroup:
12:name=systemd:/user.slice/user-1000.slice/session-c2.scope
11:perf_event:/user.slice/user-1000.slice/session-c2.scope
10:net_prio:/user.slice/user-1000.slice/session-c2.scope
9:net_cls:/user.slice/user-1000.slice/session-c2.scope
8:memory:/user.slice/user-1000.slice/session-c2.scope
7:hugetlb:/user.slice/user-1000.slice/session-c2.scope
6:freezer:/user.slice/user-1000.slice/session-c2.scope
5:devices:/user.slice/user-1000.slice/session-c2.scope
4:cpuset:/user.slice/user-1000.slice/session-c2.scope
3:cpuacct:/user.slice/user-1000.slice/session-c2.scope
2:cpu:/user.slice/user-1000.slice/session-c2.scope
1:blkio:/user.slice/user-1000.slice/session-c2.scope

**Comment by madsurgeon** [comment]
I have to add that the above error occurs when running starting an unpriviledged container from a user without sudo rights and without X11 rights. A pristine adduser user.
There I see in addition to the above errors four lines
WARN: could not reopen tty: Permission denied

From the default Ubuntu user starting unpriviledged containers works. I just had to chmod +x ~/.config, ~/.local, and ~/.local/share.
