### ISSUE TITLE
Android question

### ISSUE THREAD

**Issue by zhenyolka** [lxc/lxc#2071]
Hello! Sorry for my English. I want to run lxc on android. I try you binary in lxc-ci repository, i have only PIE error.
How i can run lxc on android(in my case it android 6.0, cyanogenmod,armv7)?
Which options i need to enable in kernel, and where i can find binary for my android?

**Comment by brauner** [comment]
Which lxc version are you using?

**Comment by zhenyolka** [comment]
I not use lxc, i want use it on android.

**Comment by zhenyolka** [comment]
I need lxc for android

**Comment by brauner** [comment]
lxc can be built for android we do not provide any packages afaik. @stgraber might know more about this.

**Comment by zhenyolka** [comment]
@brauner i found binary.
Now on start container i see error:
"lxc-start 20180106125331.783 INFO     lxc_start_ui - lxc_start.c:main:264 - using rcfile /data/lxc/containers/ubuntu/config
      lxc-start 20180106125331.784 WARN     lxc_confile - confile.c:config_personality:1117 - unsupported personality 'armvl7'
      lxc-start 20180106125331.786 WARN     lxc_start - start.c:lxc_check_inherited:254 - inherited fd 10
      lxc-start 20180106125331.786 DEBUG    lxc_start - start.c:setup_signal_fd:289 - sigchild handler set
      lxc-start 20180106125331.787 DEBUG    lxc_console - console.c:lxc_console_peer_default:431 - opening /dev/tty for console peer
      lxc-start 20180106125331.787 DEBUG    lxc_console - console.c:lxc_console_peer_default:437 - using '/dev/tty' as console
      lxc-start 20180106125331.787 DEBUG    lxc_console - console.c:lxc_console_sigwinch_init:145 - 27735 got SIGWINCH fd 9
      lxc-start 20180106125331.787 DEBUG    lxc_console - console.c:lxc_console_winsz:72 - set winsz dstfd:6 cols:53 rows:20
      lxc-start 20180106125331.787 INFO     lxc_start - start.c:lxc_init:488 - 'ubuntu' is initialized
      lxc-start 20180106125331.788 ERROR    lxc_start - start.c:must_drop_cap_sys_boot:649 - failed to clone (0x20000011): Invalid argument
      lxc-start 20180106125331.788 DEBUG    lxc_start - start.c:__lxc_start:1321 - Dropping cap_sys_boot
      lxc-start 20180106125331.789 INFO     lxc_cgroup - cgroup.c:cgroup_init:68 - cgroup driver cgroupfs initing for ubuntu
      lxc-start 20180106125331.793 ERROR    lxc_namespace - namespace.c:lxc_clone:67 - failed to clone (0x2c020000): Invalid argument
      lxc-start 20180106125331.793 ERROR    lxc_start - start.c:lxc_spawn:1140 - Invalid argument - failed to fork into a new namespace
      lxc-start 20180106125331.794 ERROR    lxc_start - start.c:__lxc_start:1353 - failed to spawn 'ubuntu'
      lxc-start 20180106125331.830 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
      lxc-start 20180106125331.831 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.
"
My config file:
"lxc.rootfs = /data/lxc/containers/ubuntu/rootfs
lxc.utsname = armvl7

# Network configuration
lxc.network.type = none

#lxc.mount.auto = cgroup

lxc.devttydir = lxc
lxc.pts = 512
lxc.arch = armvl7

lxc.kmsg = 0
# todo, bind only required stuff
#lxc.mount.entry = /dev dev/ none bind,optional,create=dir
lxc.mount.entry = /system system/ none bind,optional,create=dir
lxc.mount.entry = /vendor vendor/ none bind,optional,create=dir
"
I cant give you version of lxc, i can only write link 
https://forum.xda-developers.com/pixel-c/orig-development/linux-pixel-c-running-ubuntu-xenial-lxc-t3410655
I think to solve my problem need recompile kernel, but which options need enable?
@stgraber , can you help?

**Comment by zhenyolka** [comment]
@brauner i found binary.
Now on start container i see error:
"lxc-start 20180106125331.783 INFO lxc_start_ui - lxc_start.c:main:264 - using rcfile /data/lxc/containers/ubuntu/config
lxc-start 20180106125331.784 WARN lxc_confile - confile.c:config_personality:1117 - unsupported personality 'armvl7'
lxc-start 20180106125331.786 WARN lxc_start - start.c:lxc_check_inherited:254 - inherited fd 10
lxc-start 20180106125331.786 DEBUG lxc_start - start.c:setup_signal_fd:289 - sigchild handler set
lxc-start 20180106125331.787 DEBUG lxc_console - console.c:lxc_console_peer_default:431 - opening /dev/tty for console peer
lxc-start 20180106125331.787 DEBUG lxc_console - console.c:lxc_console_peer_default:437 - using '/dev/tty' as console
lxc-start 20180106125331.787 DEBUG lxc_console - console.c:lxc_console_sigwinch_init:145 - 27735 got SIGWINCH fd 9
lxc-start 20180106125331.787 DEBUG lxc_console - console.c:lxc_console_winsz:72 - set winsz dstfd:6 cols:53 rows:20
lxc-start 20180106125331.787 INFO lxc_start - start.c:lxc_init:488 - 'ubuntu' is initialized
lxc-start 20180106125331.788 ERROR lxc_start - start.c:must_drop_cap_sys_boot:649 - failed to clone (0x20000011): Invalid argument
lxc-start 20180106125331.788 DEBUG lxc_start - start.c:__lxc_start:1321 - Dropping cap_sys_boot
lxc-start 20180106125331.789 INFO lxc_cgroup - cgroup.c:cgroup_init:68 - cgroup driver cgroupfs initing for ubuntu
lxc-start 20180106125331.793 ERROR lxc_namespace - namespace.c:lxc_clone:67 - failed to clone (0x2c020000): Invalid argument
lxc-start 20180106125331.793 ERROR lxc_start - start.c:lxc_spawn:1140 - Invalid argument - failed to fork into a new namespace
lxc-start 20180106125331.794 ERROR lxc_start - start.c:__lxc_start:1353 - failed to spawn 'ubuntu'
lxc-start 20180106125331.830 ERROR lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
lxc-start 20180106125331.831 ERROR lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.
"
My config file:
"lxc.rootfs = /data/lxc/containers/ubuntu/rootfs
lxc.utsname = armvl7

lxc.network.type = none

#lxc.mount.auto = cgroup

lxc.devttydir = lxc
lxc.pts = 512
lxc.arch = armvl7

lxc.kmsg = 0

#lxc.mount.entry = /dev dev/ none bind,optional,create=dir
lxc.mount.entry = /system system/ none bind,optional,create=dir
lxc.mount.entry = /vendor vendor/ none bind,optional,create=dir
"
I cant give you version of lxc, i can only write link
https://forum.xda-developers.com/pixel-c/orig-development/linux-pixel-c-running-ubuntu-xenial-lxc-t3410655
I think to solve my problem need recompile kernel, but which options need enable?
@stgraber , can you help?

**Comment by brauner** [comment]
Right, it seems your kernel doesn't support:

    #define CLONE_NEWPID		0x20000000	/* New pid namespace */

pid namespaces. Can you run `lxc-checkconfig`? This should tell you what features your kernel is missing.

**Comment by zhenyolka** [comment]
@brauner i compile kernel with information, what i get from "lxc-checkconfig" command. 
With recompiled kernel i get these output of "lxc-checkconfig" command
"--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: missing
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
./lxc-checkconfig[91]: awk: not found
Cgroup: enabled
Cgroup namespace: required
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: missing
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: missing
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: missing
CONFIG_NETLINK_DIAG: missing
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config ./lxc-checkconfig
"
Cgroup namespace, CONFIG_NETLINK_DIAG,CONFIG_PACKET_DIAG,CONFIG_NF_NAT_IPV4 and other missing options i cant found in "menuconfig".
With these kernel i have these error on container start:
"
lxc-start: cgfs.c: handle_cgroup_settings: 2148 Device or resource busy - failed to set memory.use_hierarchy to 1; continuing
Failed to insert module 'autofs4': No such file or directory
Failed to insert module 'unix': No such file or directory
Failed to determine whether /sys/fs/cgroup is a mount point: Too many levels of symbolic links
Failed to mount cgroup at /sys/fs/cgroup/systemd: No such file or directory
[!!!!!!] Failed to mount API filesystems, freezing.
Freezing execution.
"
I think main error is "lxc-start: cgfs.c: handle_cgroup_settings: 2148 Device or resource busy - failed to set memory.use_hierarchy to 1; continuing". 
What need do?

**Comment by brauner** [comment]
On Sat, Jan 13, 2018 at 07:35:41PM +0000, zhenyolka wrote:
> @brauner i compile kernel with information, what i get from "lxc-checkconfig" command. 
> With recompiled kernel i get these output of "lxc-checkconfig" command
> "--- Namespaces ---
> Namespaces: enabled
> Utsname namespace: enabled
> Ipc namespace: enabled
> Pid namespace: enabled
> User namespace: missing

Note that your kernel doesn't support user namespaces. This means you
won't be able to run unprivileged containers. What containers are you
trying to run?

> Network namespace: enabled
> Multiple /dev/pts instances: enabled
> 
> --- Control groups ---
> ./lxc-checkconfig[91]: awk: not found
> Cgroup: enabled
> Cgroup namespace: required
> Cgroup device: enabled
> Cgroup sched: enabled
> Cgroup cpu account: enabled
> Cgroup memory controller: enabled
> Cgroup cpuset: enabled
> 
> --- Misc ---
> Veth pair device: enabled
> Macvlan: enabled
> Vlan: enabled
> Bridges: enabled
> Advanced netfilter: enabled
> CONFIG_NF_NAT_IPV4: missing
> CONFIG_NF_NAT_IPV6: missing
> CONFIG_IP_NF_TARGET_MASQUERADE: enabled
> CONFIG_IP6_NF_TARGET_MASQUERADE: missing
> CONFIG_NETFILTER_XT_TARGET_CHECKSUM: missing
> FUSE (for use with lxcfs): enabled
> 
> --- Checkpoint/Restore ---
> checkpoint restore: enabled
> CONFIG_FHANDLE: enabled
> CONFIG_EVENTFD: enabled
> CONFIG_EPOLL: enabled
> CONFIG_UNIX_DIAG: enabled
> CONFIG_INET_DIAG: enabled
> CONFIG_PACKET_DIAG: missing
> CONFIG_NETLINK_DIAG: missing
> File capabilities: enabled
> 
> Note : Before booting a new kernel, you can check its configuration
> usage : CONFIG=/path/to/config ./lxc-checkconfig
> "
> Cgroup namespace, CONFIG_NETLINK_DIAG,CONFIG_PACKET_DIAG,CONFIG_NF_NAT_IPV4 and other missing options i cant found in "menuconfig".
> With these kernel i have these error on container start:
> "
> lxc-start: cgfs.c: handle_cgroup_settings: 2148 Device or resource busy - failed to set memory.use_hierarchy to 1; continuing

You should set
/sys/fs/cgroup/memory/memory.use_hierarchy
to 1 before starting the container.

> Failed to insert module 'autofs4': No such file or directory
> Failed to insert module 'unix': No such file or directory
> Failed to determine whether /sys/fs/cgroup is a mount point: Too many levels of symbolic links
> Failed to mount cgroup at /sys/fs/cgroup/systemd: No such file or directory

What systemd version are you trying to run in the container?
