### ISSUE TITLE
New image generator (to replace the template)

### ISSUE THREAD

**Issue by brauner** [lxc/lxc#2072]
For a long time our template scripts were good enough but it's time for something better.

**Comment by stgraber** [comment]
`distrobuilder` below is a placeholder name for the tool, better suggestions are very much welcome!

My plan for LXC 3.0 is to effectively only ship with three templates:
 - lxc-download (download images from https://images.linuxcontainers.org as usual)
 - lxc-oci (generates a container from an OCI image)
 - lxc-distrobuilder (runs a locally installed copy of `distrobuilder` and generates a custom image through it)

**Comment by stgraber** [comment]
The `distrobuilder` tool would be fed yaml input describing the image and its metadata, what distro it is, what architecture, what release, what variant, packages to add/remove and straight up shell to execute at the end of the build.

It would support spitting out:
 - Plain old chroot (no metadata)
 - LXC image (root.tar.xz + meta.tar.xz in LXC format)
 - LXD image (root.tar.xz + meta.tar.xz in LXD format)

It should be possible to have it spit out both LXC and LXD images in one go (so we don't have to re-run or re-pack the images).

**Comment by stgraber** [comment]
Tool should be written in Go, using the same Go packages as LXD whenever possible, with the exception of CLI handling that should be done with urfave/cli.

**Comment by stgraber** [comment]
Whenever possible, we'll want this tool to download official cloud images/tarballs from the distro and repack those into a LXC/LXD image rather than build them from scratch as many of the templates do today.

This will make the resulting images more supportable from the distro and will also allow us to build those images on any Linux distro rather than requiring the target distro's packaging tools to be available.

**Comment by srkunze** [comment]
Alright my thoughts about the "distrobuilder" (alternative: **lxcfile**?).

- it definitely should do the same transactional/snapshotish thing dockerfile does which goes like this:

```
CMD1  <<< do it first and snapshot
CMD2  <<< do it second and snapshot
CMD3  <<< do it third and snapshot
```

- let's change CMD3 to CMD4

```
CMD1  <<< already done
CMD2  <<< already done
CMD4  <<< do it and snapshot, throw snaphot for CMD3 out of the window
```

I can tell you, people safe a **ton of time** by having this.

Otherwise I gather this thing wouldn't be much better than a shell script.

**Comment by srkunze** [comment]
About the orchestration/composition stuff: docker included stuff like port exposure and the "usual command to execute" into dockerfile. I think the latter can be done with a service file/service activation in LXC/LXD.

However, docker-compose is able to define how containers interact with their environment, which containers are used and stuff. I gather this is out of the scope of this issue. Although I love to see it for my favorite containerization technology as well. ;-) Even recursion might be an interesting idea here.

**Comment by stgraber** [comment]
Hmm, starting to feel like a separate tool that does this kind of stuff may be best.

The goal for distrobuilder is to replace the huge mess of shell scripts we maintain today that spits out LXC/LXD images to instead have a single tool which is fed a yaml definition of what we want (what distro, what release, what architecture, list of packages to include, list of packages to remove and a bunch of other actions to do prior to spitting out the image).

**Comment by srkunze** [comment]
> Hmm, starting to feel like a separate tool that does this kind of stuff may be best.

Completely agree.

> have a single tool which is fed a yaml definition

What do you think about the snapshotish behavior? I can tell you by experience that maintainers will save huge deal of time.

**Comment by jitakirin** [comment]
What's the benefit of the custom image format, etc.?

Wouldn't it be better to standardise on OCI? You could then take advantage of an already existing rich ecosystem. E.g. [buildah](https://github.com/projectatomic/buildah) for building images?

**Comment by stgraber** [comment]
@jitakirin LXC does support running OCI application container images through the lxc-oci template, in which case you can indeed use all the existing images and tooling around OCI images.

The focus of distrobuilder is to generate system container images, that can be supported by the original distributor and contain the amount of metadata that LXC and LXD require to run a working OS.

**Comment by jitakirin** [comment]
@stgraber thanks for answering! is this related to the fact that OCI images were designed or are more commonly used for application containers and not system containers?

**Comment by stgraber** [comment]
The LXC side of this has been done now, we've got the lxc-local template in 3.0 that can consume the output of distrobuilder. We hope to start transitioning some of our jenkins generated images over within the next week or so.
