### ISSUE TITLE
Uncertainties about cgfsng support of `lxc.cgroup.use` config

### ISSUE THREAD

**Issue by matthijskooijman** [lxc/lxc#2084]
While trying to get a fix for #1737 work (see [my comment][1]) I ran
into some issues related to the `cgfsng` backend and the
`lxc.cgroup.use` config value. I'm not entirely sure what the scope of
this issue is and how things are supposed to work, but from reading the
git master source code, it seems that at least the `cgfs` and `cgfsng`
backends handle this config value differently.

[1]: https://github.com/lxc/lxc/issues/1737#issuecomment-357380238

It seems that, to enable *all* cgroups, `cgfs` supports a value of `@all`: https://github.com/lxc/lxc/blob/master/src/lxc/cgroups/cgfs.c#L593-L598

This is not documented in the manpage (which says to not define the
value to get all cgroups), but my own config (which has been working
correctly for years), confirms this:

      # cat /etc/lxc/lxc.conf
      lxcpath=/var/lib/lxc
      lxc.cgroup.use=@all

However, it seems that the new `cgfsng` backend indeed implements only
what the documentation says: A missing config value just uses all
detected cgroups, while a value of `@all` is interpreted as a literal
cgroup name, and causes the `cgfsng` initialization to fail and makes
lxc fall back to `cgfs`): https://github.com/lxc/lxc/blob/master/src/lxc/cgroups/cgfsng.c#L739-L750

This is confirmed by my testing:

      # lxc-start -n template -l DEBUG
      # grep cgroup_init template.log
      lxc-start 20180114133401.404 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:67 - cgroup driver cgroupfs initing for template

When removing `lxc.cgroup.use=@all` from `lxc.conf` and starting the container, it properly initializes the `cgfsns` backend:

      # grep cgroup_init template.log
      lxc-start 20180114133701.184 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:67 - cgroup driver cgroupfs-ng initing for template

These tests were run using the Debian 2.0.9 version with #1888
backported onto it, but from looking at the git master source code, I
would expect the same behaviour there.

As mentioned: I'm not entirely sure what the correct behaviour would
be. I did notice some possible oddities:
 - Using `cgfsng`, setting `cgroup_use` only makes it check if those
   cgroups are detected (in `all_controllers_found()`), but it seems
   that the rest of the code always actually uses all cgroups.
 - [This comment](https://github.com/lxc/lxc/blob/master/src/lxc/cgroups/cgfs.c#L584-L586)
   specifies that named subsystems are not included when
   `lxc.cgroup.use` is not specified, but I think [this
   code](https://github.com/lxc/lxc/blob/master/src/lxc/cgroups/cgfs.c#L596-L598)
   says they are.
 - It seems that specifying an empty list disables all cgroups, at least
   in `cgfs` (which is not really odd, but might need to be clarified in
   the docs):
   https://github.com/lxc/lxc/blob/master/src/lxc/cgroups/cgfs.c#L252-L256

For completeness, here's the container config file used in testing:

      # Hostname
      lxc.utsname = template.local

      # Use this root filesystem
      lxc.rootfs = /containers/template

      # Log console output
      lxc.console.logfile = /var/log/lxc/template.console
      lxc.logfile = /var/log/lxc/template.log

      # The container gets a single virtual eth0 interface with a statically assigned
      # address (assigned by lxc-start, no need for the container to assign any
      # address itself).
      lxc.network.type = veth
      lxc.network.flags = up
      lxc.network.veth.pair = lxc-template
      lxc.network.name = eth0
      lxc.network.link = br-lxc
      lxc.network.ipv4 = 10.42.0.10/24
      lxc.network.ipv4.gateway = auto

      # The number of ttys available (shouldn't be less than the getty's
      # configured in the inittab).
      lxc.tty = 4

      # Use private pts for the container
      lxc.pts = 256

      # Set up /dev for systemd
      lxc.kmsg = 0
      lxc.autodev = 1

      # Deny all devices, except the following
      lxc.cgroup.devices.deny = a
      # /dev/null
      lxc.cgroup.devices.allow = c 1:3 rwm
      # /dev/zero
      lxc.cgroup.devices.allow = c 1:5 rwm
      # /dev/console
      lxc.cgroup.devices.allow = c 5:1 rwm
      # /dev/tty
      lxc.cgroup.devices.allow = c 5:0 rwm
      # /dev/tty0
      lxc.cgroup.devices.allow = c 4:0 rwm
      # /dev/tty1
      lxc.cgroup.devices.allow = c 4:1 rwm
      # /dev/{,u}random
      lxc.cgroup.devices.allow = c 1:9 rwm
      lxc.cgroup.devices.allow = c 1:8 rwm
      # /dev/pts/0 - /dev/pts/255
      lxc.cgroup.devices.allow = c 136:* rwm
      # /dev/ptmx
      lxc.cgroup.devices.allow = c 5:2 rwm
      # rtc
      lxc.cgroup.devices.allow = c 254:0 rwm

      # Mount special filesystems. Most of these ar normally mounted by systemd on
      # startup, but by pre-mounting them here, systemd can run without cap_sys_admin.
      # Regular mounts are in /etc/fstab in the host
      lxc.mount.auto = proc:rw
      lxc.mount.auto = sys:rw
      lxc.mount.auto = cgroup:mixed
      lxc.mount.entry = tmpfs dev/shm tmpfs rw,nosuid,nodev,create=dir 0 0
      lxc.mount.entry = tmpfs run tmpfs rw,nosuid,nodev,mode=755,create=dir 0 0
      lxc.mount.entry = tmpfs run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k,create=dir 0 0
      lxc.mount.entry = debugfs sys/kernel/debug debugfs rw,relatime 0 0
      lxc.mount.entry = mqueue dev/mqueue mqueue rw,relatime,create=dir 0 0
      lxc.mount.entry = hugetlbfs dev/hugepages hugetlbfs rw,relatime,create=dir 0 0

      # Disallow module (un)loading
      lxc.cap.drop = sys_module
      # Disallow doing raw io
      lxc.cap.drop = sys_rawio
      # Disallow changing the clock
      lxc.cap.drop = sys_time
      # Disallow changing network settings
      lxc.cap.drop = net_admin
      # Disallow changing auditing settings
      lxc.cap.drop = audit_control
      # Disallow various admin tasks (probably has side-effects)
      lxc.cap.drop = sys_admin
      # sys_boot is always dropped by lxc-start

**Comment by brauner** [comment]
Right, sorry for the late reply and thanks for the detailed analysis. :) Here's the state of things and what we should do:

- `cgfs` is deprecated and we currently have no plans to revive it so it shouldn't be a model for cgroup handling anymore. `cgfsng` has been around for so long that we can safely consider it to be authoritative wrt to `lxc.cgroup.use`.
- The notes for `lxc.cgroup.use` in the `lxc.system.conf` manpage should be adapted to reflect that `lxc.cgroup.use` only addresses controllers in legacy cgroup hierarchies.
- We won't introduce `lxc.cgroup2.use`. Instead at some point we should introduce a per-container config key that allows to specify what cgroups a container should use. Again, separated into `lxc.cgroup` and `lxc.cgroup2`. But I need to come up with a decent naming scheme.
- The `@all` syntax will not be supported by `cgfsng`.

**Comment by brauner** [comment]
I've re-enabled full lxc.cgroup.use support in LXC master, sorry for the delay.
