### ISSUE TITLE
One question about rotate of console log file

### ISSUE THREAD

**Issue by duguhaotian** [lxc/lxc#2088]
https://github.com/lxc/lxc/blob/e7d7dd73d2d16da7acccf16c22c4cb3c1af594eb/src/lxc/commands.c#L1026

Now, if i want to rotate my console log file, I need to call API **lxc_cmd_console_log**. 
This implements, if i want to limit my log file size. I need **a while loop** to check file size, and if log file size is big than limit, then i  call this API to rotate my log file.
Some scenes, I can not limit my log files. For example, when i check size of log file, container writing large logs. And then when i call API to rotate, the real size of log file, maybe is large than my limit.

And, ringbuffer, now , like log file. Better than log file, but just can limit log use disk space.

The big problem is **Now, we can not auto rotate!!!**

Why do not implement rotate of  console log file  at **lxc_console_cb_con** function.
Like below:

`
 int lxc_console_cb_con(int fd, uint32_t events, void *data, struct lxc_epoll_descr *descr)
 {

    .....   ........
    if (fd == console->peer)
        w = lxc_write_nointr(console->master, buf, r);

    w_rbuf = w_log = 0;
    if (fd == console->master) {
        /* write to peer first */
        if (console->peer >= 0)
            w = lxc_write_nointr(console->peer, buf, r);

        /* write to console ringbuffer */
        if (console->buffer_size > 0)
            w_rbuf = lxc_ringbuf_write(&console->ringbuf, buf, r);

        /* write to console log */
        if (console->log_fd >= 0) {
             /* STEP1, check log file size*/
             /* STEP2, if large than limit, begin rotate*/
             w_log = lxc_write_nointr(console->log_fd, buf, r);
        }
    }
    ..... ......

 }
`

Maybe,  we can user ringbuffer to replace console log file.
First, set ringbuffersize as limit of one log file size. For example, we limit one log file is 8KB, and then we set ringbuffersize is 8KB.
Second, if ringbuffer is full, trigger that write buffer data into new log file. Check number of log files, if number bigger than limit of log file number, and then trigger that rotate log file, or just delete the oldest one.

`
 int lxc_console_cb_con(int fd, uint32_t events, void *data, struct lxc_epoll_descr *descr)
 {

    .....   ........
    if (fd == console->peer)
        w = lxc_write_nointr(console->master, buf, r);

    w_rbuf = w_log = 0;
    if (fd == console->master) {
        /* write to peer first */
        if (console->peer >= 0)
            w = lxc_write_nointr(console->peer, buf, r);

        /* write to console ringbuffer */
        if (console->buffer_size > 0) {
            /* STEP1,  check ringbufer used,  if full,  than to write buffer data into log file*/
            /* STEP2,   check number of log files,  if exceed limit, than rotate log file, or delete oldest one*/
            w_rbuf = lxc_ringbuf_write(&console->ringbuf, buf, r);
        }

        /* write to console log */
        if (console->log_fd >= 0) 
             w_log = lxc_write_nointr(console->log_fd, buf, r);
    }
    ..... ......

 }
`

I want to know why do this like now ?  performance? or others?

Thinks!!!!!!

**Comment by brauner** [comment]
On Tue, Jan 16, 2018 at 07:44:01PM -0800, 独孤昊天 wrote:
> https://github.com/lxc/lxc/blob/e7d7dd73d2d16da7acccf16c22c4cb3c1af594eb/src/lxc/commands.c#L1026
> 
> Now, if i want to rotate my console log file, I need to call API **lxc_cmd_console_log**. 
> This implements, if i want to limit my log file size. I need **a while loop** to check file size, and if log file size is big than limit, then i  call this API to rotate my log file.
> Some scenes, I can not limit my log files. For example, when i check size of log file, container writing large logs. And then when i call API to rotate, the real size of log file, maybe is large than my limit.

Right, this is a valid problem but that's what the ringbuffer and the
ringbuffer logfile is for.

> 
> And, ringbuffer, now , like log file. Better than log file, but just can limit log use disk space.

I don't completely understand what you mean. So we basically have three
config items:

lxc.console.buffer.size
lxc.console.buffer.logfile
lxc.console.logfile

The keys in the lxc.console.buffer. namespace do not affect the
lxc.console.logfile key and it should stay this way. For performance
reasons, lxc.console.buffer.logfile is only written to when a api call is
made. I would like it to stay this way for performance reasons and
because users can retrieve the contents of the ringbuffer directly via
the api so the lxc.console.buffer.logfile is not that necessary.

> 
> The big problem is **Now, we can not auto rotate!!!**

Yes, but this only affects the lxc.console.logfile key but I'm not sure
there's something we can do about this. Basically, we have no means of
size-restricting lxc.console.logfile because we don't have a config key
that allows us to set a limit. And having lxc.console.buffer.size imply
a limit of lxc.console.logfile is not the right thing to do since they
are different keys.

> 
> Why do not implement rotate of  console log file  at **lxc_console_cb_con** function.
> Like below:

As I said, we do not know what limit to use.

> 
> `
>  int lxc_console_cb_con(int fd, uint32_t events, void *data, struct lxc_epoll_descr *descr)
>  {
> 
>     .....   ........
>     if (fd == console->peer)
>         w = lxc_write_nointr(console->master, buf, r);
> 
>     w_rbuf = w_log = 0;
>     if (fd == console->master) {
>         /* write to peer first */
>         if (console->peer >= 0)
>             w = lxc_write_nointr(console->peer, buf, r);
> 
>         /* write to console ringbuffer */
>         if (console->buffer_size > 0)
>             w_rbuf = lxc_ringbuf_write(&console->ringbuf, buf, r);
> 
>         /* write to console log */
>         if (console->log_fd >= 0) {
>              /* STEP1, check log file size*/
>              /* STEP2, if large than limit, begin rotate*/
>              w_log = lxc_write_nointr(console->log_fd, buf, r);
>         }
>     }
>     ..... ......
> 
>  }
> `
> 
> Maybe,  we can user ringbuffer to replace console log file.

Replace? No, that doesn't sound right. :)

> First, set ringbuffersize as limit of one log file size. For example, we limit one log file is 8KB, and then we set ringbuffersize is 8KB.
> Second, if ringbuffer is full, trigger that write buffer data into new log file. Check number of log files, if number bigger than limit of log file number, and then trigger that rotate log file, or just delete the oldest one.

How would we do this? Introducing lxc.console.buffer.rotate? @stgraber,
@hallyn, what do you think?

> 
> `
>  int lxc_console_cb_con(int fd, uint32_t events, void *data, struct lxc_epoll_descr *descr)
>  {
> 
>     .....   ........
>     if (fd == console->peer)
>         w = lxc_write_nointr(console->master, buf, r);
> 
>     w_rbuf = w_log = 0;
>     if (fd == console->master) {
>         /* write to peer first */
>         if (console->peer >= 0)
>             w = lxc_write_nointr(console->peer, buf, r);
> 
>         /* write to console ringbuffer */
>         if (console->buffer_size > 0) {
>             /* STEP1,  check ringbufer used,  if full,  than to write buffer data into log file*/
>             /* STEP2,   check number of log files,  if exceed limit, than rotate log file, or delete oldest one*/
>             w_rbuf = lxc_ringbuf_write(&console->ringbuf, buf, r);
>         }
> 
>         /* write to console log */
>         if (console->log_fd >= 0) 
>              w_log = lxc_write_nointr(console->log_fd, buf, r);
>     }
>     ..... ......
> 
>  }
> `
> 
> I want to know why do this like now ?  performance? or others?

Performance.

**Comment by duguhaotian** [comment]
> And, ringbuffer, now , like log file. Better than log file, but just can limit log use disk space.
>  I don't completely understand what you mean. So we basically have three

I mean ringbuffer can only remember log when log size little than lxc.console.buffer.size.  And if don't call API **lxc_cmd_console_log**  or don't close console , the lxc.console.buffer.logfile will never to increase, and lose the old log. So ringbuffer log don't result in  user disk space full.

> The big problem is **Now, we can not auto rotate!!!**
> Yes, but this only affects the lxc.console.logfile key but I'm not sure
> there's something we can do about this. Basically, we have no means of
> size-restricting lxc.console.logfile because we don't have a config key
> that allows us to set a limit. And having lxc.console.buffer.size imply
> a limit of lxc.console.logfile is not the right thing to do since they
> are different keys.

OK, lxc.console.logfile keep all logs of console. And we don't care about consumeof it, just let user to do the limit of it.  is right? thinks!

> Replace? No, that doesn't sound right. :)
>  First, set ringbuffersize as limit of one log file size. For example, we limit one log file is 8KB, and then we set ringbuffersize is 8KB.
>  Second, if ringbuffer is full, trigger that write buffer data into new log file. Check number of log files, if number bigger than limit of log file number, and then trigger that rotate log file, or just delete the oldest one.
> How would we do this? Introducing lxc.console.buffer.rotate? 

I hope that can introducing it, then 
- lxc.console.buffer.size to control ringbuffer to rotate.  When ringbuffer is full, trigger to rotate.
- lxc.console.buffer.rotate to control console log file number

tks!!!

**Comment by brauner** [comment]
@duguhaotian, are you planning on writing the patch?

**Comment by duguhaotian** [comment]
@brauner okay,I plan to write tomorrow!
Thanks!

**Comment by brauner** [comment]
Closed by #2167.
