### ISSUE TITLE
Strange networking delay when starting many containers at once.

### ISSUE THREAD

**Issue by timofurrer** [lxc/lxc#2098]
# Required information

 * Distribution: Ubuntu / debian
 * Distribution version: tested on Ubuntu 17.10 an debian stretch 9.3
 * The output of
   * `lxc-start --version`:  `2.1.0`
   * `lxc-checkconfig`: everything is enabled
   * `uname -a`: `4.13.0-25-lowlatency #29-Ubuntu SMP PREEMPT`
   * `cat /proc/self/cgroup`
   * `cat /proc/1/mounts`

# Issue description

I've encountered a strange behavior when creating and starting multiple containers at once ... 
Once they have the state `RUNNING` (using `lxc-wait`) I sleep for a `10` seconds and then those containers try to run an `apt-get update` and `apt-get install --yes curl`. 

For one container at the time this works perfectly fine. 
If I do the same scenario for multiple containers at the same time the network won't be ready when the `apt-get` starts to run.

I've understood that the `RUNNING` state doesn't mean that the network is ready. That's why I sleep for 10 seconds for now. 

# Steps to reproduce

I was able to reproduce this behavior with the following script:

```bash
#!/bin/bash

mkdir -p logs/

# Create LXC container
create_run_and_update() {
    local name
    name="test-$1"
    lxc-create --name "$name" -t debian -- -r jessie --arch i386 > logs/$name 2>&1
    lxc-start --name "$name" >> logs/$name 2>&1
    lxc-wait --name "$name" --state RUNNING >> logs/$name 2>&1
    sleep 10
    lxc-attach --name "$name" apt update >> logs/$name 2>&1
    lxc-attach --name "$name" -- apt install --yes curl >> logs/$name 2>&1
    ret=$?
    if [ $ret -ne 0 ]; then
        echo "Failed to update container $name"
    else
        echo "Successfully updated container $name"
    fi
}

for i in $(seq "$1"); do
    create_run_and_update "$i" &
done

wait
```

Make sure to run the script as root to create privileged containers.

# State of debugging

What I've noticed is that sometime between `DHCPOFFER` and `DHCPREQUEST` there are more then 10 seconds. 
The system I'm running this on is a debian stretch with nothing else on it except this test.
All containers eventually get an IP address from the `lxc-net` dnsmasq - it just takes a long time ...

Does anyone have an idea why it takes so long to get the IP address?

**Comment by brauner** [comment]
Hm, `lxc-net` ist @stgraber's domain.

**Comment by timofurrer** [comment]
Let me know if you need anything else to reproduce or about the problem we are having.

**Comment by fliiiix** [comment]
I see the same results on my Fedora
```
4.14.13-200.fc26.x86_64 #1 SMP Thu Jan 11 05:43:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by fliiiix** [comment]
> Q: Does the dnsmasq DHCP server probe addresses before allocating
>    them, as recommended in RFC2131?
> 
> A: Yes, dynamically allocated IP addresses are checked by sending an
>    ICMP echo request (ping). If a reply is received, then dnsmasq
>    assumes that the address is in use, and attempts to allocate an
>    different address. The wait for a reply is between two and three
>    seconds. Because the DHCP server is not re-entrant, it cannot serve
>    other DHCP requests during this time. To avoid dropping requests,
>    the address probe may be skipped when dnsmasq is under heavy load.

Source: https://github.com/liquidm/dnsmasq/blob/master/FAQ

Somehow this doesn't scale well when you request multiple addresses over DHCP at once. 
**So setting `---no-ping` helps here.** I think this shouldn't have side effects (except when have a container with a static ip configuration in the dhcp range)

**Comment by timofurrer** [comment]
@fliiiix thanks! This was indeed the bottleneck I was looking for! :beers:
