### ISSUE TITLE
lxc-destroy should destroy btrfs subvolumes

### ISSUE THREAD

**Issue by tailhook** [lxc/lxc#210]
Currently if someone created subvolumes in btrfs-backed container. The container can't be destroyed with lxc-destroy until subvolumes are removed by hand. I believe subvolumes must be removed automatically.

**Comment by UserTaken** [comment]
I see this was resolved for LXD but I'm still having this problem with [LXC 1.1.3-2](https://www.archlinux.org/packages/community/x86_64/lxc/). In my case I have to manually destroy every BTRFS snapshot which is not under the `rootfs` subvolume before being able to destroy the container.

**Comment by UserTaken** [comment]
I'm encountering a similar problem with [LXC 1.1.3-2](https://www.archlinux.org/packages/community/x86_64/lxc/) where I have to manually destroy every BTRFS snapshot which is not under the `rootfs` subvolume before being able to destroy the container.

**Comment by hallyn** [comment]
upstream lxc-destroy has a '-s|--snapshots' argument to delete snapshots.
