### ISSUE TITLE
overlayfs: unable to copy second level snapshot

### ISSUE THREAD

**Issue by timofurrer** [lxc/lxc#2118]
# Required information

 * Distribution: debian
 * Distribution version:  stretch / 9.3
 * The output of
   * `lxc-start --version`: `2.0.7`
   * `lxc-checkconfig`: everything is enabled.
   * `uname -a`: `Linux T-000732319b72 4.9.0-4-rt-amd64 #1 SMP PREEMPT RT Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux` It also happens with a 4.14 kernel.

# Issue description

I have the following situation:
* `/var/lib/lxc` is read-only mounted on the system via NFS
* There are two containers in this `lxcpath` at `/var/lib/lxc` . One is an overlayfs snapshot (created by `lxc-copy`) of the other one. 
   * `original`: original container
   * `level-1-snapshot`: overlayfs snapshot of `original`
* Now I want to create another overlayfs snapshot (`level-2-snapshot`) on top of the already snapshot container with the following command:
```
lxc-copy --snapshot --backingstorage overlay --name level-1-snapshot \
    --newname level-2-snapshot --lxcpath /var/lib/lxc --newpath /.writable/lxc
```

This command then leads to the following error:
```
lxc-copy: utils.c: mkdir_p: 253 Read-only file system - failed to create directory '/var/lib/lxc/level-1-snapshot/delta0'
lxc-copy: bdev/lxcoverlay.c: ovl_rsync: 704 Failed mounting original container fs
lxc-copy: bdev/lxcoverlay.c: ovl_do_rsync: 757 copying overlayfs delta
lxc-copy: bdev/bdev.c: bdev_copy: 388 failed getting pathnames for cloned storage: overlayfs:/var/lib/lxc/original/rootfs:/var/lib/lxc/level-1-snapshot/delta0
lxc-copy: lxccontainer.c: copy_storage: 2867 Error copying storage.
clone failed
```

Why is that? Am I doing something wrong or is this just not supported?

Note: If `/var/lib/lxc` is writeable is working fine.

My guess is that because we mount `/var/lib/lxc` read-only via NFS the overlayfs from `level-1-snapshot` to `original` is obviously not there and re-creating it doesn't work because `level-1-snapshot` is on the read-only mount, too. Does that make any sense?

I assume I would need a way to specify a writeable branch for the `delta` directory used by the copy ..?

**Comment by timofurrer** [comment]
If I run the above mentioned `lxc-copy` command another time, I sometimes get the following error messages instead:

```
lxc-copy: bdev/lxcoverlay.c: ovl_mount: 430 Invalid argument - Overlayfs: Error mounting /var/lib/lxc/original/rootfs onto /var/lib/lxc/level-1-snapshot/rootfs with options upperdir=/var/lib/lxc/level-1-snapshot/delta0,lowerdir=/var/lib/lxc/original/rootfs: Invalid argument.
lxc-copy: bdev/lxcoverlay.c: ovl_rsync: 704 Failed mounting original container fs
lxc-copy: bdev/lxcoverlay.c: ovl_do_rsync: 757 copying overlayfs delta
lxc-copy: bdev/bdev.c: bdev_copy: 388 failed getting pathnames for cloned storage: overlayfs:/var/lib/lxc/original/rootfs:/var/lib/lxc/level-1-snapshot/delta0
lxc-copy: lxccontainer.c: copy_storage: 2867 Error copying storage.
clone failed
```

**Comment by brauner** [comment]
Hm, can you try to reproduce this with current git master or the latest stable release? The storage drivers have been reworked significantly.

**Comment by timofurrer** [comment]
I've compiled https://github.com/lxc/lxc/tree/lxc-2.1.1 myself and it seems to work on a debian stretch 9.3 👍 

Thanks for the hint. Do you know if there are any pre-packed debian packages for stretch for 2.1.1 ?
