### ISSUE TITLE
lxc-start: parse.c: lxc_file_for_each_line: 57 Failed to parse config:

### ISSUE THREAD

**Issue by bryn1u** [lxc/lxc#2121]
Hey guys,
Im trying to run lxc with selinux on Centos 7. I installed and created lxc container with simple command lxc-create -n test -t centos. After that i just added to the:
/var/lib/lxc/test/config
line like belowe:
lxc.selinux.context = system_u:system_r:lxc_t:s0:c22
When i want to run it, im getting error:

> [root@Centos test]# lxc-start -n test
> lxc-start: confile.c: parse_line: 1750 unknown key lxc.selinux.context
> lxc-start: parse.c: lxc_file_for_each_line: 57 Failed to parse config: lxc.selinux.context = system_u:system_r:lxc_t:s0:c22
> 
> lxc-start: lxc_start.c: main: 268 Failed to create lxc_container
Someone can help me ? What am i doing wrong ? I just take it from documentation and it doesn't work :((
Thanks,

**Comment by brauner** [comment]
This seems like you're running an old liblxc version but using new configuration keys. How does your config look like?

**Comment by brauner** [comment]
This has been stale for a long time and without the config file and LXC versions installed we can't really help. So closing.
