### ISSUE TITLE
dev & proc are left mounted under /var/cache/lxc

### ISSUE THREAD

**Issue by Pascal666** [lxc/lxc#2128]
* Distribution: CentOS
 * Distribution version: 7.4.1708 (Core)
 * The output of
   * `lxc-start --version` 1.0.11
   * `uname -a` Linux localhost.localdomain 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

# Issue description

I ran `rm -rf` on `/var/cache/lxc` and lost most of '/dev'.  Turns out lxc-create left both `dev` and `proc` mounted under `/var/cache/lxc`:

    #mount | grep /var/cache/lxc
    devtmpfs on /var/cache/lxc/fedora/x86_64/bootstrap/dev type devtmpfs (rw,nosuid,seclabel,size=74173740k,nr_inodes=18543435,mode=755)
    proc on /var/cache/lxc/fedora/x86_64/bootstrap/proc type proc (rw,relatime)
    proc on /var/cache/lxc/yakkety/rootfs-amd64/proc type proc (rw,relatime)

Please make lxc-create umount everything under `/var/cache/lxc` when it exits.  Thank you.

**Comment by brauner** [comment]
This is not caused by `lxc-create` but by the `Fedora` template I suspect. So if this needs to be changed it needs to be changed in the newly created `lxc-templates` repository.

**Comment by Pascal666** [comment]
If that is the case, then the Ubuntu template has the same bug.  Notice the link under yakkety in my original report.
