### ISSUE TITLE
ZFS: lxc-clone prints misleading message

### ISSUE THREAD

**Issue by neapel** [lxc/lxc#213]
When using `lxc-clone -s -o orig -n new` to clone a container residing on ZFS, it prints the message "could not find any snapshots to destroy; check snapshot names.", I think because [zfs_clone](https://github.com/lxc/lxc/blob/master/src/lxc/bdev.c#L651) calls `zfs destroy` on the new snapshot's name (and expects it to fail) before attempting to create it.

Maybe suppress the output or use another method to check if the snapshot exists first i.e. check if the file `<mountpoint>/.zfs/snapshot/<name>` exists.

**Comment by brauner** [comment]
Should be closed by #1184.
