### ISSUE TITLE
How to mount cgroup on ubuntu when both cap sys_admin and cgns is enabled

### ISSUE THREAD

**Issue by tanyifeng** [lxc/lxc#2132]
# Required information
 * Distribution:
ubuntu
 * Distribution version:
ubuntu 16.04
 * The output of
   * `lxc-start --version`
2.1.0-devel
   * `lxc-checkconfig`

Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.4.0-109-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/blkio
/sys/fs/cgroup/memory
/sys/fs/cgroup/freezer
/sys/fs/cgroup/devices
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/pids
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/cpu,cpuacct

Cgroup v2 mount points:

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities:

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/local/bin/lxc-checkconfig
   * `uname -a`
Linux ubuntu 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`

11:cpu,cpuacct:/user.slice/user-0.slice/session-1541.scope
10:hugetlb:/
9:pids:/user.slice/user-0.slice/session-1541.scope
8:cpuset:/
7:devices:/user.slice/user-0.slice/session-1541.scope
6:freezer:/
5:memory:/user.slice/user-0.slice/session-1541.scope
4:blkio:/user.slice/user-0.slice/session-1541.scope
3:perf_event:/
2:net_cls,net_prio:/
1:name=systemd:/user.slice/user-0.slice/session-1541.scope

   * `cat /proc/1/mounts`
11:cpu,cpuacct:/user.slice/user-0.slice/session-1541.scope
10:hugetlb:/
9:pids:/user.slice/user-0.slice/session-1541.scope
8:cpuset:/
7:devices:/user.slice/user-0.slice/session-1541.scope
6:freezer:/
5:memory:/user.slice/user-0.slice/session-1541.scope
4:blkio:/user.slice/user-0.slice/session-1541.scope
3:perf_event:/
2:net_cls,net_prio:/
1:name=systemd:/user.slice/user-0.slice/session-1541.scope
root@ubuntu:bin# cat /proc/1/mounts
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=8195888k,nr_inodes=2048972,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=1643088k,mode=755 0 0
/dev/sda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=35,pgrp=1,timeout=0,minproto=5,maxproto=5,direct 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0

# Issue description
How to mount cgroup on ubuntu when both cap sys_admin and cgns is enabled

A brief description of what failed or what could be improved.
cgroup is not mounted in container
# Steps to reproduce

 1. Step one
` lxc-create -n alpine1 -t download`
```
Distribution:
alpine
Release:
3.4
Architecture:
amd64
```
 2. Step two
`lxc-start -F -n alpine1 -l DEBUG /bin/ash`
 3. Step three
```
/ # ls /sys/fs/cgroup/
/ #
```
`/sys/fs/cgroup` is empty.
# Information to attach
In my machine, cgroup namespace is supported
```
root@ubuntu:/# ls /proc/self/ns/cgroup
/proc/self/ns/cgroup
```
so when lxc try to mount cgroup, it is skipped by:
[https://github.com/lxc/lxc/blob/master/src/lxc/cgroups/cgfsng.c#L1718](https://github.com/lxc/lxc/blob/master/src/lxc/cgroups/cgfsng.c#L1718)

**Comment by brauner** [comment]
Yeah, this has been something I have been thinking about for a while but never did write the required patch. We made a decision to not mount cgroups ourselves when cgroup namespaces are support since this can now be done safely by the init system itself. Right now we recommend that users either set `lxc.mount.fstab` to a file that lists the cgroup mounts they want or set `lxc.mount.entry`s. However, if you come up with a clever solution that for the default case will defer mounting cgroup namespaces to the init system while also allowing users to explicitly request that cgroups be mounted for them we'll merge it. The catch being that it should not require another config item to be introduced. ;)

**Comment by keloyang** [comment]
It will lead general containers(non system containers) have no cgroup (/sys/fs/cgroup is empty)by default, can we add a option to determine whether to  mount cgroup by lxc itself ?

**Comment by brauner** [comment]
Well, if this is mainly an issue for application containers it wouldn't be a problem to make the cgroup backend aware that this is an application container and in this case have it mount cgroups by default. That is one option.

**Comment by brauner** [comment]
It looks like coming up with some sensible option in `lxc.mount.auto` for the `cgroup` prefix options might make sense. Then lxc could be instructed to mount the cgroups for the container. For example, one could add `cgroup-namespace` or `cgroup-ns` to indicate that if cgroup namespaces are supported then lxc should mount it for the container. You could even add support for `cgroup-ns:rw` and `cgroup-ns:ro`. Is someone up for writing a patch? @hallyn, @stgraber do you have better suggestion on how to do this?

**Comment by keloyang** [comment]
Maybe we don't need cgroup-ns:rw, just cgroup-ns, IIUC,  we have already cgroup:rw .

**Comment by tanyifeng** [comment]
When we start a container with cgroup mounted by `lxc.mount.auto = cgroup:mixed`, we can see path created by lxc in cgroup subsystem, should this be a bugs?

```

root@ubuntu:lcrd# lxc-start alpine1 -F /bin/ash
/ # ls /sys/fs/cgroup/cpuset/lxc/alpine1-1/
cgroup.clone_children            cpuset.effective_cpus            cpuset.memory_migrate            cpuset.mems                      tasks
cgroup.procs                     cpuset.effective_mems            cpuset.memory_pressure           cpuset.sched_load_balance
cpuset.cpu_exclusive             cpuset.mem_exclusive             cpuset.memory_spread_page        cpuset.sched_relax_domain_level
cpuset.cpus                      cpuset.mem_hardwall              cpuset.memory_spread_slab        notify_on_release
/ #

```
I found this is because lxc add `container_cgroup` path when bind mount cgroup to container [https://github.com/lxc/lxc/blob/master/src/lxc/cgroups/cgfsng.c#L2063](https://github.com/lxc/lxc/blob/master/src/lxc/cgroups/cgfsng.c#L2063)

**Comment by tanyifeng** [comment]
Another question is, if we don't have `cgroup_root` path `/sys/fs/cgroup` in container rootfs, we will get error: no such device when [safe_mount tmpfs](https://github.com/lxc/lxc/blob/master/src/lxc/cgroups/cgfsng.c#L2017)

**Comment by brauner** [comment]
> When we start a container with cgroup mounted by lxc.mount.auto = cgroup:mixed, we can see path created by lxc in cgroup subsystem, should this be a bug?

If you're talking about a system that doesn't have cgroup namespaces then I don't think so. Because `/proc/<pid>/cgroup` from inside the container will show you the cgroup you're in as seen from the host:

```
/ # cat /proc/self/cgroup
12:perf_event:/lxc/a9
11:blkio:/lxc/a9
10:freezer:/lxc/a9
9:memory:/lxc/a9
8:pids:/lxc/a9
7:hugetlb:/lxc/a9
6:cpuset:/lxc/a9
5:net_cls,net_prio:/lxc/a9
4:cpu,cpuacct:/lxc/a9
3:devices:/lxc/a9
2:rdma:/lxc/a9
1:name=systemd:/lxc/a9
0::/lxc/a9
```
so you already know what cgroup you are in. That's simply information leak that we cannot prevent without cgroup namespaces.
If you're talking about a system that has cgroup namespaces then:
1. you shouldn't bind-mount the cgroup from the host. Instead you should simply do what `mount_cgroup_cgns_supported()` does.

**Comment by brauner** [comment]
> Another question is, if we don't have cgroup_root path /sys/fs/cgroup in container rootfs

You're saying if the `/sys/fs/cgroup` directory doesn't exist? There should probably be code to create it.

**Comment by brauner** [comment]
> Maybe we don't need cgroup-ns:rw, just cgroup-ns, IIUC, we have already cgroup:rw .

What I expect right now without having thought too deeply about it is an option:

    lxc.mount.auto = cgroup-ns

which will cause `mount_cgroup_cgns_supported()` to be executed unconditionally. Of course you should still return a sensible error when `!cgns_supported()` and `cgroup-ns` is specified. I expect there needs to be a new internal flag `LXC_AUTO_CGROUP_NS_RW`.

**Comment by brauner** [comment]
Are you planning on working on this?

**Comment by keloyang** [comment]
@brauner I have a pr https://github.com/lxc/lxc/pull/2136, please take a look, thanks.

**Comment by brauner** [comment]
@keloyang, thanks! I commented on your PR.

**Comment by brauner** [comment]
Closed in https://github.com/lxc/lxc/pull/2170 and https://github.com/lxc/lxc/pull/2175/commits/6812d83301b652d3432775402a31089c093f4508 .
