### ISSUE TITLE
Mismatch about kernel modules

### ISSUE THREAD

**Issue by asarubbo** [lxc/lxc#2146]
This issue is at half between lxc and lxd.

On gentoo, we have a system that checks the kernel support before compile something.
While lxc-checkconfig does not show missing modules, the ebuild warns me about:

for LXC:
CONFIG_INET_UDP_DIAG

for LXD:
DUMMY: needed for network commands
NET_IPGRE: needed for network commands
NET_IPGRE_DEMUX: needed for network commands
NET_IPIP: needed for network commands
VXLAN: needed for network commands

The question is: are we checking for useless things or lxc-checkconfig should check something else?
Thanks

lxc-2.1.1
lxd-2.21

**Comment by brauner** [comment]
That's all very specific stuff. If lxc-checkconfig doesn't complain you should usually be good to run containers. You should look at the kernel config documentation and see if there's a specific module you definitely need to have. VXLAN is something that is supported so if you wan't that you should probably add it.
