### ISSUE TITLE
Mute "Failed to reset devices.list"

### ISSUE THREAD

**Issue by drydenp** [lxc/lxc#2156]
"Feb 06 13:46:40 container systemd[1]: systemd-journal-flush.service: Failed to reset devices.list: Operation not permitted"

The well known line only started appearing with LXC 2.0 (on my Debian 8 system using backports), I currently have 2 containers running started with different versions of LXC, and the 1.0 version does not have those lines.

So how can I get the LXC 1.0 behaviour back? Even if that means a 'security risk' in some way?

**Comment by brauner** [comment]
Well, you can likely go **insecure** by doing `lxc.cgroup.devices.allow=a`.

**Comment by drydenp** [comment]
That worked! But what device would I *specifically* need to allow to enable it?

**Comment by brauner** [comment]
On Sun, Feb 11, 2018 at 07:35:29PM +0000, Dryden Personalis wrote:
> That worked! But what device would I *specifically* need to allow to enable it?

No idea. LXC doesn't know what devices systemd wants. You'd have to
check and then enable them.

**Comment by drydenp** [comment]
I am just flabbergasted for a moment that lennart poettering uses 8-space indents.

**Comment by drydenp** [comment]
It actually tries apparently to set the entire cgroup-context of every unit to "a" so I am not sure if allowing singular devices will help. But you can probably turn the messages to debug level by setting the entire cgroup mount to ro (instead of mixed).

**Comment by brauner** [comment]
Cool, closing this then.

**Comment by drydenp** [comment]
Right, thanks.

The problem is more that systemd (and journald) is very verbose and then they have a default policy to log everything (and show everything) at the same time, creating numerous issues like this all the time.

E.g. there have also been plenty of systemd-tmpfiles verbosity annoyances; then Lennart changes something in Lennart Tool #1 from "warning" to "debug", while Lennart Tool #2 has no option to turn off debug messages by default. You gotta appreciate the "good cop, bad cop" fun right there.

**Comment by drydenp** [comment]
I'm sorry, I have had it with the bad treatment by open source people. Not you.

But I will stop contributing to open source. I'll see ya.
