### ISSUE TITLE
Alpine images are no longer available for armhf

### ISSUE THREAD

**Issue by BKPepe** [lxc/lxc#2161]
# Issue description

Recently what I found is alpine images are no longer available for armhf.

# Steps to reproduce

Go to this website https://uk.images.linuxcontainers.org/images/alpine/
where you can see armhf builds are gone.

# Curious things

I went to IRC channels on Freenode

#alpine-linux: 
1) Where they told me that they don't have influence over what people create and publish on Linuxcontainers.org and for LXC it's better to go with [chroot](https://wiki.alpinelinux.org/wiki/Installing_Alpine_Linux_in_a_chroot) and or there is another way, where somebody needs to add busybox-initscripts in your container.

2) Tried to use their root minimal filesystem, but it's for docker.
In LXC procd is not mounted and you need to mountd procfs, sys and manually setup network.

#lxcontainers: No respond so far except I should create an issue here. Hopefully, it will not be rejected.

Would it be possible please bring them back? :)

**Comment by brauner** [comment]
@stgraber is the master of all things templates and image server related. :) Please also note that we're in the process to replace the template system with a new project https://github.com/lxc/distrobuilder . The goal is to be as upstream friendly and possible and use the recommended way to bootstrap/create a pristine root file system for any given distribution. We're also supporting all architectures that the distro in question supports.

**Comment by stgraber** [comment]
I don't recall us ever building alpine armhf images before

**Comment by brauner** [comment]
They are now rebuilt again! Thanks!
