### ISSUE TITLE
Failed to remove interface "vethxxxxxx" from host: Operation not permitted.

### ISSUE THREAD

**Issue by ss-17** [lxc/lxc#2176]
Hi.

I am running a simple standard setup of unprivileged Debian Jessie on Jessie. Everything else seems to be fine but I just can't get rid of these two warnings in the log when the container started and stopped. Will appreciate any pointers. Thanks.

On Starting:

`WARN     lxc_start - start.c:signal_handler:322 - Invalid pid for SIGCHLD. Received pid 3207, expected pid 3214.`

On Stopping:

`WARN     lxc_conf - conf.c:lxc_delete_network:3028 - Failed to remove interface "veth94IM9B" from host: Operation not permitted.`

The interface does get deleted though.

lxc-start --version
2.0.7

uname -a
Linux server 4.9.0-0.bpo.5-amd64 #1 SMP Debian 4.9.65-3+deb9u2~bpo8+1 (2017-01-05) x86_64 GNU/Linux

**Comment by ss-17** [comment]
Looks like the first warning has been already removed in newer versions:

https://github.com/lxc/lxc/commit/af4c0f05fcf642a95933454b9c438cb03fa1dce6

But I still ponder over that interface deletion message.

**Comment by brauner** [comment]
The latter problem should be gone in master as well. :)

**Comment by brauner** [comment]
If you can reproduce in master comment here and we'll fix it.
