### ISSUE TITLE
Can't compile LXC 2.0.9 or 2.1.1 on Amazon Linux v1

### ISSUE THREAD

**Issue by xeron** [lxc/lxc#2178]
# Required information

 * Distribution: Amazon Linux
 * Distribution version: v1 (2017.03)
 * The output of
   * `uname -a`
```Linux ip-172-22-10-154 4.9.43-17.39.amzn1.x86_64 #1 SMP Fri Sep 15 23:39:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux```

# Issue description

Can't compile LXC 2.0.9 or 2.1.1 on Amazon Linux v1. Compilation fails with:

```
In file included from utils.h:36:0,
                 from console.c:46:
/usr/include/linux/loop.h:47:2: error: unknown type name '__u64'
  __u64     lo_device;   /* ioctl r/o */
  ^
/usr/include/linux/loop.h:48:2: error: unknown type name '__u64'
  __u64     lo_inode;   /* ioctl r/o */
  ^
/usr/include/linux/loop.h:49:2: error: unknown type name '__u64'
  __u64     lo_rdevice;   /* ioctl r/o */
  ^
/usr/include/linux/loop.h:50:2: error: unknown type name '__u64'
  __u64     lo_offset;
  ^
/usr/include/linux/loop.h:51:2: error: unknown type name '__u64'
  __u64     lo_sizelimit;/* bytes, 0 == max available */
  ^
/usr/include/linux/loop.h:56:2: error: unknown type name '__u8'
  __u8     lo_file_name[LO_NAME_SIZE];
  ^
/usr/include/linux/loop.h:57:2: error: unknown type name '__u8'
  __u8     lo_crypt_name[LO_NAME_SIZE];
  ^
/usr/include/linux/loop.h:58:2: error: unknown type name '__u8'
  __u8     lo_encrypt_key[LO_KEY_SIZE]; /* ioctl w/o */
  ^
/usr/include/linux/loop.h:59:2: error: unknown type name '__u64'
  __u64     lo_init[2];
  ^
make[3]: *** [liblxc_la-console.lo] Error 1
```

I can compile 2.0.7 without any issues. Didn't try 2.0.8.

# Steps to reproduce

1. Boot a host with Amazon Linux 2017.03
2. git clone lxc and switch to `lxc-2.0.9` or `lxc-2.1.1` tag
3. install dependencies:
```
yum install kernel-headers libcap-devel libcgroup-devel libselinux-devel libtool doxygen docbook-utils docbook2X
```
4. run `./autogen.sh`
5. run
```
./configure --prefix=/usr --libdir=/usr/lib64 --sysconfdir=/etc \
    --localstatedir=/var --docdir=/usr/share/doc/lxc-2.1.1 \
    --with-distro=redhat --with-init-script=sysvinit \
    --enable-doc --enable-api-docs --disable-silent-rules \
    --disable-rpath --disable-apparmor --disable-cgmanager \
    --enable-selinux
```
6. run `make -j2`

Workaround:

Adding `CFLAGS='-include /usr/include/linux/types.h'` fixes the issue but doesn't feel like correct solution.

```
./configure CFLAGS='-include /usr/include/linux/types.h' \
    --prefix=/usr --libdir=/usr/lib64 --sysconfdir=/etc \
    --localstatedir=/var --docdir=/usr/share/doc/lxc-2.1.1 \
    --with-distro=redhat --with-init-script=sysvinit \
    --enable-doc --enable-api-docs --disable-silent-rules \
    --disable-rpath --disable-apparmor --disable-cgmanager \
    --enable-selinux
```

Possibly related issues:

https://bugs.freedesktop.org/show_bug.cgi?id=84633
https://github.com/NVIDIA/libnvidia-container/issues/12

**Comment by brauner** [comment]
I suspect it's as trivial as including `linux/types.h` in `utils.h`.

**Comment by brauner** [comment]
Added a commit on one of my bugfix branches. If you want you can grab it and see if that fixes your issue.

**Comment by xeron** [comment]
Thanks, I'll test it later today.

But I think I actually tried it and it didn't help, but I was putting this line into different position (before all other includes).

**Comment by xeron** [comment]
@brauner @stgraber it doesn't help. I took the latest master and it fails with the same error:

```
In file included from utils.h:36:0,
                 from commands.c:52:
/usr/include/linux/loop.h:47:2: error: unknown type name '__u64'
  __u64     lo_device;   /* ioctl r/o */
  ^
/usr/include/linux/loop.h:48:2: error: unknown type name '__u64'
  __u64     lo_inode;   /* ioctl r/o */
  ^
/usr/include/linux/loop.h:49:2: error: unknown type name '__u64'
  __u64     lo_rdevice;   /* ioctl r/o */
  ^
/usr/include/linux/loop.h:50:2: error: unknown type name '__u64'
  __u64     lo_offset;
  ^
/usr/include/linux/loop.h:51:2: error: unknown type name '__u64'
  __u64     lo_sizelimit;/* bytes, 0 == max available */
  ^
/usr/include/linux/loop.h:56:2: error: unknown type name '__u8'
  __u8     lo_file_name[LO_NAME_SIZE];
  ^
/usr/include/linux/loop.h:57:2: error: unknown type name '__u8'
  __u8     lo_crypt_name[LO_NAME_SIZE];
  ^
/usr/include/linux/loop.h:58:2: error: unknown type name '__u8'
  __u8     lo_encrypt_key[LO_KEY_SIZE]; /* ioctl w/o */
  ^
/usr/include/linux/loop.h:59:2: error: unknown type name '__u64'
  __u64     lo_init[2];
  ^
make[3]: *** [liblxc_la-commands.lo] Error 1
```

**Comment by xeron** [comment]
@brauner @stgraber could you please reopen this issue?

**Comment by brauner** [comment]
@xeron, any chance I can access such a system?

**Comment by xeron** [comment]
@brauner nope, sorry, it's company private cloud with restrictions and access protection and VPN etc etc.

But if you have AWS account you should be able to boot a host with their Amazon Linux 2017.03.

May be this will help? – https://hub.docker.com/_/amazonlinux/ – I didn't try it, just fast googling.

**Comment by flx42** [comment]
[Been there, done that](https://github.com/NVIDIA/libnvidia-container/issues/12) cc @3XX0 

`libcap-devel` is very ancient on Amazon Linux 1 (2.16), so it doesn't include this commit:
https://git.kernel.org/pub/scm/linux/kernel/git/morgan/libcap.git/commit/?id=012bca3265ed0d84b57531919a390645052d810e
This commit had `#define _LINUX_TYPES_H`

**Comment by brauner** [comment]
@flx42 excellent. :) Thanks!

**Comment by xeron** [comment]
Thanks! I'll test this change on Monday.

**Comment by brauner** [comment]
On Wed, Mar 07, 2018 at 11:57:54PM +0000, Ivan Larionov wrote:
> Ok, sorry for the delay, I can confirm that the latest `master` compiles on Amazon Linux v1.

No worries. Thanks for the work everyone. :)

Christian
