### ISSUE TITLE
lxc-oci: improve CMD parsing

### ISSUE THREAD

**Issue by brauner** [lxc/lxc#2195]
When e.g. faced with something like this:

    CMD ["nginx", "-g", "daemon off;"]

then `lxc.execute.cmd` should be:

    lxc.execute.cmd = 'nginx -g 'daemon off;''

instead of

    lxc.execute.cmd = 'nginx -g daemon off;'

**Comment by hallyn** [comment]
Yup. I'll assign myself, but am not working on it right now so feel free to 'steal' it from me @flx42  :)
