### ISSUE TITLE
Problem with a route 192.0.0.0/8

### ISSUE THREAD

**Issue by ThibaudDauce** [lxc/lxc#220]
Hi,

I just set up two LXC container on my new Debian server and when I type "route -n" I have a weird line :
192.0.0.0       0.0.0.0         255.0.0.0       U     0      0        0 eth0

This line cause a problem with public ip in 192.xx.xx.xx like github.com (192.30.252.131). To fix the problem, I must type :
route del -net 192.0.0.0/8 dev eth0

My file /var/lib/lxc/CT101/config in my host
...
 # Network
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = br0
lxc.network.name = eth0
lxc.network.ipv4 = 192.168.0.101
lxc.network.veth.pair = vethCT101

In my container :
cat /etc/network/interfaces 
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
        address 192.168.0.101
        netmask 255.255.255.0
        broadcast 192.168.0.255
        gateway 192.168.0.1

root@CT101:~# ifconfig
eth0      Link encap:Ethernet  HWaddr fe:2a:e2:72:69:2f  
          inet adr:192.168.0.101  Bcast:192.255.255.255  Masque:255.0.0.0
          adr inet6: fe80::fc2a:e2ff:fe72:692f/64 Scope:Lien
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1334 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1819 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:1000 
          RX bytes:118459 (115.6 KiB)  TX bytes:2401690 (2.2 MiB)
...

Could you explain this to me ?

Thanks a lot

**Comment by KIVagant** [comment]
Thank you, @stgraber! I write down my message, maybe somebody will get same problem and will find this issue too:

I had trouble with github.com (because his IP starts from '192') inside container and iptables showed to me this problematic route:
```
ip r l
192.0.0.0/8 dev eth0  proto kernel  scope link  src 192.168.1.21
```

And, when I was run ```composer install```, I saw this: ```unable to connect to github.com: No route to host```

So, I changed IP my /var/lib/lxc/mycontainer/config as stated above, restarted it and now all is ok!
