### ISSUE TITLE
Unable to run lxc-autostart as a systemd .service for non-root

### ISSUE THREAD

**Issue by Aydan** [lxc/lxc#2204]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Debian
 * Distribution version: Stretch
 * The output of
   * `lxc-start --version`
     2.0.7
   * `lxc-checkconfig`
```
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.9.0-6-amd64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: enabled
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled
```
   * `uname -a`
Linux hyperion 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u2 (2018-02-21) x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
10:net_cls,net_prio:/
9:devices:/user.slice
8:memory:/user/lxc/0
7:cpuset:/
6:freezer:/user/lxc/0
5:pids:/user.slice/user-1001.slice/session-272.scope
4:cpu,cpuacct:/user.slice
3:blkio:/user.slice
2:perf_event:/
1:name=systemd:/user.slice/user-1001.slice/session-272.scope
   * `cat /proc/1/mounts`
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=4015452k,nr_inodes=1003863,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=805632k,mode=755 0 0
root_pool/root / zfs rw,relatime,xattr,noacl 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=9951 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
/dev/md0 /boot ext4 rw,relatime,data=ordered 0 0
data_pool/lxc-containers /var/lib/lxc-containers zfs rw,xattr,noacl 0 0
data_pool/lxc-containers/users /var/lib/lxc-containers/users zfs rw,xattr,noacl 0 0
data_pool/lxc-containers/users/lxc /var/lib/lxc-containers/users/lxc zfs rw,xattr,noacl 0 0
data_pool/lxc-containers/users/lxc/debian-stretch-base /var/lib/lxc-containers/users/lxc/debian-stretch-base zfs rw,xattr,noacl 0 0
data_pool/lxc-containers/users/lxc/mosquitto /var/lib/lxc-containers/users/lxc/mosquitto zfs rw,xattr,noacl 0 0
data_pool/lxc-containers/users/lxc/openhab /var/lib/lxc-containers/users/lxc/openhab zfs rw,xattr,noacl 0 0
data_pool/lxc-containers/users/lxc/openvpn /var/lib/lxc-containers/users/lxc/openvpn zfs rw,xattr,noacl 0 0
data_pool /zfs_pools/data zfs rw,xattr,noacl 0 0
root_pool /zfs_pools/root_pool zfs rw,noatime,xattr,noacl 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=805628k,mode=700,uid=1000,gid=1000 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
tmpfs /run/user/1001 tmpfs rw,nosuid,nodev,relatime,size=805628k,mode=700,uid=1001,gid=1001 0 0
tmpfs /run/user/111 tmpfs rw,nosuid,nodev,relatime,size=805628k,mode=700,uid=111,gid=113 0 0

# Issue description
unable to start containers of user lxc via the following systemd .service file:
```
[Unit]
Description=Autostart lxc containers of user LXC
Documentation=man:lxc-autostart
After=systemd-networkd.service

[Service]
Type=oneshot
User=lxc
Group=lxc
ExecStart=/home/lxc/start-containers.sh
RemainAfterExit=true
StandardOutput=journal

[Install]
WantedBy=multi-user.target
```
and the following shell script:
```
#!/bin/bash
#env
lxc-autostart
```

A brief description of what failed or what could be improved.
journalctl -xe shows the following:
```
Mar 04 20:33:42 hyperion systemd[1]: Starting Autostart lxc containers of user LXC...
-- Subject: Unit lxc-autostart-user-lxc.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit lxc-autostart-user-lxc.service has begun starting up.
Mar 04 20:33:48 hyperion start-containers.sh[20301]: Error starting container: openvpn
Mar 04 20:33:48 hyperion systemd[1]: Started Autostart lxc containers of user LXC.
-- Subject: Unit lxc-autostart-user-lxc.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit lxc-autostart-user-lxc.service has finished starting up.
--
-- The start-up result is done.
```
# Steps to reproduce

 1. Create unprivileed container for non-root user
 2. Set lxc.start.auto = 1 for the container
 3. add .service file to run lxc-autostart for the user
 4. start the service
 5. look into journal for error (journalctl -xe)

# Information to attach
content of container log file:
```
      lxc-start 20170224163037.215 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1949 - No such file or directory - Error setting devices.allow to c 10:200 rwm for openvpn
      lxc-start 20170224163037.217 ERROR    lxc_start - start.c:lxc_spawn:1236 - Failed to setup the devices cgroup for container "openvpn".
      lxc-start 20170224163037.232 ERROR    lxc_start - start.c:__lxc_start:1346 - Failed to spawn container "openvpn".
      lxc-start 20170224163037.618 ERROR    lxc_start_ui - tools/lxc_start.c:main:366 - The container failed to start.
      lxc-start 20170224163037.619 ERROR    lxc_start_ui - tools/lxc_start.c:main:370 - Additional information can be obtained by setting the --logfile and --logpriority options.
```

**Comment by brauner** [comment]
Can you try with master, please. This requires invasive cgroup code changes to make this work. If this issue still persists, please re-open.
