### ISSUE TITLE
systemd-journal hangs during unprivileged container shutdown resulting in sigkill after 60s on debian jessie

### ISSUE THREAD

**Issue by livingstonese** [lxc/lxc#2205]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Debian
 * Distribution version: Jessie 8.7
 * The output of
   * `lxc-start --version` - 2.0.6
   * `lxc-checkconfig`
```
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-3.16.0-4-amd64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: enabled
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```
   * `uname -a`
`Linux megh-fcp-image-builder-worker-ig-2-6055128 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux`
   * `cat /proc/self/cgroup`
```
9:perf_event:/
8:blkio:/
7:net_cls,net_prio:/
6:freezer:/
5:devices:/
4:memory:/
3:cpu,cpuacct:/
2:cpuset:/
1:name=systemd:/system.slice/ssh.service
```
   * `cat /proc/1/mounts`
```
rootfs / rootfs rw 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,relatime,size=10240k,nr_inodes=9296098,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,relatime,size=14877100k,mode=755 0 0
/dev/vda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=23,pgrp=1,timeout=300,minproto=5,maxproto=5,direct 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
tmpfs /usr/local/tmpfs/lxc tmpfs rw,relatime,size=47185920k 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
```

# Issue description

When using unprivileged containers created as root, issuing a lxc-stop with --nokill to a running container results in the systemd-journal process hanging. All processes except systemd-journal and systemd are terminated inside the container. In case lxc-stop is issued without --nokill, the container is sent sigkill after 60s as mentioned in the man pages. This issue is observed in systemd version 230-7~bpo8+2 which is part of the jessie backports repo.
This behaviour is not seen when container is run as privileged container.

> Why was systemd upgraded from 215-17+deb8u7 to 230-7~bpo8+2?

This was done because as mentioned by @hallyn's [comment](https://github.com/lxc/lxc/issues/979#issuecomment-214440488) in #979, the container startup was blocked for 25 seconds inside the [loopback_setup function](https://github.com/systemd/systemd/blob/v215/src/core/main.c#L1565). We had identified this by running strace on lxc-start. The container came up successfully though.
After upgrading, the issue with container startup was fixed. Before upgrading systemd, there was no issue during container shutdown. 

# Steps to reproduce

 1. Create and start the container using the download template
`lxc-create -t download -n p1 -f conf -- -d debian -r jessie -a amd64 --keyserver hkp://p80.pool.sks-keyservers.net:80`

The contents of the conf file are
```
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:xx:xx:xx
lxc.id_map = u 0 1000000 65536
lxc.id_map = g 0 1000000 65536
```

`lxc-start -n p1 -o /tmp/log -l DEBUG`

 2. Wait for container systemd to finish booting. systemd-analyze reports the time taken to boot. This usually takes around 10-15s.
```
/home/livingstone.se# lxc-attach -n p1 systemd-analyze
Startup finished in 15.097s (userspace) = 4month 2w 4d 8h 57min 38.315s
```

 3. Upgrade systemd package(215-17+deb8u7) to version 230-7~bpo8+2 available in jessie-backports
`apt-get update; apt-get install -y -t jessie-backports systemd`

 4. Shutdown the container
```
# lxc-stop -n p1 --nokill
# echo $?
1
```

 5. List containers
```
# lxc-ls -f
NAME STATE   AUTOSTART GROUPS IPV4 IPV6
p1   RUNNING 0         -      -    -
```

 6. List processes running on the container
```
# lxc-info -n p1 | grep PID
PID:            23855

# pstree -p 23855
systemd(23855)---systemd-journal(24114)
```

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [x] [container log](https://github.com/lxc/lxc/files/1784381/container_log.txt) (The <log> file from running `lxc-start -n <c> -o <log> -l DEBUG`)
 - [x] [the containers configuration file](https://github.com/lxc/lxc/files/1784313/container_conf.txt)

**Comment by livingstonese** [comment]
Why was systemd upgraded from 215-17+deb8u7 to 230-7~bpo8+2?
This was done because as mentioned by @hallyn's [comment](https://github.com/lxc/lxc/issues/979#issuecomment-214440488) in #979, the container startup was blocked for 25 seconds inside the [loopback_setup function](https://github.com/systemd/systemd/blob/v215/src/core/main.c#L1565). We had identified this by running strace on lxc-start. The container came up successfully though.
After upgrading the issue with container startup was fixed. Before upgrading systemd, there was no issue during container shutdown.

**Comment by brauner** [comment]
On Wed, Mar 07, 2018 at 06:33:56AM +0000, Livingstone wrote:
> Why was systemd upgraded from 215-17+deb8u7 to 230-7~bpo8+2?
> This was done because as mentioned by @hallyn's [comment](https://github.com/lxc/lxc/issues/979#issuecomment-214440488) in #979, the container startup was blocked for 25 seconds inside the [loopback_setup function](https://github.com/systemd/systemd/blob/v215/src/core/main.c#L1565). We had identified this by running strace on lxc-start. The container came up successfully though.
> After upgrading the issue with container startup was fixed. Before upgrading systemd, there was no issue during container shutdown. 

This very much smells like a systemd bug and not a LXC bug. But, if you
could try and reproduce this with a newer version of LXC - preferably
current git master - that would be good. Or, if that's easer try and
reproduce with a newer version of systemd.

Christian

**Comment by livingstonese** [comment]
@brauner Thanks for pointing it out. I tried reproducing the bug in a debian stretch(systemd version 232) unprivileged container on the same host(lxc version 2.0.6). Clean shutdown is working fine on the debian stretch container with systemd version 232. So this indeed looks like a bug in systemd which is fixed now in newer versions of systemd.
