### ISSUE TITLE
Question: Some confusion about lxc-test-apparmor

### ISSUE THREAD

**Issue by csqshz** [lxc/lxc#2206]
I have some confusion about source code of lxc-test-apparmor defined in 'lxc/src/tests/aa.c'.

# Required information

 * Distribution: None
 * Distribution version: None
 * The output of
   * `lxc-test-apparmor`
```
passed with /sys/kernel/uevent_helper
passed with /proc/sys/fs/file-nr
failed - opened /sys/kernel/mm/ksm/pages_to_scan
```
   * `ls -l /sys/kernel/uevent_helper`
   * `ls -l /sys/kernel/mm/ksm/pages_to_scan`
```
root@intel-x86-64:# ls -l /sys/kernel/uevent_helper    
ls: cannot access '/sys/kernel/uevent_helper': No such file or directory
root@intel-x86-64:# ls -l /sys/kernel/mm/ksm/pages_to_scan 
-rw-r--r-- 1 root root 4096 Mar  6 19:17 /sys/kernel/mm/ksm/pages_to_scan
```
# Issue description
As shown above, /sys/kernel/mm/ksm/pages_to_scan is exist, and can be opened. But error message prompts that fail to open it.
I refer to source code lxc/src/tests/aa.c, branch master and older version.
```
108 char *files_to_deny[] = {
109                 "/sys/kernel/uevent_helper",
110                 "/proc/sys/fs/file-nr",
111                 "/sys/kernel/mm/ksm/pages_to_scan",
112                 "/proc/sys/kernel/sysrq",
113                 NULL };

```
```
115 static bool test_aa_policy(struct lxc_container *c)
116 {
117         int i, ret;
118 
119         for (i = 0; files_to_deny[i]; i++) {
120                 ret = do_test_file_open(c, files_to_deny[i]);
121                 if (ret < 0) {
122                         fprintf(stderr, "attach failed; skipping test\n");
123                         return true;
124                 }
125                 if (ret > 0) {
126                         fprintf(stderr, "failed - opened %s\n",
127                                         files_to_deny[i]);
128                         return false;
129                 }
130                 fprintf(stderr, "passed with %s\n", files_to_deny[i]);
131         }
......

```
```
 63 static int do_test_file_open(struct lxc_container *c, char *fnam)
 64 {
 65         int fret = -1;
 66         int ret;
 67         pid_t pid;
 68         int pipefd[2];
 69         char result[1024];
 70         lxc_attach_options_t attach_options = LXC_ATTACH_OPTIONS_DEFAULT;
 71 
 72         ret = pipe(pipefd);
 73         if (ret < 0) {
 74                 fprintf(stderr, "pipe failed %d\n", ret);
 75                 return fret;
 76         }
 77         attach_options.stdout_fd = pipefd[1];
 78         attach_options.attach_flags &= ~(LXC_ATTACH_LSM_EXEC|LXC_ATTACH_DROP_CAPABILITIES);
 79         attach_options.attach_flags |= LXC_ATTACH_LSM_NOW;
 80         ret = c->attach(c, test_attach_write_file, fnam, &attach_options, &pid);
......
 85 
 86         ret = read(pipefd[0], result, sizeof(result)-1);
 87         if (ret < 0) {
 88                 fprintf(stderr, "read failed %d\n", ret);
 89                 goto err2;
 90         }
 91 
 92         fret = 1;
 93         if (strncmp(result, "no", 2) == 0)
 94                 fret = 0;
......
101         return fret;
102 }

```
```
 41 static int test_attach_write_file(void* payload)
 42 {
 43         char *fnam = payload;
 44         FILE *f;
 45 
 46         f = fopen(fnam, "w");
 47         if (f) {
 48                 printf("yes\n");
 49                 fclose(f);
 50                 fflush(NULL);
 51                 return 1;
 52         }
 53         printf("no\n");
 54         fflush(NULL);
 55         return 0;
 56 }

```
Line46-48: If open interfaces successfully listed in files_to_deny[], Line108, printf 'yes' into pipe[1]. 
Line86: And then pipe[0] reads out 'yes'.
Line92-101: If result is 'yes', do_test_file_open() will return 1.
Line125-128: If the return of do_test_file_open() is 1, then fprintf( failed open).
So can anyone tell me why files listed in files_to_deny[] exit but print fail.

Thanks.

**Comment by csqshz** [comment]
Dose it mean that I should unenable the files listed in files_to_deny[], when using lxc-test-apparmor ?

**Comment by csqshz** [comment]
I use the same  lxc-test-apparmor on Ubuntu16.04. And part of files listed in files_to_deny[] also exit in Ubunut system, but the result is successful.

**Comment by hallyn** [comment]
Yes, "files_to_deny[]" means files for which open should be denied.

So the bug here is that you are able to open it, but should not be able to.  This could be a bug in the apparmor policy or the apparmor kernel module.

**Comment by hallyn** [comment]
On which system does it fail?  What does 'uname -a' and  'aa-status' show there?

**Comment by hallyn** [comment]
On Thu, Mar 08, 2018 at 02:20:24AM +0000, csqshz wrote:
> @hallyn 
> My system is based on yocto-2.4 which is based on linux-4.12. 
> ```
> root@intel-x86-64:# uname -a
> Linux intel-x86-64 4.12.19-yocto-standard #3 SMP PREEMPT Tue Mar 6 21:03:59 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
> ```
>  4.12.19-yocto-standard is yocto's kernel version based on linux-4.12 .
> Here is my kernel config.
> [config.txt](https://github.com/lxc/lxc/files/1791573/config.txt)

Your kernel config has:  # CONFIG_SECURITY_APPARMOR is not set

> Now, what I'm confused about is what differences between Ubuntu1604 and my system affect the result.
> /sys/kernel/mm/ksm/pages_to_scan exits in Ubuntu and my system at the same time. And I only executed the same file, lxc-test-apparmor, compiled by the same gcc. But my system failed.
> 
> Sorry I don't know what is the mean of 'aa-status'.

Your system doesn't have apparmor.  That's why lxc-test-apparmor
fails.

-serge

**Comment by brauner** [comment]
Closing as this is not a LXC bug.
