### ISSUE TITLE
How to make function setproctitle work?

### ISSUE THREAD

**Issue by lifeng68** [lxc/lxc#2207]
Hi, my kernel version is 4.1.12 and  user namespaces and checkpoint restore enabled.
But when i started the container, there will be an info.
` utils.c:setproctitle:1523 - setting cmdline failed - Invalid argument`
And the cmdline had not been changed to '[lxc monitor]...'.
I want to make `setproctitle ` work, any other things should i to modify?
Thanks a lot.

**Comment by brauner** [comment]
@lifeng68 is this an `x86_64` architecture or something else?

**Comment by lifeng68** [comment]
@brauner the architecture is `aarch64 `, is it related to architecture ?

**Comment by brauner** [comment]
Seems to be the kernel version.

```
root@buildd08:~# uname -a
Linux buildd08 4.13.0-19-generic #22~16.04.1-Ubuntu SMP Mon Dec 4 15:39:17 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
root@buildd08:~# lxc-stop art1
root@buildd08:~# ^C
root@buildd08:~# uname -a
Linux buildd08 4.13.0-19-generic #22~16.04.1-Ubuntu SMP Mon Dec 4 15:39:17 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
root@buildd08:~# lxc-start art1
root@buildd08:~# ps aux | grep monitor
root       209  0.0  0.0  12120  3720 ?        Ss   Mar01   0:01 lldpd: monitor
root     13921  0.0  0.0   7840  3620 ?        Ss   09:04   0:00 [lxc monitor] /var/lib/lxc art1
root     13984  0.0  0.0   5548   580 pts/0    R+   09:04   0:00 grep --color=auto monitor
```
