### ISSUE TITLE
lxc-top crashes when configfile is malformed

### ISSUE THREAD

**Issue by k3a** [lxc/lxc#2224]
# Required information

 * Distribution: 
    Gentoo
 * Distribution version: 
    Latest
 * The output of
   * `lxc-start --version` 
      2.1.1

# Issue description

When a config file is malformed and the container defined in that file is running (has been started when the config was not malformed yet), issuing lxc-top causes a crash of this tool.

Unfortunately, I don't have debug symbols available for everything but it seems to be a problem in list_active_containers(). 

# Steps to reproduce

 1. Start a container with a proper config
 2. Modify some line (e.g. use lxc.net.0.ipv4 instead of lxc.net.0.ipv4.address)
 3. run lxc-top

# Information to attach

```
*** Error in `lxc-top': double free or corruption (out): 0x000000026a7afbd0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7bbb5)[0x39a9fc1fbb5]
/lib64/libc.so.6(+0x83ffb)[0x39a9fc27ffb]
/lib64/libc.so.6(+0x855a1)[0x39a9fc295a1]
/usr/lib64/liblxc.so.1(list_active_containers+0x63e)[0x39aa020ea7e]
lxc-top(main+0x197)[0x26a09b837]
/lib64/libc.so.6(__libc_start_main+0xf6)[0x39a9fbc44a6]
lxc-top(_start+0x2a)[0x26a09c5ca]
```

**Comment by stgraber** [comment]
@brauner can you try to reproduce and if that still happens, fix it?

**Comment by brauner** [comment]
This is fixed since a long time. Sorry I didn't close this.
