### ISSUE TITLE
FIO in a LXC

### ISSUE THREAD

**Issue by michacassola** [lxc/lxc#2227]
When I run FIO with --direct=1 I get this error:
`fio: looks like your file system does not support direct=1/buffered=0`

I run the latest LXD on Ubuntu 16.04.4 and ran FIO in a Ubuntu 16 Container.
All is setup on a ZFS backend.
The container has some limits applied to it.

Thanks in advance!

**Comment by brauner** [comment]
This requires the filesystem to support `O_DIRECT` which `ZFS` doesn't do properly yet. Sorry.
