### ISSUE TITLE
Why the lxctest1 container exited with 127?

### ISSUE THREAD

**Issue by DengkeDu** [lxc/lxc#2228]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: yocto
 * Distribution version: 2.4
 * The output of
   * `lxc-start --version`
2.0.8
   * `lxc-checkconfig`
   * `uname -a`
Linux intel-x86-64 4.12.20-rt0-yocto-preempt-rt 
   * `cat /proc/self/cgroup`
   * `cat /proc/1/mounts`

# Issue description
I have installed the busybox
`$ lxc-test-containertests`
```
chmod: cannot access '/var/lib/lxc/lxctest1/rootfs/bin/passwd': No such file or directory
got state 0 STOPPED
got state 1 STARTING
got state 2 RUNNING
got state 3 STOPPING
got state 4 ABORTING
got state 5 FREEZING
got state 6 FROZEN
got state 7 THAWED
Hung here!
```
I use lxc-monitor to monitor the /var/lib/lxc
`$ lxc-monitor -P /var/lib/lxc`
```
'lxctest1' changed state to [STARTING]
'lxctest1' changed state to [RUNNING]
'lxctest1' exited with status [127]
'lxctest1' changed state to [STOPPING]
'lxctest1' changed state to [STOPPED]
```
# My question
The program hung here to wait the container [RUNNING status](https://github.com/lxc/lxc/blob/lxc-2.0.8/src/tests/containertests.c#L224)
Why the lxctest1 exited with 127?

**Comment by brauner** [comment]
This is 2.0.8 that can be a lot of things. By I suspect it's the good old `lxc-monitord` that's hanging. This has all been extremely reworked and should not be reproducible with LXC 2.1 and LXC 3.0. If you can reproduce on these versions, please re-open.
