### ISSUE TITLE
Can't compile on CentOS 6.9 with most recent release -- expected specifier-qualifier-list before ‘__u64’

### ISSUE THREAD

**Issue by emprice** [lxc/lxc#2248]
# Required information

* Distribution: CentOS 6.9
* Output of `uname -a`: Linux sabriel 2.6.32-696.18.7.el6.x86_64 #1 SMP Thu Jan 4 17:31:22 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* This is an attempt to compile the most recent release of lxc, 3.0.0, downloaded in tarfile form from the Releases page.

# Issue description

I get the following error during compile:

```
libtool: compile:  /usr/bin/gcc -DHAVE_CONFIG_H -I. -I../../src -fPIC -DPIC -DLXCROOTFSMOUNT=\"/home/eprice/lxc/lib/lxc/rootfs\" -DLXCPATH=\"/home/eprice/lxc/var/lib/lxc\" -DLXC_GLOBAL_CONF=\"/home/eprice/lxc/etc/lxc/lxc.conf\" -DLXCINITDIR=\"/home/eprice/lxc/libexec\" -DLIBEXECDIR=\"/home/eprice/lxc/libexec\" -DLXCTEMPLATEDIR=\"/home/eprice/lxc/share/lxc/templates\" -DLXCTEMPLATECONFIG=\"/home/eprice/lxc/share/lxc/config\" -DLOGPATH=\"/home/eprice/lxc/var/log/lxc\" -DLXC_DEFAULT_CONFIG=\"/home/eprice/lxc/etc/lxc/default.conf\" -DLXC_USERNIC_DB=\"/run/lxc/nics\" -DLXC_USERNIC_CONF=\"/home/eprice/lxc/etc/lxc/lxc-usernet\" -DDEFAULT_CGROUP_PATTERN=\"lxc/%n\" -DRUNTIME_PATH=\"/run\" -DSBINDIR=\"/home/eprice/lxc/sbin\" -I ../../src -I ../../src/lxc -I ../../src/lxc/storage -I ../../src/lxc/cgroups -DHAVE_SELINUX -pthread -g -O2 -Wall -Werror -MT liblxc_la-start.lo -MD -MP -MF .deps/liblxc_la-start.Tpo -c start.c  -fPIC -DPIC -o .libs/liblxc_la-start.o
In file included from ./utils.h:36,
                 from lsm/lsm.h:31,
                 from start.c:76:
/usr/include/linux/loop.h:45: error: expected specifier-qualifier-list before ‘__u64’
make[3]: *** [liblxc_la-start.lo] Error 1
make[3]: Leaving directory `/h/sabriel0/src/lxc-3.0.0/src/lxc'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/h/sabriel0/src/lxc-3.0.0/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/h/sabriel0/src/lxc-3.0.0/src'
make: *** [all-recursive] Error 1
```

# Steps to reproduce

`CC=/usr/bin/gcc CXX=/usr/bin/g++ PYTHON=/usr/bin/python ./configure --prefix=/home/eprice/lxc`

# Additional info

I should note that I don't have root privileges on this machine, so I can't do anything that would require `sudo`, etc.

**Comment by gstanden** [comment]
I can confirm this issue as well

In file included from ./utils.h:36,
                 from lsm/lsm.h:31,
                 from start.c:76:
/usr/include/linux/loop.h:45: error: expected specifier-qualifier-list before '__u64'
make[3]: *** [liblxc_la-start.lo] Error 1
make[3]: Leaving directory `/opt/olxc/home/orabuntu/Downloads/orabuntu-lxc-master/uekulele/lxc/rpmbuild/BUILD/lxc-3.0.0/src/lxc'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/opt/olxc/home/orabuntu/Downloads/orabuntu-lxc-master/uekulele/lxc/rpmbuild/BUILD/lxc-3.0.0/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/opt/olxc/home/orabuntu/Downloads/orabuntu-lxc-master/uekulele/lxc/rpmbuild/BUILD/lxc-3.0.0/src'
make: *** [all-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.Ck2rVm (%build)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Ck2rVm (%build)
/opt/olxc//home/orabuntu/Downloads/orabuntu-lxc-master/uekulele/uekulele-services-1.sh: line 1008: cd: /opt/olxc//home/orabuntu/Downloads/orabuntu-lxc-master/uekulele/lxc/rpmbuild/RPMS/x86_64: No such file or directory

**Comment by gstanden** [comment]
You can get past this error as follows using the strategy from this reference [here](https://github.com/lxc/lxc/issues/2178):
```
./configure
make CFLAGS='-include /usr/include/linux/types.h'
```
However, a new error appears which I think is going to be a much more difficult issue.
```
tools/tool_utils.o: In function `switch_to_ns':
tool_utils.c:(.text+0x141d): undefined reference to `setns'
collect2: error: ld returned 1 exit status
make[3]: *** [lxc-attach] Error 1
make[3]: Leaving directory `/opt/olxc/home/orabuntu/Downloads/orabuntu-lxc-master/uekulele/lxc/lxc-3.0.0/src/lxc'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/opt/olxc/home/orabuntu/Downloads/orabuntu-lxc-master/uekulele/lxc/lxc-3.0.0/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/opt/olxc/home/orabuntu/Downloads/orabuntu-lxc-master/uekulele/lxc/lxc-3.0.0/src'
make: *** [all-recursive] Error 1
```
I believe this occurs because versions of glibc lower than 2.14 do not support the "setns" syscall.  There are references on this [here](https://sourceforge.net/p/ltp/mailman/message/34252897/).

What you could possibly do is create a build environment with the required glibc but my efforts suggest this is either non-trivial or maybe not possible.

**Comment by gstanden** [comment]
In what follows I want to make clear these steps would need to be tested very thoroughly on any production non-development system because changes such as these to glibc versions etc. could have unexpected side effects on other programs.  So you have been warned.  That being said, there is a way to build lxc-3.0.0 on CentOS and get past all these errors.

The method relies on this reference [here](https://www.redhat.com/archives/libvir-list/2015-August/msg00910.html) to handle the setns issue. 

Also , prior to the appending the patch code to linuxcontainer.c, I alsl previously installed the devtoolset as described [here](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-4/) and also I updated my glibc using this method as described [here](https://gist.github.com/harv/f86690fcad94f655906ee9e37c85b174).

Then, once you have installed the devtoolset-4 and updated glibc to v 2.17 do this step to add the required code to linuxcontainer.c:

```
cd lxc-3.0.0/src/lxc
vi linuxcontainer.c
```

then append this code to the end of the file linuxcontainer.c

```
/*
 * Workaround older glibc. While kernel may support the setns
 * syscall, the glibc wrapper might not exist. If that's the
 * case, use our own.
 */
#ifndef __NR_setns
# if defined(__x86_64__)
#  define __NR_setns 308
# elif defined(__i386__)
#  define __NR_setns 346
# elif defined(__arm__)
#  define __NR_setns 375
# elif defined(__aarch64__)
#  define __NR_setns 375
# elif defined(__powerpc__)
#  define __NR_setns 350
# elif defined(__s390__)
#  define __NR_setns 339
# endif
#endif

#ifndef HAVE_SETNS
# if defined(__NR_setns)
#  include <sys/syscall.h>

static inline int setns(int fd, int nstype)
{
    return syscall(__NR_setns, fd, nstype);
}
# else /* !__NR_setns */
#  error Please determine the syscall number for setns on your architecture
# endif
#endif
```

**Comment by gstanden** [comment]
The lxc-dheckconfig for this build is not very healthy looking though:
```

[orabuntu@centos69 lxc-3.0.0]$ lxc-checkconfig
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-2.6.32-696.23.1.el6.x86_64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
newuidmap is not installed
newgidmap is not installed
Network namespace: enabled
/usr/local/bin/lxc-checkconfig: line 127: [: -lt: unary operator expected
/usr/local/bin/lxc-checkconfig: line 127: [: -eq: unary operator expected

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/cgroup/cpuset
/cgroup/cpu
/cgroup/cpuacct
/cgroup/memory
/cgroup/devices
/cgroup/freezer
/cgroup/net_cls
/cgroup/blkio

Cgroup v2 mount points: 


Cgroup v1 systemd controller: missing
Cgroup namespace: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: /usr/local/bin/lxc-checkconfig: line 187: [: -ge: unary operator expected
/usr/local/bin/lxc-checkconfig: line 187: [: -gt: unary operator expected
enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: missing
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: missing
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: missing
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: missing
CONFIG_NETLINK_DIAG: missing
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/local/bin/lxc-checkconfig

[orabuntu@centos69 lxc-3.0.0]$ 
```
