### ISSUE TITLE
GO Error in lxc image import

### ISSUE THREAD

**Issue by bjonnh** [lxc/lxc#2253]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 18.04
 * The output of
   * `lxc-start --version`: 3.0.0
   * `lxc-checkconfig`:
Kernel configuration not found at /proc/config.gz; searching... Kernel configuration found at /boot/config-4.15.0-13-generic --- Namespaces --- Namespaces: enabled Utsname namespace: enabled Ipc namespace: enabled Pid namespace: enabled User namespace: enabled Network namespace: enabled --- Control groups --- Cgroups: enabled Cgroup v1 mount points: /sys/fs/cgroup/systemd /sys/fs/cgroup/freezer /sys/fs/cgroup/pids /sys/fs/cgroup/cpu,cpuacct /sys/fs/cgroup/net_cls,net_prio /sys/fs/cgroup/hugetlb /sys/fs/cgroup/memory /sys/fs/cgroup/devices /sys/fs/cgroup/blkio /sys/fs/cgroup/rdma /sys/fs/cgroup/cpuset /sys/fs/cgroup/perf_event Cgroup v2 mount points: /sys/fs/cgroup/unified Cgroup v1 clone_children flag: enabled Cgroup device: enabled Cgroup sched: enabled Cgroup cpu account: enabled Cgroup memory controller: enabled Cgroup cpuset: enabled --- Misc --- Veth pair device: enabled, loaded Macvlan: enabled, not loaded Vlan: enabled, not loaded Bridges: enabled, loaded Advanced netfilter: enabled, not loaded CONFIG_NF_NAT_IPV4: enabled, loaded CONFIG_NF_NAT_IPV6: enabled, loaded CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, loaded CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, loaded FUSE (for use with lxcfs): enabled, not loaded --- Checkpoint/Restore --- checkpoint restore: enabled CONFIG_FHANDLE: enabled CONFIG_EVENTFD: enabled CONFIG_EPOLL: enabled CONFIG_UNIX_DIAG: enabled CONFIG_INET_DIAG: enabled CONFIG_PACKET_DIAG: enabled CONFIG_NETLINK_DIAG: enabled File capabilities: Note : Before booting a new kernel, you can check its configuration usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
   * `uname -a`: Linux test-lxd 4.15.0-13-generic #14-Ubuntu SMP Sat Mar 17 13:44:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

# Issue description
Running (notice the : at the end) lxc image import ubuntu:                                                                        
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.(*cmdImageImport).Run(0xc42016b4a0, 0xc42021d400, 0xc420256c20, 0x1, 0x1, 0x0, 0x0)
	/build/lxd-_MhuNV/lxd-3.0.0/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/image.go:645 +0x1766
main.(*cmdImageImport).Run-fm(0xc42021d400, 0xc420256c20, 0x1, 0x1, 0x0, 0x0)
	/build/lxd-_MhuNV/lxd-3.0.0/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/image.go:578 +0x52
github.com/spf13/cobra.(*Command).execute(0xc42021d400, 0xc420256be0, 0x1, 0x1, 0xc42021d400, 0xc420256be0)
	/build/lxd-_MhuNV/lxd-3.0.0/obj-x86_64-linux-gnu/src/github.com/spf13/cobra/command.go:756 +0x468
github.com/spf13/cobra.(*Command).ExecuteC(0xc420187b80, 0x0, 0xc42026af00, 0x0)
	/build/lxd-_MhuNV/lxd-3.0.0/obj-x86_64-linux-gnu/src/github.com/spf13/cobra/command.go:846 +0x30a
github.com/spf13/cobra.(*Command).Execute(0xc420187b80, 0xc4200a6050, 0x3)
	/build/lxd-_MhuNV/lxd-3.0.0/obj-x86_64-linux-gnu/src/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
	/build/lxd-_MhuNV/lxd-3.0.0/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/main.go:204 +0x17f4

# Steps to reproduce

Run lxc image import ubuntu:

# Information to attach

N/A

**Comment by stgraber** [comment]
This is a LXD bug, not a LXC one.
The fix for the crash should be: https://github.com/lxc/lxd/pull/4387

Note that the main issue is that you're not using the tool properly, `lxc image import ubuntu:` is meaningless. If you want to copy `ubuntu:` to your local image server, you want `lxc image copy ubuntu: local:`. If you want to import a tarball then use `lxc image import <tarball>`.

Closing here as this is a LXD bug.
