### ISSUE TITLE
LXC container cgroup mounting issue

### ISSUE THREAD

**Issue by aargoon** [lxc/lxc#2255]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information
  I have Cisco Emulator which is Linux based it was working normally before the upgrade to Ubuntu16.04.
  a script is used to create, start, stop and manage the LXC container.
   however, when I run the script the container is not mounted to the cgroup

   * `lxc-start --version`

     root@ubuntu:/opt/simenv# lxc-start --version
         2.0.8

   * `lxc-checkconfig`

      root@ubuntu:/opt/simenv# lxc-checkconfig
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.4.0-118-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Warning: newuidmap is not setuid-root
Warning: newgidmap is not setuid-root
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: enabled
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

    
   * `uname -a`

root@ubuntu:/opt/simenv# uname -a
Linux ubuntu 4.4.0-118-generic #142-Ubuntu SMP Wed Mar 28 18:42:12 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

A brief description of what failed or what could be improved.

root@ubuntu:/opt/simenv# /etc/subuid

bash: /etc/subuid: Permission denied

root@ubuntu:/opt/simenv# /etc/sbugid

bash: /etc/sbugid: No such file or directory

**Comment by brauner** [comment]
That's not sufficient information for me to help right now. I'd need to see the trace log of the container e.g.

    lxc-start -n <container-name> -l trace -o <container-name>.log

and paste the contents of `<container-name>.log` here or share a link to it.

What do you mean by "not mounted to the cgroup"? What exactly is failing?

**Comment by aargoon** [comment]
Dear Brauner 

the point is that I'm not that much experts on Linux, however, I will try to elaborate more 

I'm using the attached script to create the container but what I discovered now it is not creating the lxc container, however, the previous version of Linux it was working with this script.

[mkhost.txt](https://github.com/lxc/lxc/files/1869075/mkhost.txt)

**Comment by gstanden** [comment]
What version of Ubuntu were you running on before you upgraded to Ubuntu 16.04 ?

**Comment by aargoon** [comment]
It was 12.04   I did the upgrade to 14.04 then to 16.04 TLS immediately

**Comment by gstanden** [comment]
There have been some major changes in LXC since the version of LXC that shipped with 12.04.  Just some ideas on things to check are: 
(1) location of the config file for the container.  In earlier version of LXC it was created in /container, but then later is was created in /var/lib/lxc/.  
(2) Another thing to check would be any changes to the lxc parameters in the lxc config file.  If you can find and access the location of the container config file for your container you can check on all the parameters to make sure none were deprecated or changed across LXC versions.

**Comment by brauner** [comment]
How do you create the container? The script doesn't really tell me anything.

**Comment by stgraber** [comment]
No update in the past two years, closing.
