### ISSUE TITLE
[lxc-3.0.0]Tty it doesn't mounted anymore

### ISSUE THREAD

**Issue by Obarun** [lxc/lxc#2264]
* Distribution: Obarun(arch based system with s6 instead of systemd)

 * The output of
 * `lxc-start --version`
3.0.0
* `lxc-checkconfig`
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
--- Control groups ---
Cgroups: enabled
Cgroup v1 mount points: 
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/cpu
/sys/fs/cgroup/cpuacct
/sys/fs/cgroup/blkio
/sys/fs/cgroup/memory
/sys/fs/cgroup/freezer
/sys/fs/cgroup/net_cls
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/net_prio
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/pids
/sys/fs/cgroup/rdma
Cgroup v2 mount points: 
Cgroup v1 systemd controller: missing
Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled
--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, loaded
--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

* `uname -a`
Linux obarunS6 4.15.14-1-ARCH #1 SMP PREEMPT Wed Mar 28 17:34:29 UTC 2018 x86_64 GNU/Linux
   
* `cat /proc/self/cgroup`
13:devices:/org/freedesktop/ConsoleKit/Session2
12:rdma:/org/freedesktop/ConsoleKit/Session2
11:pids:/org/freedesktop/ConsoleKit/Session2
10:hugetlb:/org/freedesktop/ConsoleKit/Session2
9:net_prio:/org/freedesktop/ConsoleKit/Session2
8:perf_event:/org/freedesktop/ConsoleKit/Session2
7:net_cls:/org/freedesktop/ConsoleKit/Session2
6:freezer:/org/freedesktop/ConsoleKit/Session2
5:memory:/org/freedesktop/ConsoleKit/Session2
4:blkio:/org/freedesktop/ConsoleKit/Session2
3:cpuacct:/org/freedesktop/ConsoleKit/Session2
2:cpu:/org/freedesktop/ConsoleKit/Session2
1:cpuset:/org/freedesktop/ConsoleKit/Session2

   * `cat /proc/1/mounts`
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sys /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
dev /dev devtmpfs rw,nosuid,relatime,size=4022836k,nr_inodes=1005709,mode=755 0 0
run /run tmpfs rw,nosuid,nodev,relatime,mode=755 0 0
/dev/sda3 / ext4 rw,relatime,data=ordered 0 0
shm /dev/shm tmpfs rw,nosuid,nodev,relatime 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
cgroup /sys/fs/cgroup tmpfs rw,relatime 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/cpu cgroup rw,relatime,cpu 0 0
cgroup /sys/fs/cgroup/cpuacct cgroup rw,relatime,cpuacct 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,relatime,blkio 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,relatime,memory 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls cgroup rw,relatime,net_cls 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,relatime,perf_event,release_agent=/run/cgmanager/agents/cgm-release-agent.perf_event 0 0
cgroup /sys/fs/cgroup/net_prio cgroup rw,relatime,net_prio 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,relatime,hugetlb,release_agent=/run/cgmanager/agents/cgm-release-agent.hugetlb 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,relatime,pids,release_agent=/run/cgmanager/agents/cgm-release-agent.pids 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,relatime,rdma,release_agent=/run/cgmanager/agents/cgm-release-agent.rdma 0 0
/dev/sda1 /boot ext2 rw,relatime,block_validity,barrier,user_xattr,acl,stripe=4 0 0
/dev/sda4 /home ext4 rw,relatime,data=ordered 0 0
none /run/user/1000 tmpfs rw,relatime,mode=700,uid=1000 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=100 0 0

*`configuration file`
lxc.seccomp.profile = /usr/share/lxc/config/common.seccomp
lxc.mount.entry = proc proc proc nodev,noexec,nosuid 0 0
lxc.mount.entry = sysfs sys sysfs defaults 0 0
lxc.mount.entry = run run tmpfs rw,nodev,relatime,mode=755 0 0
lxc.mount.entry = /dev/null dev/null none bind,create=file 0 0
lxc.mount.entry = /dev/random dev/random none bind,create=file 0 0
lxc.mount.entry = /dev/tty dev/tty none bind,create=file 0 0
lxc.mount.entry = /dev/urandom dev/urandom none bind,create=file 0 0
lxc.mount.entry = /dev/zero dev/zero none bind,create=file 0 0
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none bind,optional 0 0
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none bind,optional 0 0
lxc.mount.entry = /sys/kernel/security sys/kernel/security none bind,optional 0 0
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none bind,optional 0 0
lxc.mount.entry = /sys/firmware/efi/efivars sys/firmware/efi/efivars none bind,optional 0 0
lxc.mount.entry = tmpfs tmp tmpfs defaults
lxc.mount.entry = /dev/dri dev/dri none bind,optional,create=dir
lxc.mount.entry = /dev/snd dev/snd none bind,optional,create=dir
lxc.mount.entry = /tmp/.X11-unix tmp/.X11-unix none bind,optional,create=dir
lxc.mount.entry = /dev/video0 dev/video0 none bind,optional,create=file
lxc.mount.auto = cgroup:mixed
lxc.mount.entry = /var/cache/pacman/pkg var/cache/pacman/pkg none bind,ro 0 0
lxc.tty.max = 1
lxc.tty.dir = lxc
lxc.signal.stop = SIGKILL
lxc.cap.drop = setfcap sys_nice sys_pacct sys_rawio
lxc.cap.drop = mac_admin mac_override sys_time sys_module sys_rawio
lxc.pty.max = 10
lxc.hook.clone = /usr/share/lxc/hooks/clonehostname
lxc.cgroup.devices.deny = a
lxc.cgroup.devices.allow = c *:* m
lxc.cgroup.devices.allow = b *:* m
lxc.cgroup.devices.allow = c 1:3 rwm
lxc.cgroup.devices.allow = c 1:5 rwm
lxc.cgroup.devices.allow = c 1:7 rwm
lxc.cgroup.devices.allow = c 5:0 rwm
lxc.cgroup.devices.allow = c 5:1 rwm
lxc.cgroup.devices.allow = c 5:2 rwm
lxc.cgroup.devices.allow = c 1:8 rwm
lxc.cgroup.devices.allow = c 1:9 rwm
lxc.cgroup.devices.allow = c 136:* rwm
lxc.cgroup.devices.allow = c 10:229 rwm
lxc.cgroup.devices.allow = c 254:0 rm
lxc.cgroup.devices.allow = c 10:200 rwm
lxc.cgroup.devices.allow = c 10:228 rwm
lxc.cgroup.devices.allow = c 10:232 rwm
lxc.cgroup.cpuset.cpus = 0-3

*`log file at starting procedure`
lxc-start test 20180408233306.277 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:939 - Attempting to set proc title to [lxc monitor] /var/lib/lxc test
lxc-start test 20180408233306.277 INFO     lxc_lsm - lsm/lsm.c:lsm_init:46 - LSM security driver nop
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:585 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:761 - Adding native rule for reject_force_umount  # comment this to allow umount -f;  not recommended action 0(kill)
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:411 - Setting Seccomp rule to reject force umounts
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:765 - Adding compat rule for reject_force_umount action 0(kill)
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:411 - Setting Seccomp rule to reject force umounts
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:411 - Setting Seccomp rule to reject force umounts
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:585 - processing: .[all]
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:585 - processing: .kexec_load errno 1
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:761 - Adding native rule for kexec_load errno 1 action 327681(errno)
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:765 - Adding compat rule for kexec_load action 327681(errno)
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:585 - processing: .open_by_handle_at errno 1
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:761 - Adding native rule for open_by_handle_at errno 1 action 327681(errno)
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:765 - Adding compat rule for open_by_handle_at action 327681(errno)
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:585 - processing: .init_module errno 1
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:761 - Adding native rule for init_module errno 1 action 327681(errno)
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:765 - Adding compat rule for init_module action 327681(errno)
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:585 - processing: .finit_module errno 1
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:761 - Adding native rule for finit_module errno 1 action 327681(errno)
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:765 - Adding compat rule for finit_module action 327681(errno)
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:585 - processing: .delete_module errno 1
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:761 - Adding native rule for delete_module errno 1 action 327681(errno)
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:765 - Adding compat rule for delete_module action 327681(errno)
lxc-start test 20180408233306.277 INFO     lxc_seccomp - seccomp.c:parse_config_v2:775 - Merging in the compat Seccomp ctx into the main one
lxc-start test 20180408233306.278 DEBUG    terminal - terminal.c:lxc_terminal_peer_default:691 - The process does not have a controlling terminal
lxc-start test 20180408233306.278 INFO     lxc_start - start.c:lxc_init:846 - Container "test" is initialized
lxc-start test 20180408233306.279 INFO     lxc_network - network.c:instantiate_veth:171 - Retrieved mtu 1500 from lxcbr0
lxc-start test 20180408233306.279 INFO     lxc_network - network.c:instantiate_veth:197 - Attached "vethYUTY0G" to bridge "lxcbr0"
lxc-start test 20180408233306.279 DEBUG    lxc_network - network.c:instantiate_veth:222 - Instantiated veth "vethYUTY0G/vethCN0YCU", index is "77"
lxc-start test 20180408233306.279 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:60 - cgroup driver cgfsng initing for test
lxc-start test 20180408233306.279 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cg_legacy_handle_cpuset_hierarchy:750 - "cgroup.clone_children" was already set to "1"
lxc-start test 20180408233306.281 INFO     lxc_start - start.c:lxc_spawn:1614 - Cloned CLONE_NEWNS
lxc-start test 20180408233306.281 INFO     lxc_start - start.c:lxc_spawn:1614 - Cloned CLONE_NEWPID
lxc-start test 20180408233306.281 INFO     lxc_start - start.c:lxc_spawn:1614 - Cloned CLONE_NEWUTS
lxc-start test 20180408233306.281 INFO     lxc_start - start.c:lxc_spawn:1614 - Cloned CLONE_NEWIPC
lxc-start test 20180408233306.281 INFO     lxc_start - start.c:lxc_spawn:1614 - Cloned CLONE_NEWNET
lxc-start test 20180408233306.281 DEBUG    lxc_start - start.c:lxc_try_preserve_namespaces:199 - Preserved mnt namespace via fd 15
lxc-start test 20180408233306.281 DEBUG    lxc_start - start.c:lxc_try_preserve_namespaces:199 - Preserved pid namespace via fd 16
lxc-start test 20180408233306.281 DEBUG    lxc_start - start.c:lxc_try_preserve_namespaces:199 - Preserved uts namespace via fd 17
lxc-start test 20180408233306.281 DEBUG    lxc_start - start.c:lxc_try_preserve_namespaces:199 - Preserved ipc namespace via fd 18
lxc-start test 20180408233306.281 DEBUG    lxc_start - start.c:lxc_try_preserve_namespaces:199 - Preserved net namespace via fd 19
lxc-start test 20180408233306.281 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:__cg_legacy_setup_limits:2735 - Set controller "cpuset.cpus" set to "0-3"
lxc-start test 20180408233306.281 INFO     lxc_cgfsng - cgroups/cgfsng.c:__cg_legacy_setup_limits:2740 - Limits for the legacy cgroup hierarchies have been setup
lxc-start test 20180408233306.281 DEBUG    lxc_start - start.c:lxc_spawn:1668 - Preserved net namespace via fd 10
lxc-start test 20180408233306.296 DEBUG    lxc_network - network.c:lxc_network_move_created_netdev_priv:2479 - Moved network device "vethCN0YCU"/"eth0" to network namespace of 9352
lxc-start test 20180408233306.296 INFO     lxc_start - start.c:do_start:1177 - Unshared CLONE_NEWCGROUP
lxc-start test 20180408233306.296 DEBUG    storage - storage/storage.c:storage_query:247 - Detected rootfs type "dir"
lxc-start test 20180408233306.296 DEBUG    lxc_conf - conf.c:lxc_setup_rootfs:1347 - Mounted rootfs "/var/cache/obarun/pkgbuild/test/container/rootfs" onto "/usr/lib/lxc/rootfs" with options "(null)"
lxc-start test 20180408233306.296 INFO     lxc_conf - conf.c:setup_utsname:774 - Set hostname to "test"
lxc-start test 20180408233306.305 DEBUG    lxc_network - network.c:setup_hw_addr:2745 - Mac address "00:16:3e:ff:18:c3" on "eth0" has been setup
lxc-start test 20180408233306.305 DEBUG    lxc_network - network.c:lxc_setup_netdev_in_child_namespaces:3003 - Network device "eth0" has been setup
lxc-start test 20180408233306.305 INFO     lxc_network - network.c:lxc_setup_network_in_child_namespaces:3024 - network has been setup
lxc-start test 20180408233306.305 INFO     lxc_conf - conf.c:mount_autodev:1172 - Preparing "/dev"
lxc-start test 20180408233306.305 INFO     lxc_conf - conf.c:mount_autodev:1194 - Mounted tmpfs on "/usr/lib/lxc/rootfs/dev"
lxc-start test 20180408233306.305 INFO     lxc_conf - conf.c:mount_autodev:1211 - Prepared "/dev"
lxc-start test 20180408233306.305 INFO     lxc_conf - conf.c:lxc_fill_autodev:1247 - Populating "/dev"
lxc-start test 20180408233306.305 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1262 - Created device node "/usr/lib/lxc/rootfs/dev/full"
lxc-start test 20180408233306.305 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1262 - Created device node "/usr/lib/lxc/rootfs/dev/null"
lxc-start test 20180408233306.305 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1262 - Created device node "/usr/lib/lxc/rootfs/dev/random"
lxc-start test 20180408233306.305 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1262 - Created device node "/usr/lib/lxc/rootfs/dev/tty"
lxc-start test 20180408233306.305 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1262 - Created device node "/usr/lib/lxc/rootfs/dev/urandom"
lxc-start test 20180408233306.305 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1262 - Created device node "/usr/lib/lxc/rootfs/dev/zero"
lxc-start test 20180408233306.305 INFO     lxc_conf - conf.c:lxc_fill_autodev:1300 - Populated "/dev"
lxc-start test 20180408233306.305 DEBUG    lxc_conf - conf.c:mount_entry:2020 - Mounted "proc" on "/usr/lib/lxc/rootfs/proc" with filesystem type "proc"
lxc-start test 20180408233306.305 DEBUG    lxc_conf - conf.c:mount_entry:2020 - Mounted "sysfs" on "/usr/lib/lxc/rootfs/sys" with filesystem type "sysfs"
lxc-start test 20180408233306.305 DEBUG    lxc_conf - conf.c:mount_entry:2020 - Mounted "run" on "/usr/lib/lxc/rootfs/run" with filesystem type "tmpfs"
lxc-start test 20180408233306.305 DEBUG    lxc_conf - conf.c:mount_entry:1943 - Remounting "/dev/null" on "/usr/lib/lxc/rootfs/dev/null" to respect bind or remount options
lxc-start test 20180408233306.305 DEBUG    lxc_conf - conf.c:mount_entry:1964 - Flags for "/dev/null" were 4098, required extra flags are 2
lxc-start test 20180408233306.305 DEBUG    lxc_conf - conf.c:mount_entry:2020 - Mounted "/dev/null" on "/usr/lib/lxc/rootfs/dev/null" with filesystem type "none"
lxc-start test 20180408233306.305 DEBUG    lxc_conf - conf.c:mount_entry:1943 - Remounting "/dev/random" on "/usr/lib/lxc/rootfs/dev/random" to respect bind or remount options
lxc-start test 20180408233306.305 DEBUG    lxc_conf - conf.c:mount_entry:1964 - Flags for "/dev/random" were 4098, required extra flags are 2
lxc-start test 20180408233306.305 DEBUG    lxc_conf - conf.c:mount_entry:2020 - Mounted "/dev/random" on "/usr/lib/lxc/rootfs/dev/random" with filesystem type "none"
lxc-start test 20180408233306.305 ERROR    lxc_conf - conf.c:mount_entry:1935 - No such device or address - Failed to mount "/dev/tty" on "/usr/lib/lxc/rootfs/dev/tty"
lxc-start test 20180408233306.305 ERROR    lxc_conf - conf.c:lxc_setup:3416 - Failed to setup mount entries
lxc-start test 20180408233306.305 ERROR    lxc_start - start.c:do_start:1198 - Failed to setup container "test"
lxc-start test 20180408233306.305 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
lxc-start test 20180408233306.305 INFO     lxc_network - network.c:lxc_delete_network_priv:2563 - Interface "eth0" with index 77 already deleted or existing in different network namespace
lxc-start test 20180408233306.305 INFO     lxc_network - network.c:lxc_delete_network_priv:2573 - Removed interface "eth0" with index 77
lxc-start test 20180408233306.332 INFO     lxc_network - network.c:lxc_delete_network_priv:2594 - Removed interface "vethYUTY0G" from "lxcbr0"
lxc-start test 20180408233306.332 DEBUG    lxc_network - network.c:lxc_delete_network:3151 - Deleted network devices
lxc-start test 20180408233306.332 DEBUG    lxc_container - lxccontainer.c:wait_on_daemonized_start:812 - First child 9345 exited
lxc-start test 20180408233306.332 ERROR    lxc_container - lxccontainer.c:wait_on_daemonized_start:824 - Received container state "ABORTING" instead of "RUNNING"
lxc-start test 20180408233306.332 ERROR    lxc_start - start.c:__lxc_start:1866 - Failed to spawn container "test"

# Issue description
The tty is doesn't mounted anymore with the new 3.0.0 version. Apparently the function safe_mount in your utils.c file cause trouble.

Also the /dev on my system is correctly populated 

*`obarun@obarunS6 ~ % ls -la /dev | grep tty`
crw-rw-rw-   1 root tty         5,   2  9 avril 11:34 ptmx
crw-rw-rw-   1 root tty         5,   0  9 avril 09:35 tty
crw--w----   1 root tty         4,   0  9 avril 07:45 tty0
crw--w----   1 root tty         4,   1  9 avril 07:45 tty1
crw--w----   1 root tty         4,  10  9 avril 07:45 tty10
crw--w----   1 root tty         4,  11  9 avril 07:45 tty11
crw--w----   1 root tty         4,  12  9 avril 07:45 tty12
crw--w----   1 root tty         4,  13  9 avril 07:45 tty13
crw--w----   1 root tty         4,  14  9 avril 07:45 tty14
crw--w----   1 root tty         4,  15  9 avril 07:45 tty15
crw--w----   1 root tty         4,  16  9 avril 07:45 tty16
crw--w----   1 root tty         4,  17  9 avril 07:45 tty17
crw--w----   1 root tty         4,  18  9 avril 07:45 tty18
crw--w----   1 root tty         4,  19  9 avril 07:45 tty19
crw--w----   1 root tty         4,   2  9 avril 07:45 tty2
crw--w----   1 root tty         4,  20  9 avril 07:45 tty20
crw--w----   1 root tty         4,  21  9 avril 07:45 tty21
crw--w----   1 root tty         4,  22  9 avril 07:45 tty22
crw--w----   1 root tty         4,  23  9 avril 07:45 tty23
crw--w----   1 root tty         4,  24  9 avril 07:45 tty24
crw--w----   1 root tty         4,  25  9 avril 07:45 tty25
crw--w----   1 root tty         4,  26  9 avril 07:45 tty26
crw--w----   1 root tty         4,  27  9 avril 07:45 tty27
crw--w----   1 root tty         4,  28  9 avril 07:45 tty28
crw--w----   1 root tty         4,  29  9 avril 07:45 tty29
crw--w----   1 root tty         4,   3  9 avril 07:45 tty3
crw--w----   1 root tty         4,  30  9 avril 07:45 tty30
crw--w----   1 root tty         4,  31  9 avril 07:45 tty31
crw--w----   1 root tty         4,  32  9 avril 07:45 tty32
crw--w----   1 root tty         4,  33  9 avril 07:45 tty33
crw--w----   1 root tty         4,  34  9 avril 07:45 tty34
crw--w----   1 root tty         4,  35  9 avril 07:45 tty35
crw--w----   1 root tty         4,  36  9 avril 07:45 tty36
crw--w----   1 root tty         4,  37  9 avril 07:45 tty37
crw--w----   1 root tty         4,  38  9 avril 07:45 tty38
crw--w----   1 root tty         4,  39  9 avril 07:45 tty39
crw--w----   1 root tty         4,   4  9 avril 07:45 tty4
crw--w----   1 root tty         4,  40  9 avril 07:45 tty40
crw--w----   1 root tty         4,  41  9 avril 07:45 tty41
crw--w----   1 root tty         4,  42  9 avril 07:45 tty42
crw--w----   1 root tty         4,  43  9 avril 07:45 tty43
crw--w----   1 root tty         4,  44  9 avril 07:45 tty44
crw--w----   1 root tty         4,  45  9 avril 07:45 tty45
crw--w----   1 root tty         4,  46  9 avril 07:45 tty46
crw--w----   1 root tty         4,  47  9 avril 07:45 tty47
crw--w----   1 root tty         4,  48  9 avril 07:45 tty48
crw--w----   1 root tty         4,  49  9 avril 07:45 tty49
crw--w----   1 root tty         4,   5  9 avril 07:45 tty5
crw--w----   1 root tty         4,  50  9 avril 07:45 tty50
crw--w----   1 root tty         4,  51  9 avril 07:45 tty51
crw--w----   1 root tty         4,  52  9 avril 07:45 tty52
crw--w----   1 root tty         4,  53  9 avril 07:45 tty53
crw--w----   1 root tty         4,  54  9 avril 07:45 tty54
crw--w----   1 root tty         4,  55  9 avril 07:45 tty55
crw--w----   1 root tty         4,  56  9 avril 07:45 tty56
crw--w----   1 root tty         4,  57  9 avril 07:45 tty57
crw--w----   1 root tty         4,  58  9 avril 07:45 tty58
crw--w----   1 root tty         4,  59  9 avril 07:45 tty59
crw--w----   1 root tty         4,   6  9 avril 07:45 tty6
crw--w----   1 root tty         4,  60  9 avril 07:45 tty60
crw--w----   1 root tty         4,  61  9 avril 07:45 tty61
crw--w----   1 root tty         4,  62  9 avril 07:45 tty62
crw--w----   1 root tty         4,  63  9 avril 07:45 tty63
crw--w----   1 root tty         4,   7  9 avril 07:45 tty7
crw--w----   1 root tty         4,   8  9 avril 07:45 tty8
crw--w----   1 root tty         4,   9  9 avril 07:45 tty9
crw-rw----   1 root uucp        4,  64  9 avril 07:45 ttyS0
crw-rw----   1 root uucp        4,  65  9 avril 07:45 ttyS1
crw-rw----   1 root uucp        4,  66  9 avril 07:45 ttyS2
crw-rw----   1 root uucp        4,  67  9 avril 07:45 ttyS3
crw-rw----   1 root tty         7,   0  9 avril 07:45 vcs
crw-rw----   1 root tty         7,   1  9 avril 07:45 vcs1
crw-rw----   1 root tty         7,   2  9 avril 07:45 vcs2
crw-rw----   1 root tty         7,   6  9 avril 07:45 vcs6
crw-rw----   1 root tty         7,   7  9 avril 07:45 vcs7
crw-rw----   1 root tty         7, 128  9 avril 07:45 vcsa
crw-rw----   1 root tty         7, 129  9 avril 07:45 vcsa1
crw-rw----   1 root tty         7, 130  9 avril 07:45 vcsa2
crw-rw----   1 root tty         7, 134  9 avril 07:45 vcsa6
crw-rw----   1 root tty         7, 135  9 avril 07:45 vcsa7

the destination for tempory dev is already present too 

*`obarun@obarunS6 ~ % sudo ls -la /usr/lib/lxc/rootfs` 
total 16K
drwxr-xr-x 3 root root 4,0K  9 avril 08:38 ./
drwxr-xr-x 4 root root 4,0K  9 avril 08:38 ../
drwxr-xr-x 2 root root 4,0K 15 août   2016 dev/
-rw-r--r-- 1 root root  189  9 avril 08:38 README

**Comment by brauner** [comment]
The reason you're seeing this error is:
```
lxc-start test 20180408233306.278 DEBUG terminal - terminal.c:lxc_terminal_peer_default:691 - The process does not have a controlling terminal
```

which means `open("/dev/tty", ...)` will fail with `safe_mount()`. However, you should remove:

```
lxc.mount.entry = /dev/null dev/null none bind,create=file 0 0
lxc.mount.entry = /dev/random dev/random none bind,create=file 0 0
lxc.mount.entry = /dev/tty dev/tty none bind,create=file 0 0
lxc.mount.entry = /dev/urandom dev/urandom none bind,create=file 0 0
lxc.mount.entry = /dev/zero dev/zero none bind,create=file 0 0
```

since LXC will setup those mounts/device nodes automatically for you as you can see from the logs:

```
lxc-start test 20180408233306.305 INFO lxc_conf - conf.c:mount_autodev:1172 - Preparing "/dev"
lxc-start test 20180408233306.305 INFO lxc_conf - conf.c:mount_autodev:1194 - Mounted tmpfs on "/usr/lib/lxc/rootfs/dev"
lxc-start test 20180408233306.305 INFO lxc_conf - conf.c:mount_autodev:1211 - Prepared "/dev"
lxc-start test 20180408233306.305 INFO lxc_conf - conf.c:lxc_fill_autodev:1247 - Populating "/dev"
lxc-start test 20180408233306.305 DEBUG lxc_conf - conf.c:lxc_fill_autodev:1262 - Created device node "/usr/lib/lxc/rootfs/dev/full"
lxc-start test 20180408233306.305 DEBUG lxc_conf - conf.c:lxc_fill_autodev:1262 - Created device node "/usr/lib/lxc/rootfs/dev/null"
lxc-start test 20180408233306.305 DEBUG lxc_conf - conf.c:lxc_fill_autodev:1262 - Created device node "/usr/lib/lxc/rootfs/dev/random"
lxc-start test 20180408233306.305 DEBUG lxc_conf - conf.c:lxc_fill_autodev:1262 - Created device node "/usr/lib/lxc/rootfs/dev/tty"
lxc-start test 20180408233306.305 DEBUG lxc_conf - conf.c:lxc_fill_autodev:1262 - Created device node "/usr/lib/lxc/rootfs/dev/urandom"
lxc-start test 20180408233306.305 DEBUG lxc_conf - conf.c:lxc_fill_autodev:1262 - Created device node "/usr/lib/lxc/rootfs/dev/zero"
lxc-start test 20180408233306.305 INFO lxc_conf - conf.c:lxc_fill_autodev:1300 - Populated "/dev"
```

at which point that problem will vanish.

**Comment by Obarun** [comment]
Thanks for your help, it works now
