### ISSUE TITLE
Unprivileged containers fail to start with system umask 077

### ISSUE THREAD

**Issue by 3XX0** [lxc/lxc#2277]
LXC fails to start unprivileged containers on systems with an uncommon umask (e.g. 077).

So say `/etc/login.defs` contains `UMASK 077` (the default on Ubuntu AMIs), lxc-start will fail with: `Failed initializing cgroup support`.
It all comes down to the permissions applied by pam_cgfs:

```
ls -ld /sys/fs/cgroup/freezer/{,user,user/ubuntu,user/ubuntu/0}
dr-xr-xr-x 3 root   root   0 Apr 14 02:08 /sys/fs/cgroup/freezer/
drwx------ 4 root   ubuntu 0 Apr 14 02:08 /sys/fs/cgroup/freezer/user
drwx------ 3 root   ubuntu 0 Apr 14 02:08 /sys/fs/cgroup/freezer/user/ubuntu
drwx------ 2 ubuntu ubuntu 0 Apr 14 02:08 /sys/fs/cgroup/freezer/user/ubuntu/0
```

So we need at the very least to `chmod g+rx` the top level directories here.

**Comment by brauner** [comment]
@3XX0 do you have a patch to test? :)

**Comment by 3XX0** [comment]
Something like that maybe? I'm not sure how you want to proceed, but this does fix the issue

**Comment by brauner** [comment]
@hallyn, can you give this a look, please?

**Comment by hallyn** [comment]
lgtm

**Comment by brauner** [comment]
@3XX0, care to make this a PR? :)

**Comment by johnramsden** [comment]
I'm getting similar message on Arch Linux with a CentOS 5 container. When I attempt to run unprivileged container:

```
lxc-start: tiger: start.c: lxc_spawn: 1553 Failed initializing cgroup support
```

Is there a workaround for the time being? Or is my problem not even related? I attached a [log](https://github.com/lxc/lxc/files/1934102/tiger.log).

I have UIDs mapped, and my config looks like the following:

```
# Distribution configuration
lxc.include = /usr/share/lxc/config/common.conf
lxc.include = /usr/share/lxc/config/userns.conf
lxc.arch = x86_64

# Container specific configuration
lxc.idmap = u 0 165536 231072
lxc.idmap = g 0 165536 231072
lxc.rootfs.path = dir:/home/john/.local/share/lxc/tiger/rootfs
lxc.uts.name = tiger

# Network configuration
lxc.net.0.type = veth
lxc.net.0.link = lxcbr0
lxc.net.0.flags = up
lxc.net.0.hwaddr = 00:16:3e:6a:90:4b
```
