### ISSUE TITLE
User namespace containers with cgroup:mixed lack permissions

### ISSUE THREAD

**Issue by DeHackEd** [lxc/lxc#228]
When using cgroup:mixed in a user namespace container all the directories are still owned by host's root, making read/write mount permissions moot.

<pre>
# cd /sys/fs/cgroup/systemd/lxc/fedora
# ls -l
total 0
-rw-r--r-- 1 65534 65534 0 May 25 20:22 cgroup.clone_children
--w--w--w- 1 65534 65534 0 May 25 20:22 cgroup.event_control
-rw-r--r-- 1 65534 65534 0 May 25 20:22 cgroup.procs
-rw-r--r-- 1 65534 65534 0 May 25 20:22 notify_on_release
-rw-r--r-- 1 65534 65534 0 May 25 20:22 tasks
# cat $$ > tasks
bash: tasks: Permission denied
# 
</pre>

**Comment by brauner** [comment]
This is fixed in stable and master.
