### ISSUE TITLE
lxc-execute -d option missing (daemonise ?)

### ISSUE THREAD

**Issue by iam-TJ** [lxc/lxc#2280]
In the LXC 3.0.0 announcement [0] is a link to an asciicast apparently demonstrating "Support for daemonized app containers" [1] where it shows the command:

    > lxc-execute xenial -d -- bash

But neither 'man lxc-execute' [2] nor "lxc-execute --help" show that option.

Using LXC 3.0.0 on Ubuntu 18.04.

    $ lxc-execute --version
    3.0.0

Also, please provide more documentation on how this feature is supposed to work - specifically, can a container without /sbin/init be used in this case?

[0] https://discuss.linuxcontainers.org/t/lxc-3-0-0-has-been-released/1449
[1] https://asciinema.org/a/174498
[2] https://linuxcontainers.org/lxc/manpages//man1/lxc-execute.1.html

**Comment by brauner** [comment]
@iam-TJ, sounds like you have updated the shared library but no the tools themselves. Did you install `lxc-utils`?:

```
chb@conventiont|~
> apt search lxc-utils
Sorting... Done
Full Text Search... Done
lxc/bionic,bionic,now 3.0.0+master~20180413-1633-0ubuntu1~bionic all [installed]
  Transitional package - lxc -> lxc-utils

lxc-utils/bionic,now 3.0.0+master~20180413-1633-0ubuntu1~bionic amd64 [installed]
  Linux Containers userspace tools

lxc1/bionic,bionic,now 3.0.0+master~20180413-1633-0ubuntu1~bionic all [installed]
  Transitional package - lxc1 -> lxc-utils
```

**Comment by brauner** [comment]
> Also, please provide more documentation on how this feature is supposed to work - specifically, can a container without /sbin/init be used in this case?

Yes, that's what the asciinema shows. Unless I'm misunderstanding the question.

**Comment by iam-TJ** [comment]
Regarding the 'daemonisation' feature, I'm trying to get to grips with the basics of LXC. Up to now I've dealt with system containers (LXD etc.) so I'm not clear as to what the 'legacy' LXC technique is/was for 'application' containers but I've read various commentary that infers the container must have an init system that is responsible from starting the container's long-running service(s).

The asciicast example seems to demonstrate a container starting 'bash' - I'm guessing for it to be long-running it is in interactive mode, and is running as PID 1 (if there's no /sbin/init required) ?

Here's the Ubuntu 18.04 amd84 package details:

$  apt search lxc-utils
Sorting... Done
Full Text Search... Done
lxc/bionic,bionic,now 3.0.0-0ubuntu2 all [installed]
  Transitional package - lxc -> lxc-utils

lxc-utils/bionic,now 3.0.0-0ubuntu2 amd64 [installed,automatic]
  Linux Containers userspace tools

lxc1/bionic,bionic 3.0.0-0ubuntu2 all [residual-config]
  Transitional package - lxc1 -> lxc-utils

$ apt list '*lxc*'
Listing... Done
golang-gopkg-lxc-go-lxc.v2-dev/bionic,bionic 0.0~git20180119.b964baa-1ubuntu3 all
libclxclient-dev/bionic 3.9.0-4ubuntu1 amd64
libclxclient3/bionic,now 3.9.0-4ubuntu1 amd64 [installed]
liblxc-common/bionic,now 3.0.0-0ubuntu2 amd64 [installed,automatic]
liblxc-dev/bionic 3.0.0-0ubuntu2 amd64
liblxc1/bionic,now 3.0.0-0ubuntu2 amd64 [installed]
lxc/bionic,bionic,now 3.0.0-0ubuntu2 all [installed]
lxc-common/now 2.0.8-0ubuntu1~16.04.2 amd64 [residual-config]
lxc-dev/bionic,bionic 3.0.0-0ubuntu2 all
lxc-templates/bionic,now 3.0.0-0ubuntu1 amd64 [installed]
lxc-utils/bionic,now 3.0.0-0ubuntu2 amd64 [installed,automatic]
lxc1/bionic,bionic 3.0.0-0ubuntu2 all [residual-config]
lxc2/now 2.0.11-0ubuntu1~16.04.4 all [installed,local]
lxcfs/bionic,now 3.0.0-0ubuntu1 amd64 [installed]
lxctl/bionic,bionic,now 0.3.1+debian-4 all [installed]
nova-compute-lxc/bionic,bionic 2:17.0.1-0ubuntu1 all
python-lxc/bionic 0.1-3 amd64
python3-lxc/bionic,now 3.0.1-0ubuntu1 amd64 [installed]
vagrant-lxc/bionic,bionic 1.4.0-1 all

**Comment by iam-TJ** [comment]
Initially I was working with my own extremely minimal config to learn how to write templates. I tried the "-d" option and it apparently didn't work. It works when I use it with other, system, containers.

That's when I tried to confirm that lxc-execute has the "-d" option and found that it is not documented in the --help or the man-page, as I reported.  The issue is that "-d" isn't documented anywhere that a user would normally check.

**Comment by brauner** [comment]
So `lxc-execute` has the `-d` option but is missing it in the docs. Ok, I can send a fix for this.

**Comment by iam-TJ** [comment]
Regarding the daemon behaviour, my experiments seem to show an init process is still required asn runs as PID 1 - which explains why my minimal config experiment doesn't daemonise.

**Comment by brauner** [comment]
Sorry, I'm not following. Can you show what you're trying to do?

**Comment by iam-TJ** [comment]
I'm working up from the most minimal config so I currently create a container which only has /bin/bash bind-mounted into it (plus its required libraries). I was expecting that could be directly executed in daemon mode - as I said earlier, I'm trying to get to grips with LXC fundamentals.

In the release announcement I probably mis-understood the following:

> LXC has been running application container through a minimal init system since its first release in 2008. PID namespaces expect a functional init system capable of handling signals and reaping exiting child processes. This is why application containers always run the application as the second process.
> New versions of LXC will now additionally allow you to run basically any process daemonized

I read the 2nd paragraph as describing an alternative to the 1st paragraph - that unlike what went before, a process could be daemonized (without an init system).

When I watched the asciicast it confused me since it seemed to be showing what the 1st paragraph describes, as in "This is why application containers always run the application as the second process".

So I think it is a mis-understanding on my part due to unclear description (the paragraphs have an implicit assumption that the reader understands the previous behaviour.)

**Comment by brauner** [comment]
Ok, so I might have been imprecise. Any container that clones a new pid namespace - which is most of them - will need to have a process running as PID 1 that can handle signals and reap children. This is just an implicit assumption that the kernel makes. So an application container just running a simple application won't work correctly unless the binary itself can handle signals and reap other processes in case other processes get spawned in there. This is why LXC has always provided a minimal dumb init. It ships with LXC itself and is called - usually - `init.lxc.static` and can be found in
```
chb@conventiont|~
> which init.lxc.static
/usr/sbin/init.lxc.static
```
any application that is spawned is run as the second process. So when you do

    lxc-execute <container-name>  -- bash

then bash is run as the second process and a dumb init is running. This dumb init is mounted in by LXC at container startup automatically. Can you show the container's config?

**Comment by iam-TJ** [comment]
Ahhh, thank-you. I'd seen` init.lxc.static` but so far hadn't added it to the config. I added that to the generated config, but seeing a cryptic log message:
```
lxc-execute bash-test 20180415211033.817 TRACE    lxc_container - lxccontainer.c:wait_on_daemonized_start:828 - Container is in "RUNNING" state
lxc-execute bash-test 20180415211033.817 TRACE    lxc_start - start.c:lxc_serve_state_clients:426 - No state clients registered
lxc-execute bash-test 20180415211033.817 TRACE    lxc_start - start.c:lxc_poll:580 - Mainloop is ready
lxc-execute bash-test 20180415211033.817 NOTICE   lxc_start - start.c:signal_handler:388 - Received 17 from pid 25923 instead of container init 25929
lxc-execute bash-test 20180415211033.826 DEBUG    lxc_start - start.c:signal_handler:406 - Container init process 25929 exited
lxc-execute bash-test 20180415211033.826 TRACE    lxc_start - start.c:lxc_poll:594 - Closed console mainloop
```

By the way, thank-you for taking the time to explain/demonstrate the commands.

Config:
```
# Template used to create this container: /usr/local/share/lxc/templates/lxc-bash
# Parameters passed to the template:
# Template script checksum (SHA-1): aa02241af37872b66f50e825f3751e3dbe48cd1b
# For additional config options, please look at lxc.container.conf(5)

# Uncomment the following line to support nesting containers:
#lxc.include = /usr/share/lxc/config/nesting.conf
# (Be aware this has security implications)

# Created Sun 15 Apr 2018 21:06:42 UTC by /usr/local/share/lxc/templates/lxc-bash
lxc.include = /usr/share/lxc/config/userns.conf
lxc.net.0.type = veth
lxc.net.0.link = lxcbr0
lxc.net.0.flags = up
lxc.net.0.hwaddr = 00:16:32:xx:xx:xx
lxc.idmap = u 0 1000000 65536
lxc.idmap = g 0 1000000 65536

lxc.init.uid = 1000
lxc.init.gid = 1000

lxc.include       = /usr/share/lxc/config/common.conf
lxc.rootfs.path   = /home/tj/.local/share/lxc/bash-test/rootfs
lxc.uts.name      = bash-test
lxc.arch          = x86_64
lxc.cap.drop      = sys_module mac_admin mac_override sys_time
lxc.mount.entry   = /usr/sbin/init.lxc.static             init.lxc.static                       none create=file,ro,bind 0 0
lxc.mount.entry   = /bin/bash                             bin/bash                              none create=file,ro,bind 0 0
lxc.mount.entry   = /lib/x86_64-linux-gnu/libtinfo.so.5.9 lib/x86_64-linux-gnu/libtinfo.so.5.9  none create=file,ro,bind 0 0
lxc.mount.entry   = /lib/x86_64-linux-gnu/libdl-2.27.so   lib/x86_64-linux-gnu/libdl-2.27.so    none create=file,ro,bind 0 0
lxc.mount.entry   = /lib/x86_64-linux-gnu/libc-2.27.so    lib/x86_64-linux-gnu/libc-2.27.so     none create=file,ro,bind 0 0
lxc.mount.entry   = /lib/x86_64-linux-gnu/ld-2.27.so      lib/x86_64-linux-gnu/ld-2.27.so       none create=file,ro,bind 0 0

#lxc.mount.entry   = devpts dev/pts devpts rw,nosuid,noexec,relatime 0 0
lxc.include       = /usr/share/lxc/config/userns.conf
```

**Comment by iam-TJ** [comment]
To save dumping lots of possibly miscellaneous text into this issue about the documentation I've put all the files at http://iam.tj/projects/lxc/

**Comment by brauner** [comment]
I suspect that the container creation script is not setting up things correctly because the config looks fine. The container also exits with an error so somehow `/bin/bash` doesn't seem to happy. Can you try:

    lxc-create busy1 -t busybox
    lxc-execute busy1 -- sh

**Comment by iam-TJ** [comment]
Yes, I've got a busybox container (from the busybox template) that works fine.

I'm doing this to fully understand what is required to create the minimal config for any arbitrary executable (only including what is absolutely necessary), in order to develop a tool that can automate the analysis.

I began by wrapping /bin/bash in strace to identify files and sockets it might access. The intention being to gradually build up the config as more of bash's (internal) functionality is exercised (/dev/tcp/ and friends).

**Comment by iam-TJ** [comment]
I'm digging in now; I've added /bin/static-sh (busybox static) into the container and can execute that. It cannot execute /bin/bash so I think I've missed some resources.

Many thanks for all the help this evening; it is extremely appreciated since you've been able to confirm  my intuition that the config was correct, and cleared up my understanding of application container requirements.

**Comment by brauner** [comment]
It's all good. We're here to help where ever we can. :)

**Comment by brauner** [comment]
s/where ever/wherever/

**Comment by iam-TJ** [comment]
OK, found the problem, one of the SO symlinks created by the template was wrong.

    ln -sf "ld-2.27.so" "$rootfs/lib64/ld-linux-x86-64.so.2"

should be

    ln -sf "/lib/x86_64-linux-gnu/ld-2.27.so" "$rootfs/lib64/ld-linux-x86-64.so.2"

Stupid mistake due to staring at this stuff for too many hours! Once again, thanks so much for helping me regain focus on the source of the issue.
