### ISSUE TITLE
Ubuntu LXC  no longer starts under LXC 2.0.9 and Kernel 4.16.1 (OpenSUSE)

### ISSUE THREAD

**Issue by toeserve** [lxc/lxc#2286]
An ubuntu LXC container no longer starts up, we get errors relating to not being able to mount rootfs (see below).

# Required information

 * Distribution: OpenSUSE
 * Distribution version: Tumbleweed  
 * The output of
   * `lxc-start --version`  2.0.9

   * `lxc-checkconfig`
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/memory
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/devices
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/freezer
/sys/fs/cgroup/blkio
/sys/fs/cgroup/rdma
/sys/fs/cgroup/pids
/sys/fs/cgroup/hugetlb

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, not loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, not loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loadedCONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration

usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -a`Linux localhost 4.16.1-1-default #1 SMP PREEMPT Mon Apr 9 06:27:59 UTC 2018 (fc6541a) x86_64 x86_64 x86_64 GNU/Linux

   * `cat /proc/self/cgroup`
cat /proc/self/cgroup
12:hugetlb:/
11:pids:/user.slice/user-1002.slice/session-4.scope
10:rdma:/
9:blkio:/user.slice
8:freezer:/
7:perf_event:/
6:devices:/user.slice
5:cpu,cpuacct:/user.slice
4:cpuset:/
3:memory:/user.slice
2:net_cls,net_prio:/
1:name=systemd:/user.slice/user-1002.slice/session-4.scope
0::/user.slice/user-1002.slice/session-4.scope

   * `cat /proc/1/mounts`
 cat /proc/1/mounts
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
devtmpfs /dev devtmpfs rw,nosuid,size=2011744k,nr_inodes=502936,mode=755 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,mode=755 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
/dev/mapper/system-root / btrfs rw,relatime,space_cache,subvolid=259,subvol=/@/.snapshots/1/snapshot 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=40,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14592 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
/dev/mapper/system-root /var/log btrfs rw,relatime,space_cache,subvolid=276,subvol=/@/var/log 0 0
/dev/mapper/system-root /.snapshots btrfs rw,relatime,space_cache,subvolid=258,subvol=/@/.snapshots 0 0
/dev/mapper/system-root /var/lib/libvirt/images btrfs rw,relatime,space_cache,subvolid=269,subvol=/@/var/lib/libvirt/images 0 0
/dev/mapper/system-root /var/lib/mysql btrfs rw,relatime,space_cache,subvolid=273,subvol=/@/var/lib/mysql 0 0
/dev/mapper/system-root /var/lib/mailman btrfs rw,relatime,space_cache,subvolid=271,subvol=/@/var/lib/mailman 0 0
/dev/mapper/system-root /boot/grub2/x86_64-efi btrfs rw,relatime,space_cache,subvolid=261,subvol=/@/boot/grub2/x86_64-efi 0 0
/dev/mapper/system-root /var/lib/machines btrfs rw,relatime,space_cache,subvolid=270,subvol=/@/var/lib/machines 0 0
/dev/mapper/system-root /boot/grub2/i386-pc btrfs rw,relatime,space_cache,subvolid=260,subvol=/@/boot/grub2/i386-pc 0 0
/dev/mapper/system-root /usr/local btrfs rw,relatime,space_cache,subvolid=266,subvol=/@/usr/local 0 0
/dev/mapper/system-root /var/lib/named btrfs rw,relatime,space_cache,subvolid=274,subvol=/@/var/lib/named 0 0
/dev/mapper/system-root /var/lib/mariadb btrfs rw,relatime,space_cache,subvolid=272,subvol=/@/var/lib/mariadb 0 0
/dev/mapper/system-root /var/lib/pgsql btrfs rw,relatime,space_cache,subvolid=275,subvol=/@/var/lib/pgsql 0 0
/dev/mapper/system-root /srv btrfs rw,relatime,space_cache,subvolid=264,subvol=/@/srv 0 0
/dev/mapper/system-root /var/crash btrfs rw,relatime,space_cache,subvolid=268,subvol=/@/var/crash 0 0
/dev/mapper/system-root /var/opt btrfs rw,relatime,space_cache,subvolid=277,subvol=/@/var/opt 0 0
/dev/mapper/system-root /opt btrfs rw,relatime,space_cache,subvolid=263,subvol=/@/opt 0 0
/dev/mapper/system-root /var/tmp btrfs rw,relatime,space_cache,subvolid=279,subvol=/@/var/tmp 0 0
/dev/mapper/system-root /tmp btrfs rw,relatime,space_cache,subvolid=265,subvol=/@/tmp 0 0
/dev/mapper/system-root /var/cache btrfs rw,relatime,space_cache,subvolid=267,subvol=/@/var/cache 0 0
/dev/mapper/system-root /home btrfs rw,relatime,space_cache,subvolid=262,subvol=/@/home 0 0
/dev/mapper/system-root /var/spool btrfs rw,relatime,space_cache,subvolid=278,subvol=/@/var/spool 0 0
tmpfs /run/user/1001 tmpfs rw,nosuid,nodev,relatime,size=404176k,mode=700,uid=1001,gid=100 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
gvfsd-fuse /run/user/1001/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1001,group_id=100 0 0
tmpfs /run/user/1002 tmpfs rw,nosuid,nodev,relatime,size=404176k,mode=700,uid=1002,gid=100 0 0
gvfsd-fuse /home/user2/.gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1003,group_id=100 0 0

# Issue description

Starting LXC fails, command: lxc-start -F -l DEBUG --logfile lxclog -n ubuntu-c1

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
t 
      lxc-start 20180421184557.399 INFO     lxc_start_ui - tools/lxc_start.c:main:277 - using rcfile /var/lib/lxc/ubuntu-c1/config
      lxc-start 20180421184557.399 WARN     lxc_confile - confile.c:set_config_pivotdir:2262 - lxc.pivotdir is ignored.  It will soon become an error.
      lxc-start 20180421184557.401 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
      lxc-start 20180421184557.401 INFO     lxc_seccomp - seccomp.c:parse_config_v2:435 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
      lxc-start 20180421184557.401 INFO     lxc_seccomp - seccomp.c:parse_config_v2:610 - Adding native rule for reject_force_umount action 0(kill).
      lxc-start 20180421184557.401 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:276 - Setting Seccomp rule to reject force umounts.
      lxc-start 20180421184557.401 INFO     lxc_seccomp - seccomp.c:parse_config_v2:614 - Adding compat rule for reject_force_umount action 0(kill).
      lxc-start 20180421184557.401 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:276 - Setting Seccomp rule to reject force umounts.
      lxc-start 20180421184557.401 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:276 - Setting Seccomp rule to reject force umounts.
      lxc-start 20180421184557.401 INFO     lxc_seccomp - seccomp.c:parse_config_v2:435 - processing: .[all].
      lxc-start 20180421184557.401 INFO     lxc_seccomp - seccomp.c:parse_config_v2:435 - processing: .kexec_load errno 1.
      lxc-start 20180421184557.401 INFO     lxc_seccomp - seccomp.c:parse_config_v2:610 - Adding native rule for kexec_load action 327681(errno).
      lxc-start 20180421184557.401 INFO     lxc_seccomp - seccomp.c:parse_config_v2:614 - Adding compat rule for kexec_load action 327681(errno).
      lxc-start 20180421184557.401 INFO     lxc_seccomp - seccomp.c:parse_config_v2:435 - processing: .open_by_handle_at errno 1.
      lxc-start 20180421184557.401 INFO     lxc_seccomp - seccomp.c:parse_config_v2:610 - Adding native rule for open_by_handle_at action 327681(errno).
      lxc-start 20180421184557.401 INFO     lxc_seccomp - seccomp.c:parse_config_v2:614 - Adding compat rule for open_by_handle_at action 327681(errno).
      lxc-start 20180421184557.402 INFO     lxc_seccomp - seccomp.c:parse_config_v2:435 - processing: .init_module errno 1.
      lxc-start 20180421184557.402 INFO     lxc_seccomp - seccomp.c:parse_config_v2:610 - Adding native rule for init_module action 327681(errno).
      lxc-start 20180421184557.402 INFO     lxc_seccomp - seccomp.c:parse_config_v2:614 - Adding compat rule for init_module action 327681(errno).
      lxc-start 20180421184557.402 INFO     lxc_seccomp - seccomp.c:parse_config_v2:435 - processing: .finit_module errno 1.
      lxc-start 20180421184557.402 INFO     lxc_seccomp - seccomp.c:parse_config_v2:610 - Adding native rule for finit_module action 327681(errno).
      lxc-start 20180421184557.402 INFO     lxc_seccomp - seccomp.c:parse_config_v2:614 - Adding compat rule for finit_module action 327681(errno).
      lxc-start 20180421184557.402 INFO     lxc_seccomp - seccomp.c:parse_config_v2:435 - processing: .delete_module errno 1.
      lxc-start 20180421184557.402 INFO     lxc_seccomp - seccomp.c:parse_config_v2:610 - Adding native rule for delete_module action 327681(errno).
      lxc-start 20180421184557.402 INFO     lxc_seccomp - seccomp.c:parse_config_v2:614 - Adding compat rule for delete_module action 327681(errno).
      lxc-start 20180421184557.402 INFO     lxc_seccomp - seccomp.c:parse_config_v2:624 - Merging in the compat Seccomp ctx into the main one.
      lxc-start 20180421184557.403 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20180421184557.403 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20180421184557.403 DEBUG    lxc_start - start.c:setup_signal_fd:288 - Set SIGCHLD handler with file descriptor: 5.
      lxc-start 20180421184557.404 DEBUG    console - console.c:lxc_console_peer_default:459 - using "/dev/tty" as peer tty device
      lxc-start 20180421184557.404 DEBUG    console - console.c:lxc_console_sigwinch_init:151 - process 4757 created signal fd 9 to handle SIGWINCH events
      lxc-start 20180421184557.404 DEBUG    console - console.c:lxc_console_winsz:71 - set winsz dstfd:6 cols:171 rows:14
      lxc-start 20180421184557.404 INFO     lxc_start - start.c:lxc_init:677 - container "ubuntu-c1" is initialized
      lxc-start 20180421184557.405 DEBUG    lxc_start - start.c:__lxc_start:1501 - Not dropping CAP_SYS_BOOT or watching utmp.
      lxc-start 20180421184557.405 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:67 - cgroup driver cgroupfs-ng initing for ubuntu-c1
      lxc-start 20180421184557.406 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:filter_and_set_cpus:456 - No isolated cpus detected.
      lxc-start 20180421184557.406 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:handle_cpuset_hierarchy:627 - "cgroup.clone_children" was already set to "1".
      lxc-start 20180421184557.449 INFO     lxc_start - start.c:lxc_spawn:1324 - Cloned CLONE_NEWNS.
      lxc-start 20180421184557.449 INFO     lxc_start - start.c:lxc_spawn:1324 - Cloned CLONE_NEWPID.
      lxc-start 20180421184557.449 INFO     lxc_start - start.c:lxc_spawn:1324 - Cloned CLONE_NEWUTS.
      lxc-start 20180421184557.449 INFO     lxc_start - start.c:lxc_spawn:1324 - Cloned CLONE_NEWIPC.
      lxc-start 20180421184557.449 INFO     lxc_start - start.c:lxc_spawn:1324 - Cloned CLONE_NEWNET.
      lxc-start 20180421184557.449 INFO     lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1976 - cgroup has been setup
      lxc-start 20180421184557.450 INFO     lxc_start - start.c:do_start:1001 - Unshared CLONE_NEWCGROUP.
      lxc-start 20180421184557.459 DEBUG    storage - storage/storage.c:storage_query:233 - Detected rootfs type "dir"
      lxc-start 20180421184557.459 ERROR    lxc_conf - conf.c:lxc_setup_rootfs:1254 - Failed to mount rootfs "/var/lib/lxc/ubuntu-c1/rootfs" onto "/usr/lib64/lxc/rootfs" with options "(null)".
      lxc-start 20180421184557.459 ERROR    lxc_conf - conf.c:do_rootfs_setup:3044 - failed to setup rootfs for 'ubuntu-c1'
      lxc-start 20180421184557.459 ERROR    lxc_conf - conf.c:lxc_setup:3085 - Error setting up rootfs mount after spawn
      lxc-start 20180421184557.459 ERROR    lxc_start - start.c:do_start:1020 - Failed to setup container "ubuntu-c1".
      lxc-start 20180421184557.460 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
      lxc-start 20180421184557.460 DEBUG    lxc_network - network.c:lxc_delete_network:3096 - Deleted network devices
      lxc-start 20180421184557.460 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20180421184557.460 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20180421184557.460 ERROR    lxc_start - start.c:__lxc_start:1530 - Failed to spawn container "ubuntu-c1".
      lxc-start 20180421184557.460 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20180421184557.460 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20180421184557.468 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20180421184557.468 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20180421184557.468 INFO     lxc_conf - conf.c:run_script_argv:398 - Executing script "/usr/share/lxcfs/lxc.reboot.hook" for container "ubuntu-c1", config section "lxc".
      lxc-start 20180421184558.275 ERROR    lxc_start_ui - tools/lxc_start.c:main:368 - The container failed to start.
      

 - [ ] the containers configuration file
cat config
# Template used to create this container: /usr/share/lxc/templates/lxc-download
# Parameters passed to the template: -d ubuntu -r artful -a amd64
# For additional config options, please look at lxc.container.conf(5)

# Uncomment the following line to support nesting containers:
#lxc.include = /usr/share/lxc/config/nesting.conf
# (Be aware this has security implications)

# Distribution configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.arch = x86_64

# Container specific configuration
lxc.rootfs = /var/lib/lxc/ubuntu-c1/rootfs
lxc.rootfs.backend = dir
lxc.utsname = ubuntu-c1

# Network configuration
lxc.network.type = empty

**Comment by toeserve** [comment]
This is actually caused by a bad apparmor profile, disabling apparmor with aa-complain usr.bin.lxc-start will fix this issue.

**Comment by brauner** [comment]
Yeah, it sounds like an AppArmor bug. Anything interesting in `dmesg`? There has been a lot of upstreaming wrt to AppArmor.
