### ISSUE TITLE
proxy device type to forward network connection 

### ISSUE THREAD

**Issue by esosan** [lxc/lxc#2298]
Hi,
I was really happy for this new feature, but then I have a sad discover: on the containers the proxied connections comes always from lxdbr0 ip.

It would be nice to expand this feature to nat the incoming connection to the container.

Best regards, Davide

**Comment by stgraber** [comment]
That'd be a LXD issue rather than liblxc, so that should be reported at https://github.com/lxc/lxd.

It was our intent to add NAT optimization, though we'll need to restrict this quite a bit. I'll provide more details once you have it reported there.
