### ISSUE TITLE
centos 7.4, 1.011, lxc-attach and lxc-stop are not working

### ISSUE THREAD

**Issue by slesru** [lxc/lxc#2304]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Centos 
 * Distribution version: 7.4

both container and host

 * The output of
   * `lxc-start --version` 1.0.11
   * `lxc-checkconfig`

lxc-checkconfig
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-3.10.0-693.11.1.el7.x86_64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
newuidmap is not installed
newgidmap is not installed
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: enabled
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -a`
3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`

 cat /proc/self/cgroup
11:net_prio,net_cls:/
10:cpuset:/
9:cpuacct,cpu:/user.slice
8:perf_event:/
7:freezer:/
6:hugetlb:/
5:memory:/user.slice
4:devices:/user.slice/user-0.slice
3:pids:/user.slice
2:blkio:/user.slice
1:name=systemd:/user.slice/user-0.slice/session-5055843.scope

   * `cat /proc/1/mounts`

cat /proc/self/cgroup
11:net_prio,net_cls:/
10:cpuset:/
9:cpuacct,cpu:/user.slice
8:perf_event:/
7:freezer:/
6:hugetlb:/
5:memory:/user.slice
4:devices:/user.slice/user-0.slice
3:pids:/user.slice
2:blkio:/user.slice
1:name=systemd:/user.slice/user-0.slice/session-5055843.scope
[root@vmhost1 network-scripts]# cat /proc/1/mounts
rootfs / rootfs rw 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
devtmpfs /dev devtmpfs rw,nosuid,size=32828996k,nr_inodes=8207249,mode=755 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,mode=755 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct,cpu 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_prio,net_cls 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
/dev/sda2 / ext4 rw,relatime,stripe=64,data=ordered 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=33,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=16197 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
nfsd /proc/fs/nfsd nfsd rw,relatime 0 0
/dev/mapper/vglocal-lvgluster /wall/pool xfs rw,relatime,attr2,inode64,logbsize=256k,sunit=512,swidth=512,noquota 0 0
sunrpc /var/lib/nfs/rpc_pipefs rpc_pipefs rw,relatime 0 0
/dev/mapper/mpathzabbixroot /var/lib/lxc/zabbix ext4 rw,relatime,data=ordered 0 0
/dev/mapper/mpathneftisarouter /var/lib/lxc/neftisa-router ext4 rw,relatime,stripe=256,data=ordered 0 0
/dev/mapper/mpathgk /var/lib/lxc/gk ext4 rw,relatime,stripe=256,data=ordered 0 0
/dev/mapper/mpathp100vpnx /var/lib/lxc/p100-vpn-x ext4 rw,relatime,stripe=256,data=ordered 0 0
/dev/mapper/mpathnetflow /var/lib/lxc/netflow ext4 rw,relatime,stripe=256,data=ordered 0 0
tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=6567852k,mode=700 0 0

# Issue description

Can't attach to container console or stop it.

# Steps to reproduce

lxc-attach -n netflow  
stays forever without any output

if run it with strace I get:

socket(AF_LOCAL, SOCK_STREAM, 0)        = 3
connect(3, {sa_family=AF_LOCAL, sun_path=@"/var/lib/lxc/netflow/command"}, 31) = 0
getuid()                                = 0
getgid()                                = 0
sendmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\4\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16}], msg_controllen=32, [{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=23225, uid=0, gid=0}}], msg_flags=0}, MSG_NOSIGNAL) = 16
recvmsg(3, 

absoutely the same output from  lxc-stop -n  netflow 
 
I run several centos 7 containers on this host and all have the same problem.

Container can be shutted down from it by poweroff with no problems and can be started.

# Information to attach

containers configuration file

Container config is attached

btw, selinux is disabled on host

 sestatus 
SELinux status:                 disabled

[config.txt](https://github.com/lxc/lxc/files/1973311/config.txt)

I don't know when this happened , it worked last time I checked, may be with previous lxc version...

Thank you!

**Comment by brauner** [comment]
Does `lxc-console` work?

**Comment by slesru** [comment]
No, the same result.

connect(3, {sa_family=AF_LOCAL, sun_path=@"/var/lib/lxc/netflow/command"}, 31) = 0
getuid()                                = 0
getgid()                                = 0
sendmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"\4\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16}], msg_controllen=32, [{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, {pid=24082, uid=0, gid=0}}], msg_flags=0}, MSG_NOSIGNAL) = 16
recvmsg(3, 

All commands get no answer from command socket , let's say, /var/lib/lxc/netflow/command

Btw, this is only host I hae problems, but I have about 5 containers on it,
other centos 7 host have just one per host, everything is fine there.

**Comment by gstanden** [comment]
Hi @slesru 1.0.11 is pretty old version of LXC it's the one from the epel repo you are using I guess. It sounds like upgrading your LXC is not on your agenda, but I offer this comment in case it helps.  Also, I know you may already know how to build LXC from source on CentOS, so again, please forgive if I mentions topics of which you are already skilled.

If you are open to upgrading LXC, you might want to try that approach.  The actual steps to build LXC from source on CentOS 7 are in my Orabuntu-LXC software at github which has the commands to build LXC from source on CentOS 7 (https://github.com/gstanden/orabuntu-lxc) and use the "uekulele" code tree which is for RedHat-family linuxes.  The steps to build from source can just be cut and pasted out of uekulele-services-1.sh script.

If you do upgrade though, as you may already know, be aware that (as I recall) the default location for containers rootfs will move from /container to /var/lib/lxc.

HTH Gilbert

**Comment by slesru** [comment]
Yes, I use 1.0.11 from epel, and, as far as I know, 1.0 is still supported version and will be supported for about a year, so I'd like to find cause of my problem and get it fixed, not just upgrade software and hope it will help. Really, 1.0 is doing everything I need now , only problem is that it, or , mey be, centos 7 kernel, has bugs :-)
Could somebody tell me what no answer from command socket ( /var/lib/lxc/netflow/command ) means? 
Is this kernel or user-space problem, what should answer for these command?

Thank you!

**Comment by slesru** [comment]
btw, I'm wrong, from 6 containers on this host, I can connect  (lxc-attach) to 3  , and can't connect to 3 others.
I can't connect to containers started by autostart- I see them as /usr/bin/lxc-autostart -g onboot,
and can't connect to started later, like
22522 ?        S      0:00 lxc-start -n netflow

So , I see some difference between good and bad containers ;-) , but have no idea what it means...

Thank you!

**Comment by slesru** [comment]
Well, finally, I know difference and what cause this problem.
I don't know how lxc-autostart starts containers ( can have a look, but out of time right now), but looks like it starts them using lxc-start -d equivalent.

So, if I ssh to host and start container using lxc-start -n container , then I can do lxc-attach or whatever else until I do not close this terminal session ( not click close button in gnome-terminal, to be specific),
right after I close session I can't  lxc-attach, lxc-console, whatever else.

But, if I start container using lxc-start -d -n container , then everything is fine and works as expected.
I don't know is this lxc bug, kernel bug or systemd bug ( because all containers are centos 7) or expected behavior, but it worked without any problem in both cases some time ago.

Thank you!

**Comment by brauner** [comment]
@slesru, that sounds like systemd is not correctly booting. If you attach to one of those non-responsive containers, what does `ps auxf` show you in there?

**Comment by slesru** [comment]
I can't attach, but I can access it over ssh:

 LANG=C ps auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  43148  3400 ?        Ss   янв03   0:57 /usr/lib/systemd/systemd --system --deserialize 16
root        16  0.0  0.0  53200 13684 ?        Ss   янв03   2:35 /usr/lib/systemd/systemd-journald
root        27  0.0  0.0  24444  1332 ?        Ss   янв03   0:16 /usr/lib/systemd/systemd-logind
dbus        29  0.0  0.0  24392  1248 ?        Ss   янв03   0:13 /bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
root        38  0.0  0.0  88716   552 ?        Ss   янв03   0:00 login -- root
root       352  0.0  0.0  11760   444 lxc/console Ss+ янв03   0:00  \_ -bash
quagga      44  0.0  0.0 112812   988 ?        Ss   янв03   0:06 /usr/sbin/zebra -d -A 127.0.0.1 -f /etc/quagga/zebra.conf
quagga      55  0.0  1.6 1204352 1078008 ?     Ss   янв03  36:05 /usr/sbin/ospfd -d -A 127.0.0.1 -f /etc/quagga/ospfd.conf
root       344  0.1  0.0  47820  6004 ?        Ssl  янв03 331:47 /usr/sbin/fprobe -ieth1 -fip 192.168.22.30:3011
root     14493  0.0  0.0  89468   780 ?        Ss   фев07   0:33 /usr/libexec/postfix/master -w
postfix  14495  0.0  0.0  89748  1424 ?        S    фев07   0:05  \_ qmgr -l -t unix -u
postfix  17832  0.0  0.0  89648  4000 ?        S    14:16   0:00  \_ pickup -l -t unix -u
root     11937  0.0  0.0 105996  4104 ?        Ss   май07   0:00 /usr/sbin/sshd -D
root     17833  0.4  0.0 142108  5884 ?        Ss   14:47   0:00  \_ sshd: root@pts/0
root     17835  0.0  0.0 115388  2104 pts/0    Ss   14:47   0:00      \_ -bash
root     17849  0.0  0.0 151028  1692 pts/0    R+   14:47   0:00          \_ ps auxf
root     11966  0.0  0.0 459544  5184 ?        Ssl  май07   0:02 /usr/sbin/rsyslogd -n
zabbix   11989  0.0  0.0  80484  1372 ?        S    май07   0:00 /usr/sbin/zabbix_agentd
zabbix   11990  0.0  0.0  80484  3568 ?        S    май07   0:41  \_ /usr/sbin/zabbix_agentd: collector [idle 1 sec]
zabbix   11991  0.0  0.0  84680  1868 ?        S    май07   0:01  \_ /usr/sbin/zabbix_agentd: listener #1 [waiting for connection]
zabbix   11992  0.0  0.0  84680  1868 ?        S    май07   0:01  \_ /usr/sbin/zabbix_agentd: listener #2 [waiting for connection]
zabbix   11993  0.0  0.0  84680  1868 ?        S    май07   0:01  \_ /usr/sbin/zabbix_agentd: listener #3 [waiting for connection]
zabbix   11994  0.0  0.0  80484  1352 ?        S    май07   0:02  \_ /usr/sbin/zabbix_agentd: active checks #1 [idle 1 sec]
root     12009  0.0  0.0  22672  1568 ?        Ss   май07   0:00 /usr/sbin/crond -n
root     12454  0.0  0.0  12732   772 ?        Ss   03:28   0:00 /usr/sbin/incrond
snort    17630  0.3  0.7 589248 501452 ?       Ssl  04:00   2:09 /usr/sbin/snort -A fast -b -d -D -i eth1 -u snort -g snort -c /etc/snort/snort.conf -l /var/log/snort

Looks good for me.
all others I already restarted using -d key.

**Comment by slesru** [comment]
Why it is closed? Bug still exists!
