### ISSUE TITLE
Enhancement Request - Remove CRIU check or add flag to disable CRIU checks

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxc#2310]
CRIU checks are inconsistent.

Local copies of running containers are allowed, while remote copies are disallowed.

With a running a local container...
```
# Local copy works
lxc copy c1 c2

# Remote copy fails with - Live migration failed as CRIU isn't installed
lxc copy c1 foo:c2
```
The ugly work around is to stop c1 + start copy + restart c1 (while copy in process).

This seems overly complex + makes very little sense. There's no difference when a live container copies to another local container or remote container.

CRIU checks should be consistent... enforced always (copy to local or remote) or never.

If CRIU checks occur good to add a --disable-criu-checks flag, so circumvent these checks.

Consider copy of a 100G container to a remote, which might take a very long time.

Having CRIU block this has to be worked around via the hack above, which is overly ugly.

**Comment by brauner** [comment]
That's why a while back we added the `--stateless` flag. This allwos you to copy a running container even though `criu` is installed. We cannot change this behavior now as this would break existing users.

Please also note, that this issue should have been filed against LXD.
