### ISSUE TITLE
A question about handler->conf->maincmd_fd

### ISSUE THREAD

**Issue by duguhaotian** [lxc/lxc#2330]
Now we close maincmd_fd at two place:
+  if reboot is true, close at lxc_fini and after run post-stop hooks.
+ if reboot is false, close at lxc_fini and before run post-stop hooks.

question: Why we don't close maincmd_fd at lxc_poll, when lxc_mainloop is finish???

When lxc_mainloop  is finish, maincmd_fd is unuseful and maybe problem.
For example, if post-stop hook run "sleep 100", and other window we query state of this container.
We will get state of container, must wait for post-stop hook finish.

**Comment by brauner** [comment]
Because you're otherwise racing with other processes that want to start the container, e.g. in multi-threaded environments. The container is technically still alive although in `STOPPED` or `STOPPING` state.

**Comment by duguhaotian** [comment]
Thanks.
