### ISSUE TITLE
lxc-update-config misses old lxc.include common config

### ISSUE THREAD

**Issue by erickeller** [lxc/lxc#2331]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu 
 * Distribution version: 17.10
 * `lxc-start --version` 3.0.0

# Issue description

Updating from lxc 2.21.x to 3.0.0 and applying the `lxc-update-config -c /var/lib/lxc/mycontainer/config`

Did result in following diff:
```
diff -uri config.backup config
--- config.backup	2018-05-15 20:44:02.407088962 +0200
+++ config	2018-05-15 20:44:02.511088792 +0200
@@ -15,7 +15,7 @@
 lxc.net.0.flags = up
 lxc.net.0.hwaddr = 00:16:3e:zz:zz:zz
 lxc.rootfs.path = dir:/var/lib/lxc/mycontainer/rootfs
-lxc.utsname = mycontainer
+lxc.uts.name = mycontainer
```

Unfortunately trying to list `lxc-ls -f` this container results in:
```
lxc-ls: parse.c: lxc_file_for_each_line_mmap: 102 Failed to parse config: lxc.include = /usr/share/lxc/config/ubuntu.common.conf
Failed to load config for mycontainer
```
In fact the `lxc.include = /usr/share/lxc/config/ubuntu.common.conf` template configuration does not exist anymore in this form.

changing it to `lxc.include = /usr/share/lxc/config/common.conf` did the trick.

I would expect that the lxc-update-config tool checks the validity of this include and at least warns the user that this old configuration does not exist anymore.

# Steps to reproduce

 1. create a container with lxc 2.x
 2. use lxc-update-config -c /path/to/this/container/config
 3. lxc-ls -f

**Comment by ITwrx** [comment]
hi,

would you mind telling me what the steps are for migrating from 2x to 3.0 in regards to this "lxc.include" stuff? 

i've read the release notes, but i'm not seeing/getting it. from an end user's perspective, it would be nice if future release notes said explicitly what to do to migrate to a new version or linked to a migration guide, if necessary. i read the linked blog post and it explained various things (all good to know) but it didn't mention how to migrate an existing, previously working 2.x container to 3.x, as far as i could tell. I tried the config update script at one point, but it didn't work.

lxc is not able to start containers and complains about the lxc.include directive so, do i need to copy the contents of /usr/share/lxc/config/common.conf and /usr/share/lxc/config/archlinux.common.conf to /var/lib/lxc/containername/config? (see below for details) or is any/all of their contents default already and completely unecessary to include with 3.x?

thanks in advance

```
#archlinux.common.conf

# Allow for 6 tty devices by default
lxc.tty.max = 6

# Set the halt/stop signals
lxc.signal.halt=SIGRTMIN+4
lxc.signal.stop=SIGRTMIN+14

# Capabilities to drop
lxc.cap.drop = setfcap sys_nice sys_pacct sys_rawio

--------------------------------------------------
#common.conf

# Setup the LXC devices in /dev/lxc/
lxc.tty.dir = lxc

# Allow for 1024 pseudo terminals
lxc.pty.max = 1024

# Setup 4 tty devices
lxc.tty.max = 4

# Drop some harmful capabilities
lxc.cap.drop = mac_admin mac_override sys_time sys_module sys_rawio

# Ensure hostname is changed on clone
lxc.hook.clone = /usr/share/lxc/hooks/clonehostname

# CGroup whitelist
lxc.cgroup.devices.deny = a
## Allow any mknod (but not reading/writing the node)
lxc.cgroup.devices.allow = c *:* m
lxc.cgroup.devices.allow = b *:* m
## Allow specific devices
### /dev/null
lxc.cgroup.devices.allow = c 1:3 rwm
### /dev/zero
lxc.cgroup.devices.allow = c 1:5 rwm
### /dev/full
lxc.cgroup.devices.allow = c 1:7 rwm
### /dev/tty
lxc.cgroup.devices.allow = c 5:0 rwm
### /dev/console
lxc.cgroup.devices.allow = c 5:1 rwm
### /dev/ptmx
lxc.cgroup.devices.allow = c 5:2 rwm
### /dev/random
lxc.cgroup.devices.allow = c 1:8 rwm
### /dev/urandom
lxc.cgroup.devices.allow = c 1:9 rwm
### /dev/pts/*
lxc.cgroup.devices.allow = c 136:* rwm
### fuse
lxc.cgroup.devices.allow = c 10:229 rwm

# Setup the default mounts
lxc.mount.auto = cgroup:mixed proc:mixed sys:mixed
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none bind,optional 0 0

# Blacklist some syscalls which are not safe in privileged
# containers
lxc.seccomp.profile = /usr/share/lxc/config/common.seccomp

# Lastly, include all the configs from /usr/share/lxc/config/common.conf.d/
lxc.include = /usr/share/lxc/config/common.conf.d/
```

**Comment by moozhub** [comment]
This is also true with Fedora and a CentOS package that I built. 

From the build log --

LXC 2.x:

```
make[4]: Nothing to be done for `install-exec-am'.
 /usr/bin/mkdir -p '/builddir/build/BUILDROOT/lxc-2.0.9-1.el7.x86_64/usr/share/lxc/config'
 /usr/bin/install -c -m 644 alpine.common.conf alpine.userns.conf archlinux.common.conf archlinux.userns.conf centos.common.conf centos.userns.conf common.conf common.seccomp debian.common.conf debian.userns.conf fedora.common.conf fedora.userns.conf gentoo.common.conf gentoo.moresecure.conf gentoo.userns.conf nesting.conf opensuse.common.conf opensuse.userns.conf oracle.common.conf oracle.userns.conf plamo.common.conf plamo.userns.conf slackware.common.conf slackware.userns.conf ubuntu-cloud.common.conf ubuntu-cloud.lucid.conf ubuntu-cloud.userns.conf ubuntu.common.conf ubuntu.lucid.conf ubuntu.userns.conf openwrt.common.conf sparclinux.common.conf sparclinux.userns.conf userns.conf '/builddir/build/BUILDROOT/lxc-2.0.9-1.el7.x86_64/usr/share/lxc/config'
```

LXC 3.0.1:

```
make[4]: Nothing to be done for `install-exec-am'.
/usr/bin/mkdir -p '/builddir/build/BUILDROOT/lxc-3.0.1-1.el7.x86_64/usr/share/lxc/config'
/usr/bin/install -c -m 644 common.conf common.seccomp nesting.conf oci.common.conf userns.conf '/builddir/build/BUILDROOT/lxc-3.0.1-1.el7.x86_64/usr/share/lxc/config'
```

Install doesn't appear to be creating those files at all, so the packaging process isn't including them.

I ended up just copying one of the configs that I was using from the older package and doing a lxc-update-config on the old container configurations and everything was normal after that.

**Comment by ric96** [comment]
try
```$ lxc-update-config -c <path to old config>```

**Comment by brauner** [comment]
The `lxc.include` lines are preserved in case users install the `lxc-templates` package which we kinda expect them to do if they preserve old containers. However, if this becomes a frequent issue we might be able to patch `lxc-update-config` to handle that case. So please comment here if this is a big issue. Sorry for the delayed reply.

**Comment by gnutix** [comment]
I ran into the issue too. I fixed it with `sudo ln -s /usr/share/lxc/config/common.conf /usr/share/lxc/config/ubuntu.common.conf`.

**Comment by kensouss** [comment]
I had the same problem with centos7 container.
Here was the solution for me:

1-

```
vi  /var/lib/lxc/<<container_name>>/config
```

replace the line
```
lxc.include = /usr/share/lxc/config/centos.common.conf
```
with
```
lxc.include = /usr/share/lxc/config/common.conf
```

2- execute the command: 
```
lxc-update-config -c  /var/lib/lxc/<<container_name>>/config
```
