### ISSUE TITLE
Unable to resize the disk space on LXD container

### ISSUE THREAD

**Issue by tchimih** [lxc/lxc#2334]
Hello,

I'm currently running my ubuntu server on ubuntu 16.03 LTS using lxd server version 2.0.11. When I try to increase my disk space (according to the documentation https://stgraber.org/2016/03/26/lxd-2-0-resource-control-412/) no error is displayed. However: 

 * When I run df-h  inside my container, the disk size is the same.

I use LXD alongside with ZFS. Can you help out here ?

Thanks,

**Comment by brauner** [comment]
The disk size limit is a quota, i.e. it will limit the amount of space that the container can use. It won't change the size of the underlying storage volume itself. What should change in the `df -h` output is the `Avail` field.

If this doesn't solve your issue please re-open against https://github.com/lxc/lxd as this here is the shared library that LXD is using. :)
