### ISSUE TITLE
unprivileged lxc won't execute lxc.net.[i].script.up

### ISSUE THREAD

**Issue by harryoooooooooo** [lxc/lxc#2335]
# Issue description

I have traced the code in network.c and notice that _**lxc_create_network_priv()**_ would call instantiate functions(e.g. _**instantiate_veth()**_) and they do execute the script define by _**lxc.net.[i].script.up**_.

However, _**lxc_create_network_unpriv()**_ would just exec _**lxc-user-nic**_ and never deal with the script.

By the way, both priv and unpirv lxc execute _**lxc.net.[i].script.down**_.

Is this a feature or a bug?

**Comment by brauner** [comment]
On Fri, May 18, 2018 at 05:05:10AM -0700, 莊昕宸 wrote:
> # Issue description
> 
> I have traced the code in network.c and notice that _**lxc_create_network_priv()**_ would call instantiate functions(e.g. _**instantiate_veth()**_) and they do execute the script define by _**lxc.net.[i].script.up**_.
> 
> However, _**lxc_create_network_unpriv()**_ would just exec _**lxc-user-nic**_ and never deal with the script.
> 
> By the way, both priv and unpirv lxc execute _**lxc.net.[i].script.down**_.
> 
> Is this a feature or a bug?

lxc_create_network_unpriv() should probably also execute the up script.

Christian
