### ISSUE TITLE
LXC LVM ext4 signature detected on hangs indefinitely

### ISSUE THREAD

**Issue by alexeysofin** [lxc/lxc#2346]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 16.04.4 LTS
 * The output of
   * `lxc-start --version` 3.0.0
   * `lxc-checkconfig`

Kernel configuration found at /boot/config-4.4.0-124-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/blkio
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/memory
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/freezer
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/pids
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/devices

Cgroup v2 mount points: 

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -a`
Linux chupakabra 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
11:devices:/user.slice/user-0.slice/session-c9.scope
10:perf_event:/
9:pids:/user.slice/user-0.slice/session-c9.scope
8:hugetlb:/
7:freezer:/user/root/0
6:net_cls,net_prio:/
5:memory:/user.slice/user-0.slice/session-c9.scope
4:cpuset:/
3:cpu,cpuacct:/user.slice/user-0.slice/session-c9.scope
2:blkio:/user.slice/user-0.slice/session-c9.scope
1:name=systemd:/user.slice/user-0.slice/session-c9.scope

   * `cat /proc/1/mounts`
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=8163360k,nr_inodes=2040840,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=1636820k,mode=755 0 0
/dev/sdb1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs rw,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb,release_agent=/run/cgmanager/agents/cgm-release-agent.hugetlb 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids,release_agent=/run/cgmanager/agents/cgm-release-agent.pids 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event,release_agent=/run/cgmanager/agents/cgm-release-agent.perf_event 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=24,pgrp=1,timeout=0,minproto=5,maxproto=5,direct 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
/dev/sdb2 /windows vfat rw,relatime,gid=46,fmask=0007,dmask=0007,allow_utime=0020,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=1636820k,mode=700,uid=1000,gid=1000 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
/dev/sdb1 /var/lib/docker/aufs ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=1636820k,mode=700 0 0

   * lvcreate --version
  LVM version:     2.02.133(2) (2015-10-30)
  Library version: 1.02.110 (2015-10-30)
  Driver version:  4.34.0

# Issue description

I try to create, destroy and create again an lxc container  with the same name and LVM backend.
First create is successful, destroy goes well too, but second create hangs indefinitely with no output to console.

After stracing the second create attempt (following forks) I see 

`24405 write(2, "WARNING: ext4 signature detected on /dev/lxc/test-new4 at offset 1080. Wipe it? [y/n]: ", 87) = 87
24401 <... read resumed> "WARNING: ext4 signature detected on /dev/lxc/test-new4 at offset 1080. Wipe it? [y/n]: ", 4095) = 87
24405 read(0,  <unfinished ...>
24401 wait4(24405, ^[[A
`
as the last output.

# Steps to reproduce

 1. lxc-create test-new4 -B lvm --fssize=5GB --fstype=ext4 -t download -- --dist ubuntu --release xenial --arch amd64
 2. lxc-destroy test-new4
 3. lxc-create test-new4 -B lvm --fssize=5GB --fstype=ext4 -t download -- --dist ubuntu --release xenial --arch amd64

Maybe it is possible to make an options to LVM backend to wipe fs signatures?

**Comment by brauner** [comment]
This is reported against the wrong repository. You're using the `lxc-*` tools which are part of the shared library at https://github.com/lxc/lxc. :) Please re-open over there. :)

**Comment by brauner** [comment]
Sorry, I mis-read the repo. :) You did it correctly. :)

**Comment by brauner** [comment]
The questions is whether we simply make overriding existing filesystems the default?

**Comment by alexeysofin** [comment]
Actually there are two questions.

1. Why is lvcreate prompt is not propagated to lxc-create?
2. Yes, why not to override existing filesystem by default or maybe make on option for overriding?

The problem is that we are automating lxc-create and lvm, and the only workaround for this issue is to pass  
y to stdint of lxc-create like 
``` echo y | lxc-create test-new4 -B lvm --fssize=5GB --fstype=ext4 -t download -- --dist ubuntu --release xenial --arch amd64 ``` but this seems like the wrong solution, the second option is making lxc and lvm creation separately (because lvcreate has a way to override filesystem `lvcreate -L 5368709120b lxc -n test -y -Wy`)

Maybe you can advise something?

**Comment by brauner** [comment]
> 1. Why is lvcreate prompt not propagated to lxc-create?

That's not the idea behind the tools They shouldn't prompt you for anything so that you can use them properly in scripts. It's also ugly to make that work nicely. It's wrong that they currently hang so a patch would be much appreciated.

**Comment by alexeysofin** [comment]
I will take a look, thank you

**Comment by alexeysofin** [comment]
@brauner Do you want the default behavior to answer yes or no to lvcreate all prompts? And should I add an lxc-create option to change the default behavior?

**Comment by brauner** [comment]
Hm, the default should be `no` I think. I really don't want users to be able to wipe their disks on accident. We should warn them loud and clear. Hm, maybe an option to `lxc-create` would be nice. //cc @hallyn

**Comment by ether42** [comment]
This feature would be quite nice, I encountered it a couple of times when automating LXC deployment via Ansible, so it's a bit cumbersome to answer the prompt (if not impossible without rewriting the LXC module I think).

**Comment by tomponline** [comment]
@ether42 @brauner @alexeysofin I am running into this issue intermittently on CentOS 7, running custom kernel 4.14 (dont think this is relevant though).

lxc-create hangs intermittently, with the lvcreate command showing as blocked.

I think I've found a workaround, by turning off signature detection in /etc/lvm/lvm.conf

```
        use_blkid_wiping = 0
```

I think we could also improve this situation by adding a `-qq` param which will answer "no" to answer questions.

See http://man7.org/linux/man-pages/man8/lvcreate.8.html

```
       -q|--quiet ...
              Suppress output and log messages. Overrides --debug and
              --verbose.  Repeat once to also suppress any prompts with
              answer 'no'.
```

**Comment by ether42** [comment]
@tomponline thanks!

As I understand it, the description of `use_blkid_wiping` seems to tell that it won't use blkid but LVM's code to detect signatures, which may still introduce the problem.
However, the option following it in `lvm.conf`, namely `wipe_signatures_when_zeroing_new_lvs` seems to better fit the bill:
```
# When this setting is disabled, signatures on new LVs are not detected
# or erased unless the --wipesignatures option is used directly.
```

I quickly tried with `use_blkid_wiping = 0` and with a swap on a lv, LVM correctly detects it but with `wipe_signatures_when_zeroing_new_lvs = 0` it seems ok.

**Comment by tomponline** [comment]
even better @ether42! :)

I do think the lxc tools should protect against this kind of locking though, as its mighty confusing and frustrating.

Even on Debian its enabled by default:

```
Wiping each detected signature must be confirmed.
        # When this setting is disabled, signatures on new LVs are not detected
        # or erased unless the --wipesignatures option is used directly.
        wipe_signatures_when_zeroing_new_lvs = 1
```

**Comment by brauner** [comment]
@tompoline, sorry for the late reply. Care to send a patch with the `-qq` added?

**Comment by tomponline** [comment]
@brauner I have now added the `-qq` flags to lvcreate, please can you review? Thanks
