### ISSUE TITLE
Warning about memory.use_hierarchy on every lxc-start

### ISSUE THREAD

**Issue by jgoerzen** [lxc/lxc#236]
I created a new LXC container using lxc-create, running wheezy, and left
all the configs at their default.

```
# lxc-start --name lxctest1
lxc-start: Device or resource busy - failed to set memory.use_hierarchy to 1; continuing
```

My kernel command line:

```
# cat /proc/cmdline 
BOOT_IMAGE=/hephaestus-1/ROOT@/boot/vmlinuz-3.14-1-amd64
root=ZFS=tank/hephaestus-1/ROOT ro boot=zfs zfs-bootfs=tank/21
cgroup_enable=memory,cpu,devices,cpuacct,freezer,blkio swapaccount=1
security=apparmor
```

I observed it is accompanied by this in syslog:

```
May 31 16:17:56 hephaestus kernel: [  457.438103] cgroup: lxc-start
(9053) created nested cgroup for controller "memory" which has
incomplete hierarchy support. Nested cgroups may change behavior in the
future.
May 31 16:17:56 hephaestus kernel: [  457.438107] cgroup: "memory"
requires setting use_hierarchy to 1 on the root.
```

One tidbit:

```
#     echo 1 > /sys/fs/cgroup/memory.use_hierarchy
bash: echo: write error: Device or resource busy
```

LXC 1.0.3 on Debian jessie, kernel 3.14

**Comment by noloader** [comment]
@stgraber, thanks for the information. This issue is still present in kernels 18 months after the bug report was closed. For example, I am experiencing it on Ubuntu Server 15.04.03, running 3.19.0-49-generic.

Earlier it was stated, *"The error is still very real and means that your system created sub-cgroups in the memory controller without first setting use_hierarchy = 1 ..."*. As far as I can tell, there is no ***`use_hierarchy`*** kernel parameter. Confer, [Kernel Parameters](https://www.kernel.org/doc/Documentation/kernel-parameters.txt) at kernel.org.

My question is, what can we do to fix it?

**Comment by hallyn** [comment]
On Wed, Feb 03, 2016 at 01:17:09PM -0800, Jeffrey Walton wrote:
> @stgraber, thanks for the information. This issue is still present in kernels 18 months after the bug report was closed. For example, I am experiencing it on Ubuntu Server 15.04.03, running 3.19.0-49-generic.
> 
> Earlier it was stated, *"The error is still very real and means that your system created sub-cgroups in the memory controller without first setting use_hierarchy = 1 ..."*. As far as I can tell, there is no ***`use_hierarchy`*** kernel parameter. Confer, [Kernel Parameters](https://www.kernel.org/doc/Documentation/kernel-parameters.txt) at kernel.org.

It isn't a kernel parameter:

cat /sys/fs/cgroup/memory/memory.use_hierarchy
1

**Comment by wrathchylde** [comment]
So that's it? Just regurgitation dmesg? No fix?

**Comment by stgraber** [comment]
There's nothing LXC can fix. LXC doesn't own all your cgroups and the only way to fix this after the fact is to kill or move all your existing processes, wipe the cgroup tree clean, set the key to 1 and re-create everything.

If LXC is the first cgroup user, it does do the right thing and set the key for you, if you're using another tool which messes with cgroup and it doesn't set the key to 1 or voluntarily sets it to 0, then that effectively breaks LXC and there's nothing we can do about it.

**Comment by wrathchylde** [comment]
This is passive aggressive. You can at least allude to a fix, or even give suggestions.

I'll just step around it any way in the stack I can. At this point seems like other languages to handle this are a better approach.

**Comment by hallyn** [comment]
@wrathchylde the best thing to do would be to have an early boot script set up the use_hierarchy for you.

Note that if you use cgmanager, it will have done this for you (and with lxc built using cgmanager, lxc won't try to do this itself).
