### ISSUE TITLE
New Debian templates fail to stop

### ISSUE THREAD

**Issue by ppanczyk** [lxc/lxc#2361]
With the latest versions of Debian templates (used by lxc-create -t download), containers fail to stop with lxc-stop. I first noticed this on template from 22.05, the last working one I used was from 24.04. This applies to all released versions of Debian - from 7 to 9.

# Required information

LXC host doesn't matter - I tried on Debian and Ubuntu, LXC 2.0.7, 2.0.8, 2.1.1 and 3.0.0. The problem is with the templates themselves. Debian created with the old template and upgraded to the latest version works fine. Something has changed in template creation. It seems that the configuration of systemd and sysvinit is not prepared for LXC. No default target is set, ttys have default Debian config. Even /etc/inittab is gone on Jessie and Stretch. On Wheezy, there is a default one.

# Steps to reproduce

 1. Remove old templates:
`rm -r /var/cache/lxc/download/debian/stretch/`
 2. Create a new Debian container:
`lxc-create -n debian9 -t download -- -d debian -r stretch -a amd64`
 3. Start the container:
`lxc-start -n debian9`
 4. Stop the container:
`lxc-stop -n debian9`

# Information to attach
The result for Debians 7-9 is the same - timeout and kill of the CT:
```
# lxc-stop -n debian9
lxc-stop: debian9: commands_utils.c: lxc_cmd_sock_rcv_state: 71 failed to receive message: Resource temporarily unavailable
lxc-stop: debian9: commands.c: lxc_cmd_rsp_recv: 157 Command stop response data 1768056164 too long.
```

For Debians with systemd, however, cancelling lxc-stop and running it once again is doing the job:
```
# lxc-stop -n debian9
^C
# lxc-stop -n debian9
#
```
From my research, the conclusion is that on systemd, "systemd-networkd.socket" is the problem. Removing the file /etc/systemd/system/sockets.target.wants/systemd-networkd.socket solves the problem. On the current version of Debian Buster (unstable), systemd-networkd.socket fails to start, so there is no problem with it's stop ;)
With SysV, on Debian Wheezy, inittab handles the powerfail signal (used by lxc-stop) by /etc/init.d/powerfail, which does not exist. On Newer Debians there is no inittab at all. Copying it from the old template also solves the problem.

Why are systemd and sysvinit misconfigured in new templates?

**Comment by brauner** [comment]
Which LXC version is this? This might be related to switching over to distrobuilder.
//cc @stgraber @monstermunchkin

**Comment by ppanczyk** [comment]
As I said, I've reproduced this on 2.0.7, 2.0.8, 2.1.1 and 3.0.0, so it doesn't seem to be related to version, but the template itself.

**Comment by stgraber** [comment]
Those templates are now gone in their own deprecated repository and replaced by distrobuilder which we use to build all our images. We have daily shutdown tests on those so we're pretty confident this isn't an issue if distrobuilder is used.
