### ISSUE TITLE
seccomp support is now too strict

### ISSUE THREAD

**Issue by flx42** [lxc/lxc#2376]
The OCI runtime spec has a [section](https://github.com/opencontainers/runtime-spec/blob/v1.0.1/config-linux.md#seccomp) on seccomp. 

It's not well-defined yet what must happen when a syscall can not be resolved, but I've asked the question: https://github.com/opencontainers/runtime-spec/issues/972

In the meantime, the current seccomp support in LXC is too strict to support OCI configurations in the wild. For instance, here's the list of syscalls used by Docker for their seccomp profile:
https://github.com/moby/moby/blob/master/profiles/seccomp/default.json

1) libseccomp might be too old to know about some syscalls as I mentioned in the issue above. This will be blocked here since dfddc8aa7ef3362212f8394995088a5f525730dd:
https://github.com/lxc/lxc/blob/2095b6d83acbb61bfd3c4a33dd88a6532148a23b/src/lxc/seccomp.c#L500-L504
2) Some syscalls in this list don't make sense for `x86_64`, like `chown32`. This will be blocked here since dfddc8aa7ef3362212f8394995088a5f525730dd:
https://github.com/lxc/lxc/blob/2095b6d83acbb61bfd3c4a33dd88a6532148a23b/src/lxc/seccomp.c#L506-L509
3) Conversely, some syscalls only make sense for `x86_64`, like `epoll_ctl_old`. In this case it fails because the call is `exact`:
https://github.com/lxc/lxc/blob/2095b6d83acbb61bfd3c4a33dd88a6532148a23b/src/lxc/seccomp.c#L530-L531
We resolve the syscall for the native arch, but in libseccomp it will be translated to a pseudo-syscall and it will fail since it's `strict` mode:
https://github.com/seccomp/libseccomp/blob/8ad3638ea9023c3948976dfadebd1554380a31c9/src/arch-x86.c#L331-L334

For 2) and 3),  the issue is that the OCI spec the arch is not per syscall. But libseccomp seems to allow that with the non `add_exact` calls and "pseudo-syscalls".

Should we...
* Revert dfddc8aa7ef3362212f8394995088a5f525730dd?
* Switch to non `exact` calls?
* Revert dfddc8aa7ef3362212f8394995088a5f525730dd and switch to non `exact` calls under some conditions? For instance failing to whitelist a syscall is probably more acceptable than failing to blacklist. Or maybe behind a configuration flag?

cc @brauner @hallyn

**Comment by brauner** [comment]
We can revert dfddc8a for now.
