### ISSUE TITLE
nodejs / npm doesn't work with lxc-attach in sudo/root

### ISSUE THREAD

**Issue by shadowofsoul** [lxc/lxc#2398]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Debian / Ubuntu on Jessie, Xenial, Artful X64
 * Distribution version: 20180612_07:58

# Issue description

NodeJS nor NPM work with lxc-attach with root / sudo. 

A brief description of what failed or what could be improved.

Make a warning, somewhere, anywhere (or leave this issue for that reason). i never through this could be the reason why only legacy (0.10.2) deb version of node worked on the container. nodesource version, compiled manually, pre-compiled binaries, nothing worked out. and like not even sudo worked, i through was some kind of weird permission issues, until i found [this issue](https://github.com/npm/npm/issues/15681)

# Steps to reproduce

 1. Create the container
 2. Install nodejs in any form (pre-compiled, nodesource, nvm, all is the same)
 3. Try to execute nodejs / npm with root or sudo with lxc-attach and then with lxc-console

**Comment by stgraber** [comment]
What version of LXC, kernel, what distro and what error are you actually getting?

**Comment by shadowofsoul** [comment]
@stgraber This has 2 years. I moved all into LXD that works perfectly for my setup (including network set up that i had problem with in the past too). leave  ut for someone that maybe has this problem for some reason? can't help testing this anymore.
