### ISSUE TITLE
support variables in config files

### ISSUE THREAD

**Issue by ghost** [lxc/lxc#240]
it would be nice if lxc would support using variables in config files, e.g.:

lxc.utsname = example.org
lxc.mount.entry = /srv/lxc/data/$lxc_utsname /var/lib/lxc/$lxc_utsname/rootfs/srv/$lxc_utsname none defaults,bind 0 0

**Comment by brauner** [comment]
There are no immediate plans to support this but we'd consider merging a pr to introduce this.
