### ISSUE TITLE
Failed to start container when multiple lxc.id_map configured

### ISSUE THREAD

**Issue by mrsshr** [lxc/lxc#2410]
* Distribution: Debian GNU/Linux
 * Distribution version: 9.4 (Stretch)

lxc-start --version

2.0.7

lxc-checkconfig

Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.9.0-6-amd64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: enabled
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

uname -a

Linux container 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

cat /proc/self/cgroup

10:blkio:/user.slice/user-0.slice/session-1.scope
9:devices:/user.slice/user-0.slice/session-1.scope
8:perf_event:/
7:freezer:/user/root/0
6:net_cls,net_prio:/
5:pids:/user.slice/user-0.slice/session-1.scope
4:cpuset:/
3:cpu,cpuacct:/user.slice/user-0.slice/session-1.scope
2:memory:/user.slice/user-0.slice/session-1.scope
1:name=systemd:/user.slice/user-0.slice/session-1.scope

cat /proc/1/mounts

sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=8184368k,nr_inodes=2046092,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=1639104k,mode=755 0 0
/dev/sdf1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=31,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=450 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
/dev/sdb1 /media/HDD2 ext4 rw,relatime,data=ordered 0 0
/dev/sde1 /media/HDD4 ext4 rw,relatime,data=ordered 0 0
/dev/sdc1 /media/HDD3 ext4 rw,relatime,data=ordered 0 0
/dev/sda1 /media/HDD1 ext4 rw,relatime,data=ordered 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=1639100k,mode=700 0 0

# Steps to reproduce

 1. install debian 9 host and `apt install lxc`
 2. `usermod --add-subuids 100000-165536 root`
 3. `usermod --add-subgids 100000-165536 root`
 4. `usermod --add-subuids 33-33 root`
 5. `usermod --add-subgids 33-33 root`
 6. reboot
 7. edit global config
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
 8. `lxc-create -n samba -t download`, select debian, stretch, amd64
 9. edit container config
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
lxc.id_map = u 33 33 1
lxc.id_map = g 33 33 1
 10. `lxc-start -n samba -F`

# Information to attach

cat /var/lib/lxc/samba/config

lxc.include = /usr/share/lxc/config/debian.common.conf
lxc.include = /usr/share/lxc/config/debian.userns.conf
lxc.arch = linux64
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
lxc.id_map = u 33 33 1
lxc.id_map = g 33 33 1
lxc.rootfs = /var/lib/lxc/samba/rootfs
lxc.rootfs.backend = dir
lxc.utsname = samba
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:cc:f8:20

cat /etc/subuid
root:100000:65536
root:33:1

cat /etc/subgid
root:100000:65536
root:33:1

cat /etc/passwd | grep www-data
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin

cat /etc/group | grep www-data
www-data:x:33:

ls -l /usr/bin/new?idmap
-rwsr-xr-x 1 root root 37136 May 17  2017 /usr/bin/newgidmap
-rwsr-xr-x 1 root root 37136 May 17  2017 /usr/bin/newuidmap

strace -f -o lxc-start.log lxc-start -n samba
[lxc-start.log](https://github.com/lxc/lxc/files/2107137/lxc-start.log)
> 1323  openat(3, "uid_map", O_WRONLY)    = 5
> 1323  write(5, "0 100000 65536\n33 33 1\n", 23) = -1 EINVAL (Invalid argument)
> 1323  write(2, "newuidmap: write to uid_map fail"..., 53) = 53

newuidmap: write to uid_map failed: Invalid argument
                                                    lxc-start: start.c: lxc_spawn: 1171 Failed to set up id mapping.
                                                                                                                    lxc-start: start.c: __lxc_start: 1346 Failed to spawn container "samba".
                                                                    newuidmap: write to uid_map failed: Invalid argument
lxc-start: conf.c: userns_exec_1: 4453 Error setting up child mappings
lxc-start: cgroups/cgfsng.c: recursive_destroy: 1270 Error destroying /sys/fs/cgroup/systemd//lxc/samba
newuidmap: write to uid_map failed: Invalid argument
lxc-start: conf.c: userns_exec_1: 4453 Error setting up child mappings
lxc-start: cgroups/cgfsng.c: recursive_destroy: 1270 Error destroying /sys/fs/cgroup/memory//lxc/samba
newuidmap: write to uid_map failed: Invalid argument
lxc-start: conf.c: userns_exec_1: 4453 Error setting up child mappings
lxc-start: cgroups/cgfsng.c: recursive_destroy: 1270 Error destroying /sys/fs/cgroup/cpu//lxc/samba
newuidmap: write to uid_map failed: Invalid argument
lxc-start: conf.c: userns_exec_1: 4453 Error setting up child mappings
lxc-start: cgroups/cgfsng.c: recursive_destroy: 1270 Error destroying /sys/fs/cgroup/cpuset//lxc/samba
newuidmap: write to uid_map failed: Invalid argument
lxc-start: conf.c: userns_exec_1: 4453 Error setting up child mappings
lxc-start: cgroups/cgfsng.c: recursive_destroy: 1270 Error destroying /sys/fs/cgroup/pids//lxc/samba
newuidmap: write to uid_map failed: Invalid argument
lxc-start: conf.c: userns_exec_1: 4453 Error setting up child mappings
lxc-start: cgroups/cgfsng.c: recursive_destroy: 1270 Error destroying /sys/fs/cgroup/net_cls//lxc/samba
newuidmap: write to uid_map failed: Invalid argument
lxc-start: conf.c: userns_exec_1: 4453 Error setting up child mappings
lxc-start: cgroups/cgfsng.c: recursive_destroy: 1270 Error destroying /sys/fs/cgroup/freezer//lxc/samba
newuidmap: write to uid_map failed: Invalid argument
lxc-start: conf.c: userns_exec_1: 4453 Error setting up child mappings
lxc-start: cgroups/cgfsng.c: recursive_destroy: 1270 Error destroying /sys/fs/cgroup/perf_event//lxc/samba
newuidmap: write to uid_map failed: Invalid argument
lxc-start: conf.c: userns_exec_1: 4453 Error setting up child mappings
lxc-start: cgroups/cgfsng.c: recursive_destroy: 1270 Error destroying /sys/fs/cgroup/devices//lxc/samba
newuidmap: write to uid_map failed: Invalid argument
lxc-start: conf.c: userns_exec_1: 4453 Error setting up child mappings
lxc-start: cgroups/cgfsng.c: recursive_destroy: 1270 Error destroying /sys/fs/cgroup/blkio//lxc/samba
lxc-start: tools/lxc_start.c: main: 366 The container failed to start.
lxc-start: tools/lxc_start.c: main: 370 Additional information can be obtained by setting the --logfile and --logpriority options.

      lxc-start 20180615184747.368 INFO     lxc_start_ui - tools/lxc_start.c:main:275 - using rcfile /var/lib/lxc/samba/config
      lxc-start 20180615184747.368 WARN     lxc_confile - confile.c:config_pivotdir:1910 - lxc.pivotdir is ignored.  It will soon become an error.
      lxc-start 20180615184747.369 INFO     lxc_confile - confile.c:config_idmap:1531 - read uid map: type u nsid 0 hostid 100000 range 65536
      lxc-start 20180615184747.369 INFO     lxc_confile - confile.c:config_idmap:1531 - read uid map: type g nsid 0 hostid 100000 range 65536
      lxc-start 20180615184747.369 INFO     lxc_confile - confile.c:config_idmap:1531 - read uid map: type u nsid 33 hostid 33 range 1
      lxc-start 20180615184747.369 INFO     lxc_confile - confile.c:config_idmap:1531 - read uid map: type g nsid 33 hostid 33 range 1
      lxc-start 20180615184747.369 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver nop
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:402 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:567 - Adding native rule for reject_force_umount action 0.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:251 - Setting Seccomp rule to reject force umounts.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:570 - Adding compat rule for reject_force_umount action 0.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:251 - Setting Seccomp rule to reject force umounts.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:402 - processing: .[all].
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:402 - processing: .kexec_load errno 1.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:567 - Adding native rule for kexec_load action 327681.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:570 - Adding compat rule for kexec_load action 327681.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:402 - processing: .open_by_handle_at errno 1.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:567 - Adding native rule for open_by_handle_at action 327681.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:570 - Adding compat rule for open_by_handle_at action 327681.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:402 - processing: .init_module errno 1.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:567 - Adding native rule for init_module action 327681.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:570 - Adding compat rule for init_module action 327681.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:402 - processing: .finit_module errno 1.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:567 - Adding native rule for finit_module action 327681.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:570 - Adding compat rule for finit_module action 327681.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:402 - processing: .delete_module errno 1.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:567 - Adding native rule for delete_module action 327681.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:570 - Adding compat rule for delete_module action 327681.
      lxc-start 20180615184747.369 INFO     lxc_seccomp - seccomp.c:parse_config_v2:580 - Merging in the compat Seccomp ctx into the main one.
      lxc-start 20180615184747.369 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20180615184747.369 DEBUG    lxc_start - start.c:setup_signal_fd:273 - Set SIGCHLD handler with file descriptor: 5.
      lxc-start 20180615184747.370 DEBUG    console - console.c:lxc_console_peer_default:430 - opening /dev/tty for console peer
      lxc-start 20180615184747.370 DEBUG    console - console.c:lxc_console_peer_default:436 - using '/dev/tty' as console
      lxc-start 20180615184747.370 DEBUG    console - console.c:lxc_console_sigwinch_init:144 - 1389 got SIGWINCH fd 9
      lxc-start 20180615184747.370 DEBUG    console - console.c:lxc_console_winsz:71 - set winsz dstfd:6 cols:120 rows:36
      lxc-start 20180615184747.370 INFO     lxc_start - start.c:lxc_init:475 - Container "samba" is initialized.
      lxc-start 20180615184747.370 DEBUG    lxc_start - start.c:__lxc_start:1317 - Not dropping CAP_SYS_BOOT or watching utmp.
      lxc-start 20180615184747.372 INFO     lxc_conf - conf.c:instantiate_veth:2647 - Retrieved mtu 1500 from lxcbr0
      lxc-start 20180615184747.372 INFO     lxc_conf - conf.c:instantiate_veth:2672 - Attached 'vethXG3UQV': to the bridge 'lxcbr0': 
      lxc-start 20180615184747.372 DEBUG    lxc_conf - conf.c:instantiate_veth:2689 - instantiated veth 'vethXG3UQV/veth3AWYPH', index is '8'
      lxc-start 20180615184747.372 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for samba
      lxc-start 20180615184747.372 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1306 - Path "/sys/fs/cgroup/systemd//lxc/samba" already existed.
      lxc-start 20180615184747.372 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1363 - No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/samba: No such file or directory
      lxc-start 20180615184747.373 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:filter_and_set_cpus:474 - No isolated cpus detected.
      lxc-start 20180615184747.373 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:handle_cpuset_hierarchy:644 - "cgroup.clone_children" was already set to "1".
      lxc-start 20180615184747.374 INFO     lxc_start - start.c:lxc_spawn:1154 - Cloned CLONE_NEWUSER.
      lxc-start 20180615184747.374 INFO     lxc_start - start.c:lxc_spawn:1154 - Cloned CLONE_NEWNS.
      lxc-start 20180615184747.374 INFO     lxc_start - start.c:lxc_spawn:1154 - Cloned CLONE_NEWPID.
      lxc-start 20180615184747.374 INFO     lxc_start - start.c:lxc_spawn:1154 - Cloned CLONE_NEWUTS.
      lxc-start 20180615184747.374 INFO     lxc_start - start.c:lxc_spawn:1154 - Cloned CLONE_NEWIPC.
      lxc-start 20180615184747.378 ERROR    lxc_start - start.c:lxc_spawn:1171 - Failed to set up id mapping.
      lxc-start 20180615184747.440 INFO     lxc_conf - conf.c:lxc_delete_network:3015 - Removed interface "(null)" with index 8.
      lxc-start 20180615184747.442 WARN     lxc_conf - conf.c:lxc_delete_network:3038 - Failed to remove "vethXG3UQV" from host: Invalid argument.
      lxc-start 20180615184747.442 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20180615184747.442 ERROR    lxc_start - start.c:__lxc_start:1346 - Failed to spawn container "samba".
      lxc-start 20180615184747.442 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20180615184747.476 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20180615184747.476 INFO     lxc_conf - conf.c:run_script_argv:424 - Executing script "/usr/share/lxcfs/lxc.reboot.hook" for container "samba", config section "lxc".
      lxc-start 20180615184747.982 ERROR    lxc_conf - conf.c:userns_exec_1:4453 - Error setting up child mappings
      lxc-start 20180615184747.982 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/systemd//lxc/samba-1
      lxc-start 20180615184747.985 ERROR    lxc_conf - conf.c:userns_exec_1:4453 - Error setting up child mappings
      lxc-start 20180615184747.985 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/memory//lxc/samba-1
      lxc-start 20180615184747.988 ERROR    lxc_conf - conf.c:userns_exec_1:4453 - Error setting up child mappings
      lxc-start 20180615184747.988 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/cpu//lxc/samba-1
      lxc-start 20180615184747.991 ERROR    lxc_conf - conf.c:userns_exec_1:4453 - Error setting up child mappings
      lxc-start 20180615184747.991 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/cpuset//lxc/samba-1
      lxc-start 20180615184747.994 ERROR    lxc_conf - conf.c:userns_exec_1:4453 - Error setting up child mappings
      lxc-start 20180615184747.994 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/pids//lxc/samba-1
      lxc-start 20180615184747.997 ERROR    lxc_conf - conf.c:userns_exec_1:4453 - Error setting up child mappings
      lxc-start 20180615184747.997 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/net_cls//lxc/samba-1
      lxc-start 20180615184747.999 ERROR    lxc_conf - conf.c:userns_exec_1:4453 - Error setting up child mappings
      lxc-start 20180615184747.999 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/freezer//lxc/samba-1
      lxc-start 20180615184748.248 ERROR    lxc_conf - conf.c:userns_exec_1:4453 - Error setting up child mappings
      lxc-start 20180615184748.253 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/perf_event//lxc/samba-1
      lxc-start 20180615184748.504 ERROR    lxc_conf - conf.c:userns_exec_1:4453 - Error setting up child mappings
      lxc-start 20180615184748.509 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/devices//lxc/samba-1
      lxc-start 20180615184748.750 ERROR    lxc_conf - conf.c:userns_exec_1:4453 - Error setting up child mappings
      lxc-start 20180615184748.755 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/blkio//lxc/samba-1
      lxc-start 20180615184748.761 ERROR    lxc_start_ui - tools/lxc_start.c:main:366 - The container failed to start.
      lxc-start 20180615184748.764 ERROR    lxc_start_ui - tools/lxc_start.c:main:370 - Additional information can be obtained by setting the --logfile and --logpriority options.

**Comment by therealbstern** [comment]
The below discussion is to help others searching for how to fix this.  **TL;DR**: Don't set `lxc.id_map` and `lxc.id_map` to overlapping or repeated values.  They might also get set in an configuration brought in with `lxc.include`.

-----

For reference, this is still the case as lxc-2.0.11.  As indicated, the fix is to remove the duplicate listings for `lxc.id_map` and `lxc.id_map`.  More precisely, the problem is specifying duplicate, or even just overlapping, mappings in a configuration.  The typical mappings:

```
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
```

are usually fine, but if you specify the same mapping more than once, the second declaration overlaps the first entirely (and any overlap is a configuration error).

This happened to me by including `~/.config/lxc/default.conf` in the configuration for a container (`~/.local/share/lxc/$CONTAINER_NAME`).  At some point, I added the UID and GID maps to my `default.conf`, but the configuration created by `lxc-create` sets them to the same values, so they ended up being given to LXC twice.

A symptom of this that finally got me on the right track (which I include here to help others find it later), from `~/.local/share/lxc/$CONTAINER_NAME/$CONTAINER_NAME.log`, follows.  (I've replaced the timestamp with `(time)`, the PID of `lxc-start` with `(pid)`, and line-broken it for readability.)

      lxc-start (time) ERROR    lxc_conf - conf.c:lxc_map_ids:2796 - newuidmap failed to write
         mapping "newuidmap: write to uid_map failed: Invalid argument":
         newuidmap (pid) 0 100000 65536 0 100000 65536

Note the repeated `0 100000 65536 0 100000 65536`.

When running with `--loglevel` set to TRACE, the working configuration had `0 100000 65536` appear only once on that line.

    lxc-start (time) TRACE    lxc_conf - conf.c:lxc_map_ids:2800 - newuidmap wrote mapping "newuidmap (pid) 0 100000 65536"

(Out of completeness, a working configuration TRACE log has another call to `newuidmap` in it, but the UID and range numbers are different because it's doing something else, and it also keeps working.)

This isn't a bug in LXC.  The very reason one can specify them multiple times is shown in https://discuss.linuxcontainers.org/t/newuidmap-failed-to-write-mapping-newuidmap-uid-range-33-33-1000-1000-not-allowed/5209/4, where that OP was doing some novel UID/GID mapping and needed to be able to set multiple values for the maps.  This is also why `newuidmap` takes multiple sets of maps.

It would be nice if LXC detected overlapping maps, but I think the majority of users aren't doing anything complex and can solve this by just removing all but one set of UID/GID maps from configuration files.
