### ISSUE TITLE
Apparmor denies for systemd timer

### ISSUE THREAD

**Issue by jkroepke** [lxc/lxc#2412]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of
   * `lxc-start --version` N/A (lxd reports 3.0.0)
   * `lxc-checkconfig` N/A
   * `uname -a` 
      Linux hades 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
      
      ```
      12:cpuset:/
      11:freezer:/
      10:perf_event:/
      9:pids:/user.slice/user-1000.slice/session-1.scope
      8:memory:/user.slice
      7:devices:/user.slice
      6:blkio:/user.slice
      5:hugetlb:/
      4:net_cls,net_prio:/
      3:rdma:/
      2:cpu,cpuacct:/user.slice
      1:name=systemd:/user.slice/user-1000.slice/session-1.scope
      0::/user.slice/user-1000.slice/session-1.scope
      ```

# Issue description
For most of the systemd timers on my container I get this message on my host

`[308983.961230] audit: type=1400 audit(1529230145.049:2362): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxd-mclauncher_</var/lib/lxd>" name="/bin/" pid=26991 comm="(ionclean)" flags="ro, remount, bind"`

In the case it's phpsessionclean.timer. But it looks like the timer runs successfully.

# Steps to reproduce

 1. Run a container
 2. Install php7.2
 3. Wait / tail on dmesg

**Comment by jkroepke** [comment]
It may related to systemd's unit options:

```
ProtectHome=true
ProtectSystem=true
PrivateTmp=true
```

**Comment by brauner** [comment]
Likely. It seems that you're using LXD so this issue should be opened over there. :)

**Comment by jkroepke** [comment]
Yes!

But lxd use the apparmor profiles from lxc. lxd has no own aa profiles....

**Comment by brauner** [comment]
In fact it has.
