### ISSUE TITLE
lxc-stop --interactive

### ISSUE THREAD

**Issue by ghost** [lxc/lxc#242]
like rm -i/cp -i etc., it would be nice if lxc-stop would have a -i/--interactive flag:

daniel@debian:~$ lxc-stop -n example -i
Active Users:
foo   pts/0        2014-06-11 09:32 (:0)
bar   pts/1        2014-06-11 09:32 (:0)
baz   pts/2        2014-06-12 09:51 (:0)
[...]
Do you really want to stop the container 'example' (y/N)?
daniel@debian:~$

**Comment by brauner** [comment]
Closing due to age and out of range for low-level `LXC`. The tools should be as simple as possible.
