### ISSUE TITLE
Ubuntu trusty container hangs during boot under LXC 3.0.1

### ISSUE THREAD

**Issue by living180** [lxc/lxc#2421]
# Required information

 * Distribution: Gentoo
 * Distribution version: `default/linux/amd64/17.0/systemd`
 * The output of
   * `lxc-start --version`

          3.0.1

   * `lxc-checkconfig`

          --- Namespaces ---
          Namespaces: enabled
          Utsname namespace: enabled
          Ipc namespace: enabled
          Pid namespace: enabled
          User namespace: enabled
          Network namespace: enabled

          --- Control groups ---
          Cgroups: enabled

          Cgroup v1 mount points: 
          /sys/fs/cgroup/systemd
          /sys/fs/cgroup/cpuset
          /sys/fs/cgroup/cpu,cpuacct
          /sys/fs/cgroup/memory
          /sys/fs/cgroup/net_cls,net_prio
          /sys/fs/cgroup/freezer
          /sys/fs/cgroup/devices

          Cgroup v2 mount points: 
          /sys/fs/cgroup/unified

          Cgroup v1 clone_children flag: enabled
          Cgroup device: enabled
          Cgroup sched: enabled
          Cgroup cpu account: enabled
          Cgroup memory controller: enabled
          Cgroup cpuset: enabled

          --- Misc ---
          Veth pair device: enabled, loaded
          Macvlan: enabled, not loaded
          Vlan: enabled, not loaded
          Bridges: enabled, loaded
          Advanced netfilter: enabled, not loaded
          CONFIG_NF_NAT_IPV4: enabled, loaded
          CONFIG_NF_NAT_IPV6: enabled, not loaded
          CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
          CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
          CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
          CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
          FUSE (for use with lxcfs): enabled, loaded

          --- Checkpoint/Restore ---
          checkpoint restore: enabled
          CONFIG_FHANDLE: enabled
          CONFIG_EVENTFD: enabled
          CONFIG_EPOLL: enabled
          CONFIG_UNIX_DIAG: enabled
          CONFIG_INET_DIAG: enabled
          CONFIG_PACKET_DIAG: enabled
          CONFIG_NETLINK_DIAG: enabled
          File capabilities: 

          Note : Before booting a new kernel, you can check its configuration
          usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -a`

          Linux gentoo 4.17.2-gentoo-2018.06.18-15.48.54 #2 SMP Mon Jun 18 16:01:00 EEST 2018 x86_64 Intel(R) Xeon(R) CPU E3-1220 v5 @ 3.00GHz GenuineIntel GNU/Linux

   * `cat /proc/self/cgroup`

          7:devices:/user.slice
          6:freezer:/
          5:net_cls,net_prio:/
          4:memory:/user.slice/user-1000.slice/session-c1.scope
          3:cpu,cpuacct:/user.slice
          2:cpuset:/
          1:name=systemd:/user.slice/user-1000.slice/session-c1.scope
          0::/user.slice/user-1000.slice/session-c1.scope

   * `cat /proc/1/mounts`

          sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
          proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
          devtmpfs /dev devtmpfs rw,nosuid,size=16405792k,nr_inodes=4101448,mode=755 0 0
          tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
          devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
          tmpfs /run tmpfs rw,nosuid,nodev,mode=755 0 0
          tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
          cgroup2 /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
          cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
          pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
          efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
          bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
          cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
          cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
          cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
          cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
          cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
          cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
          /dev/disk/by-uuid/c04c9b6b-2458-491e-801c-61deafb9c218 / ext4 rw,lazytime,data=ordered 0 0
          systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=4454 0 0
          debugfs /sys/kernel/debug debugfs rw,relatime 0 0
          mqueue /dev/mqueue mqueue rw,relatime 0 0
          tmpfs /tmp tmpfs rw,nosuid,nodev 0 0
          /dev/mapper/vg-ubuntu--root /var/lib/lxc/ubuntu/rootfs ext4 rw,lazytime 0 0
          tmpfs /var/lib/lxc/ubuntu/rootfs/tmp tmpfs rw,nosuid,nodev,relatime 0 0
          /dev/mapper/vg-ubuntu--mysql /var/lib/lxc/ubuntu/rootfs/var/lib/mysql ext4 rw,lazytime,nodev 0 0
          lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
          fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
          tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=3282796k,mode=700,uid=1000,gid=1000 0 0

# Issue description

My Ubuntu trusty container (generated via the download template) hangs during boot after upgrading to LXC 3.0.1.  Downgrading to LXC  3.0.0 makes everything work again.  This is the console output under LXC 3.0.1:

     $ sudo lxc-start -F ubuntu
    Password: 
    init: Unable to create device: /dev/kmsg
     * Starting Mount filesystems on boot   ...done.
     * Stopping Send an event to indicate plymouth is up   ...done.
     * Starting Signal sysvinit that the rootfs is mounted   ...done.
     * Starting Populate /dev filesystem   ...done.
     * Starting Clean /tmp directory   ...done.
     * Stopping Read required files in advance (for other mountpoints)   ...done.
     * Stopping Clean /tmp directory   ...done.
     * Starting Populate and link to /run filesystem   ...done.
     * Starting Track if upstart is running in a container   ...done.
     * Stopping Populate and link to /run filesystem   ...done.
     * Starting load fallback graphics devices   ...done.
     * Starting workaround for missing events in container   ...done.
     * Stopping load fallback graphics devices   ...done.
     * Stopping workaround for missing events in container   ...done.
     * Starting userspace bootsplash   ...done.
     * Starting Send an event to indicate plymouth is up   ...done.
     * Starting configure network device security   ...done.
     * Stopping Send an event to indicate plymouth is up   ...done.
     * Stopping userspace bootsplash   ...done.
     * Starting Mount network filesystems   ...done.
     * Stopping Mount network filesystems   ...done.
     * Starting Bridge socket events into upstart   ...done.
     * Starting configure network device   ...done.
     * Stopping Populate /dev filesystem   ...done.

The container boot process then hangs at that point until I run `sudo lxc-stop ubuntu` from another shell, after which it shuts down cleanly.

I bisected the problem to commit 4b18ebc2fc53f7097354c9a010b6fb345da1326d.

I also found that if I added the lines

    lxc.mount.entry = /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc none bind,optional 0 0
    lxc.mount.entry = /sys/firmware/efi/efivars sys/firmware/efi/efivars none bind,optional 0 0

to the container's config file, it was able to boot successfully.

# Information to attach

 - Container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`):

       lxc-start ubuntu 20180620115612.389 INFO     lxc_confile - confile.c:set_config_idmaps:1666 - Read uid map: type u nsid 0 hostid 100000 range 1000
       lxc-start ubuntu 20180620115612.389 INFO     lxc_confile - confile.c:set_config_idmaps:1666 - Read uid map: type g nsid 0 hostid 100000 range 1000
       lxc-start ubuntu 20180620115612.389 INFO     lxc_confile - confile.c:set_config_idmaps:1666 - Read uid map: type u nsid 1000 hostid 1000 range 1
       lxc-start ubuntu 20180620115612.389 INFO     lxc_confile - confile.c:set_config_idmaps:1666 - Read uid map: type g nsid 1000 hostid 1000 range 1
       lxc-start ubuntu 20180620115612.389 INFO     lxc_confile - confile.c:set_config_idmaps:1666 - Read uid map: type u nsid 1001 hostid 101001 range 64535
       lxc-start ubuntu 20180620115612.389 INFO     lxc_confile - confile.c:set_config_idmaps:1666 - Read uid map: type g nsid 1001 hostid 101001 range 64535
       lxc-start ubuntu 20180620115612.389 INFO     lxc_lsm - lsm/lsm.c:lsm_init:46 - LSM security driver nop
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:745 - Processing "reject_force_umount  # comment this to allow umount -f;  not recommended"
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:496 - Set seccomp rule to reject force umounts
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:922 - Added native rule for arch 0 for reject_force_umount action 0(kill)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:496 - Set seccomp rule to reject force umounts
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:931 - Added compat rule for arch 1073741827 for reject_force_umount action 0(kill)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:496 - Set seccomp rule to reject force umounts
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:941 - Added compat rule for arch 1073741886 for reject_force_umount action 0(kill)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:496 - Set seccomp rule to reject force umounts
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:951 - Added native rule for arch -1073741762 for reject_force_umount action 0(kill)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:745 - Processing "[all]"
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:745 - Processing "kexec_load errno 1"
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:922 - Added native rule for arch 0 for kexec_load action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:931 - Added compat rule for arch 1073741827 for kexec_load action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:941 - Added compat rule for arch 1073741886 for kexec_load action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:951 - Added native rule for arch -1073741762 for kexec_load action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:745 - Processing "open_by_handle_at errno 1"
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:922 - Added native rule for arch 0 for open_by_handle_at action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:931 - Added compat rule for arch 1073741827 for open_by_handle_at action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:941 - Added compat rule for arch 1073741886 for open_by_handle_at action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:951 - Added native rule for arch -1073741762 for open_by_handle_at action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:745 - Processing "init_module errno 1"
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:922 - Added native rule for arch 0 for init_module action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:931 - Added compat rule for arch 1073741827 for init_module action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:941 - Added compat rule for arch 1073741886 for init_module action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:951 - Added native rule for arch -1073741762 for init_module action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:745 - Processing "finit_module errno 1"
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:922 - Added native rule for arch 0 for finit_module action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:931 - Added compat rule for arch 1073741827 for finit_module action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:941 - Added compat rule for arch 1073741886 for finit_module action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:951 - Added native rule for arch -1073741762 for finit_module action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:745 - Processing "delete_module errno 1"
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:922 - Added native rule for arch 0 for delete_module action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:931 - Added compat rule for arch 1073741827 for delete_module action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:941 - Added compat rule for arch 1073741886 for delete_module action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:951 - Added native rule for arch -1073741762 for delete_module action 327681(errno)
       lxc-start ubuntu 20180620115612.389 INFO     lxc_seccomp - seccomp.c:parse_config_v2:955 - Merging compat seccomp contexts into main context
       lxc-start ubuntu 20180620115612.390 DEBUG    terminal - terminal.c:lxc_terminal_peer_default:692 - Using terminal "/dev/tty" as proxy
       lxc-start ubuntu 20180620115612.390 DEBUG    terminal - terminal.c:lxc_terminal_signal_init:189 - Created signal fd 9
       lxc-start ubuntu 20180620115612.390 DEBUG    terminal - terminal.c:lxc_terminal_winsz:86 - Set window size to 80 columns and 53 rows
       lxc-start ubuntu 20180620115612.390 INFO     lxc_start - start.c:lxc_init:858 - Container "ubuntu" is initialized
       lxc-start ubuntu 20180620115612.390 DEBUG    storage - storage/storage.c:get_storage_by_name:225 - Detected rootfs type "dir"
       lxc-start ubuntu 20180620115612.392 INFO     lxc_network - network.c:instantiate_veth:175 - Retrieved mtu 1500 from lxcbr0
       lxc-start ubuntu 20180620115612.392 INFO     lxc_network - network.c:instantiate_veth:201 - Attached "vethLQBDJA" to bridge "lxcbr0"
       lxc-start ubuntu 20180620115612.392 DEBUG    lxc_network - network.c:instantiate_veth:226 - Instantiated veth "vethLQBDJA/vethHQQ44T", index is "42"
       lxc-start ubuntu 20180620115612.392 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cg_legacy_handle_cpuset_hierarchy:606 - "cgroup.clone_children" was already set to "1"
       lxc-start ubuntu 20180620115612.393 INFO     lxc_start - start.c:lxc_spawn:1641 - Cloned CLONE_NEWUSER
       lxc-start ubuntu 20180620115612.393 INFO     lxc_start - start.c:lxc_spawn:1641 - Cloned CLONE_NEWNS
       lxc-start ubuntu 20180620115612.393 INFO     lxc_start - start.c:lxc_spawn:1641 - Cloned CLONE_NEWPID
       lxc-start ubuntu 20180620115612.393 INFO     lxc_start - start.c:lxc_spawn:1641 - Cloned CLONE_NEWUTS
       lxc-start ubuntu 20180620115612.393 INFO     lxc_start - start.c:lxc_spawn:1641 - Cloned CLONE_NEWIPC
       lxc-start ubuntu 20180620115612.393 DEBUG    lxc_start - start.c:lxc_try_preserve_namespaces:204 - Preserved user namespace via fd 14
       lxc-start ubuntu 20180620115612.393 DEBUG    lxc_start - start.c:lxc_try_preserve_namespaces:204 - Preserved mnt namespace via fd 15
       lxc-start ubuntu 20180620115612.393 DEBUG    lxc_start - start.c:lxc_try_preserve_namespaces:204 - Preserved pid namespace via fd 16
       lxc-start ubuntu 20180620115612.393 DEBUG    lxc_start - start.c:lxc_try_preserve_namespaces:204 - Preserved uts namespace via fd 17
       lxc-start ubuntu 20180620115612.393 DEBUG    lxc_start - start.c:lxc_try_preserve_namespaces:204 - Preserved ipc namespace via fd 18
       lxc-start ubuntu 20180620115612.393 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:2778 - The binary "/usr/bin/newuidmap" does have the setuid bit set
       lxc-start ubuntu 20180620115612.393 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:2778 - The binary "/usr/bin/newgidmap" does have the setuid bit set
       lxc-start ubuntu 20180620115612.393 DEBUG    lxc_conf - conf.c:lxc_map_ids:2866 - Functional newuidmap and newgidmap binary found
       lxc-start ubuntu 20180620115612.397 INFO     lxc_start - start.c:do_start:1091 - Unshared CLONE_NEWNET
       lxc-start ubuntu 20180620115612.398 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:2778 - The binary "/usr/bin/newuidmap" does have the setuid bit set
       lxc-start ubuntu 20180620115612.398 DEBUG    lxc_conf - conf.c:idmaptool_on_path_and_privileged:2778 - The binary "/usr/bin/newgidmap" does have the setuid bit set
       lxc-start ubuntu 20180620115612.398 DEBUG    lxc_conf - conf.c:lxc_map_ids:2866 - Functional newuidmap and newgidmap binary found
       lxc-start ubuntu 20180620115612.401 DEBUG    lxc_start - start.c:lxc_spawn:1695 - Preserved net namespace via fd 10
       lxc-start ubuntu 20180620115612.427 DEBUG    lxc_network - network.c:lxc_network_move_created_netdev_priv:2495 - Moved network device "vethHQQ44T"/"eth0" to network namespace of 4225
       lxc-start ubuntu 20180620115612.427 NOTICE   lxc_utils - utils.c:lxc_switch_uid_gid:2059 - Switched to gid 0.
       lxc-start ubuntu 20180620115612.427 NOTICE   lxc_utils - utils.c:lxc_switch_uid_gid:2065 - Switched to uid 0.
       lxc-start ubuntu 20180620115612.427 NOTICE   lxc_utils - utils.c:lxc_setgroups:2077 - Dropped additional groups.
       lxc-start ubuntu 20180620115612.427 INFO     lxc_start - start.c:do_start:1198 - Unshared CLONE_NEWCGROUP
       lxc-start ubuntu 20180620115612.427 DEBUG    storage - storage/storage.c:get_storage_by_name:225 - Detected rootfs type "dir"
       lxc-start ubuntu 20180620115612.427 DEBUG    lxc_conf - conf.c:lxc_setup_rootfs:1369 - Mounted rootfs "/var/lib/lxc/ubuntu/rootfs" onto "/var/lib/lxc/rootfs" with options "(null)"
       lxc-start ubuntu 20180620115612.427 INFO     lxc_conf - conf.c:setup_utsname:787 - Set hostname to "ubuntu"
       lxc-start ubuntu 20180620115612.443 DEBUG    lxc_network - network.c:lxc_setup_netdev_in_child_namespaces:3019 - Network device "eth0" has been setup
       lxc-start ubuntu 20180620115612.443 INFO     lxc_network - network.c:lxc_setup_network_in_child_namespaces:3040 - network has been setup
       lxc-start ubuntu 20180620115612.443 INFO     lxc_conf - conf.c:mount_autodev:1194 - Preparing "/dev"
       lxc-start ubuntu 20180620115612.443 INFO     lxc_conf - conf.c:mount_autodev:1216 - Mounted tmpfs on "/var/lib/lxc/rootfs/dev"
       lxc-start ubuntu 20180620115612.443 INFO     lxc_conf - conf.c:mount_autodev:1233 - Prepared "/dev"
       lxc-start ubuntu 20180620115612.444 INFO     lxc_conf - conf.c:lxc_mount_auto_mounts:717 - Mount source or target for "/var/lib/lxc/rootfs/proc/sysrq-trigger" on "/var/lib/lxc/rootfs/proc/sysrq-trigger" does not exist. Skipping
       lxc-start ubuntu 20180620115612.444 INFO     lxc_conf - conf.c:lxc_mount_auto_mounts:717 - Mount source or target for "(null)" on "/var/lib/lxc/rootfs/proc/sysrq-trigger" does not exist. Skipping
       lxc-start ubuntu 20180620115612.444 INFO     lxc_conf - conf.c:run_script_argv:369 - Executing script "/usr/share/lxcfs/lxc.mount.hook" for container "ubuntu", config section "lxc"
       lxc-start ubuntu 20180620115612.475 INFO     lxc_conf - conf.c:lxc_fill_autodev:1269 - Populating "/dev"
       lxc-start ubuntu 20180620115612.475 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1318 - Bind mounted host device node "/dev/full" onto "/var/lib/lxc/rootfs/dev/full"
       lxc-start ubuntu 20180620115612.475 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1318 - Bind mounted host device node "/dev/null" onto "/var/lib/lxc/rootfs/dev/null"
       lxc-start ubuntu 20180620115612.475 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1318 - Bind mounted host device node "/dev/random" onto "/var/lib/lxc/rootfs/dev/random"
       lxc-start ubuntu 20180620115612.475 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1318 - Bind mounted host device node "/dev/tty" onto "/var/lib/lxc/rootfs/dev/tty"
       lxc-start ubuntu 20180620115612.475 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1318 - Bind mounted host device node "/dev/urandom" onto "/var/lib/lxc/rootfs/dev/urandom"
       lxc-start ubuntu 20180620115612.475 DEBUG    lxc_conf - conf.c:lxc_fill_autodev:1318 - Bind mounted host device node "/dev/zero" onto "/var/lib/lxc/rootfs/dev/zero"
       lxc-start ubuntu 20180620115612.475 INFO     lxc_conf - conf.c:lxc_fill_autodev:1322 - Populated "/dev"
       lxc-start ubuntu 20180620115612.475 DEBUG    lxc_conf - conf.c:mount_entry:1965 - Remounting "/sys/fs/fuse/connections" on "/var/lib/lxc/rootfs/sys/fs/fuse/connections" to respect bind or remount options
       lxc-start ubuntu 20180620115612.475 DEBUG    lxc_conf - conf.c:mount_entry:1986 - Flags for "/sys/fs/fuse/connections" were 4096, required extra flags are 0
       lxc-start ubuntu 20180620115612.475 DEBUG    lxc_conf - conf.c:mount_entry:1996 - Mountflags already were 4096, skipping remount
       lxc-start ubuntu 20180620115612.475 DEBUG    lxc_conf - conf.c:mount_entry:2042 - Mounted "/sys/fs/fuse/connections" on "/var/lib/lxc/rootfs/sys/fs/fuse/connections" with filesystem type "none"
       lxc-start ubuntu 20180620115612.476 DEBUG    lxc_conf - conf.c:mount_entry:1965 - Remounting "/sys/kernel/debug" on "/var/lib/lxc/rootfs/sys/kernel/debug" to respect bind or remount options
       lxc-start ubuntu 20180620115612.476 DEBUG    lxc_conf - conf.c:mount_entry:1986 - Flags for "/sys/kernel/debug" were 4096, required extra flags are 0
       lxc-start ubuntu 20180620115612.476 DEBUG    lxc_conf - conf.c:mount_entry:1996 - Mountflags already were 4096, skipping remount
       lxc-start ubuntu 20180620115612.476 DEBUG    lxc_conf - conf.c:mount_entry:2042 - Mounted "/sys/kernel/debug" on "/var/lib/lxc/rootfs/sys/kernel/debug" with filesystem type "none"
       lxc-start ubuntu 20180620115612.476 INFO     lxc_conf - conf.c:mount_entry:1952 - No such file or directory - Failed to mount "/sys/kernel/security" on "/var/lib/lxc/rootfs/sys/kernel/security" (optional)
       lxc-start ubuntu 20180620115612.476 DEBUG    lxc_conf - conf.c:mount_entry:1965 - Remounting "/sys/fs/pstore" on "/var/lib/lxc/rootfs/sys/fs/pstore" to respect bind or remount options
       lxc-start ubuntu 20180620115612.476 DEBUG    lxc_conf - conf.c:mount_entry:1986 - Flags for "/sys/fs/pstore" were 4110, required extra flags are 14
       lxc-start ubuntu 20180620115612.476 DEBUG    lxc_conf - conf.c:mount_entry:2042 - Mounted "/sys/fs/pstore" on "/var/lib/lxc/rootfs/sys/fs/pstore" with filesystem type "none"
       lxc-start ubuntu 20180620115612.476 DEBUG    lxc_conf - conf.c:mount_entry:2042 - Mounted "mqueue" on "/var/lib/lxc/rootfs/dev/mqueue" with filesystem type "mqueue"
       lxc-start ubuntu 20180620115612.476 INFO     lxc_conf - conf.c:mount_file_entries:2274 - Finished setting up mounts
       lxc-start ubuntu 20180620115612.476 DEBUG    lxc_conf - conf.c:lxc_setup_dev_console:1703 - Mounted pts device "/dev/pts/0" onto "/var/lib/lxc/rootfs/dev/console"
       lxc-start ubuntu 20180620115612.476 INFO     lxc_utils - utils.c:lxc_mount_proc_if_needed:1722 - I am 1, /proc/self points to "1"
       lxc-start ubuntu 20180620115612.491 DEBUG    lxc_conf - conf.c:setup_rootfs_pivot_root:1171 - pivot_root("/var/lib/lxc/rootfs") successful
       lxc-start ubuntu 20180620115612.491 DEBUG    lxc_conf - conf.c:setup_pivot_root:1500 - Finished pivot_root()
       lxc-start ubuntu 20180620115612.491 DEBUG    lxc_conf - conf.c:lxc_setup_devpts:1580 - Mount new devpts instance with options "gid=5,newinstance,ptmxmode=0666,mode=0620,max=1024"
       lxc-start ubuntu 20180620115612.491 DEBUG    lxc_conf - conf.c:lxc_setup_devpts:1600 - Created dummy "/dev/ptmx" file as bind mount target
       lxc-start ubuntu 20180620115612.491 DEBUG    lxc_conf - conf.c:lxc_setup_devpts:1605 - Bind mounted "/dev/pts/ptmx" to "/dev/ptmx"
       lxc-start ubuntu 20180620115612.491 DEBUG    lxc_conf - conf.c:lxc_allocate_ttys:985 - Created tty "/dev/pts/0" with master fd 11 and slave fd 14
       lxc-start ubuntu 20180620115612.491 DEBUG    lxc_conf - conf.c:lxc_allocate_ttys:985 - Created tty "/dev/pts/1" with master fd 15 and slave fd 16
       lxc-start ubuntu 20180620115612.491 DEBUG    lxc_conf - conf.c:lxc_allocate_ttys:985 - Created tty "/dev/pts/2" with master fd 17 and slave fd 18
       lxc-start ubuntu 20180620115612.491 DEBUG    lxc_conf - conf.c:lxc_allocate_ttys:985 - Created tty "/dev/pts/3" with master fd 19 and slave fd 20
       lxc-start ubuntu 20180620115612.491 INFO     lxc_conf - conf.c:lxc_allocate_ttys:1003 - Finished creating 4 tty devices
       lxc-start ubuntu 20180620115612.491 DEBUG    lxc_conf - conf.c:lxc_setup_ttys:944 - Bind mounted "/dev/pts/0" onto "/dev/tty1"
       lxc-start ubuntu 20180620115612.491 DEBUG    lxc_conf - conf.c:lxc_setup_ttys:944 - Bind mounted "/dev/pts/1" onto "/dev/tty2"
       lxc-start ubuntu 20180620115612.491 DEBUG    lxc_conf - conf.c:lxc_setup_ttys:944 - Bind mounted "/dev/pts/2" onto "/dev/tty3"
       lxc-start ubuntu 20180620115612.491 DEBUG    lxc_conf - conf.c:lxc_setup_ttys:944 - Bind mounted "/dev/pts/3" onto "/dev/tty4"
       lxc-start ubuntu 20180620115612.491 INFO     lxc_conf - conf.c:lxc_setup_ttys:953 - Finished setting up 4 /dev/tty<N> device(s)
       lxc-start ubuntu 20180620115612.491 INFO     lxc_conf - conf.c:setup_personality:1644 - Set personality to "0x0"
       lxc-start ubuntu 20180620115612.491 DEBUG    lxc_conf - conf.c:setup_caps:2450 - Capabilities have been setup
       lxc-start ubuntu 20180620115612.491 NOTICE   lxc_conf - conf.c:lxc_setup:3563 - The container "ubuntu" is set up
       lxc-start ubuntu 20180620115612.492 DEBUG    lxc_start - start.c:lxc_spawn:1765 - Preserved cgroup namespace via fd 19
       lxc-start ubuntu 20180620115612.492 NOTICE   lxc_utils - utils.c:lxc_switch_uid_gid:2059 - Switched to gid 0.
       lxc-start ubuntu 20180620115612.492 NOTICE   lxc_utils - utils.c:lxc_switch_uid_gid:2065 - Switched to uid 0.
       lxc-start ubuntu 20180620115612.492 NOTICE   lxc_start - start.c:start:1973 - Exec'ing "/sbin/init"
       lxc-start ubuntu 20180620115612.492 NOTICE   lxc_start - start.c:post_start:1984 - Started "/sbin/init" with pid "4225"
       lxc-start ubuntu 20180620115612.492 NOTICE   lxc_start - start.c:signal_handler:399 - Received 17 from pid 4226 instead of container init 4225

 - The container's configuration file:

       # Template used to create this container: /usr/share/lxc/templates/lxc-download
       # Parameters passed to the template: -d ubuntu -r trusty -a amd64
       # Template script checksum (SHA-1): 9748088977ba845f625e45659f305a5395c2dc7b
       # For additional config options, please look at lxc.container.conf(5)

       # Distribution configuration
       lxc.include = /usr/share/lxc/config/common.conf

       # For Ubuntu 14.04
       lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none bind,optional 0 0
       lxc.mount.entry = /sys/kernel/security sys/kernel/security none bind,optional 0 0
       lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none bind,optional 0 0
       lxc.mount.entry = mqueue dev/mqueue mqueue rw,relatime,create=dir,optional 0 0
       lxc.include = /usr/share/lxc/config/userns.conf
       lxc.arch = x86_64

       # Container specific configuration
       lxc.idmap = u 0 100000 1000
       lxc.idmap = g 0 100000 1000
       lxc.idmap = u 1000 1000 1
       lxc.idmap = g 1000 1000 1
       lxc.idmap = u 1001 101001 64535
       lxc.idmap = g 1001 101001 64535
       lxc.rootfs.path = dir:/var/lib/lxc/ubuntu/rootfs
       lxc.uts.name = ubuntu

       # Network configuration
       lxc.net.0.type = veth
       lxc.net.0.flags = up
       lxc.net.0.link = lxcbr0
       lxc.net.0.name = eth0
       lxc.net.0.ipv4.address = 172.19.1.2/24
       lxc.net.0.ipv4.gateway = 172.19.1.1

**Comment by brauner** [comment]
@stgraber, any idea what the deal with Trusty and rw sysfs is?

A workaround is to set `lxc.mount.auto = sys:mixed` in the container's config file.

**Comment by stgraber** [comment]
Should be something we can fix in the images by adding the two missing lxc.mount.entry

**Comment by stgraber** [comment]
Yeah, that's correct, users of existing unprivileged trusty containers that were created with LXC 3.0 will have to manually fix their configurations, hopefully this is a relatively small set of people/containers.

The current logic is very much correct, unfortunately /sys being read-only in the past was papering over an upstart-related mount issue which has now resurfaced...
