### ISSUE TITLE
lxc-update-config does not respect lxc.roots.backend

### ISSUE THREAD

**Issue by andidevi** [lxc/lxc#2424]
# Issue description

lxc-update-config does not respect lxc.rootfs.backend which leads to broken configurations.

```
lxc.rootfs = x/rootfs
lxc.rootfs.backend = btrfs
```

will be converted to

```
lxc.rootfs.path = x/rootfs
```

which will make lxc-copy and lxc-snapshot complain about a "wrong" backing store.

The correct behaviour would be to look at lxc.rootfs.backend and update the path accordingly:

```
lxc.rootfs.path = btrfs:x/rootfs
```

# Required information

 * Distribution:
 * Distribution version:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

 * The output of
   * `lxc-start --version
2.1.1
   * `lxc-checkconfig`
(everything green)
   * `uname -a`
Linux intern 4.4.0-109-generic #132~14.04.1-Ubuntu SMP Tue Jan 9 21:46:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
Linux intern 4.4.0-109-generic #132~14.04.1-Ubuntu SMP Tue Jan 9 21:46:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/1/mounts`
(nothing special)

# Steps to reproduce

1. 
```
# grep btrfs  legacy/config
lxc.rootfs.backend = btrfs
```
2.
```
lxc-update-config -c legacy/config
```
3.
```
# grep btrfs  legacy/config
```
   (no output)

4.
```
# lxc-snapshop -n legacy 
lxc-snapshot: legacy: lxccontainer.c: do_lxcapi_snapshot: 3751 Snapshot of directory-backed container requested.
lxc-snapshot: legacy: lxccontainer.c: do_lxcapi_snapshot: 3752 Making a copy-clone.  If you do want snapshots, then
lxc-snapshot: legacy: lxccontainer.c: do_lxcapi_snapshot: 3753 please create an aufs or overlay clone first, snapshot that
lxc-snapshot: legacy: lxccontainer.c: do_lxcapi_snapshot: 3754 and keep the original container pristine.
```

# Workaround

Manually edit the updated config and add the btrfs: to the path.

# Information to attach

legacy config
[config.txt](https://github.com/lxc/lxc/files/2123147/config.txt)

**Comment by stgraber** [comment]
@brauner can you fix that?
