### ISSUE TITLE
How to measure LXC container migration statistics 

### ISSUE THREAD

**Issue by adityacloud1** [lxc/lxc#2432]
Hi, all

My experimental setup is to migrate containers from one system to another,

Please suggest how to measure container migration metrics like network traffic, downtime, cpu, and disk utilization.

**Comment by adityacloud1** [comment]
Yes sir, I am migrating containers with host OS distribution Ubuntu 16.04 using LXD, CRIU technique. Containers are created on LXC environment. Version for these packages are:

root@server1:~# lxc --version
2.0.11
root@server1:~# lxd --version
2.0.11
root@server1:~# criu --version
Version: 3.9

**Comment by brauner** [comment]
@adrianreber, any ideas?

**Comment by adrianreber** [comment]
@adityacloud1 I did the following to measure the container downtime during migration:

 * read out clock
 * sleep 100µs
 * read out clock and compare
 * if the difference is bigger than 400µs, we probably missed on read-sleep-read cycle
 * count the missed read-sleep-read cycles and try to guess the time the container was down during migration
 
It seemed difficult to me to measure the time the container was down from LXD, but maybe there are good enough timestamps in LXC to measure it from the outside. We went the route to measure it from the running application.

**Comment by adityacloud1** [comment]
**@adrianreber**  @brauner Thanks a lot for kind information.

**Comment by brauner** [comment]
Sweet, tentatively closing this then.
