### ISSUE TITLE
lxc-start: quota reached

### ISSUE THREAD

**Issue by PeterNguyen0210** [lxc/lxc#245]
Hi,
I'm new with LXC. 
I followed stgraber's excellent tutorials in : https://www.stgraber.org/2014/02/09/lxc-1-0-gui-in-containers/ but when i start container, these errors appear:
user@ubuntu:~$ lxc-start -n precise-gui
Quota reached
lxc-start: failed to create the configured network
lxc-start: failed to spawn 'precise-gui'
lxc-start: the container failed to start.

Information:
I used VMWare to install Ubuntu 14.04 OS.
LXC version : 1.0.3.
Thanks for reading.

**Comment by emprovements** [comment]
Just out of curiosity, how many veth devices needs one container? I have 2 containers which runs fine with default 0 10 but if I tried to start 3rd I got this error.

**Comment by hallyn** [comment]
On Tue, Feb 23, 2016 at 07:15:58AM -0800, Michal Gonda wrote:
> Just out of curiosity, how many veth devices needs one container? I have 2 containers which runs fine with default 0 10 but if I tried to start 3rd I got this error.

A container by default should take up one allocation.  (It's two veth tunnel end-points, but counts as one tunnel)

So you should be able to create 10 containers...

**Comment by emprovements** [comment]
My mistake, I actually forgot to set it in lxc-usernet. Thanks!
