### ISSUE TITLE
Mount propagation of shared flag fails with lxc-start when running in a RAMFS

### ISSUE THREAD

**Issue by KamelHacene** [lxc/lxc#2464]
# Required information

 * Distribution: Custom Linux (generated with Yocto)
 * The output of
   * `lxc-start --version` : 2.0.8
   * `lxc-checkconfig`

> --- Namespaces ---
> Namespaces: enabled
> Utsname namespace: enabled
> Ipc namespace: enabled
> Pid namespace: enabled
> User namespace: enabled
> Network namespace: enabled
> 
> --- Control groups ---
> Cgroup: enabled
> Cgroup clone_children flag: enabled
> Cgroup device: enabled
> Cgroup sched: enabled
> Cgroup cpu account: enabled
> Cgroup memory controller: enabled
> 
> --- Misc ---
> Veth pair device: missing
> Macvlan: enabled
> Vlan: enabled
> Bridges: missing
> Advanced netfilter: enabled
> CONFIG_NF_NAT_IPV4: enabled
> CONFIG_NF_NAT_IPV6: missing
> CONFIG_IP_NF_TARGET_MASQUERADE: enabled
> CONFIG_IP6_NF_TARGET_MASQUERADE: missing
> CONFIG_NETFILTER_XT_TARGET_CHECKSUM: missing
> FUSE (for use with lxcfs): enabled
> 
> --- Checkpoint/Restore ---
> checkpoint restore: enabled
> CONFIG_FHANDLE: enabled
> CONFIG_EVENTFD: enabled
> CONFIG_EPOLL: enabled
> CONFIG_UNIX_DIAG: enabled
> CONFIG_INET_DIAG: enabled
> CONFIG_PACKET_DIAG: enabled
> CONFIG_NETLINK_DIAG: missing
> File capabilities: enabled

   * `uname -a`
> Linux ops 4.14.33 #1 PREEMPT Fri May 4 09:25:35 UTC 2018 armv7l GNU/Linux

   * `Filesystem : ` RAMFS 

# Issue description

When running lxc on a ramfs, the mount share flag is not propagated to the containers started with lxc-start.

This is caused by the MS_PRIVATE mount flag in [prepare_ramfs_root](https://github.com/lxc/lxc/blob/master/src/lxc/conf.c#L1416) function.

The mount propagation works when i remove the following chunk : 
```
	ret = mount(NULL, "/", NULL, MS_REC | MS_PRIVATE, NULL);
	if (ret < 0) {
		SYSERROR("Failed to make \"/\" rprivate");
		return -1;
        }
```

I wanted to be sure i was not creating any big security hole before submitting a patch.

# Steps to reproduce

 1. Create a shared bind mount : 
```
mkdir /share
mkdir /containerfs/share
mount --bind --make-shared /share /containerfs/share
```

 2. Start the container in /containerfs
`lxc-start -n container`

 3. Check /proc/self/mountinfo in the container : shared flag is not present

**Comment by brauner** [comment]
Hm, it seems that you should be able to set `lxc.rootfs.options = rshared`. But then this code would need to change a bit anyway.

**Comment by brauner** [comment]
So one thing I worry about is that the container will umount all kinds of stuff on bootup to cleanup its mount table. So setting `MS_SHARED` will potentially mess with the host but I guess this is fine if the user really wants this.

**Comment by KamelHacene** [comment]
Oh ok it's no really big deal then if we're sharing only non-critical subdirectories (and not the whole container's filesystem).

I'll keep with removing the MS_PRIVATE flag from the lxc-start code for now. Thanks !

**Comment by brauner** [comment]
Tracking this now in https://github.com/lxc/lxc/issues/2477.
