### ISSUE TITLE
"undefined symbol: cgmanager_get_pid_cgroup_abs_sync"

### ISSUE THREAD

**Issue by shovon** [lxc/lxc#247]
For some reason, whenever I run `lxc-create`, I get the error that the symbol `cgmanager_get_pid_cgroup_abs_sync` is not found.

To be more specific, the error looks like the following:

```
lxc-create: symbol lookup error: /usr/lib/x86_64-linux-gnu/liblxc.so.1: undefined symbol: cgmanager_get_pid_cgroup_abs_sync
```

I'm running Ubuntu 14.04, and I installed `lxc` using `apt-get`.

**Comment by john3exonets** [comment]
Still getting this error on an up-to-date 14.04:

$ lxc-ls
Traceback (most recent call last):
  File "/usr/bin/lxc-ls", line 31, in <module>
    import lxc
  File "/usr/lib/python3/dist-packages/lxc/__init__.py", line 26, in <module>
    import _lxc
ImportError: /usr/lib/x86_64-linux-gnu/liblxc.so.1: undefined symbol: cgmanager_get_pid_cgroup_abs_sync

Any clues?   Do I need to open a new ticket??

**Comment by onsmribah** [comment]
It is probably because you are running  an old libcgmanager. To fix this problem, you need to update libcgmanager.
`$ sudo apt-get install libcgmanager0 --upgrade`
