### ISSUE TITLE
Ubuntu apt errors in LXC containers

### ISSUE THREAD

**Issue by loxK** [lxc/lxc#2478]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 *  `lxc --version`: 2.0.11
 *  `lxc-checkconfig`: command not found
* `uname -a` Linux gaiac 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* `cat /proc/self/cgroup`:
```
11:perf_event:/
10:memory:/user.slice
9:blkio:/user.slice
8:hugetlb:/
7:pids:/user.slice/user-1000.slice
6:devices:/user.slice
5:cpuset:/
4:freezer:/
3:net_cls,net_prio:/
2:cpu,cpuacct:/user.slice
1:name=systemd:/user.slice/user-1000.slice/session-42401.scope
```

# Issue description

I don't have a local caching proxy and on my LXD/LXC containers I regularly have an error of Hashsum Mismatch doing `apt update`. When it happens, all my containers are affected by the same Hashsum Mismatch error. Clearing the apt cache doesn't fix it and I use official and main apt mirrors.

Other bare metal computer on the same network aren't affected, nor are the libvirt VMs running on the same server.

**Comment by brauner** [comment]
This is something @stgraber might now about.

**Comment by brauner** [comment]
This should be filed against https://github.com/lxc/lxd.
