### ISSUE TITLE
Try mounting without max= option on older kernels

### ISSUE THREAD

**Issue by trimsj** [lxc/lxc#2490]
It is claimed that "LXC runs on any kernel from 2.6.32 onwards" in the [README](https://github.com/lxc/lxc/blob/master/README.md).

However, the commit ["devpts: use max=<count> option on mount"](https://github.com/lxc/lxc/commit/9d28c4f980502f3bc5b7c6347d1af7bd165336a0) breaks this promise, as noted in its commit message--"This will only work with kernels >= 3.4." It is true that with older kernels, mounting devpts with the "max=" option will fail with EINVAL.

I suggest a fallback that ignores this option when it is not available (like "try mounting without gid=5"). Otherwise I suggest that the kernel requirements be adjusted accordingly in the README to avoid confusion.

**Comment by brauner** [comment]
We could potentially use `lxc.pty.max = unlimited" as an indicator to not place a limit on the `pty` instances. So on older kernels one could set `lxc.pty.max = unlimited` which would mount `devpts` without the `max` option.

**Comment by brauner** [comment]
@trimsj, can you give https://github.com/lxc/lxc/pull/2502 a try, please?
