### ISSUE TITLE
Wrong license header for nvidia hook

### ISSUE THREAD

**Issue by stgraber** [lxc/lxc#2494]
https://github.com/lxc/lxc/blob/38a8a5e5fa175bdaf2d947d134e4eac684ab5775/hooks/nvidia#L3

So hmm, that's clearly wrong, hooks should be LGPLv2.1 (like liblxc) or GPLv2 (like the tools).

@brauner @3XX0 @flx42

**Comment by brauner** [comment]
Yeah, that needs to change...

**Comment by flx42** [comment]
Sorry about that, my intention was to use LGPLv2.1.
