### ISSUE TITLE
access phpmyadmin in a LXC container

### ISSUE THREAD

**Issue by Gaio2015** [lxc/lxc#2498]
Hi

In a LXC container i have installed : 

Apache
PHP7
MySQL
VSFTPD
PHPMyAdmin

My problem is, when i in a browser write "www.domain.com/phpmyadmin" i do get phpmyadmin, but the one on my main server - but i want the one ive installed in the LXC container.

So how do i start the PHPMyAdmin through a browser and get the one from my container ?

Thanks in advance

/Gaio

**Comment by brauner** [comment]
You need to use the container's ip address.

**Comment by Gaio2015** [comment]
How ?

www.domain.com/xxx.xxx.xxx.xxx/PHPMyadmin ?

**Comment by brauner** [comment]
Get the ip address of the container from `lxc-info <container-name>` and type it in your browser.

**Comment by Gaio2015** [comment]
When i do that, i get this : 

lxc-info web
web doesn't exist

Ive installed the LXC utils

**Comment by Gaio2015** [comment]
lxc info web

Name: web
Remote: unix://
Architecture: x86_64
Created: 2018/07/29 15:37 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 10294
Ips:
  eth0: inet    10.1.1.153      vethCLI9TF
  eth0: inet6   fe80::216:3eff:fe87:b16a        vethCLI9TF
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 85
  CPU usage:
    CPU usage (in seconds): 295
  Memory usage:
    Memory (current): 240.29MB
    Memory (peak): 945.55MB
  Network usage:
    eth0:
      Bytes received: 94.32MB
      Bytes sent: 17.70MB
      Packets received: 334230
      Packets sent: 44050
    lo:
      Bytes received: 47.09kB
      Bytes sent: 47.09kB
      Packets received: 589
      Packets sent: 589
Snapshots:
  snap0 (taken at 2018/07/29 16:57 UTC) (stateless)
  snap1 (taken at 2018/07/29 17:59 UTC) (stateless)
  snap2 (taken at 2018/07/29 18:27 UTC) (stateless)
  snap3 (taken at 2018/07/29 18:43 UTC) (stateless)

**Comment by Gaio2015** [comment]
So i still dont know how and what to do to make it work
