### ISSUE TITLE
Failed to create vlan interface "vlan10-0" on "br-1": File exists

### ISSUE THREAD

**Issue by Roosterfish** [lxc/lxc#2522]
# Issue description

I would like to add multiple containers to the same bridge via vlan interfaces. All of them share the same VID. But LXC won't let me do this and throws the following error:
`Failed to create vlan interface "vlan10-0" on "br-1": File exists`
Since this is the expected behaviour (https://github.com/lxc/lxc/blob/c1cf54ebf251fdbad1e971679614e81649f1c032/src/lxc/network.c#L315), I am wondering if it is possible to add an additional container config key like `lxc.net.[i].vlan.name` to be able to set the name of the interface manually?

# Steps to reproduce

 1. Create bridge `br-1`
 2. Configure two LXC containers with the following network settings
```
lxc.net.[i].type = vlan
lxc.net.[i].vlan.id = 10
lxc.net.[i].link = br-1
``` 
 3. Start the first container
 4. Start the second container (Error!)

**Comment by stgraber** [comment]
That's normal, you can only have one VLAN interface per VID per parent.

If you need multiple containers on the same VLAN, you need to create a bridge, put that vlan in the bridge and then attach the containers to the bridge.
