### ISSUE TITLE
block i/o, limit network bandwidth

### ISSUE THREAD

**Issue by PeterNguyen0210** [lxc/lxc#253]
Hi all,

I configured my container with:
lxc.cgroup.blkio.weight = 500
lxc.cgroup.net_cls.classid = 0x00010002 # 1:2

and ran tc commands:
$sudo tc qdisc add dev lxcbr0 root handle 1: htb
$sudo tc class add dev lxcbr0 parent 1: classid 1:1 htb rate 10mbit
$sudo tc class add dev lxcbr0 parent 1: classid 1:2 htb rate 1mbit
$sudo tc filter add dev lxcbr0 protocol ip parent 1: prio 1 handle 1: cgroup

then I started container and tested block i/o, network bandwidth by 
- copy a large file: dd if=/dev/zero of=/tmp/output bs=20k count=100k; rm -f /tmp/output
- upload/download a large file.
  after that, I changed my config:

lxc-cgroup -n container blkio.weight 1000.
lxc-cgroup -n container net_cls.classid 0x00010002

and tested again, but i didn't see a difference. 
I also trying the same commands on eth0 instead of lxcbr0, but there was no effect.
Thanks for reading.

**Comment by brauner** [comment]
This is not related to lxc but to how the corresponding cgroup works. Things might be better once those cgroups are enabled in the unified hierarchy.
