### ISSUE TITLE
lxc-3.0.2 lxc-execute throws error: Failed to unmount "/usr/sbin/init.lxc.static"

### ISSUE THREAD

**Issue by mrinaldhillon** [lxc/lxc#2536]
* Distribution: ubuntu
 * Distribution version: xenial
 * The output of
   * `lxc-start --version`
root@xenial-2:~/lxc-lxc-3.0.2/build# lxc-start --version
3.0.2
   * `lxc-checkconfig`
root@xenial-2:~/lxc-lxc-3.0.2/build# lxc-checkconfig
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.4.0-133-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/pids
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/memory
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/blkio
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/devices
/sys/fs/cgroup/freezer
/sys/fs/cgroup/perf_event

Cgroup v2 mount points:

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, not loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, not loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities:
   * `uname -a`
root@xenial-2:~/lxc-lxc-3.0.2/build# uname -a
Linux xenial-2 4.4.0-133-generic #159-Ubuntu SMP Fri Aug 10 07:31:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
root@xenial-2:~/lxc-lxc-3.0.2/build# cat /proc/self/cgroup
11:perf_event:/
10:freezer:/
9:devices:/user.slice
8:net_cls,net_prio:/
7:blkio:/
6:cpu,cpuacct:/
5:memory:/
4:cpuset:/
3:pids:/user.slice/user-1000.slice
2:hugetlb:/
1:name=systemd:/user.slice/user-1000.slice/session-1.scope
   * `cat /proc/1/mounts`
root@xenial-2:~/lxc-lxc-3.0.2/build# cat /proc/1/cgroup
11:perf_event:/
10:freezer:/
9:devices:/init.scope
8:net_cls,net_prio:/
7:blkio:/
6:cpu,cpuacct:/
5:memory:/
4:cpuset:/
3:pids:/init.scope
2:hugetlb:/
1:name=systemd:/init.scope

# Issue description
lxc-execute spits non-fatal error: Failed to unmount "/usr/sbin/init.lxc.static"

root@xenial-2:~/lxc-lxc-3.0.2/build# lxc-execute cntr -- ls
lxc-init: cntr: ../../../src/lxc/cmd/lxc_init.c: remove_self: 211 No such file or directory - Failed to unmount "/usr/sbin/init.lxc.static"
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var

On host: root@xenial-2:~/lxc-lxc-3.0.2/build# ls /usr/sbin/init.lxc.static
/usr/sbin/init.lxc.static

Inside container:
root@xenial-2:~/lxc-lxc-3.0.2/build# lxc-execute cntr -- bash
lxc-init: cntr: ../../../src/lxc/cmd/lxc_init.c: remove_self: 211 No such file or directory - Failed to unmount "/usr/sbin/init.lxc.static"
root@cntr:/# ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 init
    2 pts/1    Ss     0:00 bash
   12 pts/1    R+     0:00 ps ax
root@cntr:/# readlink /proc/1/exe
/usr/sbin/init.lxc.static

What is issue here and under which scenarios will this fail lxc-execute or result in some undefined behaviours? If its non-fatal, is there a way to silence this error or treated as warning?

# Steps to reproduce
 1. Step one : Compile and Install
tar -xzvf lxc-3.0.2.tar.gz
cd ~/lxc-lxc-3.0.2/
./autogen.sh
mkdir build; cd build
../configure --prefix=/ --exec-prefix=/usr --datarootdir=/usr/share --includedir=/usr/include --disable-apparmor --enable-pam --disable-selinux --enable-capabilities --enable-seccomp
make -j12
make install

 2. Step two: 
root@xenial-2:~/lxc-lxc-3.0.2/build# lxc-create cntr -t download -- -d ubuntu -r xenial -a amd64 --no-validate
 3. Step three
root@xenial-2:~/lxc-lxc-3.0.2/build# lxc-execute cntr -- ls
lxc-init: cntr: ../../../src/lxc/cmd/lxc_init.c: remove_self: 211 No such file or directory - Failed to unmount "/usr/sbin/init.lxc.static"
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
lxc-execute cntr 20180816223402.644 WARN     start - ../../../src/lxc/start.c:lxc_check_inherited:289 - Inherited fd 3
lxc-execute cntr 20180816223402.644 INFO     lsm - ../../../src/lxc/lsm/lsm.c:lsm_init:47 - LSM security driver nop
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:757 - Processing "reject_force_umount  # comment this to allow umount -f;  not recommended"
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:do_resolve_add_rule:503 - Set seccomp rule to reject force umounts
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:934 - Added native rule for arch 0 for reject_force_umount action 0(kill)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:do_resolve_add_rule:503 - Set seccomp rule to reject force umounts
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:943 - Added compat rule for arch 1073741827 for reject_force_umount action 0(kill)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:do_resolve_add_rule:503 - Set seccomp rule to reject force umounts
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:953 - Added compat rule for arch 1073741886 for reject_force_umount action 0(kill)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:do_resolve_add_rule:503 - Set seccomp rule to reject force umounts
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:963 - Added native rule for arch -1073741762 for reject_force_umount action 0(kill)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:757 - Processing "[all]"
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:757 - Processing "kexec_load errno 1"
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:934 - Added native rule for arch 0 for kexec_load action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:943 - Added compat rule for arch 1073741827 for kexec_load action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:953 - Added compat rule for arch 1073741886 for kexec_load action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:963 - Added native rule for arch -1073741762 for kexec_load action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:757 - Processing "open_by_handle_at errno 1"
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:934 - Added native rule for arch 0 for open_by_handle_at action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:943 - Added compat rule for arch 1073741827 for open_by_handle_at action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:953 - Added compat rule for arch 1073741886 for open_by_handle_at action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:963 - Added native rule for arch -1073741762 for open_by_handle_at action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:757 - Processing "init_module errno 1"
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:934 - Added native rule for arch 0 for init_module action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:943 - Added compat rule for arch 1073741827 for init_module action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:953 - Added compat rule for arch 1073741886 for init_module action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:963 - Added native rule for arch -1073741762 for init_module action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:757 - Processing "finit_module errno 1"
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:934 - Added native rule for arch 0 for finit_module action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:943 - Added compat rule for arch 1073741827 for finit_module action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:953 - Added compat rule for arch 1073741886 for finit_module action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:963 - Added native rule for arch -1073741762 for finit_module action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:757 - Processing "delete_module errno 1"
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:934 - Added native rule for arch 0 for delete_module action 327681(errno)
lxc-execute cntr 20180816223402.645 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:943 - Added compat rule for arch 1073741827 for delete_module action 327681(errno)
lxc-execute cntr 20180816223402.646 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:953 - Added compat rule for arch 1073741886 for delete_module action 327681(errno)
lxc-execute cntr 20180816223402.646 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:963 - Added native rule for arch -1073741762 for delete_module action 327681(errno)
lxc-execute cntr 20180816223402.646 INFO     seccomp - ../../../src/lxc/seccomp.c:parse_config_v2:967 - Merging compat seccomp contexts into main context
lxc-execute cntr 20180816223402.647 DEBUG    terminal - ../../../src/lxc/terminal.c:lxc_terminal_peer_default:711 - Using terminal "/dev/tty" as proxy
lxc-execute cntr 20180816223402.647 DEBUG    terminal - ../../../src/lxc/terminal.c:lxc_terminal_signal_init:189 - Created signal fd 10
lxc-execute cntr 20180816223402.647 DEBUG    terminal - ../../../src/lxc/terminal.c:lxc_terminal_winsz:87 - Set window size to 272 columns and 69 rows
lxc-execute cntr 20180816223402.648 INFO     start - ../../../src/lxc/start.c:lxc_init:866 - Container "cntr" is initialized
lxc-execute cntr 20180816223402.648 DEBUG    cgfsng - ../../../src/lxc/cgroups/cgfsng.c:cg_legacy_handle_cpuset_hierarchy:613 - "cgroup.clone_children" was already set to "1"
lxc-execute cntr 20180816223402.649 INFO     start - ../../../src/lxc/start.c:lxc_spawn:1657 - Cloned CLONE_NEWNS
lxc-execute cntr 20180816223402.649 INFO     start - ../../../src/lxc/start.c:lxc_spawn:1657 - Cloned CLONE_NEWPID
lxc-execute cntr 20180816223402.649 INFO     start - ../../../src/lxc/start.c:lxc_spawn:1657 - Cloned CLONE_NEWUTS
lxc-execute cntr 20180816223402.649 INFO     start - ../../../src/lxc/start.c:lxc_spawn:1657 - Cloned CLONE_NEWIPC
lxc-execute cntr 20180816223402.649 INFO     start - ../../../src/lxc/start.c:lxc_spawn:1657 - Cloned CLONE_NEWNET
lxc-execute cntr 20180816223402.649 DEBUG    start - ../../../src/lxc/start.c:lxc_try_preserve_namespaces:205 - Preserved mnt namespace via fd 16
lxc-execute cntr 20180816223402.649 DEBUG    start - ../../../src/lxc/start.c:lxc_try_preserve_namespaces:205 - Preserved pid namespace via fd 17
lxc-execute cntr 20180816223402.650 DEBUG    start - ../../../src/lxc/start.c:lxc_try_preserve_namespaces:205 - Preserved uts namespace via fd 18
lxc-execute cntr 20180816223402.650 DEBUG    start - ../../../src/lxc/start.c:lxc_try_preserve_namespaces:205 - Preserved ipc namespace via fd 19
lxc-execute cntr 20180816223402.650 DEBUG    start - ../../../src/lxc/start.c:lxc_try_preserve_namespaces:205 - Preserved net namespace via fd 20
lxc-execute cntr 20180816223402.650 INFO     cgfsng - ../../../src/lxc/cgroups/cgfsng.c:__cg_legacy_setup_limits:2196 - Limits for the legacy cgroup hierarchies have been setup
lxc-execute cntr 20180816223402.666 DEBUG    start - ../../../src/lxc/start.c:lxc_spawn:1711 - Preserved net namespace via fd 11
lxc-execute cntr 20180816223402.666 INFO     start - ../../../src/lxc/start.c:do_start:1213 - Unshared CLONE_NEWCGROUP
lxc-execute cntr 20180816223402.667 DEBUG    storage - ../../../src/lxc/storage/storage.c:get_storage_by_name:229 - Detected rootfs type "dir"
lxc-execute cntr 20180816223402.667 DEBUG    conf - ../../../src/lxc/conf.c:lxc_mount_rootfs:1343 - Mounted rootfs "//var/lib/lxc/cntr/rootfs" onto "/usr/lib/lxc/rootfs" with options "(null)"
lxc-execute cntr 20180816223402.667 INFO     conf - ../../../src/lxc/conf.c:setup_utsname:802 - Set hostname to "cntr"
lxc-execute cntr 20180816223402.667 INFO     network - ../../../src/lxc/network.c:lxc_setup_network_in_child_namespaces:3037 - network has been setup
lxc-execute cntr 20180816223402.667 INFO     conf - ../../../src/lxc/conf.c:mount_autodev:1129 - Preparing "/dev"
lxc-execute cntr 20180816223402.667 INFO     conf - ../../../src/lxc/conf.c:mount_autodev:1176 - Prepared "/dev"
lxc-execute cntr 20180816223402.668 INFO     conf - ../../../src/lxc/conf.c:lxc_fill_autodev:1220 - Populating "/dev"
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:lxc_fill_autodev:1235 - Created device node "/usr/lib/lxc/rootfs/dev/full"
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:lxc_fill_autodev:1235 - Created device node "/usr/lib/lxc/rootfs/dev/null"
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:lxc_fill_autodev:1235 - Created device node "/usr/lib/lxc/rootfs/dev/random"
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:lxc_fill_autodev:1235 - Created device node "/usr/lib/lxc/rootfs/dev/tty"
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:lxc_fill_autodev:1235 - Created device node "/usr/lib/lxc/rootfs/dev/urandom"
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:lxc_fill_autodev:1235 - Created device node "/usr/lib/lxc/rootfs/dev/zero"
lxc-execute cntr 20180816223402.668 INFO     conf - ../../../src/lxc/conf.c:lxc_fill_autodev:1297 - Populated "/dev"
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:mount_entry:2025 - Remounting "/sys/fs/fuse/connections" on "/usr/lib/lxc/rootfs/sys/fs/fuse/connections" to respect bind or remount options
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:mount_entry:2046 - Flags for "/sys/fs/fuse/connections" were 4096, required extra flags are 0
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:mount_entry:2056 - Mountflags already were 4096, skipping remount
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:mount_entry:2100 - Mounted "/sys/fs/fuse/connections" on "/usr/lib/lxc/rootfs/sys/fs/fuse/connections" with filesystem type "none"
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:mount_entry:2025 - Remounting "/sys/kernel/debug" on "/usr/lib/lxc/rootfs/sys/kernel/debug" to respect bind or remount options
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:mount_entry:2046 - Flags for "/sys/kernel/debug" were 4096, required extra flags are 0
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:mount_entry:2056 - Mountflags already were 4096, skipping remount
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:mount_entry:2100 - Mounted "/sys/kernel/debug" on "/usr/lib/lxc/rootfs/sys/kernel/debug" with filesystem type "none"
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:mount_entry:2025 - Remounting "/sys/kernel/security" on "/usr/lib/lxc/rootfs/sys/kernel/security" to respect bind or remount options
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:mount_entry:2046 - Flags for "/sys/kernel/security" were 4110, required extra flags are 14
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:mount_entry:2100 - Mounted "/sys/kernel/security" on "/usr/lib/lxc/rootfs/sys/kernel/security" with filesystem type "none"
lxc-execute cntr 20180816223402.668 DEBUG    conf - ../../../src/lxc/conf.c:mount_entry:2025 - Remounting "/sys/fs/pstore" on "/usr/lib/lxc/rootfs/sys/fs/pstore" to respect bind or remount options
lxc-execute cntr 20180816223402.669 DEBUG    conf - ../../../src/lxc/conf.c:mount_entry:2046 - Flags for "/sys/fs/pstore" were 4110, required extra flags are 14
lxc-execute cntr 20180816223402.669 DEBUG    conf - ../../../src/lxc/conf.c:mount_entry:2100 - Mounted "/sys/fs/pstore" on "/usr/lib/lxc/rootfs/sys/fs/pstore" with filesystem type "none"
lxc-execute cntr 20180816223402.669 DEBUG    conf - ../../../src/lxc/conf.c:mount_entry:2100 - Mounted "mqueue" on "/usr/lib/lxc/rootfs/dev/mqueue" with filesystem type "mqueue"
lxc-execute cntr 20180816223402.669 INFO     conf - ../../../src/lxc/conf.c:mount_file_entries:2331 - Finished setting up mounts
lxc-execute cntr 20180816223402.669 DEBUG    conf - ../../../src/lxc/conf.c:lxc_setup_ttydir_console:1794 - Created directory for console and tty devices at "/usr/lib/lxc/rootfs/dev/lxc"
lxc-execute cntr 20180816223402.669 DEBUG    conf - ../../../src/lxc/conf.c:lxc_setup_ttydir_console:1839 - Mounted "/dev/pts/1" onto "/usr/lib/lxc/rootfs/dev/lxc/console"
lxc-execute cntr 20180816223402.669 DEBUG    conf - ../../../src/lxc/conf.c:lxc_setup_ttydir_console:1847 - Mounted "/dev/pts/1" onto "/usr/lib/lxc/rootfs/dev/lxc/console"
lxc-execute cntr 20180816223402.669 DEBUG    conf - ../../../src/lxc/conf.c:lxc_setup_ttydir_console:1849 - Console has been setup under "/usr/lib/lxc/rootfs/dev/lxc/console" and mounted to "/usr/lib/lxc/rootfs/dev/console"
lxc-execute cntr 20180816223402.669 INFO     utils - ../../../src/lxc/utils.c:lxc_mount_proc_if_needed:1843 - I am 1, /proc/self points to "1"
lxc-execute cntr 20180816223402.685 WARN     conf - ../../../src/lxc/conf.c:lxc_setup_devpts:1618 - Invalid argument - Failed to unmount old devpts instance
lxc-execute cntr 20180816223402.685 DEBUG    conf - ../../../src/lxc/conf.c:lxc_setup_devpts:1651 - Mount new devpts instance with options "gid=5,newinstance,ptmxmode=0666,mode=0620,max=1024"
lxc-execute cntr 20180816223402.685 DEBUG    conf - ../../../src/lxc/conf.c:lxc_setup_devpts:1670 - Created dummy "/dev/ptmx" file as bind mount target
lxc-execute cntr 20180816223402.685 DEBUG    conf - ../../../src/lxc/conf.c:lxc_setup_devpts:1675 - Bind mounted "/dev/pts/ptmx" to "/dev/ptmx"
lxc-execute cntr 20180816223402.686 DEBUG    conf - ../../../src/lxc/conf.c:lxc_allocate_ttys:1000 - Created tty "/dev/pts/0" with master fd 15 and slave fd 16
lxc-execute cntr 20180816223402.686 DEBUG    conf - ../../../src/lxc/conf.c:lxc_allocate_ttys:1000 - Created tty "/dev/pts/1" with master fd 17 and slave fd 18
lxc-execute cntr 20180816223402.686 DEBUG    conf - ../../../src/lxc/conf.c:lxc_allocate_ttys:1000 - Created tty "/dev/pts/2" with master fd 19 and slave fd 20
lxc-execute cntr 20180816223402.686 DEBUG    conf - ../../../src/lxc/conf.c:lxc_allocate_ttys:1000 - Created tty "/dev/pts/3" with master fd 21 and slave fd 22
lxc-execute cntr 20180816223402.686 INFO     conf - ../../../src/lxc/conf.c:lxc_allocate_ttys:1016 - Finished creating 4 tty devices
lxc-execute cntr 20180816223402.686 INFO     conf - ../../../src/lxc/conf.c:setup_personality:1714 - Set personality to "0x0"
lxc-execute cntr 20180816223402.686 DEBUG    conf - ../../../src/lxc/conf.c:setup_caps:2505 - Dropped mac_admin (33) capability
lxc-execute cntr 20180816223402.686 DEBUG    conf - ../../../src/lxc/conf.c:setup_caps:2505 - Dropped mac_override (32) capability
lxc-execute cntr 20180816223402.686 DEBUG    conf - ../../../src/lxc/conf.c:setup_caps:2505 - Dropped sys_time (25) capability
lxc-execute cntr 20180816223402.686 DEBUG    conf - ../../../src/lxc/conf.c:setup_caps:2505 - Dropped sys_module (16) capability
lxc-execute cntr 20180816223402.686 DEBUG    conf - ../../../src/lxc/conf.c:setup_caps:2505 - Dropped sys_rawio (17) capability
lxc-execute cntr 20180816223402.686 DEBUG    conf - ../../../src/lxc/conf.c:setup_caps:2508 - Capabilities have been setup
lxc-execute cntr 20180816223402.686 NOTICE   conf - ../../../src/lxc/conf.c:lxc_setup:3698 - The container "cntr" is set up
lxc-execute cntr 20180816223402.687 DEBUG    cgfsng - ../../../src/lxc/cgroups/cgfsng.c:__cg_legacy_setup_limits:2191 - Set controller "devices.deny" set to "a"
lxc-execute cntr 20180816223402.688 DEBUG    cgfsng - ../../../src/lxc/cgroups/cgfsng.c:__cg_legacy_setup_limits:2191 - Set controller "devices.allow" set to "c *:* m"
lxc-execute cntr 20180816223402.688 DEBUG    cgfsng - ../../../src/lxc/cgroups/cgfsng.c:__cg_legacy_setup_limits:2191 - Set controller "devices.allow" set to "b *:* m"
lxc-execute cntr 20180816223402.688 DEBUG    cgfsng - ../../../src/lxc/cgroups/cgfsng.c:__cg_legacy_setup_limits:2191 - Set controller "devices.allow" set to "c 1:3 rwm"
lxc-execute cntr 20180816223402.688 DEBUG    cgfsng - ../../../src/lxc/cgroups/cgfsng.c:__cg_legacy_setup_limits:2191 - Set controller "devices.allow" set to "c 1:5 rwm"
lxc-execute cntr 20180816223402.688 DEBUG    cgfsng - ../../../src/lxc/cgroups/cgfsng.c:__cg_legacy_setup_limits:2191 - Set controller "devices.allow" set to "c 1:7 rwm"
lxc-execute cntr 20180816223402.688 DEBUG    cgfsng - ../../../src/lxc/cgroups/cgfsng.c:__cg_legacy_setup_limits:2191 - Set controller "devices.allow" set to "c 5:0 rwm"
lxc-execute cntr 20180816223402.688 DEBUG    cgfsng - ../../../src/lxc/cgroups/cgfsng.c:__cg_legacy_setup_limits:2191 - Set controller "devices.allow" set to "c 5:1 rwm"
lxc-execute cntr 20180816223402.688 DEBUG    cgfsng - ../../../src/lxc/cgroups/cgfsng.c:__cg_legacy_setup_limits:2191 - Set controller "devices.allow" set to "c 5:2 rwm"
lxc-execute cntr 20180816223402.688 DEBUG    cgfsng - ../../../src/lxc/cgroups/cgfsng.c:__cg_legacy_setup_limits:2191 - Set controller "devices.allow" set to "c 1:8 rwm"
lxc-execute cntr 20180816223402.688 DEBUG    cgfsng - ../../../src/lxc/cgroups/cgfsng.c:__cg_legacy_setup_limits:2191 - Set controller "devices.allow" set to "c 1:9 rwm"
lxc-execute cntr 20180816223402.688 DEBUG    cgfsng - ../../../src/lxc/cgroups/cgfsng.c:__cg_legacy_setup_limits:2191 - Set controller "devices.allow" set to "c 136:* rwm"
lxc-execute cntr 20180816223402.688 DEBUG    cgfsng - ../../../src/lxc/cgroups/cgfsng.c:__cg_legacy_setup_limits:2191 - Set controller "devices.allow" set to "c 10:229 rwm"
lxc-execute cntr 20180816223402.688 INFO     cgfsng - ../../../src/lxc/cgroups/cgfsng.c:__cg_legacy_setup_limits:2196 - Limits for the legacy cgroup hierarchies have been setup
lxc-execute cntr 20180816223402.688 DEBUG    start - ../../../src/lxc/start.c:lxc_spawn:1788 - Preserved cgroup namespace via fd 21
lxc-execute cntr 20180816223402.688 NOTICE   utils - ../../../src/lxc/utils.c:lxc_setgroups:2201 - Dropped additional groups.
lxc-execute cntr 20180816223402.688 NOTICE   utils - ../../../src/lxc/utils.c:lxc_switch_uid_gid:2183 - Switched to gid 0.
lxc-execute cntr 20180816223402.688 NOTICE   utils - ../../../src/lxc/utils.c:lxc_switch_uid_gid:2189 - Switched to uid 0.
lxc-execute cntr 20180816223402.688 NOTICE   execute - ../../../src/lxc/execute.c:execute_start:116 - Exec'ing "ls"
lxc-execute cntr 20180816223402.689 NOTICE   execute - ../../../src/lxc/execute.c:execute_post_start:139 - 'ls' started with pid '26979'
lxc-init cntr 20180816223402.690 ERROR    lxc_init - ../../../src/lxc/cmd/lxc_init.c:remove_self:211 - No such file or directory - Failed to unmount "/usr/sbin/init.lxc.static"
lxc-init cntr 20180816223402.690 INFO     lxc_init - ../../../src/lxc/cmd/lxc_init.c:main:363 - Attempting to set proc title to "init"
lxc-init cntr 20180816223402.690 NOTICE   lxc_init - ../../../src/lxc/cmd/lxc_init.c:main:356 - Exec'ing "ls"
lxc-init cntr 20180816223402.693 DEBUG    lxc_init - ../../../src/lxc/cmd/lxc_init.c:main:432 - No such process - Failed to send signal "17" to 2
lxc-execute cntr 20180816223402.693 DEBUG    start - ../../../src/lxc/start.c:signal_handler:413 - Container init process 26979 exited
lxc-execute cntr 20180816223402.694 DEBUG    network - ../../../src/lxc/network.c:lxc_delete_network:3164 - Deleted network devices
~
 - [ ] the containers configuration file
root@xenial-2:~/lxc-lxc-3.0.2/build# cat /var/lib/lxc/cntr/config
# Template used to create this container: /usr/share/lxc/templates/lxc-download
# Parameters passed to the template: -d ubuntu -r xenial -a amd64 --no-validate
# Template script checksum (SHA-1): bc0f1e80a4a1262694503ec827114001faba7e6d
# For additional config options, please look at lxc.container.conf(5)

# Uncomment the following line to support nesting containers:
#lxc.include = /usr/share/lxc/config/nesting.conf
# (Be aware this has security implications)

# Distribution configuration
lxc.include = /usr/share/lxc/config/common.conf

# For Ubuntu 14.04
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none bind,optional 0 0
lxc.mount.entry = /sys/kernel/security sys/kernel/security none bind,optional 0 0
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none bind,optional 0 0
lxc.mount.entry = mqueue dev/mqueue mqueue rw,relatime,create=dir,optional 0 0
lxc.arch = linux64

# Container specific configuration
lxc.rootfs.path = dir://var/lib/lxc/cntr/rootfs
lxc.uts.name = cntr

# Network configuration
lxc.net.0.type = empty

**Comment by brauner** [comment]
As a temporary workaround you can use:
```
lxc-execute <container-name> -l fatal -o none
```
