### ISSUE TITLE
error while building the lxc-3.0.2 rpm

### ISSUE THREAD

**Issue by aston-r** [lxc/lxc#2541]
Dear Developers,

$subj

STR:
-build rpm using the default lxc.spec from the repository

Actual Result:
```
RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/lib64/liblxc.a
make: *** [rpm] Error 1
```

I have fixed the issue in the following way:
```
--- a/lxc.spec.in
+++ b/lxc.spec.in
@@ -244,6 +244,7 @@ fi
 %defattr(-,root,root)
 %{_sbindir}/*
 %{_libdir}/*.so.*
+%{_libdir}/*.a
 %{_libdir}/%{name}
 %{_localstatedir}/*

```

As far as I can see the issue appears after the following changes: https://github.com/lxc/lxc/commit/57d533fb399c7246fc94c508065f2496906ce915

**Comment by brauner** [comment]
On Thu, Aug 16, 2018 at 11:45:48PM -0700, aston-r wrote:
> Dear Developers,
> 
> $subj
> 
> STR:
> -build rpm using the default lxc.spec from the repository
> 
> Actual Result:
> ```
> RPM build errors:
>     Installed (but unpackaged) file(s) found:
>    /usr/lib64/liblxc.a
> make: *** [rpm] Error 1
> ```
> 
> I have fixed the issue in the following way:
> ```
> --- a/lxc.spec.in
> +++ b/lxc.spec.in
> @@ -244,6 +244,7 @@ fi
>  %defattr(-,root,root)
>  %{_sbindir}/*
>  %{_libdir}/*.so.*
> +%{_libdir}/*.a
>  %{_libdir}/%{name}
>  %{_localstatedir}/*
> 
> ```
> 
> As far as I can see the issue appears after the following changes: https://github.com/lxc/lxc/commit/57d533fb399c7246fc94c508065f2496906ce915

Ah right, when I introduced the static build. Can you please send your
fix as a signed-off pr against the repo?

Thanks!
Christian

**Comment by brauner** [comment]
Thanks everyone!
