### ISSUE TITLE
PAM unable to open pam_cgfs.so after upgrade

### ISSUE THREAD

**Issue by vikkio** [lxc/lxc#2556]
# Required information

 * Distribution: Arch Linux
 * Distribution version: 4.14.65-1-lts

# Issue description

Upgraded LXC from 3.0.1-1 to 3.0.2-1 and got following errors in systemd journal...

Aug 17 16:06:25 localhost sshd[747]: PAM unable to dlopen(/usr/lib/security/pam_cgfs.so): /usr/lib/security/pam_cgfs.so: undefined symbol: strlcat
Aug 17 16:06:25 localhost sshd[747]: PAM adding faulty module: /usr/lib/security/pam_cgfs.so

This affects unprivileged containers so they can't start...

lxc-start CONTAINER 20180817133714.509 ERROR cgfsng - cgroups/cgfsng.c:all_controllers_found:701 - No freezer controller mountpoint found
lxc-start CONTAINER 20180817133714.509 ERROR cgroup - cgroups/cgroup.c:cgroup_init:44 - Failed to initialize cgroup driver
lxc-start CONTAINER 20180817133714.509 ERROR start - start.c:lxc_init:861 - Failed to initialize cgroup driver

Reverted back to 3.0.1-1 and it works again.

# Steps to reproduce

$ cat "session optional pam_cgfs.so -c freezer,memory,name=systemd,unified" >> /etc/pam.d/system-login

Upgrade to 3.0.1-2 and the "PAM unable to dlopen" should appear during boot.

**Comment by stgraber** [comment]
@brauner looks like another case of the PAM module relying on internal symbols of liblxc...
We should really add a test for it or another refactoring will re-introduce this problem again.

**Comment by brauner** [comment]
This issue is caused by not having pam make use of the same sources as liblxc does. I'm trying to fix that.
