### ISSUE TITLE
Add support for openvswitch bridges

### ISSUE THREAD

**Issue by zulcss** [lxc/lxc#256]
When starting a container with openvswitch I get the following error:

lxc-start: failed to attach 'veth5GML3H' to the bridge 'br-int' : Operation not supported
lxc-start: failed to create netdev
lxc-start: failed to create the network

The following config is used:

 lxc.network.type = veth
 lxc.network.flags = up
 lxc.network.link = br-int
 lxc.network.hwaddr = fa:16:3e:15:c2:f

**Comment by brauner** [comment]
Support for openvswitch bridges has been added as of https://github.com/lxc/lxc/commit/0d2047716ad6967eb4714b2448a89593dc266cef .
