### ISSUE TITLE
LXC spec file generates error in %post section

### ISSUE THREAD

**Issue by tomponline** [lxc/lxc#2573]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: CentOS
 * Distribution version: 7
 * The output of
   * `lxc-start --version` 3.0.2
   * `lxc-checkconfig` 
   * `uname -a`
   * `cat /proc/self/cgroup`
   * `cat /proc/1/mounts`

# Issue description

A brief description of what failed or what could be improved.

When installing from RPM after building from official spec file, you get this warning:

```
/var/tmp/rpm-tmp.KPquSe: line 14: /usr/local/etc/default/lxc-net: No such file or directory
warning: %post(lxc-3.0.2-1.el7.x86_64) scriptlet failed, exit status 1
```

# Steps to reproduce

 1. Step one
Build RPM from lxc.spec

 2. Step two
Install RPM

 3. Step three

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
 - [ ] the containers configuration file

**Comment by tomponline** [comment]
https://github.com/lxc/lxc/blob/master/lxc.spec.in

**Comment by brauner** [comment]
I have to say that my rpm skills are pretty lacking since my SUSE days are over. @monstermunchkin, can you help here?

**Comment by tomponline** [comment]
@brauner i suspect its something to with the `@LXC_DISTRO_SYSCONF@` not being updated somewhere when the release tarball is built, or rather, perhaps it needs to be overriden in RPM spec file, with one of the RPM env vars.

**Comment by tomponline** [comment]
@brauner e.g. using the RPM env var for sysconfig like here https://github.com/lxc/lxc/blob/master/lxc.spec.in#L230

**Comment by 2xsec** [comment]
@tomponline post section script error is fixed.(https://github.com/lxc/lxc/pull/2686) :)

**Comment by brauner** [comment]
Thanks everyone!

**Comment by tomponline** [comment]
lovely stuff thanks @2xsec
