### ISSUE TITLE
Created container cannot bring up network

### ISSUE THREAD

**Issue by graysky2** [lxc/lxc#2582]
# Required information

 * Distribution: Arch ARM (aarch64)
 * Distribution version: rolling release
 * The output of
```
lxc-start --version
3.0.2
```

```
lxc-checkconfig
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/devices
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/debug
/sys/fs/cgroup/memory
/sys/fs/cgroup/freezer
/sys/fs/cgroup/blkio
/sys/fs/cgroup/hugetlb

Cgroup v2 mount points: 


Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, not loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: missing
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```

```
uname -r
3.16.57-1-ARCH
```

```
cat /proc/self/cgroup
11:hugetlb:/
10:blkio:/
9:freezer:/
8:memory:/user.slice/user-1000.slice/session-c5.scope
7:debug:/
6:cpuset:/
5:cpu,cpuacct:/
4:devices:/user.slice
3:perf_event:/
2:net_cls,net_prio:/
1:name=systemd:/user.slice/user-1000.slice/session-c5.scope
```

```
cat /proc/1/mounts
rootfs / rootfs rw 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sys /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
dev /dev devtmpfs rw,nosuid,relatime,size=737128k,nr_inodes=184282,mode=755 0 0
run /run tmpfs rw,nosuid,nodev,relatime,mode=755 0 0
/dev/mmcblk0p1 / ext4 rw,relatime,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/debug cgroup rw,nosuid,nodev,noexec,relatime,debug 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=39,pgrp=1,timeout=0,minproto=5,maxproto=5,direct 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=176728k,mode=700,uid=1000,gid=985 0 0
```

# Issue description

I cannot get the network within the contain to come up using the provided systemd-networkd config.  Inspecting journalctl in the container gives an error around resetting devices.list.  Related?
```
Sep 02 08:44:02 base systemd[1]: systemd-networkd.service: Failed to reset devices.list: Operation not permitted
Sep 02 08:44:02 base systemd-networkd[29]: Enumeration completed
Sep 02 08:44:02 base systemd-networkd[29]: eth0: Gained IPv6LL
Sep 02 08:44:03 base systemd-networkd[29]: request_name_destroy_callback n_ref=1
Sep 02 08:44:52 base systemd[1]: systemd-networkd.service: Failed to reset devices.list: Operation not permitted
Sep 02 08:44:53 base systemd-networkd[27]: Enumeration completed
Sep 02 08:44:53 base systemd-networkd[27]: request_name_destroy_callback n_ref=1
Sep 02 08:44:53 base systemd-networkd[27]: eth0: Gained IPv6LL
...
```

The complete journalctl output from within the container is attached.

# Information to attach

 - [X] any relevant kernel output (`dmesg`)
 - [X] container log (The <log> file from running `lxc-start -n base -l DEBUG -o base.log`)
 - [X] the containers configuration file
 - [X] journalctl output from within the container

[dmesg](https://github.com/lxc/lxc/files/2343148/dmesg.log)
[base.log](https://github.com/lxc/lxc/files/2343153/base.log)
[config](https://github.com/lxc/lxc/files/2343152/config.txt)
[journalctl.log](https://github.com/lxc/lxc/files/2343155/journalctl.log)

**Comment by graysky2** [comment]
The top post was using an ODROID-C2 (3.16.x series of kernel).  I can confirm the behavior (bug?) using a  Raspberry Pi 3 also running aarch64 but on the mainline kernel (currently 4.18.6).  A very similar setup on armv7h works just fine on the identical Raspberry Pi 3 hardware.

Note that I created the container with `lxc-create -n base -t /usr/share/lxc/templates/lxc-archlinux` using the provided templates (version 3.0.2).

# Information to attach

 - [X] output of `lxc-create` as mentioned above
 - [X] any relevant kernel output (`dmesg`)
 - [X] container log (The <log> file from running `lxc-start -n base -l DEBUG -o base.log`)
 - [X] the containers configuration file
 - [X] journalctl output from within the container

[container_creation.log](https://github.com/lxc/lxc/files/2364114/container_creation.log)
[dmesg.log](https://github.com/lxc/lxc/files/2364115/dmesg.log)
[base.log](https://github.com/lxc/lxc/files/2364117/base.log)
[config.txt](https://github.com/lxc/lxc/files/2364118/config.txt)
[journalctl.log](https://github.com/lxc/lxc/files/2364120/journalctl.log)

**Comment by graysky2** [comment]
It seems the problem lies with the created container using [lxc-templates](https://github.com/lxc/lxc-templates) ... If I go to my archive/system backup and pull out a container created before 08/02/2017 (this is the date on the backup but the container was create before this date), everything works as expected.  I updated the lxc to use the current Arch ARM packages (systemd, etc.) and it still works.

This container is called "obase" and here is the config and log:
[config.txt](https://github.com/lxc/lxc/files/2364138/config.txt)
[obase.log](https://github.com/lxc/lxc/files/2364139/obase.log)

Any thoughts are appreciated.

**Comment by Blub** [comment]
Perhaps some issue with the specific systemd-networkd version? Can you compare systemd versions between the archived one before and after the upgrade and the one that doesn't work?
