### ISSUE TITLE
How to move/copy lxc containers to lxd?

### ISSUE THREAD

**Issue by boblehue** [lxc/lxc#2583]
I wish there was a cookbook that covered how to move/copy containers from an old installation to a new ubuntu 18.04 installation. I have used many hours trying to figure out how to do it with no luck.

I'm running lxc on a fully up to date ubuntu 16.04 server and have a working lxd on ubuntu 18.04

I have looked in to the lxc-to-lxd script but can't fint it on my old installation, only on 18.04.
I also did this : https://stgraber.org/2016/04/12/lxd-2-0-remote-hosts-and-container-migration-612/
and managed to make a connection and create a container on the remote host, but it will reside in /var/lib/lxd/containers/ and my old contaniners reside in /var/lib/lxc/

I manage to copy a container to the new host with the migration aproach, but it would not start up an ended up in  error state.

Is there a way to move my existing containers in /var/lib/lxc/ to /var/lib/lxd/ and then copy them from the old host to the new one usinge Remote hosts and container migration aproach?
If so, is it a way to apply the profile on the new host to the container so it get network and storage (zfs) config that is configured to work on the ubuntu 18.04 installation.

I was also thinking of upgrading my 16.04 to 18.04 and try to move the containers, but there is not much information to tell me if that will break my existing lxc installation and leave my containers useless.

`lxc-start --version
2.0.8

lxc-checkconfig
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.4.0-134-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Warning: newuidmap is not setuid-root
Warning: newgidmap is not setuid-root
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: enabled
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

uname -a
Linux lxchost 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

cat /proc/self/cgroup
11:memory:/user/root/0
10:pids:/user.slice/user-1000.slice
9:perf_event:/
8:cpuset:/
7:cpu,cpuacct:/user.slice
6:devices:/user.slice
5:net_cls,net_prio:/
4:blkio:/user.slice
3:hugetlb:/
2:freezer:/user/root/0
1:name=systemd:/user/root/0

cat /proc/1/mounts
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=4046568k,nr_inodes=1011642,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=813536k,mode=755 0 0
/dev/sda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=32,pgrp=1,timeout=0,minproto=5,maxproto=5,direct 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,relatime 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
tmpfs /var/lib/lxd/shmounts tmpfs rw,relatime,size=100k,mode=711 0 0
tmpfs /var/lib/lxd/devlxd tmpfs rw,relatime,size=100k,mode=755 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=813536k,mode=700,uid=1000,gid=1000 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
`

**Comment by lorenzo93** [comment]
Same problem here, from Ubuntu 14.04 to 18.04.
@boblehue do you find a way to migrate them?

I just need to migrate lxc containers to lxd, I know how to move an lxd container to another host, but I don't know how to migrate them

**Comment by tomposmiko** [comment]
Assuming you're running lxc containers as root, also assuming you don't want to use lxc-to-lxd, only scripts from Ubuntu or you have customization, that makes your setup incompatible with that.
So basically you need a custom solution.

1. Create an lxd container. Make set 'security.privileged: true'. Stop-start-stop. So FS uids get shifted.
2. Replace the content of the lxd container's rootfs with the content of the lxc container's rootfs.
3. Start lxd, it should work properly.
4. Unset 'security.privileged'. Restart.

Don't forget to migrate special settings from the lxc configuration.

I didn't miss anything, that's it.

**Comment by stgraber** [comment]
`go get -v -x github.com/lxc/lxd/lxc-to-lxd` will get you lxc-to-lxd.

We have some plans to include it in the snap package but it's tricky due to the rather large system access it needs.

**Comment by ttbek** [comment]
Oh, and it would be nice if config file locations in the documentation 1) existed and 2) were correct when there.  Lots of documentation about the options, practically none about where to put them, and even the only place I found that (stgraber's 12 part article series), does not actually mention where they are stored, lxd just magics them from somewhere and writes them to that somewhere.  Maybe I'll just keep that container as LXC only forever since LXD still lacks critical documentation.  The only reason it was even created in LXC instead of LXD in the first place was because LXD was totally inscrutable to me.  It's still not clear several years later, are the configs written to the database?  var/lib/lxd/database/global sure doesn't exist on my system, so where is the database in 20.04?  find / -iname "LXD" didn't turn up anything useful except the default profile.
