### ISSUE TITLE
Why not delete the lock file?

### ISSUE THREAD

**Issue by lifeng68** [lxc/lxc#2587]
@brauner 
Hi, brauner, [lxclock](https://github.com/lxc/lxc/blob/master/src/lxc/lxclock.c) create a lock file for each container in function 'lxclock', but there are no functions to delete these lock files. 
So, when we delete the container, these files would be residual on the file system. 
I want to confirm whether this is a bug?

**Comment by Blub** [comment]
`unlink()` shouldn't hurt. The only issue you can run into is that when racing against someone currently starting up - they may have succeeded in reading the config and instantiating the lxccontainer but haven't yet opened the lock file, which would mean it gets recreated and would be independent of other already existing waiters. So the question is if that's an actual problem or expected to fail in some unknown way anyway.

**Comment by brauner** [comment]
PRs welcome but closing for now.
