### ISSUE TITLE
Have all C commands use the same code

### ISSUE THREAD

**Issue by stgraber** [lxc/lxc#259]
Currently, most C commands use arguments.c and the common parser, but there are a few that do their own things and so don't respect common options like --version, those should be converted to using the same argument parser as the rest.

**Comment by brauner** [comment]
Just saw this. I rewrote most of the executables to use the common parser. The trouble lies with C commands that use the options defined by LXC_COMMON_OPTIONS in a non-standard way. One example is lxc-clone which uses -n as the parameter for the new container, -P as the parameter for the new container path, and -o as the parameter for the old container while LXC_COMMON_OPTIONS defines -o as the parameter for logpriority and -n for the existing container name, and -P for the existing container path. A similar problem arises for lxc-config which uses the -l parameter to query the default settings for global config values while LXC_COMMON_OPTIONS uses -l as parameter for the logfile. I submitted a rewrite of lxc-clone which was reverted on the grounds of changing the command line options (see #621) and I can see why you would not like to change them but this makes rewriting them a bit more involved. What approach would you prefer in such cases?

1. Changing the command line options and carefully warning the user that the command line options for the executable have or will change?
2. Implement a new executable and fade out the old one (e.g. lxc-clone becomes lxc-copy) and instruct the user to move to the new executable?
3. Stick with the old executable?

**Comment by brauner** [comment]
All `LXC` commands that can sensibly make use of the common parser have now been switched.
