### ISSUE TITLE
Compilation fails with --disable-werror

### ISSUE THREAD

**Issue by ffontaine** [lxc/lxc#2592]
When building lxc with --disable-werror, gnu11 is not added in CLFAGS, moreover lxc does not add gnu99 so compilation fails on:
```
In file included from ./utils.h:48:0,
                 from cgroups/cgfsng.c:59:
cgroups/cgfsng.c: In function 'lxc_cpumask':
./macro.h:135:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
  for (char *__p = NULL, *__it = strtok_r(__splitme, __separators, &__p)
```

I would be happy to send a PR to add gnu99 if werror is disabled but I'm not sure that this is what is intended. Indeed, I found conflicting information on the minimum gcc version required by lxc:
 - In the commit message https://github.com/lxc/lxc/commit/81a56e8029e5c6815ed3ac9835a1d3822a22dae0, it is mentioned "We can't really support anything less than **gcc-4.8** anyway."
- But in this one https://github.com/lxc/lxc/commit/9b5724cd5808f45fd77edd6189a10f199d8f0153, it mentions gnu99 and forbids only **gcc version below 4.6 (excluded)**

**Comment by brauner** [comment]
The `compiler.h` header is the authority as to what gcc version we support. :)
And yes, please do send a patch to fix the disable case and add gnu11 to the cflags. Thanks!
