### ISSUE TITLE
Question: Hostname with network: none

### ISSUE THREAD

**Issue by tommyknows** [lxc/lxc#2605]
When launching a Docker Container with hostNetwork attached, it shares the host's Network Namespace. Thus, when running a privileged Container with hostNetwork attached, I am able to change the hostname of the host:
```
root@k8s-test:/home/ubuntu# hostnamectl
   Static hostname: k8s-test
         Icon name: computer-vm
[...]
root@k8s-test:/home/ubuntu# docker exec -ti d424bae80f07 /bin/sh
/ #
/ # hostname
k8s-test
/ # hostname test
/ # hostname
test
/ # exit
root@k8s-test:/home/ubuntu# hostnamectl
   Static hostname: k8s-test
Transient hostname: test
[...]
```

Now I'd expect the same behavior when using `lxc.net.[i].type: none`, as the documentation says:
> none: will cause the container to share the host's network namespace. This means the host network devices are usable in the container. [...]

However, I can't replicate the scenario described above.
Why is this?

Thanks

**Comment by brauner** [comment]
Just because you're sharing the network namespace doesn't mean you're sharing the uts namespace. If you want to have the exact same (and insane) behavior set:
```
lxc.namespace.keep = net uts
```

**Comment by brauner** [comment]
Insane in the sense that a container shouldn't mess with the host's uts. :)

**Comment by tommyknows** [comment]
It actually seems like Docker isn't doing that - as long as you don't tell it to.
It's Kubernetes that gives Docker the command to share the UTS Namespace of the Host when setting `hostNetwork: true`.

**Comment by tommyknows** [comment]
Don't know yet.
Asked this here: https://github.com/kubernetes/kubernetes/pull/68293
