### ISSUE TITLE
Error: LXD doesn't have a uid/gid allocation. In this mode, only privileged containers are supported.

### ISSUE THREAD

**Issue by Lampinen92** [lxc/lxc#2610]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution:
 * Distribution version:

 * The output of
   * `lxc-start --version`
3.0.1
   * `lxc-checkconfig`
Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/freezer
/sys/fs/cgroup/pids
/sys/fs/cgroup/devices
/sys/fs/cgroup/blkio
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/memory
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/rdma

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -a`
Linux drakenkatla 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
12:rdma:/
11:hugetlb:/
10:memory:/user/drakenkatla/0
9:perf_event:/
8:blkio:/user.slice
7:devices:/user.slice
6:pids:/user.slice/user-1000.slice/user@1000.service
5:freezer:/user/drakenkatla/0
4:cpu,cpuacct:/user.slice
3:cpuset:/
2:net_cls,net_prio:/
1:name=systemd:/user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
0::/user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
   * `cat /proc/1/mounts`

# Issue description

A brief description of what failed or what could be improved.
When i try to launch a container in lxc i get the. (lxc launch u1804v1 c1) Error: LXD doesn't have a uid/gid allocation. In this mode, only privileged containers are supported.
Its a fresh install. 
I have changed root to echo "root:1000000:65536" | sudo tee -a /etc/subuid /etc/subgid
As i have checked for solutions elsewhere i found something about the files 
    /proc/self/uid_map
    /proc/self/gid_map
    /proc/self/ns/user
And they are all there.
sudo lxd init are all set to default.

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
 - [ ] the containers configuration file

**Comment by brauner** [comment]
Sorry, can you file this issue against https://github.com/lxc/lxd, please?
