### ISSUE TITLE
Regression in lxc-copy -B btrfs

### ISSUE THREAD

**Issue by circulosmeos** [lxc/lxc#2612]
I think there is a new regression in Ubuntu 18.04.1 of this very same error: https://github.com/lxc/lxc/issues/2051

**Regression**

`lxc-copy -l DEBUG -B btrfs -n prueba -N test -s`

fails with error message,

    lxc-copy: prueba: storage/btrfs.c: btrfs_create_snapshot: 488 Failed to run "btrfs_snapshot_wrapper"
    lxc-copy: prueba: lxccontainer.c: copy_storage: 3449 Error copying storage.
    clone failed

**Steps to reproduce**

```
lxc-create -B btrfs -t download -n prueba -- -d ubuntu -r bionic -a amd64
lxc-copy -l DEBUG -B btrfs -n prueba -N test -s
```

**OS details**

regression **present** with;
-host & container: ubuntu-18.04.1 LTS
-kernel: 4.15.0-34-generic
-btrfs 4.15.1-1build1
-lxc 3.0.1-0ubuntu1~18.04.2

regression **not** present with Ubuntu 18.04 without upgrades:
-host & container: ubuntu-18.04 LTS
-kernel: 4.15.0-22-generic
-btrfs 4.15.1-1build1
-lxc 3.0.0-0ubuntu2

**verbose output**

[out.txt](https://github.com/lxc/lxc/files/2378750/out.txt)

**Comment by seesturm** [comment]
Problematic commit is probably 9de31d5a1394fd0bed495fa7cde5e625a1d64b48, line 331.

**Comment by circulosmeos** [comment]
Same issue as in https://github.com/lxc/lxc/issues/2655.

How much could this take to propagate to [lxc bionic Ubuntu package](https://packages.ubuntu.com/bionic/lxc)? 

Thanks all for your hard work !

**Comment by brauner** [comment]
//cc @stgraber will cherry-pick soon I think. :)

**Comment by Artanicus** [comment]
The issue is still present in 3.0.2-0ubuntu1~18.04.1. Is this version already meant to have the cherry-pick? The error is slightly different:
```
lxc-copy -n base_ubuntu_bionic_btrfs  -N base_test -l WARN
lxc-copy: base_ubuntu_bionic_btrfs: storage/btrfs.c: btrfs_create_snapshot: 530 Invalid cross-device link - Failed to create btrfs snapshot "/var/lib/lxc/base_test/rootfs" from "/usr/lib/x86_64-linux-gnu/lxc"
lxc-copy: base_ubuntu_bionic_btrfs: lxccontainer.c: copy_storage: 3571 Error copying storage.
lxc-copy: base_ubuntu_bionic_btrfs: tools/lxc_copy.c: do_clone: 369 Failed to clone
```

See the nonsensical /usr/lib/x86_64-linux-gnu/lxc path as the source of the snapshot.

**Comment by circulosmeos** [comment]
@Artanicus : no, it is not yet patched: you can see in the Ubuntu Changelog that it has date "Mon, 10 Sep 2018" and this patch is from 28 Sep.
_3.0.1-0ubuntu1~18.04.2_ is also not patched.
