### ISSUE TITLE
Network configuration of lxc container

### ISSUE THREAD

**Issue by ale9412** [lxc/lxc#2614]
I recently create a lxc container in a host with debian, stretch OS and the container with ubuntu, xenial and it brings up well, but once I change the **/var/lib/lxc/container_name/config** to config the container's network and remove the defalt `lxc.network.type = empty`, it does not start again instead it outputs this error:

_lxc-start 20180914094321.399 ERROR    lxc_conf - conf.c:instantiate_veth:2628 - failed to change mac address of host interface 'veth80YJSO': Permission denied
      lxc-start 20180914094321.418 ERROR    lxc_conf - conf.c:lxc_create_network:2962 - failed to create netdev
      lxc-start 20180914094321.418 ERROR    lxc_start - start.c:lxc_spawn:1088 - Failed to create the network.
      lxc-start 20180914094321.418 ERROR    lxc_start - start.c:__lxc_start:1346 - Failed to spawn container "Gauss".
      lxc-start 20180914094321.920 ERROR    lxc_start_ui - tools/lxc_start.c:main:366 - The container failed to start.
      lxc-start 20180914094321.920 ERROR    lxc_start_ui - tools/lxc_start.c:main:370 - Additional information can be obtained by setting the --logfile and --logpriority options._

I read a lot of places and nothing seems to work, please if somebody know this issue please let me know, I will appreciate the help, thank you

**Comment by brauner** [comment]
What does the container's config look like?

**Comment by brauner** [comment]
No response, closing.
