### ISSUE TITLE
lxc image copy command on remote repositories takes a lot of time to "initialise"

### ISSUE THREAD

**Issue by GavrielNsof** [lxc/lxc#2625]
# Issue description

lxc image copy command on remote repositories takes a lot of time to "initialise"
normally between 30 seconds to 2 minutes until it starts to download. 
(it just hangs)

# Steps to reproduce

1. lxc image copy ubuntu:d9f88b00dc5e local: --copy-aliases

# running the command with "--debug":
DBUG[09-20|12:02:43] Connecting to a remote simplestreams server
DBUG[09-20|12:02:43] Connecting to a local LXD over a Unix socket
DBUG[09-20|12:02:43] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
DBUG[09-20|12:02:43] Got response struct from LXD
DBUG[09-20|12:02:43]
	{
		"config": {},
		"api_extensions": [
			"storage_zfs_remove_snapshots",
			"container_host_shutdown_timeout",
			"container_stop_priority",
			"container_syscall_filtering",
			"auth_pki",
			"container_last_used_at",
			"etag",
			"patch",
			"usb_devices",
			"https_allowed_credentials",
			"image_compression_algorithm",
			"directory_manipulation",
			"container_cpu_time",
			"storage_zfs_use_refquota",
			"storage_lvm_mount_options",
			"network",
			"profile_usedby",
			"container_push",
			"container_exec_recording",
			"certificate_update",
			"container_exec_signal_handling",
			"gpu_devices",
			"container_image_properties",
			"migration_progress",
			"id_map",
			"network_firewall_filtering",
			"network_routes",
			"storage",
			"file_delete",
			"file_append",
			"network_dhcp_expiry",
			"storage_lvm_vg_rename",
			"storage_lvm_thinpool_rename",
			"network_vlan",
			"image_create_aliases",
			"container_stateless_copy",
			"container_only_migration",
			"storage_zfs_clone_copy",
			"unix_device_rename",
			"storage_lvm_use_thinpool",
			"storage_rsync_bwlimit",
			"network_vxlan_interface",
			"storage_btrfs_mount_options",
			"entity_description",
			"image_force_refresh",
			"storage_lvm_lv_resizing",
			"id_map_base",
			"file_symlinks",
			"container_push_target",
			"network_vlan_physical",
			"storage_images_delete",
			"container_edit_metadata",
			"container_snapshot_stateful_migration",
			"storage_driver_ceph",
			"storage_ceph_user_name",
			"resource_limits",
			"storage_volatile_initial_source",
			"storage_ceph_force_osd_reuse",
			"storage_block_filesystem_btrfs",
			"resources",
			"kernel_limits",
			"storage_api_volume_rename",
			"macaroon_authentication",
			"network_sriov",
			"console",
			"restrict_devlxd",
			"migration_pre_copy",
			"infiniband",
			"maas_network",
			"devlxd_events",
			"proxy",
			"network_dhcp_gateway",
			"file_get_symlink",
			"network_leases",
			"unix_device_hotplug",
			"storage_api_local_volume_handling",
			"operation_description",
			"clustering",
			"event_lifecycle",
			"storage_api_remote_volume_handling",
			"nvidia_runtime"
		],
		"api_status": "stable",
		"api_version": "1.0",
		"auth": "trusted",
		"public": false,
		"auth_methods": [
			"tls"
		],
		"environment": {
			"addresses": [],
			"architectures": [
				"x86_64",
				"i686"
			],
			"driver": "lxc",
			"driver_version": "3.0.1",
			"kernel": "Linux",
			"kernel_architecture": "x86_64",
			"kernel_version": "4.15.0-34-generic",
			"server": "lxd",
			"server_pid": 1885,
			"server_version": "3.0.1",
			"storage": "dir",
			"storage_version": "1",
			"server_clustered": false,
			"server_name": "hkg-hv-001-01.stg1.nsof.io"
		}
	}

*** **Hangs for some time** ***

DBUG[09-20|12:03:58] Connected to the websocket
DBUG[09-20|12:03:58] Sending request to LXD                   etag= method=POST url=http://unix.socket/1.0/images
DBUG[09-20|12:03:58]
	{
		"auto_update": false,
		"properties": null,
		"public": false,
		"filename": "",
		"source": {
			"alias": "",
			"certificate": "",
			"protocol": "simplestreams",
			"server": "https://cloud-images.ubuntu.com/releases",
			"mode": "pull",
			"type": "image",
			"url": "",
			"name": "",
			"fingerprint": "d9f88b00dc5e810519e4360590e19ecdf9de8da781f245d0eaa0fa7ff21976dd",
			"secret": ""
		},
		"compression_algorithm": "",
		"aliases": null
	}
DBUG[09-20|12:03:58] Got operation from LXD
DBUG[09-20|12:03:58]
	{
		"id": "880fbe1b-9e91-460c-bac5-a7553d956a26",
		"class": "task",
		"description": "Downloading image",
		"created_at": "2018-09-20T12:03:58.112683744Z",
		"updated_at": "2018-09-20T12:03:58.112683744Z",
		"status": "Running",
		"status_code": 103,
		"resources": null,
		"metadata": null,
		"may_cancel": false,
		"err": ""
	}
DBUG[09-20|12:03:58] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0/operations/880fbe1b-9e91-460c-bac5-a7553d956a26
DBUG[09-20|12:03:58] Got response struct from LXD
DBUG[09-20|12:03:58]
	{
		"id": "880fbe1b-9e91-460c-bac5-a7553d956a26",
		"class": "task",
		"description": "Downloading image",
		"created_at": "2018-09-20T12:03:58.112683744Z",
		"updated_at": "2018-09-20T12:03:58.112683744Z",
		"status": "Running",
		"status_code": 103,
		"resources": null,
		"metadata": null,
		"may_cancel": false,
		"err": ""
	}

# More Info:
Ubunut 16.04- 4.15.0-34-generic
lxc --version = 3.0.1

cat /proc/self/cgroup
12:blkio:/user.slice
11:hugetlb:/
10:cpuset:/
9:pids:/user.slice/user-1000.slice
8:freezer:/
7:rdma:/
6:devices:/user.slice
5:memory:/user.slice
4:perf_event:/
3:net_cls,net_prio:/
2:cpu,cpuacct:/user.slice
1:name=systemd:/user.slice/user-1000.slice/session-844.scope

**Comment by brauner** [comment]
Sorry, this is the wrong repo. Can you please file this issue against https://github.com/lxc/lxd ? :)

**Comment by GavrielNsof** [comment]
My bad! will do

**Comment by brauner** [comment]
No problem at all. The distinction can be confusing. :) For future reference: LXD == the daemon that uses LXC == the shared library to run containers. :)
