### ISSUE TITLE
Segmentation fault - lxc-3.0.2 build on Debian Stretch

### ISSUE THREAD

**Issue by 481wgxoy4** [lxc/lxc#2651]
# Required information

 * Distribution: Debian
 * Distribution version: Stretch

* lxc-start --version / lxc-create --version
2.0.7
* [lxc-checkconfig.txt](https://github.com/lxc/lxc/files/2420929/lxc-checkconfig.txt)
* [/proc/1/mounts.txt](https://github.com/lxc/lxc/files/2420933/proc_1_mounts.txt)
* [/proc/self/cgroup.txt](https://github.com/lxc/lxc/files/2420934/proc_self_cgroup.txt)
* uname -a
`Linux teststation 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux`

# Issue description

`sudo lxc-create -t download -n test` returns "Error creating container test".
`sudo lxc-create -t download -n test --logfile log.txt --logpriority DEBUG` returns "Segmentation fault".
But when running the binary in lxc/src/lxc it does work properly.
`sudo ./lxc/src/lxc/lxc-create ...`

# Steps to reproduce
* fresh Debian installation

* `sudo apt install debootstrap bridge-utils dirmngr dns-root-data dnsmasq-base liblxc1 libpam-cgfs lxcfs python3-lxc rsync uidmap pkg-config build-essential libcap-dev libtool git bridge-utils autoconf`

* `git clone https://github.com/lxc/lxc`

* `cd lxc`

* `git checkout lxc-3.0.2`

* `./autogen.sh && ./configure && make && sudo make install`

* `sudo lxc-create -t download -n test --logfile log.txt --logpriority DEBUG`

# Information to attach

* [build.log](https://github.com/lxc/lxc/files/2420788/build.log)
* `sudo lxc-create -t download -n test --logfile log.txt --logpriority DEBUG` does not create the log.txt file.

**Comment by 481wgxoy4** [comment]
It seems like I found the solution by looking into the rules file within the source package of lxc (version 3.0.1) in Ubuntu [lxc_3.0.1-0ubuntu1~18.04.2.debian.tar.xz](http://archive.ubuntu.com/ubuntu/pool/main/l/lxc/lxc_3.0.1-0ubuntu1~18.04.2.debian.tar.xz)

The Ubuntu package uses the following configuration parameters:
`DEB_HOST_MULTIARCH ?= $(shell dpkg-architecture -qDEB_HOST_MULTIARCH)`
`dh_auto_configure -- --libdir=\$${prefix}/lib/$(DEB_HOST_MULTIARCH) \
		--libexecdir=\$${prefix}/lib/$(DEB_HOST_MULTIARCH) \
		--with-rootfs-path=\$${prefix}/lib/$(DEB_HOST_MULTIARCH)/lxc \
		$(shell dpkg-buildflags --export=configure) \
		--enable-doc --disable-rpath --with-distro=ubuntu --enable-pam`

`dpkg-architecture -qDEB_HOST_MULTIARCH` returns `x86_64-linux-gnu`

According to `./configure --help` the defaults are the following:
--prefix=/usr/local
--libdir=/usr/local/lib
--libexecdir=/usr/local/libexec

But Ubuntu and Debian both require:
--prefix=/usr
--libdir=/usr/lib/x86_64-linux-gnu
--libexecdir=/usr/lib/x86_64-linux-gnu
--with-rootfs-path=/usr/lib/x86_64-linux-gnu/lxc

I had to set the prefix to /usr instead of /usr/local to get this working. The directory /usr/lib/x86_64-linux-gnu exists /usr/local/lib/x86_64-linux-gnu does not.

Why is this not automatically detected?

Interestingly the rule file within the source package of lxc (version 2.0.7) in Debian [lxc_2.0.7-2+deb9u2.debian.tar.xz](http://http.debian.net/debian/pool/main/l/lxc/lxc_2.0.7-2+deb9u2.debian.tar.xz) does not set any of the paths above.

**Comment by cyberwillis** [comment]
Hi ... I build almost each commit but for Ubuntu and I don't need to configure all this flags. 
```
./autogen.sh
./configure --enable-pam
make -j12
make install
```
