### ISSUE TITLE
Bug/Feature Request: Unable to delete container when storage pool is missing

### ISSUE THREAD

**Issue by mlaradji** [lxc/lxc#2654]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.1 LTS
 * LXD Snap Version: 3.5, Revision 8882, Publisher: canonical
 * None of the following outputs are available on my system:
   * `lxc-start --version`: 
   * `lxc-checkconfig`
   * `uname -a`
   * `cat /proc/self/cgroup`
   * `cat /proc/1/mounts`

# Issue description

There was a `btrfs` storage pool named `local` and with source `/var/lib/lxd/disks/local.img`. It used to work perfectly fine, until the file `/var/lib/lxd/disks/local.img` was deleted outside of LXC (cannot be recovered). It is used by 5 containers, and the storage pool and the containers appear in the output of `lxc storage list` and `lxc list`, respectively. Now, none of the storage pool `local` or its associated containers can be deleted in LXC.

Executing `lxc delete container1` outputs `Error: no such file or directory`. Using the `--force` flag does not change the output. There doesn't seem to be any way to remove `container1` from LXC. This, I believe, is a bug or is at least undesirable behavior. Perhaps the only real negative effect is that it limits the namespace for new containers and storage pools.

Executing  `lxc storage delete local` outputs: `Error: storage pool "local" has volumes attached to it`.

Executing `lxc storage volume list local` outputs:
```
+-----------+-----------+-------------+---------+
|   TYPE    |   NAME    | DESCRIPTION | USED BY |
+-----------+-----------+-------------+---------+
| container | container1   |             | 1       |
+-----------+-----------+-------------+---------+
| container | container2    |             | 1       |
+-----------+-----------+-------------+---------+
| container | container3 |             | 1       |
+-----------+-----------+-------------+---------+
| container | container4    |             | 1       |
+-----------+-----------+-------------+---------+
| container | container5  |             | 1       |
+-----------+-----------+-------------+---------+
```
The container storage volumes cannot be deleted outside of `lxc delete`: executing `lxc storage volume delete local container/container1` outputs `Error: storage volumes of type "container" cannot be deleted with the storage api`. 

# Steps to reproduce

 1. Create a `btrfs` storage pool with an image file as a source.
 2. Create a container in that storage pool.
 3. Delete the source image file outside of LXC, for example using `bash`.
 4. Attempt to delete the container or storage pool in LXC.

# Desired behaviour

I think that, perhaps through a `--delete_from_db` flag, LXC could offer an option to remove any references to a container/storage pool from the LXC database.

**Comment by brauner** [comment]
This needs to be filed against https://github.com/lxc/lxd :)
