### ISSUE TITLE
Random close 1006 errors of - lxc exec cname bash

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxc#2660]
Several times daily containers throw...
```
Error: websocket: close 1006 (abnormal closure): unexpected EOF
```
Which closes all shell processes attached to containers + kill off any related tty processes.

If there's something I can do to fix this, let me know.

Thanks.

All containers running Ubuntu Bionic + all updates.

Machine level runtime environment is latest... everything... 
```
net14 # lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
# All Ubuntu updates applied

net14 # snap refresh
All snaps up to date.

net14 # snap list
Name  Version  Rev   Tracking  Publisher   Notes
core  16-2.35  5328  stable    canonical*  core
lxd   3.5      8904  stable    canonical*  -
```

**Comment by stgraber** [comment]
@davidfavor Not sure about several times a day, but this would certainly happen whenever the snap refreshes and we've pushed 3 updates to stable over the past 48h.

Run `snap changes` and look at the last refresh, if that lines up with the last disconnect, then it's unfortunately normal behavior.

**Comment by stgraber** [comment]
If that's the issue, there are options to configure a preferred time for snap refreshes, making it less likely to hit during your work day:

https://snapdocs.labix.org/configuration-options/87

**Comment by davidfavor** [comment]
Ah... Likely this explains what I'm seeing...

I'll close this out for now + if I see this recur, I'll reopen the issue.

Thanks!

**Comment by stgraber** [comment]
No worries, we've been pretty aggressive on fix backports lately for our stable users, trying to save people from having to wait days/weeks for the next stable release, it's pretty cheap bandwidth wise thanks to delta updates, but it does have the annoying side effect of killing any existing exec session.
