### ISSUE TITLE
 Failed to create the configured network 

### ISSUE THREAD

**Issue by MrChenA** [lxc/lxc#2678]
* Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of
   * `lxc-start --version` 2.0.0
   * `lxc-checkconfig`
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.8.0-36-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: missing

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: enabled
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

   * `uname -a`
Linux VM 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:41 UTC 2017 i686 i686 i686 GNU/Linux
   * `cat /proc/self/cgroup`
11:cpuset:/
10:perf_event:/
9:pids:/user.slice/user-1000.slice
8:freezer:/user/seed/1
7:memory:/user/seed/1
6:devices:/user.slice
5:net_cls,net_prio:/
4:blkio:/user.slice
3:cpu,cpuacct:/user.slice
2:hugetlb:/
1:name=systemd:/user.slice/user-1000.slice/session-c1.scope

   * `cat /proc/1/mounts`
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=1010596k,nr_inodes=209392,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=206036k,mode=755 0 0
/dev/sda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs rw,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb,release_agent=/run/cgmanager/agents/cgm-release-agent.hugetlb 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids,release_agent=/run/cgmanager/agents/cgm-release-agent.pids 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event,release_agent=/run/cgmanager/agents/cgm-release-agent.perf_event 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=24,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=11831 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
cgmfs /run/cgmanager/fs tmpfs rw,relatime,size=100k,mode=755 0 0
tmpfs /run/lxcfs/controllers tmpfs rw,relatime,size=100k,mode=700 0 0
cpuset /run/lxcfs/controllers/cpuset cgroup rw,relatime,cpuset,clone_children 0 0
perf_event /run/lxcfs/controllers/perf_event cgroup rw,relatime,perf_event,release_agent=/run/cgmanager/agents/cgm-release-agent.perf_event 0 0
pids /run/lxcfs/controllers/pids cgroup rw,relatime,pids,release_agent=/run/cgmanager/agents/cgm-release-agent.pids 0 0
freezer /run/lxcfs/controllers/freezer cgroup rw,relatime,freezer 0 0
memory /run/lxcfs/controllers/memory cgroup rw,relatime,memory 0 0
devices /run/lxcfs/controllers/devices cgroup rw,relatime,devices 0 0
net_cls,net_prio /run/lxcfs/controllers/net_cls,net_prio cgroup rw,relatime,net_cls,net_prio 0 0
blkio /run/lxcfs/controllers/blkio cgroup rw,relatime,blkio 0 0
cpu,cpuacct /run/lxcfs/controllers/cpu,cpuacct cgroup rw,relatime,cpu,cpuacct 0 0
hugetlb /run/lxcfs/controllers/hugetlb cgroup rw,relatime,hugetlb,release_agent=/run/cgmanager/agents/cgm-release-agent.hugetlb 0 0
name=systemd /run/lxcfs/controllers/name=systemd cgroup rw,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=206036k,mode=700,uid=1000,gid=1000 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
vmware-vmblock /run/vmblock-fuse fuse.vmware-vmblock rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other 0 0

# Issue description
When I use the command 'lxc-start -n test -d' to start the container,I encounter an error. Like that:

   

>   **lxc-start 20181008100742.546 ERROR    lxc_start - start.c:lxc_spawn:1163 - failed to create the configured network
>       lxc-start 20181008100742.546 ERROR    lxc_start - start.c:__lxc_start:1329 - failed to spawn 'test'
>       lxc-start 20181008100748.066 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
>       lxc-start 20181008100748.068 ERROR    lxc_start_ui - lxc_start.c:main:346 - To get more details, run the container in foreground mode.
>       lxc-start 20181008100748.068 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.**

the file in ~/.config/lxc/default.conf
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
#lxc.network.hwaddr = 00:16:3e:xx:xx:xx
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536

**Comment by brauner** [comment]
Can you start the container with `-l trace -o container.log` and provide the `container.log` file here?

**Comment by MrChenA** [comment]
lxc-start 20181011094621.951 INFO     lxc_start_ui - lxc_start.c:main:264 - using rcfile /home/seed/.local/share/lxc/test/config
      lxc-start 20181011094621.998 WARN     lxc_confile - confile.c:config_pivotdir:1877 - lxc.pivotdir is ignored.  It will soon become an error.
      lxc-start 20181011094622.000 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 100000 range 65536
      lxc-start 20181011094622.000 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 100000 range 65536
      lxc-start 20181011094622.000 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 4
      lxc-start 20181011094622.012 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:797 - Attempting to set proc title to [lxc monitor] /home/seed/.local/share/lxc test
      lxc-start 20181011094622.013 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
      lxc-start 20181011094622.013 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 4
      lxc-start 20181011094622.016 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/edec1d338e7d805b//home/seed/.local/share/lxc
      lxc-start 20181011094622.020 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
      lxc-start 20181011094622.020 INFO     lxc_seccomp - seccomp.c:parse_config_v2:436 - Adding native rule for reject_force_umount action 0
      lxc-start 20181011094622.020 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

      lxc-start 20181011094622.020 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .[all].
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .kexec_load errno 1.
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:436 - Adding native rule for kexec_load action 327681
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .open_by_handle_at errno 1.
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:436 - Adding native rule for open_by_handle_at action 327681
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .init_module errno 1.
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:436 - Adding native rule for init_module action 327681
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .finit_module errno 1.
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:436 - Adding native rule for finit_module action 327681
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .delete_module errno 1.
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:436 - Adding native rule for delete_module action 327681
      lxc-start 20181011094622.021 DEBUG    lxc_start - start.c:setup_signal_fd:289 - sigchild handler set
      lxc-start 20181011094622.021 DEBUG    lxc_console - console.c:lxc_console_peer_default:473 - no console peer
      lxc-start 20181011094622.040 INFO     lxc_start - start.c:lxc_init:488 - 'test' is initialized
      lxc-start 20181011094622.041 DEBUG    lxc_start - start.c:__lxc_start:1302 - Not dropping cap_sys_boot or watching utmp
      lxc-start 20181011094622.041 INFO     lxc_start - start.c:resolve_clone_flags:999 - Cloning a new user namespace
      lxc-start 20181011094622.041 INFO     lxc_cgroup - cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for test
      lxc-start 20181011094622.085 ERROR    lxc_start - start.c:lxc_spawn:1163 - failed to create the configured network
      lxc-start 20181011094622.085 ERROR    lxc_start - start.c:__lxc_start:1329 - failed to spawn 'test'
      lxc-start 20181011094622.085 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'test', config section 'lxc'
      lxc-start 20181011094622.603 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
      lxc-start 20181011094627.609 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
  lxc-start 20181011094627.611 ERROR    lxc_start_ui - lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 20181011094627.611 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.

**Comment by MrChenA** [comment]
```

lxc-start 20181011094621.951 INFO     lxc_start_ui - lxc_start.c:main:264 - using rcfile /home/seed/.local/share/lxc/test/config
      lxc-start 20181011094621.998 WARN     lxc_confile - confile.c:config_pivotdir:1877 - lxc.pivotdir is ignored.  It will soon become an error.
      lxc-start 20181011094622.000 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 100000 range 65536
      lxc-start 20181011094622.000 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 100000 range 65536
      lxc-start 20181011094622.000 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 4
      lxc-start 20181011094622.012 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:797 - Attempting to set proc title to [lxc monitor] /home/seed/.local/share/lxc test
      lxc-start 20181011094622.013 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
      lxc-start 20181011094622.013 INFO     lxc_start - start.c:lxc_check_inherited:251 - closed inherited fd 4
      lxc-start 20181011094622.016 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/edec1d338e7d805b//home/seed/.local/share/lxc
      lxc-start 20181011094622.020 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
      lxc-start 20181011094622.020 INFO     lxc_seccomp - seccomp.c:parse_config_v2:436 - Adding native rule for reject_force_umount action 0
      lxc-start 20181011094622.020 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

      lxc-start 20181011094622.020 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .[all].
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .kexec_load errno 1.
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:436 - Adding native rule for kexec_load action 327681
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .open_by_handle_at errno 1.
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:436 - Adding native rule for open_by_handle_at action 327681
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .init_module errno 1.
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:436 - Adding native rule for init_module action 327681
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .finit_module errno 1.
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:436 - Adding native rule for finit_module action 327681
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .delete_module errno 1.
      lxc-start 20181011094622.021 INFO     lxc_seccomp - seccomp.c:parse_config_v2:436 - Adding native rule for delete_module action 327681
      lxc-start 20181011094622.021 DEBUG    lxc_start - start.c:setup_signal_fd:289 - sigchild handler set
      lxc-start 20181011094622.021 DEBUG    lxc_console - console.c:lxc_console_peer_default:473 - no console peer
      lxc-start 20181011094622.040 INFO     lxc_start - start.c:lxc_init:488 - 'test' is initialized
      lxc-start 20181011094622.041 DEBUG    lxc_start - start.c:__lxc_start:1302 - Not dropping cap_sys_boot or watching utmp
      lxc-start 20181011094622.041 INFO     lxc_start - start.c:resolve_clone_flags:999 - Cloning a new user namespace
      lxc-start 20181011094622.041 INFO     lxc_cgroup - cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for test
      lxc-start 20181011094622.085 ERROR    lxc_start - start.c:lxc_spawn:1163 - failed to create the configured network
      lxc-start 20181011094622.085 ERROR    lxc_start - start.c:__lxc_start:1329 - failed to spawn 'test'
      lxc-start 20181011094622.085 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'test', config section 'lxc'
      lxc-start 20181011094622.603 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
      lxc-start 20181011094627.609 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
      lxc-start 20181011094627.611 ERROR    lxc_start_ui - lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 20181011094627.611 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.

```

**Comment by MrChenA** [comment]
who can help me solve the problem??please!!

**Comment by MrChenA** [comment]
wow！

**Comment by brauner** [comment]
Can you show me the output of `ip addr` on the host please?
And the output of `ls -al /usr/share/lxc` please?

**Comment by MrChenA** [comment]
ens33     Link encap:Ethernet  HWaddr 00:0c:29:85:18:27  
          inet addr:192.168.93.129  Bcast:192.168.93.255  Mask:255.255.255.0
          inet6 addr: fe80::b965:3932:5b44:353/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:133 errors:0 dropped:0 overruns:0 frame:0
          TX packets:143 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:56497 (56.4 KB)  TX bytes:13762 (13.7 KB)
          Interrupt:19 Base address:0x2000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:92 errors:0 dropped:0 overruns:0 frame:0
          TX packets:92 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:31068 (31.0 KB)  TX bytes:31068 (31.0 KB)

total 40
drwxr-xr-x   6 root root  4096 Oct  6 11:43 .
drwxr-xr-x 335 root root 12288 Oct  7 15:14 ..
drwxr-xr-x   3 root root  4096 Oct  6 11:43 config
drwxr-xr-x   2 root root  4096 Oct  6 11:43 hooks
-rw-r--r--   1 root root  1107 Apr 19  2016 lxc.functions
-rw-r--r--   1 root root  1870 Apr 19  2016 lxc-patch.py
drwxr-xr-x   2 root root  4096 Oct  6 11:43 selinux
drwxr-xr-x   2 root root  4096 Oct  6 11:43 templates

**Comment by brauner** [comment]
And `ls -al /usr/lib/lxc` please.

**Comment by MrChenA** [comment]
this is result of ls -al /usr/lib/lxc

drwxr-xr-x 6 root root 4096 Oct 6 11:43 .
drwxr-xr-x 335 root root 12288 Oct 7 15:14 ..
drwxr-xr-x 3 root root 4096 Oct 6 11:43 config
drwxr-xr-x 2 root root 4096 Oct 6 11:43 hooks
-rw-r--r-- 1 root root 1107 Apr 19 2016 lxc.functions
-rw-r--r-- 1 root root 1870 Apr 19 2016 lxc-patch.py
drwxr-xr-x 2 root root 4096 Oct 6 11:43 selinux
drwxr-xr-x 2 root root 4096 Oct 6 11:43 templates

**Comment by brauner** [comment]
Two problems why it doesn't work:
- you're trying to attach a new network interface to the bridge `lxcbr0` but the bridge doesn't exist.
- LXC tries to call `lxc-user-nic` binary but it doesn't seem to exist.

**Comment by brauner** [comment]
Why is your output of `/usr/share/lxc` and `/usr/lib/lxc` identical? That seems weird did you give me the output of the correct path?

**Comment by MrChenA** [comment]
Ok,I'll check it.

**Comment by MrChenA** [comment]
I run it in my VMware.

**Comment by MrChenA** [comment]
```
[10/14/18]seed@VM:~$ ls -al /usr/share/lxc
total 40
drwxr-xr-x   6 root root  4096 Oct  6 11:43 .
drwxr-xr-x 335 root root 12288 Oct  7 15:14 ..
drwxr-xr-x   3 root root  4096 Oct  6 11:43 config
drwxr-xr-x   2 root root  4096 Oct  6 11:43 hooks
-rw-r--r--   1 root root  1107 Apr 19  2016 lxc.functions
-rw-r--r--   1 root root  1870 Apr 19  2016 lxc-patch.py
drwxr-xr-x   2 root root  4096 Oct  6 11:43 selinux
drwxr-xr-x   2 root root  4096 Oct  6 11:43 templates
```

**Comment by MrChenA** [comment]
```
[10/14/18]seed@VM:~$ ls -al /usr/lib/lxc
ls: cannot access '/usr/lib/lxc': No such file or directory
```
I don't have the path

**Comment by MrChenA** [comment]
thanks for your help,i have solved it by changing a new vm os.

**Comment by brauner** [comment]
Ok, closing then.
