### ISSUE TITLE
lxc 3.0.1: lxc-destroy failed when the container in a system boot in nfs rootfs

### ISSUE THREAD

**Issue by Mingli-Yu** [lxc/lxc#2704]
# lxc-destroy -n test9
lxc-destroy: test9: utils.c: _recursive_rmdir: 149 Failed to delete /var/lib/lxc/test9
lxc-destroy: test9: lxccontainer.c: container_destroy: 2946 Failed to destroy directory "/var/lib/lxc/test9" for "test9"
Destroying test9 failed

BTW the system boot in nfs rootfs as below:
  # cat /proc/cmdline
root=/dev/nfs nfsroot=192.168.10.1:/export/test/rootfs rw ip=dhcp
If boot the system in local hard disk, no above issue.

**Comment by brauner** [comment]
Can you please do:
```
lxc-destroy test9 -l trace -o test9.log
```
and show me the output of `test9.log?

**Comment by Mingli-Yu** [comment]
Below is the output of test9.log.(BTW, lxc-destroy works well in lxc 2.0.8, but has issue in lxc 3.0.1)

lxc-destroy test9 20181022020433.463 TRACE    lxc_commands - commands.c:lxc_cmd:311 - Connection refused - Command "get_init_pid" failed to connect command socket
lxc-destroy test9 20181022020433.467 TRACE    lxc_commands - commands.c:lxc_cmd:311 - Connection refused - Command "get_state" failed to connect command socket
lxc-destroy test9 20181022020433.470 TRACE    lxc_commands - commands.c:lxc_cmd:311 - Connection refused - Command "get_state" failed to connect command socket
lxc-destroy test9 20181022020433.470 DEBUG    storage - storage.c:get_storage_by_name:225 - Detected rootfs type "dir"
lxc-destroy test9 20181022020433.736 INFO     lxc_container - lxccontainer.c:container_destroy:2885 - Destroyed rootfs for test9
lxc-destroy test9 20181022020433.744 ERROR    lxc_utils - utils.c:_recursive_rmdir:149 - Failed to delete /var/lib/lxc/test9
lxc-destroy test9 20181022020433.746 ERROR    lxc_container - lxccontainer.c:container_destroy:2946 - Failed to destroy directory "/var/lib/lxc/test9" for "test9"

**Comment by sandy-lcq** [comment]
send the test9.log as below on behalf of Mingli-Yu.
lxc-destroy test9 20181022020433.463 TRACE    lxc_commands - commands.c:lxc_cmd:311 - Connection refused - Command "get_init_pid" failed to connect command socket
lxc-destroy test9 20181022020433.467 TRACE    lxc_commands - commands.c:lxc_cmd:311 - Connection refused - Command "get_state" failed to connect command socket
lxc-destroy test9 20181022020433.470 TRACE    lxc_commands - commands.c:lxc_cmd:311 - Connection refused - Command "get_state" failed to connect command socket
lxc-destroy test9 20181022020433.470 DEBUG    storage - storage.c:get_storage_by_name:225 - Detected rootfs type "dir"
lxc-destroy test9 20181022020433.736 INFO     lxc_container - lxccontainer.c:container_destroy:2885 - Destroyed rootfs for test9
lxc-destroy test9 20181022020433.744 ERROR    lxc_utils - utils.c:_recursive_rmdir:149 - Failed to delete /var/lib/lxc/test9
lxc-destroy test9 20181022020433.746 ERROR    lxc_container - lxccontainer.c:container_destroy:2946 - Failed to destroy directory "/var/lib/lxc/test9" for "test9"

**Comment by Mingli-Yu** [comment]
BTW,  the issue gone once upgrade lxc to 3.0.2.
