### ISSUE TITLE
network interface does not return to host when container failed to start

### ISSUE THREAD

**Issue by ludwig-gramberg** [lxc/lxc#2733]
when using lxc.network.type = phys the network is not returned to the host when the container fails to start. Is there a way to get the interface back to the host or is a reboot of the host the only option? And is this a bug or intentional?

how to reproduce:

start container with:
```
lxc.network.type = phys
lxc.network.link = ens001
lxc.network.name = eth0
lxc.network.flags = up 
```
and a mount-point that doesnt exist:
```
lxc.mount.entry = /mnt/something /var/lib/lxc/my-container/rootfs/mnt/doesnotexist none bind 0 0
```

the container fails to start but lxc claimed the interface. after removing the mount point the container still wont start because the host does not have the interface any more.

OS: debian 9
lxc: 1:2.0.7-2+deb9u2

**Comment by brauner** [comment]
LXC will now take care to restore to the correct, old name.
