### ISSUE TITLE
lxc-ls doesn't show containers (but `lxc ls` does)

### ISSUE THREAD

**Issue by dinomite** [lxc/lxc#2734]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of
   * `lxc-start --version`

    3.0.2

   * `lxc-checkconfig`

    Kernel configuration not found at /proc/config.gz; searching...
    Kernel configuration found at /boot/config-4.15.0-34-generic
    --- Namespaces ---
    Namespaces: enabled
    Utsname namespace: enabled
    Ipc namespace: enabled
    Pid namespace: enabled
    User namespace: enabled
    Network namespace: enabled

    --- Control groups ---
    Cgroups: enabled

    Cgroup v1 mount points: 
    /sys/fs/cgroup/systemd
    /sys/fs/cgroup/net_cls,net_prio
    /sys/fs/cgroup/freezer
    /sys/fs/cgroup/cpuset
    /sys/fs/cgroup/devices
    /sys/fs/cgroup/hugetlb
    /sys/fs/cgroup/rdma
    /sys/fs/cgroup/blkio
    /sys/fs/cgroup/cpu,cpuacct
    /sys/fs/cgroup/perf_event
    /sys/fs/cgroup/pids
    /sys/fs/cgroup/memory

    Cgroup v2 mount points: 
    /sys/fs/cgroup/unified

    Cgroup v1 clone_children flag: enabled
    Cgroup device: enabled
    Cgroup sched: enabled
    Cgroup cpu account: enabled
    Cgroup memory controller: enabled
    Cgroup cpuset: enabled

    --- Misc ---
    Veth pair device: enabled, loaded
    Macvlan: enabled, not loaded
    Vlan: enabled, not loaded
    Bridges: enabled, loaded
    Advanced netfilter: enabled, not loaded
    CONFIG_NF_NAT_IPV4: enabled, loaded
    CONFIG_NF_NAT_IPV6: enabled, loaded
    CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
    CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, loaded
    CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
    CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, loaded
    FUSE (for use with lxcfs): enabled, not loaded

    --- Checkpoint/Restore ---
    checkpoint restore: enabled
    CONFIG_FHANDLE: enabled
    CONFIG_EVENTFD: enabled
    CONFIG_EPOLL: enabled
    CONFIG_UNIX_DIAG: enabled
    CONFIG_INET_DIAG: enabled
    CONFIG_PACKET_DIAG: enabled
    CONFIG_NETLINK_DIAG: enabled
    File capabilities: 

    Note : Before booting a new kernel, you can check its configuration
    usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -a`

    Linux didius 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

   * `cat /proc/self/cgroup`

    12:memory:/user.slice
    11:pids:/user.slice/user-1000.slice/session-16715.scope
    10:perf_event:/
    9:cpu,cpuacct:/user.slice
    8:blkio:/user.slice
    7:rdma:/
    6:hugetlb:/
    5:devices:/user.slice
    4:cpuset:/
    3:freezer:/
    2:net_cls,net_prio:/
    1:name=systemd:/user.slice/user-1000.slice/session-16715.scope
    0::/user.slice/user-1000.slice/session-16715.scope

   * `cat /proc/1/mounts`

    sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
    proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
    udev /dev devtmpfs rw,nosuid,relatime,size=4016872k,nr_inodes=1004218,mode=755 0 0
    devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
    tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=809492k,mode=755 0 0
    /dev/sdc2 / ext4 rw,relatime,discard,data=ordered 0 0
    securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
    tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
    tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
    tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
    cgroup /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
    cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
    pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
    efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
    cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
    cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
    cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
    cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
    cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
    cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
    cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
    cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
    cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
    cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
    cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
    systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=26,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=16572 0 0
    mqueue /dev/mqueue mqueue rw,relatime 0 0
    hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
    debugfs /sys/kernel/debug debugfs rw,relatime 0 0
    fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
    configfs /sys/kernel/config configfs rw,relatime 0 0
    /dev/loop4 /snap/canonical-livepatch/42 squashfs ro,nodev,relatime 0 0
    /dev/sdc1 /boot/efi vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro 0 0
    /dev/md0 /mnt/pescennius ext4 rw,relatime,data=ordered 0 0
    lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
    tmpfs /run/snapd/ns tmpfs rw,nosuid,noexec,relatime,size=809492k,mode=755 0 0
    tmpfs /var/lib/lxd/shmounts tmpfs rw,relatime,size=100k,mode=711 0 0
    tmpfs /var/lib/lxd/devlxd tmpfs rw,relatime,size=100k,mode=755 0 0
    binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
    tracefs /sys/kernel/debug/tracing tracefs rw,relatime 0 0
    /dev/loop5 /snap/canonical-livepatch/49 squashfs ro,nodev,relatime 0 0
    nsfs /run/snapd/ns/canonical-livepatch.mnt nsfs rw 0 0
    /dev/loop0 /snap/canonical-livepatch/50 squashfs ro,nodev,relatime 0 0
    /dev/loop2 /snap/core/5662 squashfs ro,nodev,relatime 0 0
    /dev/loop3 /snap/core/5742 squashfs ro,nodev,relatime 0 0
    tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=809492k,mode=700,uid=1000,gid=1004 0 0
    /dev/md0 /var/lib/lxd/devices/unifi-video/disk.nvr-disk.mnt-unifi ext4 rw,relatime,data=ordered 0 0
    /dev/loop1 /snap/core/5897 squashfs ro,nodev,relatime 0 0
    /dev/sdc2 /var/lib/lxd/devices/nginx/disk.munin-dir.mnt-munin-www ext4 rw,relatime,discard,data=ordered 0 0

# Issue description

`lxc-ls`, provided by the `lxc-utils` package on Ubuntu produces no output.

    didius:~$ dpkg -l lxc-utils
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name                   Version          Architecture     Description
    +++-======================-================-================-========================
    ii  lxc-utils              3.0.2-0ubuntu1~1 amd64            Linux Containers userspace tools
    didius:~$ lxc list -c n
    +------------------+
    |       NAME       |
    +------------------+
    | forum-jenkins    |
    +------------------+
    | homeassistant    |
    +------------------+
    | nginx            |
    +------------------+
    | pihole           |
    +------------------+
    | unifi-controller |
    +------------------+
    | unifi-video      |
    +------------------+
    didius:~$ lxc-ls
    didius:~$

# Steps to reproduce

1. Install `lxc-utils`
2. Run `lxc-ls` see no output
3. Run `lxc list` see running hosts

**Comment by stgraber** [comment]
That's normal, lxc-ls interacts with containers created directly through low level lxc and which are typically stored in /var/lib/lxc.

"lxc ls" is the LXD client which talks to a LXD server and lists those containers.

**Comment by dinomite** [comment]
Ok, I'm now more confused than ever on LXC vs LXD—I though the former was just a UI for working with the latter.  Could you point me to something that explains the two?

**Comment by dinomite** [comment]
Further confusing to me, I don't even has a directory `/var/lib/lxc`; all of my containers show up in `/var/lib/lxd/containers/`.

**Comment by umghhh** [comment]
As to confusing I agree it is very confusing - the lxc-tools seem to work differently than lxc but removal of lxc-utils is probably not a very good idea because of this:

> root@master-1:# apt show lxc
Package: lxc
Version: 1:5.0.0 git2209-g5a7b9ce67-0ubuntu1
...
**Depends: lxc-utils (>= 1:5.0.0~git2209-g5a7b9ce67-0ubuntu1)**


From what I could see ansible's lxc_containers also uses lxc-create to spin a container.
