### ISSUE TITLE
LXC uses rundir and lxcpath together but shouldn't

### ISSUE THREAD

**Issue by therealbstern** [lxc/lxc#2756]
* Distribution: All
 * Distribution version: 2.0.1, 2.0.9, master

# Issue description

https://github.com/lxc/lxc/blob/master/src/lxc/lxclock.c#L126, https://github.com/lxc/lxc/blob/master/src/lxc/lxclock.c#L140,
https://github.com/lxc/lxc/blob/master/src/lxc/monitor.c#L74,
https://github.com/lxc/lxc/blob/master/src/lxc/monitor.c#L87, and anywhere else both `rundir` and `lxcpath` are used together incorrectly assume that `lxcpath` is relative and belongs under `rundir`.  In my experience, as an unprivileged user, `lxcpath` is an absolute path and this causes bad pathnames like
`/home/USER/.cache/lxc/run//home/USER/.local/share/lxc//lxc/.FILENAME` to be created.  This also confuses `lxc-monitord` as to where the FIFO belongs, which makes additional trouble.

It appears to me that `lxcdir` is the correct location (though this is a matter of preference and I could misunderstand which directory is preferable).

# Steps to reproduce

 1. launch (or try to launch) a container
 2. Look in `$XDG_RUNTIME_DIR` or `~/.cache/lxc/run` for garbage paths like `home/USER/` (may vary based upon whether or not `$XDG_RUNTIME_DIR` is set and how far down under `lxc`, `lxc/run`, or whatever the code has chosen as the correct path)

Alternatively, run:

```shell
strace -f lxc-start CONTAINER` 2>&1 | grep mkdir
```
and observe weird paths being created.

This makes troubleshooting a non-launching container much more challenging.

**Comment by stgraber** [comment]
This is effectively needed because you can run containers in different locations, not having the lxcpath encoded in there would cause conflicts, both in the path use for logging/locking but also for the unix socket.

**Comment by stgraber** [comment]
@brauner anything you feel we need to do on this?

**Comment by brauner** [comment]
No, I don't think so unless someone has an idea how to do this smarter.
