### ISSUE TITLE
lxc-ls: show consoles attached

### ISSUE THREAD

**Issue by ghost** [lxc/lxc#276]
it would be nice if lxc-ls --fancy would show (in an extra row) if/how many consoles are attached.

**Comment by Kentoseth** [comment]
The user has disappeared, but does the user specify that we should add a column to the --fancy display that shows which containers are currently attached?

I'm not exactly sure how that could be identified as well.

Does lxc-attach trigger any boolean values? @stgraber @idkfa @daniel-baumann 

(Apologies in advance to any of you if I pinged you and you no longer are contributing here)

**Comment by stgraber** [comment]
There is no count for lxc-attach sessions or lxc-console sessions. All that happens is that both of them talk to the command socket to grab some information and then do the attach/console on their own, so the monitor process has no idea how many consoles or attach sessions are in progress.

**Comment by Kentoseth** [comment]
Sounds like something that the LXC community will not be able to provide, as well as a high-level feature that isn't really required for most use-cases.

I propose we then move forward by closing this issue @stgraber .

**Comment by stgraber** [comment]
Yeah, it's something we may be able to do in LXD but can't really do with LXC, at least without major rework of the command socket protocol (and so likely breaking backward compatibility).
