### ISSUE TITLE
systemd-networkd.service in unprivileged lxc guest not working since systemd v 240

### ISSUE THREAD

**Issue by n8v8R** [lxc/lxc#2778]
https://github.com/systemd/systemd/issues/11371

**Comment by Blub** [comment]
I suspect you're getting log entries such as:
`audit: type=1400 audit(1547119806.282:61): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxc-414_</var/lib/lxc>" name="/" pid=18681 comm="(networkd)" flags="rw, rslave"`

particularly the `DENIED`, `operation=mount`, `flags=rw, rslave` parts, judging by the error message in the bug entry you linked to.

While we'd like to allow such mounts we cannot do so until the `apparmor_parser` is fixed to handle them correctly.

**Comment by n8v8R** [comment]
@Blub No such entries in either host or guest. In latter 

> systemd[47]: systemd-networkd.service: Failed at step NAMESPACE spawning /usr/lib/systemd/systemd-networkd: Permission denied

**Comment by Blub** [comment]
Curious. Do you generally get apparmor audit messages in your host's journal? That's at least what I get when trying to reproduce it, and the service's journal also has the `Failed at step NAMESPACE...` error in it...

**Comment by n8v8R** [comment]
Uhm, my bad (on the host `syslog-ng` is handling logs and not` journald` ...) , on the host indeed

audit: type=1400 audit(1547125168.853:722): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxc-container-default-cgns" name="/" pid=8426 comm="(networkd)" flags="rw, rslave"

**Comment by n8v8R** [comment]
> While we'd like to allow such mounts we cannot do so until the `apparmor_parser` is fixed to handle them correctly.

Who is supposed to fix that, I am afraid that is not clear to me

**Comment by n8v8R** [comment]
@Blub would you be so kind to elaborate what

> such mounts

are? The AA crew seems to be unclear about that:

> I don't know if AppArmor's log message is sufficient to reconstruct the actual mount() syscall that the process has performed -- and I don't know if the extra parameters that may be in the syscall are important or not.

**Comment by Blub** [comment]
What systemd wants to do is the equivalent of executing `mount --make-rslave /` on the commandline. The syscall from systemd specifically AFAICT is: `mount(NULL, "/", NULL, MS_REC|MS_SLAVE, NULL);`
As for the AppArmor profile rule, see https://github.com/lxc/lxc/blob/master/config/apparmor/abstractions/container-base.in#L94

I've pinged jjohansen from the AppArmor devs on irc about it and am hoping he's gonna find the time to dig into this soon.

**Comment by n8v8R** [comment]
Thank you! :+1: 

Shall we close the issue here then, perhaps also on systemd, since it all seems to be bearing down to AA. Or is there anything left to do in the lxc code once AA got patched?

**Comment by Blub** [comment]
We can keep it open as a reminder to track the update of our apparmor profile. Not sure what systemd wants to do - it's definitely not a _bug_ on their end.

**Comment by n8v8R** [comment]
@Blub Have you heard back from the AppArmor devs? Asking because the issue seems to be accelerating/cascading to the extent that that the lxc arch linux guest is now entirely dead

https://bugs.archlinux.org/task/61428

**Comment by n8v8R** [comment]
As a consequence any new Arch Linux guest on a Ubuntu host will fail connectivity if created from a recent image via `-t download`, e.g. as currently offered `20190116_01:27`

**Comment by Blub** [comment]
lxc sets the apparmor profile manually, you can use `lxc.apparmor.profile = unchanged` to disable that functionality, but I do not recommend that.

If you insist on a workaround, you _can_ add `mount options=(rw,make-rslave),` to `/etc/apparmor.d/abstractions/lxc/container-base`, which is the rule we *want*, but currently equivalent to allowing *all* mounts. And I'd rather have that part fixed first on the `apparmor_parser` side (because it's been that way for far too long already, and is only part of the issues we're facing currently...)

**Comment by n8v8R** [comment]
@Blub Thanks for the feedback :+1: 

Well, it is not insisting but the choices I am left with are neither desirable.

* hold the updates in the arch linux containers until this issue is fixed.
* set `lxc.apparmor.profile = unchanged`
* set `mount options=(rw,make-rslave)`

Probably holding the updates for a while is the least comprising one, at least for a short while. But who knows when this will be sorted as the AppArmor dev team seems rather unperturbed.
And that only works for existing guests, of which some got bricked already beyond recovery, but not new guests since the latest guest image comes already loaded with `systemd` v240.x upon inception.

Likely that that majority of users deploy guest that are homogeneous with the host and rather not mix like I do. But at some point Ubuntu is likely to update `systemd` in their branch repo to v 240 as well and  I am wondering what that will be causing then even in more homogeneous nodes.

**Comment by n8v8R** [comment]
Apparently it was misconception that this been sorted https://github.com/lxc/lxd/issues/5439#issuecomment-461257784

**Comment by n8v8R** [comment]
@Blub 

> you can use `lxc.apparmor.profile = unchanged`

That is not working for unprivileged guests since producing:

> Failed to mount tmpfs at /dev/shm: Permission denied
> Failed to mount tmpfs at /run: Permission denied
> Failed to mount tmpfs at /sys/fs/cgroup: Permission denied
> Failed to mount cgroup at /sys/fs/cgroup/systemd: No such file or directory
> [!!!!!!] Failed to mount API filesystems.
___
Only way to get an unprivileged guest with systemd v240 working is with `lxc.apparmor.profile = unconfined`

Thus there are only options between a rock and hard place and violating security to no end...
___
The bug tracker at launchpad is basically mute with no development from AppArmor attempting to resolve this mess.

**Comment by toloveru** [comment]
What's the current state of affairs on this? Is it safe to upgrade from the January ALA snapshot already?

**Comment by n8v8R** [comment]
After having upgraded the host to:

unbuntu disco (19.04) | kernel 5.0.0-13 | aa 2.13.2-9 | systemd 240-6

the issue is still present

**Comment by n8v8R** [comment]
@Blub 

> I've pinged jjohansen from the AppArmor devs on irc about it and am hoping he's gonna find the time to dig into this soon

This seems still pending. Any feedback from the AppArmor devs to get this ever sorted?

**Comment by lhorace** [comment]
> This seems still pending. Any feedback from the AppArmor devs to get this ever sorted?

Wrong place to complain about it, bring it upstream, however I will test this later and see if I can replicate it. The host is Ubuntu 19.04?

**Comment by n8v8R** [comment]
Not sure why you deign to label it as a complaint, it is an observation and a question. This thread is also referencing the upstream bug tracker.

The issue is not not with the kernel but AppArmor.

**Comment by lhorace** [comment]
> Not sure why you deign to label it as a complaint

That's beside the point, complain, reporting, etc, should be brought up to AppArmor devs. However, since a bug report is already open, you can safely ignore my comment.

**Comment by Blub** [comment]
from what I understand the issue is more difficult to fix properly than expected, and the apparmor devs seem to have a lot on their plate, will hopefully know more soon

**Comment by n8v8R** [comment]
thank for the feedback and clarification!

Since this been lagging for a while one could only hope that they would get around sooner than later, considering that the upstream (ubuntu) bug tracker appears neglected by them.

**Comment by n8v8R** [comment]
@lhorace 

> That's beside the point, complain, reporting

If that is so in your book, others may have a different perception on linguistic semantics

**Comment by lhorace** [comment]
>  Notwithstanding reading a thread prior posting something that does not contribute to the matter.

The developers responsible for AppArmor aren't available here. This thread could be more useful to people who are following if you are including updates from the upstream bug report, E.g:

> from what I understand the issue is more difficult to fix properly than expected, and the apparmor devs seem to have a lot on their plate, will hopefully know more soon

>  This seems still pending. Any feedback from the AppArmor devs to get this ever sorted?

More precisely, contact the developers directly. Otherwise you are unnecessarily pinging a group of people who may or may not have any information or be able to do anything about the problem. If the question was for Blub, it would be useful for readers to direct the question to him/her.

Regards

**Comment by n8v8R** [comment]
@lhorace 

The only one contributing nonsense to this thread is apparently you. There is not a single iota useful of what you are egressing, notwithstanding that you are not even bothering to peruse the thread properly prior blasting away.

If anyone would feel bothered that person surely could express himself and doe not need a nanny.

Why do you not find another thread to spam unnecessarily?

**Comment by lhorace** [comment]
> The only one contributing nonsense to this thread is apparently you. There is not a single iota useful of what you are egressing, notwithstanding that you are not even bothering to peruse the thread properly prior blasting away.

> Why do you not find another thread to troll with spam unnecessarily?

That's beside the point and unproductive.

FWIW, unless I could replicate the issue, which I will test in my environment, I'll follow and respond to appropriate threads. Checking status for an AppArmor bug here just seems irrelevant. Nevertheless, I'll be happy to open a new issue when and if I encounter any problems that warrant LXC developers attention.

Regards

**Comment by n8v8R** [comment]
Just stop speaking for other people and start perusing the thread https://github.com/lxc/lxc/issues/2778#issuecomment-453492686

**Comment by lhorace** [comment]
Technically speaking, I've read every single thread on this issue and I would have been more up2date with the problem and I would have done my due diligence to contribute useful information. My point still stands.  Notwithstanding, I might be able to find a workaround without using aa unconfined or unchanged for unprivileged containers.

**Comment by stgraber** [comment]
This is an apparmor bug that we're quite aware of, have been for a long time and are directly tracking.
Once apparmor behaves, we will be updating the apparmor profiles of LXC and LXD. Until then it would be a security issue to change anything.
