### ISSUE TITLE
How to run graphics-accelerated GUI apps in LXD containers on your Ubuntu desktop using host wayland

### ISSUE THREAD

**Issue by varunmv5** [lxc/lxc#2795]
I am working on LXD containers for a project in my company. I am comparatively new to the containers. But have been constantly working since a month and a half. 
It is highly critical and important to know few important things about how to run GUI applications inside the LXD container using the host system display server.

I have tried this blog on how to run GUI applications inside LXD container using X11 from host system.

https://blog.simos.info/how-to-run-graphics-accelerated-gui-apps-in-lxd-containers-on-your-ubuntu-desktop/

It works fine. I am able to run the xclock, glxgears, and also run pulse audio.

But when i change the display server to wayland, i am not able to run the GUI applications. I referred to a lot of links online but in vain. I work for a start up and i need this help. 
I get the error "Error: Cannot open display :0"

inside the container.

But for X11 i could resolve this issue by using xhost + in the local host system.

But for wayland i agree there is no Xauthority file and its very secured.

I want to run GUI applications inside LXD container using host system display server as Wayland. Please suggest me a proper reference point or a link where i could refer to and implement. Please suggest me some ideas on how to address this issue.

**Comment by schreibikus** [comment]
It’s not possible! Try to use xwayland ...

**Comment by stgraber** [comment]
Closing as this is a LXD question.

It is possible with some versions of Wayland and special extensions as is done on ChromeOS, but for most other cases, your best bet is to run XWayland outside the container and then use the normal X11 passthrough tutorials.
