### ISSUE TITLE
Make processes follow with migration

### ISSUE THREAD

**Issue by haha150** [lxc/lxc#2797]
Hi

I am trying to do migration of LXC containers between two machines. And so I was wondering, if it is possible to get the processes that are running in the LXC to follow with the migration.

Example, I have a LXC that is running a iperf client or server, when I migrate this LXC, I want the running iperf to also follow and be resumed after migration.

I simply tried this with lxc move c1 remote:c1, but the process doesn't follow, is it possible?

**Comment by stgraber** [comment]
That's what `lxc-checkpoint` and LXD live migration do. Though this is a very difficult process and rarely works.
