### ISSUE TITLE
lxc-update-config doesn't convert last line of config file

### ISSUE THREAD

**Issue by gfiedler** [lxc/lxc#2837]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04

```
$ lxc-start --version
3.0.3
```
# Issue description

lxc-update-config doesn't convert last line if the legacy configuration file doesn't has a trailing newline.

# Steps to reproduce

```
echo -n "lxc.network.type = veth" >config
lxc-update-config --config config
grep "lxc.net.0.type" config
```

**Comment by brauner** [comment]
We're using standard unix tools and if it doesn't end with a newline, which in your example you can see from:
```
cat -A ./config
```
is not the case which is why e.g. `read -r` which we use to read the config file line-by-line fail.
