### ISSUE TITLE
parsing lxc.include = files with CRLF does not work

### ISSUE THREAD

**Issue by n8v8R** [lxc/lxc#2838]
# Required information

 * Distribution: ubuntu
 * Distribution version: cosmic
 * The output of

  * `lxc-start --version` 

> 3.0.3

   * `lxc-checkconfig`

> Kernel configuration found at /boot/config-4.18.0-15-generic
> --- Namespaces ---
> Namespaces: enabled
> Utsname namespace: enabled
> Ipc namespace: enabled
> Pid namespace: enabled
> User namespace: enabled
> Network namespace: enabled
> 
> --- Control groups ---
> Cgroups: enabled
> 
> Cgroup v1 mount points:
> /sys/fs/cgroup/systemd
> /sys/fs/cgroup/cpu,cpuacct
> /sys/fs/cgroup/hugetlb
> /sys/fs/cgroup/perf_event
> /sys/fs/cgroup/memory
> /sys/fs/cgroup/net_cls,net_prio
> /sys/fs/cgroup/cpuset
> /sys/fs/cgroup/devices
> /sys/fs/cgroup/freezer
> /sys/fs/cgroup/pids
> /sys/fs/cgroup/blkio
> /sys/fs/cgroup/rdma
> 
> Cgroup v2 mount points:
> /sys/fs/cgroup/unified
> 
> Cgroup v1 clone_children flag: enabled
> Cgroup device: enabled
> Cgroup sched: enabled
> Cgroup cpu account: enabled
> Cgroup memory controller: enabled
> Cgroup cpuset: enabled
> 
> --- Misc ---
> Veth pair device: enabled, loaded
> Macvlan: enabled, not loaded
> Vlan: enabled, not loaded
> Bridges: enabled, loaded
> Advanced netfilter: enabled, loaded
> CONFIG_NF_NAT_IPV4: enabled, loaded
> CONFIG_NF_NAT_IPV6: enabled, not loaded
> CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
> CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
> CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
> CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
> FUSE (for use with lxcfs): enabled, not loaded
> 
> --- Checkpoint/Restore ---
> checkpoint restore: enabled
> CONFIG_FHANDLE: enabled
> CONFIG_EVENTFD: enabled
> CONFIG_EPOLL: enabled
> CONFIG_UNIX_DIAG: enabled
> CONFIG_INET_DIAG: enabled
> CONFIG_PACKET_DIAG: enabled
> CONFIG_NETLINK_DIAG: enabled
> File capabilities:

   * `uname -a`

> 4.18.0-15-generic #16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

   * `cat /proc/self/cgroup`

> 12:rdma:/
> 11:blkio:/user.slice
> 10:pids:/user.slice/user-0.slice/session-10.scope
> 9:freezer:/user/root/0
> 8:devices:/user.slice
> 7:cpuset:/
> 6:net_cls,net_prio:/
> 5:memory:/user.slice/user-0.slice/session-10.scope
> 4:perf_event:/
> 3:hugetlb:/
> 2:cpu,cpuacct:/user.slice
> 1:name=systemd:/user.slice/user-0.slice/session-10.scope
> 0::/user.slice/user-0.slice/session-10.scope

   * `cat /proc/1/mounts`

> sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
> proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
> udev /dev devtmpfs rw,nosuid,relatime,size=3972096k,nr_inodes=993024,mode=755 0 0
> devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
> tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=797292k,mode=755 0 0
> /dev/mapper/s-os / xfs rw,noatime,attr2,inode64,noquota 0 0
> /dev/mapper/s-usr /usr xfs rw,nodev,noatime,attr2,inode64,noquota 0 0
> securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
> tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
> tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
> tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
> cgroup2 /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
> cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
> pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
> bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
> cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
> cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
> cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
> cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
> cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
> cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
> cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
> cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
> cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
> cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
> cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
> systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=36,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14741 0 0
> debugfs /sys/kernel/debug debugfs rw,relatime 0 0
> mqueue /dev/mqueue mqueue rw,relatime 0 0
> hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
> fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
> configfs /sys/kernel/config configfs rw,relatime 0 0
> /dev/mapper/s-var /var xfs rw,nodev,noatime,attr2,inode64,noquota 0 0
> /dev/mapper/s-usr_local /usr/local xfs rw,nodev,noatime,attr2,inode64,noquota 0 0
> /dev/mapper/s-var_log /var/log xfs rw,nosuid,nodev,noexec,noatime,attr2,inode64,noquota 0 0
> /dev/mapper/s-home /home btrfs rw,nodev,noatime,nodiratime,space_cache,subvolid=256,subvol=/@home 0 0
> /dev/mapper/s-opt /opt btrfs rw,nodev,noatime,nodiratime,space_cache,subvolid=5,subvol=/ 0 0
> /dev/mapper/s-srv /srv btrfs rw,nodev,noatime,nodiratime,space_cache,subvolid=5,subvol=/ 0 0
> /dev/mapper/s-tmp /tmp xfs rw,nosuid,nodev,noatime,attr2,inode64,noquota 0 0
> /dev/sda2 /boot xfs rw,nosuid,nodev,noexec,noatime,attr2,inode64,noquota 0 0
> lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
> binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
> tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=797288k,mode=700 0 0

# Issue description

`lxc.sysctl.` settings stored in an administrative template file and loaded into the (unprivileged) container conf via `lxc.include =` resulting in

> conf.c: setup_sysctl_parameters: Failed to setup sysctl parameters

The very same `lxc.sysctl.` settings stored directly in the (unprivileged) container conf do not exhibit the issue.

# Steps to reproduce

 1. Set up a working unprivileged container
 2. create admin template file with various `lxc.sysctl.` settings
 3. Add `lxc.include =` with the admin template to the container conf
 4. for comparison/debugging move the `lxc.sysctl.` settings from the admin template to the container conf and remove `lxc.include =`

# Information to attach

 - the containers configuration file

```
lxc.include = /usr/share/lxc/config/common.conf
lxc.include = /usr/share/lxc/config/userns.conf
lxc.arch = x86_64
lxc.start.delay = 5
lxc.start.order = 0
lxc.rootfs.path = dir:/srv/lxc/dns/rootfs
lxc.uts.name = dns
lxc.apparmor.profile = unconfined
lxc.include = /srv/lxc/unrprivilged_auto_boot.conf
lxc.net.0.link = br0
lxc.net.0.hwaddr = 00:16:3e:4a:8e:72
lxc.include = /srv/lxc/network.conf
lxc.include = /srv/lxc/syctl_no_fwd.conf
```
- the unrprivilged_auto_boot.conf

```
lxc.start.auto = 1
lxc.group = onboot
lxc.idmap = u 0 100000 65536
lxc.idmap = g 0 100000 65536
lxc.ephemeral = 0
lxc.console.buffer.size = auto
lxc.mount.auto = proc:mixed sys:mixed
```

- the network.conf
```
lxc.net.0.type = veth
lxc.net.0.flags = up
```

- the syctl_no_fwd.conf

```
lxc.sysctl.net.ipv4.ip_forward = 0
lxc.sysctl.net.ipv6.conf.all.forwarding = 0
lxc.sysctl.net.ipv6.conf.default.forwarding = 0
lxc.sysctl.net.ipv6.conf.eth0.forwarding = 0

lxc.sysctl.net.ipv4.conf.all.rp_filter = 1
lxc.sysctl.net.ipv4.conf.default.rp_filter = 1
```

**Comment by brauner** [comment]
Odd, I can't reproduce the error. Can you please show the full trace log:
```
lxc-start <container-name> -l trace -o <container-name>.log
```
and append the contents of `<container-name>.log` here for a failed and successful container, please.

**Comment by n8v8R** [comment]
[fail.log](https://github.com/lxc/lxc/files/2849431/fail.log)
[succ.log](https://github.com/lxc/lxc/files/2849427/succ.log)

**Comment by brauner** [comment]
Can you do me a favor and paste verbatim from here:
```
lxc.sysctl.net.ipv4.ip_forward = 0
lxc.sysctl.net.ipv6.conf.all.forwarding = 0
lxc.sysctl.net.ipv6.conf.default.forwarding = 0
lxc.sysctl.net.ipv6.conf.eth0.forwarding = 0

lxc.sysctl.net.ipv4.conf.all.rp_filter = 1
lxc.sysctl.net.ipv4.conf.default.rp_filter = 1
```
into the file and try to include the file again. Might be that there's an invalid character in the file or sm.

**Comment by n8v8R** [comment]
You hinted correctly - the cause the line ending of the file that is to be included. The container starts correctly if `LR` is used but fails if `CRLF` is used in the file that is to be included.

Which seems like a (LXC) parsing issue then.

When generating a file from the terminal cli, e.g. `touch test`, it generates with `CRLF` as standard it seems.

**Comment by n8v8R** [comment]
You want to keep this open as bug tracker or is parsing of CRLF files simply not meant to be?

**Comment by brauner** [comment]
https://github.com/lxc/lxc/pull/2839
