### ISSUE TITLE
getty@ spam in arch linux container

### ISSUE THREAD

**Issue by n8v8R** [lxc/lxc#2840]
# Required information

same as in https://github.com/lxc/lxc/issues/2838

# Issue description

There are apparently 6 getty@ instances running in the arch linux guest container that are spamming the logs. Neither have I creates those instances nor enabled them, they appear upon installation of the guest container - created by LXC?

[getty@.log](https://github.com/lxc/lxc/files/2849662/getty%40.log)

The spam frequency is staggering and creating unnecessary cost to cpu and disk.

`systemctl list-unit-files --state=enabled` produces

> UNIT FILE                             STATE
> **getty@.service                        enabled**

Trying to stop  `systemctl stop getty@` produces

> Failed to stop getty@.service: Unit name getty@.service is missing the instance name.

Only `systemctl disable getty@` and a reboot of the guest solves the matter, but why having those instances created and running in the first place?

> 
> Removed /etc/systemd/system/getty.target.wants/getty@tty1.service.
> Removed /etc/systemd/system/getty.target.wants/getty@lxc-tty1.service.
> Removed /etc/systemd/system/getty.target.wants/getty@lxc-tty2.service.
> Removed /etc/systemd/system/getty.target.wants/getty@lxc-tty3.service.
> Removed /etc/systemd/system/getty.target.wants/getty@lxc-tty4.service.
> Removed /etc/systemd/system/getty.target.wants/getty@lxc-tty5.service.
> Removed /etc/systemd/system/getty.target.wants/getty@lxc-tty6.service.

# Steps to reproduce

 1. create a new arch linux guest
 2. configure new arch linux guest
 3. start new arch linux guest
 4. ` journalctl -f`

**Comment by brauner** [comment]
Either mask the gettys or request LXC set them up with:
```
lxc.tty.max = 6
```

**Comment by n8v8R** [comment]
masking is prevented by systemd (by design), only disabling works.

`systemctl mask getty@`
> Failed to mask unit: File /etc/systemd/system/getty@.service already exists.

What I do not understand why this is happening in an Arch Linux guest but not other guests, is it something by design of that distro? Would it not make sense to ship the Arch Linux guest image with that service disabled by default instead?

**Comment by brauner** [comment]
Might be that ArchLinux is not using `lxc.tty.max` by default. It should also happen with Alpine for that matter.
