### ISSUE TITLE
got the ssh connection fail sometimes when connect to container 

### ISSUE THREAD

**Issue by gujinqiangggs** [lxc/lxc#2851]
* Distribution: centos 
 * Distribution version: 6.5(x64)
 * The output of
[root@GGS ~]# lxc-start --version
1.0.10
[root@GGS ~]# lxc-checkconfig
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-2.6.32-431.el6.x86_64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
newuidmap is not installed
newgidmap is not installed
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroup: enabled
Cgroup namespace: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: /usr/local/bin/lxc-checkconfig: line 132: [: -ge: unary operator expected
/usr/local/bin/lxc-checkconfig: line 132: [: -gt: unary operator expected
enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: missing
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: missing
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: missing
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: missing
CONFIG_NETLINK_DIAG: missing
File capabilities: /usr/local/bin/lxc-checkconfig: line 166: [: -gt: unary operator expected

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/local/bin/lxc-checkconfig

[root@GGS ~]# uname -a
Linux GGS 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
[root@GGS ~]# cat /proc/self/cgroup
8:blkio:/
7:net_cls:/
6:freezer:/
5:devices:/
4:memory:/
3:cpuacct:/
2:cpu:/
1:cpuset:/
[root@GGS ~]# cat /proc/1/mounts
rootfs / rootfs rw 0 0
proc /proc proc rw,relatime 0 0
sysfs /sys sysfs ro,relatime 0 0
devtmpfs /dev devtmpfs rw,relatime,size=1930964k,nr_inodes=482741,mode=755 0 0
devpts /dev/pts devpts rw,relatime,gid=5,mode=620,ptmxmode=666 0 0
tmpfs /dev/shm tmpfs rw,relatime 0 0
/dev/mapper/vg_ggs-lv_root / ext4 rw,relatime,barrier=1,data=ordered 0 0
/proc/bus/usb /proc/bus/usb usbfs rw,relatime 0 0
/dev/sda1 /boot ext4 rw,relatime,barrier=1,data=ordered 0 0
/dev/mapper/vg_ggs-lv_home /home ext4 rw,relatime,barrier=1,data=ordered 0 0
none /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
cgroup /cgroup/cpuset cgroup rw,relatime,cpuset 0 0
cgroup /cgroup/cpu cgroup rw,relatime,cpu 0 0
cgroup /cgroup/cpuacct cgroup rw,relatime,cpuacct 0 0
cgroup /cgroup/memory cgroup rw,relatime,memory 0 0
cgroup /cgroup/devices cgroup rw,relatime,devices 0 0
cgroup /cgroup/freezer cgroup rw,relatime,freezer 0 0
cgroup /cgroup/net_cls cgroup rw,relatime,net_cls 0 0
cgroup /cgroup/blkio cgroup rw,relatime,blkio 0 0
[root@GGS ~]# 

# Issue description
I create 128 containers with ip from 192.168.95.1 ~ 192.168.95.128. I connect to those container with ssh, mostly they're ok, but sometime i got some container can't log in correctly. At first time, maybe 192.168.95.79 can't connect , after i input the password ,the putty hanged there with no response. At he same time, In the host ssh session, it shows the error message "[root@GGS ~]# Last login: Wed Feb 13 20:51:55 2019 from 192.168.95.200
-bash: cannot set terminal process group (-1): Inappropriate ioctl for device
-bash: no job control in this shell". Meantime this host ssh session is not working properly. It shows like this "[root@vsm_79 ~]# 
[root@GGS ~]# [root@vsm_79 ~]# 
[root@GGS ~]# [root@vsm_79 ~]# 
[root@GGS ~]# [root@vsm_79 ~]# " when i just input the enter key. It looks like confused the session socket(root@GGS is my host ssh session) . But i can connect to the container with "lxc-console -n vsm_079", it's ok.  I reboot this vsm_079 container, it's ok to connect to this container with ssh. If i reboot the host, the next time ,the container of 192.168.95.123 maybe have the same ssh connect problems,  but the vsm_079 is OK now. It's irregular. I check the few of closed issues, got a similar question (https://github.com/lxc/lxc/issues/1804 . I'am not clearly understand what you solution. What i do is just update the bash version to 5.0, it's still not work perfectly although the number of occurrences decreases. So Can you give me some advice about how to solve this problem ?update centos ? update lxc? or something else?
Thank you very much!

Here are some attach for you:
[root@GGS ~]# lxc-start -n vsm_001
lxc-start: cgfs.c: handle_cgroup_settings: 2153 Device or resource busy - failed to set memory.use_hierarchy to 1; continuing
                                                                                                                             lxc-start: cgfs.c: handle_cgroup_settings: 2153 Device or resource busy - failed to set memory.use_hierarchy to 1; continuing

/usr/local/var/lib/lxc/vsm_001/config:
lxc.mount.auto = proc:mixed sys:ro
lxc.tty = 4
lxc.pts = 1024
lxc.devttydir = lxc
lxc.arch = x86_64
lxc.seccomp = /usr/local/share/lxc/config/common.seccomp
lxc.cgroup.cpuset.cpus = 0
lxc.cgroup.devices.deny = a
lxc.cgroup.devices.allow = c *:* m
lxc.cgroup.devices.allow = b *:* m
lxc.cgroup.devices.allow = c 1:3 rwm
lxc.cgroup.devices.allow = c 1:5 rwm
lxc.cgroup.devices.allow = c 1:7 rwm
lxc.cgroup.devices.allow = c 5:0 rwm
lxc.cgroup.devices.allow = c 1:8 rwm
lxc.cgroup.devices.allow = c 1:9 rwm
lxc.cgroup.devices.allow = c 136:* rwm
lxc.cgroup.devices.allow = c 5:2 rwm
lxc.utsname = vsm_001
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = br0
lxc.network.veth.pair = v-001-e0
lxc.network.hwaddr = 00:16:3e:71:24:33
lxc.network.ipv4.gateway = 192.168.95.254
lxc.network.ipv4 = 192.168.95.1/24
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = virbr0
lxc.network.veth.pair = v-001-e1
lxc.network.hwaddr = 00:16:3e:a7:0b:15
lxc.network.ipv4 = 192.168.167.1/24
lxc.cap.drop = mac_admin
lxc.cap.drop = mac_override
lxc.cap.drop = setfcap
lxc.cap.drop = sys_module
lxc.cap.drop = sys_nice
lxc.cap.drop = sys_pacct
lxc.cap.drop = sys_rawio
lxc.cap.drop = sys_time
lxc.hook.clone = /usr/local/share/lxc/hooks/clonehostname
lxc.rootfs = /usr/local/var/lib/lxc/vsm_001/rootfs
lxc.start.auto = 1
lxc.group = onboot

**Comment by stgraber** [comment]
Did you find out what was going on?
