### ISSUE TITLE
LXC problems on Jetson TX2

### ISSUE THREAD

**Issue by Xeod757** [lxc/lxc#2855]
# Required information

 * Distribution: Linux tegra-ubuntu 
 * Distribution version: 4.4.38-tegra
 * The output of
   * `lxc-start --version : 2.0.8`
   * `lxc-checkconfig
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Warning: newuidmap is not setuid-root
Warning: newgidmap is not setuid-root
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: missing
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: missing
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: missing
CONFIG_INET_DIAG: missing
CONFIG_PACKET_DIAG: missing
CONFIG_NETLINK_DIAG: missing
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -a : Linux tegra-ubuntu 4.4.38-tegra #1 SMP PREEMPT Thu May 17 00:15:19 PDT 2018 aarch64 aarch64 aarch64 GNU/Linux`
   * `cat /proc/self/cgroup`
11:devices:/user.slice
10:cpuset:/
9:blkio:/user.slice
8:pids:/user.slice/user-1001.slice
7:perf_event:/
6:cpu,cpuacct:/user.slice
5:debug:/
4:net_cls,net_prio:/
3:freezer:/user/nvidia/0
2:memory:/user/nvidia/0
1:name=systemd:/user.slice/user-1001.slice/session-2.scope

   * `cat /proc/1/mounts`
/dev/root / ext4 rw,relatime,data=ordered 0 0
devtmpfs /dev devtmpfs rw,relatime,size=7967772k,nr_inodes=1991943,mode=755 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,mode=755 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs rw,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/debug cgroup rw,nosuid,nodev,noexec,relatime,debug 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event,release_agent=/run/cgmanager/agents/cgm-release-agent.perf_event 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids,release_agent=/run/cgmanager/agents/cgm-release-agent.pids 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
cgmfs /run/cgmanager/fs tmpfs rw,relatime,size=100k,mode=755 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
/dev/root /var/lib/docker/overlay2 ext4 rw,relatime,data=ordered 0 0
tmpfs /run/user/1001 tmpfs rw,nosuid,nodev,relatime,size=803460k,mode=700,uid=1001,gid=1001 0 0
gvfsd-fuse /run/user/1001/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1001,group_id=1001 0 0

# Issue description

Hello,
I want to install LXC on my Nvidia Jetson TX2 but I can not do it. I have several errors using the command "lxc-checkconfig" that I can not solve. and I still try to create a container, it works. but when I run it I get this error message:
lxc-start: tools/lxc_start.c: main: 366 The container failed to start.
lxc-start: tools/lxc_start.c: main: 368 To get more details, run the container in foreground mode.
lxc-start: tools/lxc_start.c: main: 370 Additional information can be obtained by setting the --logfile and --logpriority options.

Thanks for your help.
Best regard,
Raphael.

**Comment by stgraber** [comment]
Per the error, please run with logfile and logpriority so we can actually tell what's wrong.

`lxc-start -n NAME -o debug -l trace -F` would be a good start, then attach what's in the `debug` file.

**Comment by RaphaelGPR** [comment]
sudo lxc-start -n ubuntu -o debug trace -F
lxc-start: conf.c: instantiate_veth: 2736 failed to attach 'vethJAV7D3' to the bridge 'lxcbr0': Operation not permitted
                                                                                                                       lxc-start: conf.c: lxc_create_network: 3029 failed to create netdev
                                                                                                                                                                                          lxc-start: start.c: lxc_spawn: 1103 Failed to create the network.
                                               lxc-start: start.c: __lxc_start: 1358 Failed to spawn container "ubuntu".
                                                                                                                        lxc-start: tools/lxc_start.c: main: 366 The container failed to start.
lxc-start: tools/lxc_start.c: main: 370 Additional information can be obtained by setting the --logfile and --logpriority options.

**Comment by stgraber** [comment]
Again, please attach the `debug` file

**Comment by RaphaelGPR** [comment]
### the debug file : 

```
      lxc-start 20190215162222.457 ERROR    lxc_conf - conf.c:instantiate_veth:2736 - failed to attach 'vethKS5A16' to the bridge 'lxcbr0': Operation not permitted
      lxc-start 20190215162222.716 ERROR    lxc_conf - conf.c:lxc_create_network:3029 - failed to create netdev
      lxc-start 20190215162222.717 ERROR    lxc_start - start.c:lxc_spawn:1103 - Failed to create the network.
      lxc-start 20190215162222.717 ERROR    lxc_start - start.c:__lxc_start:1358 - Failed to spawn container "ubuntu".
      lxc-start 20190215162222.593 ERROR    lxc_start_ui - tools/lxc_start.c:main:366 - The container failed to start.
      lxc-start 20190215162222.595 ERROR    lxc_start_ui - tools/lxc_start.c:main:370 - Additional information can be obtained by setting the --logfile and --logpriority options.
      lxc-start 20190215162422.513 ERROR    lxc_conf - conf.c:instantiate_veth:2736 - failed to attach 'vethJAV7D3' to the bridge 'lxcbr0': Operation not permitted
      lxc-start 20190215162422.533 ERROR    lxc_conf - conf.c:lxc_create_network:3029 - failed to create netdev
      lxc-start 20190215162422.533 ERROR    lxc_start - start.c:lxc_spawn:1103 - Failed to create the network.
      lxc-start 20190215162422.533 ERROR    lxc_start - start.c:__lxc_start:1358 - Failed to spawn container "ubuntu".
      lxc-start 20190215162423.465 ERROR    lxc_start_ui - tools/lxc_start.c:main:366 - The container failed to start.
      lxc-start 20190215162423.467 ERROR    lxc_start_ui - tools/lxc_start.c:main:370 - Additional information can be obtained by setting the --logfile and --logpriority options.
      lxc-start 20190217205627.448 INFO     lxc_start_ui - tools/lxc_start.c:main:275 - using rcfile /var/lib/lxc/ubuntu/config
      lxc-start 20190217205627.504 WARN     lxc_confile - confile.c:config_pivotdir:1916 - lxc.pivotdir is ignored.  It will soon become an error.
      lxc-start 20190217205627.529 WARN     lxc_start - start.c:lxc_check_inherited:238 - Inherited fd: 3.
      lxc-start 20190217205627.530 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver nop
      lxc-start 20190217205627.541 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
      lxc-start 20190217205627.542 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for reject_force_umount action 0.
      lxc-start 20190217205627.542 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:259 - Setting Seccomp rule to reject force umounts.
      lxc-start 20190217205627.543 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for reject_force_umount action 0.
      lxc-start 20190217205627.543 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:259 - Setting Seccomp rule to reject force umounts.
      lxc-start 20190217205627.546 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .[all].
      lxc-start 20190217205627.546 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .kexec_load errno 1.
      lxc-start 20190217205627.547 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for kexec_load action 327681.
      lxc-start 20190217205627.547 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for kexec_load action 327681.
      lxc-start 20190217205627.547 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .open_by_handle_at errno 1.
      lxc-start 20190217205627.548 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for open_by_handle_at action 327681.
      lxc-start 20190217205627.548 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for open_by_handle_at action 327681.
      lxc-start 20190217205627.549 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .init_module errno 1.
      lxc-start 20190217205627.549 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for init_module action 327681.
      lxc-start 20190217205627.549 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for init_module action 327681.
      lxc-start 20190217205627.550 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .finit_module errno 1.
      lxc-start 20190217205627.550 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for finit_module action 327681.
      lxc-start 20190217205627.551 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for finit_module action 327681.
      lxc-start 20190217205627.551 INFO     lxc_seccomp - seccomp.c:parse_config_v2:418 - processing: .delete_module errno 1.
      lxc-start 20190217205627.551 INFO     lxc_seccomp - seccomp.c:parse_config_v2:590 - Adding native rule for delete_module action 327681.
      lxc-start 20190217205627.551 INFO     lxc_seccomp - seccomp.c:parse_config_v2:593 - Adding compat rule for delete_module action 327681.
      lxc-start 20190217205627.552 INFO     lxc_seccomp - seccomp.c:parse_config_v2:603 - Merging in the compat Seccomp ctx into the main one.
      lxc-start 20190217205627.553 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20190217205627.553 DEBUG    lxc_start - start.c:setup_signal_fd:273 - Set SIGCHLD handler with file descriptor: 6.
      lxc-start 20190217205627.571 DEBUG    console - console.c:lxc_console_peer_default:447 - using "/dev/tty" as peer tty device
      lxc-start 20190217205627.571 DEBUG    console - console.c:lxc_console_sigwinch_init:144 - 4076 got SIGWINCH fd 10
      lxc-start 20190217205627.572 DEBUG    console - console.c:lxc_console_winsz:71 - set winsz dstfd:7 cols:80 rows:24
      lxc-start 20190217205627.572 INFO     lxc_start - start.c:lxc_init:475 - Container "ubuntu" is initialized.
      lxc-start 20190217205627.586 DEBUG    lxc_start - start.c:__lxc_start:1329 - Not dropping CAP_SYS_BOOT or watching utmp.
      lxc-start 20190217205627.697 INFO     lxc_conf - conf.c:instantiate_veth:2717 - Retrieved mtu 1500 from vethI8LH02
      lxc-start 20190217205627.699 ERROR    lxc_conf - conf.c:instantiate_veth:2736 - failed to attach 'vethU9LEBY' to the bridge 'lxcbr0': Operation not permitted
      lxc-start 20190217205627.944 ERROR    lxc_conf - conf.c:lxc_create_network:3029 - failed to create netdev
      lxc-start 20190217205627.945 ERROR    lxc_start - start.c:lxc_spawn:1103 - Failed to create the network.
      lxc-start 20190217205627.946 ERROR    lxc_start - start.c:__lxc_start:1358 - Failed to spawn container "ubuntu".
      lxc-start 20190217205627.946 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20190217205627.947 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
      lxc-start 20190217205627.947 INFO     lxc_conf - conf.c:run_script_argv:435 - Executing script "/usr/share/lxcfs/lxc.reboot.hook" for container "ubuntu", config section "lxc".
      lxc-start 20190217205627.603 ERROR    lxc_start_ui - tools/lxc_start.c:main:366 - The container failed to start.
      lxc-start 20190217205627.603 ERROR    lxc_start_ui - tools/lxc_start.c:main:370 - Additional information can be obtained by setting the --logfile and --logpriority options.

```

**Comment by stgraber** [comment]
Sounds like you're missing a `lxcbr0` bridge on this system.

**Comment by RaphaelGPR** [comment]
### thanks it worked but I have new error:
`nvidia@tegra-ubuntu:~$ sudo lxc-start -n ubuntu -o debugt trace -F
umount: /usr/lib/aarch64-linux-gnu/lxc/sys/fs/cgroup/blkio/lxc/ubuntu: not mounted
                                                                                  umount: /usr/lib/aarch64-linux-gnu/lxc/sys/fs/cgroup/cpuset/lxc/ubuntu: not mounted
                                                                                                                                                                     umount: /usr/lib/aarch64-linux-gnu/lxc/sys/fs/cgroup/cpu/lxc/ubuntu: not mounted
                                         umount: /usr/lib/aarch64-linux-gnu/lxc/sys/fs/cgroup/debug/lxc/ubuntu: not mounted
                                                                                                                           umount: /usr/lib/aarch64-linux-gnu/lxc/sys/fs/cgroup/devices/lxc/ubuntu: not mounted
   umount: /usr/lib/aarch64-linux-gnu/lxc/sys/fs/cgroup/freezer/lxc/ubuntu: not mounted
                                                                                       umount: /usr/lib/aarch64-linux-gnu/lxc/sys/fs/cgroup/memory/lxc/ubuntu: not mounted
                                                                                                                                                                          umount: /usr/lib/aarch64-linux-gnu/lxc/sys/fs/cgroup/net_cls/lxc/ubuntu: not mounted
                                                  umount: /usr/lib/aarch64-linux-gnu/lxc/sys/fs/cgroup/perf_event/lxc/ubuntu: not mounted
                                                                                                                                         umount: /usr/lib/aarch64-linux-gnu/lxc/sys/fs/cgroup/pids/lxc/ubuntu: not mounted
              umount: /usr/lib/aarch64-linux-gnu/lxc/sys/fs/cgroup/systemd/lxc/ubuntu: not mounted
                                                                                                  lxc-start: sync.c: __sync_wait: 57 An error occurred in another process (expected sequence number 5)
                                                                                                                                                                                                      lxc-start: start.c: __lxc_start: 1358 Failed to spawn container "ubuntu".
                                                                   lxc-start: tools/lxc_start.c: main: 366 The container failed to start.
lxc-start: tools/lxc_start.c: main: 370 Additional information can be obtained by setting the --logfile and --logpriority options.
nvidia@tegra-ubuntu:~$ 
`
### the debug file : 
`lxc-start 20190217214108.368 ERROR    lxc_start - start.c:start:1443 - No such file or directory - Failed to exec "trace".
      lxc-start 20190217214108.369 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
      lxc-start 20190217214108.369 ERROR    lxc_start - start.c:__lxc_start:1358 - Failed to spawn container "ubuntu".
      lxc-start 20190217214108.893 ERROR    lxc_start_ui - tools/lxc_start.c:main:366 - The container failed to start.
      lxc-start 20190217214108.893 ERROR    lxc_start_ui - tools/lxc_start.c:main:370 - Additional information can be obtained by setting the --logfile and --logpriority options.
`

**Comment by RaphaelGPR** [comment]
Hello,
I found by myself I simply throw the container with the functinon -F.

`sudo lxc-start -n Ubuntu-Test-1.35 -o debug-1.35 -E --logfile log-1.35`

Thanks for your help.
