### ISSUE TITLE
OpenWRT Container ? how to create

### ISSUE THREAD

**Issue by Xeod757** [lxc/lxc#2868]
Hi,

I working  on a Nvidia Jetson TX2. 
I succeed to install and run existing debian lxc container on TX2 (see my solution on the forum)

Now, for a professional application i need to install OpenWRT on LXC.
I looked for an existing  Openwrt  LXC container (with `ls /usr/share/lxc/template`) but there was not any.

Can you please tell me how to create a new OpenWRT template for aarch64 ? I can not find any tutorial for creating a new LXC template from scratch (except for debian using debootstrap but debootstrap doesn't exist on openwrt) .

Thanks for your help, any pointer would be appreciate !

**Comment by rkkoszewski** [comment]
Have a look at this: https://github.com/mikma/lxd-openwrt
