### ISSUE TITLE
Problem with lxc config device

### ISSUE THREAD

**Issue by pepanillo** [lxc/lxc#2872]
* Distribution: Ubuntu
 * Distribution version: 16.04.5 LTS (GNU/Linux 4.4.0-141-generic x86_64)
 * `uname -a` 
Linux cocoloco 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

lxc --version 3.03
lxd --version 3.03

# Issue description
I need to create devices in a container. When I try

lxc config device add copias char source=/dev/tape path=/dev/tape

I get

Error: Invalid devices: Invalid device type for device 'char'

Any idea? am I doing something wrong?

**Comment by stgraber** [comment]
`unix-char` instead of `char`.

**Comment by stgraber** [comment]
Actually, you want `lxc config device add copias some-name unix-char source=/dev/tape path=/dev/tape`

**Comment by pepanillo** [comment]
# lxc config device add copias unix-char source=/dev/tape path=/dev/tape
Error: Invalid devices: Invalid device type for device 'unix-char'

Same result

**Comment by pepanillo** [comment]
Perhaps I have a problem with the sintaxis. I'll keep on trying.

**Comment by stgraber** [comment]
Yes, look at my example, you're still missing a device name.

**Comment by pepanillo** [comment]
Yes, the correct sintaxis is
lxc config device add copias device-name unix-char source=/dev/device-name

Thankyou so much!
