### ISSUE TITLE
lxc-stop do not shut down veth intime

### ISSUE THREAD

**Issue by bobykus31** [lxc/lxc#2878]
* Distribution:Ubuntu 
 * Distribution version:Ubuntu 18.04.2
 * The output of
   * `lxc-start --version` 3.0.3
   * `lxc-checkconfig`
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.15.0-36-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
newuidmap is not installed
newgidmap is not installed
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/devices
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/memory
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/blkio
/sys/fs/cgroup/rdma
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/freezer
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/pids

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -a` 
Linux base-cph3d15-lxchost7 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
12:pids:/user.slice/user-3036.slice/session-94.scope
11:hugetlb:/
10:freezer:/
9:perf_event:/
8:cpuset:/
7:rdma:/
6:blkio:/user.slice
5:cpu,cpuacct:/user.slice
4:memory:/user.slice
3:net_cls,net_prio:/
2:devices:/user.slice
1:name=systemd:/user.slice/user-3036.slice/session-94.scope
0::/user.slice/user-3036.slice/session-94.scope

   * `cat /proc/1/mounts`

# Issue description

When we stop lxc CT, sometimes it takes up to 4 min to shutdown veth interface associated 

Feb 21 14:09:48 host kernel: brU: port 2(veth1CC9EF8DAB) entered disabled state
Feb 21 14:10:07 host systemd[1]: Stopped LXC Container: guest.ct

But the veth1CC9EF8DAB remains for variable period of time (sometimes 4-5 min ), during this time CT can  not be started

Feb 21 14:10:07 host lxc-start[43345]: lxc-start: guest.ct: network.c: instantiate_veth: 106 Operation not permitted - Failed to create veth pair "veth1CC9EF8DAB" and "vethAWMWA9"

**Comment by stgraber** [comment]
Sounds like your kernel is having a hard time flushing the container's previous network namespace which would explain why that device isn't going away and causing the startup conflict.

It's a good thing that LXC doesn't let you start it though as otherwise you'd just end up with two veths that have the exact same MAC and potentially IP too, causing a whole bunch of weird conflicts.

The question though is why isn't that namespace going away instantly when the last process is gone from it.

How reliable do you reprodce this in your setup?

**Comment by bobykus31** [comment]
It might be, we use Ubuntu Bionic stock kernel,  I do not have any specific numbers yet, sometimes it release veth interface almost instantly,  but once I see it was active like 4 min, f.ex.
Thu Feb 21 10:37:50 UTC 2019 guest stopped,  Feb 21 10:41:48 interface is shut down. I will do more detailed investigation perhaps...

**Comment by pfak** [comment]
My workaround as a `lxc.hook.post-stop` hook:

``
#!/usr/bin/env bash
# https://github.com/lxc/lxc/issues/2878

LXC_INTERFACES=$(ip link show | sed -n -E "s/^[0-9]+: ($LXC_NAME-[0-9]+)@.*/\1/p")
if [ -z "$LXC_INTERFACES" ]; then
	exit 0
fi

for interface in $LXC_INTERFACES; do
	ip link set $interface down
	ip link delete $interface
done
``

**Comment by pfak** [comment]
My workaround as a `lxc.hook.post-stop` hook:

```
#!/usr/bin/env bash
# https://github.com/lxc/lxc/issues/2878

LXC_INTERFACES=$(ip link show | sed -n -E "s/^[0-9]+: ($LXC_NAME-[0-9]+)@.*/\1/p")
if [ -z "$LXC_INTERFACES" ]; then
	exit 0
fi

for interface in $LXC_INTERFACES; do
	ip link set $interface down
	ip link delete $interface
done
```

**Comment by pfak** [comment]
I created a hook on post-stop to delete the veth interface, and I'm able to restart containers now.

**Comment by mphilipps** [comment]
Same issue here. Host is Debian Buster.

Kernel: 4.19.0-6-amd64
lxc: 1:3.1.0+really3.0.3-8

I can reproduce it like 50% of the time and  if it isn't remove instantly it take 4 minutes for the host veth pair end to go away.

The network namespace itself always disappears instantly in the lsns output.

**Comment by brauner** [comment]
LXC no explicitly removes the host side veth device if it has created it. So this should hopefully be fixed. If not reopen, please. (Try to reproduce with master, please.)
