### ISSUE TITLE
lxc_start - start.c:start:1431 - Invalid argument - Failed to exec "/sbin/init".

### ISSUE THREAD

**Issue by zhankgun** [lxc/lxc#2883]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution:
 * Distribution version:2.0.7
 * The output of
   * `lxc-start --version`
# lxc-start --version
2.0.7
   * `lxc-checkconfig`
all enabled
   * `uname -a`
Linux ttu 3.10.65 #43 SMP PREEMPT Thu Feb 28 18:44:37 CST 2019 armv7l GNU/Linux
   * `cat /proc/self/cgroup`
# cat /proc/self/cgroup 
7:devices:/system.slice/sshd.service
6:cpuset:/
5:memory:/
4:freezer:/
3:debug:/
2:cpuacct,cpu:/
1:name=systemd:/system.slice/sshd.service

   * `cat /proc/1/mounts`

rootfs / rootfs rw 0 0
/dev/root / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
devtmpfs /dev devtmpfs rw,relatime,size=109932k,nr_inodes=27483,mode=755 0 0
sysfs /sys sysfs rw,relatime 0 0
proc /proc proc rw,relatime 0 0
tmpfs /dev/shm tmpfs rw 0 0
devpts /dev/pts devpts rw,relatime,gid=5,mode=620,ptmxmode=666 0 0
tmpfs /run tmpfs rw,nosuid,nodev,mode=755 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct,cpu 0 0
cgroup /sys/fs/cgroup/debug cgroup rw,nosuid,nodev,noexec,relatime,debug 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
tmpfs /tmp tmpfs rw,relatime 0 0

# Issue description
I am starting a lxc container and meet an issue that Failed to exec "/sbin/init", it reported Invalid argument.
It seems something wrong with systemd,

I attached the debug log of lxc-start below, could someone help me analysis it and give me some suggestion?

A brief description of what failed or what could be improved.

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

      lxc-start 20161103172912.474 INFO     lxc_start_ui - tools/lxc_start.c:main:275 - using rcfile /mnt/internal_storage/lxc_dir/lxc01/config
      lxc-start 20161103172912.864 WARN     lxc_confile - confile.c:config_pivotdir:1910 - lxc.pivotdir is ignored.  It will soon become an error.
      lxc-start 20161103172912.267 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:309 - Going to wait for pid 1660.
      lxc-start 20161103172912.294 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:328 - Trying to sync with child process.
      lxc-start 20161103172912.318 INFO     lxc_start - start.c:lxc_check_inherited:235 - Closed inherited fd: 3.
      lxc-start 20161103172912.325 INFO     lxc_start - start.c:lxc_check_inherited:235 - Closed inherited fd: 5.
      lxc-start 20161103172912.331 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:366 - Using pipe file descriptor 6 for monitord.
      lxc-start 20161103172912.846 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:343 - Sucessfully synced with child process.
      lxc-start 20161103172912.878 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:312 - Finished waiting on pid 1660.
      lxc-start 20161103172912.898 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:804 - Attempting to set proc title to [lxc monitor] /mnt/internal_storage/lxc_dir lxc01
      lxc-start 20161103172912.927 INFO     lxc_utils - utils.c:setproctitle:1519 - setting cmdline failed - Invalid argument
      lxc-start 20161103172912.967 INFO     lxc_start - start.c:lxc_check_inherited:235 - Closed inherited fd: 3.
      lxc-start 20161103172912.991 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:309 - Going to wait for pid 1664.
      lxc-start 20161103172912.995 DEBUG    lxc_start - start.c:setup_signal_fd:273 - Set SIGCHLD handler with file descriptor: 5.
      lxc-start 20161103172912.101 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:328 - Trying to sync with child process.
      lxc-start 20161103172912.103 INFO     lxc_start - start.c:lxc_check_inherited:235 - Closed inherited fd: 3.
      lxc-start 20161103172912.104 INFO     lxc_start - start.c:lxc_check_inherited:235 - Closed inherited fd: 5.
      lxc-start 20161103172912.105 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:366 - Using pipe file descriptor 6 for monitord.
      lxc-start 20161103172912.110 DEBUG    console - console.c:lxc_console_peer_default:468 - no console peer
      lxc-start 20161103172912.110 INFO     lxc_start - start.c:lxc_init:475 - Container "lxc01" is initialized.
      lxc-start 20161103172912.154 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:343 - Sucessfully synced with child process.
      lxc-start 20161103172912.158 DEBUG    lxc_monitor - monitor.c:lxc_monitord_spawn:312 - Finished waiting on pid 1664.
      lxc-start 20161103172912.158 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:185 - Using monitor socket name "lxc/3b5277283f1f92c1//mnt/internal_storage/lxc_dir".
      lxc-start 20161103172912.198 DEBUG    lxc_start - start.c:__lxc_start:1317 - Not dropping CAP_SYS_BOOT or watching utmp.
      lxc-start 20161103172912.247 INFO     lxc_conf - conf.c:instantiate_veth:2647 - Retrieved mtu 1500 from lxcbr0
      lxc-start 20161103172912.256 INFO     lxc_conf - conf.c:instantiate_veth:2672 - Attached 'veth55YOVO': to the bridge 'lxcbr0': 
      lxc-start 20161103172912.265 DEBUG    lxc_conf - conf.c:instantiate_veth:2689 - instantiated veth 'veth55YOVO/veth4GECET', index is '10'
      lxc-start 20161103172912.266 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for lxc01
      lxc-start 20161103172912.276 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:filter_and_set_cpus:452 - Path: /sys/devices/system/cpu/isolated to read isolated cpus from does not exist.

      lxc-start 20161103172912.276 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:filter_and_set_cpus:459 - Copying cpuset of parent cgroup.
      lxc-start 20161103172912.392 INFO     lxc_start - start.c:lxc_spawn:1154 - Cloned CLONE_NEWNS.
      lxc-start 20161103172912.393 INFO     lxc_start - start.c:lxc_spawn:1154 - Cloned CLONE_NEWPID.
      lxc-start 20161103172912.393 INFO     lxc_start - start.c:lxc_spawn:1154 - Cloned CLONE_NEWUTS.
      lxc-start 20161103172912.393 INFO     lxc_start - start.c:lxc_spawn:1154 - Cloned CLONE_NEWIPC.
      lxc-start 20161103172912.393 INFO     lxc_start - start.c:lxc_spawn:1154 - Cloned CLONE_NEWNET.
      lxc-start 20161103172912.397 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.deny' set to 'a'
      lxc-start 20161103172912.398 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c *:* m'
      lxc-start 20161103172912.398 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'b *:* m'
      lxc-start 20161103172912.398 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 1:3 rwm'
      lxc-start 20161103172912.398 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 1:5 rwm'
      lxc-start 20161103172912.398 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 1:7 rwm'
      lxc-start 20161103172912.398 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 5:0 rwm'
      lxc-start 20161103172912.398 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 5:1 rwm'
      lxc-start 20161103172912.398 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 5:2 rwm'
      lxc-start 20161103172912.399 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 1:8 rwm'
      lxc-start 20161103172912.399 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 1:9 rwm'
      lxc-start 20161103172912.399 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 136:* rwm'
      lxc-start 20161103172912.399 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 10:229 rwm'
      lxc-start 20161103172912.399 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 254:0 rm'
      lxc-start 20161103172912.399 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 10:200 rwm'
      lxc-start 20161103172912.399 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 10:228 rwm'
      lxc-start 20161103172912.399 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 10:232 rwm'
      lxc-start 20161103172912.400 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'memory.limit_in_bytes' set to '52428800'
      lxc-start 20161103172912.400 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 250:0 rwm'
      lxc-start 20161103172912.400 INFO     lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1958 - cgroup has been setup
      lxc-start 20161103172912.461 DEBUG    lxc_conf - conf.c:lxc_assign_network:3185 - move 'veth4GECET'/'(null)' to '1695': .
      lxc-start 20161103172912.472 INFO     lxcoverlay - bdev/lxcoverlay.c:ovl_mount:421 - Overlayfs: Error mounting /mnt/internal_storage/lxc_dir/lxc01/armhf.img_mnt onto /usr/lib/lxc/rootfs with options upperdir=/mnt/internal_storage/lxc_dir/lxc01/lxc01_data_dir/upperdir,lowerdir=/mnt/internal_storage/lxc_dir/lxc01/armhf.img_mnt,workdir=/mnt/internal_storage/lxc_dir/lxc01/lxc01_data_dir/olwork. Retrying without workdir: Invalid argument.
      lxc-start 20161103172912.473 INFO     lxcoverlay - bdev/lxcoverlay.c:ovl_mount:433 - Overlayfs: Mounted /mnt/internal_storage/lxc_dir/lxc01/armhf.img_mnt onto /usr/lib/lxc/rootfs with options upperdir=/mnt/internal_storage/lxc_dir/lxc01/lxc01_data_dir/upperdir,lowerdir=/mnt/internal_storage/lxc_dir/lxc01/armhf.img_mnt.
      lxc-start 20161103172912.473 DEBUG    lxc_conf - conf.c:setup_rootfs:1273 - mounted 'overlayfs:/mnt/internal_storage/lxc_dir/lxc01/armhf.img_mnt:/mnt/internal_storage/lxc_dir/lxc01/lxc01_data_dir/upperdir' on '/usr/lib/lxc/rootfs'
      lxc-start 20161103172912.474 INFO     lxc_conf - conf.c:setup_utsname:901 - 'lxc01' hostname has been setup
      lxc-start 20161103172912.529 DEBUG    lxc_conf - conf.c:setup_hw_addr:2225 - mac address '00:16:3e:6b:e3:26' on 'eth0' has been setup
      lxc-start 20161103172912.565 DEBUG    lxc_conf - conf.c:setup_netdev:2452 - 'eth0' has been setup
      lxc-start 20161103172912.565 INFO     lxc_conf - conf.c:setup_network:2473 - network has been setup
      lxc-start 20161103172912.566 INFO     lxc_conf - conf.c:mount_autodev:1130 - Mounting container /dev
      lxc-start 20161103172912.567 INFO     lxc_conf - conf.c:mount_autodev:1153 - Mounted tmpfs onto /usr/lib/lxc/rootfs/dev
      lxc-start 20161103172912.568 INFO     lxc_conf - conf.c:mount_autodev:1171 - Mounted container /dev
      lxc-start 20161103172912.581 DEBUG    lxc_conf - conf.c:mount_entry:1715 - remounting /sys/fs/fuse/connections on /usr/lib/lxc/rootfs/sys/fs/fuse/connections to respect bind or remount options
      lxc-start 20161103172912.582 DEBUG    lxc_conf - conf.c:mount_entry:1730 - (at remount) flags for /sys/fs/fuse/connections was 4096, required extra flags are 0
      lxc-start 20161103172912.582 DEBUG    lxc_conf - conf.c:mount_entry:1739 - mountflags already was 4096, skipping remount
      lxc-start 20161103172912.582 DEBUG    lxc_conf - conf.c:mount_entry:1765 - mounted '/sys/fs/fuse/connections' on '/usr/lib/lxc/rootfs/sys/fs/fuse/connections', type 'none'
      lxc-start 20161103172912.582 INFO     lxc_conf - conf.c:mount_file_entries:1985 - mount points have been setup
      lxc-start 20161103172912.586 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1560 - Remounted /usr/lib/lxc/rootfs/sys/fs/cgroup/systemd read-only
      lxc-start 20161103172912.586 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1566 - Mounting /sys/fs/cgroup/systemd//lxc/lxc01 onto /usr/lib/lxc/rootfs/sys/fs/cgroup/systemd//lxc/lxc01
      lxc-start 20161103172912.586 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1574 - Completed second stage cgroup automounts for /usr/lib/lxc/rootfs/sys/fs/cgroup/systemd//lxc/lxc01
      lxc-start 20161103172912.589 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1560 - Remounted /usr/lib/lxc/rootfs/sys/fs/cgroup/cpu read-only
      lxc-start 20161103172912.589 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1566 - Mounting /sys/fs/cgroup/cpu//lxc/lxc01 onto /usr/lib/lxc/rootfs/sys/fs/cgroup/cpu//lxc/lxc01
      lxc-start 20161103172912.589 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1574 - Completed second stage cgroup automounts for /usr/lib/lxc/rootfs/sys/fs/cgroup/cpu//lxc/lxc01
      lxc-start 20161103172912.591 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1560 - Remounted /usr/lib/lxc/rootfs/sys/fs/cgroup/cpuset read-only
      lxc-start 20161103172912.592 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1566 - Mounting /sys/fs/cgroup/cpuset//lxc/lxc01 onto /usr/lib/lxc/rootfs/sys/fs/cgroup/cpuset//lxc/lxc01
      lxc-start 20161103172912.592 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1574 - Completed second stage cgroup automounts for /usr/lib/lxc/rootfs/sys/fs/cgroup/cpuset//lxc/lxc01
      lxc-start 20161103172912.594 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1560 - Remounted /usr/lib/lxc/rootfs/sys/fs/cgroup/debug read-only
      lxc-start 20161103172912.594 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1566 - Mounting /sys/fs/cgroup/debug//lxc/lxc01 onto /usr/lib/lxc/rootfs/sys/fs/cgroup/debug//lxc/lxc01
      lxc-start 20161103172912.595 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1574 - Completed second stage cgroup automounts for /usr/lib/lxc/rootfs/sys/fs/cgroup/debug//lxc/lxc01
      lxc-start 20161103172912.597 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1560 - Remounted /usr/lib/lxc/rootfs/sys/fs/cgroup/devices read-only
      lxc-start 20161103172912.597 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1566 - Mounting /sys/fs/cgroup/devices//lxc/lxc01 onto /usr/lib/lxc/rootfs/sys/fs/cgroup/devices//lxc/lxc01
      lxc-start 20161103172912.597 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1574 - Completed second stage cgroup automounts for /usr/lib/lxc/rootfs/sys/fs/cgroup/devices//lxc/lxc01
      lxc-start 20161103172912.600 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1560 - Remounted /usr/lib/lxc/rootfs/sys/fs/cgroup/memory read-only
      lxc-start 20161103172912.600 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1566 - Mounting /sys/fs/cgroup/memory//lxc/lxc01 onto /usr/lib/lxc/rootfs/sys/fs/cgroup/memory//lxc/lxc01
      lxc-start 20161103172912.600 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1574 - Completed second stage cgroup automounts for /usr/lib/lxc/rootfs/sys/fs/cgroup/memory//lxc/lxc01
      lxc-start 20161103172912.602 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1560 - Remounted /usr/lib/lxc/rootfs/sys/fs/cgroup/freezer read-only
      lxc-start 20161103172912.602 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1566 - Mounting /sys/fs/cgroup/freezer//lxc/lxc01 onto /usr/lib/lxc/rootfs/sys/fs/cgroup/freezer//lxc/lxc01
      lxc-start 20161103172912.603 INFO     lxc_cgfsng - cgroups/cgfsng.c:do_secondstage_mounts_if_needed:1574 - Completed second stage cgroup automounts for /usr/lib/lxc/rootfs/sys/fs/cgroup/freezer//lxc/lxc01
      lxc-start 20161103172912.603 INFO     lxc_conf - conf.c:fill_autodev:1199 - Creating initial consoles under container /dev
      lxc-start 20161103172912.603 INFO     lxc_conf - conf.c:fill_autodev:1210 - Populating container /dev
      lxc-start 20161103172912.604 INFO     lxc_conf - conf.c:fill_autodev:1247 - Populated container /dev
      lxc-start 20161103172912.605 INFO     lxc_conf - conf.c:setup_dev_console:1495 - console has been setup
      lxc-start 20161103172912.607 INFO     lxc_utils - utils.c:mount_proc_if_needed:1785 - I am 1, /proc/self points to '1'
      lxc-start 20161103172912.611 DEBUG    lxc_conf - conf.c:setup_rootfs_pivot_root:1108 - pivot_root syscall to '/usr/lib/lxc/rootfs' successful
      lxc-start 20161103172912.615 DEBUG    lxc_conf - conf.c:lxc_create_tty:3429 - allocated pty '/dev/pts/0' (9/12)
      lxc-start 20161103172912.617 DEBUG    lxc_conf - conf.c:lxc_create_tty:3429 - allocated pty '/dev/pts/1' (13/14)
      lxc-start 20161103172912.618 DEBUG    lxc_conf - conf.c:lxc_create_tty:3429 - allocated pty '/dev/pts/2' (15/16)
      lxc-start 20161103172912.620 DEBUG    lxc_conf - conf.c:lxc_create_tty:3429 - allocated pty '/dev/pts/3' (17/18)
      lxc-start 20161103172912.620 INFO     lxc_conf - conf.c:lxc_create_tty:3440 - tty's configured
      lxc-start 20161103172912.623 INFO     lxc_conf - conf.c:setup_tty:1053 - 4 tty(s) has been setup
      lxc-start 20161103172912.644 INFO     lxc_conf - conf.c:setup_personality:1451 - set personality to '0x8'
      lxc-start 20161103172912.644 DEBUG    lxc_conf - conf.c:setup_caps:2135 - drop capability 'mac_admin' (33)
      lxc-start 20161103172912.644 DEBUG    lxc_conf - conf.c:setup_caps:2135 - drop capability 'mac_override' (32)
      lxc-start 20161103172912.645 DEBUG    lxc_conf - conf.c:setup_caps:2135 - drop capability 'sys_time' (25)
      lxc-start 20161103172912.645 DEBUG    lxc_conf - conf.c:setup_caps:2135 - drop capability 'sys_module' (16)
      lxc-start 20161103172912.645 DEBUG    lxc_conf - conf.c:setup_caps:2135 - drop capability 'sys_rawio' (17)
      lxc-start 20161103172912.645 DEBUG    lxc_conf - conf.c:setup_caps:2144 - capabilities have been setup
      lxc-start 20161103172912.645 NOTICE   lxc_conf - conf.c:lxc_setup:3977 - 'lxc01' is setup.
      lxc-start 20161103172912.646 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.deny' set to 'a'
      lxc-start 20161103172912.646 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c *:* m'
      lxc-start 20161103172912.647 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'b *:* m'
      lxc-start 20161103172912.647 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 1:3 rwm'
      lxc-start 20161103172912.647 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 1:5 rwm'
      lxc-start 20161103172912.648 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 1:7 rwm'
      lxc-start 20161103172912.648 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 5:0 rwm'
      lxc-start 20161103172912.648 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 5:1 rwm'
      lxc-start 20161103172912.649 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 5:2 rwm'
      lxc-start 20161103172912.649 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 1:8 rwm'
      lxc-start 20161103172912.649 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 1:9 rwm'
      lxc-start 20161103172912.650 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 136:* rwm'
      lxc-start 20161103172912.650 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 10:229 rwm'
      lxc-start 20161103172912.650 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 254:0 rm'
      lxc-start 20161103172912.650 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 10:200 rwm'
      lxc-start 20161103172912.651 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 10:228 rwm'
      lxc-start 20161103172912.651 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 10:232 rwm'
      lxc-start 20161103172912.651 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'memory.limit_in_bytes' set to '52428800'
      lxc-start 20161103172912.652 DEBUG    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1954 - cgroup 'devices.allow' set to 'c 250:0 rwm'
      lxc-start 20161103172912.652 INFO     lxc_cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits:1958 - cgroup has been setup
      lxc-start 20161103172912.653 NOTICE   lxc_start - start.c:start:1428 - Exec'ing "/sbin/init".
      lxc-start 20161103172912.654 ERROR    lxc_start - start.c:start:1431 - Invalid argument - Failed to exec "/sbin/init".
      lxc-start 20161103172912.654 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
      lxc-start 20161103172912.655 ERROR    lxc_start - start.c:__lxc_start:1346 - Failed to spawn container "lxc01".
      lxc-start 20161103172912.658 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - Command get_cgroup failed to receive response: Connection reset by peer.
      lxc-start 20161103172912.659 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:1235 - cgroup_rmdir: failed to delete /sys/fs/cgroup/systemd//lxc/lxc01: Device or resource busy
      lxc-start 20161103172912.659 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/systemd//lxc/lxc01
      lxc-start 20161103172912.661 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:1235 - cgroup_rmdir: failed to delete /sys/fs/cgroup/cpu//lxc/lxc01: Device or resource busy
      lxc-start 20161103172912.661 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/cpu//lxc/lxc01
      lxc-start 20161103172912.664 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:1235 - cgroup_rmdir: failed to delete /sys/fs/cgroup/cpuset//lxc/lxc01: Device or resource busy
      lxc-start 20161103172912.664 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/cpuset//lxc/lxc01
      lxc-start 20161103172912.666 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:1235 - cgroup_rmdir: failed to delete /sys/fs/cgroup/debug//lxc/lxc01: Device or resource busy
      lxc-start 20161103172912.666 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/debug//lxc/lxc01
      lxc-start 20161103172912.668 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:1235 - cgroup_rmdir: failed to delete /sys/fs/cgroup/devices//lxc/lxc01: Device or resource busy
      lxc-start 20161103172912.668 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/devices//lxc/lxc01
      lxc-start 20161103172912.673 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:1235 - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory//lxc/lxc01: Device or resource busy
      lxc-start 20161103172912.673 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/memory//lxc/lxc01
      lxc-start 20161103172912.674 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgroup_rmdir:1235 - cgroup_rmdir: failed to delete /sys/fs/cgroup/freezer//lxc/lxc01: Device or resource busy
      lxc-start 20161103172912.674 ERROR    lxc_cgfsng - cgroups/cgfsng.c:recursive_destroy:1270 - Error destroying /sys/fs/cgroup/freezer//lxc/lxc01
      lxc-start 20161103172917.664 ERROR    lxc_start_ui - tools/lxc_start.c:main:366 - The container failed to start.
      lxc-start 20161103172917.664 ERROR    lxc_start_ui - tools/lxc_start.c:main:368 - To get more details, run the container in foreground mode.
      lxc-start 20161103172917.664 ERROR    lxc_start_ui - tools/lxc_start.c:main:370 - Additional information can be obtained by setting the --logfile and --logpriority options.

**Comment by zhankgun** [comment]
I added debug log in lxc_start.c and found the args which passed in c->start is default_args.
char *const default_args[] = {
		"/sbin/init",
		NULL,
	};

**Comment by brauner** [comment]
This looks like an issue with your system. It seems that the kernel doesn't recognize the format of the binary.

**Comment by brauner** [comment]
What does `uname -a` on your systems show and what does the container's config look like?

**Comment by zhankgun** [comment]
Thanks Brauner.
Yes it is a kernel  issue.  I made an kernel upgrade and new kernel failed to resolute the overlayfs configuration. It failed to read the upper and lower dir.
This issue is fixed now  ；）
