### ISSUE TITLE
LXC master compile failure on CentOS 7 -Werror=maybe-uninitialized and -Werror=unused-variable

### ISSUE THREAD

**Issue by tomponline** [lxc/lxc#2885]
# Required information

 * Distribution: CentOS
 * Distribution version: 7
 * GCC version: 4.8.5-36.el7

# Issue description

Recent changes in the master branch since 3.1.0 was tagged mean that using the RPM spec and building on CentOS 7 doesn't complete any more.

There are a few errors to do with uninitialised files, I've tried fixing some of them, but before I go further I wanted to get clarification on what the newly introduced `__do_free` is for, as several of the compile errors so far are in the form:

```
In file included from confile.c:56:0:
confile.c: In function 'do_append_unexp_config_line':
memory_utils.h:35:6: error: 'tmp' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  free(*(void **)p);
      ^
confile.c:2714:18: note: 'tmp' was declared here
  __do_free char *tmp;
```

Before this was introduced, the variables were defined locally in the function.

There is also an unused variable here https://github.com/lxc/lxc/blob/master/src/lxc/attach.c#L162 that is causing the compile to fail. And another in `conf.c`:

```
conf.c: In function 'idmaptool_on_path_and_privileged':
conf.c:2816:6: error: unused variable 'fret' [-Werror=unused-variable]
  int fret = 0;
```

# Steps to reproduce

 1. Step one
Use rpm spec file to build on CentOs 7. Uses the following `./configure` command:

```
./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-systemdsystemunitdir=/usr/lib/systemd/system --with-runtime-path=/var/run --disable-rpath --with-init-script=systemd
```

Uses the following flags env vars:

```
CFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic'
export CFLAGS
CXXFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic'
export CXXFLAGS
FFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -I/usr/lib64/gfortran/modules'
export FFLAGS
FCFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -I/usr/lib64/gfortran/modules'
export FCFLAGS
LDFLAGS='-Wl,-z,relro '
export LDFLAGS
```
 2. Step two
 3. Step three

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
 - [ ] the containers configuration file

**Comment by tomponline** [comment]
Its caused by the ` -Wall` flag added to CFLAGS by rpmbuild by default.

**Comment by brauner** [comment]
They are compiler-cleanup macros that do cleanup based on scope.

**Comment by tomponline** [comment]
Thanks @brauner I can see how you want to fix these from https://github.com/brauner/lxc/commit/0cacddda88fad144264d82c3ab05e478cd2d72e9 so I'll run through and fix them up. Thanks
