### ISSUE TITLE
lxc-checkconfig line 103 [: too many arguments

### ISSUE THREAD

**Issue by sir-ragna** [lxc/lxc#290]
Version tag `lxc-1.0.5`.

When running `lxc-checkconfig` I get a `line 103: [: too many arguments` and `line 118: [: -gt: unary operator expected`. Most output is still displayed correctly though.

![lxc-check](https://cloud.githubusercontent.com/assets/1280559/3801009/3dd7a60c-1bff-11e4-8a82-76d78a2abb6e.png)
This is on a freshly installed CentOS-6.5-minimal

**Comment by bonidier** [comment]
Hi,

Following your exchanges and  @dwengen comment, I've fixed **lxc-checkconfig** script for parsing old and new kernel config file about Kernel release

Regards

**suggestion:**
```shell
# diff -u /usr/bin/lxc-checkconfig lxc-checkconfig 
--- /usr/bin/lxc-checkconfig    2014-12-07 20:12:15.000000000 +0100
+++ lxc-checkconfig     2015-02-05 17:55:15.000000000 +0100
@@ -78,13 +78,13 @@
 }
 
 CGROUP_MNT_PATH=`print_cgroups cgroup /proc/self/mounts | head -n 1`
-KVER_MAJOR=$($GREP '^# Linux.*Kernel Configuration' $CONFIG | \
+KVER_MAJOR=$($GREP -E '^# Linux.*(Kernel Configuration|kernel version)' $CONFIG | \
     sed -r 's/.* ([0-9])\.[0-9]{1,2}\.[0-9]{1,3}.*/\1/')
 if [ "$KVER_MAJOR" = "2" ]; then
-KVER_MINOR=$($GREP '^# Linux.*Kernel Configuration' $CONFIG | \
+KVER_MINOR=$($GREP -E '^# Linux.*(Kernel Configuration|kernel version)' $CONFIG | \
     sed -r 's/.* 2.6.([0-9]{2}).*/\1/')
 else
-KVER_MINOR=$($GREP '^# Linux.*Kernel Configuration' $CONFIG | \
+KVER_MINOR=$($GREP -E '^# Linux.*(Kernel Configuration|kernel version)' $CONFIG | \
     sed -r 's/.* [0-9]\.([0-9]{1,3})\.[0-9]{1,3}.*/\1/')
 fi
```

**Comment by brauner** [comment]
`LXC 1.1.*` is marked deprecated and `lxc-checkconfig` in newer `LXC` versions seems to work fine.

**Comment by z3ntu** [comment]
With lxc 2.0.6 (Arch Linux) I get:
```
# env CONFIG=kernel/arch/arm/configs/fairphone_defconfig lxc-checkconfig
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: missing
/usr/bin/lxc-checkconfig: line 92: [: -lt: unary operator expected
/usr/bin/lxc-checkconfig: line 92: [: -eq: unary operator expected

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: /usr/bin/lxc-checkconfig: line 117: [: -ge: unary operator expected
/usr/bin/lxc-checkconfig: line 117: [: -gt: unary operator expected
enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: missing
Macvlan: missing
Vlan: missing
Bridges: enabled
Advanced netfilter: missing
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: missing
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: missing
FUSE (for use with lxcfs): enabled

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: missing
CONFIG_EVENTFD: missing
CONFIG_EPOLL: missing
CONFIG_UNIX_DIAG: missing
CONFIG_INET_DIAG: missing
CONFIG_PACKET_DIAG: missing
CONFIG_NETLINK_DIAG: missing
File capabilities: /usr/bin/lxc-checkconfig: line 152: [: -gt: unary operator expected

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```

**Comment by Blub** [comment]
Since you're on ArchLinux and it says `User namespace: enabled` I wonder what kernel you're on? What's the output of `uname -a` and `zgrep '# Linux.*Kernel Configuration' /proc/config.gz` (the latter being the one `lxc-checkconfig` actually uses`).

In any case, the script should probably check for empty variables rather than using them unquoted in a call to `/bin/[`

**Comment by z3ntu** [comment]
Well I was following https://community.kde.org/Plasma/Mobile/Porting and the script should check the kernel config for an arm kernel for Android. Maybe it's not clear what that guide wants but it would still be great if there was some output which isn't a syntax error message ;)

**Comment by Blub** [comment]
Sure, it would still be nice to know the version outputs (the 2 commands I pasted above) to see why the script fails to fill the version variables.

**Comment by z3ntu** [comment]
Sorry
```
[luca@g550jk ~]$ uname -a
Linux g550jk 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
[luca@g550jk ~]$ zgrep '# Linux.*Kernel Configuration' /proc/config.gz
# Linux/x86 4.8.13-1 Kernel Configuration
```

**Comment by Blub** [comment]
Oh wait, I missed the `CONFIG=kernel/arch/arm/configs/fairphone_defconfig` part...
That file probably doesn't contain the kernel version information. Not sure how what the expected behavior should be then.

**Comment by z3ntu** [comment]
That defconfig is that one: https://github.com/z3ntu/android_kernel_fairphone_fp2/blob/aosp-5.1/arch/arm/configs/fairphone_defconfig
