### ISSUE TITLE
Lxc container network reachability  acrosss different physical hosts

### ISSUE THREAD

**Issue by selvakumars3** [lxc/lxc#2908]
Hi All,
I have a question regarding LXC container networking configuration so that I can reach the LXC container from different hosts.
My requirement is I have two hosts , host A and host B and I tried to spawn a lxc container on B , I wanted to reach the lxc container on B from host A.
How it is acheived? your help is greatly appreciated

**Comment by stgraber** [comment]
You can bridge to the physical network or use macvlan or ipvlan.

You can also have private bridges with separate subnets and routes place on the host, or even use VPNs or software defined network solutions.

LXC isn't very specific here, all we care about is a working bridge :)
