### ISSUE TITLE
Live migration with openvswitch

### ISSUE THREAD

**Issue by haha150** [lxc/lxc#2909]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version: 3.11 from snap
   * Storage backend in use: btrfs

# Issue description

I am trying to use openvswitch instead of the lxdbr0 and i am able to do so but i cannot live migrate a container attached to the openvswitch to another remote. The two machines are exactly the same and both run openvswitch with the same name of the switch etc. So when i do "lxc move c1 remote2:", i get the error that the restore fails because it cannot attach the vethXXXX interface to the openvswitch at the destionation. Am i doing something wrong?

# Steps to reproduce

assume that i have one container and two remotes running alpine/edge container

lxc network create ovs-1 bridge.driver=openvswitch
ovs-vsctl add-port ovs-1 enp0s8
lxc network attach-profile ovs-1 default eth0
lxc launch images:alpine/edge c1
lxc move c1 remote2: <---error

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Moving issue over to liblxc for now as it looks like we'll need some extra criu logic in here.

**Comment by adrianreber** [comment]
> @adrianreber I wonder, can we just tell CRIU to restore the veth but not connect it?
> If we have the name of the host side veth, then it becomes easy for liblxc to call our existing bridge attach function on it post-restore.

Not sure. I would say that it is not possible right now, but I am sure @avagin knows it better.

@avagin and ideas how to handle a veth which is connected to openvswitch?

**Comment by brauner** [comment]
This is a missing feature of criu. So closing the liblxc side for now.
