### ISSUE TITLE
Passing arguments to LXC hooks needs double escaping

### ISSUE THREAD

**Issue by Mic92** [lxc/lxc#291]
The function `run_lxc_hooks()`, which is currently used for excecuting lxc hooks, uses `lxc_popen()` to run hooks. `lxc_popen` spawns a shell for each command like this:

```
sh -c "command"
```

Arguments are passed to lxc-clone are passed like this:

```
lxc-clone -o base -n newcontainer -- --hook-option='hook value with spaces'
```

lxc_popen execute the following

```
sh -c "/path/to/hook.sh --hook-option=hook with spaces"
```

In my use case I want to pass json via commandline to ansible:

```
sudo lxc-clone -o base -n owncloud -- "--group php --vars='{\"php_extensions\":[\"pgsql\",\"pdo_pgsql\"]}'"
```

Wouldn't it not be a better option to use execlp(3) instead, where arguments can be passed as an null-terminated array?

**Comment by brauner** [comment]
We currently have no intention of changing this but we'd consider a pull request.
