### ISSUE TITLE
Regression in LXD/LXC removing Openvswitch bridge

### ISSUE THREAD

**Issue by nfrntrd** [lxc/lxc#2913]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: Bionic 18.04
 * The output of "lxc info" (see attached)
   * Kernel version: 4.15.0-46-generic
   * LXC version: 3.0.3 (deb pkg)
   * LXD version: 3.0.3 (deb pkg)
   * Storage backend in use: file

# Issue description

When attempting to apply patches on a server that took LXD/LXC up to 3.0.3 from base 3.0.0 Bionic release, a regression was introduced when stopping a container.  The bridge interface in openvswitch is not removed properly.  There is a dangling reference to the interface in openvswitch and it has to be removed manually.  If a host_name is added to the LXD container definition, it will not allow a container to be restarted as the interface still exists in openvswitch.  Also noticed this in another server that had 3.0.2 installed (Bionic server) and it did not suffer from this issue.  The regression is believed to have happened specifically between 3.0.2 and 3.0.3.  For completeness, also tested on a new server 3.11 snap and experienced the same regression.  Desired outcome is to fix removal of the interface in openvswitch when stopping a container.

# Steps to reproduce

 1. Install baseline Ubuntu server without updates to bring server to LXD 3.0.0
 2. Create a container - start and stop the container.  Observe that interface in openvswitch is created and removed successfully.
 3. Update to LXD 3.0.3 (current deb pkgs available for Bionic)
 4. Restart container and stop it - observe with ovs-vsctl show that the interface isn't removed properly

# Information to attach

Three files attached:
  1. lxc info - lxcinfo.txt
  2. t1 testing container - t1-def.txt
  3. output of ovs-vsctl after stopping container  - ovs-vsctl-aftercontainerstop.txt

[lxcinfo.txt](https://github.com/lxc/lxd/files/2992753/lxcinfo.txt)
[ovs-vsctl-aftercontainerstop.txt](https://github.com/lxc/lxd/files/2992754/ovs-vsctl-aftercontainerstop.txt)
[t1-def.txt](https://github.com/lxc/lxd/files/2992755/t1-def.txt)

**Comment by stgraber** [comment]
Moving over to liblxc as LXD itself doesn't do any direct interaction with openvswitch on container shut down, it's all done by liblxc.

**Comment by stgraber** [comment]
@brauner any idea what may be going on? I remember some refactoring/changes around that code not that long ago.

**Comment by nfrntrd** [comment]
@stgraber I took a look at the network.c but couldn't find anything obvious in the revisions between 3.0.2 and 3.0.3.  I'm a little new to how you do debugging with liblxc so if you can point me in the right direction I can try and give more debug information or debug myself.

**Comment by Milan-Benes** [comment]
@stgraber @brauner Please look at my bugreport: https://github.com/lxc/lxc/issues/2849
It is exactly the same issue

**Comment by stgraber** [comment]
Thanks, lets use the existing bug for this.
