### ISSUE TITLE
lxc-destroy fails on zfs backend

### ISSUE THREAD

**Issue by pgauret** [lxc/lxc#2916]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Alpine Linux
 * Distribution version: 3.9.2
 * The output of
   * `lxc-start --version` 3.1.0
   * `lxc-checkconfig` (Doesn't work as no /proc/config.gz)
   * `uname -a` Linux dedibox-alpine 4.19.29-0-vanilla #1-Alpine SMP Mon Mar 18 21:25:27 UTC 2019 x86_64 Linux
   * `cat /proc/self/cgroup` 1:cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,net_prio,pids:/
   * `cat /proc/1/mounts`

proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
devtmpfs /dev devtmpfs rw,nosuid,relatime,size=10240k,nr_inodes=502504,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
shm /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime 0 0
rpool/ROOT/alpine / zfs rw,relatime,xattr,noacl 0 0
tmpfs /run tmpfs rw,nodev,relatime,size=404248k,mode=755 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup cgroup rw,relatime,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,net_prio,pids 0 0

# Issue description

Deleting a lxc container on a zfs backend fails with the following error message:
lxc-destroy: guest4: storage/zfs.c: zfs_destroy: 619 Failed to detect zfs dataset "rpool/LXC/guest4": cannot open '-H': dataset does not exist

Other lxc commands (creating, starting, stoping, snapshotting the container) work fine.

# Steps to reproduce

 1. Step one

Setup ZFS backend

```
# zfs create -o canmount=off -o mountpoint=none rpool/LXC
# cat /etc/lxc/lxc.conf 
lxc.bdev.zfs.root = rpool/LXC
```

 2. Step two

Create container
```
# lxc-create -t download -n guest4 -f /etc/lxc/default.conf -B zfs -- -d alpine -r 3.9 -a amd64
 Using image from local cache
Unpacking the rootfs

---
You just created an Alpinelinux 3.9 x86_64 (20190324_13:18) container.
dedibox-alpine:~# zfs list
NAME                USED  AVAIL  REFER  MOUNTPOINT
rpool              9.00G   890G    96K  /
rpool/LXC          6.09M   890G    96K  none
rpool/LXC/guest4   6.00M   890G  6.00M  /var/lib/lxc/guest4/rootfs
rpool/ROOT          497M   890G    96K  none
rpool/ROOT/alpine   497M   890G   497M  /
rpool/swap         8.50G   899G    56K  -
```
3. Step three

Delete container
```
# lxc-destroy -n guest4
lxc-destroy: guest4: storage/zfs.c: zfs_destroy: 619 Failed to detect zfs dataset "rpool/LXC/guest4": cannot open '-H': dataset does not exist
lxc-destroy: guest4: lxccontainer.c: container_destroy: 3000 Error destroying rootfs for guest4
lxc-destroy: guest4: tools/lxc_destroy.c: do_destroy: 129 Destroying guest4 failed
```
# Information to attach

Extract from strace around when the error occurs
```
# strace lxc-destroy -n guest4
...
open("/var/lib/lxc/guest4/partial", O_RDWR|O_CLOEXEC) = -1 ENOENT (No such file or directory)
socket(AF_UNIX, SOCK_STREAM, 0)         = 3
connect(3, {sa_family=AF_UNIX, sun_path=@"/var/lib/lxc/guest4/command"}, 30) = -1 ECONNREFUSED (Connection refused)
close(3)                                = 0
stat("/var/lib/lxc/guest4/config", {st_mode=S_IFREG|0640, st_size=761, ...}) = 0
stat("/var/lib/lxc/guest4/lxc_snapshots", 0x7fff31c20de8) = -1 ENOENT (No such file or directory)
rmdir("/var/lib/lxc/guest4/snaps")      = -1 ENOENT (No such file or directory)
socket(AF_UNIX, SOCK_STREAM, 0)         = 3
connect(3, {sa_family=AF_UNIX, sun_path=@"/var/lib/lxc/guest4/command"}, 30) = -1 ECONNREFUSED (Connection refused)
close(3)                                = 0
stat("/var/lib/lxc/guest4/config", {st_mode=S_IFREG|0640, st_size=761, ...}) = 0
stat("/var/lib/lxc/guest4/config", {st_mode=S_IFREG|0640, st_size=761, ...}) = 0
stat("/var/lib/lxcsnaps", 0x7fff31c1fd28) = -1 ENOENT (No such file or directory)
open("/var/lib/lxc/guest4/snaps", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
stat("/var/lib/lxc/guest4/lxc_snapshots", 0x7fff31c1fd68) = -1 ENOENT (No such file or directory)
stat("/var/lib/lxc/guest4/config", {st_mode=S_IFREG|0640, st_size=761, ...}) = 0
open("/run/lxc/lock//var/lib/lxc/.guest4", O_RDWR|O_CREAT|O_NOCTTY|O_NOFOLLOW|O_CLOEXEC, 0600) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fcntl(3, F_OFD_SETLKW, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
socket(AF_UNIX, SOCK_STREAM, 0)         = 4
connect(4, {sa_family=AF_UNIX, sun_path=@"/var/lib/lxc/guest4/command"}, 30) = -1 ECONNREFUSED (Connection refused)
close(4)                                = 0
geteuid()                               = 0
pipe([4, 5])                            = 0
clone(child_stack=NULL, flags=SIGCHLD)  = 5199
close(5)                                = 0
read(4, "cannot open '-H': dataset does n"..., 4095) = 41
...
```
Contents of /var/lib/lxc/guest4/config
```
lxc.include = /usr/share/lxc/config/common.conf
lxc.include = /usr/share/lxc/config/userns.conf
lxc.arch = linux64

lxc.idmap = u 0 100000 65536 
lxc.idmap = g 0 100000 65536
lxc.rootfs.path = zfs:rpool/LXC/guest4
lxc.uts.name = guest4

lxc.net.0.type = veth
lxc.net.0.link = br1
lxc.net.0.flags = up
```

**Comment by streaps** [comment]
I have the exact same problem.

**Comment by pgauret** [comment]
Looks like 'lxc-destroy' calls the 'zfs' command in an incorrect way.
`execve("/usr/sbin/zfs", ["zfs", "get", "type", "-H", "-o", "name", "rpool/LXC/containers/guest99"], 0x7ffe3d0ce998 /* 15 vars */) = 0`

ZFS version is `zfs-0.7.13`

**Comment by streaps** [comment]
Will there be a new release anytime soon?
