### ISSUE TITLE
3.11 doesn't create /sys/fs/cgroup/cpuset/lxc breaking support for CTOP and sysdig

### ISSUE THREAD

**Issue by JoeMattie** [lxc/lxc#2919]
LXC v3.11 (and possibly older) splits
`/sys/fs/cgroup/cpuset/lxc`
into
`/sys/fs/cgroup/cpuset/lxc.monitor` and `/sys/fs/cgroup/cpuset/lxc.payload`

which breaks support for CTOP and sysdig, as both are expecting to find **'/lxc/'** in the path:

Relevant lines:

[CTOP](https://github.com/yadutaf/ctop/blob/1f79336a106ca2045a9f3f16114b13f2927ce473/cgroup_top.py#L289)

[sysdig](https://github.com/draios/sysdig/blob/5bb1ca94a29dc02ae14545653c9b9a72ec21732f/userspace/libsinsp/container_engine/lxc.cpp#L36)

**Comment by stgraber** [comment]
This issue should be reported against the tools that made assumptions about cgroup paths, not against liblxc.

The split on liblxc side was done for good reasons and will not be reverted.

Also worth noting that on cgroupv2 the path may look even more different so those tools probably should be made a bit smarter.
