### ISSUE TITLE
Live migration IP tool fail

### ISSUE THREAD

**Issue by haha150** [lxc/lxc#2925]
# Required information

 * Distribution: Ubuntu 18.04
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 3.11
   * LXD version: 3.11
   * Storage backend in use: btrfs

# Issue description

I keep getting an error when i am migrating a fresh alpine container from A to B then B to A.

ubuntu@local2:~$ lxc move server13 local1:
Error: Failed container creation: Error transferring container data: migration restore failed
(00.002536) Warn  (criu/cr-restore.c:1272): Set CLONE_PARENT | CLONE_NEWPID but it might cause restore problem,because not all kernels support such clone flags combinations!
(00.043305)      1: Error (criu/util.c:816): exited, status=255
(00.043317)      1: Error (criu/net.c:1730): IP tool failed on route restore  
(00.049956)      1: Error (criu/util.c:1563): Can't wait or bad status: errno=0, status=65280
(00.094059) Error (criu/mount.c:3274): mnt: Can't remove the directory /tmp/.criu.mntns.Cc76yS: No such file or directory
(00.094634) Error (criu/cr-restore.c:2300): Restoring FAILED.

# Steps to reproduce
ubuntu@local2-peer1:~$ lxc profile show server1 
config: {}
description: Default LXD profile
devices:
  eth0:
    host_name: veth-server1
    hwaddr: "00:00:00:00:00:11"
    name: eth0
    nictype: p2p
    parent: ovs-1
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: server1
used_by: []

The parent "ovs-1" is an OVS and its there but its not used

 1. lxc launch -p server1 images:alpine/edge server13
 2. lxc exec server13 -- ifconfig eth0 10.0.1.100 netmask 255.255.255.0
 2. lxc move server13 local2:
 3. lxc move server13 local1:     <-----gives error

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Tentatively moving to liblxc as LXD doesn't directly handle CRIU, though this may well be a CRIU issue too.

Can you show both the dump and restore logs on source and target?
You can find those at /var/snap/lxd/common/lxd/logs/NAME

**Comment by haha150** [comment]
Hi, please see attached logs.

[local1.log](https://github.com/lxc/lxc/files/3048420/local1.log)
[local2.log](https://github.com/lxc/lxc/files/3048421/local2.log)

**Comment by stgraber** [comment]
Ok, this looks like a CRIU issue, I first thought it may have to do with the OVS nic but it doesn't, it's failing to restore your loopback device.

Can you look for a matching issue or file a new one at https://github.com/checkpoint-restore/criu

Providing those same restore logs and any `dump` or `pre-dump` logs that you may find too?

Closing our side of this issue.

**Comment by rst0git** [comment]
@haha150  The logs in `local2.log` show that:
```
ip route restore
```
fails with `RTNETLINK answers: Invalid argument`
