### ISSUE TITLE
lxc-start-ephemeral for unprivileged containers

### ISSUE THREAD

**Issue by kirillzlds** [lxc/lxc#293]
Can't start unprivileged ephemeral container. Can't even enable some logging. (lxc.logfile and lxc.loglevel config entries does not help at all)
`lxc-create -t ubuntu-cloud -n uc`
`lxc-start -n uc` - works just nice
`lxc-start-ephemeral -o uc` - The container 'uc-xxxxxxxx' failed to start.
BTW containers created and started from `root` work as expected.

---
UPD: If that helps:
Ubuntu 3.13.0-34-generic x86_64
LXC 1.0.5

**Comment by Meseira** [comment]
I have encountered similar problem with `lxc-start-ephemeral` on my Debian Jessie host. By default, it seems that `lxc-start-ephemeral` uses `overlayfs` but this feature is only available from kernel 3.18 and Jessie comes from 3.16.

My workaround is to deal with `aufs` instead of `overlayfs`:
    lxc-start-ephemeral -o p1 -n p1-eph --union-type aufs -d

Hope that help ;-)

**Comment by megele** [comment]
Sorry for the super late reply. I just tried your suggestion but the version of lxc that ships with Jessie (lxc-1.0.6) says that 
`lxc-start-ephemeral: error: Unprivileged containers may only use overlayfs at this time.`

So how did you get around this one?

**Comment by megele** [comment]
just installed the 3.19 kernel (from sid) on jessie. While lxc-start-ephermeral no longer complains about overlayfs, containers won't start either. 
`$ lxc-start-ephemeral -o p1`
`The container 'p1-z1wstm4j' failed to start.`
Unfortunately, the logfile is entirely empty. As always, any hints or tips appreciated.

**Comment by tenforward** [comment]
I guess...
* lxc-start-ephemeral uses overlayfs or aufs
* only root can use aufs and overlayfs (on vanilla kernel). root in user namespace cannot use.
* But Ubuntu kernel is applied the patch as unpriv user can use overlayfs (I found only RFC https://lists.ubuntu.com/archives/kernel-team/2014-February/038811.html)

I guess the debian kernel is not apply the patch, so unpriv container (root in userns) can't use overlayfs. (I don't know actually whether the patch is applied or not.)

**Comment by tenforward** [comment]
I guess the Ubuntu kernel is applied the patch that root in userns can mount overlayfs (https://lists.ubuntu.com/archives/kernel-team/2014-February/038811.html).
Is debian kernel applied it?

The error message about overlayfs is displayed when aufs is specified as union type.

**Comment by megele** [comment]
@tenforward I understood the effects of the --union-type command line flags no issue here (other than it does not work). I'll try to figure out whether the Debian Sid Kernel has that specific patch applied. Thanks for the pointer!

**Comment by megele** [comment]
Sid seems to not have a 3.19 kernel. I picked up the experimental kernel instead.

**Comment by brauner** [comment]
Kernels must have a patch to allow unprivileged users to mount overlay filesystems. Once the cgroup namespace patch written by @hallyn and Aditya Kali makes it into upstream kernel this will be the default.

**Comment by tenforward** [comment]
The cgroup namespace patch is not for overlayfs but for cgroup fs and cgroupv2 fs. So even if that patch is merged, an unpriv user still can't mount overlayfs. (I guess...)

**Comment by brauner** [comment]
Yeah, you're allowed to mount a cgroup hierarchy in a non-init namespace. If you want to allow it for overlayfs you need a patched kernel or patch it yourself by appending `.fs_flags	= FS_USERNS_MOUNT` to   the `ovl_fs_type` struct in `fs/overlayfs/super.c`.

**Comment by tenforward** [comment]
:+1: I've already patched :smile: as https://github.com/lxc/lxc/issues/293#issuecomment-93711145

**Comment by nvtkaszpir** [comment]
note to self:
modprobe overlay

...and it works on kernel 4.4.2 @ ubuntu 14.04
