### ISSUE TITLE
Config entry lxc.network.0.type = none does not work anymore in lxc 2.0.11

### ISSUE THREAD

**Issue by towe75** [lxc/lxc#2958]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04.6 LTS
 * Lxc version: 2.0.11

# Issue description

We are running some containers with shared network namespace. Containers are deployed automatically and the config file uses the syntax "lxc.network.0.type = none" to enable this feature.

Lxc in version 2.0.11 interprets the configuration slightly differently and will not share the network namespace anymore.  The container will startup instead without any network interface.

It works, however, if i ommit the ".0." index: "lxc.network.type = none". So it is simple for us to work around the problem. Regular interfaces (e.g. phys) will work just fine with indexed configuration entries, only "none" is affected.

Is this behavior intentional or is it a bug?

# Steps to reproduce

 1. Create a vanilla ubuntu 16.04 container: lxc-create -n test -t download -- --dist ubuntu --release xenial --arch amd64
 2. Edit /var/lib/lxc/test/config. Remove all network lines, add "lxc.network.type = none"
 3. lxc-start -n test
 4. lxc-ls -f  **shows an ip number**
 5. lxc-stop -n test
 6. Edit /var/lib/lxc/test/config. Change to "lxc.network.0.type = none"
 7. lxc-start -n test
 8. lxc-ls -f  **no ip number**

**Comment by brauner** [comment]
What version of LXC did you upgrade from where that used to work?

**Comment by towe75** [comment]
Hey @brauner , 
thank you for coming back on this.

I checked our internal tracker and we had 2.0.8-0ubuntu1~16.04.2 before we've got 2.0.11-0ubuntu1~16.04.3

Back at that day i filed the issue because i've thought that more people might be affected.
But it seems like no one else jumped onto this issue and we, of course, just changed the config files.

**Comment by stgraber** [comment]
@brauner so in current LXC, we've got lxc.net.0.type = empty or lxc.net.0.type = none right?
Assuming that this works fine, since 3.0 requires the use of `lxc.net`, then this is likely fine now.

**Comment by brauner** [comment]
@stgraber yeah!
