### ISSUE TITLE
unable to deploy application in lxc container

### ISSUE THREAD

**Issue by pooja-kulal** [lxc/lxc#2990]
I am using ubuntu 16.04 and have installed LXC andLXD. My project requirement is to create lxc container and deploy application in and orchestrate it using kubernetes.Now I have installed kubernetes(minikube). As i am new to this i am not able to deploy application to LXC container, i found many sources which will help to deploy docker container but did not find any source to deploy lxc container.
please let me know  if there is any solution.

**Comment by brauner** [comment]
This is best asked here https://discuss.linuxcontainers.org/. Sorry for the delay.
