### ISSUE TITLE
lxc-start failed on cgroup_no_v1=all

### ISSUE THREAD

**Issue by alexshi** [lxc/lxc#2991]
* Distribution:
Centos
 * Distribution version:
7  
* The output of
   * `lxc-start --version`
   3.1.0-devel
  * `lxc-checkconfig`
lxc-checkconfig
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
newuidmap is not installed
newgidmap is not installed
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/systemd

Cgroup v2 mount points:

Cgroup v1 freezer controller: missing
Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, not loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities:

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/local/bin/lxc-checkconfig

   * `uname -a` Linux debug010000002015.local.alipay.net 5.1.0 #19 SMP Wed May 8 12:00:21 CST 2019 x86_64 x86_64 x86_64 GNU/Linux

   * `cat /proc/self/cgroup`
   cat /proc/self/cgroup
1:name=systemd:/user.slice/user-0.slice/session-2.scope

   * `cat /proc/1/mounts`
# cat /proc/1/mounts
/dev/root / xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0
devtmpfs /dev devtmpfs rw,seclabel,relatime,size=5092932k,nr_inodes=1273233,mode=755 0 0
sysfs /sys sysfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
tmpfs /dev/shm tmpfs rw,seclabel,nosuid,nodev 0 0
devpts /dev/pts devpts rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,seclabel,nosuid,nodev,mode=755 0 0
tmpfs /sys/fs/cgroup tmpfs ro,seclabel,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,seclabel,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=36,pgrp=1,timeout=0,minproto=5,maxproto=5,direct 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,seclabel,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,seclabel,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,seclabel,relatime 0 0
/dev/loop0 /var/lib/snapd/snap/core/6818 squashfs ro,seclabel,nodev,relatime 0 0
/dev/loop1 /var/lib/snapd/snap/lxd/10601 squashfs ro,seclabel,nodev,relatime 0 0
tmpfs /run/snapd/ns tmpfs rw,seclabel,nosuid,nodev,mode=755 0 0
nsfs /run/snapd/ns/lxd.mnt nsfs rw,seclabel 0 0
tmpfs /run/user/0 tmpfs rw,seclabel,nosuid,nodev,relatime,size=1019192k,mode=700 0 0

# Issue description
I made/installed lxc from src on my centos VM, the lxc-start well without cgroup_no_v1=all in kernel cmdline, but keep failed with it, on CGroup whiltelist in config file "/usr/local/share/lxc/config/common.conf" which is defauflt config.

#lxc-start centos -F
lxc-start: centos: cgroups/cgfsng.c: cg_legacy_set_data: 2273 controller devices.deny filename is devices.deny value is a
lxc-start: centos: cgroups/cgfsng.c: cg_legacy_set_data: 2287 controller devices filename is devices.deny value is a convertedv
lxc-start: centos: cgroups/cgfsng.c: cg_legacy_set_data: 2294 Failed to setup limits for the "devices" controller. The controller seems to be unused by "cgfsng" cgroup driver or not enabled on the cgroup hierarchy
 lxc-start: centos: start.c: lxc_spawn: 1826 Failed to setup legacy device cgroup controller limits
 lxc-start: centos: start.c: __lxc_start: 1980 Failed to spawn container "centos"
 lxc-start: centos: tools/lxc_start.c: main: 330 The container failed to start

A brief description of what failed or what could be improved.

# Steps to reproduce

 1. boot kernel with cgrup_no_v1=all in cmdline
 2. lxc-start any containers
 3. get the failed

**Comment by Tuxist** [comment]
Same Problem with alpine 3.10 with kernel 5.2.1:

**cat /proc/cmdline:**
tyr:~# cat /proc/cmdline 
BOOT_IMAGE=/boot/vmlinuz-vanilla root=UUID=e299ce46-33bc-4759-a10a-62c5ae8cfdd3 ro ro modules=sd-mod,usb-storage,btrfs nomodeset quiet rootfstype=btrfs swapaccount=1 cgroup_enable=memory


**lxc-start:**
tyr:~# lxc-start -F mumble
lxc-start: mumble: cgroups/cgfsng.c: cg_hybrid_get_controllers: 745 Found hierarchy not under /sys/fs/cgroup: "/sys/fs/cgroup rw,relatime - cgroup cgroup rw,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,net_prio,pids
                                                                "
                                                                 lxc-start: mumble: cgroups/cgfsng.c: cg_legacy_set_data: 2373 Failed to setup limits for the "devices" controller. The controller seems to be unused by "cgfsng" cgroup driver or not enabled on the cgroup hierarchy
                                                                                                                    lxc-start: mumble: start.c: lxc_spawn: 1821 Failed to setup legacy device cgroup controller limits
                                                    lxc-start: mumble: start.c: __lxc_start: 1972 Failed to spawn container "mumble"
                                                                                                                                    lxc-start: mumble: tools/lxc_start.c: main: 330 The container failed to start
lxc-start: mumble: tools/lxc_start.c: main: 336 Additional information can be obtained by setting the --logfile and --logpriority options

**lxc-checkconfig:**
tyr:~# lxc-checkconfig 
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup
/sys/fs/cgroup/openrc
/sys/fs/cgroup/systemd

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 freezer controller: missing
Cgroup v1 clone_children flag: enabled
Cgroup device: enabled                                                                                                                                            
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled

**Comment by OlegGirko** [comment]
This problem becomes widespread because [Fedora 31 uses cgroups v2 by default](https://docs.fedoraproject.org/en-US/fedora/f31/release-notes/sysadmin/Kernel/#cgroups-v2-by-default). There is [a bug in RedHat bugzilla for that](https://bugzilla.redhat.com/show_bug.cgi?id=1765821).

Are there any plans to support cgroups v2 in LXC?

**Comment by brauner** [comment]
LXC supports cgroup2 for a long time now. systemd in the container might not recognize it though. To fix this you can set:
```
lxc.init.cmd = /sbin/init systemd.unified_cgroup_hierarchy
```

AppArmor might still get in your way so - for unprivileged containers - you should set:
```
lxc.apparmor.profile = unconfined
```

**Comment by OlegGirko** [comment]
No, this is not `systemd` in container. In fact, I don't run `systemd` in container at all. And error messages come from `lxc-start` itself, not the script I run inside LXC container.

I've increased log level to `DEBUG` and this is what I got:

```
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.551 INFO     lsm - lsm/lsm.c:lsm_init:50 - LSM security driver SELinux
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.551 INFO     terminal - terminal.c:lxc_terminal_setup:899 - No terminal requested
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.552 INFO     start - start.c:lxc_init:919 - Container "obsbuild:Fedora_30-x86_64" is initialized
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.552 INFO     cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1401 - The monitor process uses "lxc.monitor/obsbuild:Fedora_30-x86_64" as cgroup
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.552 INFO     cgfsng - cgroups/cgfsng.c:cgfsng_payload_create:1466 - The container process uses "lxc.payload/obsbuild:Fedora_30-x86_64" as cgroup
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.553 INFO     start - start.c:lxc_spawn:1750 - Cloned CLONE_NEWNS
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.553 INFO     start - start.c:lxc_spawn:1750 - Cloned CLONE_NEWPID
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.553 INFO     start - start.c:lxc_spawn:1750 - Cloned CLONE_NEWUTS
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.553 INFO     start - start.c:lxc_spawn:1750 - Cloned CLONE_NEWIPC
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.553 INFO     start - start.c:lxc_spawn:1750 - Cloned CLONE_NEWNET
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.553 DEBUG    start - start.c:lxc_try_preserve_namespaces:192 - Preserved mnt namespace via fd 12
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.553 DEBUG    start - start.c:lxc_try_preserve_namespaces:192 - Preserved pid namespace via fd 13
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.553 DEBUG    start - start.c:lxc_try_preserve_namespaces:192 - Preserved uts namespace via fd 14
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.553 DEBUG    start - start.c:lxc_try_preserve_namespaces:192 - Preserved ipc namespace via fd 15
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.553 DEBUG    start - start.c:lxc_try_preserve_namespaces:192 - Preserved net namespace via fd 16
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.553 INFO     cgfsng - cgroups/cgfsng.c:__cg_legacy_setup_limits:2351 - Limits for the legacy cgroup hierarchies have been setup
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.553 INFO     start - start.c:do_start:1279 - Unshared CLONE_NEWCGROUP
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.554 INFO     conf - conf.c:run_script_argv:371 - Executing script "/var/lib/lxc/obsbuild:Fedora_30-x86_64/pre-mount.hook" for container "obsbuild:Fedora_30-x86_64", config section "lxc"
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.556 DEBUG    storage - storage/storage.c:get_storage_by_name:232 - Detected rootfs type "dir"
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.556 DEBUG    conf - conf.c:lxc_mount_rootfs:1332 - Mounted rootfs "/var/lib/lxc/obsbuild:Fedora_30-x86_64/rootfs" onto "/usr/lib64/lxc/rootfs" with options "(null)"
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.556 INFO     conf - conf.c:mount_autodev:1120 - Preparing "/dev"
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 INFO     conf - conf.c:mount_autodev:1167 - Prepared "/dev"
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 INFO     conf - conf.c:lxc_fill_autodev:1211 - Populating "/dev"
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 DEBUG    conf - conf.c:lxc_fill_autodev:1226 - Created device node "/usr/lib64/lxc/rootfs/dev/full"
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 DEBUG    conf - conf.c:lxc_fill_autodev:1226 - Created device node "/usr/lib64/lxc/rootfs/dev/null"
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 DEBUG    conf - conf.c:lxc_fill_autodev:1226 - Created device node "/usr/lib64/lxc/rootfs/dev/random"
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 DEBUG    conf - conf.c:lxc_fill_autodev:1226 - Created device node "/usr/lib64/lxc/rootfs/dev/tty"
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 DEBUG    conf - conf.c:lxc_fill_autodev:1226 - Created device node "/usr/lib64/lxc/rootfs/dev/urandom"
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 DEBUG    conf - conf.c:lxc_fill_autodev:1226 - Created device node "/usr/lib64/lxc/rootfs/dev/zero"
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 INFO     conf - conf.c:lxc_fill_autodev:1288 - Populated "/dev"
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 INFO     utils - utils.c:lxc_mount_proc_if_needed:1278 - Mounted /proc in container for security transition
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 DEBUG    conf - conf.c:lxc_setup_devpts:1587 - No new devpts instance will be mounted since no pts devices are requested
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 INFO     conf - conf.c:lxc_setup_ttys:951 - Finished setting up 0 /dev/tty<N> device(s)
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 DEBUG    conf - conf.c:setup_caps:2474 - Capabilities have been setup
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 NOTICE   conf - conf.c:lxc_setup:3694 - The container "obsbuild:Fedora_30-x86_64" is set up
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 WARN     cgfsng - cgroups/cgfsng.c:get_hierarchy:205 - There is no useable devices controller
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 ERROR    cgfsng - cgroups/cgfsng.c:cg_legacy_set_data:2299 - Failed to setup limits for the "devices" controller. The controller seems to be unused by "cgfsng" cgroup driver or not enabled on the cgroup hierarchy
lxc-start: obsbuild:Fedora_30-x86_64: cgroups/cgfsng.c: cg_legacy_set_data: 2299 Failed to setup limits for the "devices" controller. The controller seems to be unused by "cgfsng" cgroup driver or not enabled on the cgroup hierarchy
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 WARN     cgfsng - cgroups/cgfsng.c:__cg_legacy_setup_limits:2341 - Failed to set "devices.deny" to "a"
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 ERROR    start - start.c:lxc_spawn:1865 - Failed to setup legacy device cgroup controller limits
lxc-start: obsbuild:Fedora_30-x86_64: start.c: lxc_spawn: 1865 Failed to setup legacy device cgroup controller limits
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 DEBUG    network - network.c:lxc_delete_network:3308 - Deleted network devices
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 ERROR    start - start.c:lxc_abort:1103 - No such file or directory - Failed to send SIGKILL to 36192
lxc-start: obsbuild:Fedora_30-x86_64: start.c: lxc_abort: 1103 No such file or directory - Failed to send SIGKILL to 36192
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.557 ERROR    start - start.c:__lxc_start:2019 - Failed to spawn container "obsbuild:Fedora_30-x86_64"
lxc-start: obsbuild:Fedora_30-x86_64: start.c: __lxc_start: 2019 Failed to spawn container "obsbuild:Fedora_30-x86_64"
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.573 ERROR    lxc_start - tools/lxc_start.c:main:329 - The container failed to start
lxc-start: obsbuild:Fedora_30-x86_64: tools/lxc_start.c: main: 329 The container failed to start
lxc-start obsbuild:Fedora_30-x86_64 20191108171138.573 ERROR    lxc_start - tools/lxc_start.c:main:334 - Additional information can be obtained by setting the --logfile and --logpriority options
lxc-start: obsbuild:Fedora_30-x86_64: tools/lxc_start.c: main: 334 Additional information can be obtained by setting the --logfile and --logpriority options
```

And here is my (autogenerated) LXC config:
```
lxc.apparmor.profile = lxc-default-with-mounting

lxc.cgroup.devices.deny = a
# null
lxc.cgroup.devices.allow = c 1:3 rw
# zero
lxc.cgroup.devices.allow = c 1:5 rw
# full
lxc.cgroup.devices.allow = c 1:7 rw
# random
lxc.cgroup.devices.allow = c 1:8 rw
# urandom
lxc.cgroup.devices.allow = c 1:9 rw
# tty
lxc.cgroup.devices.allow = c 5:0 rw
# ptmx
lxc.cgroup.devices.allow = c 5:2 rw
# console
lxc.console.path = none
lxc.console.logfile = /dev/stdout
lxc.rootfs.path = dir:/var/lib/lxc/obsbuild:Fedora_31-x86_64/rootfs
lxc.hook.pre-mount = /var/lib/lxc/obsbuild:Fedora_31-x86_64/pre-mount.hook
```

**Comment by OlegGirko** [comment]
Looks like the problem is caused by `lxc.cgroup.*` directives. If I comment them out, my container starts without errors.

Manual on `lxc.container.conf` shows that `lxc.cgroup.*` directives are for cgroup v1 only and should be replaced with `lxc.cgroup2.*` directives, but different ones, because LXC is not aware of respective filesystem hierarchies, it just writes to whatever path is specified in this directive.

And [this article](https://medium.com/nttlabs/cgroup-v2-596d035be4d7) says that there is no easy transition for `devices.allow` rules for croup v2: eBPF program should be attached to cgroup directory.

Now a big question: how to specify eBPF program and attach it to cgroup directory using LXC container configuration file?

**Comment by brauner** [comment]
LXC 4.0 has full cgroup2 support and is going to be released soon. Device controller limits based on the new ebpf device controller can simply be specified the same way as for the old v1 device controller. Just that the key starts with `lxc.group2.devices.*`.
