### ISSUE TITLE
Debian9.9 - running docker in lxc - container nesting - loginuid proc permission issue

### ISSUE THREAD

**Issue by jonathan-molyneux** [lxc/lxc#3008]
# Required information

 * Distribution: debian
 * Distribution version:  9.9
 * The output of
   * `lxc-start --version`: 2.0.7
   * `lxc-checkconfig`: all green enabled
   * `uname -a`: Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
```
10:devices:/user.slice/user-0.slice/session-44933.scope
9:pids:/user.slice/user-0.slice/session-44933.scope
8:memory:/user.slice/user-0.slice/session-44933.scope
7:blkio:/user.slice/user-0.slice/session-44933.scope
6:cpu,cpuacct:/user.slice/user-0.slice/session-44933.scope
5:freezer:/
4:perf_event:/
3:net_cls,net_prio:/
2:cpuset:/
1:name=systemd:/user.slice/user-0.slice/session-44933.scope
0::/
```
   * `cat /proc/1/mounts`
```
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=32785684k,nr_inodes=8196421,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=6559964k,mode=755 0 0
/dev/mapper/root_crypt / btrfs rw,relatime,ssd,discard,space_cache,subvolid=5,subvol=/ 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=33,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=33888 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
sunrpc /run/rpc_pipefs rpc_pipefs rw,relatime 0 0
nfsd /proc/fs/nfsd nfsd rw,relatime 0 0
/dev/md0 /boot ext4 rw,relatime,discard,data=ordered 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=6559960k,mode=700 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=6559960k,mode=700,uid=1000,gid=1000 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
```
   * `docker --version`: Docker version 18.09.6, build 481bc77
   * `containerd --version`: containerd github.com/containerd/containerd 1.2.5 bb71b10fd8f58240ca47fbb579b9d1028eea7c84
   * both docker and containterd installed from packages published by docker (latest stables)

# Issue description

Having an issue when running docker containers under a privledged lxc container (nesting).
Docker containers are not able to write to /proc/self/loginuid, blocking ssh logins due to pam_loginuid.so.
This was found due to it blocking cron jobs functioning (same issue pam_loginuid.so).
Very similar to the old libpam issue that was previously addressed with lxc.

# Steps to reproduce

pam_loginuid.so (write to loginuid) works when testing from:
> the host
> inside docker run directly on the host
> inside a lxc container

But won't allow writes when run from docker inside the lxc container.
For example when cron triggers a job for the user www-data (uid 33)
You end up seeing the following:
```
[pid  1693] openat(AT_FDCWD, "/proc/self/loginuid", O_RDWR|O_NOFOLLOW) = 6
[pid  1693] read(6, "0", 24)            = 1
[pid  1693] read(6, "", 23)             = 0
[pid  1693] lseek(6, 0, SEEK_SET)       = 0
[pid  1693] ftruncate(6, 0)             = 0
[pid  1693] write(6, "33", 2)           = -1 EPERM (Operation not permitted)
```

Where as you should be seeing:
```
[pid 30378] openat(AT_FDCWD, "/proc/self/loginuid", O_RDWR|O_NOFOLLOW) = 6
[pid 30378] read(6, "4294967295", 24)   = 10
[pid 30378] read(6, "", 14)             = 0
[pid 30378] lseek(6, 0, SEEK_SET)       = 0
[pid 30378] ftruncate(6, 0)             = 0
[pid 30378] write(6, "33", 2)           = 2 
```

# Message

Have been able to reproduce the issue using both debian:9.9 and ubuntu:18.04 based images/docker containers.
Have also reproduced it using both debian:9.9 and ubuntu:18.04 lxc's running docker.
But have not (at this point in time) reproducted the issue running ubuntu:18.04 as the host os.

Have tried many tweaks to lxc and apparmor to no avail (mostly stripping away at the restrictions, have also run aa_profile unconfined normally lxc-container-default-with-mounting).
I can't seem to reproduce the issue in a lxc container directly, nor when running docker by itself.
Only able to repdocue the issue when nesting.
Any thoughts on ideas on where to go next ?

PS

This may not be an LXC issue, but I'm out of ideas on how to proceed.

**Comment by brauner** [comment]
This is is enforced by the kernel. Nothing that LXC can do. But you can try to use LXD since its way easier to run Docker in there.
