### ISSUE TITLE
lxc-start failed due to message "No such file or directory - Error examining proc in /usr/lib/lxc/rootfs/proc"

### ISSUE THREAD

**Issue by alvin1hsuaskey** [lxc/lxc#3017]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Linux OpenWRT
 * Distribution version: kernel 4.4.60 
 * The output of
   * `lxc-start --version`
1.1.3

   * `lxc-checkconfig` 
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: missing
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: missing
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: missing

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: missing
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: missing
CONFIG_INET_DIAG: missing
CONFIG_PACKET_DIAG: missing
CONFIG_NETLINK_DIAG: missing
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -a`
Linux OpenWrt 4.4.60 #1 SMP PREEMPT Wed May 29 13:11:31 CST 2019 armv7l GNU/Linux

   * `cat /proc/self/cgroup`
1:cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,pids,debug:/

   * `cat /proc/1/mounts`
mtd:ubi_rootfs /rom squashfs ro,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,noatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,noatime 0 0
cgroup /sys/fs/cgroup cgroup rw,nosuid,nodev,noexec,relatime,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,pids,debug,clone_children 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev,noatime 0 0
/dev/ubi0_2 /overlay ubifs rw,noatime 0 0
overlayfs:/overlay / overlay rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work 0 0
tmpfs /dev tmpfs rw,nosuid,relatime,size=512k,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,mode=600,ptmxmode=000 0 0
/dev/mtdblock26 /lib/firmware/IPQ8074/WIFI_FW squashfs ro,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,noatime 0 0

# Issue description

I create a container named "lqsdk". The rootfs image tarball is data-lxc.tar.gz.
When I try to start lqsdk, it's failed. The message is as below. I don't know what's missing.
And what I can do/check to debug/fix it? 

      lxc-start 1559106562.270 ERROR    lxc_utils - utils.c:open_without_symlink:1575 - No such file or directory - Error examining proc in /usr/lib/lxc/rootfs/proc
      lxc-start 1559106562.270 ERROR    lxc_conf - conf.c:mount_entry:1731 - No such file or directory - failed to mount 'proc' on '/usr/lib/lxc/rootfs/proc'
      lxc-start 1559106562.270 ERROR    lxc_conf - conf.c:lxc_setup:3745 - failed to setup the mount entries for 'lqsdk'
      lxc-start 1559106562.270 ERROR    lxc_start - start.c:do_start:702 - failed to setup the container
      lxc-start 1559106562.270 ERROR    lxc_sync - sync.c:__sync_wait:51 - invalid sequence number 1. expected 2
      lxc-start 1559106562.366 ERROR    lxc_start - start.c:__lxc_start:1172 - failed to spawn 'lqsdk'
      lxc-start 1559106567.371 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
      lxc-start 1559106567.371 ERROR    lxc_start_ui - lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 1559106567.371 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.

# Steps to reproduce

 1. Step one
lxc-create -n lqsdk -t qsdk

 2. Step two
lxc-start -n lqsdk

 3. Step three
no

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
No

 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
As message 

 - [ ] the containers configuration file

#
# lxc uci configuration
#

config lxc 'lxc'

        option url 'virtualwrt.org/containers/'

config common
        option image '/usr/share/lxc/templates/qsdk-lxc.tar.gz'

config LXC 'lqsdk'
        option haltsignal 'SIGUSR1'
        option include '/usr/share/lxc/config/openwrt.common.conf'
        option name 'lqsdk'
        option flags 'up'
        option link 'br-lan'
        option net_name 'eth1'
        option hwaddr 'empty'
        option entry 'tmpfs tmp tmpfs defaults'
        option net_type 'empty'

===============================
lxc.network.type =empty
lxc.rootfs = /lxc/lqsdk/rootfs

lxc.network.flags =up
lxc.network.link =br-lan
lxc.network.name =eth1

lxc.haltsignal=SIGUSR1

lxc.mount.entry = proc proc proc nodev,noexec,nosuid 0 0

lxc.include =/usr/share/lxc/config/openwrt.common.conf

**Comment by brauner** [comment]
Please add `,create=dir` after `nosuid`, check and report back if the error still exists.
