### ISSUE TITLE
RFE: provide /proc/sys/kernel/random/boot_id

### ISSUE THREAD

**Issue by smoser** [lxc/lxc#3027]
As originally filed in ubuntu at [bug 1831258](https://bugs.launchpad.net/bugs/1831258) `journalctl --list-boots` identifies boots by reading `/proc/sys/kernel/random/boot_id`.  Without doing this, the journal can only detect a reboot if the *host* has rebooted.

Without this ability to detect boots, functionality like `journalctl --boot=X` will also not work.

nspawn seems to do something similar in [nspawn/nspawn.c:setup_boot_id](https://github.com/systemd/systemd/blob/master/src/nspawn/nspawn.c#L1841)

**Comment by stgraber** [comment]
Transferred over to liblxc, the runtime can indeed setup a memfd or something, put a uuid in there and bind-mount it (read-only) over the /proc file when it's in charge of mounting proc.
