### ISSUE TITLE
 lxc: Set PermitRootLogin without-password in sshd_config in the default debian template

### ISSUE THREAD

**Issue by ghost** [lxc/lxc#303]
This is a forward from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=758647:

---snip---
From: Ondřej Surý <ondrej@debian.org>
To: Debian Bug Tracking System <submit@bugs.debian.org>
Subject: lxc: Set PermitRootLogin without-password in sshd_config in the default debian template
Date: Tue, 19 Aug 2014 17:19:16 +0200

[Message part 1 (text/plain, inline)]

Package: lxc
Version: 1:1.0.5-1
Severity: normal
Tags: security patch upstream

Hi,

one more patch to disable root login over ssh with password by
default.

Cheers,
Ondrej

-- System Information:
Debian Release: jessie/sid
  APT prefers unstable
  APT policy: (500, 'unstable'), (1, 'experimental')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 3.16-rc6-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_DK.UTF-8, LC_CTYPE=en_DK.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash

Versions of packages lxc depends on:
ii  libapparmor1       2.8.0-5.1+b2
ii  libc6              2.19-9
ii  libcap2            1:2.24-4
ii  libseccomp2        2.1.1-1
ii  libselinux1        2.3-1
ii  multiarch-support  2.19-9
ii  python3            3.4.1-1

Versions of packages lxc recommends:
ii  lua5.2  5.2.3-1
ii  rsync   3.1.1-2

Versions of packages lxc suggests:
ii  debootstrap  1.0.60

-- no debconf information
---snap---

**Comment by evgeni** [comment]
Given #973 is merged, shall we close this?

@terceiro @daniel-baumann what do you think?

**Comment by terceiro** [comment]
agreed
