### ISSUE TITLE
[3.0.3] unprivileged container not booting - rootfs fails mounting with options "(null)"

### ISSUE THREAD

**Issue by n8v8R** [lxc/lxc#3030]
All relevant data/information (i hope) is provided in the downstream bug tracker https://gitlab.labs.nic.cz/turris/turris-build/issues/28

Additional info -> Turris OS 4.x+ is based on OpenWRT 18.06 with just few patches where most of those patches are just backports.

**Comment by brauner** [comment]
Is the rootfs of the container id shifted?
Please show:
ls -al /srv/lxc/test
ls -al /srv/lxc/test/rootfs

**Comment by n8v8R** [comment]
`ls -al /srv/lxc/test`
> total 4
> drwxrwx--- 1 root root   24 Jun  5 17:22 .
> drwxr-xr-x 1 root root    8 Jun  5 17:21 ..
> -rw-r--r-- 1 root root 1329 Jun  5 17:25 config
> drwxr-xr-x 1 root root  122 Jun  5 08:57 rootfs
___
`ls -al /srv/lxc/test/rootfs`
> total 12
> drwxr-xr-x 1 root root  122 Jun  5 08:57 .
> drwxrwx--- 1 root root   24 Jun  5 17:22 ..
> lrwxrwxrwx 1 root root    7 Jun  5 08:43 bin -> usr/bin
> drwxr-xr-x 1 root root    0 Apr 16 08:36 boot
> drwxr-xr-x 1 root root  114 Jun  5 08:43 dev
> drwxr-xr-x 1 root root 2024 Jun  5 17:22 etc
> drwxr-xr-x 1 root root   12 Jun  5 08:54 home
> lrwxrwxrwx 1 root root    7 Jun  5 08:43 lib -> usr/lib
> drwxr-xr-x 1 root root    0 Jun  5 08:43 media
> drwxr-xr-x 1 root root    0 Jun  5 08:43 mnt
> drwxr-xr-x 1 root root    0 Jun  5 08:43 opt
> drwxr-xr-x 1 root root    0 Apr 16 08:36 proc
> drwx------ 1 root root   30 Jun  5 08:43 root
> drwxr-xr-x 1 root root    0 Jun  5 08:57 run
> lrwxrwxrwx 1 root root    8 Jun  5 08:43 sbin -> usr/sbin
> drwxr-xr-x 1 root root    0 Jun  5 08:43 srv
> drwxr-xr-x 1 root root    0 Apr 16 08:36 sys
> drwxrwxrwt 1 root root    0 Jun  5 08:52 tmp
> drwxr-xr-x 1 root root   70 Jun  5 08:43 usr
> drwxr-xr-x 1 root root   90 Jun  5 08:43 var

**Comment by n8v8R** [comment]
Not sure if it perhaps is indicative of the underlying cause but curiously adding some `lxc.sysctl.` to the config and booting as _privileged_ container produces:

> lxc-start test 20190606080720.800 ERROR    conf - conf.c:setup_sysctl_parameters:2638 - Failed to setup sysctl parameters net.ipv4.tcp_window_scaling to 1
> lxc-start test 20190606080720.800 ERROR    conf - conf.c:lxc_setup:3670 - Failed to setup sysctl parameters
> lxc-start test 20190606080720.801 ERROR    start - start.c:do_start:1263 - Failed to setup container "test"
> lxc-start test 20190606080720.801 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 5)

Tried various `lxc.sysctl.` and all are met with the same outcome.

**Comment by brauner** [comment]
The files of you container's rootfs are owned by uid 0. If you're trying to start an unprivileged container you need to make sure that those files belong to the unprivileged id of the idmapping you want to use.

**Comment by n8v8R** [comment]
Sure. 

That leads me to a question  though - the type - unprivileged or privileged  - has to be stipulated already at container creation time  and cannot be converted afterwards, unless from cli `chown -R 1000000:1000000 /path/to/lxc/container/rootfs`?
Or are different guest images requires for unprivileged and privileged?

Asking because that it not so clear (to me) from the man pages.

Would it be worth considering a feature suggestion - `lxc-convert-pivil` with = 0 (privileged) and = 1 (unprivileged)?

**Comment by n8v8R** [comment]
creating an _unprivileged_ container ends up with

> Unpacking the rootfs
> tar: ./dev/urandom: Cannot mknod: Operation not permitted
> tar: ./dev/null: Cannot mknod: Operation not permitted
> tar: ./dev/random: Cannot mknod: Operation not permitted
> tar: ./dev/ptmx: Cannot mknod: Operation not permitted
> tar: ./dev/full: Cannot mknod: Operation not permitted
> tar: ./dev/zero: Cannot mknod: Operation not permitted
> tar: ./dev/tty: Cannot mknod: Operation not permitted
> tar: Exiting with failure status due to previous errors
> lxc-create: test: lxccontainer.c: create_run_template: 1617 Failed to create container from templ                                                                  ate

output of `ls -al /dev` [dev.txt](https://github.com/lxc/lxc/files/3262873/dev.txt) and `findmnt` [mounts.txt](https://github.com/lxc/lxc/files/3262878/mounts.txt) looks normal/sane to me, at loss... Running a few lxc nodes on other (ubuntu) hosts and never such happening there.

**Comment by n8v8R** [comment]
did chown the directories but booting fails now with

lxc-start test 20190606195821.196 ERROR    utils - utils.c:safe_mount:1179 - Operation not permitted - Failed to mount "proc" onto "/usr/lib/lxc/rootfs/proc"
lxc-start test 20190606195821.196 ERROR    conf - conf.c:lxc_mount_auto_mounts:724 - Operation not permitted - Failed to mount "proc" on "/usr/lib/lxc/rootfs/proc" with flags 14
lxc-start test 20190606195821.196 ERROR    conf - conf.c:lxc_setup:3539 - Failed to setup first automatic mounts
lxc-start test 20190606195821.196 ERROR    start - start.c:do_start:1263 - Failed to setup container "test"

**Comment by n8v8R** [comment]
Is the OS likely not suited for unprivileged containers?

**Comment by brauner** [comment]
You should use the `download` template for that case and downloda the image rather than create it.

**Comment by n8v8R** [comment]
Hmm, that I have tried - see https://github.com/lxc/lxc/issues/3030#issuecomment-499606991

**Comment by n8v8R** [comment]
Suppose this could be closed if the OS is deemed not suitable to run unprivileged containers but it is not clear to me as you stated in the forum 

> If you’re creating unprivileged containers you won’t be able to mknod() prior to 4.18 kernels. Could be that the template is not correctly being informed that it is run in a user namespace. You can try and see whether you see the same issue with one of the 3.*.* releases.

**Comment by n8v8R** [comment]
Since OpenWRT ships `mknod` as `busybox` applet I gave it another whirl with `coreutils-mknod` (Full version of standard GNU mknod utility / v 8.23-3.1)

and ran `lxc-create test -t download -o /logs/lxc/create -l debug` but ending with the same

> Unpacking the rootfs
> tar: ./dev/null: Cannot mknod: Operation not permitted
> tar: ./dev/zero: Cannot mknod: Operation not permitted
> tar: ./dev/full: Cannot mknod: Operation not permitted
> tar: ./dev/random: Cannot mknod: Operation not permitted
> tar: ./dev/urandom: Cannot mknod: Operation not permitted
> tar: ./dev/tty: Cannot mknod: Operation not permitted
> tar: ./dev/ptmx: Cannot mknod: Operation not permitted
> tar: Exiting with failure status due to previous errors

> confile - confile.c:set_config_idmaps:1555 - Read uid map: type u nsid 0 hostid 100000 range 65536
> confile - confile.c:set_config_idmaps:1555 - Read uid map: type g nsid 0 hostid 100000 range 65536
> confile - confile.c:set_config_idmaps:1555 - Read uid map: type u nsid 0 hostid 100000 range 65536
> confile - confile.c:set_config_idmaps:1555 - Read uid map: type g nsid 0 hostid 100000 range 65536
> storage - storage/storage.c:get_storage_by_name:231 - Detected rootfs type "dir"
> lxccontainer - lxccontainer.c:create_run_template:1617 - Failed to create container from template
> storage - storage/storage.c:get_storage_by_name:231 - Detected rootfs type "dir"
> lxccontainer - lxccontainer.c:container_destroy:2977 - Destroyed rootfs for test
> lxccontainer - lxccontainer.c:container_destroy:3042 - Destroyed directory "/srv/lxc/test" for "test"
> lxc_create - tools/lxc_create.c:main:327 - Failed to create container test

___

Do not know what else to try to get this working

**Comment by f-roscher** [comment]
I am having the same issue, but with a privileged container. All worked before dist-upgrading Debian to 'buster'.
I traced the error up to line 1340 of src/lxc/conf.c, being 'bdev = storage_init(conf);' returning false there. 
This is how far I got now. I'm trying to find out more, but would be glad for any hints.

**Comment by stgraber** [comment]
@brauner any idea what's going on here?

**Comment by brauner** [comment]
No, can someone try and reproduce this with current master, please?
