### ISSUE TITLE
Setting kernel.shm* per container

### ISSUE THREAD

**Issue by lu-zero** [lxc/lxc#3033]
Since lxc 3 should be able to have those settings, I cannot find in the documentation how to set them in lxd.

  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.19.27-gentoo-r1
  server: lxd
  server_pid: 25835
  server_version: "3.10"
  storage: btrfs
  storage_version: "4.19"
  server_clustered: false

**Comment by brauner** [comment]
> Same behavior here though I'm getting a bit more useful error:
> 
> ```
> lxc nesting 20190605210402.453 ERROR    conf - conf.c:setup_sysctl_parameters:2652 - Permission denied - Failed to setup sysctl parameters kernel.shmmax to 1073741824
> ```
> 
> So this may suggest that the sysctl is being applied as root in the container rather than as real root?
> This would explain the permission error.
> 
> I'm moving the issue over to liblxc so @brauner can take a quick look.

Hm, no. This rather looks like these sysctls are not namespaced.

**Comment by lu-zero** [comment]
the proc entries are apparently, changing the host entries isn't reflected in the container.

**Comment by lu-zero** [comment]
@brauner Trying to setting them in the host to any value gets lost in the container, where should I look in the kernel to doublecheck their functionality?

I tried with `linux-5.2.1` and it behaves the same as `linux-4.19.27`

**Comment by brauner** [comment]
On Thu, Jul 18, 2019 at 09:48:44AM -0700, Luca Barbato wrote:
> @brauner Trying to setting them in the host to any value gets lost in the container, where should I look in the kernel to doublecheck their functionality?

kernel/sysctl.c very likely but note that they are not really namespaces
afair.

**Comment by lu-zero** [comment]
The container gets the default values instead of using the ones present in the host so some namespacing happened. Where in lxc the procfs is set up?

**Comment by lu-zero** [comment]
Poking around I see that `ipc_namespace` has `shm_ctlmax` and friends.

**Comment by lu-zero** [comment]
I assume that `security_shm_shmctl` fails somehow.

**Comment by brauner** [comment]
This is a kernel limitation rather than a LXC limitation so I think we need to close this.
