### ISSUE TITLE
pam_cgfs should have man page

### ISSUE THREAD

**Issue by AkihiroSuda** [lxc/lxc#3035]

**Comment by brauner** [comment]
Yes, agreed. Someone care to come up with one?

**Comment by adamRogerson** [comment]
@brauner I will give this a go.

**Comment by CameronNemo** [comment]
Is there any documentation currently?

**Comment by avhvr** [comment]
Hi,

I'd like to contribute to this issue. Is anyone working on it currently?

**Comment by brauner** [comment]
@avhr feel free to give it a try

**Comment by AkihiroSuda** [comment]
Thanks @avhvr
