### ISSUE TITLE
Q: Is there currently a way to snapshot directory based containers?

### ISSUE THREAD

**Issue by banderlog** [lxc/lxc#3036]
Is there currently a way to snapshot a directory based container? 
Or I do not supposed to use them at all?

**Comment by stgraber** [comment]
`lxc snapshot` works fine with directory based containers but it will:
 - Make your container hang during the snapshot
 - Will do a copy of all your data so every snapshot takes as much space as the entire container

So yeah, not something we'd recommend, but it is something which works and is tested.

Closing as this is a question, not an issue. In the future questions are usually better handled at https://discuss.linuxcontainers.org
