### ISSUE TITLE
lxc_netdev_rename_by_index() appears to report false success on bad name length

### ISSUE THREAD

**Issue by foresto** [lxc/lxc#3044]
While reading the code for lxc_netdev_rename_by_index(), I noticed what looks like a bug in its argument validation: I think it will return 0 (success) even when failing due to an invalid *newname* argument.

The problem lies in [this goto out](/lxc/lxc/blob/6ae34d21696c25de0264ce60a1641011cd17f20d/src/lxc/network.c#L1164) without first setting the *err* variable. The value of *err* is 0 at that point in the code, and since it will become the return value after the *goto*, the call will end up reporting success when it was actually a failure.

I suggest adding `err = -EINVAL;` (or similar) before that *goto*.

**Comment by brauner** [comment]
Yep, you're right. Sendig a fix rn.
