### ISSUE TITLE
Migrate lxd -> lxc

### ISSUE THREAD

**Issue by jmpolom** [lxc/lxc#3048]
This is general feedback about the state of documentation in general. I've been looking for documentation indicating whether it is possible to migrate containers from lxd to lxc, which has led me to plenty of docs for migrating from lxc to lxd. Based on what I've read it seems possible to do the reverse (lxd to lxc) but there's precious little documentation I can find on the topic. Is it possible to migrate containers from lxd to lxc? If this is possible, would it make sense to add documentation detailing the general process?

**Comment by invizus** [comment]
You can try using `lxc publish` and `lxc image export` commands found here.
https://discuss.linuxcontainers.org/t/backup-the-container-and-install-it-on-another-server/463
It will create "rootfs" folder with file system which you could try and adapt to LXC configuration.

**Comment by brauner** [comment]
Yeah, what @invizus said is probably your best bet.

**Comment by invizus** [comment]
One could also try `lxc copy` command, that will probably create new container with correct permissions and group ownership. I have no longer access to systems to test that.
