### ISSUE TITLE
Generated AppArmor profile prevents start of user unprivileged container

### ISSUE THREAD

**Issue by jmpolom** [lxc/lxc#3049]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Debian
 * Distribution version: Buster/Testing
 * The output of
   * `lxc-start --version lxc`: 3.0.3
   * `uname -a`: Linux 4.19.0-5-amd64 #1 SMP Debian 4.19.37-3 (2019-05-15) x86_64 GNU/Linux

# Issue description
In short, unprivileged containers can be run system wide via root but not via a user unless the container is run with AppArmor set to unconfined. I have followed the [configuration guidance](https://linuxcontainers.org/lxc/getting-started/) completely but was unable to successfully get the container to start.

Running `lxc-start -n <container>` as a user with `lxc.apparmor.profile = generated` the container fails to start and produces some output basically stating the same ("Failed to receive the container state" and "The container failed to start"). I'm running this in a virtual machine at present without ssh configured, so I can't copy the full output directly.

Running `lxc-start -n <container>` as a user with `lxc.apparmor.profile = unconfined` results in the container starting and functioning as expected.

Running `sudo lxc-start -n <container>` works as expected.

# Steps to reproduce

 1. Configure system for unprivileged containers created by a user
 2. Create container as user set to use the generated AppArmor profile
 3. Attempt to start unprivileged container as user with generated AppArmor profile

**Comment by n8v8R** [comment]
likely dup of https://github.com/lxc/lxc/issues/3030

**Comment by jmpolom** [comment]
Initially this was listed as a duplicate of #3030 but that doesn't seem to make sense because when I `ls -al /var/lib/lxc` and `ls -al /var/lib/lxc/<container>` the container directory and `rootfs` folder are owned by 100000 (id shifted).

I also do not believe this is identical to #2778 either because I don't get audit messages in the system log mentioning networkd.

What I do get, however, when running `lxc-start` configured to log debug messages to a file is a log entry something to the effect of (again, in VM so copying is not possible) `ERROR  apparmor - lsm/apparmor.c:apparmor_prepare:974 - Cannot use generated profile: apparmor_parser not available`.

I suspect this issue relates to how `apparmor_parser` is configured to work on Buster? You can only run the parser as root, but somehow this works on other distributions. Not sure what is going on with that?

**Comment by stgraber** [comment]
Could be as simple as your user not having `apparmor_parser` in the `PATH` env variable.
Some distros don't put `/sbin` and `/usr/sbin` in there.

To be clear, unprivileged users cannot generate and load profiles, but you should be able to use the standard pre-existing ones or unconfined.

**Comment by stgraber** [comment]
Marking as incomplete, the `PATH` issue is my best guess until then.

**Comment by dvd0101** [comment]
You are righe, on Debian buster `apparmor_parser` is not in the PATH, but even after I've added it the container won't start:
```
ERROR    apparmor - lsm/apparmor.c:make_apparmor_namespace:761 - Permission denied - Error creating AppArmor namespace: /sys/kernel/security/apparmor/policy/namespaces/lxc-syncbox_<-var-lxcmaster-.local-share-lxc>
ERROR    apparmor - lsm/apparmor.c:apparmor_prepare:980 - Failed to load generated AppArmor profile
ERROR    start - start.c:lxc_init:899 - Failed to initialize LSM
```

**Comment by ScarUY** [comment]
> You are righe, on Debian buster `apparmor_parser` is not in the PATH, but even after I've added it the container won't start:
> 
> ```
> ERROR    apparmor - lsm/apparmor.c:make_apparmor_namespace:761 - Permission denied - Error creating AppArmor namespace: /sys/kernel/security/apparmor/policy/namespaces/lxc-syncbox_<-var-lxcmaster-.local-share-lxc>
> ERROR    apparmor - lsm/apparmor.c:apparmor_prepare:980 - Failed to load generated AppArmor profile
> ERROR    start - start.c:lxc_init:899 - Failed to initialize LSM
> ```

Sorry to revive this, but have you been able to solve this? If so, would you be so kind as to share your solution? 
I'm having the same problem. Thank you in advance.

**Comment by jakob-utilityapi** [comment]
Looks like I was able to resolve this by configuring AppArmor as described [here](https://wiki.debian.org/LXC#Configure_AppArmor).

> In `.config/lxc/default.conf`, set one of the following:
> - `lxc.apparmor.profile = unconfined `
> - `lxc.apparmor.profile = lxc-container-default-cgns `

**Comment by smiba** [comment]
For me the file `/etc/apparmor/parser.conf` didn't exist, this created a warning in apparmor_parser.

After creating this file, the `Cannot use generated profile: apparmor_parser not available` error went away and the lxc container started just fine. 

Basically; the fix seems to be: `touch /etc/apparmor/parser.conf`

**Comment by Abdull** [comment]
> Looks like I was able to resolve this by configuring AppArmor as described [here](https://wiki.debian.org/LXC#Configure_AppArmor).
> 
> > In `.config/lxc/default.conf`, set one of the following:
> > 
> > * `lxc.apparmor.profile = unconfined`
> > * `lxc.apparmor.profile = lxc-container-default-cgns`

In my Debian bullseye system, with its vanilla AppArmor configuration, only with
```
lxc.apparmor.profile = unconfined
```
did my created/started unprivileged containers receive assigned IP addresses and where therefore able to access the network/Internet.

I therefore `lxc-delete`d all containers that were previously created with `lxc-container-default-cgns` and recreated them with the updated `lxc.apparmor.profile = unconfined` setting.
