### ISSUE TITLE
Migrated redhat lxc 2 container won't boot in version lxc 3.0.3

### ISSUE THREAD

**Issue by chrismatchett** [lxc/lxc#3062]
Hi,

I am moving some old lxc version 2 containers to a new Ubuntu 18.04 with lxc version 3. I am good with the Ubuntu containers but my redhat container won't boot. There are some errors at the end of the debug below but I'm not sure what to do about them? I have used the tool to update my configs.

Thanks,

Chrsi

lxc-start redhat 20190625211748.491 INFO confile - confile.c:set_config_idmaps:1555 - Read uid map: type g nsid 0 hostid 100000 range 65536
lxc-start redhat 20190625211748.492 INFO lxccontainer - lxccontainer.c:do_lxcapi_start:961 - Set process title to [lxc monitor] /home/chris/.local/share/lxc redhat
lxc-start redhat 20190625211748.493 INFO lsm - lsm/lsm.c:lsm_init:50 - LSM security driver AppArmor
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:759 - Processing "reject_force_umount # comment this to allow umount -f; not recommended"
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:do_resolve_add_rule:505 - Set seccomp rule to reject force umounts
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for reject_force_umount action 0(kill)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:do_resolve_add_rule:505 - Set seccomp rule to reject force umounts
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for reject_force_umount action 0(kill)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:do_resolve_add_rule:505 - Set seccomp rule to reject force umounts
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for reject_force_umount action 0(kill)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:do_resolve_add_rule:505 - Set seccomp rule to reject force umounts
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for reject_force_umount action 0(kill)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:759 - Processing "[all]"
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:759 - Processing "kexec_load errno 1"
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for kexec_load action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for kexec_load action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for kexec_load action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for kexec_load action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:759 - Processing "open_by_handle_at errno 1"
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for open_by_handle_at action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for open_by_handle_at action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for open_by_handle_at action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for open_by_handle_at action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:759 - Processing "init_module errno 1"
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for init_module action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for init_module action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for init_module action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for init_module action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:759 - Processing "finit_module errno 1"
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for finit_module action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for finit_module action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for finit_module action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for finit_module action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:759 - Processing "delete_module errno 1"
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:937 - Added native rule for arch 0 for delete_module action 327681(errno)
lxc-start redhat 20190625211748.493 INFO seccomp - seccomp.c:parse_config_v2:946 - Added compat rule for arch 1073741827 for delete_module action 327681(errno)
lxc-start redhat 20190625211748.494 INFO seccomp - seccomp.c:parse_config_v2:956 - Added compat rule for arch 1073741886 for delete_module action 327681(errno)
lxc-start redhat 20190625211748.494 INFO seccomp - seccomp.c:parse_config_v2:966 - Added native rule for arch -1073741762 for delete_module action 327681(errno)
lxc-start redhat 20190625211748.494 INFO seccomp - seccomp.c:parse_config_v2:970 - Merging compat seccomp contexts into main context
lxc-start redhat 20190625211748.494 DEBUG terminal - terminal.c:lxc_terminal_peer_default:707 - No such device - The process does not have a controlling terminal
lxc-start redhat 20190625211748.494 DEBUG conf - conf.c:chown_mapped_root:3166 - trying to chown "/dev/pts/4" to 1000
lxc-start redhat 20190625211748.534 INFO start - start.c:lxc_init:897 - Container "redhat" is initialized
lxc-start redhat 20190625211748.534 INFO start - start.c:lxc_spawn:1688 - Cloned CLONE_NEWUSER
lxc-start redhat 20190625211748.534 INFO start - start.c:lxc_spawn:1688 - Cloned CLONE_NEWNS
lxc-start redhat 20190625211748.534 INFO start - start.c:lxc_spawn:1688 - Cloned CLONE_NEWPID
lxc-start redhat 20190625211748.534 INFO start - start.c:lxc_spawn:1688 - Cloned CLONE_NEWUTS
lxc-start redhat 20190625211748.534 INFO start - start.c:lxc_spawn:1688 - Cloned CLONE_NEWIPC
lxc-start redhat 20190625211748.534 DEBUG start - start.c:lxc_try_preserve_namespaces:196 - Preserved user namespace via fd 14
lxc-start redhat 20190625211748.534 DEBUG start - start.c:lxc_try_preserve_namespaces:196 - Preserved mnt namespace via fd 15
lxc-start redhat 20190625211748.534 DEBUG start - start.c:lxc_try_preserve_namespaces:196 - Preserved pid namespace via fd 16
lxc-start redhat 20190625211748.534 DEBUG start - start.c:lxc_try_preserve_namespaces:196 - Preserved uts namespace via fd 17
lxc-start redhat 20190625211748.534 DEBUG start - start.c:lxc_try_preserve_namespaces:196 - Preserved ipc namespace via fd 18
lxc-start redhat 20190625211748.534 DEBUG conf - conf.c:idmaptool_on_path_and_privileged:2836 - The binary "/usr/bin/newuidmap" does have the setuid bit set
lxc-start redhat 20190625211748.534 DEBUG conf - conf.c:idmaptool_on_path_and_privileged:2836 - The binary "/usr/bin/newgidmap" does have the setuid bit set
lxc-start redhat 20190625211748.534 DEBUG conf - conf.c:lxc_map_ids:2928 - Functional newuidmap and newgidmap binary found
lxc-start redhat 20190625211748.539 INFO start - start.c:do_start:1136 - Unshared CLONE_NEWNET
lxc-start redhat 20190625211748.539 DEBUG conf - conf.c:idmaptool_on_path_and_privileged:2836 - The binary "/usr/bin/newuidmap" does have the setuid bit set
lxc-start redhat 20190625211748.539 DEBUG conf - conf.c:idmaptool_on_path_and_privileged:2836 - The binary "/usr/bin/newgidmap" does have the setuid bit set
lxc-start redhat 20190625211748.539 DEBUG conf - conf.c:lxc_map_ids:2928 - Functional newuidmap and newgidmap binary found
lxc-start redhat 20190625211748.548 DEBUG start - start.c:lxc_spawn:1742 - Preserved net namespace via fd 10
lxc-start redhat 20190625211748.548 WARN start - start.c:lxc_spawn:1746 - Operation not permitted - Failed to allocate new network namespace id
lxc-start redhat 20190625211748.549 INFO network - network.c:lxc_create_network_unpriv_exec:2150 - Execing lxc-user-nic create /home/chris/.local/share/lxc redhat 22352 veth lxcbr0 (null)
lxc-start redhat 20190625211748.598 NOTICE utils - utils.c:lxc_switch_uid_gid:1378 - Switched to gid 0
lxc-start redhat 20190625211748.598 NOTICE utils - utils.c:lxc_switch_uid_gid:1387 - Switched to uid 0
lxc-start redhat 20190625211748.598 NOTICE utils - utils.c:lxc_setgroups:1400 - Dropped additional groups
lxc-start redhat 20190625211748.598 INFO start - start.c:do_start:1242 - Unshared CLONE_NEWCGROUP
lxc-start redhat 20190625211748.598 DEBUG storage - storage/storage.c:storage_query:253 - Detected rootfs type "dir"
lxc-start redhat 20190625211748.598 DEBUG conf - conf.c:lxc_mount_rootfs:1332 - Mounted rootfs "/home/chris/.local/share/lxc/redhat/rootfs" onto "/usr/lib/x86_64-linux-gnu/lxc" with options "(null)"
lxc-start redhat 20190625211748.598 INFO conf - conf.c:setup_utsname:791 - Set hostname to "redhat"
lxc-start redhat 20190625211748.598 DEBUG network - network.c:setup_hw_addr:2767 - Mac address "00:16:3e:be:05:73" on "eth0" has been setup
lxc-start redhat 20190625211748.598 DEBUG network - network.c:lxc_setup_netdev_in_child_namespaces:3032 - Network device "eth0" has been setup
lxc-start redhat 20190625211748.598 INFO network - network.c:lxc_setup_network_in_child_namespaces:3053 - network has been setup
lxc-start redhat 20190625211748.598 INFO conf - conf.c:mount_autodev:1118 - Preparing "/dev"
lxc-start redhat 20190625211748.598 INFO conf - conf.c:mount_autodev:1165 - Prepared "/dev"
lxc-start redhat 20190625211748.599 INFO conf - conf.c:lxc_fill_autodev:1209 - Populating "/dev"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:lxc_fill_autodev:1224 - Created device node "/usr/lib/x86_64-linux-gnu/lxc/dev/full"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:lxc_fill_autodev:1282 - Bind mounted host device node "/dev/full" onto "/usr/lib/x86_64-linux-gnu/lxc/dev/full"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:lxc_fill_autodev:1224 - Created device node "/usr/lib/x86_64-linux-gnu/lxc/dev/null"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:lxc_fill_autodev:1282 - Bind mounted host device node "/dev/null" onto "/usr/lib/x86_64-linux-gnu/lxc/dev/null"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:lxc_fill_autodev:1224 - Created device node "/usr/lib/x86_64-linux-gnu/lxc/dev/random"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:lxc_fill_autodev:1282 - Bind mounted host device node "/dev/random" onto "/usr/lib/x86_64-linux-gnu/lxc/dev/random"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:lxc_fill_autodev:1224 - Created device node "/usr/lib/x86_64-linux-gnu/lxc/dev/tty"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:lxc_fill_autodev:1282 - Bind mounted host device node "/dev/tty" onto "/usr/lib/x86_64-linux-gnu/lxc/dev/tty"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:lxc_fill_autodev:1224 - Created device node "/usr/lib/x86_64-linux-gnu/lxc/dev/urandom"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:lxc_fill_autodev:1282 - Bind mounted host device node "/dev/urandom" onto "/usr/lib/x86_64-linux-gnu/lxc/dev/urandom"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:lxc_fill_autodev:1224 - Created device node "/usr/lib/x86_64-linux-gnu/lxc/dev/zero"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:lxc_fill_autodev:1282 - Bind mounted host device node "/dev/zero" onto "/usr/lib/x86_64-linux-gnu/lxc/dev/zero"
lxc-start redhat 20190625211748.599 INFO conf - conf.c:lxc_fill_autodev:1286 - Populated "/dev"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:mount_entry:2027 - Remounting "/dev/console" on "/usr/lib/x86_64-linux-gnu/lxc/dev/console" to respect bind or remount options
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:mount_entry:2048 - Flags for "/dev/console" were 4098, required extra flags are 2
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:mount_entry:2102 - Mounted "/dev/console" on "/usr/lib/x86_64-linux-gnu/lxc/dev/console" with filesystem type "none"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:mount_entry:2027 - Remounting "/dev/full" on "/usr/lib/x86_64-linux-gnu/lxc/dev/full" to respect bind or remount options
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:mount_entry:2048 - Flags for "/dev/full" were 4098, required extra flags are 2
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:mount_entry:2102 - Mounted "/dev/full" on "/usr/lib/x86_64-linux-gnu/lxc/dev/full" with filesystem type "none"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:mount_entry:2027 - Remounting "/dev/null" on "/usr/lib/x86_64-linux-gnu/lxc/dev/null" to respect bind or remount options
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:mount_entry:2048 - Flags for "/dev/null" were 4098, required extra flags are 2
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:mount_entry:2102 - Mounted "/dev/null" on "/usr/lib/x86_64-linux-gnu/lxc/dev/null" with filesystem type "none"
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:mount_entry:2027 - Remounting "/dev/random" on "/usr/lib/x86_64-linux-gnu/lxc/dev/random" to respect bind or remount options
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:mount_entry:2048 - Flags for "/dev/random" were 4098, required extra flags are 2
lxc-start redhat 20190625211748.599 DEBUG conf - conf.c:mount_entry:2102 - Mounted "/dev/random" on "/usr/lib/x86_64-linux-gnu/lxc/dev/random" with filesystem type "none"
lxc-start redhat 20190625211748.599 ERROR conf - conf.c:mount_entry:2019 - No such device or address - Failed to mount "/dev/tty" on "/usr/lib/x86_64-linux-gnu/lxc/dev/tty"
lxc-start redhat 20190625211748.599 ERROR conf - conf.c:lxc_setup:3611 - Failed to setup mount entries
lxc-start redhat 20190625211748.599 ERROR start - start.c:do_start:1263 - Failed to setup container "redhat"
lxc-start redhat 20190625211748.600 ERROR sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 5)
lxc-start redhat 20190625211748.600 DEBUG network - network.c:lxc_delete_network:3180 - Deleted network devices
lxc-start redhat 20190625211748.600 DEBUG lxccontainer - lxccontainer.c:wait_on_daemonized_start:830 - First child 22344 exited
lxc-start redhat 20190625211748.600 ERROR lxccontainer - lxccontainer.c:wait_on_daemonized_start:842 - Received container state "ABORTING" instead of "RUNNING"
lxc-start redhat 20190625211748.600 ERROR lxc_start - tools/lxc_start.c:main:330 - The container failed to start
lxc-start redhat 20190625211748.600 ERROR lxc_start - tools/lxc_start.c:main:333 - To get more details, run the container in foreground mode
lxc-start redhat 20190625211748.600 ERROR lxc_start - tools/lxc_start.c:main:336 - Additional information can be obtained by setting the --logfile and --logpriority options
lxc-start redhat 20190625211748.601 ERROR start - start.c:__lxc_start:1939 - Failed to spawn container "redhat"
lxc-start redhat 20190625211748.601 DEBUG conf - conf.c:idmaptool_on_path_and_privileged:2836 - The binary "/usr/bin/newuidmap" does have the setuid bit set
lxc-start redhat 20190625211748.601 DEBUG conf - conf.c:idmaptool_on_path_and_privileged:2836 - The binary "/usr/bin/newgidmap" does have the setuid bit set
lxc-start redhat 20190625211748.601 DEBUG conf - conf.c:lxc_map_ids:2928 - Functional newuidmap and newgidmap binary found

**Comment by stgraber** [comment]
Output suggests you may have an odd mount entry in your container's config, can you show the config file?

**Comment by chrismatchett** [comment]
Thanks Stéphane,

Cross posted in lxd there by mistale but couldn't find the delete issue button.

My config;

lxc.start.auto = 1 
lxc.mount.entry = /dev/console dev/console none bind,create=file 0 0
lxc.mount.entry = /dev/full dev/full none bind,create=file 0 0
lxc.mount.entry = /dev/null dev/null none bind,create=file 0 0
lxc.mount.entry = /dev/random dev/random none bind,create=file 0 0
lxc.mount.entry = /dev/tty dev/tty none bind,create=file 0 0
lxc.mount.entry = /dev/urandom dev/urandom none bind,create=file 0 0
lxc.mount.entry = /dev/zero dev/zero none bind,create=file 0 0
lxc.mount.entry = /sys/firmware/efi/efivars sys/firmware/efi/efivars none bind,optional 0 0
lxc.mount.entry = /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc none bind,optional 0 0
lxc.mount.auto = proc:mixed sys:ro
lxc.tty.max = 4
lxc.pty.max = 1024
lxc.arch = x86_64
lxc.seccomp.profile = /usr/share/lxc/config/common.seccomp
lxc.uts.name = redhat
lxc.net.0.type = veth
lxc.net.0.flags = up
lxc.net.0.link = lxcbr0
lxc.net.0.hwaddr = 00:16:3e:be:05:73
lxc.cap.drop = mac_admin
lxc.cap.drop = mac_override
lxc.cap.drop = setfcap
lxc.cap.drop = sys_module
lxc.cap.drop = sys_nice
lxc.cap.drop = sys_pacct
lxc.cap.drop = sys_rawio
lxc.cap.drop = sys_time
lxc.idmap = u 0 100000 65536
lxc.idmap = g 0 100000 65536
lxc.hook.clone = /usr/share/lxc/hooks/clonehostname
lxc.rootfs.path = /home/chris/.local/share/lxc/redhat/rootfs

**Comment by chrismatchett** [comment]
> Output suggests you may have an odd mount entry in your container's config, can you show the config file?

I can't find this locally, not sure what it is?

/sys/firmware/efi/efivars

Ta,

Chrsi

**Comment by stgraber** [comment]
Shouldn't matter as it's marked optional.

My guess is that you've got a conflict between those device nodes you're attempting to pass yourself and those that come out of the box through autodev these days.

Maybe try adding `lxc.autodev = 0` to try and force the old behavior?

**Comment by chrismatchett** [comment]
> Shouldn't matter as it's marked optional.
> 
> My guess is that you've got a conflict between those device nodes you're attempting to pass yourself and those that come out of the box through autodev these days.
> 
> Maybe try adding `lxc.autodev = 0` to try and force the old behavior?

Stéphane,

Your suggestion fixed it. Thank you for your work on lxc. I have been using it for years and love it.

Chris
