### ISSUE TITLE
Can LXC_NET_NS be exported when net hook being executed?

### ISSUE THREAD

**Issue by ss1h2a3tw** [lxc/lxc#3066]
# Issue description

Since the net hook script may need to modify the network configs in the lxc's network namespace. Exporting this variable will be helpful.

**Comment by stgraber** [comment]
Seems reasonable to me, can you send a PR that adds the environment variable?

**Comment by ss1h2a3tw** [comment]
I found that the  `LXC_[NAMESPACE IDENTIFIER]_NS` are not set even in the start-host hook. Is it intentional?

**Comment by ss1h2a3tw** [comment]
But if `LXC_PID` are set, maybe this variable won't be needed. Because during starting the container, the script can get the namespace by `/proc/PID/ns`. Maybe moving the setenv of the `LXC_PID` forward will be a easier approach.

**Comment by stgraber** [comment]
@brauner @tomponline I'm guessing you two will have a stronger opinion than I do

**Comment by tomponline** [comment]
@brauner has said in the past that LXC_PID can.be used for this as @ss1h2a3tw says.

**Comment by ss1h2a3tw** [comment]
I found that the time that the hook being executed will differ by whether the lxc is running as root. If it is running as root, the hook will be executed before clone(). If not running as root, the hook will be executed after clone(). So `LXC_PID` or `LXC_NET_NS` will be only available for the hook if the user is not root.

**Comment by brauner** [comment]
For containers started as root neither LXC_PID nor LXC_NET_NS can be made available since it is done before the container is started. But I'm sure we could redesign this.
