### ISSUE TITLE
lxc might want to umount /proc/sys/net if dropping CAP_NET_ADMIN

### ISSUE THREAD

**Issue by eqvinox** [lxc/lxc#3091]
in a container configured with:

```
lxc.cap.drop = net_admin
lxc.mount.auto = proc:mixed
```

it doesn't make sense for `/proc/sys/net` to be mounted read-write, but it still is.  While write accesses will still fail due to CAP_NET_ADMIN checks in the kernel, removing the read-write mount provides an extra layer of security.

This is particularly relevant if sharing the host netns, e.g.:
```
lxc.cap.drop = net_admin
lxc.net.0.type = none
lxc.mount.auto = proc:mixed
```
but in general if CAP_NET_ADMIN is dropped, that should drop `/proc/sys/net` too.

(Same theoretically applies to `/sys/devices/virtual/net`, but as far as I know the kernel just refuses to mount sysfs at all if the netns isn't owned by the caller — at least I haven't been able to mount sysfs in these containers.  Don't need it either.)

Maybe a `LXC_AUTO_PROC_MIXED_NONET` could be added to be used here? https://github.com/lxc/lxc/blob/4f71ecb85e59e0671f6ab3634002a6c77292b107/src/lxc/conf.c#L676-L708

**Comment by stgraber** [comment]
@brauner what do you think?

Assuming that we expect every file in there to always require cap_net_admin for write access (don't know if true), then marking it read-only if instructed to drop cap_net_admin doesn't feel wrong to me and should be reasonably easy to do.

If however we know or expect that there may be files in /proc/sys/net which will purposeful allow writes from non cap_net_admin tasks, then we shouldn't do this.

**Comment by zhenr667** [comment]
Is it ok if my team and I tackle this issue?

**Comment by stgraber** [comment]
Certainly, assigned it to you!

**Comment by stgraber** [comment]
The logic to look at is in `lxc_mount_auto_mounts`, this is what causes a special read-write mount of `/proc/sys/net`.

There are two entries in the `default_mounts` struct that are all used to make `/proc/sys/net` read-write while the rest of `/proc/sys` is kept read-only.

`/proc/sys/net mounted on /proc/tty`
`/proc/tty mount back onto /proc/sys/net`

Both of those should be skipped if the container config drops CAP_NET_ADMIN.

Look like there is a `in_caplist` helper that may help perform the actual check. It may be easiest to extend the `default_mounts` struct to add a capability member which would be set to CAP_NET_ADMIN in this case while the rest is just a default 0.
Then during iterating through the struct, any entry that specifies a cap and where that cap is missing would be skipped.

@brauner thoughts?

**Comment by zhenr667** [comment]
@stgraber I believe this is issue should be resolved now.
