### ISSUE TITLE
bind mount not working with Android

### ISSUE THREAD

**Issue by riddhiterminator** [lxc/lxc#3098]
# Required information

*`lxc-start --version`
2.0.9

*`uname -r`
4.9.135+

*`lxc-checkconfig`
— Namespaces —
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
newuidmap is not installed
newgidmap is not installed
Network namespace: enabled

— Control groups —
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/devices
/sys/fs/cgroup/memory
/sys/fs/cgroup/cpu
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/cpuacct
/sys/fs/cgroup/pids
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/debug
/sys/fs/cgroup/freezer

Cgroup v2 mount points:

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

— Misc —
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, not loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, not loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

— Checkpoint/Restore —
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities:

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

# Issue description
I am working LXC 2.0.9 and running `Android` using LXC, on my custom hardware.

I am trying to bind mount a file from my Linux host to Android container via config file,
`lxc.mount.entry = /dev/usock dev/usock none bind,optional,create=file`

However, once Android is running and if I check,  `dev/usock` never exist inside that.

What may be reason here ?

**Comment by hallyn** [comment]
It seems likely that android userspace overmounted the /dev.

You can find out more by (a) looking at /proc/1/mounts in the container to see what is mounted on /dev, and (b) starting the container with -l trace -o trace.out and looking through trace.out to see whether /dev/usock did in fact get mounted.

Also, if you remove the 'optional' from the lxc.mount.entry, then if the file fails to get mounted for some reason, the container will faill to start, so that should help figure out where it's going wrong.

**Comment by riddhiterminator** [comment]
Hi Hallyn,

In container, usock is mounted
```
cat /proc/1/mounts  | grep usock
devtmpfs /dev/usock devtmpfs rw,seclabel,relatime,size=1980916k,nr_inodes=495229,mode=755 0 0
```

But there is one more mount on /dev. So you are right, Android is over-mouting it.

1) Is there any way I can prevent this over mounting  with LXC configs only ?  or configure LXC to bind mount this only after Android mounts on /dev is completed ?
2) LXCFS is still working fine, even though Android is mounting its own ```procfs``` at ```/proc```. How ?

**Comment by riddhiterminator** [comment]
Over mounting of /dev or any other, we need to take care in rootfs of container only.
In my case I created a separated file in rootfs image itself at other location than /dev, which  no one is using. So no over mounting on top of that if I configure container to mount host file at that location in container.

```So we can close this```. However it would be better if we get some details on "if we want to bind mount something in container at some specif point say only after container mount /dev or /proc".
Is this possible via some hooks or something else ?

**Comment by brauner** [comment]
I'd suggest trying to run on android with lxc master. We've made some fixes to get this to work better.
