### ISSUE TITLE
SIGWINCH not sent to lxc-console

### ISSUE THREAD

**Issue by Rachid-Koucha** [lxc/lxc#3099]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: ubuntu
 * Distribution version: Ubuntu 18.04.2 LTS
 * The output of
   * `lxc-start --version` ==> 3.1.0-devel

# Issue description

when calling "lxc-console -n name -t 1", the SIGWINCH signal is not sent to lxc-console process when the xterminal is resized.

The problem seems to come from the fact that "terminal.c/lxc_console()" calls setsid() which creates a new terminal session. Hence, when the xterminal is resized, the SIGWINCH is not sent to this new session. So, lxc-console never receives SIGWINCH.

I made a "strace" try with and without a call to setsid() in "terminal.c/lxc_console()" :

====> WITH the call to setsid(), the mainloop() doesn't receive any SIGWINCH notification :

epoll_wait(6, [{EPOLLIN, {u32=3920200320, u64=93853250585216}}], 10, -1) = 1
read(4, "/root\r\n~ # \33[6n", 1024)    = 15
write(1, "/root\r\n~ # \33[6n", 15/root
~ # [6n)     = 15

epoll_wait(6, [{EPOLLIN, {u32=3920200256, u64=93853250585152}}], 10, -1) = 1
read(0, "\1", 1)                        = 1

epoll_wait(6, [{EPOLLIN, {u32=3920200256, u64=93853250585152}}], 10, -1) = 1
read(0, "q", 1)                         = 1

ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_CONTINUE or TCSETSF, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
close(6)                                = 0
close(5)                                = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
close(4)                                = 0
close(3)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++

====> WITHOUT the call to setsid(), the mainloop() receives the SIGWINCH notifications :

epoll_wait(6, [{EPOLLIN, {u32=703586624, u64=94575883444544}}], 10, -1) = 1
read(5, "\34\0\0\0\0\0\0\0\200\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 128) = 128
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, TIOCGWINSZ, {ws_row=37, ws_col=235, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(4, TIOCSWINSZ, {ws_row=37, ws_col=235, ws_xpixel=0, ws_ypixel=0}) = 0
epoll_wait(6, [{EPOLLIN, {u32=703586944, u64=94575883444864}}], 10, -1) = 1
read(4, "\r~ # \33[J", 1024)            = 8
write(1, "\r~ # \33[J", 8
~ # [J)              = 8
epoll_wait(6, [{EPOLLIN, {u32=703586880, u64=94575883444800}}], 10, -1) = 1
read(0, "\1", 1)                        = 1
epoll_wait(6, [{EPOLLIN, {u32=703586880, u64=94575883444800}}], 10, -1) = 1
read(0, "q", 1)                         = 1
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_CONTINUE or TCSETSF, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
close(6)                                = 0
close(5)                                = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
close(4)                                = 0
close(3)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++

**Comment by brauner** [comment]
This is not reproducible with current master anymore. If the issue still exists, please reopen.
