### ISSUE TITLE
lxc-attach command does not return error exit code if the command is failed

### ISSUE THREAD

**Issue by aston-r** [lxc/lxc#3104]
Hi,

```
[#]> cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

Here is example with 3.1.0:
```
[$]> lxc-start --version
3.1.0
[#]> lxc-attach --logpriority=DEBUG --name=1_oracledb -- exit
lxc-attach: 1_oracledb: attach.c: lxc_attach_run_command: 1544 No such file or directory - Failed to exec "exit"
[#]> echo $?
127 <-----!!!!!!!!!!!!!
```

Here is example with 3.2.1:
```
[#]> lxc-start --version
3.2.1
[#]> lxc-attach --logpriority=DEBUG --name=1_oracledb -- exit
lxc-attach: 1_oracledb: attach.c: lxc_attach_run_command: 1503 No such file or directory - Failed to exec "exit"
[#]> echo $?
0 <-----!!!!!!!!!!!!!
```

As you can see lxc-attach returns '0' exit code even if the command is failed. Let me know if you need additional info.

**Comment by danmilon** [comment]
Got bitten by that too!
The debian maintainers have fixed [in their own repo](https://salsa.debian.org/lxc-team/lxc/commit/ea29d53e2093e67bfb58e1b8d5bf6caf60bacba8).

**Comment by Blub** [comment]
This should already be patched in git: https://github.com/lxc/lxc/commit/576b950f6c3b1f7d8d32d9e5c3e6ec053e393765

**Comment by danmilon** [comment]
Indeed, thank you.

I'd suggest releasing 3.2.2 asap, cause this is a critical feature that a lot of software depends on.
