### ISSUE TITLE
Containers fail to start regression lxc 3.2

### ISSUE THREAD

**Issue by SibrenVasse** [lxc/lxc#3108]
# Required information
 * Distribution: Archlinux
 * Distribution version: Rolling
 * The output of
   * `lxc-start --version`
```
3.2.1
```
   * `lxc-checkconfig`
```
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/memory
/sys/fs/cgroup/blkio
/sys/fs/cgroup/freezer
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/pids
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/devices
/sys/fs/cgroup/rdma

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```
   * `uname -a`
```
Linux hostname 5.2.3-arch1-1-ARCH #1 SMP PREEMPT Fri Jul 26 08:13:47 UTC 2019 x86_64 GNU/Linux
```
   * `cat /proc/self/cgroup`
```
12:rdma:/
11:devices:/user.slice
10:cpuset:/
9:pids:/user.slice/user-1000.slice/session-2.scope
8:hugetlb:/
7:net_cls,net_prio:/
6:freezer:/
5:blkio:/
4:memory:/user.slice/user-1000.slice/session-2.scope
3:perf_event:/
2:cpu,cpuacct:/
1:name=systemd:/user.slice/user-1000.slice/session-2.scope
0::/user.slice/user-1000.slice/session-2.scope
```
   * `cat /proc/1/mounts`
```
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sys /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
dev /dev devtmpfs rw,nosuid,relatime,size=8151640k,nr_inodes=2037910,mode=755 0 0
run /run tmpfs rw,nosuid,nodev,relatime,mode=755 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
/dev/sdb2 / ext4 rw,noatime,data=writeback 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup2 /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=31,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=17575 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
/dev/sdb1 /boot vfat rw,nosuid,nodev,noexec,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0
/dev/sda1 /home ext4 rw,nosuid,nodev,noatime,data=writeback 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=1639280k,mode=700,uid=1000,gid=985 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=985 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
```
# Issue description
After upgrading to 3.2.1 my privileged containers fail to start. Issue disappears after downgrade to 3.1.0. So this is probably a regression from 3.1 to 3.2.
Using [this workaround](https://discuss.linuxcontainers.org/t/cannot-launch-containers-with-lxd-3-15-and-lxc-3-2-1/5346/3) seems to solve the issue.
Downstream bugreport https://bugs.archlinux.org/task/63277

# Information to attach
 - [x] any relevant kernel output (`dmesg`)
no relevant parts
 - [x] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
[debug.log](https://github.com/lxc/lxc/files/3438604/debug.log)
 - [x] the containers configuration file
[config.txt](https://github.com/lxc/lxc/files/3438607/config.txt)

**Comment by graysky2** [comment]
Is [FS#61078](https://bugs.archlinux.org/task/61078) relevant here?

**Comment by SibrenVasse** [comment]
I'm starting my containers using lxc-start -n <container>, so I don't think editing systemd service files will change anything?

**Comment by graysky2** [comment]
Interesting... one difference I see between our 2 setups is that you generated your config with lxc-download whereas I used an older [template](https://aur.archlinux.org/packages/lxc-templates/).  I can start/stop from systemd or via `lxc-xxxx`.

**Comment by SibrenVasse** [comment]
I've bisected the issue.
```
git bisect start
# good: [4dcd858b92d4135024290d70534c245e9cdd8d6d] Release LXC 3.1.0
git bisect good 4dcd858b92d4135024290d70534c245e9cdd8d6d
# bad: [ad48c77c50cf7c3451177d665bbed9831ae6541e] Release LXC 3.2.1
git bisect bad ad48c77c50cf7c3451177d665bbed9831ae6541e
# skip: [2009688da461547d674a3b076488579a75311820] Merge pull request #2901 from brauner/2019-03-11/compiler_flags
git bisect skip 2009688da461547d674a3b076488579a75311820
# skip: [92db57092b683ac61706477e56c8ef53674ac5c7] attach: cleanup macros lxc_put_attach_clone_[...]
git bisect skip 92db57092b683ac61706477e56c8ef53674ac5c7
# bad: [0f03b15592fc76f29360df3aa028a78434f274dd] Merge pull request #3074 from brauner/2019-07-03/fix_phys_network_creation
git bisect bad 0f03b15592fc76f29360df3aa028a78434f274dd
# skip: [84b31b36b119e01e8f5a15bd94b7d53737be77a0] Merge pull request #2889 from tomponline/tp-2019-03-02/bugfixes
git bisect skip 84b31b36b119e01e8f5a15bd94b7d53737be77a0
# good: [978dfc7ec4b2241bafcccd68a69e8f5fb1a883c6] Merge pull request #2956 from brauner/2019-04-29/seccomp_trap_cleanup
git bisect good 978dfc7ec4b2241bafcccd68a69e8f5fb1a883c6
# good: [6ae34d21696c25de0264ce60a1641011cd17f20d] Merge pull request #3006 from tomponline/tp-phys-downhook
git bisect good 6ae34d21696c25de0264ce60a1641011cd17f20d
# bad: [16512e0c36e3e0097c289418885eb12e78277146] Merge pull request #3039 from brauner/master
git bisect bad 16512e0c36e3e0097c289418885eb12e78277146
# bad: [39cb2d9ee8f07cfe885defc9794d14799923aa0c] start: fix handler memory leak at lxc_init failed
git bisect bad 39cb2d9ee8f07cfe885defc9794d14799923aa0c
# good: [18a405ee88419e0799cf8849f1ad468c859615ba] Merge pull request #2987 from tych0/pass-zero-to-clone
git bisect good 18a405ee88419e0799cf8849f1ad468c859615ba
# good: [1eaa8c428a5d81c256246a375f634be0273a72d2] Merge pull request #3024 from avkvl/fix_groups_with_a_lot_of_members
git bisect good 1eaa8c428a5d81c256246a375f634be0273a72d2
# bad: [94d3c14dd72f6015e7d42bdd0d26870b6d97fd50] Merge pull request #3014 from brauner/2019-05-24/cgroups_handle_offline_cpus
git bisect bad 94d3c14dd72f6015e7d42bdd0d26870b6d97fd50
# bad: [36f7018103cd66cc16128b04200df15320472a54] cgroups: handle offline cpus in v1 hierarchy
git bisect bad 36f7018103cd66cc16128b04200df15320472a54
# first bad commit: [36f7018103cd66cc16128b04200df15320472a54] cgroups: handle offline cpus in v1 hierarchy
```
```
36f7018103cd66cc16128b04200df15320472a54 is the first bad commit
commit 36f7018103cd66cc16128b04200df15320472a54
Author: Christian Brauner <christian.brauner@ubuntu.com>
Date:   Fri May 24 15:59:57 2019 +0200

    cgroups: handle offline cpus in v1 hierarchy
    
    Handle offline cpus in v1 hierarchy.
    
    In addition to isolated cpus we also need to account for offline cpus when our
    ancestor cgroup is the root cgroup and we have not been initialized yet.
    
    Closes #2953.
    
    Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

 src/lxc/cgroups/cgfsng.c | 135 ++++++++++++++++++++++++++---------------------
 1 file changed, 75 insertions(+), 60 deletions(-)
```
Issue is no longer present when building 3.2.1 with this commit reverted.
```
cat /sys/devices/system/cpu/isolated

```
```
cat /sys/devices/system/cpu/offline
12-31
```

**Comment by brauner** [comment]
Yeah, thanks for doing that.
I'll take a look at fixing this today.

On July 28, 2019 10:26:21 AM EDT, Sibren Vasse <notifications@github.com> wrote:
>I've bisected the issue.
>```
>git bisect start
># good: [4dcd858b92d4135024290d70534c245e9cdd8d6d] Release LXC 3.1.0
>git bisect good 4dcd858b92d4135024290d70534c245e9cdd8d6d
># bad: [ad48c77c50cf7c3451177d665bbed9831ae6541e] Release LXC 3.2.1
>git bisect bad ad48c77c50cf7c3451177d665bbed9831ae6541e
># skip: [2009688da461547d674a3b076488579a75311820] Merge pull request
>#2901 from brauner/2019-03-11/compiler_flags
>git bisect skip 2009688da461547d674a3b076488579a75311820
># skip: [92db57092b683ac61706477e56c8ef53674ac5c7] attach: cleanup
>macros lxc_put_attach_clone_[...]
>git bisect skip 92db57092b683ac61706477e56c8ef53674ac5c7
># bad: [0f03b15592fc76f29360df3aa028a78434f274dd] Merge pull request
>#3074 from brauner/2019-07-03/fix_phys_network_creation
>git bisect bad 0f03b15592fc76f29360df3aa028a78434f274dd
># skip: [84b31b36b119e01e8f5a15bd94b7d53737be77a0] Merge pull request
>#2889 from tomponline/tp-2019-03-02/bugfixes
>git bisect skip 84b31b36b119e01e8f5a15bd94b7d53737be77a0
># good: [978dfc7ec4b2241bafcccd68a69e8f5fb1a883c6] Merge pull request
>#2956 from brauner/2019-04-29/seccomp_trap_cleanup
>git bisect good 978dfc7ec4b2241bafcccd68a69e8f5fb1a883c6
># good: [6ae34d21696c25de0264ce60a1641011cd17f20d] Merge pull request
>#3006 from tomponline/tp-phys-downhook
>git bisect good 6ae34d21696c25de0264ce60a1641011cd17f20d
># bad: [16512e0c36e3e0097c289418885eb12e78277146] Merge pull request
>#3039 from brauner/master
>git bisect bad 16512e0c36e3e0097c289418885eb12e78277146
># bad: [39cb2d9ee8f07cfe885defc9794d14799923aa0c] start: fix handler
>memory leak at lxc_init failed
>git bisect bad 39cb2d9ee8f07cfe885defc9794d14799923aa0c
># good: [18a405ee88419e0799cf8849f1ad468c859615ba] Merge pull request
>#2987 from tych0/pass-zero-to-clone
>git bisect good 18a405ee88419e0799cf8849f1ad468c859615ba
># good: [1eaa8c428a5d81c256246a375f634be0273a72d2] Merge pull request
>#3024 from avkvl/fix_groups_with_a_lot_of_members
>git bisect good 1eaa8c428a5d81c256246a375f634be0273a72d2
># bad: [94d3c14dd72f6015e7d42bdd0d26870b6d97fd50] Merge pull request
>#3014 from brauner/2019-05-24/cgroups_handle_offline_cpus
>git bisect bad 94d3c14dd72f6015e7d42bdd0d26870b6d97fd50
># bad: [36f7018103cd66cc16128b04200df15320472a54] cgroups: handle
>offline cpus in v1 hierarchy
>git bisect bad 36f7018103cd66cc16128b04200df15320472a54
># first bad commit: [36f7018103cd66cc16128b04200df15320472a54] cgroups:
>handle offline cpus in v1 hierarchy
>```
>```
>36f7018103cd66cc16128b04200df15320472a54 is the first bad commit
>commit 36f7018103cd66cc16128b04200df15320472a54
>Author: Christian Brauner <christian.brauner@ubuntu.com>
>Date:   Fri May 24 15:59:57 2019 +0200
>
>    cgroups: handle offline cpus in v1 hierarchy
>    
>    Handle offline cpus in v1 hierarchy.
>    
>In addition to isolated cpus we also need to account for offline cpus
>when our
>ancestor cgroup is the root cgroup and we have not been initialized
>yet.
>    
>    Closes #2953.
>    
>    Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>
>
>src/lxc/cgroups/cgfsng.c | 135
>++++++++++++++++++++++++++---------------------
> 1 file changed, 75 insertions(+), 60 deletions(-)
>```
>Issue is no longer present when building 3.2.1 with this commit
>reverted.
>```
>cat /sys/devices/system/cpu/isolated
>
>```
>```
>cat /sys/devices/system/cpu/offline
>12-31
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lxc/lxc/issues/3108#issuecomment-515767169

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brauner** [comment]
Can someone verify that https://github.com/lxc/lxc/pull/3109 fixes the issue, please?

**Comment by SibrenVasse** [comment]
It does for me, thank you.

**Comment by Flohack74** [comment]
Sorry to resurrect, but @brauner can you tell me in which version this finally landed? As you remember probably I was interested in getting the original issue fixed. Do you think we also need to patch this fix?
