### ISSUE TITLE
typo in sysvinit usage function

### ISSUE THREAD

**Issue by ghost** [lxc/lxc#311]
the sysvinit initscript uses this code within the usage function:

echo $"Usage: $0 {start|stop|restart|reload|force-reload}"

the first '$'-sign is a typo and should be removed.

**Comment by evgeni** [comment]
@stgraber can you please close this? https://github.com/lxc/lxc/commit/3083782cf871b7278f4643414bc060830659f6f4 is fixing it, but the closes line in the commit failed :(
