### ISSUE TITLE
[Debian][lxc.service] Missing After target?

### ISSUE THREAD

**Issue by P-EB** [lxc/lxc#3114]
Hi,

A Debian user asked me in bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920195 if the lxc.service file provided by you shouldn't include `remote-fs.target` in the `After` statement?

I'm interested in your input.

With best regards,

**Comment by brauner** [comment]
Sorry for the delay. It doesn't sound unreasonable. Feel free to send a patch
