### ISSUE TITLE
Issue with network interfaces created at run time

### ISSUE THREAD

**Issue by riddhiterminator** [lxc/lxc#3116]
# Required information

   * `lxc-start --version`
2.0.9
   * `lxc-checkconfig`
— Namespaces —
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
newuidmap is not installed
newgidmap is not installed
Network namespace: enabled

— Control groups —
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/devices
/sys/fs/cgroup/memory
/sys/fs/cgroup/cpu
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/cpuacct
/sys/fs/cgroup/pids
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/debug
/sys/fs/cgroup/freezer

Cgroup v2 mount points:

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

— Misc —
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, not loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, not loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

— Checkpoint/Restore —
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities:

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -r`
4.9.135+

# Issue description

I am running Android using lxc on Linux host. I am facing issue with run time network interfaces.
Whenever I insert any kernel module (let say WiFi driver module)from my container, the network interface (e.g. wlan0 )is by default created in Linux host only instead in container.
(Same thing I am facing with other network interfaces also)

Is it not possible to make network interface available only to the container network name space from which it was created at run time ?

**Comment by riddhiterminator** [comment]
@stgraber @brauner 
Can you please comment ?

**Comment by stgraber** [comment]
No, it's not. Module loading is global and new physical devices always appear in the initial network namespace.

Only virtual devices created inside a network namespace will appear in it.
