### ISSUE TITLE
SIGSEGV when starting a container in a host with misleading cgroup mounts

### ISSUE THREAD

**Issue by CajuM** [lxc/lxc#3126]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * lxc version: 3.0.3-0ubuntu1~18.04.1

# Issue description
When starting a container with a misleading /proc/self/mountinfo lxc crashes. This happens when  all cgroups have been bind mounted and cgroup namespaces were not used, as is the case with docker.
The problem is at https://github.com/lxc/lxc/blob/51a9e74bae816b034766fd93bd97457b91b87511/src/lxc/cgroups/cgfsng.c#L1318
since the code assumes that ops->hierarchies is not NULL and since no elements have been added to the list, it will segfault.

# Steps to reproduce
```
cat << EOF | docker run -i --rm --privileged ubuntu:bionic bash
apt-get update
apt-get -y install lxc-utils xz-utils wget gnupg2
lxc-create -t download -n test -- -d alpine -r edge -a amd64
sed -i '/net/d' /var/lib/lxc/test/config
cat /proc/self/mountinfo | grep ' cgroup' | grep -v /docker/ | cut -f5 -d' ' | xargs umount # this removes all mounted cgroups with valid controlers
lxc-start -F -n test
EOF
```

**Comment by brauner** [comment]
That's already fixed in master:
```
commit 69b4a4bbfdffc99053df289a1c1512b911072088
Author: Christian Brauner <christian.brauner@ubuntu.com>
Date:   Tue Jan 8 23:56:50 2019 +0100

    cgroups: try to handle layouts with no cgroups

    Cc: Ondrej Kubik <ondrej.kubik@canonical.com>
    Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>
```

**Comment by CajuM** [comment]
oh, ok
