### ISSUE TITLE
WLAN devices not renamed back to original name on host when container is stopped

### ISSUE THREAD

**Issue by tomponline** [lxc/lxc#3131]
# Required information

 * Distribution: All
 * Distribution version: N/A
 * The output of
   * `lxc-start --version` 3.1.2 (and current master)

# Issue description

When moving a physical WLAN device into a container, if the device is renamed inside the container such that it does not match the device name on the host, then when the container is stopped the device is moved back to the host's netns but with the device name that it had inside the container remains and the device is not renamed back to its original name.

# Steps to reproduce

 1. Step one
Install wifi device simulator model
`sudo modprobe mac80211_hwsim` 

 2. Step two
Create example config:

```
lxc.net.0.type = phys
lxc.net.0.link = wlan0
lxc.net.0.flags = up
lxc.net.0.name = eth0
```
 3. Step three

```
lxc-start <ct name>
lxc-stop <ct name>
```

 4. Step three

Device that was called `wlan0` is now called `eth0` on host.

**Comment by PSGXerus** [comment]
Thanks for adding the bug

**Comment by brauner** [comment]
This has been fixed for quite a while now. Sorry I missed to close this bug.
