### ISSUE TITLE
 lxc-stop 20000213072641.288 ERROR    lxc_commands - commands.c:lxc_cmd_stop:628 - Failed to stop container "CT1": Operation not permitted.

### ISSUE THREAD

**Issue by guoyanzhang0817** [lxc/lxc#3136]
I run a program on the lxc container. After running for a while, the container stops. After a while, it will restart automatically. It is found in the log file of /var/log/lxc. If the container stops, it will write a log ‘ lxc-stop 20000213072641.288 ERROR    lxc_commands - commands.c:lxc_cmd_stop:628 - Failed to stop container "CT1": Operation not permitted.’ in the log file. in. What causes the container to reboot?

**Comment by guoyanzhang0817** [comment]
**the 'lxc_cmd_stop' function just be called by the 'do_lxcapi_stop' function, but But there is no function to call the ‘do_lxcapi_stop’ function. why?**
static bool do_lxcapi_stop(struct lxc_container *c)
1206 {
1207     int ret;
1208
1209     if (!c)
1210         return false;
1211
1212     ret = lxc_cmd_stop(c->name, c->config_path);
1213
1214     return ret == 0;
1215 }

**Comment by brauner** [comment]
This false positive should be fixed upstream now. Sorry for the delay!
