### ISSUE TITLE
lxc-copy should not copy lxc.mount.entry entries or issue a warning

### ISSUE THREAD

**Issue by shubhra-prakash-nandi** [lxc/lxc#3138]
# Required information

 * Distribution: Debian
 * Distribution version: 10
 * The output of
   * `lxc-start --version` : 3.0.3
   * `lxc-checkconfig`

Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.19.0-5-amd64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/devices
/sys/fs/cgroup/blkio
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/rdma
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/pids
/sys/fs/cgroup/memory
/sys/fs/cgroup/freezer

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

# Issue description

I have a container old-lxc with manually defined mount point for a filesystem directory in it's config using lxc.mount.entry directive.

I copied that container using lxc-copy --name old-lxc --newname new-lxc

The new container now has the same mount point (pointing to the same directory). Now if I start both containers, I can edit the same location from both places without one container knowing about the other. I think it can be a good idea to issue a warning that old container has mount points defined, so that the same can be updated in new container.

**Comment by stgraber** [comment]
I wouldn't mind a warning, for entries outside of /dev, /proc or /sys (such as the default mounts).

**Comment by shubhra-prakash-nandi** [comment]
Thanks! Stéphane.

**Comment by brauner** [comment]
We'd have to parse each mount entry and warn if it contains a reference to the old container. That would involve writing a temporary mount file etc pp. That's also not how the parser during copy works and then we'd likely also need to make this handle includes and fstab entries which we can't modify anyway. So sorry, that's out of scope imho.
