### ISSUE TITLE
dcaches use up memory, container runs OOM

### ISSUE THREAD

**Issue by styx-tdo** [lxc/lxc#3143]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16
 * The output of
   * `lxc-start --version` 
3.0.3
   * `lxc-checkconfig`
N/A
   * `uname -a`
Linux vie01a-pemc-phost-pe33 4.15.0-55-generic #60~16.04.2-Ubuntu SMP Thu Jul 4 09:03:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
12:memory:/user.slice
11:cpuset:/
10:devices:/user.slice
9:perf_event:/
8:freezer:/
7:rdma:/
6:net_cls,net_prio:/
5:blkio:/user.slice
4:cpu,cpuacct:/user.slice
3:hugetlb:/
2:pids:/user.slice/user-1808.slice
1:name=systemd:/user.slice/user-1808.slice/session-483.scope
   * `cat /proc/1/mounts`
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=65917972k,nr_inodes=16479493,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=13189588k,mode=755 0 0
/dev/mapper/vgroot-lvroot / ext4 rw,relatime,stripe=128,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=21,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=36899 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
sunrpc /run/rpc_pipefs rpc_pipefs rw,relatime 0 0
nfsd /proc/fs/nfsd nfsd rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
tmpfs /var/lib/lxd/shmounts tmpfs rw,relatime,size=100k,mode=711 0 0
tmpfs /var/lib/lxd/devlxd tmpfs rw,relatime,size=100k,mode=755 0 0
lxd/containers/vie01a-pemc-pdmta-at50 /var/lib/lxd/storage-pools/default/containers/vie01a-pemc-pdmta-at50 zfs rw,relatime,xattr,noacl 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
lxd/containers/vie01a-pemc-pmxin-at51 /var/lib/lxd/storage-pools/default/containers/vie01a-pemc-pmxin-at51 zfs rw,relatime,xattr,noacl 0 0
tmpfs /run/user/2501 tmpfs rw,nosuid,nodev,relatime,size=13189588k,mode=700,uid=2501,gid=14 0 0
tmpfs /run/user/1808 tmpfs rw,nosuid,nodev,relatime,size=13189588k,mode=700,uid=1808,gid=10 0 0

# Issue description

Host has 125G RAM
One container has 32G RAM.
after some time (~2 weeks), slabtop dentries go up to 155 mio files, blocking a huge chonk of memory.
fresh:
5494146 5484413  99%    0.19K 130813       42   1046504K dentry
When issue is there:
Active / Total Objects (% used)    : 159212338 / 159389534 (99.9%)
Active / Total Slabs (% used)      : 3787709 / 3787709 (100.0%)
Active / Total Caches (% used)     : 96 / 139 (69.1%)
Active / Total Size (% used)       : 30481941.86K / 30528329.44K (99.8%)
Minimum / Average / Maximum Object : 0.01K / 0.19K / 22.88K

The container ran out of memory at that point in time.

echo 2 >  > /proc/sys/vm/drop_caches 
works, but impacts the services negitively and doesn't make sense to run scheduled
We tried tuning:
sysctl vm.vfs_cache_pressure=100000
sysctl vm.overcommit_ratio=2
sysctl vm.dirty_background_ratio=99
sysctl vm.dirty_ratio=98
to no avail. Memory usage in the ct still showed 29G used, even after container restart.

Also, see:
https://discuss.linuxcontainers.org/t/strange-ram-usage-on-host/3601

# Steps to reproduce
Let container with 10% of total mem run, when memory avail on host is high

# Information to attach

 - [x] any relevant kernel output (`dmesg`)
 - [x] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
 - [x] the containers configuration file
architecture: x86_64
config:
  volatile.base_image: 405d4fdfe6d5cbc3dd28c9f57a356c09c1affbe4d86f87a576798906ebc24bc1
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices: {}
ephemeral: false
profiles:
- PROD_XXXXX
stateful: false
description: ""

**Comment by stgraber** [comment]
Bug report seems to be mixing LXD and LXC which makes it confusing.

In either case, this seems to be reporting a cgroup bug in the kernel, not something that LXC or LXD can directly influence.

I'd recommend testing on the most recent kernel you can get your hands on, possibly trying on cgroupv2 as well and if the issue still occurs, then a kernel bug report is in order.
