### ISSUE TITLE
Clone hooks receive wrong rootfs information on ZFS storage backend

### ISSUE THREAD

**Issue by danielkza** [lxc/lxc#316]
Running Ubuntu 14.04 with LXC 1.0.5 and ZFSOnLinux 0.6.3.

While cloning a container stored on ZFS with a clone hook set up, the hook script receives wrong environment variables for rootfs information. For example, creating a container named `zfs-test` with the default `lxcpath` of `/var/lib/lxc`, the clone hook receives:

`LXC_ROOTFS_MOUNT` => `/usr/lib/x86_64-linux-gnu/lxc`
`LXC_ROOTFS_PATH` => `/var/lib/lxc/zfs-test/rootfs`

Notice how the container name is nowhere to be seen in the mount path.

The filesystem is properly created and mounted at it's `lxcpath` subdirectory though. So right now I'm working around the issue by checking if `LXC_ROOTFS_PATH` is a directory and using it in lieu of `LXC_ROOTFS_MOUNT`.

This actually looks like a combination of weird behaviors to me.
- Obviously the mount path is not being properly updated for ZFS containers. Also, to be in line with the other backends, the device path should actually be the name of the filesystem, like `tank/containers/{container}`.
- The container should probably be mounted, as non-ZFS ones are, in the temporary directory instead of at it's final location during cloning, since the hooks can fail and leave an undermined state. The mountpoint can be altered to the correct one after the cloning finishes with the `zfs set` command.
- `/usr/lib` seems like a really weird place to do the mounting. `/run`, `/var/tmp`, or even something like `/var/lib/lxc/{container}/rootfs-tmp` would fit the usage better, would they not? Is there a specific reason for this choice that am I missing?

**Comment by brauner** [comment]
The storage backends have been reworked substantially please re-open if the issue still exists.
