### ISSUE TITLE
lxc does not work on centos8 headless (installed from source)

### ISSUE THREAD

**Issue by scgbckbone** [lxc/lxc#3162]
# Required information

```
uname -a
Linux localhost.localdomain 4.18.0-80.7.1.el8_0.x86_64 #1 SMP Sat Aug 3 15:14:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/centos-release
CentOS Linux release 8.0.1905 (Core) 

lxc-start --version
3.0.4

lxc-create --version
3.0.4

cat /proc/self/cgroup                                                                       
12:perf_event:/
11:hugetlb:/
10:pids:/user.slice/user-1000.slice/session-10.scope
9:memory:/user.slice/user-1000.slice/session-10.scope
8:devices:/user.slice
7:cpu,cpuacct:/
6:net_cls,net_prio:/
5:rdma:/
4:freezer:/
3:blkio:/user.slice
2:cpuset:/
1:name=systemd:/user.slice/user-1000.slice/session-10.scope

cat /proc/1/mounts
sysfs /sys sysfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
devtmpfs /dev devtmpfs rw,seclabel,nosuid,size=30821868k,nr_inodes=7705467,mode=755 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,seclabel,nosuid,nodev 0 0
devpts /dev/pts devpts rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,seclabel,nosuid,nodev,mode=755 0 0
tmpfs /sys/fs/cgroup tmpfs ro,seclabel,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,seclabel,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,seclabel,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,seclabel,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,seclabel,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,seclabel,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,seclabel,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,seclabel,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,seclabel,nosuid,nodev,noexec,relatime,perf_event 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
/dev/mapper/cl-root / xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,seclabel,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,seclabel,relatime,pagesize=2M 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=40,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=16948 0 0
mqueue /dev/mqueue mqueue rw,seclabel,relatime 0 0
/dev/sda1 /boot ext4 rw,seclabel,relatime 0 0
tmpfs /run/user/1000 tmpfs rw,seclabel,nosuid,nodev,relatime,size=6167420k,mode=700,uid=1000,gid=1000 0 0

lxc-checkconfig
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.18.0-80.7.1.el8_0.x86_64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled
Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/blkio
/sys/fs/cgroup/freezer
/sys/fs/cgroup/rdma
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/devices
/sys/fs/cgroup/memory
/sys/fs/cgroup/pids
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/perf_event

Cgroup v2 mount points:

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, not loaded
Advanced netfilter: enabled, loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled

File capabilities:
Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/local/bin/lxc-checkconfig
```

# Issue description

I cannot make lxc to work on centos8. After I installed lxc (as in steps to reproduce) I'm getting different errors for different commands.

`lxc-create -n centos -t centos` fails with:
 lxc-create: centos: conf.c: chown_mapped_root: 3182 lxc-usernsexec failed: No such file or directory - Failed to open ttyNo such file or directory - Failed to open tt
lxc-create: centos: tools/lxc_create.c: main: 331 Failed to create container centos

`sudo /usr/local/bin/lxc-create -n ubuntu -t ubuntu` fails with:
Host CPE ID from /etc/os-release: cpe:/o:centos:centos:8
Checking cache download in /usr/local/var/cache/lxc/centos/x86_64/8/rootfs ...
Downloading CentOS minimal ...
Unable to detect release version (use '--releasever' to specify release version)
CentOS-8 - Base                                                                       31  B/s |  38  B     00:01
Error: Failed to synchronize cache for repo 'base'
Reinstalling packages ...
mkdir: cannot create directory ‘/usr/local/var/cache/lxc/centos/x86_64/8/partial/etc/yum.repos.disabled’: File exists
mv: cannot stat '/usr/local/var/cache/lxc/centos/x86_64/8/partial/etc/yum.repos.d/*.repo': No such file or directory 
mknod: /usr/local/var/cache/lxc/centos/x86_64/8/partial//usr/local/var/cache/lxc/centos/x86_64/8/partial/dev/null: File exists
mknod: /usr/local/var/cache/lxc/centos/x86_64/8/partial//usr/local/var/cache/lxc/centos/x86_64/8/partial/dev/urandom: File exists
cp: cannot stat '/usr/local/var/cache/lxc/centos/x86_64/8/partial/var/cache/yum/*': No such file or directory
chroot: failed to run command ‘yum’: No such file or directory
Failed to download the rootfs, aborting.
Failed to download 'CentOS base'
failed to install CentOS
lxc-create: centos: lxccontainer.c: create_run_template: 1626 Failed to create container from template
lxc-create: centos: tools/lxc_create.c: main: 331 Failed to create container centos

`sudo /usr/local/bin/lxc-create -n ubuntu -t ubuntu` fail with:
'debootstrap' command is missing
lxc-create: ubuntu: lxccontainer.c: create_run_template: 1626 Failed to create container from template
lxc-create: ubuntu: tools/lxc_create.c: main: 331 Failed to create container ubuntu

however I am able to create container with download template:
`sudo /usr/local/bin/lxc-create -n centos -t download`
after lot of output from tar it pops that container is created yet I'm unable to start it
`sudo /usr/local/bin/lxc-start -n centos  -F ` fails with:
lxc-start: centos: network.c: lxc_ovs_attach_bridge: 2008 Failed to attach "lxcbr0" to openvswitch bridge "vethWZQ5QI": lxc-start: centos: utils.c: run_command_internal: 1648
lxc-start: centos: network.c: instantiate_veth: 173 Operation not permitted - Failed to attach "vethWZQ5QI" to bridge "lxcbr0"
lxc-start: centos: network.c: lxc_create_network_priv: 2577 Failed to create network device
lxc-start: centos: start.c: lxc_spawn: 1686 Failed to create the network
lxc-start: centos: start.c: __lxc_start: 2023 Failed to spawn container "centos"
lxc-start: centos: tools/lxc_start.c: main: 329 The container failed to start
lxc-start: centos: tools/lxc_start.c: main: 335 Additional information can be obtained by setting the --logfile and --logpriority options 

# Steps to reproduce

1. download centos8 iso and install server os (headless) with no additive packages
2. add your user ability tu run sudo without password  
3. run below script

```
#!/bin/bash

# do not forget to add below line to sudoers file
# <user> ALL=(ALL) NOPASSWD: ALL

sudo dnf update -y
sudo dnf groupinstall "Development Tools" -y
sudo dnf install epel-release -y
sudo dnf install git htop libtool openssl-devel libcap-devel wget -y

git clone https://github.com/lxc/lxc.git -b stable-3.0
cd lxc || exit 1
./autogen.sh
./configure
#--disable-dependency-tracking \
#--enable-apparmor \
#--enable-openssl \
#--enable-selinux \
#--enable-capabilities \
#--enable-tests

make
sudo make install

cd ~ || exit 1
git clone https://github.com/lxc/lxc-templates.git
cd lxc-templates || exit 1
./autogen.sh
./configure
make
sudo make install

cd ~ || exit 1

sudo chmod u+s /usr/bin/new{g,u}idmap

mkdir -p ~/.config/lxc/
cat >> ~/.config/lxc/default.conf<< EOF
lxc.include = /usr/local/etc/lxc/default.conf
lxc.idmap = u 0 100000 65536
lxc.idmap = g 0 100000 65536
EOF

echo "done"
```
4. try commands mentioned in issue description section

**Comment by stgraber** [comment]
Sounds like `lxc-usernsexec` cannot be located on your system somehow.
It could be because of the `PATH` environment variable or something else preventing that binary from being located.

You may want to try to run `lxc-usernsexec` directly, if it's found but is failing, try running it under `strace`.
