### ISSUE TITLE
unprivileged container cannot be created. lxc-usernsexec Failed to find subuid or subgid allocation

### ISSUE THREAD

**Issue by Qomolang** [lxc/lxc#3163]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution:SuSE 
 * Distribution version: SLE 12 SP4
 * The output of
   * `lxc-start --version`  
3.1.0
   * `lxc-checkconfig`
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/devices
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/blkio
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/memory
/sys/fs/cgroup/freezer
/sys/fs/cgroup/pids
/sys/fs/cgroup/rdma

Cgroup v2 mount points:

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, not loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, not loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities:

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -a`

Linux lfgphicprd12555 4.12.14-94.41-default #1 SMP Wed Oct 31 12:25:04 UTC 2018 (3090901) x86_64 x86_64 x86_64 GNU/Linux

   * `cat /proc/self/cgroup`

12:rdma:/user/root/0
11:pids:/user.slice/user-0.slice/session-563.scope
10:freezer:/user/root/0
9:memory:/user/root/0
8:perf_event:/user/root/0
7:blkio:/user/root/0
6:hugetlb:/user/root/0
5:net_cls,net_prio:/user/root/0
4:devices:/user/root/0
3:cpu,cpuacct:/user/root/0
2:cpuset:/user/root/0
1:name=systemd:/user.slice/user-0.slice/session-563.scope

   * `cat /proc/1/mounts`

sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
devtmpfs /dev devtmpfs rw,nosuid,size=8182580k,nr_inodes=2045645,mode=755 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,mode=755 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
/dev/xvda2 / ext3 rw,relatime,data=ordered 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=22,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14829 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
tmpfs /run/user/484 tmpfs rw,nosuid,nodev,relatime,size=1638548k,mode=700,uid=484,gid=483 0 0
tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=1638548k,mode=700 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0

# Issue description

it is fine to create and run a priviledged lxc container, but it goes wrong with creating a unpriviledge container, 

as a unprivileged user:
$ lxc-create -n pruefungg -t busybox
Permission denied - Failed to open ttyPermission denied - Failed to open ttyPermission denied - Failed to open tty

it seems the point is the lxc-usernsexec like #2764 
even as a root user:
$ lxc-usernsexec
Failed to find subuid or subgid allocation

i am sure i have the newuidmap and newgidmap 
$ newuidmap -h
usage: newuidmap <pid> <uid> <loweruid> <count> [ <uid> <loweruid> <count> ] ...
$ newgidmap -h
usage: newuidmap <pid> <uid> <loweruid> <count> [ <uid> <loweruid> <count> ] ...

i will also show the related information:

$  cat /etc/subgid
commonuser:100000:65536
qemu:165536:65536
tftp:231072:65536
dnsmasq:296608:65536
radvd:362144:65536

$  cat /etc/subuid
commonuser:100000:65536
qemu:165536:65536
tftp:231072:65536
dnsmasq:296608:65536
radvd:362144:65536

$  cat /etc/lxc/default.conf
lxc.net.0.type = veth
lxc.net.0.link = lxcbr0
lxc.net.0.flags = up
lxc.net.0.hwaddr = 00:16:3e:xx:xx:xx

$ cat /etc/permissions.local
/usr/lib/lxc/lxc-user-nic  root:root  04750
(after this step, 
$ chkstat --system --set && chmod u+s /usr/lib/lxc/lxc-user-nic 
is done)

$ cat /etc/pam.d/common-session
session optional        pam_cgfs.so -c all

$ cat  /etc/lxc/lxc-usernet
commonuser veth lxcbr0 10

$ ll /usr/bin/new{u,g}idmap
-rwsr-sr-x 1 root root 37888 Sep  5  2018 /usr/bin/newgidmap
-rwsr-sr-x 1 root root 33793 Oct 15 07:58 /usr/bin/newuidmap

$ ls -al /usr/lib/lxc/lxc-user-nic
-rwsr-x--- 1 root root 105921 Oct 14 01:37 /usr/lib/lxc/lxc-user-nic

if I still missed something, please tell me
 
# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
 - [ ] the containers configuration file

**Comment by Qomolang** [comment]
it is fixed.
it is a problem of permission. As the source code of lxc-usernsexec shows, it opens three files
/proc/self/fd/0 ttyname0
/proc/self/fd/1 ttyname1
/proc/self/fd/2 ttyname2
which link to /dev/pts 0 1 2 respectively.
so
$cd /dev/pts
$chmod 660 0 1 2 
then it goes well

**Comment by Abdull** [comment]
> it is fixed. it is a problem of permission. As the source code of lxc-usernsexec shows, it opens three files /proc/self/fd/0 ttyname0 /proc/self/fd/1 ttyname1 /proc/self/fd/2 ttyname2 which link to /dev/pts 0 1 2 respectively. so $cd /dev/pts $chmod 660 0 1 2 then it goes well

This looks very unsafe, see https://www.pc-freak.net/blog/how-to-work-around-screen-cannot-open-your-terminal-devpts1-please-check/ .
