### ISSUE TITLE
LXC 3.2.1 Source Build on Oracle Linux 8 Fails

### ISSUE THREAD

**Issue by gstanden** [lxc/lxc#3166]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Oracle Linux
 * Distribution version:  8
 * The output of
   * `lxc-start --version`
   * `lxc-checkconfig`
   * `uname -a`
inux oracle81 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Fri Sep 20 22:48:55 GMT 2019 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
[ubuntu@oracle81 anylinux]$ cat /proc/self/cgroup
12:perf_event:/
11:blkio:/user.slice
10:hugetlb:/
9:cpu,cpuacct:/
8:pids:/user.slice/user-1000.slice/session-2.scope
7:devices:/user.slice
6:rdma:/
5:freezer:/
4:cpuset:/
3:memory:/user.slice/user-1000.slice/session-2.scope
2:net_cls,net_prio:/
1:name=systemd:/user.slice/user-1000.slice/session-2.scope
[ubuntu@oracle81 anylinux]$ 

   * `cat /proc/1/mounts`
[ubuntu@oracle81 anylinux]$ cat /proc/1/mounts
sysfs /sys sysfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
devtmpfs /dev devtmpfs rw,seclabel,nosuid,size=8114556k,nr_inodes=2028639,mode=755 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,seclabel,nosuid,nodev 0 0
devpts /dev/pts devpts rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,seclabel,nosuid,nodev,mode=755 0 0
tmpfs /sys/fs/cgroup tmpfs ro,seclabel,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,seclabel,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,seclabel,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,seclabel,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,seclabel,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,seclabel,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,seclabel,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,seclabel,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,seclabel,nosuid,nodev,noexec,relatime,perf_event 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
/dev/mapper/ol-root / xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=17593 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,seclabel,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,seclabel,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,seclabel,relatime 0 0
/dev/mapper/ol-home /home xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0
/dev/sda1 /boot xfs rw,seclabel,relatime,attr2,inode64,noquota 0 0
sunrpc /var/lib/nfs/rpc_pipefs rpc_pipefs rw,relatime 0 0
tmpfs /run/user/42 tmpfs rw,seclabel,nosuid,nodev,relatime,size=1625804k,mode=700,uid=42,gid=42 0 0
tmpfs /run/user/1000 tmpfs rw,seclabel,nosuid,nodev,relatime,size=1625804k,mode=700,uid=1000,gid=1000 0 0
[ubuntu@oracle81 anylinux]$ 

# Issue description
Source build of LXC 3.2.1 fails on Oracle Linux 8

A brief description of what failed or what could be improved.

I have no problems using the following code to build LXC 3.0.x series and 3.1.x series but 3.2.1 fails using the following build from source procedure.

# Steps to reproduce
                        echo ''
                        echo "=============================================="
                        echo "Untar source code and build LXC RPM...        "
                        echo "=============================================="
                        echo ''

                        sleep 5

                        ping -c 10 linuxcontainers.org
                        echo ''
                        wget --timeout=5 --tries=10 https://linuxcontainers.org/downloads/lxc/lxc-"$LxcVersion".tar.gz
                        sudo mkdir -p /opt/olxc/"$DistDir"/uekulele/lxc/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
                        sudo chown -R $Owner:$Group /opt/olxc/
                        cp -p lxc-"$LxcVersion".tar.gz /opt/olxc/"$DistDir"/uekulele/lxc/rpmbuild/SOURCES/.
                        tar -zxvf lxc-"$LxcVersion".tar.gz
                        cp -p lxc-"$LxcVersion"/lxc.spec /opt/olxc/"$DistDir"/uekulele/lxc/.
                        cd /opt/olxc/"$DistDir"/uekulele/lxc

                        function CheckMacrosFile {
                                cat /etc/rpm/macros | grep _unpackaged_files_terminate_build | sort -u | grep -c 0
                        }
                        MacrosFile=$(CheckMacrosFile)

                        if [ $MacrosFile -eq 0 ]
                        then
                                sudo sh -c "echo '%_unpackaged_files_terminate_build 0' >> /etc/rpm/macros"
                        fi
                        rpmbuild --define "_topdir /opt/olxc/"$DistDir"/uekulele/lxc/rpmbuild" -ba lxc.spec

                        echo ''
                        echo "=============================================="
                        echo "Done: Untar source code and build LXC RPM     "
                        echo "=============================================="

# Information to attach

In file included from lxcseccomp.h:42,
                 from conf.h:41,
                 from confile.c:50:
confile.c: In function 'set_config_net_veth_ipv6_route':
memory_utils.h:35:2: error: 'list' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  free(*(void **)p);
  ^~~~~~~~~~~~~~~~~
confile.c:914:29: note: 'list' was declared here
  __do_free struct lxc_list *list;
                             ^~~~
In file included from lxcseccomp.h:42,
                 from conf.h:41,
                 from confile.c:50:
memory_utils.h:35:2: error: 'inet6dev' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  free(*(void **)p);
  ^~~~~~~~~~~~~~~~~
confile.c:913:33: note: 'inet6dev' was declared here
  __do_free struct lxc_inet6dev *inet6dev;
                                 ^~~~~~~~
In file included from lxcseccomp.h:42,
                 from conf.h:41,
                 from confile.c:50:
memory_utils.h:35:2: error: 'valdup' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  free(*(void **)p);
  ^~~~~~~~~~~~~~~~~
confile.c:912:18: note: 'valdup' was declared here
  __do_free char *valdup;
                  ^~~~~~
cc1: all warnings being treated as errors
make[3]: *** [Makefile:2004: liblxc_la-confile.lo] Error 1
make[3]: Leaving directory '/opt/olxc/home/ubuntu/Downloads/orabuntu-lxc-master/uekulele/lxc/rpmbuild/BUILD/lxc-3.2.1/src/lxc'
make[2]: *** [Makefile:432: all-recursive] Error 1
make[2]: Leaving directory '/opt/olxc/home/ubuntu/Downloads/orabuntu-lxc-master/uekulele/lxc/rpmbuild/BUILD/lxc-3.2.1/src'
make[1]: *** [Makefile:371: all] Error 2
make[1]: Leaving directory '/opt/olxc/home/ubuntu/Downloads/orabuntu-lxc-master/uekulele/lxc/rpmbuild/BUILD/lxc-3.2.1/src'
make: *** [Makefile:526: all-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.FiVfQt (%build)

**Comment by Blub** [comment]
Looks like #3101 and should also be fixed by #3102.

**Comment by brauner** [comment]
What @Blub said should be accurate.
