### ISSUE TITLE
when run poweroff in one container, lxc-attach cannot work for another container

### ISSUE THREAD

**Issue by laogaolao** [lxc/lxc#3167]
Poweroff command affect all the containers, I dont know why, please help, thank you.

# Required information

 * Distribution:
 * Distribution version:
 * The output of
   * `lxc-start --version`
      3.1.0
   * `lxc-checkconfig`
      --- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/cpu
/sys/fs/cgroup/cpuacct
/sys/fs/cgroup/memory
/sys/fs/cgroup/devices
/sys/fs/cgroup/freezer

Cgroup v2 mount points: 

Cgroup v1 systemd controller: missing
Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, not loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
   * `uname -a`
    Linux groove41 4.1.35-rt41 #2 SMP Thu Oct 10 16:46:12 CST 2019 ppc GNU/Linux
   * `cat /proc/self/cgroup`
     6:freezer:/
     5:devices:/
     4:memory:/
     3:cpuacct:/
     2:cpu:/
     1:cpuset:/
   * `cat /proc/1/mounts`
/dev/mmcblk0p1 /mnt/sdcard ext4 rw,noatime,data=ordered 0 0
/dev/loop0 /ro squashfs ro,noatime 0 0
tmpfs /rw tmpfs rw,noatime,size=524288k 0 0
/dev/loop1 /tellabs squashfs ro,noatime 0 0
none / overlay rw,noatime,lowerdir=/mnt/tellabs:/mnt/newroot.ro,upperdir=/mnt/tmpfs/root,workdir=/mnt/tmpfs/.work 0 0
proc /proc proc rw,relatime 0 0
sysfs /sys sysfs rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
devtmpfs /dev devtmpfs rw,relatime,size=1994520k,nr_inodes=166287,mode=755 0 0
devpts /dev/pts devpts rw,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /var/volatile tmpfs rw,relatime 0 0
/dev/loop5 /storage_ne ext4 rw,noatime,data=ordered 0 0
/dev/loop6 /storage_nc ext4 rw,noatime,data=ordered 0 0
cgroup_root /sys/fs/cgroup tmpfs rw,relatime 0 0
cgroup_cpuset /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup_cpu /sys/fs/cgroup/cpu cgroup rw,nosuid,nodev,noexec,relatime,cpu 0 0
cgroup_cpuacct /sys/fs/cgroup/cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct 0 0
cgroup_memory /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup_devices /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup_freezer /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
/dev/loop2 /lxc/nc/app squashfs ro,relatime 0 0
overlay /lxc/nc/root overlay rw,relatime,lowerdir=/lxc/nc/app/:/ro,upperdir=/var/volatile/nc_upper,workdir=/var/volatile/nc_work 0 0
/dev/loop3 /lxc/ne/app squashfs ro,relatime 0 0
overlay /lxc/ne/root overlay rw,relatime,lowerdir=/lxc/ne/app/:/ro,upperdir=/var/volatile/ne_upper,workdir=/var/volatile/ne_work 0 0
# Issue description
There are two containers in our system, one is called NC and anther one is called NE.
When run 'poweroff' command in NC, lxc-attach command does not work for NE, and NC cannot startup either.

A brief description of what failed or what could be improved.

# Steps to reproduce

 1. Step one
      run lxc-start to start NC and NE
 2. Step two
     lxc-attach -n nc
     now run 'poweroff'
     the NC container will be stopped
 3. Step three
     lxc-attach -n ne
     lxc-attach: ne: terminal.c: lxc_terminal_create: 889 Read-only file system - Failed to open terminal
     lxc-attach: ne: attach.c: lxc_attach_terminal: 994 Failed to create terminal
     lxc-attach: ne: attach.c: lxc_attach: 1203 Failed to setup new terminal

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ x] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
log of lxc-attach -n ne:
   lxc-attach ne 20191022034734.825 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:165 - Response data length for command "get_init_pid" is 0
lxc-attach ne 20191022034734.829 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:165 - Response data length for command "get_init_pid" is 0
lxc-attach ne 20191022034734.834 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:165 - Response data length for command "get_config_item" is 0
lxc-attach ne 20191022034734.846 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:165 - Response data length for command "get_config_item" is 0
lxc-attach ne 20191022034734.847 INFO     attach - attach.c:fetch_seccomp:659 - Failed to retrieve lxc.seccomp.profile
lxc-attach ne 20191022034734.849 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:165 - Response data length for command "get_config_item" is 0
lxc-attach ne 20191022034734.850 INFO     attach - attach.c:fetch_seccomp:663 - Failed to retrieve lxc.seccomp
lxc-attach ne 20191022034734.854 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:165 - Response data length for command "get_clone_flags" is 0
lxc-attach ne 20191022034734.856 DEBUG    attach - attach.c:lxc_attach:1180 - Inheriting user namespace from 4238
lxc-attach ne 20191022034734.880 ERROR    terminal - terminal.c:lxc_terminal_create:889 - Read-only file system - Failed to open terminal
lxc-attach ne 20191022034734.881 ERROR    attach - attach.c:lxc_attach_terminal:994 - Failed to create terminal
lxc-attach ne 20191022034734.882 ERROR    attach - attach.c:lxc_attach:1203 - Failed to setup new terminal
 

 - [x ] the containers configuration file
NC container configuration file：
lxc.uts.name = nc
lxc.rootfs.path = /lxc/nc/root
lxc.mount.entry=/mnt/sdcard/images/ images none bind 0 0
lxc.mount.entry=/var/mon var/mon  none  bind 0 0
lxc.environment = SHELF_ID=254
lxc.environment = TIPC_BEARER_IF=eth0.17
lxc.environment = CONTAINER_TYPE=nc
lxc.net.0.type = veth
lxc.net.0.flags = up
lxc.net.0.script.up = /var/lib/lxc/lxcbr-ifup
lxc.net.0.script.down = /var/lib/lxc/lxcbr-ifdown
lxc.net.0.name = eth0.17
lxc.net.0.veth.pair = NcVethBr.17
lxc.net.0.link = lxcbr0
lxc.net.0.ipv4.address = 192.168.0.254/24

lxc.net.1.type = veth
lxc.net.1.flags = up
lxc.net.1.script.up = /var/lib/lxc/lxcbr-ifup
lxc.net.1.script.down = /var/lib/lxc/lxcbr-ifdown
lxc.net.1.name = eth0.16
lxc.net.1.veth.pair = NcVethBr.16
lxc.net.1.link = lxcbr0
lxc.net.1.ipv4.address = 192.168.100.254/24

lxc.net.2.type = veth
lxc.net.2.flags = up
lxc.net.2.script.up = /var/lib/lxc/lxcbr-ifup
lxc.net.2.script.down = /var/lib/lxc/lxcbr-ifdown
lxc.net.2.name = eth0.18
lxc.net.2.veth.pair = NcVethBr.18
lxc.net.2.link = lxcbr0
lxc.net.2.ipv4.address = 192.168.200.254/24

lxc.net.3.type = phys
lxc.net.3.macvlan.mode = bridge
lxc.net.3.flags = up
lxc.net.3.link = mvh40
lxc.net.3.name = eth0.40

lxc.pty.max = 60
lxc.tty.max = 2
lxc.mount.entry = none dev/shm tmpfs nodev,nosuid,noexec,mode=1777,create=dir 0 0
lxc.mount.auto = cgroup:mixed proc:mixed sys:mixed
lxc.autodev = 1
lxc.mount.entry=/storage_nc storage  none  bind 0 0
lxc.mount.entry=/mnt/sdcard/nc_sdcard mnt/sdcard  none  bind 0 0

**Comment by hallyn** [comment]
Can you show the NE config file?

**Comment by brauner** [comment]
Please try to reproduce on current master and re-open if the issue stil exists.
