### ISSUE TITLE
lxc-user-nic fails for uid >= 10000 - with fix proposal

### ISSUE THREAD

**Issue by qippur** [lxc/lxc#3176]
This issue seems to come from commits
bd72001f1aa30732a48d9fe3b58260ee9fe4eb9f 
and/or
aa2fdfd362586bdbedf0a5f7751d9237bf91afa9

Below, issue description and proposed fix.

--

Debian Buster - AMD64 - compiled from source

max length for veth name is IFNAMSIZ (15)
for uid between 0 and 65536 veth name should include user ID

src/lxc/cmd/lxc_user_nic.c - from line 768
    /* for POSIX integer uids the network device name schema is vethUID_XXXXX */
    if (uid > 0 && uid <= 65535)
        ret = snprintf(nicname, sizeof(nicname), "veth%d_XXXXX", uid);

When creating paired NIC name, a "p" is added

src/lxc/cmd/lxc_user_nic.c - from line 553
    ret = snprintf(veth2buf, IFNAMSIZ, "%sp", veth1buf);
    if (ret < 0 || ret >= IFNAMSIZ) {
        usernic_error("%s\n", "Could not create nic name");
        return -1;
    }

this check will fail for uid >= 10000, as total string length is greater than IFNAMSIZ

Proposed fix:
src/lxc/cmd/lxc_user_nic.c - from line 768
    /* for POSIX integer uids the network device name schema is vethUID_XXXXX */
    if (uid > 0 && uid < 10000)
        ret = snprintf(nicname, sizeof(nicname), "veth%d_XXXXX", uid);

**Comment by brauner** [comment]
Can you please create a proper PR for this?

**Comment by qippur** [comment]
Here you are

# Required information

 * Distribution: 
Debian
 * Distribution version: 
buster
 * The output of
   * `lxc-start --version` 
3.2.1-devel
   * `lxc-checkconfig` 
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.20.17+
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/freezer
/sys/fs/cgroup/blkio
/sys/fs/cgroup/memory
/sys/fs/cgroup/devices
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/pids

Cgroup v2 mount points:
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, not loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities:

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/local/bin/lxc-checkconfig

   * `uname -a`
   * `cat /proc/self/cgroup`
   * `cat /proc/1/mounts`

# Issue description

when running an user with uid >= 10000 tries to run an unprivileged container, start fails complaining 

# Steps to reproduce

1. lxc-devel@ava:~ $ id
uid=65008(lxc-devel) gid=65008(lxc-devel) groups=65008(lxc-devel)
2. lxc-devel@ava:~ $ lxc-ls
NAME         STATE   AUTOSTART GROUPS IPV4 IPV6 UNPRIVILEGED
devel        STOPPED 1         -      -    -    true
3. lxc-devel@ava:~ $ lxc-start -n devel -l debug -o /tmp/devuan.log
lxc-start: devel: lxccontainer.c: wait_on_daemonized_start: 874 Received container state "ABORTING" instead of "RUNNING"
lxc-start: devel: tools/lxc_start.c: main: 329 The container failed to start
lxc-start: devel: tools/lxc_start.c: main: 332 To get more details, run the container in foreground mode
lxc-start: devel: tools/lxc_start.c: main: 335 Additional information can be obtained by setting the --logfile and --logpriority options

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
nothing to see here

 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
lxc-devel@ava:~ $ cat /tmp/devuan.log
lxc-start devuan 20191030142218.729 INFO     utils - utils.c:get_rundir:276 - XDG_RUNTIME_DIR isn't set in the environment
lxc-start devuan 20191030142218.729 ERROR    lxc_start - tools/lxc_start.c:main:289 - No container config specified
lxc-start devuan 20191030142228.959 INFO     utils - utils.c:get_rundir:276 - XDG_RUNTIME_DIR isn't set in the environment
lxc-start devuan 20191030142228.959 ERROR    lxc_start - tools/lxc_start.c:main:289 - No container config specified
lxc-start devel 20191030142236.904 INFO     utils - utils.c:get_rundir:276 - XDG_RUNTIME_DIR isn't set in the environment
lxc-start devel 20191030142236.904 INFO     confile - confile.c:set_config_idmaps:2003 - Read uid map: type u nsid 0 hostid 689824 range 65536
lxc-start devel 20191030142236.904 INFO     confile - confile.c:set_config_idmaps:2003 - Read uid map: type g nsid 0 hostid 689824 range 65536
lxc-start devel 20191030142236.905 INFO     lxccontainer - lxccontainer.c:do_lxcapi_start:994 - Set process title to [lxc monitor] /lxc/devel/.local/share/lxc devel
lxc-start devel 20191030142236.905 INFO     lsm - lsm/lsm.c:lsm_init:50 - LSM security driver nop
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:789 - Processing "reject_force_umount  # comment this to allow umount -f;  not recommended"
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:do_resolve_add_rule:535 - Set seccomp rule to reject force umounts
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:975 - Added native rule for arch 0 for reject_force_umount action 0(kill)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:do_resolve_add_rule:535 - Set seccomp rule to reject force umounts
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:984 - Added compat rule for arch 1073741827 for reject_force_umount action 0(kill)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:do_resolve_add_rule:535 - Set seccomp rule to reject force umounts
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:994 - Added compat rule for arch 1073741886 for reject_force_umount action 0(kill)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:do_resolve_add_rule:535 - Set seccomp rule to reject force umounts
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:1004 - Added native rule for arch -1073741762 for reject_force_umount action 0(kill)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:789 - Processing "[all]"
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:789 - Processing "kexec_load errno 1"
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:975 - Added native rule for arch 0 for kexec_load action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:984 - Added compat rule for arch 1073741827 for kexec_load action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:994 - Added compat rule for arch 1073741886 for kexec_load action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:1004 - Added native rule for arch -1073741762 for kexec_load action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:789 - Processing "open_by_handle_at errno 1"
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:975 - Added native rule for arch 0 for open_by_handle_at action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:984 - Added compat rule for arch 1073741827 for open_by_handle_at action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:994 - Added compat rule for arch 1073741886 for open_by_handle_at action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:1004 - Added native rule for arch -1073741762 for open_by_handle_at action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:789 - Processing "init_module errno 1"
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:975 - Added native rule for arch 0 for init_module action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:984 - Added compat rule for arch 1073741827 for init_module action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:994 - Added compat rule for arch 1073741886 for init_module action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:1004 - Added native rule for arch -1073741762 for init_module action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:789 - Processing "finit_module errno 1"
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:975 - Added native rule for arch 0 for finit_module action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:984 - Added compat rule for arch 1073741827 for finit_module action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:994 - Added compat rule for arch 1073741886 for finit_module action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:1004 - Added native rule for arch -1073741762 for finit_module action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:789 - Processing "delete_module errno 1"
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:975 - Added native rule for arch 0 for delete_module action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:984 - Added compat rule for arch 1073741827 for delete_module action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:994 - Added compat rule for arch 1073741886 for delete_module action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:1004 - Added native rule for arch -1073741762 for delete_module action 327681(errno)
lxc-start devel 20191030142236.905 INFO     seccomp - seccomp.c:parse_config_v2:1008 - Merging compat seccomp contexts into main context
lxc-start devel 20191030142236.905 INFO     utils - utils.c:get_rundir:276 - XDG_RUNTIME_DIR isn't set in the environment
lxc-start devel 20191030142236.906 DEBUG    terminal - terminal.c:lxc_terminal_peer_default:677 - No such device - The process does not have a controlling terminal
lxc-start devel 20191030142236.906 DEBUG    conf - conf.c:chown_mapped_root:3179 - trying to chown "/dev/pts/9" to 65008
lxc-start devel 20191030142236.957 INFO     start - start.c:lxc_init:942 - Container "devel" is initialized
lxc-start devel 20191030142236.958 INFO     cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1407 - The monitor process uses "lxc.monitor/devel" as cgroup
lxc-start devel 20191030142236.959 INFO     cgfsng - cgroups/cgfsng.c:cgfsng_payload_create:1472 - The container process uses "lxc.payload/devel" as cgroup
lxc-start devel 20191030142236.960 INFO     start - start.c:proc_pidfd_open:1665 - Sending signals through pidfds not supported on this kernel
lxc-start devel 20191030142236.960 INFO     start - start.c:lxc_spawn:1799 - Cloned CLONE_NEWUSER
lxc-start devel 20191030142236.960 INFO     start - start.c:lxc_spawn:1799 - Cloned CLONE_NEWNS
lxc-start devel 20191030142236.960 INFO     start - start.c:lxc_spawn:1799 - Cloned CLONE_NEWPID
lxc-start devel 20191030142236.960 INFO     start - start.c:lxc_spawn:1799 - Cloned CLONE_NEWUTS
lxc-start devel 20191030142236.960 INFO     start - start.c:lxc_spawn:1799 - Cloned CLONE_NEWIPC
lxc-start devel 20191030142236.960 DEBUG    start - start.c:lxc_try_preserve_namespaces:193 - Preserved user namespace via fd 15
lxc-start devel 20191030142236.960 DEBUG    start - start.c:lxc_try_preserve_namespaces:193 - Preserved mnt namespace via fd 16
lxc-start devel 20191030142236.960 DEBUG    start - start.c:lxc_try_preserve_namespaces:193 - Preserved pid namespace via fd 17
lxc-start devel 20191030142236.960 DEBUG    start - start.c:lxc_try_preserve_namespaces:193 - Preserved uts namespace via fd 18
lxc-start devel 20191030142236.960 DEBUG    start - start.c:lxc_try_preserve_namespaces:193 - Preserved ipc namespace via fd 19
lxc-start devel 20191030142236.960 DEBUG    conf - conf.c:idmaptool_on_path_and_privileged:2855 - The binary "/usr/bin/newuidmap" does have the setuid bit set
lxc-start devel 20191030142236.960 DEBUG    conf - conf.c:idmaptool_on_path_and_privileged:2855 - The binary "/usr/bin/newgidmap" does have the setuid bit set
lxc-start devel 20191030142236.960 DEBUG    conf - conf.c:lxc_map_ids:2941 - Functional newuidmap and newgidmap binary found
lxc-start devel 20191030142236.970 INFO     start - start.c:do_start:1203 - Unshared CLONE_NEWNET
lxc-start devel 20191030142236.970 DEBUG    conf - conf.c:idmaptool_on_path_and_privileged:2855 - The binary "/usr/bin/newuidmap" does have the setuid bit set
lxc-start devel 20191030142236.970 DEBUG    conf - conf.c:idmaptool_on_path_and_privileged:2855 - The binary "/usr/bin/newgidmap" does have the setuid bit set
lxc-start devel 20191030142236.970 DEBUG    conf - conf.c:lxc_map_ids:2941 - Functional newuidmap and newgidmap binary found
lxc-start devel 20191030142236.980 DEBUG    start - start.c:lxc_spawn:1860 - Preserved net namespace via fd 7
lxc-start devel 20191030142236.980 WARN     start - start.c:lxc_spawn:1865 - Operation not permitted - Failed to allocate new network namespace id
lxc-start devel 20191030142236.980 INFO     network - network.c:lxc_create_network_unpriv_exec:2758 - Execing lxc-user-nic create /lxc/devel/.local/share/lxc devel 9173 veth br0 (null)
lxc-start devel 20191030142236.986 ERROR    network - network.c:lxc_create_network_unpriv_exec:2786 - lxc-user-nic failed to configure requested network: cmd/lxc_user_nic.c: 1300: main: Quota reached
lxc-start devel 20191030142236.986 ERROR    start - start.c:lxc_spawn:1873 - Failed to create the network
lxc-start devel 20191030142236.986 DEBUG    network - network.c:lxc_delete_network:4030 - Deleted network devices
lxc-start devel 20191030142236.986 INFO     utils - utils.c:get_rundir:276 - XDG_RUNTIME_DIR isn't set in the environment
lxc-start devel 20191030142236.986 DEBUG    lxccontainer - lxccontainer.c:wait_on_daemonized_start:862 - First child 9164 exited
lxc-start devel 20191030142236.986 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:874 - Received container state "ABORTING" instead of "RUNNING"
lxc-start devel 20191030142236.986 ERROR    lxc_start - tools/lxc_start.c:main:329 - The container failed to start
lxc-start devel 20191030142236.986 ERROR    lxc_start - tools/lxc_start.c:main:332 - To get more details, run the container in foreground mode
lxc-start devel 20191030142236.986 ERROR    lxc_start - tools/lxc_start.c:main:335 - Additional information can be obtained by setting the --logfile and --logpriority options
lxc-start devel 20191030142236.986 ERROR    start - start.c:__lxc_start:2063 - Failed to spawn container "devel"
lxc-start devel 20191030142236.986 INFO     utils - utils.c:get_rundir:276 - XDG_RUNTIME_DIR isn't set in the environment
lxc-start devel 20191030142236.987 DEBUG    conf - conf.c:idmaptool_on_path_and_privileged:2855 - The binary "/usr/bin/newuidmap" does have the setuid bit set
lxc-start devel 20191030142236.987 DEBUG    conf - conf.c:idmaptool_on_path_and_privileged:2855 - The binary "/usr/bin/newgidmap" does have the setuid bit set
lxc-start devel 20191030142236.987 DEBUG    conf - conf.c:lxc_map_ids:2941 - Functional newuidmap and newgidmap binary found
lxc-start devel 20191030142237.950 INFO     utils - utils.c:get_rundir:276 - XDG_RUNTIME_DIR isn't set in the environment

 - [ ] the containers configuration file
# Template used to create this container: /usr/local/share/lxc/templates/lxc-download
# Parameters passed to the template:
# Template script checksum (SHA-1): 161cea1217a1fb9b5c968b27bb92a0965de39eb3
# For additional config options, please look at lxc.container.conf(5)

# Uncomment the following line to support nesting containers:
#lxc.include = /usr/local/share/lxc/config/nesting.conf
# (Be aware this has security implications)


# Distribution configuration
lxc.include = /usr/local/share/lxc/config/common.conf
lxc.include = /usr/local/share/lxc/config/userns.conf
lxc.arch = linux64

# Container specific configuration
lxc.idmap = u 0 689824 65536
lxc.idmap = g 0 689824 65536
lxc.rootfs.path = dir:/lxc/devel/.local/share/lxc/devel/rootfs
lxc.uts.name = devel

# Network configuration
lxc.net.0.type = veth
lxc.net.0.link = br0
lxc.net.0.flags = up
lxc.net.0.hwaddr = 00:16:3e:c6:ba:b5

lxc.apparmor.profile = generated
lxc.apparmor.allow_nesting = 1

lxc.start.auto = 1

**Comment by qippur** [comment]
I am a newbie. I had to find out the issue and my fix as I have many containers at home and I have to make sure that LXC works. It took a lot of effort as I am not a programmer.
Please forgive any wrong approach. My only goal is to help.
If I may suggest, the message "quota reached" should be returned only if NIC number really exceeds quota.
Looking at the code it is returned when anything in nic pair creation goes wrong.

**Comment by SPKorhonen** [comment]
I'm wondering whether the uid should be formatted as hex? That way uids between 0 and 65536 would fit nicely into 4 characters.

Namely should the line "ret = snprintf(nicname, sizeof(nicname), "veth%d_XXXXX", uid);" actually be "ret = snprintf(nicname, sizeof(nicname), "veth%X_XXXXX", uid);"

I would be willing to submit a pull request for this if acceptable.

**Comment by qippur** [comment]
I think it would fit, but the goal of this code snippet is to associate uid and veth for an user.
Making it HEX would make it still possible, but more difficult.

**Comment by narcisgarcia** [comment]
```
$ lsb_release -ds
Debian GNU/Linux 10 (buster)
$ uname -sv
Linux #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11)
$ lxc-start --version
3.0.3
$ cat test14/config | grep -e lxc.idmap
lxc.idmap = u 0 362144 65536
lxc.idmap = g 0 362144 65536
$ cat test15/config | grep -e lxc.idmap
lxc.idmap = u 0 493216 65536
lxc.idmap = g 0 493216 65536
```

"test14" container boots. "test15" not and logs this first line:

> network - network.c:lxc_create_network_unpriv_exec:2178 - lxc-user-nic failed to configure requested network: cmd/lxc_user_nic.c: 1296: main: Quota reached

Is there some workaround for Debian stable (buster) with only repository software?

**Comment by narcisgarcia** [comment]
I see now that my problem is I've really reached NICs quota, because I can start "test15" container if I previously stop "test14"
```
$ ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master lanbr0 state UP group default qlen 1000
    link/ether 00:16:3e:f1:52:ed brd ff:ff:ff:ff:ff:ff
3: lanbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:f1:52:ed brd ff:ff:ff:ff:ff:ff
    inet 172.16.24.100/16 brd 172.16.255.255 scope global lanbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fef1:52ed/64 scope link 
       valid_lft forever preferred_lft forever
5: veth3QDKN1@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master lanbr0 state UP group default qlen 1000
    link/ether fe:ae:77:68:91:50 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::fcae:77ff:fe68:9150/64 scope link 
       valid_lft forever preferred_lft forever
7: veth23XA7I@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master lanbr0 state UP group default qlen 1000
    link/ether fe:50:1e:dd:da:b8 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::fc50:1eff:fedd:dab8/64 scope link 
       valid_lft forever preferred_lft forever
9: vethR9RGBQ@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master lanbr0 state UP group default qlen 1000
    link/ether fe:85:2a:58:3d:14 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::fc85:2aff:fe58:3d14/64 scope link 
       valid_lft forever preferred_lft forever
11: vethFCPI4W@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master lanbr0 state UP group default qlen 1000
    link/ether fe:d5:b0:a3:ad:6a brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::fcd5:b0ff:fea3:ad6a/64 scope link 
       valid_lft forever preferred_lft forever
13: vethELOIDU@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master lanbr0 state UP group default qlen 1000
    link/ether fe:73:1b:0a:91:61 brd ff:ff:ff:ff:ff:ff link-netnsid 4
    inet6 fe80::fc73:1bff:fe0a:9161/64 scope link 
       valid_lft forever preferred_lft forever
15: vethSFN6V6@if14: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master lanbr0 state UP group default qlen 1000
    link/ether fe:78:cd:0f:bc:59 brd ff:ff:ff:ff:ff:ff link-netnsid 5
    inet6 fe80::fc78:cdff:fe0f:bc59/64 scope link 
       valid_lft forever preferred_lft forever
41: vethX387EY@if40: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master lanbr0 state UP group default qlen 1000
    link/ether fe:a4:c2:a4:7b:78 brd ff:ff:ff:ff:ff:ff link-netnsid 6
    inet6 fe80::fca4:c2ff:fea4:7b78/64 scope link 
       valid_lft forever preferred_lft forever
43: vethKEBULH@if42: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master lanbr0 state UP group default qlen 1000
    link/ether fe:cc:23:94:9c:8a brd ff:ff:ff:ff:ff:ff link-netnsid 7
    inet6 fe80::fccc:23ff:fe94:9c8a/64 scope link 
       valid_lft forever preferred_lft forever
77: vethETW99T@if76: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master lanbr0 state UP group default qlen 1000
    link/ether fe:64:68:c0:4f:73 brd ff:ff:ff:ff:ff:ff link-netnsid 8
    inet6 fe80::fc64:68ff:fec0:4f73/64 scope link 
       valid_lft forever preferred_lft forever
83: veth2UB5GB@if82: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master lanbr0 state UP group default qlen 1000
    link/ether fe:41:bb:db:76:7e brd ff:ff:ff:ff:ff:ff link-netnsid 9
    inet6 fe80::fc41:bbff:fedb:767e/64 scope link 
       valid_lft forever preferred_lft forever
```
Where is this LXC user NIC quota managed, to enlarge it?

**Comment by hallyn** [comment]
> Where is this LXC user NIC quota managed, to enlarge it?

/etc/lxc/lxc-usernet

**Comment by stgraber** [comment]
@brauner probably ought to look into this for 4.0

**Comment by brauner** [comment]
The simplest solution I can think of is to remove one extra `X` from the randomly generated part of the veth name. Currently with `lxc_mkifname()` we have `36^5` unique network device names for veth devices generated with a `uid` as part of the name (at least for uids with less than five digits). First, let's remove one `X` that'll bring us down to `36^4` (That's still `1679616` veth devices per uid.). But while we're add it let's also extend `lxc_mkifname()` to use `62` chars, i.e. make it case-sensitive. Then we get `62^4` unique network device names. That's plenty for now.
