### ISSUE TITLE
Replacement for fuidshift (missing in LXD snap)?

### ISSUE THREAD

**Issue by hhtznr** [lxc/lxc#3186]
Ubuntu used to ship fuidshift in the lxd-tools package until 18.04. Since Ubuntu 18.10, lxd-tools is a meta package that points to LXD snap. This snap however does not ship with fuidshift. Unluckily, the old lxd-tools package can also no longer be forcibly installed in Ubuntu 19.10 due to broken dependencies.

fuidshift was a really useful tool for shifting UIDs/GIDs of privileged and unprivileged containers. At the moment, I cannot find a good way or good information on how else to do this without accidentally breaking something in the container file system.

Has fuidshift been replaced by another tool or is there another way to easily do what fuidshift did?

**Comment by stgraber** [comment]
It still exists but as it wasn't needed by LXD itself, it didn't make sense to try to package it with the snap.

You can still easily build it with:
- snap install go --classic
- go get github.com/lxc/lxd/fuidshift

**Comment by hhtznr** [comment]
Thank you very much for the quick reply. This got me back fuidshift and it's working like a charm!

As a hint to anyone else, who might wants to reproduce this: On the Ubuntu host where I executed the above commands, I had to install the packages git, libcap-dev and libacl1-dev to enable retrieval and compilation of fuidshift by go.
