### ISSUE TITLE
libpam-cgfs cannot help non-root users to use CGroup in LXC when Linux is booted with systemd.unified_cgroup_hierarchy

### ISSUE THREAD

**Issue by emojifreak** [lxc/lxc#3198]
* Distribution: Ubuntu
 * Distribution version: Eoan 19.10

I observed this issue with 
libpam-cgls	3.0.4-0ubuntu1
and
libpam-cgls `3.2.1+master~20191202-0205-0ubuntu1~eoan` 

I am pretty sure that libpam-cgls is enabled by `pam-auth-update`

# Issue description

When Linux is booted with systemd.unified_cgroup_hierarchy,
/sys/fs/cgroup/user.slice/user-$UID.slice/session-nnn.scope is not chowned to a login user.

# Steps to reproduce

1. Boot Linux with systemd.unified_cgroup_hierarchy
2. Login from a console (or a display manager, see below)
3. ls -l /sys/fs/cgroup/user.slice/user-YOURUID.slice and see the owner

By the way, the opening comments of pam_cgfs.c seem to assume that the name of cgroup is session-nnn.scope. But Light DM makes session-c10.scope (10 can be different).

If this issue is confirmed, please consider to include a fix to the next release of 3.0 LTS.

It seems that libpam_cgls is required to correctly use `lxc.cgroup.relative=1`.
Another way to get required delegation might be to use
`systemd-run --user  -p "Delegate=pids memory cpu io" lxc-start ...`
and lxc is put into a cgroup correctly chowned. With such execution cgroup tree looks like:

```
├─user.slice
│ └─user-0.slice
│   └─user@0.service
│     ├─run-r2f86bd3279fe4aeb88c99b64fe63a2c5.service
│     │ ├─lxc.payload
│     │ │ └─eoan
│     │ │   ├─init.scope
│     │ │   │ └─8084 /sbin/init
│     │ │   └─system.slice
│     │ │     ├─systemd-networkd.service
│     │ │     │ └─8138 /lib/systemd/systemd-networkd
│     │ │     ├─cron.service
│     │ │     │ └─8172 /usr/sbin/cron -f
│     │ │     ├─networkd-dispatcher.service
│     │ │     │ └─8167 /usr/bin/python3 /usr/bin/networkd-dispatcher --run-st...
│     │ │     ├─systemd-journald.service
│     │ │     │ └─8115 /lib/systemd/systemd-journald
│     │ │     ├─rsyslog.service
│     │ │     │ └─8168 /usr/sbin/rsyslogd -n -iNONE
│     │ │     ├─console-getty.service
│     │ │     │ └─8204 /sbin/agetty -o -p -- \u --noclear --keep-baud console...
│     │ │     ├─systemd-resolved.service
│     │ │     │ └─8166 /lib/systemd/systemd-resolved
│     │ │     ├─system-container\x2dgetty.slice
│     │ │     │ ├─container-getty@0.service
│     │ │     │ │ └─8200 /sbin/agetty -o -p -- \u --noclear --keep-baud pts/0...
│     │ │     │ ├─container-getty@2.service
│     │ │     │ │ └─8202 /sbin/agetty -o -p -- \u --noclear --keep-baud pts/2...
│     │ │     │ ├─container-getty@1.service
│     │ │     │ │ └─8205 /sbin/agetty -o -p -- \u --noclear --keep-baud pts/1...
│     │ │     │ └─container-getty@3.service
│     │ │     │   └─8201 /sbin/agetty -o -p -- \u --noclear --keep-baud pts/3...
│     │ │     ├─dbus.service
│     │ │     │ └─8171 /usr/bin/dbus-daemon --system --address=systemd: --nof...
│     │ │     └─systemd-logind.service
│     │ │       └─8169 /lib/systemd/systemd-logind
│     │ └─lxc.monitor
│     │   └─eoan
│     │     └─8083 [lxc monitor] /var/lib/lxc eoan
```

**Comment by emojifreak** [comment]
https://github.com/lxc/lxc/blob/master/doc/pam_cgfs.sgml.in says: LXC has supported fully unprivileged containers since LXC 1.0. Fully unprivileged containers are the safest containers and are run by normal (non-root) users.

According to https://github.com/lxc/lxc/issues/3201#issuecomment-561397547 libpam_cgfs needs to prepare `cgroup.subtree_control`, or documentation needs to explain what functions are unavailable in fully unprivileged containers. When this issue is closed, please make sure that one of these two conditions is met.

**Comment by emojifreak** [comment]
Now it seems that the most systemd-friendly way of starting a fully unprivileged container is that

1. Copy https://github.com/lxc/lxc/blob/master/config/init/systemd/lxc%40.service.in to `/lib/systemd/user`
2. Just do `systemctl --user start lxc@containername`

After https://github.com/lxc/lxc/issues/3206 and https://github.com/lxc/lxc/issues/3211 are fixed,  a non-root user should be able to start a fully unprivileged container with full functionality. `systemctl --user` now does what had been done by `libpam-cgfs` when host Linux is booted with `systemd.unified_cgroup_hierarchy`.

**Comment by brauner** [comment]
This will not work as you think it does. We can't chown these files anymore behind systemd's back and it's not going to work in general for fully unprivileged containers; not without using `systemd --user`.

The cgroup2 hierarchy has an internal process constraint. In short, there can only be processes in a cgroup _with controllers enabled_ if it's a leaf node.
When you log into your system systemd on cgroup2-only hosts will place you in a `session.scope` for your user, i.e. you are now on a leaf node and can't have subcgroup with controllers enabled and live processes in it. The kernel will prevent that.
All your processes including privileged processes your session needs will live in this sesscion scope. This means before you could start any container with actual controllers enabled you would need to move your whole session, i.e. all the processes assigned to it into a separate cgroup in you session scope and then create the cgroups for the container in the now empty session scope.
That's not just out of scope for LXC itself we also can't just move your user or your session around the hierarchy. That's a no-go security wise and also won't work since your user will not be privileged enough to move processes that it doesn't have privilege over.

We can certainly accept patches to pam_cgfs.c which would chown the files to you but it won't help I fear. That's the cgroup2 design. Feel free to experiment with this and come up with patches though.

**Comment by emojifreak** [comment]
@brauner Thank you for your response, but I agree to none of your view. The below is a proper way to use CGroup controllers by a non-root user. LXC fully unprivileged container started by a non-root user can do the same thing:

```
ryutaroh@newlaptop:~$ export CGROUPDIR=/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope
ryutaroh@newlaptop:~$ systemd-run --unit=myshell --user --scope -p "Delegate=pids memory" /bin/bash
Running scope as unit: myshell.scope
ryutaroh@newlaptop:~$ cd $CGROUPDIR
ryutaroh@newlaptop:/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope$ cat cgroup.controllers
memory pids
ryutaroh@newlaptop:/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope$ cat cgroup.subtree_control
ryutaroh@newlaptop:/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope$ mkdir test.scope
ryutaroh@newlaptop:/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope$ echo $$ >test.scope/cgroup.procs
ryutaroh@newlaptop:/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope$ cat test.scope/cgroup.controllers
ryutaroh@newlaptop:/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope$ echo "+pids +memory" >cgroup.subtree_control
ryutaroh@newlaptop:/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope$ cat test.scope/cgroup.controllers
memory pids
```

When lxc-start is started by `systemctl --user` with `Delegate=pids memory io cpu`, a fully unprivileged container can use V2 pids memory io cpu controllers.

**Comment by emojifreak** [comment]
We can probably agree that host Linux booted with systemd.unified_cgroup_hierarchy does not need libpam_cgfs at all.

**Comment by brauner** [comment]
> @brauner Thank you for your response, but I agree to none of your view. The below is a proper way to use CGroup controllers by a non-root user. LXC fully unprivileged container started by a non-root user can do the same thing:
> 
> ```
> ryutaroh@newlaptop:~$ export CGROUPDIR=/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope
> ryutaroh@newlaptop:~$ systemd-run --unit=myshell --user --scope -p "Delegate=pids memory" /bin/bash
> Running scope as unit: myshell.scope
> ryutaroh@newlaptop:~$ cd $CGROUPDIR
> ryutaroh@newlaptop:/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope$ cat cgroup.controllers
> memory pids
> ryutaroh@newlaptop:/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope$ cat cgroup.subtree_control
> ryutaroh@newlaptop:/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope$ mkdir test.scope
> ryutaroh@newlaptop:/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope$ echo $$ >test.scope/cgroup.procs
> ryutaroh@newlaptop:/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope$ cat test.scope/cgroup.controllers
> ryutaroh@newlaptop:/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope$ echo "+pids +memory" >cgroup.subtree_control
> ryutaroh@newlaptop:/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope$ cat test.scope/cgroup.controllers
> memory pids
> ryutaroh@newlaptop:/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/myshell.scope$ cat /proc/$$/cgroup
> 0::/user.slice/user-1000.slice/user@1000.service/myshell.scope/test.scope
> ```
> 
> When lxc-start is started by `systemctl --user` with `Delegate=pids memory io cpu`, a fully unprivileged container can use V2 pids memory io cpu controllers.

I think you misunderstood my response. I explicitly said that `systemctl --user` works. But pam_cgfs will be called when you create your login session, i.e. way before systemctl --user and there will usually be multiple processes in that session and this is the problem. None of this relates to separate scopes creates for a _single_ process through the systemd api.

**Comment by brauner** [comment]
You also do exactly what I described would work so I don't know what your disagreeing with.

**Comment by emojifreak** [comment]
Thanks again for response. My assumption/recognition is that you believe that a fully unprivileged LXC container cannot use CGroup V2 controller nor `lxc.cgroup2.something` config items when lxc-start is started by `systemctl --user`. The reason behind this guess is  because you closed https://github.com/lxc/lxc/issues/3201 and you keep https://github.com/lxc/lxc/issues/3201 closed.  My intention was to show a sequence of commands that can probably be used by LXC started by non-root user to give CGroup V2 controllers to a container. My recognition is

1. LXC fully unprivileged container started by a non-root user can use V2 controllers and lxc.cgroup2.something on a Linux host booted with systemd.unified_cgroup_hierarchy when lxc-start is started by either `systemctl --user` or `systemd-run --user` with proper `Delegate` property, by a sequence of manipulations similar to one shown in https://github.com/lxc/lxc/issues/3198#issuecomment-562090652 , possibly with `chmod a+rw $CGROUPDIR/test.scope/cgroup.subtree_control` before doing `lxc-usernsexec`-equivalent.
2. If libpam-cgls chowns directoly `/sys/fs/user.slice/user-$UID.slice/session-nnn.scope` to a login user, then `lxc-start` can do an equivalent manipulation to a sequence of commands given in https://github.com/lxc/lxc/issues/3198#issuecomment-562090652 , and LXC fully unprivileged container started by a non-root user can use V2 controllers and lxc.cgroup2.something on a Linux host booted with systemd.unified_cgroup_hierarchy
3. So I cannot understand what is a reason behind keeping https://github.com/lxc/lxc/issues/3201 closed. https://github.com/lxc/lxc/issues/3201 seems a software bug that can be fixed on a Linux host booted with systemd.unified_cgroup_hierarchy.
4. An equivalent effect is achieved by `systemctl --user` or `systemd-run --user`, so `libpam-cgfs` is unnecessary on a Linux host booted with systemd.unified_cgroup_hierarchy, and we can stop using `libpam-cgfs` on a Linux host booted with systemd.unified_cgroup_hierarchy, after telling users to use `systemctl --user` or `systemd-run --user` in place of libpam-cgfs.
5. `/sys/fs/user.slice/user-$UID.slice/session-nnn.scope` is not delegated to a login user, so chowning `session-nnn.scope` and letting `lxc-start` to make directories under `session-nnn.scope` is a violation to a guideline https://systemd.io/CGROUP_DELEGATION.html told by systemd developers.

Anyway, I have absolutely no objection to any design decision nor any direction of future LXC develeopment  decided by you and your collaborators. So I am fine if you choose to let LXC be unable to use V2 contorollers and lxc.cgroup2.something in a fully unprivileged container started by a non-root user on a Linux host booted with systemd.unified_cgroup_hierarchy. Please do whatever you like. It is just and completely fine with me. I am also happy to share my view further if it is helpful. I also believe that an OSS developer/maintainer has absolutely no obligation to respond to an issue/a bug report given by a user. I am just reporting something that I believe a software bug.

**Comment by brauner** [comment]
Please try
```
ryutaroh@newlaptop:~$ systemd-run --unit=myshell --user --scope -p "Delegate=pids memory" lxc-start <container_name>
```
with current master.

**Comment by emojifreak** [comment]
@brauner Thank you very much for your kind help. LXC daily PPA https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/daily (I tested `3.2.1+master~20191206-1422-0ubuntu1~eoan`) probably has not yet incorporated your updates, and please allow me to wait the next update to LXC daily PPA.

**Comment by emojifreak** [comment]
@brauner Let me say thank you again. I will talk about `3.2.1+master~20191206-2142-0ubuntu1~eoan` from https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/daily

* I confirmed that `lxc.cgroup2.memory.high` and `lxc.cgroup2.pids.max` worked as documented.
* All CGroup V2 controllers were still unusable in an unprivileged container started by a non-root user. The symptom was exactly the same as https://github.com/lxc/lxc/issues/3206#issuecomment-562806281 so please have a look at it.

The below are less related comments, which I hope somewhat helpful:

At https://github.com/lxc/lxc/blob/0374aacd73e33e15f8673aafac337a32eef62f58/doc/pam_cgfs.sgml.in#L80-L82
the text seems incompatible with your view, and the documentation seems to need revision.

At https://systemd.io/CGROUP_DELEGATION.html#delegation it is said that

> If your service makes use of the User= functionality, then the sub-tree will be chown()ed to the indicated user so that it can correctly create cgroups below it. Note however that systemd will do that only in the unified hierarchy (in unified and hybrid mode) as well as on systemd’s own private hierarchy (in legacy and hybrid mode). It won’t pass ownership of the legacy controller hierarchies. Delegation to less privileges processes is not safe in cgroup v1 (as a limitation of the kernel), hence systemd won’t facilitate access to it.

It seems unclear whether `systemctl/systemd-run --user -p "Delagate=..."` can play the same role as `libpam-cgfs` in the hybrid and the legacy cgroup hierarchy. So `libpam-cgfs` seems to keep its importance.

**Comment by emojifreak** [comment]
Although
https://github.com/lxc/lxc/blob/0374aacd73e33e15f8673aafac337a32eef62f58/doc/lxc-usernsexec.sgml.in#L126-L128
chown and chmod to `/sys/fs/cgroup/cgroup.subtree_control` just give 

```shell-session
root@unpriv:/# chown 0.0 /sys/fs/cgroup/cgroup.subtree_control
chown: changing ownership of '/sys/fs/cgroup/cgroup.subtree_control': Operation not permitted
root@unpriv:/# chmod a=rw /sys/fs/cgroup/cgroup.subtree_control
chmod: changing permissions of '/sys/fs/cgroup/cgroup.subtree_control': Operation not permitted
```

**Comment by brauner** [comment]
Closing this as `libpam_cgfs` can't be reasonably used on pure unified systems.
