### ISSUE TITLE
give to lxc privileges to run CRIU

### ISSUE THREAD

**Issue by farso92** [lxc/lxc#3200]
i m running last lxc version on ubuntu 19.10. I m trying to run CRIU but after the installation when i run "criu check --all" i got this error:
`Error (criu/util.c:610): exited, status=1
Error (criu/util.c:610): exited, status=1
Error (criu/tun.c:85): tun: Unable to create tun: No such file or directory
Error (criu/cr-check.c:798): couldn't suspend seccomp: Operation not permitted
Error (criu/cr-check.c:840): Dumping seccomp filters not supported: Permission denied
Error (criu/tun.c:66): tun: Can't check tun support: No such file or directory
Error (criu/cr-check.c:1033): failed to mount autofs: Permission denied
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
`
it is a priviliges problem...what can i do?

**Comment by brauner** [comment]
This is really a criu problem not a lxc problem. Sorry.
