### ISSUE TITLE
"busy" field of "struct lxc_terminal_info" should be initialized to -1

### ISSUE THREAD

**Issue by Rachid-Koucha** [lxc/lxc#3209]
As the "busy" field of the "struct lxc_terminal_info" is set to a socket descriptor when the embedding structure is marked "in use", it should be initialized to -1 instead of 0 as 0 is also a valid file descriptor.

So, I would propose to modify:

. conf.c/lxc_allocate_ttys()
       tty->busy = -1;

. terminal.c/lxc_terminal_allocate()

	if (*ttyreq > 0) {
		if (*ttyreq > ttys->max)
			goto out;

		if (ttys->tty[*ttyreq - 1].busy >= 0)
			goto out;

		/* The requested tty is available. */
		ttynum = *ttyreq;
		goto out_tty;
	}

	/* Search for next available tty, fixup index tty1 => [0]. */
	for (ttynum = 1; ttynum <= ttys->max && ttys->tty[ttynum - 1].busy >= 0; ttynum++) {
		;
	}

. terminal.c/lxc_terminal_free()

	for (i = 0; i < ttys->max; i++)
		if (ttys->tty[i].busy == fd)
			ttys->tty[i].busy = -1;

**Comment by brauner** [comment]
Can you send a patch that we can discuss, please?

**Comment by Rachid-Koucha** [comment]
Created pull request #3210

**Comment by brauner** [comment]
This is fixed in master.
