### ISSUE TITLE
Move container to new pool

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [lxc/lxc#3212]
This is probably the wrong place to ask, but how do you move a container to a different pool?

Right now I'm setting up a new server and would like to get all my containers running before I pull the plug on my old server and move its zpool over, but to do that I need to be able to move the containers to the zpool once it's transferred.

It seems like this [was an option](https://discuss.linuxcontainers.org/t/move-container-from-one-pool-to-another/1296/8) at one point, how do you go about this now?

Is the right way to recreate the container on the other pool then copy the filesystem overtop of the "new" container?

**Comment by stgraber** [comment]
`lxc move container-name container-name-moved --storage new-storage` followed by `lxc move container-name-moved container-name`.

If running on a LXD release that doesn't support this, then you can publish and re-create the container from an image or move it to another system and then back to the storage pool you want it on.

**Comment by Adrian-at-CrimsonAuzre** [comment]
Thanks, default install on Ubuntu Server is 3.03 so I had to update to the snap package.

BTW for future people that get stuck trying to switch to the snap package, [here's](https://askubuntu.com/questions/397185/upgrading-lxc-version) how to completely purge all the LXD related packages installed via apt.
