### ISSUE TITLE
Grant lxc-create the ability to create it's own default config file on first-run

### ISSUE THREAD

**Issue by toddhpoole** [lxc/lxc#3219]
# Required information

 * Distribution: Fedora
 * Distribution version: 31
 * The output of
   * `lxc-start --version`
```
[regularuser@testserver ~]$ lxc-start --version
3.0.4
```
   * `lxc-checkconfig`
```
[regularuser@testserver ~]$ lxc-checkconfig
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-5.3.14-300.fc31.x86_64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Warning: newuidmap is not setuid-root
Warning: newgidmap is not setuid-root
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 


Cgroup v2 mount points: 
/sys/fs/cgroup

Cgroup v1 systemd controller: missing
Cgroup v1 freezer controller: missing
Cgroup namespace: required
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```
   * `uname -a`
```
[regularuser@testserver ~]$ uname -a
Linux testserver 5.3.14-300.fc31.x86_64 #1 SMP Mon Dec 2 15:41:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
   * `cat /proc/self/cgroup`
```
[regularuser@testserver ~]$ cat /proc/self/cgroup
0::/user.slice/user-1000.slice/session-7.scope
```
   * `cat /proc/1/mounts`
```
[regularuser@testserver ~]$ cat /proc/1/mounts
sysfs /sys sysfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
devtmpfs /dev devtmpfs rw,seclabel,nosuid,size=16337860k,nr_inodes=4084465,mode=755 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,seclabel,nosuid,nodev 0 0
devpts /dev/pts devpts rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,seclabel,nosuid,nodev,mode=755 0 0
cgroup2 /sys/fs/cgroup cgroup2 rw,seclabel,nosuid,nodev,noexec,relatime,nsdelegate 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
/dev/mapper/fedora_host-root / xfs rw,seclabel,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=25757 0 0
debugfs /sys/kernel/debug debugfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
mqueue /dev/mqueue mqueue rw,seclabel,nosuid,nodev,noexec,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,seclabel,relatime,pagesize=2M 0 0
tmpfs /tmp tmpfs rw,seclabel,nosuid,nodev 0 0
/dev/sda2 /boot xfs rw,seclabel,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota 0 0
/dev/sda1 /boot/efi vfat rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=winnt,errors=remount-ro 0 0
tmpfs /run/user/0 tmpfs rw,seclabel,nosuid,nodev,relatime,size=3270444k,mode=700 0 0
sunrpc /var/lib/nfs/rpc_pipefs rpc_pipefs rw,relatime 0 0
tmpfs /run/user/1000 tmpfs rw,seclabel,nosuid,nodev,relatime,size=3270444k,mode=700,uid=1000,gid=1000 0 0
```

# Issue description

The first time an unprivileged user tries to create an unprivileged container, `lxc-create` will fail with an error message helpfully instructing the user to define UID mappings in `~/.config/lxc/defalt.conf`:
```
[regularuser@testserver ~]$ lxc-create -t download -n testfedora31_1 -- -d fedora -r 31 -a amd64
[... snip snip ...]
lxc-create: testfedora31_1: conf.c: suggest_default_idmap: 4699 You must either run as root, or define uid mappings
lxc-create: testfedora31_1: conf.c: suggest_default_idmap: 4700 To pass uid mappings to lxc-create, you could create
lxc-create: testfedora31_1: conf.c: suggest_default_idmap: 4701 ~/.config/lxc/default.conf:
lxc-create: testfedora31_1: conf.c: suggest_default_idmap: 4702 lxc.include = /etc/lxc/default.conf
lxc-create: testfedora31_1: conf.c: suggest_default_idmap: 4703 lxc.idmap = u 0 100000 65536
lxc-create: testfedora31_1: conf.c: suggest_default_idmap: 4704 lxc.idmap = g 0 100000 65536
[... snip snip ...]
```

`lxc-create` could be improved by giving it the ability to automatically create `~/.config/lxc/default.conf` with the above recommended key value pairs instead of asking the user to manually copy-paste them from the output.

This would improve the first-run user experience and would make the behavior of LXC consistent with many other binaries and utilities that create reasonable default config files in `~/.config/` when they don't detect any pre-existing ones on first-run.

# Steps to reproduce

 1. Run `lxc-create` as an unprivileged user on a fresh install:
 ```
[regularuser@testserver ~]$ lxc-create -t download -n testfedora31_1 -- -d fedora -r 31 -a amd64
lxc-create: testfedora31_1: parse.c: lxc_file_for_each_line_mmap: 100 No such file or directory - Failed to open file "/home/regularuser/.config/lxc/default.conf"
lxc-create: testfedora31_1: conf.c: chown_mapped_root: 3082 No uid mapping for container root
lxc-create: testfedora31_1: lxccontainer.c: do_storage_create: 1295 Error chowning "/home/regularuser/.local/share/lxc/testfedora31_1/rootfs" to container root
lxc-create: testfedora31_1: conf.c: suggest_default_idmap: 4699 You must either run as root, or define uid mappings
lxc-create: testfedora31_1: conf.c: suggest_default_idmap: 4700 To pass uid mappings to lxc-create, you could create
lxc-create: testfedora31_1: conf.c: suggest_default_idmap: 4701 ~/.config/lxc/default.conf:
lxc-create: testfedora31_1: conf.c: suggest_default_idmap: 4702 lxc.include = /etc/lxc/default.conf
lxc-create: testfedora31_1: conf.c: suggest_default_idmap: 4703 lxc.idmap = u 0 100000 65536
lxc-create: testfedora31_1: conf.c: suggest_default_idmap: 4704 lxc.idmap = g 0 100000 65536
lxc-create: testfedora31_1: lxccontainer.c: do_lxcapi_create: 1876 Failed to create (none) storage for testfedora31_1
lxc-create: testfedora31_1: tools/lxc_create.c: main: 331 Failed to create container testfedora31_1
```
 2. Observe errror message.

# Information to attach

 - [x] ~~any relevant kernel output (`dmesg`)~~ 
Not applicable. Error does not generate any kernel output.
 - [x] ~~container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)~~
Not applicable. Container does not exist and so cannot be started.
 - [x] ~~the containers configuration file~~
Not applicable. Container does not exist and so does not have a configuration file.

**Comment by brauner** [comment]
We wouldn't mind reviewing a patch for that.

**Comment by brauner** [comment]
But honestly that likely won't work unless you're running as root.

**Comment by toddhpoole** [comment]
Hi @brauner,

Could you help me understand your response? Not certain I follow the reason for closing.

Why would an unprivileged user, creating an unprivileged container, need to be root in order for `lxc-create` to automatically generate a sensible `~/.config/lxc/default.conf` on first-run if it doesn't already exist?

Creating reasonable default config files in an unprivileged user's `~/.config/` directory when no pre-existing ones are detected on first-run certainly seems like something that could be done without elevated privileges...

**Comment by lietu** [comment]
![image](https://github.com/lxc/lxc/assets/1296558/1ac926c9-79bd-4423-b604-7971bdd7d975)

Feel free to re-open this issue so someone will notice that it needs work.

**Comment by lietu** [comment]
And since for some reason this does not seem obvious, I guess I have to spell it out. Errors like this are more likely to bother people who are just trying out lxc for the first time. That is to say, people, who will not be able to submit a patch to fix it.

**Comment by perlun** [comment]
Ran into this same issue locally. For reference, in the case it helps:

### Current workaround

* Run `lxc-create` (or in our case, `packer build`) as `root` instead. Make sure to set `VAGRANT_CLOUD_TOKEN` or other required environment variables before running it (this is a Packer requirement, but mentioning it anyway since it was relevant in my case)

### Suggested fix

* Make `lxc-create` be more helpful to the user when trying to run `lxc-create` as an unprivileged user, since the `default.conf` file (with `uid` mappings) **must** exist in this context.

Superficially, this doesn't seem too hard to do - just write the content already suggested on screen to a new `default.conf` in the user's `~/.config/lxc` directory, perhaps interactively asking for confirmation first (if a TTY is attached), and probably failing hard if the file already exists (but lacks the UID mappings). But I agree that reopening the issue to confirm that "yes, this is indeed a stumbling stone for inexperienced people trying out LXC" also seems like a good first step.
