### ISSUE TITLE
Error in "Information to attach" section of issue tempate on GitHub

### ISSUE THREAD

**Issue by toddhpoole** [lxc/lxc#3220]
In the pre-populated issue template on GitHub, the **Information to attach** section lists a "container log" with a suggested command of:
`lxc-start -n <c> -l <log> -o DEBUG`

The arguments for `-l` and `-o` options appear to be transposed. That is, the command should read:
`lxc-start -n <c> -l DEBUG -o <log>`

In order to increase legibility and clarify intent, it might also be better to expand the angled bracketed arguments to something like:
`lxc-start -n <container_name> -l DEBUG -o <log_filepath>`

Relevant section of issue template is quoted below:

> # Information to attach
> 
>  - [ ] any relevant kernel output (`dmesg`)
>  - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
>  - [ ] the containers configuration file
>

**Comment by emojifreak** [comment]
@toddhpoole You can probably make a pull request directly for
https://github.com/lxc/lxc/blob/master/.github/ISSUE_TEMPLATE.md
