### ISSUE TITLE
Containers not reachable after a while with lxc-attach: missing cgroup folders

### ISSUE THREAD

**Issue by devkid** [lxc/lxc#323]
After a while (approximately 1 hour, or maybe less?), any container, started by systemd, with the following service file:

```
–> cat /etc/systemd/system/lxc@.service
[Unit]
Description=%i LXC
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/lxc-start -n %i
ExecStop=/usr/bin/lxc-stop -n %i
Restart=on-failure

[Install]
WantedBy=lxc.target
```

using `systemctl start lxc@web`, won't be reachable anymore by using `lxc-attach`:

```
–> lxc-attach -n web
lxc_container: No such file or directory - Could not add pid 21043 to cgroup /lxc/web: internal error
lxc_container: could not move attached process 21043 to cgroup of container
lxc_container: error communicating with child process
```

The container itself is still running and all applications running inside are working without any problem.

This problem seems to be related to the fact, that the containers, that aren't reachable anymore, aren't present in `/sys/fs/cgroup/memory/lxc/<container>` anymore. Furthermore, if no containers are reachable anymore, the folder `/sys/fs/cgroup/memory/lxc` isn't present anymore at all.

systemd itself still sees the cgroup, though:

```
-> systemctl status lxc@web
● lxc@web.service - web LXC
   Loaded: loaded (/etc/systemd/system/lxc@.service; enabled)
   Active: active (running) since Sun 2014-08-31 12:05:14 CEST; 2 days ago
 Main PID: 30615 (lxc-start)
   CGroup: /system.slice/system-lxc.slice/lxc@web.service
           ├─30615 /usr/bin/lxc-start -n web
           ├─30625 /sbin/init
           └─system.slice
             ├─nginx.service
             │ ├─ 5480 nginx: worker process
             │ ├─ 5481 nginx: worker process
...
```

Relevant config entries:

```
lxc.autodev = 1
lxc.kmsg = 0
lxc.cap.drop = sys_module mac_admin mac_override sys_time net_admin

lxc.network.type = veth
lxc.network.link = br0
lxc.network.flags = up
lxc.network.name = eth0
lxc.network.mtu = 1500
lxc.network.ipv4.gateway = auto
lxc.network.ipv6.gateway = x::x

# cgroups
lxc.cgroup.devices.deny = a
lxc.cgroup.devices.allow = c *:* m
lxc.cgroup.devices.allow = b *:* m
lxc.cgroup.devices.allow = c 1:3 rwm
lxc.cgroup.devices.allow = c 1:5 rwm
lxc.cgroup.devices.allow = c 1:7 rwm
lxc.cgroup.devices.allow = c 1:8 rwm
lxc.cgroup.devices.allow = c 1:9 rwm
lxc.cgroup.devices.allow = c 4:1 rwm
lxc.cgroup.devices.allow = c 5:0 rwm
lxc.cgroup.devices.allow = c 5:1 rwm
lxc.cgroup.devices.allow = c 5:2 rwm
lxc.cgroup.devices.allow = c 136:* rwm

lxc.cgroup.memory.soft_limit_in_bytes = 1500M
lxc.cgroup.memory.limit_in_bytes = 2000M
lxc.cgroup.cpu.shares = 256
lxc.cgroup.blkio.weight = 500

lxc.mount.entry = /data/pacman-pkg-cache var/cache/pacman/pkg none bind 0 0
lxc.mount.entry = /data/repo srv/repo none bind,ro,create=dir 0 0
lxc.mount.entry = /run/systemd/journal mnt/journal none bind,ro,create=dir 0 0

lxc.utsname = web
lxc.rootfs = /data/containers/web/rootfs
lxc.network.ipv4 = x.x.x.x/16
lxc.network.ipv6 = x::x/80
lxc.network.veth.pair = lxc_web
```

Using Linux Kernel 3.14.15-1-lts from Arch Linux.

**Comment by thmo** [comment]
Could you please cherry-pick this also on stable-1.0? Thanks.

**Comment by fanyeren** [comment]
--elevated-privileges works for me.

**Comment by mailinglists35** [comment]
this issue is present in latest centos 7.3 with `kernel-3.10.0-514.6.2.el7.x86_64` and `lxc-1.0.9-1.el7.x86_64`

`--elevated-privileges` workaround is working

**Comment by Mic92** [comment]
@thmo there is nothing to cherry-pick, just modify your systemd service to pick it up.

**Comment by stgraber** [comment]
I just cherry-picked the Delegate=true option into the stable-1.0 branch.

**Comment by mailinglists35** [comment]
I did not create/start the containers using system units, but only with lxc-* commands.

should I start them with systemd units instead like op describes, and add that Delegate=true option to the systemd unit as a workaround?

**Comment by Mic92** [comment]
@mailinglists35 if you start it manually, it should be not a problem to my knowledge.

**Comment by mailinglists35** [comment]
yes there is a problem when starting manually, too. I have created the unit and now I'm waiting to see if it happens again.
