### ISSUE TITLE
lxc-checkpoint -D does not work under systemd.unified_cgroup_hierarchy=1

### ISSUE THREAD

**Issue by emojifreak** [lxc/lxc#3240]
* Distribution: Ubuntu
 * Distribution version: 19.10 Eoan
 * Host Linux booted with systemd.unified_cgroup_hierarchy and does not have V1 CGroup Freezer
 * Host Kernel version: `Linux version 5.3.0-24-generic (buildd@lgw01-amd64-035) (gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2)) #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 (Ubuntu 5.3.0-24.26-generic 5.3.10)`
 * Package versions:
```shell-sessioin
# dpkg-query -W | egrep 'lxc|criu'
criu	3.13-2ppa1.19.04
liblxc-common	3.2.1+master~20191217-0246-0ubuntu1~eoan
liblxc1	3.2.1+master~20191217-0246-0ubuntu1~eoan
lxc-utils	3.2.1+master~20191217-0246-0ubuntu1~eoan
lxcfs	3.0.4-2
```

# Issue description

`lxc-checkpoint -D` gives the following error on a host Linux with cgroup v2-only.

```shell-session
# lxc-checkpoint -v -n eoan -D /tmp/checkpoint
lxc-checkpoint: eoan: criu.c: exec_criu: 413 failed getting freezer path
lxc-checkpoint: eoan: criu.c: do_dump: 1304 dump failed with 1
lxc-checkpoint: eoan: criu.c: do_dump: 1318 criu output: 
lxc-checkpoint: eoan: tools/lxc_checkpoint.c: checkpoint: 184 Checkpointing eoan failed
```

The below code does not seem to handle the new V2 freezer interface, e.g.,
`/sys/fs/cgroup/lxc.payload.eoan/cgroup.freeze` available in Linux kernel 5.2 and newer.

https://github.com/lxc/lxc/blob/2d50f34074beeb24b70a77044878b7aa6e199c32/src/lxc/criu.c#L409-L415

# Steps to reproduce

 1. Boot Linux with `systemd.unified_cgroup_hierarchy=1`
 2. Run some LXC container.
 3. `lxc-checkpoint -v -D -n  container-name`

**Comment by brauner** [comment]
LXC master handles the unified cgroup hierarchy. Please test with master and reopen if the issue still exists. But note that criu does not fully support the cgroup2 hierarchy yet, afaik.

**Comment by kolyshkin** [comment]
criu 3.14 added support for cgroupv2
