### ISSUE TITLE
Can't mount cgroup -- operation not permitted

### ISSUE THREAD

**Issue by danielrobbins** [lxc/lxc#3256]
We have two incidents of the infamous inability to create the systemd cgroup within an unprivileged container.

This is on Funtoo Linux. First report is here and was experienced with lxd: (I was hoping to not overload the bug tracker): https://discuss.linuxcontainers.org/t/issue-with-openrc-cgroup-permission-denied/6414

The second issue reported, which is using the identical lxc software versions, and appears to just be pure lxc, is reported here:
https://bugs.funtoo.org/browse/FL-6897

The reporter of the Funtoo bug indicates that downgrading lxc appears to work around the issue, so the problem appears to be related to lxc, not lxd, which is why I am reporting it here.

**Comment by brauner** [comment]
Is this still reproducible with current master which has completely reworked cgroup support. If so, please reopen!
