### ISSUE TITLE
lxc_strmmap's MAP_FIXED fails on sparc64 in src/lxc/cmd/lxc_user_nic.c

### ISSUE THREAD

**Issue by NsCDE** [lxc/lxc#3262]
Hi,

As many insane people, I use Ultra 45 for Linux and making lxc container there. I have stuck with this unportable mmap's MAP_FIXED problem in lxc_strmmap in src/lxc/parse.c which probably has to be ifdef'd with __sparc__, but I'm not really sure how to do this myself and submit a patch. :)

 * Distribution: Debian (sparc64)
 * Distribution version: bullseye/sid

 * The output of
   * `lxc-start --version`

3.0.4

   * `lxc-checkconfig`

Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-5.4.0-3-sparc64-smp
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/blkio
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/pids
/sys/fs/cgroup/memory
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/freezer
/sys/fs/cgroup/devices
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/rdma

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -a`
Linux varnava 5.4.0-3-sparc64-smp #1 SMP Debian 5.4.13-1 (2020-01-19) sparc64 GNU/Linux

   * `cat /proc/self/cgroup`

lxcusr1@varnava:~$ cat /proc/self/cgroup 
11:rdma:/user.slice/user-1001.slice
10:perf_event:/user.slice/user-1001.slice
9:devices:/user.slice/user-1001.slice
8:freezer:/user.slice/user-1001.slice
7:cpuset:/user.slice/user-1001.slice
6:memory:/user.slice/user-1001.slice
5:pids:/user.slice/user-1001.slice
4:cpu,cpuacct:/user.slice/user-1001.slice
3:net_cls,net_prio:/user.slice/user-1001.slice
2:blkio:/user.slice/user-1001.slice
1:name=systemd:/user.slice/user-1001.slice
0::/user.slice/user-1001.slice/session-5.scope

# Issue description

I cannot run containers in unprivileged mode, because suid root lxc-user-nic while using lxc_strmmap's MAP_FIXED flag fails due to non-portable flag. I'm not really a programmer but from my investigation it has to do something with page aligment where SHMLBA is bigger than getpagesize(): see this similar discussion: https://lists.gnu.org/archive/html/qemu-devel/2019-05/msg04252.html and this: https://patchwork.kernel.org/patch/10103041/

# Steps to reproduce

user: /usr/libexec/lxc/lxc-user-nic create /home/lxcusr1/.local/share/lxc lxtest4 $$ veth cuprija0 veth0

root: strace -f -s 512 -v -p <pid of user's shell> (user cannot strace suid root binaries)

# Information to attach

8051  mmap(0xfff0000100026000, 37, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_FIXED, 3, 0) = -1 EINVAL (Invalid argument)
8051  munmap(0xfff0000100026000, 38)    = 0
8051  write(2, "Invalid argument - Failed to establish shared memory mapping\n", 61) = 61

 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)

lxc-start lxtest4 20200205173658.960 INFO     network - network.c:lxc_create_network_unpriv_exec:2267 - Execing lxc-user-nic create /home/lxcusr1/.local/share/lxc lxtest4 7978 veth cuprija0 eth0
lxc-start lxtest4 20200205173659.854 ERROR    network - network.c:lxc_create_network_unpriv_exec:2296 - lxc-user-nic failed to configure requested network: Invalid argument - Failed to establish shared memory mapping
lxc-start lxtest4 20200205173659.855 ERROR    start - start.c:lxc_spawn:1840 - Failed to create the configured network

**Comment by brauner** [comment]
Let me see if I can fix this.

**Comment by NsCDE** [comment]
Thank you very much. Compiled and tested today. Nice!

**Comment by brauner** [comment]
No problem, sorry for the delay!
