### ISSUE TITLE
sysctl net.ipv4.tcp_allowed_congestion_control and net.ipv4.tcp_available_congestion_control

### ISSUE THREAD

**Issue by hloeung** [lxc/lxc#3267]
Hi,

Not sure if this is the right place to report it or this is something within the Linux kernel.

 * Distribution: Ubuntu
 * Distribution version: 18.04 and 20.04
 * The output of
   * `3.0.3` (from apt) and `3.21` (from snap)

# Issue description

Currently, within containers you can switch TCP congestion control algorithms. e.g. with sysctl net.ipv4.tcp_congestion_control=bbr or via /proc/sys//proc/sys/net/ipv4/tcp_congestion_control.

Unfortunately, there is no way to tell which ones are available or allowed. Would be nice to expose or pass through net.ipv4.tcp_allowed_congestion_control and net.ipv4.tcp_available_congestion_control from the host.

# Steps to reproduce

 1. sudo lxc launch ubuntu:18.04 ...
 2. sudo modprobe tcp_bbr
 3. sudo lxc exec ... -- sudo --login --user ubuntu
 4. sudo sysctl net.ipv4.tcp_congestion_control=bbr
 5. sudo sysctl net.ipv4.tcp_allowed_congestion_control net.ipv4.tcp_available_congestion_control

**Comment by stgraber** [comment]
That'd be a kernel bug. Should be a pretty easy one to fix though if @brauner is up for more networking fun :)

**Comment by hloeung** [comment]
@stgraber , thanks. I had thought it was within the kernel as I couldn't find any references in both the LXD nor LXC codebase.

@brauner , you up for the challenge? :)

**Comment by brauner** [comment]
@hloeung, @stgraber 
https://lore.kernel.org/netdev/20200219120253.2667548-1-christian.brauner@ubuntu.com/

**Comment by Merkus622** [comment]
Классная настройка сети
