### ISSUE TITLE
Question: Add new filesystem to lxc container

### ISSUE THREAD

**Issue by vot4anto** [lxc/lxc#3269]
Hi,
I'm sorry if the question is not concerning any issue, but I don't find any documentation about the possibility to add a new filesystem at one existing lxc container.
Even it is possible to create a container lxc with a fs separate one for / and for example one for /var.

thanks

# Required information

 * Distribution: Ubuntu 18.04

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

 * The output of
#lxc-start --version
  3.0.3

   * `lxc-checkconfig`
lxc-checkconfig
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.15.0-72-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/rdma
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/devices
/sys/fs/cgroup/freezer
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/memory
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/blkio
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/pids
/sys/fs/cgroup/net_cls,net_prio

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -a`
uname -a
Linux franklin 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

   * `cat /proc/self/cgroup`
cat /proc/self/cgroup
12:net_cls,net_prio:/
11:pids:/user.slice/user-1926200054.slice/session-341501.scope
10:cpuset:/
9:blkio:/user.slice
8:hugetlb:/
7:memory:/user.slice
6:perf_event:/
5:freezer:/
4:devices:/user.slice
3:cpu,cpuacct:/user.slice
2:rdma:/
1:name=systemd:/user.slice/user-1926200054.slice/session-341501.scope
0::/user.slice/user-1926200054.slice/session-341501.scope

**Comment by hallyn** [comment]
If you mean while it's running, no, only lxd does that for now.

You can add filesystems for the container to mount the next time it starts up in the container configuration file.  See 'man lxc.container.conf'.
