### ISSUE TITLE
make lxc-user-nic allow veth without bridging

### ISSUE THREAD

**Issue by mercora** [lxc/lxc#330]
Hi, i am currently testing unprivileged containers and i am happy to see it mostly just works....
However, i do not want to bridge the interfaces used by the containers. I just want them to have the tap device pair on the host side and do the routing manually...
I could add a bridge for every container i want to start but i really don't like this approach...

I tried few things and one of them was to replace the binary with a shell script that just returns the names as the lxc-user-nic binary would. I created the tap device on the host side manually and made the owner the user that should be able to start the container.

Sadly this did not work quite right so i'm now suggesting this feature because i think it should be fairly easy to add. Just do not add the device to a bridge and leave it as is after creation. It would also be nice for me to allow these tap devices to be pre created by some other script, in order to be able to set an ip address and other stuff. But i could life with doing it some other way.... 

I might also be happy with a workaround that does not involve creating bridges :)

**Comment by tbilles** [comment]
I'd like to see this feature too. My use case for unprivileged containers is to get an extra layer of security. I don't mind setting up the container as root (or run some custom setup script with root privileges). But after the initial setup, I'd feel better knowing that the container is separated from the root user on the host.

**Comment by hallyn** [comment]
You can set up a bridge specifically for your user used only for its containers. Containers won't be able to spoof/snoop on nics not on that bridge.

**Comment by brauner** [comment]
Seems there already is a solution for this. However, we won't necessarily nack a pr to introduce this feature.

**Comment by tbilles** [comment]
Thank you for your responses. The solution I'm currently using is a privileged container (owned and started by root), but configured to use user namespaces. The network traffic is routed and I'm using proxy ARP (no bridge).

For anybody who comes looking for the same thing that I did, here are some references that I found useful:

- https://lists.linuxcontainers.org/pipermail/lxc-users/2015-February/008553.html
- http://blog.benoitblanchon.fr/lxc-unprivileged-container/
- https://unix.stackexchange.com/questions/127554/building-unprivileged-userns-lxc-container-from-scratch-by-migrating-a-privil

**Comment by ceving** [comment]
Instead of a bridge you can also use peer-to-peer networks. But this requires either NAT or you have to tell your router about the virtual network in your host. See here for a detailed description for the NAT version:

- https://gitlab.com/snippets/1712451
