### ISSUE TITLE
Can't make an unprivileged contained, but privileged works fine

### ISSUE THREAD

**Issue by SamuilDichev** [lxc/lxc#3311]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 (Windows Subsystem for Linux)
* **lxc-start --version**
```
3.0.3
```
   * **lxc-checkconfig**
```
Kernel configuration not found at /proc/config.gz; searching...
lxc-checkconfig: unable to retrieve kernel configuration
Try recompiling with IKCONFIG_PROC, installing the kernel headers,
or specifying the kernel configuration path with:
  CONFIG=<path> lxc-checkconfig
```
   * **uname -a**
```
Linux DESKTOP-TFD5KD2 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```
   * **cat /proc/self/cgroup**
```
1:devices:/
```
   * **cat /proc/1/mounts**
```
rootfs / lxfs rw,noatime 0 0
none /dev tmpfs rw,noatime,mode=755 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,noatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,noatime 0 0
devpts /dev/pts devpts rw,nosuid,noexec,noatime,gid=5,mode=620 0 0
none /run tmpfs rw,nosuid,noexec,noatime,mode=755 0 0
none /run/lock tmpfs rw,nosuid,nodev,noexec,noatime 0 0
none /run/shm tmpfs rw,nosuid,nodev,noatime 0 0
none /run/user tmpfs rw,nosuid,nodev,noexec,noatime,mode=755 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
cgroup /sys/fs/cgroup tmpfs rw,relatime,mode=755 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,relatime,devices 0 0
C:\134 /mnt/c drvfs rw,noatime,uid=0,gid=0,case=off 0 0
D:\134 /mnt/d drvfs rw,noatime,uid=0,gid=0,case=off 0 0
F:\134 /mnt/f drvfs rw,noatime,uid=0,gid=0,case=off 0 0
S:\134 /mnt/s drvfs rw,noatime,uid=0,gid=0,case=off 0 0
```

# Issue description

A brief description of what failed or what could be improved.

**Note**: This is Ubuntu 18.04 running on Windows as a WSL and it works as `root`, but not as my user.

```
$ lxc-create -t download -n my-container
lxc-create: my-container: conf.c: chown_mapped_root: 3226 lxc-usernsexec failed: No such file or directory - Failed to open tt
lxc-create: my-container: tools/lxc_create.c: main: 327 Failed to create container my-container
```

```
dyils@DESKTOP-TFD5KD2:~/repos/local-golf-system$ cat ~/.config/lxc/default.conf
lxc.net.0.type = veth
lxc.net.0.link = lxcbr0
lxc.net.0.flags = up
lxc.net.0.hwaddr = 00:16:3e:xx:xx:xx
lxc.idmap = u 0 165536 65536
lxc.idmap = g 0 165536 65536

dyils@DESKTOP-TFD5KD2:~/repos/local-golf-system$ cat /etc/subuid
lxd:100000:65536
root:100000:65536
dyils:165536:65536

dyils@DESKTOP-TFD5KD2:~/repos/local-golf-system$ cat /etc/subgid
lxd:100000:65536
root:100000:65536
dyils:165536:65536
```

I also have `/etc/subuid-` and `/etc/subgid-` files, neither of which had my user but I've added the same line into them as well.

# Steps to reproduce

 1. Follow https://linuxcontainers.org/lxc/getting-started/

# Information to attach

 - [x] any relevant kernel output (`dmesg`)
[    0.006259]  Microsoft 4.4.0-18362.476-Microsoft 4.4.35
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l TRACE -o <logfile> `)
 - [ ] the containers configuration file

**Comment by stgraber** [comment]
What happens if you run `lxc-usernsexec`?

**Comment by SamuilDichev** [comment]
```
dyils@DESKTOP-TFD5KD2:~$ lxc-usernsexec
Failed to find subuid or subgid allocation
```
How is that possible, it looks like I have everything in order

**Comment by stgraber** [comment]
Can you run it under strace?

`strace -f lxc-usernsexec`

**Comment by SamuilDichev** [comment]
I gave up on it and ran it on a Virtual Machine, followed the same steps and working. Could this be WSL thing?

**Comment by stgraber** [comment]
Yeah, it could very well be that WSL uses `nosuid` or has a kernel with some limitations of some kind.

Since we don't have more details or proof of a LXC bug, let's close this for now.
