### ISSUE TITLE
How to configure a container to use fscrypt within

### ISSUE THREAD

**Issue by graysky2** [lxc/lxc#3334]
I'd like to use `fscrypt` within a LXC  to encrypt a directory therein.  I'm finding that the user space util, `fscrypt` does not like the fact that it is containerized.  For example, I start the container and ssh into it:

```
# fscrypt setup
Defaulting to policy_version 2 because kernel supports it.
Customizing passphrase hashing difficulty for this system...
Created global config file at "/etc/fscrypt.conf".
[ERROR] fscrypt setup: /: not a mountpoint
```

I was reading the `lxc.container.conf` man page and it seems like I might want to use a config option called `lxc.hook.pre-mount` but I am unclear on configuring it or if it's needed for this use-case.  I'd like to avoid having to encrypt this target outside of the container before I start it.

**Comment by brauner** [comment]
I think that @stgraber used to do something like this once?

**Comment by graysky2** [comment]
@brauner - I also opened this up at fscrypt's project page.  https://github.com/google/fscrypt/issues/211

I'm thinking if there is a configuration within lxc's config that can some how satisfy the condition of mounts described at that issue, they could leave their codebase as-is.  I just don't know enough about what LXC can do in this regard.

**Comment by stgraber** [comment]
@brauner no, in my case, it was an fscrypt protected directory being passed into the container, causing read/write to fail.

**Comment by graysky2** [comment]
@brauner @stgraber - The comments from @ebiggers in https://github.com/google/fscrypt/issues/211 consistent with this being a bug in `fscrypt` so unless you feel otherwise, please close this as not a lxc issue.  Thank you both for weighing in on this!

**Comment by brauner** [comment]
Thanks, closing then for now. Please report back if there's anything to fix on our side.
