### ISSUE TITLE
lxc-user-nic dies on user groups without names

### ISSUE THREAD

**Issue by spacefrogg** [lxc/lxc#3361]
We are running lxc in a corporate environment with central user management. This means users end up being associated with (system) groups that might have no meaning on a particular system and, thus, no name associated with it.

`lxc-user-nic` fails in `get_groupnames()` with "Could not find matched group record".

As you can see from the log, group 131 (docker, not installed on all systems) has no matching name.

I couldn't see from the source why this is treated as an error and the group is not just ignored. Additionally some systems, like OpenAFS (the network file system, which we also use) create anonymous groups per login session to separate access control per process group. So, this anonymous group issue is not just a lazy administrators thing.

# Steps to reproduce

 1. Associate a user with a group without a name (cannot be done locally)
 2. Create and start an lxc userspace container

# Information to attach

 - [x] container log (The <log> file from running `lxc-start -n <c> -l TRACE -o <logfile> `)
```
...
lxc-start pl 20200407154809.756 DEBUG    start - start.c:lxc_spawn:1738 - Preserved net namespace via fd 5
lxc-start pl 20200407154809.756 WARN     start - start.c:lxc_spawn:1743 - Operation not permitted - Failed to allocate new network namespace id
lxc-start pl 20200407154809.757 INFO     network - network.c:lxc_create_network_unpriv_exec:2633 - Execing lxc-user-nic create /home/spacefrogg/lxc pl 8451 veth vbr0 (null)
lxc-start pl 20200407154809.772 TRACE    network - network.c:lxc_create_network_unpriv_exec:2661 - Received output "cmd/lxc_user_nic.c: 224: get_groupnames: Could not find matched group record
cmd/lxc_user_nic.c: 226: get_groupnames - Success - Failed to get group name: 131
" from lxc-user-nic
lxc-start pl 20200407154809.772 ERROR    network - network.c:lxc_create_network_unpriv_exec:2677 - Argument list too long - Container side veth device name returned by lxc-user-nic is too long
lxc-start pl 20200407154809.773 ERROR    start - start.c:lxc_spawn:1751 - Failed to create the network
lxc-start pl 20200407154809.773 DEBUG    network - network.c:lxc_delete_network:3690 - Deleted network devices
lxc-start pl 20200407154809.773 TRACE    start - start.c:lxc_serve_state_clients:427 - Set container state to ABORTING
lxc-start pl 20200407154809.773 TRACE    start - start.c:lxc_serve_state_clients:430 - No state clients registered
```

**Comment by stgraber** [comment]
@brauner should be easy to fix

**Comment by brauner** [comment]
Sent a pr that should fix this!
