### ISSUE TITLE
lxc-update-config breaks lxc.logfile settings

### ISSUE THREAD

**Issue by matthijskooijman** [lxc/lxc#3369]
There is a typo in the script:

https://github.com/lxc/lxc/blob/b7b0264251c99a2c24ebc2514dbf24517945a5cd/src/lxc/cmd/lxc-update-config.in#L77

It has `1` where it should have `\1` in the replacement. Running the script on a file with the `lxc.logfile` directive produces:

```diff
-lxc.logfile = /var/log/lxc/template.log
+1lxc.log.file = /var/log/lxc/template.log
```

**Comment by stgraber** [comment]
Sent a fix

**Comment by matthijskooijman** [comment]
Thanks :-)
