### ISSUE TITLE
Fails to mount rootfs when / is shared on btrfs

### ISSUE THREAD

**Issue by terasaka2k** [lxc/lxc#338]
/ and /containers are mounted as btrfs subvolumes.
/containers/busy1 is a normal directory and contains a rootfs of busybox.

`mount --make-rprivate /`, then `lxc-start -n busy1` works fine.

But `mount --make-rshared /`, then `lxc-start -n busy1` fails with "ERROR    lxc_conf - failed to mount rootfs".

I printf debugged and found `rtfs_type[i].cb(...)` in conf.c:mount_rootfs() return -1.

**Comment by brauner** [comment]
This should be fixed in newer versions of `LXC`.
