### ISSUE TITLE
netlink: 'lxd': attribute type 1 has an invalid length.

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxc#3386]
* Distribution: Ubuntu
 * Distribution version: 19.10
 * Kernel version: 5.3.0-46-generic
 * LXC version: 4.0.2
 * LXD version: 4.0.0 (latest stable snap)
 * Storage backend in use: Dir

Upon starting container with defined network type `ipvlan` I am getting this warning in dmesg output.
`[11351.612158] netlink: 'lxd': attribute type 1 has an invalid length.`

This does not affect working state of container, `ipvlan` interface works as expected.

**Comment by stgraber** [comment]
LXD never directly interacts with netlink, so the only reason the kernel would show this is because `liblxc` is the source of the issue, for any of LXD's calls, it would show up as `ip`.

**Comment by tomponline** [comment]
Confirmed occurring with liblxc too:

```
[  436.771363] netlink: 'lxc-start': attribute type 1 has an invalid length.
```
