### ISSUE TITLE
Unprivilegized containers can't start for a second time.

### ISSUE THREAD

**Issue by tudorapo** [lxc/lxc#3387]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: debian
 * Distribution version: 10.3
 * The output of
   * `lxc-start --version` 
3.0.3
   * `lxc-checkconfig` (see below)
   * `uname -a`  
Linux melak 5.4.0-10.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.4-10.1~buster (2020-01-09) x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
10:perf_event:/
9:net_prio:/
8:net_cls:/
7:memory:/
6:hugetlb:/
5:freezer:/
4:devices:/
3:cpuset:/
2:cpu:/
1:blkio:/
0::/

   * `cat /proc/1/mounts`
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=8004708k,nr_inodes=2001177,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=1605392k,mode=755 0 0
/dev/nvme0n1p3 / ext4 rw,relatime,errors=remount-ro 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
pstore /sys/fs/pstore pstore rw,relatime 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=3210760k 0 0
/dev/mapper/ssd-home /home xfs rw,nosuid,nodev,noexec,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota 0 0
/dev/mapper/ssd-lxc /var/lib/lxc ext4 rw,relatime 0 0
/dev/mapper/ssd-download /download xfs rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota 0 0
/dev/mapper/ssd-csaszar /opt/csaszar xfs rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota 0 0
securityfs /sys/kernel/security securityfs rw,relatime 0 0
rpc_pipefs /run/rpc_pipefs rpc_pipefs rw,relatime 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup tmpfs rw,relatime,size=12k,mode=755 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,relatime,cpuset,release_agent=/run/cgmanager/agents/cgm-release-agent.cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/cpu cgroup rw,relatime,cpu,release_agent=/run/cgmanager/agents/cgm-release-agent.cpu 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,relatime,blkio,release_agent=/run/cgmanager/agents/cgm-release-agent.blkio 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,relatime,memory,release_agent=/run/cgmanager/agents/cgm-release-agent.memory 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,relatime,devices,release_agent=/run/cgmanager/agents/cgm-release-agent.devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,relatime,freezer,release_agent=/run/cgmanager/agents/cgm-release-agent.freezer 0 0
cgroup /sys/fs/cgroup/net_cls cgroup rw,relatime,net_cls,release_agent=/run/cgmanager/agents/cgm-release-agent.net_cls 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,relatime,perf_event,release_agent=/run/cgmanager/agents/cgm-release-agent.perf_event 0 0
cgroup /sys/fs/cgroup/net_prio cgroup rw,relatime,net_prio,release_agent=/run/cgmanager/agents/cgm-release-agent.net_prio 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,relatime,hugetlb,release_agent=/run/cgmanager/agents/cgm-release-agent.hugetlb 0 0
nfsd /proc/fs/nfsd nfsd rw,relatime 0 0
storage/tftp /var/tftp zfs rw,noatime,xattr,noacl 0 0
storage /storage zfs rw,noatime,xattr,noacl 0 0
storage/mentes /storage/mentes zfs rw,noatime,xattr,noacl 0 0
storage/lxc /storage/lxc zfs rw,noatime,xattr,noacl 0 0
storage/film /storage/film zfs rw,noatime,xattr,noacl 0 0
storage/betv /storage/betv zfs rw,noatime,xattr,noacl 0 0
storage/kep /storage/kep zfs rw,noatime,xattr,noacl 0 0
storage/zene /storage/zene zfs rw,noatime,xattr,noacl 0 0
storage/test /storage/test zfs rw,noatime,xattr,noacl 0 0

# Issue description

Containers start on boot, but not later.

For historical reasons I start the unprivilegized containers as root, with su:

su - -c "/usr/bin/lxc-start -n titkos -o /var/tmp/torr-titkos.log -l TRACE" torr

At boot this happens happily, I can stop it using the same su command but with lxc-stop, but not after.
# su - -c "/usr/bin/lxc-start -n titkos -o /var/tmp/torr-titkos.log -l TRACE" torr
lxc-start: titkos: lxccontainer.c: wait_on_daemonized_start: 833 No such file or directory - Failed to receive the container state
lxc-start: titkos: tools/lxc_start.c: main: 330 The container failed to start
lxc-start: titkos: tools/lxc_start.c: main: 333 To get more details, run the container in foreground mode
lxc-start: titkos: tools/lxc_start.c: main: 336 Additional information can be obtained by setting the --logfile and --logpriority options

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
[ 2788.256466] lxc-start[29087]: segfault at 0 ip 00007fb9dcedfbcd sp 00007ffefa83b620 error 4 in liblxc.so.1.4.0[7fb9dceca000+87000]
[ 2788.256471] Code: fe ff 48 89 df e8 43 cf fe ff 4a 8d 44 25 00 c7 44 24 14 00 00 00 00 48 89 44 24 18 48 8d 44 24 20 48 89 44 24 08 49 8b 45 28 <4c> 8b 38 4d 85 ff 0f 84 9f 01 00 00 45 31 e4 31 db eb 50 49 8b 7f

 - [ ] container log (The <log> file from running `lxc-start -n <c> -l TRACE -o <logfile> `)
 - [ ] the containers configuration file

**Comment by tudorapo** [comment]
trace log
[torr-titkos.log](https://github.com/lxc/lxc/files/4495474/torr-titkos.log)

**Comment by tudorapo** [comment]
lxc-checkconfig, for the user who should run this container
[lxc-checkconfig.txt](https://github.com/lxc/lxc/files/4495480/lxc-checkconfig.txt)

**Comment by tudorapo** [comment]
container config:

# cat /home/torr/.local/share/lxc/titkos/config 
# Template used to create this container: /usr/share/lxc/templates/lxc-download
# Parameters passed to the template:
# Template script checksum (SHA-1): 740c51206e35463362b735e68b867876048a8baf
# For additional config options, please look at lxc.container.conf(5)

# Uncomment the following line to support nesting containers:
#lxc.include = /usr/share/lxc/config/nesting.conf
# (Be aware this has security implications)


# Distribution configuration
lxc.include = /usr/share/lxc/config/debian.common.conf
lxc.include = /usr/share/lxc/config/debian.userns.conf
lxc.arch = x86_64

# Container specific configuration
lxc.idmap = u 0 165536 65536
lxc.idmap = g 0 165536 65536
lxc.rootfs.path = /var/lib/lxc/torr/titkos/
lxc.uts.name = titkos
lxc.mount.entry = /download  download/ none bind 0 0
# Network configuration
lxc.net.0.type = veth
lxc.net.0.link = lxbr0
lxc.net.0.flags = up
lxc.net.0.hwaddr = de:ad:be:ef:00:fc
lxc.start.auto = 1

**Comment by tudorapo** [comment]
subuid and subgid files have this line:

torr:165536:65536

**Comment by tudorapo** [comment]
[ejnye.23317.txt](https://github.com/lxc/lxc/files/4498770/ejnye.23317.txt)

strace output, the config for this attempt was this:

# Distribution configuration
lxc.include = /usr/share/lxc/config/debian.common.conf
lxc.include = /usr/share/lxc/config/debian.userns.conf
lxc.arch = x86_64

# Container specific configuration
lxc.idmap = u 0 165536 65536
lxc.idmap = g 0 165536 65536
lxc.rootfs.path = /var/lib/lxc/torr/titkos/
lxc.uts.name = titkos
lxc.mount.entry = /download  download/ none bind 0 0
# Network configuration
lxc.net.0.type = veth
lxc.net.0.link = lxbr0
lxc.net.0.flags = up
lxc.net.0.hwaddr = de:ad:be:ef:00:fc
lxc.start.auto = 1
lxc.apparmor.profile=unconfined
lxc.mount.auto=cgroup-full:mixed

**Comment by brauner** [comment]
Can you try and reproduce with 3.0.4 at least?
I need to backport quite a range of fixes and then we should make a bugfix release soon!

**Comment by tudorapo** [comment]
Is there a cheap and easy way to get 3.0.4 on a slightly mangled debian buster?

**Comment by tudorapo** [comment]
no worries, it starts with 3.0.4.

**Comment by brauner** [comment]
Excellent. Closing for now then.
