### ISSUE TITLE
lxc container migrate

### ISSUE THREAD

**Issue by zaczhou** [lxc/lxc#34]
is there have some method to migrate container to other lxc host, no matter hot migrate

**Comment by naisanza** [comment]
@stgraber does this also pertain to lxd? is all that is lxd live only in `/var/lib/lxd`? so if you copied `/var/lib/lxd` from one 16.04 system into a completely fresh 16.04 system, typed `lxc list` and it will work?

**Comment by stgraber** [comment]
Yeah, for LXD if you move all of /var/lib/lxd you should be fine too. But you can also just setup a fresh LXD on the target and then use "lxc move" to move the containers from one host to the other.

**Comment by naisanza** [comment]
@stgraber very nice. I like the portability of ZFS, and wanted to be able to just drop the pool in and LXD will be up and running without a hassel

**Comment by naisanza** [comment]
@stgraber how would you handle migrating the `/etc/default/lxd-bridge` configuration file? Since it's a single file in a big open directory we can't depend on mounting a ZFS dataset onto `/etc/default`
