### ISSUE TITLE
pam_cgfs.sgml.in needs update for pure cgroupv2

### ISSUE THREAD

**Issue by emojifreak** [lxc/lxc#3406]
At https://github.com/lxc/lxc/issues/3198#issuecomment-600176205 it is said that

> Closing this as libpam_cgfs can't be reasonably used on pure unified systems.

On the other hand, pam_cgfs.sgml.in has false description as

https://github.com/lxc/lxc/blob/57140e5a345acad0c89db8cdf97a907c94210d14/doc/pam_cgfs.sgml.in#L80-L85

In addition, there does not seem to exist an official document on how to prepare a manipulatable cgroup in pure cgroup2 hierarchy by a fully unprivileged user. There should be some document.
Lack of official statement seems to cause confusion such as #3404 
@avhvr

**Comment by avr1254** [comment]
@emojifreak What do you propose the comment should be updated to say?

**Comment by emojifreak** [comment]
For my cited part of the manual, I suggest

 The <command>pam_cgfs.so</command> module can handle ~~both~~ pure cgroupfs v1 
 (<filename>/sys/fs/cgroup/$controller</filename>) and ~~pure cgroupfs 
 v2 (<filename>/sys/fs/cgroup</filename>), as well as~~ mixed  *v1 and v2* mounts, 
 where some controllers are mounted in a standard cgroupfs v1 hierarchy 
 (<filename>/sys/fs/cgroup/$controller</filename>) and others in 
 cgroupfs v2 hierarchy (<filename>/sys/fs/cgroup/unified</filename>). 
*Pure cgroup v2 mount is not covered by the <command>pam_cgfs.so</command> module.*

The lack of documentation issue is filed separately as
https://github.com/lxc/linuxcontainers.org/issues/409

**Comment by avr1254** [comment]
After PR #3522, this issue can be closed.
