### ISSUE TITLE
ubuntu ppa:ubuntu-lxc/lxc-git-master not working for focal

### ISSUE THREAD

**Issue by smoser** [lxc/lxc#3421]
There seem to be 2 issues with the [ubuntu-lxc/lxc-git-master](https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/lxc-git-master/+packages) ppa.

1. Ubuntu archive version of 'lxc' now has an epoch (`1:4.0.2-0ubuntu1`), so it is newer than the lxc-git-master version (`4.0.2+master~20200519-1034-0ubuntu1~focal`)
2. the link above currently shows errors for each release for 4.0.3 like:

       Copying failed of lxcfs (4.0.3-0ubuntu1~ubuntu16.04.1~ppa1)  
       Copied from: LXCFS: stable. Copied by: Stéphane Graber Target series: Xenial
       lxcfs 4.0.3-0ubuntu1~ubuntu16.04.1~ppa1 in xenial (source has no binaries to be copied)

**Comment by stgraber** [comment]
Updated the packaging branch to line up with focal, that should help.
