### ISSUE TITLE
[created_at] => 0001-01-01T00:00:00Z

### ISSUE THREAD

**Issue by jamielsharief** [lxc/lxc#3425]
I am on LXC 4.1, I created an instance of Alpine Linux 3.1/amd64 and installed apache and enabled it, then created an image from it. As you can see the created_at and other dates say i created it 2000 years ago. 

I have experienced other strange problems with dates, where strtotime did not accept all dates, then i had to switch to DateTime class. 

```
[architecture] => x86_64
[cached] => 
[filename] => 
[fingerprint] => cc1f4a341aeda94e3a71f15c184646a5622129eeba729c3bab6cbf1d4b8a9165
[size] => 5730164
[type] => container
[created_at] => 0001-01-01T00:00:00Z
[last_used_at] => 0001-01-01T00:00:00Z
[uploaded_at] => 2020-05-27T10:50:57.071572141Z
[name] => apache
```

**Comment by stgraber** [comment]
that's the Go time representation of a zero-value.
`created_at` we can probably find a way to set, `last_used_at` should change the first time you create a container from that image.

**Comment by jamielsharief** [comment]
I noticed another issue with the datetime stamp, for example look at this, i just created an instance and it says created_at is `2020-05-27T14:57:13.298584683Z` however when  i try to convert like this `date('Y-m-d H:i:s', strtotime($datetime))` it comes back as 1970. If it is an ISO date, then the php strtotime should pick this up right? however `DateTime::createFromFormat('Y-m-d\TH:i:s+', $datetime)` does work.

The odd thing, is `strtotime` does work most time for the datetimes returned by the API.

**Comment by stgraber** [comment]
RFC3339nano looks like. It's not something we're picking, it's the default format in Go.

**Comment by brauner** [comment]
This is not a lxc bug so closing. @stgraber will send a pr for this to LXD I'd assume.

**Comment by stgraber** [comment]
Done already
