### ISSUE TITLE
No such device while trying to bring up interface using "SIOCSIFFLAGS"

### ISSUE THREAD

**Issue by vikikumar** [lxc/lxc#3429]
# Issue description
No such device while trying to bring up a cdc_ether interface using "SIOCSIFFLAGS" inside container.

# Information 
My host has a cdc_ether interface which it detects as eth0 as shown below using ls -lrt.

lrwxrwxrwx    1 root     root             0 Jan  1 00:51 eth0 -> ../../devices/platform/soc/1803a100.ehci/usb1/1-2/1-2:1.0/net/eth0

Now I wanted to access the device interface only from my container. So inside my container conf, i did add the following options
lxc.network.type  = phys
lxc.network.link  = eth0
lxc.network.flags = up
lxc.network.name  = eth2
lxc.mount.entry = /sys/class/net sys/class/net none bind,nosuid,nodev,rw 0 0 # created an empty directory inside my container rootfs like /sys/class/net sys/class/net 
lxc.mount.entry = /sys/devices sys/devices none bind,nosuid,nodev,rw 0 0 # created an empty directroy inside my container rootfs like /sys/devices

And before lxc-start, i am able to see the /sys/class/net sys/class/net  and /sys/devices getting mounted from host filesystem to my container filesystem.
Now from one of my binary inside container, i am trying to create a socket and to bring up the eth2 interface inside the container up using ioctl "SIOCSIFFLAGS". But its returning the error "No such device".
I am very new to lxc, Could you please let me know if I am missing something.

**Comment by stgraber** [comment]
What does `ip link show` get you from inside the container?

**Comment by vikikumar** [comment]
The command is not supported. Its a very trimmed up environment and many commands are removed, It only support few mandatory ones. I couldn't run ip link show. we have the ifconfig. I am not sure that helps.
ifconfig: 
eth2      Link encap:Ethernet  HWaddr 00:12:BD:06:DA:D9  
             inet addr:192.168.15.101  Bcast:192.255.255.255  Mask:255.0.0.0
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

**Comment by stgraber** [comment]
`ifconfig -a` then?

**Comment by vikikumar** [comment]
ifconfig -a was not showing the device, but if i assign an ipv4 ip address along with the interface lxc configuration, ifconfig -a output is as below:

 eth1      Link encap:Ethernet  HWaddr 26:F0:3F:34:27:3F  
           inet addr:1.2.3.7  Bcast:1.2.3.255  Mask:255.255.255.0
           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
 
 eth2      Link encap:Ethernet  HWaddr 00:12:BD:06:DA:D9  
           inet addr:192.168.15.101  Bcast:192.255.255.255  Mask:255.0.0.0
           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
 
 lo        Link encap:Local Loopback  
           inet addr:127.0.0.1  Mask:255.0.0.0
           UP LOOPBACK RUNNING  MTU:65536  Metric:1
 
LXC logs while creating the network from conf file:
================================
      lxc-start         15.805 INFO     lxc_start - Failed to store namespace references for stop hook: Kernel does not support setns.
      lxc-start         15.810 DEBUG    lxc_conf - move 'eth1' to '1607'
      lxc-start         15.860 DEBUG    lxc_conf - move 'eth2' to '1607'
      lxc-start         15.860 INFO     lxc_conf - 'usb_ipManager' hostname has been setup
      lxc-start         15.863 DEBUG    lxc_conf - 'eth1' has been setup
      lxc-start         15.917 DEBUG    lxc_conf - 'eth2' has been setup
      lxc-start         15.918 INFO     lxc_conf - network has been setup

**Comment by stgraber** [comment]
Can you run that failing binary under strace so we can see exactly what syscall is being done and against what?
If it works properly against a virtual ethernet device though, then it's most likely a kernel issue.

All that LXC can really do is move the device across namespace which it did, once it's there, if the driver or kernel gets confused about the network namespace, there isn't really anything we can do.

I'd recommend running as recent a kernel as you can find. What are you currently running on?

**Comment by vikikumar** [comment]
ok. I will integrate strace and check it where exactly its failing. 
kernel version is 4.4.155
I have a doubt, the eth2 interface created inside the container is moved to 1607 as per the lxc log as below
lxc-start         15.860 DEBUG    lxc_conf - move 'eth2' to '1607'

So to monitor or reset the uevent, I should point to the uevent file. where will lxc move this. 
while i am putting ls -lR inside my container, eth2 device is not present in /sys/class/net/eth2 and 
even /sys/class/net/eth0 is not present after bringing up eth2.

**Comment by stgraber** [comment]
```
 lxc.mount.entry = /sys/class/net sys/class/net none bind,nosuid,nodev,rw 0 0 # created an empty directory inside my container rootfs like /sys/class/net sys/class/net
```

This part in your config makes it so you see the host's view of /sys/class/net in the container rather than the namespace one.

**Comment by vikikumar** [comment]
Hi Graber, 
Thank you.
I removed the mount part and the temporarily created directories, but still I couldn't see the containers network interface drivers in /sys/class/net. 
I know that I am doing some mistakes. Will there be anything that prevents the access of container's network interface display in /sys/class/net.
I will close the issue and raise others as a new one as anyway the original issue is already resolved. Thank you. Much appreciated.

**Comment by stgraber** [comment]
You can force all of /sys to be writable through `lxc.mount.auto = sys:rw` but /sys/class/net is a path we normally make sure is writable as it is properly namespace.
