### ISSUE TITLE
macvlan setup with static ip continues to obtain dhcp address

### ISSUE THREAD

**Issue by erpadmin** [lxc/lxc#3431]
* Distribution:
fedora
 * Distribution version:
32
 * The output of
   * `lxc-start --version`
3.2.1
   * `lxc-checkconfig`
```
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-5.3.11-100.fc29.x86_64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Warning: newuidmap is not setuid-root
Warning: newgidmap is not setuid-root
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/devices
/sys/fs/cgroup/memory
/sys/fs/cgroup/freezer
/sys/fs/cgroup/blkio
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/pids
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/cpu,cpuacct

Cgroup v2 mount points:
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, loaded
Vlan: enabled, not loaded
Bridges: enabled, not loaded
Advanced netfilter: enabled, loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities:

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```
   * `uname -a`
Linux lxcserv.localnet 5.3.11-100.fc29.x86_64 #1 SMP Tue Nov 12 20:41:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
11:cpu,cpuacct:/user.slice
10:hugetlb:/
9:pids:/user.slice/user-0.slice/session-3.scope
8:perf_event:/
7:blkio:/user.slice
6:freezer:/
5:memory:/user.slice/user-0.slice/session-3.scope
4:devices:/user.slice
3:cpuset:/
2:net_cls,net_prio:/
1:name=systemd:/user.slice/user-0.slice/session-3.scope
0::/user.slice/user-0.slice/session-3.scope

# Issue description
container using macvlan setup and static config still obtains dhcp address in addition to static ip

# Steps to reproduce
lxc.net.0.type = macvlan
lxc.net.0.macvlan.mode = bridge
lxc.net.0.link = abcd
lxc.net.0.flags = up
lxc.net.0.hwaddr = e:f:g:h
lxc.net.0.ipv4.address =192.168.0.58/24
lxc.net.0.ipv4.gateway = x.x.x.y

example ip a in container after boot
```
~# ip a s dev eth0
8: eth0@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:a0:90:34 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.0.58/24 brd 192.168.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.0.198/24 brd 192.168.0.255 scope global secondary dynamic eth0
       valid_lft 86355sec preferred_lft 86355sec
    inet6 fe80::216:3eff:fea0:9034/64 scope link
       valid_lft forever preferred_lft forever
```
imo setting ipv4.address should disable dhcp for net.0

**Comment by stgraber** [comment]
DHCP is a user space thing, LXC does not alter any configuration files for your distro.

When using manual configuration of the network namespace through LXC, you should make sure that your container does not run some kind of network manager tool inside it which may flush those pre-applied settings or cause more to be applied.
