### ISSUE TITLE
Missing Devuan Beowulf Templates

### ISSUE THREAD

**Issue by numerys** [lxc/lxc#3433]
A Devuan template for the new release is missing. At least for the AMD64 platform.

**Comment by brauner** [comment]
That should either be filed against:
https://github.com/lxc/lxc-templates/pull/25
or against distrobuilder:
https://github.com/lxc/distrobuilder

**Comment by stgraber** [comment]
@monstermunchkin can we add beowulf?

**Comment by monstermunchkin** [comment]
> can we add beowulf?

I'll see what I can do.

**Comment by monstermunchkin** [comment]
https://github.com/lxc/lxc-ci/pull/165

**Comment by numerys** [comment]
https://git.devuan.org/gregolsen/lxc-devuan/blob/master/templates/lxc-devuan

**Comment by numerys** [comment]
I got a 'Beowulf' container installed, I just added 'beowulf' to
https://git.devuan.org/gregolsen/lxc-devuan/blob/master/templates/lxc-devuan#L818 
Nevertheless, this template does not allow for unprivileged container.
