### ISSUE TITLE
Trusty based containers fail to start on Precise host after HWE update

### ISSUE THREAD

**Issue by maiself** [lxc/lxc#344]
For various reasons I've been not yet been able to upgrade my system from Ubuntu 12.04 to 14.04, but I've been running several containers based off of Trusty (14.04) without problems until recently. The Hardware Enablement stack on my system had reached end-of-life, and upgrading the stack seems to have broken LXC. Trusty based containers hang when starting under the new Trusty based kernel, but work fine when booting from a pre-upgrade kernel. Containers based off of other versions of Ubuntu are unaffected. I'm not sure what information to provide, or if there's some configuration that fixes this; please let me know what may help.

What starting a Trusty based container on the new HWE stack looks like:

```
$ sudo lxc-start -n trusty-based-container
 * Starting Mount filesystems on boot                                    [ OK ]
 * Starting Signal sysvinit that the rootfs is mounted                   [ OK ]
 * Stopping Send an event to indicate plymouth is up                     [ OK ]
 * Starting Clean /tmp directory                                         [ OK ]
 * Stopping Clean /tmp directory                                         [ OK ]
 * Starting Populate and link to /run filesystem                         [ OK ]
 * Stopping Populate and link to /run filesystem                         [ OK ]
 * Starting Track if upstart is running in a container                   [ OK ]
 * Starting load fallback graphics devices                               [ OK ]
 * Starting workaround for missing events in container                   [ OK ]
 * Starting load fallback graphics devices                               [fail]
 * Starting Initialize or finalize resolvconf                            [ OK ]
 * Stopping workaround for missing events in container                   [ OK ]
 * Starting userspace bootsplash                                         [ OK ]
 * Starting Send an event to indicate plymouth is up                     [ OK ]
 * Starting configure network device security                            [ OK ]
 * Stopping userspace bootsplash                                         [ OK ]
 * Stopping Send an event to indicate plymouth is up                     [ OK ]
 * Starting Mount network filesystems                                    [ OK ]
 * Stopping Mount network filesystems                                    [ OK ]
 * Starting Bridge socket events into upstart                            [ OK ]
 * Starting configure network device                                     [ OK ]
HANG
```

kernels I have available:
3.5.0-54-generic (pre HWE update, all containers work)
3.13.0-37-generic (post update, Trusty based containers hang)

**Comment by maiself** [comment]
Relevant line from dmesg:

```[29674.444422] type=1400 audit(1417598698.812:112): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default" name="/sys/fs/pstore/" pid=5621 comm="mount" fstype="pstore" srcname="none" flags="ro"```

There were other file systems as well on some containers... I no longer have the logs for these.

Comparing the config files of containers that failed to start with ones that worked properly I found the following line missing from the failing containers config:

```lxc.include = /usr/share/lxc/config/ubuntu.common.conf```

Which has mention of ```/sys/fs/pstore``` and other file systems. After adding this line all containers now start properly for me. I don't know if this will solve the issue for anyone else tho...

**Comment by midnightmagic** [comment]
Thank you kindly for the follow-up; it will help people going forward.

**Comment by brauner** [comment]
Seems that the reason was a missing include. This should be fixed.
