### ISSUE TITLE
lxc-3.0.0 compilation failure on uclibc

### ISSUE THREAD

**Issue by john1jxm** [lxc/lxc#3440]
compile lxc-3.0.0 failure:
mipsel-linux-uclibc-4.6.3-kernel3.18
uClibc-0.9.33.2

error message:

/bin/sh ../../libtool  --tag=CC   --mode=compile /usr/local/bin/ccache /opt/trendchip/mipsel-linux-uclibc-4.6.3-kernel3.18/usr/bin/mipsel-buildroot-linux-uclibc-gcc -Wa,-mno-pdr -Wno-implicit-fallthrough -Wno-sizeof-pointer-memaccess -Wno-format-truncation -Wno-format-overflow -Wno-restrict  -DHAVE_CONFIG_H -I. -I../../src    -fPIC -DPIC -DLXCROOTFSMOUNT=\"/usr/local/lib/lxc/rootfs\" -DLXCPATH=\"/usr/local/var/lib/lxc\" -DLXC_GLOBAL_CONF=\"/usr/local/etc/lxc/lxc.conf\" -DLXCINITDIR=\"/usr/local/libexec\" -DLIBEXECDIR=\"/usr/local/libexec\" -DLXCTEMPLATEDIR=\"/usr/local/share/lxc/templates\" -DLXCTEMPLATECONFIG=\"/usr/local/share/lxc/config\" -DLOGPATH=\"/usr/local/var/log/lxc\" -DLXC_DEFAULT_CONFIG=\"/usr/local/etc/lxc/default.conf\" -DLXC_USERNIC_DB=\"/tmp/lxc/nics\" -DLXC_USERNIC_CONF=\"/usr/local/etc/lxc/lxc-usernet\" -DDEFAULT_CGROUP_PATTERN=\"lxc/%n\" -DRUNTIME_PATH=\"/tmp\" -DSBINDIR=\"/usr/local/sbin\" -I ../../src -I ../../src/lxc -I ../../src/lxc/storage -I ../../src/lxc/cgroups      -pthread -DASB_PLATFORM_MTK -Wall -Werror -MT liblxc_la-conf.lo -MD -MP -MF .deps/liblxc_la-conf.Tpo -c -o liblxc_la-conf.lo `test -f 'conf.c' || echo './'`conf.c
libtool: compile:  /usr/local/bin/ccache /opt/trendchip/mipsel-linux-uclibc-4.6.3-kernel3.18/usr/bin/mipsel-buildroot-linux-uclibc-gcc -Wa,-mno-pdr -Wno-implicit-fallthrough -Wno-sizeof-pointer-memaccess -Wno-format-truncation -Wno-format-overflow -Wno-restrict -DHAVE_CONFIG_H -I. -I../../src -fPIC -DPIC -DLXCROOTFSMOUNT=\"/usr/local/lib/lxc/rootfs\" -DLXCPATH=\"/usr/local/var/lib/lxc\" -DLXC_GLOBAL_CONF=\"/usr/local/etc/lxc/lxc.conf\" -DLXCINITDIR=\"/usr/local/libexec\" -DLIBEXECDIR=\"/usr/local/libexec\" -DLXCTEMPLATEDIR=\"/usr/local/share/lxc/templates\" -DLXCTEMPLATECONFIG=\"/usr/local/share/lxc/config\" -DLOGPATH=\"/usr/local/var/log/lxc\" -DLXC_DEFAULT_CONFIG=\"/usr/local/etc/lxc/default.conf\" -DLXC_USERNIC_DB=\"/tmp/lxc/nics\" -DLXC_USERNIC_CONF=\"/usr/local/etc/lxc/lxc-usernet\" -DDEFAULT_CGROUP_PATTERN=\"lxc/%n\" -DRUNTIME_PATH=\"/tmp\" -DSBINDIR=\"/usr/local/sbin\" -I ../../src -I ../../src/lxc -I ../../src/lxc/storage -I ../../src/lxc/cgroups -pthread -DASB_PLATFORM_MTK -Wall -Werror -MT liblxc_la-conf.lo -MD -MP -MF .deps/liblxc_la-conf.Tpo -c conf.c  -fPIC -DPIC -o .libs/liblxc_la-conf.o
conf.c: In function 'lxc_setup':
conf.c:3437:20: error: 'O_PATH' undeclared (first use in this function)
conf.c:3437:20: note: each undeclared identifier is reported only once for each function it appears in
conf.c: At top level:
cc1: error: unrecognized command line option "-Wno-restrict" [-Werror]
cc1: error: unrecognized command line option "-Wno-format-overflow" [-Werror]
cc1: error: unrecognized command line option "-Wno-format-truncation" [-Werror]
cc1: error: unrecognized command line option "-Wno-sizeof-pointer-memaccess" [-Werror]
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors

**Comment by stgraber** [comment]
Can you try building LXC 4.0 instead? And also make sure your compiler is reasonably recent? Those unrecognized command line options seem to indicate an older compiler.

3.0 is in security and critical bugfix maintenance at this point, so it's pretty unlikely that we'd fix this.

**Comment by john1jxm** [comment]
thanks, actually,  my compiler is old. but the compiler was supplied by the soc vendor, we can't replace.
also fail to compile LXC 4.0.
