### ISSUE TITLE
whether LXC support uclibc

### ISSUE THREAD

**Issue by john1jxm** [lxc/lxc#3441]
compile lxc-3.0.0 on uclibc 0.9.33.2  mipsel-linux-uclibc-4.6.3-kernel3.18, there are many errros.

https://linuxcontainers.org/lxc/getting-started/,as it say, lxc support uclibc.

my question is whether LXC support uclibc and if yes,  which version of uclibc is required?

**Comment by stgraber** [comment]
What are the errors?

**Comment by stgraber** [comment]
Ah, I see you filed another issue for the error.
