### ISSUE TITLE
Dongle 4G interface detects only in host even when running the container in UID 0

### ISSUE THREAD

**Issue by vikikumar** [lxc/lxc#3448]
I have a 4G Huwawei dongle. The host system has no problem in detecting the device as eth0. But since I want to bridge the device eth0 to a bridge interface br0 during dongle hotplug or bootup.
I have a udev(eudev) daemon running inside container, which will detect the hotplug of devices, and will provide us the hooks where we can run our scripts or binaries on device findings, so I ran the below command from the hook.
brctl addif br0 eth0

But the udevd container on executing brctl says the below error
eth0 interface does not exist
But the same container is able to detect the bridge interface created from the host.
I found that the bridge interface is detected when i mount, /sys/class and /sys/devices from the host. But even the information related to eth0 is available in /sys/class and /sys/devices, but why not its getting detected.

**Comment by stgraber** [comment]
Your container is using a network namespace but you're then leaking some data over /sys from the host.
This causes your container to be able to see those devices in /sys but not use them as they're not actually available in the network namespace of the container.

You're going to want to undo your /sys/ trick so you can actually see what's in the container and then either move the device or a veth pair to connect the container to the host or if you want to actually share network namespace with the host, then configure your container to do that instead.

**Comment by vikikumar** [comment]
Thank you stgraber.
I am using a very old version of lxc, lxc-0.9.0. Hence I couldn't do either lxc-device add for moving the device or do the lxc.network.type=none for sharing the network namespace.
Since I can't upgrade to the higher versions of lxc. Is it easier to backport the lxc.network.type=none from the higher versions of lxc.

**Comment by stgraber** [comment]
Looking at the code for 0.9, if no `lxc.network` keys are set at all in the config, no network namespace is created, effectively behaving as if lxc.network.type=none.
