### ISSUE TITLE
Lxc does not work well with MPTCP.

### ISSUE THREAD

**Issue by ytxing** [lxc/lxc#3455]
Hi, I am now using an ubuntu 16.04 vm in virtualbox. With the guild of the [HOWTO](https://www.nsnam.org/wiki/HOWTO_Use_Linux_Containers_to_set_up_virtual_networks), I succeed building two containers and they work well.
Then I try to use MPTCP. First of all, my host is MPTCP-enabled and well configured, and dmesg in the containers shows that I am using MPTCP v0.95. Then I create two containers with two interfaces for each of them. 

And I use NS3 tap-bridge to make it possible to ping each other using the two paths. However, traffic generated by iperf can only use one path at a time. That is, while each of the two paths works well alone, they cannot transfer data together as MPTCP is supposed to do.

BTW, when I enable pacp tracer, terrible pkt loss occurs.

Here is how the containers are configured:
```
# lxc-left-mp.conf
# Container with network virtualized using a pre-configured bridge named br-left and
# veth pair virtual network devices
lxc.utsname = left
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = br-left1
lxc.network.ipv4 = 10.0.0.1/24

lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = br-left2
lxc.network.ipv4 = 10.0.1.1/24
```
PLZ, is it impossible to use MPTCP in lxc?

**Comment by brauner** [comment]
Have you enabled `mptcp` via `/proc/sys/net/mptcp/enabled` (or some other name)?

**Comment by brauner** [comment]
Haven't heard back in a while. If you have new info and still think something needs to be fixed in LXC to make this work, please reopen.

**Comment by ytxing** [comment]
hi
Though, I can see 
```
root@left:/# dmesg | grep MPTCP
[    1.420724] MPTCP: Stable release v0.95.1
```
in my container, I got this too: 
```
root@left:/# sysctl net.mptcp
sysctl: cannot stat /proc/sys/net/mptcp: No such file or directory
```
My host is MPTCP enabled, but I did not install MPTCP in lxc containers, maybe I should first install it?
