### ISSUE TITLE
LXC container creation fails very often on Travis CI due to "invalid signature"

### ISSUE THREAD

**Issue by RalfJung** [lxc/lxc#3467]
I do not know if this is a Travis problem or an LXC problem or which side is best equipped to fix it, but I had to start somewhere with bring this up. ;)

# Required information

 * Distribution: Ubuntu
 * Distribution version: Bionic

LXC is running on CI here so it is non-trivial to get the version information... let me know if I should try to do that.

# Issue description

More than 50% of the time when we run
```python
container.create("download", args={"dist": "ubuntu", "release": ubuntu_release, "arch": "amd64"})
```
the command fails, saying
```
Downloading the image index

ERROR: Invalid signature for /tmp/tmp.EDpm19VcvC/index.asc
```
This means that I basically have to hit the "retry" button on CI many times until all jobs are green. And that is even though we run the above command 5 times in a loop with 10s wait time after each attempt to make sure we do not fail due to intermittent network failures.

I have tried setting `DOWNLOAD_KEYSERVER` to `keyserver.ubuntu.com`, which helped for some time but recently also started failing (and then it failed 100% of the time). I also tried `pgp.mit.edu`, but that has not helped. I am somewhat at a loss here. Rewriting CI to not use LXC would be rather painful but LXC on CI is so unreliable that it gets in the way of development. I would appreciate any advice you may have. :)

**Comment by RalfJung** [comment]
It seems like the retries do not actually attempt to even re-check the signature:
```
Setting up the GPG keyring

ERROR: Unable to fetch GPG key from keyserver

container creation failed, retrying after some waiting...

container creation failed, retrying after some waiting...

container creation failed, retrying after some waiting...

container creation failed, retrying after some waiting...

Traceback (most recent call last):

  File "./tests/tunneldigger.py", line 353, in <module>

    setup_template(args.setup)

  File "./tests/tunneldigger.py", line 35, in setup_template

    raise RuntimeError("failed to create container")

RuntimeError: failed to create container
```
The GPG error only occurs on the first attempt.

**Comment by stgraber** [comment]
Try to use a different gpg key server?

**Comment by RalfJung** [comment]
I did:

> I have tried setting DOWNLOAD_KEYSERVER to keyserver.ubuntu.com, which helped for some time but recently also started failing (and then it failed 100% of the time). I also tried pgp.mit.edu, but that has not helped. 

Are there other servers you could suggest?

**Comment by stgraber** [comment]
@RalfJung I've found keyserver.ubuntu.com to be pretty reliable

**Comment by RalfJung** [comment]
As mentioned I had tried that one, and it worked well for a few weeks but failed entirely last week, so I had to switch back to not setting `DOWNLOAD_KEYSERVER` at all.

**Comment by RalfJung** [comment]
I just had to retry a single job 4 times until it works. Is there any solution for this on the horizon? Clearly the keyserver infrastructure is way too unreliable to be used the way LXC uses it, when using LXC on CI. Caching could help, but I have no idea which folder we'd have to cache. Also retrying 5 times does not actually seem to help; is there a way to tell LXC to re-fetch all the keys that it previously failed to fetch?

**Comment by falves1** [comment]
same problem here, on Ubuntu
lxc-create -t download -n https1 -- -d ubuntu -r focal -a amd64 
Setting up the GPG keyring
Downloading the image index
ERROR: Invalid signature for /tmp/tmp.YkAOdA71OP/index.asc

**Comment by brauner** [comment]
This is now fixed in https://github.com/lxc/lxc/pull/3882
