### ISSUE TITLE
COPYING states GPLv3 in official lxc 4.0.3 tarball

### ISSUE THREAD

**Issue by ffontaine** [lxc/lxc#3484]
The official lxc 4.0.3 tarball (https://linuxcontainers.org/downloads/lxc/lxc-4.0.3.tar.gz) contains a COPYING file with the GPL-3.0 license text. However, from my understanding lxc is mainly licensed under LGPL-2.1+ with some files under GPL-2.0-only. Could you clarify why COPYING is GPLv3?

**Comment by stgraber** [comment]
All files have SPDX headers that make it very clear what license they're under.
The repo also ships the full text of both the GPLv2 and LGPLv2.1 license.

COPYING as interpreted by Github and other platforms does not support specifying varied licenses based on files, therefore it makes sense for it to be the most restrictive license, so folks don't mistakenly copy code from the coebase thinking it's all LGPLv2.1 based on COPYING.

Instead they'll either be fine with it being GPLv2 in which case LGPLv2.1 is fine too, or they'll look at the license of the actual code they're using to see if it's less restrictive than the default.

**Comment by tpetazzoni** [comment]
I think the point of the question is: does it make sense for the COPYING file to contain the GPLv3 text, if there is nothing under GPLv3 in your project ? Having COPYING contain the GPLv2 text would be more sensible if we follow the reasoning you have outlined.

**Comment by brauner** [comment]
> I think the point of the question is: does it make sense for the COPYING file to contain the GPLv3 text, if there is nothing under GPLv3 in your project ? Having COPYING contain the GPLv2 text would be more sensible if we follow the reasoning you have outlined.

The COPYING file is autogenerated it seems. We have never consciously used GPL v3 anywhere nor generated it. Do you have a patch to prevent this?

**Comment by ffontaine** [comment]
The COPYING file is added to the official tarball because `automake --add-missing` is called in `autogen.sh`:

It should be noted that automake already displays the following warning:
```
Makefile.am: installing './COPYING' using GNU General Public License v3 file
Makefile.am:     Consider adding the COPYING file to the version control system
Makefile.am:     for your code, to avoid questions about which license your project uses
```
So, the easiest way to fix this "issue" is to add back a simple COPYING file containing a single sentence explaining that:
> 
> All files have SPDX headers that make it very clear what license they're under.
> The repo also ships the full text of both the GPLv2 and LGPLv2.1 license.

**Comment by brauner** [comment]
> The COPYING file is added to the official tarball because `automake --add-missing` is called in `autogen.sh`:
> 
> It should be noted that automake already displays the following warning:
> 
> ```
> Makefile.am: installing './COPYING' using GNU General Public License v3 file
> Makefile.am:     Consider adding the COPYING file to the version control system
> Makefile.am:     for your code, to avoid questions about which license your project uses
> ```
> 
> So, the easiest way to fix this "issue" is to add back a simple COPYING file containing a single sentence explaining that:
> 
> > All files have SPDX headers that make it very clear what license they're under.
> > The repo also ships the full text of both the GPLv2 and LGPLv2.1 license.

https://github.com/lxc/lxc/pull/3486

Does that look reasonable?

**Comment by tpetazzoni** [comment]
Sounds reasonable, thanks!

**Comment by ffontaine** [comment]
Yes, that's look good, thanks.
