### ISSUE TITLE
Possible images.linuxcontainers.org replication problem

### ISSUE THREAD

**Issue by vsenko** [lxc/lxc#3489]
Mirror https://us.images.linuxcontainers.org/images/ubuntu/bionic/amd64/default/ contains:
- 20200715_08:05/
- 20200716_07:43/
- 20200717_10:32/
- 20200718_08:31/

While https://uk.images.linuxcontainers.org/images/ubuntu/bionic/amd64/default/ contains:
- 20200715_08:05/
- 20200716_07:43/
- 20200717_10:32/

Last successful build occurred more than an hour ago.

This results in errors when trying to create images (`lxc launch images:ubuntu/18.04 test`):
```
Error: Failed container creation: Unable to fetch https://images.linuxcontainers.org/images/ubuntu/bionic/amd64/default/20200718_08:31/lxd.tar.xz: 404 Not Found
```

**Comment by vsenko** [comment]
Issue resolved, mirrors contents is in sync.

I'll keep this issue opened to notify that synchronization of data between mirrors once took a significant amount of time.

**Comment by stgraber** [comment]
The mirrors aren't run by us. The origin server is always consistent on disk but network issues at the time of sync from the frontends can unfortunately happen.

This is monitored and was likely caught and fixed, though it being the weekend, likely not as fast as during the week.
