### ISSUE TITLE
Lxc static Ipv4 problem

### ISSUE THREAD

**Issue by pcsystemd** [lxc/lxc#3493]
Hello ,

I cannot understand why my containers do not keep their just one static IP when restarting and display several IPs when I run the command `lxc-ls -f` which causes access problems when it seems to me that this is OK in the lxc configuration file below.

lxc-ls -f
`NAME     STATE       AUTOSTART   GROUPS        IPV4          IPV6          UNPRIVILEGED 

app       RUNNING    1     -   192.168.12.100, 192.168.12.179    -     false   `

Thanks for your help

 * Distribution : Debian
 * Distribution version : 10 Buster
 * `lxc-start --version`  : 3.0.3

`
# Distribution configurationah, I've just noticed you have provided an example of the IPs, its just the formatting messed up a bit.
lxc.include = /usr/share/lxc/config/common.conf
lxc.arch = linux64

# Container specific configuration
lxc.apparmor.profile = generated
lxc.apparmor.allow_nesting = 1
lxc.rootfs.path = dir:/var/lib/lxc/app/rootfs
lxc.uts.name = app

# Network configuration
lxc.net.0.type = veth
lxc.net.0.link = virbr0
lxc.net.0.name = eth0
lxc.net.0.flags = up
lxc.start.auto = 1
lxc.net.0.ipv4.address = 192.168.12.100/24
lxc.net.0.ipv4.gateway = 192.168.12.254
`

**Comment by tomponline** [comment]
Can you give an example of the IPs being shown please?

Also what image do you use (i.e are you using one of our `download` templates)?

Finally, can you confirm if you are running a DHCP client inside your container?

Thanks

**Comment by tomponline** [comment]
@pcsystemd ah, I've just noticed you have provided an example of the IPs, its just the formatting messed up a bit.

**Comment by pcsystemd** [comment]
- Image : --template=download -- --dist=debian --release=buster --arch=amd64
- No running a DHCP in container

**Comment by tomponline** [comment]
@pcsystemd have just re-created this, and as suspected its because the `download` templates have DHCP enabled by default. Depending on the distro you pick, some replace the static IP with the dynamic one, others add a dynamic one as well as the original static one. Neither situation is what you want though, so you can fix this by disabling DHCP client in the container.

```
lxc-attach -n <container>
sed -i 's/iface eth0 inet dhcp/iface eth0 inet manual/g' /etc/network/interfaces
reboot
```

You also will likely need to modify that file `/etc/network/interfaces` and add a static gateway and nameserver config.

**Comment by pcsystemd** [comment]
Thanks a lot for your help. It actually works I now have a fixed IP but on the other hand the lxc does not respond and I think it is a problem with the gateway or other missing configuration. The problem is that I do not know that it is the gateway that must be indicated or what configuration is missing, so I go back to dynamic ip and comment on the last two lines below

# Network configuration
lxc.net.0.type = veth
lxc.net.0.link = virbr0
lxc.net.0.name = eth0
lxc.net.0.flags = up
lxc.start.auto = 1
#lxc.net.0.ipv4.address = 192.168.122.100/24
#lxc.net.0.ipv4.gateway = 192.168.122.254
