### ISSUE TITLE
how to run the test file in the project?

### ISSUE THREAD

**Issue by ccnankai** [lxc/lxc#3502]
I am a novice, how to run the test file in the project. Does it need to be compiled separately? After executing the make command, the test binary files are not generated.

**Comment by stgraber** [comment]
You need to build with `--enable-tests`

**Comment by ccnankai** [comment]
Thank you for your guidance.The forum seems to be unable to ask questions, so I came here.
(1)
Sorry, I don't know how to use the tools in the project. How do I get the option parameters ? I did not see the "--enable-tests" string   in any file.
(2)
I have used python and golang to develop upper-level applications before, and I am not familiar with the C development environment and development tools. I understand namespace, cgroup, and I can implement a simple container with golang. I want to use the lxc project to learn C and some low-level knowledge of Linux. Is it too difficult for me ?
I'm really sorry, there are a lot of questions.

**Comment by stgraber** [comment]
You pass --enable-tests to the configure command.

The forum works fine but your post was held for moderation and then deleted as it looked like spam.
There was no indication of what you were trying to do or even what project you were talking about.

**Comment by ccnankai** [comment]
I understand. Thank you very much.
