### ISSUE TITLE
lxccontainer.c fires templates not POSIXLY CORRECT

### ISSUE THREAD

**Issue by jelmd** [lxc/lxc#352]
For unprivileged containers/when a idmap is configured lxc-create fires the given template in a posixly incorrect way. The problem is, that it just appends the additional (intended) options to the argv list (see lxccontainer.c#1093 ff.) and thus they become operands if one passes one or more operands to lxc-create. As the result templates either break or need to re-invent the wheel ...

**Comment by brauner** [comment]
Tentatively closing this. Please re-open if this is still a problem.
