### ISSUE TITLE
Running losetup removes loop devices

### ISSUE THREAD

**Issue by ssampath** [lxc/lxc#3524]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution:
 * Distribution version:
 * The output of
ssgroot@SudheFMdev02:~/work/ncc/deploy/lxc$  sudo lxc-start --version
3.0.3
ssgroot@SudheFMdev02:~/work/ncc/deploy/lxc$ sudo lxc-checkconfig
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-5.4.0-42-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/blkio
/sys/fs/cgroup/memory
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/devices
/sys/fs/cgroup/pids
/sys/fs/cgroup/freezer
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/rdma
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/perf_event

Cgroup v2 mount points:
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities:

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

ssgroot@SudheFMdev02:~/work/ncc/deploy/lxc$ uname -a
Linux SudheFMdev02 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# Issue description

Running 'losetup' to map files to loop devices does NOT work.

# Steps to reproduce

 1. Create file-based nvme devices (/usr/bin/lxc-execute -n target -- dd if=/dev/zero of=/opt/nvme1 count=65535 bs=512)
 2. Add loop devices (/usr/bin/lxc-device -n target add /dev/loop5)
 3. Run losetup to map loop device with the file based device created in step 1
+ /usr/bin/lxc-execute -n target -- /sbin/losetup /dev/loop5 /opt/nvme0
losetup: /dev/loop5: failed to set up loop device: No such file or directory

I am doing this in a script so that I can create multiple files and map it with loop devices for my setup.

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l TRACE -o <logfile> `)
 - [ ] the containers configuration file

**Comment by ssampath** [comment]
When I try this 'manually' inside the container it works.

root@target:~/work# losetup /dev/loop5 /opt/nvme0
root@target:~/work# losetup -a
/dev/loop5: [2050]:1323177 (/opt/nvme0)
root@target:~/work# losetup /dev/loop6 /opt/nvme1
root@target:~/work# losetup /dev/loop7 /opt/nvme2
root@target:~/work# losetup -a
/dev/loop6: [2050]:1323178 (/opt/nvme1)
/dev/loop7: [2050]:1323179 (/opt/nvme2)
/dev/loop5: [2050]:1323177 (/opt/nvme0)
root@target:~/work#

**Comment by stgraber** [comment]
Don't use `lxc-execute`, if you're acting against a running container, you need `lxc-attach` or the result will be very confusing.

**Comment by brauner** [comment]
Indeed, this should be done with `lxc-attach`.
