### ISSUE TITLE
lxc fails to detect if root file system is on ramfs for kernel 5.4.58 and up

### ISSUE THREAD

**Issue by pranjas** [lxc/lxc#3525]
# Required information

 * Distribution: custom
 * Distribution version: kernel 5.4
 * The output of
   * `lxc-start --version` 3.0.3
   * `lxc-checkconfig`
`
WARNING: Unable to detect version from configuration, assuming latest\n
--- Namespaces ---
Namespaces: required
Utsname namespace: missing
Ipc namespace: required
Pid namespace: required
User namespace: missing
Network namespace: missing

--- Control groups ---
Cgroups: missing
/usr/bin/lxc-checkconfig: line 149: awk: not found

Cgroup v1 mount points: 

/usr/bin/lxc-checkconfig: line 155: awk: not found
Cgroup v2 mount points: 

Cgroup v1 systemd controller: missing
Cgroup v1 freezer controller: missing
/usr/bin/lxc-checkconfig: line 174: head: not found
Cgroup namespace: required
Cgroup device: missing
Cgroup sched: missing
Cgroup cpu account: missing
Cgroup memory controller: missing

--- Misc ---
Veth pair device: missing
Macvlan: missing
Vlan: missing
Bridges: missing
Advanced netfilter: missing
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: missing
CONFIG_IP6_NF_TARGET_MASQUERADE: missing
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: missing
CONFIG_NETFILTER_XT_MATCH_COMMENT: missing
FUSE (for use with lxcfs): missing

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: missing
CONFIG_EVENTFD: missing
CONFIG_EPOLL: missing
CONFIG_UNIX_DIAG: missing
CONFIG_INET_DIAG: missing
CONFIG_PACKET_DIAG: missing
CONFIG_NETLINK_DIAG: missing
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
`
   * `uname -a`
`
Linux (none) 5.4.58 #5 SMP Tue Aug 18 15:08:20 UTC 2020 x86_64 GNU/Linux
`
   * `cat /proc/self/cgroup`
`
3:name=devices:/
2:name=systemd:/
1:cpuset,cpu,cpuacct,blkio,memory,devices,freezer,perf_event,hugetlb,pids,rdma,debug:/
0::/
`
   * `cat /proc/1/mounts`
`
rootfs / rootfs rw 0 0
none /proc proc rw,nosuid,nodev,noexec,relatime 0 0
none /dev devtmpfs rw,relatime,size=10240k,nr_inodes=123540,mode=755 0 0
none /sys sysfs rw,relatime 0 0
none /dev/pts devpts rw,relatime,mode=600,ptmxmode=000 0 0
none /sys/fs/cgroup cgroup rw,relatime,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,perf_event,hugetlb,pids,rdma,debug 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,relatime,name=systemd 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,relatime,name=devices 0 0
none /root tmpfs rw,relatime 0 0
none /run tmpfs rw,relatime 0 0
/dev/sda3 /storage ext4 rw,relatime 0 0
`
# Issue description
lxc fails to detect that rootfs is on ramfs due to which pivot_root sys call fails and container fails
to come up.

# Steps to reproduce
 1. Step one
Use a kernel version 5.4.58 or later. 

 2. Step two
rootfs of host should be on ramfs. kernel command line parameter root=/dev/ram rootfstype=ramfs

 3. Step three
Starting a lxc container gives error lxc_pivot_root failed.

# Information to attach
The function `detect_ramfs_rootfs` checks specifically for the string `- rootfs rootfs` in `/proc/self/mountinfo` to detect whether or not ramfs is rootfs.
The last working kernel I used was 5.2.11 where `cat /proc/self/mountinfo` had

`
0 0 0:1 / / rw - rootfs rootfs rw
18 0 0:4 / /proc rw,nosuid,nodev,noexec,relatime - proc none rw
19 0 0:6 / /dev rw,relatime - devtmpfs none rw,size=10240k,nr_inodes=123540,mode=755
20 0 0:18 / /sys rw,relatime - sysfs none rw
21 19 0:19 / /dev/pts rw,relatime - devpts none rw,mode=600,ptmxmode=000
22 20 0:20 / /sys/fs/cgroup rw,relatime - cgroup none rw,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,perf_event,hugetlb,pids,rdma,debug
23 22 0:21 / /sys/fs/cgroup/systemd rw,relatime - cgroup cgroup rw,name=systemd
24 22 0:22 / /sys/fs/cgroup/devices rw,relatime - cgroup cgroup rw,name=devices
25 0 0:23 / /root rw,relatime - tmpfs none rw
26 0 0:24 / /run rw,relatime - tmpfs none rw
27 0 8:3 / /storage rw,relatime - ext4 /dev/sda3 rw
`

With kernel 5.4.58 the rootfs entry is changed to 
`0 0 0:1 / / rw - rootfs none rw`

This is due to the fact that kernel changed rootfs to use `ramfs_context_ops` whose `ramfs_parse_param` ignores the "source" (device) parameter but doesn't mark it as parameter not recognised (-ENOPARAM) but marks it as handled (0). Because of this the device "source" parameter isn't set and the device information is marked as "none" instead of "rootfs".

I'm unsure if this is kernel regression or should lxc change the function `detect_ramfs_rootfs` to check only for `- rootfs` instead of `- rootfs rootfs` so that it works with older kernels as well as latest ones.

**Comment by brauner** [comment]
On Wed, Aug 19, 2020 at 01:54:48AM -0700, Pranay Kumar Srivastava wrote:
> 
> # Information to attach
> The function `detect_ramfs_rootfs` checks specifically for the string `- rootfs rootfs` in `/proc/self/mountinfo` to detect whether or not ramfs is rootfs.
> The last working kernel I used was 5.2.11 where `cat /proc/self/mountinfo` had
> 
> `
> 0 0 0:1 / / rw - rootfs rootfs rw
> 18 0 0:4 / /proc rw,nosuid,nodev,noexec,relatime - proc none rw
> 19 0 0:6 / /dev rw,relatime - devtmpfs none rw,size=10240k,nr_inodes=123540,mode=755
> 20 0 0:18 / /sys rw,relatime - sysfs none rw
> 21 19 0:19 / /dev/pts rw,relatime - devpts none rw,mode=600,ptmxmode=000
> 22 20 0:20 / /sys/fs/cgroup rw,relatime - cgroup none rw,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,perf_event,hugetlb,pids,rdma,debug
> 23 22 0:21 / /sys/fs/cgroup/systemd rw,relatime - cgroup cgroup rw,name=systemd
> 24 22 0:22 / /sys/fs/cgroup/devices rw,relatime - cgroup cgroup rw,name=devices
> 25 0 0:23 / /root rw,relatime - tmpfs none rw
> 26 0 0:24 / /run rw,relatime - tmpfs none rw
> 27 0 8:3 / /storage rw,relatime - ext4 /dev/sda3 rw
> `
> 
> With kernel 5.4.58 the rootfs entry is changed to 
> `0 0 0:1 / / rw - rootfs none rw`
> 
> This is due to the fact that kernel changed rootfs to use `ramfs_context_ops` whose `ramfs_parse_param` ignores the "source" (device) parameter but doesn't mark it as parameter not recognised (-ENOPARAM) but marks it as handled (0). Because of this the device "source" parameter isn't set and the device information is marked as "none" instead of "rootfs".
> 
> I'm unsure if this is kernel regression or should lxc change the function `detect_ramfs_rootfs` to check only for `- rootfs` instead of `- rootfs rootfs` so that it works with older kernels as well as latest ones.

Seems like a kernel regression to me. /proc/mountinfo format has an API
stability guarantee and shouldn't be broken.

But if you can send a PR to fix LXC to work with both than we'll take
it.

Thanks!
Christian

**Comment by brauner** [comment]
This should've been fixed by:
https://github.com/lxc/lxc/commit/97edebfacd8be1163a1ad285ddcfcf843f1a46de
