### ISSUE TITLE
Failed to reset devices.list: Operation not permitted

### ISSUE THREAD

**Issue by knstn-project** [lxc/lxc#3533]
* Distribution: Ubuntu
 * Distribution version: 20.04.1 LTS
 * The output of
   * `lxc-start --version` 4.0.2
   * `lxc-checkconfig` All green ("enabled") except:

CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing

   * `uname -a` Linux ubuntu 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

   * `cat /proc/self/cgroup`

12:net_cls,net_prio:/
11:devices:/user.slice
10:rdma:/
9:perf_event:/
8:pids:/user.slice/user-1000.slice/session-7.scope
7:memory:/user.slice/user-1000.slice/session-7.scope
6:hugetlb:/
5:blkio:/user.slice
4:freezer:/user/knstn/0
3:cpuset:/
2:cpu,cpuacct:/user.slice
1:name=systemd:/user.slice/user-1000.slice/session-7.scope
0::/user.slice/user-1000.slice/session-7.scope

   * `cat /proc/1/mounts`

sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,noexec,relatime,size=3984692k,nr_inodes=996173,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,noexec,relatime,size=802576k,mode=755 0 0
/dev/nvme0n1p2 / ext4 rw,relatime,errors=remount-ro 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup2 /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
none /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=16924 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
tracefs /sys/kernel/tracing tracefs rw,nosuid,nodev,noexec,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
/dev/loop1 /snap/chromium/1269 squashfs ro,nodev,relatime 0 0
/dev/loop2 /snap/chromium-ffmpeg/15 squashfs ro,nodev,relatime 0 0
/dev/loop3 /snap/core/9804 squashfs ro,nodev,relatime 0 0
/dev/loop5 /snap/gtk-common-themes/1506 squashfs ro,nodev,relatime 0 0
/dev/loop0 /snap/chromium/1284 squashfs ro,nodev,relatime 0 0
/dev/loop4 /snap/core/9665 squashfs ro,nodev,relatime 0 0
/dev/loop7 /snap/core18/1880 squashfs ro,nodev,relatime 0 0
/dev/loop6 /snap/gnome-3-34-1804/33 squashfs ro,nodev,relatime 0 0
/dev/loop8 /snap/snap-store/415 squashfs ro,nodev,relatime 0 0
/dev/loop10 /snap/gnome-3-28-1804/128 squashfs ro,nodev,relatime 0 0
/dev/loop9 /snap/snapd/8542 squashfs ro,nodev,relatime 0 0
/dev/loop11 /snap/snapd/8790 squashfs ro,nodev,relatime 0 0
/dev/loop12 /snap/gnome-3-34-1804/36 squashfs ro,nodev,relatime 0 0
/dev/loop13 /snap/snap-store/467 squashfs ro,nodev,relatime 0 0
/dev/loop14 /snap/core18/1885 squashfs ro,nodev,relatime 0 0
/dev/nvme0n1p1 /boot/efi vfat rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=802572k,mode=700,uid=1000,gid=1000 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0

# Issue description
What ever service i install/start inside a privileged container i get this error after a "systemctl status <service.unit>":
Failed to reset devices.list: Operation not permitted

I noticed first when i set up an OpenVPN server and tun interface wasn't being created. I searched online, tried multiple "solutions" but none worked.

# Steps to reproduce

 1. Step one
Start a privileged container
 2. Step two
Install and start a service like OpenSSH or OpenVPN server
 3. Step three
Check systemctl status <service.unit>

# Information to attach

  - [ ] container log (The <log> file from running `lxc-start -n <c> -l TRACE -o <logfile> `) 
[attachment_1.txt](https://github.com/lxc/lxc/files/5163977/attachment_1.txt)

 - [ ] the containers configuration file 
[attachment_2.txt](https://github.com/lxc/lxc/files/5163979/attachment_2.txt)

**Comment by brauner** [comment]
Privileged containers prevent device access by default as it is a security risk to grant the container access to arbitrary devices. So any service that tries to create non-allow-listed devices will fail. Older systemds logged failures to alter the device policy of a container but newer ones definitely don't.
If some service isn't starting because it is trying to create a device and you are sure that it is ok to create this device then you can add the device to the allow list of the container.
