### ISSUE TITLE
Discrepancy lxc-checkpoint vs lxc snapshot

### ISSUE THREAD

**Issue by jnnksdev** [lxc/lxc#3537]
Creating snapshots of containers is not working when using `lxc-checkpoint`, but `lxc snapshot` works fine.
I'm using Ubuntu 18.04 and am trying to snapshot a Ubuntu 18.04 container.
`lxc --version: 3.0.3` and `criu --version: 3.14` (GitID: `v3.14-120-gbbd33a44`, built myself with https://github.com/checkpoint-restore/criu/pull/1044 implemented)

```
sudo lxc launch ubuntu:bionic lxd-bionic
sudo lxc snapshot lxc-bionic sn1 --stateful
```
Works without a problem. The snapshot is created and can be restored afterwards.
____
```
sudo lxc-create --name bionic --template ubuntu -- template-options -r bionic
sudo lxc-start --name bionic --logfile ${PWD}/lxc.log --logpriority=DEBUG
sudo lxc-checkpoint --name=bionic --logfile ${PWD}/lxc.log --logpriority=DEBUG --checkpoint-dir=/tmp/cp
```
Does not work:
```
Error (criu/files-ext.c:96): Can't dump file 20 of that type [600] (anon anon_inode:bpf-map)
Error (criu/cr-dump.c:1349): Dump files (pid: 24273) failed with -1
Error (criu/cr-dump.c:1766): Dumping FAILED.
```
Considering that the PR mentioned above should include bpf-map support and lxd utilities working fine, I'm not sure where the problem is. 

Using lxd is not an option as I plan to use LXC C API in [Anbox](https://github.com/anbox/anbox/issues/1554).

**Comment by brauner** [comment]
This is a CRIU error and not a LXC error. You should double check that you're really using the CRIU version you think you are. In any case, there is nothing that LXC can do to help here, sorry!
