### ISSUE TITLE
Gentoo template not usable out-of-the-box

### ISSUE THREAD

**Issue by m23project** [lxc/lxc#3544]
# Required information

 * Distribution: Proxmox
 * Distribution version: 6.1

# Issue description

Hi there,

the Gentoo template is missing a feature to make the package manager work. To enable it, do the following:

echo 'FEATURES="-pid-sandbox"' >> /etc/portage/make.conf

Then the SSH server is not installed in the template, so a SSH connection to the container will not work, even if the public SSH key is given in the Proxmox GUI. To enable the SSH server, do the following:

emerge-webrsync
emerge --changed-use net-misc/openssh
rc-update add sshd default
rc-service sshd start

Further information (in German) can be found in https://www.goos-habermann.de/howto-10048-Gentoo-Proxmox-Paketverwaltung-LAMP-Software-Downgrade .

It would be nice, if you could include these "patches" into the next version of the Gentoo template. So it would be fully usable out-of-the-box.

Cu Hauke

**Comment by brauner** [comment]
This should be filed against https://github.com/lxc/lxc-templates. Please reopen over there.
