### ISSUE TITLE
Failing to start any container :  "Failed to setup cgroup limits"

### ISSUE THREAD

**Issue by rozmanro1** [lxc/lxc#3546]
Hi all,

I'm working on an arm64 machine.
# Distribution: Centos7 OS.
# kernel 4.19.128 
# Using an LXC version 3.0.4 

# lxc-checkconfig:
[root@localhost ~]# lxc-checkconfig
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Warning: newuidmap is not setuid-root
Warning: newgidmap is not setuid-root
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/freezer
/sys/fs/cgroup/memory
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/net_cls
/sys/fs/cgroup/blkio
/sys/fs/cgroup/devices
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/pids

Cgroup v2 mount points:

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, not loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, not loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: missing
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: missing
CONFIG_NETLINK_DIAG: missing
File capabilities:

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /lxd/bin/lxc-checkconfig

[root@localhost ~]#

# uname -a 
[root@localhost ~]# uname -a
Linux localhost 4.19.128 #3 SMP PREEMPT Sun Sep 6 10:09:06 IDT 2020 aarch64 aarch64 aarch64 GNU/Linux

# cat /proc/self/cgroup:
[root@localhost ~]# cat /proc/self/cgroup
11:pids:/
10:perf_event:/
9:hugetlb:/
8:devices:/user.slice
7:blkio:/
6:net_cls:/
5:cpuset:/
4:memory:/
3:freezer:/
2:cpu,cpuacct:/
1:name=systemd:/user.slice/user-0.slice/session-1.scope
[root@localhost ~]#

# cat /proc/1/mounts
[root@localhost ~]# cat /proc/1/mounts
/dev/root / ext4 rw,relatime 0 0
devtmpfs /dev devtmpfs rw,relatime,size=495828k,nr_inodes=123957,mode=755 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,mode=755 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/net_cls cgroup rw,nosuid,nodev,noexec,relatime,net_cls 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
/dev/mmcblk0p6 /USERFS ext4 rw,relatime 0 0
/dev/mmcblk0p3 /USERFS/sw/sw_pack ext4 rw,relatime 0 0
tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=100940k,mode=700 0 0
/dev/loop0 /lxd squashfs ro,relatime 0 0
/dev/mmcblk0p7 /mnt/extra btrfs rw,relatime,ssd,noacl,space_cache,subvolid=5,subvol=/ 0 0
/dev/loop1 /mnt/extra/lxd/storage-pools/default btrfs rw,relatime,compress=lzo,noacl,space_cache,user_subvol_rm_allowed,subvolid=5,subvol=/ 0 0
tmpfs /mnt/extra/lxd/shmounts tmpfs rw,relatime,size=100k,mode=711 0 0
tmpfs /mnt/extra/lxd/devlxd tmpfs rw,relatime,size=100k,mode=755 0 0
[root@localhost ~]#

# The issue:
I am able to start the LXD, to add images to the lxc from server, but when i try to start the container i am getting the following error:
Error: Failed to run: /lxd/bin/lxd forkstart test /var/lib/lxd/containers /var/log/lxd/test/lxc.conf:

# Steps to reproduce

 1. start lxd
 2. start container by running lxc start test

# Information to attach
[root@localhost ~]# lxc list
+------+---------+------+------+------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+------+------+------------+-----------+
| test | STOPPED |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+
[root@localhost ~]# lxc start test
EROR[09-30|05:12:14] Failed starting container                stateful=false name=test action=start created=2020-09-30T04:56:22+0000 ephemeral=false used=2020-09-30T04:56:43+0000
Error: Failed to run: /lxd/bin/lxd forkstart test /var/lib/lxd/containers /var/log/lxd/test/lxc.conf:
Try `lxc info --show-log test` for more info
[root@localhost ~]#

**lxc info --show-log test:**
[root@localhost ~]# lxc info --show-log test
Name: test
Remote: unix://
Architecture: aarch64
Created: 2020/09/30 04:56 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

lxc test 20200930051213.813 WARN     initutils - initutils.c:setproctitle:341 - Invalid argument - Failed to set cmdline
lxc test 20200930051213.962 ERROR    start - start.c:proc_pidfd_open:1607 - Function not implemented - Failed to send signal through pidfd
**lxc test 20200930051214.106 WARN     cgfsng - cgroups/cgfsng.c:__cg_legacy_setup_limits:2342 - Failed to set "cpu.cfs_period_us" to "100000"
lxc test 20200930051214.116 ERROR    start - start.c:lxc_spawn:1785 - Failed to setup cgroup limits for container "test"**
lxc test 20200930051214.148 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:851 - Received container state "ABORTING" instead of "RUNNING"
lxc test 20200930051214.568 ERROR    start - start.c:__lxc_start:2019 - Failed to spawn container "test"
lxc 20200930051214.140 WARN     commands - commands.c:lxc_cmd_rsp_recv:135 - Connection reset by peer - Failed to receive response for command "get_state"

# lxc.conf
[root@localhost ~]# cat /var/log/lxd/test/lxc.conf
lxc.log.file = /var/log/lxd/test/lxc.log
lxc.log.level = warn
lxc.console.buffer.size = auto
lxc.console.size = auto
lxc.console.logfile = /var/log/lxd/test/console.log
lxc.mount.auto = proc:rw sys:rw
lxc.autodev = 1
lxc.pty.max = 1024
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file,optional 0 0
lxc.mount.entry = /dev/net/tun dev/net/tun none bind,create=file,optional 0 0
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none rbind,create=dir,optional 0 0
lxc.mount.entry = /dev/mqueue dev/mqueue none rbind,create=dir,optional 0 0
lxc.arch = linux64
lxc.hook.version = 1
lxc.hook.pre-start = /lxd/bin/lxd callhook /var/lib/lxd 3 start
lxc.hook.stop = /lxd/bin/lxd callhook /var/lib/lxd 3 stopns
lxc.hook.post-stop = /lxd/bin/lxd callhook /var/lib/lxd 3 stop
lxc.tty.max = 0
lxc.uts.name = test
lxc.mount.entry = /var/lib/lxd/devlxd dev/lxd none bind,create=dir 0 0
lxc.seccomp.profile = /var/lib/lxd/security/seccomp/test
lxc.idmap = u 0 1000000 65536
lxc.idmap = g 0 1000000 65536
lxc.cgroup.memory.soft_limit_in_bytes = 32000000
lxc.cgroup.cpu.shares = 224
lxc.cgroup.cpu.cfs_period_us = 100000
lxc.rootfs.path = dir:/var/lib/lxd/containers/test/rootfs
lxc.mount.entry = /var/lib/lxd/shmounts/test dev/.lxd-mounts none bind,create=dir 0 0
[root@localhost ~]#

I am seeing as well these warnings when starting the LXD:
[root@localhost cgroup]# lxd &
[1] 5254
[root@localhost cgroup]# WARN[09-30|04:52:09] AppArmor support has been disabled because of lack of kernel support
**WARN[09-30|04:52:09] Couldn't find the CGroup network class controller, network limits will be ignored.**

Maybe the warning in bold might be the problem?
I'm pretty new to lxc so any help would be appreciated. 
Thanks!

**Comment by stgraber** [comment]
Looks like your kernel may not be using cfs causing CPU limits to fail to apply.

**Comment by rozmanro1** [comment]
> Looks like your kernel may not be using cfs causing CPU limits to fail to apply.

Yes that what was missing. thanks!!

Another question, now the container is starting and running, but i see in the log those warnings/errors:
[root@localhost ~]# lxc info newTest --show-log
Name: newTest
Remote: unix://
Architecture: aarch64
Created: 2020/10/05 00:38 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 4639
Resources:
  Processes: 4
  CPU usage:
    CPU usage (in seconds): 2
  Memory usage:
    Memory (current): 1.18MB
    Memory (peak): 4.95MB
  Network usage:
    ip_vti0:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    gre0:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    gretap0:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    ip6tnl0:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    sit0:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    tunl0:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    erspan0:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    ip6_vti0:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0

Log:

**lxc newTest 20201007145344.748 WARN     initutils - initutils.c:setproctitle:341 - Invalid argument - Failed to set cmdline
lxc newTest 20201007145344.910 ERROR    start - start.c:proc_pidfd_open:1607 - Function not implemented - Failed to send signal through pidfd**

[root@localhost ~]#

Is that something important ?

**Comment by stgraber** [comment]
Both of those are fine. It looks like the kernel you're using doesn't make it easy to rewrite the process name but that's just a cosmetic thing. The pidfd error is similar, your kernel doesn't support that feature so liblxc will use the legacy mode transparently.

I believe we have a change in our upcoming release to quiesce that latter one as ERROR is misleading here :)
