### ISSUE TITLE
lxc-create -t download  : unable ERROR: Unable to fetch GPG key from keyserver

### ISSUE THREAD

**Issue by luffah** [lxc/lxc#3550]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of
   * `lxc-start --version`  : 3.0.3
   * `lxc-checkconfig`
     ```
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.15.0-118-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/memory
/sys/fs/cgroup/blkio
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/pids
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/rdma
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/freezer
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/devices

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```
   * `uname -a`
``` Linux kilauea 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```
   * `cat /proc/self/cgroup`
```
12:devices:/user.slice
11:cpuset:/
10:perf_event:/
9:freezer:/user/root/0
8:net_cls,net_prio:/
7:rdma:/
6:hugetlb:/
5:pids:/user.slice/user-1000.slice/session-c2.scope
4:cpu,cpuacct:/user.slice
3:blkio:/user.slice
2:memory:/user/root/0
1:name=systemd:/user/root/0
0::/user.slice/user-1000.slice/session-c2.scope
```
   * `cat /proc/1/mounts | grep cgroup`
```
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0

```

# Issue description
Option -t dowload  fails on fetching gpg key.
``
$ lxc-create -n lenomdetontruc -t download -- -d debian -r buster -a amd64
The cached copy has expired, re-downloading...
Setting up the GPG keyring
ERROR: Unable to fetch GPG key from keyserver
lxc-create: lenomdetontruc: lxccontainer.c: create_run_template: 1617 Failed to create container from template
lxc-create: lenomdetontruc: tools/lxc_create.c: main: 327 Failed to create container lenomdetontruc
```

Probably related to https://github.com/lxc/lxc/issues/3068

It would be nice to know if this option still supported in LXC or if i shall use LXD now.

**Comment by brauner** [comment]
@stgraber

**Comment by stgraber** [comment]
Our key was not attacked on any of the key servers. This error is most likely the result of connectivity issues on your side, firewalling, ...

You can try using an alternate key server, see if that helps.

**Comment by stgraber** [comment]
Closing since there is no apparent bug in LXC itself here and we have existing issues to track a potential switch away from GPG validation.

**Comment by luffah** [comment]
The question was to know if i shall continue to use LXC to create containers or am i required to use LXD ?
It works with LXD but not LXC ....

Does LXD use a different protocol ?

**Comment by TheBlueMatt** [comment]
For those who end up on this issue and don't see a workaround, you may need to set the server manually, eg `DOWNLOAD_KEYSERVER="pgp.mit.edu" lxc-create -t download...` instead of simply calling `lxc-create`.

**Comment by TheBlueMatt** [comment]
Looks like the mit keyserver has also succumbed to the keyserver DoS attacks that broke LXC, new workaround seems to be the ubuntu keyserver - `DOWNLOAD_KEYSERVER="keyserver.ubuntu.com" lxc-create...`

**Comment by keesj** [comment]
Still the method remains unreliable and it is really not necessary to download that key every time. Why not bundle the key or host it on a reliable servers?

Adding some instrumentation (strace) shows that the server often does accept the connection

what is the "ERR 167772380 No name <Dirmngr>\n" gotten from the key server?

```
lxc-create -t download 
newfstatat(AT_FDCWD, "/var/run/user/0", 0x7ffcd341d480, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/tmp/tmp.RuLosUhoo5/gpg/S.dirmngr", {st_mode=S_IFSOCK|0700, st_size=0, ...}, 0) = 0
socket(AF_UNIX, SOCK_STREAM, 0)         = 3
newfstatat(AT_FDCWD, "/tmp/tmp.RuLosUhoo5/gpg/S.dirmngr", {st_mode=S_IFSOCK|0700, st_size=0, ...}, 0) = 0
connect(3, {sa_family=AF_UNIX, sun_path="/tmp/tmp.RuLosUhoo5/gpg/S.dirmngr"}, 35) = 0
read(3, "# Home: /tmp/tmp.RuLosUhoo5/gpg\n"..., 1002) = 34
read(3, "Config: [none]\nOK Dirmngr 2.2.20"..., 1000) = 49
write(3, "GETINFO version", 15)         = 15
write(3, "\n", 1)                       = 1
read(3, "D 2.2.20\nOK\n", 1002)         = 12
write(3, "KEYSERVER --clear hkp://pool.sks"..., 47) = 47
write(3, "\n", 1)                       = 1
read(3, "OK\n", 1002)                   = 3
write(3, "KS_GET -- 0xE7FB0CAEC8173D669066"..., 52) = 52
write(3, "\n", 1)                       = 1
read(3, "ERR 167772380 No name <Dirmngr>\n", 1002) = 32
openat(AT_FDCWD, "/usr/share/locale/en_US/LC_MESSAGES/gnupg2.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale/en/LC_MESSAGES/gnupg2.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale-langpack/en_US/LC_MESSAGES/gnupg2.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale-langpack/en/LC_MESSAGES/gnupg2.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
```

**Comment by linas** [comment]
Hmm. Debugging now.  So, plain-old `gpg --refresh-keys` seems to work fine, so the failure seems to be limited to `lxc-create`. `strace` is unhelpful: 
```
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f0f2596b650) = 2829
wait4(2829, Setting up the GPG keyring
ERROR: Unable to fetch GPG key from keyserver
```
For some keyservers, the error return is almost instant; for others, its a 2-6 second delay before failing. This is from Austin.   I'm not sure what to try to trace next....

**Comment by keesj-exset** [comment]
Last time I downloaded the key and uploaded to the ubuntu gpg servers e.g. 
DOWNLOAD_KEYSERVER="keyserver.ubuntu.com" lxc-create -t download -n test1 -- -d alpine
Perhaps this works for you? . Documenting the steps to bypass the key download would also be great.

**Comment by keesj-exset** [comment]
pgp.mit.edu, keyserver.ubuntu.com both currently work for me

**Comment by linas** [comment]
Never mind. False alarm. Firewall issue on my end. How embarrassing. (Everything was working fine not all that long ago.)

**Comment by luffah** [comment]
If have no firewall. 

It works only with `DOWNLOAD_KEYSERVER="keyserver.ubuntu.com"` for me (Europe/France).

I abandoned using `lxc-create -t download ..`  and use instead default templates provided with debian. (`lxc-create -t <distrib> [distrib options] ..` and i look in template to check about every parameter effect)

This way is cleaner for me.

**Comment by keesj-exset** [comment]
> Edit : after `gpg --refresh-keys` (done with user and sudo and pressing Return key with a hammer), it works with `pgp.mit.edu` too

What type of hammer did you use?

**Comment by linas** [comment]
> `gpg --refresh-keys`

??? If I call `gpg -refresh-keys` it only refreshes my own personal keyring.  If I do it as root, then it refreshes `/root/.gnupg` which doesn't have any keys in it. If lxc is keeping a keyring somewhere, its not obvious where.  The only keyring in `/etc` is in `/etc/apt`

... Oh. I see a bunch of keyrings in `/usr/share/keyrings` but half of them have not been updated in 5 years, and the rest haven't been updated in 15 years. None are fresh. None have names that suggest that LXC is using them.

**Comment by keesj** [comment]
Hi Linas,

To add to this when I looked at it these operations where themself also happening inside a container hence updating the local keyrings would not have the desired effect.
