### ISSUE TITLE
Incorrectly signed index file on the UK mirror

### ISSUE THREAD

**Issue by mrc0mmand** [lxc/lxc#3557]
Hello!

For the past week or so we've got bitten by the issue described in https://github.com/lxc/lxc/issues/3467. After trying several other keyservers, the issue was still there, so I delved a bit deeper and the issue seems to be present on the UK mirror, but not on the US one (haven't tried other mirrors, if there are any):

#### UK mirror with a _bad_ signature:
```
$ wget -q https://uk.images.linuxcontainers.org/meta/1.0/{index-system,index-system.asc}
$ gpg --verify index-system.asc
gpg: assuming signed data in 'index-system'
gpg: Signature made Tue 20 Oct 2020 08:30:20 AM CEST
gpg:                using RSA key E7FB0CAEC8173D669066514CBAEFF88C22F6E216
gpg: BAD signature from "LXC pre-built images <lxc-devel@lists.linuxcontainers.org>" [unknown]
```

#### US mirror with a _good_ signature:
```
$ wget -q https://us.images.linuxcontainers.org/meta/1.0/{index-system,index-system.asc}
$ gpg --verify index-system.asc
gpg: assuming signed data in 'index-system'
gpg: Signature made Tue 20 Oct 2020 12:15:23 PM CEST
gpg:                using RSA key E7FB0CAEC8173D669066514CBAEFF88C22F6E216
gpg: Good signature from "LXC pre-built images <lxc-devel@lists.linuxcontainers.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: E7FB 0CAE C817 3D66 9066  514C BAEF F88C 22F6 E216
```

It applies to both the _user_ and the _system_ indexes.

I'm not sure if it's just a mirror desynchronization or there's something else going on. I managed to temporarily fix the issue locally by explicitly using the US mirror, e.g.:

```
 $ lxc-create -n bullseye-amd64 -t download -- -d debian -r bullseye -a amd64 --server us.images.linuxcontainers.org
```

/cc @RalfJung as the author of the original issue

**Comment by brauner** [comment]
@stgraber

**Comment by stgraber** [comment]
The UK mirror is currently out of sync for an unknown reason, the hosting provider was alerted and is looking into it.

**Comment by stgraber** [comment]
Confirmed that the sync issue has been resolved and all mirrors are back in sync.
