### ISSUE TITLE
Blocking lxc-wait for yet-to-run container breaks

### ISSUE THREAD

**Issue by peat-psuwit** [lxc/lxc#3570]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of
   * `lxc-start --version`: 4.0.2 (`lxc-utils` package version `1:4.0.2-0ubuntu1`)
   * `lxc-checkconfig` (Sorry for the mess, kernel has `CONFIG_MODULES` disabled)
<details>
<pre>
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/net_cls
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/devices
/sys/fs/cgroup/memory
/sys/fs/cgroup/debug
/sys/fs/cgroup/freezer

Cgroup v2 mount points: 

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: missing
--- Misc ---
Veth pair device: enabledlibkmod: ERROR ../libkmod/libkmod-module.c:1668 kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory
, not loaded
Macvlan: enabledlibkmod: ERROR ../libkmod/libkmod-module.c:1668 kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory
, not loaded
Vlan: enabledlibkmod: ERROR ../libkmod/libkmod-module.c:1668 kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory
, not loaded
Bridges: enabledlibkmod: ERROR ../libkmod/libkmod-module.c:1668 kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory
, not loaded
Advanced netfilter: enabledlibkmod: ERROR ../libkmod/libkmod-module.c:1668 kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory
, not loaded
CONFIG_NF_NAT_IPV4: enabledlibkmod: ERROR ../libkmod/libkmod-module.c:1668 kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory
, not loaded
CONFIG_NF_NAT_IPV6: enabledlibkmod: ERROR ../libkmod/libkmod-module.c:1668 kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory
, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabledlibkmod: ERROR ../libkmod/libkmod-module.c:1668 kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory
, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: missing
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabledlibkmod: ERROR ../libkmod/libkmod-module.c:1668 kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory
, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabledlibkmod: ERROR ../libkmod/libkmod-module.c:1668 kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory
, not loaded
FUSE (for use with lxcfs): enabledlibkmod: ERROR ../libkmod/libkmod-module.c:1668 kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory
, not loaded

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: missing
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: missing
CONFIG_NETLINK_DIAG: missing
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
</pre>
</details>

   * `uname -a`: `Linux localhost.localdomain 4.4.146-gce579499b-dirty #10 SMP PREEMPT Thu Oct 22 20:29:27 +07 2020 aarch64 aarch64 aarch64 GNU/Linux`
   * `cat /proc/self/cgroup`
<details>
<pre>
7:freezer:/user/root/0
6:debug:/
5:memory:/user.slice/user-0.slice/session-c1.scope
4:devices:/user.slice
3:cpu,cpuacct:/user.slice
2:net_cls:/
1:name=systemd:/user.slice/user-0.slice/session-c1.scope
</pre>
</details>

   * `cat /proc/1/mounts`
<details>
<pre>
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=1263844k,nr_inodes=315961,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,mode=600,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=279900k,mode=755 0 0
/dev/mmcblk0p51 /userdata ext4 rw,relatime,discard,nodelalloc,data=journal 0 0
/dev/loop0 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
/dev/loop1 /android/system ext4 ro,relatime,data=ordered 0 0
tmpfs /var/lib/lxc/android/rootfs tmpfs rw,relatime 0 0
none /android tmpfs rw,relatime,size=4k 0 0
/dev/mmcblk0p51 /android/data ext4 rw,relatime,discard,nodelalloc,data=journal 0 0
/dev/disk/by-partlabel/oem /android/odm ext4 ro,relatime,data=ordered 0 0
/dev/disk/by-partlabel/dsp /android/dsp ext4 ro,nosuid,nodev,relatime,nodelalloc,errors=panic,data=ordered 0 0
/dev/disk/by-partlabel/modem /android/firmware vfat ro,relatime,uid=1000,gid=1000,fmask=0337,dmask=0227,codepage=437,iocharset=iso8859-1,shortname=lower,errors=remount-ro 0 0
/dev/disk/by-partlabel/persist /android/persist ext4 rw,nosuid,nodev,relatime,nodelalloc,errors=panic,data=ordered 0 0
/dev/mmcblk0p51 /android/cache ext4 rw,relatime,discard,nodelalloc,data=journal 0 0
/dev/loop1 /etc/apparmor.d/abstractions/base ext4 ro,relatime,data=ordered 0 0
/dev/loop1 /etc/init/ofono.override ext4 ro,relatime,data=ordered 0 0
/dev/loop1 /usr/lib/udev/rules.d/70-android.rules ext4 ro,relatime,data=ordered 0 0
/dev/loop1 /usr/share/apparmor/hardware/graphics.d/apparmor-easyprof-ubuntu_android ext4 ro,relatime,data=ordered 0 0
/dev/loop1 /usr/share/apparmor/hardware/video.d/apparmor-easyprof-ubuntu_android ext4 ro,relatime,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/net_cls cgroup rw,nosuid,nodev,noexec,relatime,net_cls 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/debug cgroup rw,nosuid,nodev,noexec,relatime,debug 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
tracefs /sys/kernel/tracing tracefs rw,nosuid,nodev,noexec,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
none /var/lib/lxc/android/rootfs/boot tmpfs rw,relatime,size=4k 0 0
/dev/mmcblk0p51 /var/lib/lxc/android/rootfs/cache ext4 rw,relatime,discard,nodelalloc,data=journal 0 0
/dev/mmcblk0p51 /var/lib/lxc/android/rootfs/data ext4 rw,relatime,discard,nodelalloc,data=journal 0 0
/dev/disk/by-partlabel/dsp /var/lib/lxc/android/rootfs/dsp ext4 ro,nosuid,nodev,relatime,nodelalloc,errors=panic,data=ordered 0 0
/dev/disk/by-partlabel/modem /var/lib/lxc/android/rootfs/firmware vfat ro,relatime,uid=1000,gid=1000,fmask=0337,dmask=0227,codepage=437,iocharset=iso8859-1,shortname=lower,errors=remount-ro 0 0
none /var/lib/lxc/android/rootfs/misc tmpfs rw,relatime,size=4k 0 0
none /var/lib/lxc/android/rootfs/none tmpfs rw,relatime,size=4k 0 0
/dev/disk/by-partlabel/oem /var/lib/lxc/android/rootfs/odm ext4 ro,relatime,data=ordered 0 0
/dev/disk/by-partlabel/persist /var/lib/lxc/android/rootfs/persist ext4 rw,nosuid,nodev,relatime,nodelalloc,errors=panic,data=ordered 0 0
none /var/lib/lxc/android/rootfs/persistent tmpfs rw,relatime,size=4k 0 0
none /var/lib/lxc/android/rootfs/recovery tmpfs rw,relatime,size=4k 0 0
/dev/loop1 /var/lib/lxc/android/rootfs/system ext4 ro,relatime,data=ordered 0 0
/dev/loop1 /var/lib/lxc/android/rootfs/vendor ext4 ro,relatime,data=ordered 0 0
udev /var/lib/lxc/android/rootfs/socket devtmpfs rw,nosuid,relatime,size=1263844k,nr_inodes=315961,mode=755 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=279896k,mode=700 0 0
</pre>
</details>

# Issue description

Running `lxc-wait` on a yet-to-be-running container should wait for the container to run. Instead, it gives out the error immediately. This makes running `lxc-wait` right after `lxc-start` racy.

This seems to be the regression of #2027.

IMO, I believe this regression comes from commit 7792a5b60f79 ("commands: add additional check to lxc_cmd_sock_get_state()"). The function is called by `lxc_wait()` in `src/lxc/state.c`, which checks for `errno != ECONNREFUSED` to bail out. That errno is returned from `lxc_cmd_add_state_client()`, however, the commit makes `lxc_cmd_sock_get_state()` overwrite the errno when returning with error, which makes the check always true and the command always bails out.

# Steps to reproduce

 1. Create a container. Keep it not-running.
 2. Run `lxc-wait -l trace --name=<container name> --state=RUNNING --timeout=5`
   - Expected result: the command should wait for 5 seconds.
   - Actual result: the command exits immediately, with error:
```
lxc-wait: android: state.c: lxc_wait: 104 Invalid argument - Failed to receive state from monitor
```

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [x] container log (The <log> file from running ~~`lxc-start -n <c> -l TRACE -o <logfile> `~~ `lxc-wait -l trace --name=<container name> --state=RUNNING`)
```
lxc-wait android 20200401173529.977 TRACE    commands - commands.c:lxc_cmd:285 - Connection refused - Command "get_init_pid" failed to connect command socket
lxc-wait android 20200401173529.978 TRACE    commands - commands.c:lxc_cmd:285 - Connection refused - Command "add_state_client" failed to connect command socket
lxc-wait android 20200401173529.978 ERROR    state - state.c:lxc_wait:104 - Invalid argument - Failed to receive state from monitor
```
 - [x] the containers configuration file: https://github.com/ubports/lxc-android-config/blob/8d5ff8a867c3d05f3a5ef0531ffad7d6b811ee96/var/lib/lxc/android/config

(Before you asked: yes, I'm porting UT to Ubuntu 20.04.)

**Comment by r10r** [comment]
I can confirm this behaviour with lxc master:

```
lxc 20201118151307.322 ERROR    state - state.c:lxc_wait:104 - Invalid argument - Failed to receive state from monitor
```

I've reviewed the commit and can confirm the analysis of @peat-psuwit. Reverting https://github.com/lxc/lxc/commit/7792a5b60f7949d1a41db95f1ea2a7a6b89d9a3f fixes it.

@peat-psuwit  Thanks for reporting!
@brauner Please revert/update this commit and make lxc_wait() happy again  ;) Btw. I wonder what coverty has reported ...

**Comment by brauner** [comment]
This https://github.com/lxc/lxc/pull/3583 should fix it. Sorry I missed this issue.
