### ISSUE TITLE
lxc in openwrt, Error examining proc in /usr/lib/lxc/rootfs/proc

### ISSUE THREAD

**Issue by VicLin66** [lxc/lxc#3573]
### The output of
**-lxc-start --version**
1.1.3

**lxc-checkconfig**
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
Bridges: enabled
Advanced netfilter: enabled
CONFIG_NF_NAT_IPV4: enabled
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled
CONFIG_IP6_NF_TARGET_MASQUERADE: missing
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: missing

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: missing
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

**uname -a**
Linux OpenWrt 4.4.60

**cat /proc/self/cgroup**
1:cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,pids,debug:/

**cat /proc/1/mounts**
mtd:ubi_rootfs /rom squashfs ro,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,noatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,noatime 0 0
cgroup /sys/fs/cgroup cgroup rw,nosuid,nodev,noexec,relatime,cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,pids,debug,clone_children 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev,noatime 0 0
/dev/ubi0_2 /overlay ubifs rw,noatime 0 0
overlayfs:/overlay / overlay rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work 0 0
tmpfs /dev tmpfs rw,nosuid,relatime,size=512k,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,mode=600,ptmxmode=000 0 0
debugfs /sys/kernel/debug debugfs rw,noatime 0 0

# Issue to description
After I enabled default lxc package flag in openwrt, there are some uci setting and auto-create container when system is boot up. And I followed issue **#3017**, added [**,create=dir**] after nosuid in /lxc/lqsdk/config.
But when I ran lxc-start -n lqsdk -F, it showed error message. Seems stranged, does somebody have this experience before?
My rootfs/ in /lxc/lqsdk/ is empty, is it matter with run (lxc-attach) container?
### console log
root@OpenWrt:/# ls -la /lxc/lqsdk/
drwxrwx---    3 root     root           360 Nov  4 08:43 .
drwxr-xr-x    1 root     root           304 Nov  4 08:43 ..
-rw-r--r--    1 root     root           348 Nov  4 08:44 config
-rw-r--r--    1 root     root          4319 Nov  4 08:44 lqsdk.log
drwxr-xr-x    3 root     root           224 Nov  4 08:44 rootfs
root@OpenWrt:/#
root@OpenWrt:/# ls -la /lxc/lqsdk/rootfs/
drwxr-xr-x    3 root     root           224 Nov  4 08:44 .
drwxrwx---    3 root     root           360 Nov  4 08:43 ..
drwxr-xr-x    2 root     root           160 Nov  4 08:44 proc

# Information to attach
### run failed LOG
root@OpenWrt:/# lxc-start -n lqsdk -F
lxc-start: utils.c: open_without_symlink: 1575 No such file or directory - Error examining proc in /usr/lib/lxc/rootfs/proc
lxc-start: conf.c: mount_entry: 1731 No such file or directory - failed to mount 'proc' on '/usr/lib/lxc/rootfs/proc'
lxc-start: conf.c: lxc_setup: 3745 failed to setup the mount entries for 'lqsdk'
lxc-start: start.c: do_start: 702 failed to setup the container
lxc-start: sync.c: __sync_wait: 51 invalid sequence number 1. expected 2
lxc-start: start.c: __lxc_start: 1172 failed to spawn 'lqsdk'
lxc-start: lxc_start.c: main: 344 The container failed to start.
lxc-start: lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.
###

# config
root@OpenWrt:/# cat /lxc/lqsdk/config
lxc.network.type =empty
lxc.rootfs = /lxc/lqsdk/rootfs

lxc.network.flags =up
lxc.network.link =br-lan
lxc.network.name =eth1

\# fix for lxc-stop
lxc.haltsignal=SIGUSR1

\# Default mount entries
lxc.mount.entry = proc proc proc nodev,noexec,nosuid,create=dir 0 0

\#Include common configuration
lxc.include =/usr/share/lxc/config/openwrt.common.conf

### uci lxc config
root@OpenWrt:/# cat /etc/config/lxc
#
# lxc uci configuration
#

config lxc 'lxc'

        option url 'virtualwrt.org/containers/'

config common
        option image '/usr/share/lxc/templates/qsdk-lxc.tar.gz'

config LXC 'lqsdk'
        option haltsignal 'SIGUSR1'
        option include '/usr/share/lxc/config/openwrt.common.conf'
        option name 'lqsdk'
        option flags 'up'
        option link 'br-lan'
        option net_name 'eth1'
        option hwaddr 'empty'
        option entry 'tmpfs tmp tmpfs defaults'
        option net_type 'empty'

### Other
If need other information, ex, kernel config setting, please tell me.

**Comment by VicLin66** [comment]
Update more info.
Here is my debug command with lxc-start:
### lxc-start -n lqsdk -o debug -l trace

The log is in below:
### #debug log
root@OpenWrt:/lxc/lqsdk# cat /lxc/lqsdk/debug
      lxc-start 1604999900.415 INFO     lxc_start_ui - lxc_start.c:main:264 - using rcfile /lxc/lqsdk/config
      lxc-start 1604999900.416 WARN     lxc_cgfs - cgfs.c:lxc_cgroup_get_container_info:1100 - Not attaching to cgroup cpuset unknown to /lxc lqsdk
      lxc-start 1604999900.417 INFO     lxc_start - start.c:lxc_check_inherited:224 - closed inherited fd 4
      lxc-start 1604999900.421 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:708 - Attempting to set proc title to [lxc monitor] /lxc lqsdk
      lxc-start 1604999900.422 DEBUG    lxc_start - start.c:setup_signal_fd:262 - sigchild handler set
      lxc-start 1604999900.422 DEBUG    lxc_console - console.c:lxc_console_peer_default:536 - no console peer
      lxc-start 1604999900.422 INFO     lxc_start - start.c:lxc_init:454 - 'lqsdk' is initialized
      lxc-start 1604999900.423 DEBUG    lxc_start - start.c:__lxc_start:1145 - Not dropping cap_sys_boot or watching utmp
      lxc-start 1604999900.423 INFO     lxc_cgroup - cgroup.c:cgroup_init:65 - cgroup driver cgroupfs initing for lqsdk
      lxc-start 1604999900.423 INFO     lxc_start - start.c:lxc_check_inherited:224 - closed inherited fd 4
      lxc-start 1604999900.427 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/5f9d9d75c69c009b//lxc
      lxc-start 1604999900.430 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1921 - cgroup 'devices.deny' set to 'a'
      lxc-start 1604999900.430 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1921 - cgroup 'devices.allow' set to 'c 1:3 rwm'
      lxc-start 1604999900.430 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1921 - cgroup 'devices.allow' set to 'c 1:5 rwm'
      lxc-start 1604999900.430 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1921 - cgroup 'devices.allow' set to 'c 5:0 rwm'
      lxc-start 1604999900.430 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1921 - cgroup 'devices.allow' set to 'c 5:1 rwm'
      lxc-start 1604999900.430 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1921 - cgroup 'devices.allow' set to 'c 1:8 rwm'
      lxc-start 1604999900.430 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1921 - cgroup 'devices.allow' set to 'c 1:9 rwm'
      lxc-start 1604999900.430 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1921 - cgroup 'devices.allow' set to 'c 5:2 rwm'
      lxc-start 1604999900.430 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1921 - cgroup 'devices.allow' set to 'c 136:* rwm'
      lxc-start 1604999900.430 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1921 - cgroup 'devices.allow' set to 'c 254:0 rm'
      lxc-start 1604999900.430 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1921 - cgroup 'devices.allow' set to 'c 10:200 rwm'
      lxc-start 1604999900.430 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1921 - cgroup 'devices.allow' set to 'c 4:0 rwm'
      lxc-start 1604999900.430 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1921 - cgroup 'devices.allow' set to 'c 4:1 rwm'
      lxc-start 1604999900.430 INFO     lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1925 - cgroup has been setup
      lxc-start 1604999900.472 DEBUG    lxc_conf - conf.c:setup_rootfs:1295 - mounted '/lxc/lqsdk/rootfs' on '/usr/lib/lxc/rootfs'
      lxc-start 1604999900.473 INFO     lxc_conf - conf.c:setup_network:2441 - network has been setup
      lxc-start 1604999900.473 INFO     lxc_conf - conf.c:mount_autodev:1157 - Mounting container /dev
      lxc-start 1604999900.473 WARN     lxc_conf - conf.c:mount_autodev:1168 - No /dev in container.
      lxc-start 1604999900.473 WARN     lxc_conf - conf.c:mount_autodev:1169 - Proceeding without autodev setup
      lxc-start 1604999900.473 DEBUG    lxc_conf - conf.c:mount_entry:1788 - mounted 'proc' on '/usr/lib/lxc/rootfs/proc', type 'proc'
      lxc-start 1604999900.473 INFO     lxc_conf - conf.c:mount_file_entries:1975 - mount points have been setup
      lxc-start 1604999900.473 INFO     lxc_conf - conf.c:fill_autodev:1225 - Creating initial consoles under container /dev
      lxc-start 1604999900.473 ERROR    lxc_conf - conf.c:setup_ttydir_console:1536 - No such file or directory - failed with errno 2 to create /usr/lib/lxc/rootfs/dev/lxc
      lxc-start 1604999900.473 ERROR    lxc_conf - conf.c:lxc_setup:3782 - failed to setup the console for 'lqsdk'
      lxc-start 1604999900.473 ERROR    lxc_start - start.c:do_start:702 - failed to setup the container
      lxc-start 1604999900.473 ERROR    lxc_sync - sync.c:__sync_wait:51 - invalid sequence number 1. expected 2
      lxc-start 1604999900.549 ERROR    lxc_start - start.c:__lxc_start:1172 - failed to spawn 'lqsdk'
      lxc-start 1604999900.549 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
      lxc-start 1604999900.549 WARN     lxc_cgfs - cgfs.c:lxc_cgroup_get_container_info:1100 - Not attaching to cgroup cpuset unknown to /lxc lqsdk
      lxc-start 1604999905.554 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
      lxc-start 1604999905.554 ERROR    lxc_start_ui - lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 1604999905.554 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.
### #debug log end


Should I solve "Not attaching to cgroup cpuset unknown to /lxc lqsdk" first? But it's only waring.
The first error message int the log is:
### lxc-start** 1604999900.473 ERROR    lxc_conf - conf.c:setup_ttydir_console:1536 - No such file or directory - failed with errno 2 to create /usr/lib/lxc/rootfs/dev/lxc

**Comment by brauner** [comment]
(Note that LXC 1.* is out of support.)

This looks like the container's rootfs does not have a `dev/` directory. Create the `dev/` directory in the rootfs and try again.
