### ISSUE TITLE
Warnings with lxc exec in non-interactive mode

### ISSUE THREAD

**Issue by kautMaks** [lxc/lxc#3576]
# Required information
 
* Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-52-generic
   * LXC version: 4.0.4
   * LXD version: 4.7
   * Storage backend in use: dir

# Issue description

There are warnings in lxd container's log, while performing lxc exec in non-interactive mode:
```
lxc test 20201105190051.515 WARN     utils - utils.c:fix_stdio_permissions:1893 - Operation not permitted - Failed to chown standard I/O file descriptor 0 to uid -1 and gid 65534
lxc test 20201105190051.515 WARN     utils - utils.c:fix_stdio_permissions:1900 - Operation not permitted - Failed to chmod standard I/O file descriptor 0
lxc test 20201105190051.516 WARN     utils - utils.c:fix_stdio_permissions:1893 - Operation not permitted - Failed to chown standard I/O file descriptor 1 to uid -1 and gid 65534
lxc test 20201105190051.516 WARN     utils - utils.c:fix_stdio_permissions:1900 - Operation not permitted - Failed to chmod standard I/O file descriptor 1
lxc test 20201105190051.516 WARN     utils - utils.c:fix_stdio_permissions:1893 - Operation not permitted - Failed to chown standard I/O file descriptor 2 to uid -1 and gid 65534
lxc test 20201105190051.516 WARN     utils - utils.c:fix_stdio_permissions:1900 - Operation not permitted - Failed to chmod standard I/O file descriptor 2
lxc test 20201105190051.516 WARN     attach - attach.c:attach_child_main:879 - Failed to ajust stdio permissions
```

This pack of warnings appears for every lxc exec with non-interactive mode.
Such warnings appears also while exec performing by using api in code with ```Interactive: false``` in ContainerExecPost struct.

# Steps to reproduce

 1. lxc launch ubuntu:20.04 test
 2. lxc exec --mode="non-interactive" test -- hostname
 3. lxc info --show-log test

**Comment by stgraber** [comment]
Transferring to LXC as this is happening in liblxc.

@brauner should we silence this or is it legitimate.

**Comment by kautMaks** [comment]
Wow, @stgraber thanks for such fast reaction)

**Comment by brauner** [comment]
We should silence this. This is a result of the new devpts implementation we're using.
