### ISSUE TITLE
LXC containers that use 'bind mount' via NFS regulary freezed (stuck in refrigerator)

### ISSUE THREAD

**Issue by coobic** [lxc/lxc#3578]
# Required information
 * Distribution: Proxmox
 * Distribution version: 6.2 (latest)

 * The output of
   * `lxc-start --version`
4.0.3
   * `lxc-checkconfig`

Kernel configuration found at /boot/config-5.4.65-1-pve
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/memory
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/pids
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/freezer
/sys/fs/cgroup/blkio
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/rdma
/sys/fs/cgroup/devices

Cgroup v2 mount points:
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, loaded
Bridges: enabled, not loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities:

   * `uname -a`
Linux pve2 5.4.65-1-pve #1 SMP PVE 5.4.65-1 (Mon, 21 Sep 2020 15:40:22 +0200) x86_64 GNU/Linux

   * `cat /proc/self/cgroup`

12:devices:/user.slice
11:rdma:/
10:perf_event:/
9:blkio:/user.slice
8:freezer:/
7:net_cls,net_prio:/
6:pids:/user.slice/user-0.slice/session-917804.scope
5:cpu,cpuacct:/user.slice
4:hugetlb:/
3:cpuset:/
2:memory:/user.slice/user-0.slice/session-917804.scope
1:name=systemd:/user.slice/user-0.slice/session-917804.scope
0::/user.slice/user-0.slice/session-917804.scope

   * `cat /proc/1/mounts`

sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=123782592k,nr_inodes=30945648,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=24761720k,mode=755 0 0
rpool/ROOT/pve-1 / zfs rw,relatime,xattr,noacl 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup2 /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
none /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=32526 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
sunrpc /run/rpc_pipefs rpc_pipefs rw,relatime 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
rpool /rpool zfs rw,noatime,xattr,noacl 0 0
rpool/ROOT /rpool/ROOT zfs rw,noatime,xattr,noacl 0 0
rpool/data /rpool/data zfs rw,noatime,xattr,noacl 0 0
rpool/data/subvol-2236-disk-0 /rpool/data/subvol-2236-disk-0 zfs rw,noatime,xattr,posixacl 0 0
[skipped]
rpool/data/subvol-1130-disk-0 /rpool/data/subvol-1130-disk-0 zfs rw,noatime,xattr,posixacl 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /etc/pve fuse rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=24761716k,mode=700 0 0
192.168.168.10:/volume1/Backups /mnt/pve/NAS_backup nfs rw,relatime,vers=3,rsize=131072,wsize=131072,namlen=255,soft,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.168.10,mountvers=3,mountport=892,mountproto=udp,local_lock=none,addr=192.168.168.10 0 0
192.168.168.10:/volume2/Records /mnt/pve/NAS_records nfs rw,relatime,vers=3,rsize=131072,wsize=131072,namlen=255,soft,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.168.10,mountvers=3,mountport=892,mountproto=udp,local_lock=none,addr=192.168.168.10 0 0
rpool/data/subvol-2268-disk-0 /rpool/data/subvol-2268-disk-0 zfs rw,noatime,xattr,posixacl 0 0

# Issue description

LXC containers that use 'bind mount' (lxc.mount.entry) via NFS regulary freezed.
Stack trace for all pids are similar - they are in refrigerator call (attached).
All processes in container (except init) stuck in D state.

I think that this problem caused by lxc-freeze command or something near.
Proxmox storage replication (which we use) works like this: freeze the container (lxc-freeze) -> create snapshot (zfs) -> unfreeze the container -> copy zfs snapshot via ssh to another cluster node and so on.
Sometimes (one container of 30 per 3 days) then container (Asterisk in our case) is writing to bind mounted nfs folder (call record) - it stuck after lxc-freeze forever (all system calls is blocked for them forever) - only 'kill -KILL' or reboot entire host helps.

With 3.1.0-devel version of lxc and kernel 4.15 this configuration works prefectly for years.
We tried to use several kernels (5.3.18 more stable) and lxc versions (4.0.1, 4.0.2) - issue is persist.

We will be very grateful to the community for any advice and help in solving this problem.

# Steps to reproduce

It`s hard to reproduce problem in regular manner.
We create test cluster with 30 LXC containers (with Asterisk PBX) - one (random) container is stuck every 3-4 days.

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
[dmesg for 1130.txt](https://github.com/lxc/lxc/files/5497987/dmesg.for.1130.txt)
[stack trace.txt](https://github.com/lxc/lxc/files/5497997/stack.trace.txt)
[ps axf for 1130.txt](https://github.com/lxc/lxc/files/5497977/ps.axf.for.1130.txt)
 - [ ] the containers configuration file
[container config.txt](https://github.com/lxc/lxc/files/5498001/container.config.txt)

Linked topic: https://forum.proxmox.com/threads/storage-replication-regulary-hangs-after-upgrade.72690

**Comment by stgraber** [comment]
That's a kernel bug.

All that lxc-freeze/lxc-unfreeze do is toggle a flag on a cgroup. This seems to be causing the kernel to go completely crazy in your case with the process tree being somehow half frozen and leaving a bunch of tasks in a bad state.

If you must use this kernel, it looks like you should avoid using the freezer cgroup.

**Comment by coobic** [comment]
Many thanks for answer, @stgraber.
I will try to submit a bug to pve developers:
https://bugzilla.proxmox.com/show_bug.cgi?id=3117
