### ISSUE TITLE
 lxc-start fails to parse lxc-user-nic outputs

### ISSUE THREAD

**Issue by olvaffe** [lxc/lxc#3592]
I was trying out lxc 4.0.4 on a Debian-based machine.  When I started the container as a regular user, I got this error

    lxc-start alpine 20201205232643.679 INFO     network - network.c:lxc_create_network_unpriv_exec:2600 - Execing lxc-user-nic create /home/olv/.local/share/lxc alpine 5112 veth lxcbr0 (null)
    lxc-start alpine 20201205232643.732 ERROR    network - network.c:lxc_create_network_unpriv_exec:2646 - Argument list too long - Container side veth device name returned by lxc-user-nic is too long

I was able to work around it by renaming /usr/libexec/lxc/lxc-user-nic and creating a wrapper

    #!/bin/sh
    /usr/libexec/lxc/lxc-user-nic.bin $@ 2>/dev/null

It turned out that on my machine, lxc-user-nic output

    stderr: cmd/lxc_user_nic.c: 192: get_groupnames: Failed to get group members: 5000
    stdout: eth0:2:vethe0t0vv:5

lxc-start got confused by the stderr.

My machine has libnss-cache and indeed gid 5000 is in /etc/group.cache but not in /etc/group.

**Comment by brauner** [comment]
I think the issue might be that the number of members in the groups is larger than the buffer we allocated.
