### ISSUE TITLE
Changes to `src/lxc/conf.c:mount_autodev` from version 4.0.4 to 4.0.5 break containers with ZFS backing stores

### ISSUE THREAD

**Issue by ahesford** [lxc/lxc#3598]
# Issue description

After upgrading to version 4.0.5 as packaged in Void Linux (the build options were identical in both versions), containers created with a ZFS backing store cannot be started. The problem appears to be related to changes in `src/lxc/conf.c:mount_autodev` in commit ee8eeba881274bc4f4cd028255d019a4a41f73f3 (cc: @brauner), as evidenced by the debug log. However, I have *not* bisected the issue to this specific commit.

This is a regression with respect to version 4.0.4 and does not affect directory-backed containers.

I only use unprivileged containers, started as root, so I cannot say if the same issue affects privileged containers.

# Required information

- Distribution: Void Linux
- Distribution version: rolling release, up to date
- `lxc-start --version`: 4.0.5
- `lxc-checkconfig`: All items "enabled" EXCEPT: cgroup v1 systemd controller ("missing"); CONFIG_NF_NAT_IPV4 ("missing"); CONFIG_NF_NAT_IPV6 ("missing"). I am *not* using systemd-based containers and the output is identical between the functional 4.0.4 and the affected 4.0.5.
- `uname -a`: `Linux host.domain 5.9.13_1 #1 SMP 1607463776 x86_64 GNU/Linux`
- `cat /proc/self/cgroup`:
```
12:pids:/
11:hugetlb:/
10:net_prio:/
9:perf_event:/
8:net_cls:/
7:freezer:/
6:devices:/
5:memory:/
4:blkio:/
3:cpuacct:/
2:cpu:/
1:cpuset:/
0::/
```
   * `cat /proc/1/mounts`:
```
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
devtmpfs /dev devtmpfs rw,nosuid,noexec,size=8108656k,nr_inodes=2027164,mode=755,inode64 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev,noexec,inode64 0 0
tmpfs /run tmpfs rw,nosuid,nodev,noexec,mode=755,inode64 0 0
system/OS/void / zfs rw,relatime,xattr,posixacl 0 0
securityfs /sys/kernel/security securityfs rw,relatime 0 0
cgroup /sys/fs/cgroup tmpfs rw,relatime,mode=755,inode64 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/cpu cgroup rw,relatime,cpu 0 0
cgroup /sys/fs/cgroup/cpuacct cgroup rw,relatime,cpuacct 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,relatime,blkio 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,relatime,memory 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls cgroup rw,relatime,net_cls 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/net_prio cgroup rw,relatime,net_prio 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,relatime,pids 0 0
cgroup2 /sys/fs/cgroup/unified cgroup2 rw,relatime,nsdelegate 0 0
system/home /home zfs rw,relatime,xattr,posixacl 0 0
/dev/nvme0n1p1 /boot/efi vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev,relatime,inode64 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
/etc/autofs/auto.misc /misc autofs rw,relatime,fd=5,pgrp=1617,timeout=300,minproto=5,maxproto=5,indirect,pipe_ino=20253 0 0
-hosts /net autofs rw,relatime,fd=11,pgrp=1617,timeout=300,minproto=5,maxproto=5,indirect,pipe_ino=14650 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,relatime 0 0
```

# Steps to reproduce

1. Create a ZFS filesystem (*e.g.*, `system/lxc`, mounted at `/lxc`).
2. Set the following parameters in `/etc/lxc/lxc.conf` (from example filesystem):
```
lxc.lxcpath = /lxc
lxc.bdev.zfs.root = system/lxc
lxc.default_config = /etc/lxc/default.conf
```
3. Set the following parameters in `/etc/lxc/default.conf`:
```
lxc.idmap = u 0 1179648 65536
lxc.idmap = g 0 1179648 65536
```
4. Make sure that the subordinate UID and GID ranges in the `default.conf` are delegated to `root`.
5. Create a Void Linux container with a directory backing store:
```
sudo lxc-create -n test --template download -- -d voidlinux -r current -a amd64
```
6. Launch the test container:
```
sudo lxc-start -n test -F --logfile test.log --logpriority TRACE
```
7. Create a Void Linux container with a ZFS backing store:
```
sudo lxc-create -n test-zfs -B zfs --template download -- -d voidlinux -r current -a amd64
```
8. Launch the test container:
```
sudo lxc-start -n test-zfs -F --logfile test-zfs.log --logpriority TRACE
```

# Expected results

Both containers should launch without issue.

# Actual results

The directory-backed `test` container launches without issue, while the ZFS-backed `test-zfs` container fails to launch and indicates a failure to mount tmpfs on `/var/lxc/containers` in the function `src/lxc/conf.c:mount_autodev`. (See lines 229--234 in the attached `test-zfs.log`.)

# Details

Configuration and log file for the directory-backed `test` container, which starts successfully, are available at:
- [test.config.txt](https://github.com/lxc/lxc/files/5684217/test.config.txt)
- [test.log.txt](https://github.com/lxc/lxc/files/5684218/test.log.txt)

Configuration and log file for the ZFS-backed `test-zfs` container, which fails to start, are available at:
- [test-zfs.config.txt](https://github.com/lxc/lxc/files/5684219/test-zfs.config.txt)
- [test-zfs.log.txt](https://github.com/lxc/lxc/files/5684220/test-zfs.log.txt)

**Comment by brauner** [comment]
Thanks for reporting this! This should be fixed by #3601.
