### ISSUE TITLE
lxc-start faild when used with unprivileged busybox container

### ISSUE THREAD

**Issue by hitsjt** [lxc/lxc#3606]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution:Ubuntu
 * Distribution version:Ubuntu 18.04 
 * The output of
   * `lxc-start --version`:4.0.5(compiled by myself)
   * `lxc-checkconfig`
   bryan@bryan-ubuntu1804:~/LXC$ lxc-checkconfig

> LXC version 4.0.5
> Kernel configuration not found at /proc/config.gz; searching...
> Kernel configuration found at /boot/config-5.4.0-58-generic
> --- Namespaces ---
> Namespaces: enabled
> Utsname namespace: enabled
> Ipc namespace: enabled
> Pid namespace: enabled
> User namespace: enabled
> Network namespace: enabled
> 
> --- Control groups ---
> Cgroups: enabled
> 
> Cgroup v1 mount points: 
> /sys/fs/cgroup/systemd
> /sys/fs/cgroup/rdma
> /sys/fs/cgroup/net_cls,net_prio
> /sys/fs/cgroup/blkio
> /sys/fs/cgroup/hugetlb
> /sys/fs/cgroup/cpu,cpuacct
> /sys/fs/cgroup/memory
> /sys/fs/cgroup/cpuset
> /sys/fs/cgroup/devices
> /sys/fs/cgroup/perf_event
> /sys/fs/cgroup/pids
> /sys/fs/cgroup/freezer
> 
> Cgroup v2 mount points: 
> /sys/fs/cgroup/unified
> 
> Cgroup v1 clone_children flag: enabled
> Cgroup device: enabled
> Cgroup sched: enabled
> Cgroup cpu account: enabled
> Cgroup memory controller: enabled
> Cgroup cpuset: enabled
> 
> --- Misc ---
> Veth pair device: enabled, loaded
> Macvlan: enabled, not loaded
> Vlan: enabled, not loaded
> Bridges: enabled, loaded
> Advanced netfilter: enabled, not loaded
> CONFIG_NF_NAT_IPV4: missing
> CONFIG_NF_NAT_IPV6: missing
> CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
> CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
> CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
> CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
> FUSE (for use with lxcfs): enabled, not loaded
> 
> --- Checkpoint/Restore ---
> checkpoint restore: enabled
> CONFIG_FHANDLE: enabled
> CONFIG_EVENTFD: enabled
> CONFIG_EPOLL: enabled
> CONFIG_UNIX_DIAG: enabled
> CONFIG_INET_DIAG: enabled
> CONFIG_PACKET_DIAG: enabled
> CONFIG_NETLINK_DIAG: enabled
> File capabilities: 
> 
> Note : Before booting a new kernel, you can check its configuration
> usage : CONFIG=/path/to/config /usr/local/bin/lxc-checkconfig
> 

   * `uname -a`::Linux bryan-ubuntu1804 5.4.0-58-generic #64~18.04.1-Ubuntu SMP Wed Dec 9 17:11:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`

> 12:freezer:/
> 11:pids:/user.slice/user-1000.slice/user@1000.service
> 10:perf_event:/
> 9:devices:/user.slice
> 8:cpuset:/
> 7:memory:/
> 6:cpu,cpuacct:/
> 5:hugetlb:/
> 4:blkio:/
> 3:net_cls,net_prio:/
> 2:rdma:/
> 1:name=systemd:/user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
> 0::/user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service

   * `cat /proc/1/mounts`

> sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
> proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
> udev /dev devtmpfs rw,nosuid,relatime,size=1665880k,nr_inodes=416470,mode=755 0 0
> devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
> tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=338008k,mode=755 0 0
> /dev/sda1 / ext4 rw,relatime,errors=remount-ro 0 0
> securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
> tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
> tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
> tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
> cgroup /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
> cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
> pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
> cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
> cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
> cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
> cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
> cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
> cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
> cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
> cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
> cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
> cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
> cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
> systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=25,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=13157 0 0
> mqueue /dev/mqueue mqueue rw,relatime 0 0
> debugfs /sys/kernel/debug debugfs rw,relatime 0 0
> hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
> fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
> configfs /sys/kernel/config configfs rw,relatime 0 0
> /dev/loop0 /snap/gnome-calculator/748 squashfs ro,nodev,relatime 0 0
> /dev/loop1 /snap/core18/1944 squashfs ro,nodev,relatime 0 0
> /dev/loop2 /snap/gtk-common-themes/1506 squashfs ro,nodev,relatime 0 0
> /dev/loop5 /snap/gnome-characters/550 squashfs ro,nodev,relatime 0 0
> /dev/loop4 /snap/gnome-3-34-1804/36 squashfs ro,nodev,relatime 0 0
> /dev/loop3 /snap/gnome-characters/570 squashfs ro,nodev,relatime 0 0
> /dev/loop6 /snap/snapd/8542 squashfs ro,nodev,relatime 0 0
> /dev/loop8 /snap/core18/1885 squashfs ro,nodev,relatime 0 0
> /dev/loop7 /snap/gtk-common-themes/1514 squashfs ro,nodev,relatime 0 0
> /dev/loop11 /snap/snapd/10492 squashfs ro,nodev,relatime 0 0
> /dev/loop10 /snap/gnome-3-34-1804/60 squashfs ro,nodev,relatime 0 0
> /dev/loop9 /snap/gnome-logs/100 squashfs ro,nodev,relatime 0 0
> /dev/loop12 /snap/gnome-system-monitor/148 squashfs ro,nodev,relatime 0 0
> /dev/loop13 /snap/gnome-calculator/826 squashfs ro,nodev,relatime 0 0
> tmpfs /run/user/121 tmpfs rw,nosuid,nodev,relatime,size=338004k,mode=700,uid=121,gid=125 0 0
> tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=338004k,mode=700,uid=1000,gid=1000 0 0
> gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
> gvfsd-fuse /home/bryan/.gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=0,group_id=0 0 0
> /dev/fuse /home/bryan/.cache/doc fuse rw,nosuid,nodev,relatime,user_id=0,group_id=0 0 0

# Issue description

A brief description of what failed or what could be improved.
I use a normal user to run lxc-create as follows:
`lxc-create -t busybox -n busybox`
and then lxc-start to start it,but faild.

here is the log

> bryan@bryan-ubuntu1804:~/LXC$ cat busybox_non_pri5.log
> lxc-start busybox_non_pri 20201222071841.860 ERROR    utils - utils.c:safe_mount:1205 - No such file or directory - Failed to mount "/dev/ram0" onto "/usr/local/lib/lxc/rootfs/dev/ram0"
> lxc-start busybox_non_pri 20201222071841.860 ERROR    conf - conf.c:lxc_fill_autodev:1228 - No such device or address - Failed to bind mount host device node "/dev/tty" onto "tty"
> lxc-start busybox_non_pri 20201222071841.860 ERROR    conf - conf.c:lxc_setup:3396 - Failed to populate "/dev"
> lxc-start busybox_non_pri 20201222071841.860 ERROR    start - start.c:do_start:1218 - Failed to setup container "busybox_non_pri"
> lxc-start busybox_non_pri 20201222071841.863 ERROR    sync - sync.c:__sync_wait:36 - An error occurred in another process (expected sequence number 5)
> lxc-start busybox_non_pri 20201222071841.863 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:860 - Received container state "ABORTING" instead of "RUNNING"
> lxc-start busybox_non_pri 20201222071841.863 ERROR    lxc_start - tools/lxc_start.c:main:308 - The container failed to start
> lxc-start busybox_non_pri 20201222071841.863 ERROR    lxc_start - tools/lxc_start.c:main:311 - To get more details, run the container in foreground mode
> lxc-start busybox_non_pri 20201222071841.863 ERROR    lxc_start - tools/lxc_start.c:main:314 - Additional information can be obtained by setting the --logfile and --logpriority options
> lxc-start busybox_non_pri 20201222071841.864 ERROR    start - start.c:__lxc_start:1999 - Failed to spawn container "busybox_non_pri"

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l TRACE -o <logfile> `)
 - [ ] the containers configuration file

**Comment by brauner** [comment]
This looks like your compilation options aren't correctly set. Also make sure that `/usr/local/lib/lxc/rootfs/` exists. If you're using containers under the `/var/lib/lxc` path you need to specify `--lxcpath /var/lib/lxc` otherwise LXC will look at `/usr/local/lib/lxc` if you haven't set this specifically.
