### ISSUE TITLE
chown_mapped_root - lxc-usernsexec failed: execvpe: Permission denied

### ISSUE THREAD

**Issue by vikikumar** [lxc/lxc#3610]
Hi,

I am using lxc version 3.0.1 and I am facing the below error logs while trying to bring up my container in the un-privileged mode. Kindly help me understand the issue.
All helper binaries lxc_usernsexec are having the user and group permission for my container UID 1000 and GID 1000
The issue is resolving only if i have a map of linking container and root u 0 0 1 and g 0 0 1

lxc-start LXC_db_mon 19700101000027.926 DEBUG    lxc_conf - conf.c:chown_mapped_root:3044 - hostuid 1000
lxc-start LXC_db_mon 19700101000027.926 DEBUG    lxc_conf - conf.c:chown_mapped_root:3045 - hostgid 1000
lxc-start LXC_db_mon 19700101000027.926 DEBUG    lxc_conf - conf.c:chown_mapped_root:3051 - rootuid 100000
lxc-start LXC_db_mon 19700101000027.926 DEBUG    lxc_conf - conf.c:chown_mapped_root:3057 - rootgid 100000
lxc-start LXC_db_mon 19700101000027.926 DEBUG    lxc_conf - conf.c:chown_mapped_root:3078 - st_mode 8592
lxc-start LXC_db_mon 19700101000027.926 DEBUG    lxc_conf - conf.c:chown_mapped_root:3079 - -
lxc-start LXC_db_mon 19700101000027.926 DEBUG    lxc_conf - conf.c:chown_mapped_root:3080 - r
lxc-start LXC_db_mon 19700101000027.926 DEBUG    lxc_conf - conf.c:chown_mapped_root:3081 - w
lxc-start LXC_db_mon 19700101000027.926 DEBUG    lxc_conf - conf.c:chown_mapped_root:3082 - -
lxc-start LXC_db_mon 19700101000027.926 DEBUG    lxc_conf - conf.c:chown_mapped_root:3083 - -
lxc-start LXC_db_mon 19700101000027.926 DEBUG    lxc_conf - conf.c:chown_mapped_root:3084 - w
lxc-start LXC_db_mon 19700101000027.926 DEBUG    lxc_conf - conf.c:chown_mapped_root:3085 - -
lxc-start LXC_db_mon 19700101000027.927 DEBUG    lxc_conf - conf.c:chown_mapped_root:3086 - -
lxc-start LXC_db_mon 19700101000027.927 DEBUG    lxc_conf - conf.c:chown_mapped_root:3087 - -
lxc-start LXC_db_mon 19700101000027.927 DEBUG    lxc_conf - conf.c:chown_mapped_root:3088 - -
lxc-start LXC_db_mon 19700101000027.927 DEBUG    lxc_conf - conf.c:chown_mapped_root:3089 -
lxc-start LXC_db_mon 19700101000027.927 DEBUG    lxc_conf - conf.c:chown_mapped_root:3098 - trying to chown "/dev/pts/0" to 1000
lxc-start LXC_db_mon 19700101000027.927 DEBUG    lxc_conf - conf.c:chown_mapped_root:3099 - trying to chown "1000" to 1000
lxc-start LXC_db_mon 19700101000027.927 DEBUG    lxc_conf - conf.c:chown_mapped_root:3113 - map1 u:0:100000:1
lxc-start LXC_db_mon 19700101000027.927 DEBUG    lxc_conf - conf.c:chown_mapped_root:3120 - map2 u:1000:1000:1
lxc-start LXC_db_mon 19700101000027.927 DEBUG    lxc_conf - conf.c:chown_mapped_root:3127 - map3 g:0:100000:1
lxc-start LXC_db_mon 19700101000027.927 DEBUG    lxc_conf - conf.c:chown_mapped_root:3135 - map4 g:1000:101000:1
lxc-start LXC_db_mon 19700101000027.927 DEBUG    lxc_conf - conf.c:chown_mapped_root:3142 - map5 g:1000:1000:1
lxc-start LXC_db_mon 19700101000028.104 ERROR    lxc_conf - conf.c:chown_mapped_root:3159 - lxc-usernsexec failed: execvpe: Permission denied
lxc-start LXC_db_mon 19700101000028.104 ERROR    terminal - terminal.c:lxc_terminal_map_ids:1194 - Failed to chown terminal "/dev/pts/0"
lxc-start LXC_db_mon 19700101000028.104 ERROR    lxc_start - start.c:lxc_init:846 - Failed to chown console

My lxc config file
===========

lxc.uts.name = db_mon
#root filesystem
lxc.rootfs.path = /tmp/lxc/lxc-db_mon/rootfs

lxc.net.0.type  = veth
lxc.net.0.link  = br0
lxc.net.0.flags = up
lxc.net.0.ipv4.address  = 1.2.3.8/24
lxc.net.0.hwaddr = 4a:49:43:49:79:bf
lxc.net.0.name  = eth1
lxc.idmap = u 0 100000 65536
lxc.idmap = g 0 100000 65536
lxc.init.uid = 1000
lxc.init.gid = 1000

/etc/subuid 100000 65536

/etc/subgid 100000 65536

Network: /et/lxc/lxc-usernet uDbMon veth br0 1

Thank you

**Comment by brauner** [comment]
Please try this with a rather recent version of LXC such as >= 4.0.4 and report back. These codepaths have changed significantly!

**Comment by brauner** [comment]
Make sure that the `lxc-usernsexec` binary is located on a filesystem that is _not_ `nosuid`.
