### ISSUE TITLE
LXC test "lxc-test-usernsexec" failed with ERRORS: myuidgid test

### ISSUE THREAD

**Issue by Cypresslin** [lxc/lxc#3611]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.10 Groovy
 * The output of
   * `lxc-start --version` - 4.0.4
   * `lxc-checkconfig` - https://pastebin.ubuntu.com/p/WQJKX64s3T/
   * `uname -a` - Linux curly 5.8.0-33-generic #36-Ubuntu SMP Wed Dec 9 09:14:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup` 
     * > 12:blkio:/user.slice
11:memory:/user.slice/user-1000.slice/session-212.scope
10:perf_event:/
9:rdma:/
8:freezer:/
7:devices:/user.slice
6:net_cls,net_prio:/
5:cpu,cpuacct:/user.slice
4:pids:/user.slice/user-1000.slice/session-212.scope
3:cpuset:/
2:hugetlb:/
1:name=systemd:/user.slice/user-1000.slice/session-212.scope
0::/user.slice/user-1000.slice/session-212.scope

   * `cat /proc/1/mounts`
     * > sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,noexec,relatime,size=969216k,nr_inodes=242304,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,noexec,relatime,size=203068k,mode=755 0 0
/dev/vda1 / ext4 rw,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,size=4096k,nr_inodes=1024,mode=755 0 0
cgroup2 /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,clone_children,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
none /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb,clone_children 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids,clone_children 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct,clone_children 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio,clone_children 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices,clone_children 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer,clone_children 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma,clone_children 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event,clone_children 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory,clone_children 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio,clone_children 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=18067 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
tracefs /sys/kernel/tracing tracefs rw,nosuid,nodev,noexec,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
/dev/loop0 /snap/core18/1932 squashfs ro,nodev,relatime 0 0
/dev/loop1 /snap/lxd/18251 squashfs ro,nodev,relatime 0 0
/dev/loop2 /snap/snapd/9721 squashfs ro,nodev,relatime 0 0
tmpfs /run/snapd/ns tmpfs rw,nosuid,nodev,noexec,relatime,size=203068k,mode=755 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
/dev/loop3 /snap/snapd/10492 squashfs ro,nodev,relatime 0 0
/dev/loop4 /snap/core18/1944 squashfs ro,nodev,relatime 0 0
/dev/loop5 /snap/lxd/18772 squashfs ro,nodev,relatime 0 0
nsfs /run/snapd/ns/lxd.mnt nsfs rw 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=203064k,nr_inodes=50766,mode=700,uid=1000,gid=1000 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0

# Issue description

The lxc test failed with:
>  FAIL: lxc-tests: lxc-test-usernsexec (2s)
>  \---
  as test-userns executing /tmp/autopkgtest.6YF1of/build.sBb/src/src/tests/lxc-test-usernsexec 
  uid=1001 gid=1001 name=test-userns subuid=165536 subgid=165536 ver=1:4.0.4-0ubuntu3
  lxc-utils=1:4.0.4-0ubuntu3 kver=5.8.0-33-generic
  USERNSEXEC=lxc-usernsexec
  nouidgid: PASS
  myuidgid: FAIL - runtest failed 1
    $ lxc-usernsexec -mu:0:1001:1 -mg:0:1001:1 -- /tmp/autopkgtest.6YF1of/build.sBb/src/src/tests/lxc-test-usernsexec inside f0
    lxc 20201230072135.386 ERROR    utils - utils.c:lxc_setgroups:1363 - Operation not permitted - Failed to setgroups()
    kid 112371 is gone 1
  subuidgid: PASS
  bothsets: PASS
  mismatch: PASS
  ERRORS: myuidgid
> \ ---
>  PASS: lxc-tests: lxc-test-utils (0s)
>  
>  SUMMARY: pass=43, fail=1, ignored=1

# Steps to reproduce

 1. Install automake, autopkgtest, build-essential, cloud-image-utils, dh-autoreconf, texinfo, lxc, liblxc1
 2. Run command "autopkgtest lxc -- null" (We need to specify proxy in kernel team lab) 

# Information to attach
This issue can be found on both Bare-metals / KVMs
https://bugs.launchpad.net/ubuntu-kernel-tests/+bug/1900662
This issue can be found on Groovy / Hirsute (passed with Focal 5.8)

**Comment by brauner** [comment]
This is already fixed in

```
commit 3f6e5c831eebf46e4e755bbc1bfbf4c9e1fb0d91
Author: Christian Brauner <christian.brauner@ubuntu.com>
Date:   Thu Sep 17 17:44:26 2020 +0200 (origin/2020-09-17/fixes_2, 2020-09-17/fixes_2)

    lxc-usernsexec: setgroups() similar to other places shouldn't fail on EPERM

    FAIL: lxc-tests: lxc-test-usernsexec (1s)
    ---
    as test-userns executing /tmp/autopkgtest.waGEXj/build.Hm3/src/src/tests/lxc-test-usernsexec
    uid=1001 gid=1001 name=test-userns subuid=165536 subgid=165536 ver=1:4.0.4-0ubuntu3
    lxc-utils=1:4.0.4-0ubuntu3 kver=5.8.0-19-generic
    USERNSEXEC=lxc-usernsexec
    nouidgid: PASS
    myuidgid: FAIL - runtest failed 1
      $ lxc-usernsexec -mu:0:1001:1 -mg:0:1001:1 -- /tmp/autopkgtest.waGEXj/build.Hm3/src/src/tests/lxc-test-usernsexec inside f0
      lxc 20200914222824.562 ERROR    utils - utils.c:lxc_setgroups:1363 - Operation not permitted - Failed to setgroups()
      kid 73112 is gone 1
    subuidgid: PASS
    bothsets: PASS
    mismatch: PASS
    ERRORS: myuidgid
    ---

    Reported-by: Seth Forshee <seth.forshee@canonical.com>
    Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>
```

**Comment by brauner** [comment]
@stgraber will need to release a new stable version which will contain this fix.
