### ISSUE TITLE
conf.c: HAVE_LIBCAP

### ISSUE THREAD

**Issue by thedolphin** [lxc/lxc#3612]
include of sys/capabilities.h depends on HAVE_LIBCAP
but CAP_NET_ADMIN is used later regardless of HAVE_LIBCAP and this leads to error

```
conf.c:654:38: error: use of undeclared identifier 'CAP_NET_ADMIN'
        bool has_cap_net_admin = in_caplist(CAP_NET_ADMIN, &conf->caps);
```

**Comment by stgraber** [comment]
Looks like an easy fix for anyone who wants it.
I think it may be a recent regression too.
