### ISSUE TITLE
lxc-test-device-add-remove test failed on Bionic 5.4

### ISSUE THREAD

**Issue by Cypresslin** [lxc/lxc#3616]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: Ubuntu Bionic
 * The output of
   * `lxc-start --version` - 3.0.3
   * `lxc-checkconfig` - https://pastebin.ubuntu.com/p/F8hptG5THT/
   * `uname -a` - Linux selfprovisioned-phlin-lxc 5.4.0-1034-gcp #37~18.04.1-Ubuntu SMP Wed Jan 6 19:44:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`
> 12:hugetlb:/
11:devices:/user.slice
10:blkio:/user.slice
9:pids:/user.slice/user-1007.slice/session-7.scope
8:net_cls,net_prio:/
7:freezer:/user/jenkins/0
6:cpu,cpuacct:/user.slice
5:rdma:/
4:perf_event:/
3:memory:/user/jenkins/0
2:cpuset:/
1:name=systemd:/user.slice/user-1007.slice/session-7.scope
0::/user.slice/user-1007.slice/session-7.scope
   * `cat /proc/1/mounts`
>sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=1864212k,nr_inodes=466053,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=377208k,mode=755 0 0
/dev/sda1 / ext4 rw,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,clone_children,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory,clone_children 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event,clone_children 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma,clone_children 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct,clone_children 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer,clone_children 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio,clone_children 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids,clone_children 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio,clone_children 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices,clone_children 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb,clone_children 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=27,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14128 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
/dev/sda15 /boot/efi vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
/dev/loop0 /snap/snapd/10707 squashfs ro,nodev,relatime 0 0
/dev/loop1 /snap/core18/1944 squashfs ro,nodev,relatime 0 0
/dev/loop2 /snap/google-cloud-sdk/163 squashfs ro,nodev,relatime 0 0
tmpfs /run/user/1007 tmpfs rw,nosuid,nodev,relatime,size=377204k,mode=700,uid=1007,gid=1008 0 0

# Issue description

One of the test failed:
FAIL: lxc-tests: lxc-test-device-add-remove (0s)

This issue does not exist in Focal 5.4, just Bionic 5.4

# Steps to reproduce
 1. Run the lxc test with `autopkgtest lxc -- null`
 2. You will see:
>   FAIL: lxc-tests: lxc-test-device-add-remove (0s)
  \---
  Adding /dev/network_latency to the container (device_add_remove_test) failed...
  \---

# Information to attach
  - https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1884024

**Comment by brauner** [comment]
This has been fixed a long while ago:

```
commit 920cbb00268ce50d1306daebb74871f66583a46c
Author: Christian Brauner <christian.brauner@ubuntu.com>
Date: Mon Nov 18 15:08:22 2019 +0100

    tests: use /dev/loop-control instead of /dev/network_latency

    BugLink: https://bugs.launchpad.net/bugs/1848587

    The latter device has been removed apparently.
```

which is also backported to stable-3.0. So @stgraber needs to cut a new stable point release.
