### ISSUE TITLE
container can suspend the parent system via systemctl without restrictions

### ISSUE THREAD

**Issue by daniel-baumann** [lxc/lxc#362]
Kenshi Muto reports in https://bugs.debian.org/770901:

---snip---
I noticed lxc container could suspend parent system by just typing
"systemctl suspend" when both parent system and container used systemd.
(Yes, usually we don't want this behavior...)

# lxc-create -n mylxc -t debian -- -r jessie
# lxc-start -n mylxc
mylxc# systemctl suspend
(parent system goes suspend)

I'm not sure but CAP_BLOCK_SUSPEND seems a capability for the restriction
likely. Even so, lxc 1.0.6-3 doesn't support block_suspend for cap.drop.
---snap---

**Comment by stgraber** [comment]
Closing this bug since LXC does provide an apparmor profile which prevents that very issue.
