### ISSUE TITLE
lxc-start creates /dev with wrong permissions if invoked with restrictive umask

### ISSUE THREAD

**Issue by daniel-baumann** [lxc/lxc#363]
Drake Wilson reports in https://bugs.debian.org/770684

---snip---
Recently I started a container via « sudo lxc-start … » without
configuring sudo to reset the umask first.  I subsequently found
SSHing into the container was slightly broken and user sessions were
hanging in weird ways.  This turned out to be because /dev had been
created with mode 0750 instead of the proper 0755; the problem went
away when I explicitly reset the umask from 0027 to 0022.  It would be
nice if LXC programs that deal with files in the container either
reset the umask themselves or explicitly chmodded created files to
avoid causing problems when so invoked.
---snap---

**Comment by evgeni** [comment]
this is fixed in 1.1.x

@stgraber / @brauner please close :)

**Comment by segdy** [comment]
Hi,

Can you tell me what you did in order to fix that?
I use Debian lenny which does not seem to have backported this fix.
I would like to "backport" it myself.

Thanks!
