### ISSUE TITLE
autoconf: compilation failure on archlinux: -Werror=strict-prototype -Werror=old-style-definition

### ISSUE THREAD

**Issue by r10r** [lxc/lxc#3630]
# Required information

 * Distribution: archlinux
 * LXC version: heads/master-0-g609d2b2e6
 
# Issue description

@vrubiolo Noticed that lxc doesn't compile on latest archlinux.  https://github.com/Drachenfels-GmbH/crio-lxc/issues/6#issuecomment-765561674
I discovered that this happens after upgrading autoconf  from `2.69-7` to `2.70-1`.
All warnings are treated as errors (full logs are attached):

```bash
log.c:85:20: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
   85 | static const char *lxc_log_get_container_name()
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
log.c: In function ‘lxc_log_get_container_name’:
log.c:85:20: error: old-style function definition [-Werror=old-style-definition]
log.c: In function ‘lxc_log_options_no_override’:
log.c:817:13: error: old-style function definition [-Werror=old-style-definition]
  817 | inline void lxc_log_options_no_override()
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [Makefile:4496: liblxc_la-log.lo] Error 1
make[3]: Leaving directory '/root/test/lxc/src/lxc'
make[2]: *** [Makefile:432: all-recursive] Error 1
make[2]: Leaving directory '/root/test/lxc/src'
make[1]: *** [Makefile:371: all] Error 2
make[1]: Leaving directory '/root/test/lxc/src'
make: *** [Makefile:529: all-recursive] Error 1
```

# Steps to reproduce

```bash
[root@k8s-cluster2-controller lxc]# ./autogen.sh > autogen.sh.log 2>&1
[root@k8s-cluster2-controller lxc]# ./configure --enable-bash=no --enable-tools=no   --enable-commands=no --enable-seccomp=yes   --enable-capabilities=yes --enable-apparmor=yes > configure.log 2>&1
[root@k8s-cluster2-controller lxc]# make > make.log 2>&1
```

# Solution

*  either downgrade autoconf from `2.70-1` to `2.69-7`
*  or prepend `CFLAGS="-Wno-error=strict-prototypes -Wno-error=old-style-definition"` to `configure.sh`

I wonder if the relevant warnings should be fixed in the code or if the relevant CFLAGS should be put in `configure.ac`.

# Information to attach

[autogen.sh.log](https://github.com/lxc/lxc/files/5859844/autogen.sh.log)
[configure.log](https://github.com/lxc/lxc/files/5859843/configure.log)
[config.log](https://github.com/lxc/lxc/files/5859845/config.log)
[make.log](https://github.com/lxc/lxc/files/5859842/make.log)
[installed_packages.log](https://github.com/lxc/lxc/files/5859853/installed_packages.log)

**Comment by brauner** [comment]
#3631 should fix this.

**Comment by brauner** [comment]
Thanks for the report!

**Comment by r10r** [comment]
Works. Thanks for the quick fix!
