### ISSUE TITLE
How to configure CAN socket passthrough to container ?

### ISSUE THREAD

**Issue by jackshu** [lxc/lxc#3635]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution:
 * Distribution version:
 * The output of
   * `lxc-start --version`
   * `lxc-checkconfig`
   * `uname -a`
   * `cat /proc/self/cgroup`
   * `cat /proc/1/mounts`

# Issue description

A brief description of what failed or what could be improved.

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l TRACE -o <logfile> `)
 - [ ] the containers configuration file

**Comment by brauner** [comment]
What exactly are you trying to do?

**Comment by jackshu** [comment]
Host OS：
[root@localhost]# lxc device config：
devices:
  can0:
    name: can0
    nictype: physical
    parent: can0
    type: nic

Container OS:
[root@localhost]# ifcofig can0
can0: flags=193<UP,RUNNING,NOARP>  mtu 16
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 10  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 41 

[root@localhost]# candump can0
**socket: Address family not supported by protocol**

**Comment by mihalicyn** [comment]
If it's still actual, please show us the output from `strace -f candump can0`.

As issue was created more than 3 years ago, I'm closing it for now. Feel free to reopen!
