### ISSUE TITLE
pass the FDs of the container namespaces to the lxc.net.[i].script.down hooks

### ISSUE THREAD

**Issue by danmilon** [lxc/lxc#3667]
# Feature request description

When a container that has a network mount (e.g. nfs) stops and cleans up the mnt namespace, it cannot unmount cleanly because the network has been already taken down. This prolongs the time it takes to stop by a few minutes (eventually it times out).

To workaround this I use the `lxc.net.[i].script.down` hook to cleanup the mnt namespace, but unfortunately the FDs of the container namespaces are not passed to that hook, only to the `.stop` hook (but that's too late), so I resort to ugly hacks by scanning the FDs of the lxc-start process to find the mnt namespace FD.

Would it be possible to set the `LXC_[NAMESPACE IDENTIFIER]_NS` environmental variables before the network down script runs, in order to accommodate this use case?

**Comment by brauner** [comment]
Seems fine to me. @stgraber, @Blub, @hallyn ?

**Comment by stgraber** [comment]
No objection

**Comment by hallyn** [comment]
+1

**Comment by brauner** [comment]
@danmilon should be available in #3671
