### ISSUE TITLE
apparmor: lxc doesn't support new /proc/self/attr/apparmor/... setup

### ISSUE THREAD

**Issue by cyphar** [lxc/lxc#3685]
This is related to opencontainers/runc#2801 and docker/for-linux#1199, and is a heads-up since it looks like you have the same bug we did.

It turns out that with certain kernel configurations (such as the one enabled by Arch recently -- where `CONFIG_LSM` has `bpf` as the last entry), the `/proc/self/attr` files no longer refer to AppArmor and instead operate on the BPF LSM. It turns out that some time ago, "major" LSMs got their own subdirectories (`/proc/self/attr/apparmor/...`) which is what we should be using when writing process labels. I believe the same thing goes for SELinux but I haven't tried. [It turns out that `/proc/self/attr/...` files are "legacy"](https://www.kernel.org/doc/html/latest/admin-guide/LSM/index.html):

> Process attributes associated with “major” security modules should be accessed and maintained using the special files in `/proc/.../attr`. A security module may maintain a module specific subdirectory there, named after the module. `/proc/.../attr/smack` is provided by the Smack security module and contains all its special files. The files directly in `/proc/.../attr` remain as legacy interfaces for modules that provide subdirectories.

As far as I can tell, `src/lxc/lsm/apparmor.c` only references `/proc/self/attr/` files so it should have the same issue as us. (You use `/proc/self/attr/current` while we use `/proc/self/attr/exec`, but I believe it's the same issue either way).

I can send a patch for this if you'd like -- it'll look something like opencontainers/runc#2803.

**Comment by brauner** [comment]
Please do send a patch and thank you very much!
