### ISSUE TITLE
lxc-monitor causes lxc-monitord.log to be created & endlessly written

### ISSUE THREAD

**Issue by foresto** [lxc/lxc#3747]
# Required information

 * Distribution: Ubuntu 20.04.2 LTS
 * The output of
   * `lxc-start --version`  `4.0.6` (problem also exists in 4.0.2 and 3.0.4)
   * `lxc-checkconfig`  irrelevant, I think
   * `uname -a`  `Linux myhost 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

# Issue description

Running lxc-monitor always causes a log file called lxc-monitord.log to be written. This file grows endlessly, becoming rather large over the course of months, and needlessly contributing to SSD write wear.

This happens even when I don't pass any log options to lxc-monitor (which claims its default is no log), and even with `-o /dev/null` and/or `-l FATAL`. The file appears to belong to lxc-monitord, which doesn't seem to have any option for disabling logging.

I first noticed the problem in lxc 3.0.4 and reported it [on the mailing list](https://lists.linuxcontainers.org/pipermail/lxc-users/2020-April/015208.html) last year.

# Steps to reproduce

 1. Configure an account for unprivileged containers, noting the lxc.lxcpath in ~/.config/lxc/lxc.conf . [This step might be unnecessary; I don't use privileged containers.]
 2. Start lxc-monitor.
 3. Notice that a file called lxc-monitord.log has been created in the lxc.lxcpath directory.
 4. Over time and container use, watch that file grow endlessly.

# Example snippet from the unwanted log file

    lxc-monitord 20210328221750.111 INFO     monitor - monitor.c:lxc_monitor_sock_name:191 - Using monitor socket name "lxc/bfa3b48b08475425//home/ubuntu/lxc" (length of socket name 37 must be <= 105)
    lxc-monitord 20210328221750.111 NOTICE   lxc_monitord - cmd/lxc_monitord.c:main:424 - lxc-monitord with pid 28768 is now monitoring lxcpath /home/ubuntu/lxc
    lxc-monitord 20210328221750.111 INFO     lxc_monitord - cmd/lxc_monitord.c:lxc_monitord_sock_accept:212 - Accepted client file descriptor 4. Number of accepted file descriptors is now 1
    lxc-monitord 20210328221812.833 INFO     lxc_monitord - cmd/lxc_monitord.c:lxc_monitord_sock_accept:212 - Accepted client file descriptor 4. Number of accepted file descriptors is now 1
    lxc-monitord 20210328221812.833 NOTICE   lxc_monitord - cmd/lxc_monitord.c:main:435 - No remaining clients. lxc-monitord is exiting
    lxc-monitord 20210328221812.833 INFO     monitor - monitor.c:lxc_monitor_sock_name:191 - Using monitor socket name "lxc/bfa3b48b08475425//home/ubuntu/lxc" (length of socket name 37 must be <= 105)

**Comment by brauner** [comment]
I think we should just remove the log since the tool is rarely used and it's not that helpful for debugging anyway.
