### ISSUE TITLE
Compilation failure with warnings treated as errors

### ISSUE THREAD

**Issue by 1div0** [lxc/lxc#3752]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Fedora
 * Distribution version: 33 with the GCC 11.0.0 from F34

# Issue description

Failed to compile with warnings treated as errors

```
../../../../src/lxc/string_utils.c: In function ‘parse_byte_size_string’:
../../../../src/lxc/string_utils.c:939:37: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  939 |                 *(end - suffix_len) = '\0';
      |                 ~~~~~~~~~~~~~~~~~~~~^~~~~~
../../../../src/lxc/string_utils.c:905:14: note: at offset -1 into destination object ‘dup’ of size 22
  905 |         char dup[INTTYPE_TO_STRLEN(long long int)] = {0};
      |              ^~~
../../../../src/lxc/string_utils.c:905:14: note: at offset -1 into destination object ‘dup’ of size 22
../../../../src/lxc/string_utils.c:905:14: note: at offset -2 into destination object ‘dup’ of size 22
../../../../src/lxc/string_utils.c:937:17: error: ‘memcpy’ offset 0 is out of the bounds [0, 0] [-Werror=array-bounds]
  937 |                 memcpy(suffix, end - suffix_len, suffix_len);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [Makefile:4433: string_utils.o] Error 1
```

# Steps to reproduce

 1. ./configure --prefix=/usr/local/debug --libdir=/usr/local/debug/lib64 --enable-shared --disable-static
 2. make
 3. boom

**Comment by brauner** [comment]
Can you reproduce this with current master/main or stable-4.0 branch? This function has been rewritten just a few days ago and should be fixed.

**Comment by evverx** [comment]
@brauner it's reproducible with `master`. Though to judge from https://gcc.gnu.org/gcc-11/changes.html GCC-11 hasn't been released yet so I'd wait for it to be stabilized and released. If there's a real bug lurking there I'm pretty sure OSS-Fuzz will report it.

**Comment by 1div0** [comment]
Just updated to

gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-11.0.1-20210324/obj-x86_64-redhat-linux/isl-install --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.0.1 20210324 (Red Hat 11.0.1-0) (GCC) 

The same result.

**Comment by 1div0** [comment]
Thank you.
