### ISSUE TITLE
ls --fancy by default

### ISSUE THREAD

**Issue by daniel-baumann** [lxc/lxc#377]
similar to lxc-start with the -d option, lxc commands should default to the convenient mode, therefore.. please make lxc-ls have the --fancy option implicit default and for those who want to use lxc-ls in scripts or otherwise require the short option, have them use lxc-ls --short.

**Comment by stgraber** [comment]
Seems reasonable to me, maybe for 1.2.

**Comment by lyrixx** [comment]
:+1:

**Comment by Kentoseth** [comment]
@brauner:

Is #748 a solution to this issue? I speed-read through it and understood that quite a few other changes were added to that issue/feature.

**Comment by brauner** [comment]
@Kentoseth, ultimately we did decide against fancy by default to not break expectations of existing users. Afaik, I don't think that has changed (@stgraber).

**Comment by stgraber** [comment]
Right, a lot of things seem to wrap lxc-ls, so changing the default output would break people.
