### ISSUE TITLE
Failed to parse config file at line "lxc.net.0.veth.vlan.id = ..."

### ISSUE THREAD

**Issue by justablob** [lxc/lxc#3786]
# Required information

 * Distribution: Alpine Linux
 * Distribution version: 3.14.0_alpha20210212
 * The output of
   * `lxc-start --version`: 4.0.6
   * `lxc-checkconfig`: https://hatebin.com/toiioumzto
   * `uname -a`: `Linux alastor 5.10.27-0-lts #1-Alpine SMP Wed, 31 Mar 2021 06:03:59 +0000 x86_64 Linux`
   * `cat /proc/self/cgroup`: https://hatebin.com/kkyzamqaiv
   * `cat /proc/1/mounts`: https://hatebin.com/zibfvldfbn

# Issue description

Trying to use `lxc.net.0.veth.vlan.id` results in an error: 
```
lxc-start: jellyfin: parse.c: lxc_file_for_each_line_mmap: 131 Failed to parse config file "/var/lib/lxc/jellyfin/config" at line "lxc.net.0.veth.vlan.id = 17"
Failed to load config for jellyfin
lxc-start: jellyfin: tools/lxc_start.c: main: 242 Failed to create lxc_container
```

# Steps to reproduce

 1. Create an Alpine container on an Alpine host
 2. Configure the network like I did
 3. Watch it not start

# Information to attach

 - dmesg: nothing relevant
 - container log: https://hatebin.com/vkqhtvwaew
 - container config: https://hatebin.com/bwbgwgytdj

**Comment by brauner** [comment]
Hm, `lxc.net.[idx].veth.vlan.id` and `lxc.net.[idx].veth.vlan.tagged.id` were added after `4.0` was released and so is only available in newer LXC release. :(

**Comment by justablob** [comment]
@brauner From what I can see, 4.0.6 is the latest version, which I'm using

**Comment by stgraber** [comment]
4.0.6 is a bugfix release for 4.0.
You won't find new features in those, so any new feature added after 4.0 will be in 4.1.

**Comment by justablob** [comment]
Oh, alright. Didn't know that. Guess that means I'll be waiting a few months. I did find a solution in the meantime, to connect the host bridge to the container and configure the VLANs inside the container, if anyone's wondering. Obviously won't work for untrusted containers.
