### ISSUE TITLE
Two typos in gentoo template for auth_key

### ISSUE THREAD

**Issue by nougad** [lxc/lxc#379]
in https://github.com/lxc/lxc/blob/master/templates/lxc-gentoo.in#L644 the file name which should be `cat` is missing (should be `"${auth_key}"`

in https://github.com/lxc/lxc/blob/master/templates/lxc-gentoo.in#L778 the parameter is called `auth_key` but the case statement uses `--auth-key` (with `-`).

    --- /usr/share/lxc/templates/lxc-gentoo 2014-12-15 21:49:41.383135672 +0100
    +++ /tmp/lxc-gentoo     2014-12-15 21:52:16.000064629 +0100
    @@ -641,7 +641,7 @@
         if [[ -r "${auth_key}" ]]; then
             printf " deploying auth_key %s for user %s ...\n" "${auth_key}" "${user}"
             mkdir -p "${rootfs}/${auth_home}/.ssh"
    -        cat "${auth_key}" >> "${rootfs}/${auth_home}/.ssh/authorized_keys"
    +        cat >> "${rootfs}/${auth_home}/.ssh/authorized_keys"
             chroot "${rootfs}" chown "${user}:" "${auth_home}/.ssh/authorized_keys"
             printf "  => inserted public key in %s/.ssh/authorized_keys\n" "${auth_home}"
             [[ -z "${forced_password}" ]] && unset password
    @@ -775,7 +775,7 @@
     password="toor"
     tty=1
     settings="common"
    -options=$(getopt -o hp:n:a:FcPv:t:S:u:w:s:m: -l help,rootfs:,path:,name:,arch:,flush-cache,cache-only,private-portage,variant:,portage-dir:,tarball:,auth-key:,user:,autologin,password:,settings:,mirror:,tty: -- "$@")
    +options=$(getopt -o hp:n:a:FcPv:t:S:u:w:s:m: -l help,rootfs:,path:,name:,arch:,flush-cache,cache-only,private-portage,variant:,portage-dir:,tarball:,auth_key:,user:,autologin,password:,settings:,mirror:,tty: -- "$@")
     
     eval set -- "$options"

**Comment by stgraber** [comment]
Would you mind sending an updated patch or a pull request with that change and the required Signed-off-by line (per CONTRIBUTING)?

Thanks

**Comment by nougad** [comment]
Hi @stgraber here the updated patch:

    --- /usr/share/lxc/templates/lxc-gentoo 2014-12-15 21:49:41.383135672 +0100
    +++ /tmp/lxc-gentoo     2014-12-15 21:52:16.000064629 +0100
    @@ -641,7 +641,7 @@
         if [[ -r "${auth_key}" ]]; then
             printf " deploying auth_key %s for user %s ...\n" "${auth_key}" "${user}"
             mkdir -p "${rootfs}/${auth_home}/.ssh"
    -        cat >> "${rootfs}/${auth_home}/.ssh/authorized_keys"
    +        cat "${auth_key}" >> "${rootfs}/${auth_home}/.ssh/authorized_keys"
             chroot "${rootfs}" chown "${user}:" "${auth_home}/.ssh/authorized_keys"
             printf "  => inserted public key in %s/.ssh/authorized_keys\n" "${auth_home}"
             [[ -z "${forced_password}" ]] && unset password
    @@ -775,7 +775,7 @@
     password="toor"
     tty=1
     settings="common"
    -options=$(getopt -o hp:n:a:FcPv:t:S:u:w:s:m: -l help,rootfs:,path:,name:,arch:,flush-cache,cache-only,private-portage,variant:,portage-dir:,tarball:,auth_key:,user:,autologin,password:,settings:,mirror:,tty: -- "$@")
    +options=$(getopt -o hp:n:a:FcPv:t:S:u:w:s:m: -l help,rootfs:,path:,name:,arch:,flush-cache,cache-only,private-portage,variant:,portage-dir:,tarball:,auth-key:,user:,autologin,password:,settings:,mirror:,tty: -- "$@")

     eval set -- "$options"

**Comment by stgraber** [comment]
Thanks, though again, can you please give us the required Signed-off-by line? otherwise we can't include that change.
