### ISSUE TITLE
The UK image mirror seems to be out of sync

### ISSUE THREAD

**Issue by mrc0mmand** [lxc/lxc#3830]
# Issue description

Looks like the UK mirror got out of sync, which causes issues when using the `download` template with `lxc-create`.

# Steps to reproduce

```
$ sudo lxc-create -n bullseye-amd64 -t download -- -d debian -r bullseye -a amd64
Setting up the GPG keyring
Downloading the image index
Downloading the rootfs
ERROR: Failed to download http://images.linuxcontainers.org//images/debian/bullseye/amd64/default/20210507_05:24//rootfs.tar.xz
lxc-create: bullseye-amd64: lxccontainer.c: create_run_template: 1617 Failed to create container from template
lxc-create: bullseye-amd64: tools/lxc_create.c: main: 327 Failed to create container bullseye-amd64
```

### Debian, US mirror:
https://us.images.linuxcontainers.org//images/debian/bullseye/amd64/default/
![image](https://user-images.githubusercontent.com/679338/117536996-8f8f0180-affe-11eb-850f-0d04f20c8178.png)

### Debian, UK mirror:
https://uk.images.linuxcontainers.org//images/debian/bullseye/amd64/default/
![image](https://user-images.githubusercontent.com/679338/117537002-9e75b400-affe-11eb-9d49-ccfef340b707.png)

The same applies to other images as well (from what I've checked).

**Comment by stgraber** [comment]
Hmm, indeed. I'll run a few more tests and will open a ticket with Canonical IS as they're the ones running those mirrors.

**Comment by stgraber** [comment]
I've filed a ticket with Canonical now (ID 130871) and I've updated the redirection logic on our side so no traffic will be sent to the UK mirror for now.

**Comment by stgraber** [comment]
Closing as there isn't anything else we can do on our side. Once Canonical has corrected the mirror, we'll add it back to the main endpoint for our European users.

**Comment by mrc0mmand** [comment]
> Closing as there isn't anything else we can do on our side. Once Canonical has corrected the mirror, we'll add it back to the main endpoint for our European users.

Thank you!
