### ISSUE TITLE
lxc-create fails due to unsupported personality "aarch64"

### ISSUE THREAD

**Issue by graysky2** [lxc/lxc#3832]
# Required information

 * Distribution: Arch ARM aarch64
 * Distribution version: rolling release
 * The output of
   * `lxc-start --version 4.0.9`
   * `lxc-checkconfig`
```
LXC version 4.0.9
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Warning: newuidmap is not setuid-root
Warning: newgidmap is not setuid-root
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 


Cgroup v2 mount points: 
/sys/fs/cgroup

Cgroup v1 systemd controller: missing
Cgroup v1 freezer controller: missing
Cgroup namespace: required
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: missing
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```
   * `uname -a Linux submyth 5.10.35-2-ARCH #1 SMP PREEMPT Fri May 7 12:46:30 EDT 2021 aarch64 GNU/Linux`

# Issue description

`lxc-create` is unable to create an archlinux arm64 container failing due to what I think is an internal change in how you are defining the architecture of the target.  In the past, the target was **aarch64** but with the release of v4.0.9, I believe you changed it to **arm64** so there is a mismatch.

For example, I have an existing lxc container I created under version 4.0.6 I believe.  The `config` generated by the script contained `lxc.arch = aarch64` which I had to manually adjust to `lxc.arch = arm64` in order to start the container under v4.0.9.

For your reference, here is the output of the creation step under 4.0.9:
```
# lxc-create -n newcontainer -t download -- --dist archlinux --release current --arch arm64
Using image from local cache
Unpacking the rootfs

---
You just created an Archlinux  aarch64 (20210509_04:18) container.
lxc-create: newcontainer: confile.c: set_config_personality: 1249 Invalid argument - Unsupported personality "aarch64"
lxc-create: newcontainer: parse.c: lxc_file_for_each_line_mmap: 131 Failed to parse config file "/var/lib/lxc/newcontainer/config" at line "lxc.arch = aarch64"
lxc-create: newcontainer: tools/lxc_create.c: main: 319 Failed to create container newcontainer
```

# Steps to reproduce

 1. Run: `lxc-create -n newcontainer -t download -- --dist archlinux --release current --arch arm64`

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l TRACE -o <logfile> `)
 - [ ] the containers configuration file

**Comment by brauner** [comment]
I'll go check this right away. Sorry for that bug!

**Comment by brauner** [comment]
Oh this is dumb. It got dropped apparently.

**Comment by brauner** [comment]
https://github.com/lxc/lxc/pull/3833 should fix it.

**Comment by graysky2** [comment]
Thanks for the quick reply.  I patched 4.0.9 with your fix and built it.  Problem fixed.

**Comment by brauner** [comment]
I'm adding tests for all valid arch values now so this doesn't happen again!

**Comment by graysky2** [comment]
Maybe roll out 4.0.9.1 or something official once you're satisfied?

**Comment by brauner** [comment]
> Maybe roll out 4.0.9.1 or something official once you're satisfied?

Yeah, we're going to release `4.0.10` most likely because of some other fixes we had to do.

**Comment by graysky2** [comment]
Thanks @brauner :trophy:
