### ISSUE TITLE
Config parsing error when built without AppArmor

### ISSUE THREAD

**Issue by thmo** [lxc/lxc#3839]
This is related by [this](https://bugzilla.redhat.com/show_bug.cgi?id=1959328) Fedora bug report.

When LXC is built without AppArmor suport, it fails to parse `lxc.apparmor.profile = ...` config directives. Would it be possible to skip the directive instead (and maybe issue a warning)?

**Comment by brauner** [comment]
This is with `v4.0.8` as I can see from the bug report. And for stable I have already fixed that (though I would still prefer to error in master, i.e. with the next major release). The patch you need is:
https://github.com/lxc/lxc/commit/05cd29daad6e213bb0b524587056b0d453705111

Sorry for the regression!

**Comment by brauner** [comment]
Oh, and we're releasing a new stable update soon too.
