### ISSUE TITLE
templates: need /proc mounted

### ISSUE THREAD

**Issue by ghost** [lxc/lxc#384]
some debian packages require /proc to be mounted, therefore the template should mount /proc during creation of the chroot.

**Comment by stgraber** [comment]
debootstrap provides /proc and /sys for any package installed during the bootstrap phase, however further apt-get installs from the template will indeed run without /proc mounted.

The template should be updated to run those commands inside a separate mntns (lxc-unshare -s MNT) and then mount proc and sys.

**Comment by daniel-baumann** [comment]
"The template should [...] run those commands inside a separate mntns"

it shoudn't because it would uselessly make it required to have cgroups on the system in order to be able to create (!= run) containers. just bind-mount (and unmount) them and be done with it...

**Comment by stgraber** [comment]
no it wouldn't. Unsharing the mntns doesn't in any way touches the cgroups.

And it should be in a separate mntns to prevent anything starting from a postinst script from potentially messing the mount table of the host.

**Comment by daniel-baumann** [comment]
well, not cgroups per se, but namespaces.

and no, there's policy-rc.d for preventing starting things.

**Comment by Sleaker** [comment]
I'm not sure if this is the suggested way to handle this, but I'm using the following command in my template to handle installation of additional packages and it seems to work fine.

lxc-unshare -s MOUNT -M -- chroot "$cache/partial-${arch}" /install.sh || { suggest_flush; false }

contents of install.sh:
#!/bin/sh
export DEBIAN_FRONTEND=noninteractive
tasksel install server
mount -t proc proc /proc
apt-get install -y list of packages
apt-get -y autoremove --purge list_of_packages_
umount /proc

**Comment by harridu** [comment]
Is the lxc-unshare construct the official way to handle this?

Would it be possible to fix the templates accordingly?

**Comment by brauner** [comment]
Yes, `lxc-unshare` would be a good place. You could however also rely on the presence of the `unshare` binary which is part of `util-linux`. The latter seems a good idea to me. The templates can then simply be adapted to `unshare` + mount `/proc`. Patches welcome.

**Comment by brauner** [comment]
Most templates should do the right thing by now already.
