### ISSUE TITLE
Support LISTEN_FDS to keep inherited file descriptors open.

### ISSUE THREAD

**Issue by r10r** [lxc/lxc#3845]
Hi there,

while implementing https://github.com/lxc/lxcri/issues/13  for lxcri. I noticed that lxc warns about inherited file descriptors.

```
lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 3
lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 4
lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 8
lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 9
lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 10
lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 11
lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 12
lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 13
lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 14
```

The `LISTEN_FDS` environment variable is mentioned in the OCI spec and used by systemd to support socket activiation.

>  *`LISTEN_FDS`:* The number of file descriptors passed.
>       For example, `LISTEN_FDS=2` would mean that the runtime MUST pass file descriptors 3 and 4 to the container process (in addition to the standard streams) to support [socket activation][systemd-listen-fds].

see https://github.com/opencontainers/runtime-tools/blame/master/docs/command-line-interface.md#L78

What about supporting `LISTEN_FDS` in lxc instead ?

**Comment by brauner** [comment]
> Hi there,
> 
> while implementing [lxc/lxcri#13](https://github.com/lxc/lxcri/issues/13) for lxcri. I noticed that lxc warns about inherited file descriptors.
> 
> ```
> lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 3
> lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 4
> lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 8
> lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 9
> lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 10
> lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 11
> lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 12
> lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 13
> lxc buildah-buildah975299976 20210519121608.238 WARN     start - start.c:lxc_check_inherited:300 - Inherited fd 14
> ```
> 
> The `LISTEN_FDS` environment variable is mentioned in the OCI spec and used by systemd to support socket activiation.
> 
> > _`LISTEN_FDS`:_ The number of file descriptors passed.
> > For example, `LISTEN_FDS=2` would mean that the runtime MUST pass file descriptors 3 and 4 to the container process (in addition to the standard streams) to support [socket activation][systemd-listen-fds].
> 
> see https://github.com/opencontainers/runtime-tools/blame/master/docs/command-line-interface.md#L78
> 
> What about supporting `LISTEN_FDS` in lxc instead ?

Yeah, we can do that. Can you come up with a patch for that?

**Comment by r10r** [comment]
> Yeah, we can do that. Can you come up with a patch for that?

Sure!

**Comment by r10r** [comment]
I'd like to add a test to the test suite. But being a bit time constraint - I did test the implementation
with the following script.

```bash
#!/bin/sh -eu

n="test-listen-fds"
export LXCPATH=$(mktemp -d /tmp/lxcpath.XXXXXXXXXX)
echo "using LXCPATH $LXCPATH"
lxc-create -P $LXCPATH -n $n -t busybox
cat >>$LXCPATH/$n/config <<EOF
lxc.ephemeral = 1
lxc.init.cmd = ls -l /proc/self/fd
lxc.console.path = none
EOF

# fd 3 referes to the executable (is marked close-on-exec ?)
exec 4<>/dev/null
ls -l /proc/self/fd

lxc-start --close-all-fds -F -P $LXCPATH -n $n -l DEBUG -o /dev/stdout |
	egrep 'lxc_check_inherited|LISTEN_FDS'
rmdir $LXCPATH
```

```
[root@k8s-cluster9-controller lxc]# LISTEN_FDS=2 ./test.sh 
using LXCPATH /tmp/lxcpath.r5UPGKSHFS
total 0
lrwx------ 1 root root 64 Jun  7 15:03 0 -> /dev/pts/0
lrwx------ 1 root root 64 Jun  7 15:03 1 -> /dev/pts/0
lrwx------ 1 root root 64 Jun  7 15:03 2 -> /dev/pts/0
lr-x------ 1 root root 64 Jun  7 15:03 3 -> /proc/3512455/fd
lrwx------ 1 root root 64 Jun  7 15:03 4 -> /dev/null
lxc-start: test-listen-fds: cgroups/cgroup2_devices.c: bpf_program_load_kernel: 334 Operation not permitted - Failed to load bpf program: (null)
lxc-start: test-listen-fds: cgroups/cgfsng.c: __cgroup_tree_create: 771 File exists - Creating the final cgroup 9(lxc.monitor.test-listen-fds) failed
lxc-start: test-listen-fds: cgroups/cgfsng.c: cgroup_tree_create: 831 File exists - Failed to create monitor cgroup 9(lxc.monitor.test-listen-fds)
lxc-start test-listen-fds 20210607130317.328 DEBUG    start - start.c:get_listen_fds_max:231 - Using "LISTEN_FDS=2" environment variable to keep inherited file descriptors open
lxc-start test-listen-fds 20210607130317.328 INFO     start - start.c:lxc_check_inherited:322 - Inherited fd 4 (using the LISTEN_FDS environment variable)
lxc-start: test-listen-fds: cgroups/cgfsng.c: __cgroup_tree_create: 771 File exists - Creating the final cgroup 9(lxc.payload.test-listen-fds) failed
lxc-start: test-listen-fds: cgroups/cgfsng.c: cgroup_tree_create: 831 File exists - Failed to create payload cgroup 9(lxc.payload.test-listen-fds)
ls: /proc/self/fd/3: cannot read link: No such file or directory
```

```
[root@k8s-cluster9-controller lxc]# ./test.sh 
using LXCPATH /tmp/lxcpath.483xS1WAY1
total 0
lrwx------ 1 root root 64 Jun  7 15:03 0 -> /dev/pts/0
lrwx------ 1 root root 64 Jun  7 15:03 1 -> /dev/pts/0
lrwx------ 1 root root 64 Jun  7 15:03 2 -> /dev/pts/0
lr-x------ 1 root root 64 Jun  7 15:03 3 -> /proc/3512898/fd
lrwx------ 1 root root 64 Jun  7 15:03 4 -> /dev/null
lxc-start: test-listen-fds: cgroups/cgroup2_devices.c: bpf_program_load_kernel: 334 Operation not permitted - Failed to load bpf program: (null)
lxc-start: test-listen-fds: cgroups/cgfsng.c: __cgroup_tree_create: 771 File exists - Creating the final cgroup 8(lxc.monitor.test-listen-fds) failed
lxc-start: test-listen-fds: cgroups/cgfsng.c: cgroup_tree_create: 831 File exists - Failed to create monitor cgroup 8(lxc.monitor.test-listen-fds)
lxc-start test-listen-fds 20210607130329.468 INFO     start - start.c:lxc_check_inherited:330 - Closed inherited fd 4
lxc-start: test-listen-fds: cgroups/cgfsng.c: __cgroup_tree_create: 771 File exists - Creating the final cgroup 8(lxc.payload.test-listen-fds) failed
lxc-start: test-listen-fds: cgroups/cgfsng.c: cgroup_tree_create: 831 File exists - Failed to create payload cgroup 8(lxc.payload.test-listen-fds)
ls: /proc/self/fd/3: cannot read link: No such file or directory
```

**Comment by brauner** [comment]
This is merged and will be available in the point release we're about to tag.

**Comment by r10r** [comment]
This is good news! Thanks for the notice!
