### ISSUE TITLE
lxc-autostart exits with failure when there are no containers to process

### ISSUE THREAD

**Issue by Gwani** [lxc/lxc#3847]
# Required information
```
# lxc-start --version
4.0.5
```
likely applicable to any distribution.

# Issue description

`lxc-autostart` returns with exit code 1 when there are no containers in `lxc.lxcpath`.

Although a minor issue, it gave me some trouble with some of my scripts which might call `lxc-autostart` on machines where there aren't any containers created (yet). I would expect `lxc-autostart` to exit with 0 in this case, since no container actually failed - even if there are none to begin with.

I think the problem might be caused by [this line in `lxc-autostart.c`](https://github.com/lxc/lxc/blob/master/src/lxc/tools/lxc_autostart.c#L496). `failed == count` is of course `true` when both are zero.
`if (count > 0 && failed == count)` might do the trick.

# Steps to reproduce

 1. have a `lxc.lxcpath` without any container directories.
 2. execute `lxc-autostart`
 3. execute `echo $?`, which then prints `1` instead of (the expected) `0`.

# Information to attach
N/A

**Comment by stgraber** [comment]
Sounds like a pretty trivial fix and it'd definitely make sense to not have lxc-autostart error out when there's nothing to start :)
