### ISSUE TITLE
Setting gateway and ipv4 (incl. netmask) via python-lxc

### ISSUE THREAD

**Issue by run2fail** [lxc/lxc#385]
Hi,

I noticed the following with lxc version `1.0.6-0ubuntu0.1` on Ubuntu trusty. I did not try newer versions as there are no matching changelog entries for the following issue.

The container's `config` contains:

    lxc.network.type = veth
    lxc.network.flags = up
    lxc.network.link = my_bridge
    lxc.network.ipv4.gateway = 10.1.1.1
    lxc.network.ipv4 = 10.1.1.2/24

Then I create an `lxc.Container` instance:

    >>> import lxc
    >>> container = lxc.Container('container')
    >>> container.get_config_item('lxc.network.0.ipv4')
    ['10.1.1.2']
    >>> container.get_config_item('lxc.network.0.ipv4.gateway')
    ''
    >>> container.get_config_item('lxc.network.0.ipv4_gateway')
    '10.1.1.1'
    >>> container.save_config()

The `config` is not changed - as expected. The `netmask` in CIDR notation is nevertheless not returned by `get_config_item()`. The gateway attribute seems to be accessed differently but that's not a problem.

Now I try to set the IP address and the gateway:

    >>> container.set_config_item('lxc.network.0.ipv4_gateway', '10.1.1.1')
    False
    >>> container.set_config_item('lxc.network.0.ipv4.gateway', '10.1.1.1')
    False
    >>> container.network[0].ipv4_gateway = '10.1.1.1'
    
    >>> container.set_config_item('lxc.network.0.ipv4', '10.1.1.2/24')
    False
    >>> container.network[0].ipv4 = '10.1.1.2/24'
    
    >>> container.save_config()

Now the container's `config` contains:

    lxc.network.type = veth
    lxc.network.flags = up
    lxc.network.link = my_bridge
    lxc.network.ipv4 = 10.1.1.2/8
    lxc.network.ipv4 = 10.1.1.1/8
    lxc.network.ipv4 = 10.1.1.1/8
    lxc.network.ipv4 = 10.1.1.1/8
    lxc.network.ipv4 = 10.1.1.1/8

Result:
* The gateway is missing
* The gateway's IP address was assigned to the container's interface
* The netmask of `lxc.network.ipv4` is wrong
* There are duplicated entries (as the `ipv4` seems to be a list in python)
* `set_config_item()` returned `False` but did something nevertheless

Maybe I am using the Python module in a wrong way but currently I am out of ideas.

Kind regards,

BB

**Comment by run2fail** [comment]
As discussed on the lxc-users mailing list the version (1.1.0~alpha3+master~20150101-2236-0ubuntu1~trusty) from the ppa works.

see: https://lists.linuxcontainers.org/pipermail/lxc-users/2015-January/008241.html

**Comment by stgraber** [comment]
Can you try against 1.0.7? I believe it should include the required commits.

**Comment by run2fail** [comment]
1.0.7 from trusty-updates works indeed: The netmask can be set and retrieved. Sorry, this release (in trusty-updates) was so close to the holidays that I did not notice it.

**Comment by stgraber** [comment]
That's alright, I've only let 1.0.7 into trusty-updates a couple of days ago :)
