### ISSUE TITLE
lxc-autostart -A -g group exits with a partial failure (2) when containers exist that don't match the group

### ISSUE THREAD

**Issue by sim-** [lxc/lxc#3857]
# Required information

   * `lxc-start --version`: 2.0.7 (works), 3.0.3 (fails), 4.0.6 (fails)

# Issue description

`lxc-autostart -A -g group` exits with a partial failure code (`2`) when containers exist that don't match the group. This behaviour starts with e3e70db364505a5f9e7eb5aa922f636300d3a0d1 which adds the "failed" counter and the code to try to return the exit codes. This code makes the assumption that the containers which still exist during the cleanup before exiting are because of failures, but it also happens when containers exist that don't match the group filter list.

# Steps to reproduce

 1. Set up at least one container
 2. Execute `lxc-autostart -A -g anything`
 3. Execute `echo $?` which prints `2` instead of the expected `0`.

**Comment by stgraber** [comment]
@brauner can you take a look?
