### ISSUE TITLE
read-only snapshots on btrfs

### ISSUE THREAD

**Issue by laurivosandi** [lxc/lxc#386]
Hi, in order to take advantage of btrfs send/receive to push/pull containers between machines the snapshots should be created in read-only mode. At least the lxc-snapshot utility should expose --read-only flag which would tell the btrfs backend to create read-only snapshot. I am currently investigating how you're interfacing with btrfs, perhaps I can come up with a patch in following weeks. Any suggestions and ideas are welcome.

**Comment by stgraber** [comment]
I believe LXC basically just shells out to btrfs at the moment, so hopefully it shouldn't be too difficult to do. The trick will be to flip it back to read-write on snapshot restore though.

**Comment by v6sa** [comment]
Hello, I digged some code. It's not invoking btrfs command-line utility, instead there is insane amount of abstractions do_lxcapi_snapshot -> lxcapi_clone -> do_lxcapi_clone -> copy_storage -> bdev_copy -> clone_paths -> btrfs_clonepaths -> btrfs_snapshot_wrapper -> btrfs_snapshot -> ioctl(..., BTRFS_IOC_SNAP_CREATE_V2, ...)

Hopefully adding LXC_CLONE_READONLY does the trick, I'll investigate further later :)

**Comment by stgraber** [comment]
I so wish there was an official libbtrfs we could use for that stuff :)

**Comment by brauner** [comment]
Patches welcome but we currently won't spend time on this.
