### ISSUE TITLE
init_groups support is incomplete in v4.0.9

### ISSUE THREAD

**Issue by r10r** [lxc/lxc#3862]
Hi @brauner,

I'm currently testing lxcri against release v4.0.9.
According the the changelog init_groups support should have been merged.
But I'm getting test failures and the lxcri logs indicate that the `lxc.init.groups` config item is unsupported:
```
... ,"lxc.config":"lxc.init.groups","t":"10:24:11.832","c":"container.go:368","m":"unsupported config item"}
```

I looked at the changes in v4.0.9 and noticed that init_groups changes from https://github.com/lxc/lxc/commit/bf31b3378f2feae908efb0ae094a3ec07dc69af6 were only merged partially, e.g the changes from confile.c and  tests/get_item.c are missing. Is this on purpose ?

**Comment by brauner** [comment]
We usually only backport really necessary things. Do you need it in 4.0? If so I can backport this.

**Comment by r10r** [comment]
I see. Yes I need it - it would be really great if you can do this!

**Comment by brauner** [comment]
> I see. Yes I need it - it would be really great if you can do this!

Can you merge try
https://github.com/lxc/lxc/pull/3866
and see whether that works for you?

**Comment by r10r** [comment]
Looks good to me. I did merge it - but I have to fix my test cluster before I can rerun the tests. 
This has to be automated - sorry for the delay.

**Comment by brauner** [comment]
Merged and backported.
