### ISSUE TITLE
utopic amrhf containers fails on trusty amd64 host

### ISSUE THREAD

**Issue by laurivosandi** [lxc/lxc#387]
I created utopic armhf container on trusty amd64 host:

```
lxc-create -B btrfs -t ubuntu -n utopic-cubietruck-template -- --release utopic --arch armhf
```

With QEMU 2.0.0 userspace emulation (trusty default) I had unknown ioctl errors, with QEMU 2.1 (from utopic amd64) these dissapeared but upstart errors remain:

```
root@i7:~# lxc-start -n utopic-cubietruck-template
<4>init: Failed to spawn plymouth main process: unable to set trace: Function not implemented
<4>init: Failed to spawn ureadahead main process: unable to set trace: Function not implemented
<4>init: plymouth-upstart-bridge main process (5) terminated with status 1
<4>init: plymouth-upstart-bridge main process ended, respawning
<4>init: hwclock main process (9) terminated with status 77
<4>init: Failed to spawn mountall main process: unable to set trace: Function not implemented
```

The container doesn't boot up properly. lxc-attach somewhat works but it seems several mountpoints are not mounted.

Same approach with trusty armhf container on trusty amd64 host works perfectly. I am guessing it has something to do with utopic's upstart?

**Comment by stgraber** [comment]
Sorry for the mess, was changing the wrong bug report :)

**Comment by brauner** [comment]
This rather looks like an init system problem than a LXC problem. Also the cgroup interface for LXC has changed substantially. If you can reproduce on current master or stable please report back and here and I'll reopen!
