### ISSUE TITLE
lxc_start - start.c: start() -> execvp(): No such file or directory - Failed to exec "/system/bin/HelloWorld"(android)

### ISSUE THREAD

**Issue by shk242673** [lxc/lxc#3873]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution:
 * Distribution version:
 * The output of
   * `lxc-start --version`
   x:/ # lxc-start --version 
   4.0.9
   * `lxc-checkconfig`
   LXC version 4.0.9
   --- Namespaces ---
   Namespaces: enabled
   Utsname namespace: enabled
   Ipc namespace: enabled
   Pid namespace: enabled
   User namespace: enabled
   newuidmap is not installed
   newgidmap is not installed
   Network namespace: enabled

   --- Control groups ---
   Cgroups: enabled

   Cgroup v1 mount points:
   /dev/cpuctl
   /acct
   /dev/cpuset
   /dev/freezer
   /dev/memcg
   /dev/stune

   Cgroup v2 mount points:
   /dev/cg2_bpf

   Cgroup v1 systemd controller: missing
   Cgroup v1 clone_children flag: enabled
   Cgroup device: enabled
   Cgroup sched: enabled
   Cgroup cpu account: enabled
   Cgroup memory controller: enabled
   Cgroup cpuset: enabled

   --- Misc ---
   Veth pair device: enabled, not loaded
   Macvlan: enabled, not loaded
   Vlan: enabled, not loaded
   Bridges: enabled, not loaded
   Advanced netfilter: enabled, not loaded
   CONFIG_NF_NAT_IPV4: enabled, not loaded
   CONFIG_NF_NAT_IPV6: enabled, not loaded
   CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
   CONFIG_IP6_NF_TARGET_MASQUERADE: missing
   CONFIG_NETFILTER_XT_TARGET_CHECKSUM: missing
   CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
   FUSE (for use with lxcfs): enabled, not loaded

   --- Checkpoint/Restore ---
   checkpoint restore: enabled
   CONFIG_FHANDLE: enabled
   CONFIG_EVENTFD: enabled
   CONFIG_EPOLL: enabled
   CONFIG_UNIX_DIAG: enabled
   CONFIG_INET_DIAG: enabled
   CONFIG_PACKET_DIAG: enabled
   CONFIG_NETLINK_DIAG: enabled
   File capabilities:

   Note : Before booting a new kernel, you can check its configuration
   usage : CONFIG=/path/to/config /vendor/bin/lxc-checkconfig

   * `uname -a`
   Linux localhost 4.14.186-g95384a6e4-dirty #1 SMP PREEMPT Tue Jun 8 21:02:13 CST 2021 aarch64

   * `cat /proc/self/cgroup`
   6:schedtune:/
   5:memory:/
   4:freezer:/
   3:cpuset:/
   2:cpuacct:/uid_0/pid_1174
   1:cpu:/
   0::/

   * `cat /proc/1/mounts`
tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,mode=755 0 0
devpts /dev/pts devpts rw,seclabel,relatime,mode=600,ptmxmode=000 0 0
proc /proc proc rw,relatime,gid=3009,hidepid=2 0 0
sysfs /sys sysfs rw,seclabel,relatime 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
tmpfs /mnt tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000 0 0
/dev/block/by-name/md_udc /metadata ext4 rw,seclabel,nosuid,nodev,noatime,discard,data=ordered 0 0
/dev/block/dm-2 / ext4 ro,seclabel,nodev,relatime 0 0
/dev/block/dm-1 /vendor ext4 ro,seclabel,relatime 0 0
/dev/block/dm-0 /product ext4 ro,seclabel,relatime 0 0
tmpfs /apex tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755 0 0
tmpfs /linkerconfig tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755 0 0
tmpfs /mnt/installer tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000 0 0
tmpfs /mnt/androidwritable tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000 0 0
/dev/block/dm-2 /apex/com.android.extservices ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.media ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.cellbroadcast ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.resolv ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.sdkext ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.neuralnetworks ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.media.swcodec ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.vndk.v30 ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.tzdata ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.i18n ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.runtime ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.ipsec ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.conscrypt ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.mediaprovider ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.adbd ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.os.statsd ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.art ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.wifi ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.permission ext4 ro,seclabel,relatime 0 0
/dev/block/dm-2 /apex/com.android.tethering ext4 ro,seclabel,relatime 0 0
none /dev/cg2_bpf cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
none /dev/cpuctl cgroup rw,nosuid,nodev,noexec,relatime,cpu 0 0
none /acct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct 0 0
none /dev/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent 0 0
none /dev/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
none /dev/memcg cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
none /dev/stune cgroup rw,nosuid,nodev,noexec,relatime,schedtune 0 0
tmpfs /linkerconfig tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755 0 0
tracefs /sys/kernel/tracing tracefs rw,seclabel,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,seclabel,relatime 0 0
none /config configfs rw,nosuid,nodev,noexec,relatime 0 0
binder /dev/binderfs binder rw,relatime,max=1048576,stats=global 0 0
none /sys/fs/fuse/connections fusectl rw,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,seclabel,relatime 0 0
/dev/block/by-name/protect1 /mnt/vendor/protect_f ext4 rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered 0 0
/dev/block/by-name/protect2 /mnt/vendor/protect_s ext4 rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered 0 0
/dev/block/by-name/nvdata /mnt/vendor/nvdata ext4 rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered 0 0
/dev/block/by-name/nvcfg /mnt/vendor/nvcfg ext4 rw,seclabel,nosuid,nodev,noatime,nodelalloc,noauto_da_alloc,commit=1,data=ordered 0 0
adb /dev/usb-ffs/adb functionfs rw,relatime 0 0
/dev/block/dm-7 /data ext4 rw,seclabel,nosuid,nodev,noatime,noauto_da_alloc,resuid=10010,resgid=1065,errors=panic,data=ordered 0 0
/dev/block/dm-7 /data/user/0 ext4 rw,seclabel,nosuid,nodev,noatime,noauto_da_alloc,resuid=10010,resgid=1065,errors=panic,data=ordered 0 0
tmpfs /data_mirror tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=700,gid=1000 0 0
/dev/block/dm-7 /data_mirror/data_ce/null ext4 rw,seclabel,nosuid,nodev,noatime,noauto_da_alloc,resuid=10010,resgid=1065,errors=panic,data=ordered 0 0
/dev/block/dm-7 /data_mirror/data_ce/null/0 ext4 rw,seclabel,nosuid,nodev,noatime,noauto_da_alloc,resuid=10010,resgid=1065,errors=panic,data=ordered 0 0
/dev/block/dm-7 /data_mirror/data_de/null ext4 rw,seclabel,nosuid,nodev,noatime,noauto_da_alloc,resuid=10010,resgid=1065,errors=panic,data=ordered 0 0
/dev/block/dm-7 /data_mirror/cur_profiles ext4 rw,seclabel,nosuid,nodev,noatime,noauto_da_alloc,resuid=10010,resgid=1065,errors=panic,data=ordered 0 0
tmpfs /storage tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000 0 0
/data/media /mnt/runtime/default/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/runtime/read/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/runtime/write/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/runtime/full/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/dev/fuse /mnt/user/0/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /mnt/installer/0/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /mnt/androidwritable/0/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /storage/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/data/media /mnt/pass_through/0/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/dev/block/dm-4 /mnt/scratch ext4 rw,seclabel,noatime,data=ordered 0 0
overlay /system overlay rw,seclabel,noatime,lowerdir=/system,upperdir=/mnt/scratch/overlay/system/upper,workdir=/mnt/scratch/overlay/system/work,override_creds=off 0 0
overlay /vendor overlay rw,seclabel,noatime,lowerdir=/vendor,upperdir=/mnt/scratch/overlay/vendor/upper,workdir=/mnt/scratch/overlay/vendor/work,override_creds=off 0 0
overlay /product overlay rw,seclabel,noatime,lowerdir=/product,upperdir=/mnt/scratch/overlay/product/upper,workdir=/mnt/scratch/overlay/product/work,override_creds=off 0 0
/data/media /mnt/user/0/emulated/0/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /storage/emulated/0/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/androidwritable/0/emulated/0/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/installer/0/emulated/0/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/user/0/emulated/0/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /storage/emulated/0/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/androidwritable/0/emulated/0/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/installer/0/emulated/0/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/dev/block/dm-2 /data/freeme/secdroid/root ext4 ro,seclabel,nodev,relatime 0 0
overlay /data/freeme/secdroid/root/system overlay rw,seclabel,noatime,lowerdir=/system,upperdir=/mnt/scratch/overlay/system/upper,workdir=/mnt/scratch/overlay/system/work,override_creds=off 0 0
/dev/block/dm-2 /data/freeme/secdroid/root ext4 ro,seclabel,nodev,relatime 0 0
overlay /data/freeme/secdroid/root/system overlay rw,seclabel,noatime,lowerdir=/system,upperdir=/mnt/scratch/overlay/system/upper,workdir=/mnt/scratch/overlay/system/work,override_creds=off 0 0

# Issue description
Only a HelloWorld program is started through Lxc, which only prints logs, but it is found that the execvp of lxc_start fails(No such file or directory - Failed to exec "/system/bin/HelloWorld")

And through the access() function test, F_OK and X_OK both return 0. And the argv ends by NULL.

# Steps to reproduce
The start function
static int start(struct lxc_handler *handler, void* data)
{
	struct start_args *arg = data;

	INFO("Begin to test %s exist", arg->argv[0]);
	if(access(arg->argv[0], F_OK) == 0) {
		INFO("File exist: %s", arg->argv[0]);
	}else
		ERROR("Can't find file : %s", arg->argv[0]);

	if(access(arg->argv[0], X_OK) == 0) {
		INFO("File %s is executable", arg->argv[0]);
	}else
		ERROR("File %s is't executable", arg->argv[0]);

	if(arg->argv[1] != NULL) 
		ERROR("arg->argv[1] is not NULL");
	else
		ERROR("arg->argv[1] is NULL");

	INFO("Begin to readFileList of \"/\"");
	readFileList("/");

	NOTICE("Exec'ing \"%s\"", arg->argv[0]);

	execvp(arg->argv[0], arg->argv);
	SYSERROR("Failed to exec \"%s\"", arg->argv[0]);
	return 0;
}

Error logs:
06-21 19:43:52.894  4796  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/utils.c:lxc_drop_groups:1347  Dropped supplimentary groups
06-21 19:43:52.894  4796  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:do_start:1447  Before handler->ops->start(), and this should't return
06-21 19:43:52.894  4796  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:start:2197  Begin to test /system/bin/HelloWorld exist
06-21 19:43:52.894  4796  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:start:2199  File exist: /system/bin/HelloWorld
06-21 19:43:52.894  4796  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:start:2204  File /system/bin/HelloWorld is executable
06-21 19:43:52.894  4796  4795 E Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:start:2211  arg->argv[1] is NULL

06-21 19:43:52.897  4796  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:start:2216  Exec'ing "/system/bin/HelloWorld"
06-21 19:43:52.897  4796  4795 E Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:start:2219  No such file or directory - Failed to exec "/system/bin/HelloWorld"
06-21 19:43:52.897  4796  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:do_start:1449  After handler->ops->start(), Error occur
06-21 19:43:52.897  4796  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/sync.c:lxc_sync_wake_parent:106  Child waking parent with sequence error
06-21 19:43:52.897  4795  4795 E Lxc     : vendor/secdroid/external/lxc/src/lxc/sync.c:sync_wait:36  An error occurred in another process (expected sequence number 7)
06-21 19:43:52.897  4795  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:lxc_expose_namespace_environment:897  Set environment variable LXC_MNT_NS=/proc/4795/fd/18
06-21 19:43:52.898  4795  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:lxc_expose_namespace_environment:897  Set environment variable LXC_PID_NS=/proc/4795/fd/19
06-21 19:43:52.898  4795  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:lxc_expose_namespace_environment:897  Set environment variable LXC_UTS_NS=/proc/4795/fd/20
06-21 19:43:52.898  4795  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:lxc_expose_namespace_environment:897  Set environment variable LXC_IPC_NS=/proc/4795/fd/21
06-21 19:43:52.898  4795  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:lxc_expose_namespace_environment:897  Set environment variable LXC_NET_NS=/proc/4795/fd/22
06-21 19:43:52.898  4795  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:lxc_expose_namespace_environment:897  Set environment variable LXC_CGROUP_NS=/proc/4795/fd/9
06-21 19:43:52.898  4795  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/network.c:lxc_delete_network:4181  Deleted network devices
06-21 19:43:52.898  4795  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:lxc_abort:1026  Before lxc_set_state ABORTING
06-21 19:43:52.898  4795  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:lxc_set_state:529  Begin...
06-21 19:43:52.898  4795  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:lxc_serve_state_socket_pair:517  Sent container state "ABORTING" to 6
06-21 19:43:52.898  4795  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:lxc_serve_state_clients:452  Set container state to ABORTING
06-21 19:43:52.898  4795  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:lxc_serve_state_clients:455  No state clients registered
06-21 19:43:52.898  4795  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:lxc_set_state:543  End...
06-21 19:43:52.898  4795  4795 I Lxc     : vendor/secdroid/external/lxc/src/lxc/start.c:lxc_abort:1028  After lxc_set_state ABORTING
06-21 19:43:52.898  4793  4793 E Lxc     : vendor/secdroid/external/lxc/src/lxc/lxccontainer.c:wait_on_daemonized_start:875  Received container state "ABORTING" instead of "RUNNING"
06-21 19:43:52.898  4793  4793 I Lxc     : vendor/secdroid/external/lxc/src/lxc/lxccontainer.c:do_lxcapi_start:989  After wait_on_daemonized_start

Thanks!

**Comment by mihalicyn** [comment]
I barely understand what it is about and what the question is to be honest.

Taking into account that this was created more than 3 years ago, I'm closing this.

Feel free to reopen if it's actual and provide a bit more context, please.
