### ISSUE TITLE
Use Official Canonical KeyServers, not the adhoc poorly run SKS Keyservers.

### ISSUE THREAD

**Issue by jpopovitch** [lxc/lxc#3874]
# Short Issue description

pool.sks-keyservers.net is M.I.A (again).   SKS have no motivation to maintain a well running key infrastructure.

# A brief description of what could be improved.

Switch lxc-download.in:DOWNLOAD_KEYSERVER to use keyserver.ubuntu.com and never have to worry again.

**Comment by brauner** [comment]
This is now fixed in https://github.com/lxc/lxc/pull/3882 .
