### ISSUE TITLE
src/lxc/start.c do_start():1079 ERROR("Failed to receive status file descriptor to child process")

### ISSUE THREAD

**Issue by shk242673** [lxc/lxc#3875]
# Issue description
Log print

In the do_start function, isn't the function of code on line 1078 (lxc_abstract_unix_recv_one_fd(data_sock1, &status_fd, NULL, 0)) to receive status file descriptor from parent process ?

static int do_start(void *data)
{
...
if (lxc_abstract_unix_recv_one_fd(data_sock1, &status_fd, NULL, 0) < 0) {
                **ERROR("Failed to receive status file descriptor to child process");**
                goto out_warn_father;
        }
...
}

The code below can be modified like this?

old:    **ERROR("Failed to receive status file descriptor to child process");**
new:  **ERROR("Failed to receive status file descriptor from parent process");**

Similarly, src/lxc/sync.c lxc_sync_wake_child() :122
bool lxc_sync_wake_child(struct lxc_handler *handler, int sequence)
{
        TRACE("Child waking parent with sequence %s", start_sync_to_string(sequence));
        return sync_wake(handler->sync_sock[1], sequence);
}

old:    **TRACE("Child waking parent with sequence %s", start_sync_to_string(sequence));**
new:  **TRACE("Parent waking child with sequence %s", start_sync_to_string(sequence));**

thanks!

**Comment by brauner** [comment]
Yeah, I think that should be a reasonable change.

**Comment by brauner** [comment]
You want to send a patch?

**Comment by shk242673** [comment]
Yeah, If these changes are correct, I want to merge them. Tks!
