### ISSUE TITLE
Output of `lxc-attach` is broken after piped

### ISSUE THREAD

**Issue by megurost** [lxc/lxc#3879]
# Issue description

When I pipe the output of `lxc-attach` to `grep` it results in messed up output.
The same doesn't happen when using SSH.

In my case, the call to `lxc-attach` is wrapped by another command which output I want to grep. However, below I provide a simple example which admittedly doesn't make sense as we could grep the file directly, but it should suffice to reproduce.

# Steps to reproduce

 1. Consider a text file inside a container named `dev` placed at `/root/name.txt` with the following content:
```
this is john
this is john doe
this is jane
this is jane doe
these are john and jane doe
```

 2. Step two

If I read the file with `cat` via SSH and pipe to `grep` it works as expected:
```bash
$ ssh dev -- cat /root/name.txt | grep john
this is john
this is john doe
these are john and jane doe
```

 3. The same using `lxc-attach` results in broken output:
```bash
$ lxc-attach -n dev -- cat /root/name.txt | grep john
this is john
            this is john doe
                            these are john and jane doe
                                                       $
```

Piping to `cat -` instead of `grep john` should provide similar results.

# Required information

 * Distribution: Fedora
 * Distribution version: 33
 * The output of
   * `lxc-start --version`: 4.0.8
   * `uname -a`: Linux 5.11.18 x86_64

I have manage to reproduce the above with Fedora 33 and Ubuntu Xenial containers.

**Comment by brauner** [comment]
I sent a PR in #3892 that should hopefully fix this!

**Comment by megurost** [comment]
@brauner awesome, the fix works. Thanks!
