### ISSUE TITLE
unprivileged lxc crashing on lxc-attach

### ISSUE THREAD

**Issue by micsuka** [lxc/lxc#3881]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Manjaro
 * Distribution version: latest (2021-06-27)
 * The output of
   * `lxc-start --version` 4.0.9
[checkconfig.txt](https://github.com/lxc/lxc/files/6722276/checkconfig.txt)

   * `lxc-checkconfig`
   * `uname -a` `Linux micsa 5.12.9-1-MANJARO #1 SMP PREEMPT Thu Jun 3 14:56:42 UTC 2021 x86_64 GNU/Linux`
   * `cat /proc/self/cgroup` 0::/user.slice/user-1000.slice/session-1.scope
   * `cat /proc/1/mounts`

# Issue description

after starting an unprivileged lxc, the lxc-attach crashes the whole lxc process

A brief description of what failed or what could be improved.

the crash itself is happening in the liblxc.so, in the prepare_cgroup_ctx() function, the ops->hierarchies is NULL.
so, it works for me with a little sanity check in the for loop:

`
-       for (idx = 0; ops->hierarchies[idx]; idx++) {
+       for (idx = 0; ops->hierarchies && ops->hierarchies[idx]; idx++) {
`

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l TRACE -o <logfile> `)
 - [ ] the containers configuration file

**Comment by brauner** [comment]
Thanks for the report and helping to debug this. I've sent a PR that should fix this.
