### ISSUE TITLE
Question about lxc-download

### ISSUE THREAD

**Issue by Zqiang1211** [lxc/lxc#3886]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution:
 * 
 * Distribution version:
 * The output of
   `lxc-start --version`
   `lxc-checkconfig`
   * `uname -a`
   * `cat /proc/self/cgroup`
   * `cat /proc/1/mounts`

# Issue description
lxc-start --version
4.0.6

lxc-create -t download -n vc1

Setting up the GPG keyring
ERROR: Unable to fetch GPG key from keyserver
lxc-create: vc1: lxccontainer.c: create_run_template: 1616 Failed to create container from template
lxc-create: vc1: lxc_create.c: main: 319 Failed to create container vc1

the  gpg_setup()  execution failed  failed, the DOWNLOAD_KEYSERVER = hkp://pool.sks-keyservers.net

 Is it related to the network environment ?  and  how to solve it .

Thanks

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l TRACE -o <logfile> `)
 - [ ] the containers configuration file

**Comment by brauner** [comment]
Yeah, so somehow the sks keyserver went down which is why we switched keyservers. So https://github.com/lxc/lxc/pull/3882 should fix the issue. I already backported it to our stable branch.
