### ISSUE TITLE
OverlayFS doesn't work on 3.18

### ISSUE THREAD

**Issue by ajf** [lxc/lxc#389]
Upstream kernel changed "overlayfs" to "overlay" for the filesystem type with this commit:

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=ef94b1864d1ed5be54376404bb23d22ed0481feb

LXC uses "overlayfs", so LXC doesn't work with a vanilla 3.18 Linux kernel.  Changing 'overlayfs' to 'overlay' in bdev.c seems to fix the issue.

**Comment by ajf** [comment]
Yeah, that sounds reasonable, it's how docker detects whether or not overlayfs is available.

**Comment by stgraber** [comment]
We have support for this in lxc-start-ephemeral and Serge is testing a patch to get it in for the wider bdev support now.
