### ISSUE TITLE
lxc-create fails because "ERROR: Unable to fetch GPG key from keyserver"

### ISSUE THREAD

**Issue by kloczek** [lxc/lxc#3894]
```console
$ sudo lxc-create -t download -n fedora-dist -B btrfs -- -d fedora -r 33 -a amd64
The cached copy has expired, re-downloading...
Setting up the GPG keyring
ERROR: Unable to fetch GPG key from keyserver
lxc-create: fedora-dist: lxccontainer.c: create_run_template: 1621 Failed to create container from template
lxc-create: fedora-dist: tools/lxc_create.c: main: 319 Failed to create container fedora-dist
```
From https://sks-keyservers.net/
"This service is deprecated. This means it is no longer maintained, and new HKPS certificates will not be issued. Service reliability should not be expected.

Update 2021-06-21: Due to even more GDPR takedown requests, the DNS records for the pool will no longer be provided at all."

**Comment by stgraber** [comment]
Closing as we have already merged a change to use another key server.

**Comment by kloczek** [comment]
OK. May I ask where is the fix of that issue?

**Comment by stgraber** [comment]
https://github.com/lxc/lxc/commit/f2a5d95d00a55bed27ef9920d67617cc75fecad8

**Comment by kloczek** [comment]
Thank you.
