### ISSUE TITLE
container with loopback-only network configuration fails after upgrading to LXC 4

### ISSUE THREAD

**Issue by fickert** [lxc/lxc#3922]
## General Information
 * OS: Ubuntu 20.04 LTS
 * LXC version 4.0.6

## Issue Description
I am trying to set up a container with only a loopback network interface, using the following configuration snippet:
```
lxc.net.0.type = empty
lxc.net.0.flags = up
```
Starting the container fails with:
```
lxc-execute: (...) network.c: lxc_network_setup_in_child_namespaces_common: 3435 Invalid argument - Failed to set network device "" up
lxc-execute: (...) network.c: lxc_setup_network_in_child_namespaces: 3535 Invalid argument - Failed to setup netdev
```
The container was working fine before with LXC 3.0.1 on Ubuntu 18.04 LTS.

## Possible Cause and Workaround

I think the issue was caused by the changes to `src/lxc/network.c` introduced in commit 8bf64b77ac8a6f7d447709cdb6c6ad768f2302c1. The `lxc_network_setup_in_child_namespaces_common` function now sets up the loopback device once in [line 3414](https://github.com/lxc/lxc/blob/lxc-4.0.6/src/lxc/network.c#L3414), and then again in [line 3433 but with an empty name](https://github.com/lxc/lxc/blob/lxc-4.0.6/src/lxc/network.c#L3433), which probably should not be called in this case. Previously, the original function had early returns for devices with type `LXC_NET_EMPTY` or `LXC_NET_NONE`; I guess reintroducing the early return or adding a check for the device type in the [`if` condition](https://github.com/lxc/lxc/blob/lxc-4.0.6/src/lxc/network.c#L3432) could fix the issue.

As a workaround, I can add `lxc.net.0.name = lo` to the container configuration so the second (redundant) call to `lxc_netdev_up` doesn't fail. Any other name will cause the same error message as above (except with the configured name instead of "").

**Comment by brauner** [comment]
Sorry about that! Thanks for the bug report and thanks for pointing out the buggy commit. This should fix it:
https://github.com/lxc/lxc/pull/3923
