### ISSUE TITLE
python3-lxc creates duplicate config entries

### ISSUE THREAD

**Issue by run2fail** [lxc/lxc#394]
Hi,

this is probably strongly related to #214 but is not exactly the same issue (there is no second `load_config()`). It was tested with version `1.1.0~alpha3+master~20150105-2240-0ubuntu1~trusty` from the ppa.

Initial container `config` (excerpt):

    lxc.network.0.type = veth
    lxc.network.0.flags = up
    lxc.network.0.link = test

Python instance of the container:

    >>> con = lxc.Container('name')
    >>> con.get_config_item('lxc.network.0.link')
    'test'
    >>> con.clear_config_item('lxc.network.0.link')    # optional action
    True
    >>> con.get_config_item('lxc.network.0.link')
    ''
    >>> con.set_config_item('lxc.network.0.link', 'foo')
    True
    >>> con.save_config()
    True

Now the `config` contains:

    lxc.network.0.type = veth
    lxc.network.0.flags = up
    lxc.network.0.link = 
    lxc.network.0.link = foo

The result is independent of the `clear_config_item()` call.

Is that the expected result? What's the right workflow to read the config file, get particular values, set some of them and then save the result to the file?

Kind regards

**Comment by stgraber** [comment]
So that behaviour would be correct if "link" was a multi-value key which it isn't.

The = <nothing> on clear_config_item is meant to clear any value, inherited or otherwise before you set it again to whatever you actually want.

However this is still invalid behaviour for that specific key.

**Comment by stgraber** [comment]
Ok, so the real problem here is that clear_config_item should only be allowed against lists, not against single value keys which is what's wrong here...

**Comment by stgraber** [comment]
Sent a patch to fix this by making clear_config_item more consistent (returns -1 for any non-list entry).

**Comment by stgraber** [comment]
The first patch for this issue has been Acked, however this uncovered another problem with config storage which we're still looking into.
