### ISSUE TITLE
Unable to install DEB package in container

### ISSUE THREAD

**Issue by blinux45** [lxc/lxc#3945]
I created a debian9 unprivileged container for user "lxcuser".
I need to install libwayland-cursor0 in this container.

lxcuser@host:~/$ lxc-attach  --clear-env --keep-var TERM --keep-var XAUTHORITY -n debianContainer --logfile ~/logs/lxc-attach.log --logpriority DEBUG
WARN: could not reopen tty: Permission denied
root@LXC_NAME:/#

I ran : apt-get install libwayland-cursor0
The installation produced no error.

root@LXC_NAME:/home/tor-browser_en-US/Browser# dpkg -l | grep libwayland-cursor0
ii  libwayland-cursor0:amd64      1.12.0-1+deb9u1                   amd64        wayland compositor infrastructure - cursor library

However,
root@LXC_NAME:/var/cache/apt/archives# dpkg-query -L libwayland-client0_1.12.0-1+deb9u1_amd64.deb
dpkg-query: package 'libwayland-client0_1.12.0-1+deb9u1_amd64.deb' is not installed
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.

root@LXC_NAME:/var/cache/apt/archives# ls -lah libwayland*
-rw-r--r--. 1 root root  14K Nov 10  2018 libwayland-cursor0_1.12.0-1+deb9u1_amd64.deb

root@LXC_NAME:/var/cache/apt/archives# dpkg-deb --contents libwayland-client0_1.12.0-1+deb9u1_amd64.deb
drwxr-xr-x root/root         0 2021-08-10 23:51 ./
The deb package is shown to have no content.

Checking for the same package from the host, I get:
lxcuser@host:~# ls -lah /home/lxcuser/.local/share/lxc/debianContainer/rootfs/var/cache/apt/archives/libwayland*
-rw-r--r--. 1 200000 200000  14K Nov 10  2018 /home/lxcuser/.local/share/lxc/debianContainer/rootfs/var/cache/apt/archives/libwayland-cursor0_1.12.0-1+deb9u1_amd64.deb

lxcuser@host:~/.local/share/lxc/debianContainer/rootfs/var/cache/apt/archives$ dpkg-deb -c libwayland-cursor0_1.12.0-1+deb9u1_amd64.deb
drwxr-xr-x root/root         0 2018-03-04 05:43 ./
drwxr-xr-x root/root         0 2018-03-04 05:43 ./usr/
drwxr-xr-x root/root         0 2018-03-04 05:43 ./usr/lib/
drwxr-xr-x root/root         0 2018-03-04 05:43 ./usr/lib/x86_64-linux-gnu/
-rw-r--r-- root/root     31168 2018-03-04 05:43 ./usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0.0.0
drwxr-xr-x root/root         0 2018-03-04 05:43 ./usr/share/
drwxr-xr-x root/root         0 2018-03-04 05:43 ./usr/share/doc/
drwxr-xr-x root/root         0 2018-03-04 05:43 ./usr/share/doc/libwayland-cursor0/
-rw-r--r-- root/root      3311 2018-03-04 05:43 ./usr/share/doc/libwayland-cursor0/changelog.Debian.gz
-rw-r--r-- root/root      1593 2018-03-04 05:43 ./usr/share/doc/libwayland-cursor0/copyright
lrwxrwxrwx root/root         0 2018-03-04 05:43 ./usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0 -> libwayland-cursor.so.0.0.0

The package is not empty!
I found nothing online or in the logs to resolve this.
I tried to reinstall and manually download the deb package.
But this did not resolve the problem.
I would appreciate any suggestion.
Thank you.

**Comment by stgraber** [comment]
What does `cat /var/lib/dpkg/info/libwayland-cursor0\:amd64.list` show you?
And what do you get with `ls -lh /usr/lib/x86_64-linux-gnu/libwayland-cursor.so*`?

**Comment by blinux45** [comment]
The shared library did not install.
It seems that apt marks packages without content as installed successfully.
Why the content of the package is not seen within the container?

root@LXC_NAME:/var/cache/apt/archives# cat /var/lib/dpkg/info/libwaylandcursor0\:amd64.list
cat: '/var/lib/dpkg/info/libwaylandcursor0:amd64.list': No such file or directory

root@LXC_NAME:/var/cache/apt/archives# ls -lh /usr/lib/x86_64-linux-gnu/libwayland-cursor.so*
ls: cannot access '/usr/lib/x86_64-linux-gnu/libwayland-cursor.so*': No such file or directory

**Comment by stgraber** [comment]
Can you show `cat /proc/self/mountinfo` from inside this container?

**Comment by blinux45** [comment]
root@LXC_NAME:/var/cache/apt/archives# cat /proc/self/mountinfo

239 240 254:1 /lxcuser/.local/share/lxc/debianContainer/rootfs / rw,relatime master:28 - ext4 /dev/mapper/debian-home rw,seclabel,data=ordered
314 239 0:42 / /dev rw,relatime - tmpfs none rw,seclabel,size=492k,mode=755,uid=200000,gid=200000
315 239 0:44 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
316 317 0:44 /sys/net /proc/sys/net rw,nosuid,nodev,noexec,relatime - proc proc rw
317 315 0:44 /sys /proc/sys ro,nosuid,nodev,noexec,relatime - proc proc rw
318 315 0:44 /sysrq-trigger /proc/sysrq-trigger ro,nosuid,nodev,noexec,relatime - proc proc rw
319 239 0:45 / /sys rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw,seclabel
320 319 0:45 / /sys ro,nosuid,nodev,noexec,relatime - sysfs sysfs rw,seclabel
321 320 0:45 / /sys/devices/virtual/net rw,relatime - sysfs sysfs rw,seclabel
322 321 0:45 /devices/virtual/net /sys/devices/virtual/net rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw,seclabel
323 320 0:39 / /sys/fs/fuse/connections rw,relatime master:101 - fusectl fusectl rw
324 314 0:6 /console /dev/console rw,nosuid,relatime master:2 - devtmpfs udev rw,seclabel,size=2836556k,nr_inodes=709139,mode=755
325 314 0:6 /full /dev/full rw,nosuid,relatime master:2 - devtmpfs udev rw,seclabel,size=2836556k,nr_inodes=709139,mode=755
326 314 0:6 /null /dev/null rw,nosuid,relatime master:2 - devtmpfs udev rw,seclabel,size=2836556k,nr_inodes=709139,mode=755
327 314 0:6 /random /dev/random rw,nosuid,relatime master:2 - devtmpfs udev rw,seclabel,size=2836556k,nr_inodes=709139,mode=755
328 314 0:6 /tty /dev/tty rw,nosuid,relatime master:2 - devtmpfs udev rw,seclabel,size=2836556k,nr_inodes=709139,mode=755
329 314 0:6 /urandom /dev/urandom rw,nosuid,relatime master:2 - devtmpfs udev rw,seclabel,size=2836556k,nr_inodes=709139,mode=755
330 314 0:6 /zero /dev/zero rw,nosuid,relatime master:2 - devtmpfs udev rw,seclabel,size=2836556k,nr_inodes=709139,mode=755
331 239 8:3 /tmp/.X11-unix /tmp/.X11-unix ro,noatime,nodiratime master:1 - ext4 /dev/sda3 rw,seclabel,errors=remount-ro,data=ordered
332 315 0:38 /proc/cpuinfo /proc/cpuinfo rw,nosuid,nodev,relatime master:61 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
333 315 0:38 /proc/diskstats /proc/diskstats rw,nosuid,nodev,relatime master:61 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
334 315 0:38 /proc/meminfo /proc/meminfo rw,nosuid,nodev,relatime master:61 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
335 315 0:38 /proc/stat /proc/stat rw,nosuid,nodev,relatime master:61 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
336 315 0:38 /proc/swaps /proc/swaps rw,nosuid,nodev,relatime master:61 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
337 315 0:38 /proc/uptime /proc/uptime rw,nosuid,nodev,relatime master:61 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
338 324 0:18 /5 /dev/console rw,nosuid,noexec,relatime master:3 - devpts devpts rw,seclabel,gid=5,mode=620,ptmxmode=000
241 314 0:46 / /dev/pts rw,relatime - devpts devpts rw,seclabel,gid=200005,mode=620,ptmxmode=666
242 314 0:46 /0 /dev/tty1 rw,relatime - devpts devpts rw,seclabel,gid=200005,mode=620,ptmxmode=666
243 314 0:46 /1 /dev/tty2 rw,relatime - devpts devpts rw,seclabel,gid=200005,mode=620,ptmxmode=666
244 314 0:46 /2 /dev/tty3 rw,relatime - devpts devpts rw,seclabel,gid=200005,mode=620,ptmxmode=666
245 314 0:46 /3 /dev/tty4 rw,relatime - devpts devpts rw,seclabel,gid=200005,mode=620,ptmxmode=666
246 314 0:47 / /dev/shm rw,nosuid,nodev - tmpfs tmpfs rw,seclabel,uid=200000,gid=200000
247 239 0:48 / /run rw,nosuid,nodev - tmpfs tmpfs rw,seclabel,mode=755,uid=200000,gid=200000
248 247 0:49 / /run/lock rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,seclabel,size=5120k,uid=200000,gid=200000
249 320 0:50 / /sys/fs/cgroup rw,nosuid,nodev,noexec - tmpfs tmpfs rw,seclabel,mode=755,uid=200000,gid=200000
250 249 0:23 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
251 249 0:26 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,freezer
252 249 0:27 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,perf_event
287 249 0:29 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,pids
288 249 0:28 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpu,cpuacct
289 249 0:31 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,net_cls,net_prio
290 249 0:33 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,memory
291 249 0:32 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuset,clone_children
292 249 0:30 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,devices
293 249 0:25 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,blkio
294 314 0:43 / /dev/mqueue rw,relatime - mqueue mqueue rw,seclabel

**Comment by brauner** [comment]
Closing since this doesn't seem something that LXC can do something about.
