### ISSUE TITLE
LXC doesn't free the container lock on ctrl+c during startup

### ISSUE THREAD

**Issue by flavius** [lxc/lxc#395]
Calling lxc-info in the hook makes lxc-start hang.

This is the first problem which I suspect is hard to avoid.

However, there is one more problem which is really annoying: if, while hung, I press CTRL+C to exit from lxc-start, then I can no longer use any lxc (I have tried lxc-ls, lxc-stop and lxc-destroy) command, they also hang.

The only solution is to reboot the entire server.

Please, make it that CTRL+C from a lxc-create which for whatever reason does not behave correctly, at least cleans up such that the lxc infrastructure remains usable.

**Comment by stgraber** [comment]
Looks like you're running into a pretty interesting locking situation there.

lxc-start takes the global lock for a little while, lxc-info then gets stuck on it and ctrl-c will not release the lock so everything else hangs. There's probably a bug there somewhere, though generally, calling lxc-info against a container that's not started yet is a pretty bad idea.

What exactly are you trying to get from lxc-info which isn't in the environment?

**Comment by brauner** [comment]
I can't reproduce this problem. If it still exists please re-open with a reproducer.
