### ISSUE TITLE
Error obtaining IP address of a newly created container from within a shell script

### ISSUE THREAD

**Issue by LenzGr** [lxc/lxc#396]
I've created a small shell script that I use to quickly create a new empty container based on a minimal CentOS6 template. The host is Ubuntu 14.04, running LXC 1.0.6 from the "ubuntu-lxc" PPA.

```bash
#!/bin/bash

NAME="testcontainer"

lxc-destroy -f -n $NAME
lxc-clone -s -o centos6base -n $NAME
echo "Starting $NAME."
lxc-start -d -n $NAME
echo "Determining IP address."
HOSTIP=$(lxc-info -i -H -n $NAME)

if test -z "$HOSTIP"
then
  echo "Could not determine IP address for $NAME!"
else
  echo "$NAME has IP $HOSTIP."
fi
```

However, running the script fails to determine the IP address, even though running the same call from the command line later returns the intended output:

```
% sudo ./create-container.sh 
Container is not defined
Created container testcontainer as snapshot of centos6base
Starting testcontainer.
Determining IP address.
Could not determine IP address for testcontainer!
% sudo lxc-info -i -H -n testcontainer
10.0.3.242
```

Adding a `sleep 5` after the `lxc-start` and `lxc-info` call does not help. Somehow `lxc-info -i` is unable to obtain the IP address when run within the same shell script that spawned the container. Interestingly, a plain `lxc-info -n` works!

**Comment by LenzGr** [comment]
Looking at the lxc_info.c source file, I wonder: shouldn't the `fflush()` call be made *after* printing out the IP addresses?

https://github.com/lxc/lxc/blob/master/src/lxc/lxc_info.c#L328

**Comment by LenzGr** [comment]
After adding a longer `sleep` in the shell script, the IP address is displayed - seems like I've been running into timing issues before. I modified the script as follows, to wait for the IP address to appear:

```bash
#!/bin/bash

NAME="testcontainer"

lxc-destroy -f -n $NAME
lxc-clone -s -o centos6base -n $NAME
echo "Starting $NAME."
lxc-start -d -n $NAME

echo -n "Determining IP address."
while test -z "$HOSTIP"
do
  echo -n "."
  HOSTIP=$(lxc-info -H -i -n $NAME)
  sleep 1
done

echo "$NAME has IP $HOSTIP."
```

Still, I find the location of `fflush()` above the actual print statements somewhat misplaced.

**Comment by dwengen** [comment]
Hi Lenz! The fflush() is to prevent previous lines from being printed twice due to the fork()ing that get_ips() does internally. See the full commit message of e2426f0b for a more detailed description.

Sometimes it can take the containers' dhcp client a bit to get an IP, so a loop like you have is a good solution.

**Comment by LenzGr** [comment]
Thanks for the explanation, Dwight!
