### ISSUE TITLE
symbol lookup error: lxc-create: undefined symbol: strlcpy

### ISSUE THREAD

**Issue by MK27** [lxc/lxc#3960]
# Required information

 * Distribution: Debian
 * Distribution version: 9.13
 * The output of
   * `lxc-start --version` 2.0.7
   * `lxc-checkconfig` 
LXC version 2.0.7                                                                                                                                                                                                 
--- Namespaces ---                                                                                                                                                                                                
Namespaces: enabled                                                                                                                                                                                               
Utsname namespace: enabled                                                                                                                                                                                        
Ipc namespace: enabled      
Pid namespace: enabled
User namespace: enabled
newuidmap is not installed                                         
newgidmap is not installed                                   
Network namespace: enabled
Multiple /dev/pts instances: enabled
                            
--- Control groups ---
Cgroups: enabled
Cgroup namespace: missing

Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/pids
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/blkio
/sys/fs/cgroup/devices
/sys/fs/cgroup/memory
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/freezer
/sys/fs/cgroup/net_prio

Cgroup v2 mount points:

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, not loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, not loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: missing
CONFIG_INET_DIAG: missing
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: missing
File capabilities:

   * `uname -a`

Linux tinkerboard 4.4.132+ #3 SMP Sat Apr 3 07:44:55 EDT 2021 armv7l GNU/Linux

   * `cat /proc/self/cgroup`

 10:net_prio:/
9:freezer:/
8:cpuset:/
7:memory:/user.slice/user-0.slice/session-c68.scope
6:devices:/user.slice/user-0.slice/session-c68.scope
5:blkio:/user.slice/user-0.slice/session-c68.scope
4:cpu,cpuacct:/user.slice/user-0.slice/session-c68.scope
3:perf_event:/
2:pids:/user.slice/user-0.slice/session-c68.scope
1:name=systemd:/user.slice/user-0.slice/session-c68.scope

   * `cat /proc/1/mounts`

/dev/root / ext4 rw,noatime,data=ordered 0 0
devtmpfs /dev devtmpfs rw,relatime,size=1019936k,nr_inodes=186384,mode=755 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,mode=755 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_prio 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
sunrpc /run/rpc_pipefs rpc_pipefs rw,relatime 0 0
nfsd /proc/fs/nfsd nfsd rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
/dev/mmcblk0p1 /boot vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro 0 0
/dev/sda1 /mnt/usb ext4 rw,noatime,data=ordered 0 0
adb /dev/usb-ffs/adb functionfs rw,relatime 0 0
tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=205728k,mode=700 0 0

# Issue description

This is an old-ish Debian armhf system on an Asus tinkerboard; it can't be easily upgraded, and the stock `lxc-create` craps out on template directives for newer images (the reason I want to do this is to create a build environment with a gcc that implements all of C++17).

I've tried building with the current master branch and with stable-4.0.   The build seems to go fine, the problem occurs when running `lxc-create` and is much the same as: https://github.com/lxc/lxc/issues/2436  

    > lxc-create -t download -n foobar
    lxc-create: symbol lookup error: lxc-create: undefined symbol: strlcpy

`configure.log` catches the strlcat/cpy problem:
 
    /usr/local/src/lxc/conftest.c:110: undefined reference to `strlcpy'
    /usr/local/src/lxc/conftest.c:110: undefined reference to `strlcat'

**Comment by brauner** [comment]
LXC 2.* is end of life so we won't be making a bugfix release for this unfortunately. But I put up a fix for our master branch.

**Comment by MK27** [comment]
> LXC 2.* is end of life so we won't be making a bugfix release for this unfortunately. But I put up a fix for our master branch.

I was just going to come back here and comment on that -- I was using the master and stable-40 branch.  Because the version reports wrong,  I though perhaps I had pulled the repo wrong, so I've gone through this again.  Here's the funny bit: After make install, `/usr/local/bin/lxc-create` reports as 2.0.7 and throws the undefined symbol error.  So does `lxc/src/lxc/.libs/lxc-create` (which is what make installed).  However, `lxc/src/lxc/lxc-create` (the shell script one level up) reports **4.0.10**.  But there's more: `lxc/src/lxc/.libs/lt-lxc-create` (something which is not installed by make) reports 4.0.10 and !! *works when `lxc-create` in the same directory does not*.  So right now it appears I've gotten my wish (it installed a fedora 35 image), hopefully I can sort it out (since other commands like `lxc-start` also report `2.0.7` and do not have an `lt-` version).

I'm going to ask about this in https://discuss.linuxcontainers.org/ before reporting it as a separate issue (which would resolve this one).
