### ISSUE TITLE
lxc fails to cross build from source as a Debian package due to the handling of %m

### ISSUE THREAD

**Issue by helmutg** [lxc/lxc#3961]
lxc used to cross build as a Debian package, but no longer does.

# Required information

 * Distribution: Debian
 * Distribution version: unstable
 * Version of the package: 1:4.0.10-1
 * The output of various tools is unavailable as this is a build failure

# Issue description

It gained a new check for the `%m` format specifier. That check is a `AC_RUN_IFELSE` check that cannot be performed during cross compilation. Instead it defensively errs on `%m` being unavailable during cross compilation while it is normally available on native builds with glibc. As such `HAVE_M_FORMAT` is not set during cross builds. As a consequence, conditional compilation causes different source code to be compiled and that normally dead code causes a compilation failure:

    In file included from criu.c:22:
    criu.c: In function ‘exec_criu’:
    log.h:378:2: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
      378 |  LXC_ERROR(&locinfo, format, ##__VA_ARGS__);   \
          |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    log.h:459:3: note: in expansion of macro ‘ERROR’
      459 |   ERROR("%s - " format, ptr, ##__VA_ARGS__); \
          |   ^~~~~
    log.h:493:3: note: in expansion of macro ‘SYSERROR’
      493 |   SYSERROR(format, ##__VA_ARGS__);              \
          |   ^~~~~~~~
    criu.c:324:11: note: in expansion of macro ‘log_error_errno’
      324 |    return log_error_errno(-ENOMEM, ENOMEM, "Failed to remove extraneous slashes from \"%s\"", tmp);
          |           ^~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

I think it would be best to have the cross build resemble a native build. As such using the `%m` format during cross builds would be good. A very simple way to get there is wrapping the relevant check in `AC_CACHE_CHECK` to allow cross builders to supply a result for it instead of performing the test. Another way would be hard coding the expected result (i.e. enable `%m` whenever encountering glibc unless building natively where the check can be performed).

Additionally, the code path where `HAVE_M_FORMAT` is unset should be fixed to compile.

# Steps to reproduce

    sbuild -d unstable --host=s390x lxc

# Information to attach

* You can find cross build logs at http://crossqa.debian.net/src/lxc
* This issue is tracked in Debian as https://bugs.debian.org/993380

**Comment by brauner** [comment]
Thanks for the report. I think the easiest fix is to just use `__GNU_LIBRARY__`.

**Comment by brauner** [comment]
Sent a PR for this just now.

**Comment by asac** [comment]
@brauner  fyi, I still see the null check error when using musl cross compiler after cherry picking your commit to stable-4.0....

**Comment by asac** [comment]
.... also checking for __MUSL__ on top of __GNU_LIBRARY__ fixed the build failure for me ....
