### ISSUE TITLE
`lxc-ls --active` does not list containers with whitespaces.

### ISSUE THREAD

**Issue by denisfa** [lxc/lxc#3970]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: archlinux
 * The output of
   * `lxc-start --version` 4.0.10

# Issue description

`lxc-ls --active` fails to list containers with whitespace in its name. The reason is that the function `list_active_containers` parses line by line of `/proc/net/unix` and  goes for the furthest whitespace char it can locate for the socket entry. As for an example:

```
...
00000000ae44e167: 00000002 00000000 00010000 0001 01 622302 @/home/denisfa/.local/share/lxc/arch/command
00000000a97d8962: 00000002 00000000 00010000 0001 01 624583 @/home/denisfa/.local/share/lxc/arch linux/command
...
```

Notice the whitespace on `arch linux`. This is where the function tries to locate the socket entry.

# Steps to reproduce

 1. Create 2 containers

```
lxc-create -t download -n arch -- -d archlinux -r current -a amd64
lxc-create -t download -n "arch linux" -- -d archlinux -r current -a amd64
```

 2. Start both containers

```
lxc-start arch
lxc-start arch\ linux
```

 3. `lxc-ls --active` outputs

```
arch
```

instead of
```
arch       arch linux
```

**Comment by mihalicyn** [comment]
replaced by https://github.com/lxc/lxc/pull/4422

**Comment by mihalicyn** [comment]
Fixed in https://github.com/lxc/lxc/pull/4422
