### ISSUE TITLE
Unable to start container with nesting

### ISSUE THREAD

**Issue by deric** [lxc/lxc#398]
I'm trying to start nested lxc with Debian Jessie on machine with Ubuntu 14.04

```
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = lxcbr0
lxc.network.hwaddr = 00:16:3e:05:8f:0a
lxc.rootfs = /var/lib/lxc/jessie/rootfs
lxc.include = /usr/share/lxc/config/debian.common.conf
lxc.mount = /var/lib/lxc/jessie/fstab
lxc.utsname = jessie
lxc.arch = amd64
lxc.aa_profile = lxc-container-default-with-nesting
lxc.mount.auto = cgroup
lxc.cgroup.cpuset.cpus = 2-10
lxc.cgroup.memory.limit_in_bytes = 16G
# systemd bug
lxc.kmsg = 0
lxc.autodev = 1
lxc.start.auto = 1
lxc.start.delay = 5
```

`$ cat /proc/cgroups`

```
#subsys_name    hierarchy   num_cgroups enabled
cpuset  2   6   1
cpu 3   6   1
cpuacct 4   6   1
memory  5   6   1
devices 6   6   1
freezer 7   6   1
blkio   8   6   1
perf_event  9   6   1
hugetlb 10  6   1
```

`$ dpkg -l | egrep "(cgroup|cgmanager|lxc)"`

```
ii  cgmanager                             0.24-0ubuntu7.1                      amd64        Central cgroup manager daemon
ii  cgmanager-tests                       0.24-0ubuntu7.1                      amd64        Central cgroup manager daemon (tests)
ii  cgroup-lite                           1.9                                  all          Light-weight package to set up cgroups at system boot
ii  libcgmanager0:amd64                   0.24-0ubuntu7.1                      amd64        Central cgroup manager daemon (client library)
rc  liblxc0                               1.0.0~alpha1-0ubuntu14~ubuntu12.04.1 amd64        Linux Containers userspace tools (library)
ii  liblxc1                               1.0.6-0ubuntu0.1                     amd64        Linux Containers userspace tools (library)
ii  lxc                                   1.0.6-0ubuntu0.1                     amd64        Linux Containers userspace tools
ii  lxc-docker                            1.2.0                                amd64        Linux container runtime
rc  lxc-docker-0.10.0                     0.10.0                               amd64        Linux container runtime
rc  lxc-docker-0.7.6                      0.7.6                                amd64        Linux container runtime
rc  lxc-docker-0.8.1                      0.8.1                                amd64        Linux container runtime
ii  lxc-docker-1.2.0                      1.2.0                                amd64        Linux container runtime
ii  lxc-templates                         1.0.6-0ubuntu0.1                     amd64        Linux Containers userspace tools (templates)
ii  lxctl                                 0.3.1+debian-3                       all          Utility to manage LXC
ii  python3-lxc                           1.0.6-0ubuntu0.1                     amd64        Linux Containers userspace tools (Python 3.x bindings)
```

and here's output of lxc-start: http://paste.ubuntu.com/9731254/

Potential source of problems could be `systemd` in jessie container, however I was able to start this container before.

`lxc-checkconfig`:

```
Kernel configuration found at /boot/config-3.13.0-44-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

```

**Comment by deric** [comment]
Looks like nesting it not important, same problem without
```
lxc.aa_profile = lxc-container-default-with-nesting
```
however restarting `cgmanager` does help.

**Comment by deric** [comment]
With following profile I managed to start the LXC, however the default one in Ubuntu doesn't work:
```
profile lxc-container-with-nesting flags=(attach_disconnected,mediate_deleted) {
  network,
  capability,
  file,
  umount,

  # addition for container nesting
  mount -> /sys/fs/cgroup/**,
  mount fstype=proc -> /var/cache/lxc/**,
  mount fstype=sysfs -> /var/cache/lxc/**,
  mount fstype=devpts -> /dev/pts/,
  mount -> /usr/lib/lxc/root/,
  mount -> /usr/lib/lxc/root/**,
  mount /dev/pts/ptmx/ -> /dev/ptmx/,
  pivot_root,
  change_profile -> lxc-*,

  # ignore DENIED message on / remount
  deny mount options=(ro, remount) -> /,

  # allow tmpfs mounts everywhere
  mount fstype=tmpfs,

  # allow mqueue mounts everywhere
  mount fstype=mqueue,

  # allow bind mount of /lib/init/fstab for lxcguest
  mount options=(rw, bind) /lib/init/fstab.lxc/ -> /lib/init/fstab/,

  # deny writes in /proc/sys/fs but allow fusectl to be mounted
  mount fstype=binfmt_misc -> /proc/sys/fs/binfmt_misc/,
  deny @{PROC}/sys/fs/** wklx,

  # block some other dangerous paths
  deny @{PROC}/sysrq-trigger rwklx,
  deny @{PROC}/mem rwklx,
  deny @{PROC}/kmem rwklx,
  deny @{PROC}/sys/kernel/** wklx,

  # deny writes in /sys except for /sys/fs/cgroup, also allow
  # fusectl, securityfs and debugfs to be mounted there (read-only)
  mount fstype=fusectl -> /sys/fs/fuse/connections/,
  mount fstype=securityfs -> /sys/kernel/security/,
  mount fstype=debugfs -> /sys/kernel/debug/,
  deny mount fstype=debugfs -> /var/lib/ureadahead/debugfs/,
  mount fstype=proc -> /proc/,
  mount fstype=sysfs -> /sys/,
  deny /sys/[^f]*/** wklx,
  deny /sys/f[^s]*/** wklx,
  deny /sys/fs/[^c]*/** wklx,
  deny /sys/fs/c[^g]*/** wklx,
  deny /sys/fs/cg[^r]*/** wklx,
}
```

**Comment by stgraber** [comment]
Kinda hard to tell exactly what you changed in that profile.

Anyway, nested Ubuntu containers should work perfectly on 14.04 (I use that all the time). Nested through Debian jessie with systemd may be much harder due to cgroup configurations and systemd just not really well working with current LXC 1.0 (we basically just solved most of that last week in git master).

**Comment by stgraber** [comment]
Can you provide a diff of what you actually changed in the profile to see if that's indeed a bug and something we should include upstream (vs a known systemd limitation that'd cripple security should we merge that change)?

**Comment by deric** [comment]
The original profile looks like this:
```
profile lxc-container-default-with-nesting flags=(attach_disconnected,mediate_deleted) {
  mount fstype=proc -> /var/cache/lxc/**,
  mount fstype=sysfs -> /var/cache/lxc/**,
  mount options=(rw,bind) /var/cache/lxc/**/dev/shm/ -> /var/cache/lxc/**/run/shm/,
}
```

**Comment by stgraber** [comment]
Ok.

Can you try re-running your workload with the original profile and then look at the "dmesg" output for apparmor denials? That'd more specifically tell you what's wrong.

**Comment by deric** [comment]
Here's the complete `TRACE` log: http://paste.ubuntu.com/10369476/

* `lxc`: 1.0.7-0ubuntu0.1
* `cgmanager`: 0.24-0ubuntu7.3

**Comment by KenSharp** [comment]
>nested Ubuntu containers should work perfectly on 14.04

Fails miserably here on 14.04.

>W: Failure trying to run: chroot /var/cache/lxc/trusty/partial-i386 mount -t proc proc /proc
>W: See /var/cache/lxc/trusty/partial-i386/debootstrap/debootstrap.log for details
>lxc-create: lxccontainer.c: create_run_template: 1201 container creation template for trusty-nested failed
>lxc-create: lxc_create.c: main: 274 Error creating container trusty-nested

*/var/cache/lxc/trusty/partial-i386* doesn't even exist.

- `lxc`: 1.1.5-0ubuntu3~ubuntu14.04.1~ppa1
- `cgmanager`: 0.39-2ubuntu2~ubuntu14.04.1~ppa1

I tried @deric's apparmor profile but it still doesn't work.

Tried the daily too, same result.
- `lxc`: 1.1.5+master~20151208-0111-0ubuntu1~trusty

**Comment by KenSharp** [comment]
I guess AA is still blocking it, then:

>kernel: [49594.564711] type=1400 audit(1449734556.689:224): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default" name="/run/lxcfs/controllers/cpuset/" pid=8424 comm="lxcfs" fstype="cgroup" srcname="cpuset" flags="rw"
>kernel: [49830.420246] type=1400 audit(1449734792.545:232): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default" name="/var/cache/lxc/trusty/partial-i386/proc/" pid=14009 comm="mount" fstype="proc" srcname="proc" flags="ro

**Comment by hallyn** [comment]
Debian Jessie runs systemd which wants to mount cgroups.  The mount of cgroupfs is not allowed.  Is lxcfs installed?  Do you have 'lxc.mount.auto = proc:mixed sys:mixed cgroup:mixed' in your config?

**Comment by KenSharp** [comment]
>Is lxcfs installed?

Yup.

>Do you have 'lxc.mount.auto = proc:mixed sys:mixed cgroup:mixed' in your config?
Which config? /etc/lxc/default.conf on the host? In the parent container? I added it to the parent container but it didn't help.

Also tried `lxc-create -f /usr/share/lxc/config/nesting.conf ...` but same thing.

**Comment by hallyn** [comment]
the lxc.mount.auto line goes into your container configuration.  It really should
already be in one of the included files under /usr/share/lxc/config, I was just
grasping at straws.

Can you show the DENIED messages from your run when using

lxc-create -f /usr/share/lxc/config/nesting.conf

?  Bc while it may still fail it should fail differently, since the
nesting profile should give the rights to mount those.

**Comment by KenSharp** [comment]
I've just got  2.0.0~rc2-0ubuntu2~ubuntu14.04.1~ppa1 and tried again:

`Feb 25 09:40:13 kernel: [168752.898508] type=1400 audit(1456393213.807:93): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default" pid=16747 comm="apparmor_parser"`
`Feb 25 09:40:13 kernel: [168752.902072] type=1400 audit(1456393213.811:94): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxc-container-default-cgns" pid=16747 comm="apparmor_parser"`
`Feb 25 09:40:13 kernel: [168752.903960] type=1400 audit(1456393213.811:95): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default-with-mounting" pid=16747 comm="apparmor_parser"`
`Feb 25 09:40:13 kernel: [168752.906354] type=1400 audit(1456393213.815:96): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxc-container-default-with-nesting" pid=16747 comm="apparmor_parser"`
`Feb 25 09:40:14 kernel: [168753.197804] type=1400 audit(1456393214.107:97): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/bin/lxc-start" pid=16753 comm="apparmor_parser"`
`Feb 25 09:47:38 kernel: [169197.353080] lxcbr0: port 1(vethRT7XQB) entered forwarding state`
`Feb 25 09:47:38 kernel: [169197.353095] lxcbr0: port 1(vethRT7XQB) entered forwarding state`
`Feb 25 09:47:38 kernel: [169197.358799] lxcbr0: port 1(vethRT7XQB) entered disabled state`
`Feb 25 09:47:38 kernel: [169197.578708] lxcbr0: port 1(vethRT7XQB) entered forwarding state`
`Feb 25 09:47:38 kernel: [169197.578783] lxcbr0: port 1(vethRT7XQB) entered forwarding state`
`Feb 25 09:47:42 kernel: [169201.664537] type=1400 audit(1456393662.575:98): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default" name="/sys/" pid=28159 comm="mount" flags="rw, nosuid, nodev, noexec, remount"`
`Feb 25 09:47:53 kernel: [169212.608046] lxcbr0: port 1(vethRT7XQB) entered forwarding state`
`Feb 25 10:04:36 kernel: [170215.113727] type=1400 audit(1456394676.023:101): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default" name="/run/lxcfs/controllers/name=systemd/" pid=10466 comm="lxcfs" fstype="cgroup" srcname="name=systemd" flags="rw"`
`Feb 25 10:04:36 kernel: [170215.249404] type=1400 audit(1456394676.159:102): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default" name="/run/lxcfs/controllers/name=systemd/" pid=10472 comm="lxcfs" fstype="cgroup" srcname="name=systemd" flags="rw"`
`Feb 25 10:04:36 kernel: [170215.334653] type=1400 audit(1456394676.243:103): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default" name="/run/lxcfs/controllers/name=systemd/" pid=10480 comm="lxcfs" fstype="cgroup" srcname="name=systemd" flags="rw"`
`Feb 25 10:04:36 kernel: [170215.432740] type=1400 audit(1456394676.343:104): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default" name="/run/lxcfs/controllers/name=systemd/" pid=10485 comm="lxcfs" fstype="cgroup" srcname="name=systemd" flags="rw"`
`Feb 25 10:04:36 kernel: [170215.605945] type=1400 audit(1456394676.515:106): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default" name="/run/lxcfs/controllers/name=systemd/" pid=10495 comm="lxcfs" fstype="cgroup" srcname="name=systemd" flags="rw"`
`Feb 25 10:04:36 kernel: [170215.689186] type=1400 audit(1456394676.599:107): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default" name="/run/lxcfs/controllers/name=systemd/" pid=10501 comm="lxcfs" fstype="cgroup" srcname="name=systemd" flags="rw"`
`Feb 25 10:04:36 kernel: [170215.821847] type=1400 audit(1456394676.731:108): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default" name="/run/lxcfs/controllers/name=systemd/" pid=10508 comm="lxcfs" fstype="cgroup" srcname="name=systemd" flags="rw"`
`Feb 25 10:04:36 kernel: [170215.960666] type=1400 audit(1456394676.871:109): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default" name="/run/lxcfs/controllers/name=systemd/" pid=10513 comm="lxcfs" fstype="cgroup" srcname="name=systemd" flags="rw"`
`Feb 25 10:04:36 kernel: [170216.052626] type=1400 audit(1456394676.963:110): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default" name="/run/lxcfs/controllers/name=systemd/" pid=10519 comm="lxcfs" fstype="cgroup" srcname="name=systemd" flags="rw"`
`Feb 25 10:12:05 kernel: [170664.332790] type=1400 audit(1456395125.243:112): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default" name="/var/cache/lxc/trusty/partial-i386/proc/" pid=16561 comm="mount" fstype="proc" srcname="proc" flags="rw"`
`Feb 25 10:12:05 kernel: [170664.332922] type=1400 audit(1456395125.243:113): apparmor="DENIED" operation="mount" info="failed type match" error=-13 profile="lxc-container-default" name="/var/cache/lxc/trusty/partial-i386/proc/" pid=16561 comm="mount" fstype="proc" srcname="proc" flags="ro"`

**Comment by hallyn** [comment]
I'm not sure what you're running inside what, but if you're running a nested container nest1 in a parent container parent1, is parent1 definately running in the lxc-container-default-with-nesting profile?  (it's hard to tell from your syslog since lxc-container-default-with-nesting allows transitioning to lxc-container-default)

**Comment by KenSharp** [comment]
Sorry, my stupid mistake, ignore all that previous rubbish.

Starting correctly it fails instantly:

    Feb 27 12:43:02 kernel: [76720.265713] type=1400 audit(1456576982.025:104): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxc-container-default-with-nesting" name="/sys/" pid=8613 comm="mount" flags="rw, nosuid, nodev, noexec, remount"

**Comment by KenSharp** [comment]
I tried removing the AA restriction just so that I could get it working, but I get:

    $ sudo apparmor_parser -R /etc/apparmor.d/lxc/lxc-default-with-nesting
    Found reference to variable PROC, but is never declared

Could that offer a clue? The restriction remains in place.

**Comment by DavidVentura** [comment]
I know this is old but I found the same error.
I "fixed" it by commenting all lines containing PROC on
`/etc/apparmor.d/abstractions/lxc/container-base`

**Comment by Akronix** [comment]
We were experiencing this issue with the following configuration:

Host Machine: Ubuntu 16.04
Virtual Machine (lxc): Debian jessie
A series of different lxc and docker containers inside the VM.

We were getting an error related to lxc-net. I think it was this one:
`Failed to start LSB: Bring up/down LXC Network Bridge.`

Uncomenting `lxc.include = /usr/share/lxc/config/nesting.conf` didn't fix the problem.

We fixed the problem after upgrading Debian jessie to Debian stretch 9.3 (stable)

**Comment by brauner** [comment]
AppArmor stacking is enabled on newer kernels also there was a bug in AppArmor that prevented containers from being started. The mount feature detection in AppArmor was wrong.

**Comment by Akronix** [comment]
So What are the workarounds for older kernels? Just upgrade to newer kernels?

**Comment by brauner** [comment]
@Akronix since the issue you were having is likely a kernel bug I'd say yes, upgrading is your best bet. If this is really the AppArmor bug then there's nothing that liblxc can do.
