### ISSUE TITLE
Can't kill forked processes

### ISSUE THREAD

**Issue by deric** [lxc/lxc#399]
I'm trying to compile Mesos subproject which includes tests for forking and reparenting processes, the source code is available here: https://github.com/deric/libprocess

One of the tests is creating a tree of processes https://github.com/deric/libprocess/blob/master/3rdparty/stout/tests/os_tests.cpp#L626

``` cpp
Try<ProcessTree> tree =
    Fork(dosetsid,        // Child.
         Fork(None(),     // Grandchild.
              Fork(None(),
                   Exec("sleep 100")),
              Exec("sleep 100")),
         Exec("exit 0"))();
```

and then killing the child and expecting that tree will be reparented to PID 1 (init). However this does not happen.

```
grandchild tree:
-+- 24125 sh -c sleep 100 
 \--- 24126 sh -c sleep 100 
grandchild:
24125
stout/tests/os_tests.cpp:687: Failure
Value of: os::exists(grandchild)
  Actual: false
Expected: true
```

I'm not sure if there is a problem with mapping PIDs, because some have processes have small number. Anyway the `os::exists()` util doesn't seem to work correctly in container.

```
root       402  0.0  0.0 104084  2788 ?        S    Jan13   0:01 ./stout-tests
```

and some are pretty high `24133`.

Processes created this way are indestructible, I can't kill them from the container nor from the host.

Tested on `lxc 1.0.6-0ubuntu0.1`

**Comment by deric** [comment]
the code for checking that process exists is here: https://github.com/deric/libprocess/blob/master/3rdparty/stout/include/stout/os/exists.hpp#L39

**Comment by stgraber** [comment]
Are you running that code through lxc-attach?

If you are, then technically whatever you execute isn't a child of PID 1 but of the process which lxc-attach spawns in the container (that is, you have more than one root PID in the container).

If that's the case, then it's the expected behaviour, even if that may look a bit odd.

**Comment by deric** [comment]
No, I'm running that code from a ssh session inside the container. From `ps aux` inside container I see the PID 1 process:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  28104  3036 ?        Ss   Jan13   0:14 /sbin/init
root       402  0.0  0.0 104084  2776 ?        S    Jan13   0:28 ./stout-tests
root     24044  0.0  0.0 104084  2768 ?        S    Jan14   0:26 ./stout-tests
root     24133  0.0  0.0 104084   720 ?        S    Jan14   0:26 ./stout-tests
root     24679  0.0  0.0 104084  2772 ?        S    Jan14   0:27 ./stout-tests
root     25040  0.0  0.0 104088  2776 ?        S    Jan14   0:26 ./stout-tests
```

**Comment by stgraber** [comment]
Can you try "ps -eo pid,ppid,cmd" and see what the ppid is?

**Comment by deric** [comment]
```
$ ps -eo pid,ppid,cmd
  PID  PPID CMD
    1     0 /sbin/init
   18     1 /lib/systemd/systemd-udevd
   20     1 /lib/systemd/systemd-journald
   79     1 /usr/sbin/sshd -D
   80     1 /usr/sbin/atd -f
   81     1 /usr/sbin/cron -f
   83     1 /lib/systemd/systemd-logind
   85     1 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
  100     1 /sbin/agetty --noclear tty1 linux
  101     1 /sbin/agetty --noclear --keep-baud console 115200 38400 9600 linux
  340     1 /usr/sbin/exim4 -bd -q30m
  402     1 ./stout-tests
24044     1 ./stout-tests
24133     1 ./stout-tests
24679     1 ./stout-tests
25040     1 ./stout-tests
29650    79 sshd: root@pts/3    
29652 29650 -bash
29661 29652 ps -eo pid,ppid,cmd
```
any idea why I can't kill those processes?

**Comment by stgraber** [comment]
So even a kill -9 doesn't get rid of them?

Anything suspicious in your kernel.log/dmesg?

**Comment by deric** [comment]
No, event as `root` is says permission denied.
```
root|localhost:~  $ kill -9 402
-bash: kill: (402) - Permission denied
root|localhost:~  $ sudo kill -9 402
root|localhost:~  $ ps aux | grep 402
root       402  0.0  0.0 104084  2776 ?        S    Jan13   0:33 ./stout-tests
```

**Comment by stgraber** [comment]
And can you kill them from the host?

**Comment by deric** [comment]
No, that's also impossible.

**Comment by stgraber** [comment]
Can you paste the last few lines of dmesg?

**Comment by deric** [comment]
There's nothing related to this lxc, just when I was trying to attach to the process, the apparmor didn't like it.
```
kernel: [1270843.097511] type=1400 audit(1422429421.384:44423): apparmor="DENIED" operation="ptrace" profile="
lxc-container-with-nesting" pid=2871 comm="systemd-journal" requested_mask="readby" denied_mask="readby" peer="lxc-container-with-nes
ting"
```

**Comment by brauner** [comment]
It's hard to figure out now what has been going on here. It would be good if you could re-open if this is still an issue on current git master.

**Comment by sherpya** [comment]
I have similar problem, linux stretch host with 3.0.2, container with a squeeze distro (but I've also noticied it sporadically on a stretch container too).
I have apache2 master process, SIGTERM does not reaches the target process, from inside or outside, SIGKILL effectively does work.
I've tested it also while stracing the target process e no signal arrives at all, I've tried other signals (SIGHUP, SIGUSR1) and they worked as expected.
The result is I cannot gracefully stop apache2 in the container.
There is something I can do to further debug?

**Comment by sherpya** [comment]
Looks like only child launched from lxc-attach are affected

**Comment by brauner** [comment]
Do you have a reproducer, you can paste here?

**Comment by sherpya** [comment]
what do you need? strace? lxc debug log says nothing intrestring

**Comment by sherpya** [comment]
it's not related to #313, I've tried to comment out the SIG_IGN command but it does the same

**Comment by sherpya** [comment]
it happens also with 3.0.0, but if I run 2.0.7 version of lxc-attach on version 3.0.2 started container the problem is not exposed, is very annoying since if I update a package in a container the daemon is resterted and it cannot be stopped (except using -9)

**Comment by sherpya** [comment]
[straced.txt](https://github.com/lxc/lxc/files/2453511/straced.txt)

strace output of `lxc-attach -n bareos cat`, the cat process is not killable with signal 15 (at the end of the log there are not signals detected), I suppose it is a different bug anyway

**Comment by brauner** [comment]
@sherpya, this should be fixed by https://github.com/lxc/lxc/pull/2677 .

**Comment by sherpya** [comment]
@brauner confirmed working on master and 3.0.2 thanks
