### ISSUE TITLE
Failed to remount the root path as read-only  in the container 

### ISSUE THREAD

**Issue by gaohuatao-1** [lxc/lxc#3999]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution:
 * Distribution version:
$ lxc-start --version
4.0.3
$  lxc-checkconfig
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-5.6.16-300.fc32.x86_64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Warning: newuidmap is not setuid-root
Warning: newgidmap is not setuid-root
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/systemd
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/pids
/sys/fs/cgroup/blkio
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/freezer
/sys/fs/cgroup/memory
/sys/fs/cgroup/devices

Cgroup v2 mount points:
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities:

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/local/bin/lxc-checkconfig

$ uname -a 
Linux fedora 5.6.16-300.fc32.x86_64

# Issue description

In this case, I use iSulad container engine  to run container.  Failed to remount the root path in the container as read-only because the lxc-start process opened the file named ".lxc_keep". This behavior of lxc is inconsistent with that of runc. In some scenarios, we need to remount rootfs as read-only. So,  can we remove the action of opening the lxc-keep file in lxc-start process?  What are the consequences， if we do that. Looking forward to your reply

# Steps to reproduce

 1. isula run -tid -cap-add sys_admin ubuntu bash
 87b0d463416916bb95f87b88ecbace1fb1d2f98ace0b1da9eada0430ba22aa3a
 2. isula exec -ti 87b0d463416916bb95f87b88ecbace1fb1d2f98ace0b1da9eada0430ba22aa3a
 $ mount -o remount,ro /
mount: / is busy

# Information to attach
$ ps -ef |grep lxc
root     1501849       1  1 16:40 ?        00:00:00 [lxc monitor] /var/lib/isulad/engines/lcr 87b0d463416916bb95f87b88ecbace1fb1d2f98ace0b1da9eada0430ba22aa3a
 $ lsof -p 1501849 |grep lxc-keep
lxc-start 1501849 root   32u      REG               0,54        0   68401547 /var/lib/isulad/storage/overlay/87b0d463416916bb95f87b88ecbace1fb1d2f98ace0b1da9eada0430ba22aa3a/merged/.lxc-keep (deleted)

**Comment by brauner** [comment]
> In this case, I use iSulad container engine to run container. Failed to remount the root path in the container as read-only because the lxc-start process opened the file named ".lxc_keep". This behavior of lxc is inconsistent with that of runc. In some scenarios, we need to remount rootfs as read-only. So, can we remove the action of opening the lxc-keep file in lxc-start process? What are the consequences， if we do that. Looking forward to your reply

Hi,

When starting container LXC with a separate read-write rootfs LXC will open a read-write `.lxc_keep` file to ensure that on container shutdown or while the container is running the underlying filesystem cannot be remounted read-only. If we would not do that and `/var/lib/lxc` would be a separate filesystem then the init system on shutdown or a user using `mount -o remount,ro /` would cause the whole underlying filesystem, i.e. `/var/lib/lxc` to become read-only on shutdown. If we stop keeping `.lxc_keep` open we would effectively allow privileged containers not making use of additional security layers through LSMs such as AppArmor to remount a filesystem read-only affecting the host.

**Comment by gaohuatao-1** [comment]
> > In this case, I use iSulad container engine to run container. Failed to remount the root path in the container as read-only because the lxc-start process opened the file named ".lxc_keep". This behavior of lxc is inconsistent with that of runc. In some scenarios, we need to remount rootfs as read-only. So, can we remove the action of opening the lxc-keep file in lxc-start process? What are the consequences， if we do that. Looking forward to your reply
> 
> Hi,
> 
> When starting container LXC with a separate read-write rootfs LXC will open a read-write `.lxc_keep` file to ensure that on container shutdown or while the container is running the underlying filesystem cannot be remounted read-only. If we would not do that and `/var/lib/lxc` would be a separate filesystem then the init system on shutdown or a user using `mount -o remount,ro /` would cause the whole underlying filesystem, i.e. `/var/lib/lxc` to become read-only on shutdown. If we stop keeping `.lxc_keep` open we would effectively allow privileged containers not making use of additional security layers through LSMs such as AppArmor to remount a filesystem read-only affecting the host.

![image](https://user-images.githubusercontent.com/22569211/137831563-bc7359e3-6ee9-4a75-b357-9a9e310b0697.png)

Thanks \Hi

**Comment by gaohuatao-1** [comment]
> > In this case, I use iSulad container engine to run container. Failed to remount the root path in the container as read-only because the lxc-start process opened the file named ".lxc_keep". This behavior of lxc is inconsistent with that of runc. In some scenarios, we need to remount rootfs as read-only. So, can we remove the action of opening the lxc-keep file in lxc-start process? What are the consequences， if we do that. Looking forward to your reply
> 
> Hi,
> 
> When starting container LXC with a separate read-write rootfs LXC will open a read-write `.lxc_keep` file to ensure that on container shutdown or while the container is running the underlying filesystem cannot be remounted read-only. If we would not do that and `/var/lib/lxc` would be a separate filesystem then the init system on shutdown or a user using `mount -o remount,ro /` would cause the whole underlying filesystem, i.e. `/var/lib/lxc` to become read-only on shutdown. If we stop keeping `.lxc_keep` open we would effectively allow privileged containers not making use of additional security layers through LSMs such as AppArmor to remount a filesystem read-only affecting the host.

Hi, Thanks  for your reply.
I have some questions about the last sentence,  "If we stop keeping `.lxc_keep` open we would effectively allow privileged containers not making use of additional security layers through LSMs such as AppArmor to remount a filesystem read-only affecting the host."

When the overlay file system is used to provide rootfs for container, the root path of lxc container is a directory on the host, such as "/var/lib/isulad/storage/overlay/merged".  So, remounting / as read-only in the container cannot affect the host, because the root path of the container just is a regular dir on the host and we cannot remount the root path of the host as read-only.
Looking forward to your answers.

**Comment by brauner** [comment]
> > > In this case, I use iSulad container engine to run container. Failed to remount the root path in the container as read-only because the lxc-start process opened the file named ".lxc_keep". This behavior of lxc is inconsistent with that of runc. In some scenarios, we need to remount rootfs as read-only. So, can we remove the action of opening the lxc-keep file in lxc-start process? What are the consequences， if we do that. Looking forward to your reply
> > 
> > 
> > Hi,
> > When starting container LXC with a separate read-write rootfs LXC will open a read-write `.lxc_keep` file to ensure that on container shutdown or while the container is running the underlying filesystem cannot be remounted read-only. If we would not do that and `/var/lib/lxc` would be a separate filesystem then the init system on shutdown or a user using `mount -o remount,ro /` would cause the whole underlying filesystem, i.e. `/var/lib/lxc` to become read-only on shutdown. If we stop keeping `.lxc_keep` open we would effectively allow privileged containers not making use of additional security layers through LSMs such as AppArmor to remount a filesystem read-only affecting the host.
> 
> Hi, Thanks for your reply. I have some questions about the last sentence, "If we stop keeping `.lxc_keep` open we would effectively allow privileged containers not making use of additional security layers through LSMs such as AppArmor to remount a filesystem read-only affecting the host."
> 
> When the overlay file system is used to provide rootfs for container, the root path of lxc container is a directory on the host, such as "/var/lib/isulad/storage/overlay/merged". So, remounting / as read-only in the container cannot affect the host, because the root path of the container just is a regular dir on the host and we cannot remount the root path of the host as read-only. Looking forward to your answers.

We need to distinguish between making the superblock or making a single mountpoint read-only. If you issue a `mount -o remount,ro /` then the `mount` tool will take that to mean to make the whole underlying filesystem read-only. If you're using a read-write overlayfs __filesystem__ using the contents of one or multiple directories on the host as lower directories and providing the container's rootfs as an upper directory the `mount -o remount,ro /` issued from within the container will turn the overlayfs filesystem read-only. But if you weren't using a separate overlayfs fielsystem you'd turn the underlying filesystem read-only, i.e. the host (in case it's not - which is very likely - EBUSY). We can't distinguis this case easily.


, i.e. will translate this to `MS_REMOUNT | MS_RDONLY

Right, but then your filesystem that you're remounting is the relevant overlayfs filesyste.
Right, but then your filesystem that you're remounting is the relevant overlayfs filesyste.
