### ISSUE TITLE
Container failing to start (Ubuntu 14.10)

### ISSUE THREAD

**Issue by mandeepsandhu** [lxc/lxc#400]
I've had a working container for some time now. Recently, I started noticing that the container wouldn't start at all (there were no changes done to the config or anything else related to lxc).

```
sudo lxc-start -F -n nseries --logfile /tmp/lxc-fail.log --logpriority debug
lxc-start: lsm/apparmor.c: apparmor_process_label_set: 200 No such file or directory - failed to change apparmor profile to lxc-container-default
lxc-start: sync.c: __sync_wait: 51 invalid sequence number 1. expected 4
lxc-start: start.c: __lxc_start: 1087 failed to spawn 'nseries'
lxc-start: cgfs.c: cgroup_rmdir: 207 Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/hugetlb/lxc/nseries-1
lxc-start: cgfs.c: cgroup_rmdir: 207 Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/perf_event/lxc/nseries-1
lxc-start: cgfs.c: cgroup_rmdir: 207 Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/blkio/lxc/nseries-1
lxc-start: cgfs.c: cgroup_rmdir: 207 Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/net_cls,net_prio/lxc/nseries-1
lxc-start: cgfs.c: cgroup_rmdir: 207 Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/freezer/lxc/nseries-1
lxc-start: cgfs.c: cgroup_rmdir: 207 Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/devices/lxc/nseries-1
lxc-start: cgfs.c: cgroup_rmdir: 207 Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/memory/lxc/nseries-1
lxc-start: cgfs.c: cgroup_rmdir: 207 Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/cpu,cpuacct/lxc/nseries-1
lxc-start: cgfs.c: cgroup_rmdir: 207 Device or resource busy - cgroup_rmdir: failed to delete /sys/fs/cgroup/cpuset/lxc/nseries-1
lxc-start: lxc_start.c: main: 337 The container failed to start.
lxc-start: lxc_start.c: main: 341 Additional information can be obtained by setting the --logfile and --logpriority options.
```

Does this ring a bell? I'm running this `Ubuntu 14.10` on `x86_64`.

**Comment by stgraber** [comment]
Looks like something's wrong with your apparmor profile.

Do you have apparmor enabled on that system (that's the default) and is the lxc-container-default profile properly loaded? (try "sudo /etc/init.d/apparmor reload" and look for errors).

**Comment by mandeepsandhu** [comment]
Yes, it seems like a `apparmor` issue. I'm using `systemd` as my init. I don't know if that changed anything, but after I disabled and re-enabled `apparmor` it started working again.

Even `firefox` was crashing when this problem was happening.

Thanks!

**Comment by stgraber** [comment]
Hmm, ok, closing this then.

**Comment by davidfavor** [comment]
I got a different failure, which also cleared up after - service apparmor restart

rmt-net8# lxc-start -n dev-alpine -F
lxc-start: lsm/apparmor.c: apparmor_process_label_set: 183 No such file or directory - failed to change apparmor profile to lxc-container-default
lxc-start: sync.c: __sync_wait: 51 invalid sequence number 1. expected 4
lxc-start: start.c: __lxc_start: 1164 failed to spawn 'dev-alpine'
lxc-start: cgmanager.c: cgm_remove_cgroup: 519 call to cgmanager_remove_sync failed: invalid request
lxc-start: cgmanager.c: cgm_remove_cgroup: 521 Error removing all:lxc/dev-alpine-2
lxc-start: lxc_start.c: main: 344 The container failed to start.
lxc-start: lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.
rmt-net8# lxc-start -n dev-alpine -F --logfile /tmp/lxc-fail.log --logpriority debug
lxc-start: lsm/apparmor.c: apparmor_process_label_set: 183 No such file or directory - failed to change apparmor profile to lxc-container-default
lxc-start: sync.c: __sync_wait: 51 invalid sequence number 1. expected 4
lxc-start: start.c: __lxc_start: 1164 failed to spawn 'dev-alpine'
lxc-start: cgmanager.c: cgm_remove_cgroup: 519 call to cgmanager_remove_sync failed: invalid request
lxc-start: cgmanager.c: cgm_remove_cgroup: 521 Error removing all:lxc/dev-alpine-3
lxc-start: lxc_start.c: main: 344 The container failed to start.
lxc-start: lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.

**Comment by davidfavor** [comment]
This was fixed by bouncing apparmor - service apparmor restart
