### ISSUE TITLE
Add support for lxc.include of directories

### ISSUE THREAD

**Issue by stgraber** [lxc/lxc#402]
It'd be quite useful to be able to lxc.include a directory, in which case, all files in that directory are included one after the other in alphabetical order.

This is to allow .d style config directories for distributions to ship lxc config snippets.

**Comment by hallyn** [comment]
Do we want any sort of convention about filenames to include (so we can say have a README file in there that lxc ignores)?  Maybe lxc-*.conf?  Or just *.conf (so we can do 00-start.conf, 10-something.conf, etc)

**Comment by stgraber** [comment]
just *.conf would be reasonable I think.

**Comment by hallyn** [comment]
D'oh, I meant to use a git pull request to address this, but my fingers sent the patch in email before I knew what i was doing.
