### ISSUE TITLE
Fix liblxc's handling of router IPv4 broadcast setting for /32 addresses

### ISSUE THREAD

**Issue by tomponline** [lxc/lxc#4026]
Fix regression caused by https://github.com/lxc/lxc/commit/365136359f8bf991ed172b498909000ec18b32de

See https://discuss.linuxcontainers.org/t/container-with-routed-nic-cant-ping-its-neighbour-ip-address-since-its-also-its-own-broadcast-address/11829/7

In LXC 4.0.6 (the package that is in Ubuntu Focal) the router veth interface gets configured as:

```
inet 192.168.31.7/32 brd 255.255.255.255 scope global eth0
```

And in current main branch (and the one bundled with LXD 4.16 it seems), it gets configured as:

```
inet 192.168.31.7/32 brd 192.168.31.7 scope global eth0
```

We should do the same as LXD and update liblxc to set the broadcast address to zero for `router` type NICs to ensure all other address are reachable.

**Comment by mef-merekash** [comment]
For RFC 3021 /31 and /32 networks there is no "direct broadcast", as is being calculated in lxc's confile.c. I believe the fix might just be to check if the prefix is 31 or 32, and if so to set the broadcast to 255.255.255.255 (aka INADDR_BROADCAST in the c code).

**Comment by marcfiu** [comment]
For RFC 3021 /31 point to point networks and single IP /32 setups there is no "direct broadcast", as is being calculated in lxc's confile.c when broadcast is not supplied. I believe the fix might just be to check if the prefix is 31 or 32, and if so to set the broadcast to 255.255.255.255 (aka INADDR_BROADCAST in the c code) rather than trying to calculate the direct broadcast.

**Comment by tomponline** [comment]
Yes I suspect so. Will try and look at this soon. Thanks

**Comment by tomponline** [comment]
In the mean time you can add the netmask to the lxc config to work around this as per https://github.com/lxc/lxd/pull/9103/files#diff-e5d2c9ea3e0d86c4f244b314acd4940e9fabfeb2dc16c0a457c849978a317a94R269

**Comment by marcfiu** [comment]
Hi Tom, we use a similar workaround but specify 255.255.255.255. While 0.0.0.0 should also work, I think we'll stick with the all ones broadcast address.

**Comment by marcfiu** [comment]
Hi Tom,

Neither the 4.0.5 nor whatever is in the more recent 4.0.x releases is right for /31 and /32. For a prefix <=30 they have the same result. I believe that /31 and /32, due to the nature of these networks being point-to-point and single IP networks, requires special handling to set to 255.255.255.255.

The below test code validates this. The "fixed()" function contains the proposed solution.

```
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#define BITS_PER_BYTE 8
#define BITS_PER_TYPE(type) (sizeof(type) * 8)
#define LAST_BIT_PER_TYPE(type) (BITS_PER_TYPE(type) - 1)

struct lxc_inetdev {
        struct in_addr addr;
        struct in_addr bcast;
        unsigned int prefix;
};

void info(struct lxc_inetdev *inetdev, char *version){
  char bcast[32], addr[32], *ntoa;
  ntoa=inet_ntoa(inetdev->bcast);
  strncpy(bcast,ntoa,sizeof(bcast));
  ntoa=inet_ntoa(inetdev->addr);
  strncpy(addr,ntoa,sizeof(addr));
  printf("%s bcast %s addr %s/%d\n",version, bcast, addr, inetdev->prefix);
}

void lxc4dot0dot5(struct lxc_inetdev *inetdev){
  inetdev->bcast.s_addr = inetdev->addr.s_addr;
  inetdev->bcast.s_addr |= htonl(INADDR_BROADCAST >> inetdev->prefix);
  info(inetdev,"4.0.5 ");
}

void lxc4dot0dot11(struct lxc_inetdev *inetdev){
  unsigned int shift = LAST_BIT_PER_TYPE(inetdev->prefix);
  inetdev->bcast.s_addr = inetdev->addr.s_addr;
  if (inetdev->prefix < shift)
    shift = inetdev->prefix;
  inetdev->bcast.s_addr |= htonl(INADDR_BROADCAST >> shift);
  info(inetdev,"4.0.11");
}


void fixed(struct lxc_inetdev *inetdev){
  inetdev->bcast.s_addr = inetdev->addr.s_addr;
  /* 0<=inetdev->prefix<=32 */
  switch (inetdev->prefix) {
  case 32: /* single IPv4 network */
    /* fall thru */
    ;
  case 31: /* RFC 3021 point to point network */
    inetdev->bcast.s_addr = INADDR_BROADCAST;
    break;

  default:
    inetdev->bcast.s_addr |= htonl(INADDR_BROADCAST >> inetdev->prefix);
    break;
  }
  info(inetdev,"fixed ");
}

void main(int argc, char** argv){
  struct lxc_inetdev x, *inetdev=&x;
  if (argv[1] == 0) exit(1);
  inetdev->addr.s_addr = inet_addr(argv[1]);

  if (argv[2] == 0) exit(1);
  inetdev->prefix = atoi(argv[2]);

  lxc4dot0dot5(inetdev);
  lxc4dot0dot11(inetdev);
  fixed(inetdev);
}
```

**Comment by marcfiu** [comment]
so maybe the code change in confile.c might look like this diff:
```
diff --git a/src/lxc/confile.c b/src/lxc/confile.c
index 40f34af..54c38c2 100644
--- a/src/lxc/confile.c
+++ b/src/lxc/confile.c
@@ -899,13 +899,19 @@ static int set_config_net_ipv4_address(const char *key, const char *value,
 
        /* If no broadcast address, compute one from the prefix and address. */
        if (!bcast) {
-               unsigned int shift = LAST_BIT_PER_TYPE(inetdev->prefix);
+               /* 0<=inetdev->prefix<=32 */
+               switch (inetdev->prefix) {
+               case 32: /* single IPv4 network */
+                       ; /* fall thru */
+               case 31: /* RFC 3021 point to point network */
+                       inetdev->bcast.s_addr = INADDR_BROADCAST;
+                       break;
 
-               inetdev->bcast.s_addr = inetdev->addr.s_addr;
-               if (inetdev->prefix < shift)
-                       shift = inetdev->prefix;
-               inetdev->bcast.s_addr |= htonl(INADDR_BROADCAST >> shift);
-       }
+               default:
+                       inetdev->bcast.s_addr |= htonl(INADDR_BROADCAST >> inetdev->prefix);
+                       break;
+               }
+        }
 
        list_add_tail(&inetdev->head, &netdev->ipv4_addresses);
        move_ptr(inetdev);
```

**Comment by marcfiu** [comment]
In a nutshell, the lxc code was trying to compute the so-called "directed broadcast", which does not exist for /31 and /32. As such, for those it should use the so-called "local broadcast" IP address. The proposed code change does that. Let me know your thoughts and if you agree let me know whether you want to create a PR with the proposed fix (amended for style, comments, etc.) or if I should do it. Cheers.

**Comment by tomponline** [comment]
Why 255.255.255.255? In lxd I  tested the equivalent result of doing 'ip a add n.n.n.n/32' and it resulted in no broadcast address being added (hence using 0.0.0.0). Both work AFAIK but using zeroes seems to be inline with the ip tool behavior for /32 addresses

**Comment by marcfiu** [comment]
Happy to go with zeros instead of ones if that's the best practice.

**Comment by tomponline** [comment]
> The proposed code change does that. Let me know your thoughts and if you agree let me know whether you want to create a PR with the proposed fix (amended for style, comments, etc.) or if I should do it. Cheers.

Sounds good thanks!
