### ISSUE TITLE
lxc ignores EDITOR bash variable

### ISSUE THREAD

**Issue by novakboskov** [lxc/lxc#4036]
# Required information

 * Distribution: Arch
 * Distribution version: latest
 * The output of
   * `lxc-start --version`: 4.0.11
   * `uname -a`: Linux novaksXPS 5.15.2-arch1-1 x86_64 GNU/Linux

# Issue description

lxc ignores EDITOR variable.

```
$ echo $EDITOR
nano
$ sudo lxc profile edit example
# opens vim
```

**Comment by stgraber** [comment]
You're using `sudo` which strips the environment.

**Comment by novakboskov** [comment]
@stgraber Could you please explain what you exactly meant? :)
Because I have `export EDITOR=nano` in my `~/.bashrc`, and 
```
$ sudo echo $EDITOR
nano
```

**Comment by stgraber** [comment]
`sudo echo $EDITOR` makes your shell expand `$EDITOR` prior to passing the command `echo nano` over to `sudo`.
If you were to run `sudo sh -c "echo \$EDITOR"` instead, you'd see that it doesn't make it through.

Instead running `sudo -E sh -c "echo \$EDITOR"` will have it show up.

**Comment by novakboskov** [comment]
@stgraber That makes sense. Thanks!
