### ISSUE TITLE
Avahi daemon doesn't work inside unprivileged containers

### ISSUE THREAD

**Issue by yann-soubeyrand** [lxc/lxc#404]
Hi,

Avahi daemon doesn't work inside unprivileged containers, more precisely inside containers where the uid 0 is mapped to an uid other than 0.

I identified the line where the problem occurs in the Avahi sources: http://git.0pointer.net/avahi.git/tree/avahi-core/netlink.c#n85.

I don't know if it's a bug of Avahi or if it's of a bug inside the kernel. My guess is that it's the latter one but I'm not sure. I think that the kernel passes the credentials mapped to zero when it's the sender of the message whereas it should pass all zero credentials in this case. But I didn't read the code of netlink and it's purely speculation. Also, I wonder if it could not introduce security flaws doing so.

Cheers

**Comment by stgraber** [comment]
I just installed and succesfully started avahi-daemon in an unprivileged Ubuntu 15.04 container here.

**Comment by stgraber** [comment]
That's avahi 0.6.31

**Comment by stgraber** [comment]
Anyway, while there may well be a bug affecting your case, it's unfortunately not something LXC can do a great deal about (as LXC is just the userspace tool).

You may want to bring that bug up to the avahi mailing-list who may then advise you as to whether it's a kernel bug or not (feel free to Cc me).

**Comment by yann-soubeyrand** [comment]
Hi,

The avahi-daemon is also starting inside my container but the MDNS name resolution doesn't work. Does it work for you? What kernel version are you using?

I thought LXC developpers were also the developpers of the kernel related features (namespaces and the like), that's why I opened a bug report here. I'm going to bring that bug to the Avahi mailing list. Sorry for the inconvenience.

Cheers

**Comment by r0bj** [comment]
The avahi-daemon itself starts under unprivileged LXC but it's not properly binded to UDP sockets and do not responds for UDP requests:

```bash
# netstat -panu
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -
udp        0      0 0.0.0.0:40132           0.0.0.0:*                           -
udp6       0      0 :::5353                 :::*                                -
udp6       0      0 :::33733                :::*                                -
```

Requests without answer:
```bash
23:14:18.163524 IP 10.100.10.114.5353 > 224.0.0.251.5353: 0 SRV (QU)? afp._afpovertcp._tcp.local. (44)
23:14:19.165211 IP 10.100.10.114.5353 > 224.0.0.251.5353: 0 SRV (QM)? afp._afpovertcp._tcp.local. (44)
```
