### ISSUE TITLE
LXC C API undefined reference on list_defined_containers

### ISSUE THREAD

**Issue by ManuMTS** [lxc/lxc#4044]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of
   * `lxc-start --version`: 4.0.6

# Issue description

I'm trying to use C to write an application which uses LXC. The function "list_defined_containers" seems to be broken.
GCC Compiler complains: __undefined reference to `list_defined_containers'__. I'm including <lxc/lxccontainer.h>. Is there anything else required?

**Comment by stgraber** [comment]
Did you pass `-llxc` so gcc properly links against the library?

**Comment by stgraber** [comment]
I just tested here with a modified version of the test for that symbol (src/tests/list.c) and had no problem compiling it and running it.

**Comment by ManuMTS** [comment]
Thank you for the quick answer. I didn't add the library flag before. Now that gcc has the -l lxc it compiles and runs.
So this issue is solved for me.
