### ISSUE TITLE
cannot create a centos container on lvm

### ISSUE THREAD

**Issue by ruffianhy** [lxc/lxc#406]
lxc version:1.0.7
I tried to create a lxc on lvm with command:
lxc-create -n mylxc2 -t centos -B lvm
and i got the errors:

Copy /usr/local/var/cache/lxc/centos/x86_64/6/rootfs to /dev/lxc/mylxc2 ... 
Copying rootfs to /dev/lxc/mylxc2 ...mkdir: cannot create directory ‘/dev/lxc/mylxc2’: File exists
rsync: writefd_unbuffered failed to write 4 bytes to socket [sender]: Broken pipe (32)
rsync: ERROR: cannot stat destination "/dev/lxc/mylxc2/": Not a directory (20)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(565) [Receiver=3.0.9]
rsync: connection unexpectedly closed (9 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=3.0.9]

**Comment by stgraber** [comment]
Looks like a bad interaction between lxc.autodev and the LVM backing store.

**Comment by hallyn** [comment]
I think this was discusse don the mailing list.  The problem is the centos template was buggy.  It needs to take the --rootfs passed by lxc-create to the template, NOT the lxc.rootfs from the container configuration file.
