### ISSUE TITLE
redhat template

### ISSUE THREAD

**Issue by ruffianhy** [lxc/lxc#407]
where can i get a redhat template？

**Comment by ruffianhy** [comment]
my system is Red Hat Enterprise Linux Server release 7.0 (Maipo)
the centos template cannot recognize it as a redhat.

**Comment by stgraber** [comment]
There isn't a Red Hat template. Feel free to contribute one if you want though.

I believe in the past the main reason nobody attempted to make one was because of the whole subscription mechanism behind Red Hat Enterprise and it being generally hard to come up with a generic (and legal) template.
