### ISSUE TITLE
Obscure lxc-checkconfig warning: Cgroup ns_cgroup: required

### ISSUE THREAD

**Issue by maxnikulin** [lxc/lxc#4070]
I am confused by the following warning issued by `lxc-checkconfig`

    Cgroup ns_cgroup: required

when it is running on Ubuntu-21.10 impish with unified systemd cgroup hierarchy. I can run Ubuntu impish in containers with no problem. I get no such warning on ubuntu-20.04 focal with hybrid hierarchy despite absence of `CONFIG_CGROUP_NS` in kernel config. Does it mean that cgroup v1 should be present as well to run older containers with no additional configuration?

Text of warning was changed in #3893, but it is not clear enough yet.

https://github.com/lxc/lxc/blob/master/src/lxc/cmd/lxc-checkconfig.in#L195 checks for `cgroup.clone_children` and I have no idea what should be checked instead in unified hierarchy:

sysctl: `kernel.unprivileged_userns_clone = 1`

    ls /proc/self/ns
    cgroup  ipc  mnt  net  pid  pid_for_children  time  time_for_children  user  uts

    cat /sys/fs/cgroup/cgroup.controllers 
    cpuset cpu io memory hugetlb pids rdma misc

Kernel: `5.13.0-27-generic #29-Ubuntu SMP Wed Jan 12 17:36:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

    systemd 248 (248.3-1ubuntu8.2)
    +PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP -LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT
    default-hierarchy=unified

Full output of `lxc-checkconfig`
```
LXC version 4.0.10
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-5.13.0-27-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled
Cgroup namespace: enabled

Cgroup v1 mount points: 


Cgroup v2 mount points: 
/sys/fs/cgroup

Cgroup v1 systemd controller: missing
Cgroup v1 freezer controller: missing
Cgroup ns_cgroup: required
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```

I suspect some inconsistency in the script. Messages for success and for failure of this test are rather different.

**Comment by lyderic** [comment]
I also have this weird report in lxc-checkconfig saying that ns_cgroup is 'required', although all seems to be working ok. Here my details (os is archlinux, fully up-to-date as of Feb. 11 2022):

```
$ uname -rom
5.15.22-1-lts x86_64 GNU/Linux
$ systemctl --version
systemd 250 (250.3-4-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
$ lxc-checkconfig | head -1
LXC version 4.0.12
$ lxc-checkconfig | grep ns_cgroup
Cgroup ns_cgroup: required
```

Looking at https://github.com/lxc/lxc/pull/3893 indeed, it seems that it is only a bug in lxc-checkconfig ans this worrying 'required' can be safely ignored. Do you confirm?

**Comment by laf0rge** [comment]
Same here on Debian unstable:
<pre>
$ uname -r
5.17.0-2-amd64
$ lxc-checkconfig | grep ns_cgroup
Cgroup ns_cgroup: required
</pre>

**Comment by stgraber** [comment]
The checkconfig rework from earlier this week changes that.

**Comment by Sun-Wukong** [comment]
Confirming the same on Lubuntu 22.04.5 LTS

```
Cgroup v2 mount points: 
/sys/fs/cgroup

Cgroup v1 systemd controller: missing
Cgroup v1 freezer controller: missing
Cgroup ns_cgroup: required
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

```
