### ISSUE TITLE
lxc-start fails with io_uring

### ISSUE THREAD

**Issue by dElogics** [lxc/lxc#4081]
* Distribution: Gentoo
 * Distribution version: n/a
 * The output of
   * `lxc-start --version` 4.0.11
   * `lxc-checkconfig`LXC version 4.0.11
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /lib/modules/5.10.87-gentoo-gentoo/build/.config
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled
Cgroup namespace: enabled

Cgroup v1 mount points: 
/mnt/cgroupv1

Cgroup v2 mount points: 
/sys/fs/cgroup

Cgroup v1 systemd controller: missing
Cgroup v1 freezer controller: missing
Cgroup v1 clone_children flag: enabled
Cgroup device: missing
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: missing
--- Misc ---
Veth pair device: enabled, loaded
Macvlan: missing
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: missing
CONFIG_NETFILTER_XT_MATCH_COMMENT: missing
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: missing
CONFIG_INET_DIAG: missing
CONFIG_PACKET_DIAG: missing
CONFIG_NETLINK_DIAG: missing
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
   * `uname -a` Linux desktopminer 5.10.87-gentoo-gentoo #2 SMP PREEMPT Sat Dec 25 23:22:35 IST 2021 x86_64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz GenuineIntel GNU/Linux
   * `cat /proc/self/cgroup` cat /proc/self/cgroup
1:name=systemdold:/
0::/system.slice/sshd.service
   * `cat /proc/1/mounts` /dev/root / ext4 rw,noatime,journal_checksum,journal_async_commit,max_batch_time=10000000,data=writeback,inode_readahead_blks=32768 0 0
devtmpfs /dev devtmpfs rw,relatime,size=8156288k,nr_inodes=2039072,mode=755 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev,noexec 0 0
devpts /dev/pts devpts rw,relatime,mode=600,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,size=3265900k,nr_inodes=819200,mode=755 0 0
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot 0 0
none /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=5129 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
cgroupv1compat /mnt/cgroupv1 cgroup rw,relatime,name=systemdold 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=1632948k,nr_inodes=408237,mode=700,uid=1000,gid=1000 0 0

# Issue description

I've LXC compiled with io_uring support. When I start a container with -- 
lxc-start -F --name volatile -f /etc/lxc_configs/template_buster.nexus.conf
It hangs. There's no output. Attached are the debug logs

Compile without io_uring, and things start working again.
[lxc_debug.log](https://github.com/lxc/lxc/files/8031029/lxc_debug.log)

**Comment by mihalicyn** [comment]
It should be fixed by https://github.com/lxc/lxc/pull/4304 or (if it was a kernel bug) in recent Linux kernel versions.
Please check and feel free to reopen if it's still a problem.

**Comment by dElogics** [comment]
/reopen

No this problem still persists. I cannot reopen.
