### ISSUE TITLE
ubuntu template fails when keyring file is not installed

### ISSUE THREAD

**Issue by Wuodan** [lxc/lxc#409]
The ubuntu template calls debootstrap which uses:
/usr/share/keyrings/ubuntu-archive-keyring.gpg
If that file is missing, debootstrap defaults to debian mirror thus fails to download the ubuntu release.

LXC is not the cause of this issue, rather the victim :-)
But at least 3 others reported the same issue - seems the problem occured on 3 distros (RedHat, Debian, Gentoo).

Solution proposal 1:
If that file is missing, call debootstrap with a mirror, for ex. "http://archive.ubuntu.com/ubuntu"

Solution proposal 2:
wget that file to /var/cache/lxc/keyrings and call debootstrap with --keyring=file.

Links to similar reports:
https://bugzilla.redhat.com/show_bug.cgi?id=1115728
https://lists.debian.org/debian-boot/2014/01/msg00390.html
http://readthefuckingmanual.net/error/5342/

Output of `lxc-create -t ubuntu -n gaga 2>&1`:

Checking cache download in /var/cache/lxc/precise/rootfs-amd64 ... 
dpkg-query: error: failed to open package info file `/var/lib/dpkg/status' for reading: No such file or directory
Installing packages in template: ssh,vim,language-pack-en
Downloading ubuntu precise minimal ...
which: no qemu-debootstrap in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/4.8.3:/opt/cuda/bin:/usr/sbin:/usr/bin:/sbin:/bin)
I: Keyring file not available at /usr/share/keyrings/ubuntu-archive-keyring.gpg; switching to https mirror https://mirrors.kernel.org/debian
I: Retrieving Release 
E: Failed getting release file https://mirrors.kernel.org/debian/dists/precise/Release
lxc_container: lxccontainer.c: create_run_template: 1136 container creation template for gaga failed
lxc_container: lxc_create.c: main: 280 Error creating container gaga

**Comment by stgraber** [comment]
Marking as incomplete as we're waiting for a sign-off in the pull request.

**Comment by starkers** [comment]
still broken on centos :(

**Comment by gabri94** [comment]
broken also on debian

**Comment by hallyn** [comment]
@Wuodan 

Please see Stéphane's comment - could you please sign off your commit?

**Comment by benbenolson** [comment]
I'm having this issue too. For the time being, how would I solve this?

**Comment by benbenolson** [comment]
Nevermind, solved by installing the "ubuntu-archive-keyring" package in Debian Jessie.

**Comment by nehaljwani** [comment]
On CentOS7, when trying to create a container using the command:
```
lxc-create -n ubuntu -t ubuntu -B lvm --vgname lxc --fssize=2G --fstype ext4 -- --release=vivid
```
I faced the same difficulty. So, as a quick hack, I had to do:
```
cd /usr/sbin ; ln -sf debootstrap qemu-debootstrap
```
Then edit /usr/sbin/debootstrap to look like:
```
DEF_HTTPS_MIRROR="https://mirrors.kernel.org/ubuntu"
```

**Comment by Syntechboy** [comment]
I'm having the same problem. It was working fine yesterday, but today it didnt work at all. This is what I am getting:
I: Keyring file not available at /usr/share/keyrings/ubuntu-archive-keyring.gpg; switching to https mirror https://mirrors.kernel.org/debian
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...

**Comment by amorphid** [comment]
I bumped into this problem on debian.  Installing ubuntu-archive-keyring fixed it.

**Comment by acepsaepudin** [comment]
thanks @amorphid ! you save my time 💃

**Comment by ian7on** [comment]
there should be a package "var/cache/apt/archives/ubuntu-keyring_2012.05.19_all.deb" Install it using "dpkg -i" and that should solve the issue

**Comment by brauner** [comment]
Should be fixed in master and closed by the mentioned commits.
