### ISSUE TITLE
Feature request: allow hook script for lxc-download template

### ISSUE THREAD

**Issue by imrejonk** [lxc/lxc#4094]
Dear LXC developers,

I'm currently using lxc-create with the 'download' template to create unprivileged Debian containers. I start them using lxc-unpriv-start. It would be great if I could make the lxc-download script run a hook script that, for example, installs a few Debian packages for me inside the container, like openssh-server. This preferably happens in a completely unprivileged setting, i.e. with the setuid mapping I configured beforehand. This would allow me and other LXC users to easily and quickly customize their unprivileged containers.

My /etc/subuid (and /etc/subgid, they're the same):
```
imre:100000:65536
```

My ~/.config/lxc/default.conf:
```
lxc.apparmor.profile = unconfined
lxc.idmap = u 0 100000 65536
lxc.idmap = g 0 100000 65536
```

Thank you for developing LXC.

**Comment by stgraber** [comment]
We won't be doing that. The unpack logic in `lxc-download` is pretty simple, it unpacks the tarball in the correct namespace, that's it.

If you want to be able to run hooks that can install packages, now we'd need to mount procfs, sysfs, populate devices in /dev, setup networking, kick in DHCP in the instance to get you DNS setup, ... This really isn't practical and is extremely distro dependent.

Instead you're far better off creating the instance with `lxc-create`, then start it, run whatever you want through `lxc-attach` and then make some copies of that instance.

**Comment by imrejonk** [comment]
Ah okay, that would also work I guess. Thanks!
