### ISSUE TITLE
call to cgmanager_create_sync failed: invalid request

### ISSUE THREAD

**Issue by henn** [lxc/lxc#411]
First attempt at using unprivileged containers on Ubuntu 14.10 (amd64) yields error in the title. Looking for similar bug reports seem to offer systemd responses, however I am still using the default upstart that comes with 14.10 (systemd wasn't mentioned as a prerequisite).

After following the [ubuntu instructions](https://help.ubuntu.com/14.04/serverguide/lxc.html), I ran:

```
lxc-create -n test1 -t download -- -d ubuntu -r utopic -a amd64
lxc-start -n test1 --logpriority=DEBUG --logfile=test1.out`
```

This resulted in the following log (trimmed for size):

```
INFO     lxc_start - start.c:lxc_init:443 - 'test1' is initialized
DEBUG    lxc_start - start.c:__lxc_start:1061 - Not dropping cap_sys_boot or watching utmp
INFO     lxc_start - start.c:lxc_spawn:805 - Cloning a new user namespace 
INFO     lxc_cgroup - cgroup.c:cgroup_init:62 - cgroup driver cgmanager initing for test1
ERROR    lxc_cgmanager - cgmanager.c:lxc_cgmanager_create:284 - call to cgmanager_create_sync failed: invalid request
ERROR    lxc_cgmanager - cgmanager.c:lxc_cgmanager_create:286 - Failed to create name=systemd:test1
ERROR    lxc_cgmanager - cgmanager.c:cgm_create:638 - Error creating cgroup name=systemd:test1 
INFO     lxc_cgmanager - cgmanager.c:cgm_remove_cgroup:508 - cgroup removal attempt: name=systemd:test1 did not exist
INFO     lxc_cgmanager - cgmanager.c:cgm_remove_cgroup:508 - cgroup removal attempt: perf_event:test1 did not exist 
INFO     lxc_cgmanager - cgmanager.c:cgm_remove_cgroup:508 - cgroup removal attempt: net_prio:test1 did not exist
INFO     lxc_cgmanager - cgmanager.c:cgm_remove_cgroup:508 - cgroup removal attempt: net_cls:test1 did not exist
INFO     lxc_cgmanager - cgmanager.c:cgm_remove_cgroup:508 - cgroup removal attempt: memory:test1 did not exist
INFO     lxc_cgmanager - cgmanager.c:cgm_remove_cgroup:508 - cgroup removal attempt: hugetlb:test1 did not exist
INFO     lxc_cgmanager - cgmanager.c:cgm_remove_cgroup:508 - cgroup removal attempt: freezer:test1 did not exist
INFO     lxc_cgmanager - cgmanager.c:cgm_remove_cgroup:508 - cgroup removal attempt: devices:test1 did not exist
INFO     lxc_cgmanager - cgmanager.c:cgm_remove_cgroup:508 - cgroup removal attempt: cpuset:test1 did not exist
INFO     lxc_cgmanager - cgmanager.c:cgm_remove_cgroup:508 - cgroup removal attempt: cpuacct:test1 did not exist
INFO     lxc_cgmanager - cgmanager.c:cgm_remove_cgroup:508 - cgroup removal attempt: cpu:test1 did not exist
INFO     lxc_cgmanager - cgmanager.c:cgm_remove_cgroup:508 - cgroup removal attempt: blkio:test1 did not exist
ERROR    lxc_start - start.c:lxc_spawn:864 - failed creating cgroups
INFO     lxc_utils - utils.c:get_rundir:420 - XDG_RUNTIME_DIR isn't set in the environment.
ERROR    lxc_start - start.c:__lxc_start:1087 - failed to spawn 'test1'
INFO     lxc_utils - utils.c:get_rundir:420 - XDG_RUNTIME_DIR isn't set in the environment.
INFO     lxc_utils - utils.c:get_rundir:420 - XDG_RUNTIME_DIR isn't set in the environment. 
WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_init_pid failed to receive response
WARN     lxc_cgmanager - cgmanager.c:cgm_get:946 - do_cgm_get exited with error
ERROR    lxc_start_ui - lxc_start.c:main:337 - The container failed to start.
```

Just in case, I tried setting apparmor to complain instead of enforce with `aa-complain lxc-start`, however received the same error. The system is up to date on all packages.

Any ideas?

Thanks

**Comment by stgraber** [comment]
Hmm, so the errors about XDG_RUNTIME_DIR seem to indicate that you aren't running this inside a regular user session.

Can you paste your /proc/self/cgroup?

Also, try rebooting the system and then login either to a graphical session or a text console directly as the target user, then try to start the container from there.

Switching user using su or sudo is known not to cause a cgroup switch and not to set XDG_RUNTIME_DIR leading to what you've pasted above.

**Comment by Meseira** [comment]
Hi,

I have the same problem as henn and I run an up-to-date Ubuntu 14.04 and LXC 1.0.3 from Ubuntu repos. My unprivileged containers fail to start with the following messages:
```
lxc-start: call to cgmanager_create_sync failed: invalid request
lxc-start: Failed to create cpuset:test
lxc-start: Error creating cgroup cpuset:test
lxc-start: failed creating cgroups
lxc-start: failed to spawn 'test'
```

In the logs, I also have the messages about `XDG_RUNTIME_DIR`,
```
lxc-start 1423653303.058 INFO     lxc_utils - XDG_RUNTIME_DIR isn't set in the environment.
```

I am doing this on my server (thus, no graphical session) and simply connected by SSH. At a first time, I was dealing with a connection through sudo. After the comment of stgraber, I switch to a classical user with a classical login and the same problem happens. Rebooting the server does not change anything.

My /proc/self/cgroup:
```
11:hugetlb:/
10:perf_event:/
9:blkio:/
8:freezer:/
7:devices:/
6:memory:/
5:cpuacct:/
4:cpu:/
3:cpuset:/
2:name=systemd:/
```

Thanks for your help

**Comment by tarruda** [comment]
[Here](https://gist.github.com/tarruda/2aea9107f04d8b8d8dbf) is a small script to work around this issue.

**Comment by henn** [comment]
As you guessed, I am indeed not running this within a typical user session - I would like to keep the containers under a separate non-interactive user, and am using su to do that.

Trying this on Ubuntu 15.10, I now see the following error from lxc-create:
```
 $ lxc-create -n test1 -t download -- -d ubuntu -r trusty -a amd64
WARN: could not reopen tty: Permission denied
WARN: could not reopen tty: Permission denied
WARN: could not reopen tty: Permission denied
lxc-create: lxccontainer.c: create_partial: 176 Permission denied - Erorr creating partial file
lxc-create: lxc_create.c: main: 274 Error creating container test1
```

Any thoughts?
Thanks

**Comment by nek0** [comment]
I got the same error, when the folder `<containername>/rootfs` existed before executing `lxc-create`. Check also the folder `<containername>` and its permissions.

**Comment by brauner** [comment]
The cgmanager cgroup driver is deprecated. Newer versions will remove it completely.
