### ISSUE TITLE
lxc: how to start with cgroup v2 in cgroup namespace?

### ISSUE THREAD

**Issue by sitano** [lxc/lxc#4119]
What is the correct LXC configuration for setting up containers that use `Unified` cgroup (v2) hierarchy mounted in the cloned cgroup namespace (think of docker privileged container with systemd unified)?

If this is supported at all, https://wiki.debian.org/LXC/CGroupV2 has no info on the topic.

The problem is: the pid==1 sits in `0::/` but `/sys/fs/cgroup` is a leaf and already contains all of the processes of the current pid namespace so that the LXC would not be able to delegate controllers to the sub classes. This can be work around manually. But what is then the proper LXC configuration? 

the issue is similar to https://github.com/lxc/lxc/issues/3206, but the question is how LXC would be able to recognize the cgroup node for the monitors/payload?

**Comment by brauner** [comment]
We have a branch which we'll merge soon that should fix this for LXC containers started by non-root

https://github.com/lxc/lxc/pull/4107

**Comment by sitano** [comment]
@brauner great! thank you for the reference. if I don't want to work with systemd inside of my namespaces is there a way to tell LXC what unified cgroup nodes to use for monitors and payloads that I will prepare manually?

**Comment by hallyn** [comment]
If you're preparing the cgroups manually and not using systemd in the container, then the patch shouldn't be needed.  However, cgroup2 enforced (IIUC) a new restriction that if you are in in CG1 and want to move to CG2, then you must have write access not only to CG2/cgroup.procs, but also CG1/cgroup.procs.  So you'll have to make sure your login daemon sets that up.

**Comment by sitano** [comment]
thx you
