### ISSUE TITLE
Container in rest reaching memory limit, gets high cpu and starts using maximum disk read throughput for ever.

### ISSUE THREAD

**Issue by jalbstmeijer** [lxc/lxc#4122]
* Distribution: Ubuntu
 * Distribution version: jammy-22.04
 * The output of
   * `lxc --version` : 5.1
   * `lxc-checkconfig`: is not included
   * `uname -a`:  Linux ip-10-11-21-54 5.15.0-1005-aws 7-Ubuntu SMP Wed Apr 20 03:44:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
   * `cat /proc/self/cgroup`: 
   13:devices:/user.slice
12:hugetlb:/
11:misc:/
10:cpuset:/
9:freezer:/
8:memory:/user.slice/user-1000.slice/session-23.scope
7:perf_event:/
6:cpu,cpuacct:/user.slice
5:rdma:/
4:net_cls,net_prio:/
3:pids:/user.slice/user-1000.slice/session-23.scope
2:blkio:/user.slice
1:name=systemd:/user.slice/user-1000.slice/session-23.scope
0::/user.slice/user-1000.slice/session-23.scope
   * `cat /proc/1/mounts`
/dev/root / ext4 rw,relatime,discard,errors=remount-ro 0 0
devtmpfs /dev devtmpfs rw,relatime,size=1894916k,nr_inodes=473729,mode=755,inode64 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev,inode64 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,size=760556k,nr_inodes=819200,mode=755,inode64 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k,inode64 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,size=4096k,nr_inodes=1024,mode=755,inode64 0 0
cgroup2 /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/misc cgroup rw,nosuid,nodev,noexec,relatime,misc 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14362 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,nosuid,nodev,noexec,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,nosuid,nodev,noexec,relatime 0 0
tracefs /sys/kernel/tracing tracefs rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
none /run/credentials/systemd-sysusers.service ramfs ro,nosuid,nodev,noexec,relatime,mode=700 0 0
/dev/loop1 /snap/core20/1434 squashfs ro,nodev,relatime,errors=continue 0 0
/dev/loop0 /snap/amazon-ssm-agent/5163 squashfs ro,nodev,relatime,errors=continue 0 0
/dev/loop2 /snap/core18/2344 squashfs ro,nodev,relatime,errors=continue 0 0
/dev/loop4 /snap/snapd/15534 squashfs ro,nodev,relatime,errors=continue 0 0
/dev/nvme0n1p15 /boot/efi vfat rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro 0 0
tmpfs /run/snapd/ns tmpfs rw,nosuid,nodev,size=760556k,nr_inodes=819200,mode=755,inode64 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
/dev/loop5 /snap/snapd/15904 squashfs ro,nodev,relatime,errors=continue 0 0
/dev/loop6 /snap/core18/2409 squashfs ro,nodev,relatime,errors=continue 0 0
/dev/loop7 /snap/amazon-ssm-agent/5656 squashfs ro,nodev,relatime,errors=continue 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=380276k,nr_inodes=95069,mode=700,uid=1000,gid=1000,inode64 0 0
/dev/loop3 /snap/lxd/23037 squashfs ro,nodev,relatime,errors=continue 0 0
nsfs /run/snapd/ns/lxd.mnt nsfs rw 0 0
tmpfs /var/snap/lxd/common/ns tmpfs rw,relatime,size=1024k,mode=700,inode64 0 0
nsfs /var/snap/lxd/common/ns/shmounts nsfs rw 0 0
nsfs /var/snap/lxd/common/ns/mntns nsfs rw 0 0

# Issue description

In production we have seen regularly containers become unavailable when memory limits get reached.
Most of the time it gets preceded by an OOM kill action and then most if not all processes in the container start reading at full capacity from disk. As far as we can see the container disk hits maximum throughput speed and stays there till the container is stopped. (have left it for hours once in this state)

I can imagine a read peek and higher read throughput when there is almost no disk cache available in memory, but the behavior we see seems not to be expected or desirable.
luckily we use dedicated disks for each container, otherwise it would probably take out the complete instance and all the containers on it.

An important side note is that we also see this happen on containers that are in no way under load and or publicly available to be able to explain a constant need to read at maximum capacity. Also we see processes at maximum read capacity, from which you would not expect much reads at all (init, nscd, crond etc).

In production we run on LXD/LXC on AmazonLinux, so I decided to reproduce it on a dedicated default Ubuntu instance on AWS to isolate the problem and rule out as much of the exotic choices we made. (OS/kernel/settings).

# Steps to reproduce

1. Start the Ubuntu instance based on Ubuntu jammy-22.04-amd64 (ami-07bd2fc45c8a8dd48 in eu-west-1)

As I could not start a AmazonLinux container:

(Error: The image used by this instance requires a CGroupV1 host system)

I had to change this and reboot;

/etc/default/grub
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=false"

update-grub2

reboot

3. Run lxd init;

Would you like to use LXD clustering? (yes/no) [default=no]:
Do you want to configure a new storage pool? (yes/no) [default=yes]: no
Would you like to connect to a MAAS server? (yes/no) [default=no]:
Would you like to create a new local network bridge? (yes/no) [default=yes]:
What should the new bridge be called? [default=lxdbr0]:
What IPv4 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 10.11.21.121/24
Would you like LXD to NAT IPv4 traffic on your bridge? [default=yes]:
What IPv6 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: none
Would you like the LXD server to be available over the network? (yes/no) [default=no]: no
Would you like stale cached images to be updated automatically? (yes/no) [default=yes]: no
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: yes
config:
images.auto_update_interval: "0"
networks:
- config:
ipv4.address: 10.11.21.121/24
ipv4.nat: "true"
ipv6.address: none
description: ""
name: lxdbr0
type: ""
project: default
storage_pools: []
profiles:
- config: {}
description: ""
devices:
eth0:
name: eth0
network: lxdbr0
type: nic
name: default
projects: []
cluster: null

4. Attach a dedicated swap and container disk  to the instance
5. Enable swap and create storage

mkswap /dev/nvme1n1 -L swap
echo "LABEL=swap none swap defaults,nofail 0 0" >> /etc/fstab
swapon -a

lxc storage create burst1 lvm source=/dev/nvme2n1

6. Create an AmazonLinux container

lxc launch -s burst1 images:amazonlinux burst1

7. Install clamd on the container

lxc exec -t burst1 -- sh -c "yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
lxc exec -t burst1 -- sh -c "yum install -y iputils procps-ng clamd clamav-server clamav-data clamav-update clamav-filesystem clamav clamav-scanner-systemd clamav-devel clamav-lib clamav-server-systemd"
lxc exec -t burst1 -- sh -c "sed -i s/^#LocalSocket/LocalSocket/g /etc/clamd.d/scan.conf"
lxc exec -t burst1 -- sh -c "systemctl enable clamd@scan"
lxc exec -t burst1 -- sh -c "systemctl start clamd@scan"

5. Limit the memory to 1GB and restart the container

lxc stop burst1
lxc config set burst1 limits.memory 1GB
lxc start burst1

6. See top, iotop and the AWS volume metrics to see high cpu and read io usage 

iotop:

Total DISK READ: 128.17 M/s | Total DISK WRITE: 0.00 B/s
Current DISK READ: 128.17 M/s | Current DISK WRITE: 0.00 B/s
TID PRIO USER DISK READ DISK WRITE SWAPIN IO> COMMAND
6244 be/4 1000000 42.76 M/s 0.00 B/s ?unavailable? init
6648 be/4 1000000 42.65 M/s 0.00 B/s ?unavailable? systemd-hostnamed
6649 be/4 1000998 42.76 M/s 0.00 B/s ?unavailable? clamd -c /etc/clamd.d/scan.conf

Total DISK READ: 128.25 M/s | Total DISK WRITE: 0.00 B/s
Current DISK READ: 128.25 M/s | Current DISK WRITE: 0.00 B/s
TID PRIO USER DISK READ DISK WRITE SWAPIN IO> COMMAND
6244 be/4 1000000 32.37 M/s 0.00 B/s ?unavailable? init
6639 be/4 1000081 32.33 M/s 0.00 B/s ?unavailable? dbus-daemon --system --add~idfile --systemd-activation
6642 be/4 1000000 32.61 M/s 0.00 B/s ?unavailable? crond -n
6649 be/4 1000998 30.94 M/s 0.00 B/s ?unavailable? clamd -c /etc/clamd.d/scan.conf

# Information to attach

Find dmesg, lxc.log and lxc.conf and AWS volume metric read-io.png attached

![read-io](https://user-images.githubusercontent.com/362000/170229993-548e175f-5647-469b-a5d1-643a8b8dd690.png)
[lxc.conf.txt](https://github.com/lxc/lxc/files/8769741/lxc.conf.txt)
[lxc.log](https://github.com/lxc/lxc/files/8769742/lxc.log)
[dmesg.txt](https://github.com/lxc/lxc/files/8769743/dmesg.txt)

**Comment by jalbstmeijer** [comment]
In an effort to make it as straight forward as possible;

Started a new instance, Ubuntu Jammy instance (ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220609, ami-0d75513e7706cf2d9 in eu-west1) in a t3.medium.
Tested now with a Ubuntu Jammy container, which has CGroupV2 support.
So no need need to change any kernel parameter as with an AmazonLinux container.

Also in this configuration I can reproduce the never ending read io burst.

```
lxc launch -s burst1 images:ubuntu/jammy/cloud burst1

lxc exec -t burst1 -- sh -c "apt-get update"
lxc exec -t burst1 -- sh -c "apt-get -y install clamav-daemon"
lxc exec -t burst1 -- sh -c "service clamav-daemon start"

lxc stop burst1
lxc config set burst1 limits.memory 1GB
lxc start burst1
```

iotop output
```
    TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND 
   8705 be/4 1000000    31.90 M/s    0.00 B/s  ?unavailable?  init
   8851 be/4 1000102    34.24 M/s    0.00 B/s  ?unavailable?  @dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
   8859 be/4 1000106    32.44 M/s    0.00 B/s  ?unavailable?  clamd --foreground=true
   8860 be/4 1000000    29.77 M/s    0.00 B/s  ?unavailable?  systemd-hostnamed
```

**Comment by RDReindeer** [comment]
Is this issue resolved now?

**Comment by jalbstmeijer** [comment]
> Is this issue resolved now?

Not that I'm aware of.
I mitigated the problem for now with dedicated disks for each container and more memory assignment.

As far as I know the issue has not even been acknowledged or reproduced with the information above.

Reactions till now in other fora have been "expect behavior". 

But when I ask, 'why is OOM not interfering?' or 'how is bringing down the complete instance expect behavior?' I have had not clear answer.

I also have never seen this issue on OpenVZ, which I used for years.

**Comment by RDReindeer** [comment]
> > Is this issue resolved now?
> 
> Not that I'm aware of. I mitigated the problem for now with dedicated disks for each container and more memory assignment.
> 
> As far as I know the issue has not even been acknowledged or reproduced with the information above.
> 
> Reactions till now in other fora have been "expect behavior".
> 
> But when I ask, 'why is OOM not interfering?' or 'how is bringing down the complete instance expect behavior?' I have had not clear answer.
> 
> I also have never seen this issue on OpenVZ, which I used for years.

I think this is not expected behavior at all. I have opened 100 lxc containers in pve. As long as one of them is full of memory, other containers will be unable to connect or the connection speed will slow down. This problem bothers me very much.

**Comment by jalbstmeijer** [comment]
@RDeindeer and you see the same max io read usage? In that case,  good to hear I'm not alone.
Maybe you can be the first to confirm my findings by reproducing what I documented above.

**Comment by RDReindeer** [comment]
> @RDeindeer and you see the same max io read usage? In that case, good to hear I'm not alone. Maybe you can be the first to confirm my findings by reproducing what I documented above.

Yes, I also found the problem of full io usage. How can I confirm your discovery? I am a newbie on github.

**Comment by RDReindeer** [comment]
> @RDeindeer and you see the same max io read usage? In that case, good to hear I'm not alone. Maybe you can be the first to confirm my findings by reproducing what I documented above.

I can provide you with a reproduction process of encountering the same problem, but it is a Chinese website and you may need to translate it https://www.nodeseek.com/post-9871-1

**Comment by jalbstmeijer** [comment]
@RDeindeer I checked the link. It seems indeed to hit the same issue. So that looks like a confirmation for me.
Do I understand correctly on that link that openvz7 tests do not show the same issue?

**Comment by jalbstmeijer** [comment]
@RDeindeer Well now we have to figure out how to get the attention of the LXC developers.

**Comment by RDReindeer** [comment]
> @RDeindeer Well now we have to figure out how to get the attention of the LXC developers.

agree

**Comment by Magisk1024** [comment]
Is there any solution to this problem? I also encountered this problem.

**Comment by david-barbion** [comment]
Hi,

I'm facing the same problem here. My LXD host is running an updated ubuntu jammy, lxd is version 5.21.1 LTS.
I'm setting `memory.limits` for some lxc containers. Sometime, if that limits is too low, that container goes very slowly, all cpu time is taken doing I/O:
![image](https://github.com/lxc/lxc/assets/878967/2c93292d-bd75-46b4-9a14-55d336d141c9)

**Comment by stgraber** [comment]
That's actually perfectly normal.

The memory limit doesn't just affect the memory used by the processes, it also includes the page cache memory.

The page cache is what stores all the files (binaries, libraries, working files, ...) which are currently in use or have been recently used.

When you run out of memory, the page cache gets flushed to give that memory back to your processes, basically trying to avoid crashes. The consequence of that is that now any access to those files must be performed again from scratch, that uses a lot of I/O and a bunch of CPU.

The patterns you're showing above are exactly what happens on a Linux system that's low on memory and where the page cache had to be emptied to save space. It's somewhat rare that things stay that way though as eventually one of the processes running in there will require more memory, fully running the system dry and triggering the OOM killer which will go and kill a process to get some memory back.

**Comment by jalbstmeijer** [comment]
@stgraber , 
You might be completely right. But somewhere I think the OOM killer is not being triggered where it should.
This impacts stability, especially where a shared local or remote storage back-end is shared among containers.

As I and @RDReindeer showed, this issue can not reproduced on OpenVZ6/7.
See also https://discuss.linuxcontainers.org/t/strange-continuous-read-io-burst-when-container-is-low-in-memory/14419/5

So there seems room for improvement.

If LXC is not the place to improve this, maybe you can point us were we should post this issue.

Gr, J

**Comment by stgraber** [comment]
We don't have any control on when the OOM killer triggers, it normally happens at the time a process calls `malloc` and the cgroup doesn't have sufficient memory to provide, whether it's free memory or currently buffered memory (page cache) that can be freeed to satisfy the request.

The usual ways to mitigate this are:
 - Provide some swap memory space if possible
 - Make sure that all running processes are aware of the memory limit (that means running LXCFS and if possible, something providing the correct memory limit through the sysinfo system call)
 - Apply I/O limits if your system can apply those (very few I/O controllers can do it these days)
 - Monitor your system, put alerts in place and take action before your memory consumption becomes a problem

Worth noting that what causes this kind of issue are processes which very slowly grow their memory footprint, anything which requires a lot more memory than is available or has large memory spikes will require more memory than the kernel can release by flushing the page cache and so will kick in the OOM killer.

You'll also want to make sure you're running on cgroup2 these days and a recent Linux kernel so you get to pull the memory pressure information for your containers and can monitor those values and react before you see system-wide impact.

**Comment by jalbstmeijer** [comment]
> We don't have any control on when the OOM killer triggers, it normally happens at the time a process calls `malloc` and the cgroup doesn't have sufficient memory to provide, whether it's free memory or currently buffered memory (page cache) that can be freeed to satisfy the request.

So, better to ask upstream at kernel/cgroup development?
I'll try to reproduce it again on a 6.1+ kernel.

> Worth noting that what causes this kind of issue are processes which very slowly grow their memory footprint, anything which requires a lot more memory than is available or has large memory spikes will require more memory than the kernel can release by flushing the page cache and so will kick in the OOM killer.

Did you ever try the procedure I posted to reproduce it?
No slow memory usage at all, it's almost instant.

**Comment by jalbstmeijer** [comment]
> I will retest with cgroup2 (disabled to support older containers) and see if that has different results.

Did not make any difference.

I'll put on my todo to see if I test against the 6.7.9 kernel

**Comment by david-barbion** [comment]
I've found that /run is a tmpfs and systemd-journald writes its journal in /run/log/journald. I've configured systemd-journald storage to none to avoid wasting memory.
