### ISSUE TITLE
cgroup error in containers

### ISSUE THREAD

**Issue by ich777** [lxc/lxc#4152]
# Required information

 * Distribution: Unraid - Slackware
 * Distribution version: Unraid 6.10.3 - Slackware 15.0
 * The output of
   * `lxc-start --version`: `5.0.0`
   * `lxc-checkconfig`: [lxc-checkconfig.txt](https://github.com/lxc/lxc/files/8948439/lxc-checkconfig.txt)
   * `uname -a`: `Linux Server 5.15.46-Unraid #1 SMP Fri Jun 10 11:08:41 PDT 2022 x86_64 Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz GenuineIntel GNU/Linux`
   * `cat /proc/1/mounts` do you really want this with about 30 containers...? :D
   * `cat /proc/self/cgroup`:
 ```
13:name=elogind:/c2
12:pids:/
11:hugetlb:/
10:net_prio:/
9:perf_event:/
8:net_cls:/
7:freezer:/
6:devices:/
5:memory:/
4:blkio:/
3:cpuacct:/
2:cpu:/
1:cpuset:/
0::/
```

# Issue description

I want to bring LXC to Unraid and already created a plugin as you can see [here](https://github.com/ich777/unraid-lxc-plugin) and [here](https://forums.unraid.net/topic/123935-plugin-lxc-plugin/) (this is LXC without LXD) and it is in very early stages.
No matter what I try I'm unable to mount cgroups to the containers or at least if I do so it ultimately fails.

Some distributions like Ubuntu Bionoic have issues to start as @Miosame already pointed out in this issue: #4145 and adding `lxc.init.cmd = /lib/systemd/systemd systemd.unified_cgroup_hierarchy=1` to the config makes the container start.

# Steps to reproduce

 1. Pull down a Alpine container on Unraid
 2. Install Docker in the container and try to install for example [appwrite](https://appwrite.io/)
 3. Get this message:
`docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write "c 10:200 rwm": write /sys/fs/cgroup/devices/docker/d397b582d07aa3fc689ccb6bd44ad163fc04f28af2dafd0e38dffde0d57a4eca/devices.allow: operation not permitted: unknown.`

Note: Even if I add `lxc.cgroup.devices.allow = c 10:200 rwm` to the container config it won't work.

# Information to attach

 - [X] any relevant kernel output [dmesg.txt](https://github.com/lxc/lxc/files/8948547/dmesg.txt)
 - [X] container log [alpine.log](https://github.com/lxc/lxc/files/8948527/alpine.log)
 - [X] the containers configuration file [config.txt](https://github.com/lxc/lxc/files/8948554/config.txt) (Please note: this is a real basic configuration without any modifications so far and I've already tried many things to get it to work)

The same also happens on LXC v`4.0.12`

Am I missing something obvious?

**Comment by ich777** [comment]
Something related also happens for instance if you try to install [FreeIPA](https://www.freeipa.org/page/Main_Page) on Fedora 36 for example with the command `ipa-server-install --mkhomedir`

![image](https://user-images.githubusercontent.com/28066518/175312578-05dbf223-5d23-42a8-8e32-715d9b864fb3.png)

**Comment by ich777** [comment]
Can't anybody help with this?

**Comment by Miosame** [comment]
@ich777 try reaching out in the lxc/lxd forums, https://discuss.linuxcontainers.org/ it seems to be generally more active
