### ISSUE TITLE
lxc  storage info  shows non existing  container

### ISSUE THREAD

**Issue by killiche** [lxc/lxc#4165]
* Distribution: ubuntu 1804
 * Distribution version: 3.0.3
# Issue description
lxc  storage info  shows non existing  container
as result the storage could not be removed

# Steps to reproduce
1 lxc storage info my-btrfs
---
info:
  description: ""
  driver: btrfs
  name: my-btrfs
  space used: 589.25MB
  total space: 1.02TB
used by:
  containers:
  - c8lb08-x64
  profiles:
  - my-btrfs
--- 
Here  the container c8lb08-x64   does not exist.  it  was  deleted looong  ago.  
There is no any folders with such name 
all tries to make a  fake container with lxd import  from backup.yaml   are failed. 
---
lxd import  c8lb08-x64 
Error: Storage volume for container "c8lb08-x64" already exists in the database. Set "force" to overwrite
--
lxd import -f c8lb08-x64 
Error: The name "c8lb08-x64" of the storage volume is not identical to the container's name "c8lb08-x64"
--- 
How I can  remove  storage  and non existed  container ?

**Comment by stgraber** [comment]
You'll need to use `lxd sql global "DELETE FROM storage_volumes WHERE name='c8lb08-x64'"`

**Comment by stgraber** [comment]
I'm closing the issue because this particular DB record likely predates our rework of our storage logic and current LXD is much less likely to be leaving such leftover records on creation or deletion failure.

**Comment by killiche** [comment]
Thank you .    that helped
