### ISSUE TITLE
lxc container can't access local lan in gw

### ISSUE THREAD

**Issue by askgh** [lxc/lxc#4171]
use lxc launch a simple conainer
curl publicip:80 is ok
curl publicip:22 is hang

why?

thanks

**Comment by getopendroplet** [comment]
@askgh hi, please provide more data.

**Comment by askgh** [comment]
i use snap install lxc with default config. the network is bridge

the linux host ip is 192.168.1.100, gw is 192.168.1.1

the lxc container ip is 10.60.211.9,

lxc container ip 10.60.211.9 ping linux host 192.168.1.100 is ok
lxc container ip 10.60.211.9 ping linux host gw 192.168.1.1 is error

**Comment by askgh** [comment]
@getopendroplet
