### ISSUE TITLE
Option 'sd-bus' hard depends on systemd while it should also be available in elogind

### ISSUE THREAD

**Issue by juippis** [lxc/lxc#4174]
# Required information

 * Distribution: Gentoo

# Issue description

A newly added configure option 'sd-bus' hard depends on systemd, but `sd_bus_call_method_asyncv` along with the files **/usr/include/elogind/sd-bus.h** and **/usr/include/elogind/sd-event.h** are available with [elogind](https://github.com/elogind/elogind), which is used as an alternative to systemd. I wonder if it's enough to satisfy the 'sd-dbus' build and runtime functionality?

**Comment by brauner** [comment]
Puh, good question. I honestly don't know. I think even if all the calls were available I don't think this would work because afaict there's no cgroup management done the same way systemd does?

**Comment by juippis** [comment]
People who know this stuff better than I do agrees with you :)
