### ISSUE TITLE
Build fails when /etc/default or /etc/sysconfig do not exist

### ISSUE THREAD

**Issue by CameronNemo** [lxc/lxc#4178]
If neither of these directories exist, then LXC_DISTRO_SYSCONF is never set, and I get some warnings and an error like so:

```
config/init/common/meson.build:3: WARNING: The variable(s) 'LXC_DISTRO_SYSCONF' in the input file 'config/init/common/lxc-containers.in' are not present in the given configuration data.
config/init/common/meson.build:10: WARNING: The variable(s) 'LXC_DISTRO_SYSCONF' in the input file 'config/init/common/lxc-net.in' are not present in the given configuration data.
meson.build:900:9: ERROR: Entry LXC_DISTRO_SYSCONF not in configuration data.
```

The relevant section of code is here:

https://github.com/lxc/lxc/blob/cbbb09b56f0ab3a9054daf38987c4a5520480289/meson.build#L119-L128

**Comment by CameronNemo** [comment]
Some information/context: this is in a void musl chroot. We use `/etc/default`, but none of the build dependencies have files `/etc/default`. On glibc we have `/etc/default/glibc-locales` so we do not run into the issue. For now I am working around this by just creating `/etc/default`.

One simple thing to make this error more clear is to explicitly error out in the third branch referenced.

**Comment by sgn** [comment]
Another way is allowing set `LXC_DISTRO_SYSCONF` by builder
