### ISSUE TITLE
Request for background information / reasoning why LXC_BRIDGE_MAC is hard-coded to "00:16:3e:00:00:00"

### ISSUE THREAD

**Issue by fde6-a09a-b373** [lxc/lxc#4189]
# Required information
 * Distribution: Debian
 * Distribution version: 11

# Issue description  
Default `lxcbr0` is using a static MAC address.

# Steps to reproduce
Using (the default) `USE_LXC_BRIDGE="true"` in `/etc/default/lxc-net`

As introduced in [84432621edd4e8b9fb82bb69ef52a8991e2b166a](https://github.com/lxc/lxc/commit/84432621edd4e8b9fb82bb69ef52a8991e2b166a) a/the default `lxcbr0` has the hard-coded address: "00:16:3e:00:00:00". 
This can be configured/overwritten in `/etc/default/lxc-net` by using `LXC_BRIDGE_MAC=<another mac address>` but I did not find any reference of this in the documentation, and revealed it from the source. (If someone could be point were to find it, I would appreciate it.)

My questions are:
* Why was there a need to hard-code a MAC address in the first place? [84432621edd4e8b9fb82bb69ef52a8991e2b166a](https://github.com/lxc/lxc/commit/84432621edd4e8b9fb82bb69ef52a8991e2b166a) does not give any information.
* As the bridges gets created with `ip link add dev ${LXC_BRIDGE} type bridge` why can't just the random MAC be used, which the device gets anyway?

Thanks.

**Comment by stgraber** [comment]
This is primarily for backward compatibility reason.

Linux up until pretty recently (not sure exactly when) would have the bridge take the lowest MAC address of all its members as its own. This would then mean that the bridge MAC would change as containers start and stop. This would in turn force ARP and would lead to a temporary loss in network connectivity.

Pinning a MAC on the bridge avoids this issue entirely.

**Comment by fde6-a09a-b373** [comment]
Thanks. Right, the (old) issue with an address of an enslaved devise ...
I think I just had to keep this in mind and need to ensure dedicated mac addresses for the bridge devices. Thanks again.
