### ISSUE TITLE
Add support for systemd's $container_ttys interface.

### ISSUE THREAD

**Issue by CameronNemo** [lxc/lxc#419]
It is described in [here](http://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/). It is preferred over fake ttys because it will cause less confusion to getty's and logind.

The reasoning is also described toward the bottom of [this systemd-devel](http://lists.freedesktop.org/archives/systemd-devel/2015-January/027433.html), as well as in other messages I am not going to dig up.

**Comment by brauner** [comment]
+1
 Commit fixed 393903d108f860bff092bb41b21f44fd20ea7045 this I think and works nice.

**Comment by hallyn** [comment]
Great, thanks for the update.
