### ISSUE TITLE
error_utils.h question

### ISSUE THREAD

**Issue by DuratarskeyK** [lxc/lxc#4206]
# Issue description

src/lxc/error_utils.h lines 50 to 104. Can someone explain the reasoning behind including 54 lines of code, that culminate in the IN_SET macros, that supposedly checks if x is present in later arguments(up to 20 arguments). If github is to be believed, IN_SET is used 7 times in the entire code and always with 3 parameters, which could simply be replaced with an OR condition.

# Steps to reproduce

 1. Open src/lxc/error_utils.h
 2. Stare in awe at lines 50-104
 3. Do a git grep IN_SET

**Comment by mihalicyn** [comment]
Looks covered by https://github.com/lxc/lxc/pull/4209
