### ISSUE TITLE
lxc-create -t /path/to/template -h looks in incorrect directory.

### ISSUE THREAD

**Issue by Sleaker** [lxc/lxc#421]
Running Ubuntu 14.04 and LXC 1.0.6-0ubuntu0.1

the -t option for lxc-create allows the specification of a hard-path to a custom template.  if you attempt to run the -h option to dump the help portion of the template file lxc will throw an error.

Example:
lxc-create -t /path/to/my/template -h

lxc: Error executing /usr/share/lxc/templates/lxc-/path/to/my/template -h

Expected: The template script is executed with the -h option rather than attempting to run the script from the /usr/share/lxc/templates directory.

**Comment by stgraber** [comment]
Sent a patch for that one to lxc-devel.

**Comment by Sleaker** [comment]
thanks much stgraber!
