### ISSUE TITLE
lxc-download for unprivileged containers

### ISSUE THREAD

**Issue by brauner** [lxc/lxc#422]
Hello. When I try to download `rootfs` images for unprivileged containers certain distributions do not show up (`fedora`, `OpenSuse`, `Plamo`, `Gentoo`). Is this expected? And if so how can I get hold of unprivileged `rootfs` images for these distributions?

My `lxc` version is `1.1.0.rc3.8.g393903d-1` running on `Archlinux` with `user ns` enabled kernel.

**Comment by stgraber** [comment]
It is expected. The download template only lists distros which will work unprivileged.
