### ISSUE TITLE
Frequent kernel panics when doing heavy I/O in containers on Btrfs

### ISSUE THREAD

**Issue by LenzGr** [lxc/lxc#424]
I'm running Ubuntu 14.04.1 LTS (x86_64) on my Laptop. Current Kernel version is "3.13.0-44-generic". The LXC version is "1.0.7-0ubuntu0.1", installed from the "ubuntu-lxc" PPA on Launchpad.

I have a dedicated Btrfs file system mounted on ```/container/```, which I use for storing all LXC containers. 

The file system is created on top of a logical volume:

```
lenz@lenz-ThinkPad-T440 ~ % mount | grep container
/dev/mapper/ubuntu--vg-container on /container type btrfs (rw)
lenz@lenz-ThinkPad-T440 ~ % sudo lvdisplay /dev/mapper/ubuntu--vg-container
  --- Logical volume ---
  LV Path                /dev/ubuntu-vg/container
  LV Name                container
  VG Name                ubuntu-vg
  LV UUID                JUq21P-SSoS-UeU5-rdDS-k6V4-d30e-gJM1FA
  LV Write Access        read/write
  LV Creation host, time lenz-ThinkPad-T440, 2014-09-15 13:42:27 +0200
  LV Status              available
  # open                 1
  LV Size                65,00 GiB
  Current LE             16640
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           252:5
```

The hard disk drive is a Samsung SSD ("Samsung SSD 840 EVO 500GB, EXT0BB0Q, max UDMA/133", according to dmesg).

I have a number containers based on CentOS 6, these were created by cloning a base image using ```lxc-clone -s```.

Quite frequently, when I create heavy disk I/O in one or several of these containers (e.g. by running ```yum update``` concurrently, or by transferring large files e.g. via a HTTP upload to one of the container instances), my host system freezes. This only happens when container activity is involved, the system runs stable otherwise. Most of the time the X desktop freezes, sometimes a Kernel panic can be observed on the console. Unfortunately I'm unable to capture it other than by taking a picture. The only solution is to perform a cold reboot using the power button.

This occurred to me before. I then re-created the ```/container/``` file system from scratch and started again. But now it's happening again, so I would like to report it for investigation.

Here are two screen shots of the kernel panics I observed in the last few days - I hope they are readable:

![img_20150126_095337](https://cloud.githubusercontent.com/assets/263427/5938371/9dc2f36a-a6fa-11e4-8852-08f92166da23.jpg)

![img_20150128_133720](https://cloud.githubusercontent.com/assets/263427/5938377/b6d2e4d2-a6fa-11e4-8dde-e59536f13ab2.jpg)

**Comment by LenzGr** [comment]
Of course this could very likely be a Btrfs issue. But so far I've only experienced these kernel crashes when using Btrfs in combination with LXC - hence I report this here first.

**Comment by stgraber** [comment]
This is a kernel bug. Under no circumstances should the kernel panic. LXC is purely userspace so there's nothing that we can do about this. Please file a bug against the Ubuntu kernel.

**Comment by LenzGr** [comment]
OK, fair enough - thanks! I'll try to submit this as a kernel bug there.

**Comment by LenzGr** [comment]
FWIW, I now reported it on Launchpad: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1415510
