### ISSUE TITLE
Building troubles in ubuntu

### ISSUE THREAD

**Issue by 12D687** [lxc/lxc#4240]
# Required information

 * Distribution: Ubuntu
 * Distribution version:20.04 LTS
I'm trying to build lxc from source. When I execute the readme's build commands then I face the below error message. I had installed the docbook-utils package (version 0.6.14-3.3).

# Steps to reproduce

 1. Go to lxc root build directory
 2. run make or meson compile -C build
 3. Then you face this issue (or then your "should" face this issue).
 Error message:
doc/meson.build:67:8: ERROR: Command "/usr/bin/docbook2man --encoding=UTF-8 lxc.sgml" failed with status 1.

**Comment by mihalicyn** [comment]
Please, try to install `docbook2x` instead. It's a known issue with `docbook-utils`.

**Comment by 12D687** [comment]
Hi
Thanks. I installed the package an it works. But wonder how to launch lxc. Because when I type the name in terminal it claims that there is no lxc.

**Comment by mihalicyn** [comment]
Did you install it by `DESTDIR=/path/to/install/directory ninja -C build install`?

**Comment by 12D687** [comment]
Sorry for this late reply
It doesn't work form me. Because ninja claims that:
ninja: error: loading 'build.ninja': No such file or directory
Instead I tried to build it into /usr/local using the readme's building instructions. But I still cannot launch lxc (because it weirdly symlinks the binaries to /usr/local but doesn't move them into it)

**Comment by mihalicyn** [comment]
@12D687 please provide full commands for each step

I've checked on my system just now
```
lxc$ meson setup -Dprefix=/usr build
lxc$ meson compile -C build
lxc$ DESTDIR=/some/path ninja -C build install
```

Please ensure that you running these commands from the LXC root directory (not a build directory!)

**Comment by 12D687** [comment]
1. First I run meson setup -Dprefix=/usr build
2. meson compile -C build
3. When I run DESTDIR=/usr/local ninja -C build install. Then I get follow command line output
ninja: Entering directory `build'
[0/1] Installing files.
Installing src/lxc/liblxc.a to /usr/local/usr/lib/x86_64-linux-gnu
Installing liblxc.so.1.7.0 to /usr/local/usr/lib/x86_64-linux-gnu
Installing hooks/unmount-namespace to /usr/local/usr/libexec/lxc/hooks
Installing src/lxc/cmd/init.lxc.static to /usr/local/usr/sbin
Installing src/lxc/cmd/init.lxc to /usr/local/usr/sbin
Installing src/lxc/cmd/lxc-monitord to /usr/local/usr/libexec/lxc
Installing src/lxc/cmd/lxc-user-nic to /usr/local/usr/libexec/lxc
Installing src/lxc/cmd/lxc-usernsexec to /usr/local/usr/bin
Installing src/lxc/tools/lxc-attach to /usr/local/usr/bin
Installing src/lxc/tools/lxc-autostart to /usr/local/usr/bin
Installing src/lxc/tools/lxc-cgroup to /usr/local/usr/bin
Installing src/lxc/tools/lxc-checkpoint to /usr/local/usr/bin
Installing src/lxc/tools/lxc-config to /usr/local/usr/bin
Installing src/lxc/tools/lxc-console to /usr/local/usr/bin
Installing src/lxc/tools/lxc-copy to /usr/local/usr/bin
Installing src/lxc/tools/lxc-create to /usr/local/usr/bin
Installing src/lxc/tools/lxc-destroy to /usr/local/usr/bin
Installing src/lxc/tools/lxc-device to /usr/local/usr/bin
Installing src/lxc/tools/lxc-execute to /usr/local/usr/bin
Installing src/lxc/tools/lxc-freeze to /usr/local/usr/bin
Installing src/lxc/tools/lxc-info to /usr/local/usr/bin
Installing src/lxc/tools/lxc-ls to /usr/local/usr/bin
Installing src/lxc/tools/lxc-monitor to /usr/local/usr/bin
Installing src/lxc/tools/lxc-snapshot to /usr/local/usr/bin
Installing src/lxc/tools/lxc-start to /usr/local/usr/bin
Installing src/lxc/tools/lxc-stop to /usr/local/usr/bin
Installing src/lxc/tools/lxc-top to /usr/local/usr/bin
Installing src/lxc/tools/lxc-unfreeze to /usr/local/usr/bin
Installing src/lxc/tools/lxc-unshare to /usr/local/usr/bin
Installing src/lxc/tools/lxc-wait to /usr/local/usr/bin
Installing new directory /usr/local/var/cache/lxc
Installing new directory /usr/local/var/lib/lxc
Installing /home/username/lxc/build/src/lxc/attach_options.h to /usr/local/usr/include/lxc
Installing /home/username/lxc/build/src/lxc/lxccontainer.h to /usr/local/usr/include/lxc
Installing /home/username/lxc/build/src/lxc/version.h to /usr/local/usr/include/lxc
Installing /home/username/lxc/build/src/lxc/lxc.functions to /usr/local/usr/share/lxc
Installing /home/username/lxc/build/config/bash/_lxc to /usr/local/usr/share/bash-completion/completions
Installing /home/username/lxc/build/config/etc/default.conf to /usr/local/etc/lxc
                                                     ...
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-attach
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-autostart
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-cgroup
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-checkpoint
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-config
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-console
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-copy
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-create
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-destroy
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-device
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-execute
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-freeze
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-info
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-ls
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-monitor
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-snapshot
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-start
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-stop
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-top
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-unfreeze
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-unshare
Installing symlink pointing to _lxc to /usr/local/usr/share/bash-completion/completions/lxc-usernsexec
                                                       ...
5. ls -l /usr/local/lxc total 0
So it doesn't move any binaries in /usr/local/lxc. Instead it weirdly symlinks them to /usr/local/lxc. I'm running all these above commands in lxc root directory.

**Comment by mihalicyn** [comment]
According to logs that you have provided `lxc` binaries are in the `/usr/local/usr/bin` directory.
