### ISSUE TITLE
Feasibility to manage multiple lxc environment

### ISSUE THREAD

**Issue by adhicode** [lxc/lxc#4241]
Hi Team
I would need to manage multiple environments (aka group of containers) and each environment shall have container control info, container storage, etc. Pls suggest if its feasible.

Thanks for help
Here the platform + LxC info,

root@Bea6:/opt/lxc/NOS/Sense# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='Chaos Calmer'
DISTRIB_REVISION='eb807c1efc413eb0964ccdf8e8faa31174963fe1'
DISTRIB_CODENAME='chaos_calmer'
DISTRIB_TARGET='ipq/ipq807x'
DISTRIB_DESCRIPTION='OpenWrt Chaos Calmer 15.05.1'
DISTRIB_TAINTS='no-all busybox override'

oot@Bea6:/opt/lxc/NOS/Sense# uname -a
Linux 4.4.60 https://github.com/lxc/lxc/issues/47 SMP PREEMPT Mon Oct 31 16:19:18 UTC 2022 armv7l GNU/Linux

root@Bea6:/opt/lxc/NOS/Sense# lxc-start --version
4.0.10

root@Beacon 6:/opt/lxc/NOS/Sense# lxc-checkconfig
LXC version 4.0.10
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
newuidmap is not installed
newgidmap is not installed
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroups: enabled
Cgroup namespace: missing

Cgroup v1 mount points:
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/cpu
/sys/fs/cgroup/cpuacct
/sys/fs/cgroup/memory
/sys/fs/cgroup/devices
/sys/fs/cgroup/freezer
/sys/fs/cgroup/net_cls
/sys/fs/cgroup/blkio
/sys/fs/cgroup/pids

Cgroup v2 mount points:

Cgroup v1 systemd controller: missing
Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: missing
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, loaded
CONFIG_NF_NAT_IPV6: enabled, loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: missing
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: missing
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: missing
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: missing
CONFIG_INET_DIAG: missing
CONFIG_PACKET_DIAG: missing
CONFIG_NETLINK_DIAG: missing
File capabilities:

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

**Comment by mihalicyn** [comment]
Couldn't you clarify what do you mean by "have container control info"?

>container storage, etc

I'm not sure that I've fully understood your question but each container rootfs can live in a different storage if needed.

**Comment by adhicode** [comment]
hi @mihalicyn Thanks. Yes each container shall have rootfs n other bindpoints n other propagated or dedicated resources. May be, your answers help already if i put one abstracted view of requirement
*) Container envX:
all of containers X_i would use lxc config thats defined for envX. For ex, lxc.cgroup.cpuset.cpus = 0,1
we shall able to use all other config params like cpu pinning given above but specific to envX.
*) Container env Y
all of containers X_i would use lxc config thats defined for envX. For ex, lxc.cgroup.cpuset.cpus = 2,3 (OR)  0,1 with appropriate shares.
we shall able to use all other config params like cpu pinning given above but specific to envY.

**Comment by mihalicyn** [comment]
I think I understand what you ask. You want to group containers into some kind of "configuration groups" and then manage some common parameters on a group-level basis instead of a container-level, correct?

We have really close feature https://linuxcontainers.org/lxd/docs/master/profiles/

**Comment by adhicode** [comment]
hi @mihalicyn Thank you, Yes, it would be good to double confirm it.  As i understand, we typically have one profile (if i put the definition using profiles) that provides config, storage and controlling all namespaces for the containers that would get created using this default profile. Using lxc profiles, we can replicate default profile as we require to control specific group of containers.
Am i correct?
Thanks

**Comment by hallyn** [comment]
You can simply put the configuration files into separate directories and use the '-P lxcpath' option to lxc-* commands to keep containers of different "profiles" separated.  For instance 'lxc-ls -P /var/lib/lxc-ssd', 'lxc-ls -P /var/lib/lxc-other', etc.

**Comment by adhicode** [comment]
Hi @mihalicyn @hallyn Indeed I already use -P option for file system and certain global level config. For instance, I use /opt/lxc/myOS instead of default.  I understand, We still have control via /etc and how it can be grouped as per my requirements. Thanks a lot

**Comment by adhicode** [comment]
Hi @mihalicyn @hallyn Its still not clear on how we can handle this requirement. Kindly help. Thanks

**Comment by hallyn** [comment]
I guess I misread your previous response.

You're still being quite vague about what exactly want.  But in any case if you're not happy using -P lxcpath for this, then you'll need to implement a higher level management layer on top of lxc.  Perhaps a new lxc creation template could accept a --env argument and set some default configuration based on that.

**Comment by adhicode** [comment]
Hi @hallyn thanks for helping. Let me clarify it again. Pls have a look at https://github.com/lxc/lxc/issues/208 as well
I would need multiple lxcpaths to manage multiple groups of containers. /etc/lxc/lxc.conf can point to one storage and its configs but i would need to manage as below,
cat /etc/lxc/lxc.conf
/opt/containerGroup1 --> this will be used with -P when i mange a container using this group for storage and configs.
/opt/conainerGroup2

By this way, i can insulate/isolate the environment for multiple groups of containers. Kindly let me know if it can be achieved. 
Note: I would also investigate your template suggestion.

**Comment by adhicode** [comment]
Hi @hallyn @mihalicyn @stgraber Kindly help. Would you pls confirm that we dont have any other file based variables to operate when we use "-P" option? If we use "-P" with specific directory, storage of containers and config can be managed that specific directory.
Thanks a lot

**Comment by hallyn** [comment]
Confirmed.

I neither have nor know of anyone else having plans to implement this.  I'm going to close this.  If you intend to try and implement something yourself, please feel free to re-open.

**Comment by adhicode** [comment]
Hi @hallyn Thanks for confirming, "-P" option should work in this use case. i would try managing containers in such groups and share notes/issues if any.
Thanks
