### ISSUE TITLE
Mounting proc:mixed fails if sysrq is not enabled

### ISSUE THREAD

**Issue by Bun** [lxc/lxc#425]
If `/proc/sysrq-trigger` does not exist, the `proc:mixed` automount fails:

    lxc-start: conf.c: lxc_mount_auto_mounts: 801 No such file or directory - error mounting /usr/lib/lxc/rootfs/proc/sysrq-trigger on /usr/lib/lxc/rootfs/proc/sysrq-trigger flags 4096
    lxc-start: conf.c: lxc_setup: 4153 failed to setup the automatic mounts for 'example'
    lxc-start: start.c: do_start: 688 failed to setup the container

Changing to `proc:rw` does work, but would leave `/proc/sys` unprotected which is not desirable.

This should not be an error, since protecting `/proc/sysrq-trigger` isn't needed if it doesn't exist. I.e. if `CONFIG_MAGIC_SYSRQ` is not enabled.

Tested on lxc 1.0.7 on Gentoo Hardened (3.17.7-r1)

**Comment by stgraber** [comment]
Oops, indeed we should fix that, especially now that proc:mixed is the default (as of 1.1).

**Comment by stgraber** [comment]
I have submitted a patch which ought to fix this. It's currently on lxc-devel awaiting review.
