### ISSUE TITLE
Idea for lxc-checkconfig: sysctl user.max_user_namespaces

### ISSUE THREAD

**Issue by maxnikulin** [lxc/lxc#4259]
Consider adding to `lxc-checkconfig` a test for
```sh
sysctl user.max_user_namespaces
cat /proc/sys/user/max_user_namespaces
```
Despite currently it should enabled by default, namespaces might be considered as additional target for attacks by some users, see e.g.
<https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898446#112>
so the parameter might be changed in local config.

Taking into account that LXC errors are often quite cryptic, additional diagnostics by `lxc-checkconfig` might be helpful.

Feel free to reject this request if you prefer to keep scope of `lxc-checkconfig` to kernel compile config leaving aside runtime configuration.

**Comment by mihalicyn** [comment]
cc @stgraber

**Comment by stgraber** [comment]
Yeah, would make sense to show the sysctl value in the output when present.

**Comment by maxnikulin** [comment]
Thanks for implementing it.

Though I am unsure whether I would easily associate values with `sysctl user.max_user_namespaces` looking into a pretty-print report:
```
Namespace limits:
  cgroup: 93423
  ipc: 93423
  mnt: 93423
  net: 93423
  pid: 93423
  time: 93423
  user: 93423
  uts: 93423
```
