### ISSUE TITLE
lxc-test-fuzzers is broken

### ISSUE THREAD

**Issue by hallyn** [lxc/lxc#4261]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of
   * `lxc-start --version`
   * `lxc-checkconfig`
   * `uname -a`
   * `cat /proc/self/cgroup`
   * `cat /proc/1/mounts`

# Issue description

lxc-test-fuzzers is broken:

serge@jerom ~/src/lxc/src/tests$ ./lxc-test-fuzzers
+ set -o pipefail
++ mktemp -d
+ TMP_DIR=/tmp/tmp.vq7l35MsvZ
+ export ASAN_OPTIONS=detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:strict_string_checks=1
+ ASAN_OPTIONS=detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:strict_string_checks=1
+ export UBSAN_OPTIONS=print_stacktrace=1:print_summary=1:halt_on_error=1
+ UBSAN_OPTIONS=print_stacktrace=1:print_summary=1:halt_on_error=1
+ trap cleanup exit
+ for fuzzer in /usr/bin/fuzz-lxc-*
++ basename '/usr/bin/fuzz-lxc-*'
+ name='fuzz-lxc-*'
+ corpus_dir='/tmp/tmp.vq7l35MsvZ/fuzz-lxc-*'
+ mkdir -p '/tmp/tmp.vq7l35MsvZ/fuzz-lxc-*'
+ wget --directory-prefix=/tmp/tmp.vq7l35MsvZ 'https://storage.googleapis.com/lxc-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/lxc_fuzz-lxc-*/public.zip'
Warning: wildcards not supported in HTTP.
--2023-01-18 11:56:15--  https://storage.googleapis.com/lxc-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/lxc_fuzz-lxc-*/public.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 2607:f8b0:4023:1009::80, 2607:f8b0:4023:1006::80, 2607:f8b0:4023:1000::80, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|2607:f8b0:4023:1009::80|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-01-18 11:56:15 ERROR 403: Forbidden.

+ '/usr/bin/fuzz-lxc-*' -max_total_time=120 '/tmp/tmp.vq7l35MsvZ/fuzz-lxc-*'
./lxc-test-fuzzers: line 24: /usr/bin/fuzz-lxc-*: No such file or directory
+ cleanup
+ rm -rf /tmp/tmp.vq7l35MsvZ

Looks like the URL needs to be updated.

**Comment by hallyn** [comment]
@evverx @diederikdehaas   Do you know offhand what should be the new location?

**Comment by evverx** [comment]
Looks like the fuzz targets are no longer installed to `/usr/bin`. I think this script can be safely removed because that local fuzzing infrastructure was removed when `lxc` switched to `meson`. CIFuzz runs the fuzz targets with those corpora on every PR these days anyway.

**Comment by diederikdehaas** [comment]
@hallyn maybe you tried to get someone else's attention?

**Comment by hallyn** [comment]
> @hallyn maybe you tried to get someone else's attention?

Could be - apologies if so.  I was looking at the changelog which listed     Signed-off-by: Diederik de Haas <didi.debian@cknow.org>

**Comment by hallyn** [comment]
(but I do see that it was not actually relevant to the test itself, so in any case a bad callout.  Sorry)

**Comment by diederikdehaas** [comment]
No worries :)  
I did make changes, but that was without knowing or understanding the full tests. So I can't provide any useful input here.
