### ISSUE TITLE
Which dbus library to use

### ISSUE THREAD

**Issue by hallyn** [lxc/lxc#4266]
Currently liblxc has to link against libsystemd to use dbus calls to create scopes.

lxc also wants to create a statically linked lxc-init, so that it can bind mount it into any container of any (or no) distro, and run it without dependencies.

What alternatives do we have for a dbus client library which is not deprecated and provides a statically linked library?

qt and glib both provide dbus libraries, but they are not statically linked by default.  libnih-dbus is obviously way out of support.  dbus itself advises not using it, although it may actually be our best bet.  Are there any other alternatives?

**Comment by stgraber** [comment]
@hallyn would calling out `dbus-send` when not linked against a dynamic dbus library be an option?

I don't think we should depend on libnih-dbus given that upstream has been dead a long time and may get removed from distros at any time.

**Comment by hallyn** [comment]
> @hallyn would calling out `dbus-send` when not linked against a dynamic dbus library be an option?

None of the statically linked users that I know of so far would actually need to do any dbus calls at all anyway - not lxc-init and not stacker, anyway.  But I'm not sure how we can code that up.  We'd have to follow a different codepath depending on how we're being linked.  I guess we can add a -Dstatic=true or something, and have that compile out the libsystemd.so callouts and replace with dbus-send.

> I don't think we should depend on libnih-dbus given that upstream has been dead a long time and may get removed from distros at any time.

lol yes and especially given that it suffers an unfortunate usage of select() and crashes any callers using fds > 1024.
