### ISSUE TITLE
[bpf] lxc-4.0.3 load bpf failed

### ISSUE THREAD

**Issue by duguhaotian** [lxc/lxc#4293]
# Required information

 * Distribution: fedora
 * Distribution version: 37
 * The output of
   * `lxc-start --version`：4.0.3
   * `lxc-checkconfig`
   * `uname -a`
   * `cat /proc/self/cgroup`
   * `cat /proc/1/mounts`

# Issue description

# Steps to reproduce

1. config file: 
```
lxc.rootfs.path = /root/lxctest/overlay/mergdir/
lxc.uts.name = 90927f98914b
lxc.init.cmd = /test
lxc.init.cwd = /
lxc.environment = PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
lxc.environment = HOSTNAME=90927f98914b
lxc.mount.auto = proc:rw
lxc.console.logfile = /tmp/test.log
lxc.cgroup.dir = lxc
lxc.cgroup2.devices.deny = a *:* rwm
lxc.rootfs.mount = /tmp/lxchome
lxc.pty.max = 1024
```
2. `lxc-start -F -f config -n  90927f98914b --logfile=/tmp/xxx.log` 
3. got error message：
```
lxc-start: 90927f98914b: cgroups/cgroup2_devices.c: bpf_program_load_kernel: 332 Invalid argument - Failed to load bpf program
lxc-start: 90927f98914b: cgroups/cgroup2_devices.c: bpf_program_cgroup_attach: 364 Unknown error -1 - Failed to load bpf program
lxc-start: 90927f98914b: cgroups/cgfsng.c: cgfsng_devices_activate: 3019 Cannot allocate memory - Failed to attach bpf program
lxc-start: 90927f98914b: start.c: lxc_spawn: 1791 Failed to setup cgroup2 device controller limits
lxc-start: 90927f98914b: start.c: __lxc_start: 1950 Failed to spawn container "90927f98914b"
lxc-start: 90927f98914b: tools/lxc_start.c: main: 308 The container failed to start
lxc-start: 90927f98914b: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and --logpriority options
```

i found error cause by config item: **lxc.cgroup2.devices.deny = a *:* rwm**
this item, make only https://github.com/lxc/lxc/blob/master/src/lxc/cgroups/cgroup2_devices.c#L274  add to bpf,
and if add log_buf for bpf, load bpf will report error: **bpf unreachable insn 8**

## resolve patch

after line: https://github.com/lxc/lxc/blob/master/src/lxc/cgroups/cgroup2_devices.c#L230

```
// add a check, if no jump should do, just return.
if (jump_nr == 1)
   return 0;
```

i donot know, this patch is ok?

**Comment by duguhaotian** [comment]
> Hi @duguhaotian
> 
> `uname -a`?

Linux localhost.localdomain 6.0.7-301.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov 4 18:35:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by duguhaotian** [comment]
> Hi @duguhaotian!
> 
> I can't reproduce this on `5.19.0-1008-kvm`. Before changing anything I think we need to understand is this is change in eBPF verifier in the kernel or LXC problem.
> 
> Couldn't you try to reproduce this on the LXC `master` branch version?

```
$ lxc-start -F -n 90927f98914b -f ./config -l error -o /tmp/xxx.log
lxc-start: 90927f98914b: ../src/lxc/utils.c: open_devnull: 1231 Operation not permitted - Can't open /dev/null
hello world
$ lxc-start --version
5.0.0
```

--> no error in 5.0.0

**Comment by mihalicyn** [comment]
Are you ready to upgrade to LXC 5.0.x?

I'm not sure if we still support LXC 4.* branches.
cc @stgraber

**Comment by duguhaotian** [comment]
> Are you ready to upgrade to LXC 5.0.x?
> 
> I'm not sure if we still support LXC 4.* branches. cc @stgraber

curious why this is? i check the code of cgroup2_devices.c, donot found difference.

**Comment by mihalicyn** [comment]
> > Are you ready to upgrade to LXC 5.0.x?
> > I'm not sure if we still support LXC 4.* branches. cc @stgraber
> 
> curious why this is? i check the code of cgroup2_devices.c, donot found difference.

between LXC 4.0.3 and 5.0.x? I can see many differences. But yes, I can't see any difference between 4.0.12 and 5.0.x

**Comment by duguhaotian** [comment]
> 

OK, we can update to 5.0.x to fix it. just close this issuse
