### ISSUE TITLE
segfault in python bindings

### ISSUE THREAD

**Issue by mgwilliams** [lxc/lxc#430]
Assuming that neither 'base' nor 'test' containers exist, this generates a segfault on the last line:

``` python
base1 = lxc.Container('base')
base2 = lxc.Container('base')
base2.create('download', lxc.LXC_CREATE_QUIET, {'dist': 'ubuntu',
                                                'release': 'trusty',
                                                'arch': 'amd64'})
base1.clone('test')
```

kernel: 3.13.0-45-generic
lxc: 1.0.7

**Comment by marcosps** [comment]
Does not happen in my local tests using:
kernel:4.13.13-300.fc27.x86_64
lxc: 2.1.0-devel

can you test again?

**Comment by brauner** [comment]
If this is still reproducible in 1.0.11 please re-open.
