### ISSUE TITLE
ERROR: Failed to download https://images.linuxcontainers.org//images/ubuntu/jammy/amd64/default/20230423_12:40//rootfs.tar.xz

### ISSUE THREAD

**Issue by zanferrari** [lxc/lxc#4306]
If I try to create a container from template (download) with this command:

sudo lxc-create --template download -n name_of_cnt -o ./create.log -- --dist ubuntu --release jammy --arch amd64 1> exec.log

I get the error:

ERROR: Failed to download https://images.linuxcontainers.org//images/ubuntu/jammy/amd64/default/20230423_12:40//rootfs.tar.xz

Then I try to download the footfs.tar.xz manually with wget and I get the output below:

 wget https://images.linuxcontainers.org//images/ubuntu/jammy/amd64/default/20230423_12:40//rootfs.tar.xz
--2023-04-24 11:04:12--  https://images.linuxcontainers.org//images/ubuntu/jammy/amd64/default/20230423_12:40//rootfs.tar.xz
Resolving images.linuxcontainers.org (images.linuxcontainers.org)... 45.45.148.8, 2602:fc62:a:1::8
Connecting to images.linuxcontainers.org (images.linuxcontainers.org)|45.45.148.8|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://fra1lxdmirror01.do.letsbuildthe.cloud//images/ubuntu/jammy/amd64/default/20230423_12:40//rootfs.tar.xz [following]
--2023-04-24 11:04:13--  https://fra1lxdmirror01.do.letsbuildthe.cloud//images/ubuntu/jammy/amd64/default/20230423_12:40//rootfs.tar.xz
Resolving fra1lxdmirror01.do.letsbuildthe.cloud (fra1lxdmirror01.do.letsbuildthe.cloud)... 164.90.187.92, 2a03:b0c0:3:d0::3b:1
Connecting to fra1lxdmirror01.do.letsbuildthe.cloud (fra1lxdmirror01.do.letsbuildthe.cloud)|164.90.187.92|:443... connected.
ERROR: cannot verify fra1lxdmirror01.do.letsbuildthe.cloud's certificate, issued by ‘emailAddress=support@fortinet.com,CN=FG1K2D3I17800413,OU=Certificate Authority,O=Fortinet,L=Sunnyvale,ST=California,C=US’:
  Self-signed certificate encountered.
To connect to fra1lxdmirror01.do.letsbuildthe.cloud insecurely, use `--no-check-certificate'.

At the end of all there is a server with a self signed certificate...that's not so good I suppose...

Please see if you can correct this....

Thanks.

**Comment by stgraber** [comment]
You're dealing with a corporate proxy server here.

**Comment by stgraber** [comment]
```
stgraber@castiana:~$ wget https://images.linuxcontainers.org//images/ubuntu/jammy/amd64/default/20230423_12:40//rootfs.tar.xz
--2023-04-24 11:38:19--  https://images.linuxcontainers.org//images/ubuntu/jammy/amd64/default/20230423_12:40//rootfs.tar.xz
Resolving images.linuxcontainers.org (images.linuxcontainers.org)... 45.45.148.8, 2602:fc62:a:1::8
Connecting to images.linuxcontainers.org (images.linuxcontainers.org)|45.45.148.8|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://fra1lxdmirror01.do.letsbuildthe.cloud//images/ubuntu/jammy/amd64/default/20230423_12:40//rootfs.tar.xz [following]
--2023-04-24 11:38:20--  https://fra1lxdmirror01.do.letsbuildthe.cloud//images/ubuntu/jammy/amd64/default/20230423_12:40//rootfs.tar.xz
Resolving fra1lxdmirror01.do.letsbuildthe.cloud (fra1lxdmirror01.do.letsbuildthe.cloud)... 164.90.187.92, 2a03:b0c0:3:d0::3b:1
Connecting to fra1lxdmirror01.do.letsbuildthe.cloud (fra1lxdmirror01.do.letsbuildthe.cloud)|164.90.187.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 112052744 (107M) [application/octet-stream]
Saving to: ‘rootfs.tar.xz’

rootfs.tar.xz                                               100%[==========================================================================================================================================>] 106.86M  13.1MB/s    in 8.2s    

2023-04-24 11:38:28 (13.0 MB/s) - ‘rootfs.tar.xz’ saved [112052744/112052744]
```

**Comment by zanferrari** [comment]
thanks, May be that the self signed certificate is still present in the cache of the fortinet? I tried on a laptop without vpn connection and it goes as a charm...
