### ISSUE TITLE
lxc 32-bit application (ARMv7l-32-bit) on the 64-bit host (ARMv8)

### ISSUE THREAD

**Issue by adhicode** [lxc/lxc#4307]
Can 32-bit application run seamlessly on 64-bit host?
If we have any propagated rootfs from host, how does it work?

`
root@myHost 6:/lib# uname -a
Linux myHost 6 5.4.164 #0 SMP PREEMPT Mon Feb 6 12:01:57 2023 armv7l GNU/Linux
root@myHost 6:/lib#

root@myHost 6:/lib# file libubox.so
libubox.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, no section header
root@myHost 6:/lib#

root@myHost 6:/# lxc-info --version
3.2.1
root@myHost 6:/# lxc-checkconfig
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
newuidmap is not installed
newgidmap is not installed
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points:
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/cpu
/sys/fs/cgroup/cpuacct
/sys/fs/cgroup/memory
/sys/fs/cgroup/devices
/sys/fs/cgroup/freezer
/sys/fs/cgroup/net_cls
/sys/fs/cgroup/blkio
/sys/fs/cgroup/pids

Cgroup v2 mount points:

Cgroup v1 systemd controller: missing
Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: missing
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: missing
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: missing
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: missing
CONFIG_FHANDLE: missing
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: missing
CONFIG_INET_DIAG: missing
CONFIG_PACKET_DIAG: missing
CONFIG_NETLINK_DIAG: missing
File capabilities:

**Comment by mihalicyn** [comment]
Hi @adhicode 

how this question is related to the LXC? :)

ARM has so many types and sub types. We are not ARM architecture experts there. It's better to check this experimentally or refer to the ARM architecture/CPU manual to understand if it will work for you or not. As far as I know, in some cases 32-bit ARMv7 apps can run on ARMv8 but there are some limitations (some instructions were deprecated or so). So, easiest way is to try.

**Comment by adhicode** [comment]
hi @mihalicyn Thanks for quick response:) Indeed its not directly related to lxc code. If anyone tried or could share some views like you, it would be helpful as i am building a generic APP and my only runtime is lxc:)
Thanks

**Comment by mihalicyn** [comment]
if you want to share experience/discuss with other users it's better to create a topic on https://discuss.linuxcontainers.org I believe.
Because the Github Issues is the place for LXC bugs. ;-)

**Comment by adhicode** [comment]
Thank you @mihalicyn :)
