### ISSUE TITLE
OOMScoreAdjust= in dbus.service on systemd-based unprivileged containers

### ISSUE THREAD

**Issue by brauner** [lxc/lxc#431]
In the past I had troubles getting systemd-based unprivileged containers such as Archlinux, Fedora or Debian Jessie to boot. On the other hand some systemd-based unpriv. containers such as Ubuntu Vivid worked fine and out of the box. (But I remember Stéphane once saying that they were somehow patched.)

With a little trick I can now also get Archlinux and Fedora unpriv. containers booting out of the box.

For this to work the `dbus.service` file in the unpriv.  Archlinux/Fedora container under `/usr/lib/systemd/system/` must be patched. It contains the entry:

    OOMScoreAdjust=-900

where `OOMScoreAdjust` in a `systemd` `.service`-file:

    "Sets the adjustment level for the Out-Of-Memory killer for executed
    processes. Takes an integer between -1000 (to disable OOM killing
    for this process) and 1000 (to make killing of this process under
    memory pressure very likely). See proc.txt for details."

(I won't get into detail here as all the relevant parts can be found under: https://www.kernel.org/doc/Documentation/filesystems/proc.txt)

The `OOMScoreAdjust` score of each process can be seen by doing

    cat /proc/PID/oom_adj
    cat /proc/PID/oom_score
    cat /proc/PID/oom_score_adj

E.g. the values for `dbus-daemon` on an Archlinux host will look like this:

    cat /proc/PID/oom_adj

will be` -15` (It is only there for backwards compatibility with older kernels where the oom adjustement was made there.).

    cat /proc/PID/oom_adj_score

will be `-900` as specified in dbus.service on Archlinux.

Finally,

    cat /proc/PID/oom_score

will be `0`.

Both values, `-15` and `-900` make `dbus` one of the few processes that is killed last when out of memory.

All unprivileged containers I have run so far (`Ubuntu Vivid`, `Debian Jessie`) even though they may have the line `OOMScoreAdjust` in their `dbus.service` (e.g. `Ubuntu Vivid`) file do not adjust this value meaning when they boot they show `0` on all three fields under `/proc`.

When disabling `OOMScoreAdjust` in the Archlinux `dbus.service` file of the unpriv. container the boot will be immediately successful and all three values under proc will show `0` just as for an `Ubuntu Vivid` or `Debian Jessie` unpriv. container. Without the adjustment, Archlinux will hang endlessly. It seems that in this distribution `dbus` failure is taken to be fatal. Fedora on the other hand boots through but complains and `dbus` and some other processes will be missing when `oom` adjust is not commented out.

So it seems that during boot `systemd` in Archlinux and Fedora is trying to adjust the `oom` score under the `/proc` tree for `dbus` but somehow fails.

Is it a distribution-specific problem or should `lxc`/`lxcfs` somehow handle this by providing some options for the fuse filesystem where `/proc` for the unpriv. container is mounted?

**Comment by stgraber** [comment]
I fixed that bug in upstream systemd. That's one of the reasons why the LXC 1.1 announcement specifically mentions "recent" systemd.

**Comment by stgraber** [comment]
Distributions caring about running unprivileged, ought to cherry-pick those recent systemd changes. Having LXC hack around the problem will only cause additional problems on upgrades of those containers (unit being replaced and the option re-enabled causing the problem to re-appear all of a sudden).

**Comment by brauner** [comment]
In case you know, is the patch already included in `systemd 218-1` or later?

**Comment by stgraber** [comment]
I don't believe systemd made any release since this got fixed. So unless your distro chery-picks it, you won't have it.

**Comment by cholin** [comment]
I looked at your [thread](http://lists.freedesktop.org/archives/systemd-devel/2015-January/026858.html) on the systemd mailing list from last year. Is it really fixed upstream? Couldn't find any commit referencing to this issue since then in [systemd/systemd](https://github.com/systemd/systemd).
