### ISSUE TITLE
__sync_wake: 62 sync wake failure : Broken pipe with --share-net option

### ISSUE THREAD

**Issue by ik-nitk** [lxc/lxc#432]
I am trying to start a lxc container deb1 and use --share-net to start another container deb2 to share the network namespace.  But both in fedora and ubunut i and getting error below: 
## issue |

[root@blr-vxr-056 ~]# lxc-start --share-net deb1 -n deb2
lxc-start: cgfs.c: handle_cgroup_settings: 2077 Device or resource busy - failed to set memory.use_hierarchy to 1; continuing
lxc-start: cgfs.c: handle_cgroup_settings: 2077 Device or resource busy - failed to set memory.use_hierarchy to 1; continuing
lxc-start: sync.c: __sync_wake: 62 sync wake failure : Broken pipe
lxc-start: start.c: __lxc_start: 1080 failed to spawn 'deb2'

| Steps to recreate | command |
| --- | --- |
| start a container | lxc-start -n deb1 |
| get pid of init process of that container. | or create link in /var/run/netns/deb1 -> /proc/56298/ns/net |
| start another container | lxc-start --share-net deb1 -n deb2 |

**Comment by newtonkishore** [comment]
I am facing the same issue. Please provide a solution if its a known issue.

LXC Version: 1.0.7
Ubuntu : 14.04   [ 3.13 x86 - Virtual OS ]

root!lxc-info -n share_lxc
Name:           share_lxc
State:          STOPPED

#Sharing the Namespace with another LXC

root!lxc-start --share-net exr -n share_lxc
lxc-start: sync.c: __sync_wake: 62 sync wake failure : Broken pipe
lxc-start: start.c: __lxc_start: 1080 failed to spawn 'share_lxc'

#Sharing the Namespace with a PID [ created using unshare call ]

root!lxc-start -n share_lxc --share-net 2649
lxc-start: sync.c: __sync_wake: 62 sync wake failure : Broken pipe
lxc-start: start.c: __lxc_start: 1080 failed to spawn 'share_lxc'

root!ps -ef | grep /bin/bash
root      2649  2396  0 14:29 pts/1    00:00:00 /bin/bash

**Comment by brauner** [comment]
The namespace sharing logic has been reworked substantially and should work correctly now.
