### ISSUE TITLE
Implement logfile rotate command?

### ISSUE THREAD

**Issue by hallyn** [lxc/lxc#4323]
I'm kind of surprised this hasn't been a problem for anyone else before, which suggests maybe I'm thinking a out it wrongly.  But here goes anyway:

We have some long running containers.  They were started with the equivalent of lxc-start -l trace -o /some/path.  Now, something was misbehaving and spinning on (I think) lxc-ls -f.  So the command monitor code was filling up the logfiles, eventually filling up the disk.

Production shouldn't be using INFO log level, and the abuser probably should be fixed, however it still strikes me that we have no way of rotating the lxc.log.file .

What do people think about introducing a new monitor command, LXC_CMD_ROTATE_LOGFILE ?

**Comment by Blub** [comment]
It definitely makes sense to have the functionality available. I do wonder if a signal might make more sense (easier to use - not that I'm a fan of signals...). Then again, I believe tools such as `logrotate` do tend to allow using arbitrary commands for this, so it probably doesn't matter much as long as there's also a simple enough CLI command available.

**Comment by hallyn** [comment]
A signal does feel natural.  So long as we're not already messing with signals too much there - but the monitor should be in the parent namespace and accepting signals, so that should be fine.

**Comment by hallyn** [comment]
Oh, hm.  Yes, I suppose copy+truncate would work  :).  Let's leave things simpler then.  Thanks.
