### ISSUE TITLE
Error message lacks of trailing newline: Unprivileged users cannot create %s containers.

### ISSUE THREAD

**Issue by cuihaoleo** [lxc/lxc#433]
At `/src/lxc/lxc_create.c:228`
```
	fprintf(stderr, "Unprivileged users cannot create %s containers", my_args.bdevtype);
```

I think there should be a trailing newline :)

**Comment by stgraber** [comment]
Or we should be using the appropriate logging wrapper which does add the newline by default.

**Comment by brauner** [comment]
This is fixed.
