### ISSUE TITLE
lxc5.0.1 library and userland binaries size increased hugely comparing with lxc-3.2.1

### ISSUE THREAD

**Issue by adhicode** [lxc/lxc#4335]
From the initial investigation, here the findings,
1. In comparison with lxc-3.2.1, build system changed to meson build system
2. liblxc is statically getting linked.
Kindly help resolving as we look for tinier version of lxc like lxc-3.2.1 in our embedded system applications urgently as we encountered this sizing impact after porting lxc-5.0.1.
Thanks a lot.

`**CPU: ARMv7l 32-bit**

root@B6:/home/superadmin# lxc-start --version
3.2.1
root@B6:/usr/bin# ls -l *lxc*
-rwxr-xr-x    1 root     root         26472 Jun 14 08:55 lxc-attach
-rwxr-xr-x    1 root     root         22352 Jun 14 08:55 lxc-autostart
-rwxr-xr-x    1 root     root         18256 Jun 14 08:55 lxc-cgroup
-rwxr-xr-x    1 root     root          7873 Jun 14 08:55 lxc-checkconfig
-rwxr-xr-x    1 root     root         17668 Jun 14 08:55 lxc-config
-rwxr-xr-x    1 root     root         18232 Jun 14 08:55 lxc-console
-rwxr-xr-x    1 root     root         39128 Jun 14 08:55 lxc-create
-rwxr-xr-x    1 root     root         22424 Jun 14 08:55 lxc-destroy
-rwxr-xr-x    1 root     root         22344 Jun 14 08:55 lxc-execute
-rwxr-xr-x    1 root     root         18232 Jun 14 08:55 lxc-freeze
-rwxr-xr-x    1 root     root         22272 Jun 14 08:55 lxc-info
-rwxr-xr-x    1 root     root         30580 Jun 14 08:55 lxc-ls
-rwxr-xr-x    1 root     root         26536 Jun 14 08:55 lxc-monitor
-rwxr-xr-x    1 root     root         22400 Jun 14 08:55 lxc-snapshot
-rwxr-xr-x    1 root     root         22464 Jun 14 08:55 lxc-start
-rwxr-xr-x    1 root     root         22392 Jun 14 08:55 lxc-stop
-rwxr-xr-x    1 root     root         18232 Jun 14 08:55 lxc-unfreeze
-rwxr-xr-x    1 root     root         30728 Jun 14 08:55 lxc-unshare
-rwxr-xr-x    1 root     root        174520 Jun 14 08:55 lxc-usernsexec
-rwxr-xr-x    1 root     root         18224 Jun 14 08:55 lxc-wait
root@B6:/usr/bin#
root@B6:/usr/lib# ls -l *lxc*
lrwxrwxrwx    1 root     root            11 Jun 14 08:55 liblxc.so -> liblxc.so.1
lrwxrwxrwx    1 root     root            15 Jun 14 08:55 liblxc.so.1 -> liblxc.so.1.6.0
-rwxr-xr-x    1 root     root        823184 Jun 14 08:55 liblxc.so.1.6.0

**CPU: ARMv8A, 64-bit**

root@B6:/# lxc-start --version
5.0.1
root@B6:/rom# find . -name *lxc* | xargs ls -l 
-rw-r--r--    1 root     root            23 Jan  3 08:24 ./etc/lxc/lxc.conf
-rwxr-xr-x    1 root     root       1158504 Jan  3 08:24 ./usr/bin/lxc-attach
-rwxr-xr-x    1 root     root       1158184 Jan  3 08:24 ./usr/bin/lxc-autostart
-rwxr-xr-x    1 root     root       1154088 Jan  3 08:24 ./usr/bin/lxc-cgroup
-rwxr-xr-x    1 root     root          8678 Jan  3 08:24 ./usr/bin/lxc-checkconfig
-rwxr-xr-x    1 root     root       1145048 Jan  3 08:24 ./usr/bin/lxc-config
-rwxr-xr-x    1 root     root       1154040 Jan  3 08:24 ./usr/bin/lxc-console
-rwxr-xr-x    1 root     root       1158376 Jan  3 08:24 ./usr/bin/lxc-create
-rwxr-xr-x    1 root     root       1154232 Jan  3 08:24 ./usr/bin/lxc-destroy
-rwxr-xr-x    1 root     root       1158352 Jan  3 08:24 ./usr/bin/lxc-execute
-rwxr-xr-x    1 root     root       1154040 Jan  3 08:24 ./usr/bin/lxc-freeze
-rwxr-xr-x    1 root     root       1157992 Jan  3 08:24 ./usr/bin/lxc-info
-rwxr-xr-x    1 root     root       1166304 Jan  3 08:24 ./usr/bin/lxc-ls
-rwxr-xr-x    1 root     root       1158520 Jan  3 08:24 ./usr/bin/lxc-monitor
-rwxr-xr-x    1 root     root       1154184 Jan  3 08:24 ./usr/bin/lxc-snapshot
-rwxr-xr-x    1 root     root       1158592 Jan  3 08:24 ./usr/bin/lxc-start
-rwxr-xr-x    1 root     root       1154160 Jan  3 08:24 ./usr/bin/lxc-stop
-rwxr-xr-x    1 root     root       1154040 Jan  3 08:24 ./usr/bin/lxc-unfreeze
-rwxr-xr-x    1 root     root       1162784 Jan  3 08:24 ./usr/bin/lxc-unshare
-rwxr-xr-x    1 root     root       1153192 Jan  3 08:24 ./usr/bin/lxc-usernsexec
lrwxrwxrwx    1 root     root            11 Jan  3 08:24 ./usr/lib/liblxc.so -> liblxc.so.1
lrwxrwxrwx    1 root     root            15 Jan  3 08:24 ./usr/lib/liblxc.so.1 -> liblxc.so.1.7.0
-rwxr-xr-x    1 root     root       1153024 Jan  3 08:24 ./usr/lib/liblxc.so.1.7.0

`

**Comment by adhicode** [comment]
@mihalicyn @brauner Kindly help as its an urgent requirement.

**Comment by paulocoghi** [comment]
_Disclaimer: I'm not a maintainer, just a regular LXC user giving a friendly advice_

This is an open source project where everyone involved works voluntarily on it, and it isn't kind nor polite to ask for "urgent" fixes.

Leaving that aside, depending on your urgency, you can contact the main company and sponsor of LXC, called [Zabbly](https://zabbly.com/) (check the contact info at the end of the page) and I believe they are available to offer enterprise support and faster fixes.

**Comment by paulocoghi** [comment]
Leaving that aside, if this is really urgent for you or your company, you can immediately contact the main company and sponsor of LXC, called [Zabbly](https://zabbly.com/) (check the contact info at the end of the page). I believe they are available for enterprise support and faster fixes.

**Comment by mihalicyn** [comment]
Looks related to https://github.com/lxc/lxc/issues/4251

**Comment by adhicode** [comment]
> _Disclaimer: I'm not a maintainer, just a regular LXC user giving a friendly advice_
> 
> This is an open source project where everyone involved works voluntarily on it, and it isn't kind nor polite to ask for "urgent" fixes. And trust me, tagging maintainers to try to get their attention is not good etiquette and doesn't help, either.

Thanks, yes it makes sense :) 

> Leaving that aside, if this is really urgent for you or your company, you can immediately contact the main sponsor company of LXC, called [Zabbly](https://zabbly.com/) (check the contact info at the end of the page). I believe they are available for enterprise support and faster fixes.

Thanks for sharing

**Comment by adhicode** [comment]
> Looks related to #4251
Hi @mihalicyn This issue is still open. I tried those changes and it was not helping:( I still see the same sizing.

**Comment by lateautumn233** [comment]
> > _Disclaimer: I'm not a maintainer, just a regular LXC user giving a friendly advice_
> > This is an open source project where everyone involved works voluntarily on it, and it isn't kind nor polite to ask for "urgent" fixes. And trust me, tagging maintainers to try to get their attention is not good etiquette and doesn't help, either.
> 
> Thanks, yes it makes sense :)
> 
> > Leaving that aside, if this is really urgent for you or your company, you can immediately contact the main sponsor company of LXC, called [Zabbly](https://zabbly.com/) (check the contact info at the end of the page). I believe they are available for enterprise support and faster fixes.
> 
> Thanks for sharing

Perhaps you can try compressing binaries?
https://github.com/upx/upx

**Comment by mihalicyn** [comment]
Let's track the status of this in there https://github.com/lxc/lxc/issues/4251

Closing as a duplicate.
