### ISSUE TITLE
lxc-attach gives execute permission on stdio file descriptors

### ISSUE THREAD

**Issue by smoser** [lxc/lxc#4338]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: ubuntu
 * Distribution version: 22.04
 * The output of
   * `lxc-start --version`: 5.0.1
   * `uname -a`: 5.19.0-46-generic

# Issue description
lxc-attach is doing a fchmod and fchown on nits open file descriptors 0, 1, 2 (stdin, stdout, stderr).
fchmod is given 0700 as the mode.
This came from 6aff5157220de749afc559901d990c5088ca8143 which suggests "fix non-root user cannot write /dev/stdout"

I can't think of any reason for execute bit to be set at all.

The behavior is at least surprising and potentially dangerous ; unexpected executable files on the filesystem.

I do not see the problem in unprivileged container, but I'm not sure why.

# Steps to reproduce
1. download [go.sh](https://github.com/lxc/lxc/files/12469014/go.sh.txt)
2. execute go.sh
```
$ sudo ../go.sh
deleting existing bb1
execute: lxc-destroy -nbb1
:: 0
creating bb1
execute: lxc-create -tbusybox -nbb1
:: 0
execute: lxc-start bb1
:: 0
execute: id
uid=0(root) gid=0(root) groups=0(root),130(sbuild)
:: 0
execute: umask
0022
:: 0
execute: rm -f stdin stdout stderr
:: 0
execute: touch stdin stdout stderr
:: 0
execute: ls -l stdin stdout stderr
-rw-r--r-- 1 root root 0 Aug 29 16:42 stderr
-rw-r--r-- 1 root root 0 Aug 29 16:42 stdin
-rw-r--r-- 1 root root 0 Aug 29 16:42 stdout
:: 0
execute: lxc-attach -nbb1 -- /bin/echo hi <stdin >stdout 2>stderr
:: 0
execute: ls -l stdin stdout stderr
-rwx------ 1 root root 0 Aug 29 16:42 stderr
-rwx------ 1 root root 0 Aug 29 16:42 stdin
-rwx------ 1 root root 3 Aug 29 16:42 stdout
:: 0
execute: rm -f stdin stdout stderr
:: 0
execute: touch stdin stdout stderr
:: 0
execute: lxc-attach -nbb1 --uid=1 -- /bin/echo hi <stdin >stdout 2>stderr
:: 0
execute: ls -l stdin stdout stderr
-rwx------ 1 daemon root 0 Aug 29 16:42 stderr
-rwx------ 1 daemon root 0 Aug 29 16:42 stdin
-rwx------ 1 daemon root 3 Aug 29 16:42 stdout
:: 0

```

# Information to attach

**Comment by hallyn** [comment]
> I do not see the problem in unprivileged container, but I'm not sure why.

Maybe you would see the issue in your unprivileged container if you also mapped your own uid into the container?  By default, the container root id (say, 100000) probably doesn't have the perms.

**Comment by smoser** [comment]
@hallyn thanks for the quick fix.

600 is definitely better than it was. it might be better to just make sure that owner has write and leave the other bits unchanged, but that is a bit more entailed.

also surprising at least to me is the chown (see below), but anything else is probably more entailed.

```
execute: touch stdin stdout stderr
:: 0
execute: ls -l stdin stdout stderr
-rw-r--r-- 1 root root 0 Aug 29 16:42 stderr
-rw-r--r-- 1 root root 0 Aug 29 16:42 stdin
-rw-r--r-- 1 root root 0 Aug 29 16:42 stdout
execute: lxc-attach -nbb1 --uid=1 -- /bin/echo hi <stdin >stdout 2>stderr
:: 0
execute: ls -l stdin stdout stderr
-rwx------ 1 daemon root 0 Aug 29 16:42 stderr
-rwx------ 1 daemon root 0 Aug 29 16:42 stdin
-rwx------ 1 daemon root 3 Aug 29 16:42 stdout
:: 0
```

**Comment by hallyn** [comment]
btw, confirmed that if i do not map my own uids, the stdout file doesn't get chmod'd, but if i do map my host uid into the container, then the file gets chmod'd.

Part of me says it wouldn't be all that much extra work to do an access() check before changing the files, but another part of me says there are already enough ways for container startup to fail...
