### ISSUE TITLE
Some default options for systemd-based containers

### ISSUE THREAD

**Issue by brauner** [lxc/lxc#436]
Hello,

I've just finished a long journey on getting systemd-based unprivileged containers to run cleanly. I think there are some default mount options for both privileged and unprivileged that should be enabled for a clean boot without any errors. The Ubuntu config

    /usr/share/lxc/config/ubuntu.common.conf

contains

    lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none bind,optional 0 0
    lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none bind,optional 0 0
    lxc.mount.entry = /sys/kernel/security sys/kernel/security none bind,optional 0 0
    lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none bind,optional 0 0

I think these options could be enabled in all default configs but given `lxcfs` it seems that 

    lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none bind,optional 0 0

at least should.

**Comment by stgraber** [comment]
Hmm, well, not quite.

The fuse one is only relevant if you intend to run a fuse filesystem INSIDE the container. lxcfs is designed to be bind-mountable into sub-containers, therefore not requiring the container be able to mount fuse filesystems.

However, this mount is designed to be safe and could indeed be enabled for all containers without causing harm (can you send a match to move that to common.conf ?).

As for the other ones, they are only mounted to prevent mountall from failing on Ubuntu, none of those should EVER be mounted in a privileged container which doesn't run under an apparmor profile as all of those let you cause serious harm to the host system from within a privileged container.

**Comment by brauner** [comment]
Would you prefer a patch or a signed pull-request?

**Comment by stgraber** [comment]
either way is fine so long as the Signed-off-by line is present somewhere :)

**Comment by stgraber** [comment]
Applied your pull request, closing this.

**Comment by brauner** [comment]
Thank you!

One quick question:

    lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none bind,optional 0 0
    lxc.mount.entry = /sys/kernel/security sys/kernel/security none bind,optional 0 0
    lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none bind,optional 0 0

should be safe for unprivileged.(?)

And

    lxc.mount.entry = /sys/kernel/config sys/kernel/config none bind,optional 0 0

seems also to be wanted by `Ubuntu Vivid` and some other distros otherwise systemd non-fatally-complains about:

    [FAILED] Failed to mount Configuration File System.
    See "systemctl status sys-kernel-config.mount" for details.

during boot. If they are safe for unpriv containers maybe it is worth thinking about adding them to `userns.conf` or maybe have a separate `systemd.userns.conf` file... (Probably `sysvinit` and `systemd` privs and unprivs need to be treated differently anyway.)
