### ISSUE TITLE
Limit on cpus and memory does not work

### ISSUE THREAD

**Issue by WindKnight** [lxc/lxc#438]
I have used 
         lxc-cgroup -n my_container cpuset.cpus 0  
         lxc-cgroup -n my_container  memory.limit_in_bytes  256M  
to set limit to the cpu and memory, but when I write a C program in the container to get memory and cpu info, it doesn't match with the limit I set. Here is my code:
int main(int argc, char **argv) {
  struct sysinfo sys_info;
  sysinfo(&sys_info);
  printf("mem is : %lu num of proc is : %u\n",
    sys_info.totalram,get_nprocs());
  fflush(stdout);
  return 0;
}
Output is : mem is : 2084110336 num of proc is : 2

How can get the actual info of memory and cpu in my program? Are there some APIs I can use?
Looking forward to your reply

**Comment by brauner** [comment]
`sysinfo()` looks at file in `/proc` if you call it inside the container you'd need `lxcfs` running that. LXC is not to blame here. :)
