### ISSUE TITLE
Missing variable specified in lxc.enviromnent makes lxc-* utilities to fail

### ISSUE THREAD

**Issue by amateur80lvl** [lxc/lxc#4385]
Suppose we want to pass some environment variable to the container (let it be `test`) but this variable is not set yet:
```
lxc.environment=XXX
```
Now every lxc command complains:
```
$ lxc-ls -f
Failed to load config for test

$ lxc-info test
Failed to load config for test
```
and so on.

We have to say:
```
$ XXX= lxc-info test
Name:           test
State:          STOPPED
```

Given that shell scripts do not complain when a variable does not exist, they simply return empty string, I think it's reasonable to do the same for container configuration. Unless there's a rationale for current behavior I'm not aware of.

Suggested patch:
```diff
--- a/src/lxc/confile.c
+++ b/src/lxc/confile.c
@@ -1595,12 +1595,12 @@ static int set_config_environment(const char *key, const char *value,
        env_val = strchr(dup, '=');
        if (!env_val) {
                env_val = getenv(dup);
+               if (!env_val)
+                       env_val = "";
        } else {
                *env_val = '\0';
                env_val++;
        }
-       if (!env_val)
-               return ret_errno(ENOENT);
 
        val = strdup(env_val);
        if (!val)
```

Or, even better version where strchr logic is not split by getenv logic:
```diff
--- a/src/lxc/confile.c
+++ b/src/lxc/confile.c
@@ -1593,14 +1593,14 @@ static int set_config_environment(const char *key, const char *value,
                return ret_errno(ENOMEM);
 
        env_val = strchr(dup, '=');
-       if (!env_val) {
-               env_val = getenv(dup);
-       } else {
+       if (env_val) {
                *env_val = '\0';
                env_val++;
+       } else {
+               env_val = getenv(dup);
+               if (!env_val)
+                       env_val = "";
        }
-       if (!env_val)
-               return ret_errno(ENOENT);
 
        val = strdup(env_val);
        if (!val)
```

**Comment by stgraber** [comment]
`lxc.environment=A` isn't valid, all environment variables must have a value. That value can be empty, but it's still a value.

So `lxc.environment=A=` should be allowed (if it isn't already) but other values should be refused.

For your shell equivalent, `XXX env` isn't valid, the terminal interprets `XXX` in this case as being a command, which doesn't exists and therefore fails. `XXX= env` is valid though.

This does line up with our current behavior and in general with how environment variables function on UNIX systems.

**Comment by hallyn** [comment]
@stgraber 'man lxc.container.conf' does explicitly say that

```
              It is possible to inherit host environment variables by setting the name of the variable without a "=" sign. For example:

                            lxc.environment = PATH
```

That was new to me and I don't know how I feel about it (it's kinda cool and kinda asking for trouble), but since it was documented I wasn't going to argue with that.

**Comment by stgraber** [comment]
Oh, that's also new to me, though failing if the variable doesn't exist on the host still seems appropriate.

An env variable set to empty isn't the same as a non-existing env variable.

Probably just needs better logging indeed.

**Comment by amateur80lvl** [comment]
Well, any idea how to inherit nonexistent vars with an empty or some default value? Amended syntax?
Thanks.

**Comment by hallyn** [comment]
Well, if you really do want to do that, you can set it:

```
bash: Y: unbound variable
serge@serge-l-PF3DENS3 ~$ export Y=
serge@serge-l-PF3DENS3 ~$ echo $Y

serge@serge-l-PF3DENS3 ~$ env | grep "^Y="
Y=
```

**Comment by stgraber** [comment]
Yeah, the options I see are:
 - Have whatever script calls `lxc-start` do something along the lines of `export Y=${Y:-}`, so setting the variable to empty if it's not already set.
 - Use the `-s` option of `lxc-start` to pass in just the variables that are actually present in the environment rather than keep a hardcoded list in config.
 - Add a new `lxc.environment.optional` or something config key which would have listed inherited variables not fail when missing. Though I'm not sure how much more work we want to put into that particular feature ;)

**Comment by amateur80lvl** [comment]
Well, I wanted to pass some variables to some containers. Setting system-wide defaults is not a nice idea.

`-s` option looks the best one. Thanks for pointing to it.

**Comment by amateur80lvl** [comment]
Unfortunately, `-s` does not seem to work for `lxc.environment`. If I run
```bash
ASDF=asd lxc-start -n test -s lxc.environment=ASDF=qwe
```
I observe ASDF=asd inside the container.
Double `=` parsing problem? Haven't looked into source code yet.

**Comment by hallyn** [comment]
Oh, actually, I had not noticed that there is more help than I thought if you do -l trace:

```
serge@serge-l-PF3DENS3 ~/src/lxc$ lxc-info -l trace -n bb1
lxc-info: bb1: ../src/lxc/parse.c: lxc_file_for_each_line_mmap: 129 Failed to parse config file "/home/serge/.local/share/lxc/bb1/config" at line "lxc.environment = XXX"
```

I have a patch to add more, but maybe this is sufficient?

**Comment by hallyn** [comment]
@amateur80lvl we are not going to take away 'lxc.environment=XXX' working.

It's just that if you want it to work with an empty XXX, then you have to define it as empty.  So:


```
serge@serge-l-PF3DENS3 ~$ grep XXX .local/share/lxc/bb1/config
lxc.environment = XXX
serge@serge-l-PF3DENS3 ~$ lxc-info -n bb1 -l trace
lxc-info: bb1: ../src/lxc/parse.c: lxc_file_for_each_line_mmap: 129 Failed to parse config file "/home/serge/.local/share/lxc/bb1/config" at line "lxc.environment = XXX"
Failed to load config for bb1
Failure to retrieve information on /home/serge/.local/share/lxc:bb1
serge@serge-l-PF3DENS3 ~$ XXX= lxc-info -n bb1
Name:           bb1
State:          STOPPED
```
