### ISSUE TITLE
lxc-start :  pthread_mutex_unlock ERROR

### ISSUE THREAD

**Issue by tombishop-83** [lxc/lxc#439]
Hi,
i created a new container (Debian - Wheezy - amd64) as root, and when I try to boot it , with lxc-start (still as root) , I get this error returned:

host@host# lxc-start -d -n node1
pthread_mutex_unlock returned:1 Operation not permitted
    Obtained 8 stack frames.
        /usr/local/lib/liblxc.so.1(+0xff95) [0x7f249ad9df95]
        /usr/local/lib/liblxc.so.1(process_unlock+0x3e) [0x7f249add3b9e]
        /lib/x86_64-linux-gnu/libc.so.6(__libc_fork+0x1c6) [0x7f249a2834b6]
        /usr/local/lib/liblxc.so.1(lxc_monitord_spawn+0x2f) [0x7f249adada4f]
        /usr/local/lib/liblxc.so.1(+0x4c2a1) [0x7f249adda2a1]
        lxc-start(main+0x269) [0x401239]
        /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd) [0x7f249a1f5ead]
        lxc-start() [0x401765]

browsing a little bit, I found that the error rises from a erroneous handling of the mutex. Is it a bug ? how to solve it ?

my host machine is a Debian/wheezy/amd64 (same as the created container).

Thanks,regards

**Comment by brauner** [comment]
This should be fixed in master.
