### ISSUE TITLE
lxc-console can not connected to tty

### ISSUE THREAD

**Issue by shaba** [lxc/lxc#4393]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: ALTLinux
 * Distribution version: Sisyphus
 * The output of
   * `lxc-start --version` : 5.0.2
   * `uname -a` : 6.1.73-std-def-alt1 x86_64

# Issue description
```
#lxc-console -n test

Connected to tty 1
Type <Ctrl+a q> to exit the console, <Ctrl+a Ctrl+a> to enter Ctrl+a itself

```
# Steps to reproduce

 1. start container: lxc-start -n test -d
 2. lxc-console -n test

# Information to attach
getty@tty1.service not started in container
```
# systemctl status getty@tty1.service 
 getty@tty1.service - Getty on tty1
     Loaded: loaded (/etc/systemd/system/getty@.service; enabled; vendor preset: enabled)
    Drop-In: /lib/systemd/system/getty@tty1.service.d
             └─noclear.conf
             /run/systemd/system/service.d
             └─zzz-lxc-service.conf
     Active: inactive (dead)
  Condition: start condition failed at Fri 2024-02-02 13:06:23 UTC; 16s ago
             └─ ConditionPathExists=/dev/tty0 was not met
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       Docs: man:agetty(8)
             man:systemd-getty-generator(8)
             http://0pointer.de/blog/projects/serial-console.html

```
because ConditionPathExists=/dev/tty0 in /lib/systemd/system/getty@.service,
but lxc don't make /dev/tty0
```
#LANG=C ls -la /dev/tty*
crw-rw-rw- 1 root root 5, 0 Feb  2 13:25 /dev/tty
lrwxrwxrwx 1 root root    8 Feb  2 13:25 /dev/tty1 -> lxc/tty1
lrwxrwxrwx 1 root root    8 Feb  2 13:25 /dev/tty2 -> lxc/tty2
lrwxrwxrwx 1 root root    8 Feb  2 13:25 /dev/tty3 -> lxc/tty3
lrwxrwxrwx 1 root root    8 Feb  2 13:25 /dev/tty4 -> lxc/tty4
```

If disable ConditionPathExists=/dev/tty0 in unit, then lxc-console run successfully.

**Comment by anooprac** [comment]
Hello, we are UT Austin students working on open-source contributions for a final project in a class. Would it be fine to be assigned this issue? Thank you!

**Comment by DevonSchwartz** [comment]
![Screenshot from 2024-04-30 12-07-09](https://github.com/lxc/lxc/assets/41024725/bf343635-ba7b-4efa-ad61-8980f117b173)
It looks like systemctl works fine for the lxc-console in the 6.0 stable release. Does this mean the issue is resolved.

**Comment by stgraber** [comment]
Yeah, we actually tracked down something similar on the Debian side a few days ago.

Basically, some images do not have getty running on tty1 through tty4, that kinda makes sense as it's a waste of resource.

If you want to attach to /dev/console instead, which does always have a getty running on it, you need to ask `lxc-console` for that through `-t 0`.

**Comment by XLTechie** [comment]
It's only a waste of resources if you don't want to log in on those consoles. If you do, it's a PITA that only /dev/console logins work.

#### Fix, for anyone having this problem in 2025 like I am.

Setting `lxc.tty.max = 4`, for example, should be done first. Setting the number of desired consoles in `/etc/systemd/logind.conf` (or `logind.conf.d/...`) should be done on the container.

At least under Ubuntu and Debian, the systemd script condition is looking for the wrong thing.

In `/usr/lib/systemd/system/getty@.service`, line 32, the condition is checking for `/dev/tty0`. If it doesn't find it, it says there are no ttys in /dev. However, while there is no `tty0` like it wants, there is a `tty`. I have four configured in LXC, and so I have:
```
/dev/tty
/dev/tty1
/dev/tty2
/dev/tty3
/dev/tty4
```

Changing the condition to look for `/dev/tty`, makes it properly "find" the ttys that do exist, and succeed to bring up gettys on the other ttys.
It is a simplistic fix, for an overly simplistic condition, that causes an obscure headache.

**Comment by jm009** [comment]
I wonder what is the "correct" way of fixing this...
The systemd founder and chief engineer @poettering says, it should not be solved by editing getty@.service
See https://github.com/systemd/systemd/issues/41702
I will need some time and help from kind people to understand what is the matter here...

**Comment by jm009** [comment]
I don't know if this is how it is supposed to be "fixed", but here is my way of "fixing" it:

- Copied /lib/systemd/system/getty@.service to lxc-getty@.service
- In lxc-getty\@.service changed
   ConditionPathExists=/dev/tty0
   to
   ConditionPathExists=/dev/tty1
- Created symlinks in
   /etc/systemd/system/getty.target.wants/
   lxc-getty@tty1.service -> /lib/systemd/system/lxc-getty@.service
   lxc-getty@tty2.service -> /lib/systemd/system/lxc-getty@.service
   lxc-getty@tty3.service -> /lib/systemd/system/lxc-getty@.service
   lxc-getty@tty4.service -> /lib/systemd/system/lxc-getty@.service

lxc-getty\@.service is not overwritten by updates, and for me that was the main PITA point.
