### ISSUE TITLE
Destroying container with "-f" option is failing sometimes (zfs)

### ISSUE THREAD

**Issue by redixin** [lxc/lxc#440]
$ lxc-create -s orig cont
    $ lxc-destroy -f -n cont
    cannot destroy 'tank/lxc/cont': dataset is busy.

container is in STOPPED state after this

Probably it is zfs problem, because there is a similar issue with libvirt virsh

**Comment by brauner** [comment]
As this seems to be `ZFS` problem as you mentioned and not `LXC` I'm closing.
