### ISSUE TITLE
6.0.0 - With IPv6 Disabled - Bad file descriptor - Failed to disable IPv6 link-local addresses for veth pair

### ISSUE THREAD

**Issue by ESPNSTI** [lxc/lxc#4429]
Distribution: Arch
LXC 6.0.0

After updating from 5.03 to 6.0, I get this error when trying to start containers:

```
lxc-start xyz 20240407030125.294 ERROR    network - ../src/lxc/network.c:netdev_configure_server_veth:729 - Bad file descriptor - Failed to disable IPv6 link-local addresses for veth pair "veth9qud9k"
lxc-start xyz 20240407030125.325 ERROR    network - ../src/lxc/network.c:lxc_create_network_priv:3463 - Bad file descriptor - Failed to create network device
lxc-start xyz 20240407030125.325 ERROR    start - ../src/lxc/start.c:lxc_spawn:1847 - Failed to create the network
```

[The error is on line 729 of network.c](https://github.com/lxc/lxc/blob/3dee5fb88c6f77496dbcab46f31bcd891c9ee4e0/src/lxc/network.c#L729)

I have ipv6 disabled with the `ipv6.disable=1` kernel parameter.

So my system doesn't have /proc/sys/net/ipv6:
```
ls /proc/sys/net/ipv6
ls: cannot access '/proc/sys/net/ipv6': No such file or directory
```

Looking at line 722, I assume it should skip lines 727-732 if `disable_ipv6_fd < 0 && errno == ENOENT` is true.

**Comment by stgraber** [comment]
@mihalicyn can you send a fix, should be pretty trivial to tolerate the ENOENT.
