### ISSUE TITLE
Feature request: scripting support for lxc-start-ephemeral

### ISSUE THREAD

**Issue by MOZGIII** [lxc/lxc#443]
When I use `lxc-start-ephemeral -d -n $NAME` I get pretty verbose, "humanized" output:

```
vagrant@vagrant:~$ sudo lxc-start-ephemeral -o guestvm -d
The ephemeral container is now started.

You can enter it from the command line with: lxc-console -n guestvm-fsjs1wti
The following IP addresses have be found in the container:
 - 10.0.3.19
```

It would be neat if there was an option to make the output more scripting-friendly, i.e. like this:

```
vagrant@vagrant:~$ sudo lxc-start-ephemeral -o guestvm -d -H
guestvm-fsjs1wti
10.0.3.19
```

So, for the output to be first the name of the container, and then the IPs, each one on it's own line (or newline separated if you will).

Relevant source: https://github.com/lxc/lxc/blob/master/src/lxc/lxc-start-ephemeral.in

**Comment by MOZGIII** [comment]
I'd implement it myself, but the contribution rules seem too complicated (unfamiliar to me).

**Comment by brauner** [comment]
`lxc-start-ephemeral` has been replaced by `lxc-copy`.

**Comment by MOZGIII** [comment]
Well, I don't need it anymore anyway.
