### ISSUE TITLE
Question - naming scheme from tags changed

### ISSUE THREAD

**Issue by ich777** [lxc/lxc#4430]
Hi,
this is not an issue, this is more a question.

Did the name from the tags change by accident or was that something intentional:
![grafik](https://github.com/lxc/lxc/assets/28066518/d7686de0-8e0a-4342-a46f-202393efbc1a)

Cheers,
Christoph

**Comment by stgraber** [comment]
It's intentional, we've started using semver patterns with Incus a few months ago and have now switched to it for all our projects starting with 6.0.

**Comment by ich777** [comment]
@stgraber thanks for the quick response and of course all you do here and the continuous work on LXC!
Awesome piece of software! :)
