### ISSUE TITLE
lxc image import --verbose should make progress messages like lxc import --verbose does

### ISSUE THREAD

**Issue by jidanni** [lxc/lxc#4447]
I notice for the same 3GB tarball,
`lxc import --verbose`
makes great progress messages. Alas
`lxc image import --verbose`
does not make progress messages. Causing the user to
think it got stuck.
`$ lxc-start --version
5.0.3`

By the way,
```
$ lxc image import 3GBfile --alias new-pen --verbose
Error: Image with same fingerprint already exists
```
takes many minutes to come up with that answer.
Perhaps it could check earlier.
OK, maybe it needs to make a total byte count or something.

**Comment by stgraber** [comment]
Wrong project, you're talking about LXD :)
