### ISSUE TITLE
lxc-create -t /path/to/template throws incorrect errors on script failure and fails to handle local pathing.

### ISSUE THREAD

**Issue by Sleaker** [lxc/lxc#445]
I think this may be a result of change to fix the -h option but I can no longer use lxc-create -n -t to generate a container.

Kernel: Ubuntu 14.04 - 3.13.0-45-generic #74-Ubuntu SMP i686
lxc: 1.1.0-0ubuntu1~ubuntu14.0.4.1~ppa1

lxc-create -n test -t /tmp/lxc-isi-trusty

Result:

lxc_container: lxccontainer.c: create_run_template: 1088 No such file or directory - failed to execute template /tmp/lxc-isi-trusty
lxc_container: lxccontainer.c: create_run_template: 1093 container creation template for test failed
lxc_container: lxc_create.c: main: 274 Error creating container test

/tmp/lxc-isi-trusty is permission rwxr-xr-x for root/root and lxc is being run as root so it should not have any problems reading the file.

This also happens if I try moving the template into /usr/share/lxc/templates, but I can still create ubuntu containers normally using lxc-create -t ubuntu

Update: Also from an analytical point of view the way the template check happens seems very wrong. Shouldn't the code first check the t* to see if it's an actual template, if not, assume local file and try to read in the file on the path as is?  Currently lxc templating can't handle files in the current directory using either filename or ./filename because '/' will not be the first character. 

So More or less, please fix up the file handling for the -t option.

Update2: Tried to downgrade to 1.07 from the trusty-updates archive and having similar issues with lxc not being able to run now.  Not sure what happened here or how to start debugging.

@stgraber

**Comment by Sleaker** [comment]
Figured out the issue was the file had line endings converted to DOS. Converting them back to unix fixed this.
Better errors should be forthcoming instead of making it seem like the script file doesn't exist.  Also, file pathing still needs a second pass as it doesn't handle local pathing at all

**Comment by stgraber** [comment]
The error we return is the one coming from the kernel on exec, so there's nothing we can do to improve that since we're not the ones parsing the script.

**Comment by Sleaker** [comment]
@stgraber - bummer on that front!  can the pathing be made better so we can pass in local paths ex: ./some-template

Thanks for the response!

**Comment by stgraber** [comment]
The execvp error actually makes sense if you know what execvp does :)

The kernel parses the header of your file in an attempt to find what it's supposed to execute to run that file. So you got the No such file or directory error because the path on that first line didn't match an existing executable file.

**Comment by Sleaker** [comment]
Ah, that makes more sense now, since it's trying to exec #!/bin/bash\r 
fun fun.

**Comment by Sleaker** [comment]
Closing as issue was with script, not lxc.  Perhaps a future enhancement could be done to enable better error handling/file checking for custom templates? - Thanks

**Comment by J-kumari** [comment]
Hi,
I have just started to learn lxc. I am also getting the same error (i.e lxc-create: lxccontainer.c: create_run_template:1292 No such file or directory - failed to execute template /us/share/lxc/templates/). Help me to solve this error.
