### ISSUE TITLE
Resource management for whole lxc and per container.

### ISSUE THREAD

**Issue by tomaszdrozdz** [lxc/lxc#4451]
Hello and greetings to all :)  

1)
I know I can configure per container resource usage, for example:  
```
#/etc/lxc/default.conf:
# for legacy cgroups
lxc.cgroup.cpu.cfs_quota_us =  25000 
lxc.cgroup.cpu.cfs_period_us
# for unified cgroups
lxc.cgroup2.cpu.max = 25
```
but:  
- i need to know if my system use cgroup v1 or cgroup v2  
- and need to know specific cgroup settings
both of which are doable but i think it could be done more user friendly.

LXC conf could use settings names convention as [https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html](https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html)
and deal with cgroup v1 and v2 on behalf, so for example:
```
#/etc/lxc/default.conf:
lxc.container.CPUQuota=25
```
would suffice.

2)
It would be also really nice to have similar possibility to control resource usage for lxc as a whole (not per single container, but for all containers) for example:
```
#/etc/lxc/lxc.conf:
lxc.CPUQuota=25
```
so all containers together could not exceed 25% of cpu.

Please comment on this.

**Comment by stgraber** [comment]
We're not interested in applying this level of abstraction in something as low level as LXC.

If you want this kind of abstraction, that's something we provide through Incus.

**Comment by tomaszdrozdz** [comment]
Thank you for reply :)

**Comment by stgraber** [comment]
np!

It's certainly always a bit of a balancing act trying to figure out how far to go with things like that. LXC is very simple, basically just a C library with some tools using that library. It (on-purpose) doesn't have a system-wide view of things or even any kind of coordination between the various containers its running, that's left for more complex managers like Incus which can then provide a more user friendly experience.
