### ISSUE TITLE
`lxc file push` ~5gb errors with 413 Request Entity Too Large (VM)

### ISSUE THREAD

**Issue by JSmith-Aura** [lxc/lxc#4477]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution:  Mac
 * The output of
   * `lxc-start --version`: 6.1

# Issue description

When pushing a large local file to a VM using `lxc file push` an error is returned.

```
lxc file push ./thing.tar.gz instance-name/opt/
Error: Failed to fetch https://example.com:443/1.0/instances/for-kapil/files?path=%2Fopt%2Fthing.tar.gz&project=vms: 413 Request Entity Too Large
```

# Steps to reproduce

 1. Generate large file (I created a 5.8gb tar.gz)
 2. Push to your vm
 3. Profit

**Comment by stgraber** [comment]
You're referring to LXD here, not LXC.
