### ISSUE TITLE
lxc-start mounts sysfs on the *host* read-only

### ISSUE THREAD

**Issue by cburroughs** [lxc/lxc#450]
This obviously breaks anything that needs to write to sys, such as a config managment system to setup lxc.

Off of a fresh reboot
```
lxc.mount.auto = proc:mixed sys:ro
# cat /proc/mounts | grep sysfs
sysfs /sys sysfs rw,relatime 0 0
# lxc-start --version
1.0.7
# lxc-start -d -n sys-test
# cat /proc/mounts | grep sysfs
sysfs /sys sysfs ro,relatime 0 0
```

**Comment by lyind** [comment]
Same issue here with LXC 1.0.6 on Debian Jessie. Solving it by re-mounting manually after launching the container:

`$ mount /sys -o remount,rw`

**Comment by brauner** [comment]
You should be able to set `sys:rw` in `lxc.mount.auto`.

**Comment by lyind** [comment]
@brauner I do not want the container to be able to write to my host's sysfs. The issue is that THE HOST'S sysfs mount is turned read-only on container start, which should never happen.

**Comment by brauner** [comment]
@lyind, can please specify the kernel version you're using?

**Comment by brauner** [comment]
Also, please append any logs for the container you have. If you can reproduce the issue please specify `-l DEBUG -o container_name.log` for the `LXC` commands you use and append them here.

**Comment by lyind** [comment]
The kernel is a vanilla kernel, lxc.network.type is set to "none" so the container can use the hosts interface w/o bridging or routing.

`uname -a`
`Linux node0 4.7.4zlinux-svr #3 SMP PREEMPT Fri Sep 16 10:06:04 UTC 2016 x86_64 GNU/Linux`

`lxc-start --name=c1 -l DEBUG -o c1.log`
[c1.log.txt](https://github.com/lxc/lxc/files/479901/c1.log.txt)

`mount`
**`sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)`**
(Note that sysfs on the HOST is mounted readonly now.)

**Comment by brauner** [comment]
This is related to your kernel version and how automatic mounts (including `sys`) are handled in `LXC < 1.0.8`. So you need to update to at least `LXC 1.0.8` to prevent this from happening. Maybe you can get hold of a PPA or backport.
