### ISSUE TITLE
incus Web UI not open

### ISSUE THREAD

**Issue by TorbenMartin** [lxc/lxc#4501]
Hello.

Want to explore Incus instead LXD because my favourite Developer plays here now i guess :D 

LXD -> Ubuntu 24.04 VM

Inside Ubuntu VM:

> apt-get install lxc incus-tools qemu-system incus
> 
> groupadd incus-admin
> adduser ubuntu incus-admin
> 
> incus admin init
>
>incus config set core.https_address :8443
> 
> incus config show

restart
```

root@intimate-midge:/home/ubuntu# incus config show
config:
  cluster.https_address: 192.168.0.45:8443
  core.https_address: :8443
root@intimate-midge:/home/ubuntu# 
```

> https://192.168.0.45:8443/

```
...
-- | --
type | "sync"
status | "Success"
status_code | 200
operation | ""
error_code | 0
error | ""
metadata |  
0 | "/1.0"
...
```

![Bildschirmfoto zu 2024-12-16 16-28-27](https://github.com/user-attachments/assets/9572868b-b430-45f1-b8dd-f5e1a7982307)

**Comment by stgraber** [comment]
Ubuntu doesn't ship a packaged version of the Incus UI.

Easiest way to get it would be to use the packages from https://github.com/zabbly/incus which do have an `incus-ui-canonical` package that will provide that UI for you.
