### ISSUE TITLE
[bug] create storage pool with btrfs selected -> error

### ISSUE THREAD

**Issue by TorbenMartin** [lxc/lxc#4504]
hello.

just run for tests:

LXD -> ubuntu 24.04 VM -> incus

```
root@above-whippet:~# incus --version
6.0.2
```

When i want to create a Storage Pool by Web UI and let BTRFS selected it shows me an Error related to ZFS.
![Bildschirmfoto zu 2024-12-16 20-24-15](https://github.com/user-attachments/assets/696ff0f6-94f6-435f-86a9-33055c5bb0c4)

i can choose another., than back to BTRFS and it works.

**Comment by stgraber** [comment]
Can you file this here instead: https://github.com/zabbly/incus-ui-canonical/issues
We can't transfer issues cross-organization as would be needed here.
