### ISSUE TITLE
lxc-start should intelligently handle mem vs memsw limits

### ISSUE THREAD

**Issue by hallyn** [lxc/lxc#453]
If a lxc.cgroup.memory.memsw.limit_in_bytes is placed before a lxc.cgroup.memory.limit_in_bytes line, then the container may fail to start because you may not make the memsw limit lower than the limit_in_bytes.

Lxc should order these when applying them.  Note this should be done for both cgfs.c and cgmanager.c  Therefore a common helper which gives a temporary re-ordered list would probably be best.

**Comment by dikei** [comment]
Hi, I can do this. But where should I put the helper function in ?

**Comment by hallyn** [comment]
Sorry, conf.c which you used is a fine place to put the helper.

Note the other way to have done it would be to insert entries in the right order at src/lxc/confile.c:config_cgroup.  But your way has its advantages, let's stick with that.
