### ISSUE TITLE
Pentoo & Sabayon LXC templates

### ISSUE THREAD

**Issue by necrose99** [lxc/lxc#454]
the pentoo container type is proving to be rather thorn full atm do to the limits of skill
namely find string match string feed string to eleclect profile & set that profile for x86/amd64 reg  or hardened. 
however one needs the Gentoo template the ability to name it as a pentoo-arch 
then set the symlinks Preferably binary as one needs a tester pentoo in lxc for building against one can
a: arch$ (reg) or + hardened.

https://github.com/necrose99/lxc/commit/4eec25a5e81b70fd336c70f745cbe907e1a11480

as for sabayon 
this one is albeit easier to make an LXC templates for, 
x86-(ouch) official support has been axed so one will need to manually build everything (hence why an LXC container and a CI server service/s handy. https://github.com/Spike-Pentesting/App-witchcraft

***\* AMD-64 container type should be more simple to build.. 
add layman to gentoo containers name it to sabayon AMD-64... 
"make and bake"  equo entropy matter , equo rescue spmsync to sync Packamanger systems
equo up & equo u to upgrade the system to very bleeding edge Gentoo compatible box. 

any-case feel free to fork the template/s my HDD crashed so I in the next few days should have an alpha template for sabayon-x64.lxc

**Comment by brauner** [comment]
We have a Sabayon template for quite a while now. So closing this.
