### ISSUE TITLE
download template - small bugfix centos unprivileged containers

### ISSUE THREAD

**Issue by itoffshore** [lxc/lxc#455]
For `lxc-console` to work on centos guests inside **unprivileged containers** the following is needed in the download template:

``` bash
    # prevent mingetty from calling vhangup(2) since it fails with userns
    if [ -f $container_rootfs/etc/init/tty.conf ]; then
         sed -i 's|mingetty|mingetty --nohangup|' $container_rootfs/etc/init/tty.conf
    fi
```

(from the Oracle template lines 378-81 https://github.com/lxc/lxc/blob/master/templates/lxc-oracle.in)

**Comment by stgraber** [comment]
Can you submit a pull request or a path for this issue?

**Comment by itoffshore** [comment]
https://github.com/lxc/lxc/pull/456

**Comment by evgeni** [comment]
#456 is merged, @stgraber can you close please? :)
