### ISSUE TITLE
lxc-attach error

### ISSUE THREAD

**Issue by ruffianhy** [lxc/lxc#458]
my os is： redhat7
i started the container with "lxc-start -n mylxc".
and i used the command "lxc-attach -n mylxc echo hello" in the vm, it worked.
but when i tended to use same command through xshell or SecureCRT , it failed:
lxc_container: attach.c: lxc_attach_run_command: 1094 No such file or directory - failed to exec 'echo'

**Comment by stgraber** [comment]
That's probably because your PATH is different. As it's inherited by the container on lxc-attach, your command must be inside that PATH. That or use the whole path to the command inside the container.

**Comment by ruffianhy** [comment]
thanks for your help , it works.
