### ISSUE TITLE
lxc-destroy needs an option to destory child datasets 

### ISSUE THREAD

**Issue by cburroughs** [lxc/lxc#462]
I want to keep n hourly/daily snapshots of each lxc container for all of the obvous reasons snapshots are handy things to have (for example, to make incremental backups).  However, this means that a vanilla `lxc-destory` will fail due to the existance of child datasets.

I'm not sure what the neutral zfs/btrfs/lvm/etc name for the flag for be.  ZFS would call it a recursive destory.

```
# lxc-destroy --version
1.0.7
# lxc-destroy -n zb1
cannot destroy 'tank/lxc/zb1': filesystem has children
use '-r' to destroy the following datasets:
tank/lxc/zb1@zfs-auto-snap_hourly-2015-03-09-1709
lxc_container: lxccontainer.c: lxcapi_destroy: 2073 Error destroying rootfs for zb1
Destroying zb1 failed
```

**Comment by schammy** [comment]
Yeah, lxc-destroy needs to support recursively destroying zfs child datasets

In my opinion this should be the default (why would you *not* want to delete child data sets of a container you're about to destroy?) - but at the very least, allow an extra flag to be passed to lxc-destroy to tell zfs destroy to do its recursively. And if it's not passed, then issue a message about why it failed and what flag to pass to fix it.

**Comment by brauner** [comment]
`lxc-destroy` does allow for recursive destroy via `-s` now.
