### ISSUE TITLE
SIG_DFL signal handlers not working in container's init process

### ISSUE THREAD

**Issue by dmaluka** [lxc/lxc#470]
When a signal handler in container's init process is set to the default value SIG_DFL, the init process does not respond to the signal as it should according to 'man 7 signal', i.e. does not terminate and does not dump core.

When an explicit signal handler function is set instead of SIG_DFL, the signal is handled correctly.

This issue is observed with all the standard signals, except SIGKILL, SIGSTOP and SIGCONT which are working as expected.

The issue is observed only with the container's init process. Its descendant processes handle signals properly.

For example, take this simple program:

```
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <signal.h>

void sighandler(int sig)
{
    printf("===== signal %d =====\n", sig);
    exit(0);
}

int main(int argc, char *argv[])
{
    int sig = SIGTERM;
    if (argc > 1)
        sig = atoi(argv[1]);
    printf("===== default handler =====\n");
    signal(sig, SIG_DFL);
    sleep(10);
    printf("===== our handler =====\n");
    signal(sig, sighandler);
    while (1) sleep(1);
    return 0;
}
```

If we run it in lxc container (e.g. "lxc-start -n test /bin/test 15"), sending the corresponding signal to it (e.g. "kill -TERM $pid") does not terminate the process if we do it during first 10 seconds, but successfully terminates if we do it after 10 seconds elapsed.

Similar behavior is observed if we try to shutdown the container via lxc-stop instead of simply killing the process.

**Comment by brauner** [comment]
How the container's init responds to signals is not really up to LXC but what signal handlers the program has setup. For a full init system for example  `man 2 signal` states:

> The  only  signals  that can be sent to process ID 1, the init process, are
       those for which init has explicitly installed  signal  handlers.   This  is
       done to assure the system is not brought down accidentally.

**Comment by bronger** [comment]
It is `man 2 kill`, actually.  But thank you for this comment, it answered my related question.

**Comment by Blub** [comment]
Also `man 7 pid_namespaces` which I'd interpret so that this should only happen from inside the container's PID namespace, iow. when sending to pid 1. If you do it from the host it should respond like a regular process.
