### ISSUE TITLE
failed to detect blockdev type

### ISSUE THREAD

**Issue by huegelc** [lxc/lxc#471]
Hi,

using 
Package: lxc
Status: install ok installed
Priority: optional
Section: admin
Installed-Size: 750
Maintainer: Ubuntu Developers ubuntu-devel-discuss@lists.ubuntu.com
Architecture: amd64
Version: 1.0.7-0ubuntu0.1

when I want to clone a container I get following error:

```
`lxc_container: bdev.c: bdev_copy: 3028 failed to detect blockdev type for /var/lib/lxc/test/rootfs
lxc_container: lxccontainer.c: copy_storage: 2489 Error copying storage
clone failed
```

**Comment by brauner** [comment]
This is no sufficient information to go on and the issue is quite old. Sorry, that we dropped the ball on this one. If you can still reproduce and are interested, please open a new issue and provide the information we request in our issue template.
