### ISSUE TITLE
Supporting more than 2 layers with AUFS

### ISSUE THREAD

**Issue by sigmonsays** [lxc/lxc#473]
Trying to use a container with an AUFS rootfs with 3 layers.

```
lxc.rootfs = aufs:/opt/lxc/ubuntu12/rootfs:/opt/lxc/devtools/rootfs:/opt/lxc/build-20048/delta
```

The container starts just fine and all 3 layers are presented. However during shutdown I see this

```
# lxc-destroy -P /opt/cask -n build-20048
lxc-destroy: utils.c: lxc_rmdir_onedev: 167 lxc_rmdir_onedev: failed to stat /opt/lxc/devtools/rootfs:/opt/lxc/build-20048/delta
lxc-destroy: lxccontainer.c: container_destroy: 2053 Error destroying rootfs for build-20048
Destroying build-20048 failed
```

and the container is not properly cleaned up after when destroy is called.

I'm having a hard time determining if this is working as designed or not since I do not see anything about 3 or more layers in the documentation.  Is this more than 2 layers supposed to be supported?

Using lxc daily ppa with the following packages

```
ii  liblxc1                           1.1.0+master~20150224-0137-0ubuntu1~precise         Linux Containers userspace tools (library)
ii  lxc                               1.1.0+master~20150224-0137-0ubuntu1~precise         Linux Containers userspace tools
```

**Comment by brauner** [comment]
The aufs driver is considered deprecated and will soon be removed completely.
