### ISSUE TITLE
lxc-create -B lvm errors

### ISSUE THREAD

**Issue by ruffianhy** [lxc/lxc#483]
os:redhat7
lxc version: lxc-1.1.1
lxc os:centos
i try to create a lxc on lvm ,but i get erros:
File descriptor 3 (/usr/local/var/lib/lxc/lxc_lvm/partial) leaked on lvcreate invocation. Parent PID 35401: lxc-create
  Volume group "lxc" not found
lxc_container: bdev.c: lvm_create: 1145 Error creating new lvm blockdev /dev/lxc/lxc_lvm size 1073741824 bytes
lxc_container: lxccontainer.c: do_bdev_create: 832 Failed to create backing store type lvm
lxc_container: lxccontainer.c: lxcapi_create: 1314 Error creating backing store type lvm for lxc_lvm
lxc_container: lxc_create.c: main: 274 Error creating container lxc_lvm

do i need to create a vg by myself

**Comment by tenforward** [comment]
You need to create VG yourself. The default name of VG is "lxc". 
You can specify VG name using `lxc.bdev.lvm.vg`. (See lxc.system.conf(5))

**Comment by ruffianhy** [comment]
lxc-start 1428013869.627 ERROR lxc_conf - conf.c:lxc_mount_auto_mounts:808 - Permission denied - error mounting /usr/local/lib/lxc/rootfs/proc/sys/net on /usr/local/lib/lxc/rootfs/proc/net flags 4096
lxc-start 1428013869.627 ERROR lxc_conf - conf.c:lxc_setup:3811 - failed to setup the automatic mounts for 'mylxc'
lxc-start 1428013869.627 ERROR lxc_start - start.c:do_start:699 - failed to setup the container
lxc-start 1428013869.627 ERROR lxc_sync - sync.c:__sync_wait:51 - invalid sequence number 1. expected 2
lxc-start 1428013869.627 WARN lxc_conf - conf.c:lxc_delete_network:2968 - failed to remove interface '(null)'
lxc-start 1428013869.627 ERROR lxc_start - start.c:__lxc_start:1157 - failed to spawn 'mylxc'

lxc-start 1428013874.634 ERROR lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
lxc-start 1428013874.634 ERROR lxc_start_ui - lxc_start.c:main:346 - To get more details, run the container in foreground mode.
lxc-start 1428013874.634 ERROR lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.

**Comment by ruffianhy** [comment]
after i created “lxc” VG，i found errors above

**Comment by dmitrygribenchuk** [comment]
Hi everyone! I'm start to use LXC version 1.1.5 on Debian Jessie.
  Sometimes when I create a container I recieve an error:

  lxc-create -n test -t vps --bdev=lvm --lvname=test --vgname=vg
  --fstype=xfs --fssize=8G -- --release=jessie --clean

  File descriptor 3 (/var/lib/lxc/test/partial) leaked on lvcreate invocation. Parent PID 1089: lxc-create
    Logical volume "test" created
  lxc-create: bdev/lxclvm.c: lvm_create: 411 Error creating filesystem type xfs on /dev/vg/test
  lxc-create: lxccontainer.c: do_bdev_create: 1035 Failed to create backing store type lvm
  lxc-create: lxccontainer.c: do_lxcapi_create: 1511 Error creating backing store type lvm for test
  lxc-create: tools/lxc_create.c: main: 318 Error creating container test

  Recently I'm upgrade LXC to 2.0.4, but the error remains.

**Comment by brauner** [comment]
Are `xfsprogs` installed? If not, please do so and try again.

**Comment by dmitrygribenchuk** [comment]
Yes, xfsproxs v. 3.2.1

**Comment by brauner** [comment]
Closing because we're tracking this now in https://github.com/lxc/lxc/issues/1188.
