### ISSUE TITLE
Prefix option to configure not honoured completely

### ISSUE THREAD

**Issue by eriknstr** [lxc/lxc#485]
Hi,

I attempted to install lxc with a different prefix. The path was created and some files copied to the prefix path but later, the prefix is disregarded so the install fails.

This is using the master branch HEAD at the time of writing this, which is commit b2937903a0fd1840de572ff6ee9b6777e372cc3a.

I'm running Lubuntu 14.04.2 on an ARMv7 single board computer.

`$ uname -a`

```
Linux odroid 3.10.72 #1 SMP PREEMPT Wed Apr 1 21:33:21 BRT 2015 armv7l armv7l armv7l GNU/Linux
```

`$ lsb_release -a`

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:    14.04
Codename:   trusty
```

`$ git describe`

```
lxc-1.1.0-44-gb293790
```

`$ ./autogen.sh 2>&1 | tee /tmp/lxc-autogen.log`

```
[...]
```

`$ ./configure --prefix=/home/odroid/opt/github.com/lxc/lxc 2>&1 | tee /tmp/lxc-configure.log`

```
[...]
```

`$ make install 2>&1 | tee /tmp/lxc-make-install.log`

```
[...]
 /bin/mkdir -p '/home/odroid/opt/github.com/lxc/lxc/libexec/lxc'
[...]
/usr/bin/install -c -m 644 lxc.service lxc-net.service /lib/systemd/system/
/usr/bin/install: cannot create regular file ‘/lib/systemd/system/lxc.service’: Permission denied
/usr/bin/install: cannot create regular file ‘/lib/systemd/system/lxc-net.service’: Permission denied
make[5]: *** [install-systemd] Error 1
make[5]: Leaving directory `/home/odroid/src/github.com/lxc/lxc/config/init/systemd'
make[4]: *** [install-am] Error 2
make[4]: Leaving directory `/home/odroid/src/github.com/lxc/lxc/config/init/systemd'
make[3]: *** [install] Error 2
make[3]: Leaving directory `/home/odroid/src/github.com/lxc/lxc/config/init/systemd'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/home/odroid/src/github.com/lxc/lxc/config/init'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/odroid/src/github.com/lxc/lxc/config'
make: *** [install-recursive] Error 1
```

Full logs:
- https://gist.github.com/erikano/8722d674497854fe5631/raw/18181d317f92f29842fde51b3dcd194a18976a30/lxc-autogen.log
- https://gist.github.com/erikano/8722d674497854fe5631/raw/377f30c6cdc1bb4325df0a8596b722aefe62d28f/lxc-configure.log
- https://gist.github.com/erikano/8722d674497854fe5631/raw/8eeeac4717ae5229f940a74cd14f27f7f2cd90f2/lxc-make-install.log

**Comment by erikano** [comment]
In my particular case, I actually only needed the binaries so with `make install-exec`, I got what I needed.

**Comment by brauner** [comment]
This should be fixed in master since I've compiled with a custom prefix a couple of times.
