### ISSUE TITLE
Documentation of Jenkins Build job used to create rootfs.tar.xz and meta.tar.xz

### ISSUE THREAD

**Issue by benbooth493** [lxc/lxc#490]
Please could you provide documentation on how you create rootfs.tar.xz and meta.tar.xz for use with lxc-download script.

Thanks,

Ben Booth

**Comment by stgraber** [comment]
They are built using build-image from the github.com/lxc/lxc-ci branch.

**Comment by benbooth493** [comment]
Thanks for this, although I can't see how meta.tar.xz is generated.

**Comment by stgraber** [comment]
lxc_ci.generate_image_metadata(args.template, args.arch, config,
                                   args.target)

**Comment by benbooth493** [comment]
The build_image script requires an argument for a repo. What repo would this be? Also, could you provide a little detail on how the Jenkins job is configured.

Regards

**Comment by stgraber** [comment]
It's the git URL to the repository containing the templates.

All that Jenkins does for every template is:
     sudo bin/build-image git://github.com/lxc/lxc master HEAD ${dist} ${release} ${arch} ${variant} target/

And you then get the new image in target/
