### ISSUE TITLE
lxc-stop -r different from lxc-stop and lxc-start

### ISSUE THREAD

**Issue by gnyman** [lxc/lxc#492]
Not sure if this is intended behaviour or not, doing a 

```
lxc-stop -r 
```

does not apply lxc.mount.auto (might be others, have not tested). To apply it one has to do a lxc-stop/start. At least for me this was unexpected behaviour and took some time to figure out.

I'm on lxc 1.1.2 (from the ubuntu-lxc ppa) running on ubuntu 14.04.2

To reproduce, create a ubuntu-cloud instance on ubuntu 14.04.2.

Start it and attach to it and try to write to /proc/sys, for example.

```
root@ubuntu-test:/# echo "33554432" > /proc/sys/kernel/shmmax 
bash: /proc/sys/kernel/shmmax: Read-only file system
```

Change the config to contain
    lxc.mount.auto = proc:rw

Do lxc-stop -r, then attach and try writing again, same error.

Do lxc-stop and then lxc-start, then attach and try the same thing. Works.

**Comment by brauner** [comment]
Yes, this behavior is expected as `LXC` doesn't really stop the container it reboots it so the initial container setup is not redone.
