### ISSUE TITLE
bridging fails silently for interfaces with dash in the name

### ISSUE THREAD

**Issue by zabbal** [lxc/lxc#495]
Create interface on your host:
sudo brctl addbr my-bridge
sudo ip link set my-bridge up
Everything good, no errors.

Create 2 containers with either veth or macvlan in bridge mode which uses newly created interface via
lxc.network.link = my-bridge

Result - they are unable to ping each other.
Now replace my-bridge with mybridge and everything start to work.

This is beyond horrible - it should either work or there should be HUGE error message all over the place with complains about interface name which breaks lxc networking altogether.

**Comment by brauner** [comment]
This should be fixed in master if not please re-open.
