### ISSUE TITLE
add simple static route support

### ISSUE THREAD

**Issue by zabbal** [lxc/lxc#496]
In addition to existing lxc.network.ipv4 and lxc.network.ipv4.gateway would be great to be able to specify static routes inside the container config:
lxc.network.ipv4.route = 192.168.1.4/10.2.3.9
which would add inside the container:
ip route add 192.168.1.4 via 10.2.3.9

Instead of / we could use word via or whatever syntax is more convenient to parse.

**Comment by blakedotfr** [comment]
Yes, it would be great if the value of this AVP could just be passed to the "ip route" command.

For IPv6 too :-)

Thanks very much.

**Comment by frankreppin** [comment]
+1
and yes - this would be awesome...

**Comment by stgraber** [comment]
you do realize that most Linux distributions will flush any route that's present at container boot time right?

**Comment by frankreppin** [comment]
Shouldn't it then flush 'away' the default gw as well - set via 'lxc.network.ipv4.gateway'?
[that's why I too think that it may be possible]

**Comment by stgraber** [comment]
Yeah, it would. If your distro doesn't flush a pre-configured IP or default gateway, then this feature would work.

**Comment by ar45** [comment]
Which distros do flush away `lxc.network.ipv4.gateway`?

**Comment by stgraber** [comment]
ifupdown on Debian/Ubuntu used to either flush the routing table at boot or just completely fail when then attempting to add routing entries which are already present (causing boot to hang).

**Comment by ar45** [comment]
I wonder. I am using that with debian jessie host and jessie containers and it works for me well. Is there any specific setup that is causing it?

**Comment by stgraber** [comment]
Could be that ifupdown isn't flushing routes anymore (pretty sure NetworkManager still does), so the only problem you'd run into is if you had a conflicting route being applied with ifupdown.

**Comment by brauner** [comment]
That's not a feature we're likely to introduce for the aforementioned reasons by @stgraber.

**Comment by fyl2xp1** [comment]
Assuming this will not get implemented: what's the recommended way to add static routes to interfaces that are otherwise completely declared in the container's config?
I'm either used to configure them entirely within the container or externally. I haven't found mixed examples so far (Debian in my case).

**Comment by apardyl** [comment]
@fyl2xp1 currently I'm doing it like this:
```
# setup static routing
lxc.hook.mount = /etc/lxc/setup_routing.sh
```
where `/etc/lxc/setup_routing.sh` is:
```
ip ro add 10.30.0.0/16 via 10.20.0.1
ip ro add 10.10.0.0/16 via 10.20.0.1
```
It's a bit hacky, but it works.

**Comment by fyl2xp1** [comment]
Thanks, I added to my `/etc/network/interface`:
```
auto eth3
iface eth3 inet manual
    post-up route add -net ...
    pre-down route del -net ...
```
This seems to work reliably but still feels odd because all other adapters as missing from that list and the rest of the interface's configuration resides in an external configuration.

**Comment by dominikdev-m** [comment]
Anything new on this?
