### ISSUE TITLE
Clarify the acceptance of pull requests in CONTRIBUTING

### ISSUE THREAD

**Issue by krichter722** [lxc/lxc#500]
Due to the fact that the project is on github.com mentioning pull requests in CONTRIBUTING explicitly is useful in general - regardless of whether " The contributions should be email patches" is quite clear (there're merged pull requests, so there's need for clarafication).

**Comment by jirutka** [comment]
This seems to be already fixed. There’s [CONTRIBUTING](https://github.com/lxc/lxc/blob/master/CONTRIBUTING) file in the repo and according to it, contributions are accepted via email patches _and_ pull requests.

**Comment by krichter722** [comment]
Agreed. Yet, an explicit statement would be helpful, i.e. "Pull requests are not accepted.", "Pull requests are accepted.".

**Comment by krichter722** [comment]
It was changed and the author missed to close this issue. Thanks for the pointer.
