### ISSUE TITLE
Wrong API documentation for get_config_item()

### ISSUE THREAD

**Issue by jhenninger** [lxc/lxc#505]
The [API documentation](https://linuxcontainers.org/lxc/apidoc/structlxc__container.html#ad400f7bf1a0ae8181df01591d80c23ce) for `get_config_item()` states:

> If `inlen` is smaller than required, the value written to retv `will` be truncated.

But that's not what happens. If `inlen` is smaller than required, nothing will be written to `retv`. The method will still return the length of the value of the config item though, as if it was successfully written.

https://github.com/lxc/lxc/blob/master/src/lxc/confile.c#L2433:

``` c
if (!v)
    return 0;
if (retv && inlen >= strlen(v) + 1)
    strncpy(retv, v, strlen(v)+1);
return strlen(v);
```

I did not make a pull request because I don't know which behavior is preferred and whether the code or documentation should be changed.

**Comment by brauner** [comment]
At this point the documentation should be updated since there might well be users which rely on this behavior.

**Comment by marcosps** [comment]
It seems this issue is fixed by looking at the api docs: https://linuxcontainers.org/lxc/apidoc/structlxc__container.html#a7411db2a0e7a8471c41a4a58d8e83b33
