### ISSUE TITLE
lxc removal triggers /var/lib/lxc removal

### ISSUE THREAD

**Issue by kiorky** [lxc/lxc#507]
Im -1 on automatic removal of /var/lib/lxc which can contain persistent data (from old containers).

I was removing manually my lxc packages to reinstall them cleanly as i was testing packages version amongst the different lxc PPA, and i noted that from the removal stage i got a
```
dpkg : avertissement : lors de la suppression de lxc, impossible de retirer « /var/lib/lxc » : Périphérique ou ressource occupé - peut-être le répertoire est-il un point de montage ?
```
Sorry for the french local, but yes something triggers /var/lib/lxc removal, i think that it should just be left as is.

**Comment by kiorky** [comment]
If you want more confidences on versions, that's an uptodate trusty host and:
```
rc  liblxc0                                  1.0.0~alpha1-0ubuntu14.1            amd64        Linux Containers userspace tools (library)
rc  liblxc1                                  1.1.2-0ubuntu3~ubuntu14.04.1~ppa1   amd64        Linux Containers userspace tools (library)
rc  lxc                                      1.1.2-0ubuntu3~ubuntu14.04.1~ppa1   amd64        Linux Containers userspace tools
rc  lxcfs                                    0.7-0ubuntu4~ubuntu14.04.1~ppa1     amd64        FUSE based filesystem for LXC
rc  lxctl                                    0.3.1+debian-3                      all          Utility to manage LXC

```

**Comment by kiorky** [comment]
As it is more a packaging issue, that bug may not live here...

**Comment by stgraber** [comment]
root@castiana:~/data/code/lxc/lxd# apt-get remove lxc
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following packages will be REMOVED:
      lxc lxc-dev lxc-templates
    0 upgraded, 0 newly installed, 3 to remove and 0 not upgraded.
    After this operation, 2,168 kB disk space will be freed.
    Do you want to continue? [Y/n] 
    (Reading database ... 195964 files and directories currently installed.)
    Removing lxc-templates (1.1.2+master~20150428-0938-0ubuntu1~vivid) ...
    Removing lxc-dev (1.1.2+master~20150428-0938-0ubuntu1~vivid) ...
    Removing lxc (1.1.2+master~20150428-0938-0ubuntu1~vivid) ...
    Removing lxc dnsmasq configuration
    Processing triggers for man-db (2.7.0.2-5) ...
    root@castiana:~/data/code/lxc/lxd# ls /var/lib/lxc
    lxd-01	lxd-02

Even if passing --purge, dpkg will not remove a /var directory as long as it contains data.

I believe it does that by attempting a rmdir and if that fails (as is the case if there's something inside), it just ignores the error and continues, so even if /var/lib/lxc wasn't a mount point in your case, it wouldn't have removed any container.

Closing the issue since it's not actually an issue :)

**Comment by kiorky** [comment]
ok, thx.
