### ISSUE TITLE
lxc-usernet group permissions/limits

### ISSUE THREAD

**Issue by hkjolhede** [lxc/lxc#513]
I would suggest that the lxc-usernet file could also contain permissions for usergroups to create nics, E.g. `@lxc veth lxcbr0 20` which would allow any user of the lxc group to create a new nic, up to a total of 20 for that group. This would allow for easier administration when using separate users for each container.
If you like the suggestion I would be happy to create a PR.

**Comment by stgraber** [comment]
Hi,

It's something that's been in our mental todolist for a while so yes, it'd be great if you could send a pull request for it!

Thanks!

**Comment by hkjolhede** [comment]
Any opinions on which pool should be used first if the user is specified both as an individual user and as part of a group?

**Comment by stgraber** [comment]
I'd count it first towards the user's own allocation and once the user's run out, they use the group's.

**Comment by hkjolhede** [comment]
That was my thought as well, so glad you agree. :)

**Comment by evgeni** [comment]
#517 is merged, @stgraber can you close here? :)
