### ISSUE TITLE
download template - fix for /tmp mounted separately

### ISSUE THREAD

**Issue by itoffshore** [lxc/lxc#516]
If `/tmp` is mounted separately it is likely to be either a `tmpfs` or a small partition mounted `noexec` & `lxc-create -n xxxx -t download` will not complete.

A [simplified condition](https://github.com/lxc/lxc/compare/master...itoffshore:master) to check if `/tmp` is mounted separately.

**Comment by brauner** [comment]
If this is still an issue for you please send a pr.
