### ISSUE TITLE
Allow using wireless interfaces with type = phys

### ISSUE THREAD

**Issue by stgraber** [lxc/lxc#52]
Currently using:
lxc.network.type = phys
lxc.network.link = wlan0

Will fail as apparently moving one of those is slightly different than moving a standard eth interface, it'd be good to have lxc and lxc-device detect those and do the right thing.

**Comment by cernekee** [comment]
Now that lxc-device supports migrating wireless interfaces via `iw`, does it make sense to reopen this bug and add the same functionality to lxc-start?

**Comment by stgraber** [comment]
I thought that already worked today so long as you make sure to list phy0 or whatever the name of the physical device is first.

**Comment by cernekee** [comment]
Is this what you're suggesting?

```
lxc.network.type = phys
lxc.network.name = phy0
lxc.network.link = phy0
lxc.network.flags = up

lxc.network.type = phys
lxc.network.name = wlan0
lxc.network.link = wlan0
lxc.network.flags = up
```

Unfortunately LXC was not able to look up the `phy0` interface (it doesn't actually exist in `ifconfig -a` either):

```
# lxc-start -F -f /mnt/stateful_partition/lxc/bb/config --name busybox
lxc-start: conf.c: instantiate_phys: 2845 failed to retrieve the index for phy0
lxc-start: conf.c: lxc_create_network: 2955 failed to create netdev
lxc-start: start.c: lxc_spawn: 914 failed to create the network
lxc-start: start.c: __lxc_start: 1164 failed to spawn 'busybox'
lxc-start: lxc_start.c: main: 344 The container failed to start.
lxc-start: lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.
```

but `lxc-device --name=busybox -- add wlan0` successfully transferred the device after the container was started.

**Comment by nimaaghli** [comment]
is this problem solved ? i can use lxc-device to add wlan but i dont want to do it each time i start container! is there anywaya to do same thing in config file of container ?
