### ISSUE TITLE
LXC Iptables Issue

### ISSUE THREAD

**Issue by jonny3010** [lxc/lxc#524]
root@WinterFell /home/jonny                                                                                       [21:30:33] 
### lxc-attach -n u1                                                                                                        
root@u1:# iptables -L
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.0.2-040002-generic/modules.dep.bin'
iptables v1.4.21: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
root@u1:# exit
exit
                                                                                                                             
root@WinterFell ~jonny                                                                                            [21:30:44] 
### iptables -L                                                                                                             
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
                                                                                                                             
root@WinterFell ~jonny                                                                                            [21:30:47] 
### lxc-attach -n u1                                                                                                        
root@u1:# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
root@u1:/# /etc/iptables.sh 
root@u1:/# iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  192.168.2.0/24       anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain FORWARD (policy DROP)
target     prot opt source               destination         

Chain OUTPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             192.168.2.0/24      
ACCEPT     all  --  anywhere             servidor. 
ACCEPT     all  --  anywhere             ip14
ACCEPT     all  --  anywhere             ip109
ACCEPT     all  --  anywhere             ip46
ACCEPT     all  --  anywhere             anywhere            
root@u1:/# exit

**Comment by stgraber** [comment]
Not a bug. iptables requires kernel modules to be loaded. If those modules aren't loaded, the container's iptables will fail as seen above. When running iptables on the host, the modules are automatically loaded and so iptables works in containers after that.
