### ISSUE TITLE
mktemp in scripts fail if libpam-tmpdir is in use (unprivileged lxc)

### ISSUE THREAD

**Issue by shinji257** [lxc/lxc#525]
Ok so this is an odd one.  Took me a bit to track down.  For the sake of tracking this is the error that shows up when you hit this.  Note there are a couple of assumptions made based on observation during issue isolation.

lxc-create: lxccontainer.c: lxc_container_new: 3876 Error: test creation was not completed
mktemp: failed to create directory via template ‘/tmp/user/1000/tmp.XXXXXXXXXX’: Permission denied
lxc-create: lxccontainer.c: create_run_template: 1194 container creation template for test failed
lxc-create: lxc_create.c: main: 274 Error creating container test

The issue comes around because during script operation it changes context to run as the target uid.  In my case it is trying to create the above folder as uid/gid 100000 since that's what my uidmap/gidmap is set to.  This gets denied due to the secure perms set by libpam-tmpdir.

These are the default perms the module creates.
drwx------ 2 shinji root 4096 May 14 22:00 /tmp/user/1000

There are a couple of possible options here.

1) If mktemp fails then retry with TMPDIR unset.
2) Override mktemp targeting of TMPDIR to use $HOME instead when creating unprivileged containers (mktemp -d --tmpdir=$HOME)
3) If mktemp fails then retry with mkdir instead.

There might be more.  For now I'm just explicitly setting TMPDIR when I run it (TMPDIR=/tmp lxc-create...) which works for me however this should probably get patched up.

P.S. - Looks like I got this package in from a ppa build of tmux and it had been listed as a recommend.  XD

**Comment by shinji257** [comment]
Looking at #516 it might be feasible to expand that to include a permission check and use the same fallback method.

**Comment by brauner** [comment]
If someone sends the pr in #516 we can have a discussion about this. :)

**Comment by htot** [comment]
The patch in PR #4681 is carried by Yocto [here](https://git.yoctoproject.org/meta-virtualization/tree/recipes-containers/lxc/files/templates-actually-create-DOWNLOAD_TEMP-directory.patch) (along with others) and resolves this issue. However the use of -p is incorrect as if causes a new error when DOWNLOAD_TEMP is not set. The modified patch using --tmpdir= resolves that too.
