### ISSUE TITLE
Container's filesystem group rights ignored

### ISSUE THREAD

**Issue by Neckara** [lxc/lxc#527]
Hello,

In a LXC container I got :

``` shell
me@container:~$ ls -l ~/../user/dir
ls: impossible d'ouvrir le répertoire /home/me/../user/dir: Permission non accordée
me@container:~$ ls -l ~/../user/
total 4
drwxr-x--- 7 user GP 4096 mai   15 09:10 dir
me@container:~$ cat /etc/group | grep GP
GP:x:1006:me,user
```

I can't access the folder "dir" with my user "me" which have rx rights for group and belong to the group "GP". But "me" also belong to "GP".

Which is stange as I can't reproduce it in another Debian computer outside a container.

Might it be a LXC bug (?).

**Comment by brauner** [comment]
If you're using an unprivileged container this is not a bug since the {g,u}ids are mapped. If you're using a privileged container but the gid number for the groups on the host and inside the of the container are different you'd also get the same behavior. In any case not a LXC bug.
