### ISSUE TITLE
Support relative bind mounts in fstab

### ISSUE THREAD

**Issue by willbryant** [lxc/lxc#528]
One thing we make a lot of use of in VMs is to mount a large storage volume from the host as a device in the VM, and to bind mount subdirectories of that volume to places in the VM.  In a VM it looks something like this:

```
/dev/vdb /var/storage ext4 defaults 0 0
/var/storage/mysql /var/lib/mysql bind defaults,bind 0 0
```

In LXC we'd like to do the same thing.  In the host we start with this in the fstab for the container:

```
/dev/root_vg/somecontainer-storage var/storage ext4 defaults 0 0
```

I'd then hoped to add the bind mount in the same fstab for the container, so that I don't have to give the container the apparmor permission to do bind mounts itself.  

```
/dev/root_vg/somecontainer-storage var/storage ext4 defaults 0 0
var/storage/mysql var/lib/mysql bind defaults,bind 0 0
```

LXC already supports relative paths for the target path to make the bind mount appear in the right place in the container.  But a relative source path is just interpreted as being relative to the host's /usr/lib directory with the LXC binaries.

It'd be good if it instead meant a path inside of the container, potentially mounted by a previous line in the fstab.  In this example, it's not possible to specify the path in the host, because the source of the bind mount isn't mounted before the container is started.

**Comment by brauner** [comment]
Support for this has been added in 181437fd530cb1d2a9e1ce2afd8aaa5fca16b872 .
