### ISSUE TITLE
CentOS 7 x86_64 Very Slow Start

### ISSUE THREAD

**Issue by Lothriel** [lxc/lxc#530]
Running LXC 1.1.2 and 1.0.7 I have reproduced this issue 100% of the time;

[root@cent7-test ~]# lxc-create -n c7 -t download -- -r 7 -d centos -a amd64
[root@cent7-test ~]# lxc-start -n c7 -F
systemd 208 running in system mode. (+PAM +LIBWRAP +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ)
Detected virtualization 'lxc'.

Welcome to CentOS Linux 7 (Core)!

Cannot add dependency job for unit display-manager.service, ignoring: Unit display-manager.service failed to load: No such file or directory.
[  OK  ] Reached target Remote File Systems.
[  OK  ] Listening on /dev/initctl Compatibility Named Pipe.
[  OK  ] Listening on Delayed Shutdown Socket.
[  OK  ] Reached target Encrypted Volumes.
[  OK  ] Listening on Journal Socket.
         Starting Create static device nodes in /dev...
         Mounting Huge Pages File System...
         Mounting POSIX Message Queue File System...
         Mounting Debug File System...
         Starting Journal Service...
[  OK  ] Started Journal Service.
         Mounting Configuration File System...
[  OK  ] Reached target Swap.
         Starting Remount Root and Kernel File Systems...
[  OK  ] Created slice Root Slice.
[  OK  ] Created slice User and Session Slice.
[  OK  ] Created slice System Slice.
[  OK  ] Reached target Slices.
[  OK  ] Created slice system-getty.slice.

After this point it takes about 2 minutes per [ OK ] step. I've successfully loaded a centos6 container with no issues.

**Comment by OxAA** [comment]
Got exactly the same behaviour.
Host: debian jessie 3.16.0-4-amd64, LXC 1.0.6, container was created via 
\# lxc-create -n test -t centos -- -R 7

**Comment by dmick** [comment]
You need a later lxc and templates.  Running into the same issue myself; installed lxc from the trusty PPA, and got much further, but still having problems; now trying the updated lxc-templates

**Comment by nehaljwani** [comment]
I think 28468a67cbe3a3b1dc915c6afabefd7d666cd11e fixed this issue.
Till that a temporary workaround was to use to replace:
```lxc.include = /usr/share/lxc/config/centos.common.conf```
with
```lxc.include = /usr/share/lxc/config/fedora.common.conf```

**Comment by brauner** [comment]
This is fixed in newer versions of the template.
