### ISSUE TITLE
Creating on LVM

### ISSUE THREAD

**Issue by alex-eri** [lxc/lxc#531]
I tried to install Centos 7 in LXC on Debian 8 with command 

lxc-create -n hosting -t centos --lvname=hosting --vgname=cyber1 -B lvm --fssize=320G --fstype=ext4 -- -R 7

lxc-create tried to copy rootfs directory to device /dev/cyber1/hosting not mount point, then create nodes with paths like this 
«/dev/cyber1/hosting/dev/tty»

**Comment by brauner** [comment]
The storage drivers have been reworked substantially so it is unclear whether this is still an issue and reproducible. I'm also unclear what exactly the problem here is. Please provide the information in the issue template and re-open if this is still an issue for you.
