### ISSUE TITLE
Configuration option for running LXC containers as user

### ISSUE THREAD

**Issue by daald** [lxc/lxc#535]
When installing unprivileged containers as a user, they are placed in `.local/share/lxc/`. This setup is safe, but I have several disadvantages. For example, I cannot auto-start containers and have other limitations like su/sudo which is not working and calling lxc-ls as root returns an empty list.

I currently try to set up a secure host which purpose is to run unprivileged lxc containers. In this simple setup, I'd like to have my containers stored in /var/lib/lxc, have all the advantages of it, but I still want that the monitor process runs as user and that that the container's root user is not mapped to the host's root user (because it needs the subuid/subgid mapping "root:100000:65536" which is worth nothing).

Why not implementing a config option like `lxc.changeuid` which calls `setuid()` inside lxc-start after initializing just to make sure that security leaks in lxc don't result in root permissions on the host? With this option, lxc-start would behave like when called from a non-root user and work with user mappings but still feel like privileged containers.

In the far future, this could also become a default option, for example with a system user called lxc-container.

**Comment by stgraber** [comment]
We'd have to be pretty careful if we were to do that as we may very well have code today which requires the monitor process to be able to do operations inside the container's namespace.
The only way it'd be able to do that is if it's either running as root or running as the user who owns the uid/gid range in use by the container. Switching to another uid would prevent us from ever using setns in the monitor.

We've never really considered this to be a security concern as there's no interface between the processes inside the container and the monitor, so a user in the container cannot do anything which would be parsed by the monitor outside of the container.

As for the rest, we do support having root spawn unprivileged containers and have them stored in /var/lib/lxc. All you need to do to do that is set the two lxc.id_map entries in /etc/lxc/default.conf

**Comment by daald** [comment]
When I start unprivileged containers from root I have to add "root:100000:65536" to /etc/subuid and /etc/subgid which maps the container's root with uid 100000 mapped to the host's root user with uid 0, so there is no extra security anymore compared to privileged containers.

When I don't add the root line to /etc/sub?id, lxc-start fails with errors like "lxc_conf - conf.c:userns_exec_1:4735 - Error setting up child mappings"

**Comment by stgraber** [comment]
Your understanding of /etc/subuid is incorrect.

**Comment by stgraber** [comment]
/etc/subuid and /etc/subgid only lists uids/gids which your user is allowed to use on top of its own existing uid/gid, it doesn't map those to the user. So when root switches to uid 100000, it no longer has any privileges.

**Comment by daald** [comment]
I see, I was really wrong with that. But anyway: I would prefer to see the monitor task to be (optionally) owned by the somthing which is matching to the uid/gid mapping, also when started as root. I don't know the technical backgrounds but it works too with user-space containers, so it shouldn't be a big problem.

**Comment by gdm85** [comment]
I would like as well to use **both** the subuid/subgid mapping and change the default user of the container. I've tried experimenting with ``init_uid``/``init_gid``, without success. For example with [my busybox-nonroot image](https://github.com/gdm85/lxd-images) I can successfully run:
```
# lxc launch busybox-nonroot mytest
# lxc exec mytest sh


BusyBox v1.21.1 (Ubuntu 1:1.21.0-1ubuntu1) built-in shell (ash)
Enter 'help' for a list of built-in commands.

/root # su -l nobody


BusyBox v1.21.1 (Ubuntu 1:1.21.0-1ubuntu1) built-in shell (ash)
Enter 'help' for a list of built-in commands.

~ $ whoami
nobody
~ $ 
```

However I'd like to run a process in the container as init (not ``/sbin/init``, obviously) directly as non-root.

**Comment by brauner** [comment]
Changing the monitor owner is not something which we'll implement. As @stgraber pointed out there are some operations which the monitor process is expected to perform which require it to be non-container user owned. Also, there's no security thread as he also pointed out.

The latter issue is really about using `LXD` and not `LXC` itself so should be reopened there. However, setting `lxc.init_{g,u}id` didn't work correctly prior to d08f8d2f74c7407c40fc80e3878d631bd8f50214 . Note however, that switching to an unprivileged {g,u}id before init start will only work with certain programs. For example, a bash shell with `lxc-{start,execute}` will work fine a full init system like `systemd` however will be very very very unhappy with this and refuse to work.
