### ISSUE TITLE
Unprivileged containers with LVM

### ISSUE THREAD

**Issue by matlink** [lxc/lxc#537]
Is it planned to have an unprivileged version of LXC using LVM (with -B option) ? 
I can imagine that the only picky point is to  ask sudo password while creating the LV and mount it (also when lxc-start if not in /etc/fstab). 
I could make a script or do it manually every time I want to create/use a container, but that's quite pain in the face.

**Comment by stgraber** [comment]
We don't have any such plan as allowing unprivileged users to mount random block devices is a clear security issue and not something we've got any plans in supporting.

If at some point, those security problems are resolved to a point where the kernel developers feel that LVM and filesystem use is suitable for unprivileged user, things will just work with LXC.

Until then, your best bet is to use a pre-mount hook within LXC to setup your container's rootfs. You can do whatever you want in those, including calling sudo if you so wish.

**Comment by matlink** [comment]
Thanks @stgraber, but there is no hook for running script before starting the container since the config file is in the Logical volume, and if it's not mounted lxc-start cannot find it.

For those who might be interested by this, I've made a couple of bash scripts that create Logical volumes, mount them and fix permissions before creating the container. The second one can also check if LV is mounted and check permissions before starting the container, and the last one can destroy a container and unmount LV followed by removing the LV. Of course, they ask for sudo password in order to manage Logical Volumes and fixe permissions.

You can find them here : https://github.com/matlink/lxc

**Comment by stgraber** [comment]
Then you're doing something really weird. LXC using LVM only uses a LV for the rootfs, not for the LXC configuration file which remains in /var/lib/lxc or /home/USER/.local/share/lxc/

**Comment by adam-edwards** [comment]
Just finding this thread and I've got a question. @stgraber above you state:
> allowing unprivileged users to mount random block devices is a clear security issue

... but in `/etc/lxc/lxc-usernet`:
```
<user> veth lxcbr0 10
```
I don't think we're just letting unprivileged users create random network interfaces. Could there be an interface like this for allowing an unprivileged user to create/mount a block device within the configured parameters? Or is there some other solution to this by now?

**Comment by brauner** [comment]
On Sat, Mar 23, 2019 at 06:44:39PM -0700, Adam wrote:
> Just finding this thread and I've got a question. @stgraber above you state:
> > allowing unprivileged users to mount random block devices is a clear security issue
> 
> ... but in `/etc/lxc/lxc-usernet`:
> ```
> <user> veth lxcbr0 10
> ```
> I don't think we're just letting unprivileged users create random
> network interfaces. Could there be an interface like this for allowing
> an unprivileged user to create/mount a block device within the
> configured parameters? Or is there some other solution to this by now?

LXC can't do this without using setuid binaries and I'm very much
against this. It is possible to do it safely with LXD though. So you
might want to take a look at LXD.
