### ISSUE TITLE
Unprivileged container doesn't get a network address automatically.

### ISSUE THREAD

**Issue by ccope** [lxc/lxc#539]
On a fresh install of 15.04 fully updated as of 05/26. Steps to repro:
1. Install lxc from the default repo's
2. Follow the guide at https://www.stgraber.org/2014/01/17/lxc-1-0-unprivileged-containers/
3. After creating and starting a vivid image from the download template, the new unprivileged container has no IP address. Running dhclient eth0 fixes this.

**Comment by brauner** [comment]
This is not really `LXC`'s fault. If the init system doesn't start a dhcp client on startup you need to do it manually afterwards.
