### ISSUE TITLE
major breakage on fedora - ppc64

### ISSUE THREAD

**Issue by xcasex** [lxc/lxc#544]
Due to the $arch guesswork there's major breakage on ppc64 fedora, we are unable to utilize half of our server farm due to this.
on top of this issue, there's also something odd going on with getting the systems up.

will be reacquiring logs to support this report.

**Comment by brauner** [comment]
The `fedora` template has been rewritten from scratch. This issue should have been addressed during this hopefully. If you still see the breakage, report back here and we'll reopen.
