### ISSUE TITLE
OpenSUSE 12.3 URI pointing to OpenSUSE 13.1 image in linuxcontainers.org

### ISSUE THREAD

**Issue by groug** [lxc/lxc#549]
When using lxc-create -t download, the only container available for suse is 12.3 but it installs a 13.1 suse.
The problem is that the rootfs archive inside http://images.linuxcontainers.org/images/opensuse/12.3/ is an archive of OpenSUSE 13.1 despite the URI name.
I don't know where to report this, so I'm reporting it here.

**Comment by brauner** [comment]
This should be fixed in newer versions of the template. Also, `12.3`, and `13.1` are not supported anymore.
