### ISSUE TITLE
Not able to start unprivileged container on Linux Mint 17 - Quota Reached

### ISSUE THREAD

**Issue by ajitabhpandey** [lxc/lxc#551]
Hello,

On fully updated Linux Mint 17, I installed unprivileged container successfully, but when I try to start them I get the following message - 

$ lxc-start -n unprivileged1 -l trace -o debug.out
Quota reached
lxc-start: start.c: lxc_spawn: 927 failed to create the configured network
lxc-start: start.c: __lxc_start: 1080 failed to spawn 'unprivileged1'
lxc-start: lxc_start.c: main: 342 The container failed to start.
lxc-start: lxc_start.c: main: 346 Additional information can be obtained by setting the --logfile and --logpriority options.

$ cat debug.out
      lxc-start 1433427964.021 INFO     lxc_start_ui - lxc_start.c:main:265 - using rcfile /home/ajitabhp/.local/share/lxc/unprivileged1/config
      lxc-start 1433427964.021 INFO     lxc_confile - confile.c:config_idmap:1325 - read uid map: type u nsid 0 hostid 100000 range 65536
      lxc-start 1433427964.021 INFO     lxc_confile - confile.c:config_idmap:1325 - read uid map: type g nsid 0 hostid 100000 range 65536
      lxc-start 1433427964.021 WARN     lxc_log - log.c:lxc_log_init:316 - lxc_log_init called with log already initialized
      lxc-start 1433427964.023 WARN     lxc_cgmanager - cgmanager.c:cgm_get:954 - do_cgm_get exited with error
      lxc-start 1433427964.023 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
      lxc-start 1433427964.023 DEBUG    lxc_conf - conf.c:lxc_create_tty:3665 - allocated pty '/dev/pts/7' (5/6)
      lxc-start 1433427964.024 DEBUG    lxc_conf - conf.c:lxc_create_tty:3665 - allocated pty '/dev/pts/8' (7/8)
      lxc-start 1433427964.024 DEBUG    lxc_conf - conf.c:lxc_create_tty:3665 - allocated pty '/dev/pts/11' (9/10)
      lxc-start 1433427964.024 DEBUG    lxc_conf - conf.c:lxc_create_tty:3665 - allocated pty '/dev/pts/12' (11/12)
      lxc-start 1433427964.024 INFO     lxc_conf - conf.c:lxc_create_tty:3676 - tty's configured
      lxc-start 1433427964.024 DEBUG    lxc_start - start.c:setup_signal_fd:247 - sigchild handler set
      lxc-start 1433427964.024 DEBUG    lxc_console - console.c:lxc_console_peer_default:500 - opening /dev/tty for console peer
      lxc-start 1433427964.024 DEBUG    lxc_console - console.c:lxc_console_peer_default:506 - using '/dev/tty' as console
      lxc-start 1433427964.024 DEBUG    lxc_console - console.c:lxc_console_sigwinch_init:179 - 4392 got SIGWINCH fd 17
      lxc-start 1433427964.024 DEBUG    lxc_console - console.c:lxc_console_winsz:88 - set winsz dstfd:14 cols:181 rows:39
      lxc-start 1433427964.276 INFO     lxc_start - start.c:lxc_init:443 - 'unprivileged1' is initialized
      lxc-start 1433427964.291 DEBUG    lxc_start - start.c:__lxc_start:1058 - Not dropping cap_sys_boot or watching utmp
      lxc-start 1433427964.291 INFO     lxc_start - start.c:lxc_spawn:802 - Cloning a new user namespace
      lxc-start 1433427964.291 INFO     lxc_cgroup - cgroup.c:cgroup_init:62 - cgroup driver cgmanager initing for unprivileged1
      lxc-start 1433427964.331 ERROR    lxc_start - start.c:lxc_spawn:927 - failed to create the configured network
      lxc-start 1433427964.367 ERROR    lxc_start - start.c:__lxc_start:1080 - failed to spawn 'unprivileged1'
      lxc-start 1433427964.371 ERROR    lxc_start_ui - lxc_start.c:main:342 - The container failed to start.
      lxc-start 1433427964.371 ERROR    lxc_start_ui - lxc_start.c:main:346 - Additional information can be obtained by setting the --logfile and --logpriority options.

**Comment by jcarmena** [comment]
Hello, you can solve this problem following the [getting started instructions](https://linuxcontainers.org/lxc/getting-started/): 

> Next up is /etc/lxc/lxc-usernet which is used to set network devices quota for unprivileged users.
> By default, your user isn't allowed to create any network device on the host, to change that, add:
> 
> `your-username veth lxcbr0 10`

**Comment by brauner** [comment]
See the previous comment for a solution. :)

**Comment by ledlamp** [comment]
how to start lxc container with no networking?
