### ISSUE TITLE
lxc-attach not a tty, so tmux/byobu is broken

### ISSUE THREAD

**Issue by linas** [lxc/lxc#554]
If you `lxc-attach -n some-container`, then tmux and byobu don't work.  The reason for this becomes clear: `tmux -v` reports:

```
server started, pid 760
socket path /tmp/tmux-1002/default
new client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 14 from client 7
got 6 from client 7
fatal: tty_init: ttyname failed
```

This can be confirmed with the `tty` command which reports: `not a tty`

There is a simple work-around: say `script /dev/null` and then `tty` reports `/dev/pts/1` and tmux works.

**Comment by linas** [comment]
Sorry: I should add: this is for the apt-get lxc on ubuntu 14.04 runing ubunutu 14.04 amd64  so it is the completely stock LTS version, and NOT the current github version, which maybe is fixed.  Also: FYI: the docker folks have more or less exactly this same bug; they have a bug open in their github to cover this.  They seem to be unable to wrap their minds around why anyone would want to do this, despite maybe a dozen "me too" posts.

**Comment by ericsnowcurrently** [comment]
FTR: https://github.com/docker/docker/issues/8755

**Comment by brauner** [comment]
This is a known bug in glibc and @hallyn has send a fix to glibc (https://sourceware.org/ml/libc-alpha/2016-08/msg00307.html). It just needs to be applied.

**Comment by linas** [comment]
Wow! Awesome!  Thank you @hallyn !  (I'm saying "awesome" because this is an interesting patch, not what I might have guessed.)

**Comment by linas** [comment]
I guess the normal protocol is to leave this open until glibc applies the patch, and then wait till it rolls out, test it, and then close this bug (!?).  Unfortunately, the patch just missed the glibc 2.24 release by a week.   I wonder what the chances are that debian/ubuntu might pick up the patch in their stable branches; I have no clue how that decision would get made.

**Comment by kfix** [comment]
the glibc fix seems to have been upstreamed recently: http://patchwork.ozlabs.org/patch/720749/
No idea when they will next cut a release that will be seen in Ubuntu.

**Comment by brauner** [comment]
This is the same issue that we've tracked in https://github.com/lxc/lxd/issues/936 .
- A version of the required `glibc` patch has been upstreamed by @hallyn and me (https://github.com/lxc/lxd/issues/936#issuecomment-291472736).
- `tmux` should be fixed as of https://github.com/tmux/tmux/commit/9b28200578670183a0dc70f1d16d5642101a6982
- I've also sent patches to `screen` (https://git.savannah.gnu.org/cgit/screen.git/commit/?id=fbee2ab0bc0a3d9be9d6987dc5228f5bf46a07cb , https://git.savannah.gnu.org/cgit/screen.git/commit/?id=565b8901cad828d921038cd6235501c42d1c9a32 )

Once the distros pick-up on those you're good to go.
