### ISSUE TITLE
Predictable root passwords for most templates

### ISSUE THREAD

**Issue by major** [lxc/lxc#565]
I was reading through a [Red Hat Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1132004) ticket about predictable root passwords in LXC templates and noticed that Fedora/CentOS templates set a randomized root password while many of the other templates don't.  I've not made commits to the LXC project before but I'm curious to know if pull requests adding this functionality to more of the templates would be welcomed.

If those changes would be welcomed, please let me know and I'll be more than happy to work on them. ;)

**Comment by stgraber** [comment]
Yeah, it's something that came up a few times. Nowadays we recommend most users use the pre-build images with the download template. Those images come with no password set for any of the users, instead recommending users use lxc-attach.

Those images also come without ssh servers.

I think it'd be a good thing to bring this up on the mailing-list again and suggest that all templates default to no password set (and refusing empty password) as well as no remote shell. Supporting the same password options as fedora/centos is also an option, though not applicable to the download template which we may be able to implement for all templates using shared functions.

**Comment by major** [comment]
Thanks, @stgraber. Would that be a better topic for lxc-devel or lxc-users?

**Comment by stgraber** [comment]
lxc-devel

**Comment by major** [comment]
I'm on it, @stgraber!  Thanks for pointing me in the right direction.

**Comment by major** [comment]
Thread: https://lists.linuxcontainers.org/pipermail/lxc-devel/2015-June/011883.html
