### ISSUE TITLE
lxc-clone fail to copy a hook script

### ISSUE THREAD

**Issue by jan021213** [lxc/lxc#566]
When config is set same a hook script, lxc-clone fail. 
'''
root@dgt-srv403:/var/lib/lxc/XXX# grep hook config 
lxc.hook.pre-start = /var/lib/lxc/XXX/hook.sh
lxc.hook.post-stop = /var/lib/lxc/XXX/hook.sh
lxc.hook.clone = /var/lib/lxc/XXX/hook.sh
'''
'''
root@dgt-srv403:/var/lib/lxc/XXX# lxc-clone -o XXX -n YYY
lxc_container: lxccontainer.c: copy_file: 2285 copy destination /var/lib/lxc/YYY/hook.sh exists
lxc_container: lxccontainer.c: lxcapi_clone: 2750 error copying hooks
lxc_container: utils.c: _recursive_rmdir: 148 _recursive_rmdir: failed to delete /var/lib/lxc/YYY
lxc_container: lxccontainer.c: container_destroy: 2071 Error destroying container directory for YYY
clone failed
'''
And recursive_rmdir can.t delete btrfs subvolume rootfs.

**Comment by brauner** [comment]
`lxc-clone` is deprecated in favor of `lxc-copy`. Please re-open if the problem persists.
