### ISSUE TITLE
lxc ubuntu error cloning "container is not defined"

### ISSUE THREAD

**Issue by fortinux** [lxc/lxc#575]
Hi,
When I try to clone a container I get this error message:
sudo lxc-clone -o webserver -n webserver2
Error: container webserver is not defined

The host is Ubuntu 14.04 and lxc-checkconfig shows:                                                                               
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-3.16.0-41-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled
Multiple /dev/pts instances: enabled

--- Control groups ---
Cgroup: enabled
Cgroup clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled
Macvlan: enabled
Vlan: enabled
File capabilities: enabled

Thanks in advance.

**Comment by stgraber** [comment]
what does lxc-ls show?

**Comment by fortinux** [comment]
sudo lxc-ls                                                                                                                    
container-test  

sudo lxc info container-test
error: not found

If I do (webserver is the container that I want to clone): 
sudo lxc info webserver
Name: webserver
Status: STOPPED

lxc version
0.11

Is that help?

**Comment by stgraber** [comment]
Your problem (as you may have noticed since you closed it) is that you're mixing LXC and LXD commands.

**Comment by fortinux** [comment]
yes, thanks!

**Comment by krichter722** [comment]
There's still the issue that the error message effectively says `container is not defined` when it should say `The lxd binary could not be found/not be executed (because of underlying error xy)` or `Could not connect to lxd socket ab (because of underlying issue xy)`. That's a huge UX issue.
