### ISSUE TITLE
lxc-stop --nokill fails for unprivileged container

### ISSUE THREAD

**Issue by jakemagee** [lxc/lxc#583]
It seems that I cannot stop unprivileged containers with "lxc-stop --nokill".  It fails every time with a return of 1.  However, if I execute a shutdown inside of the container while the -stop --nokill is waiting, when the container shutsdown, it will return successful.  It seems like my user doesn't have permission to send the command/signal to the container.

Running lxc 1.1.2 on Ubuntu 15.04 with an unprivileged container of Ubuntu 15.04.

**Comment by brauner** [comment]
`LXC 1.1.*` is now officially deprecated. Please update to `LXC 2.*.*`.
