### ISSUE TITLE
Lxc container rebooting with lxc-stop not working

### ISSUE THREAD

**Issue by dvyas** [lxc/lxc#584]
Hi, 
lxc-1.0.7

I have created a lxc container and started it. Now I want to reboot it 

lxc-stop -r -W -n vm0

while lxc-monitor -n vm0 not showing status change.

The debug output shows
lxc-stop 1436466451.887 WARN     lxc_log - log.c:lxc_log_init:316 - lxc_log_init called with log already initialized 

Any ideas about the solution or problem?

**Comment by brauner** [comment]
The amount of information given is unfortunately insufficient to reproduce and debug this problem. If this is still reproducible please open a new issue and provide the information we request in our issue template.
