### ISSUE TITLE
relative lxc.hook paths

### ISSUE THREAD

**Issue by foresto** [lxc/lxc#587]
I want to share some of my container config files for other people to use without modification, but since lxc.hook.pre-start seems to require an absolute path, it looks like this is impossible. It would be nice if I could specify my hook scripts using paths relative to the container config file. (Specifying them relative to the rootfs might work as well, so long as the scripts could still live outside the rootfs.)

It looks like lxc.rootfs has the same problem.

**Comment by brauner** [comment]
We'd not be opposed to looking at a patch but I'm not sure what the security implications of this would be.

**Comment by EinstokFair** [comment]
Does "competed" mean that relative paths are now possible?

**Comment by hallyn** [comment]
No, I think that's just what github labeled it as.

FWIW I think accepting a relative path which is assumed as relative to the [-P | --lxcpath] directory (default /var/lib/lxc for root or ~/.local/share/lxc for non-root) would be reasonable.
