### ISSUE TITLE
Delete port from OVS bridge when stopping container

### ISSUE THREAD

**Issue by reversecipher** [lxc/lxc#590]
( original bug report: https://github.com/lxc/lxd/issues/835 )

LXC container veth-interface doesn't get removed from openvswitch bridge when container is stopped.

Steps to reproduce:

Create OVS bridge and configure container to use it:

```
ovs-vsctl add-br br-int

lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = br-int
```

Start container and check that veth gets added to bridge:

```
lxc-start -d -n test

lxc-info -n test
Name:           test
State:          RUNNING
PID:            23231
CPU use:        0.84 seconds
BlkIO use:      8.87 MiB
Memory use:     11.57 MiB
KMem use:       0 bytes
Link:           vethCX18P7
 TX bytes:      5.06 KiB
 RX bytes:      648 bytes
 Total bytes:   5.70 KiB

ovs-vsctl show
b8010668-97a7-40d3-8876-bc319e3a5418
    Bridge br-int
        Port br-int
            Interface br-int
                type: internal
        Port "vethCX18P7"
            Interface "vethCX18P7"
    ovs_version: "2.0.2"
```

Stop container, check OVS bridge and veth-interface:

```
lxc-stop -n test

lxc-info -n test
Name:           test
State:          STOPPED

ovs-vsctl show
b8010668-97a7-40d3-8876-bc319e3a5418
    Bridge br-int
        Port br-int
            Interface br-int
                type: internal
        Port "vethCX18P7"
            Interface "vethCX18P7"
    ovs_version: "2.0.2"

ifconfig vethCX18P7
vethCX18P7: error fetching interface information: Device not found
```

Tested using LXC 1.1.2 and OSV 2.0.2.

**Comment by stgraber** [comment]
@hallyn can you take a look since you've done the ovs integration?

**Comment by hallyn** [comment]
is there a proposed patch for this issue?

**Comment by hallyn** [comment]
(Note from the original commit message:

Note that with this patch, veths do not appear to be removed from the
openvswitch bridge.  This seems a bug in openvswitch, as the veths
in fact do disappear from the system.  If lxc is required to remove
the port from the bridge manually, that becomes more complicated
for unprivileged containers, as it would require a setuid-root
wrapper to be called at shutdown.
)

**Comment by itoffshore** [comment]
I use [these scripts] (https://github.com/itoffshore/lxc-scripts) in `lxc 1.1.2` with `ovs` in Alpine Linux.

But I have been noticing it takes a little while for the interface to disappear. Sometimes if I stop & start the container too quickly I get an interface error & the container doesn't start. If I wait a second & try again it starts.

**Comment by itoffshore** [comment]
I use [these scripts] (https://github.com/itoffshore/lxc-scripts) in `lxc 1.1.2` with `ovs` in Alpine Linux.

But I have been noticing it takes a little while for the interface to disappear. Sometimes if I stop & start the container too quickly I get an interface error & the container doesn't start. If I wait a second & try again it starts.

**Comment by itoffshore** [comment]
I use [these scripts] (https://github.com/itoffshore/lxc-scripts) in `lxc 1.1.2` with `ovs` in Alpine Linux.

But I have been noticing it takes a little while for the interface to disappear. Sometimes if I stop & start the container too quickly I get an interface error & the container doesn't start. If I wait a second & try again it starts.

**Comment by itoffshore** [comment]
I use [these scripts] (https://github.com/itoffshore/lxc-scripts) in `lxc 1.1.2` with `ovs` in Alpine Linux.

But I have been noticing it takes a little while for the interface to disappear. Sometimes if I stop & start the container too quickly I get an interface error & the container doesn't start. If I wait a second & try again it starts.

**Comment by itoffshore** [comment]
`veth` interfaces are added ok but not removed in `openvswitch 2.3.2` / `lxc 1.1.2`

I've updated my [lxc / ovs-scripts](https://github.com/itoffshore/lxc-scripts) to just `del-port` in `ovsdown`

These scripts + [`debian/ifupdown.sh`](https://github.com/openvswitch/ovs/blob/master/debian/ifupdown.sh) allow you to restart networking & the containers do not lose connectivity

**Comment by bradenwright** [comment]
I ran into this issue as well.  Thanks @itoffshore (and others I found googling) for help with the solution.  While it would be nice if it just worked, its a good work around.

**Comment by reversecipher** [comment]
I can confirm that LXC now deletes the OVS port when container is stopped, thanks to c43cbc040b83e4eef8d64c26a3636c48d6c5988b. However when container host is rebooted, the port doesn't get deleted and remains in OVS bridge. This prevents the container from starting because the port already exists.

Here are errors in container log:

lxc 20160205214856.513 ERROR    lxc_conf - conf.c:instantiate_veth:2627 - failed to attach 'c1eth0' to the bridge 'br-int': Operation not permitted
            lxc 20160205214856.524 ERROR    lxc_conf - conf.c:lxc_create_network:2904 - failed to create netdev
            lxc 20160205214856.524 ERROR    lxc_start - start.c:lxc_spawn:1010 - failed to create the network
            lxc 20160205214856.524 ERROR    lxc_start - start.c:__lxc_start:1273 - failed to spawn 'test'

I am running LXC 2.0.0.beta2 & LXD 2.0.0.beta1

**Comment by itoffshore** [comment]
I manage `lxc` containers with `runit` now & in the container `run` script I use:
```
ovs-vsctl --if-exists del-port portname
lxc-start -n container -F || exit 1
```
For this to work you need to set in the container `config`:
```
lxc.network.veth.pair = portname
```
You can probably also set a name automatically with:
```
lxc.network.veth.pair = veth.${LXC_ROOTFS_MOUNT##*/}
```

**Comment by brauner** [comment]
Right, since LXC now deletes the ports we can close this issue.
