### ISSUE TITLE
lxc-centos: --repo doesn't work after creating the first container to update

### ISSUE THREAD

**Issue by smalenfant** [lxc/lxc#592]
I have some machine on a private network where I want to use a private repo. When I specify the `--repo http://host/path` it works fine only for the first time. But then it can't be updated afterward (without modifying the repo files in the cache).

Would be nice to specify a directory where the specifics repo files are. There are workarounds, but they need to be done after the cache has been built.

```
Host CPE ID from /etc/os-release: cpe:/o:centos:centos:7
dnsdomainname: Name or service not known
Checking cache download in /var/cache/lxc/centos/x86_64/7/rootfs ... 
Cache found. Updating...
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
warning: Failed to read auxiliary vector, /proc not mounted?
Loaded plugins: fastestmirror
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was
14: curl#56 - "Network error recv()"
```

There is also a problem with the `--repo` option since you can only specify the "os" and not take the "update" in consideration as well.

**Comment by brauner** [comment]
If this is still a problem, patches are welcome.
