### ISSUE TITLE
Pulse audio with lxc

### ISSUE THREAD

**Issue by matlink** [lxc/lxc#599]
Hi,
I've got pulseaudio working with an app ran in an LXC container (based on this https://www.stgraber.org/2014/02/09/lxc-1-0-gui-in-containers/).
However, since I run this app in container, pulseaudio seems to be locked by this app, and any other app than tries to output sound with pulseaudio becomes stuck.
Is there any conf for pulseaudio to stop apps to lock the socket ?

**Comment by brauner** [comment]
Sorry, we can unfortunately not provide configuration support for pulse audio.

**Comment by bmullan** [comment]
@matlink 

Search for and read about using PulseAudio's TCP capability:

basically in your Host you edit /etc/pulse/system.pa and append the following:

load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1;10.0.3.0/24
load-module module-zeroconf-publish

The 1st statement tells PulseAudio daemon in the Host to listen for PulseAudio connections from the localhost & from any device on 10.0.3.x subnet (or whatever your LXC bridge IP is.

In the Host restart the pulseaudio daemon

$ sudo killall pulseaudio

that will kill then automatically restart pulseaudio for your UserID in the host

Then IN the container add the following to your UserID's .bashrc file

in ~/.bashrc

append the following statement to your .bashrc:

export PULSE_SERVER=10.0.3.1

where 10.0.3.1 is the IP address you see for the LXCBR0 bridge when you do an ifconfig lxcbr0 (or with lxdbr0 if using LXD).

lastly while still logged into the container you have to make your UserID a member of the groups audio, pulse, pulse-access:

$ sudo adduser yourID audio
$ sudo adduser yourID pulse
$ sudo adduser yourID pulse-access

see if that gets your app working
