### ISSUE TITLE
liblxc.so: undefined reference to cgmanager_list_controllers_sync

### ISSUE THREAD

**Issue by TragicWarrior** [lxc/lxc#601]
I built libcgmanager from master be4733fad148482c49745f22a86f972b875632d5 without any problems on Ubuntu 14.04.02 LTS 64.  However, now that I am trying to build lxc I am encountering this error:

gcc -I../../src -DLXCROOTFSMOUNT=\"/usr/lib/lxc/rootfs\" -DLXCPATH=\"/usr/var/lib/lxc\" -DLXC_GLOBAL_CONF=\"/usr/etc/lxc/lxc.conf\" -DLXCINITDIR=\"/usr/libexec\" -DLIBEXECDIR=\"/usr/libexec\" -DLXCTEMPLATEDIR=\"/usr/share/lxc/templates\" -DLOGPATH=\"/usr/var/log/lxc\" -DLXC_DEFAULT_CONFIG=\"/usr/etc/lxc/default.conf\" -DLXC_USERNIC_DB=\"/run/lxc/nics\" -DLXC_USERNIC_CONF=\"/usr/etc/lxc/lxc-usernet\" -DDEFAULT_CGROUP_PATTERN=\"/lxc/%n\" -DRUNTIME_PATH=\"/run\" -DSBINDIR=\"/usr/sbin\"  -DHAVE_CGMANAGER -DHAVE_SELINUX   -g -O2 -Wall -Werror -Wl,-E   -o lxc-attach lxc_attach.o liblxc.so   -lselinux  -lutil -lpthread 
liblxc.so: undefined reference to `cgmanager_list_controllers_sync'
collect2: error: ld returned 1 exit status

I first tried building lxc stable-1.1 but every time I tried to run lxc-create I would get an undefined symbol error for 'current_config'.  So now I am trying to build from master which is currently at f5fd66f70ab513a1175f42ea8a878fc985725ce4

**Comment by brauner** [comment]
`LXC 1.1.*` and `cgmanager` are officially deprecated. Please switch to a new version of `LXC`.
