### ISSUE TITLE
lxc-snaphot multiple containers error on zfs bdev

### ISSUE THREAD

**Issue by orgoj** [lxc/lxc#603]
Can't create snapshot on second container, because cloned filesystem haven't unique name. All containers on ZFS bdev create cloned filesystem as ZFSROOT/snap0 (eg. tank/lxc/containers/snap0).

I suggest use name ZFSROOT/CONTAINER_NAME/snap0 on https://github.com/lxc/lxc/blob/f5fd66f70ab513a1175f42ea8a878fc985725ce4/src/lxc/bdev.c#L644
(void) snprintf(path2, MAXPATHLEN, "%s/%s/%s", zfsroot, oname, nname);

**Comment by gotlium** [comment]
+1 

	root@s594:~# lxc-create -t ubuntu -n test1 -B zfs
	...
	# Use the 'sudo' command to run tasks as root in the container.
	##

	root@s594:~# lxc-snapshot -n test1

	root@s594:~# zfs list
	NAME                       USED  AVAIL  REFER  MOUNTPOINT
	tank                        832M   898G    96K  /tank
	tank/lxc                    831M   898G   100K  /tank/lxc
	tank/lxc/containers         361M   898G   100K  /tank/lxc/containers
	tank/lxc/containers/snap0     8K   898G   361M  /tank/lxc/containerssnaps/test1/snap0/rootfs
	tank/lxc/containers/test1   361M   898G   361M  /tank/lxc/containers/test1/rootfs

	root@s594:~# lxc-snapshot -n test1

	root@s594:~# zfs list
	NAME                       USED  AVAIL  REFER  MOUNTPOINT
	tank                        832M   898G    96K  /tank
	tank/lxc                    831M   898G   108K  /tank/lxc
	tank/lxc/containers         362M   898G   100K  /tank/lxc/containers
	tank/lxc/containers/snap0     8K   898G   361M  /tank/lxc/containerssnaps/test1/snap0/rootfs
	tank/lxc/containers/snap1     8K   898G   361M  /tank/lxc/containerssnaps/test1/snap1/rootfs
	tank/lxc/containers/test1   361M   898G   361M  /tank/lxc/containers/test1/rootfs

	root@s594:~# lxc-create -t ubuntu -n test2 -B zfs
	....
	# Use the 'sudo' command to run tasks as root in the container.
	##

	root@s594:~# lxc-snapshot -n test2
	cannot create 'tank/lxc/containers/snap0': dataset already exists
	lxc_container: bdev.c: bdev_copy: 3090 failed getting pathnames for cloned storage: /tank/lxc/containers/test2/rootfs
	lxc_container: lxccontainer.c: copy_storage: 2489 Error copying storage
	lxc_container: lxccontainer.c: lxcapi_snapshot: 2923 clone of /tank/lxc/containers:test2 failed
	lxc_container: lxc_snapshot.c: do_snapshot: 55 Error creating a snapshot

	root@s594:~#

**Comment by hallyn** [comment]
I believe the bug is in src/lxc/bdev.c:zfs_clone, where it uses "$zfsroot/$nname".

What exactly should we use?  Shoudl we just use the full $zfsroot/$lxcpath/$nname?

**Comment by hallyn** [comment]
Putting the lxcpath in there makes zfs unhappy.   Perhaps the zfs path should always be $zfsroot/$(sha1sum lxcpath)/$name.

**Comment by hallyn** [comment]
Thinking that something like lxc/LXCPATH_var_lib_lxc_z1_snaps_z1 is the way to go.

**Comment by hallyn** [comment]
Ok so going that way allows me to snapshot multiple containers, but restoring snapshots still doesn't work because zfs wont' allow us to first delete the original rootfs.  I think we need a different strategy.

**Comment by hallyn** [comment]
zfs seems inherently mismatched with lxc-snapshot, unfortunately.  'zfs restore' to a snapshot would require all snapshots later than the one being restored to be deleted.

I'm tempted to suggest that lxc-snapshot refuse to run with zfs.

**Comment by pejcaofrito** [comment]
Having the same issue here. 
Is that important to have a sequence 0,1,2,,,n for **each** container?
I mean, why not use a global stored (or at that moment calculated) "next_snap_id" and use that? So in Gotlium case the snap will be "snap2" (whether or not is the next id for container "test2")...
...or am I missing something?

BTW, this is "zfs list -t snapshot" after playing for a while:
NAME                   USED  AVAIL  REFER  MOUNTPOINT
zfsvms/vms/ext@snap0      0      -   291M  -
zfsvms/vms/int@snap0      0      -   235M  -
zfsvms/vms/int@snap1      0      -   235M  -
zfsvms/vms/int@snap2      0      -   279M  -

so $zfsroot/$lxcpath<INSERT_SOME_DELIMITER_HERE>$nname looks cool

**Comment by brauner** [comment]
I agree with @hallyn that this seems to be a problem with how zfs snapshots and restores from snapshots work. If someone is willing to put in the effort to come up with a suitable patch that works nicely and keeps track of zfs snapshots we're willing to merge this. However, there are no plans to do the work.
