### ISSUE TITLE
machined registration support

### ISSUE THREAD

**Issue by zabbal** [lxc/lxc#605]
Would be nice if each lxc container would register itself with systemd-machined automatically if it's available. It has stable dbus interface described at https://wiki.freedesktop.org/www/Software/systemd/machined/

This would help to improve interoperability and makes integration with host smoother and better.

**Comment by stgraber** [comment]
Hi,

We're not necessarily opposed to supporting this but also won't be spending time doing so as it's providing little to no added value to our users.
When we considered this for LXC we also ran into the problem that machined only works for containers started by root and it doesn't track containers created by unprivileged users using user namespaces.

**Comment by brauner** [comment]
There currently seems no intention for anyone to work on this and we won't spend time on this. So closing.

**Comment by hallyn** [comment]
Hi,

what about just adding a 'community' tag or somesuch, to make it clear
that if community wants it, patches will be welcome?  Closing it seems
to send a bit of a different message.

**Comment by brauner** [comment]
@hallyn sure. If you can add new labels then please do so. We just have so many of these things sitting around.

**Comment by stgraber** [comment]
Been over 3 years and no such patches or new requests, let's just close this.

**Comment by srd424** [comment]
FWIW, it looks like this could be implemented with hooks - this example command seems to work:
```
dbus-send --print-reply --system --dest=org.freedesktop.machine1 \
  /org/freedesktop/machine1 org.freedesktop.machine1.Manager.RegisterMachine \
  string:newmachine array:byte:  string:someservice string:container uint32:123456 string:/
```
