### ISSUE TITLE
Alpine template is broken

### ISSUE THREAD

**Issue by rcarmo** [lxc/lxc#609]
On Ubuntu Trusty, with `lxc(-templates) 1.0.7`I get the following errors when trying to create an Alpine container:

<pre>
$ sudo lxc-create --name builder -t alpine
Determining the latest release... v3.2
Using static apk from http://wiki.alpinelinux.org/cgi-bin/dl.cgi/v3.2/main/x86_64
Downloading alpine-mirrors-3.1.3-r2.apk
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
Downloading apk-tools-static-2.6.3-r0.apk
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
Downloading alpine-keys-1.1-r0.apk
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub: OK
Verification Failure
Failed to download a valid static apk
lxc_container: lxccontainer.c: create_run_template: 1125 container creation template for builder failed
lxc_container: lxc_create.c: main: 271 Error creating container builder
</pre>

Using the current template on git tip yields identical results.

**Comment by xor-gate** [comment]
On Arch Linux host I also get the same error.

```
[root@shulgin jerry]# lxc-create --name tst02 -t alpine
which: no apk in (/usr/local/sbin:/usr/local/bin:/usr/bin:/data/files/scripts:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/sbin:/usr/bin:/sbin:/bin)
Determining the latest release... v3.2
Using static apk from http://wiki.alpinelinux.org/cgi-bin/dl.cgi/v3.2/main/x86_64
Downloading alpine-mirrors-3.1.3-r2.apk
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
Downloading apk-tools-static-2.6.3-r0.apk
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
Downloading alpine-keys-1.1-r0.apk
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub: OK
Verification Failure
Failed to download a valid static apk
lxc-create: lxccontainer.c: create_run_template: 1202 container creation template for tst02 failed
lxc-create: lxc_create.c: main: 274 Error creating container tst02
```

```
[root@shulgin jerry]# lxc-create --version
1.1.2
```

**Comment by rcarmo** [comment]
I've worked around this by commenting the signature check [here](https://github.com/lxc/lxc/blob/master/templates/lxc-alpine.in#L86-L87), but of course that is sub-optimal to say the least. 

My guess is that Alpine is signing the static APK binary with a different key (there is also a buildozer key in one of their packaging files), but it also seems that the current way the template is checking for a signing key is flawed - although I lack the time and the familiarity with the signing mechanism to point out exactly how...

**Comment by ncopa** [comment]
I suppose a better workaround would be to build and install apk-tools from sources, and add `apk` to $PATH.

**Comment by rcarmo** [comment]
Hmm. That seems like overkill. I don't expect LXC templates to force me to compile new binaries unless there is a very good reason for it...

I think that the new `apk` is simply signed with a different key, and that the logic for key selection is broken. If anyone has a 5-minute tutorial on how to check for signatures handy, I can figure out what key it is and maybe even attempt a patch.

**Comment by ncopa** [comment]
You cannot create arch linux containers without pacman or ubuntu/debian without dpkg (and debootstrap). Same with redhat/fedora/centos and rpm.

That said, this should be fixed. It seems that the default hash algorithm used with `openssl dgst -verify` changed. adding `-sha1` fixes it.

```diff
diff --git a/templates/lxc-alpine.in b/templates/lxc-alpine.in
index 963c42a..6dcc51b 100644
--- a/templates/lxc-alpine.in
+++ b/templates/lxc-alpine.in
@@ -83,7 +83,7 @@ get_static_apk () {
 
     # verify the static apk binary signature
     APK=$rootfs/sbin/apk.static
-    openssl dgst -verify $rootfs/etc/apk/keys/$keyname \
+    openssl dgst -sha1 -verify $rootfs/etc/apk/keys/$keyname \
         -signature "$APK.SIGN.RSA.$keyname" "$APK" || return 1
 
     if [ "$auto_repo_dir" ]; then
```
