### ISSUE TITLE
lxc-start: Invalid argument - pivot_root syscall failed

### ISSUE THREAD

**Issue by pva** [lxc/lxc#61]
Hi. I'm using 1.0.0.alpha1 although I've tried with 0.8.0 also and I'm unable to start container with the following error:
<pre>
lxc-start: Invalid argument - pivot_root syscall failed
lxc-start: failed to setup pivot root
lxc-start: failed to set rootfs for 'repos'
lxc-start: failed to setup the container
lxc-start: invalid sequence number 1. expected 2
lxc-start: failed to spawn 'repos'
</pre>

I've tried mount --make-private on all mount point I've thought of with no luck.
Also I've tried lxc.autodev = 1 also no luck and I guess this is relevant with systemd while this systems uses openrc as init system.

Container's conf file:
<pre>
lxc.arch = amd64
lxc.utsname = repos
lxc.rootfs = /virt/lxc/repos
</pre>

Distribution Gentoo. Same config works fine on another gentoo system. Although systems are completely different I think important differences are: 
1. init system: on laptop I'm using systemd while on server openrc
2. on server I have full system inside ram (system resides inside initramfs  and after boot root stays in RAM on rootfs)

  # cat /proc/self/mountinfo
<pre>
1 1 0:1 / / rw - rootfs rootfs rw
14 1 0:3 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
15 1 0:13 / /run rw,nosuid,nodev,relatime - tmpfs tmpfs rw,mode=755
16 1 0:5 / /dev rw,nosuid,relatime - devtmpfs udev rw,size=10240k,nr_inodes=4081011,mode=755
17 16 0:10 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=000
18 16 0:14 / /dev/shm rw,nosuid,nodev,noexec,relatime - tmpfs shm rw
19 1 0:15 / /sys rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
20 19 0:12 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime - securityfs securityfs rw
21 19 0:7 / /sys/kernel/debug rw,nosuid,nodev,noexec,relatime - debugfs debugfs rw
22 19 0:16 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime - tmpfs cgroup_root rw,size=10240k,mode=755
23 22 0:17 / /sys/fs/cgroup/openrc rw,nosuid,nodev,noexec,relatime - cgroup openrc rw,release_agent=/lib64/rc/sh/cgroup-release-agent.sh,name=openrc
24 22 0:18 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime - cgroup cpuset rw,cpuset,clone_children
25 22 0:19 / /sys/fs/cgroup/cpu rw,nosuid,nodev,noexec,relatime - cgroup cpu rw,cpu
26 22 0:20 / /sys/fs/cgroup/cpuacct rw,nosuid,nodev,noexec,relatime - cgroup cpuacct rw,cpuacct
27 22 0:21 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime - cgroup memory rw,memory
28 22 0:22 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime - cgroup devices rw,devices
29 22 0:23 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime - cgroup freezer rw,freezer
30 22 0:24 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime - cgroup blkio rw,blkio
31 22 0:25 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime - cgroup perf_event rw,perf_event
32 1 8:1 / /mnt/root rw,noatime - ext4 /dev/sda1 rw,data=ordered
33 1 254:1 / /virt rw,relatime - ext4 /dev/mapper/virt rw,data=ordered
</pre>

So any suggestions are welcome. I'll put debugging information in a moment.

**Comment by brauner** [comment]
Closing since this is supposedly fix. Please re-open if appropriate.
