### ISSUE TITLE
Update README about API freeze

### ISSUE THREAD

**Issue by alkino** [lxc/lxc#618]
Hi o/

Today, we can read

```
  lxc  is  still  in  development, so the command syntax and the API can
  change. The version 1.0.0 will be the frozen version.
```

I don't know what is the current state of API. But 1.0.0 is behind us. So if the API is fixed, it can be a good point to notice that.

Thanks,

**Comment by brauner** [comment]
This has been addressed by https://github.com/lxc/lxc/commit/0cb906e681c1b4672798d5330f33d6568215eb52 .
