### ISSUE TITLE
lxc-start segfaults when jemalloc is the heap allocator

### ISSUE THREAD

**Issue by TragicWarrior** [lxc/lxc#620]
When jemalloc is the system wide heap allocator on the host system, lxc-start will segfault.  This occurs with the "stock" install of LXC on Ubuntu 14.04.3 LTS 64-bit.  The jemalloc allocator is built from current stable source (version 3.6.0) and added system wide using /etc/ld.so.preload

**Comment by TragicWarrior** [comment]
Instructions for building jemalloc that I used are as follows:

1.  Obtain jemalloc 3.6.0 source from http://www.canonware.com/jemalloc/
2.  configure --prefix=/usr
3.  make
4.  make install

The defaults auto-detected by configure on this system are:

jemalloc version   : 3.6.0-0-g46c0af68bd248b04df75e4f92d5fb804c3d75340
library revision   : 1

CC                 : gcc
CPPFLAGS           :  -D_GNU_SOURCE -D_REENTRANT
CFLAGS             : -std=gnu99 -Wall -pipe -g3 -fvisibility=hidden -O3 -funroll-loops
LDFLAGS            : 
EXTRA_LDFLAGS      : 
LIBS               :  -lpthread
RPATH_EXTRA        : 

XSLTPROC           : false
XSLROOT            : 

PREFIX             : /usr
BINDIR             : /usr/bin
INCLUDEDIR         : /usr/include
LIBDIR             : /usr/lib
DATADIR            : /usr/share
MANDIR             : /usr/share/man

srcroot            : 
abs_srcroot        : /usr/src/jemalloc-3.6.0/
objroot            : 
abs_objroot        : /usr/src/jemalloc-3.6.0/

JEMALLOC_PREFIX    : 
JEMALLOC_PRIVATE_NAMESPACE
                   : je_
install_suffix     : 
autogen            : 0
experimental       : 1
cc-silence         : 0
debug              : 0
code-coverage      : 0
stats              : 1
prof               : 0
prof-libunwind     : 0
prof-libgcc        : 0
prof-gcc           : 0
tcache             : 1
fill               : 1
utrace             : 0
valgrind           : 0
xmalloc            : 0
mremap             : 0
munmap             : 0
dss                : 0
lazy_lock          : 0
tls                : 1

**Comment by brauner** [comment]
Is this issue still reproducible?

**Comment by TragicWarrior** [comment]
I'll check today.

**Comment by TragicWarrior** [comment]
Please advise which version I should use.

**Comment by brauner** [comment]
@TragicWarrior, for both, LXC and Jemalloc, the newest ones available.

**Comment by brauner** [comment]
This issue has been stale for a while. If you can reproduce with lxc and jemalloc in the latest version I would need at least a useable coredump or the stacktrace from the crash to further debug this. If this is still an issue for you, please re-open with the requested information. Thanks!
