### ISSUE TITLE
Starting centos 7 takes a really long time on Ubuntu 14.04.3 LTS host

### ISSUE THREAD

**Issue by TragicWarrior** [lxc/lxc#622]
After first figuring out why centos 7 threw a segv at startup, it took well over 10 minutes for the OS to reach login.  After reviewing the git commits here:

https://github.com/lxc/lxc/commit/a4aed378f802ad9caf74ee1c20dc74a6f9d7ca17

I realized that there was probably disparity between the current templates and this code change.  After I removed the drop caps for setfcap and setpcap, the system starts very fast as expected.

**Comment by fanyeren** [comment]
systemd-journald/systemd-logind  need cap_setfcap and cap_setpcap

**Comment by brauner** [comment]
This is fixed in newer versions of the template.
