### ISSUE TITLE
lxc-top: add iops column(s)

### ISSUE THREAD

**Issue by borutmrak** [lxc/lxc#624]
As is, the BlkIO Total is not really useful to find out which containers are using how much I/O currently, which top-like utility should do.

It would be great if lxc-top could show which containers are using most IO, (write/read/both iops separately, per second since last refresh as well as total since container start).

Current BlkIO Total (bytes) from container start would also benefit from per second display option.

I guess all those columns are not relevant for everybody so they should be configurable and not all enabled by default.

**Comment by brauner** [comment]
We'd certainly merge a PR that implements this behavior.

**Comment by 0x0916** [comment]
Does anyone working on this issue? if no, I would like to

**Comment by brauner** [comment]
No, no one is so far. If you want I can assign you this. But there's obviously no pressure here.

**Comment by 0x0916** [comment]
ok

**Comment by brauner** [comment]
What, you want it assigned or not? :)

**Comment by brauner** [comment]
Doesn't seem possible right now but feel like it has been assigned to you. :)

**Comment by brauner** [comment]
Support for this has been added afaik.
