### ISSUE TITLE
lxc at hetzner with additional ip's doesn't work

### ISSUE THREAD

**Issue by No1zzz** [lxc/lxc#635]
Hello,some one get working lxc on ex-40 server with additional network?
I can ping lxc public ip from host,but can't from other place's.

**Comment by No1zzz** [comment]
Lxc not working at hetzner?

**Comment by MSahl** [comment]
Hello No1zzz

Which operating system did you use? (fedora, debian,ubuntu,OpenSUSE)
How did you setup the Network Bridge ?

Can you also post the output of:
root # brctl show 

Best regards
MSahl

**Comment by No1zzz** [comment]
Hello,i using ubuntu

**Comment by hallyn** [comment]
fwiw I use lxc with no problems on an ex-60.  But what do you mean by "ping lxc public ip".  You'll need to give detailed network configuration for your host and containers.

**Comment by No1zzz** [comment]
brctl show
bridge name	bridge id		STP enabled	interfaces
br0		8000.d43d7eece904	no		eth0
							vethRCLFMA

**Comment by No1zzz** [comment]
I have subnet 136.243.211.96/29 - but seems that doesn't work at all.
lxc-ls -f
NAME             STATE    IPV4            IPV6  AUTOSTART
---------------------------------------------------------
test_host  RUNNING  136.243.211.97  -     YES

**Comment by No1zzz** [comment]
iface br0 inet static
  bridge_ports eth0
in my /etc/network/interface

**Comment by MSahl** [comment]
Hello No1zzz

Can you please check if ip_forward is enabled.
root # sysctl -a | grep ip_forward
net.ipv4.ip_forward = 1

If that is not helping, try:
https://www.sysorchestra.com/2014/11/08/hetzner-root-server-with-kvm-ipv4-and-ipv6-networking/

@hallyn Can you please tell us how you configured your network of the host and lxc (guest) at your ex-60?

**Comment by No1zzz** [comment]
net.ipv4.ip_forward = 1

**Comment by No1zzz** [comment]
All working now,TY.
