### ISSUE TITLE
ZFS: 'lxc-clone --snapshot' creates but does not use snapshot

### ISSUE THREAD

**Issue by JohnPeacockMessageSystems** [lxc/lxc#637]
Tangentially related to the issue #401 and possibly #316, it is clear that lxc-clone is not doing the right thing on zfs:

```
$ sudo zfs list | fgrep jpeacock-plat1
lxc/lib/containers/jpeacock-plat1-6              503K  2.64T   330M  /var/lib/lxc/containers/jpeacock-plat1-6/rootfs
lxc/lib/containers/rh66-base@jpeacock-plat1-6       0      -   330M  -
```

As you can see, the zfs snapshot is created properly, but then lxc-clone just dupes the rh66-base container for the new rootfs.  When I use `lxc-destroy -f`on that instance, the ZFS snapshot is left behind.

**Comment by brauner** [comment]
The storage drivers have been reworked substantially. If you can still reproduce with current master, please re-open.
