### ISSUE TITLE
Latest arch template looks for pacman on host OS before container creation

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxc#642]
https://github.com/lxc/lxc/blob/master/templates/lxc-alpine.in produces following error when attempting to create an Arch container on Ubuntu latest stable.

net4-dev# lxc-create --version
1.1.2

net4-dev# uname -a
Linux net4.bizcooker.com 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

net4-dev# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.04
Release:    15.04
Codename:   vivid

New template named lxc-arch-latest

net4-dev# lxc-create -t archlinux-latest -n arch-base
/usr/share/lxc/templates/lxc-archlinux-latest: line 53: pacman: command not found
'pacman' command is missing, refer to wiki.archlinux.org for information about installing pacman
lxc_container: lxccontainer.c: create_run_template: 1108 container creation template for arch-base failed
lxc_container: lxc_create.c: main: 274 Error creating container arch-basenet4-dev# lxc-create -t archlinux-latest -n arch-base
/usr/share/lxc/templates/lxc-archlinux-latest: line 53: pacman: command not found
'pacman' command is missing, refer to wiki.archlinux.org for information about installing pacman
lxc_container: lxccontainer.c: create_run_template: 1108 container creation template for arch-base failed
lxc_container: lxc_create.c: main: 274 Error creating container arch-base

**Comment by davidfavor** [comment]
Looking deeper into this template it appears a good bit of logic to bootstrap the created container requires being moved into post processing of container (after it's created).

**Comment by asbachb** [comment]
I ran into the same issue. Are there any workarounds?

**Comment by davidfavor** [comment]
The template must be fixed.

Anyone have an ETA on when this might be fixed?

**Comment by stgraber** [comment]
We don't have a maintainer for that template so basically if you want it fixed, sent a pull request or a patch.

**Comment by brauner** [comment]
I'm not completely following the bug actually. If you want to use the template but don't have the necessary bootstrap tool installed then it is expected to fail, no. Also the template you linked is Alpine but you're talking about Archlinux. I suspect this was an accident.

**Comment by brauner** [comment]
I believe this is fixed. If this is still an issue, please re-open. Also note, that there'll be a new way to create images using distrobuilder. @monstermunchkin is working on this in https://github.com/lxc/distrobuilder .
