### ISSUE TITLE
Alpine container networking appears broken

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxc#647]
Using Ubuntu Vivid + LXC-1.1.2 + latest GitHub Alpine template.

1) Creating container works as of latest fixes...

lxc-create -t alpine-latest -n dev-alpine -- --release v3.2

2) Starting container works...

lxc-start -n dev-alpine -d

3) And there's no IP address associated with container.

net4-dev# lxc-ll
NAME             STATE    IPV4        IPV6  GROUPS  AUTOSTART  
-------------------------------------------------------------
dev-alpine       RUNNING  -           -     -       NO         
dev-vivid  RUNNING  10.0.3.128  -     -       NO

Looking at packages installed during creation, there are no dhcp packages installed.

Selecting mirror http://dl-5.alpinelinux.org/alpine/v3.2/main
fetch http://dl-5.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
(1/15) Installing musl (1.1.9-r5)
(2/15) Installing busybox (1.23.2-r0)
Executing busybox-1.23.2-r0.post-install
(3/15) Installing alpine-baselayout (2.3.2-r0)
Executing alpine-baselayout-2.3.2-r0.pre-install
Executing alpine-baselayout-2.3.2-r0.post-install
(4/15) Installing openrc (0.15.1-r3)
Executing openrc-0.15.1-r3.post-install
(5/15) Installing alpine-conf (3.2.1-r6)
(6/15) Installing zlib (1.2.8-r1)
(7/15) Installing libcrypto1.0 (1.0.2d-r0)
(8/15) Installing libssl1.0 (1.0.2d-r0)
(9/15) Installing apk-tools (2.6.3-r0)
(10/15) Installing busybox-initscripts (2.2-r27)
Executing busybox-initscripts-2.2-r27.post-install
(11/15) Installing scanelf (0.9.1-r0)
(12/15) Installing musl-utils (1.1.9-r5)
(13/15) Installing libc-utils (0.7-r0)
(14/15) Installing alpine-keys (1.1-r0)
(15/15) Installing alpine-base (3.2.3-r0)
Executing busybox-1.23.2-r0.trigger
OK: 6 MiB in 15 packages
Setting up /etc/inittab
Setting up device nodes

I believe the fix here is to...

1) install the correct dhcp package

2) after container is created, run these commands inside container:

rc-update add networking default
rc-service networking start or /etc/init.d/networking start

**Comment by davidfavor** [comment]
Any LXC gurus out there know how to setup Alpine networking, so it works?

**Comment by davidfavor** [comment]
https://bugs.alpinelinux.org/issues/4617 discusses several possible fixes, including a change I made which seems to work.

What's required here is an LXC expert to fix the Alpine Container correctly.

Thanks.

**Comment by davidfavor** [comment]
Still broken in LXC-1.1.5 templates.

**Comment by brauner** [comment]
Should be fixed on current lxc master with the new alpine template.
