### ISSUE TITLE
user namespace inside container

### ISSUE THREAD

**Issue by sowndaryak** [lxc/lxc#648]
how to run container with user namespace in ubuntu and how to map that to host uid with commands ?
can anyone help me out?

**Comment by alkino** [comment]
RTFM maybe: https://linuxcontainers.org/lxc/getting-started/

**Comment by sowndaryak** [comment]
But the things is how to check that it has been mapped to host?

**Comment by jirutka** [comment]
LXC has nothing to do with Docker.

**Comment by sowndaryak** [comment]
how do i create user namesapce in lxc containers..? can any one help out with  commands in steps?

**Comment by jirutka** [comment]
Well, you need lxc >=1.1 compiled with grmanager. Then it should be possible to manage cgroups from container. I’ve never tried that although, so can’t provide exact steps.

**Comment by sowndaryak** [comment]
i have installed lxc in ubuntu system, so i need the steps to just to map uid of container to host.

**Comment by sowndaryak** [comment]
Thank u jitutka

**Comment by sowndaryak** [comment]
docker run --lxc-conf="lxc.uid_map=u 0 100000 65536" -d  -ti ubuntu /bin/bash can i use this to run containers to utilize this uid namespace?

**Comment by stgraber** [comment]
This would most likely fail. You're not providing a gid map and docker doesn't know about user namespaces so won't be remapping the filesystem for you, which means that every file will be owned with -1/-1 and you won't have any access to them (except for world readable files).

**Comment by brauner** [comment]
Configuring low-level lxc tools is something best left to more experienced users that want a very fine-grained control over a bunch of options. It seems like you're not that experienced yet with containers so I suggest you take a look at our LXD package in Ubuntu which abstracts away a lot of the complexity.
