### ISSUE TITLE
Request for instructions to convert template.in files into templates

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxc#650]
I've tried all sorts of auto tool command line incantations + none have worked.

Can someone let me know how to do this or point me to where this is covered in docs.

Thanks.

**Comment by stgraber** [comment]
.in files are processed by autoconf.

Just run ./autogen.sh and ./configure to have them generated.

Building LXC is covered in README.

**Comment by davidfavor** [comment]
St���������������������������������������� wrote:
> .in files are processed by autoconf.
> 
> Just run ./autogen.sh and ./configure to have them generated.
> 
> Building LXC is covered in README.
> 
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/lxc/lxc/issues/650#issuecomment-138004832>.
> 

Oh right. I have to use autogen.sh out of the project.

I'm asleep at the wheel.

Thanks.
