### ISSUE TITLE
Creating unpriviledged containers as root fails "mkdir: cannot create directory ‘/usr/local/var/cache/lxc//download’: Permission denied"

### ISSUE THREAD

**Issue by jhenninger** [lxc/lxc#652]
When following the [instructions to create an unpriviledged container as root](https://linuxcontainers.org/lxc/getting-started/#creating-unprivileged-containers-as-root), lxc-create fails with "mkdir: cannot create directory ‘/usr/local/var/cache/lxc//download’: Permission denied". 

I'm using the 1.0.x branch (lxc-1.0.7-178-g3a88a8c) on Debian Sid.

```
root@hostname:~# grep -H root /etc/sub{uid,gid}
/etc/subuid:root:820896:65536
/etc/subgid:root:820896:65536
```

```
root@hostname:~# cat /usr/local/etc/lxc/default.conf
lxc.network.type = empty
lxc.id_map = u 0 820896 65536
lxc.id_map = g 0 820896 65536
```

```
root@hostname:~# lxc-create -t download -n test -- -d debian -r wheezy -a amd64
Setting up the GPG keyring
Downloading the image index
Downloading the rootfs
Downloading the metadata
mkdir: cannot create directory ‘/usr/local/var/cache/lxc//download’: Permission denied
lxc_container: lxccontainer.c: create_run_template: 1080 container creation template for test failed
lxc_container: lxc_create.c: main: 265 Error creating container test
```

```
root@hostname:~# ls -la /usr/local/var/cache/lxc/
total 8
drwxr-sr-x 2 root staff 4096 Sep  8 16:16 .
drwxr-sr-x 3 root staff 4096 Sep  8 16:16 ..
```

Container creation only succeeds for priviledged containers or when there is a cached image available:

```
# disable uid mappings
root@hostname:~# mv /usr/local/etc/lxc/default.conf /usr/local/etc/lxc/default.conf.disabled
```

```
# create priviledged container
root@hostname:~# lxc-create -t download -n test -- -d debian -r wheezy -a amd64
Setting up the GPG keyring
Downloading the image index
Downloading the rootfs
Downloading the metadata
The image cache is now ready
Unpacking the rootfs

---
You just created a Debian container (release=wheezy, arch=amd64, variant=default)

To enable sshd, run: apt-get install openssh-server

For security reason, container images ship without user accounts
and without a root password.

Use lxc-attach or chroot directly into the rootfs to set a root password
or create user accounts.
```

```
# enable uid mappings
root@hostname:~# mv /usr/local/etc/lxc/default.conf.disabled /usr/local/etc/lxc/default.conf
```

```
# create unpriviledged container
root@hostname:~# lxc-create -t download -n test2 -- -d debian -r wheezy -a amd64
Using image from local cache
Unpacking the rootfs

---
You just created a Debian container (release=wheezy, arch=amd64, variant=default)

To enable sshd, run: apt-get install openssh-server

For security reason, container images ship without user accounts
and without a root password.

Use lxc-attach or chroot directly into the rootfs to set a root password
or create user accounts.
```

**Comment by subodh-dharma** [comment]
@jhenninger Did you got any resolution on this? I am running into same error.

**Comment by jhenninger** [comment]
@subodh-dharma Back then I worked around this problem by creating a temporary privileged container if the creation of an unprivileged one fails. This makes sure that the image in question is in the cache. The privileged container can then be deleted and an unprivileged one can be created.

It's a rather ugly workaround but it was ok for my use case.

**Comment by hallyn** [comment]
fwiw i cannot recreate this with the default lxc 1.0.3 on
ubuntu 14.04.  Since uidmap is not available on debian sid
(and since your lxc is using /usr/local/var/lib) I assume
you built both shadow and lxc.  Though I can't imagine what
git tag you used that would cause this.  As far as I can
recall lxc has always mapped the caller's euid into the
namespace in which the template runs, so this shouldn't
happen.

Happily as there's a workaround we can leave this at low
priority.  If you feel like debugging it, i would recommend
adding a sleep right before the offending mkdir_p call and
looking at the /proc/pid/uid_map and /proc/pid/status.

**Comment by jhenninger** [comment]
@hallyn Back when I had this issue I built LXC but not shadow. I mentioned the LXC version in the first post ([lxc-1.0.7-178-g3a88a8c](../commits/3a88a8c)). uidmap is available on Debian Sid via the [uidmap package](https://packages.debian.org/sid/uidmap).

Creating an unpriviledged container as root works just fine for me now though when using LXC 2.0.7 from the Debian Sid repos.

**Comment by brauner** [comment]
Seems that this issue is been fixed. Closing.
