### ISSUE TITLE
udevadm trigger corrupts the container

### ISSUE THREAD

**Issue by hallyn** [lxc/lxc#656]
I'm creating an issue to track information from the mailing list.

Christoph Mathys reported on lxc-users that with a PREEMPT_RT_FULL kernel,
in particular:

Upstream Kernel source is here:
https://git.kernel.org/cgit/linux/kernel/git/rt/linux-stable-rt.git/
We are using the code from tag: v3.12.33-rt47
The config we are using atm:
http://pastebin.com/APamRdtp

containers using lxc.autodev=1 are broken when udevadm trigger is run on
the host.

**Comment by brauner** [comment]
There's seems to have been no interest in diggin deeper into this and it is unclear whether newer kernel versions still suffer form that problem. If this is something we need to look into from lxc's side please re-open.
