### ISSUE TITLE
lxc.autostart fails when called non-interactively

### ISSUE THREAD

**Issue by morremeyer** [lxc/lxc#657]
Hey everyone,

after a few days of trying this and that, I'm finally giving up. Maybe it's a bug or I'm just plain stupid and don't see my own error.
### Following problem arose:

My **unprivileged** containers that have **lxc.autostart = 1** set won't start when my system does. 
### I've verified the following:
- _lxc.autostart = 1_ is written and set correctly (verified by _lxc-ls -f_ showing _yes_ for the _autostart_
- I've also added the containers to the **onboot** group while _lxc.autostart = 1_ was set
- _lxc-autostart_ is executed during boot, I get local mail each time the system reboots. This mail just says **Error starting container: [containername]** for all containers
- _lxc-autostart_ works without any problem when called interactively from an SSH session

I don't get any more log info or error messages and I'm not aware of a possibility to increase the loglevel of the autostart routine.

Everything else works fine.

@tarruda has written [a script that simulates an SSH session](https://gist.github.com/tarruda/2aea9107f04d8b8d8dbf) which apparently works as a workaround, but I'm starting to think that it is a bug that such workaround is needed.
### System Configuration
- Ubuntu 14.04.2, current patchlevel
- nothing more than _lxc_, _unattended-upgrades_, _openssh-server_ and _qemu-kvm_ installed

If anyone has a hint, please let me know. Thanks a lot!

**Comment by stgraber** [comment]
Hmm, I've never ran into any such problem here.

Can you paste the configuration of one of the affected containers?

**Comment by tarruda** [comment]
> Can you paste the configuration of one of the affected containers?

On a Ubuntu 14.04.3 VPS I have this in every unprivileged container, but I also remember experiening this in a Ubuntu 15.04 desktop. Here's the configuration for one of them(they are all very similar):

```
# Template used to create this container: /usr/share/lxc/templates/lxc-download
# Parameters passed to the template: -d ubuntu -r trusty -a amd64
# For additional config options, please look at lxc.container.conf(5)

# Distribution configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.include = /usr/share/lxc/config/ubuntu.userns.conf
lxc.arch = x86_64

# Container specific configuration
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
lxc.rootfs = /lxc/.local/share/lxc/uproxy/rootfs
lxc.start.auto = 1
lxc.start.delay = 5
lxc.utsname = uproxy

# Network configuration
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = lxcbr0
lxc.network.hwaddr = 00:16:3e:68:c7:d4
```

You can see the error by executing `lxc-autostart` outside a login environment(such as a user cron script). When I first ran in to this error, I remember reading somewhere(can't remember exactly, possibly a mailing list) that this was about lxc-autostart expecting a certain environment(related to XDG environment variables) that was not necessarily available outside interactive/login shells. Just speculating though.

**Comment by tarruda** [comment]
Here are some links(one of them from your blog):

https://www.stgraber.org/2014/01/17/lxc-1-0-unprivileged-containers/#comment-183371  (In this thread someone suggests unsetting certain XDG environment variables as a workaround)
http://serverfault.com/questions/620709/how-to-auto-start-unprivileged-lxc-containers
https://lists.linuxcontainers.org/pipermail/lxc-users/2014-May/006815.html

**Comment by mauricemeyer** [comment]
My configuration looks nearly exactly as yours, @tarruda, except that I'm using a bridge on the host as network interface.

```
# Distribution configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.include = /usr/share/lxc/config/ubuntu.userns.conf
lxc.arch = x86_64

# Container specific configuration
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
lxc.rootfs = /home/maurice/.local/share/lxc/intra-dnsmasq/rootfs
lxc.utsname = intra-dnsmasq

# Network configuration
lxc.network.type = veth
lxc.network.link = br1
lxc.network.hwaddr = 22:01:95:19:01:02

# Autostart
lxc.start.auto = 1
lxc.start.order = 1
lxc.start.delay = 5
```
I tried the configuration with your script, @tarruda, now it doesn't report any errors to my mail (/var/mail/username) but still doesn't start the containers.

**Comment by mauricemeyer** [comment]
Update: I tweaked on some setting, all with no effect, but I also found out why your script was not working for me (@tarruda), I fixed it and now it does its job. Thank you very much!

**Comment by mcortinas** [comment]
maybe, you selinux o arrmor deny the autoexec-start on LXC...
you can look for in selinux logs....

**Comment by jseadragon** [comment]
Any word on if this is an actual issue, or something that will be looked at? I've also encountered this issue on several machines when trying to use `lxc.autostart` with unprivileged containers. I can provide details if that would be helpful.

**Comment by brauner** [comment]
I'd like to see the logs of one of those failing containers, please. :)
