### ISSUE TITLE
Ephemeral containers die on reboot

### ISSUE THREAD

**Issue by Ziris85** [lxc/lxc#658]
I've been toying around with ephemeral containers (since I really like the concept, and it would work very well for something I'm working on). However, I notice that, when a reboot is done from within the container, instead of simply rebooting and staying live, the container dies as though it was told to shutdown.

It's worth mentioning that the ephemeral functionality in lxd works as (at least I) would expect - the container remains active after a reboot of the container, and only disappears upon actual shutdown.

Since these two projects seem to be extremely similar, I thought I might bring this incongruity of function to your attention. Since lxd seems to work as I expect it to, I'll just roll with that for now (I'm honestly struggling to find a difference, functionally).

I tried, and got the same results, with ephemeral containers on versions 1.0.3 (version shipped in Ubuntu repos), as well as the latest stable build, 1.1.3. All this using Ubuntu 14.04.3.

If you would like any more information, just let me know.

Thanks.

**Comment by brauner** [comment]
Hi, I have a series of patches staged for merging that reimplements
ephemeral containers in lxc. Once the recent patches are merged I plan on
implementing reboot-survival for ephemeral containers. I hope this will
happen soon so I can go on.

Christian

**Comment by Ziris85** [comment]
Awesome to hear! Definitely looking forward to that, since ephemeral containers from lxc seem to boot up significantly faster than ephemeral containers from lxd (seems like they approach the creation of ephemeral containers differently).

**Comment by brauner** [comment]
This is now already fixed for lxc-start-ephemeral on current master branch (#7111ed6).

**Comment by Ziris85** [comment]
Really excited to check this out when it gets resolved. However, I just tried the latest stable build (`1.1.4`), and also the latest development build (`1.1.3+stable~20151007-2301-0ubuntu1~trusty`, from [here](https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/lxc-git-stable-1.1)), and both continued to have the problem with their ephemeral containers. Is this, for now, only available by downloading and compiling the source from the master branch?

**Comment by brauner** [comment]
I can confirm this. I know the source of the problem but this requires a more substantial rewrite of `lxc-start-ephemeral` and I would like to put this on hold until I have finished `lxc-copy` in a satisfactory way. :)

**Comment by brauner** [comment]
@Ziris85 `lxc-copy` is now in master.

**Comment by Ziris85** [comment]
I'm sorry, I meant to comment back to you earlier. I tested it out and it works great! I like the idea of pulling this functionality into an existing binary (`lxc-copy`), rather than having a separate one (`lxc-start-ephemeral`).

Well done, and thanks!
