### ISSUE TITLE
error_string field not used

### ISSUE THREAD

**Issue by zoggy** [lxc/lxc#659]
Hello,

Documentation at https://github.com/lxc/lxc/blob/master/src/lxc/lxccontainer.h#L103 claims that the `error_string` field of `lxc_container` contains a "human-readable string  representing last error", but it is never set, even in case of error.

Same for `error_num` excepted in `lxc_start.c` .

**Comment by hallyn** [comment]
Yup...  we've never properly implemented that.

**Comment by brauner** [comment]
Support for `error_num` at least has been added.

**Comment by libre-man** [comment]
It would be nice if there was some sort of comment explaining that the field is unused at the moment.
