### ISSUE TITLE
pam_loginuid.so problems - unprivileged container

### ISSUE THREAD

**Issue by lenisko** [lxc/lxc#661]
Hello there.

Just wanted to say, if someone gonna have any problems with cron, and they are something like that:
```Sep 24 22:56:01 kitty CRON[1202]: Cannot make/remove an entry for the specified session```

module __pam_loginuid.so__ should be commented out or set to optional inside /etc/pam.d/cron

Same goes for sshd

**Comment by matlink** [comment]
Why does this error happen?

**Comment by qris** [comment]
@matlink It seems that LXC makes `/proc/<pid>/loginuid` read-only (it's not fully supported in containers yet) but `pam_loginuid.so` tries to write to it, which fails:

> The previous patch to support user namespaces works fine with containers
> that are started from a desktop/terminal session but fails when dealing
> with containers that were started from a remote session such as ssh.
> 
> I haven't looked at the exact reason for that in the kernel but on the
> userspace side of things, the difference is that containers started from
> an ssh session will happily let pam open /proc/self/loginuid read-write,
> will let it read its content but will then fail with EPERM when trying
> to write to it. 

Ubuntu applied [a patch to fix this issue](https://git.fedorahosted.org/cgit/linux-pam.git/commit/modules/pam_loginuid/pam_loginuid.c?id=2e62d5aea3f5ac267cfa54f0ea1f8c07ac85a95a) in Wily (15.10) but it [didn't make it into Debian Jessie](https://lists.debian.org/debian-ssh/2016/04/msg00022.html), so Jessie guests have problems with `sshd` in LXC containers. Probably other distributions are affected too.

The symptoms are errors like this in the logs:

```
sshd[422]: pam_loginuid(sshd:session): set_loginuid failed
sshd[422]: pam_unix(sshd:session): session opened for user ??? by (uid=0)
sshd[422]: error: PAM: pam_open_session(): Cannot make/remove an entry for the specified session
```

and the user is immediately disconnected after entering their password.

I also found a [patch in LXC](https://lists.linuxcontainers.org/pipermail/lxc-devel/2013-November/006278.html) to disable `pam_loginuid.so` when creating new containers. The comments in that patch say:

> This is a known problem and documented in RedHat bugzilla as relating
> to a problem with auditing enabled.  This prevents an error in
> the container "Cannot make/remove an entry for the specified session"

Despite this comment, I did not find any references in Redhat Bugzilla, but I did find [CentOS bug 2191](https://bugs.centos.org/view.php?id=2191) and [Debian bug 726661](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=726661).

**Comment by stgraber** [comment]
Distros really should be including the upstream PAM fix...

As for LXC making loginuid read-only, that's not true. What's happening is that loginuid is a real-root owned file, so only root on the host can change it, root in a user namespace isn't allowed to do so by the kernel.

**Comment by stgraber** [comment]
Having LXC modify the PAM config isn't the right way to deal with this as the PAM config may then be reverted during package updates. It was an acceptable workaround to improve things a bit while waiting for distros to pick up the fix.

The real fix is to ask your distro to include the bugfix I sent upstream over 2 years ago.

**Comment by evgeni** [comment]
FWIW, this has been fixed in Debian recently.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=726661

**Comment by brauner** [comment]
Thansk @evgeni.
