### ISSUE TITLE
run nested/combined commands with lxc.attach

### ISSUE THREAD

**Issue by tbleiker** [lxc/lxc#671]
Is it possible to run nested and/or combined commands like

```
# lxc-attach -n test -- ls -la / | grep var
```

in python? It works perfectly with the lxc-attach command. However, I cannot manage to get such commands to work in python.

```
>>> c.attach_wait(lxc.attach_run_command, ['ls', '-la', '/', '|', 'grep', 'var' ])
ls: cannot access |: No such file or directory
ls: cannot access grep: No such file or directory
ls: cannot access var: No such file or directory
```

**Comment by habnabit** [comment]
If you want to involve the shell, involve it explicitly:

```
c.attach_wait(lxc.attach_run_command, ['sh', '-c', 'ls -la / | grep var'])
```

Usually trivial pipelining like that can be better implemented in pure python though.
