### ISSUE TITLE
How to install Centos lxc

### ISSUE THREAD

**Issue by alajangi** [lxc/lxc#677]
Hi,

I am cloned this git with

# git clone https://github.com/lxc/lxc.git

and ran

# ./autogen.sh && ./configure && make && sudo make install

I am stuck here, what to do next, how to create centos lxc ?

when I run

# lxc-create -t lxc-centos -n my-container

# lxc command not found

# yum install lxc
# lxc-create -t lxc-centos -n my-container

the error is 
lxc-create: error while loading shared libraries: liblxc.so.1: cannot open shared object file: No such file or directory

what wrong i did ? how to rid from this error ?

please help me...

Thanks,
Kishore.

**Comment by gokul-uf** [comment]
Hi Kishore,
you have two installs of lxc. One through source and the other through `yum`.
Uninstall the second one and the add the path where the version built through source to the `PATH` environment variable

**Comment by Kentoseth** [comment]
@stgraber:

I think this issue can be closed as well.

@gokul-uf provided a good solution and extra resources/tutorial.
