### ISSUE TITLE
lxc-start:failed to mount rootfs

### ISSUE THREAD

**Issue by z00189512** [lxc/lxc#679]
1.my host  rootfs is ramfs。
rootfs on / type rootfs (rw)
2.lxc conf  :
lxc.console = none
lxc.utsname = lxc-container
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = virbr0
lxc.network.name = eth0
lxc.rootfs = /container/lxc-rootfs/
3.After i change  the  /container/lxc-rootfs/ to ext2 filesystem,the error is:
lxc-start:Invalid argument - piviot_root syscall failed.

Anyboby has a idea about this problem?

**Comment by hallyn** [comment]
Which version of lxc are you on?  If a newer version, I'd be curious whether going back to an older version like 1.0.1 fixes it.

There is code in lxc specifically to (try to) handle a ramfs rootfs, however that is a hard environment to reproduce to actually debug our code.

The relevant code is in src/lxc/conf.c:prepare_ramfs_rootfs().  Actually looking at it right now I don't see how it is supposed to work (unlike the 1.0.1 version which seems pretty clear).

What sort of system do you have?

**Comment by brauner** [comment]
Closing due to unresponsiveness. If the problem still persists, please re-open.
