### ISSUE TITLE
Get lxc-ls to also list containers from list_running_containers

### ISSUE THREAD

**Issue by erkules** [lxc/lxc#68]
# on 12.04 / 3.8.0-31-generic / lxc version: 0.7.5

terminal1 # lxc-execute -n seeme /bin/bash
terminal2 # lxc-list| grep seeme
  seeme
###### 
# on 13.10 / 3.11.0-12-generic / lxc version: 1.0.0.alpha1

terminal1 # lxc-execute -n seeme /bin/bash
terminal2 # lxc-ls| grep seeme
terminal2 # 
But the container exists:
terminal1 # lxc-info  -n seeme
state:   RUNNING
pid:      5036
terminal1 # lxc-stop -n seeme

**Comment by coolavibv** [comment]
I am also having same problem. I upgraded lxc 1.0.8 to lxc 2.0.0 on ubuntu 14.04 using sudo apt-get upgrade. As you have given patch, but now there is no src/python-lxc/lxc.c file to add this patch. Can you please help me with this.

**Comment by coolavibv** [comment]
I have sorted out this problem. This is due to apt-get upgrade. Do not  upgrade the lxc once you have installed it on your host.
