### ISSUE TITLE
small improvement: replace grep | awk | grep | sort .. echo | awk with single awk

### ISSUE THREAD

**Issue by smoser** [lxc/lxc#681]
hallyn's suggested fix for bug https://launchpad.net/bugs/1509414
included:

```
+    # find an open 10.0.a.0 network
+    conflict=0
+    for l in `ip addr show | grep "inet\>" |awk '{ print $2 }' | grep '^10\.0\.' | sort -n`; do
+        j=`echo $l | awk -F. '{ print $3 }'`
+        if [ "$LXC_ADDR" = "10.0.$j.1" ]; then
+            conflict=1
+        fi
+    done
```

That 'ip addr show'.... that can probably be done as 

```
ip addr show | awk '$1 == "inet" && $2 ~ netmatch { split($2, a, "."); print a[3]}' netmatch=10[.]0[.]
```

That gives you a list of all N for 10.0.N.\* networks.
The loop then:

```
ten_dot_zero_nets=`ip addr show | awk '$1 == "inet" && $2 ~ netmatch { split($2, a, "."); print a[3]}' netmatch=10[.]0[.]`
for j in ${ten_dot_zero_nets}; do
    if [ "$LXC_ADDR" = "10.0.$j.1" ]; then
        conflict=1
    fi
done
```

**Comment by hallyn** [comment]
Been playing with this and it seems to work fine in both bash and dash.

**Comment by hallyn** [comment]
Note though that that script does not exist here (afaics), it's only in the Ubuntu packaging.

**Comment by brauner** [comment]
Since the script doesn't exist in LXC this issue should be reopened against the ubuntu package if this is still important.
