### ISSUE TITLE
lxc-destroy: strange bug when used `find`

### ISSUE THREAD

**Issue by gotlium** [lxc/lxc#682]
root@ldl-master:/vagrant# find /var/lib/lxcsnaps/god/ -type d -name 'snap*'| tac | xargs -I 1 lxc-snapshot -n god -d 1
    lxc_container: lxccontainer.c: lxcapi_snapshot_destroy: 3177 Could not find snapshot /var/lib/lxcsnaps/god/snap0
    lxc_container: lxc_snapshot.c: do_destroy_snapshots: 118 Error destroying snapshot /var/lib/lxcsnaps/god/snap0

    root@ldl-master:/vagrant# find /var/lib/lxcsnaps/god/ -type d -name 'snap*' -exec lxc-snapshot -n god -d {} \;
    lxc_container: lxccontainer.c: lxcapi_snapshot_destroy: 3177 Could not find snapshot /var/lib/lxcsnaps/god/snap0
    lxc_container: lxc_snapshot.c: do_destroy_snapshots: 118 Error destroying snapshot /var/lib/lxcsnaps/god/snap0

    root@ldl-master:/vagrant# find /var/lib/lxcsnaps/god/ -type d -name 'snap*' -exec rm -rf {} \;
    find: `/var/lib/lxcsnaps/god/snap0': No such file or directory

    # without problems
    root@ldl-master:/vagrant# find /var/lib/lxcsnaps/god/ -type d -name 'snap*'| tac | xargs -I 1 bash -c 'lxc-snapshot -n god -d 1'
    root@ldl-master:/vagrant# 

PS - When I use lvm, all snapshot will be removed automatically, but when I use overlayfs/zfs all snapshots not removed automatically.

**Comment by brauner** [comment]
This should be fixed in current versions of `LXC`.
