### ISSUE TITLE
[lxc-create] Error creating container

### ISSUE THREAD

**Issue by srkunze** [lxc/lxc#684]
What am I missing here?

```
root@host:~# lxc-create -l DEBUG -n test-lxc
lxc_container: lxc_create.c: main: 271 Error creating container test-lxc
```

I am working through: https://wiki.ubuntuusers.de/LXC -- installation works, lxc-execute works, but then lxc-create fails.

**Comment by srkunze** [comment]
Alright. I think I managed to get it running by reading the man pages. It says that "-t" is not optional.

Would be great if the docs and "-h" would reflect that somehow.

**Comment by hallyn** [comment]
On Tue, Nov 03, 2015 at 12:25:02PM -0800, Sven R. Kunze wrote:
> Alright. I think I managed to get it running by reading the man pages. It says that "-t" is not optional.
> 
> Would be great if the docs and "-h" would reflect that somehow.

What version did you use?  I get a useful error message:

1 ✗ serge@sl ~ $ lxc-create -n xxx -l DEBUG
A template must be specified.

**Comment by srkunze** [comment]
@hallyn The output was generated by lxc 1.0. :) But I upgraded as suggested here: https://github.com/lxc/lxc/issues/685#issuecomment-153477325

Thanks. :)

**Comment by hallyn** [comment]
Perhaps stable-1.0 should get commit d3de16bb56b418884b41c50a4d15543129b5a564

**Comment by stgraber** [comment]
On Fri, Nov 06, 2015 at 09:53:28AM -0800, Serge Hallyn wrote:
> Perhaps stable-1.0 should get commit d3de16bb56b418884b41c50a4d15543129b5a564

It originally wasn't included as it was seen as a feature difference,
but given that things really don't quite work without it, I'll be
including it in the next release as a bugfix.

Stéphane

**Comment by srkunze** [comment]
@stgraber Excellent idea. I would consider it a documentation fix rather than a bugfix or a feature.

Thank you both for helping newbie here. :)
