### ISSUE TITLE
Warnings When Using a Standard Ubuntu Container

### ISSUE THREAD

**Issue by srkunze** [lxc/lxc#686]
Sorry for the stupid questions (I fear there will be more to come). What's wrong with those warnings/errors? They look dangerous but the command works.

```
lxc-test is not running
root@mexico:~# lxc-execute -n lxc-test /bin/echo hi
init.lxc.static: initutils.c: mount_fs: 36 failed to mount /proc : Device or resource busy
init.lxc.static: initutils.c: mount_fs: 36 failed to mount /dev/shm : No such file or directory
hi
```

**Comment by stgraber** [comment]
What are you expecting this command to do?

**Comment by stgraber** [comment]
It feels to me like you meant to use lxc-attach instead of lxc-execute there.

**Comment by srkunze** [comment]
Well, the command run perfectly fine. It echoes "hi" as intended. I am confused by the failures.

I expected no errors for a clean setup.

**Comment by stgraber** [comment]
lxc-execute doesn't run the command you're passing inside an existing container, instead it spawns that command as the PID 1 of a new container.

It's expected that the command in question be able to act as an init system, which echo clearly doesn't.

**Comment by srkunze** [comment]
Okay, I see. So, why does it echo "hi" then? To me that seems as if it would work.

**Comment by stgraber** [comment]
echo gets spawned as pid1 and still does its job which is to print stuff, it's just not doing the rest of the work it's supposed to do as pid1, signal handling, setting up network, mounting stuff, ...

**Comment by srkunze** [comment]
That makes sense somehow.

However, when reading the man page, it tells me that the "echo" is not pid1.

```
lxc-execute command will run the specified command into the container
via an intermediate process, lxc-init.  This lxc-init after launching the
specified command, will wait for its end and all other reparented
processes.  (to support daemons in the container). 
In other words, in the container, lxc-init has the pid 1 and the
first process of the application has the pid 2.
```

**Comment by monnier** [comment]
I'm trying to use an "application container" (to run various text-processing tools on untrusted files).  So I use `lxc-execute` to run the text-processing tool.  It seems to work, but I also get the "spurious" warning:

    init.lxc: initutils.c: mount_fs: 36 failed to mount /proc : Device or resource busy

Clearly, `/proc` is mounted (e.g. if I do `lxc-execute --name=mycon -- ls -al /proc` I see the expected contents of `/proc`), and the warning seems to indicate that something tries to mount it a second time.  But I don't see anything in my config/template that would try to mount `/proc`, so I assume that both attempts to mount `/proc` are performed by LXC itself.
