### ISSUE TITLE
Permission denied - could not access /var/lib/lxc

### ISSUE THREAD

**Issue by srkunze** [lxc/lxc#688]
After re-creating the Ubuntu 15.10 container on a Ubuntu 14.04 and putting
```
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
```
into `/etc/lxc/default.conf`, I got the following error:

```
root@mexico:~# lxc-execute -n lxc-test /bin/bash
lxc-execute: start.c: print_top_failing_dir: 102 Permission denied - could not access /var/lib/lxc.  Please grant it 'x' access, or add an ACL for the container root.
lxc-execute: sync.c: __sync_wait: 51 invalid sequence number 1. expected 2
lxc-execute: start.c: __lxc_start: 1172 failed to spawn 'lxc-test'
```

**Comment by stgraber** [comment]
the error message is pretty clear, you need to grand the x permission on /var/lib/lxc.

chmod +x /var/lib/lxc

**Comment by stgraber** [comment]
Not done by default due to security concerns when combining that with privileged containers, it's however perfectly safe to do when using unprivileged containers.

**Comment by srkunze** [comment]
@stgraber Alright, just wanted to make sure to bring that to your attention.

Security and convenience seem to have a hard time with each other.

**Comment by cavricks** [comment]
> Not done by default due to security concerns when combining that with privileged containers, it's however perfectly safe to do when using unprivileged containers.

Could you elaborate on what are those security concerns please?
