### ISSUE TITLE
setting of blkio.throttle.write_bps_device fails via config file

### ISSUE THREAD

**Issue by steverding** [lxc/lxc#695]
I added :

**lxc.cgroup.blkio.throttle.write_bps_device="8:0 1048576"**

to the containers config file and got the following error message 

root@xgwsste:/var/log/lxc# lxc-start -n rootcont1 
lxc-start: lxc_start.c: main: 344 The container failed to start.
lxc-start: lxc_start.c: main: 346 To get more details, run the container in foreground mode.
lxc-start: lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.
root@xgwsste:/var/log/lxc# cat /var/log/lxc/rootcont1.log 
      lxc-start 1447231970.761 ERROR    lxc_cgmanager - cgmanager.c:cgm_setup_limits:1386 - call to cgmanager_set_value_sync failed: invalid request
      lxc-start 1447231970.761 ERROR    lxc_cgmanager - cgmanager.c:cgm_setup_limits:1389 - Error setting cgroup blkio:lxc/rootcont1 limit type blkio.throttle.write_bps_device
      lxc-start 1447231970.761 ERROR    lxc_start - start.c:lxc_spawn:990 - failed to setup the cgroup limits for 'rootcont1'
      lxc-start 1447231970.843 ERROR    lxc_start - start.c:__lxc_start:1172 - failed to spawn 'rootcont1'
      lxc-start 1447231975.847 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.
      lxc-start 1447231975.847 ERROR    lxc_start_ui - lxc_start.c:main:346 - To get more details, run the container in foreground mode.
      lxc-start 1447231975.847 ERROR    lxc_start_ui - lxc_start.c:main:348 - Additional information can be obtained by setting the --logfile and --logpriority options.

When i remove the line from the config file, start the container and add the line directly via echo to the sysfs file, it works and the IO is throttled :

root@xgwsste:/# echo "8:0 1048576" >/sys/fs/cgroup/blkio/lxc/rootcont1/blkio.throttle.write_bps_device 
root@xgwsste:/# 

I did this on an Ubuntu whily machine with the following up to date lxc packets:

root@xgwsste:/# dpkg -l |grep lxc
ii  liblxc1                                                     1.1.4-0ubuntu1.1                           amd64        Linux Containers userspace tools (library)
ii  lxc                                                         1.1.4-0ubuntu1.1                           amd64        Linux Containers userspace tools
ii  lxc-templates                                               1.1.4-0ubuntu1.1                           amd64        Linux Containers userspace tools (templates)
ii  lxcfs                                                       0.10-0ubuntu2                              amd64        FUSE based filesystem for LXC
ii  python3-lxc                                                 1.1.4-0ubuntu1.1                           amd64        Linux Containers userspace tools (Python 3.x bindings)

**Comment by hallyn** [comment]
Hi,

remove the quotes.

lxc.cgroup.blkio.throttle.write_bps_device = 8:0 1048576

works for me.

**Comment by steverding** [comment]
Great, it works. This was easy. Thank you :)
