### ISSUE TITLE
Fedora template on fedora host uses host repositories

### ISSUE THREAD

**Issue by isage** [lxc/lxc#696]
Subj. This leads to broken systems inside container if your host is some kind of remix (rfremix, for example).
Because container packages was installed using host repositories, but they are unavailable inside container this will lead to unupgradable system.
Also, i've noticed that you're using yum, please note, that it was deprecated in favor of dnf.

**Comment by brauner** [comment]
Patches to update the `fedora` template are welcome. :)

**Comment by isage** [comment]
Yeah, i get it, patches are welcome.
But who will write them, if this report is closed?
