### ISSUE TITLE
Debian SID - LXC Unprivileged containers don't start

### ISSUE THREAD

**Issue by ne0zer0** [lxc/lxc#704]
Hi,

I try for some time now to start LXC Unprivileged containers on Debian SID (up to date), without success.

(I'm aware that Debian SID, like over Versions and Distros, is not said to work with LXC Unprivileged containers ; but lastly I read that some people have run with success LXC Unprivileged containers on Debian Jessie.)

As there are no user related information in /proc/self/cgroup, i run this command :
>sudo cgm create all $USER;sudo cgm chown all $USER $(id -u $USER) $(id -g $USER);sudo cgm movepid all $USER $$

Anyway, when i try to launch LXC Unprivileged containers on Debian SID I get this :

>huraira@debian:~$ cat /dev/null > /tmp/lxc_test.log; lxc-start -n test -l DEBUG -o /tmp/lxc_test.log -f ~/.config/lxc/default.conf
>lxc-start: cgmanager.c: cgm_setup_limits: 1238 call to cgmanager_set_value_sync failed: invalid request
>lxc-start: cgmanager.c: cgm_setup_limits: 1241 Error setting cgroup use:test limit type use
>lxc-start: start.c: lxc_spawn: 911 failed to setup the cgroup limits for 'test'
>lxc-start: start.c: __lxc_start: 1080 failed to spawn 'test'
>lxc-start: lxc_start.c: main: 342 The container failed to start.
>lxc-start: lxc_start.c: main: 346 Additional information can be obtained by setting the --logfile and --logpriority options.

Here the configuration file used

      lxc.autodev = 1
      lxc.kmsg = 1
      lxc.network.type = veth
      lxc.network.link = br0
      lxc.network.flags = up
      lxc.network.hwaddr = 00:FF:AA:00:00:01
      lxc.network.ipv4 = 192.168.1.110/24
      lxc.network.ipv4.gateway = 192.168.1.1
      lxc.id_map = u 0 1214112 65536
      lxc.id_map = g 0 1214112 65536
      lxc.cgroup.use = freezer,devices,blkio,cpu,cpuacct,cpuset,devices,freezer,perf_event,name=systemd,net_cls,net_prio,memory

LXC versions :
>ii  liblxc1                               1:1.0.7-11                             amd64        Linux Containers userspace tools (library)
>ii  lxc                                   1:1.0.7-11                             amd64        Linux Containers userspace tools

Cgroup related packages
>ii  cgmanager                             0.39-2                                 amd64        Central cgroup manager daemon
>ii  cgmanager-tests                       0.39-2                                 all          Central cgroup manager daemon (tests)
>ii  cgroupfs-mount                        1.2                                    all          Light-weight package to set up cgroupfs mounts
>ii  libcgmanager0:amd64                   0.39-2                                 amd64        Central cgroup manager daemon (client library)
>ii  libcgroup1:amd64                      0.41-7                                 amd64        control and monitor control groups (library)
>ii  libpam-cgm                            0.39-2                                 amd64        Central cgroup manager daemon (PAM module)
>ii  libpam-cgroup:amd64                   0.41-7                                 amd64        control and monitor control groups (PAM)

Here the lxc log file :

      lxc-start 1448299312.128 INFO     lxc_confile - confile.c:config_idmap:1325 - read uid map: type u nsid 0 hostid 1214112 range 65536
      lxc-start 1448299312.128 INFO     lxc_confile - confile.c:config_idmap:1325 - read uid map: type g nsid 0 hostid 1214112 range 65536
      lxc-start 1448299312.128 WARN     lxc_log - log.c:lxc_log_init:316 - lxc_log_init called with log already initialized
      lxc-start 1448299312.129 INFO     lxc_confile - confile.c:config_idmap:1325 - read uid map: type u nsid 0 hostid 1214112 range 65536
      lxc-start 1448299312.129 INFO     lxc_confile - confile.c:config_idmap:1325 - read uid map: type g nsid 0 hostid 1214112 range 65536
      lxc-start 1448299312.130 WARN     lxc_cgmanager - cgmanager.c:cgm_get:954 - do_cgm_get exited with error
      lxc-start 1448299312.130 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver nop
      lxc-start 1448299312.130 DEBUG    lxc_start - start.c:setup_signal_fd:247 - sigchild handler set
      lxc-start 1448299312.130 INFO     lxc_start - start.c:lxc_init:443 - 'test' is initialized
      lxc-start 1448299312.130 DEBUG    lxc_start - start.c:__lxc_start:1058 - Not dropping cap_sys_boot or watching utmp
      lxc-start 1448299312.130 INFO     lxc_start - start.c:lxc_spawn:802 - Cloning a new user namespace
      lxc-start 1448299312.130 INFO     lxc_cgroup - cgroup.c:cgroup_init:62 - cgroup driver cgmanager initing for test
      lxc-start 1448299312.135 ERROR    lxc_cgmanager - cgmanager.c:cgm_setup_limits:1238 - call to cgmanager_set_value_sync failed: invalid request
      lxc-start 1448299312.135 ERROR    lxc_cgmanager - cgmanager.c:cgm_setup_limits:1241 - Error setting cgroup use:test limit type use
      lxc-start 1448299312.135 ERROR    lxc_start - start.c:lxc_spawn:911 - failed to setup the cgroup limits for 'test'
      lxc-start 1448299312.170 ERROR    lxc_start - start.c:__lxc_start:1080 - failed to spawn 'test'
      lxc-start 1448299312.170 WARN     lxc_conf - conf.c:lxc_delete_autodev:1575 - Failed to locate autodev /dev/.lxc and /dev/.lxc/user.
      lxc-start 1448299312.172 ERROR    lxc_start_ui - lxc_start.c:main:342 - The container failed to start.
      lxc-start 1448299312.172 ERROR    lxc_start_ui - lxc_start.c:main:346 - Additional information can be obtained by setting the --logfile and --logpriority options.

Here the journalctl -xe related output

      Nov 23 18:21:52 debian cgmanager[1407]: cgmanager: Found no cgroup entry for pid 4959 controller use
      Nov 23 18:21:52 debian cgmanager[1407]: cgmanager:set_value_main: Could not determine the requested cgroup (use:test)
      Nov 23 18:21:52 debian cgmanager[1407]: me=systemd/user.slice/user-1000.slice/session-1.scope/huraira for 4923 (0:0)
      Nov 23 18:21:52 debian cgmanager[1407]: cgmanager_create: returning 0; existed is 1
      Nov 23 18:21:52 debian cgmanager[1407]: Disconnected from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Connection from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Chown: Client fd is: 6 (pid=4927, uid=0, gid=0)
      Nov 23 18:21:52 debian cgmanager[1407]: Disconnected from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Connection from private client
      Nov 23 18:21:52 debian cgmanager[1407]: MovePid: Client fd is: 6 (pid=4929, uid=0, gid=0)
      Nov 23 18:21:52 debian cgmanager[1407]: 4872 moved to blkio:huraira by 4929's request
      Nov 23 18:21:52 debian cgmanager[1407]: 4872 moved to cpu:huraira by 4929's request
      Nov 23 18:21:52 debian cgmanager[1407]: 4872 moved to cpuset:huraira by 4929's request
      Nov 23 18:21:52 debian cgmanager[1407]: 4872 moved to devices:huraira by 4929's request
      Nov 23 18:21:52 debian cgmanager[1407]: 4872 moved to freezer:huraira by 4929's request
      Nov 23 18:21:52 debian cgmanager[1407]: 4872 moved to net_cls:huraira by 4929's request
      Nov 23 18:21:52 debian cgmanager[1407]: 4872 moved to perf_event:huraira by 4929's request
      Nov 23 18:21:52 debian cgmanager[1407]: 4872 moved to name=systemd:huraira by 4929's request
      Nov 23 18:21:52 debian cgmanager[1407]: Disconnected from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Connection from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Disconnected from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Connection from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Disconnected from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Connection from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Create: Client fd is: 6 (pid=4933, uid=1000, gid=1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/blkio/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/cpu/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/cpuset/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/devices/user.slice/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/freezer/user/huraira/0/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/net_cls/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/perf_event/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/none,name=systemd/user.slice/user-1000.slice/session-1.scope/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: cgmanager_create: returning 0; existed is -1
      Nov 23 18:21:52 debian cgmanager[1407]: Disconnected from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Connection from private client
      Nov 23 18:21:52 debian cgmanager[1407]: SetValue: Client fd is: 6 (pid=4933, uid=1000, gid=1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Disconnected from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Connection from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Remove: Client fd is: 6 (pid=4933, uid=1000, gid=1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/blkio/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/cpu/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/cpuset/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/devices/user.slice/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/freezer/user/huraira/0/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/net_cls/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/perf_event/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/none,name=systemd/user.slice/user-1000.slice/session-1.scope/huraira/test for 4933 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Disconnected from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Connection from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Disconnected from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Connection from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Disconnected from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Connection from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Create: Client fd is: 6 (pid=4959, uid=1000, gid=1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/blkio/huraira/test for 4959 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/cpu/huraira/test for 4959 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/cpuset/huraira/test for 4959 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/devices/user.slice/huraira/test for 4959 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/freezer/user/huraira/0/huraira/test for 4959 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/net_cls/huraira/test for 4959 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/perf_event/huraira/test for 4959 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Created /run/cgmanager/fs/none,name=systemd/user.slice/user-1000.slice/session-1.scope/huraira/test for 4959 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: cgmanager_create: returning 0; existed is -1
      Nov 23 18:21:52 debian cgmanager[1407]: Disconnected from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Connection from private client
      Nov 23 18:21:52 debian cgmanager[1407]: SetValue: Client fd is: 6 (pid=4959, uid=1000, gid=1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Disconnected from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Connection from private client
      Nov 23 18:21:52 debian cgmanager[1407]: Remove: Client fd is: 6 (pid=4959, uid=1000, gid=1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/blkio/huraira/test for 4959 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/cpu/huraira/test for 4959 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/cpuset/huraira/test for 4959 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/devices/user.slice/huraira/test for 4959 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/freezer/user/huraira/0/huraira/test for 4959 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/net_cls/huraira/test for 4959 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/perf_event/huraira/test for 4959 (1000:1000)
      Nov 23 18:21:52 debian cgmanager[1407]: Removed /run/cgmanager/fs/none,name=systemd/user.slice/user-1000.slice/session-1.scope/huraira/test for 4959 (1000:1000)

**Comment by jm009** [comment]
From my understanding it should work somehow if you install cgroup-tools and configure the cgrulesengd daemon, and the cgroups, as described here:
https://myles.sh/configuring-lxc-unprivileged-containers-in-debian-jessie/

**Comment by hallyn** [comment]
lxc.cgroup.use is a lxc.system.conf(5) setting, not a lxc.container.conf(5)
setting.  In a container configuration it is invalid.

**Comment by ne0zer0** [comment]
Hi,

Thank you jm009,

I managed to run unprivileged containers, unfortunately, I did a lot of mistakes, **owing to bad and incomplete available documentations**.

You should really work on it, because it leads to a huge waste of time!
