### ISSUE TITLE
lxc-fedora: mirrors.kernel.org no longer hosts Fedora 20

### ISSUE THREAD

**Issue by Pascal666** [lxc/lxc#705]
The lxc-fedora template requires Fedora 20 LiveOS to build any Fedora release and is hardcoded to pull it from mirrors.kernel.org, but mirrors.kernel.org has stopped hosting Fedora 20 so this template no longer works.

**Comment by nehaljwani** [comment]
I think commit f71e8f41fb129043323b13290c6697d27e603335 fixed this issue?
