### ISSUE TITLE
Created container with fedora template set to UTC timezone instead host's timezone

### ISSUE THREAD

**Issue by rafaelrs** [lxc/lxc#707]
Have to do:

``` bash
mv /etc/localtime /etc/localtime.bak
ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime
```

on every container i did based on fedora template.

**Comment by nehaljwani** [comment]
Which version of lxc are you using? I think commit f5067ecbcc1e97052c33269b4afa6375073a91a1 fixed this issue.

**Comment by brauner** [comment]
I think this is fixed.
