### ISSUE TITLE
LXC always instert itself into init.scope

### ISSUE THREAD

**Issue by Kubuxu** [lxc/lxc#713]
LXC inserts itself into "init.scope" cgroup which is limited in systemd 228 to 512 pids which breaks containers as then LXC is double included in cgroup tree.

For ref: https://bugs.archlinux.org/index.php?do=details&action=details.addvote&task_id=47303

**Comment by hallyn** [comment]
Are you by chance using cgfs (i.e not using cgmanager)?

The cgmanager code makes an exception for init.scope, but the cgfs code probably does not (and should).

**Comment by hallyn** [comment]
No, the cgfs attach code does still end up calling prune_init_scope().

Which version of lxc are you using?

**Comment by Kubuxu** [comment]
I am using cgfs. lxc 1:1.1.5-1 but before I was using build from the git.

The issue is that systemd has `init.scope` for `init` process and there is also dedicated scope from LXC (in which lxc-start is put). For unknown reasons LXC end-ups in both scopes.

**Comment by brauner** [comment]
This should not be an issue anymore in newer liblxc versions.
