### ISSUE TITLE
lxc-start detaches and loses track of running container when daemonised

### ISSUE THREAD

**Issue by KenSharp** [lxc/lxc#715]
For reasons I cannot fathom, _lxc-start -d -n foo_ completely loses track of what's going on, printing the single line:
**lxc-start: utils.c: setproctitle: 1455 Invalid argument - setting cmdline failed**

The container itself is actually started, I can see it running in htop (/sbin/init and friends) and it can be told to shutdown cleanly by sending _lxc-stop -n foo_. Sadly though it seems to be a bit of a secret.

_lxc-ls_ knows nothing about it. Indeed _lxc-ls_ from this point on has lost track of any and all containers that are now started.

Thankfully the syslog does shed some light:
dnsmasq-dhcp[1418]: DHCPDISCOVER(lxcbr0) 10.0.3.84 00:16:3e:b2:36:8a 
dnsmasq-dhcp[1418]: DHCPOFFER(lxcbr0) 10.0.3.84 00:16:3e:b2:36:8a 
dnsmasq-dhcp[1418]: DHCPREQUEST(lxcbr0) 10.0.3.84 00:16:3e:b2:36:8a 
dnsmasq-dhcp[1418]: DHCPACK(lxcbr0) 10.0.3.84 00:16:3e:b2:36:8a foo

I can connect to this address via SSH, and _lxc-console -n foo_ also works.

Now, to compare this to _lxc-start-ephemeral -o foo -n bar -d_:
$ sudo lxc-start-ephemeral -o foo -n bar -d
setting rootfs to .%s. /var/lib/lxc/bar/rootfs
The ephemeral container is now started.

You can enter it from the command line with: lxc-console -n bar
The following IP addresses have be found in the container:
 - 10.0.3.83

I'm assuming this latter behaviour is desirable. Indeed, there was no error message or failure before I upgraded from 1.0.7 to 1.1.5 (Ubuntu PPA).

_lxc-start -n foo -F_ (foreground) also seems to work correctly.

The only reference I could find to the setproctitle message was:

> this is a non-fatal error, so you're just fine. I sent a patch to
> lxc-devel to turn it down to an info message at Stéphane's request
> because he was worried it might freak people out, and it seems he was
> right
> 
> If you want the fancy proctitles, then you need to enable
> CONFIG_CHECKPOINT_RESTORE in your kernel."
> https://lists.linuxcontainers.org/pipermail/lxc-users/2015-November/010411.html

But:
$ fgrep CONFIG_CHECKPOINT_RESTORE /boot/config-$(uname -r)*
CONFIG_CHECKPOINT_RESTORE=y

$ uname -rs
Linux 3.13.0-71-generic

I'm stuck on this kernel for a good while.

Could it be that my kernel is too old? Is that message even relevant? Either way there's a little niggle here somewhere that is upsetting what I assume is a script.

**Comment by deric** [comment]
Having the same issue with starting Debian Jessie container on Ubuntu:
```
    lxc-start 1457735170.268 WARN     lxc_confile - confile.c:config_pivotdir:1801 - lxc.pivotdir is ignored.  It will soon become an error.
      lxc-start 1457735170.271 WARN     lxc_cgmanager - cgmanager.c:cgm_get:994 - do_cgm_get exited with error
      lxc-start 1457735170.272 INFO     lxc_start - start.c:lxc_check_inherited:240 - closed inherited fd 4
      lxc-start 1457735170.280 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:712 - Attempting to set proc title to [lxc monitor] /var/lib/lxc vagrant-base-jessie-amd64
      lxc-start 1457735170.280 ERROR    lxc_utils - utils.c:setproctitle:1455 - Invalid argument - setting cmdline failed
```
kernel: `3.13.0-79-generic #123-Ubuntu`

the config doesn't contain any special configuration:
```
# Parameters passed to the template: --dist debian --release jessie --arch amd64
# For additional config options, please look at lxc.container.conf(5)

# Distribution configuration
lxc.include = /usr/share/lxc/config/debian.common.conf
lxc.arch = x86_64

# Container specific configuration
lxc.rootfs = /var/lib/lxc/vagrant-base-jessie-amd64/rootfs
lxc.utsname = vagrant-base-jessie-amd64

# Network configuration
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:54:ff:1b

# settings for systemd with PID 1:
lxc.kmsg = 0
lxc.autodev = 1
```

**Comment by Auch999** [comment]
I have exactly the same issue (custom kernel (4.4.5) with user namespaces and checkpoint restore enabled). My container starts in foreground mode (-F) with no issues but fails in in daemon mode with the exact same message (lxc-start: utils.c: setproctitle: 1455 Invalid argument - setting cmdline failed).

**Comment by deltahotel** [comment]
@KenSharp Did you run `lxc-ls` as root?

@deric @Auch999 Apart from the error message (which was already [addressed](https://lists.linuxcontainers.org/pipermail/lxc-users/2015-November/010411.html)) and the possibly missing output from `lxc-ls` is the container actually failing? Can you log into the container e.g. using `lxc-console`?

**Comment by KenSharp** [comment]
Definitely run as root but I'm not sure if this has already been fixed. I'll have to check and come back.

**Comment by brauner** [comment]
The `setproctitle()` issue has been fixed. `lxc-ls` could not possibly be affected by the `setproctitle()` failure. What is likely happening is that you didn't run `lxc-ls` as root. If this issue is still reproducible, please ping us and we'll reopen and figure out what's going on.
