### ISSUE TITLE
Machine readable output

### ISSUE THREAD

**Issue by Master-Foo** [lxc/lxc#726]
Maybe this is already a feature, but after RTFM, I couldn't find anything like this. Help me out if I'm being retarded.

Assuming this isn't a feature... It would be nice to have an option to output results in machine readable format. JSON perhaps?

For instance, running the command:

``` bash
lxc-ls --fancy --json
```

might output something similar to:

``` json
{["name":"container_0","state":"STOPPED","ipv4":"","ipv6":"","groups":"","autostart":"no"],["name":"container_1","state":"STOPPED","ipv4":"","ipv6":"","groups":"","autostart":"no"]}
```

Thanks!

**Comment by larsemil** [comment]
on the lxc list format you can put --format=json for info. 
as far as i know thats the only command that has this.

**Comment by brauner** [comment]
To be clear, @larsemil's comment is about the set of `lxc` commands provided by [LXD](https://github.com/lxc/lxd), not the low-level `LXC` tools.

**Comment by brauner** [comment]
We wouldn't necessarily be opposed to a patch. Although there's no precedence of using json in low-level lxc tools. Note however, that you'd need to implement a minimal json parser for the container info struct as we're likely not going to link against an external json library.

**Comment by stgraber** [comment]
No interest in the past 3 years, let's close this.
