### ISSUE TITLE
iptables rule prevents connecting from lxcbr0 to portforwarded external ip-address

### ISSUE THREAD

**Issue by monkz** [lxc/lxc#728]
Hi,
i try to dNAT from my external ipv4-address to my container connected to lxcbr0.

`iptables -t nat -A PREROUTING -d 192.168.0.2/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.0.3.2`

so far so good - works.
But connecting to 192.168.0.2:80 from a container connected to lxcbr0 does not.

**Comment by monkz** [comment]
I deleted now -t nat -A POSTROUTING -s 10.0.3.0/24 ! -d 10.0.3.0/24 -j MASQUERADE
and added  -t nat -A POSTROUTING -s 10.0.3.0/24 -d 10.0.3.0/24 -j MASQUERADE
(there is a ! in the rule)

It seems to work - but why was this rule placed initially (there has to be a reason for it - but i don't see it)

**Comment by brauner** [comment]
The lxc-net script has changed quite a bit if you can still reproduce this please re-open and ping @stgraber.
