### ISSUE TITLE
Support --without-init-script / --with-init-script=no

### ISSUE THREAD

**Issue by ip1981** [lxc/lxc#730]
`--without-foo` (`--with-foo=no`) is a natural feature of [autotools](https://autotools.io/autoconf/arguments.html), but is does not work with LXC:

```
checking for init system type... configure: error: Unknown init system type in no
```

configure.ac suggests `none`: https://github.com/lxc/lxc/blob/master/configure.ac#L118

Please allow `no` as well.

**Comment by brauner** [comment]
This is really just a one line addition to `configure.ac` and I see no need to track this any longer.
