### ISSUE TITLE
Container stuck if it's on ZFS

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxc#736]
There is a related report for ZFS:

https://github.com/zfsonlinux/zfs/issues/3980
Until now I thought it's because I use zfs differently (not just the rootfs, but the whole container (with config ...etc.).

But now there is LXD, everything is in the official way and it's stuck:

```
12983 ?        Ss     0:00 [lxc monitor] /var/lib/lxd/containers fronthera-site
13009 ?        Ss     0:00  \_ /sbin/init
```

BTW, usually the init process is stuck and actually other times it was in D state, so I'm not sure if it's really the same.

Stack traces (echo t > /proc/sysrq-trigger):

http://pastebin.com/raw/7Hv4xMu3

IMO this is a serious issue, it can get out from this state only with hard reboot.

**Comment by tych0** [comment]
What is your guest OS and what is the host kernel version? Can you set lxc.console.logfile and see if the init process tells you why it's hanging? In LXD this would be a config that's soemthing like:

```
raw.lxc: lxc.console.logfile = /tmp/log
```

Thanks!

**Comment by tomposmiko** [comment]
Hmm, first of all as I see, there are two issues.

This one is stuck in ```Ss``` state. And recently I cannot reproduce it, but still strying.
The other one is stuck in ```D``` state and it's not that easy to reproduce, but I'll do my best.

**Comment by brauner** [comment]
It seems that  this issue can't be reproduced. If I'm mistaken, please re-open.

**Comment by tomposmiko** [comment]
Yes, correct.
Thanks.
