### ISSUE TITLE
lxc-ls could produce negative swap value

### ISSUE THREAD

**Issue by ec-m** [lxc/lxc#737]
In the function `get_containers` of lxc-ls.in in line 315 `memory_ram` is
subtracted from `memsw`, which - in my opinion - can result in values that
don't make sense. Here's an example of such a scenario:

Suppose at one point `memory_ram`'s value is 4GB (line 308) and a little later
(when the value of `memsw` is read out, line 314) the usage has gone down and
is now 3GB. Since `memsw` equals the sum of current memory usage plus swap
space, `memsw` has the value 3GB. As `memory_swap` is calculated by subtracting
`memory_ram`'s from `memsw`, `memory_swap` will hence have the value 3GB - 4GB
= -1 GB.

I would volunteer to fix this :)

**Comment by brauner** [comment]
@ec-m, good catch. I had the same problem: You could read in `memory.stat` and parse the current swap-value out of  the `swap` field. This is what I do in the new implementation of `lxc-ls`. :)

**Comment by ec-m** [comment]
@brauner Alright - I'll try that. Thanks!
