### ISSUE TITLE
lxc-console -n container hang

### ISSUE THREAD

**Issue by magic1988yang** [lxc/lxc#741]
Hi
1) Sometimes ,after I create and start a container,I use lxc-console -n container to console the lxc,it hangs and I can't get the login at the terminal.the issue as show follow:
/lxc/lxc-rootfs/bin#lxc-console -n container
Type <Ctrl+a q> to exit the console, <Ctrl+a Ctrl+a> to enter Ctrl+a itself

2) I think the lxc-console doesn't call /bin/login correctlly,because this issue is occasional,so it puzzled me very much!
3) Anyone can help me?,thank you very much!

**Comment by magic1988yang** [comment]
I strace the lxc-console ,the process as follow:
strace lxc-console -n container
execve("/usr/bin/lxc-console", ["lxc-console", "-n", "container"], [/* 22 vars */]) = 0
brk(0)                                  = 0x10013000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x48000000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/tls/ppce500mc/liblxc.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/lib/tls/ppce500mc", 0xbf90a658) = -1 ENOENT (No such file or directory)
open("/lib/tls/liblxc.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/lib/tls", {st_mode=S_IFDIR|0777, st_size=1024, ...}) = 0
open("/lib/ppce500mc/liblxc.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/lib/ppce500mc", 0xbf90a658)    = -1 ENOENT (No such file or directory)
open("/lib/liblxc.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/lib", {st_mode=S_IFDIR|0777, st_size=60, ...}) = 0
open("/usr/lib/tls/ppce500mc/liblxc.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/usr/lib/tls/ppce500mc", 0xbf90a658) = -1 ENOENT (No such file or directory)
open("/usr/lib/tls/liblxc.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/usr/lib/tls", {st_mode=S_IFDIR|0777, st_size=1024, ...}) = 0
open("/usr/lib/ppce500mc/liblxc.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat64("/usr/lib/ppce500mc", 0xbf90a658) = -1 ENOENT (No such file or directory)
open("/usr/lib/liblxc.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\2\1\0\0\0\0\0\0\0\0\0\0\3\0\24\0\0\0\1\0\0\317\200\0\0\0004"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0777, st_size=838885, ...}) = 0
mmap(0xff5b000, 347316, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xff5b000
mprotect(0xff99000, 65536, PROT_NONE)   = 0
mmap(0xffa9000, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3e000) = 0xffa9000
mmap(0xffad000, 11444, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xffad000
close(3)                                = 0
open("/lib/tls/libcap.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libcap.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\2\1\0\0\0\0\0\0\0\0\0\0\3\0\24\0\0\0\1\17\324\20\320\0\0\0004"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0777, st_size=20240, ...}) = 0
mmap(0xfd40000, 83036, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xfd40000
mprotect(0xfd45000, 61440, PROT_NONE)   = 0
mmap(0xfd54000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0xfd54000
close(3)                                = 0
open("/lib/tls/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\2\1\0\0\0\0\0\0\0\0\0\0\3\0\24\0\0\0\1\0\0f\0\0\0\0004"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0777, st_size=1014581, ...}) = 0
mmap(0xfd04000, 176680, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xfd04000
mprotect(0xfd1d000, 61440, PROT_NONE)   = 0
mmap(0xfd2c000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18000) = 0xfd2c000
mmap(0xfd2e000, 4648, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xfd2e000
close(3)                                = 0
open("/lib/tls/libutil.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libutil.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\2\1\0\0\0\0\0\0\0\0\0\0\3\0\24\0\0\0\1\17\333\n@\0\0\0004"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0777, st_size=11432, ...}) = 0
mmap(0xfdb0000, 73872, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xfdb0000
mprotect(0xfdb2000, 61440, PROT_NONE)   = 0
mmap(0xfdc1000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0xfdc1000
close(3)                                = 0
open("/lib/tls/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\2\1\0\0\0\0\0\0\0\0\0\0\3\0\24\0\0\0\1\17\3444\260\0\0\0004"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0777, st_size=1572420, ...}) = 0
mmap(0xfe20000, 1643952, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x48001000
mprotect(0x4817b000, 61440, PROT_NONE)  = 0
mmap(0x4818a000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x179000) = 0x4818a000
mmap(0x48190000, 9648, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x48190000
close(3)                                = 0
open("/lib/tls/libattr.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libattr.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\2\1\0\0\0\0\0\0\0\0\0\0\3\0\24\0\0\0\1\17\333\16\20\0\0\0004"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0777, st_size=19772, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x48193000
mmap(0xfdb0000, 82600, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x48194000
mprotect(0x48199000, 61440, PROT_NONE)  = 0
mmap(0x481a8000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x481a8000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x481a9000
mprotect(0x4818a000, 20480, PROT_READ)  = 0
mprotect(0xfdc1000, 4096, PROT_READ)    = 0
mprotect(0xfd2c000, 4096, PROT_READ)    = 0
mprotect(0xfff2000, 4096, PROT_READ)    = 0
set_tid_address(0x481a9068)             = 22551
set_robust_list(0x481a9070, 12)         = 0
futex(0xbf90b058, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0xbf90b058, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, 1) = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGRTMIN, {0xfd0a090, [], SA_SIGINFO}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0xfd09f50, [], SA_RESTART|SA_SIGINFO}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM_INFINITY}) = 0
brk(0)                                  = 0x10013000
brk(0x10034000)                         = 0x10034000
open("/etc/lxc/lxc.conf", O_RDONLY)     = -1 ENOENT (No such file or directory)
access("/var", F_OK)                    = 0
access("/var/log", F_OK)                = 0
access("/var/log/lxc", F_OK)            = 0
getuid()                                = 0
open("/var/log/lxc/container.log", O_WRONLY|O_CREAT|O_APPEND|O_CLOEXEC, 0666) = 3
getuid()                                = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCSETSF, {B38400 opost -isig -icanon -echo ...}) = 0
socket(PF_LOCAL, SOCK_STREAM, 0)        = 4
connect(4, {sa_family=AF_LOCAL, sun_path=@"/var/lib/lxc/container/command"}, 110) = 0
getuid()                                = 0
getgid()                                = 0
sendmsg(4, {msg_name(0)=NULL, msg_iov(1)=[{"\0\0\0\0\377\377\377\377", 8}], msg_controllen=24, {cmsg_len=24, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS{pid=22551, uid=0, gid=0}}, msg_flags=0}, 0) = 8
recvmsg(4, {msg_name(0)=NULL, msg_iov(1)=[{"\0\0\0\1", 20}], msg_controllen=16, {cmsg_len=16, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, {5}}, msg_flags=0}, 0) = 4
write(2, "\nType <Ctrl+a q> to exit the con"..., 77
Type <Ctrl+a q> to exit the console, <Ctrl+a Ctrl+a> to enter Ctrl+a itself
) = 77
setsid()                                = 22551
rt_sigaction(SIGWINCH, {0x10001360, [WINCH], SA_RESTART}, {SIG_DFL, [], 0}, 8) = 0
ioctl(0, TIOCGWINSZ, {ws_row=39, ws_col=132, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(5, TIOCSWINSZ, {ws_row=39, ws_col=132, ws_xpixel=0, ws_ypixel=0}) = 0
epoll_create(2)                         = 6
fcntl64(6, F_SETFD, FD_CLOEXEC)         = 0
epoll_ctl(6, EPOLL_CTL_ADD, 0, {EPOLLIN, {u32=268513352, u64=1153256065379336197}}) = 0
epoll_ctl(6, EPOLL_CTL_ADD, 5, {EPOLLIN, {u32=268513384, u64=1153256202818289669}}) = 0
epoll_wait(6,

**Comment by magic1988yang** [comment]
I don't know why the epoll_wait() continue to wait and can't get any return,actually i typed Enter at terminal,
anyone else can help me ?thank you very much!

**Comment by pascalrobert** [comment]
I have the same issue. Containers were created on Ubuntu 12.04, and moved to Ubuntu 16.04.

**Comment by brauner** [comment]
The console handling has changed substantially in master if you can still reproduce there please reopen.
