### ISSUE TITLE
c99 + c11 features

### ISSUE THREAD

**Issue by brauner** [lxc/lxc#749]
Can we use c99 and c11 features such as `restrict`, type-generic macros, for-loop initial declarations etc.? Travis yells at me for the `gcc` build when I e.g. use `restrict const` pointers or for-loop initial declarations while the `clang` build passes.

**Comment by hallyn** [comment]
On Sat, Jan 02, 2016 at 08:21:44AM -0800, Christian Brauner wrote:
> Can we use c99 and c11 features such as `restrict`, type-generic macros etc.? Travis yells at me for the `gcc` build when I e.g. use `restrict const` pointers while the `clang` build passes.

I'd prefer not, for several reasons (ignoring travis).  If you feel it makes
your code safer, then let's discuss it with specific examples.  If you feel it
makes it more elegant/easier-to-read, well let's discuss on the list I guess.

restrict in particular seems like begging for new bugs.

**Comment by brauner** [comment]
On Tue, Jan 05, 2016 at 11:52:59AM -0800, Serge Hallyn wrote:
> On Sat, Jan 02, 2016 at 08:21:44AM -0800, Christian Brauner wrote:
> > Can we use c99 and c11 features such as `restrict`, type-generic macros etc.? Travis yells at me for the `gcc` build when I e.g. use `restrict const` pointers while the `clang` build passes.
> 
> I'd prefer not, for several reasons (ignoring travis).  If you feel it makes
> your code safer, then let's discuss it with specific examples.  If you feel it
> makes it more elegant/easier-to-read, well let's discuss on the list I guess.
> 
> restrict in particular seems like begging for new bugs.

One thing I'm really keen about are for-loop initial declarations. It makes the
code easier to read and it keeps things in one place:
`for (size_t i = 0, n = 10; i < n; i++)`

close
