### ISSUE TITLE
Question: Mounting /run/foo directory from host into the container

### ISSUE THREAD

**Issue by sim590** [lxc/lxc#754]
I have this line in my config file:
```
lxc.mount.entry = /run/netns run/netns tmpfs bind,optional,create=dir
```
But when I start the container, attach to it and `ls /run/`, the directory `/run/netns` doesn't appear. *The directory does exist in the host* at the moment I start the container and attach to it. There must be something I am doing wrong. Am I trying to do something impossible?

Also, from the host:
```
$ mount | grep /run/netns
run on /run/netns type tmpfs (rw,nosuid,nodev,relatime,mode=755)
nsfs on /run/netns/node0 type nsfs (rw)
nsfs on /run/netns/node0 type nsfs (rw)
```

**Comment by stgraber** [comment]
that's most likely because your container's operating system is mounting a new tmpfs on top of /run at boot time, hiding any pre-existing mounts you've setup in lxc.

**Comment by sim590** [comment]
Ok, I understand.

Actually, what I'm trying to do is to play with network namespaces inside the lxc container. I've created #756 for this, so I'll close this one.
