### ISSUE TITLE
Container shows zeroes in /proc/uptime

### ISSUE THREAD

**Issue by alitvak69** [lxc/lxc#755]
cat /proc/uptime 
0.0 0.0

lxc 1.1.5

**Comment by hallyn** [comment]
On Fri, Jan 08, 2016 at 10:20:01AM -0800, alitvak69 wrote:
> cat /proc/uptime 
> 00 00
> 
> lxc 115

What is your host's lxcfs version?

**Comment by alitvak69** [comment]
```
lxcfs --version

0.13
```

**Comment by hallyn** [comment]
And it stays that way?

I get

root@docker:~# cat /proc/uptime
8.0 5.0

**Comment by alitvak69** [comment]
Yes it stays this way.  I t caused me to file bug with monit where they
relied on /proc/uptime to start some monitoring functions, and they endup
switching to sysinfo in the latest master version.  But it shouldn't be the
case since it works for you.

**Comment by hallyn** [comment]
What os/release, and how did you get or build lxcfs?

Can you try the current git HEAD?

**Comment by alitvak69** [comment]
Sorry for delay.  I am on Wiley.  I will try git HEAD if I can build it

**Comment by hallyn** [comment]
You should be able to 

pull-lp-source lxcfs
cd lxcfs-0.15

(check debian/control and make sure you have 0.15-0ubuntu2)

dpkg-checkbuilddeps debian/control
(make sure to install any missing packages)
debian/rules build && fakeroot debian/rules binary

(all of the patches in the new 0.16 release are in the xenial 0.15-0ubuntu2 package)

**Comment by alitvak69** [comment]
I didn't have to build it I just pulled debs from the master build.  It is
possible that I am missing something but /proc/uptimet started working.

**Comment by hallyn** [comment]
Ok, thank you - I will see if I can reproduce in wily and, if so, I can
figure out the missing patch.

**Comment by hallyn** [comment]
wait, you said you were running 0.13, but wily has 0.10-0ubuntu2.1.

Which ppas do you have enabled?

**Comment by brauner** [comment]
This should be reported against `lxcfs`. Also, `lxcfs` is not at version `> 2` and quite a bunch of fixes have gone in since then. If this is still reproducible, please reopen in the `lxcfs` repo.
