### ISSUE TITLE
Creating network namepsace inside lxc container

### ISSUE THREAD

**Issue by sim590** [lxc/lxc#756]
I'm trying to create network namepsaces inside an lxc-container. For some reason, it fails. The following python code illustrate what I do:
```python
import argparse, subprocess

from pyroute2 import IPDB, NetNS
from pyroute2.netns.process.proxy import NSPopen

for ifn in range(args.ifnum):
    iface = args.ifname+str(ifn)
    if not iface in ip.interfaces:
        ip.create(kind='veth', ifname=iface, peer=iface+'.1').commit()

ip.create(kind='tuntap', ifname='tap'+args.ifname, mode='tap').commit()

with ip.create(kind='bridge', ifname=brige_name) as i:
    for ifn in range(args.ifnum):
        iface = args.ifname+str(ifn)
        i.add_port(ip.interfaces[iface])
    i.add_port(ip.interfaces['tap'+args.ifname])
    if args.ipv4:
        i.add_ip(local_addr4+'1/24')
    if args.ipv6:
        i.add_ip(local_addr6+'1/64')
    i.up()

with ip.interfaces['tap'+args.ifname] as tap:
    tap.up()

for ifn in range(args.ifnum):
    iface = args.ifname+str(ifn)

    nns = NetNS('node'+str(ifn))
    iface1 = iface+'.1'
    with ip.interfaces[iface1] as i:
        i.net_ns_fd = nns.netns

    with ip.interfaces[iface] as i:
        i.up()

    ip_ns = IPDB(nl=nns)
    try:
        with ip_ns.interfaces.lo as lo:
            lo.up()
        with ip_ns.interfaces[iface1] as i:
            if args.ipv4:
                i.add_ip(local_addr4+str(ifn+8)+'/24')
            if args.ipv6:
                i.add_ip(local_addr6+str(ifn+8)+'/64')
            i.up()
    finally:
        ip_ns.release()

    nsp = NSPopen(nns.netns, ["tc", "qdisc", "add", "dev", iface1, "root", "netem", "delay", str(args.delay)+"ms", str(int(args.delay/2))+"ms", "loss", str(args.loss)+"%", "25%"], stdout=subprocess.PIPE)
    #print(nsp.communicate()[0].decode())
    nsp.communicate()
    nsp.wait()
    nsp.release()

if args.ipv4:
    subprocess.call(["sysctl", "-w", "net.ipv4.conf."+brige_name+".forwarding=1"])
if args.ipv6:
    subprocess.call(["sysctl", "-w", "net.ipv6.conf."+brige_name+".forwarding=1"])
```
When I run this inside an lxc container, I get this:
```
fd = os.open(TUNDEV, os.O_RDWR)
PermissionError: [Errno 1] Operation not permitted: '/dev/net/tun'
```
I have this in my config for my container:
```
# Template used to create this container: /usr/share/lxc/templates/lxc-archlinux
# Parameters passed to the template:
# For additional config options, please look at lxc.container.conf(5)
lxc.rootfs = /var/lib/lxc/foo/rootfs
lxc.utsname = foo
lxc.arch = x86_64
lxc.include = /usr/share/lxc/config/archlinux.common.conf

## network: share with host
lxc.network.type = none

## mounts
## specify shared filesystem paths in the format below
## make sure that the mount point exists on the lxc
lxc.mount.entry = /home home none bind 0 0

## systemd within the lxc
lxc.autodev = 1
lxc.pts = 1024
lxc.kmsg = 0
lxc.hook.autodev=/var/lib/lxc/opendht/autodev
```
The last line shows I call the following script as lxc hook:
```
#!/bin/bash

cd ${LXC_ROOTFS_MOUNT}/dev
mkdir net
mknod net/tun c 10 200
chmod 0666 net/tun
```
What am I missing?

**Comment by sim590** [comment]
Additionnaly, when I do this `ip netns add node0` inside the container, I get this:
```sh
mount --make-shared /var/run/netns failed: Operation not permitted
```

**Comment by hallyn** [comment]
On Fri, Jan 08, 2016 at 12:40:41PM -0800, Simon Désaulniers wrote:
> Additionnaly, when I do this `ip netns add node0` inside the container, I get this:
> ```sh
> mount --make-shared /var/run/netns failed: Operation not permitted

I assume this is due to an apparmor mount restriction.  'ip' wants
to bind mount files for later use, and apparmor is not allowing it
because that can lead to circumvneting path-based permission checks.

**Comment by hallyn** [comment]
On Fri, Jan 08, 2016 at 12:36:55PM -0800, Simon Désaulniers wrote:
> I'm trying to create network namepsaces inside an lxc-container For some reason, it fails The following python code illustrate what I do:

Note that 'creating a network namespace' is trivially done using
'unshare -n' or 'lxc-unshare -s NETWORK', and this will work in
a container.

...

> When I run this inside an lxc container, I get this:
> ```
> fd = osopen(TUNDEV, osO_RDWR)
> PermissionError: [Errno 1] Operation not permitted: '/dev/net/tun'

You need to add

lxc.cgroup.devices.allow = c 10:200 rwm

to your container configuration.  Some '*.common.conf's allow this,
but the common one does not.

**Comment by sim590** [comment]
Awesome. It works fine now. I had trouble finding the keywords I needed to find out what I needed. I found this [doc](https://www.kernel.org/doc/Documentation/cgroups/devices.txt) that explains your solution. Thank you very much.
