### ISSUE TITLE
lxc-clone resolves lxc.include from old config

### ISSUE THREAD

**Issue by kartoffelheinz** [lxc/lxc#758]
We are currently in the evaluation phase to use lxc for a bigger project, which facilitates administrative effort with heavy use of lxc.include in all configs **and** that will make use of lxc-clone quite often. We experienced a rather annoying behavior when cloning a container. The lxc-clone command will not actually clone the container and its config, but rather interpret the config and resolve **all** lxc.include settings to the actual contents of included files. 

This is unexpected and not documented. One should be safe to assume that clone actually means to clone, i.e. making an **identical** copy (except for hostname and the containerpath/name obviously, which are also configurable and documented).
With resolved lxc.include stanzas, the administrative burden is not only much higher, but this also leaves room for lots of "accidents" (especially security-related) with new admins, that don't know about this and will think changing the included file will also change it for all containers that ought to  use it.

Since resolving includes is neither needed nor expected, and actually does tamper with sane environments, this is a bug that should be fixed.

If this is indeed a desired feature, please document it with lxc-clone. Better though would be switching to a sane (and expected) behavior and keeping lxc.include stanzas in a cloned config, optionally allowing a commandline switch to revert back to resolving it.

**Comment by hallyn** [comment]
Which version are you using?

Older lxc used to have this behavior.  Newer lxc uses the 'expanded_config'
to track the configuration to actually save, so that 'lxc.include's are not
expanded.

**Comment by kartoffelheinz** [comment]
Using latest version from Debian stable, which is 1.0.6-6+deb8u2.

Will try to get a newer Version from some ppa or the likes to test. Thanks for the info.

**Comment by kartoffelheinz** [comment]
I can confirm that this issue has indeed bin fixed in newer LXC-Versions. I just tested with 1.1.15, which worked as expected.
