### ISSUE TITLE
container disk iops tracking?

### ISSUE THREAD

**Issue by MACscr** [lxc/lxc#766]
Is there a script that I can use to get live or on demand disk iops for a specific container? I've seen lxc-top that shows total disk transfer for a container, but that's not to useful to me and not really to anyone in my opinion. Need actual IOPS. Not sure if this is even possible when using the default configuration of LXC on Ubuntu since every guest is on the same file system and not its own block device.

Thanks!

**Comment by MACscr** [comment]
Not possible?

**Comment by brauner** [comment]
We have an issue tracking this that asks for implementing this feature in `lxc-top` so closing this one in favor of https://github.com/lxc/lxc/issues/624 .
