### ISSUE TITLE
Strange behaviour when using proxy arp in a container

### ISSUE THREAD

**Issue by zem** [lxc/lxc#775]
I am using IPv4 proxy arp in a container on two Servers to provide a transparent Firewall for my other container. The setup is somehow behaving very odd at mac level on both machines....   

I configured the following in sysctl.conf:
net.ipv4.ip_forward = 1
net.ipv4.conf.eth0.proxy_arp = 1
net.ipv4.conf.eth1.proxy_arp = 1

eth0 is my external interface bridged to the providers switch while eth1 is bridged with my other containers.  One of my problems is that I have to add extra mac addresses to my external ethernet interface like this: 

ip link add link eth0 address f6:83:72:e4:77:0a eth0.1 type macvlan
ifconfig eth0.1 up
ip link add link eth0 address ca:d3:cd:27:fe:f2 eth0.2 type macvlan
ifconfig eth0.2 up

I also have to fix the mac addresses of my containers, otherwise the the value of mac addresses to add is changing on reboot.  I usually find the right mac addresses with tcpdump -e on the firewall while I am trying to ping the outside world.  But even when I see the the right arp packets in tcpdump the firewall container receives packets meant for him with the wrong mac addresses. 

I was not able to track any wrong arp request, but on my second system which has a similar setup I now got a complain that my VM answers an ARP request for an  ip address that does not belong to any of my containers on the system at all, which is also very strange. 

I am not sure if that problem is related to proxy arp code or the cgroups code, or the right place to report that to, maybe one of you has a clue.

**Comment by brauner** [comment]
@stgraber

**Comment by Zetanova** [comment]
Did you got it resolved?

I have the same thing going on with keepalived in docker.

But i could replicated the behavior with a manual added vmaclan.
It it is in rp_filter=0 or rp_filter=2 and proxy_arp=1 then 
the vmaclan interface will reply for every ARP request

on a eth* interface the behavior of proxy_arp is that it is only replying 
to arp requests if a /32 target route is present or 
the target ip is bound on an interface.

On the vmaclan interface everything gets replayed.

Here the test setup:
```
ip link add link eth2 address f6:83:72:e4:77:0a vtest type macvlan
ip addr add 10.253.10.10/32 dev vtest
ip link set vtest up

sysctl -w net.ipv4.conf.vtest.rp_filter=2
sysctl -w net.ipv4.conf.vtest.proxy_arp=1
sysctl -w net.ipv4.conf.vtest.arp_filter=0
sysctl -w net.ipv4.conf.vtest.arp_ignore=0
sysctl -w net.ipv4.conf.vtest.accept_local=1
sysctl -p 
```
arping from an other machine in the net:
`arping -c 1 -I eth2 -s 10.253.10.117 8.8.8.8`

My DC didn't complaine, they just smashed the server with a hammer
and it is not POSTing anymore.

**Comment by Zetanova** [comment]
This is a followup
It looks like it is a miss concept from your side or just a small kernel bug

As soon as the macvlan interface proxy_arp is enabled (with rp_filter=2 or 0)
It will respond to ALL arp with its MAC as response.

I tried to but it to a other routing table and set the medium_id's
arp_filter on or off. 

The only workaround that i found was with:
If xx.xx.xx.xx is the IP that should be routed to the other interface.
```
sysctl -w net.ipv4.conf.vtest.rp_filter=2

arp -Ds XX.XX.XX.XX vtest pub
```

**Comment by stgraber** [comment]
Sounds like something @tomponline may know.

**Comment by tomponline** [comment]
@stgraber @Zetanova I wasn't aware of this, but tried to re-create locally this morning on my ubuntu 18.04 machine running kernel `5.3.0-42-generic`.

This certainly looks like a kernel bug to me, as I can re-create it without using LXC or LXD.

```
ip link add link enp3s0 address f6:83:72:e4:77:0a vtest type macvlan
ip addr add 192.168.1.200/32 dev vtest
ip link set vtest up

sysctl -w net.ipv4.conf.vtest.rp_filter=2
sysctl -w net.ipv4.conf.vtest.proxy_arp=1
sysctl -w net.ipv4.conf.vtest.forwarding=1
`

I found that `net.ipv4.conf.vtest.accept_local` wasn't required for me (it occurred whether it was enabled or disabled), nor was `net.ipv4.conf.vtest.arp_filter=0` and `net.ipv4.conf.vtest.arp_ignore=0` as these are set by default.

The key bit was the last line for me, which I had to add `sysctl -w net.ipv4.conf.vtest.forwarding=1` as without this (or `sysctl -w net.ipv4.conf.all.forwarding=1`) it didn't reply to all ARP requests.

But with either of those 2 lines, combined with `net.ipv4.conf.vtest.proxy_arp=1` and `net.ipv4.conf.vtest.rp_filter=2`,  it does indeed, reply to any ARP request (very bad).

From a different PC on the network:

Without:
```
arping -c 1 -I eth1 -s 192.168.1.2 10.1.2.3
ARPING 10.1.2.3 from 192.168.1.2 eth1
Sent 1 probe(s) (0 broadcast(s))
Received 0 response(s) (0 request(s), 0 broadcast(s))
```

With `sysctl -w net.ipv4.conf.vtest.forwarding=1`
```
arping -c 1 -I eth1 -s 192.168.1.2 10.1.2.3
ARPING 10.1.2.3 from 192.168.1.2 eth1
Unicast reply from 10.1.2.3 [f6:83:72:e4:77:0a] 419.288ms
Sent 1 probe(s) (0 broadcast(s))
Received 1 response(s) (0 request(s), 0 broadcast(s))
```

Also, you can see it faking responses for other devices on the network:

```
arping -c 1 -I eth1 -s 192.168.1.2 192.168.1.240
ARPING 192.168.1.240 from 192.168.1.2 eth1
Unicast reply from 192.168.1.240 [b0:39:56:4f:a5:dc] 0.456ms
Unicast reply from 192.168.1.240 [f6:83:72:e4:77:0a] 27.754ms
Sent 1 probe(s) (0 broadcast(s))
Received 2 response(s) (0 request(s), 0 broadcast(s))
```

One of those is real, the other is faked.

**Comment by stgraber** [comment]
I'm not sure I'd call it a security issue as the permissions required to set this up are similar to CAP_NET_RAW, at which point you could have a scappy script or similar behave in the same way.

But it's certainly a bug to have proxy_arp on macvlan respond to absolutely everything rather than stuff that's "directly attached"...

@tomponline would you mind filing a bug at https://bugzilla.kernel.org/ with the reproducer you've given here? That would be a more suitable place than this Github issue as there's no actual LXC bug.

**Comment by tomponline** [comment]
@stgraber I see your point, yep will do.

**Comment by tomponline** [comment]
Logged kernel issue https://bugzilla.kernel.org/show_bug.cgi?id=206885

**Comment by stgraber** [comment]
@brauner not sure if anything else to do to get the right person to take a look ^
