### ISSUE TITLE
why /dev is limited to 100k, and how to increase or change it?

### ISSUE THREAD

**Issue by mingewang** [lxc/lxc#781]
see the man page:
       If  lxc.autodev is set to 1, then after mounting the container's rootfs LXC
       will mount a fresh tmpfs under /dev (limited to 100k)  and  fill  in  a
       minimal  set  of  initial  devices.   

the question is: why /dev is limited to 100K, and is there anyway to increase it? where is the code to set this limit.

I have a box which has /dev 100%. ( due to 100K limit)

thanks.

**Comment by stgraber** [comment]
On Fri, Jan 29, 2016 at 06:57:40AM -0800, Min Wang wrote:
> see the man page:
>        If  lxcautodev is set to 1, then after mounting the container's rootfs LXC
>        will mount a fresh tmpfs under /dev (limited to 100k)  and  fill  in  a
>        minimal  set  of  initial  devices   
> 
> the question is: why /dev is limited to 100K, and is there anyway to increase it? where is the code to set this limit
> 
> I have a box which has /dev 100%
> 
> 
> thanks

./lxc/conf.c:   if (safe_mount("none", path, "tmpfs", 0, "size=100000,mode=755",

A patch to bump it to say 500k would be welcome.

Stéphane

**Comment by mingewang** [comment]
@stgraber , thanks. I submitted a patch and created a pull request, please review. thanks.

**Comment by stgraber** [comment]
Merged, closing this issue.
