### ISSUE TITLE
Missing lxc.rootfs causes lxc-execute to segfault during container launch

### ISSUE THREAD

**Issue by DeHackEd** [lxc/lxc#782]
Config file:

<pre>
lxc.network.type = veth
lxc.network.flags = up
lxc.network.ipv4 = 192.168.255.2/30
lxc.network.ipv4.gateway = 192.168.255.1
lxc.network.script.up = /var/lib/lxc/VNC/network-up.sh
lxc.network.veth.pair = VNC

lxc.cgroup.cpuset.cpus = 6-7

lxc.cgroup.devices.deny = a
lxc.cgroup.devices.allow = c 136:* rw
lxc.cgroup.devices.allow = c 1:7 rwm
lxc.cgroup.devices.allow = c 1:3 rwm
lxc.cgroup.devices.allow = c 1:8 rwm
lxc.cgroup.devices.allow = c 1:9 rwm
lxc.cgroup.devices.allow = c 1:5 rwm
lxc.cgroup.devices.allow = c 5:2 rwm
lxc.cgroup.devices.allow = c 5:0 rwm

lxc.mount.entry = /dev/pts /dev/pts devpts newinstance,ptmxmode=666 0 0

lxc.cap.drop = audit_control linux_immutable mac_admin mac_override sys_boot
lxc.cap.drop = sys_module  sys_pacct sys_rawio sys_time
</pre>

Execution log:
<pre>
# lxc-execute -n VNC -o /dev/stderr -l DEBUG /bin/bash
    lxc-execute 1454084473.396 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver nop
    lxc-execute 1454084473.396 DEBUG    lxc_start - start.c:setup_signal_fd:249 - sigchild handler set
    lxc-execute 1454084473.396 INFO     lxc_console - console.c:lxc_console_create:565 - no console for lxc-execute.
    lxc-execute 1454084473.396 INFO     lxc_start - start.c:lxc_init:449 - 'VNC' is initialized
    lxc-execute 1454084473.396 DEBUG    lxc_start - start.c:__lxc_start:1078 - Not dropping cap_sys_boot or watching utmp
    lxc-execute 1454084473.397 INFO     lxc_conf - conf.c:run_script:406 - Executing script '/var/lib/lxc/VNC/network-up.sh' for container 'VNC', config section 'net'
    lxc-execute 1454084473.400 DEBUG    lxc_conf - conf.c:instantiate_veth:3130 - instantiated veth 'VNC/vethDKNRLW', index is '31'
    lxc-execute 1454084473.400 INFO     lxc_cgroup - cgroup.c:cgroup_init:62 - cgroup driver cgroupfs initing for VNC
    lxc-execute 1454084473.401 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'cpuset.cpus' set to '6-7'
    lxc-execute 1454084473.401 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.deny' set to 'a'
    lxc-execute 1454084473.401 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 136:* rw'
    lxc-execute 1454084473.401 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:7 rwm'
    lxc-execute 1454084473.401 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:3 rwm'
    lxc-execute 1454084473.401 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:8 rwm'
    lxc-execute 1454084473.401 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:9 rwm'
    lxc-execute 1454084473.401 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:5 rwm'
    lxc-execute 1454084473.401 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 5:2 rwm'
    lxc-execute 1454084473.401 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 5:0 rwm'
    lxc-execute 1454084473.401 INFO     lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1926 - cgroup has been setup
    lxc-execute 1454084473.418 DEBUG    lxc_conf - conf.c:lxc_assign_network:3547 - move '(null)' to '11911'
    lxc-execute 1454084473.425 DEBUG    lxc_conf - conf.c:setup_netdev:2909 - 'eth0' has been setup
    lxc-execute 1454084473.425 INFO     lxc_conf - conf.c:setup_network:2930 - network has been setup
    lxc-execute 1454084473.425 DEBUG    lxc_conf - conf.c:check_autodev:4031 - Set exec command to /bin/bash
    lxc-execute 1454084473.425 INFO     lxc_conf - conf.c:check_autodev:4069 - Autodev not required.
    lxc-execute 1454084473.426 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'cpuset.cpus' set to '6-7'
    lxc-execute 1454084473.426 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.deny' set to 'a'
    lxc-execute 1454084473.426 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 136:* rw'
    lxc-execute 1454084473.426 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:7 rwm'
    lxc-execute 1454084473.426 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:3 rwm'
    lxc-execute 1454084473.426 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:8 rwm'
    lxc-execute 1454084473.426 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:9 rwm'
    lxc-execute 1454084473.426 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 1:5 rwm'
    lxc-execute 1454084473.426 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 5:2 rwm'
    lxc-execute 1454084473.426 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1922 - cgroup 'devices.allow' set to 'c 5:0 rwm'
    lxc-execute 1454084473.426 INFO     lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1926 - cgroup has been setup
    lxc-execute 1454084473.426 ERROR    lxc_sync - sync.c:__sync_wake:62 - sync wake failure : Broken pipe
lxc-execute: sync.c: __sync_wake: 62 sync wake failure : Broken pipe
    lxc-execute 1454084473.426 ERROR    lxc_start - start.c:__lxc_start:1100 - failed to spawn 'VNC'
lxc-execute: start.c: __lxc_start: 1100 failed to spawn 'VNC'
#
</pre>

The clone(CLONE_NEWNET | CLONE_NEWIPC | ...) process segfaulted. Cause: `conf.c:2375 mount_entry_on_generic` dereferences a null pointer `rootfs` variable.

Workaround: add `lxc.rootfs = /` to config file.

This bug showed up after a system patch upgrading LXC to 1.0.8.

**Comment by brauner** [comment]
I'll look into that. I think this was introduced when we allowed lxc overlay mount entries.

**Comment by brauner** [comment]
Totally forgot: @DeHackEd, thanks for reporting.
