### ISSUE TITLE
lxc-stop causes eth to disappear when network.name specified

### ISSUE THREAD

**Issue by jasonguy** [lxc/lxc#783]
This looks like it is a known issue since 2014. I cannot find any recent bug, although I found this: https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/764278

I am running debian jessie: 
Linux lab4 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
LXC version: 1:1.0.6-6+deb8u2.

The lxc config causing the issue is the use of the lxc.network.name option:

```
# Network configuration
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = br0

#Need a 2nd interface?
lxc.network.type = phys
lxc.network.flags = up
lxc.network.link = eth14
lxc.network.name = eth1
```

Container starts fine, and has eth0 and eth1. However, after stopping this container, it cannot restart claiming the interface is missing:

```
root@lab4:~# lxc-start -n mylxc    
lxc-start: failed to retrieve the index for eth14
lxc-start: failed to create netdev
lxc-start: failed to create the network
lxc-start: failed to spawn 'rama1'
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --logpriority options.
```

Apparently the eth14 is changed to dev16 in sysfs:

```
root@lab4:~# ls /proc/sys/net/ipv4/conf/
all      dev16  eth11  eth10     eth4  eth8   veth094ARQ
eth7   eth0   eth12  eth17     eth5  eth9   veth097N84
br0      eth1   eth13  eth2      eth6  lo     veth0Y39RP 
```

It looks like the only way to get the interface back into the kernel is to reboot.

**Comment by viswesn** [comment]
I too see similar issue but not ALL TIME; when I configure to use interface as 'Phys' and remap the interface with different name;  I am using Ubuntu 14.04 and configured eth1 as eth0 in container.

**Comment by towe75** [comment]
Yesterday i faced the same problem on Ubuntu 16.04 / lxc 2.0.4 but can not reproduce it in our test environment. After some searching i spotted this in the [release notes](https://linuxcontainers.org/lxc/news/) for lxc 2.0.6:

> conf: merge network namespace move & rename on shutdown

It should be this commit: 27866a41a3b217cd81ed8cbc8fa5d2413e94a3c1

IMHO it is closely related and possibly solves this bug?

**Comment by Blub** [comment]
Yes this sounds like the same problem.
