### ISSUE TITLE
Login to host system not possible after LXC update on ubuntu 14.04

### ISSUE THREAD

**Issue by bauruine** [lxc/lxc#802]
Hi

I can't longer login to the host system after updating lxc from the stable ppa on ubuntu 14.04 yesterday. https://i.imgur.com/wSISVy4.png it just hangs from there. I have the same issue on 3 different hosts.

Someone on the IRC could reproduce it.
Feb 02 2016 16:49:53 <craag>	Hi bauruine_, I experienced that issue on a fresh 14.04 VM earlier this afternoon.
<craag> [18:21:22] I've reproduced the issue by installing only cgmanager from the ppa (0.39-2ubuntu5~ubuntu14.04.1~ppa1)
<craag> [18:23:16] When trying to log in over ssh, it's ssh that spins 100% cpu. auth.log reports session opened successfully by pam_unix

I booted a live cd on one affected server and chrooted to the system. If `I su - username` there `su` uses 100% CPU and hangs forever. Changing the user with `sudo -iu root` works. 

apt history from the update.
```
Start-Date: 2016-02-01  23:24:48
Commandline: /usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold dist-upgrade
Install: libpam-cgfs:amd64 (0.17-0ubuntu2~ubuntu14.04.1~ppa1, automatic), linux-image-extra-3.13.0-77-generic:amd64 (3.13.0-77.121, automatic), linux-image-3.13.0-77-generic:amd64 (3.13.0-77.121, automatic), linux-headers-3.13.0-77:amd64 (3.13.0-77.121, automatic), linux-headers-3.13.0-77-generic:amd64 (3.13.0-77.121, automatic)
Upgrade: lxc:amd64 (1.1.5-0ubuntu5~ubuntu14.04.1~ppa1, 1.1.5-0ubuntu6~ubuntu14.04.1~ppa1), apt:amd64 (1.0.1ubuntu2.10, 1.0.1ubuntu2.11), linux-headers-generic:amd64 (3.13.0.76.82, 3.13.0.77.83), apt-utils:amd64 (1.0.1ubuntu2.10, 1.0.1ubuntu2.11), prosody:amd64 (0.9.9-1~trusty2, 0.9.10-1~trusty1), libapt-inst1.5:amd64 (1.0.1ubuntu2.10, 1.0.1ubuntu2.11), curl:amd64 (7.35.0-1ubuntu2.5, 7.35.0-1ubuntu2.6), ifupdown:amd64 (0.7.47.2ubuntu4.1, 0.7.47.2ubuntu4.3), lxcfs:amd64 (0.15-0ubuntu2~ubuntu14.04.1~ppa1, 0.17-0ubuntu2~ubuntu14.04.1~ppa1), python3-lxc:amd64 (1.1.5-0ubuntu5~ubuntu14.04.1~ppa1, 1.1.5-0ubuntu6~ubuntu14.04.1~ppa1), liblxc1:amd64 (1.1.5-0ubuntu5~ubuntu14.04.1~ppa1, 1.1.5-0ubuntu6~ubuntu14.04.1~ppa1), libapt-pkg4.12:amd64 (1.0.1ubuntu2.10, 1.0.1ubuntu2.11), lxc-templates:amd64 (1.1.5-0ubuntu5~ubuntu14.04.1~ppa1, 1.1.5-0ubuntu6~ubuntu14.04.1~ppa1), libcurl3:amd64 (7.35.0-1ubuntu2.5, 7.35.0-1ubuntu2.6), nginx-common:amd64 (1.8.0-1+trusty1, 1.8.1-1+trusty0), nginx:amd64 (1.8.0-1+trusty1, 1.8.1-1+trusty0), linux-libc-dev:amd64 (3.13.0-76.120, 3.13.0-77.121), nginx-full:amd64 (1.8.0-1+trusty1, 1.8.1-1+trusty0), linux-image-generic:amd64 (3.13.0.76.82, 3.13.0.77.83), libcurl3-gnutls:amd64 (7.35.0-1ubuntu2.5, 7.35.0-1ubuntu2.6)
Remove: libpam-cgm:amd64 (0.39-2ubuntu5~ubuntu14.04.1~ppa1)
End-Date: 2016-02-01  23:30:11
```

**Comment by hallyn** [comment]
You need cgroup-lite installed because you don't have systemd
mounting the cgroups for you.  The next lxcfs version in ppa
adds that as a dependency, but unfortunately you got the broken
version (broken wrt ppa).

There's still something wrong here though - this module is
marked as optional so your login should not be prevented just
because libpam-cgfs failed.

**Comment by stgraber** [comment]
I don't think it's failing, I think it's hanging.

If it failed, you'd either get in immediately (expected) or (if not optional), your login would fail.

Here when missing cgroupfs, you just never login but you're not being sent back to the login prompt either.

**Comment by bauruine** [comment]
cgroupe-lite indeed seems to fix the problem. Thanks for the update!
