### ISSUE TITLE
veth interfaces not brought back up after suspend+resume on Ubuntu 15.04

### ISSUE THREAD

**Issue by ccope** [lxc/lxc#804]
I suspect this is also broken on 15.10+ but I don't have test machines at the moment. Procedure:

- start container with the standard veth + nat bridge configuration
  - running `ifconfig` on the host shows a veth device has been created and is up.
- sleep + resume the machine
  - running `ifconfig` on the host doesn't show the veth interface anymore. `ifconfig -a` shows the veth interface still exists but is down. eth0 inside the container is still up with an ip address, but it can't ping the gateway.
- `ifconfig $veth_name up` restores network connectivity to the container.

**Comment by stgraber** [comment]
Not something LXC has anything to do with. The linux kernel will not bring interfaces down on suspend, userspace network managers can do that though (Network Manager or the like).

I've never seen this behavior on Ubuntu, regardless of version so I suspect you've got some odd Network Manager setup that's messing with interfaces that it shouldn't mess with (basically running DHCP on veth host devices, failing to grab an IP and then bringing it down).

I'd suggest you look for anything related to lxcbr0 or veth devices in /etc/NetworkManager/system-connections/, if you do, remove those files and reboot.
If that doesn't help, file a bug on Launchpad against network-manager and include your syslog after going through the steps you listed above.
