### ISSUE TITLE
lxc-clone on top of LVM thin provisioning + XFS doesn't quite work

### ISSUE THREAD

**Issue by lxnt** [lxc/lxc#807]
debian8(jessie) lxc 1.0.6-6+deb8u2

```
box:~#lxc-clone -s d8template cloname  fails:
  Logical volume "cloname" created
lxc_container: Error destroying rootfs for cloname
clone failed
```

In fact the cloned container is fine. However, to start it I need to:
- `lvchange -kn /dev/data/cloname`   -- because thin provisioned LVs are skip-autostart by default
- `lvchange -ay /dev/data/cloname`  -- because the LV doesn't get activated due to skip-autostart

and then 
- `xfs_admin -U generate /dev/data/d8template`

this changes filesystem UUID (doesn't matter which one - template or clone) and is needed because othewise xfs.ko refuses to mount it (duplicate UUIDs) thus lxc-start fails.

**Comment by vbaskoff** [comment]
Hi,
I see this in lxc 2.0.0rc13 + OracleLinux7.2
STR:
- Create  base container like sudo lxc-create --name='template' --bdev='lvm' --vgname='lxdata' --thinpool='lxpool' --fssize='7G' --template='/home/porta-one/lxc/lxc-portaonelinux' -- --target-mr='55.0' --repo-domain='packages.portaone.com'

**Comment by vbaskoff** [comment]
Could some one check this issue? It is quite inconvinient to suppress 'lxc-clone' exit code in build scripts and force to add code for direct lvm manipulations.

**Comment by vbaskoff** [comment]
Situation getting worth in lxc 2.0.0, now 'lxc-copy' fails to determine fs on cloned LV and removes it, so 'lvchange' can't help anymore.

STR: 
0. sudo lxc-create --name=template --bdev=lvm --vgname=lxdata --thinpool=lxpool --fssize=15G --template=./template/lxc-lxsys.sh -- --target-mr=55.0 --storage-url=ftp://md.intra/
1. sudo lxc-copy --name='template' --newname='config+log' --snapshot -B lvm --logpriority='DEBUG' --logfile='./copy.log'

> cat ./copy.log
       lxc-copy 20160413141629.413 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/template'->'/var/lib/lxc/template/rootfs' with fstype 'xfs'
       lxc-copy 20160413141629.423 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: Invalid argument
       lxc-copy 20160413141629.423 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/template'->'/var/lib/lxc/template/rootfs' with fstype 'ext4'
       lxc-copy 20160413141629.432 INFO     bdev - bdev/bdev.c:find_fstype_cb:918 - mounted '/dev/lxdata/template' on '/var/lib/lxc/template/rootfs', with fstype 'ext4'
       lxc-copy 20160413141629.446 INFO     bdev - bdev/bdev.c:detect_fs:659 - detected fstype ext4 for /dev/lxdata/template
       lxc-copy 20160413141629.603 INFO     lxc_container - lxccontainer.c:copy_file:2622 - Error stat'ing /var/lib/lxc/template/lxc_rdepends
       lxc-copy 20160413141629.603 INFO     lxc_container - lxccontainer.c:copy_rdepends:2781 - Error copying reverse dependencies
       lxc-copy 20160413141629.617 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/config+log'->'/usr/lib64/lxc/rootfs' with fstype 'xfs'
       lxc-copy 20160413141629.617 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: No such file or directory
       lxc-copy 20160413141629.617 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/config+log'->'/usr/lib64/lxc/rootfs' with fstype 'ext4'
       lxc-copy 20160413141629.617 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: No such file or directory
       lxc-copy 20160413141629.617 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/config+log'->'/usr/lib64/lxc/rootfs' with fstype 'ext3'
       lxc-copy 20160413141629.617 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: No such file or directory
       lxc-copy 20160413141629.617 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/config+log'->'/usr/lib64/lxc/rootfs' with fstype 'ext2'
       lxc-copy 20160413141629.617 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: No such file or directory
       lxc-copy 20160413141629.617 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/config+log'->'/usr/lib64/lxc/rootfs' with fstype 'iso9660'
       lxc-copy 20160413141629.617 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: Permission denied
       lxc-copy 20160413141629.617 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/config+log'->'/usr/lib64/lxc/rootfs' with fstype 'vfat'
       lxc-copy 20160413141629.617 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: No such file or directory
       lxc-copy 20160413141629.617 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/config+log'->'/usr/lib64/lxc/rootfs' with fstype 'hfs'
       lxc-copy 20160413141629.620 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: No such device
       lxc-copy 20160413141629.620 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/config+log'->'/usr/lib64/lxc/rootfs' with fstype 'hfsplus'
       lxc-copy 20160413141629.623 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: No such device
       lxc-copy 20160413141629.623 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/config+log'->'/usr/lib64/lxc/rootfs' with fstype '*'
       lxc-copy 20160413141629.626 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: No such device
       lxc-copy 20160413141629.626 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/config+log'->'/usr/lib64/lxc/rootfs' with fstype 'xfs'
       lxc-copy 20160413141629.626 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: No such file or directory
       lxc-copy 20160413141629.626 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/config+log'->'/usr/lib64/lxc/rootfs' with fstype 'ext3'
       lxc-copy 20160413141629.626 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: No such file or directory
       lxc-copy 20160413141629.626 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/config+log'->'/usr/lib64/lxc/rootfs' with fstype 'ext2'
       lxc-copy 20160413141629.626 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: No such file or directory
       lxc-copy 20160413141629.626 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/config+log'->'/usr/lib64/lxc/rootfs' with fstype 'ext4'
       lxc-copy 20160413141629.626 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: No such file or directory
       lxc-copy 20160413141629.626 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/config+log'->'/usr/lib64/lxc/rootfs' with fstype 'iso9660'
       lxc-copy 20160413141629.626 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: Permission denied
       lxc-copy 20160413141629.626 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:902 - trying to mount '/dev/lxdata/config+log'->'/usr/lib64/lxc/rootfs' with fstype 'vfat'
       lxc-copy 20160413141629.626 DEBUG    bdev - bdev/bdev.c:find_fstype_cb:910 - mount failed with error: No such file or directory
       lxc-copy 20160413141629.626 ERROR    bdev - bdev/bdev.c:mount_unknown_fs:780 - failed to determine fs type for '/dev/lxdata/config+log'
       lxc-copy 20160413141629.732 INFO     lxc_container - lxccontainer.c:container_destroy:2379 - Destroyed rootfs for config+log
       lxc-copy 20160413141629.732 INFO     lxc_container - lxccontainer.c:container_destroy:2395 - Destroyed directory for config+log

**Comment by lxnt** [comment]
Obviously, bdev/bdev.c::do_lvm_create() should be patched to do the -ay -kn dance right after successful creation in the thinpool case.

https://github.com/lxc/lxc/blame/master/src/lxc/bdev/lxclvm.c#L111

Should be trivial.

This will not help with the duplicate UUID problem though. It may not prevent operation in the ext4 case, but most certainly will in the xfs one. It is also quite untidy to have multiple differing filesystems with the same UUID.

So a call to xfs_admin -U generate  / tune2fs -U random / whatever it is for other filesystems should be inserted somewhere between snapshot/clone and attempts to mount. I have no idea where this point would be in the codebase. Will also mean dependencies on e2fsprogs/xfsprogs/whatever.

Ah, and yes, one can get rid of UUIDs completely ( xfs_admin -U nil  / tune2fs -U clear). This should be mentioned in the documentation though.

Some advocacy in the mailing lists might help attacting someone wiser to this issue.

**Comment by lxnt** [comment]
A workaround for the activation issue: https://github.com/lxc/lxc/issues/968#issuecomment-209965246

set  'auto_set_activation_skip = 0' in '/etc/lvm/lvm.conf' 

(thanks to @vbaskoff )

So the complete workaround is: 

- set  auto_set_activation_skip = 0
- clear  template/source lv's uuid

I still think this should be fixed in lxc code.

**Comment by brauner** [comment]
The storage drivers have been reworked substantially if this is still reproducible on master, please re-open.
