### ISSUE TITLE
Cannot start nested container: cgroupfs failed to detect cgroup metadata

### ISSUE THREAD

**Issue by onionjake** [lxc/lxc#809]
I am trying to start a `jessie` container inside of a `jessie` container on Ubuntu 15.10.

```
$ lsb_release -d
Description:    Ubuntu 15.10
$ sudo lxc-create -n fresh -t debian -- -r jessie 
... snipped ...
# echo "lxc.mount.auto = cgroup" >> /var/lib/lxc/fresh/config
# echo "lxc.aa_profile = lxc-container-default-with-nesting" >> /var/lib/lxc/fresh/config
$ sudo lxc-start -n fresh
$ sudo lxc-attach -n fresh
root@fresh:/# apt-get update
... snipped ...
root@fresh:/# apt-get install lxc cgroupfs-mount 
... snipped ...
root@fresh:/# lxc-create -n subfresh -t debian -- -r jessie
... snipped ...
root@fresh:/# lxc-start -n subfresh -l trace
lxc-start: cgroupfs failed to detect cgroup metadata
lxc-start: failed initializing cgroup support
lxc-start: failed to spawn 'subfresh'
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --logpriority options.
```

I don't believe it is an apparmor issue because setting `aa_profile = unconfined` on the `fresh` container has the same problem.

**Comment by Kentoseth** [comment]
Did you add these 2 lines in the parent container configuration:

```
lxc.mount.auto = cgroup
lxc.aa_profile = lxc-container-default-with-nesting
```

?

You can find more details about troubleshooting this on this [Serverfault](https://serverfault.com/questions/366575/is-it-possible-to-start-lxc-container-inside-lxc-container) question.

**Comment by brauner** [comment]
The cgroup driver has been reworked substantially. If this is still reproducible on current master please re-open with the information we ask for in the issue template. Thanks!
