### ISSUE TITLE
LXC should provide a way to play with shared mount points

### ISSUE THREAD

**Issue by francoisbussery** [lxc/lxc#810]
Since version 1.0.0 of LXC, lxc is automatically remounting all SHARED mount points into SLAVE one.
with former lxc, it was possible to play with shared mount points (ex: https://s3hh.wordpress.com/2011/09/22/sharing-mounts-with-a-container/). It is no more possible.

For embedded platforms, it is a problem. In embedded world, it is really common to delegate the ability to manage mass storage in a different container than the one who use it.
So we need to share the mount points.

It is important for 2 reasons:
1) We sometime use filesystem that don't support multiple mounting (like jffs2)
2) The security of the embedded platform rely on the separation of the actors and the delegation of the system & administration entity to specific containers. A simple example is having a container in charge of networking, an other in charge of storage,... So, the one in charge of storage have the capability to mount an hard disk for instance and provide the ressource to an other container. 

This kind of thing is only possible if we can share mount points between containers.

So, we would be please to add to lxc configuration file the possibility to add some exceptions to the SLAVE mount points.

possible some "allow_shared' next to 'create=dir' options" could be a good option

**Comment by Kentoseth** [comment]
@stgraber:

Can this be marked as a feature request?
