### ISSUE TITLE
Must have criu 1.9 or greater to checkpoint/restore

### ISSUE THREAD

**Issue by Andrew-Machen** [lxc/lxc#815]
I have started receiving the below error in relation to an as of yet unreleased version of criu when checkpointing lxc containers, as of the most recent update to lxc:

lxc-checkpoint: criu.c: criu_version_ok: 348 must have criu 1.9 or greater to checkpoint/restore

I am using the version of criu and lxc available from ppa:ubuntu-lxc/stable

Was this change meant for the stable release repository, as it creates a shortfall in required dependencies?

**Comment by tomposmiko** [comment]
Indeed, there is no updated criu package version available.
