### ISSUE TITLE
lxc-checkpoint unprivileged container

### ISSUE THREAD

**Issue by tarruda** [lxc/lxc#817]
Hi

It seems that [criu RPC](http://criu.org/RPC) was created to allow dumping processes without root permissions. Maybe it could be used instead of spawning the criu binary? This would probably allow checkpointing unprivileged containers without root permissions.

**Comment by brauner** [comment]
Afaik, criu will not allow you to dump + restore processes when you are not real root. At least I've never heard of it. You need a privileged caller to do it for you.
