### ISSUE TITLE
lxc-create (unprivileged) error using -f with config file containing lxc.rootfs

### ISSUE THREAD

**Issue by J-Siu** [lxc/lxc#819]
Host OS: Ubuntu 16.04
LXC version: 2.0.0~beta2-0ubuntu2 amd64
Command: lxc-create -t download -n lxc10009 -f lxc10009.conf -- -d ubuntu -r xenial -a amd64
lxc10009.conf:

```
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.include = /usr/share/lxc/config/ubuntu.userns.conf
lxc.arch = x86_64

lxc.id_map = u 0 1000900000 65536
lxc.id_map = g 0 1000900000 65536
lxc.rootfs = /home/js/.local/share/lxc/lxc10009/rootfs
lxc.utsname = lxc10009

# Private Bridge
lxc.network.type = veth
lxc.network.link = br-host01
lxc.network.name = eth0
lxc.network.flags = up
lxc.network.mtu = 65535
lxc.network.hwaddr = 02:xx:xx:xx:xx:xx
lxc.network.ipv4 = 172.16.200.109/24

# Public Bridge
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.name = eth1
lxc.network.flags = up
lxc.network.mtu = 65535
lxc.network.hwaddr = 02:xx:xx:xx:xx:xx

```

Command will fail with following error:
`lxc-create: lxc_create.c: main: 303 Error creating container lxc10009`

It will succeed if "lxc.rootfs" is removed from the config file.

If "lxc.rootfs" is not suppose to be used in a lxc-create config file, maybe we can have a more meaningful error message.

**Comment by brauner** [comment]
Please try to reproduce on the newest stable branch and re-open. The tools have changed a lot as well.
