### ISSUE TITLE
systemd PrivateNetwork fails due to AppArmor

### ISSUE THREAD

**Issue by ChlorideCull** [lxc/lxc#820]
Originally from [lxd issue #1603](https://github.com/lxc/lxd/issues/1603). Requested to be posted here as the AppArmor configuration is from LXC.

Additional requested information:

```
chloridecull@changeling:~$ uname -a
Linux changeling 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
chloridecull@changeling:~$ lxc info
apicompat: 1
auth: trusted
environment:
  addresses: []
  architectures:
  - 2
  - 1
  driver: lxc
  driverversion: 2.0.0.beta2
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-27-generic
  server: lxd
  serverpid: 10049
  serverversion: 2.0.0.beta2
  storage: btrfs
  storageversion: "4.0"
config: {}
public: false
```

---

Simply put, plenty of systemd services require PrivateNetwork (basically creates a new network namespace with only a loopback network) which fails on the latest PPA build on Ubuntu Wily.

Log on host:

```
-- Logs begin at Sun 2016-02-14 19:13:49 UTC, end at Sun 2016-02-14 23:29:34 UTC. --
Feb 14 23:29:34 changeling kernel: audit: type=1400 audit(1455492574.134:46): apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none
Feb 14 23:29:34 changeling kernel: audit: type=1400 audit(1455492574.134:45): apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none
Feb 14 23:29:34 changeling kernel: audit: type=1400 audit(1455492574.134:44): apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none
Feb 14 23:29:34 changeling kernel: audit: type=1400 audit(1455492574.134:43): apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none
Feb 14 23:29:34 changeling audit[6396]: AVC apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none
Feb 14 23:29:34 changeling audit[6396]: AVC apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none
Feb 14 23:29:34 changeling audit[6396]: AVC apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none
Feb 14 23:29:34 changeling audit[6396]: AVC apparmor="DENIED" operation="file_lock" profile="lxd-pythonhijinx_</var/lib/lxd>" pid=6396 comm="(sh)" family="unix" sock_type="dgram" protocol=0 addr=none
```

[Service in question](https://github.com/systemd/systemd/blob/b95292a1523fb119a1cfa11a461f605566b41cec/test/test-execute/exec-privatenetwork-yes.service) being used is from the systemd testing suite, and is run on the child container (and fails with `225/NETWORK` and Permission Denied):

```
[Unit]
Description=Test for PrivateNetwork

[Service]
ExecStart=/bin/sh -x -c 'i=$$(ip link | grep ": " | grep -v ": lo:"); test -z "$$i"'
Type=oneshot
PrivateNetwork=yes
```

**Comment by stgraber** [comment]
I mentioned this issue to our security team, hoping to hear back from them soon.

**Comment by stgraber** [comment]
John Johansen on our apparmor team says that this is an actual apparmor bug. He's looking into it.

**Comment by hallyn** [comment]
A launchpad bug has been opened at
https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1575779

**Comment by brauner** [comment]
@stgraber what's the status on this one?

**Comment by jkroepke** [comment]
There are any new about this issue? Upcomming bionic has some system services that requires PrivateNetwork

```
/lib/systemd/system/rtkit-daemon.service:PrivateNetwork=yes
/lib/systemd/system/dbus-org.freedesktop.hostname1.service:PrivateNetwork=yes
/lib/systemd/system/dbus-org.freedesktop.locale1.service:PrivateNetwork=yes
/lib/systemd/system/systemd-localed.service:PrivateNetwork=yes
/lib/systemd/system/systemd-hostnamed.service:PrivateNetwork=yes
```

**Comment by brauner** [comment]
@stgraber any news?

**Comment by brauner** [comment]
@jkroepke is this still an issue for you or are you just asking?

**Comment by stgraber** [comment]
No idea, apparmor bug is still open so I'd think it's still happening.

**Comment by jkroepke** [comment]
@brauner It's still an issue for me.

It maybe an issue with the beta Containers of 18.04 but it looks like 17.10 had the same problems.

To workaround this issue, i had to define some systemd overrides.

```
# /etc/systemd/system/rtkit-daemon.service.d/override.conf
[Service]
PrivateNetwork=no
# /etc/systemd/system/systemd-hostnamed.service.d/override.conf
[Service]
PrivateNetwork=no
# /etc/systemd/system/systemd-localed.service.d/override.conf
[Service]
PrivateNetwork=no
```

I don't if this is this the way to go.

**Comment by jkroepke** [comment]
This issue feel like the old issue about the openvpn service since 16.04.

https://github.com/systemd/systemd/issues/6011

Maybe lxd must be expose a capability that netnamespace are not availible inside unpriv. containers. unless the apparmor bug is fixed.

**Comment by brauner** [comment]
@jkroepke I'm running systemd-hostnamed in a container just fine Debian Buster, 4.16 kernel.

**Comment by jkroepke** [comment]
In a Unpriv. container with an own user namespace?

Am 15.03.2018 um 18:35 schrieb Christian Brauner <notifications@github.com>:

@jkroepke <https://github.com/jkroepke> I'm running systemd-hostnamed in a
container just fine Debian Buster, 4.16 kernel.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/lxc/lxc/issues/820#issuecomment-373461159>, or mute the
thread

**Comment by brauner** [comment]
```
Mar 15 17:36:56 bust3 systemd[1]: Started Hostname Service.
root@bust3:~# cat /proc/self/uid_map
         0     100000 1000000000
root@bust3:~# systemctl status systemd-hostnamed
● systemd-hostnamed.service - Hostname Service
   Loaded: loaded (/lib/systemd/system/systemd-hostnamed.service; static; vendor preset: enabled)
   Active: active (running) since Thu 2018-03-15 17:36:56 UTC; 10s ago
     Docs: man:systemd-hostnamed.service(8)
           man:hostname(5)
           man:machine-info(5)
           https://www.freedesktop.org/wiki/Software/systemd/hostnamed
 Main PID: 372 (systemd-hostnam)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/systemd-hostnamed.service
           └─372 /lib/systemd/systemd-hostnamed

Mar 15 17:36:56 bust3 systemd[1]: Starting Hostname Service...
Mar 15 17:36:56 bust3 systemd[1]: Started Hostname Service.
root@bust3:~# cat /lib/systemd/system/systemd-hostnamed.service | grep PrivateNetwork
PrivateNetwork=yes
```

**Comment by jkroepke** [comment]
Hm. I‘m using the 16.04 GA Kernel. 4.4?

**Comment by brauner** [comment]
Oh, yeah, then AppArmor very likely.

**Comment by jkroepke** [comment]
So before I can use 18.04 containers without any hacks, I have to upgrade my host first. Right?

**Comment by brauner** [comment]
@jkroepke, if it's acceptable to you you can try and switch to the hwe kernel which should be 4.15.

**Comment by jkroepke** [comment]
I‘m using the GA Kernel for the livepatching service. But okay. I‘ll. have a migration parh for now. Thanks.

**Comment by brauner** [comment]
Closing as this is not a LXC bug.
