### ISSUE TITLE
cgfs fixes

### ISSUE THREAD

**Issue by brauner** [lxc/lxc#824]
commit https://github.com/lxc/lxc/commit/5f4aafaccbd7b94b8c8afe4be8b9dd132fdc9c34 fixed an initialization issue with a temporary variable `i` causing code to be executed that was previously skipped (bc `i` was initialized by `snprintf()` and so probably some cgroup subsystems where never checked whether they can be written to or not). Specifically, we're talking about:

	i = 0;
	while (i < nr_subsystems) {
		char *p = get_last_controller_in_list(subsystems[i]);

		if (!subsys_is_writeable(p, probe)) {
			if (is_crucial_subsys(p)) {
				ERROR("Cannot write to crucial subsystem %s\n",
					subsystems[i]);
				goto out;
			}
			if (cgroup_use && any_in_comma_list(subsystems[i], cgroup_use)) {
				ERROR("Cannot write to subsystem %s which is requested in lxc.cgroup.use\n",
					subsystems[i]);
				goto out;
			}
			WARN("Cannot write to subsystem %s, continuing with out it\n",
				subsystems[i]);
			dropped_any = true;
			drop_subsystem(i);
		} else {
			cgm_remove_cgroup(subsystems[i], probe);
			i++;
		}
	}

This e.g. causes `lxc-attach` to fail with unprivileged containers when the shell it is executed in is not in the same cgroup as the container, since we error out with `ERROR("Cannot write to crucial subsystem %s\n", subsystems[i]);`. `lxc_cgroupfs_enter()` in `cgfs.c` will then try to write the corresponding `pid` of the program executed by `lxc-attach` in the containers cgroup but will fail (I guess the path it tries to build is wrong.).

**Comment by brauner** [comment]
I should note that I haven't completely convinced myself that this is a bug yet.

**Comment by hallyn** [comment]
I'm confused.  The patch you're pointing to is in cgmanager.c, but you're talking about cgfs.c ?  The two are essentially mutually exclusive.

**Comment by brauner** [comment]
If I comment out `i` in that patch again I can `lxc-attach` without a problem. If I uncomment it I get the following error:

    lxc-attach: cgfs.c: lxc_cgroupfs_enter: 1157 Invalid argument - Could not add pid 30411 to cgroup lxc/ubuntu_wily_u: internal error
    lxc-attach: cgfs.c: lxc_cgroupfs_attach: 2448 could not move attached process 30411 to cgroup of container
    lxc-attach: attach.c: lxc_attach: 929 error communicating with child process

This seems to point to some weird interaction between `cgmanager.c` and `cgfs.c`; or something on my side is really broken.

**Comment by brauner** [comment]
Ok, here is my idea for how this comes about:

`verify_final_subsystems()` returns `false` --> `collect_subsytems()` returns `false` --> `cgm_ops_init()` returns `NULL`. Now we move on to `cgroup.c`:

```
 void cgroup_ops_init(void)                                                         
{                                                                                  
        if (ops) {                                                                 
                INFO("cgroup driver %s", ops->name);                               
                return;                                                            
        }                                                                          
                                                                                   
        DEBUG("cgroup_init");                                                      
        #if HAVE_CGMANAGER                                                         
        ops = cgm_ops_init();                                                      
        #endif                                                                  
        if (!ops)                                                               
                ops = cgfs_ops_init();                                          
        if (ops)                                                                
                INFO("Initialized cgroup driver %s", ops->name);                
}
```

And with the call to `cgfs_ops_init()` we switch to `cgfs.c`. But I might be totally wrong with this.

**Comment by hallyn** [comment]
So when you remove the i=0, do you end up using cgmanager in cgfs?

I'm trying to discern whether you want cgmanager to be used, or whether
you are saying that cgmanager is somehow impacting cgfs's state.

**Comment by hallyn** [comment]
If what you want is to have cgmanager run, then we should figure out
why a controller is check is failing in that i < nr_subsystems loop.
The idea is we ignore any controllers which are not writeable so
long as they are not 'crucial' (frezer, systemd) and they are
not listed as required in cgroup.use.  If neither of those
applies, we should ignroe it and not fail.  

not resetting i to 0 just means we skip that loop where we check
the subsystems.

**Comment by brauner** [comment]
When I remove the `i = 0` then I'm using cgmanager only. When I insert `i = 0` cgfs setting up cgroups with cgmanager fails and cgfs comes into play. I don't know what your original intentions were: When cgmanager fails then cgfs is used to setup cgroups?
That's why I said I'm not sure whether this is a bug or just expected behaviour.

**Comment by hallyn** [comment]
Quoting Christian Brauner (notifications@github.com):
> When I remove the `i = 0` then I'm using cgmanager only. When I insert `i = 0` cgfs setting up cgroups with cgmanager fails and cgfs comes into play. I don't know what your original intentions were: When cgmanager fails then cgfs is used to setup cgroups?
> That's why I said I'm not sure whether this is a bug or just expected behaviour.

Yes, if cgmanager fails to setup, then we fall back to cgfs.  That's the intent.

So the q is why we think cgmanager has failed.

**Comment by brauner** [comment]
This is the (legacy) cgroup layout I see when I open a new shell:

```
[chb@conventiont ~]$ cat /proc/self/cgroup 
12:blkio:/user.slice
11:debug:/
10:perf_event:/
9:pids:/user.slice/user-1000.slice/session-c1.scope
8:cpuset:/
7:hugetlb:/
6:memory:/user.slice
5:net_cls:/user.slice
4:devices:/user.slice
3:cpu,cpuacct:/user.slice
2:freezer:/
1:name=systemd:/user.slice/user-1000.slice/session-c1.scope
```

**Comment by brauner** [comment]
The `systemd` group is not writeable probably because I'm missing the `libpam-cgfs` setup that is standard on `Ubuntu` on my system?

**Comment by brauner** [comment]
When I create the cgroups and move myself into it:

```
[chb@conventiont ~]$ cat /proc/self/cgroup 
12:blkio:/user.slice/chb
11:debug:/chb
10:perf_event:/chb
9:pids:/user.slice/user-1000.slice/session-c1.scope/chb
8:cpuset:/chb
7:hugetlb:/chb
6:memory:/user.slice/chb
5:net_cls:/user.slice/chb
4:devices:/user.slice/chb
3:cpu,cpuacct:/user.slice/chb
2:freezer:/chb
1:name=systemd:/user.slice/user-1000.slice/session-c1.scope/chb
```

everything's fine. So it seems that `lxc-attach` was previously working for me when I was in a non-writeable cgroup although it should have refused to work.

**Comment by hallyn** [comment]
Quoting Christian Brauner (notifications@github.com):
> The `systemd` group is not writeable probably because I'm missing the `libpam-cgfs` setup that is standard on `Ubuntu` on my system?

Yeah also freezer is required.

**Comment by brauner** [comment]
Good, than this was indeed expected behaviour for `lxc-attach` to fail. `lxc-attach` was supposed to work only when you we're in a writeable cgroup. I was not sure if the prior behavior or the new behavior was a bug; the old one was.

**Comment by brauner** [comment]
FWIW, this might irritate user that are not on a system that moves them into their own writeable cgroup on login. We should probably note this changed behavior for `lxc-attach` somewhere when we release `lxc 2.0.0`.

**Comment by hallyn** [comment]
We can probably do a better job of reporting errors there.  Perhaps
store a cgmanager and cgfs error, cgmanager can store that it failed
to create a cgroup for systemd;  then if we fail at cgroup_enter,
spit out those errors.

(It's a bit convoluted bc the init code runs before logging is set up)
