### ISSUE TITLE
Fix LXC nested inside privileged LXD (devices.allow problem)

### ISSUE THREAD

**Issue by stgraber** [lxc/lxc#827]
LXC should warn (WARN) but not fail (ERROR) when asked to give the containers more devices access than it itself have.

LXD by default has a cgroup policy much stricter than LXC's default one. As a result, nesting LXC containers inside a privileged LXD containers fails.

Unprivileged LXD containers don't suffer from that problem as the devices cgroup policy isn't applied to unprivileged containers.

Nor does LXD in LXD as the policies then match.

There is no security risk in moving forward in such a case, the only potential problem is that the user won't be able to interact with the device they requested, but a WARN should be enough for them to realize that without breaking most users.

**Comment by hallyn** [comment]
So do you think it is enough to WARN when the write fails, or does lxc need to compute the current access list and verify for itself?  Otherwise it's conceivable that the write could fail due to another reason, although if an unprivileged user can affect that then we do have other problems, meaning that it should be only possible due to serendipity on the user's part.

**Comment by stgraber** [comment]
What does errno look like? Do we get a clear difference between invalid input (EINVAL) and refuse to extend permissions (EPERM)?

**Comment by hallyn** [comment]
sorry, a few more details - are you seeing this with cgmanager or cgfs?  I create a lxc container under lxd, and the download template causes /usr/share/lxc/config/ubuntu.userns.conf to be included so that devices cgroup entries are cleared.

**Comment by hallyn** [comment]
(in cgmanager you won't be able to discern eperm from einval, but with cgfs you should)

**Comment by hallyn** [comment]
Oh, right, this is for unprivileged containers.

**Comment by stgraber** [comment]
That was priv LXC inside priv LXD.

**Comment by hallyn** [comment]
Yup, testing a fix.
