### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [lxc/lxc#83]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html) ⇒ [main](https://github.com/lxc/lxc/blob/a8aa709c9de0e6b4c6174396590e265f7bda75c7/src/lxc/lxc_init.c#L77)
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html) ⇒ [print_usage](https://github.com/lxc/lxc/blob/e555005b15a1d8e95997bd2d72abd0bc230a541d/src/lxc/arguments.c#L87)

**Comment by brauner** [comment]
We've been doing a lot more error handling since this issue has been opened. I think this is invalid by now.

**Comment by elfring** [comment]
It seems that there are still [implementation details left over for further development considerations](https://github.com/lxc/lxc/blob/70e1f27e0bc2fd15e6a702a4b75e92b0a82e0857/src/lxc/initutils.c#L127 "Update candidate: lxc_global_config_value()").

**Comment by brauner** [comment]
@elfring, care to send a patch?

**Comment by elfring** [comment]
* There are a few design choices available to fix remaining update candidates.
* It seems that some linked information sources did not get the software development attention I am hoping for a while.

**Comment by brauner** [comment]
At the time you were posting them I wasn't around and the two links seemed to have been invalidated. Maybe you can expand on the design you have in mind here. I'd be interested to hear your thoughts.

**Comment by elfring** [comment]
* How much do you understand information around mentioned higher level development tools?
* Are you really interested in an update for software links?

**Comment by brauner** [comment]
I'm happy to engage with the idea. I don't know what the intention of the other two questions is.

The missing error checks for `malloc()` in the codepath you pointed out seem intentional.

**Comment by elfring** [comment]
>… seem intentional.

I got an other development impression from [the current implementation of the function “lxc_global_config_value”](https://github.com/lxc/lxc/blob/70e1f27e0bc2fd15e6a702a4b75e92b0a82e0857/src/lxc/initutils.c#L127 "Update candidate") (for example).


>I'm happy to engage with the idea.

* Which higher level tools would you dare to integrate into the development process for this software?
* Are you going to reopen this issue?
