### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [lxc/lxc#84]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html)" to [your build specification](https://github.com/lxc/lxc/blob/8b54fb4de8097d719a595c019c08a99bd458de0d/configure.ac#L399)?

**Comment by elfring** [comment]
Please reopen this issue until the additional macro call will be correctly used.

**Comment by brauner** [comment]
@elfring?

**Comment by elfring** [comment]
@brauner, @marcosps: I suggest to pass additional parameters for the call of the macro “AX_PTHREAD”.

**Comment by brauner** [comment]
When you claim "correctly used" it would be nice to know what you mean by that. What parameters are you referring to and would you be up for sending patch?

**Comment by marcosps** [comment]
@elfring I left the AX_PTHREAD without any additional parameters because AC_SEARCH_LIBS wasn't using anything too. What do you suggests to do in this case?

**Comment by elfring** [comment]
How do you think about an update suggestion like the following?

```diff
 # Check for some libraries
-AX_PTHREAD
+AX_PTHREAD([LIBS="$PTHREAD_LIBS $LIBS"
+CFLAGS="$CFLAGS $PTHREAD_CFLAGS"
+CC="$PTHREAD_CC"],
+           [AC_MSG_ERROR([Could not configure POSIX threads support])])
 AC_SEARCH_LIBS(clock_gettime, [rt])
```
