### ISSUE TITLE
lxc-create fails to create a -B loop container

### ISSUE THREAD

**Issue by dann1** [lxc/lxc#845]
Hello I tried to create a loop container and I typed "lxc-create -n name -t ubuntu -B loop" it fails to create the container but I tried to start a loop container I created using lxc on  debian jessie and it works perfect, so the problem is just to create loop containers in ubuntu 14.04, any ideas? Thank you

**Comment by hallyn** [comment]
Hi,

could you show exactly the command you used, and the output it gave?

**Comment by dann1** [comment]
root@ubuntu5:/home/ubuntu5# MIRROR=http://10.8.91.175/Soft_Linux/Repos/ubuntu/trusty lxc-create -t ubuntu -n fail -B loop
lxc-create: bdev.c: do_loop_create: 2028 Error creating filesystem type ext3 on /var/lib/lxc/fail/rootdev
lxc-create: lxccontainer.c: do_bdev_create: 936 Failed to create backing store type loop
lxc-create: lxccontainer.c: do_lxcapi_create: 1419 Error creating backing store type loop for fail
lxc-create: lxc_create.c: main: 274 Error creating container fail

I defined my mirror address because I dont't use the internet defined mirror in the ubuntu template

**Comment by englebert** [comment]
I found a fix. It just need to put a "-F" into the execlp.
# git diff
diff --git a/src/lxc/bdev/bdev.c b/src/lxc/bdev/bdev.c
index 090b685..955ab1b 100644
--- a/src/lxc/bdev/bdev.c
+++ b/src/lxc/bdev/bdev.c
@@ -721,7 +721,7 @@ int do_mkfs(const char *path, const char *fstype)
        // us about whether to proceed.
        if (null_stdfds() < 0)
                exit(1);
-       execlp("mkfs", "mkfs", "-t", fstype, path, (char *)NULL);
+       execlp("mkfs", "mkfs", "-F", "-t", fstype, path, (char *)NULL);
        exit(1);
 }

**Comment by englebert** [comment]
I wish to commit the changes, may i know how to help on this please?

**Comment by hallyn** [comment]
On Thu, Mar 24, 2016 at 09:18:37PM -0700, englebert wrote:
> I found a fix. It just need to put a "-F" into the execlp.
> # git diff
> diff --git a/src/lxc/bdev/bdev.c b/src/lxc/bdev/bdev.c
> index 090b685..955ab1b 100644
> --- a/src/lxc/bdev/bdev.c
> +++ b/src/lxc/bdev/bdev.c
> @@ -721,7 +721,7 @@ int do_mkfs(const char *path, const char *fstype)
>         // us about whether to proceed.
>         if (null_stdfds() < 0)
>                 exit(1);
> -       execlp("mkfs", "mkfs", "-t", fstype, path, (char *)NULL);
> +       execlp("mkfs", "mkfs", "-F", "-t", fstype, path, (char *)NULL);

This is not an mkfs option.  it is an mkfs.ext option.  For instance

mkfs.-t xfs -F xxx

fails.  So you'll need to tweak the patch to only do this for
filessytems which need the flag.

**Comment by hallyn** [comment]
On Thu, Mar 24, 2016 at 09:35:53PM -0700, englebert wrote:
> I wish to commit the changes, may i know how to help on this please?

Make the change in your github.com/englebert/lxc tree (make the change
locally, then 'git push git+ssh://git@github.com/englebert/lxc master:mkfs'),
then load up github.com/lxc/lxc and near the top of the page you should an
option to start a pull request for your branch.

**Comment by englebert** [comment]
Thanks Hallyn.
