### ISSUE TITLE
Gateway fail when not in same network of the ip address

### ISSUE THREAD

**Issue by guilhem** [lxc/lxc#85]
For now this configuration don't work:

```
lxc-start: failed to setup ipv4 gateway for 'eth1': Network is unreachable
```

```
lxc.network.type = macvlan
lxc.network.hwaddr = 52:54:00:\*:\*:\*
lxc.network.link = eth0
lxc.network.ipv4 = 212.83.\*.\*/32
lxc.network.ipv4.gateway = 62.210.\*.1
lxc.network.flags = up
```

it's because 62.210.*.1 isn't part of 212.83.*.*/32 ... but it's the right things to do in my case.
To be able to use this, we must add route for 62.210.***.1 on interface.

```
# ip route add 62.210.\*.1 dev eth1
# ip route add default via 62.210.\*.1
```

Solution can be to add gw as route by default to this interface to avoid any problem like this.

PS: I know that it can be seen like somethings "weird", but here (in France/Europe/USA) some big hosting company (OVH, Online.net) use this way to add more IP for their dedicated servers.

**Comment by narcisgarcia** [comment]
Can't this be fixed for unprivileged containers (veth)?
