### ISSUE TITLE
Segmentation fault on lxc-attach

### ISSUE THREAD

**Issue by kourindouhime** [lxc/lxc#858]
Hi.

Ubuntu Xenial Xerus (development branch)
4.4.0-7-generic #22-Ubuntu SMP Thu Feb 18 20:50:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

    # lxc-attach --version
    2.0.0.rc4

Fresh install. What was done:

    # apt-get install lxc libnl-3-dev criu pkg-config thin-provisioning-tools libprotobuf-dev protobuf-c-compiler libcap-dev protobuf-compiler
    # # get latest criu from git and compile
    # lxc-create --template ubuntu --name goodicon.ru -- --release xenial
    # lxc-start -n goodicon.ru
    # lxc-attach -n goodicon.ru
    Segmentation fault (core dumped)

Strace:

[out.txt](https://github.com/lxc/lxc/files/150627/out.txt)

**Comment by brauner** [comment]
I can't reproduce in a xenial `KVM` following exactly your steps. According to the strace you get a bad file descriptor somewhere. Can you run `lxc-attach` as:

    lxc-attach -n goodicon.ru -l debug -o attach_debug.txt

and

    lxc-start -n goodicon.ru -l debug -o start_debug.txt

and paste both files here, please.

**Comment by kourindouhime** [comment]
[attach_debug.txt](https://github.com/lxc/lxc/files/150735/attach_debug.txt)
[start_debug.txt](https://github.com/lxc/lxc/files/150734/start_debug.txt)

**Comment by brauner** [comment]
This is reliably reproducible on your side?

**Comment by kourindouhime** [comment]
I can capture the screen of how I'm installing xenial on Parallels and loading it with lxc, if you want. Or what do you mean?

**Comment by brauner** [comment]
Hm, no. I just mean if every time you do these steps a segfault happens? The thing is that I cannot reproduce this at all. I tried three times; each time a fresh `KVM` instance.

**Comment by kourindouhime** [comment]
Did that again twice and the 2nd time is was fine.

**Comment by brauner** [comment]
Still weird though. @hallyn, hate to drag you into this but do you have any idea?

**Comment by kourindouhime** [comment]
My bad, I was adding "lxc.console = none" to machine config file for criu. Attach works fine without that one.

**Comment by brauner** [comment]
Still a bug though; this is supposed to work.
