### ISSUE TITLE
cgfs: respect cgroup.use

### ISSUE THREAD

**Issue by hallyn** [lxc/lxc#870]
To make lxc not fail for unprivileged users, we are ignoring errors for non-crucial cgroups.  But, like we are doing in cgroup manager, all those cases where we are checking is_crucial_subsys() should also be checking whether the subsystem is in cgroup.use.

Probably best to put that check into is_crucial_subsys itself.

**Comment by marcosps** [comment]
@hallyn it was what you thought about when you opened this bug?

This worked for me, when I "umounted" the blkio subsystem and used blkio in lxc.cgroup.use, so lxc-start failed for me.

If this the right approach?
