### ISSUE TITLE
tools/lxc_destroy: remove remaining entities when rootfs is missing

### ISSUE THREAD

**Issue by KenSharp** [lxc/lxc#877]
`lxc-destroy -n foo` fails, as one might expect, if the rootfs is not available. However, it makes no attempt to clean anything up and simply continues to fail with each attempt. One might expect `lxc-destroy -f` to force remove the config files, but it does not.

The rootfs can disappear for a number of reasons: failed partition/volume, corruption, ephemeral storage or good-old human error. The reason why it might occur isn't really the issue.

The user has to manually remove the relevant directory so that the long-gone container is no longer listed with `lxc-ls`. They have to find it first.

```
# lxc-destroy -fn trusty
lxc-destroy: lxccontainer.c: container_destroy: 2388 Error destroying rootfs for trusty
Destroying trusty failed

# lxc-info -n trusty
Name:           trusty
State:          STOPPED

# fgrep rootfs /var/lib/lxc/trusty/config
lxc.rootfs = /tmp/trusty

# ls /tmp/trusty
ls: cannot access /tmp/trusty: No such file or directory
```

**Comment by marcosps** [comment]
I can't reproduce the problem in current master (ba2861).

Maybe due to: 067650d

I tested using DIR storage. Can you still reproduce with the latest stable version?

**Comment by stgraber** [comment]
Let's assume not.
