### ISSUE TITLE
Container not cleaned up after migration when using ZFS

### ISSUE THREAD

**Issue by SvenWiltink** [lxc/lxc#886]
Linux kernel: 4.4.4-040404
lxc version: 2.0.0.rc2
criu version: 2.0

When migrating a container from one host to the other the sending side is not properly cleaned up. It tries to, but it encounters the following error error: 
```
Failed to get ZFS config: bad property list: invalid property 'clones
```
When I manually delete the snapshot that was created for the migration and run lxc delete, it clean up just fine

**Comment by tych0** [comment]
Can you post the lxd log? Did this cause the migration to fail, or what happened?

**Comment by SvenWiltink** [comment]
I'll grab the lxd log when I get home. It did not cause the migration to fail. It just didn't clean up the old container. #887 happened on the same machines. I am reinstalling those when I get home, so we can rule out configuration/installation issues :)

**Comment by tych0** [comment]
Ok, can you post the full log from this first? I'd be curious to see what happened. Sounds like we're looking for snapshot properties on non-snapshots in some case somewhere.

**Comment by SvenWiltink** [comment]
Sure thing

**Comment by SvenWiltink** [comment]
Hmm. There is no migration log and the log of the container itself is clean. I'll see if I can reproduce it and try to catch the log.

**Comment by SvenWiltink** [comment]
Ok. I've done a clean install on both systems, but the issue is still present. This one seems to happen after a container has been migrated to another host. If a container is on host A and is migrated to host B, host B gets a snapshot (eg: lxc/containers/test@migration-send-a5ab8397-eb0d-4176-9a41-3976d90fa258). If the container is migrated back to host A you get the error I reported. After I manually delete the snapshot I can lxc delete the container.

**Comment by tych0** [comment]
Hm. We should be trying to clean those snapshots up here: https://github.com/lxc/lxd/blob/master/lxd/storage_zfs.go#L1398 but clearly something isn't quite right. I'll take a look, thanks.

**Comment by tych0** [comment]
Ah ha, I just hit a similar bug :). I bet I know what the issue is, and I'll post a patch shortly (although on github.com/lxc/lxd, since that's where the issue is).

**Comment by tych0** [comment]
https://github.com/lxc/lxd/pull/1745

**Comment by SvenWiltink** [comment]
Cool,  thanks.  I'll upgrade my lxd and check if it is fixed for me as well.

**Comment by SvenWiltink** [comment]
It seems like the issue has been resolved with the update. I am closing this issue :smiley:
