### ISSUE TITLE
Live migration failed: can't open ghost original file

### ISSUE THREAD

**Issue by SvenWiltink** [lxc/lxc#887]
I have a container running mysql-server (ubuntu image). When I try to migrate it, it can't create a checkpoint. The error it reports is the following: 
```
error: Error transferring container data: checkpoint failed:
(00.316083) Error (files-reg.c:628): Can't open ghost original file: No such file or
(00.316103) Error (cr-dump.c:1303): Dump files (pid: 2637) failed with -1
(00.321660) Error (cr-dump.c:1600): Dumping FAILED.
```

linux kernel: 4.4.4-040404
criu version: 2.0
lxc version: 2.0.0.rc2

**Comment by tych0** [comment]
Hmm, this Should Never Happen :). Can you post the full dump log from /var/lib/lxd/$container_name/?

The underlying issue here is that CRIU thought it needed to checkpoint a fd that it doesn't actually have, which is probably a bug in CRIU.

What version of the ubuntu container are you using? How exactly did you set up mysql-server?

**Comment by SvenWiltink** [comment]
The full dump log: http://paste.ubuntu.com/15338056/

image info:
  architecture: x86_64
  description: Ubuntu 14.04 LTS server (20160222)
  os: ubuntu
  release: trusty

I installed mysql-server by getting in the container via lxc exec <name> -- bash and using apt-get update && apt-get install mysql-server. The mysql server works as gogs.io (which was installed on the same machine, but later removed) was using it at the time. When I turn mysql-server off it migrates fine (apart from the other issue I had)

**Comment by tych0** [comment]
Hmm. I tried to install mysql myself, and definitely got what CRIU refers to as "ghost files":

```
lrwx------ 1 mysql mysql 64 Mar 10 15:05 4 -> /tmp/ib1PC3nm (deleted)
lrwx------ 1 mysql mysql 64 Mar 10 15:05 5 -> /tmp/ibsKLZmr (deleted)
lrwx------ 1 mysql mysql 64 Mar 10 15:05 6 -> /tmp/ib76IWlw (deleted)
lrwx------ 1 mysql mysql 64 Mar 10 15:05 7 -> /tmp/ibvBnCnG (deleted)
```

but for me the migration worked :(. Looking at this code path a bit more, I don't really understand how this could happen, so I'll have to think about it.

**Comment by tych0** [comment]
Is there anything unusual about the environment you're running LXD in? Does LXD have a reasonable /proc?

**Comment by SvenWiltink** [comment]
How do you mean reasonable /proc?

I have tried with the daily ubuntu image as well, but still no dice.

**Comment by tych0** [comment]
On Thu, Mar 10, 2016 at 08:00:50AM -0800, SvenWiltink wrote:
> How do you mean reasonable /proc?

I just mean that /proc is mounted for the pidns that LXD is running
in. But I think this would fail in other ways first if it wasn't, so
this probably isn't an issue.

> I have tried with the daily ubuntu image as well, but still no dice.

If I send you a patch with some extra debugging, do you mind running
that? Can you show how you set up mysql beyond `sudo apt-get install
mysql server`?

**Comment by SvenWiltink** [comment]
I wouldn't mind at all. 
If it helps I could grant you access to the machine. It is solely used for lxc testing anyways.

**Comment by tych0** [comment]
Sure, although it may be easier to just figure out exactly what mysql is configured to do so I can reproduce it locally.

**Comment by SvenWiltink** [comment]
Beyond installing mysql it is not configured to actually do anything.

After updating the lxd image in the hope that it would fix the issue, I had more issues. To rule out   configuration issues I will create a clean vm where I will reinstall lxc. I will post my findings after I tried again with the fresh installation :)

**Comment by SvenWiltink** [comment]
I have reinstalled both systems but the issue is still there. Since you don't seem to be able to reproduce the issue locally I can offer you access to both hosts. Let me know if you would like that so I can create an account for you to use :)

**Comment by tych0** [comment]
Sure, that would be great. I can't take a look today, but perhaps tomorrow or next week if time gets away from me.

**Comment by SvenWiltink** [comment]
I'll send the account details to your email (tycho@tycho.ws) tomorrow, I need to catch some sleep now ;)

**Comment by tych0** [comment]
On Thu, Mar 10, 2016 at 04:37:27PM -0800, SvenWiltink wrote:
> I'll send the account details to your email (tycho@tycho.ws) tomorrow, I need to catch some sleep now ;)

No problem, thanks :)

**Comment by SvenWiltink** [comment]
Ok, so it is dumping ok now I think (I don't know where it puts the file). It sends the zfs over to the new host, but then encounters a different error:

```
t=2016-03-11T13:24:54+0100 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-03-11T13:24:54+0100 lvl=info msg=handling method=GET url="/1.0/containers?recursion=1" ip=@
t=2016-03-11T13:25:09+0100 lvl=info msg=handling method=GET url=/1.0/profiles ip=10.1.0.3:39528
t=2016-03-11T13:25:09+0100 lvl=info msg=handling ip=10.1.0.3:39528 method=POST url=/1.0/containers
t=2016-03-11T13:25:09+0100 lvl=info msg=handling method=GET url=/1.0/operations/1051346c-fc06-4a42-9843-a8081054e677/wait ip=10.1.0.3:39528
t=2016-03-11T13:26:08+0100 lvl=eror msg="Error during migration sink" err="checkpoint failed:\ncheckpoint failed"
t=2016-03-11T13:27:37+0100 lvl=info msg=handling method=GET url=/1.0 ip=@
t=2016-03-11T13:27:37+0100 lvl=info msg=handling method=GET url="/1.0/containers?recursion=1" ip=@
t=2016-03-11T13:28:12+0100 lvl=info msg=handling url=/1.0/profiles ip=10.1.0.3:39530 method=GET
t=2016-03-11T13:28:12+0100 lvl=info msg=handling method=POST url=/1.0/containers ip=10.1.0.3:39530
t=2016-03-11T13:28:12+0100 lvl=info msg=handling ip=10.1.0.3:39530 method=GET url=/1.0/operations/76b9d53e-88ff-4e69-808c-1fff65200113/wait
t=2016-03-11T13:29:20+0100 lvl=eror msg="Error during migration sink" err="checkpoint failed:\ncheckpoint failed"
```

I couldn't find any other logs, but maybe I have missed a spot.

**Comment by SvenWiltink** [comment]
After updating to the latest version we are back to the ghostfile issue.

**Comment by SvenWiltink** [comment]
I have tried again after updating. The dumping failed.

log: http://paste.ubuntu.com/15551578/

**Comment by tych0** [comment]
Thanks for the update, I just replied to your email offline.

**Comment by SvenWiltink** [comment]
I will reinstall the servers with ubuntu 16.04 LTS and see if the issue is still present.

**Comment by SvenWiltink** [comment]
I have not yet encountered the problem on 16.04 so I am closing this :)
