### ISSUE TITLE
Cannot start container

### ISSUE THREAD

**Issue by bmarkowww** [lxc/lxc#904]
Container doesn't start on Ubuntu Server 14.04 (Linux server3 4.2.0-34-generic #39~14.04.1-Ubuntu SMP Fri Mar 11 11:38:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)

Here's startup log:
```
lxc-start 20160320183400.858 DEBUG    lxc_conf - conf.c:run_buffer:338 - script output: 123 116 0:43 /blkio /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/blkio ro,relatime - tmpfs cgroup_root rw,size=10240k,mode=755

lxc-start 20160320183400.861 DEBUG    lxc_conf - conf.c:run_buffer:338 - script output: 123 116 0:43 /blkio /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/blkio ro,relatime - tmpfs cgroup_root rw,size=10240k,mode=755

lxc-start 20160320183400.864 DEBUG    lxc_conf - conf.c:run_buffer:338 - script output: 123 116 0:43 /blkio /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/blkio ro,relatime - tmpfs cgroup_root rw,size=10240k,mode=755
```

**Comment by stgraber** [comment]
It would be useful if you told us what version of lxc you actually have installed.

The version of lxcfs may also be useful here.

**Comment by bmarkowww** [comment]
Latest from
https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/stable

lxc 	2.0.0~rc11-0ubuntu1~ubuntu14.04.1~ppa1
lxcfs 	2.0.0~rc6-0ubuntu2~ubuntu14.04.1~ppa1

**Comment by stgraber** [comment]
Ok, so I fixed that problem earlier today a new lxcfs (2.0.0~rc6-0ubuntu3~ubuntu14.04.1~ppa1) is on its way with the fix, new packages should be available within a couple of hours.
