### ISSUE TITLE
lxc-checkpoint failed when restore unprivileged containers

### ISSUE THREAD

**Issue by chenhaiq** [lxc/lxc#913]
I have sent this to mail group (lxc-users@lists.linuxcontainers.org) yesterday, but no reply. It should be a regression after 2.0 rc10.

I run everything in root, and has below lines in lxc config file to have unprivilleged container.
```
  lxc.id_map = u 0 100000 65536
  lxc.id_map = g 0 100000 65536
```

The cmd to restore container is:
` lxc-checkpoint -n wily8 -D /var/lib/lxc/wily8/dump -r TRACE -v`
Error in dump.log from ciru is:
```
(00.005616) Wait until namespaces are created
(00.006988) Running setup-namespaces scripts
(00.007010)      1: Calling restore_sid() for init
(00.007017)      1: Restoring 1 to 1 sid
(00.007091)      1: Mount procfs in crtools-proc.goosvl
(00.007154)      1: Restoring namespaces 1 flags 0x7c028000
(00.007196)      1: Error (image.c:318): Unable to open netns-9.img: Permission denied
(00.007374) Error (cr-restore.c:1306): 10779 exited, status=1
```

My env:
```
ubuntu 15.10 with 4.4.5-040405-generic
lxc 2.0.0~rc13
criu 2.0
```

config
```
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.include = /usr/share/lxc/config/ubuntu.userns.conf
lxc.arch = x86_64

# Container specific configuration
lxc.aa_allow_incomplete = 1
lxc.console = none
lxc.tty = 0
lxc.cgroup.devices.deny = c 5:1 rwm
lxc.seccomp =
lxc.mount.auto = cgroup:mixed
lxc.autodev = 1
lxc.kmsg = 0
lxc.include = /usr/share/lxc/config/common.conf.d/00-lxcfs.conf
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
lxc.rootfs = /var/lib/lxc/wily8/rootfs
lxc.utsname = wily8

# Network configuration
lxc.network.type = veth
lxc.network.link = lxcbr0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:72:7c:20

```

checkpoint used to work in my env when I using lxc 2.0.0~rc10 for unprivileged containers, but not after I update to rc13.

**Comment by tych0** [comment]
Hmm, I thought I replied to this already. You need to chown the CRIU images to the root uid for the container in the unprivileged case, so that CRIU can open them when restoring.

**Comment by chenhaiq** [comment]
@tych0 sorry for late reply, I was stuck by dumping errors recently, until upgraded to 4.4.0-21. Thanks for your comment in anther issue :)

However, I am still not able to restore an unprivileged container.

root uid in container is 100000. I actually chown all images, but still hit the same error.

-rw-r--r-- 1 100000 100000 128 Apr 22 22:57 /var/lib/lxc/w7/dump/netns-9.img

(00.004365) Running setup-namespaces scripts
(00.004381)      1: Calling restore_sid() for init
(00.004384)      1: Restoring 1 to 1 sid
(00.004411)      1: Mount procfs in crtools-proc.BIaCxL
(00.015499)      1: Restoring namespaces 1 flags 0x7c028000
(00.015527)      1: Error (image.c:318): Unable to open netns-9.img: Permission denied
(00.027483) Error (cr-restore.c:1387): 10353 killed by signal 9: Killed

**Comment by tych0** [comment]
On Fri, Apr 22, 2016 at 08:08:37AM -0700, Chen Hai Quan wrote:
> @tych0 sorry for late reply, I was stuck by dumping errors recently, until upgraded to 4.4.0-21. Thanks for your comment in anther issue :)
> 
> However, I am still not able to restore an unprivileged container.
> 
> root uid in container is 100000. I actually chown all images, but still hit the same error.

What about the directory as well?

**Comment by chenhaiq** [comment]
@tych0 cool. It works now!
