### ISSUE TITLE
python-lxc: Python bindings for LXC - Basic operation not working

### ISSUE THREAD

**Issue by C24IO** [lxc/lxc#918]
Maybe I am doing something wrong here, but a basic operation to create a container is not working in the  latest lxc. 

ipython3 
Python 3.5.1+ (default, Feb 24 2016, 10:41:47) 

In [1]: import lxc

In [2]: container = lxc.Container("pyapi_container")

In [3]: container.create("debian", {"release": "jessie", "architecture": "amd64"})
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-3-0a4b2b0c82bd> in <module>()
----> 1 container.create("debian", {"release": "jessie", "architecture": "amd64"})

/usr/lib/python3/dist-packages/lxc/__init__.py in create(self, template, flags, args, bdevtype)
    227             template_args['template'] = template
    228         template_args['flags'] = flags
--> 229         template_args['args'] = tuple(tmp_args)
    230         if bdevtype:
    231             template_args['bdevtype'] = bdevtype

UnboundLocalError: local variable 'tmp_args' referenced before assignment

In [4]:

**Comment by brauner** [comment]
Hi, should be fixed by https://github.com/lxc/lxc/commit/9cee41def4bbaddc089ea02f85b2ed028ac5a549.
Closing.
