### ISSUE TITLE
lxc-snapshot (lxc version 1.1.5) doesn't preserve hwaddr when restoring to same container

### ISSUE THREAD

**Issue by audiocricket** [lxc/lxc#921]
Hello there,

there seems to be an issue with lxc-snapshot (lxc version 1.1.5) when restoring from snapshot to the same container.

Everything in config file is the same as it was at the time snapshot was taken, however lxc.network.hwaddr is always changed.

I understand that hwaddr should change when restoring to new (another) container, but this is probably not needed for the same container the snapshot is being restored from.

As a workaround, I need to keep the hwaddr before restoring from snapshot and then manually reset it again to the original value.

Is this intended behavior or something's wrong here?

Thanks for any clarification.

**Comment by brauner** [comment]
The hwaddr is changed on purpose to avoid conflicts. Thanks!
