### ISSUE TITLE
Support for foreign architectures

### ISSUE THREAD

**Issue by ghost** [lxc/lxc#93]
[ fwd from debian bts ]

Luca Falavigna <dktrkranz@debian.org> wrote:
> It would be nice to have the possibility to create containers for
> foreign architectures, as already implemented in Ubuntu:
> https://help.ubuntu.com/12.04/serverguide/lxc.html

**Comment by brauner** [comment]
Containers for foreign architectures can easily be created and downloaded nowadays. If I missed the point of the the issue feel free to reopen.
