### ISSUE TITLE
lxc-destroy kaput for unprivileged btrfs-backed containers with kernel >= 4.2

### ISSUE THREAD

**Issue by overlayfs** [lxc/lxc#935]
To reproduce the bug on ubuntu 14.04, 15.10 or 16.04, create an unprivileged, btrfs-backed container and then attempt to destroy it:
``lxc-create -B btrfs -t downloads -n test_unprivileged_btrfs -- -d ubuntu -r wily -a amd64``
``lxc-destroy -n test_unprivileged_btrfs``
``sudo lxc-destroy -P /home/ubuntu/.local/share/lxc -n test_unprivileged_btrfs``
-  **sudo lxc-destroy**:  always succeeds.
- **lxc-destroy**: succeeds for kernels <= 4.1 if the container only has a single btrfs subvolume; otherwise it fails.
- **lxc-destroy**:  always fails for kernels >= 4.2 (tested up to 4.6rc1).

The error message for kernel >= 4.2 is:
_lxc-destroy: bdev/lxcbtrfs.c: btrfs_recursive_destroy: 619 Error: can't perform the search under /home/ubuntu/.local/share/lxc/test_unprivileged_btrfs/rootfs_

**Comment by overlayfs** [comment]
**Details**
The error is unaffected by:
- the version of lxc (regular repositories or ppa:ubuntu-lxc/daily)
- the kernel variant (regular repositories or mainline ppa).

**Comment by overlayfs** [comment]
**Straces**

**strace when lxc-destroy succeeds: (kernel <= 4.1)**
     open("/home/ubuntu/.local/share/lxc/test_unprivileged_btrfs/rootfs", O_RDONLY) = 4
     ioctl(4, BTRFS_IOC_INO_LOOKUP, 0x7ffe3ae4bd80) = -1 EPERM (Operation not permitted)
     close(4)                          = 0
     open("/home/ubuntu/.local/share/lxc/test_unprivileged_btrfs", O_RDONLY) = 4
     ioctl(4, BTRFS_IOC_SNAP_DESTROY, 0x7ffc6d5f7970) = 0

**strace when lxc-destroy fails: (kernel >= 4.2)**
     open("/home/ubuntu/.local/share/lxc/test_unprivileged_btrfs/rootfs", O_RDONLY) = 4
     ioctl(4, BTRFS_IOC_INO_LOOKUP, 0x7fff204b69d0) = 0
     ioctl(4, BTRFS_IOC_TREE_SEARCH, 0x7fff204b7a60) = -1 EPERM (Operation not permitted)

**strace for sudo lxc-destroy:**
     open("/home/ubuntu/.local/share/lxc/test_unprivileged_btrfs/rootfs", O_RDONLY) = 4
     ioctl(4, BTRFS_IOC_INO_LOOKUP, 0x7ffd812e64e0) = 0
     ioctl(4, BTRFS_IOC_TREE_SEARCH, 0x7ffd812e7570) = 0
     ioctl(4, BTRFS_IOC_TREE_SEARCH, 0x7ffd812e7570) = 0
     ioctl(4, BTRFS_IOC_INO_LOOKUP, 0x7ffd812e64c0) = 0
     ioctl(4, BTRFS_IOC_INO_LOOKUP, 0x7ffd812e64c0) = 0
     ioctl(4, BTRFS_IOC_TREE_SEARCH, 0x7ffd812e7570) = 0
     close(4)                          = 0
     open("/home/ubuntu/.local/share/lxc/test_unprivileged_btrfs", O_RDONLY) = 4
     ioctl(4, BTRFS_IOC_SNAP_DESTROY, 0x7ffd812e64d0) = 0

**strace for btrfs subvol list -o .  [similar to strace when lxc-destroy fails]**
     openat(AT_FDCWD, ".", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
     ioctl(3, BTRFS_IOC_INO_LOOKUP, 0x7ffea7ce84b8) = 0
     ioctl(3, BTRFS_IOC_TREE_SEARCH, 0x7ffea7ce83b8) = -1 EPERM (Operation not permitted)

**Comment by overlayfs** [comment]
For kernel <= 4.1, btrfs_ioctl_ino_lookup requires privileges and hence fails for an unprivileged user.  btrfs_recursive_destroy then abandons the search for nested subvolumes and calls btrfs_ioctl_snap_destroy to destroy the entire container.  This succeeds if the contains only has one subvolume; otherwise it fails.

For kernel >= 4.2, btrfs_ioctl_ino_lookup does not require privileges and hence succeeds.  The next call is to btrfs_ioctl_tree_search, which requires CAP_SYS_ADMIN in the init_user_ns, and hence fails for an unprivileged user.  btrfs_recursive_search then error-exits.

**Comment by overlayfs** [comment]
The patched version in the pull request replaces the error-exit with a call to btrfs_ioctl_snap_destroy, so that the outcome is the same as for kernel <= 4.1.

**Comment by overlayfs** [comment]
The patch only enables unprivileged users to destroy containers with one subvolume.  Unprivileged destruction of containers with nested subvolumes will require either:

- an unprivileged version of btrfs_ioctl_tree_search.
- an extension of btrfs_ioctl_snap_destroy to handle deletion of nested subvolumes.

An unprivileged version of btrfs_ioctl_tree_search seems feasible from a privileges POV, since the list of subvolumes can already be found (slowly) without privileges using, 
``find path_to_container -type d -inum 256``

**Comment by hallyn** [comment]
Seems like counterintuitively this would be caused by kernel commit 01b810b88: btrfs: make root id query unprivileged then.

**Comment by hallyn** [comment]
Ok yeah that makes perfect sense.  We first do a INO_LOOKUP.  This used to return eperm for unpriv users, then we'd skip to ignore_searc:.  But now that that is allowed for unpriv users, we continue on to the TREE_SEARCH and get eperm there.  We ignored that bc we never got to that point before.

So the patch you have in #936 looks fine for a fix, thanks.
