### ISSUE TITLE
Getting an error when trying to limit Memory in containers.

### ISSUE THREAD

**Issue by jonny3010** [lxc/lxc#946]
Getting the following error when adding memory limiting to containers. I do have the fuse module loaded.

` [root@WinterFell rootfs]# cat /var/log/lxc/u2.log
lxc-start 1453581686.335 ERROR    lxc_utils - utils.c:open_without_symlink:1317 - No such file or directory - Error examining fuse in /usr/lib64/lxc/rootfs/sys/fs/fuse/connections
lxc-start 1453636092.854 ERROR    lxc_utils - utils.c:setproctitle:1461 - Invalid argument - setting cmdline failed
lxc-start 1453636092.911 ERROR    lxc_utils - utils.c:open_without_symlink:1626 - No such file or directory - Error examining fuse in /usr/lib/lxc/rootfs/sys/fs/fuse/connections
lxc-start 1458177092.203 ERROR    lxc_utils - utils.c:setproctitle:1461 - Invalid argument - setting cmdline failed
lxc-start 1458177092.260 ERROR    lxc_utils - utils.c:open_without_symlink:1626 - No such file or directory - Error examining fuse in /usr/lib/lxc/rootfs/sys/fs/fuse/connections`

This is what I'm adding to my config.
`lxc.cgroup.memory.limit_in_bytes = 256MB`

I have added the following to grub boot options
`cgroup_enable=memory swapaccount=1`

**Comment by stgraber** [comment]
Please post a complete log, neither of those errors are fatal.

**Comment by stgraber** [comment]
according to kernel documentation, MB isn't a valid suffix, try 256M instead.

**Comment by jonny3010** [comment]
Thanks for your help. Seems to be working now.
