### ISSUE TITLE
Containers created through restore leave zombie processes behind

### ISSUE THREAD

**Issue by n-eiling** [lxc/lxc#957]
As far as I understand containers started through `start` are de-parented from the calling process such that the init process is the parent of the lxc monitor process. This is not done when a container is restored through `migrate(c, MIGRATE_RESTORE,...)`. Because of this, when the container is subsequently stopped (either through `stop` or through `migrate(c, MIGRATE_DUMP,...)`) the lxc monitor process is not reaped and thus remains as a zombie process behind until the parent process exits.

To reproduce this do something like:

```
c->checkpoint(c, path, true, true);
c->restore(c, path, true));
c->stop(c));
while(1);
```

[complete-reproduce-program.txt](https://github.com/lxc/lxc/files/211211/complete-reproduce-program.txt)

**Comment by brauner** [comment]
Is this still reproducible with current git master? If so, please re-open and sorry for the delayed response. We're currently cleaning up a bunch of issues.
