### ISSUE TITLE
Is there a way to manage lvm volumns in lxc-container

### ISSUE THREAD

**Issue by whatot** [lxc/lxc#960]
My host is ubuntu 16.04 beta, lxc-container is centos-6.
What I need is that I want create and use lv in containers,

I use ``lxc-device`` or ``lxc.cgroup.devices.allow`` to add block devices into containers,
then set needed capabilities to /sbin/lvm, then I can pvcreate/vgcreate new pv/vg in containers.
But lvcreate will failed with below:
```
# /sbin/lvcreate -v -n data_lv --size 20G data_vg
File descriptor 6 (anon_inode:[signalfd]) leaked on lvcreate invocation. Parent PID 885: /bin/bash
    Setting logging type to disk
    Finding volume group "data_vg"
    Archiving volume group "data_vg" metadata (seqno 17).
    Creating logical volume data_lv
    Creating volume group backup "/etc/lvm/backup/data_vg" (seqno 18).
    activation/volume_list configuration setting not defined: Checking only host tags for data_vg/data_lv
  setpriority -18 failed: Permission denied
    Creating data_vg-data_lv
    Loading data_vg-data_lv table (252:2)
    Resuming data_vg-data_lv (252:2)
    Clearing start of logical volume "data_lv"
  /dev/data_vg/data_lv: not found: device not cleared
  Aborting. Failed to wipe start of new LV.
  setpriority -18 failed: Permission denied
    Removing data_vg-data_lv (252:2)
    Creating volume group backup "/etc/lvm/backup/data_vg" (seqno 19).
```
it means new lv can't be created in /dev.

Anyone can solve this problem? 

> [used capabilities cmds](http://unix.stackexchange.com/questions/189054/how-to-obtain-info-about-physical-volume-as-non-root-user)

**Comment by whatot** [comment]
The mismatch of lvm-version in ubuntu16.04 and centos6 maybe cause the problem.

So I reach my target in another way, by mounting the data-lv inside the rootfs of  lxc-container.
The command 'lsblk' in container will see the different view of host's 'lsblk'. The directory will be processed as a mountpoint in container. So I reached my goal.

Hope my problem will help others encouter similar problems.
So this issue can be closed.

**Comment by pevogam** [comment]
I am encountering a similar issue and unfortunately need to create the logical volume within the container programmatically. I am also having this issue on container and host OS of the same distro and version. So it would be great if anyone figured out any reasons for this.
