### ISSUE TITLE
aufs mount syntax with "br:" not supported

### ISSUE THREAD

**Issue by tstarling** [lxc/lxc#967]
In the [aufs manpage](https://sourceforge.net/p/aufs/aufs-util/ci/aufs4.x-rcN/tree/aufs.in.5) of the current version of aufs-utils, only the br: syntax for branch options is documented, the br= syntax is not mentioned. But lxc only supports the br= syntax, and it fails without any explanation if you try to use the other syntax.

Most mount errors are accompanied at least by an explanatory WARN level log message, but none of the "goto err" cases in aufs_mkdir() or ovl_mkdir() result in a log message, either directly or in the caller mount_entry_create_dir_file(). So all you get is a vague message like

lxc-start: conf.c: lxc_setup: 3920 failed to setup the mount entries for 'container-name'

If the mount is optional, you don't even get that much.

**Comment by hallyn** [comment]
Please tell us which kernel / aufs module source you are using.  Lxc has always used br=.  It sounds like br= and br: should be equivalent (see discussion in https://github.com/lxc/lxc/pull/969), so switching may be ok, but i don't want to break long-time users if we can help it.

**Comment by brauner** [comment]
Hi, so I think we'd like to avoid further logging in smaller helper functions for now. We report `SYSERROR()` back on mount failure and a `WARN()` when we fail to create a aufs/overlay helper dir.

If the syntax for `br:` and `br=` is equivalent it probably be best to stick with `br=` for simplicity and backwards compatibility; otherwise we'd have to special case `br:` in there again.
Closing this for now.

**Comment by tstarling** [comment]
Sorry, I didn't realise I would have to spell this out. Yes, the kernel module supports both. lxc should similarly support both. #969 would break lxc for all existing users and I certainly would not recommend it. It is not difficult to support both. I'll submit a pull request if you like.

**Comment by hallyn** [comment]
Oh, I see.  Not at all how I interpreted your original email.

As you say that should be easy enough.  A PR would be great.

**Comment by brauner** [comment]
The aufs driver will be deprecated. For a union filesystem one should use the overlay fs driver which is available in the upstream kernel.
