### ISSUE TITLE
lxc-info switches ignored under some circumstances

### ISSUE THREAD

**Issue by LaKing** [lxc/lxc#977]
I have a script that calls lxc-info with the -s / --state switch. If called by root from console, it operates normally, but if it is called by the script that runs as sudo user, the switches are ignored. The name is passed, as the query is done on the correct container, but other switches are ignored. For example -p reports: "-p doesn't exist" ... --state or -s is simply ignored, and the full output returned.

I guess that is a minor bug.

**Comment by hallyn** [comment]
I can't reproduce this.

Please show how you reproduce this as in

cat > /tmp/bad << EOF
#!/bin/sh
lxc-info -n w1 -s
EOF

sudo /tmp/bad

**Comment by LaKing** [comment]
I think I found the problem.

LD_LIBRARY_PATH

In previous versions of lxc, /usr/local/lib had to be added, and now with lxc 2.0 it seems to be unnecessary.
