### ISSUE TITLE
Debian Jessie containers broken with LXC 2.0.0 / Ubuntu 14.04.4 host

### ISSUE THREAD

**Issue by schammy** [lxc/lxc#979]
I've been mucking around with LXC 2 since the betas started coming out a few months back. Before final release, the latest one I used was rc12, on a Ubuntu 14.04.4 host, with the PPA version of LXC. Everything was working fine with that set up.

I recently got some new hardware and installed a fresh version of Ubuntu 14.04.4 on there, added the PPAs, and installed LXC 2.0.0.

Other than installing a few basic packages on the host level, disabling lxc-net (since I use static IPs), and creating /etc/lxc/lxc.conf to set a custom lxc.lxcpath, I haven't touched _any_ settings.

Creating a Debian Jessie container still works fine, but when the container starts, it's all messed up. I know that LXCFS is required for running systemd in a container, and I verified that LXCFS was installed with LXC by default and is running.

When I start the container in the foreground, I get this:

```
root@104:/etc/apparmor.d/lxc# lxc-start -F -n db99
umount: /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/blkio/lxc/db99: not mounted
umount: /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/cpuset/lxc/db99: not mounted
umount: /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/cpu/lxc/db99: not mounted
umount: /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/cpuacct/lxc/db99: not mounted
umount: /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/devices/lxc/db99: not mounted
umount: /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/freezer/lxc/db99: not mounted
umount: /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/hugetlb/lxc/db99: not mounted
umount: /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/memory/lxc/db99: not mounted
umount: /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/net_cls/lxc/db99: not mounted
umount: /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/net_prio/lxc/db99: not mounted
umount: /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/perf_event/lxc/db99: not mounted
umount: /usr/lib/x86_64-linux-gnu/lxc/sys/fs/cgroup/systemd/lxc/db99: not mounted
systemd 215 running in system mode. (+PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ -SECCOMP -APPARMOR)
Detected virtualization 'lxc'.
Detected architecture 'x86-64'.

Welcome to Debian GNU/Linux 8 (jessie)!

Set hostname to <db99>.
Failed to install release agent, ignoring: No such file or directory
Failed to create root cgroup hierarchy: Invalid argument
Failed to allocate manager object: Invalid argument
```

I can attach to the container fine but only 3 total processes are running, and I can't install anything with apt-get. It's just completely broken.

```
Unpacking rsync (3.1.1-3) ...
Processing triggers for systemd (215-17+deb8u4) ...
Failed to get D-Bus connection: No such file or directory
dpkg: error processing package systemd (--unpack):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 systemd
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

As a test, I created Trusty and Xenial containers, as well as Debian Wheezy (which doesn't use systemd). All of these worked completely fine.

Debian is my OS of choice, hence why I need that to run at the container level. I'm using Ubuntu as my host since I want to keep up with the latest/greatest LXC, plus I'm excited for the built-in ZFS support coming with Xenial.

**Comment by schammy** [comment]
I forgot to say, these containers are all privileged.

Also, just to make sure my image cache wasn't bunk, I nuked it so it redownloaded it. Still the same issue with systemd.

Went back to my old 14.04.4 host and nuked the cache there as well and created a Jessie container... no problems!

**Comment by schammy** [comment]
I was too quick to judge on my old rc12 host... now that I'm looking into it more, new Jessie containers I create are messed up. Not as bad as on my new host though, e.g. some stuff will install. 

So, I'd assume that your image rootfs is messed up, or something... I dunno.

What's weird though is I also have my own image-based system. Thankfully LXC does everything in plain text so creating a container can be done entirely outside of any `lxc-create` syntax, so I have a Debian image that I have saved after some basic stuff is installed in a tarball. That still works fine on my old host when I create a new container with it. But on the new one, major issues. So that makes me think it's not related to your image... so I'm completely lost.

**Comment by aguytech** [comment]
I have exactly the same problem when I tried to start a container with jessie on lxd 2.0 from a fresh install...
I'm waiting some helps too ;o)

**Comment by schammy** [comment]
Upgrading systemd to the Stretch (Debian 9) version does fix the issue, as per http://www.panticz.de/node/882

However, this isn't a satisfactory fix for me. Why does Debian 8 work out of the box with LXC 2.0 rc12 but requires hackery with 2.0 final?

**Comment by aguytech** [comment]
Thanks for this post, pending a better solution it works ;o)

**Comment by schammy** [comment]
I just tested the same on the new Ubuntu 16.04, and Jessie works fine on there.

So must just be something screwy with my config on the 14.04.4 server then? That's still kinda critical though since most people won't be moving to Xenial until the first point release, 3-6 months from now.

I swear I didn't do anything weird on my 14.04.4 server, just a few tweaks that I specifically mentioned above. I did the exact same tweaks on my new Xenial set up. Sigh.

**Comment by dsbaars** [comment]
With the steps aguytech described i got Debian jessie working on Ubuntu 16.04 (upgrade from 14.04). On 14.04.4 first it can't install systemd because of the same d-bus error described above. 
When bind-mounting /var/run/dbus the installation completes but dhclient still fails:
```
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 6
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 11
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 13
5 bad udp checksums in 5 packets
```
Manual configuration of IPv4 does work.

Ubuntu 14.04: Linux xxx 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 16.04: Linux xxx 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

On 14.04 I installed LXD with trusty-backports

**Comment by aguytech** [comment]
Hi dsbaars,

May be I don't understand your comment, but If I tried this method of installing systemd from stretch version of debian it's because the initial container were broken : No ip address, no usage of services (ssh, networking..), no dbus...
Initially, I've tried to set manually ipv4 address without success, and after investigation I saw the problem come from services not working and not only the dhcp client.

For me I use for host :
4.2.0-35-generic #40~14.04.1-Ubuntu SMP Fri Mar 18 16:37:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
and for jessie image:

If you can give information of the jessie image you use for your successfull installation of jessie in trusty ?
`lxc image info jessie`
thanks

for me:
```
lxc image info jessie
Fingerprint: 09cbd1efc9c2c5a4fc0e833419a01b9c242b93e40a1b057470ad5711a535c3aa
Size: 104.06MB
Architecture: x86_64
Public: no
Timestamps:
    Created: 2016/04/19 23:31 UTC
    Uploaded: 2016/04/20 09:20 UTC
    Expires: never
Properties:
    architecture: amd64
    build: 20160419_22:42
    description: Debian jessie (amd64) (20160419_22:42)
    distribution: debian
    release: jessie
Aliases:
    - debian8
    - jessie
Auto update: enabled
```

**Comment by dsbaars** [comment]
Hi, I used debian/jessie/amd64. I experienced the same with old lxc (< 2.0) and a fresh install on libvirt/qemu (similar to https://raymii.org/s/articles/virt-install_introduction_and_copy_paste_distro_install_commands.html#Debian_8)
I think it has something to do with the systemd in the jessie repositories and apparmor profiles.

```
Fingerprint: 01d98403bd8738c31d0c7a7890ad58039b0a2580d31a9baa4a4eb85ceff67e2b
Size: 104.07MB
Architecture: x86_64
Public: no
Timestamps:
    Created: 2016/04/24 23:19 UTC
    Uploaded: 2016/04/25 03:43 UTC
    Expires: never
Properties:
    architecture: amd64
    build: 20160424_22:42
    description: Debian jessie (amd64) (20160424_22:42)
    distribution: debian
    release: jessie
Aliases:
Auto update: enabled
Source:
    Server: https://images.linuxcontainers.org
    Protocol: lxd
    Alias: debian/jessie/amd64
```

**Comment by aguytech** [comment]
I just update my image of debian jessie to feat with yours:
```
root@fx8320e:~$lxc image info jessie-new
Fingerprint: 01d98403bd8738c31d0c7a7890ad58039b0a2580d31a9baa4a4eb85ceff67e2b
Size: 104.07MB
Architecture: x86_64
Public: no
Timestamps:
    Created: 2016/04/24 23:19 UTC
    Uploaded: 2016/04/25 12:20 UTC
    Expires: never
Properties:
    architecture: amd64
    build: 20160424_22:42
    description: Debian jessie (amd64) (20160424_22:42)
    distribution: debian
    release: jessie
Aliases:
    - jessie-new
Auto update: enabled
```
start an new fresh container
```
root@fx8320e:~$lxc init jessie-new j1
Creating j1
root@fx8320e:~$lxc start j1
```
```
exec bash on container
root@fx8320e:~$lxc exec j1 bash
root@j1:~# service ssh restart
Failed to get D-Bus connection: No such file or directory
root@j1:~# systemctl list-units -t service
Failed to get D-Bus connection: No such file or directory
root@j1:~# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  27080  3036 ?        Ss   12:24   0:24 /sbin/init
root        94  0.0  0.0  20244  3224 ?        Ss   12:34   0:00 bash
root       107  0.0  0.0  17500  2052 ?        R+   12:38   0:00 ps aux
root@j1:~# exit
```
May be is the difference of kernel ?
4.2.0-35-generic vs 3.19.0-58-generic

**Comment by hallyn** [comment]
On a stock 15.10 system with ppa:ubuntu-lxc/lxd-git-master I get the same thing.  The lxcfs fixes from yakkety do not help.

**Comment by hallyn** [comment]
Hm, no, seems I was impatient before.

**Comment by hallyn** [comment]
It blocks between:

Set hostname to <j1>.

and

Failed to configure loopback device: Operation not supported

**Comment by hallyn** [comment]
Ok, so yes, lxcfs with the two acess() patches from upstream (as found in yakkety) fixes it.

**Comment by schammy** [comment]
Upstream as in the kernel?

**Comment by aguytech** [comment]
Can you give me the installed packages around 3.19.0-58-generic ? linux-image-extra ? linux-tools ? ...

**Comment by sts** [comment]
@schammy I think @hallyn talks about the two patches related to https://github.com/lxc/lxcfs/issues/107

* https://github.com/lxc/lxcfs/commit/575316c4706e5600f3935e8245027f7de6222656
* https://github.com/lxc/lxcfs/commit/3f441bc7bec47694a5159df4ddfc1d1093aa8dec

**Comment by Napsty** [comment]
Just installed LXC 2.0 from jessie-backports on a Debian Jessie running on purpose NOT with systemd. And lxc-ls is throwing errors now, containers cannot even be started anymore:

	# lxc-ls -f
	lxc-ls: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found
	lxc-ls: state.c: lxc_str2state: 66 invalid state ''
	lxc-ls: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found
	lxc-ls: state.c: lxc_str2state: 66 invalid state ''
	lxc-ls: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found
	lxc-ls: state.c: lxc_str2state: 66 invalid state ''
	lxc-ls: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found
	lxc-ls: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found
	lxc-ls: state.c: lxc_str2state: 66 invalid state ''
	lxc-ls: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found

Start:

	# lxc-start -n a1 -F
	lxc-start: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found
	lxc-start: start.c: lxc_spawn: 1079 failed initializing cgroup support
	lxc-start: start.c: __lxc_start: 1329 failed to spawn 'a1'
	lxc-start: lxc_start.c: main: 344 The container failed to start.
	lxc-start: lxc_start.c: main: 348 Additional information can be obtained by setting the --logfile and --logpriority options.


cgroup is mounted:

    # mount|grep cgroup
    cgroup on /sys/fs/cgroup type cgroup (rw,relatime,cpuset,cpu,cpuacct,memory,devices,freezer,net_cls,blkio,perf_event,net_prio)

**Comment by brauner** [comment]
@Napsty, this looks like all of your controllers are mounted into a single cgroup hierarchy whereas they should be mounted into separate hierarchies. That would explain why `all_controllers()` cannot find your freezer cgroup.

**Comment by hallyn** [comment]
On Thu, Jun 30, 2016 at 05:31:56AM -0700, Claudio Kuenzler wrote:
> Just installed LXC 2.0 from jessie-backports on a Debian Jessie running on purpose NOT with systemd. And lxc-ls is throwing errors now, containers cannot even be started anymore:
> 
> 	# lxc-ls -f
> 	lxc-ls: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found
> 	lxc-ls: state.c: lxc_str2state: 66 invalid state ''

Hm, this is ugly, and a bit scary.  We should definately get to the
bottom of the invalid state error.

> 	lxc-ls: cgfsng.c: all_controllers_found: 430 no freezer controller mountpoint found

This says "no freezer controller mountpoint found" but really means no
*writeable* such mountpoint found.

Can you show /proc/self/cgroup contents?

**Comment by hallyn** [comment]
Quoting Claudio Kuenzler (notifications@github.com):
> I meanwhile rolled back and ditched lxc 2.0 which, as I mentioned, was installed from jessie-backports:
> 
>     Upgrade: lxc:amd64 (1.1.5-1~bpo8+1, 2.0.0-3~bpo8+1)
> 
> As jessie-backports doesn't contain 1.5 version anymore I went back to 1.0.6 from the jessie repository. All containers work again.

Do you have cgmanager installed?

> /proc/self/cgroup shows the following, but it's possible that this has changed again since I now installed LXC 1.0.6:
> 
>     # cat /proc/self/cgroup
>     1:cpuset,cpu,cpuacct,memory,devices,freezer,net_cls,blkio,perf_event,net_prio:/

Right you are in the root cgroup so as unprivileged user cannot write in
it.

**Comment by Napsty** [comment]
No, cgmanager is not installed (libcgmanager is though). Want me to install it for further analysis? 
The containers were launched as privileged containers. 

Please let me know how I can help. I could upgrade to LXC 2.0 again. Luckily this machine is not yet in production, but will be soon.

**Comment by hallyn** [comment]
@Napsty,

Your issue appears to be very different from the original reported one.
Would you mind opening a new one, and showing exactly how the host and
containers are configured?  I'd like to try to (or ask someone to :)
reproduce.

**Comment by Napsty** [comment]
@hallyn Sure. Sorry I hijacked this issue ;-).

**Comment by brauner** [comment]
The cgroup handling code has been reworked substantially and I suspect that this is not an issue anymore. If you can still reproduce with current git master, please re-open.
