### ISSUE TITLE
undefined symbol: is_valid_bdev_type

### ISSUE THREAD

**Issue by LaKing** [lxc/lxc#983]
Dear devs, after an update i get this error when creating ubuntu containers on a fedora host.
It might be related to experiments running docker in containers - that produced strange errors. 
like no space left on device with over 40G free space, ...

lxc-create -n ubuntu -t ubuntu
lxc-create: symbol lookup error: lxc-create: undefined symbol: is_valid_bdev_type

please advise, what might help in clearing the issue.

Thank you, ...

**Comment by stgraber** [comment]
No space left on device with 40G of free space is most likely unrelated, look at "df -i", you probably ran out of inode.

The error above suggests that your liblxc is out of sync with the lxc-* tools.

liblxc's public API is stable, but the LXC commands do use private symbols and so must be kept in sync with the library.

**Comment by LaKing** [comment]
I see, and indeed lxc 1.1.5 was still installed as a package. 

Thank you.
