### ISSUE TITLE
(2.0.0 regression) container name not found by lxc-ls and lxc-attach (>= kernel 4.5) (lxc-info and lxc-console seem to work)

### ISSUE THREAD

**Issue by Auch999** [lxc/lxc#984]
If a(ny) (unprivileged) container is started like this (without having been 'created' beforehand): 

$ lxc-start -n containerName -F/-d -f /path/to/conf -s 'lxc.id_map = u 0 100000 65536' -s 'lxc.id_map = g 0 100000 65536' -s 'lxc.rootfs = /path/to/rootfs' -s 'lxc.init_cmd = /path/to/initcmd' ,

the container name ('containerName' here) is not recognized by the lxc tools. 'lxc-ls' shows nothing at all and 'lxc-attach -n containerName' prints 'Error: container containerName is not defined'

Note: The container starts fine and is well usable in foreground mode. 
(Linux 4.5 and up (same behavior with 4.6.0-rc4) (CHECKPOINT_RESTORE enabled))

Is there a workaround to start the container in background mode and attach to it later on?

How do the lxc tools determine which containers are currently running btw.?

EDIT: lxc-info seems to work: (container name m3all1)

[The cgroups have been created like this by root:
 cgm create all username
 cgm chown all username uid gid

 The user moved the pid of the the shell into the cgroups before launching lxc-start:
 cgm movepid all username $$ && lxc-start -n m3all1 -F -f /path/to/conf -s 'lxc.id_map = u 0 100000 65536' -s 'lxc.id_map = g 0 100000 65536' -s 'lxc.rootfs = /path/to/rootfs' -s 'lxc.init_cmd = /path/to/initcmd' ]

$ cgm movepid all username $$
$ lxc-ls
$ lxc-attach -n m3all1
Error: container m3all1 is not defined
$ lxc-info -n m3all1
Name:           m3all1
State:          RUNNING
PID:            4664
IP:             10.0.3.13
CPU use:        0.01 seconds
BlkIO use:      0 bytes
Memory use:     1.17 MiB
KMem use:       804.00 KiB

How can I attach to it?

After having downgraded to lxc 1.1.5, I can confirm that the above works and it is definitely a bug in lxc 2.0.0 .

**Comment by panic-amt** [comment]
I'm also seeing this after upgrading to Linux 4.5.0.

**Comment by tobiaspal** [comment]
This bug is still present in the latest LXC 2.0.4.

**Comment by jordemort** [comment]
`lxc-ls` is working for us in 2.0.9. We tried a hack to get `lxc-attach` to work but it just hangs. Here's the patch we tried: https://gist.github.com/jordemort/44603d34bb602bb15fa19e4fcd1b2089

**Comment by brauner** [comment]
I'm looking into this now.

**Comment by brauner** [comment]
Ok, so I think the issue is simply that the tools should not check whether a container is actually defined.

**Comment by brauner** [comment]
`lxc-console` works exactly for this reason: it doesn't check whether the container is defined.

**Comment by brauner** [comment]
`lxc-attach` should not rely on a valid conf to be present.
