### ISSUE TITLE
Fail to get console in debian8-container created on Ubuntu 14.04 Host

### ISSUE THREAD

**Issue by dann1** [lxc/lxc#986]
Hello I moved to lxc 1.1.5 since the standard lxc version on Ubuntu official repository couldn't start debian jessie containers because of something related on systemd, I read this was solved on lxc 1.1.5 and I installed it from the trusty-backports, then I tested the ubuntu containers and so far so good, but after creating a jessie container when I try to enter the console using "lxc-console -n container-name -t 0" it gets stuck on the following message no matter what I type:

Connected to tty 0
Type <Ctrl+a q> to exit the console, <Ctrl+a Ctrl+a> to enter Ctrl+a itself

The same happens with ttys 1-4 and without "-t #" as well, I can never enter the console, "lxc-attach" is not an alternative. I tried that on jessie as Host OS and it works fine.

**Comment by Kentoseth** [comment]
Can you explain why

> "lxc-attach" is not an alternative.

cannot be used instead?
